### ISSUE TITLE
Suggestion: Permission/per world for Friendly Fire

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#1242]
Originally reported on Google Code with ID 1213

```
I would like to have friendly fire on a per world/permission basis. I tried to set up
separate worlds for PVP arena and Hunger games, I have to manually enable friendly
fire affecting all worlds or else people in same town cannot attack each other.
```

Reported by `jackal.c` on 2012-07-27 08:10:48

**Comment by LlmDl** [comment]
Not much interest in this one.

**Comment by yimyum** [comment]
I think there should be an option to enable and disable friendly fire in worlds due to some people having worlds dedicated to free for all pvp
