### ISSUE TITLE
Suggestion: Town vs Town

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#1392]
Originally reported on Google Code with ID 1366

```
Our server wishes there could be town vs town warfare for obvious reasons. No more to
be said. Thank you for your work!

```

Reported by `l1skou` on 2012-10-10 15:53:27

**Comment by Golvore** [comment]
This suggestion is wonderful, Towny should always be just cities, nations have often been a hindrance.

**Comment by Wolf2323** [comment]
In my opinion this is a cool feature but it is important to have an option that new towns cannot get attacked instantly on creation. In my opinion there has to be a a time limit and a resident limit. Or someone else has a cool idea on when a town can be attacked.

Right now it is really simple, if a town is big enough to join a nation the town is also big enough to get attacked. The only negative is that a town in never forced to join a nation at the moment.
