### ISSUE TITLE
Suggestion: Ability for non town members to use outposts.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#2038]
Originally reported on Google Code with ID 2015

```
Since the new addition of towny admin commands to telephone to outposts, there should
be a way to do so with anyone.

Let the town decide if they want to: /t toggle outpost, this command can toggle if
outposts are public or not.

Or make it more tailored, ie, /t set perm allies outpost on, Etc etc.

Command to telephone to outposts of another town: /T Spawn TownName Outpost 2

Either way, this expands on outposts for more than just town members.
```

Reported by `BlissMCServer` on 2014-04-09 20:51:40

**Comment by TawnyFrogmouth** [comment]
It would be useful for mayors to be able to set access per outpost, e.g., to make some town outposts publicly accessible but keep others accessible only by residents.

**Comment by LlmDl** [comment]
This one I never liked much, if Towny ever does get this functionality it will probably be through a warp system.
