### ISSUE TITLE
Suggestion: Maximum towns/residents per Nation option.

### ISSUE THREAD

**Issue by Brocoee** [TownyAdvanced/Towny#2402]
Hello, I am here to make a very very useful suggestion. I have been doing a lot of research and there seems to be no way to add a resident cap to towns and a town cap to nations. This would come in handy because on my server (and possibly other servers) we have a cap on the amount of residents and towns a town/nation can have. This cap is a simple rule - players can still add more than 10 (the cap) if they want to. It'd be one of the greatest add-ons in a future update to have caps on the amount of residents a town can hold and the amount of towns a nation can hold. Thank-you for taking your time to read my suggestion, please consider adding it!

**Comment by Keeland** [comment]
A config option for this would be really nice or to make the townjoinnation event cancellable would even be better.

**Comment by Keeland** [comment]
Even better if there were an option for the amount of allies nations can have in order to stop domination effectively on pvp based servers.

**Comment by LlmDl** [comment]
I bet its possible to do some mathing and figure out if the number of allies is greater than 50% of the total nations.

**Comment by LlmDl** [comment]
As of 0.91.4.11 the residents-per-town-cap is something that exists, I'm changing the title to reflect that.

**Comment by PainOchoco** [comment]
Are you still interested in that suggestion?

**Comment by PainOchoco** [comment]
Well there's already a `max_towns_per_nation`, do you think that a `max_residents_per_nations` is really needed?

**Comment by LlmDl** [comment]
I think with the ability for a town to be 1 -> n residents, the max_residents_per_town can't really accurately predict how many residents the max_towns_per_nation will allow. 

Might be a bit redundant but teh max_residents_per_nation might be exactly what someone is wanting.

**Comment by PainOchoco** [comment]
Alright, I'll work on that tomorrow
