### ISSUE TITLE
Please add an option to allow nation members to spawn to each others' towns only when they are also public.

### ISSUE THREAD

**Issue by LoadedServerowner** [TownyAdvanced/Towny#2461]
I want players in nations to to teleport to other towns in the nation only if the town is public cause at the moment people can tp  to the towns no matter what the status of the town is atm theres just a msg saying "Town spawn travel to other towns in your nation of forbidden"

**Comment by ThemInspectors** [comment]
do they have the permission towny.town.spawn.ally ?

**Comment by ThemInspectors** [comment]
because there are more permissions:
towny.town.spawn.nation
towny.town.spawn.town
towny.town.spawn.public
towny.town.spawn.ally

Ally is to travel to an Ally town
Nation is for the Nation.
Town is for the Town
and Public is for any public towns

**Comment by LoadedServerowner** [comment]
Um this is the msg i get when i want to remove it http://prntscr.com/am3uny

**Comment by LlmDl** [comment]
@ThemInspectors what loadedserverowner is asking for isn't currently possible.

**Comment by ThemInspectors** [comment]
ah like a "/t toggle allyspawn" would be cool

**Comment by LlmDl** [comment]
Better late than never, this is now a thing as of 0.92.0.12:
```
    - New Config Option: global_town_settings.is_nation_ally_spawning_requiring_public_status
      - default: false
      - When set to true both nation and ally spawn travel will also require the target town to have their status set to public.
```
