### ISSUE TITLE
Unbelievable intrusive message sent on givebonus

### ISSUE THREAD

**Issue by doitliketyler** [TownyAdvanced/Towny#2479]
https://imgur.com/x2jku7b

Way to spread your personal opinions on a server where this doesn't even apply. Have you even considered the servers who use Towny and are 100% EULA compliant? You think its ok to flood a players chat with this kind of crap? Honestly...shame on you. I cant even give my players a few blocks out of kindness or for voting without this being sent to them. Its just bad user experience and it makes my players have to read something that doesn't even apply to them and actually makes them confused. Some have even asked me to disable it.

Residence looks so good right now...

**Comment by LlmDl** [comment]
k

**Comment by itsmariatee** [comment]
Ok. I guess I'll post in this thread.

I think this needs to happen to. I don't sell town blocks to players. I don't even have a store for my server. Its ugly and long and no one needs to read this.

P.S.
I don't think "k" was a proper response either. Also, spreading opinions directly to you in a thread made for suggestions is much different than you spreading your opinion to countless players on countless public servers using Towny that this scenario doesn't even apply to. Either way...this message definitely should be removed. Thanks.

**Comment by LlmDl** [comment]
Your post's tone is much nicer. Thanks for contributing.

**Comment by itsmariatee** [comment]
Maybe so but I still feel the same way the original poster does and would have been equally offended with the one syllable response from you. Also when you "close" a topic that typically means its not longer up for discussion and you have prevented other people from seeing it thus preventing them from sharing their input. In my experience it stays open until there has been a conclusion.

**Comment by doitliketyler** [comment]
Aye aye.

**Comment by LlmDl** [comment]
This is how I see it from my perspective:

I've been with the Towny project for more than 4 years, helping with it before ElgarL joined. Towny has never brought in many donations. I believe ElgarL got a few, I have received one. Both of us donated our time and money to code/support/host the towny project with no expectation of reimbursement.

I've run my own server for more than 5 years and have never taken a donation for it. 

When I'm doing support for Towny on our IRC and end up learning that the person in question is selling Townblocks (usually for a lot of money,) its not fun. It's my opinion that Townblocks shouldn't be sold, period. The alternative to removing this message is removing the ability to use the command via console. This ticket will remain open while cooler heads are discussing it. If it turns back into the type of discussion I saw in the OP then it'll probably be closed again.

**Comment by doitliketyler** [comment]
I agree that townblocks shouldn't be sold either. If you really want to prevent people from selling them then the only option is removing the command from the console. I personally am all for this. Lets put them out of business and get rid of that message.

(I apologize if I came off harsh at first but that plugin message was harsh to me first.)

**Comment by LlmDl** [comment]
Removing the option to send via the console would also remove the ability to give townblocks for voting.

**Comment by doitliketyler** [comment]
Hmm...thats true and that would suck for anyone giving plots for voting unfortunately and I'm sure there are other servers that do this. The only option is to remove it. I mean yeah you want to prevent townblocks being sold but if anyone is doing that and needs to get around it they have probably have already done so and gone about their business.

(The apology was for opening the post harshly...everything else I meant.)

**Comment by Portanna** [comment]
That command is very useful when making custom rewards in-game, I use it for achievements that towns have to reach and they get rewarded with extra-plots, so please don't get rid of it. But the long message that is being shown in chat could definitely be shortened out, like 2 rows of text.

**Comment by maxlehot1234** [comment]
If a server want to break eula, it was his choice, not yours :(

Why you force to having this text?

Please enable us to give townyblocks using events, quests completed, jobs completed, achivements completed, etc. It was really useful for events :(

**Comment by Portanna** [comment]
Edit Towny.jar with Jbyteedit or Jbytemod, find the string and edit the text, save et voilà..

**Comment by maxlehot1234** [comment]
@Portanna What is the software you used to edit .jar file, I doesn't remember the name and they removed your comment on github for no reason... Thank you ;)

**Comment by hoorigan** [comment]
I don't see a problem with the message existing, so much as I see a problem with the wording.  This was recently brought to my attention by other staff on a server I help run, so forgive me for not remembering the exact text.

There's something in there about "go play on another server" that was the first thing they caught as the message flashed by.  If that was what staff took away from the message, it's safe to say some percentage of players will take that as the main takeaway, as well.  Maybe change the string to something like:

> Sale of bonus plots for real-world currency violates `(Minecraft|Towny)` EULA and should be reported to `$entity`!

Or:

> If you paid real-world currency for bonus plots, demand a refund!

Would that be a bit more agreeable?
