### ISSUE TITLE
Suggestion: A minimum distance from spawn where towns/outposts can't be created/expanded

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#2601]
This would help with overcrowding issues around spawn. On my server many outposts are created right outside spawn in order to "trap" new players. Having a minimum distance from spawn where towns/outposts can't be created/expanded would be useful in such cases.

**Comment by Portanna** [comment]
+1

**Comment by Managering** [comment]
This would easily be prevented using world guard no? flag blocked-cmds: t new,town new,t claim outpost etc.

**Comment by LlmDl** [comment]
This is something you can accomplish yourself by making an NPC spawn town, or even by placing outposts of a town strategically around the spawn yourself (and using the config setting to limit how close another town can claim near to another plot/outpost.)

The real answer is to claim it yourself though. What is claimed cannot be claimed by another.
