### ISSUE TITLE
Suggestion: Backup MySQL data to flatfile

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#2628]
Mcmmo does this and it's very convenient

**Comment by Portanna** [comment]
+1

**Comment by Portanna** [comment]
This is really needed

**Comment by LlmDl** [comment]
Done as of the above commit, will be a part of 0.95.0.4.

**Comment by FixTheAdmin** [comment]
Amazing work as always, keep it up!
