### ISSUE TITLE
Make Titles and Subtitles Configurable

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TownyAdvanced/Towny#2647]
### What steps will reproduce the problem?
1. Go into town
2. Title message showing what town you entered
3. Leave town
4. No Entering Wilderness

### What is the expected output?
1. Go into town
2. show Now Entering as title and town name as subtitle
3. Go out of town
4. show Entering Wilderness Title
5. Make both configurable

### What is your Towny version?
0.91.4.9

### What is your spigot/craftbukkit version?
git-Spigot-99c2a37-3819f8d (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/ee0rMd9u
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/XLdhSC18
3. Your townyperms.yml : https://pastebin.com/qAWyNmFE
4. Your log's error : No Errors

**Comment by LlmDl** [comment]
A thing as of 0.92.0.12:
```
- New Config Section: notifications.titles
      - Requires the notification.using_titles setting to be true.
      - This makes the title messages seen when entering towns configurable.
      - This also adds the ability to show a similar message announcing the wilderness as well.
      - {townname} is supported in the town message, {wilderness} is supported in the wilderness message. Colour codes can be used too, ex: &f, &c.
```

**Comment by xH3LLRAIZ3Rx** [comment]
Thanks :D
