### ISSUE TITLE
Suggestion: Hover town/nation tag chat

### ISSUE THREAD

**Issue by darkboomba** [TownyAdvanced/Towny#2651]
Hello,

On my server I use town and nation tags as prefixes instead of the full names. Could you add that when you hover such a tag that it shows the whole town or nation name? That would be great.

Thanks for reading!

- DarkBoomba

**Comment by LlmDl** [comment]
This is something that isn't currently possible using the Bukkit API. When there is such a way to do things, that doesn't break between MC version we'll take another look at this.

**Comment by Articdive** [comment]
Update: This may be possible with the Spigot-API, when using messages we send to 1 player and only 1 player, so e.g Invites, the town status, the nation status e.t.c, If this will be implemented is questionable, however if the Bungeecord Chat API gets added into Bukkit, it most likely will be.

**Comment by ElMoha943** [comment]
+1 Would love this feature!

**Comment by LlmDl** [comment]
Possible with https://github.com/LaBoulangerie/TownyChatRemake
