### ISSUE TITLE
Suggestion: Towny Spy format change

### ISSUE THREAD

**Issue by WalkingPixel** [TownyAdvanced/Towny#2665]
Hey, So I am an Admin on a server and Me and my other staff find it extremely difficult to split the town/nation chats up from everyone else's town chats.

My suggestion is that if you could possibly add something like the following.

Have a bracket with [TS] making those letters Towny Spy and then adding the normal one which would be [TC] and [NC]

[TS] [TC] **Playername** Players coversation blah blah blah
[TS] [NC]**Nation Player** Conversation here

I would suggest colours but there is so many colours as it is on servers that it would just make it more difficult. maybe the Towny Spy could be a different color from others with those suggestions above.

Thank you for considering and reading this post.

Pixel.

**Comment by Metisuneatn** [comment]
Damnit pixel you beat me to it -.- 

Also an admin on this server, it would be nice to have them with the option to config the color just like the normal towny chat configs
