### ISSUE TITLE
Suggestion: Nation/Town Bank/Command Logs

### ISSUE THREAD

**Issue by Johnsonk2** [TownyAdvanced/Towny#2670]
Suggestion: Be able to view command logs for both Nation and Towns.

Sometimes with larger nations, you don't know who withdrew or deposited money or who added/kicked the town.

Using a command such as /n log town or /n log bank
Would be a neat way of keeping tabs on this, showing who did what and at which time.

**Comment by Johnsonk2** [comment]
looking at this up again, any word on if this is being added or considered at all?

**Comment by LlmDl** [comment]
It's something that is doable, there's already money logs kept by Towny, but they only contain the days' information, other days are in zip files.

**Comment by Johnsonk2** [comment]
Yeah, that's good. I'm thinking more of something a nation leader or chancellor can access in-game.

**Comment by LlmDl** [comment]
@Articdive just redid the logging system, maybe he wants to add this too.

**Comment by Johnsonk2** [comment]
😢

**Comment by LlmDl** [comment]
I'm sorry I don't know why the bot closed the ticket.

**Comment by Johnsonk2** [comment]
not a problem, its been a few years anyways aha
