### ISSUE TITLE
Suggestion: More plot types

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TownyAdvanced/Towny#2693]
I think you should add these type of plots:

Mine
Marketplace
Town Hall
Courthouse
Pub

**Comment by LlmDl** [comment]
So what do each of those plots types do? What do they bring to Towny? 

How does a marketplace plot differ from a shop plot?

**Comment by xH3LLRAIZ3Rx** [comment]
The mine can maybe do something with ores and maybe give a haste effect (with cooldown so you cant spam)
Marketplace can maybe be like shop plot but instead of it being 16x16 it can be something smaller like 8x8 to make a marketplace type of area
Town Hall not really sure but has to do with mayor
Courthouse would be to decide jailed peoples fate
Pub would be sorta like a inn, but it would be neat if it gave off a relaxed state, maybe giving a effect of some kind (with cooldown to prevent spam)

**Comment by LlmDl** [comment]
- The mine plot could potentially be like the farm/wilds plots, only allowing a configurable list of blocks to be built/destroyed.

- We cannot do smaller plots inside of plots (your town_block_size is used, always.)

- The rest really feel more like role-playing than actual plot types.

**Comment by LlmDl** [comment]
Closing this ticket, as none of these panned out.
