### ISSUE TITLE
Suggestion: More defined purge options.

### ISSUE THREAD

**Issue by SeruhioX** [TownyAdvanced/Towny#2780]
I would like to suggest that you could choose when you run "/ta purge x" if users have a city or plots are not deleted.

https://github.com/LlmDl/Towny/blob/master/src/com/palmergames/bukkit/towny/tasks/ResidentPurge.java#L41

I'm not very familiar with the code of this plugin but I guess it would be a modification on these lines (maybe I'm wrong) and some new option in the configuration.

If it could be done, I would be quite grateful.

**Comment by Articdive** [comment]
Would require a small recode of how I handled confirmations, shouldn't be too problematic though

**Comment by LlmDl** [comment]
Calling this one done: https://github.com/TownyAdvanced/Towny/commit/4158d99e17a9fe199cca03357239b9e0940d5cd2 as of 0.94.0.15. It only handles townless players, as we do not store plots-owned on the Resident object we could only tell if a nomad owned plots by looping through all the townblocks (while we are looping through all the residents.) This would make a long, slow process even longer.
