### ISSUE TITLE
Suggestion: "/town list open" command.

### ISSUE THREAD

**Issue by Roy416** [TownyAdvanced/Towny#2800]
Was thinking maybe a command for all the open towns? So new players can see all the towns there are to join instead of repeatedly asking chat, or not finding a mayor online at that moment. Maybe something like '/t open'. That will show all the open towns with the amount of people in that town. Also maybe an option to randomize the list? So all the towns get a fair chance. and maybee letting the mayors create a description for it to attract players, that would be beside the amount of players in that town. 

So something like "TownName - (#ofpeople) - description/message

**Comment by LlmDl** [comment]
Likely be added as /town list open, with the blurb/description being sourced from the town's board message.

**Comment by LlmDl** [comment]
This is now a thing using /t list by open. It lists towns by resident count.

https://github.com/TownyAdvanced/Towny/commit/f783799de889aa662109c79d47cd4aa0050e8a1d
