### ISSUE TITLE
Suggestion: /t spawn here

### ISSUE THREAD

**Issue by KingBohica** [TownyAdvanced/Towny#2805]
Hello,

Our server is set-up with no warping / spawn use. We also have the ability to edit blocks in the wilderness. It would be nice to be able to allow a spawn permission separate from the other 4 (.town, .nation, .ally, .public). The idea is to use the same functionality as the 'here' command for town screens. We don't want to allow using spawns from anywhere in the world, but there are many scenarios where players can become trapped. Since this only occurs in towns, the ability to warp to the town in which you are currently standing, as a means of getting unstuck, would be very useful. Thank you for your consideration.

**Comment by LlmDl** [comment]
Just had a thought about this: Most towns have their spawns in a secure location (or they ought to in case of a war or pvp raid.) Would this command not require each town to set their spawn in a place that is public. Otherwise the player is just getting 'stuck' somewhere else. What would stop a player from walking into a town with a secured spawn and using the '/t spawn here' command to TP into the secure area?

**Comment by KingBohica** [comment]
Yeah, fair enough. I suppose it depends on the server you are running, which is why I figured it would be an optional thing. It's funny you mention wars because that's one of the reasons I have spawns disabled in the first place. Otherwise when attacked, a town could just instantly warp all of its defenders back home. In my case, so long as everyone knows the rules from the start, I would just have mayors be required to allow access out of their home chunk. I have the option to only allow attacks on the borders of a town anyway, so I don't think this would do much damage since the home chunk shouldn't be immediately vulnerable unless they have it in a weird place.

**Comment by LlmDl** [comment]
There's new updates to spawning that allow you to disable the different types of spawning separately, only during peace time, or only during war time. Might be in the last one or two dev builds. 

I'll still consider adding this though, it would just be disabled by default.

**Comment by KingBohica** [comment]
That's true, but the war thing was just one of the reasons. We're resetting our server soon after 3 years of running our current setup and plan on making some changes from the rules we have now. I just want to do away with warps in general as they tended to be overused for our purposes. We're hoping to switch over from Grief Prevention to Towny, but Towny doesn't really have a trapped command like Grief Prevention does. I just figured having a 'spawn here' function would be a nice way to have something similar to a 'trapped' command, without having to add as much code as would be needed for a whole new trapped function.

**Comment by KingBohica** [comment]
As an alternative, since some folks might have their town spawn secure, would it be easier to have a town boot command of some kind? So it would look for a nearby chunk that is not part of that town and send you there, so you you are getting ejected from the town when stuck, instead of going to the center of it.

**Comment by LlmDl** [comment]
Note: /res trapped
Figure out if the player is currently unable to use /t spawn at the location to allow the command. Also requires permission node towny.command.resident.trapped.
