### ISSUE TITLE
Suggestion: Merge TownyNameUpdater with Towny

### ISSUE THREAD

**Issue by Leonardo-DGS** [TownyAdvanced/Towny#2819]
Since the TownyNameUpdater is a very simple plugin, it would be better if it was integrated into Towny, and maybe putting an option to disable it. This would reduce the jar files number, so management would be easier.

**Comment by LlmDl** [comment]
The only reason to have it disabled would be for offline mode servers.

**Comment by Leomixer17** [comment]
@LlmDl This is precisely why I made this proposal

**Comment by LlmDl** [comment]
Offline servers can just not use the jar for now.

**Comment by Articdive** [comment]
Maybe it would be a good idea to port Towny over to UUIDs now

**Comment by jackstrosahl** [comment]
Any idea what kind of undertaking that would be?  I'm looking into doing that but I'm not sure where to start.

**Comment by LlmDl** [comment]
@Articdive's comment is not serious. Towny will likely never move over to using UUIDs for storing players. It would make repairing a corrupted database overly difficult, and for the foreseeable future while Towny MYSQL databases are generally unstable, we will not be making the change.

**Comment by jackstrosahl** [comment]
@LlmDl Jsyk I went ahead and made a fork that uses UUIDs.  I would love input, it seems to be working.  I also made a data migrator.  https://github.com/jackstrosahl/Towny-UUID

**Comment by LlmDl** [comment]
@jackstrosahl I see you've posted your fork on Spigot, this is in violation of the Towny license. Please remove it.

**Comment by Leomixer17** [comment]
Maybe if @jackstrosahl did a pull request it would be a good idea, to update Towny to a more consistent way to handle player data

**Comment by LlmDl** [comment]
I'd be up for an optional UUID mode, which is something I'm sure can be done fairly easily. I don't think the average server owner is ready to solve Towny safe mode issues while also reading UUIDs instead of names.

**Comment by jackstrosahl** [comment]
@LlmDl Sorry about that I should've read more carefully I'll pull it when I get home.

**Comment by LlmDl** [comment]
@jackstrosahl thanks.

**Comment by Articdive** [comment]
There may be a new approach to this thanks to an extension of the Mojang API in 1.10.2 not many people seemed to notice, will be discussed in private, is however a nice approach and could possibly deprecate usernames in Towny
