### ISSUE TITLE
Suggestion: Nation Board

### ISSUE THREAD

**Issue by hoorigan** [TownyAdvanced/Towny#2857]
There's been some chatter on my server recently about wishing nations had boards, in addition to towns.  We often use the town boards for slogans or taglines that give some idea of what the town is about, and this is something I've seen as a common use for the town board on other servers I've played as well.  Being able to use nation boards similarly would be fun, and I think it would help build more character and culture for nations.

**Comment by LlmDl** [comment]
Will require a config option to not show up on startup (as I believe there is for the town boards).

```
	GNATION_SETTINGS_DISPLAY_NATIONBOARD_ONLOGIN(
			"global_nation_settings.display_board_onlogin",
			"true",
			"# If Towny should show players the nationboard when they login"
	),
```

**Comment by LlmDl** [comment]
Now a thing as of 0.92.0.11
```
    - New Feature: nation board messages
      - just like town's board messages but for nations.
    - New command: /nation set board {message}
      - Permission node: towny.command.nation.set.board
        - child node of towny.command.nation.set.*
        - no change required to existing townyperms.yml files.
      - Set the nation's board message.
    - New Config Option: global_nation_settings.display_board_onlogin
      - default: true
      - If Towny should show players the nationboard when they login.
```
