### ISSUE TITLE
Suggestion: Additonal leve of permissions for town ranks

### ISSUE THREAD

**Issue by Phyther** [TownyAdvanced/Towny#2859]
I would love to see an additional town/nation rank permission set. Often I setup builders for towns and it would be great to allow them to switch in certain plots that no one else can access things like building material storage without having to add a chest locking plugin.

**Comment by LlmDl** [comment]
How is this not covered by the towny.claimed.townowned.switch.* permission node?

Create a town rank in the townyperms.yml and add that node to it. Tell your mayors they can give the rank to their builders.

**Comment by LlmDl** [comment]
Closed due to lack of feedback.
