### ISSUE TITLE
Towny.log filling with errors.

### ISSUE THREAD

**Issue by DragonsMc** [TownyAdvanced/Towny#2865]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Towny Save
2. Disk
3. SSD

### What is the expected output?
1. DISK

### What is your Towny version?
Do not say "latest".
0.92.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot-1.10.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://drive.google.com/open?id=1Cu7s9rqXQsSHuF23yQ4_BJVXziYOAJkT
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/StZqRdh8
3. Your townyperms.yml : https://pastebin.com/StZqRdh8
4. Your log's error : https://imgur.com/a/jdT0T and https://pastebin.com/uKcgFvXH

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Why do you have towny set to load flatfile and save mysql. You cannot do both unless you're in teh process of converting.

**Comment by LlmDl** [comment]
Going to assume you've fixed your loading and saving to be one or the other and are not having any issue.
