### ISSUE TITLE
Suggestion: Ability to set jail time by mayors/ranks.

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2869]
Hello,
We are not sure if it is possible, but we are using Essentials for players to set home points and would like to suggest you adding a possibility to forbid this command on town territory. For that they would have /town spawn command.

Also, we would like to suggest adding a maximum time spam of jailing players in configs by mayors or those who have this permission. Players by themselves would have a possibility to jail players on time they want to. Example: /town toggle jail <number of jail> <nick> 1h.

We are looking forward to your answer

**Comment by LlmDl** [comment]
I can't do much about another plugin's /set home command. You can just not use it and rely on Towny's bed spawning feature. It only allows residents to use a bed in plots they personally own. Then they can use /res spawn to get to their bed, which you can alias to /home.

The jailing time is a good idea.

**Comment by LlmDl** [comment]
The config should have  a maximum allowed amount of time a player can be jailed.

**Comment by LlmDl** [comment]
Duplicate ticket https://github.com/TownyAdvanced/Towny/issues/3232
