### ISSUE TITLE
[Help needed] Region type Spleef | Registration time of nations and its towns

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2870]
In new versions there was added a plot type Spleef, but no information was provided about it. Could you please explain us, what this plot is about?

Also, towns which are in nations don't have its registration time, while those who are not in nation have it. What it can be connected with? Is it actually a bug or it is okay with that?

We are looking forward to your answer

Spigot version: 1.11.2
Towny version: 0.92.0.10
config.yml: https://pastebin.com/K9z6xBeg

**Comment by LlmDl** [comment]
Spleef was added as a plot type back when ElgarL was lead developer. Nothing was done with it and it has no purpose.

The code for whether the Founded date is shown on the /town screen has nothing to do with whether the town has a nation. If the town is older than when we started tracking town founding dates then the Founded date is not shown.

```
		// Created Date
		Long registered= town.getRegistered();
		if (registered != 0) {
			out.add(String.format(TownySettings.getLangString("status_founded"), registeredFormat.format(town.getRegistered())));
		}
```
