### ISSUE TITLE
[Issue] Jails problem after town deletion

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2873]
Hello,
We have found a problem. If a town has some jailed players and then a mayor deletes the town, jailed player still stay jailed and cannot neither leave town nor pay bail. Only, when the town with the same name is created, then they can leave/paybail.
What it can be connected with?

We are looking forward to your answer

Towny version: 0.92.0.10
Spigot version: 1.11.2

**Comment by LlmDl** [comment]
Doesn't look like deleted towns were handling jailed players at all, test this build for me please:
https://www.dropbox.com/s/lie5lp71mai4wp0/Towny%20-%20Alpha.jar?dl=0

**Comment by AIphaDragon** [comment]
Unfortunately, it didn't help.

Also, it is not connected with this build, but we have found an error in our console.
https://pastebin.com/XMiXbKcR

**Comment by LlmDl** [comment]
Sorry, that was entirely my fault, try this build: https://www.dropbox.com/s/h9l5ro8w32pb89l/Towny%20-%20Alpha2.jar?dl=0

For the other thing, file a new ticket. One bug per ticket please.

**Comment by AIphaDragon** [comment]
We testet your build. It caused some errors in console and didn't fix an issue.
Here are the errors: https://pastebin.com/QYnUh5M9
Here is a video to demonstrate the issue: https://www.youtube.com/watch?v=jvJF8gge_48

**Comment by LlmDl** [comment]
The NPE is because your world has no spawnpoint set.

I just tested this on my own server and it unjailed my test subject with on issue. When the jailed resident isn't a member of a town they are sent to the world spawn instead of their town's spawn when they are unjailed. Set a world spawnpoint please.
