### ISSUE TITLE
[Bug] /plot perm hud causing NPE's from plot name.

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2875]
Hello,
Recently, we have found out some errors in console connected with PlotChangeEvent. 
What it can be connected with?

We are looking forward to your answer

Here are the errors' pastebin: https://pastebin.com/FA77rkk8
Server startup: https://pastebin.com/dkbdby4X
config.yml: https://pastebin.com/TExU3teS
townyperms.yml: https://pastebin.com/JcarbQJJ
Spigot version: 1.11.2
Towny version: 0.92.0.10

**Comment by LlmDl** [comment]
It is failing on the plot name. When you're doing this, is the plot named? If it is, what is the name?

**Comment by AIphaDragon** [comment]
These errors are from our server during online 25-35 players. Some of them do name their plots, so it's impossible to check what the name is.
We thought the problem was in naming plots in other laguages, but only English is allowed, so that was not a problem

**Comment by LlmDl** [comment]
Well keep an eye on it for more errors, if you see them try to track down the source. Come back when you can figure out where it is that is causing this.

**Comment by AIphaDragon** [comment]
The error is related to moving the player between worlds with /plot perm hud
Video: https://youtu.be/VUxZnIvJu7A

**Comment by LlmDl** [comment]
Good, I'll get this tested/fixed when I'm back home from holiday.

**Comment by LlmDl** [comment]
As far as I can see I've fixed this as of 0.92.0.11
