### ISSUE TITLE
[Issue] Nation with no territory can attack others and has no daily upkeep

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2879]
Hello,
Recently, we have found out a serious issue, when a nation consisting of 1 town has no claimed town blocks and attacks other nations. Such nations can seize territories, but no one can attack their's.

What they do, is just unclaim their chunks (have 0 town blocks claimed, but still remain towns/nations) and live without paying daily upkeep.

So can it be fixed in any way? Could the town or nation be deleted in case when the starting homeblock or all of town blocks are unclaimed?

We are looking forward to your answer.

Towny version: 0.92.0.10

**Comment by LlmDl** [comment]
I need you to not skip the form. Please resubmit with the form filled out.
