### ISSUE TITLE
[Suggestion] PvP remains on chunks that were captured during nation war

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2880]
Hello,
We have noticed such a thing, that during nations' war players tend to leave the server to prevent the attackers to seize more land. It appears, that in town will be less people required to attack it. So the captured land and nation in whole is invincible.

So, is it possible to make configurable time span, when the captured land still can be recaptured by attacked nation despite the fact that there are not enough people in town?
For instance, nation A captured land from nation B and there 5 players needed to attack the town. After attack, all players from nation A left the server, so nation B cannot attack them.
It will be good, if there is configured time [1 hour], when nation B can take back their land.

We are looking forward to your answer

**Comment by LlmDl** [comment]
This is flag war or event war? It sounds like flag war which isn't supported any longer.

I also do not understand, your title does not seem to match up with your ticket.

**Comment by AIphaDragon** [comment]
It was about flag war

**Comment by LlmDl** [comment]
Again, as with the other ticket, this is related to the unsupported Flag War. You are welcome to find someone to submit a pull request fixing issues with Flag War, but I do not have time to support Flag War.
