### ISSUE TITLE
[Issue] Nation with no territory can attack others and has no daily upkeep

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2881]
Hello,
Recently, we have found out a serious issue, when a nation consisting of 1 town has no claimed town blocks and attacks other nations. Such nations can seize territories, but no one can attack their's.

What they do, is just unclaim their chunks (have 0 town blocks claimed, but still remain towns/nations) and live without paying daily upkeep.

So can it be fixed in any way? Could the town or nation be deleted in case when the starting homeblock or all of town blocks are unclaimed?

We are looking forward to your answer.

Towny version: 0.92.0.10
server startup: https://pastebin.com/GMuBbtet
config: https://pastebin.com/B2jd7rgZ
townyperms: https://pastebin.com/WbYbEdL2

**Comment by LlmDl** [comment]
Are you saying the nation isn't paying the $300 nation upkeep? I can understand them not paying the town's per-plot upkeep if they have to plots.

Towns without plots should be eliminated from the war as soon as it begins, because they have no land to lose.

**Comment by AIphaDragon** [comment]
Well, it's about flag war. Nation without land can still place flags and capture the land while the others cannot attack and seize them. They pay only $300 nation upkeep, but no per-plot upkeep

**Comment by LlmDl** [comment]
With no land I can't make them pay a per-plot-upkeep. I will try to fix both wars from letting towns without plot engage in war.

**Comment by LlmDl** [comment]
Fairly sure I've fixed this for EventWar as of 0.92.0.11, not for flag war yet.

**Comment by LlmDl** [comment]
And now flag war also prevent towns with 0 townblocks from causing attacks.
