### ISSUE TITLE
Missing confirmation for /ta town rename

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#2882]
Basically you have no idea if /ta town rename actually worked as the person executing the command gets no confirmation.

**Comment by LlmDl** [comment]
I thought we had just done this recently. You're using 0.92.0.10 correct?

**Comment by KarlOfDuty** [comment]
Ah, I thought I had forgotten to send the issue last time, but yes I am on the version you guys sent to me right before the latest dev build came out and I got no message.

**Comment by KarlOfDuty** [comment]
The mayor seems to get one but not the admin executing it.

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.11.
