### ISSUE TITLE
Suggestion: Admin Commands to reset all plots in a town to default flags

### ISSUE THREAD

**Issue by Sheepotastic** [TownyAdvanced/Towny#2883]
Hello,
It'd be quite nice if administrators were able to personally set the flags for plots or other towns, and especially if this could be done in bulk. I recently made a mistake by not checking thoroughly through the default town flags, people made towns since then and fellow town's members are able to go through each other's chests because the friend flag is registered to everything (or ally). It'd be nice if we could quickly set all of the town's flags to the default, or editted default, file in my case. As well as plots.
But I can't even edit other people's plots, so I'm forced to just tell players to use a long command (/plot set perm friend off) every time they don't want to be stolen from. (This is especially dangerous since every town is disallowed from being non-public on my server)

**Comment by LlmDl** [comment]
Towns can use /t set perm off, then /t set perm reset, which will reset town-owned plots in the town that have the newly set permissions line seen in /town. Only plots which had the old default permission line will be reset. 

As for individual plots, admins can already override a plot's permissions using /plot set perm, they do not have the ability to set the permission line seen in /town.

**Comment by LlmDl** [comment]
Note: new /ta protect {town}
  - cycles through all townblocks and sets all BDSI to --- and all fire/mobs/explosions to off.

**Comment by LlmDl** [comment]
This was done a little while back when I made /ta town TOWNNAME set piggyback off of the town's set command, allowing console/admins to do anything to a Town that they can do via /t set.
