### ISSUE TITLE
The Bank account of the city is equal to zero

### ISSUE THREAD

**Issue by Chypik** [TownyAdvanced/Towny#2884]
such a problem: When the server crash the Bank account of the city to become zero. Is the economy plugin iConomy. Players ' accounts remain unchanged.
Towny 0.92.0.0
iConomy 5.05
I have not found a command to make a cash Deposit to the accounts of towns as administrator
what to do in this situation?

**Comment by LlmDl** [comment]
skipped form, invalid ticket, please resubmit
