### ISSUE TITLE
Are you hiding something from us?

### ISSUE THREAD

**Issue by MAXvxv** [TownyAdvanced/Towny#2888]
I found this in your files

http://towny.palmergames.com/file-repo/Towny%20Advanced/Releases/0.92.0.0%20%28For%20MC%201.7.10%29/

Why is this not on the main page?

**Comment by ThisIzEthan** [comment]
Snooper

**Comment by MAXvxv** [comment]
This version works well, what's wrong with it?

Cursed is she?

Or is it not finished?

**Comment by LlmDl** [comment]
I don't remember building that, when I'm back from holiday I'll check if it was actually made using Bukkit 1.7.*

**Comment by LlmDl** [comment]
Apparently this was built for bukkit 1.7.10 and I'd just forgotten about it. If it's working good that's great. I might get around to adding this to the palmergames.com site when I have some more spare time.
