### ISSUE TITLE
[Issue] Nations cannot place flag to enemy's plots, if there is an enabled permission to build for outsiders

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2894]
Hello,
So the problem is that enemy's nation cannot place the flag on the plot, when the permission to build for outsiders is ON. They simply place blocks, but not activate the flag to capture the plot.
How this problem can be solved? We are looking forward to your answer

spigot version: 1.11.2
Towny version: 0.92.0.10
config.yml: https://pastebin.com/0ypxg7qM
townyperms.yml: https://pastebin.com/wJARL88d

**Comment by LlmDl** [comment]
You keep posting issue tickets for the Flag War which is not supported any longer. If you want to have someone fix it and send in a pull request I will gladly accept it. I do not have time to support Flag War myself.
