### ISSUE TITLE
Letters "r" and "f" switched between each other in /plot perm hud scoreboard

### ISSUE THREAD

**Issue by LazosPlaying** [TownyAdvanced/Towny#2899]
### What steps will reproduce the problem?
user command `/plot perm hud`

### What is the expected output?
```Build; r--```

### What is your Towny version?
0.92.0.9

### What is your spigot/craftbukkit version?
2918 (from config)

1. Your full server startup from the logs\latest.log : https://pastebin.com/fYBEmAvw
2. Your Towny config.yml: https://pastebin.com/FMUF2pa6

**Comment by LlmDl** [comment]
Personally-owned plots have FAO (Friends, Ally, Outsider) while town-owned plots have RAO (Resident, Ally, Outsider.) Are you mistaken about this? I don't understand what your ticket is trying to say.

**Comment by LazosPlaying** [comment]
Oh that might be the thing. Thanks for the info :)
