### ISSUE TITLE
Outposts can not be limited ?

### ISSUE THREAD

**Issue by LazosPlaying** [TownyAdvanced/Towny#2900]
Is there a way to limit the amount of outposts per town? I was not able to find any :/

### What is your Towny version?
0.92.0.9
### What is your spigot/craftbukkit version?
2918 (from config)

1. Your full server startup from the logs\latest.log : https://pastebin.com/fYBEmAvw
2. Your Towny config.yml: https://pastebin.com/FMUF2pa6

**Comment by LlmDl** [comment]
Outposts can be limited using the townLevels and nationLevels. You need to be using Towny 0.92.0.10
