### ISSUE TITLE
Outpost can be "hidden" ?

### ISSUE THREAD

**Issue by LazosPlaying** [TownyAdvanced/Towny#2901]
### Expected:
I was expecting that when you remove an outpost, it will also unclaim all claims (chunks) "attached" to that outpost, but that's not the case :/

### What actually happened
The claimed chunks were still there without being changed. And if someone does that, they can simply lose the claim location of their outpost

### What is your Towny version?
0.92.0.9

### What is your spigot/craftbukkit version?
2918 (from config)

1. Your full server startup from the logs\latest.log : https://pastebin.com/fYBEmAvw
2. Your Towny config.yml: https://pastebin.com/FMUF2pa6

**Comment by LlmDl** [comment]
We won't be making it so unclaiming an outpost will unclaim all of the attached townblocks.
