### ISSUE TITLE
Outsiders can kill animals in town with bows if outside the town ?

### ISSUE THREAD

**Issue by LazosPlaying** [TownyAdvanced/Towny#2904]
### What steps will reproduce the problem?
1. create a town
2. get some animals
3. outsiders can not kill them while in the town
4. outsiders can kill them while outside the town (shooting with a bow for example)

### What is the expected output?
1. create a town
2. get some animals
3. outsiders can not kill them while in the town
4. outsiders can not kill them while outside the town (bow)

### What is your Towny version?
0.92.0.9

### What is your spigot/craftbukkit version?
2918 (from Towny config)

1. Your full server startup from the logs\latest.log : https://pastebin.com/fYBEmAvw
2. Your Towny config.yml: https://pastebin.com/FMUF2pa6

**Comment by LazosPlaying** [comment]
Alright, so ? 
Any info ?

**Comment by LlmDl** [comment]
I'm busy at a week long work thing, I haven't been able to test this which I will do. I recall fixing this, so I'll have to reproduce it first.

**Comment by LazosPlaying** [comment]
Alright, thanks for the reply 😄

**Comment by LlmDl** [comment]
Checked this just now and it's not happening for me on my test server. Please pastebin.com your luckperms permissions file, luckperms config.yml and your townyperms.yml file.

**Comment by LlmDl** [comment]
Closed due to lack of feedback
