### ISSUE TITLE
Renaming town duplicates it in MySQL db

### ISSUE THREAD

**Issue by Phumix** [TownyAdvanced/Towny#2905]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
Rename a town when Towny is connected to a MySQL database using /t set name <name>
https://i.imgur.com/OAbjWAO.png
Doesn't have to rename it as many times as I did, two times should work. I just wanted to see if I could dupe the town more times.

### What is the expected output?
The towny data will duplicate and cause an error on next /ta reload or restart.
I remember this being a issue few years back too, however I ended up using flatfile for my server. But now we are using MySQL again for better performance. This will also cause towny lockdown.

Screenshot of duplicated town in the database can be found below.
https://i.imgur.com/KhUghtL.png

### What is your Towny version?
0.92.0.10

### What is your spigot/craftbukkit version?
1.12.2-R0.1

**Comment by Phumix** [comment]
This error does not happen with nations, just tested. It instantly updates the nation names. So this is only for towns it seems.

I believe this is same issue as reported under this ticket #2180

**Comment by DracarysPro** [comment]
This is confirmed to happen, has happened to me several times and I had to block the renaming feature.

**Comment by LlmDl** [comment]
@Phumix @DracarysPro I'd like to know exactly which version of mysql you use, and for anyone else who will comment on this ticket to also include the type/version of database software you're using and a screenshot of your /towny universe screen. I just had a user in the IRC who has had issues with renaming towns cause the town's membership in their nation to become corrupt.  (If you're having that exact issue please tell me if the town was a capital of the nation or not.)

I've never been able to reproduce these bugs as my testing databases are not large enough and I cannot slow things down enough to cause the problem.

**Comment by LlmDl** [comment]
So there's a PR in place https://github.com/TownyAdvanced/Towny/pull/3312 that will mean this all has to be retested/might not even be a thing anymore. Closing this ticket. If there's still problems with the new code we'll see about it in a new ticket.
