### ISSUE TITLE
Suggestion Command: /plot eviction

### ISSUE THREAD

**Issue by SeDark** [TownyAdvanced/Towny#2906]
For a long time I've been having a problem in my server. When mayors and assistants reach the max number of plots they can claim, they aren't able to remove plots from unactive town residents since they have no free plots to do so.
 
I would suggest adding a command that could be used by the mayor or assistant to claim a plot directly for the city without them needing to claim it for themselves and then unclaim it so it goes back to the city.
 
If this can't be done, at least it would be nice if there was a permission like "towny.canclaimonemore" which if given to mayors and assistants, when they had 100 plots, would let them claim 1 more so they are able to claim and unclaim plots from the afk residents.
 
______________________________________________________________________
 
On another matter, it would be great if you could add a permission that adds extra plots, on my server what I'm planning to do is create certain towny related challenges and quests that when completed add more plots to the player. For example when completing a specific quest the player is rewarded with "towny.extraplots.50" that would essentially increase your limit by 50. So if someone has ("towny_maxplots.100") and reaches the 100 plots, they would be able to claim up to 150. Could this be done?

**Comment by LlmDl** [comment]
You're saying that you've given mayors and assistants limits on their personally owned plots (using the maxplots node,) and because of this they cannot use the /plot claim command to take a plot from a resident?

**Comment by SeDark** [comment]
Yes, a normal user can claim 100 plots but they only 99, if they claim 100 they can not use "plot claim" to work in their city.

**Comment by SeDark** [comment]
I consider this resolved, because it has already been done

https://github.com/TownyAdvanced/Towny/commit/be1ece7815fb5b3111d36d5b9546298e7404acbc

**Comment by LlmDl** [comment]
Thanks for the PR on this one SeDark.
