### ISSUE TITLE
[Issue] Problem with maximum invites

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2911]
Hello,
We have faced such problem, when a player receives a maximum amount of invites from towns, he is supposed to get a message, that he reached a max amount of invites. But he sees a different message instead "None of the names were valid". So, how we can fix it?
We are looking forward to your answer

Here is a screenshot: https://imgur.com/a/QC2lZ
Startup: https://pastebin.com/8LjtHD37
Console log to show the issue better: https://pastebin.com/brzMtypZ
config.yml: https://pastebin.com/EkrZXyZm
Spigot version: 1.11.2
Towny version: 0.92.0.11

**Comment by LlmDl** [comment]
That console message is saying that Towny couldn't read whatever you have in your language file for that string. That is why there's a blank [Towny] line in your screenshot. Fix your translation file.
