### ISSUE TITLE
Sentence. Transfer

### ISSUE THREAD

**Issue by MAXvxv** [TownyAdvanced/Towny#2914]
Is it possible to separate this function in your language file "% s = data provided by the plugin." 

into several parts?

Example english.yml
%a Disabled/Enabled
%b "playername"
%c "rank"
%d "townname"
%e "nationname"
etc

msg_changed_pvp: '&c%d PVP has been %a.'
msg_you_have_been_given_rank: 'You have been granted the %c rank of %b.'

This should improve and facilitate the translation
It would be nice to add this feature to all versions of the language files

**Comment by LlmDl** [comment]
I'm not exactly sure what you're asking for here. Are you wanting to be able to reorder the %s when there are multiple %s's in a string?

**Comment by MAXvxv** [comment]
Yes, %s in some places needs to be moved because of the Russian language, but I do not understand how to do it, the same problem can arise with Turkish and Chinese languages, %s can be in different places for each language, you know what I'm talking about?

**Comment by LlmDl** [comment]
Yes, this can already be handled by java itself 

https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html

make note of this section:

```

   // Explicit argument indices may be used to re-order output.
   formatter.format("%4$2s %3$2s %2$2s %1$2s", "a", "b", "c", "d")
   // -> " d  c  b  a"
```
