### ISSUE TITLE
Issue with /towny spy moving the admin to general if they are in another channel.

### ISSUE THREAD

**Issue by Phyther** [TownyAdvanced/Towny#2916]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. /a 
2./towny spy
3.moved to general chat

### What is the expected output?
1./towny spy should not move the admin from the channel they are in.
2.
3.

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
Spigot 1.12.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/z10vA5fh
2. https://pastebin.com/MMvYyLTB
3. https://pastebin.com/qdMeyppD
4. No errors

(optional) If this is to do with permissions, 
5. Your permissions file : Not a part of this issue.

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/eJq1Dpjp
7. Your channels.yml : https://pastebin.com/ecZthU7B

**Comment by LlmDl** [comment]
fixed in 0.92.0.11
```
- Fix using /towny spy moving a player from other chat channels and removing other modes.
```
