### ISSUE TITLE
Suggestion: Towny Spy specific channel

### ISSUE THREAD

**Issue by Phyther** [TownyAdvanced/Towny#2917]
Can /towny spy have the town/nation/channel modifier added so someone could spy on a specific channel?

**Comment by HvPanda** [comment]
Has this issue already been fixed? Maybe I've missed it. I could really use this on the server. I can't see no difference between spying and people that are really talking to me.

**Comment by LlmDl** [comment]
There's a new spy format applied to chat you're spying on, which should help with not confusing spied-on chat with normal chat.

The ability to spy on specific channels has not been added yet.
