### ISSUE TITLE
Console spamming errors - Cannot update to 0.92.10

### ISSUE THREAD

**Issue by KevinM23** [TownyAdvanced/Towny#2918]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. I dont know the steps, the error occurred without knowing what's going on to be honest.

### What is the expected output?
1. Not having errors spamming the console and cannot update to the 0.92.10 as suggested here by you:
https://www.spigotmc.org/threads/towny-spamming-console-without-reason.313181/#post-2959442

Constantly spamming:
https://pastebin.com/DqxEvs73

### What is your Towny version?
Do not say "latest". 0.92.0.0

### What is your spigot/craftbukkit version?
Do not say "latest". This server is running CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/mfkfCZbw
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/9dcJxtB2
3. Your townyperms.yml :
https://pastebin.com/DY3bs0cM
4. Your log's error : 
Not sure what you mean by this. In the towny log folder i do not see any error files. The errors shown are:
https://pastebin.com/DqxEvs73

And after you suggested (to fix this) to update to 0.92.10, the error is that it cannot be updated:
https://pastebin.com/tkxZbnfC

Summary:
The server started spamming an issue which you suggested would be fixed by updating to the newest version. When trying to do this, seems  towny cannot load in the newest version, so i'm stuck at the moment.

**Comment by LlmDl** [comment]
The new error is because you didn't read the changelog and do the required changes to your town and nation levels section of your config. The older error has already been fixed in 0.92.0.11 which you can have an advanced copy of from here: https://www.dropbox.com/s/jbnxvja6bjy3i8n/Towny.jar?dl=0

Please confirm that this solves the primary issue.

**Comment by KevinM23** [comment]
So I need to do the changes needed for 0.92.0.5 and also 0.92.0.10 and then update to 0.92.0.11?

**Comment by LlmDl** [comment]
You don't need to update in stages, you just need to do the changes. In the changelog after version 0.92.0.0 look for REQUIRED CHANGES and make sure you do them. Alternatively the town and nation levels sections can be deleted if you use the default settings, towny will readd them with the new defaults which aren't missing what you're missing.

**Comment by KevinM23** [comment]
Helllo,

Thanks for your help. After updating and reviewing the logs for a few days I can confirm everything works fine now.
