### ISSUE TITLE
/plot perm hud causing server to freeze

### ISSUE THREAD

**Issue by SirKillian** [TownyAdvanced/Towny#2919]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. using the command "/plot perm hud" (players do not need perms)

### What is the expected output?
1. The server will completely freeze and kick multiple people for "timed out" (even when server is using decent hardware)

### What is your Towny version?
Towny 0.92.0.9

### What is your spigot/craftbukkit version?
PaperSpigot git-paper-1391
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://hastebin.com/abixoditup.log

2. Your Towny config.yml (if using MySQL please remove password,) :
https://hastebin.com/ubozadupej.yml

3. Your townyperms.yml :
https://hastebin.com/ribadikudu.yml

4. Your log's error : 
This isnt really an error but you can see how everyone gets disconnected shortly after usage of the command. I made sure it happens every single time someone uses this command.
https://hastebin.com/biwicefufo.log

**Comment by LlmDl** [comment]
I have given @SirKillian a test build to see if this is fixed. Waiting for feedback.

**Comment by SirKillian** [comment]
Still happening on the provided test build. Even when there is only 1 player on the server i do get a small freeze.

**Comment by Articdive** [comment]
I will do some further testing on this this week, if LlmDL doesn't find out the issue already xD.
I think it may have to do with being on PaperSpigot but this is a shot in the dark.

**Comment by LlmDl** [comment]
All of the hastebin files expired on this, if there is still an issue after you've updated to 0.92.0.12 or newer please open a new ticket. 0.92.0.12 is available on the discord's [#new_builds](https://discord.gg/vW9z2p5) channel.
