### ISSUE TITLE
Suggestion: Put player in Global channel if does not have a town and is still in towny channels

### ISSUE THREAD

**Issue by DracarysPro** [TownyAdvanced/Towny#2920]
Sometimes players have this problem, they are in a town and logout while being in town / nation channel, and if their town gets disbanded while they are offline, when they log-in again, they are still in the town/nation channel, thus they can't write in chat. Would be a cool fix just adding a check at login if the player does not have a town/nation and putting him in the global channel.

**Comment by LlmDl** [comment]
This was fixed a while back, file an issue ticket if you still have it happening.
