### ISSUE TITLE
Language does not change (?)

### ISSUE THREAD

**Issue by Grabenkind** [TownyAdvanced/Towny#2922]
I wanted to change the language in towny to german, but towny does not take it,
no matter if I take a template or translate it by hand.

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

-> german.yml: https://pastebin.com/embed_js/7MWVZ8E9

latest.log: https://pastebin.com/embed_js/k3nXyYGq
config.yml: https://pastebin.com/embed_js/4UBWgV0f
townyperms.yml: https://pastebin.com/embed_js/uisVUHJr

ChatConfig.yml: https://pastebin.com/embed_js/F4Gwt49q
Channels.yml: https://pastebin.com/embed_js/1N7L60Vw

**Comment by Grabenkind** [comment]
@LlmDl What do you mean by that? I don't understand :/ (sry I'm new to this Plugin stuff)

**Comment by LlmDl** [comment]
Nevermind, I see now that it's just the link you provided, that changed how it's presented. Your files don't have a bunch of ```/'s``` symbols everywhere. When you set the language to german.yml and towny creates the german.yml does it not work before you begin making other changes?

**Comment by Grabenkind** [comment]
Towny does not create the .yml automatically. 
I have to translate the default file or can use a template.
I've already downloaded a german.yml, but he does not recognize it.
And if I want to edit / translate the default file, then Towny does not recognize it too.

**Comment by LlmDl** [comment]
Try this:

- Stop your server.
- Delete or rename your german.yml file.
- Make sure that your config's language is german.yml and start the server. 

Towny should be making the german.yml appear using the german.yml file included inside of the towny.jar file. If a file called german.yml does not appear then you can open your towny.jar file using winrar or 7zip and copy the german.yml file from inside.

**Comment by Grabenkind** [comment]
I have followed the steps (I did not know that there is a german.yml in .jar), but he also does not recognize this german.yml.

**Comment by LlmDl** [comment]
Pastebin.com the new startup of you following the steps above. Also pastebin.com the german.yml file you are using.

**Comment by LlmDl** [comment]
I've just tested it myself and when I set my config to use german.yml for the language, it makes a german.yml and it works just fine in-game.

On an unrelated note: there's a townychat error, your channels.yml's local section should have type: GLOBAL or type: DEFAULT, there is no type: LOCAL.

**Comment by Grabenkind** [comment]
UPDATE: He generates the german.yml !

BUT! Towny also does not recognize this file -.-
He seems to work around this File :(

**Comment by Grabenkind** [comment]
Ingame Screenshot: https://ibb.co/bKiwwn

**Comment by Grabenkind** [comment]
It is still all in English.
In some places he does not seem to show ANY command description (see screenshot)

**Comment by LlmDl** [comment]
Pastebin.com the startup again now that your german.yml has generated.

**Comment by Grabenkind** [comment]
latest.log: https://pastebin.com/embed_js

By the way, thank you for your patience.

**Comment by Grabenkind** [comment]
Sorry, wrong Link!
here is the right one:

latest.log: https://pastebin.com/mwsRwZtL

**Comment by LlmDl** [comment]
I'd forgotten that there was an issue with the german.yml included with 0.92.0.0, it was fixed in 0.92.0.2, which you can download from here: http://towny.palmergames.com/dev-build-towny-advanced-0-92-0-2-1-11-2/
