### ISSUE TITLE
Suggestion: towny.chat.spy node should allow /towny spy

### ISSUE THREAD

**Issue by Phyther** [TownyAdvanced/Towny#2923]
Groups with the towny.chat.spy do not have access to /towny spy but can access spy with /res set mode spy

### What steps will reproduce the problem?
1. set permission node towny.chat.spy to a player or group
2. Player/group cannot do /towny spy

### What is the expected output?
1. Player/group should be able to do /towny spy

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
paper 1.12.2 (git-paper-1391)

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.12

```
    - Fix /towny spy not working when a player has towny.chat.spy but not towny.command.towny.spy
```
