### ISSUE TITLE
Suggestion: Option to delay the last connection update

### ISSUE THREAD

**Issue by SeruhioX** [TownyAdvanced/Towny#2924]
I would like there to be an option so that if a user enters the server less than x time (configurable) his last connection is not updated.

For example, if the minimum time to tell you that you have logged in is 5 minutes, if you enter 2, it is not updated and it is as if you did not enter the server that day.

This option would help a lot in cases where I must decide if the user is active on the server or only enters 5 seconds and disconnects.

**Comment by LlmDl** [comment]
I thought about this, while it could be done it means running a task from inside another task which could get messy. It's also a little bit unfair to the player that wants to keep his resident from being deleted.
