### ISSUE TITLE
Problem with Embassy in other City's

### ISSUE THREAD

**Issue by SeDark** [TownyAdvanced/Towny#2927]
Users can put their own plots for sale and remove them from the sale, but if these plots are embassy and the embassy is not from their own city they can't be removed from the sale.

### What steps will reproduce the problem?
1. /plot fs 1 in another city that is not yours, that is, in an embassy
2. /plot nfs

### What is the expected output?
1.That the plot of sale be removed

### What is your Towny version?
v0.92.0.11

### What is your spigot/craftbukkit version?
PaperSpigot 1.12.2 (1403)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/SDfyT4eH
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/9mBqy8zu
3. Your townyperms.yml :  https://pastebin.com/25veqtmG
4. Your log's error : No error is displayed

**Comment by LlmDl** [comment]
So it's a plot they own, which is an embassy, but it's not in the city they belong to?

**Comment by LlmDl** [comment]
As of 0.92.0.12:

```
    - Fix Embassy plots not being able to be removed from sale under certain conditions.
    - Fix placing an embassy plot for sale not showing the for sale message under certain conditions.
    - Fix a missing denial message when using /plot nfs on an area where the user does own the land.  
```
