### ISSUE TITLE
Error on new player join

### ISSUE THREAD

**Issue by Kbryst** [TownyAdvanced/Towny#2928]
### What steps will reproduce the problem?
1. Happens when a new player joins the server

### What is the expected output?
1. I don't know, I don't think the error really does anything

### What is your Towny version?
0.92.0.8
*Will be moving to newer versions soon to test as welll

### What is your spigot/craftbukkit version?
Paperspigot 1.12.2

Error:

https://pastebin.com/1yjXHuXZ

*I do not have access to the start up logs and all of that at this time. 
*I have already contacted the other plugin that shows up in this error, they directed me to towny.

**Comment by ThisIzEthan** [comment]
Looks Like a problem with a player

**Comment by Kbryst** [comment]
This pops up every time a new player joins for the first time.

**Comment by LlmDl** [comment]
Show me your startup logs.

**Comment by Kbryst** [comment]
https://pastebin.com/RqzSpBgy

**Comment by LlmDl** [comment]
I don't see any reason why this should happen, you haven't made any significant changes to the townyperms.yml have you? Maybe try updating to 0.92.0.10 or I can give you an early copy of 0.92.0.11

**Comment by Kbryst** [comment]
I believe we added a few ranks to the towny perms actually. If I switch it back to the default townyperms.yml what happens to players in the ranks that go missing?

**Comment by LlmDl** [comment]
Can you pastebin.com your townyperms.yml please. This is why the form you skipped is important.

**Comment by Kbryst** [comment]
Sorry, doing a lot of traveling and can't always access the files. Honestly didn't think you would reply so quickly lol. 

https://pastebin.com/vNJBiVKW

**Comment by Kbryst** [comment]
Sure thing,

https://pastebin.com/BMKK7P7e

**Comment by LlmDl** [comment]
I'm guessing you use a plugin that teleports the players to a spawn when they join, but that location is not the actual minecraft/bukkit server spawn?

**Comment by Kbryst** [comment]
Yeah I do. I think it’s CMI that does it actually.

**Comment by LlmDl** [comment]
It's teleporting them quicker than towny can properly register them I guess, so when they teleport to a different plot it's throwing an error. You can set their actual server spawn point to where ever CMI is moving them to to get rid of the error.
