### ISSUE TITLE
Suggestion: Display towny-info in the "toolbar"

### ISSUE THREAD

**Issue by Nesseley** [TownyAdvanced/Towny#2929]
I really love showing my players who owns a plot, but if the mayors don't build a "correct" town, they will spam their chat as they walk trough the town. (Because they walk trough owned plots)

Instead we could display towny-messages like [outpost] [farm] ~username over the toolbar, then we could reduce spam in chat by alot.

**Comment by KarlOfDuty** [comment]
I agree with this, we did the same thing with mcmmo's spammy messages and it is much better using the action text.

**Comment by LlmDl** [comment]
I'll have to look into whether this is something that is part of the Bukkit API yet.

**Comment by Nesseley** [comment]
Multiple other plugins uses this feature so its possible :)

**Comment by LlmDl** [comment]
It is possible but Towny only makes use of the Bukkit API. We don't use any craftbukkit, spigot or NMS code.

**Comment by LlmDl** [comment]
This is something I checked out recently:

**Comment by LlmDl** [comment]
Done as of 0.95.1.2
