### ISSUE TITLE
Sponge/Forge Support

### ISSUE THREAD

**Issue by ACPenguin** [TownyAdvanced/Towny#2933]
Sponge/Forge Support

Yo can you guys develop the sponge or forge version, if not doing it already. A lot of people would love to see towny on modded servers. I've been trying to find something like towny war but there's nothing like it

So could there be a sponge/forge version or would it be to long of a task. Like you could work with the guy whos making the Nations Plugin https://forums.spongepowered.org/t/earth-africa-nations-v2-5-towny-like-protection-plugin/12127

-ACPenguin

**Comment by LlmDl** [comment]
I'm afraid I do not have time to port Towny over to sponge. I thought there was still bukkit/forge servers running though, maybe you could run that.
