### ISSUE TITLE
[Bug] /plot perm hud causing NPE's from plot name.

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2935]
Hello, the problem remained. Thanks in advance for your help.

Issue: https://github.com/TownyAdvanced/Towny/issues/2875
New video: https://youtu.be/Fbpffrn4xX4
Version Towny: 0.92.11

**Comment by AIphaDragon** [comment]
Startup + error: https://pastebin.com/4n032eGT

**Comment by LlmDl** [comment]
Can you test with this build please: https://www.dropbox.com/s/166n2uzkm4a62sv/Towny%20alphdragon2.jar?dl=0 

It is an advance copy of 0.92.0.12, here is the changelog so far: 

```
0.92.0.12:
    - New Feature: Nation spawn points! courtesy of MartenM
      - Nation's can now set a spawn and whether their spawn is public, nearly exactly like town's and their spawn abilities.
      - Enemy's can be prevented from spawning to public nations' spawns using the already existing config "prevent_town_spawn_in:" list.
        - You can also prevent spawning from unclaimed or neutral areas using this config entry.
      - Any cost for spawning to a Nation is paid to the nation being spawned to.
      - Cost is the same as the cost for spawning to a Town.
    - New Config Option: global_nation_settings.capital_spawn
      - default: true
      - If enabled, only allow the nation spawn to be set in the capital city.
    - New Config Option: global_nation_settings.default.public
      - default: false
      - If set to true, any newly made nation will have their spawn set to public.
    - REQUIRED TOWNYPERMS.YML CHANGE:
      - Add towny.command.nation.spawn to your nations.default rank/group.
    - Bump language files to version 0.46.
    - German.yml updated to 0.46 by Wolf2323.
    - Overhaul cache/permissions system to use material instead of blockid:data values. 
      - Old API still in place but deprecated. 
      - Plugin authors are advised to begin using new Material options when querying the Towny cache/utils.  
    - Fix /nation not showing the nation ranks. 
    - Add /plot evict to /plot ?.
    - Fix Embassy plots not being able to be removed from sale under certain conditions.
    - Fix placing an embassy plot for sale not showing the for sale message under certain conditions.
    - Fix a missing denial message when using /plot nfs on an area where the user does own the land.
    - Fix /towny spy not working when a player has towny.chat.spy but not towny.command.towny.spy  
    - New Config Option: resident_settings.is_showing_welcome_message
      - default: true
      - If true, players who join the server for the first time will cause the msg_registration message in the language files to be shown server-wide.
```

**Comment by AIphaDragon** [comment]
The problem remains.

**Comment by LlmDl** [comment]
Can you pastebin.com the error so I know it's teh same and not different now?

When you are typing /spawn, which plugin is handling that? Is the /spawn in that plugin different from the minecraft world's spawn point? Are you changing worlds? Is towny enabled in that world?

**Comment by AIphaDragon** [comment]
1) Error: https://pastebin.com/ik7mHyyL
2) Essentials - /spawn
3) Worlds change
4) Towny enabled only in one world

**Comment by LlmDl** [comment]
Try this: https://www.dropbox.com/s/jwv431ou719yuvs/Towny%20alphadragon3.jar?dl=0

**Comment by AIphaDragon** [comment]
It does not matter. An error appears during tp both from one world, and from another. The problem remains.
Error: https://pastebin.com/D5iekKg4

After testing, came to the conclusion that the problem is in one of the plugins. And indeed it is. Updated the HealthBar plugin to the latest version and the problem has disappeared - https://www.spigotmc.org/resources/healthbar.15230. Sorry for the trouble. Thanks for the help.

**Comment by LlmDl** [comment]
Well that's a weird conclusion. Good to hear you figured it out.
