### ISSUE TITLE
Could towny support Chinese charactor as town or nation name?

### ISSUE THREAD

**Issue by smartmadio** [TownyAdvanced/Towny#2938]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.set Chineses charactors in town name
2.restart server
3.town will disappera

### What is the expected output?
1.
2.
3.

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
1.12.2 Spigot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
There are regex lists in the Towny config which towny uses to validate names. Since the chinese characters are not there by default I assume this is why it does not work. If you were to add your characters to the regex it might allow chinese names.

**Comment by w15736776759** [comment]
> 在Towny配置中有正则表列表，towny用它来验证名称。由于中文字符默认不存在，我认为这就是为什么它不起作用。如果您要将字符添加到正则表达式，它可能允许使用中文名称。

How should I fill in this form?

**Comment by w15736776759** [comment]
> 这

The board can be changed into Chinese by modifying the regular expression, but the name is not good.
