### ISSUE TITLE
Question MPDB and Towny

### ISSUE THREAD

**Issue by Sprungente** [TownyAdvanced/Towny#2940]
Hello my honeys :))

Today i have a question how MPDB works with Towny, specially with the daily taxes.

Does it have a bridge or something? 

Does MPDB or Towny support each other? If not, could it add support for it?

Link to the plugin: https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/

@brunyman

**Comment by LlmDl** [comment]
Towny doesn't store the bank accounts for towns and nations, they are stored in your economy plugin. There should be no reason why the mysql bridge doesn't do what it does for all the other accounts.
