### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Beelzebu** [TownyAdvanced/Towny#2941]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Clone repository from github
2. Run `ant` from the terminal

### What is the expected output?
1. It should build the latest version of the plugin

Here is the error log https://hastebin.com/tujiyadafo

**Comment by LlmDl** [comment]
Odd, it builds fine for me. Are you sure nothing old is cached or otherwise interfering with the new code? Those NSpawnLevel and NationSpawnLevel are from very very recent commits.

**Comment by Beelzebu** [comment]
I cloned the latest version from github, it seems that not all classes are on github, so I see there is no NationSpawnLevel [here](https://github.com/TownyAdvanced/Towny/tree/master/src/com/palmergames/bukkit/towny/object)

**Comment by LlmDl** [comment]
Ah right, I forgot to check the box on that new file. Fixed now.
