### ISSUE TITLE
Suggestion : Per-Town Nation Upkeep.

### ISSUE THREAD

**Issue by Liancos** [TownyAdvanced/Towny#2943]
Hi ! 
I would like to know if it would be possible to modify the taxes of nations. 

My idea would be to able a new tax in the config file (in addition of the tax who already exist).      Where nations pay according to their number of cities

Like that : (amoutofmoney) * (numberofcity).

Thx for regarding my suggestion ! Have a great day !

**Comment by Phyther** [comment]
You mean kind of like towns pay by plot, nations would pay by towns? I love it!

**Comment by LlmDl** [comment]
This would be replacing the upkeep they pay correct?

**Comment by Liancos** [comment]
Yeah i want to do like the town but for the nation ^^

**Comment by TheFlagCourier** [comment]
I think this would be nice, especially with extra modifiers:
Do 'Public' (warpable) towns raise/lower the tax rate?
Should distance between the two furthest town homeblocks affect the modifier?

**Comment by Ectabro** [comment]
Any news for this ?

It would be awsome to create an other sytem of taxes based on the number of towns in the nation !

**Comment by LlmDl** [comment]
Completed as of https://github.com/TownyAdvanced/Towny/commit/e0c1ff3efd4426bd82d9e3da5d7c2a3b8beab78c 

Part of 0.94.0.4
