### ISSUE TITLE
[Bug] Items in the frame can be twisted

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2945]
### What steps will reproduce the problem?
Video: https://youtu.be/WUGK58l4CKo

### What is your Towny version?
0.92.12

### What is your spigot/craftbukkit version?
Spigot 1.12.2

1. Full server startup from the logs\latest.log : https://pastebin.com/dPzEH1Zq
2. Towny config.yml: https://pastebin.com/Z2s5Mr7F

**Comment by LlmDl** [comment]
You're missing ITEM_FRAME in your switch_ids, add it and try again.

**Comment by AIphaDragon** [comment]
Helped, thanks.
