### ISSUE TITLE
[Bug] Problems with "/plot perm on" during Flag War

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2947]
### What steps will reproduce the problem?
Video with "/plot perm on": https://youtu.be/pwIQ_PI4Fi8
Video with "/plot perm off": https://youtu.be/NJutjd4bbQs
Description: if the perms in the region are ON, then the flag of war can not be set. We are informed, that you no longer support Flag War, as you don't have time for this. But if there is, we would like to ask you to fix this issue as it is the basic mechanic.
Thanks in advance.
We are looking forward to your answer

### What is your Towny version?
0.92.12

### What is your spigot/craftbukkit version?
Spigot 1.12.2

1. Full server startup from the logs\latest.log : https://pastebin.com/dPzEH1Zq
2. Towny config.yml: https://pastebin.com/Z2s5Mr7F

**Comment by LlmDl** [comment]
Does your video-maker have towny.admin in his permission nodes?

**Comment by AIphaDragon** [comment]
This problem was with ordinary players. We just recreated it.

**Comment by LlmDl** [comment]
If you want to have someone find the problem and code the fix for it, they can submit the pull request here and I will go over it/accept it.
