### ISSUE TITLE
[Question] Flag War between 2 nations (/n enemy add nation)

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2948]
### What steps will reproduce the problem?
Video: https://youtu.be/tWW1fUrTHt8
Description: you can set the flag of war only after the command is written (/n enemy add test22). Although there has already been declared war on another nation (/n enemy add test11). That is, for the war 2 nations must declare war to each other, not one. So it's planned? Thank you in advance for your help.

### What is your Towny version?
0.92.12

### What is your spigot/craftbukkit version?
Spigot 1.12.2

1. Full server startup from the logs\latest.log : https://pastebin.com/dPzEH1Zq
2. Towny config.yml: https://pastebin.com/Z2s5Mr7F

**Comment by LlmDl** [comment]
You have disallow_one_way_alliance: 'true' in your config, I was fairly sure that also made enemy declarations also two-way only. Is this not the case?

**Comment by AIphaDragon** [comment]
Put on false and nothing has changed. Maybe it works correctly, but we do not understand.

**Comment by LlmDl** [comment]
I looked at the code and it is only ally-relationships which are two-way. Enemies have to declare each other, and are not affected by the config line I mentioned above. One-way war was never a planned thing.
