### ISSUE TITLE
Suggestion: Multiple-day-long Cooldowns.

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2949]
Hello, 
Recently, we have noticed, that for oncoming wars nations add new towns just for temporal reinforcement. Then, as there is no need of them, new towns are kicked. And this remains the same until the next battle, so these towns can be added and kicked a lot of times a day.
Moreover, there is a bonus of chunks for the nation, so some towns join the nation only for bonus. They just join, receive a bonus for town, claim as much land, as the can afford and just leave the nation. It appears, that a town can have more chunks than it can claim (100 claimed out of possible 80, for instance).

So, we would like to suggest you some new features. 

- Cooldown on creating nation after deleting it (if a player deletes his nation, there is a configurable cooldown on it - for instance, 7 days) 
- Cooldown for town on joining nation after leaving from nation 
- Cooldown for player on joining town after leaving from town

We are looking forward to your answer

**Comment by LlmDl** [comment]
Towny now has a cooldowntimertask. It's being used for toggling pvp, and using the towny spawn commands. Sadly it is not persistant over server restarts so it won't be very useful for long-term cooldowns like days/weeks.
