### ISSUE TITLE
[Question/Bug] Claim/unclaim outpost

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2952]
Hello! So it should be? Thanks in advance for the answer.

### What steps will reproduce the problem?
1. Creating an outpost
2. Claim chunk near the outpost, at least 1 chunk.
3. Unclaim the outpost
4. Now it is possible to have one more town and the counter of the outpost was lost
5. Video: https://youtu.be/OdAcsg37LZU

### What is your Towny version?
Towny - 0.92.12

### What is your spigot/craftbukkit version?
Spigot-1.12.2

### Please use Pastebin.com to link the following files:
1. Full server startup from the logs\latest.log : https://pastebin.com/dPzEH1Zq
2. Towny config.yml : https://pastebin.com/KbgkNiRg

**Comment by LlmDl** [comment]
That is expected behaviour. The downside to the player is that they have to walk between the plots to get to their now non-outpost.
