### ISSUE TITLE
[Problem] After-war spam message and console errors

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2953]
Hello,
After finishing Event War by '/ta toggle war' I've got a spam of after-war result message. Moreover, there were errors in console, spamming as well. And the war wasn't ending.
So, how could I solve this problem?
Looking forward to your answer.

Here is a video to show the problem: https://www.youtube.com/watch?v=fHvFas3hAJY

Towny version: 0.92.0.12
Spigot version: 1.11.2

config.yml: https://pastebin.com/fwHQschu
My language file - russian.yml: https://pastebin.com/PLYM3ttr
Errors: https://pastebin.com/VERnHQQk

**Comment by LlmDl** [comment]
Pastebin.com the error you get now.

**Comment by LlmDl** [comment]
Nevermind, you're using 
```
msg_war_winning_town_spoils: '&6[Война]&b Лучший результат - город %s победил со счетом %d.'
```
when you should be using 
```
msg_war_winning_town_spoils: '&6[Война]&b Лучший результат - город %s победил со счетом %s.'
```

Is there a reason why you're not using the russian.yml included in towny?

**Comment by AIphaDragon** [comment]
Yes, that helped. Thank you.

Answering your question:
Well, actually included in towny russian.yml doesn't fully satisfy me. There are some wrong translations and sentences, which russians wouldn't use. Moreover, in my language file there is a gender division, so messages concern both boys and girls
