### ISSUE TITLE
[Issue] Event War - Chunk farming

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2955]
Hello,
Faced with a problem, when nations during Event War can infinitely farm bonus chunks.
So, attacking one town constantly and conquering town blocks or home blocks, they get bonus chunks.
Town leaves war, as it looses its home block, but on the nex war it is involved in war again with a minus some number chunks. And this negative bonus remains forever and do not exclude, or somehow protect this town from attacks and chunk conquer.

It looks like that: https://imgur.com/a/CK99f2I
Town with overfarmed bonus: https://imgur.com/a/VjqqrKR

So, is there any possibility somehow to solve this problem?
We are looking forward to your answer.

Towny version: 0.92.0.12
Spigot version: 1.12.2
config.yml: https://pastebin.com/KCVTyMmn

**Comment by LlmDl** [comment]
You can remove the transfer of townblocks by setting:

```
    # If set to true when a town drops an enemy townblock's HP to 0, the attacking town gains a bonus townblock,
    # and the losing town gains a negative (-1) bonus townblock.
    costs_townblocks: 'false'
```
which I believe is the default setting. It used to default to true but it does imbalance things quite a bit so I changed it.
