### ISSUE TITLE
[INFO] Built-in protection against cheats

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2956]
The essence of the problem: The player teleports down, if during the fall, when the flight is on, the player stops with a space. Thus, the players were dying.

Steps to repeat the problem:
1) In settings Towny: cheat_protection: 'true'
2) The player has the permission to use /fly
3) In any world, even if Towny does not work in it, we fly up
4) Disable fly by space
5) Player falls
6) Enable fly by space during the fall
7) Player teleports down

Solution:
In settings Towny: cheat_protection: 'false'

Video: https://youtu.be/Zn7yNxcGRj8

We solved the problem for ourselves. We decided to inform you of such a problem.

**Comment by LlmDl** [comment]
This is an older feature which doesn't even do all that it originally used to do. It primarily kept people from using client-side blocks that weren't removed yet from jumping over top of walls. 

I think most servers use a dedicated anti-cheat plugin now anyways, so this feature will probably be removed.
