### ISSUE TITLE
[Suggestion] Towny with Grief Prevention and Residence support

### ISSUE THREAD

**Issue by Baktus79** [TownyAdvanced/Towny#2957]
Hey

Towny is an awesome plugin with perfect features for building towns/cities, but for the average Joe this can be too much, especially on my server where they are used to a golden showel, right click each corner and you are good to go. When we update to 1.13 I want to integrate Towny on my server for all the players that want something more than just that showel. 

I am not sure how I can do this now because Grief Prevetion and Towny will overlapp the claims.
Is it possible to add support for Grief Prevetion and Residence so that they wont collide on to each other? I have already checked with both Grief Prevention and Residence devs for a solution but they both say that this has to be done from the Towny plugin.

I am hoping for a positive answer and I really wish I could use Towny for Minecraft 1.13.

**Comment by LlmDl** [comment]
Generally you should not have two types of area protection in the same world. For it to truly work, each plugin has to stop the other. Other plugins can hook are pretownclaimevent and stop a Towny claim from happening in a GP / residence area. Towny would also have to stop GP/residence claims in Towny areas, which is something I personally do not have the time to do. Someone else could put in a PR, but it's best to just stick with my original suggestion, do not put more than one protection plugin in a world.
