### ISSUE TITLE
[Bug] Problems with armorstand and rod

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2961]
Hello, found that if you hook on a rod for armor and pull, then it will move. Thanks in advance for your help.

### What steps will reproduce the problem?
Video: https://youtu.be/fdghma_uf-o

### What is your Towny version?
Towny 0.92.12

### What is your spigot/craftbukkit version?
Spigot 1.11.2-1.12.2

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/dPzEH1Zq
2. Your Towny config.yml : https://pastebin.com/KbgkNiRg

**Comment by LlmDl** [comment]
A thing as of 0.92.0.13:
```
- Fix fishing rods being able to grab a hold of armour stands and entities when the player using it does not have destroy permissions in the plot.
```
