### ISSUE TITLE
Daily Upkeep not rounded after second decimal

### ISSUE THREAD

**Issue by DracarysPro** [TownyAdvanced/Towny#2963]
Towny 0.92.0.12
Spigot 1.12.2

When using:
    town_plotbased_upkeep: 'true'
    town_plotbased_upkeep_affected_by_town_level_modifier: 'true'
And the upkeepModifier in the town_levels:
  upkeepModifier: 1.0

The output Daily Upkeep on the /t <town> command is not rounded after the second decimal
![image](https://user-images.githubusercontent.com/33911680/42129769-10b6ca24-7ccf-11e8-95f5-c8f8fd5cf7ab.png)

Could you please round the number after the second decimal?

**Comment by LlmDl** [comment]
Fixed in 0.92.0.13:
```
- Fix purely visual town upkeep bug when town_plotbased_upkeep and town_plotbased_upkeep_affected_by_town_level_modifier were used together.
```
