### ISSUE TITLE
[Suggestion] Configurable Payment for Renaming Towns/Nations

### ISSUE THREAD

**Issue by DracarysPro** [TownyAdvanced/Towny#2964]
A configurable amount of money to pay in order to rename a Town or a Nation should be added to the configuration. Many players abuse the command, and the frequent changes in the Town/Nation name often cause problems in the database (corruption in mysql is a daily occurance).

**Comment by TheFlagCourier** [comment]
If data corruption is a concern, would a safer option not be to _disable_ the ability to modify town/nation names for normal players? Surely this can be done through modifying townyperms and restricting it to townyadmins.

**Comment by DracarysPro** [comment]
Data corruption is not my primary concern. Being able to charge people for renaming is a simple but great feature.

**Comment by LlmDl** [comment]
This was completed by MartenM in the PR merged above.
