### ISSUE TITLE
[Issue] PEX overwrite Towny prefixes

### ISSUE THREAD

**Issue by Gabrusz** [TownyAdvanced/Towny#2966]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.If i put in the PermissionEX
2.talking
3.-

### What is the expected output?
1.What i got: "[TC][Member]player:"
2.What i want: "[TC][Member][assistant]player:"
3.Even if i put in every chatformat there will never be the "assistant" prefix

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/3GtvyXRB
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/32xn6AjU
3. Your townyperms.yml :https://pastebin.com/HaaaVEA0
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :https://pastebin.com/srXr2TKA

(optional) If this is to do with chat,
6. Your chatconfig.yml :https://pastebin.com/Y1bmNLap
7. Your channels.yml :

**Comment by LlmDl** [comment]
Is the assistant tag meant to come from having the town assistant rank?

**Comment by LlmDl** [comment]
Closed due to lack of feedback.
