### ISSUE TITLE
Suggestion: More info shown in /plot perm & /plot info alias.

### ISSUE THREAD

**Issue by Phyther** [TownyAdvanced/Towny#2968]
Add a /plot info that shows information on a plot such as permissions, type of plot, owner, etc.

Right now we have /plot perms but it doesn't show the owner or plot type.

**Comment by LlmDl** [comment]
I thought /plot perm had owner when it's owned?

**Comment by Phyther** [comment]
Ahh, yes, that is correct. Can we just add the type to that then?

**Comment by LlmDl** [comment]
Added in 0.92.0.13:
```
    - Add plot type to /plot perm screen.
    - Add alias /plot info alias to /plot perm.
```
