### ISSUE TITLE
Towny Claim Issue

### ISSUE THREAD

**Issue by BeastMode35** [TownyAdvanced/Towny#2969]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

Every time a town mayor wants to claim land, they are unable to. The only way they can claim land, is if they add 5 users to their town. The claimable blocks show up on /t, but until 5 members join the town cannot claim outside of the home block. This is for anywhere, not for outposts. 

### What is your Towny version?
Do not say "latest".

0.92.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".

spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Attached to the ticket below:

[2018-07-03-2.log.gz](https://github.com/TownyAdvanced/Towny/files/2161981/2018-07-03-2.log.gz)
[2018-07-03-2.log.gz](https://github.com/TownyAdvanced/Towny/files/2161982/2018-07-03-2.log.gz)
[2018-07-03-3.log.gz](https://github.com/TownyAdvanced/Towny/files/2161984/2018-07-03-3.log.gz)
[2018-07-03-4.log.gz](https://github.com/TownyAdvanced/Towny/files/2161985/2018-07-03-4.log.gz)
[2018-07-03-5.log.gz](https://github.com/TownyAdvanced/Towny/files/2161986/2018-07-03-5.log.gz)

2. Your Towny config.yml : https://hastebin.com/yadapapusu.coffeescript
3. Your townyperms.yml : https://paste.extendedclip.com/uqabelecof.php
4. Your log's error : Not enough residents in town to claim more land

If this is to do with permissions, 
5. Your permissions file : https://hastebin.com/ijosapupuj.coffeescript

**Comment by LlmDl** [comment]
This is a bug fixed in 0.92.0.2:
```
 - Fix for the minimum_amount_of_residents_in_town_for_outpost option in the config breaking claiming normal, non-outpost chunks.
      - Credit goes to Wolf2323 for finding and fixing this bug.
```
You have ```minimum_amount_of_residents_in_town_for_outpost```
Either set that to 0 or upgrade to at least 0.92.0.2
