### ISSUE TITLE
Suggestion: /townyadmin town {townname} forcepvp

### ISSUE THREAD

**Issue by Drc-DEV** [TownyAdvanced/Towny#2971]
I suggest adding a new command that forces pvp in a specific town (ignores the town's pvp e plot pvp set by the mayor, and restores them when toggled off). Useful in various situations or custom types of war/raids. Would also be cool to have an API method to do so (like from the town object: .setForcedPvP(boolean))

**Comment by LlmDl** [comment]
The api already has something which I think would work for you: http://palmergames.com/javadoc/towny-bukkit/com/palmergames/bukkit/towny/object/Town.html#setAdminEnabledPVP(boolean) 

It's a hidden option which has no command to it for in-game use, yet.

**Comment by DracarysPro** [comment]
Yeah but it seems like it does not work as intended. Both isAdminEnabledPVP and isAdminDisabledPVP return false on the boolean isPVP.

```
	public boolean isPVP() {

		// Admin has enabled PvP for this town.
		if (isAdminEnabledPVP()) 
			return false;
				
		// Admin has disabled PvP for this town.
		if (isAdminDisabledPVP()) 
			return false;
		
		return this.permissions.pvp;
	}
```

**Comment by LlmDl** [comment]
Done as of 0.94.0.6 and https://github.com/TownyAdvanced/Towny/commit/f8f94e3841a1a69e45a821cf6349d8fb27d406c2
