### ISSUE TITLE
Flag War lagging

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2972]
Hello,
Recently we had a problem with Flag War. We know, that Flag Wag is not supported anymore, but what can be an issue?
The problem is that during attack on chunck our TPS suddenly fell up to 10 and continued to be so until the attack finished.

Here are the timings: https://timings.spigotmc.org/?url=yamesimubu
Spigot version 1.12.2
Towny vesion: 0.92.0.12
config.yml: https://pastebin.com/55xNKkX8
Image of problem chunk: https://imgur.com/a/9FuWB4Y

**Comment by LlmDl** [comment]
It's not supported.
