### ISSUE TITLE
[Issue] Event War | Participation of the only nation in war causes war finishing cycling

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2973]
Hello,
We have got an issue with Event War.
So the problem is that in our Event War three nations were supposed to participate, but two of them bought neutrality and only 1 nation was participating. Sure it followed this nation to win the war, but the war was not finishing keeping to announce about its finish.
How this problem can be solved?

Log pastebin: https://pastebin.com/uMdVvsQ1
Config.yml: https://pastebin.com/55xNKkX8
Spigot version 1.12.2
Towny vesion: 0.92.0.12

**Comment by LlmDl** [comment]
Pastebin.com your language file.

**Comment by AIphaDragon** [comment]
Russian.yml pastebin: https://pastebin.com/BBynYLDf

**Comment by LlmDl** [comment]
Your language file has once again been translated with missing values

our english.yml:
msg_war_winning_town_spoils: '&6[War]&b Highest Score: %s won %s with the score %d.'

your russian.yml:
msg_war_winning_town_spoils: '&6[Война]&b Лучший результат: город "%s" победил со счетом %d.'

You're missing an %s

I also want you to start including your startup in your tickets., your version of 0.92.0.12 is not the same as what we have released at this point., your townysettings.java does not match what is current.

**Comment by LlmDl** [comment]
I need to know if fixing your language file solved the issue with war not ending.
