### ISSUE TITLE
[Help needed] Event War | Calculation of war spoils

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2974]
Hello,
Following ticket #2973 we had a nation, that won the war. But its war spoils were unexpectedly too high despite those which were specified in config. So instead of 10,000$, it won additionally 135,000$. Is there any formula of calculating this war spoils? What it bases on?  How can we modify it, so nations will get only those war spoils specified in config?

Looking forward to your answer.

Config.yml: https://pastebin.com/55xNKkX8
Spigot version 1.12.2
Towny vesion: 0.92.0.12

**Comment by LlmDl** [comment]
If it was your first war it's likely that the war spoils account had been collecting a lot of money. The war spoils account is added to whenever Towny makes money 'disappear', usually things like buying towns or nations, banks of fallen towns/nations. That amount is taken and the base_spoilts are added to it. 

You can view the account in your economy plugin. I believe it's called towny_war_spoils.

**Comment by AIphaDragon** [comment]
As economy plugin we use Essentials. Can this account be found somewhere in Towny files? Or it only conciders specific plugin that we use for economy? Can it also be connected with open/closed economy type when, for instance, tax money from towns are transfered on specified account?
We simply cannot find the account with such name in our Essentials files

**Comment by LlmDl** [comment]
None of the economy accounts are stored in towny, they're all in your eco plugin (ess eco). It will be towny-war-chest (just looked it up on my server.)
