### ISSUE TITLE
Ranks being reset when Town is Kicked by a Nation

### ISSUE THREAD

**Issue by DracarysPro** [TownyAdvanced/Towny#2976]
Towny 0.92.0.12
PaperSpigot 1.12.2

When a Town is kicked by its Nation, everybody inside the Town who has been kicked lose their town ranks (only mayor is spared)

Create a Town
Create a second Town
Make the second Town create a Nation
Make the second Town add the first Town to the Nation
Rank some players in the first town
Make the second Town kick the first Town
Watch all the ranks go away in the wind

**Comment by LlmDl** [comment]
Pastebin.com your townyperms.yml, and startup log

**Comment by LlmDl** [comment]
We're clearing all their perms and then adding their perms. When the mayor is getting his perms, the residents should be getting their rank nodes too. There's probably something up which is not immediately obvious, next time do not skip the form.

**Comment by DracarysPro** [comment]
Well It's the whole rank that gets removed. Not only the permissions. If you had a player ranked as builder, that player will lose his builder rank.
I tested with the default townyperms.yml, using flatfile database. No errors in the startup log.

**Comment by LlmDl** [comment]
So when you look at the resident using /res NAME, or in the /town TOWNNAME screen their ranks are gone?

**Comment by DracarysPro** [comment]
Yes, exactly. In a few hours I'm going to test this with 0.92.0.13 pre-release, I'll tell you if the problem still persists.

**Comment by LlmDl** [comment]
I've fixed it just now, it will be a part of 0.92.0.13 or 0.93.0.0 whichever gets released first.
