### ISSUE TITLE
Missing space between nick and online status in /res page

### ISSUE THREAD

**Issue by Leomixer17** [TownyAdvanced/Towny#2986]
In the first line of the resident status page the `(Online)` status is shown attached to the nick. It would be better if there was a space.

### What steps will reproduce the problem?
1. Do /res

### What is your Towny version?
0.92.0.12

**Comment by LlmDl** [comment]
A thing as of 0.92.0.13

**Comment by Leomixer17** [comment]
@LlmDl Why do you have created another string for fix this? I thought if it was possible to put the space into the plugin code, otherwise it would have been enough to add a space to the existing strings

**Comment by LlmDl** [comment]
A new language string means that all teh language files and existing language files will have the space. Changing the code would be putting a space that cannot be configured by the end-user. Changing just the existing language string would leave all the existing towny installs without a space.

**Comment by Leomixer17** [comment]
@LlmDl Changing the string to which the code refers will change the space even in the existings towny installs
