### ISSUE TITLE
Suggestion: Add some missing translations

### ISSUE THREAD

**Issue by Leomixer17** [TownyAdvanced/Towny#2987]
There are some strings that are still not translatable.
- [x] /towny map
- [x] In the string "Not allowed to %s in the wild." the possible values of %s are not translatable, so the result will be an english word in a phrase in another language
- [x] /t toggle (Enabled/Disabled variable)

**Comment by LlmDl** [comment]
When did github start doing those check boxes. I like it.

**Comment by LlmDl** [comment]
```
    - Made build/destroy/switch/item_use parts of denial messages translatable.
    - Made /towny map translatable.
    - Made feedback from /plot|town|nation|townyworld|townyadmin toggle commands translatable, ex: enabled, disabled, forced, adjustable. 
```
