### ISSUE TITLE
Outlaw name change causes Towny to go into safe mode

### ISSUE THREAD

**Issue by jackstrosahl** [TownyAdvanced/Towny#2988]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Make a player an outlaw in a town
2. Player changes name
3. Towny goes into safe mode

### What is the expected output?
1. Make a player an outlaw in a town
2. Player changes name
3. Towny is all good

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.92.0.0 [1.11-1.12.2]

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.12.2-R0.1-Snapshot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

**^^^I'm very sorry for skipping this, I don't have an account to reproduce this bug with, but I believe I've found a mistake in the code, so hear me out please.**

When renaming a resident, in /src/com/palmergames/bukkit/towny/db/TownyDataBaseHandler, the code is this for updating the resident as an outlaw:
```
toCheckTown.removeOutlaw(resident);
toCheckTown.addOutlaw(resident);
```
Should it not be:
```
toCheckTown.removeOutlaw(oldResident);
toCheckTown.addOutlaw(resident);
```
Edit: the line in question is 1013

**Comment by LlmDl** [comment]
Good catch, I'll get this sorted. Thanks.

**Comment by LlmDl** [comment]
And done, this will be a part of 0.92.0.13
