### ISSUE TITLE
Towny data syntax errors and non-existent worlds

### ISSUE THREAD

**Issue by wizrow** [TownyAdvanced/Towny#2994]
Problem description: Iv'e been having trouble with towny recently, mostly dealing with town claiming. This issue has been causing major syntactical errors in the townblocks.txt file, making it difficult to fix and locate through over 100,000 plots. These syntax errors occur only sometimes on a certain line, for example it would say "world, wor-56, 245" or "woNUL NUL NUL...". I'm not sure if the problem is because I'm claiming too fast or just have a lot of plots already claimed. If anyone has solutions to why its causing this problem, it would be greatly appreciated. As well as any tips to make the server start-up time a lot faster when loading towny (I already have town plot snapshots disabled). 

FYI: I have fixed the syntax errors in the problem described above, but I'm afraid this issue will be a reoccurring problem.

Another issue I encountered is described below, where worlds in the worlds file keep being created when they don't even exist.

### What steps will reproduce the problem?
1. World files will be created in the towny/data/worlds. These world files don't exist!
2. Deleting them and restarting the server keeps loading them back into the worlds folder directory.

### What is the expected output?
1. To only have world files that do exsist.

### What is your Towny version?
Towny 0.92.0.0

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/M7BG6MWG
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/gpLJdNGg
3. Your townyperms.yml : https://pastebin.com/337stV8D
4. Your log's error : No log error

**Comment by LlmDl** [comment]
Can you get teh rest of the server startup, the beginning is missing.

**Comment by LlmDl** [comment]
Also, if you could please supply an example file that is corrupted.

**Comment by wizrow** [comment]
The rest of the server start up is just the plugins being enabled and some personal information. The main issue right now that I have is the nonexistent worlds. Here is the worlds file...
![img](https://user-images.githubusercontent.com/23705939/43101744-e965cedc-8e7d-11e8-8837-aaac900f6c9c.PNG)
The world legacy is what I'm working on currently. Worlds such as "egacy", "gacy", "legy", and "lelegacy" are worlds that have never been made before. I'm not sure how to get rid of them, they keep downloading again after a server restart.

As for the claiming issue, I believe I was claiming too quickly. Perhaps claiming areas that are already being processed couldn't handle the queue of the plots already being claimed right after.

**Comment by wizrow** [comment]
Worlds.txt: https://pastebin.com/VCxw9XFf
Console: https://pastebin.com/u2FEQHsj

**Comment by LlmDl** [comment]
Well I'm not sure what would cause you to have extra files, none of them should matter if the worlds.txt file only contains correctly-named worlds anyways. Do you have a plugin which would cause world names to change/become mis-reported in the Bukkit API?

**Comment by LlmDl** [comment]
Can you make it happen at will?

**Comment by LlmDl** [comment]
Assuming this is no longer a problem for you. If it is please comment and I'll reopen it
