### ISSUE TITLE
Suggestion: Claiming plots as other users

### ISSUE THREAD

**Issue by Srborjaa** [TownyAdvanced/Towny#2997]
Hi there!

My suggestion is to add a command to claim a plot as another user. For example, I am User1 and I want User2 to claim some certain plots. So the command that I'm suggesting would do that.

I suggest that because some assistants/mayors evict their residents without following the server rules, and the admins need to reassign the plots again to the previous owner.

Thanks for your attention.

**Comment by LlmDl** [comment]
Is this something that would only be available to server admins/mods?

**Comment by NekoShouta** [comment]
Effectively.

**Comment by LlmDl** [comment]
Completed: https://github.com/TownyAdvanced/Towny/commit/718bd4514c38a5264e71c9d681448232429a2394
