### ISSUE TITLE
Suggestion: Add "/ta town {townname} set and toggle" commands so admins can change toggles and settings for other towns

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3000]
Is there a command that allows you to adjust another towns toggles (PVP, Fire etc) If not I suggest adding it for assisting players and convenience for admins/server developers

**Comment by LlmDl** [comment]
That is not one of the commands I added recently to /ta, it will be added when there's time.

**Comment by axemwa** [comment]
So there isn't a command for that yet, kwl I can stop trying to find it now then... Thanks for the reply :)

**Comment by axemwa** [comment]
Thanx for kicking me from discord all i ask for is help and u go and be rude like that well FUCK YOU TOO of course im gonna be rude back... Jerk!

**Comment by LlmDl** [comment]
Just because you're beligerant and rude on the Discord (which is why you were banned,) doesn't mean I won't consider your ticket, as it is a good suggestion.

**Comment by axemwa** [comment]
We were both being rude, I took it bit too far tho so I deeply apologize, its been a rough 3 days and nights working on my server and helping other server developers fix issues with plugins theyre having trouble with and I haven't slept for those 3 days either and my fuse was short... I'm not normally like this I'm sorry I said all that stuff and I don't hate you, peace.

Also yeah I think this ticket is a good idea too so people don't have to change anything in the database (I don't even know how to change database files etc)

**Comment by LlmDl** [comment]
No hard feelings, in my position I've had a lot of situations like this. The trick is to just stay objective.

**Comment by axemwa** [comment]
And for me to get some proper sleep lol I'm too dedicated

**Comment by axemwa** [comment]
Is it possible to show the town map in scoreboard screen so that it updates in there when players are walking through plots? I think it's a good idea but doesn't sound possible is it?

Also I have another suggestion you might find handy for towny, to make the %s displayname instead of playername for messages like this below

msg_join_town: '&b%s joined the town!'

**Comment by LlmDl** [comment]
Done as of https://github.com/TownyAdvanced/Towny/commit/be61bd42de0f7dfb26ad56324d05c7acf81831eb

Add nationSet/Toggle & townSet/Toggle to /ta abilities.

- New Command /ta town {townname} toggle ....
- New Command /ta town {townname} set ....
- New Command /ta nation {nationname} toggle ....
- New Command /ta nation {nationname} set ....
