### ISSUE TITLE
Claiming mid-revert plots causes original plot snapshot to be thrown away, in place of a brand new snapshot.

### ISSUE THREAD

**Issue by B4TT3RY** [TownyAdvanced/Towny#3001]
### What steps will reproduce the problem?
1.  claim a plot (with snapshot)
2. unclaim a plot
3. turn on "revert on claim"
4. claim a plot before revert done
5. unclaim a plot

### What is the expected output?
1. The snapshot is overwritten and the existing snapshot is lost.
2.  Plot is not returned to its original state because the existing snapshot is overwritten. (Even if you unclaim, existing buildings remain.)

### What is your Towny version?
0.92.0.13

### What is your spigot/craftbukkit version?
git-Paper-1463

(With Google Translator, Sorry for my bad english)

**Comment by LlmDl** [comment]
Tested this finally today (sorry it took so long) and found that a plot which is unclaimed/reclaimed does go back to the original snapshot. Couldn't reproduce this bug.
