### ISSUE TITLE
Set Price for plots in towns = Infinite SQL Query + Infinite Log

### ISSUE THREAD

**Issue by Blackyvk** [TownyAdvanced/Towny#3004]
### What steps will reproduce the problem?
1. config towny with mysql
2. /t set plotprice 10000000000000000000000000000000000000000000000000000000000000000...
   /t set embassyprice 10000000000000000000000000000000000000000000000000000000000000...

I believe anything that lets the player set prices, I think you should check with names aswell...

3. The error spams the console generating a infinite log related to mysql until the server is restarted

### What is the expected output?
1. Cap the number of characters to avoid issues with mysql

### What is your Towny version?
0.92.0.13

### What is your spigot/craftbukkit version?
1.12.2

**Comment by LlmDl** [comment]
The one that was fixed a long time ago as the plot tax right?

**Comment by LlmDl** [comment]
It was, this has now been taken care of for plot, embassy and commercial prices as of 0.92.0.13:

```
    - New Config Option: global_town_settings.maximum_plot_price_cost
      - default: 1000000.0
      - Maximum amount that a town can set their plot, embassy, shop, etc plots' prices to.
      - Setting this higher can be dangerous if you use Towny in a mysql database. Large numbers can become shortened to scientific notation.
```

**Comment by Blackyvk** [comment]
oh if you are adding a global config, could be good to add it to the command /plot fs

https://github.com/ElgarL/Towny/blob/master/src/com/palmergames/bukkit/towny/command/PlotCommand.java#L567

I don't remember if there is another command that add prices.

**Comment by LlmDl** [comment]
Ah yep, good catch.

**Comment by LlmDl** [comment]
We'd actually already had a hard coded cap of 1000000 for the use of that command, but now it will use the config setting:
```
- The previous hard cap of 1000000.00 on the /plot fs command has now been changed to use the maximum_plot_price_cost setting in the config.
```
