### ISSUE TITLE
Claim Problem

### ISSUE THREAD

**Issue by yoDaMeister** [TownyAdvanced/Towny#3005]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Cretate a town, take up a larger area like I go around, so I do not protect every chunk, just round it.
2.
3.

### What is the expected output?
1.My Dyn map, I see not only has the area been protected by what I have clapped, but also with it.
2.However, it did not defend the center of the circle so he could be ruined.
3.Is there any way to protect an area around it, do not just "pinch" it on the dynamic map, but take it out? Thanks in advance!

### What is your Towny version?
Do not say "latest".
0.92.0.0 

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot v1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/kk2A7k6q
3. Your townyperms.yml :https://pastebin.com/jLwivAcq
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Am I correct in guessing that you are asking about the centre of a town which is unclaimed, appearing on your dynmap as though it is claimed? The mayor claimed a circle, or "o" shape of claims while leaving the centre hollow/unclaimed?

**Comment by yoDaMeister** [comment]
I'm claiming a 3x3 cube, but not the middle. (/ t claim). In the end, on the dynamic map, I see that the middle is protecting, but in reality it is not. Obviously, this must be something like this, but I would need it to get the middle of it automatically. Do I have that?
Sorry, I do not know much English.

**Comment by LlmDl** [comment]
I understand you, this is something that the developers of Dynmap-Towny would fix for you. This is not something that Towny is responsible for.

**Comment by yoDaMeister** [comment]
I understand, thank you for your quick answer! Have a nice day!
