### ISSUE TITLE
Hi I want to Use protectionstones   In Towny Claims 

### ISSUE THREAD

**Issue by rotus1122334455** [TownyAdvanced/Towny#3006]
Hi I want to Use protectionstones   In Towny Claims    .  Only Staff will be able to add the protectionstones  .   Is this possible ?

**Comment by LlmDl** [comment]
Server staff or town staff?

**Comment by LlmDl** [comment]
They could create a preciousstones protection area anywhere but towny and preciousstones would clash. If either plugin protected an area and stops a player from doing something, they would be prevented.
