### ISSUE TITLE
Errors spamming the console related to PlayerInteractEvent

### ISSUE THREAD

**Issue by BlueSoapTurtle** [TownyAdvanced/Towny#3007]
### What steps will reproduce the problem?
Using a fresh installation on my towny server, not sure what players are interacting with but the console is being spammed with errors

### What is the expected output?
1. no errors spamming the console

### What is your Towny version?
Towny v0.92.0.12

### What is your spigot/craftbukkit version?
paperclip version 149
https://destroystokyo.com/ci/job/Paper-1.13/149/

### Please use Pastebin.com to link the following files:
Relevant startup logs(There weren't any errors or other things related to towny): https://pastebin.com/NKABXWkk
Towny config: https://pastebin.com/m4NyEQVn
Towny Permissions: https://pastebin.com/TmAGNbdz
Errors: https://pastebin.com/jz2vN3Lb

**Comment by LlmDl** [comment]
Missing a full startup, this is likely caused by a different plugin (which I cannot remember off the top of my head.) Include the full log like the form asks for.

**Comment by BlueSoapTurtle** [comment]
My apologies, https://pastebin.com/CwKPD6sn

**Comment by LlmDl** [comment]
I want to say it was cratereloaded. [ https://www.spigotmc.org/resources/mystery-crate-cratereloaded-free.861/updates ] 
Try updating and if it goes away let me know, otherwise we'll take a good look at it.

**Comment by LlmDl** [comment]
Closing ticket for lack of feedback.
