### ISSUE TITLE
Wilderness regeneration - grass becomes dead bush on regen

### ISSUE THREAD

**Issue by SmallSansSerif** [TownyAdvanced/Towny#3008]
What steps will reproduce the problem?
1. Use a creeper to create a surface explosion in overworld wilderness where grass is growing on the surface. https://imgur.com/w14WN1V
2. Watch Towny regenerate this area. 
3. Observe that the surface grass regenerates as dead bushes, sometimes breaking into sticks. https://imgur.com/1BEQzLX

What is the expected output?
1.  Expected to restore wilderness overworld to it's original state.

What is your Towny version?
Towny version: 0.92.0.12

What is your spigot/craftbukkit version?
Paper version git-Paper-155 (MC: 1.13)

1. Your full server startup from the logs\latest.log : https://pastebin.com/57L1PYAY
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/ncyvNaTJ
3. Your townyperms.yml :  https://pastebin.com/zPQwzBrR

_Related but not same as above as seen on Discord:_

"NesseleyToday at 1:21 AM
1.13 regen is bugged. It doesnt place back stairs the right way, upperslabs go to the ground aswell
You can report it on git, I forgot and aint home rn"

**Comment by LlmDl** [comment]
Found this was not exclusive to using 1.13. LONG_GRASS was left out of the regeneration recode on accident. Now fixed, as part of 0.92.0.13:
```
- Fix long_grass regeneration.
```

**Comment by SmallSansSerif** [comment]
I re-downloaded that build on a different computer to avoid browser caching or anything like that. Tested on the server again and still getting the dead bushes on regen fyi.

**Comment by LlmDl** [comment]
This could be exclusive to 1.13 which I am not testing against. I am going to make another build for you to try, I'll need you to test it and do supply a full server startup with results.

**Comment by LlmDl** [comment]
@SmallSansSerif https://www.dropbox.com/s/lu0n6gtjblfew06/TownySmallSerif.jar?dl=0 use this one please.

**Comment by LlmDl** [comment]
If that one doesn't work try this one: https://www.dropbox.com/s/c8w6qqa27brl58q/TownySmallSerif2.jar?dl=0

**Comment by SmallSansSerif** [comment]
I posted this in response to your '/tw' question in Discord but dropping here so it's all together too.

https://imgur.com/a/CELdMGA

**Comment by LlmDl** [comment]
Ok, I've confirmed this as well as a few other things which don't regenerate properly, so I'll be tracking that in the new ticket. Thanks for finding the tip of the iceberg. 
Follow #3010 for future updates.
