### ISSUE TITLE
TownyChat not working in 1.13

### ISSUE THREAD

**Issue by Ectabro** [TownyAdvanced/Towny#3011]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. ![capture](https://user-images.githubusercontent.com/20256156/44580691-3376e700-a79b-11e8-97f0-1faf2048f70c.PNG)

### What is the expected output?
1. 
![capture](https://user-images.githubusercontent.com/20256156/44580777-86509e80-a79b-11e8-943e-c9b37349fd1b.PNG)

### What is your Towny version?
0.92.0.12 and TownyChat 0.53

### What is your spigot/craftbukkit version?
git-Spigot-fe3ab0d-3418f8d (MC: 1.13)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/ZTunXcpJ I know it's full of bug i'm testing my entire server to 1.13, but no error for towny
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : I don't have any error in my console so...

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/kCha2KrT
7. Your channels.yml : https://pastebin.com/Q5LTNDay

**Comment by LlmDl** [comment]
I haven't had anyone with this issue yet. It could be another chat plugin (which might be one of the plugins erroring in your startup) causing it or it could be that your chatconfig.yml has not been regenerated. We changed the code behind the chatconfig to be like Towny's config.yml that will update automatically. The upgrade process has been fairly smooth but some people's chatconfig's update looking wrong (your comments are at the bottom,) and some people have had their old chatconfig not update properly.
As a first step I would 
- stop the server and rename your chatconfig.yml to oldchatconfig.yml
- start the server and let TC make a new chatconfig.yml
- stop the server and edit your chatconfig.yml's channel_formats to what you have in the oldchatconfig.yml.
- start the server and see if that has fixed your missing formatting.

**Comment by Ectabro** [comment]
I made what you said but nothing happen...

**Comment by LlmDl** [comment]
pastebin.com your new chatconfig.yml please.

**Comment by Ectabro** [comment]
https://pastebin.com/rM2qUmd9

**Comment by Ectabro** [comment]
Okay forgot that.. My fault, it's caused by a new plugin who take control on chat
Sorry for the lost of time !

**Comment by LlmDl** [comment]
That was my suspicion, have fun using 1.13!
