### ISSUE TITLE
Suggestion: Add a new placeholder in PlaceholderAPI which shows which channel the player is in

### ISSUE THREAD

**Issue by iskandarluqman** [TownyAdvanced/Towny#3012]
With this placeholder implemented, we can make custom GUI /channel so the player can choose which channel they want. With the placeholder we can show which channel is the player in so he cant be confused. Please add it . Thanks

**Comment by LlmDl** [comment]
I'm sorry I don't develop the PAPI or it's Towny add-ons.

**Comment by iskandarluqman** [comment]
Can you tell me who is incharge of the add-ons?

**Comment by LlmDl** [comment]
I couldn't say, I don't use PAPI.
