### ISSUE TITLE
BUG: 1.13 - joined player not registered as a resident

### ISSUE THREAD

**Issue by Szikszai60** [TownyAdvanced/Towny#3014]
### What steps will reproduce the problem?
1. Install the latest spigot (1.13 -git-Spigot-fe3ab0d-f41aae4)
2. Install Towny from the site (0.92.0.0 - for 1.10)

### What is the expected output?
Joined player registered as a resident - but they are not registered

### What is your Towny version?
0.92.0.0 - for 1.10+

### What is your spigot/craftbukkit version?
Latest (now) 1.13 Spigot - git-Spigot-fe3ab0d-f41aae4 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/iWJKfxmm
2. Your Towny config.yml: https://pastebin.com/vmTzDPQj
3. Your townyperms.yml : not changed, default, but the link: https://pastebin.com/EfrZdY1B
4. Your log's error : https://pastebin.com/K5re3kGd

**Comment by LlmDl** [comment]
Can you reproduce this error when using the latest dev builds of Towny v0.92.0.13 ?

You can download it here: https://www.dropbox.com/s/e9hi2ykym8430l3/Towny.jar?dl=0

Please start with a default config or read the changelog carefully here: https://git.io/vxiWf
making note of the things you must to do upgrade your config.

**Comment by Szikszai60** [comment]
With a new config it works as it should work. Thanks!

**Comment by LlmDl** [comment]
Strange, those resident errors shouldnt really be possible, but I guess sometimes somehow they do.
