### ISSUE TITLE
Outlaws not respawning in town jail, but instead at bed.

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3015]
### What steps will reproduce the problem?
1. Set person as outlaw
2. Kill person in town land(tested as the mayor of the town)
3. Person respawns at bed spawn.

### What is the expected output?
1. Outlawed person should respawn inside the towns jail

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
spigot 1.13 dev build #2

1. Your full server startup from the logs\latest.log :
https://pastebin.com/w43v9r6C

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/KtC9GF0t

3. Your townyperms.yml :
https://pastebin.com/eSTMnGHz

4. Your log's error : 
None

5. Your permissions file :
I use the plugin LuckPerms. This is the default groups permissions. It contains some towny perms.
https://pastebin.com/aLQhy4ix

PS. There are 2 error messages in my console log. Neither is towny. The first one says teleporting and ambiguity alot. I don't know what that is. The second error message is a chest shop message. I've contacted the dev and he says he doesn't know what causes it, but to ignore it.

PS. This is also my first time using towny, both as an owner, and as a player. I've always used factions, we switched for 1.13. I'm in love so far and it's 10x cooler and 10x more features and everyone should switch its amazing, but some things might not be set up right? If you notice anything looks weird or not permed right, if you want, let me know! =D

**Comment by LlmDl** [comment]
The town does have a jail plot set right?

Can you pastebin your CMI config please, or any other plugin that is affecting your spawning.

**Comment by LlmDl** [comment]
Based on the comments it sounds like when the world isn't in the Specific list it falls back to the PriorityOrder:

"# Defines respawn order if defined world is not present in Specific list"

which contradicts what you see below "# Remove world if you want to leave respawn handling for server or 3rd party plugin"

You could probably test it pretty quickly by removing CMI and seeing what happens. If its the same as what you have now it would rule out CMI.

**Comment by BeeRando** [comment]
Ah I see. My appologise for not noticing that contradiction. After restarting with out CMI, the killed person now respawns at the jail correctly. So CMI is overriding Towny respawn settings.

**Comment by BeeRando** [comment]
After re-adding CMI after the following restart, I now have this error in console. I've seen it before and I've fixed it before, but I don't remember what caused it. I'm sure I can take care of it again, but I'll just leave it here incase it helps.
https://pastebin.com/G8Jjyevr

**Comment by LlmDl** [comment]
I'm guessing that you can tweak the PriorityOrder around? Or maybe there's a way to disable it entirely in a world?

**Comment by LlmDl** [comment]
That error should just be a one-off. If it's persistant please file a new ticket. I'm going to close this one for now. Hopefully you can get your CMI set up satisfactorily. If no solution comes up please leave a new comment and I'll see if I can force it using event priorities.
