### ISSUE TITLE
See the year on "Last Online"

### ISSUE THREAD

**Issue by NekoShouta** [TownyAdvanced/Towny#3016]
Hi there,
My suggestion is to add the year of the last online of a player. So, if I put "/p Jorgin001" I could see the year of his latest connection.

![imagen](https://user-images.githubusercontent.com/29895095/44623187-bb0e4400-a8c8-11e8-9d21-e22859c2497b.png)

I suggest that because we can't know if his last online was on 28/12/2018, 2017, 2016, 2015...

Greetings.

**Comment by LlmDl** [comment]
This is now a thing as of 0.92.0.13:
```
- Make /res status screen show year for LastOnline when the year they were last online is not the current year.
```
