### ISSUE TITLE
/plot fs Replies "you are not Mayor" 1.12.2 PaperSpigot

### ISSUE THREAD

**Issue by Spzatak** [TownyAdvanced/Towny#3017]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Create a town as Permissions rankHellDiver And up
2.claim a second plot, as to be able to have a /plot forsale enabled plot (not home plot)
3.type /plot fs, /plot forsale, /plot nfs, /plot notforsale

### What is the expected output?
1. Chat Says [Towny] You are not the Mayor or an Assistant.  https://gyazo.com/d447c973cf024a92375df83493e9fcd2
2. Other MAyor Commands appear to work in spite of this.
3.

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.92.0.0 [CB/Spigot 1.11-1.12.2]

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperSpigot 1.12.2
Specific release Unspecifiable 

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
https://pastebin.com/88yUf5SL
2. Your Towny config.yml (if using MySQL please remove password,) : 
https://pastebin.com/uVhcU0Zx
3. Your townyperms.yml :
https://pastebin.com/Rw0L4i0x
4. Your log's error : 
No error in log. In chat, https://gyazo.com/d447c973cf024a92375df83493e9fcd2
(optional) If this is to do with permissions, 
5. Your permissions file :
https://pastebin.com/1KU6dW8n
(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

NOTE: the permission node for creating towns is withing the permissions file, rank HellDiver

**Comment by LlmDl** [comment]
```
[19:59:33] <LlmDl> Spzatak: its cause you have not give mayors the towny.command.plot.asmayor node
[19:59:42] <LlmDl> they would have it but you removed towny.command.plot.*
[20:00:36] <LlmDl> I'll still be double checking things, since we probably shouldnt be showing the message when they arent allowed to do it because they're mayors but still able to do it because they have the permission node
```
