### ISSUE TITLE
Town cost $0 even if config says $250 and creates FREE towns if you have the money.

### ISSUE THREAD

**Issue by Nesseley** [TownyAdvanced/Towny#3019]
### What steps will reproduce the problem?
1. Install newest version of Towny and TheNewEconomy
2. Have $0 in your bank
3. Use /t new testname and the town gets created even if price_new_town: '250.0' in config og a new clean setup.
4. The town will get created and no money is taken. (This also works id you have the money, town is still created for free"

### What is the expected output?
1. Towny should tell the player that he needs $250 before he can make a new town.

### What is your Towny version?
Towny version 0.92.0.13

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

This was a clean startup with no changes made to any configs of any plugins. If you really need the files let me know and Il paste them.

**Comment by LlmDl** [comment]
I need the files.

**Comment by Nesseley** [comment]
Your full server startup : https://pastebin.com/qJqPQqjH
Your Towny config.yml : https://pastebin.com/j4WxBiN7
Your townyperms.yml : https://pastebin.com/RnwdhdQY

Hopefully this helps :)

**Comment by Nesseley** [comment]
Your full server startup : https://pastebin.com/F3VSjKVD
Your Towny config.yml  : https://pastebin.com/QhwjbDgM
Your townyperms.yml : https://pastebin.com/tw3irUDq

There you go! :)

**Comment by LlmDl** [comment]
So now with vault it still doesn't work? Maybe you want to use TNE's register (it's a vault replacement, which Towny also supports.)

**Comment by Nesseley** [comment]
It does not work with vault no. Il do a test with this THE's register thingy! :)

**Comment by Momshroom** [comment]
I'd like to confirm that I have this same issue and adding Reserve did not fix it.  Reverting to the pre-release version of Towny from here DID fix it.  When I have the dev release it does not charge me for towns, when I have the prerelease it does.  
I'm using Spigot 1.13, Towny 0.92.0.13 (prerelease (works) or dev version(has issue)) and TNE 1.1.2.

**Comment by Momshroom** [comment]
Here's the changelog: https://pastebin.com/pyhkzPsQ
The jar is showing uploaded to my test server on August 3.

**Comment by LlmDl** [comment]
Looking at it, it might be caused by missing language strings? This can happen when you update to a new version of the same version and the language file doesn't know to add the new strings. Can you try a new language file @Momshroom (just rename or delete your current english.yml and start the server anew.)

**Comment by Momshroom** [comment]
That didn't fix it.
Sorry

**Comment by LlmDl** [comment]
Nearly certain I've fixed this, can you test the build I posted in #new_builds on the discord @Momshroom

**Comment by Momshroom** [comment]
Yes, that fixed it. Ty.

**Comment by LlmDl** [comment]
Probably the dumbest mistake I've made in a while...

This will be out officially as 0.92.0.14 tomorrow:
```
- Fix stupid boolean that made charges not apply for creating a town.
```
