### ISSUE TITLE
Suggestion: Skip updating Last_Online time for hidden players.

### ISSUE THREAD

**Issue by CryinDaily** [TownyAdvanced/Towny#3020]
Hello,

I would like to make a suggestion to add the possibility of excluding people from the command /resident, alias /p.

In the latest versions of EssentialsX, there is a permission "essentials.silentjoin.vanish", so that when you enter the server you are in vanish. Although in the /resident you don't appear online, it does update to the last hour you entered to the server.

In general, I would like some way so that there is no record of that event.

An example:
Last online: Today, 21:25
List from command /list: [Hidden] (this is to show that I entered hidden)
![screenshot_2](https://user-images.githubusercontent.com/27264148/44824182-18501100-abb9-11e8-871e-02acc18ec4eb.png)
![screenshot_3](https://user-images.githubusercontent.com/27264148/44824183-18501100-abb9-11e8-99a7-ee0a494954ed.png)

**Comment by LlmDl** [comment]
We already show hidden players as offline (or at least we used to, inform me if there is an (Online) tag on hidden online players.) It should be easy enough to not update a hidden player's last_online timestamp.

**Comment by LlmDl** [comment]
This is actually a bit tricky, we'll need to support the plugin you use to vanish people. Which one are you using @CryinDaily ?

**Comment by LlmDl** [comment]
Should be working for you when you try it out on 0.92.0.14
```
    - Make it so that players vanished by the plugin Essentials do not have the LastOnline value updated.
      - Note: This means that a player could be deleted by the old-resident-deletion feature.
```
