### ISSUE TITLE
Suggestion: Tab Complete

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TownyAdvanced/Towny#3021]
I would love a improved tab complete for 1.13 of towny

**Comment by LlmDl** [comment]
I think you might need to add what needs to be improved? Can you provide a list?

**Comment by xH3LLRAIZ3Rx** [comment]
like atm you can't tab complete most args, like /t new and /n new

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/issues/3314
