### ISSUE TITLE
Resident rename causes duplicated entries

### ISSUE THREAD

**Issue by Artuto** [TownyAdvanced/Towny#3022]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Let the user join the server with the name changed
2. Make them join the town they were in previously with their old name
3. Do `/ta resident <name> rename <newname>`

### What is the expected output?
1. Do not break

### What is your Towny version?
Do not say "latest".
0.92.0.12

### What is your spigot/craftbukkit version?
Do not say "latest".
This server is running Paper version git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/nusedoloze.md
2. Your Towny config.yml (if using MySQL please remove password,) : I dont think its relevant to this
3. Your townyperms.yml : I dont think its relevant to this
4. Your log's error :  https://hastebin.com/ojiriponuw.sql

**Comment by LlmDl** [comment]
I'm confused, you already run TownyNameUpdater.jar which does this automatically. Why are you using the manual command too?

**Comment by Artuto** [comment]
Well the user notified me they lost all of their claimed plots. So they joined the town and then I tried to rename them.

**Comment by LlmDl** [comment]
Weird, they are listed twice in the town Capital at this point, so it must have renamed them the first time, which should have transferred all their plots. If plots aren't transferring that's probably worthy of its own ticket.

**Comment by Artuto** [comment]
They joined manually to the City using a command. so that also didnt got transferred.

**Comment by LlmDl** [comment]
Also weird. We're working on a new version of TownyNameUpdater which should be faster. Then after we switch to MC 1.13 we'll eventually have a (probably optional) UUID supported database.

**Comment by Artuto** [comment]
Good. Thanks.
