### ISSUE TITLE
 Error when inviting a user to a city

### ISSUE THREAD

**Issue by Mundo-Minecraft** [TownyAdvanced/Towny#3025]
Hi, I have two very strange problems with towny. To rule out my server failure, I created a server from 0 with the latest version of spigot and towny. I let towny generate the files and I do not modify anything. I create a city and invite a user, the user receives the invitation but when accepting towny it indicates that "he has nothing to accept" and nothing happens, no user can join the city.

The second problem is with the config, if I edit any example parameter namePostfix: 'Ruins' by namePostfix: 'Ruins' or simply numResidents: 0 by numResidents: 4 when creating a city and typing / town indicates the following:

https://pastebin.com/1pVkwC1Y

To make sure that it is nothing of my configuration and that is why all the files are just generated by towny, here I detail the versions that I use.

-CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
-Towny versión 0.93.0.0

Greetings and thank you

**Comment by LlmDl** [comment]
Please resubmit and fill out the form.
