### ISSUE TITLE
Console warn on new players joining the server.

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3026]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Have a player join the server for the first time.
2. Console gives a warning that player isn't registered.

### What is the expected output?
1. Player will be registered in towny on join.

### What is your Towny version?
Do not say "latest".
0.92.0.14 dev build

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/mDYCwDBZ
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/KCTt8Hqy
3. Your townyperms.yml :
https://pastebin.com/KaMRjaPK
4. Your log's error : 
https://pastebin.com/kpV4sy06

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Are you using a plugin to move your players to a different world when they join? One that isn't actually the natural spawn for your server?

**Comment by LlmDl** [comment]
It looks like they're being teleported before towny gets to register them. Make your server spawn the place they actually go to and it will go away.

**Comment by LlmDl** [comment]
Youd want to set your spawn world in teh server.properties and use the vanilla set spawn command wherever you are moving them to with MV and CMI. Those plugins are teleporting them to a different world before towny can register someone. Or you can just ignore the error.
