### ISSUE TITLE
Using latest towny, players can claim plots within a WorldGuard region

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3027]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. It's as the title says, for some reason players can claim plots within WG regions is this something I can fix, towny devs can fix or worldguard can fix?
2. I also noticed players can found/create a town within a worldguard region is there a setting for this in config or something worldguard needs to fix/update?

I also made a suggestion to the worldguardextraflags author to add a WG flag that prevents town plots/homes from being claimed/founded for now but thought I'd ask you guys anyway just incase. Although I could just block those specfic commands for that region using WGEF which pretty much works the same

### What is the expected output?
1. All towny ranks/users shouldn't be able to claim a town in a worldguard region

If you make a fix for this too I suggest adding an option in config that allows server owners to set the radius of how far a town plot/home can be claimed/founded from a world guard region, pretty technical but very useful I think so that they cant claim just outside the border that way they can't just keep extending their plots over with region either

### What is your Towny version?
Version: 0.92.0.14

### What is your spigot/craftbukkit version?
Paper version git-Paper-1555 (MC: 1.12.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/TSW8cewS
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/d4vvVr24
3. Your townyperms.yml : https://pastebin.com/pVZ5Zqs6
4. Your log's error : none

(optional) If this is to do with permissions, 
5. Your permissions file : none

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/vWGPHGws
7. Your channels.yml : https://pastebin.com/wYQHGHfr

Reference:
https://github.com/ElgarL/Towny/issues/190#issuecomment-418829030

**Comment by LlmDl** [comment]
I'm sorry, this is not something we plan on implementing. You can make a towny town run by an NPC in your WG regions to keep them from being claimed by normal players. 

"If you make a fix for this too I suggest adding an option in config that allows server owners to set the radius of how far a town plot/home can be claimed/founded from a world guard region, pretty technical but very useful I think so that they cant claim just outside the border that way they can't just keep extending their plots over with region either" There's a ticket for this on here already.

**Comment by axemwa** [comment]
It's ok I've found a better work around, I just use WorldGuards' "blocked-cmds" flag to prevent those commands from being used within the world region, works great!

**Comment by LlmDl** [comment]
That will work until someone does /t claim rect # and then manages to claim inside of the region when they are standing outside it. This is why regions should be claimed.

**Comment by axemwa** [comment]
Ok thanx what if I block /t from being used in regions? Also another topic, do you know if the %s can be changed in english.yml so that it shows the users displayname instead of default name?

'&b%s deposited %s into the %s bank.'

**Comment by LlmDl** [comment]
Blocking the /t command in regions wont stop people from using the multi-claim commands to claim into regions. There's no option atm to use displayname instaed of name in the language strings.

**Comment by axemwa** [comment]
ok I guess I'll have to make an NPC claim the area as you suggested before unless you know all the multi claim commands I would have to block which is easier you think? I'm guessing doing the npc thing as you said. :)

**Comment by axemwa** [comment]
What if you could make it so that towny will recognize WG regions as another town would that be easy to implement wouldn't it? It's just a bit of a pain in the butt having to set up an npc for every region just so others can't claim it that's all
