### ISSUE TITLE
Error modifying congif.yml

### ISSUE THREAD

**Issue by Mundo-Minecraft** [TownyAdvanced/Towny#3028]
### What steps will reproduce the problem?
1. Create a folder with Spigot and start the server
2. in the plugins folder (newly generated) copy essentials, vault,  towny.jar
3. I just modify numResidents: and townBlockLimit: in the first three groups (config.yml).
4. create a city and write for example / town
5. that error in console will be repeated constantly

### What is the expected output?

when writing / town should show me the properties of the city

### What is your spigot/craftbukkit version?

CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

Towny version 0.93.0.0

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/LSuQizMt
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/EzqnfSA6
3. Your townyperms.yml : https://pastebin.com/ag13KXEA
4. Your log's error : https://pastebin.com/DGen2225

Thx.

**Comment by LlmDl** [comment]
Your Town levels are broken. It's a strange quirk but you must have a numResidents: 0 level. You cannot start with 4. Make sure you have a numResidents: 0 level and see if it fixes it.

**Comment by Mundo-Minecraft** [comment]
You're right, I did not think that was why, since on my server the city is configured to start with 4 players since I started towny in 2012. In this way, until 4 users are added to the city, they can not start protecting chunks.

Will Towny have this option available again?

Thank you.

**Comment by LlmDl** [comment]
This has always been the way it is. If you show me the config on your production server I might be able to see how you've been able to do this in the past.

**Comment by Mundo-Minecraft** [comment]
The server of my community has been running since the end of 2010, at the beginning of 2012 I included towny and established that the initial city should have 4 inhabitants. The plugin worked very well, if you did not add the 4 inhabitant did not let protect ground or do anything. I send you the server's config (it's still in version 1.12.2).

https://pastebin.com/LkB8BtKn (I have only modified the database).

Thx

**Comment by LlmDl** [comment]
I thought this would be the case and it is, you can do this on your production server because of this:
```
  # The maximum townblocks available to a town is (numResidents * ratio).
  # Setting this value to 0 will instead use the level based jump values determined in the town level config.
  town_block_ratio: '0'
```
When that is anything other than 0 it will cause errors like what you see above. When it is zero, the townlevels dictate how many townblocks are given to a town.
