### ISSUE TITLE
Jailed re spawn follow up

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3030]
This is a follow up to an issue I reported that we discussed earlier.
https://github.com/TownyAdvanced/Towny/issues/3015

I don't know when the CMI dev will fix the issue. It's been a week or two now since I opened a ticket to him about the issue. He's got many opened tickets, and has become less active lately, I'd guess due to school since the summer is over now. Could you add an override to fix attackers not respawning at the town jail when killed, due to the CMI plugin?

**Comment by LlmDl** [comment]
Try it out using this build for me: https://www.dropbox.com/s/ta0ccijdrz1l0tg/Towny%20beerando.jar?dl=0

Note that it is newer than 0.93.0.0 so you should update to 0.93.0.0 before using this build so you can see the changelog.

**Comment by BeeRando** [comment]
After updating to 0.93.0.0 from 0.92.0.0, towny no longer works, and I now get this error in console.
https://pastebin.com/DDGCRKM2
I'm on 1.13.1

**Comment by BeeRando** [comment]
Sorry for the delay. I had never updated towny before. I'm a new user. going 92 - 93 confused me on why it wasnt working, i figured it out tho. 
The new jar works and outlaws now respawn at the town jail, and people at their town spawn!

**Comment by LlmDl** [comment]
Alright, good to hear. It was just a matter of moving the respawn of jailed players to a higher priority than normal. Thanks for following up with me, this is good to clear up as CMI is getting more popular.
