### ISSUE TITLE
Trident disappears if thrown at someone in a town with pvp off

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3034]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Make a town with pvp toggled off.
2. Throw a trident at someone inside the town.
3. Trident bounces off them, sticks in the ground briefly, then disappears.

### What is the expected output?
1. Trident should bounce off, but remain in the ground.
2.
3.

### What is your Towny version?
Do not say "latest".
towny momshroom2.jar
(./towny version reports 0.93.0.0)
### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/FLT0yFy6

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/dpnqW6Ft

3. Your townyperms.yml :
https://pastebin.com/JzC6MRbf

4. Your log's error : 
None

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Momshroom** [comment]
Just confirming that I have this same issue on the latest discord pre-release towny version:
0.93.1.0

**Comment by LlmDl** [comment]
Awaiting feedback using 0.93.0.4

**Comment by Momshroom** [comment]
It seems fixed. Ty.

**Comment by LlmDl** [comment]
Thanks for the confirmation.

**Comment by AustinGarrettRichards** [comment]
This is still an issue on all current versions.

**Comment by LlmDl** [comment]
@AustinGarrettRichards are you using 0.93.1.0 PR 2? ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf
