### ISSUE TITLE
Suggestion: Resident teleportation

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#3036]
I'd like to see towny support player to player teleportation with the ability set limits based on town, nation and alliances. For example players only being able to teleport to other town members.

**Comment by LlmDl** [comment]
> An option in the config to enable town and nation tpa.
> 
> Enabling it for town means you can do /t tpa name, to tp to someone from your town
> Enabling it for nations means you can do /n tpa name, to tp to anyone whos a member of your nation
> 
> Along with a cost for both options, with the option to make the payments either to the person they tpd to, or the server and dissapear
> 
> and tpa timer option, like, stay still for 30 seconds,
> and cooldown option, like, you cant tpa again for 2 minutes

Above comes from the duplicate ticket #3063

**Comment by LlmDl** [comment]
> Currently, many players tp to each other via base plugins such as essentials and/or CMI. The issue with these plugins is that they do not take into account towny when they do this.
> 
> This leads to something called "spawn trapping" where players will switch the PVP settings in the plot their tp'ing a person to, to enable PVP and subsequently kill the player. I believe that if we add a resident teleportation system via towny, then this problem can be helped a lot. In addition, you can assign special permissions for teleporting for example instant teleport to allies but cooldown teleport for other players.
> 
> ### Implementation
> * `/r tp <resident>` - Teleports to the given resident (should only be given to admins)
> * `/r tpa <resident>` - Asks to teleport a resident to another resident.
> * `/r tpahere <resident>` - Asks resident to tp to the senders currently location.
>   
>   * The resident receiving the teleportation offer gets this confirmation:
>     ```
>     [Towny] Resident bob would like you to teleport to them in townblock (1, 2), 
>          bob has PVP control in this townblock (potentially unsafe) are you sure you want to continue?
>     [Click to Accept]
>     [Click to Deny]
>     ```
>   * If bob is teleporting you to the wild and/or another block they don't have control of, the warning part of the confirmation will be omitted.
> 
> #### New Permissions
> * `resident.tpa.*` - Allow teleportation to all kinds of residents.
> * `resident.tpa.ally`- Only allow teleportation to allies.
> * `resident.tpa.townmember` - Only allow teleportation to town members.
> 
> In addition to these, there would preferably be cooldown perm nodes for each of the nodes listed above.

Above comes form the duplicate ticket #4571
