### ISSUE TITLE
Suggestion: EULA Message

### ISSUE THREAD

**Issue by BenRulez** [TownyAdvanced/Towny#3038]
PLEASE can you make it so people can remove the EULA message with town blocks?
My vote crate gives people town blocks as a custom item, to actually redeem to townblocks they right click said item and each item gives +1 block.
The issue is that everytime people use this custom item (that they pay no money for, my server doesnt sell ANY in game perks, not even just a title) they get spammed, their town members get spammed and the console gets spammed.

Its really annyoing.

**Comment by LlmDl** [comment]
Not what you want to hear but: If you had the item give it to the player by their name (instead of the player's town) it would only spam the player.
