### ISSUE TITLE
version: 0.93.0.0  [Towny] Error could not read (language: russian.yml)

### ISSUE THREAD

**Issue by Chypik** [TownyAdvanced/Towny#3040]
version:
   # This is the current version of Towny. Please do not edit.
   version: 0.93.0.0
   # This is for showing the changelog on updates. Please do not edit.
   last_run_version: 0.93.0.0
   # Minimum required version of CraftBukkit. Please do not edit.
   bukkit_version: '2918'
   # The language file you want to use
   language: russian.yml

This server is running CraftBukkit version of git-Spigot-2440e18-4228a56 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

[Towny] Error could not read

[latest.log](https://github.com/TownyAdvanced/Towny/files/2404326/latest.log)

**Comment by Chypik** [comment]
> version:
>    # This is the current version of Towny. Please do not edit.
>    version: 0.93.0.0
>    # This is for showing the changelog on updates. Please do not edit.
>    last_run_version: 0.93.0.0
>    # Minimum required version of CraftBukkit. Please do not edit.
>    bukkit_version: '2918'
>    # The language file you want to use
>    language: russian.yml
> 
> This server is running CraftBukkit version of git-Spigot-2440e18-4228a56 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
> 
> [Towny] Error could not read
> 
> [latest.log](https://github.com/TownyAdvanced/Towny/files/2404326/latest.log)

**Comment by LlmDl** [comment]
Delete your russian.yml and let towny make a new one. If you still have problems, file a new ticket and don't skip the form. Include your russian.yml.

**Comment by Chypik** [comment]
deleted the file (language: russian.yml) launched the server. Without changes
