### ISSUE TITLE
Suggestion: TownResidentRankChangeEvent

### ISSUE THREAD

**Issue by Artuto** [TownyAdvanced/Towny#3041]
Would be nice an Event for when a Resident is added or removed from a Town rank.

**Comment by LlmDl** [comment]
Is this something you would want to be cancellable, or just to be notified when it happens?

**Comment by Artuto** [comment]
To notify me.

**Comment by LlmDl** [comment]
Going to leave this open until I can get this commit: https://github.com/TownyAdvanced/Towny/commit/99f9c3946ff0922f6b9aa7c99bd166a809083a36

into the other branches.

**Comment by Artuto** [comment]
Update of this reaching 1.13 branch? Need it for my server...

**Comment by LlmDl** [comment]
This got done.
