### ISSUE TITLE
Suggestion: Keep xp/inventory on death seperate in config

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3045]
I really like the idea of being able to keep xp on death in your own town land. However, enabling this feature in the config also means the player keeps their entire inventory. I can't enable this as it'd just totally break pvp. Could we have these two options separated? A keep xp on death, and keep inventory on death in claimed land?

**Comment by LlmDl** [comment]
I thought they were separate, maybe we broke something. I'm sure they were initially separate config options.

**Comment by LlmDl** [comment]
Yep, this was just a mistyping in the confignodes source. 
Fixed version here with both relevant settings:
https://cdn.discordapp.com/attachments/321710042091094026/494283411738066974/Towny.jar
