### ISSUE TITLE
Recheck that oak doors are working as switches in 1.13 builds

### ISSUE THREAD

**Issue by MamaBeau** [TownyAdvanced/Towny#3046]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Place Doors, trapped doors, item frames and/or shulker boxes in a town claim.
2. Have another member try to use these items.
3. See that other members can use all items within a protected area.

### What is the expected output?
1. Change protections tp protect doors, trapped doors, shulker boxes and item frames.
2.
3.

### What is your Towny version?
Do not say "latest".
0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : My latest.log is too long to paste into Pastebin.com and hastebin.com - Website crashes everytime I try.
2. Your Towny config.yml (if using MySQL please remove password,) :  [https://pastebin.com/qHrpiGLR](https://pastebin.com/qHrpiGLR)
3. Your townyperms.yml :   [https://pastebin.com/Zma2sKnH](https://pastebin.com/Zma2sKnH)
4. Your log's error :  None

(optional) If this is to do with permissions, 
5. Your permissions file :  

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
If you'd like you can test this out on my pre-release version for 1.13. Please let me know if any of the above blocks are still unprotected.

**Comment by MamaBeau** [comment]
Thanks!
I have tested on 0.93.0.2 heres my results:

All doors accept "Oak Door" are protected (Cannot be opened) Oak Doors can be opened.
All Trapped doors can be opened.
Item frames can be changed, as in they can turn the item in the frame.
Shulkers are protected
Chests are protected

**Comment by LlmDl** [comment]
The oak doors is probably just me forgetting to change the old door to the new door in the default config, or your config not being updated to include the oak door in the switch list. (It used to be called door.) Same goes for the trapped doors, but I know I added them. Can you try either deleting the old config or just deleting the old switch id list in the config. Removing the whole line from the config will readd the new default switch id list when you start back up.

Itemframe spinning is something I think that has been an issue that went unreported for a while now but I never remember to fix.

**Comment by MamaBeau** [comment]
Deleted the config and restarted. Everything is protected, except item frame moving of course. If you ever get that fixed shoot me a message. And thanks for being so fast to respond and get this stuff fixed!

**Comment by LlmDl** [comment]
> There is a similar problem in 1.12.2 with the 0.93.0.0 build, which allows players from other towns to place any shulker box on another town and after it's placed they keep it in their inventory(duplication bug), and the shulker box on the ground is buggy, can't be removed without using worldedit.

I don't think that's Towny causing it, and if you could prove it you should make a new ticket for it.

**Comment by LlmDl** [comment]
@MamaBeau Thanks, I'm starting a new ticket for the frame thing: https://github.com/TownyAdvanced/Towny/issues/3054
