### ISSUE TITLE
Suggestion: Town sets tp cost

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3047]
I think it'd be cool if towns could set their own cost on tp features, such as /t spawn, or /t spawn othertown, rather than just a set cost in the config. Just like how each town can set their own taxes with /t set taxes. These commands could be /t set homecost 5, and /t set publiccost 15. 

One town may want to tax its members a small fee for using /t spawn, others might not. Some might want their public town to have a fee of lets say 5 coin, others might want it at 15, or 20. This would just add way more customization for towns.

**Comment by LlmDl** [comment]
Added in 0.92.0.12:
```    - New Command: /t set spawncost {amount}
      - Enables mayors to set their town's spawn cost to anything equal to or lesser than the public spawn cost set in the config.
      - Requires towny.command.town.set.spawncost permission node to use. 
    - New Command: /n set spawncost {amount}
      - Enables kings to set their nation's spawn cost to anything equal to or lesser than the public spawn cost set in the config.
      - Requires towny.command.nation.set.spawncost permission node to use.```
