### ISSUE TITLE
Suggestion: Bank plot exclusive

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3048]
I like the idea of only being able to deposit/withdraw town funds from a bank plot, but making the home plot be included in this makes the bank plot idea kind of worthless. Why go to the bank plot to withdraw/deposit funds to the town, if I can just /t spawn, and do it there.

Would it be possible to make it so that once a bank plot has been made, it then disables the bank features from home plot? Or just exclusively a bank plot period?

I'd like to make a cool bank for my town, but no ones going to use it if they can just do money stuff at the home plot.

**Comment by LlmDl** [comment]
> Why go to the bank plot to withdraw/deposit funds to the town, if I can just /t spawn, and do it there.

Because when a town is first founded they cannot claim anything new until they deposit money.

> Would it be possible to make it so that once a bank plot has been made, it then disables the bank features from home plot?

Possible yes, but slow. We would have to check if all of the town's plots to see if one is a bank plot if the player tried to deposit in the home block.
