### ISSUE TITLE
With these settings, I can not break, the plug protects any (0.93.0.0)

### ISSUE THREAD

**Issue by Chypik** [TownyAdvanced/Towny#3050]
I can not understand how to do in a wasteland to break a certain block of ore. The plugin should have such an opportunity as I understood.
That is, a player without a city can break only a certain list of blocks around the world. How to do it?

version:
   This is the current version of Towny.  Please do not edit.
  version: 0.93.0.0
   This is for showing the changelog on updates.  Please do not edit.
  last_run_version: 0.93.0.0
   Minimum required version of CraftBukkit.  Please do not edit.
  bukkit_version: '2918'

minecraft 1.13.1

`    True to attempt to use GroupManager, PEX, bPermissions, Permissions2/3 or BukkitPerms
     False to disable permission checks and rely on Towny settings.
    using_permissions: 'false'`

`# Unclaimed Zone settings.
unclaimedZoneBuild=false
unclaimedZoneDestroy=false
unclaimedZoneSwitch=true
unclaimedZoneItemUse=true
unclaimedZoneName=Wilderness

# The following settings are only used if you are not using any permissions provider plugin
unclaimedZoneIgnoreIds=SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LEAVES,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,LOG_2,VINE,NETHER_WARTS,COCOA`
With these settings, I can not break, the plug protects any!

**Comment by LlmDl** [comment]
This issue may be already fixed when you use the proper 1.13 version of Towny. I will test it.

**Comment by Chypik** [comment]
I look forward to continuing the development of the plugin for 1.13 so that players can play on this new version

**Comment by LlmDl** [comment]
Please test using the 0.93.1.0 prerelease that is in the new_builds channel on the discord.
