### ISSUE TITLE
Error Load TOWNY (Cannot run plugin)

### ISSUE THREAD

**Issue by DragonSurvival** [TownyAdvanced/Towny#3052]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Cannot run plugin
2.
3.

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Do not say "latest".
0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Yy1ZrAvJ
3. Your townyperms.yml : https://hastebin.com/vufobavegi.php
4. Your log's error : https://hastebin.com/epahehuxuw.sql

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
The towns  WAF.Noob and SurvivalTeam both think that §cTBNRguest is a member.  Stop the server and find the towny\data\residents\§cTBNRguest.txt file and see which town he is in, remove him from the other town.

**Comment by DragonSurvival** [comment]
Hello, I can't find it in the file

**Comment by LlmDl** [comment]
Do you have a towny\data\residents\TBNRguest.txt  ?

**Comment by DragonSurvival** [comment]
No

**Comment by DragonSurvival** [comment]
It does not exist

**Comment by DragonSurvival** [comment]
Please help me

**Comment by DragonSurvival** [comment]
Hello, Are you still there?

**Comment by DragonSurvival** [comment]
is now 2am, you can help me? :((

**Comment by DragonSurvival** [comment]
support me please

**Comment by LlmDl** [comment]
You need to learn some patience. There has to be a file for the resident, is he listed in the towny\data\residents.txt file?
