### ISSUE TITLE
Pumpkin and Melon not breakable on farm plots even when added to config

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3056]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Add pumpkin and melon to the config as items breakable on farm plots
2. turn on perms on a farm plot
3. Have someone try to break them: it won't work.

### What is the expected output?
1. I would expect that with pumpkins and melons enabled in the config players with perms would be able to break them, they can't.
2.
3.

### What is your Towny version?
Discord pre-release towny version:
0.93.1.0

### What is your spigot/craftbukkit version?
1.13.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/b1fu4L1E
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cgHJeuEg (I have multiple names for some of them as I kept trying to add things.  Players CAN break the stem, just not the pumpkin/melon itself.  I kept thinking I must have the blocks named wrong, but the 1.13 names do seem to be PUMPKIN and MELON)
3. Your townyperms.yml : https://pastebin.com/7UyAYA6F
4. Your log's error : There is no error

(optional) If this is to do with permissions, 
5. Your permissions file : 
default group permissions: https://pastebin.com/s05chJKr
towny builder global group permissions: https://pastebin.com/kyy2pcA9
The other inherited global groups have no towny perms in them.
(optional) If this is to do with chat,
6. Your chatconfig.yml : 
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your startup and config both say 0.93.0.0. I'm guessing that if this were tested using the 1.13 builds that it would be already fixed. They probably just renamed the pumpkin and melon blocks.

**Comment by Momshroom** [comment]
They did, but PUMPKIN and MELON are the new names as far as I can tell.

**Comment by Articdive** [comment]
This is probably because we aren't compiling with 1.13 bukkit yet

**Comment by LlmDl** [comment]
Should be good as of 0.93.1.0
