### ISSUE TITLE
Players are able to put themselves into chats they don't have permssion for and speak in, but not read them.

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3057]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Create a towny chat channel.  (in our case admin and mod channels)
2. Have some groups without permission for it.
3. Have a permissionless player toggle that chat channel on. (for our channels have the player type /m (or /ad) then enter to get into the chat.)
4. The player's chat will now appear in the channels they don't have access to.  They will not be able to read it.

### What is the expected output?
1. It is expected that players will not be able to enter chats they don't have permission for.
2.
3.

What is your Towny version?

Discord pre-release towny version:
0.93.1.0
What is your spigot/craftbukkit version?

1.13.1
Please use Pastebin.com to link the following files:

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

    Your full server startup from the logs\latest.log : https://pastebin.com/b1fu4L1E
    Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cgHJeuEg 
    Your townyperms.yml : https://pastebin.com/7UyAYA6F
    Your log's error : There is no error

(optional) If this is to do with permissions,
5. Your permissions file :
default group permissions: https://pastebin.com/s05chJKr
towny builder global group permissions: https://pastebin.com/kyy2pcA9
The other inherited global groups have no towny perms in them.
(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/WzuLX9ax
7. Your channels.yml : https://pastebin.com/HT1u2xYK

**Comment by PetrichorCraft** [comment]
I can confirm that I have this as well.

Minecraft version: 1.13.2
Towny Version: 0.93.0.0
TownyChat Version: 0.53
Towny Config.yml: https://pastebin.com/y3UALH0E
Towny ChatConfig.yml: https://pastebin.com/kNh3DvnE
Towny Channels.yml: https://pastebin.com/MCyEdzpX
Towny townyperms.yml: https://pastebin.com/8Ngj7hwY
Permissions: https://pastebin.com/BpL3AJug

**Comment by LlmDl** [comment]
@PetrichorCraft which permission plugin is that?

**Comment by PetrichorCraft** [comment]
My bad, I should have said that, sorry. It's PermissionsEx.

**Comment by MrWardy** [comment]
@LlmDl This post was made in October? Is it still a bug?

**Comment by creatorfromhell** [comment]
This still occurs on EarthMC.

**Comment by MrWardy** [comment]
> This still occurs on EarthMC.

Still occurs on my server too, although I discovered this bug only yesterday, but I see it's been a bug since several months ago.

**Comment by LlmDl** [comment]
@MrWardy yes it's still a bug, I have been quite busy IRL, it shouldn't be hard to fix when I do get the chance.

**Comment by MrWardy** [comment]
Okay, thanks.

**Comment by LlmDl** [comment]
Just leaving some notes here, don't mind me:

[08:22:44] <LlmDl^> ok I'm not sure but I think it's happening via the ChannelJoinAliasCommand.java  in TownyChat
[08:23:38] <LlmDl^> line 64 we're setting a mode for the chat without testing for the permission node, which we are doing in townychat's channelCommand on line 383 
[08:25:03] <LlmDl^> yeah the plugin.getTowny().setPlayerMode we call doesn't look at permission nodes at all, so I think that's the failing

**Comment by Articdive** [comment]
I can do this one once my other PR is accepted, don't want to do any merging on my system, it's still broken for me

**Comment by neglected18** [comment]
There is still some bugs

**Comment by neglected18** [comment]
Players can type text in /a /mod etc. 
but they dont have permissions for it

Minecraft version: 1.12.2
Towny Version: 0.93.0.0
TownyChat Version: 0.53
Towny Config.yml: https://pastebin.com/d9EsSggp
Towny ChatConfig.yml: https://pastebin.com/ZMLvvGC7
Towny Channels.yml: https://pastebin.com/iPQxQhTk
Towny townyperms.yml: https://pastebin.com/u9adfTg6
Permissions: https://pastebin.com/dkHpwRgS (PermissionEx)

**Comment by neglected18** [comment]
![2019-07-12_13 59 19](https://user-images.githubusercontent.com/45654141/61120152-5989a080-a4ad-11e9-92fd-e64843902f4e.png)

**Comment by LlmDl** [comment]
It was fixed in a later version of Towny. There is no build for 1.12 that has the fix for it.
