### ISSUE TITLE
Town rank changes for offline players are not saved after restart

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3059]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Promote or demote a player within a town
2. Towny says it did the promotion or demotion but ALSO tells you the player is offline: http://prntscr.com/l24hku. /t reflects the rank change properly. http://prntscr.com/l24l3d
3.  Restart the server:  /t will now show the player with the rank they had before you did anything.
http://prntscr.com/l24k1l

### What is the expected output?
1. It's expected that towny will remember rank changes across restarts even for offline players.
2.
3.

What is your Towny version?

Discord pre-release towny version:
0.93.1.0
What is your spigot/craftbukkit version?

1.13.1
Please use Pastebin.com to link the following files:

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

    Your full server startup from the logs\latest.log : https://pastebin.com/b1fu4L1E
    Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cgHJeuEg 
    Your townyperms.yml : https://pastebin.com/7UyAYA6F
    Your log's error : There is no error

(optional) If this is to do with permissions,
5. Your permissions file :
default group permissions: https://pastebin.com/s05chJKr
towny builder global group permissions: https://pastebin.com/kyy2pcA9
The other inherited global groups have no towny perms in them.
(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Blackyvk** [comment]
I think something similar to this also happens when a player buys a plot, after a restart he loses the plots it's like the database is not saving.

**Comment by LlmDl** [comment]
@Blackyvk file a separate ticket.

**Comment by LlmDl** [comment]
Fixed as of 0.93.1.0

**Comment by RubenStryker** [comment]
Where can download this version 0.93.1.0 ?
