### ISSUE TITLE
Suggestion: Revert spawning priority change for CMI (fixed on their end now.)

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3060]
A while ago I made the post about how CMI overrides towny. The CMI dev has returned from innactivity, and fixed the described issue. CMI can now properly disable respawn handling, and leave it to other plugins. The Towny override has had a few little bugs since it overrides all other plugin settings, like not making people spawn at the proper first spawn position, when they join the sever for the first time. Can we disable the towny override option, or make it a true/false option in config?

**Comment by LlmDl** [comment]
I can just return it to the way it used to be.

**Comment by LlmDl** [comment]
I looked it over and as far as I can tell there shouldn't be any issue with us moving new players. Have you got players being added to a default town using Towny's config option?

**Comment by BeeRando** [comment]
No I don't. Should I? I'm using CMI still and since I added the new towny version that overrides the old issue cmi had, players don't spawn where I've set them to spawn with cmi, when they join the server for the first time ever.

**Comment by LlmDl** [comment]
Have you tried moving the vanilla minecraft server spawn?

Does Towny generate a null resident error when a player joins?

**Comment by Momshroom** [comment]
My new players are also being spawned in on the wrong place now... it
hadn’t occurred to me Towny might be involved.  I’m also using CMI.  Atm,
players are showing up at the nether world spawn....  occasionally people
are also respawning in the wrong location.

**Comment by LlmDl** [comment]
Not sure if this is still happening. Not sure if it has to do with where the vanilla spawn point is.
