### ISSUE TITLE
Suggestion: Unclaim refund

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3062]
A setting in the config to set a refund price for unclaiming land.

**Comment by LlmDl** [comment]
I can do this but you should know it can be abusable. If there's no permanent cost to claiming then players can claim in long bridges to other areas, unclaiming behind themselves and gain free outposts.

**Comment by LlmDl** [comment]
Yeah, I'll be adding it with a default amount of 0, if it's set higher they will get that amount. The comments in the config will warn against setting the refund price at the same amount that claiming costs.

**Comment by LlmDl** [comment]
Completed as of https://github.com/TownyAdvanced/Towny/commit/ac7d9678791c04236e9c5e6dda6ef996efd3b45b

This will be a part of 0.94.0.4 when it is out.
