### ISSUE TITLE
Suggestion: Add an outpost range limit

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3065]
Basically a config option which limits how far away from your own townblocks you can place an outpost. We don't want outposts to be able to be placed on the other side of the world, just in the general vicinity of the town.

**Comment by Twitchyyy** [comment]
It would allow for more strategic town placement and expansion tbh. From a game design standpoint, especially on an Earth Map, it makes a lot of sense.
