### ISSUE TITLE
Town Bank money disappearances 

### ISSUE THREAD

**Issue by MamaBeau** [TownyAdvanced/Towny#3083]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. No Steps, cannot reproduce.
2.
3.

### What is the expected output?
1. 
2.
3.

### What is your Towny version?
Do not say "latest".
0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : (Too long to paste/hastebin)
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/diwadopiqo.coffeescript. 
3:Your townyperms.yml :
https://hastebin.com/tutevujuyi.php. 
Your log's error : NONE
(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

ISSUE: Last night, player logged out with 10mil in their town bank, many of my staff members confirmed the amount. 
When they logged on this morning at 1am all their money in their bank (10mil) was suddenly gone. I went through the logs from all of yesterday and today and could not find anything about the Mayor withdrawing 10mil, also she did not claim enough land to equal 10mil and the daily taxes for the town were only 15k.

This has apparently happened before with other players, but it wasn't such a large amount and we ignored it and moved on. Those players reported all the money from their bank disappearing.

**Comment by LlmDl** [comment]
You left out the startup but I can bet you use essentials economy, which is known to do this. Sadly nothing Towny can do until they fix it.

**Comment by MamaBeau** [comment]
I don't understand how Essentials is known to do this when I've spoken to MANY other server owners that have never heard of this issue and they use Essentials Eco with the plugin.
