### ISSUE TITLE
Question: How can I get Towny bonuses working?

### ISSUE THREAD

**Issue by AshtonMemer** [TownyAdvanced/Towny#3084]
When somebody runs /town bonus buy (amount), nothing happens. No output, error, or anything.

I want players to be able to pay to get more land, so it is not all based on town members. How is this possible? Is there a reason that the command is giving no feedback? Thanks!

**Comment by LlmDl** [comment]
You need to enable it in the config:
  # Limits the maximum amount of bonus blocks a town can buy.
  max_purchased_blocks: '0'

**Comment by AshtonMemer** [comment]
> You need to enable it in the config:
> 
> # Limits the maximum amount of bonus blocks a town can buy.
> max_purchased_blocks: '0'

Awesome, got it working. Thanks a lot!
