### ISSUE TITLE
Suggestion: Add /res friend list as an actual list showing which towny residents' friends are online or offline

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3088]
It's as the title says I suggest adding an actual friends list instead of just the add remove and clear arguments so that players know who's on their list.

**Comment by LlmDl** [comment]
Added as of https://github.com/TownyAdvanced/Towny/commit/cf0f0e7fd095e7ea6ad05393acf75fef85d9fa86
