### ISSUE TITLE
Suggestion: Town invite range

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3089]
It would be nice to make it so players could only be invited if they are within a certain range from the town homeblock. We will not have any player teleporting aside from /res spawn and /t spawn so it could help against people joining towns just to teleport to the other side of the world. It could work similarly as to how the current nation invite range handles for towns.

**Comment by LlmDl** [comment]
Added as of https://github.com/TownyAdvanced/Towny/commit/fd2c12d308d1813be5e5903c334393d00ca82baf will be a part of 0.95.0.2
