### ISSUE TITLE
Massive lag on toggling /plot perm hud

### ISSUE THREAD

**Issue by NorbiPeti** [TownyAdvanced/Towny#3090]
As a test, first I executed /plot perm hud and then /gc directly after (on a server only I was on) and the server froze, the attached log shows 26 seconds between the two commands. Subsequent calls of the command only took around 2 seconds but that's still relatively slow.

### What steps will reproduce the problem?
1. Do /plot perm hud

### What is the expected output?
The HUD is opened without lag.

### What is your Towny version?
The issue occurs both on 0.92.0.0 and 0.93.0.0.

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/WLWHsbet
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/ZbZP891u
3. Your townyperms.yml: https://pastebin.com/My2YCGZ6
4. Your log's error: -

(optional) If this is to do with permissions, 
5. Your permissions file: -

(optional) If this is to do with chat,
6. Your chatconfig.yml: -
7. Your channels.yml: -

#2919

**Comment by LlmDl** [comment]
So I recently got rid of a bunch of deprecated code in the Hud systems, be curious to see if you still have this issue. 0.94.0.12 or newer has the changes.

**Comment by LlmDl** [comment]
Closing this ticket. If there is still a problem after the re-write in 0.94.0.12 then there can be a new ticket submitted.
