### ISSUE TITLE
Suggestion: Wilderness max/min Y

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3092]
In the config, we're able to set what blocks people can break in the wilderness. Could we also get a max/min y height for wilderness grief? So for example, we could set 
id
stone
max height: 64
min height: 0

This could be block specific, or just applied to all id's if its easier. So people could mine stone, but not destroy mountains, custom terrain, or anything else above or below that height.

**Comment by LlmDl** [comment]
This is going to have to be denied. The way we keep towny as light-weight as possible is by using a cache to determine if a player do X action to Y block in the townblock they're in.  We only have to actually test things when the cache needs to be updated for a new type of block or action.

One thing that the cache does not care about is height.  This is something that could be made with the TownyAPI but it's still not a very smart thing to do performance wise.
