### ISSUE TITLE
allow_nation_spawn_travel_ally=true gives error message "nation is no public"

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#3095]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Create two nations
2. Config: 
capital_spawn: 'true'
allow_nation_spawn: 'true'
allow_nation_spawn_travel: 'false' (this might should not override below option)
allow_nation_spawn_travel_ally: 'true'
3. Ally other nation
4. Run command /n spawn alliednationname
5. Gives error message "town is not public"

### What is the expected output?
I try to set up the server so that players can teleport to their town, capital and allies capitals only. Players should be able to teleport to the allied capital regardless of their public status.

### What is your Towny version?
Towny version 0.93.0.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-375 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Towny starts without errors. Hooked in to vault. I'd like for full startup to be anonymouse. Can send in discord pm if you wish.
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/vekotapepa.coffeescript
3. Your townyperms.yml : https://hastebin.com/ovijuwacin.cs
4. Your log's error : No error log

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Phyther** [comment]
Out of curiosity, are you trying to /t spawn allynationname 
or
/t spawn allynationcapitalname
?

**Comment by LlmDl** [comment]
Looked over the code and it appears you might just be missing the permission node to use nation ally spawning. Try adding towny.nation.spawn.ally to the nations.default section of the townyperms.yml

**Comment by FixTheAdmin** [comment]
Thanks! It's working now.
