### ISSUE TITLE
Residents can disband a nation

### ISSUE THREAD

**Issue by ipozow** [TownyAdvanced/Towny#3097]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Create a town
2. Add residents
3. Create a nation
4. Let a resident write /n leave
5. Watch the nation being disbanded

### What is the expected output?
4. You don't have permission to do that.

### What is your Towny version?

0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
CraftBukkit version git-Spigot-eb21557-4a47be6 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/ks26hLaq
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/icPJgzsr
3. Your townyperms.yml : https://pastebin.com/RtVg6uHs
4. Your log's error : [08:52:24] [Server thread/INFO]: {nick} issued server command: /n leave
[08:52:24] [Server thread/INFO]: [Global Msg] The nation Name was disbanded!

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/Wa4PZbBT

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Remove     - towny.command.nation.leave from your Jugador group.

Also remove: 
- towny.command.town.* from Jugadora

These nodes are already properly given out in the Townyperms.yml file.
