### ISSUE TITLE
Feature: Change to deny_bed_use

### ISSUE THREAD

**Issue by Phyther** [TownyAdvanced/Towny#3099]
Can we either have a seperate setting:
allow_sleeping:
or change the way deny_bed_use: works?
Right now, players can't setup a bed in the wild and sleep in it. I would like them to have this ability, while not necessarily setting their spawn.

**Comment by LlmDl** [comment]
Dug into this and we cannot do it as there is no actual PlayerChangeSpawnEvent for us to cancel.
