### ISSUE TITLE
PlayerChangePlotEvent

### ISSUE THREAD

**Issue by Twiistrz** [TownyAdvanced/Towny#3100]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. When player move chunk this error pop out and spamming the console

### What is your Towny version?
Towny v0.93.0.0

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-642f6d2-ca6d2cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/cogagubemo.php
3. Your townyperms.yml : https://hastebin.com/mixogixale.php
4. Your log's error : https://hastebin.com/mepagoxewu.pl

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
None of the hastebins are working? Your log's link is just a link to hastebin.
