### ISSUE TITLE
Bug: Wilderness regeneration.

### ISSUE THREAD

**Issue by DragonisOmega** [TownyAdvanced/Towny#3107]
### What steps will reproduce the problem?
1. Have a creeper explode While wilderness regeneration is on
2.When Blocks come back the are the wrong type, and stripped logs don't come back at all
3.Half slabs come back the wrong type

### What is the expected output?
1. That everything regens correctly.
I'm turning my regeneration off for now.
I hope the issue gets fixed. for others that like it on. 
2. If you are going to setup a section in config to change block types to regen as something else
would be ok too.

### What is your Towny version?
Do not say "latest".
Towny version: 0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This was already fixed in the builds made for 1.13. If you want access just ask on Discord.
