### ISSUE TITLE
Towny 1.13 loading problems

### ISSUE THREAD

**Issue by arkobat** [TownyAdvanced/Towny#3111]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
Generate a fresh config
Change some config options, some booleans and some ints
My config: https://hastebin.com/epilicedaw.coffeescript

The error: https://hastebin.com/apedovikux.md

### What is your Towny version?
v0.93.0.0

### What is your spigot/craftbukkit version?
 This server is running Paper version git-Paper-454 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/xebiqoriri.md
2. Your Towny config.yml (if using MySQL please remove password,) : Is pasted above
3. Your townyperms.yml : https://hastebin.com/vawikijine.php
4. Your log's error :  Pasted above

**Comment by LlmDl** [comment]
You did not generate a fresh config, your town_levels are missing the townOutpostLimit, this is what it is complaining about in the startup error. Try a fresh config, or copy the townlevels from a fresh config into your existing config.
