### ISSUE TITLE
[10:28:42 WARN]: [com.palmergames.bukkit.towny.log] [Towny] Error: No compatible Economy plugins found. Install Vault.jar with any of the supported eco systems

### ISSUE THREAD

**Issue by EOT3000** [TownyAdvanced/Towny#3113]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What is the expected output?
Working economy.

### What is your Towny version?
latest - 0.93.0.0

### What is your spigot/craftbukkit version?
Paper 451

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
https://pastebin.com/KfbpCQ9W
https://pastebin.com/fsd3FbEU
townyperms has nothing to do with this. If you really need it I will add comment.

When I start up my server with my eco plugin and vault, towny says no eco plugin is found. But if I write vault-info in console, it says that there is an eco plugin. I also installed other plugins that use economy to test. The other plugins work.

[10:42:25 INFO]: [Vault] Vault v1.7.1-b91 Information
[10:42:25 INFO]: [Vault] Economy: Basics [Basics](My plugin)
[10:42:25 INFO]: [Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
[10:42:25 INFO]: [Vault] Chat: LuckPerms [LuckPerms]

**Comment by EOT3000** [comment]
anyone here?

**Comment by LlmDl** [comment]
You don't have an economy plugin, just Vault. Get an economy plugin to get Towny to work. If you don't want an economy plugin, set using_economy: false in your towny config.yml.

**Comment by EOT3000** [comment]
I have one. I made it. I made the question inaccurate. Its more that how would I make my Eco plugin compatible?

**Comment by LlmDl** [comment]
You'll have to make your eco plugin hook into Vault as an EconomyProvider (I believe that's what it's called, it's been a while.)

**Comment by creatorfromhell** [comment]
> I have one. I made it. I made the question inaccurate. Its more that how would I make my Eco plugin compatible with towny?
In order to correctly show up, you'll have to correctly implement the Economy Provider interface from Vault, and register it accordingly. You may also want to check out Reserve as an alternative API that allows multi-currency support, and also automatically registers your plugin with Vault and Reserve. https://www.spigotmc.org/resources/reserve.50739/
