### ISSUE TITLE
Suggestion: Add/Fix these items' towny switch/itemuse protections

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3116]
The following items have been confirmed to be interactable when all town and plot permissions are off by a person in another nation unrelated to the local town:

- Oak doors
- Oak fence gates
- All trapdoors
- All pressure plates
- All buttons (at least wooden ones)
- Default coloured shulker boxes
- Light grey shulker boxes
- Redstone repeaters
- Redstone comparators

The towny config has the default itemuse and switch lists. While some of these items are listed there they do not seem to still function in 1.13.2.

**Comment by LlmDl** [comment]
Your recent tickets have skipped the form. Please fill out the forms, I don't know which Towny version you're using and which version of MC. Please resubmit this.
