### ISSUE TITLE
Add/Fix these items' towny switch/itemuse protections

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3117]
The following items have been confirmed to be interactable when all town and plot permissions are off by a person in another nation unrelated to the local town:

- Oak doors
- Oak fence gates
- All trapdoors
- All pressure plates
- All buttons (at least wooden ones)
- Default coloured shulker boxes
- Light grey shulker boxes
- Redstone repeaters
- Redstone comparators

The towny config has the default itemuse and switch lists. While some of these items are listed there they do not seem to still function in 1.13.2.

### What steps will reproduce the problem?
1. Use any of the above items while you should not be allowed to in town protections.

### What is the expected output?
1. You should not be allowed to.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
`Paper version git-Paper-460 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

Your Towny config.yml (if using MySQL please remove password,) : [config.txt](https://github.com/TownyAdvanced/Towny/files/2616312/config.txt)
Your townyperms.yml :
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/2616316/townyperms.txt)

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/49039192-59a78b00-f1bf-11e8-82e9-8639ff27ead3.png)
I'll add this on as well.

**Comment by LlmDl** [comment]
Fairly sure all of this is already fixed on the builds made for 1.13.2 but you could test it if you want. They're available on the Discord if you have the 1.13 tester rank.

**Comment by KarlOfDuty** [comment]
I see, I was not aware there were builds specifically for 1.13, please add me.

**Comment by LlmDl** [comment]
This was done, if anything got missed please file a new ticket with a new list.
