### ISSUE TITLE
Large Chat error

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3120]
### What steps will reproduce the problem?
Any server start. This has no impact on the functioning of the plugin once the server starts. All chats work and all functions work. I don't know when this started. I came back from a tournament over the weekend and I saw it in the console. 

### What is your Towny version?
v 0.53 is what config for townychat says
Towny version 0.93.0.0

### What is your spigot/craftbukkit version?
spigot 1.13.2
https://imgur.com/a/bI3RqOs

1. Your full server startup from the logs\latest.log : https://pastebin.com/dLY1igdV
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cM7JEQTt
3. Your townyperms.yml : https://pastebin.com/vKxcHgGh
4. Your log's error : https://pastebin.com/5J1a1uts

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/rVbmyx74
7. Your channels.yml : https://pastebin.com/qTyHNWvG

**Comment by LlmDl** [comment]
That error isn't a TownyChat error, looks like it might be idisguise?
