### ISSUE TITLE
Townperms It seems that it is not detected

### ISSUE THREAD

**Issue by RubenStryker** [TownyAdvanced/Towny#3123]
### What steps will reproduce the problem?
1. A user is given the rank of "coalcalde"
2. The user has all the permissions that this range has
https://pastebin.com/sSdeEzbK
3. After a while the user loses the permissions, but retains the rank.
4. The users when restarting the server, have the permissions again, but the 2 previous steps are repeated.
5. Screenshot of a user: https://i.imgur.com/BsMHawb.png
6. Node check
![image](https://user-images.githubusercontent.com/24832320/49696554-7d010b80-fbab-11e8-8b10-590a78db5fdc.png)

### What is the expected output?
Well the permissions should be maintained, and should not have to restart the server to be corrected.
And it is very rare that users have to restart the server for this to be corrected.

### What is your Towny version?
0.93.1.0 -> I got it in the discord of towny, in the #updates channel

### What is your spigot/craftbukkit version?
Spigot 1.13.2

### Please use Pastebin.com to link the following files:

1. In logs you do not see anything
2. Config.yml : https://pastebin.com/yab9gAVr
3. Your townyperms.yml : https://pastebin.com/sSdeEzbK

On other occasions, it also happens that after degrading a rank user, it returns to recover its rank after a few hours of time.

**Comment by LlmDl** [comment]
You skipped the startup log. I'm assuming you're still using LuckPerms? Can you make it happen when LP isn't installed? They cache permissions which could explain why the player is losing permission to do things when they haven't lost their rank. Or when they change worlds.

**Comment by RubenStryker** [comment]
Update: [12:52:39] [Server thread/INFO]: [Towny] Error could not read msg_err_command_disabl e from spanish.yml

**Comment by RubenStryker** [comment]
Update: Users can not do / t spawn when go to another world
![image](https://user-images.githubusercontent.com/24832320/49699436-75545d80-fbd1-11e8-845a-b0b45bfa50f8.png)
![image](https://user-images.githubusercontent.com/24832320/49699442-8e5d0e80-fbd1-11e8-9480-25cc1db2d380.png)

**Comment by LlmDl** [comment]
It isn't something that Towny is doing by itself, I would be getting hundreds of tickets if it were. Test it without LP in use or see if you can find some configuration options for caching of permissions in LP.

**Comment by LlmDl** [comment]
Also, you aren't using 0.93.1.0, you're using 0.93.0.0.

**Comment by RubenStryker** [comment]
LuckyPerm Config.yml (Towny server): https://pastebin.com/dDTjPAGk

To test this failure, disabling the LuckyPerm plugin should do the tests another day, right now I can not do them on the server.

If I use version 0.93.1.0, but this version does not indicate that this is your version number.
Inside the .jar file I get the changelogs.txt file and I can see the addition of version 0.93.1.0

![image](https://user-images.githubusercontent.com/24832320/49699765-7c7d6a80-fbd5-11e8-9025-54f8223b384c.png)

You can check.

**Comment by RubenStryker** [comment]
... older versions
0.92.0.14:
    - Change made to config code. Should fix the extra newlines seen on some servers.
    - Fix stupid boolean that made charges not apply for creating a town.
    - Make it so that players vanished by the plugin Essentials do not have the LastOnline value updated.
      - Note: This means that a player could be deleted by the old-resident-deletion feature.
    - Fix for nations that lack nationBoards causing issues when upgrading from older versions of Towny.
0.93.0.0:
    - Bump version number for release build.
0.93.1.0:
    - Fix for nationZones affecting nation-less towns when the only_capitals setting is false. 
    - Fix for servers using CMI that cannot have jailed players sent to jail on respawn.
    - Fix for russian.yml not loading.
    - Fix for global_town_settings.keep_experience_on_death_in_town setting not appearing in configs.

**Comment by LlmDl** [comment]
I guess I forgot to bump the version number in the test jar, let me know when you've got a test server running without LP and you see the results.

**Comment by LlmDl** [comment]
This ended up being LP specific. Not present when LP was not installed.
