### ISSUE TITLE
Suggestion: Disable warps and teleports for the player when non-town members and/or non-friends are within a certain radius

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3124]
Suggestion: 
To be able to disable warps and teleports via config for the player when non-town members and/or non friends are within a certain radius depending on how it's setup in config, but when town members are close or if player is near no-one, warping/teleporting is allowed.

This way players wont be able to tele out when they see another player keeping pvp consistant, in order to tele they must run out of range first

**Comment by axemwa** [comment]
I also suggest adding the same for non-tagged mobs so that players can't teleport when they are within a set "x, y and z" radius from a mob depending on how it's set in config

**Comment by LlmDl** [comment]
This is something that plugins like CombatTag are made for. It would be better if one of them were to add support for Towny via our API rather than us recreating the entire plugin inside of Towny.

**Comment by axemwa** [comment]
good point, my bad il suggest it to the author of the combat plugin I use thanks 4 gettin bak 2 me

**Comment by LlmDl** [comment]
If he needs help using our API you can send him my way. Then I'll know which combattagger I can recommend too.
