### ISSUE TITLE
spawn_travel does not charge players

### ISSUE THREAD

**Issue by OpalMoonstride** [TownyAdvanced/Towny#3125]
### What steps will reproduce the problem?
1. config.yml has spawn_travel set to charge 20.00 per /town spawn
2. Player is not charged, but is allowed to travel, despite $0 balance

### What is the expected output?
1. Players should be charged 20 per /town spawn.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Paper("684bd2a") 1.13.2-R0.1-SNAPSHOT

1. Your full server startup from the logs\latest.log : https://paste.ubuntu.com/p/vv6tnDpVMp/
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/uU8EXpbV
3. Your townyperms.yml : https://pastebin.com/RPTf69LW
4. Your log's error : No known errors shown

(optional) If this is to do with permissions, 
5. Your permissions file : https://www.dropbox.com/s/e8sdrh1u1p68jta/luckperms-h2.mv.db?dl=0

### Relavent plugins
Vault: 1.6.7
Economy: TheNewEconomy 0.1.1.7

### Notes:
Economy works in other aspects (pay, take, give, set, town deposit, taxes, setting town accounts etc).

**Comment by OpalMoonstride** [comment]
Anyone able to help me? 

I've tried asking in a few places, for help. I don't know what I am missing. I had this set so that all towns charged 20 in 1.12, but in 1.13, it lets players set it to $0.

**Comment by OpalMoonstride** [comment]
Help is not forthcoming, it seems. 

Towny cannot do this, according to code-trudging. I will have to restrict travel another way.

**Comment by LlmDl** [comment]
In a recent update we allowed mayors/kings to set their spawn costs as long as they do not go over the set config spawn cost.

It is still possible to stop mayor from setting their spawn costs by giving the negated node towny.command.town.set.spawncost in the mayor/assistant sections of the townyperms.yml, as well as towny.command.nation.set.spawncost from the king/assistant sections.
