### ISSUE TITLE
Permission question/issue. Join nation

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3126]
With out towny.command.town.*, mayors can't accept a nation invite. I don't want to give them this though, because I don't want people to be able to do certain commands, like disabling pvp in their town. How do I get around this? Is there a permission that lets mayors join nations because I'm not able to locate any on the permission nodes page.

**Comment by LlmDl** [comment]
towny.command.town.invite.accept and towny.command.town.invite.deny are two nodes you probably want to give them, or you could just do towny.command.town.invite.* and get them all (the list ones too.)
