### ISSUE TITLE
Suggestion: {playername} {Displayname}

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3128]
In the options for towny chat, can there be two different name options? For example, I want to allow nicks in tc and l, so its easy for people to roleplay, but just have playernames in global/nc, because nicks can get annoying/abused/confusing for the server as a whole in server wide chats.

**Comment by LlmDl** [comment]
Most other plugins change a player's name using the commonly named DisplayName, that chat tag is what we call {modplayername}, I'm pretty sure this is what you're asking for.
