### ISSUE TITLE
War How to disable PVP lock for non nation towns & enemy nations

### ISSUE THREAD

**Issue by WillisAwesome** [TownyAdvanced/Towny#3129]
How do I enable global pvp during war & how can I make all nations can cap eachother without forcing them to do /n enemy add.

**Comment by WillisAwesome** [comment]
When towns are neutral you can grief in them

**Comment by LlmDl** [comment]
Well if you want you can not use the towns_are_neutral option and just use '/tw toggle forcepvp' in all the applicable worlds.

**Comment by WillisAwesome** [comment]
Are you looking to fix the griefing issue in towns when griefing is disabled in the config?

**Comment by LlmDl** [comment]
No ones shown me a proper ticket for that bug yet. You can resubmit that if you'd like without skipping the form.

**Comment by WillisAwesome** [comment]
Alright I'll probably do that
