### ISSUE TITLE
Towny War Neutral Glitched

### ISSUE THREAD

**Issue by WillisAwesome** [TownyAdvanced/Towny#3130]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Disabling Neutral Towns in The Config
2. Toggling War
3.

### What is the expected output?
1. Able to grief in towns without nations
2.
3.

### What is your Towny version?
Do not say "latest". 0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest". PAPER-426

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : (no errors)
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/0K6ej1hB
3. Your townyperms.yml : (not a permissions issue)
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Before Toggling war:
https://gyazo.com/a82fb1425f2c3dc8d11568a09d71fa0b

After Toggling war:
https://gyazo.com/bb7c86422863e47f7feaa37ca8a56993

**Comment by WillisAwesome** [comment]
Is this going to get resolved?

**Comment by WillisAwesome** [comment]
I don't want them to be griefable them

**Comment by LlmDl** [comment]
Ok I don't understand what you want then. In the ticket the only Expected outcome you list is "Able to grief in towns without nations".

**Comment by WillisAwesome** [comment]
I don't want anything to be griefable in war, griefing is disabled entirely but when netural towns are enabled people can grief in them.

**Comment by WillisAwesome** [comment]
So is this going to be resolved?

**Comment by WillisAwesome** [comment]
To reproduce it make sure     "towns_are_neutral: false" and block griefing is disabled.

**Comment by LlmDl** [comment]
And then go to a nationless town and try to grief? I'd like to know exactly what I should be testing so I don't waste time trying to find what you're seeing please.

**Comment by WillisAwesome** [comment]
Correct

**Comment by WillisAwesome** [comment]
So how long will this take to be fixed?

**Comment by WillisAwesome** [comment]
Any updates?

**Comment by LlmDl** [comment]
When I get some free time to test for it, then look at the code, I'll have an update for you.

**Comment by WillisAwesome** [comment]
Have you got the time yet to work on it?

**Comment by WillisAwesome** [comment]
Never mind its working now

**Comment by LlmDl** [comment]
Any idea what changed?
