### ISSUE TITLE
[BUG] Auto-reassignment of the "Assistant" rank.

### ISSUE THREAD

**Issue by NekoShouta** [TownyAdvanced/Towny#3131]
### What steps will reproduce the problem?
1. Removing a player from the "Assistant" rank.
2. Restarting the server.

### What is the expected output?
1. To remove an user permanently from a town rank.

### What is your Towny version?
Towny Advanced 0.93.0.0 

I don't know if it also happens with the other ranks, but if I remove an user from the rank, when I restart the server the player still has the rank.

**Comment by LlmDl** [comment]
Skipped form, but this sounds an awful lot like what some luckperms users have been experiencing. Re-file your ticket without skipping the form.
