### ISSUE TITLE
Suggestion: Make /leave persistant

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3133]
If someone rejoins they have to leave all channels they don't want to be in again.

**Comment by Articdive** [comment]
If we create a database system where a property can be set and get regardless of it's name and it having to be generated in a schema. for example set("randomname", 5) would just write randomname=5 into the config without stuff like a name check and checking if it's a valid columnname. At the moment we make sure we only save what we need to. This could also be used to save invites.
