### ISSUE TITLE
Cannot Buy Bonus Blocks even though set to 1000.

### ISSUE THREAD

**Issue by DragonSlayer696** [TownyAdvanced/Towny#3134]
So I have max_purchased_blocks: '1000' as well as the Price of them to $100. But whenever I do /t buy bonus (amount) I get no response in chat or in the console for errors. I do /t buy it says nothing is for sale. I cannot find anyone else with this issue and with no errors I can't find the problem myself I am hoping someone can help me figure this issue out.

### What steps will reproduce the problem?
1.Using /t buy bonus (Amount)
2.Does nothing and does not give any prompt what so ever in chat or in server console.

### What is the expected output?
1.When using /t buy bonus (Amount) 
2.It's suppose to give me the Bonus blocks I want to buy.

### What is your Towny version?
0.88.0.0

### What is your spigot/craftbukkit version?
Thermos : 1.7.10-R0.1-SNAPSHO : 1.7.10-1614.58 (MC: 1.7.10).

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/ryh3RT5L
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/nN84Ghsd
3. Your townyperms.yml :https://pastebin.com/ATV0Q7ct
4. Your log's error : There isn't one that's why I can't figure out what's wrong.

(optional) If this is to do with permissions, 
5. Your permissions file :https://pastebin.com/ATV0Q7ct

(optional) If this is to do with chat,

**Comment by LlmDl** [comment]
There's a 0.92.0.0 for 1.7 that you can try out http://palmergames.com/file-repo/Towny%20Advanced/Releases/0.92.0.0%20(For%20MC%201.7.10)/

but I did not fix the chat output for that command until 0.92.0.6 according to the changelog https://git.io/vxiWf

your config seems to be fine though.

**Comment by DragonSlayer696** [comment]
That was the fix Thank you so much! As long as it works I don't really need a chat output as long as I can buy more claims. Again I can not express my gratitude enough thank you.

**Comment by DragonSlayer696** [comment]
Glad to know it was a incompatibility or screw up on my end.

**Comment by LlmDl** [comment]
Good to hear, I'll close this ticket.
