### ISSUE TITLE
[Bug] Revert on unclaim in 1.13 still needs work. NPE's are generated on some blocks.

### ISSUE THREAD

**Issue by LuisGVE** [TownyAdvanced/Towny#3136]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
The error has started to appear since I updated the versions of the 1.13

### What is the expected output?
A solution to this problem as it creates spam of errors and fills my server with log files

### What is your Towny version?
0.93.0.4

### What is your spigot/craftbukkit version?
Paper 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/xpAH6xnD
2. Your Towny config.yml (if using MySQL please remove password,) : default
3. Your townyperms.yml : default
4. Your log's error : https://pastebin.com/7av7i0sB

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This should be sorted out with 0.93.1.0
