### ISSUE TITLE
Prevent invites from being sent to Citizens NPCs.

### ISSUE THREAD

**Issue by RubenStryker** [TownyAdvanced/Towny#3138]
### What steps will reproduce the problem?
1. A user invites another user to their city
2. the invitation arrives, but does not appear

### What is the expected output?
1. that the invitation arrives and can see the commands to accept or deny the invitation

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Spigot 1.13.2

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/d7FyUzBT
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/pj5LJt3y
3. Your townyperms.yml : https://pastebin.com/173tpHw0
4. Your log's error : - None -

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by RubenStryker** [comment]
Update: 
It worked for me by erasing the user data, it seems that the difference between use of uppercase and lowercase

![image](https://user-images.githubusercontent.com/24832320/50518006-98c54680-0ab3-11e9-9976-b39a1c0d6e07.png)
![image](https://user-images.githubusercontent.com/24832320/50518048-e3df5980-0ab3-11e9-9542-7f727ae9f809.png)

**Comment by LlmDl** [comment]
I'll look into whether we are really that strict about the upper-lower-casing of the user names.

**Comment by RubenStryker** [comment]
[00:34:50] [Server thread/INFO]: [Towny] Error could not read owner_status from spanish.yml

Other error

**Comment by LlmDl** [comment]
> [00:34:50] [Server thread/INFO]: [Towny] Error could not read owner_status from spanish.yml
> 
> Other error

That's just your language file not being complete/having a broken string.

**Comment by RubenStryker** [comment]
Update: I have discovered by chance that this is because the towny plugin tries to find data from Citizens NPCs, it is not real users.

**Comment by LlmDl** [comment]
I wonder why it's doing that. Did you add Citizens npcs to the towns manually or something?

**Comment by RubenStryker** [comment]
No, I did not do anything.
But one of the npc had the same name as a user that if it belongs to a city.
Player: rampeltiski
NPC: Rampeltiski

I have deleted the npc to avoid the faults and the lagg that produces this error in towny, it seems that it happens when interacting with them.

**Comment by LlmDl** [comment]
Ok, good find. We do ignore NPCs at some points in the code. I guess we have to be a bit more careful of where we're sending invites.
