### ISSUE TITLE
Towny using syncChunkLoad might be causing TPS drop any way to improve performance if needed?

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3139]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Start server with timings enabled in paper.yml and plugin profiling enabled in bukkit.yml
2. Run Towny on server for wait 5-10 mins
3. Teleport to town spawn
4. Do /timings paste
5. Stop server and check the link

### What is the expected output?
1. For it not to affect TPS as much when using syncChunkLoad

### May be the same as this issue
https://github.com/TownyAdvanced/Towny/issues/2187

### What is your Towny version?
version: 0.93.0.4

### What is your spigot/craftbukkit version?
Do not say "latest".

This server is running Paper version git-Paper-481 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/EkUvp0cy
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/zvHSXGu6
3. Your townyperms.yml : https://pastebin.com/LSAQTsX6
4. Your log's error : No error, it's TPS drop

![image](https://user-images.githubusercontent.com/37608633/50543539-ff20a500-0c2a-11e9-8d31-1c9e6abd094a.png)

![image](https://user-images.githubusercontent.com/37608633/50543542-13fd3880-0c2b-11e9-8954-252f3dc94785.png)

**Comment by LlmDl** [comment]
Like the ticket you linked, I'll ask to see the timings please.

**Comment by axemwa** [comment]
oh sorry u mean the actual link right? Here - https://timings.aikar.co/?id=b5f0c15a8e3449808c4cfcbf5a778aa4#

**Comment by axemwa** [comment]
ok thankyou I have removed randomteleport since then as I was infact having trouble with that and did report it the the author, and some other plugin authors/devs have fixed their plugins issues since then aswell I'll do another timings report to see if this is still happening
