### ISSUE TITLE
Outpost claim error

### ISSUE THREAD

**Issue by MooseKrazy** [TownyAdvanced/Towny#3140]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. player typing /t claim outpost

### What is the expected output?
1. Error: You cannot own more than 0 outposts

### What is your Towny version?
 0.93.0.0

### What is your spigot/craftbukkit version?
 Paper Spigot 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/wjPw2ut8
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/GypJSTKW
3. Your townyperms.yml : https://pastebin.com/pLj5F3fW
4. Your log's error : 30.12 21:26:49 [Server] INFO dirtyRapscallion issued server command: /t claim outpost

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/xzS6sH8Y

(optional) If this is to do with chat, 
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
Just guessing that this could be a bug when the limit_outposts_using_town_and_nation_levels setting is false. I'll look into this, but I'm betting you could just toggle that to true and configure some high numbers in the Town Levels for now.

**Comment by MooseKrazy** [comment]
Thanks! Will give that a try!

**Comment by MooseKrazy** [comment]
I'm looking at the config. Just so I'm sure I understand, when you said "configure some high numbers in the Town Levels" are you talking about under the section Town and Nation Levels and changing the townOutpostLimit for each to say 5?

**Comment by LlmDl** [comment]
Yep, what ever you think is appropriate for your server.

**Comment by MooseKrazy** [comment]
Sweet! Thanks will give that a go and let you know if it worked.

**Comment by MooseKrazy** [comment]
Unfortunately this didn't resolve the issue. I put the limit_outposts_using_town_and_nation_levels setting to 'true' and increased all townOutpostLimit to 5. I realize it's New Years and understand if you can't get back to this for a few days.

**Comment by LlmDl** [comment]
Huh, well if that didn't solve it the problem must be somewhere else. The town trying to claim the outpost does have townblocks available to claim right?

**Comment by MooseKrazy** [comment]
Yes they do. For example tried with my alt, who isn't opped, claimed 1/8 chunks to start a town then posted $500 into the town account, then went out away from any other claimed chunks and tried to claim the outpost. Got the error. My opped account can claim an outpost.

**Comment by LlmDl** [comment]
Ok, I've done some searching through teh code for this and it appears to be failing at getting a value for the resident's max outposts, which is something that isn't given by default via townyperms.yml.

The towny_maxoutposts node is something which you aren't giving in your permission file but when I did look at it, you are giving lots of towny nodes that shouldn't be there. Everything besides towny.wild.* should be removed. All of the rest of the nodes are already given out correctly in the townyperms.yml. Something you're giving in your permission plugin is probably making it so that your players are somehow registering maxposts at 0. 

After you've removed all but towny.wild.* from the permission file try it out again. You can of course leave your admin rank with towny.admin.*

**Comment by MooseKrazy** [comment]
Ok, we were finally able to work on this. We removed ultra permissions and installed Group Manager and it works like a charm! Thank you so much!
