### ISSUE TITLE
Suggestion: Disable Outsiders from entering towns.

### ISSUE THREAD

**Issue by DragonSlayer696** [TownyAdvanced/Towny#3142]
Option to Disable/Enable Outsiders from entering your town. And they can only enter plot claims you have set to shops.

I have Towny on a modded server and not all containers are protected from Outsiders Recently someone came in and took all of our villagers because they could Right click on them and tell them to follow them outside the claim and kill them all. I tried adding the containers from mods but I haven't had any luck so maybe this could be a good idea?

**Comment by LlmDl** [comment]
This has been shot down in the past because it is too laggy. We cannot be constantly checking every player to see if they're crossing into a town they shouldn't be allowed to enter. I have told people in the past that they should just build some in-game walls/fences.
