### ISSUE TITLE
Flag War is broken in master branch / 1.13.2 - compound issue.

### ISSUE THREAD

**Issue by TheFlagCourier** [TownyAdvanced/Towny#3145]
Note: I am aware that Flag-War is deprecated and unsupported. This is only being filed for those who search the issue tracker, and for potential triage into #2995. I do not expect a fix in the near future, and we'll probably end up pushing a PR later to address this.

### What steps will reproduce the problem?
1. Set `war.enemy.allow_attacks` to `true`
2. Attempt to flag an enemy nation, place a fence
3. **Fail to Flag**
4. Change `war.enemy.flag.base_block` from `fence` to `oak_fence`
5. Reload config and repeat steps 1-2 with an oak_fence.
6. **Flag partially generates, and war event starts**
     - At this phase, the "flag" consists of the fence post, and whatever is set to `war.enemy.flag.light_block` - with air in the middle.
     - The flag is indestructible (not cancel-able)
     - de-commenting code in CellUnderAttack does allow the wool to generate, but be destroyed until the next time it queues an update to the next color.

### What is the expected output?
1. Enable the flag-war system
2. Go through the motions
3. Take plots from thine enemies (or loose your flags to defenders)

### What is your Towny version?
0.93.0.4 ("1.13 Very Early Build") & f18ce10e338485b2c8bcc74f39e8372f7a1f760c + local edits (testing-only)

### What is your spigot/craftbukkit version?
Paper 1.13.2 (Build 492 aka: https://github.com/PaperMC/Paper/commit/ccbeb5c4ed056161da4277993db962d995159df3 )

### Additional Information
This seems to be the result of deprecation in both Bukkit and Towny. It seems that the wool is in part affected by https://github.com/TownyAdvanced/Towny/commit/583c330346ee04ba20b735648d334976470bf874 - in which `/tw regen` was removed. Code effecting the wool was commented out, but mostly undocumented.

A few others on our team are currently looking into it more, as we are in the process of moving from 1.8.8.

**Comment by LlmDl** [comment]
Correct on all fronts, any PRs will be welcome if you're up for maintaining flag war up to 1.13 support.

**Comment by AsylumDevs** [comment]
We'll look into the bug for you TheFlagCourier.

**Comment by LlmDl** [comment]
Closed because I am not supporting flagwar, anyone who stumbles across this and wants to prepare a Pull Request fixing flag war is more than welcome to do so.
