### ISSUE TITLE
Huge TPS drop when using /town claim command

### ISSUE THREAD

**Issue by gerardvanschip** [TownyAdvanced/Towny#3146]
### What steps will reproduce the problem?
1. Use /town claim

### What is the expected output?
1. You get claims. It works as expected

### What is your Towny version?
Do not say "latest".
0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.13.2-r0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/UMiHWL5X

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/6k0LRhiv

3. Your townyperms.yml :
https://pastebin.com/NmAXCFDG

4. Your log's error : 
No error log? Towny is functioning OK but the problem we have is that using the claim command will kill the server tps. Make it super laggy. If we don't use it all is fine. Weirder is that when we use it a lot you don't see a spike in cpu or memory. Just a stead drop in tps. Takes roughly 6 hours for tps to drop to 6. If we don't claim it stays between 18 and 20 at all times. 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Can you take a screenshot of the /tw screen when it's used in teh world you're claiming in?

**Comment by gerardvanschip** [comment]
I disabled revert on unclaim in config. Is it back on?

**Comment by gerardvanschip** [comment]
Ah yeah I see it now. That's supposed to be off.

**Comment by LlmDl** [comment]
The config is only default settings for new worlds, it's all stored per-world.

**Comment by gerardvanschip** [comment]
Aaah. That explains. Great will edit that and see how it goes.

**Comment by LlmDl** [comment]
I'm assuming the revert on unclaim was turned off and the server claims without TPS drop now.
