### ISSUE TITLE
Info Tool on Mobs Prints Three Times

### ISSUE THREAD

**Issue by TheFlagCourier** [TownyAdvanced/Towny#3148]
Using the info tool on a mob seems to run the output four times.

### What steps will reproduce the problem?
1. Equip Towny's Information Tool (Brick)
2. Secondary-Click on a Mob
3. Get Entity Info printout, Entity Info printout, Entity Info printout, and Entity Info printout

![screenshot_20190107_023007](https://user-images.githubusercontent.com/2712890/50757694-c7ff5480-1225-11e9-832c-1e93b8a273f6.png)
![screenshot_20190107_030612](https://user-images.githubusercontent.com/2712890/50758947-427da380-1229-11e9-8edf-297bdb74c59e.png)

### What is the expected output?
1. Equip
2. Click
3. Get a singular output.

### What is your Towny version?
Build from PR #3147 - _Should also affect master branch (https://github.com/TownyAdvanced/Towny/commit/f18ce10e338485b2c8bcc74f39e8372f7a1f760c)_

### What is your spigot/craftbukkit version?
1.13.2-R0.1-SNAPSHOT git-Paper-495

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://gist.github.com/TheFlagCourier/2822b47777d5937f0857da817eec4b92
2. Your Towny config.yml  : https://gist.github.com/TheFlagCourier/867bd83e05d275654df6a88247e99b31
3. Your townyperms.yml : https://gist.github.com/TheFlagCourier/31ef094b6e1ceafe2afdac6eefa6196c
4. Your log's error : _Not Applicable; Not a logged error_

**Comment by LlmDl** [comment]
I don't see how this was happening but I do notice we've since changed to the getItemInMainHand, could you retest this with 0.93.1.0 please https://cdn.discordapp.com/attachments/321710042091094026/580758574393982977/Towny.jar

**Comment by TheFlagCourier** [comment]
Yeah, I'll give it a go tonight.

**Comment by TheFlagCourier** [comment]
@LlmDl It [Still Occurs](https://youtu.be/xyE-2kIIjT4) - retested on 0.93.0.5 and ran additional tests on 0.93.1.0 and 2abf181

#### Testing Environment
- 1.13.2 - Paper-626, git-Spigot-1a3504a-dfa7583 (Final Build)
- Java 11 (OpenJDK [ojdkbuild])
- Widnows 10 (1809)
- Other Plugins:  LuckPerms 4.4.24, Vault-1.7.2, EssentialsX 2.16.1.156

**Comment by LlmDl** [comment]
Thanks for testing.

**Comment by LlmDl** [comment]
Just made a new commit that should drop the count down to 2 (or 1.)

**Comment by TheFlagCourier** [comment]
Alright, I'll give it another test tonight.

**Comment by TheFlagCourier** [comment]
I've got good news and bad news!
The good news, it's spamming less.
The bad news, it's doing it three times instead of once.

![2019-05-26_11 29 43](https://user-images.githubusercontent.com/2712890/58384645-c3a3c000-7fa9-11e9-9c96-c0e2b25cd439.png)

**Comment by Articdive** [comment]
This is caused by the left_hand also being called we can add a: 
```java

		if (event.getHand().equals(EquipmentSlot.OFF_HAND)) {
			return;
		}

```
this should get rid of at least one of the messages.

**Comment by LlmDl** [comment]
The last one he tested which got it from 4 to 3 messages was done by adding 
```
if (event.getHand() != EquipmentSlot.HAND)
	return;
```

But I'll try it your way @Articdive 

Can you test again @TheFlagCourier with the latest commit.

**Comment by TheFlagCourier** [comment]
@LlmDl No change from previous build - still displaying three messages.

**Comment by LlmDl** [comment]
Try it now, we found the derp.

**Comment by TheFlagCourier** [comment]
Commit 7afb521 effectively closes the issue!

![image](https://user-images.githubusercontent.com/2712890/58385928-bdb7da00-7fbd-11e9-9900-614f951eb854.png)
