### ISSUE TITLE
Towny Issue: Other Users are unable to claim plots for sale, recieving message "cannot claim more than 0 plots"

### ISSUE THREAD

**Issue by Wakeeng** [TownyAdvanced/Towny#3149]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Using UltraPerm Plugin
2. Placing a plot in your town for sale
3. User attempting to use command /plot claim

### What is the expected output?
1. User/Resident is able to claim plot
2.
3.

### What is your Towny version?
Towny Advanced 0.93.0.0

### What is your spigot/craftbukkit version?
Spigot-1.13.2.Jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/3NWr5UP8
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/nGz3QYkE
3. Your townyperms.yml : https://pastebin.com/xC17LsYj
4. Your log's error : Did not receive logs error

(optional) If this is to do with permissions, 
5. Your permissions file :

**Comment by LlmDl** [comment]
This was/is an issue with ultraperms handing out the towny_maxplots.# node incorrectly, switch to any other perm plugin and it will not happen.
