### ISSUE TITLE
Towny fails to load after upgrading from 0.90.0.0 to 0.93.0.0

### ISSUE THREAD

**Issue by bbayu123** [TownyAdvanced/Towny#3150]
A NullPointerException occurs when I attempted to upgrade my Towny version from 0.90.0.0 to 0.93.0.0, and the plugin fails to load.

### What steps will reproduce the problem?
1. Stopping the server that has Towny Advanced 0.90.0.0
2. Upgrading directly from 0.90.0.0 to 0.93.0.0
3. Start the server and watch it fail

### What is the expected output?
1. The plugin enables properly
2. There are no errors in the console
3. All the functions of Towny work

### What is your Towny version?
Towny Advanced 0.93.0.0

### What is your spigot/craftbukkit version?
Spigot 1.12.2, build 1573-i

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/HyiUQk5J
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/WsUCNUE5
3. Your townyperms.yml : https://pastebin.com/trqvyHQV
4. Your log's error : https://pastebin.com/D8kh05Uz

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
Your town_levels and nation_levels are out of date:
```
java.lang.NullPointerException: null
    at com.palmergames.bukkit.towny.TownySettings.loadTownLevelConfig(TownySettings.java:115) ~[?:?]
```

The download pages to all the builds between 0.90.0.0 to 0.93.0.0 all include the list of Required Changes, of which there are a few for townlevels & nationlevels. These two sections of the config cannot be updated automatically so whenever there are changes to them the admin is required to do it.

The other option is to delete your town_levels and nation_levels sections and towny will remake them with the new defaults.

**Comment by bbayu123** [comment]
Where are the townlevel and nationlevel settings? I have difficulty finding them.

**Comment by LlmDl** [comment]
in the config.yml

**Comment by bbayu123** [comment]
Aah found them, I was searching with "nation_levels" before and that's why I wasn't seeing any search results.
