### ISSUE TITLE
SQLITE_ERROR Spam on Startup

### ISSUE THREAD

**Issue by bbayu123** [TownyAdvanced/Towny#3151]
There seems to be some weird error with SQLite about not finding a table that it does not use, despite the plugin working absolutely fine.
(Also while on the same topic, it says `Make sure you schedule a backup in MySQL too!!!`, despite me using SQLite, which is covered by the backup.)

### What steps will reproduce the problem?
1. Set plugin.database.database_save in config.yml to "sqlite", while keeping database_load as "flatfile"
2. Shut the server down to save the information to SQLite
3. Set plugin.database.database_load in config.yml to "sqlite"
4. Start the plugin up
5. Watch it spam

### What is the expected output?
1. No SQLITE_ERRORs in the console

### What is your Towny version?
Towny Advanced 0.93.0.0
Persists since Towny Advanced 0.90.0.0
_Although I must say, it did not spam this severely on 0.90.0.0. I can provide what it looked like back on 0.90.0.0 on request._

### What is your spigot/craftbukkit version?
Spigot 1.12.2 build 1573-i

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/d3BathPw
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/EhrQpExJ
3. Your townyperms.yml : Uh... can I skip this? I mean, it's not related to the error, however, I'd gladly provide if you request it.
4. Your log's error : https://pastebin.com/thvrC0rU

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
So if you open your db up do you have the tables it says are missing? I'll be honest I don't remember the last time anyone used sqlite or even h2, so if they're broken then it's been broken for a long time.

**Comment by bbayu123** [comment]
All 5 tables are present, as seen in the screenshot below.
![image](https://user-images.githubusercontent.com/26726381/50849449-13466e00-13b2-11e9-814a-ec1765f269c8.png)

**Comment by bbayu123** [comment]
Any fix? The situation is getting worse, the spam is lengthening... and for some reason, the "backup" process is now taking over 40 minutes...

**Comment by LlmDl** [comment]
For now, use h2, flatfile or mysql instead of sqlite.
