### ISSUE TITLE
Add SHULKER_BOX to default config switch list/Add CHORUS_FRUIT to itemuse default

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#3152]
Add DAYLIGHT_DETECTOR to switch also

**Comment by RubenStryker** [comment]
Help, you can not protect the shulkers without color

**Comment by SharkDice** [comment]
Yeah I'm having this issue as well where players cannot protect shulker boxes without colour.

**Comment by LlmDl** [comment]
This is something you can add yourself as long as you have the 1.13 build from teh 1.13 channel on teh discord.
