### ISSUE TITLE
Strange behaviour/bugs

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3153]
There are two main issues that have come to my attention recently.
1) Anyone can break any block anywhere. However, it doesn't drop anything, it regens after a few seconds. it doesnt always regen as the correct block though. For example, if someone breaks a quartz pillar block, it will regen as a quartz block a few seconds later.
2) Random players will lack the perms needed to do things, like /t spawn, after an unknown amount of time online. For t spawn, it will say "[Towny] Town spawn travel is forbidden." If they relog, this #2 issue is fixed. https://imgur.com/a/tPLOfAW
3) Also as a side note, I appear unable to make nationzones a thing. Is that because people have full perms to the wilderness? They shouldn't be able to break in wilderness chunks near the claim of towns in nations correct?

### What steps will reproduce the problem?
1) Nothing. It's constant for the block breaking.
2) Unknown. I don't know if doing a certain action triggers it or if being online for x amount of time triggers it. But it has been a random player now and then from different towns. Some have been online for 10 minutes, others a few hours. 

### What is the expected output?
Not able to break anywhere/not perm glitched.

### What is your Towny version?
v0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
https://imgur.com/a/71ly4fb

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/2TyJYH4r
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/jqqvZqFF
3. Your townyperms.yml : https://pastebin.com/B3PhtJ5K
4. Your log's error : None

(optional) If this is to do with permissions, 
5. Your permissions file : Using plugin LuckPerms. here is the default groups perms file. https://pastebin.com/naKY3tnM

**Comment by LlmDl** [comment]
You've turned on a very old, unsupported feature:

```
  # The amount of time it takes for a protected block to regenerate.  Use zero for no delay.
  regen_delay: 10s
```

Set that to 0 and your problem will vanish. I should really remove this config setting entirely because all it does is cause the exact same strange problem you've just had.
