### ISSUE TITLE
Issues with fire not working?

### ISSUE THREAD

**Issue by Dracathio** [TownyAdvanced/Towny#3154]
So yea I'm not getting the proper bonuses in town blocks, and people are realizing that they can't keep netherrack lit without having fire spread turned on.

It should be saying: Town Size: 248/375 not Town Size: 248/286
### What steps will reproduce the problem?
1. Place down netherrack
2. Get flint and steel
3. Light netherrack
4. Light instantly goes out.....

### What is the expected output?
1. Light doesn't go out o . O

### What is your Towny version?
Do not say "latest".

0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".

the last 1.12.2 release of it.  No clue the exact version.  Sorry.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Latest log apparently doesn't show last start up due to server being up for a good 12 hours now.
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/XA8GhENG
3. Your townyperms.yml : https://pastebin.com/EikXgYMy
4. Your log's error : there wasn't one.

Also... um suggestion?

Could we please have another ratio choice?

(ratio * num of residents) + town level = default town block limit

going either town level or ratio isn't how I'd really like to do things.  Though it seams like a nice idea and all... it really isn't... though for now I may just be forced to go it that route.

Also... your IRC for towny?
Has my net provider banned, my net traffic goes through longlines, which is banned on your ban list.  Nothing would allow me to use IRC because the path to my home network and the path out of my home network goes through that provider before getting to the information I am viewing on the internet.

**Comment by LlmDl** [comment]
Ok lets go over the townblock thing first, the town_levels amount is not used if the town_block_ratio is more than 0:
```
  # The maximum townblocks available to a town is (numResidents * ratio).
  # Setting this value to 0 will instead use the level based jump values determined in the town level config.
  town_block_ratio: '8'
```
How many people are in the town?

**Comment by LlmDl** [comment]
And I've unbanned longlines on the IRC, hopefully that doesn't become a problem.

**Comment by BeeRando** [comment]
I have the same issue of people not being able to place fire. It just started happening recently so I'll see if its one of the recent changes I made. However I can still light obsidian on fire.

**Comment by LlmDl** [comment]
@BeeRando There's always been a bypass for fire on obsidian, so that people can light portals where firespread is off. I should add one for netherrack so people can use it for fire-decorations without have to toggle on firespread.

**Comment by LlmDl** [comment]
I think we covered everything else in the IRC so I'll close this ticket.
