### ISSUE TITLE
Suggestion: Per channel timers

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3158]
An option to add to the channels.yml an option under each chat channel that reads something like
#This is the number of seconds that you must wait between messages before speaking again
Timer: 0

So basically the current chat timer that's in towny, except instead of having it server wide for everything, I can have it be different times for different channels. I could have for example maybe a 10s timer for global, maybe a 0s timer for townchat.

Also, an idea to add a timer bypass permission, to ignore the setting.

**Comment by LlmDl** [comment]
And done as of 0.63: https://github.com/TownyAdvanced/TownyChat/releases/tag/0.63
