### ISSUE TITLE
Suggestion: Nation additions

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3159]
So these are some general upgrades/addition ideas to nations to make them even cooler to join and provide more incentive. 

1) Nation jail. this will do a few things.
 - Let the nation owner/ranks jail ANYONE in his nation. For example, the nation owner can jail the leader of one of their towns, that are within their nation, or a player from any of the towns in their nation.
 - The ability to override town jails. For example, lets say there's a nation called Rome, and in it is a town called Carthage. If the nation owner does /n jail override true(or whatever), than if someone dies in Carthage, instead of getting sent to the Carthage jail, they get sent to the Rome jail.

2) Nation wide enhancements
(All of these features add more "upgrades" to work towards, in addition to the current bonuses in the config, being the more people you have the more benifits you get)

 - Paid nation bonus land: An option to do for example, /n buy bonus 1. Doing this would give 1 bonus power to all towns in the nation
 - Paid nation bonus outpost: an option to do for example, /n buy bonusoutpost 1. Doing this would add 1 bonus outpost to all towns in the nation. This feature could also be copied over to towns. /t buy bonusoutpost 1, allowing it to increase its max outpost limit.
 - A nation wide discount: /n buy discount 5. This would mean the nation discount on claiming land, and buying an outpost is now 5%. doing the command again, /n buy discount 1, would raise the discount to 6%. There'd be a max discount amount in the config, for example no higher than 10%, and a price for each number, for example, each 1% costs 1,000. This would make joining nations super appealing, as it now makes it cheaper to expand for all towns within said nation.

**Comment by bonnedav** [comment]
I think this would add a bit more of a point to nations and, intensive for players to make them, even on servers were war is not enabled.
I would like to see this implemented.

**Comment by DeadGlamour** [comment]
I like the ideas, but the first 1 prob not, I really dont like the idea of the nation owner having unlimited powers.
