### ISSUE TITLE
Suggestion: Add banned-commands list for jailed players.

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3160]
When someone gets jailed, all they have to do is /spawn (cmi plugin) to escape. They can also do other commands like tpa, and so on. Perhaps make a section in the config to deny certain commands while jailed.

All info (server version, towny version, etc) same as my last bug post
https://github.com/TownyAdvanced/Towny/issues/3153

**Comment by LlmDl** [comment]
Don't know what happened but I did (try to) make a comment earlier.

We already block teleports of players where the teleport is based on a command being used. Can you pastebin.com your CMI config for me please.

**Comment by BeeRando** [comment]
CMI Config
https://pastebin.com/maFCzFad

**Comment by BeeRando** [comment]
I dont know anything about all that. I'm not a coder myself. Just that people can tp while in jail. Sorry I can't be more help!

**Comment by LlmDl** [comment]
This is now a thing as of https://github.com/TownyAdvanced/Towny/commit/c7e874b2b42d1544c21cb2078d3a4c8d3ae9fea7 and will be part of 0.94.0.17.
