### ISSUE TITLE
Bug: Chat randomly stops working for players

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3163]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

Basically, after a while a player wont be able to speak in 

### What steps will reproduce the problem?
Nothing. Chat will just randomly stop working for a player.
https://imgur.com/a/mlhjRfv

### What is the expected output?
Being able to speak normally.

What is your Towny version?
v0.93.0.0

What is your spigot/craftbukkit version?
Do not say "latest".
https://imgur.com/a/71ly4fb

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

Your full server startup from the logs\latest.log : https://pastebin.com/2TyJYH4r
Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/jqqvZqFF
Your townyperms.yml : https://pastebin.com/B3PhtJ5K
Your log's error : None

**Comment by LlmDl** [comment]
Do you still see this happening some times?

**Comment by Momshroom** [comment]
We had this same issue.  It seemed like players were sometimes stuck in local chat on login (even though toggling it said put you in general).  Adding explicit permission for the general chat to the default group fixed the issue for us.

**Comment by LlmDl** [comment]
It telling you you're joining a channel, but joining a different channel instead is probably related to this bug: https://github.com/TownyAdvanced/Towny/issues/3171

**Comment by LlmDl** [comment]
Default chat channel was also fixed in the commit that fixed the channel name ticket above. Pretty sure this wont be an issue.
