### ISSUE TITLE
Bug: add ignoreplots & constantplotborder to /res toggle and /res set mode help pages.

### ISSUE THREAD

**Issue by MidnightSugar** [TownyAdvanced/Towny#3164]
I suggest adding a command allowing residents to toggle notifications in chat. It could be **/res toggle notifications**.

This would make chat less spammy for those people that do not need to see them.

**Comment by LlmDl** [comment]
This was already a thing, but not documented properly in the in-game command or on the website.

**Comment by LlmDl** [comment]
Fixed the other missing help bits.
