### ISSUE TITLE
Suggestion: town/nation mute command

### ISSUE THREAD

**Issue by bonnedav** [TownyAdvanced/Towny#3165]
Add a command for mayors/kings to mute residents in there own town/nation chat.
Like /t toggle mute [player] and /n toggle mute [player].
The player can be un-muted the same way.
Residents also become un-muted form town chat by leaving there town and from nation chat by leaving there town or there town leaving the nation.
Also add an admin command to un-mute anyone.
Also make sure the mute has a permission node that can be given to other town/nation ranks.

**Comment by bonnedav** [comment]
Any update on this?

**Comment by LlmDl** [comment]
Haven't looked into this one too deeply, but I have a feeling it isn't super easy to implement into TownyChat.

**Comment by bonnedav** [comment]
Why not? It already has mute right?
