### ISSUE TITLE
Suggestion: Collate Post-TaxCollection messages

### ISSUE THREAD

**Issue by TheFlagCourier** [TownyAdvanced/Towny#3167]
**Current Functionality**: 
![lang](https://user-images.githubusercontent.com/2712890/52140815-690cdf80-2619-11e9-94c7-b6efde67e3ab.png)

```
msg_del_nation: '&bThe nation %s was disbanded!'
msg_del_resident: '&b%s lost all his Towny data!'
msg_del_town: '&bThe town of %s fell into ruin!'
```

**Suggested Functionality**:
To combine the functionality into a single output so as not to flood the chat. Each sub-field should only print if it has data entries to print.
Current strings (such as msg_del_nation) should continue to be used for single-subject printouts, as in wartime events.

Example:
```
msg_new_day_tax ('&bA new day is here! Taxes and rent have been collected')
msg_del_residents_tax ('The following player(s) have lost their towny data'):
    %ArrayOfPlayers% (Notch, Jeb, etc.)
msg_del_towns_tax ('The following town(s) have fallen to ruin'):
    %ArrayOfTowns% (Town1, Town2, Town3, Town4, etc.)
msg_del_nations_tax ('The following nation(s) disbanded'):
    %ArrayOfNations% (Nation1, Nation2, etc.)
```

Example without bankrupt players:
```
(!) New Day (!)
Towns Foreclosed:
    Smallville, Junkertown, Atlantis
Nations Fallen:
	Polis of Atlantis (Could use msg_del_nation in this instance instead of the array)
```

**Extra:**
Add ability for residents to opt out of seeing these messages (/res toggle alerts)

**Comment by LlmDl** [comment]
- [ ] Do nation/town upkeep messages

- [ ] Do language files

- [ ] Do resident tax

**Comment by LlmDl** [comment]
Complete as of https://github.com/TownyAdvanced/Towny/commit/cd0c8ae2cd32f7b2abc5bdf5b36fa098df5a5394

Will be a part of 0.94.0.4

Before:
![2019-07-27_12 15 13](https://user-images.githubusercontent.com/879756/61997727-c1261b00-b06b-11e9-9bfe-a82b56043845.png)

After:
![2019-07-27_12 17 12](https://user-images.githubusercontent.com/879756/61997730-c84d2900-b06b-11e9-8560-5adc7c2fb7a9.png)
