### ISSUE TITLE
persistent ranks

### ISSUE THREAD

**Issue by RubenStryker** [TownyAdvanced/Towny#3170]
Users recover the range of towny when the server stops and starts again.
It seems that the changes are not saved in the plugin

### What steps will reproduce the problem?
1. You take away assistant rank from a user who was already an assistant for a long time
2. Restart the server (No -> /restart) / stop and start script
3. The user returns to the range that was removed

### What is the expected output?
1.
2.
3.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Spigot 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : - It is not appreciated -
2. Your Towny config.yml: https://pastebin.com/EFwHSUqF
3. Your townyperms.yml : https://pastebin.com/c6FAKZsZ
4. Your log's error : - It is not appreciated -

(optional) If this is to do with permissions, 
5. Your permissions file : We use LuckPerms and we already have some failures related to towny
https://github.com/TownyAdvanced/Towny/issues/3123
https://github.com/lucko/LuckPerms/issues/1330

**Comment by LlmDl** [comment]
This is just teh same as the other ticket you submitted, which traced back to an issue with LP caching.
https://github.com/TownyAdvanced/Towny/issues/3123

**Comment by RubenStryker** [comment]
No friend, this has nothing to do with LP.

I choose a user with rank (towny rank) -> I remove the rank of towny -> (the user was disconnected) -> I download the towny files.

- Town data (Name of town)
- Affected user (Name of user)

And I see that the user retains the range in its configuration and in the configuration of the city.

I miss it so much that it is for LP, I do not understand that it saves the LP of this

**Comment by LlmDl** [comment]
I'll check it out then.

**Comment by RubenStryker** [comment]
Any advance?

**Comment by LlmDl** [comment]
This was fixed, maybe a little while ago. We now handle offline rank changes properly.
