### ISSUE TITLE
Changing channels doesn't always report proper channel you've joined.

### ISSUE THREAD

**Issue by RubenStryker** [TownyAdvanced/Towny#3171]
### What steps will reproduce the problem?
1. You are in the general channel
2. Switch to any other channel, example admin using /a (A message tells you that you are on that channel)
3. You get distracted and put back /a (A message tells you that you are on that channel)
4. However, you find yourself talking in general.

### What is the expected output?
1. That you speak in the channel that tells you
2. and if you deactivate the channel, taking you to general ... to let you know

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Spigot 1.13.2

**Comment by LlmDl** [comment]
Fixed as of TownyChat 0.54
