### ISSUE TITLE
Towny allows building in otherwise restricted areas

### ISSUE THREAD

**Issue by MyHatStinks** [TownyAdvanced/Towny#3173]
As per #3027 the only way to prevent an area being claimed is to create a Towny town over it. This isn't an issue in and of itself, the issue is that Towny completely overrides any permissions that would otherwise affect that area.

### What steps will reproduce the problem?
1. Create a Towny town with build permissions enabled.
2. Create a more restricted region (eg with WorldGuard) overlapping the Towny town.
3. Attempt to place a block. Towny's Allow permissions will override anything else.

### What is the expected output?
1. More restrictive permissions should always have priority unless explicitly configured otherwise.

### What is your Towny version?
`0.93.0.0`

### What is your spigot/craftbukkit version?
`1.13.2` (Latest build as of 2019-01-31)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/g97C1g3f
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/9fnpkQTx
3. Your townyperms.yml : https://pastebin.com/cB3uXig1
4. Your log's error :  N/A

**Comment by LlmDl** [comment]
This issue was resolved on the IRC, a result of either bperms2 or WG caching something.

For future-readers, when setting up a WG spawn area that has a Towny town in place to prevent people claiming inside of the WG area, the permissions of the town should be set to allow everything using 
```
/town set perm on
'''
and then making sure that plots have the perm line b=RAO d=RAO s=RAO i=RAO.

This will keep towny from preventing any of the above things, while WG will do the protecting.
