### ISSUE TITLE
[suggestion] Allow us to sort "/n list" by different parameters

### ISSUE THREAD

**Issue by johnyuki** [TownyAdvanced/Towny#3174]
Currently, _/n list_ only displays top nations sorted by number of residents. It would be good to see this command have a parameter added so that we can choose from the following:

- [x] Highest bank balance.
- [x] Highest number of towns.
- [x] Chunks claimed (All town sizes added up).
- [ ] Active members (This could be calculated by members that have logged on in the last week).

The same would be good to see for towns and players too.

**Comment by LlmDl** [comment]
This is done except for the nation by chunks claimed.

**Comment by LlmDl** [comment]
Chunks claimed is now a thing as of https://github.com/TownyAdvanced/Towny/commit/332c29c19691f831d127d93e8364b51b3d7cdf9b

The active residents is just too much searching I feel. Going through every nation or every town (possibly much more residents depending on how much nations get used) on a server, checking how many residents logged in less than a week ago, then comparing it over each nation to nation or town to town, would probably end up being a very slow process/laggy. 

So instead I did add /n list by online and /t list by online here https://github.com/TownyAdvanced/Towny/commit/254f7e031590e213e8a8c153e4ed9e55300d5bed which will show how many are active right then.
