### ISSUE TITLE
Error related with DungeonsXL (PlayerChangedWorldEvent)

### ISSUE THREAD

**Issue by Segysmundo** [TownyAdvanced/Towny#3178]
Getting this error when disconnecting while in a dungeon world instance created by the plugin [DungeonsXL](https://www.spigotmc.org/resources/dungeonsxl.9488/) that teleports me out of the world when completing/leaving the dungeon and I suppose it does the same when disconnecting while inside it.

### What steps will reproduce the problem?
1. Install Towny.
2. Instal [DungeonsXL](https://www.spigotmc.org/resources/dungeonsxl.9488/).
3. Create a dungeon world.
4. Enter to play the dungeon world (It creates an instance of the world).
5. Disconnect from server.

### What is the expected output?
1. I guess when disconnecting it should teleport my player out of the world without giving out the error.
2. The error doesn't show up when Towny isn't installed.

### What is your Towny version?
- Tested on **v0.93.0.0** and **v0.93.0.4**

### What is your spigot/craftbukkit version?
- Spigot 1.13.2-R0.1

1. [Server startup](https://pastebin.com/vHqLtYPM).
2. Default config.
3. Default townyperms.
4. [Error log](https://pastebin.com/7fzKz52F).

_**From DungeonsXL dev:**_
![image](https://user-images.githubusercontent.com/19178945/52396809-6e53a980-2ab3-11e9-8fb2-088eb1453181.png)

**Comment by LlmDl** [comment]
I'm curious as to whether this still happens when you use the prerelease of 0.93.1.0 that is on the discord #new_builds channel.

**Comment by Segysmundo** [comment]
An error still shows up, I'm using Paper 1.13.2 this time, although it shouldn't make too much of a difference.

Using **0.93.1.0**
 **[Error](https://pastebin.com/WmCGFp3a)**

**Comment by LlmDl** [comment]
Made this go away. Players being moved were actually offline.

**Comment by Segysmundo** [comment]
On what version of towny is this fixed?

**Comment by LlmDl** [comment]
Thought what we were doing to fix this would work but I'm guessing there's a bit more to it.

https://github.com/TownyAdvanced/Towny/commit/c8664f3b51cec8b630fc66d9b1c7dbc404680a92 should keep the error quiet from now on, since it's harmless it doesn't matter much.
