### ISSUE TITLE
Suggestion: Jail additions

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3180]
A few features to suggest for jails

The first is different bails depending on the person. A town leader is more valuable than a town member, and a nation leader even more so. So perhaps the ability to set different bail prices. A bail price might be good for regular players, but super super cheap to the point it means nothing to town/nation owners. And vice versa, a bail based on the wealth of nation/town leaders might be incredibly too high for regular players. So, make 3 different options

Different bail costs
- [x] Regular bail cost: x
- [x] Town leader bail cost: x
- [x] Nation leader bail cost: x

~An option to set a maximum jail time. This would prevent abuse, and afford an escape for those who can't afford the bail/can't get friends to offer them the money. When the time is reached, the player is released from jail.~ Covered in #3232 

An option to make jailed individuals invincible. For exmaple, there can be jail abuse. Someone places lava in the jail and the jailed player is forced to constantly respawn to their death in the cell. For some servers, like where escape methods are available, escaping is super cool, but for ours, with tnt and such not enabled, it's not really a possibility. So this option would just help non-greifable servers prevent jailed player abuse. 
Also to prevent abuse, perhaps this would only apply to non-town members, so that people dont just jail their own town members to make them invincible. 
 - [ ] Invincible jailed: true/false

An option for a town to set its own bailcost. Like the public spawn cost, the price set in the config would be the maximum bail price.
 - [ ] /t set bailprice x

**Comment by LlmDl** [comment]
First three done as of https://github.com/TownyAdvanced/Towny/commit/b742d81bccf561b5144c2afcfc57b7690ab7cea7 and part of 0.95.0.4

**Comment by LlmDl** [comment]
The invincibility does seem very abusable. Not very hyped on the ability to alter the bail prices either, because with the 3 different bail costs almost means you need to allow all three to be set, meaning we have to save 3 new values in each town.

**Comment by LlmDl** [comment]
I'm going to close this, the invincibility doesn't really seem feasible. Even limiting it to just non-townmembers could go wrong when two towns decide to team up and jail each other to stop someone raiding their towns.

Setting bail doesn't seem like it is very important now that there's three bail costs.
