### ISSUE TITLE
Suggestion : Tax Overhaul

### ISSUE THREAD

**Issue by Faunsce** [TownyAdvanced/Towny#3181]
- Nations
   - Upkeep
     - [x]      Per Plot upkeep modifier (the plots of all its towns, kinda like the one for towns)
     - [x]      Per Town Tax
     - [x]      Per Resident Tax(all towns residents)

   - Tax
     - [x] % Tax
     
- Towns
   - Tax
     - [ ] PerPlotTax, but actually per plot, allows making (High Rent) plots
     - [ ] PPT but % instead of flat as an option

**Comment by LlmDl** [comment]
The per-town nation upkeep is a thing now.

**Comment by Faunsce** [comment]
Awesome!

**Comment by LlmDl** [comment]
Nation per-resident tax is handled via the nation_level's upkeep modifier.

**Comment by LlmDl** [comment]
Nation tax percent was added in 0.98.4.0.

I don't think I'll be implementing a per-plot-tax. A similar thing can be achieved by using plot groups to make high-value plots.
