### ISSUE TITLE
Bug: Town spawn cost doesn't impact allies

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3182]
When a nation member teleports to a public town spawn that has a tp fee, they aren't charged the spawns public spawn cost. For example

outsider - /t spawn rome
 ^ They're charged 5 coin

Nation member - /t spawn rome
 ^ isn't charged 5coin

### What is your Towny version?
v0.93.0.0

### What is your spigot/craftbukkit version?
https://imgur.com/a/71ly4fb

### Please use Pastebin.com to link the following files:
Your full server startup from the logs\latest.log : https://pastebin.com/2TyJYH4r
Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/jqqvZqFF
Your townyperms.yml : https://pastebin.com/B3PhtJ5K
Your log's error : None

**Comment by Acramus** [comment]
Hello, I think I found your problem:
![image](https://user-images.githubusercontent.com/26900294/55586077-183b6500-56f6-11e9-9d65-e07f80bd8178.png)

In your Towny config.yml you have town spawn travel set to "0.0" under the economy settings.

**Comment by Acramus** [comment]
Also in your permissions.yml file within the towny file system, add the towny.nation.spawn.public to your 
![image](https://user-images.githubusercontent.com/26900294/55586383-d19a3a80-56f6-11e9-99c1-607fff443d97.png) nation's default section.

**Comment by LlmDl** [comment]
Good catch @Acramus
