### ISSUE TITLE
Suggestion: Add support for permission plugin

### ISSUE THREAD

**Issue by wsman217** [TownyAdvanced/Towny#3184]
I would like to suggest that support for the permission manager LuckPerms be added to the TownyChat plugin so that chat is not edited by TownyChat but LuckPerms.

**Comment by LlmDl** [comment]
I don't really understand what you mean. Can you explain what is not happening now, or what you want to have happen.

**Comment by wsman217** [comment]
Sorry I might be misusing the plugin not sure but the permuserprefix does not work with LuckPerms

**Comment by wsman217** [comment]
Also it does not seem that when I disable the modify chat that it works and im assuming that its because of the LuckPerms but not totally sure

**Comment by LlmDl** [comment]
I haven't looked at whether LP supports user and group prefixes like the older permission plugins do. 
{permsuffix} and {permprefix} are the two main things that I would think would work (if LP does prefix/suffix.

Again, I'm not really sure what you mean when you say "it does not seem that when I disable the modify chat that it works," Can you explain what isn't working exactly?

Generally modify_chat should be left on true, if you're using TownyChat, it is to have the chat be modified.

**Comment by wsman217** [comment]
Ok the found out the perm prefix was my fault except that it is lowercasing the prefix is there a way to fix this and if the modify_chat has to be used to get the [g] and other channel names on there i need to keep that

**Comment by wsman217** [comment]
Also perm prefix does not include parenthesis in it if you have it set similar to &8(&5Owner&8)

**Comment by LlmDl** [comment]
Can you pastebin.com your permission file so I can see what you're configuring where please.

If you want the channel names to show in the chat line, configure their tags in the channels.yml.

**Comment by wsman217** [comment]
https://pastebin.com/bWCNX4dh
There is the pastebin what I am mainly worrying about right now is the fact that the Owner tag does not get capitalized when printed in the chat by TownyChat.

**Comment by LlmDl** [comment]
Ok, can you pastebin.com your permission file so I can see what you're setting and use it for testing please.

**Comment by wsman217** [comment]
are you needing my luckperms permission file?

**Comment by LlmDl** [comment]
yes
