### ISSUE TITLE
Interactions with new 1.13.2 blocs

### ISSUE THREAD

**Issue by SamuDu24** [TownyAdvanced/Towny#3185]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?

**To meet the problem you have to be in a protected area by Towny, for me a world. The problem is related to the interaction with pressure plates, buttons, and trapdoors. Destroying and posing does not work, which is normal for the player since he does not have the required permissions. But the player can interact with the elements mentioned above that would have been added in version 1.13.2. So we see that Towny has not been updated to be compatible with the new blocks of 1.13.2 ...**

### What is the expected output?

**A disaster in the cities and in the world, since the players can "ruin" the constructions by putting in the bad positions the trapdoors. For builders, it's pretty problematic.
Here is a video example of the problem (in French, captured by a moderator of my server):**
https://www.youtube.com/watch?v=AkonpINXeqs&feature=youtu.be

### What is your Towny version?

**Towny version: 0.93.0.0**

### What is your spigot/craftbukkit version?

PaperSpigot: git-Paper-525 (MC: 1.13.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log :
https://pastebin.com/DeXc3fst

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/wSg1gw5a

3. Your townyperms.yml :
https://pastebin.com/YkBVDYxe

**Comment by LlmDl** [comment]
You need to be using the 1.13 builds of towny (0.93.0.4) The names of some items changed. Join the discord and check out the 1.13 builds channel.
