### ISSUE TITLE
revert_on_unclaim set to false yet still reverting town in ruin

### ISSUE THREAD

**Issue by Xenthyk** [TownyAdvanced/Towny#3187]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Create a town
2. Let it fall into ruin
3. It starts to regenerate

### What is the expected output?
1. With the enabled flag set to false I expect it to keep the town as is but the player would need to setup a new town if they want to continue building there. 
2.
3.

### What is your Towny version?
Do not say "latest".
version: 0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Did you turn off the revert in the config instead of using /tw toggle revertunclaim, which turns it off in the world?

**Comment by Xenthyk** [comment]
I did turn it off in the config about a week ago and just had a town go into ruin that it started reverting today. Im working on getting the configs up to pastebin.

**Comment by Xenthyk** [comment]
Closed already? The problem isnt fixed

**Comment by LlmDl** [comment]
The config is only the default settings for new worlds. You need to use the command I said or edit the towny\data\worlds\worldname.txt files

The command wont stop a town already reverting. To do that stop the server and delete the towny\data\regen.txt file.

**Comment by Xenthyk** [comment]
Thank you. I will try that :)
