### ISSUE TITLE
Not can make with towny.admin permission plot nfs

### ISSUE THREAD

**Issue by matahombres** [TownyAdvanced/Towny#3192]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Make 2 citys.
2. Join in 1
3. With towny.admin permission can plot fs in you city and plot nfs
4. Go other town
5. Make a plot fs, and make plot nfs
6. Say "plot not is you owner"

### What is the expected output?
1. Plot notforsale

### What is your Towny version?
0.93

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/pgJJ8BtC
2. https://pastebin.com/1Nf8V29g
3. https://pastebin.com/dUgzZ31y
4. Your log's error :

**Comment by LlmDl** [comment]
Fixed as of: https://github.com/TownyAdvanced/Towny/commit/b89cd779e54af3f657d04a93dfbf9878c38bea63
