### ISSUE TITLE
Suggestion: Town Merging.

### ISSUE THREAD

**Issue by jackstrosahl** [TownyAdvanced/Towny#3193]
A town could use this command to annex another.  Upon the other town accepting, all of the plots and residents from the annexed town would be transferred, including nation/town ranks if still applicable.

I've poked around the source a bit and my attempts to manually transfer residents/plots without unclaiming/reclaiming and kicking/joining haven't worked out.

**Comment by LlmDl** [comment]
There's actually a /townyadmin command for this purpose on a plot-by-plot basis. Nothing that would absorb an entire town though.

**Comment by Faunsce** [comment]
Im new to programming but in a sense couldnt a pairs() type function just run through the list of the "annexed town" and that apply everything that way ex
*player 1*
*store rank, add to plots they owned [already transferred], log perms*
*remove from town*
*add to passed in name of town*
*add ranks and perms etc back to player*
*move onto next*

**Comment by Faunsce** [comment]
If i knew java id write a framework for you but if you want my idea of i could maybe do some psuedo code? @LlmDl . But, you're probably exp enough that you already know how youd do it. just lemme know if you want it though.

**Comment by Faunsce** [comment]
Nevermind, ill just share it anyways, there's no reason not to. This is oversimplified and actually modularized but would in essence work and could be done by someone here or yourself in maybe an hour or less?
```cpp
transferTown()
{
	//Store plots
	//Ask old mayor what happens to money in bank (to new town bank, his pocket, split among town, mix of all 3)
	//Ask new mayor if hed like to carry over ranks, merge ranks containing same privs
	//if no merge then what ranks to what or if that rank simply defaults
	//Ask mayor being annexed which role he would like in new town
	//confirm on annexing mayors end if hes okay with it
	//Run through all plots and store in some form of list
	//attach their type, owner, sub-owner/permitted residents, taxes, etc.
	//run through residents, store them in list aswell and attach ranks and other imp info
	//Store the last bits such as money and how many bonus plots were added (add the bonus to the other towns bonus, but not their cap
	//after storing everything check if the reset on unclaim in enabled, disable it if enabled before next step, quadruple check just in case
	//dissolve town
	//add each resident to new town and give new ranks
	//move ownership of plots and attach all their info that was stored to new town
	//possibly add to a town stat [Towns Annexed : 0], or even a list so /town ThisTown Annexed [Alias: /t here ann] 
}
```

**Comment by LlmDl** [comment]
You have the gist of it, but it's a fair bit more complicated than that. It is probably fairly close to the code we use for renaming towns, but in this case we would be changing the name to the annexing town.

**Comment by jackstrosahl** [comment]
Good point about being similar to renaming.  I've gotten it working, hopefully PR soon

**Comment by jackstrosahl** [comment]
Here's my attempt.  It's not perfect and especially I need to figure out how to use an invite to accept/deny the annex. Not sure if should PR without that.
https://github.com/jackstrosahl/Towny-PRs/commit/7d56de2910119e80d6cb5271a0a70d4cafeffe2f

**Comment by LlmDl** [comment]
Left you some comments to work on.

**Comment by Faunsce** [comment]
While it may be similar, im sure the asking where what goes and to whom is what will make this command alot more complex seeing as it does have to do the money and ranks stuff. Glad you were able to get a prototype up! @jackstrosahl . Gl man.

**Comment by FutureLemon** [comment]
I would like this a lot for neighbouring towns but there should be a way to not exceed the maximum amount of residents and claims.

**Comment by BlueFyreMatt** [comment]
In an attempt to avoid opening useless issues, there isn't currently a method to force a towns merge through ta, we have a temporary workaround that involves setting a staff member as the towns mayor and performing the merge that way, but townyadmin doesn't have a command for it. 

Any chance you could add that? @LlmDl
