### ISSUE TITLE
Towny Permissions & Console Error

### ISSUE THREAD

**Issue by stickmenz2** [TownyAdvanced/Towny#3195]
### What steps will reproduce the problem?
1. Players in towns and nations seem to be able to change their town or nation admin permissions
2. Players who are not admins can change all the settings of their towns (such as setting mayor or king)

### What is the expected output?
1. Players should not be able to change these settings

### What is your Towny version?

0.93.0.0

### What is your spigot/craftbukkit version?

Spigot 1.13.2-R0.1-Snapshot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/pURBB4tM
3. Your townyperms.yml :  https://pastebin.com/RibDWckk
4. Your log's error :  https://pastebin.com/d0wyvvRq

**Comment by LlmDl** [comment]
Pastebin.com your permission plugin's permission file.

**Comment by stickmenz2** [comment]
Okay.  Using LuckPerms.  Unable to paste the contents of the maven file, but can link this:

https://luckperms.github.io/editor/#uVoliVDAiJ

**Comment by LlmDl** [comment]
which rank should I be looking at?

**Comment by LlmDl** [comment]
Nevermind, your default rank has a bunch of towny nodes in it. The only node you need to give in luckperms is the towny.wild.* node if you want players to have full reign over teh wilderness. Remove every other node from towny from luckperms. All the towny nodes are already given out in the townyperms.yml file.

**Comment by stickmenz2** [comment]
I feel terrible for wasting your time.  I thought I needed the towny perms inserted.

What about the error that is pushing to console? 
https://pastebin.com/d0wyvvRq

**Comment by LlmDl** [comment]
If that shows up only when a new player joins the server for the first time, then it is a byproduct of having a plugin set your server spawn. You can avoid it by setting the server spawn to where the plugin has your spawn set. 

Otherwise it's probably got something to do with player moving to a corrupt spot while using the perm hud.

**Comment by stickmenz2** [comment]
Nope.  No new players joining.  A corrupt spot? hmmm

**Comment by LlmDl** [comment]
It just means that some of teh data needed to make the perm hud appear correctly wasn't there. It's not a critical error and it doesn't mean your towny data has problems.
