### ISSUE TITLE
URGENT: Bug with UTF-8 symbols and Towny 

### ISSUE THREAD

**Issue by Daphsquid** [TownyAdvanced/Towny#3197]
Hi there! 

We found a bug in Towny regarding "special" characters such as "❤" being used in Towny messages. When used, there are console errors which spam extremely fast (our logs file was 4GBs+ by the time we found it, less than an hour after it started occurring). We are using MySQL for data storage. 

### What steps will reproduce the problem?
1. Create a Town (/town new name)
2. Claim a piece of land (/town claim)
3. Stand on the piece of land and type something along the lines of "/plot set name I ❤_J+L's Area_❤ I" (This is the exact command that produced the errors on our server.)
WARNING: The console will spam with errors extremely fast. 
Screenshot of the error from our server: https://i.imgur.com/up5DnJa.png

### What is the expected output?
1. The plugin should block special characters from being used in plot names, however, using this command, it seems not to. 

### What is your Towny version?
Do not say "latest".
[00:34:04 INFO]: Towny version 0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 1.13.2 #544

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 
I can provide any of these required files in PM, if they are necessary to fix this issue (I don't believe they are). Feel free to friend me on Discord and I can do that: Daphsquid#0001 :)

(optional) If this is to do with permissions, 
5. Your permissions file : Not an issue related to permissions. 

(optional) If this is to do with chat,
6. Your chatconfig.yml : Not an issue with chat.
7. Your channels.yml : Not an issue with chat.

NOTE: If any other server owners are having an issue with this, we have created a "bandaid" fix. This plugin has the ability to filter all special characters from commands (with a whitelist). We quickly wrote this plugin to prevent this issue from being abused on our server.
https://github.com/ShadowKingdomMC/ShadowCommandFilter

Thank you,

**Comment by LlmDl** [comment]
pastebin.com your config and startup like the form asked for

**Comment by Daphsquid** [comment]
> pastebin.com your config and startup like the form asked for

I can do this for you! Would you mind adding me on Discord so I can PM you these files? Or any other private means of communication works (we just don't want to post it publicly, I'm sure you understand). @Daphsquid#0001 is my Discord

**Comment by LlmDl** [comment]
Join the IRC, and show me the files. I don't use Discord often.
