### ISSUE TITLE
Default "r--" plot setting while leaving towns.

### ISSUE THREAD

**Issue by Srborjaa** [TownyAdvanced/Towny#3199]
### What steps will reproduce the problem?
1. Claiming a plot like a normal resident.
2. Leaving the town.

### What is the expected output?
1.  When doing /plot perm:
![imagen](https://user-images.githubusercontent.com/29895095/54209698-81a4cb00-44de-11e9-8188-a27bea3dbaf3.png)

The problem is that when a user leaves a town, their plot gets the permissions ON for residents:

![imagen](https://user-images.githubusercontent.com/29895095/54209923-e19b7180-44de-11e9-8b52-b1e40ce51070.png)

**The Towny and Server software are:**

Towny 0.93.0 and PaperSpigot 1.12.2

I don't paste any pastebin because we haven't experienced any error in the console.

**Comment by LlmDl** [comment]
Skipped form.

I need to see the config and the towny\data\towns\TOWNNAME.txt file on pastebin.com
