### ISSUE TITLE
Stop permHUD failure appearing in log.

### ISSUE THREAD

**Issue by FuneralSuits** [TownyAdvanced/Towny#3202]
I've been getting this error:
https://pastebin.com/QV1EsNAy

I have no idea the cause or what makes it happen, let me know if you need any other files or have questions. Thanks!

Towny Version 0.93.0.0
Paper Spigot Version 559 (1.13.2-R0.1-SNAPSHOT)

My Towny Config:
https://pastebin.com/VcmidpJS

**Comment by LlmDl** [comment]
The startup pastebin.com'd would probably be helpful in this case. 

Does it happen only when new players join or all the time or what?

**Comment by FuneralSuits** [comment]
Here's my startup log:
https://pastebin.com/YynRpFUX

And no, I haven't be able to determine any pattern to when the errors happen but they aren't constantly occurring.
I'll let you know if I notice any patterns or connections or when the errors take place.
Thank you!

**Comment by LlmDl** [comment]
Last time I recall seeing something like this it was when players who had the permHUD activated were changing worlds. It's harmless however it is happening. I can probably do something about making it fail silently though so your log doesn't get affected.
