### ISSUE TITLE
Sometimes permissions do not apply.

### ISSUE THREAD

**Issue by B4TT3RY** [TownyAdvanced/Towny#3207]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. World Change
2. /t spawn

### What is the expected output?
1. &cTown spawn travel is forbidden.
2. /ta checkperm {name} towny.town.spawn.town -> Permission false

### What is your Towny version?
Do not say "latest".
0.93.0.5

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
2. Your Towny config.yml (if using MySQL please remove password,) : `Default`
3. Your townyperms.yml : `Default`
4. Your log's error : `No Error`

**Comment by LlmDl** [comment]
You skipped the startup.

**Comment by B4TT3RY** [comment]
> You skipped the startup.

but my Towny is translated towny, is it ok?

**Comment by LlmDl** [comment]
I'm more interested in which permission plugin you use, but you need to supply the startup.

**Comment by B4TT3RY** [comment]
> I'm more interested in which permission plugin you use, but you need to supply the startup.

OK wait a minute, i'm using on LuckPerms.

**Comment by LlmDl** [comment]
That's a known issue with LuckPerms, it appears that their caching doesn't refresh often enough.

**Comment by B4TT3RY** [comment]
oh not Towny's issues?
I came to know something new. Thank you!
XD

**Comment by LlmDl** [comment]
There's a ticket for it on the LuckPerms tracker, but as far as I know Luck hasn't been shown a reproduce-able bug, because it's not something easily repeated.

**Comment by B4TT3RY** [comment]
thx!
when i print "Permission false", type "/lp sync" then "Permission true".

**Comment by LlmDl** [comment]
Yeah the sync command has to be used to sort it out.
