### ISSUE TITLE
Fishing error in towny

### ISSUE THREAD

**Issue by Halfhand1** [TownyAdvanced/Towny#3208]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. When my players use a fishing rod in a towny claim

### What is the expected output?
Nothing really happens but I get this error in my console; https://pastebin.com/2huw8Dak

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
spigot 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/bPv8y15k
2. Your Towny config.yml : https://pastebin.com/MBFu9yDL
3. Your townyperms.yml : https://pastebin.com/4bz3QSNX
4. Your log's error : https://pastebin.com/SCQJb2wz

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml : d

**Comment by LlmDl** [comment]
Retest using this build made for 1.13 and let me know if it still causes the error. https://cdn.discordapp.com/attachments/487025202539266048/500317161177219075/Towny.jar

**Comment by Halfhand1** [comment]
Alrighty will do

**Comment by Halfhand1** [comment]
Ok so I added this and it seems to have fixed the issue. I am using towny war on my server though and it seems to be disabled in this version. I was wondering when this will be added.

**Comment by LlmDl** [comment]
Are you talking about Flag War?

**Comment by Halfhand1** [comment]
Yes

**Comment by LlmDl** [comment]
That had to be disabled in order to get the 1.13 compatibility started. I believe there are people who plan to send in Pull Requests in order to maintain Flag War, but I don't do support for it personally. Wait and see I guess.
