### ISSUE TITLE
{townytagoverride} not working correctly

### ISSUE THREAD

**Issue by Swigglezz** [TownyAdvanced/Towny#3209]
Problem description: A few of my players that are not in towns have {townytagoverride} before their names, it is odd because I am not in a town but it does not show it for me? In the config the tag description says it will "falls back to the full name" which it doesn't but only for particular players. Very odd!

### What steps will reproduce the problem?
1. Not exactly sure

### What is the expected output?
1. For players that are not in a town or nation it does not display anything before their name.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
paper-571.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/NJsz2a60
2. https://pastebin.com/mTK8ZaBB
3. https://pastebin.com/2xLGbE0Q
4. https://pastebin.com/gU8AdLJq

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/agPzKb5X 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/X87e37qN
7. Your channels.yml : https://pastebin.com/YPYmfv5v

Images:
https://imgur.com/IvTwCnL
https://imgur.com/c01KRdT
https://imgur.com/rvIICYW
https://imgur.com/vOz7YJn
https://imgur.com/mEugyyX

**Comment by LlmDl** [comment]
So in those screenshots, Glitchbird has no town, but neither do Sabbie and Beef?

**Comment by Swigglezz** [comment]
It’s weird because after some time we all noticed that if you are in a town
that is not in a nation then it displays the tag but as soon as you join a
nation it goes away. As long as normal players aren’t in towns they never
have the tag in front of their names.

**Comment by LlmDl** [comment]
I have just tested this and could not reproduce it. {townytagoverride} is in the default chatconfig, if this were an issue I think it would have been experienced by someone else. Hopefully you can track down what is causing it, if you are still having trouble.
