### ISSUE TITLE
Suggestion: Nation merge

### ISSUE THREAD

**Issue by shirazmatas** [TownyAdvanced/Towny#3210]
On the server that I play on people can create their nations in real life corresponding places. One of the issues that have come up is that a real life nation is split in two (like west germany and east germany) but after some time might warm up their relations again.

However as the cost to create a nation is so high none of them really wants to throw away the money invested. A solution to this would be to add a /nation merge (nation) command.

/nation merge (nation) would then be accepted by the other nation with /nation merge accept (nation) and the nation who initiated with /nation merge gets a configurable amount back of the money.

**Comment by FutureLemon** [comment]
Would love to see the same with town's that border eachother! :)

**Comment by LlmDl** [comment]
And done: https://github.com/TownyAdvanced/Towny/commit/de409c47b85cd76f1b734a9a62e8793e58d7bf18
