### ISSUE TITLE
0.93.0.4: NPE showing in (probably) reverting plot snapshots, should fail silently.

### ISSUE THREAD

**Issue by Halfhand1** [TownyAdvanced/Towny#3211]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Not sure but I think its when players are doing things within town claims

### What is the expected output?
1. https://pastebin.com/ECHUsiFa , https://pastebin.com/WWyhjsN8

### What is your Towny version?
Towny v0.93.0.4

### What is your spigot/craftbukkit version?
spigot 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/SvY7vdrZ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cQYNwEGT
3. Your townyperms.yml : https://pastebin.com/CqitfyVk
4. Your log's error : https://pastebin.com/ECHUsiFa , https://pastebin.com/WWyhjsN8

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I think this might be what happens when the revert-on-unclaim cannot figure out the new name/block for older snapshots that are being reverted. I may or may not have forgotten to remove some error messaging that should probably be silent.

**Comment by Halfhand1** [comment]
Yea so the error is coming up in some plots that are locked

**Comment by Halfhand1** [comment]
I've reloaded with a backup I had, might have fixed the issue

**Comment by Halfhand1** [comment]
Ok so I've gotten rid of those errors but now Im getting this one 
https://pastebin.com/9iWzdZiz

**Comment by LlmDl** [comment]
The 0.93.0.4 build made for 1.13 doesn't really handle the revert on unclaim feature very well yet. I would recommend you turn it off until we can get it sorted out.

**Comment by Halfhand1** [comment]
I have it turned off, still getting the errors.

**Comment by LlmDl** [comment]
Did you turn it off in the world using /tw toggle revertunclaim, or did you turn it off in the config?

**Comment by Halfhand1** [comment]
in the config

**Comment by LlmDl** [comment]
The config is only default settings for new worlds. Turn it off in the worlds using the /tw toggle revertunclaim command.
