### ISSUE TITLE
Can't claim towny plots, error

### ISSUE THREAD

**Issue by IITFA** [TownyAdvanced/Towny#3212]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Try to claim plot /towny claim or /plot claim

### What is the expected output?
1. Be able to claim plot

### What is your Towny version?
v0.93.0.0

### What is your spigot/craftbukkit version?
spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/Y6KnLcU8
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/raw/vzgm7dYu
3. Your townyperms.yml : https://pastebin.com/raw/Edza9HL6
4. Your log's error : https://pastebin.com/raw/VW6CwQMD

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your permission plugin is returning an incorrect result for the maxplots setting. Can you show me your luckperms file?

**Comment by IITFA** [comment]
config.yml: https://pastebin.com/raw/snp9nnKv

No idea about the database.

**Comment by LlmDl** [comment]
I dont know how much help the config will be. There was an issue similar to this with ultraperms recently. you could try to give players the maxplots node with a high value (eg: towny_maxplots.100) and see if that helps.

**Comment by IITFA** [comment]
Doesn't fix anything. Anything else I can do to try to resolve this? Towny is pretty much useless for my server is players can't claim their own plots within towns.

**Comment by LlmDl** [comment]
I've since had another Towny/LuckPerms user tell me that LP 4.4.0 broke a few things with Towny. Try updating to 4.4.1 or 4.4.2 or downgrading to a pre-4.4.0 and let me know if that's helped.

**Comment by IITFA** [comment]
Upgrading to 4.4.2 fixed it.

**Comment by LlmDl** [comment]
Good, have fun.
