### ISSUE TITLE
Issue with towny residential check

### ISSUE THREAD

**Issue by WillisAwesome** [TownyAdvanced/Towny#3213]
Me and my dev team are currently working on a updated towny war flag system but there seems to be an issue with residental check on towny 
Here is the hastebin:
https://hasteb.in/eceveyic.kotlin

"			if (TownyUniverse.getOnlineResidentsViewable(null, targetNation).size() < 3) {
				player.sendMessage(ChatColor.RED + "You can't declare war with them, they have less than 3 online residents.");
				return true;
			}"
This is the line of code that is causing the issue

**Comment by LlmDl** [comment]
My response from the IRC:
```
[22:53:41] <LlmDl^> Webchat634: lookin at it now
[22:58:09] <LlmDl^> line 66, instead of targetNation try targetNation.getResidents()
```

**Comment by WillisAwesome** [comment]
It seems that takes all residents in the nation not the current online members or am I wrong

**Comment by LlmDl** [comment]
What do you see if you add a bit of debug code before the if statement on line 66, try 
System.out.println( TownyUniverse.getOnlineResidentsViewable(null, targetNation.getResidents()).size())
or
System.out.println( TownyUniverse.getOnlineResidentsViewable(null, targetNation.getResidents())

**Comment by WillisAwesome** [comment]
Thats the same method we tried but that didn't work

**Comment by LlmDl** [comment]
Yeah but when you do system.out's you'll at least see what you're receiving, and you can show me.
