### ISSUE TITLE
Suggestion: Limit on the amount of towns in a nation

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#3219]
It would be nice to be able to limit the amount of towns in a nation from the towny config.

**Comment by LlmDl** [comment]
something for the global.nation.settings of the config

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/da2559e8d2e74e5cbbb055f6698cbc1cab9d4b09 

completed as of 0.93.0.6

```
    - New Config Option: global_nation_settings.max_towns_per_nation
      - default: 0
      - If higher than 0, it will limit how many towns can be joined into a nation.
      - Does not affect existing nations that are already over the limit.
```
