### ISSUE TITLE
Duplicate and Missing Data in MySQL Database

### ISSUE THREAD

**Issue by Cooperating** [TownyAdvanced/Towny#3220]
### What steps will reproduce the problem?
1. Player changes the name of their town or nation and then back to what it was originally.
2. Server restarts or towny is reloaded.

1. Towns are automatically deleted after specified amount of inactivity (60 d).
2. Server restarts or towny is reloaded.

### What is the expected output?
1. There is extra data in the tables, for example, Town 1 changed their name to Town 2 and back to Town 1 again.
2. After restart, both Town 1 and Town 2 are in the database and Towny is locked in safe mode and some town blocks are listed as owned by Town 2 rather than Town 1.

1. Town is deleted but resident data stays in the database or the resident data is deleted while the town data is not.
2. Towny can't find the town / resident that was removed and Towny is locked in safe mode.

I am able to manually delete the duplicate data to allow towny to work correctly, but this problem has been occurring almost every restart.  In addition to that, ever since this began happening, I've been experiencing 6-8 minute restart times while Towny is connecting to MySQL compared to the usual 1-2 minute restart times.

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
Paper(597) 1.13.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/sGi8wprn
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Wg0DgE6F
3. Your townyperms.yml : https://pastebin.com/0pddPZ77
4. Your log's error : 
(Both occur when towns were automatically deleted for inactivity)
https://pastebin.com/fuMtJAz2
https://pastebin.com/5wfcm67V

**Comment by LlmDl** [comment]
This sort of thing has been happening for years when servers run in MySQL instead of flatfile. I've never had anything that I can reproduce reliably. I have chalked it up to mysql software running on some servers just not being able to handle some large database updates, like town renames. If it gives you any peace of mind if you used flatfile you would see no loss of speed, whether towny runs in flatfile or mysql we operate at the speed of your ram. If you can find an issue with the Towny code that would be the culprit I will gladly reopen this ticket.

**Comment by LlmDl** [comment]
If you're using 1.13 you should consider trying teh 1.13 builds we have available on the towny discord. It will solve other issues that are unique to 1.13 and unrelated to this issue with renaming/mysql.

**Comment by Cooperating** [comment]
Is there a way to convert all the towns, nations, and residents easily from MySQL or would it all have to be done manually?

**Comment by LlmDl** [comment]
It's all got to be fixed manually if you don't keep mysql backups, which is advised.

**Comment by LlmDl** [comment]
Sorry I misread that last comment. You can convert from flatfile to mysql and vice versa as long as the database isn't already in safe mode. There are instructions on the How Towny Works page on the palmergames.com site.

**Comment by Cooperating** [comment]
Thanks for the help!  However, I asked the server host about the problem and they vehemently disapproved of the use of flatfile, stating that it corrupts easily / frequently and there should be no reason their NVME SSDs can't handle the Towny database.  They said nothing about their software when I asked and I believe this is the software they use: 10.1.38-MariaDB - MariaDB Server.  They suggested I continue to use their MySQL database and to update to the latest version of Towny to see if it would fix the problem.  Do you still think converting to flatfile from MySQL would be the best option?

**Comment by LlmDl** [comment]
Yes, as far as Towny is concerned flatfile is way more reliable than mysql.
