### ISSUE TITLE
Creatures still spawning in town.

### ISSUE THREAD

**Issue by kazeookami** [TownyAdvanced/Towny#3222]
So the past couple days I noticed mobs are still spawning inside towns on my server. 

I tried tinkering a bit by adding the names of the mobs I noticed in town to the removal list manually. Creepers and Phantoms at the time. This did not work so I brought my problem to the discord. 

I was informed there was a newer version of Towny than the 0.93 that I was using at the time. I was then pointed towards the 'very early builds' channel, so I upgraded to the 0.93.0.5.

This At this time I began noticing skeletons as well. I am not sure if that's a change or just random chance that I didn't see them before. But still, it's not preventing mobs in towns. Just to be sure, due to the notes that indicated changed in the config, I even wiped the config out so the 0.93.0.5 version can create it's own config. This did not help the matter any.

**Comment by FutureLemon** [comment]
Doesn't /t toggle mobs work?

**Comment by kazeookami** [comment]
No. I have tried it both enabled and disabled to see if I was misunderstanding how it was supposed to work.

**Comment by LlmDl** [comment]
Skipped the form. Resubmit your ticket and I can probably answer your question right away.
