### ISSUE TITLE
Creatures still spawning in town

### ISSUE THREAD

**Issue by kazeookami** [TownyAdvanced/Towny#3223]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Have a town
2. Disable mob spawns
3. Spawn mobs by eggs, or wait till night time
4. Watch mobs wander around unconcerned you have a town here.

### What is the expected output?
1. Monsters unexist after 1-5 seconds after step 3 but before step 4 of reproduction

### What is your Towny version?
0.93.0.5

### What is your spigot/craftbukkit version?
Spigot-f09662d-f40143e  1.13.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/3ykcNcgV
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/EtAX6sTU
3. Your townyperms.yml : https://pastebin.com/are67tbs
4. Your log's error : https://pastebin.com/uHzZ1UuG

(optional) If this is to do with permissions, 
5. Your permissions file : I do not believe this has anything to do with permissions.

(optional) If this is to do with chat,
6. Your chatconfig.yml : I do not believe this has anything to do with chat.
7. Your channels.yml : I do not believe this has anything to do with chat.

**Comment by LlmDl** [comment]
This is usually caused by using an improper citizens build # for your version. I looked up build 1617 on their page here: https://ci.citizensnpcs.co/job/Citizens2/changes and it isn't listed anymore. Try removing citizens, if that fixes the mob thing update to a newer version than build 1617.

**Comment by LlmDl** [comment]
Sorry it's not that it's a bad build, it's that Citizens isn't starting properly. Get it to start properly and Towny's mob removal will be fine.
