### ISSUE TITLE
Suggestion: Adding List of Disabled Commands In Enemied Towns / Nations

### ISSUE THREAD

**Issue by WillisAwesome** [TownyAdvanced/Towny#3225]
I think there should be a way to disable commands in towns that you dont belong to like /sethome or in enemy nations in the config

**Comment by JohnS19** [comment]
+1 for this, if there was a config option for disabled commands for outsiders and enemies, it'd be great.

**Comment by LlmDl** [comment]
This is fulfilled by the own_town_and_wilderness_limited_commands option in teh config. It doesn't pertain to enemies but does handle all outsiders.
