### ISSUE TITLE
Suggestion: Detach from outdated parent repository.

### ISSUE THREAD

**Issue by Justin42** [TownyAdvanced/Towny#3226]
It would be really nice to be able to search this repository. Searching is not available for forks. The parent repository is extremely outdated, and is unlikely to be useful for anyone that is browsing this repository.

I believe github support will detach this project from the parent by request. That will make this repository searchable. It should have very little effect on anything else.

**Comment by LlmDl** [comment]
Interesting. I did not know that github support would do this.

**Comment by LlmDl** [comment]
This was done quite wonderfully by the folks at github support.
