### ISSUE TITLE
Task #151 for Towny v0.93.0.5 generated an exception

### ISSUE THREAD

**Issue by CitrusFruit** [TownyAdvanced/Towny#3229]
### What steps will reproduce the problem?
Run Towny v0.93.0.5 on Spigot 1.13.2 (latest).

### What is the expected output?
https://pastebin.com/FVsKACdU

### What is your Towny version?
Towny v0.93.0.5.

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT).
This is a final build for 1.13.2.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/uTswgqsK
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/3LAX2BYQ
3. Your townyperms.yml : https://pastebin.com/hkv7Fn5z
4. Your log's error : https://pastebin.com/FVsKACdU

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
line 699 of your startup, Citizens is erroring, which makes towny's mob removal system error. Get your Citizens working and the Towny error will go away.

**Comment by CitrusFruit** [comment]
Ah perfect, thanks.
