### ISSUE TITLE
Outposts null

### ISSUE THREAD

**Issue by CitrusFruit** [TownyAdvanced/Towny#3230]
### What steps will reproduce the problem?
Trying to claim an outpost with /t claim outpost just spits out a null.

### What is the expected output?
No errors show up in console, you only see this in-game - [Towny] null

### What is your Towny version?
Towny v0.93.0.5.

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT).
This is a final build for 1.13.2.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/gzVjfUq4
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/3LAX2BYQ
3. Your townyperms.yml : https://pastebin.com/hkv7Fn5z
4. Your log's error : No error is output apart from in-game https://i.imgur.com/UNgkcfk.png

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
How many residents are in the town that is trying to do the command?

**Comment by CitrusFruit** [comment]
Currently 4 residents.

**Comment by LlmDl** [comment]
Are they able to claim normally? They already have some claimed plots?

**Comment by CitrusFruit** [comment]
Yeah, normal claiming with /t claim works fine.

**Comment by xH3LLRAIZ3Rx** [comment]
Getting the same problem with a town that has over 40 residents

**Comment by xH3LLRAIZ3Rx** [comment]
@LlmDl 0.93.0.6

**Comment by LlmDl** [comment]
@xH3LLRAIZ3Rx do you use luckperms? If so, which version?

**Comment by xH3LLRAIZ3Rx** [comment]
@LlmDl Yes, I am using version 4.4.1

**Comment by LlmDl** [comment]
I think yours is a separate issue @xH3LLRAIZ3Rx you can probably get around it by making town and nation levels which have numResidents very high (ex: 99999) All the rest of the settings for those new nationLevel and townLevel can be the same as the current highest ones. If that doesn't solve it, file a ticket for the issue.

**Comment by xH3LLRAIZ3Rx** [comment]
@LlmDl Can you give me a example of that, kinda confused..

**Comment by LlmDl** [comment]
At teh bottom of the townLevels section add
```
  - numResidents: 9999
    namePostfix: ' (Metropolis)'
    mayorPrefix: 'Lord '
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 448
    upkeepModifier: 1.0
    townOutpostLimit: 4
```

At the bottom of the nationLevels add:
```
  - kingPostfix: ''
    capitalPostfix: ''
    upkeepModifier: 1.0
    kingPrefix: 'God Emperor '
    capitalPrefix: ''
    numResidents: 9999
    nationBonusOutpostLimit: 5
    namePostfix: ' Realm'
    townBlockLimitBonus: 140
    namePrefix: 'The '
    nationZonesSize: 3
    nationTownUpkeepModifier: 1.0
```
