### ISSUE TITLE
1.14: Land Claim Throws Exception

### ISSUE THREAD

**Issue by MayorMike** [TownyAdvanced/Towny#3231]
On land claim, Towny throws an exception and never informs the player that the land was claimed, just processing. The land does get claimed though.

### What steps will reproduce the problem?
1. Create Town
2. Claim land
3. Never tells you it's successful, throws exception, but still claims the land

### What is the expected output?
1. Create town
2. Claim Land
3. Successful claim message, no console errors

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
git-Spigot-0c02b0c-e879c44 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Console Log: https://pastebin.com/cvuf6dA2
2. Towny Config: https://pastebin.com/TLL6PzmH 
3. Towny Perms: https://pastebin.com/yJfWHgic 
4. Your log's error: https://pastebin.com/rVnkfK1x

(Config and TownyPerms are the default generated)

**Comment by MayorMike** [comment]
Further inspection shows that Towny isn't saving any land that is claimed as well, except for the home block. No further errors show in the console on reboot or start.

**Comment by BarnabyD** [comment]
[1.14 Spigot API Changes](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-development-builds.369724/)
> Events are now strictly sync or async. A sync event may only be fired from the main server thread, whilst an async event may only be fired from another server thread. Previously only the latter was true. 

To temporarily get around the issue on my server, I've wrapped every callEvent in a runTask. 
```
Bukkit.getScheduler().runTask(Towny.getPlugin(), () -> {
   BukkitTools.getPluginManager().callEvent( ... );
});
```
I don't know if its a good way to resolve it or not, so I'll leave it to the pro's. Just thought I would mention it.

**Comment by LlmDl** [comment]
Real busy IRL, hopefully some people have the time to put in a PR or two to cover the bases on this API change.

**Comment by LlmDl** [comment]
Should be fixed as of 0.93.1.0

**Comment by Symphonized19** [comment]
Where can I get the version 0.93.1.0? Can you kindly post a link or something? Thank you

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/321710042091094026/580758574393982977/Towny.jar

**Comment by MothGirlMusic** [comment]
real lifesaver!
