### ISSUE TITLE
Suggestion: MythicMobs support

### ISSUE THREAD

**Issue by RogerPlaysMC** [TownyAdvanced/Towny#3233]
Suggestion: Add MythicMobs support for despawning mobs. 

The implementation looks easy, soft depend MM, use the MM api to if the target mob is a MM. If so, check to see if the MM type is on a list in a config file. If so, cancel/stop the MobRemovalEvent from Towny. That way you can have town guards and such made by MM that don’t get wiped out immediately. 

Thanks!

**Comment by LlmDl** [comment]
I took a look into this today. Not familiar with MythicMobs so I don't really know if there's some way that Towny can tell if a MythicMob is supposed to be removed or not. I assume that most MythicMobs are ones you wouldn't want walking into town, unlike your Town guard idea.

What I do know is that Towny does fire a MobRemovalEvent for every LivingEntity that we remove. MythicMobs could listen for this event and cancel it if the mob is part of a do-not-remove list.

Unless there's a do-not-remove flag I can look up via the MM api I don't really see this happening on our end.

**Comment by RogerPlaysMC** [comment]
Is the mob removal event in towny fired continuously as long as the mob stays alive, or does it just try once? If the former, it could process a lot of code continuously. If the latter, that may work out great.

**Comment by LlmDl** [comment]
It's a cancel-able event that fires when they are removed. If it were canceled it would try to remove them again. The code is already quite heavy so a few town guards isn't going to be noticed.

**Comment by LlmDl** [comment]
Doesn't appear to be a do-not-remove flag for MM.

**Comment by RogerPlaysMC** [comment]
Not built directly for towny compatibility, no. But there is a despawn: false option.

**Comment by LlmDl** [comment]
There is?

**Comment by LlmDl** [comment]
Doesn't look like there's maven repo for MM. That's too bad.

**Comment by LlmDl** [comment]
I see the despawn option is only for determining if the mob should be despawned when the chunks are unloaded. Not exactly what we're needing.
