### ISSUE TITLE
1.14 no access

### ISSUE THREAD

**Issue by Subtrahero** [TownyAdvanced/Towny#3235]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.when server is started
2./t
3.

### What is the expected output?
1.not to say :you do not have permission to execute this command
2.
3.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Spigot Version: c529d43-9926d78 (MC: 1.14)

### Please use Pastebin.com to link the following files:

No error on startup
No error executing commands
No change in config

It worked fine in 1.13.2

Please help! not just lock and no help

**Comment by Abwasserrohr** [comment]
Permissions are working for you? For me, Towny works on 1.14, just a little bit laggy.

**Comment by Subtrahero** [comment]
Permissions on everything else works fine. it is just on Towny commands.
/res commands works

**Comment by LlmDl** [comment]
Skipped form. Resubmit.
