### ISSUE TITLE
[permissions] nation join

### ISSUE THREAD

**Issue by playfrite** [TownyAdvanced/Towny#3238]
Hello,

I do not find permission that allows a group to join a nation.

Can you help me?

thank you

**Comment by LlmDl** [comment]
towny.nation.spawn.nation: Ability to spawn to your own nation.

towny.command.nation.new: Able to use nation creation command.

towny.command.nation.add: Able to add a town to your nation.

Are you asking about something different?

**Comment by playfrite** [comment]
Hello, players do not have permission to join a nation.  can you give me the command to join the nation and permission to join the nation?

**Comment by Yasu-San** [comment]
Players are not supposed to join a nation. A nation is a group of towns.

The king/leader of a nation invites a town to join their nation.

**Comment by LlmDl** [comment]
Mayors already have the proper permissions to accept a nation invite in the townyperms.yml file.

**Comment by playfrite** [comment]
I had to delete permissions from towny perm.yml because I restricted access to commands for each grade. The problem is that even adding all permissions to a rank, at the invitation, the guest town can not accept because it is missing permission.
