### ISSUE TITLE
permission nation

### ISSUE THREAD

**Issue by playfrite** [TownyAdvanced/Towny#3239]
I had to delete permissions from towny perm.yml because I restricted access to commands for each grade. The problem is that even adding all permissions to a rank, at the invitation, the guest town can not accept because it is missing permission.

_Originally posted by @playfrite in https://github.com/TownyAdvanced/Towny/issues/3238#issuecomment-489327745_

**Comment by LlmDl** [comment]
It's probably towny.command.town.invite.*

Not using townyperms for splitting up mayor/resident priviledges isn't recommended.
