### ISSUE TITLE
Could not pass event PlayerTeleportEvent to Towny v0.93.0.0 

### ISSUE THREAD

**Issue by Coarby** [TownyAdvanced/Towny#3243]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
teleporting to another world
or just teleporting in general

### What is your Towny version?
0.0.93.0

### What is your spigot/craftbukkit version?
git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/jRTYKNEi
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/9XLyQYbH
3. Your townyperms.yml : https://pastebin.com/ejgw6x1L
4. Your log's error : https://pastebin.com/Pk6Pt3z3

**Comment by LlmDl** [comment]
Try using a version of towny made for 1.8: http://towny.palmergames.com/?p=1099

Let me know if that fixes it.

**Comment by Coarby** [comment]
Hey, i tried using the 1.8 version but it gave me more problems..

**Comment by LlmDl** [comment]
Define problems.

**Comment by Coarby** [comment]
"An internal error has occurred while attempting to perform this command" with /t new or any /t command

**Comment by LlmDl** [comment]
Does the log show any errors?

**Comment by Coarby** [comment]
No

Op do 9 mei 2019 06:00 schreef LlmDl <notifications@github.com>:

**Comment by LlmDl** [comment]
pastebin.com a new startup log please.
