### ISSUE TITLE
Spammed Null Pointer Exceptions on console. Many player plots getting locked! [Regen is turned off]

### ISSUE THREAD

**Issue by RishabhRaghunath** [TownyAdvanced/Towny#3245]
I am getting a wall of errors filled by Null Pointer Exception errors on the console. The error is constant and fills up logs very quickly. Players have reported many of their plots getting locked and they are unable to further play. I have attached the logs so you can see what I'm experiencing. I have Regen on un-claim & Explosions turned off in config.yml.

This is kind of urgent as most of the players on the server are experiencing issues due to plots getting locked.

`[07:44:33] [Server thread/WARN]: [Towny] Task #428 for Towny v0.93.0.5 generated an exception
java.lang.NullPointerException: null
	at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(PlotBlockData.java:140) ~[?:?]
	at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(RepeatingTimerTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

### What steps will reproduce the problem?
1. - People have reported claiming new plots, immediately locks it. Random other plots get locked too. The Spam starts when players join and they load up their chunks.

### What is your Towny version?
0.93.0.5

### What is your spigot/craftbukkit version?
Paper-624 - MC 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/2fMfyz2g

As you see, as soon as a player joins and loads up a chunk the errors start appearing on a very fast loop.
This affects multiple people in many other towns in different places as well.

2. Your Towny config.yml : https://pastebin.com/iSeVB6h7
3. Your debug log : https://pastebin.com/L4LNufNq
4. Console Error Log: https://pastebin.com/EAR28z3g

Help with this ASAP is really appreciated.  Looking forward to hear from you guys soon!

**Comment by LlmDl** [comment]
You can leave the explosion revert on, but you need to turn off the revert-on-unlcaim feature in each world using /tw toggle revertunclaim

The config is only default settings for new worlds.

The revert-on-unclaim feature should not be used with 1.13.

**Comment by RishabhRaghunath** [comment]
Uhm Hello LlmDl.
I already have both the Revert options turned off. I'm still getting the above issue of really fast null pointer exceptions on console and plots of many players getting locked..
What steps should I take to fix this? Since I already do not use regen on the server.
    revert_on_unclaim:
      enabled: 'false'
    wild_revert_on_mob_explosion:
      enabled: 'false'

**Comment by LlmDl** [comment]
In the ticket OP you said you had those set to false in the config, which doesn't affect the worlds. The config is only default settings for new worlds, the config section is the Default New World settings. 

Attempt to turn it off in the worlds using the command I mentioned in my post above and tell me what happens.

**Comment by RishabhRaghunath** [comment]
I did turn off both revert on unclaim and explosions for all the worlds I have.
Below is the settings for one of my worlds related to revert.
I have tried this and still errors are shown when /t claim is done
https://pastebin.com/AhLgRV0d
`> [15:36:00 WARN]: [Towny] Task #428 for Towny v0.93.0.5 generated an exception
java.lang.NullPointerException: null
 `
I still get this under a fast loop when someone does /t claim.

# If enabled when a town claims a townblock a snapshot will be taken at the time it is claimed.
# When the townblock is unclaimded its blocks will begin to revert to the original snapshot.
usingPlotManagementRevert=false
# Any block Id's listed here will not be respawned. Instead it will revert to air.
plotManagementIgnoreIds=GOLD_ORE,LAPIS_ORE,LAPIS_BLOCK,GOLD_BLOCK,IRON_BLOCK,MOSSY_COBBLESTONE,TORCH,MOB_SPAWNER,DIAMOND_ORE,DIAMOND_BLOCK,SIGN_POST,WALL_SIGN,GLOWSTONE

# If enabled any damage caused by explosions will repair itself.
usingPlotManagementWildRegen=false
PlotManagementWildRegenEntities=creeper,endercrystal,enderdragon,fireball,smallfireball,largefireball,tntprimed,explosiveminecart
usingPlotManagementWildRegenDelay=20

**Comment by LlmDl** [comment]
What you linked looks like the revert-on-unclaim regen happening. You might have some plots still reverting from before your turned it off in the world using /tw toggle revertunclaim.

To stop already reverting plots you need to stop the server and delete the towny\data\regen.txt

**Comment by RishabhRaghunath** [comment]
Yes, that fixed it! Thanks a lot
Any information on when we can get 1.14 support? .. I know a lot of server owners who are wanting to switch from 1.12 to 1.14.1 when it releases.

**Comment by LlmDl** [comment]
I don't have the time right now to finish the 1.13 update (it's really just the revert-on-unclaim system left) or to update Towny for 1.14. I'm hoping some of the developers that sometimes contribute code to Towny will step up and get things ready for 1.14.
