### ISSUE TITLE
Outpost claiming is null

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TownyAdvanced/Towny#3246]
### What steps will reproduce the problem?
1. do /t claim outpost
2. null error
3. don't profit

### What is the expected output?
1. do /t claim outpost
2. claimed outpost for town
3. profit

### What is your Towny version?
0.93.0.6

### What is your spigot/craftbukkit version?
git-Spigot-1a3504a-a46fdbc (MC: 1.13.2)

### Please use Pastebin.com to link the following files:
1. Server Log: https://pastebin.com/GnjLPMNT
2. Towny Config: https://pastebin.com/xeac6kC1
3. Towny Perms: https://pastebin.com/pHLd0M9n
4. No Error at all in logs

**Comment by LlmDl** [comment]
I thought this had to do with something like having over 40 residents (according to your previous post) but this is not mentioned in the steps to repeat the problem, please clarify.

**Comment by xH3LLRAIZ3Rx** [comment]
It seems like the town having the problem only has 39 residents my bad, it is a odd issue though.

**Comment by xH3LLRAIZ3Rx** [comment]
any update to this issue @LlmDl?

**Comment by LlmDl** [comment]
Does it still occur if you're using the 0.93.1.0 pre release 2 version of Towny? Have you narrowed down exactly when it happens?

**Comment by Flexxxxx** [comment]
Our server is having this exact same problem, but we're using the most recent spigot 1.14.3 build.

**Comment by LlmDl** [comment]
@Flexxxxx if you're using 0.93.1.0 PR2 then please pastebin.com your errors from the log. If you aren't on that build, please update.

Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

**Comment by Flexxxxx** [comment]
Outlined the issues here: https://github.com/TownyAdvanced/Towny/issues/3304

**Comment by xH3LLRAIZ3Rx** [comment]
@LlmDl Just tested with latest version, still getting null with no errors.

**Comment by LlmDl** [comment]
Towny 0.93.1.0 PR4 ( https://cdn.discordapp.com/attachments/321710042091094026/597844593614258177/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

Try this one please @xH3LLRAIZ3Rx it should finally have all of the pesky async things out of the way.

**Comment by xH3LLRAIZ3Rx** [comment]
Just tested, still giving NULL

**Comment by LlmDl** [comment]
@xH3LLRAIZ3Rx can you give me your latest.log startup please.

**Comment by LlmDl** [comment]
Ok, unless you come up with a new problem I'm writing this off as a bug with LP version 4.4.0 which was fixed in 4.4.1. Update your LP.
