### ISSUE TITLE
Town Claims Not Processing

### ISSUE THREAD

**Issue by caes4r** [TownyAdvanced/Towny#3247]
### What steps will reproduce the problem?
1. Create a town on a fresh install using Minecraft 1.14+.
2. Claim a block next to the town using /town claim.
3. Claimed block attempting to process though fails due to PlotChangeTypeEvent being fired asynchronously from another thread.
4. Restart server.
5. Town home block still exist though the newly claimed town blocks do not.

### What is the expected output?
1. Claim plot.
2. Restart server.
3. Claimed plot should still exist.

### What is your Towny version?
0.93.0.6 - built using Ant in order to build it against 1.14.1.

### What is your spigot/craftbukkit version?
Spigot 1.14.1 (8043ebc-89c52b7).

I started working on an update to this issue yesterday (5/14) and just wanted to make a thread here so that it could be discussed further among new collaborators. LlmDL and I discussed this for about an hour on 5/15 and came up with a few potential problems but namely getting the async thread fire fixed would be the first priority that I have.

Related error:
https://gist.github.com/caes4r/6ef24c9c619ffb8817043471fb0d6ab1

Related classes are as follows (in no particular order):
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/tasks/TownClaim.java#L34
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/event/TownClaimEvent.java
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/event/PlotChangeTypeEvent.java
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/object/TownBlock.java
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/object/TownBlockType.java

Conversation #1 between LlmDl and myself: https://gist.github.com/caes4r/706785920c4c86e3ebf381ee613181ba

**Comment by BarnabyD** [comment]
Related Ticket #3231

**Comment by LlmDl** [comment]
Should be fixed as of 0.93.1.0
