### ISSUE TITLE
Farm plots appear broken-those with destroy/build perms cannot harvest

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3252]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Set a plot as a farm and plant crops on it.
2. Give perms to build and break on the plot. (I gave perms to all groups)
3. Have someone without mayor/townyadmin perms that does have plot perms try to break the crops. (I tried both a resident and an outsider)

### What is the expected output?
1. The player should be able to break the crops, but they cannot (The are told they can't break here). (Tested with wheat, potatoes)
2.
3.

### What is your Towny version?
Do not say "latest".
0.93.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 1.13.2 (624)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/LBWzN0U0
2. Your Towny config.yml (if using MySQL please remove password,) :
I tried regenning the config.yml and only replacing my mysql data.  Farm plots were still broken. Here's the reggened config:
https://pastebin.com/ptK2JgHD
3. Your townyperms.yml :
https://pastebin.com/fB2mjaJq
4. Your log's error : 
No error.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Momshroom** [comment]
This bug has been at least partially present since upgrading to 1.13.2- it is not new to this build.

**Comment by Feldmarschall** [comment]
btw. how u get the 0.93.1.0 build?

**Comment by Momshroom** [comment]
The towny discord.

**Comment by LlmDl** [comment]
@Momshroom try adding WHEAT,POTATOES to the farm_plot_allow_blocks, do /ta reload and retest.

**Comment by Momshroom** [comment]
Thank you.
I regenned the entire config before filing a report, it generates with the values listed in the bug report.
But, yes, adding WHEAT, POTATOES fixed those two crops. I'm working through testing the rest of the crops:
 I needed to add CARROTS to fix carrots. (Default config is CARROT)
I needed to add COCOA to fix cocoa beans.
I'm still unable to plant or harvest beetroot.  Current config line is:
  farm_plot_allow_blocks: BEETROOT_SEEDS,BEETROOT_BLOCK,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,SEAGRASS,TALL_SEAGRASS,MELON,CARROTS,WHEAT,POTATOES,LONG_GRASS,DOUBLE_PLANT,YELLOW_FLOWER,RED_ROSE,PUMPKIN_STEM,MELON_STEM,BEETROOT_BLOCK,CARROT,POTATO,CROPS,MELON_BLOCK,PUMPKIN,BEETROOT_BLOCK,CHORUS_PLANT,CHORUS_FLOWER

**Comment by Momshroom** [comment]
Edit:
Beetroot works if BEETROOTS is added to the config

**Comment by Momshroom** [comment]
SOIL needed to be changed to FARMLAND for that to work.

**Comment by LlmDl** [comment]
ok so 
```
farm_plot_allow_blocks: BEETROOT_SEEDS,BEETROOTS,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,SEAGRASS,TALL_SEAGRASS,MELON,CARROTS,WHEAT,POTATOES,LONG_GRASS,DOUBLE_PLANT,YELLOW_FLOWER,RED_ROSE,PUMPKIN_STEM,MELON_STEM,BEETROOT_BLOCK,CARROT,POTATO,CROPS,MELON_BLOCK,PUMPKIN,CHORUS_PLANT,CHORUS_FLOWER,FARMLAND
```

Does that cover it all?

**Comment by Momshroom** [comment]
SUGARCANE,COCOA assuming you want those two to work.

My final line is:
  farm_plot_allow_blocks: JUNGLE_LOG,JUNGLE_SAPLING,OAK_LOG,OAK_SAPLING,BIRCH_LOG,BIRCH_SAPLING,ACACIA_LOG,ACACIA_SAPLING,DARK_OAK_LOG,DARK_OAK_SAPLING,SPRUCE_LOG,SPRUCE_SAPLING,FARMLAND,BEETROOTS,COCOA,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,SEAGRASS,TALL_SEAGRASS,MELON,CARROTS,WHEAT,POTATOES,LONG_GRASS,DOUBLE_PLANT,PUMPKIN_STEM,LOG,LEAVES,LEAVES_2,LOG_2,NETHER_WART,COCOA,VINE,SAPLING,MELON_STEM,PUMPKIN,CHORUS_PLANT,CHORUS_FLOWER,SUGAR_CANE_BLOCK,MELON,DIRT,GRASS
but I've got extra things in there because I want tree farms to work and want people to be able to replace the farmland if they break it accidentally.

**Comment by LlmDl** [comment]
farm_plot_allow_blocks: JUNGLE_LOG,JUNGLE_SAPLING,OAK_LOG,OAK_SAPLING,BIRCH_LOG,BIRCH_SAPLING,ACACIA_LOG,ACACIA_SAPLING,DARK_OAK_LOG,DARK_OAK_SAPLING,SPRUCE_LOG,SPRUCE_SAPLING,FARMLAND,BEETROOTS,COCOA,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,SEAGRASS,TALL_SEAGRASS,CARROTS,WHEAT,POTATOES,LONG_GRASS,DOUBLE_PLANT,PUMPKIN,PUMPKIN_STEM,ATTACHED_PUMPKIN_STEM,NETHER_WART,COCOA,VINE,MELON,MELON_STEM,ATTACHED_MELON_STEM,SUGAR_CANE,DIRT,GRASS,JUNGLE_LEAVES,OAK_LEAVES,BIRCH_LEAVES,ACACIA_LEAVES,DARK_OAK_LEAVES,SPRUCE_LEAVES

Added ATTACHED_MELON_STEM,ATTACHED_PUMPKIN_STEM,JUNGLE_LEAVES,OAK_LEAVES,BIRCH_LEAVES,ACACIA_LEAVES,DARK_OAK_LEAVES,SPRUCE_LEAVES

Removed LOG,LOG_2,SAPLING,LEAVES,LEAVES_2

Also cleaned up some duplicates in your list. Wonder if there are any more?

**Comment by Momshroom** [comment]
Thank you. I'm always hesitant to remove things.

KELP needs adding

**Comment by LlmDl** [comment]
What the difference between kelp and seagrass and tall_seagrass?

Also removing LONG_GRASS in favour of TALL_GRASS

Double_Plant doesn't exist now either. 

List as of now:
```
- JUNGLE_LOG,JUNGLE_SAPLING,JUNGLE_LEAVES,OAK_LOG,OAK_SAPLING,OAK_LEAVES,BIRCH_LOG,BIRCH_SAPLING,BIRCH_LEAVES,ACACIA_LOG,ACACIA_SAPLING,ACACIA_LEAVES,DARK_OAK_LOG,DARK_OAK_SAPLING,DARK_OAK_LEAVES,SPRUCE_LOG,SPRUCE_SAPLING,SPRUCE_LEAVES,BEETROOTS,COCOA,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,KELP,SEAGRASS,TALL_SEAGRASS,TALL_GRASS,CARROTS,WHEAT,POTATOES,PUMPKIN,PUMPKIN_STEM,ATTACHED_PUMPKIN_STEM,NETHER_WART,COCOA,VINE,MELON,MELON_STEM,ATTACHED_MELON_STEM,SUGAR_CANE,DIRT,GRASS,FARMLAND
```

**Comment by LlmDl** [comment]
Found more, FERN,LARGE_FERN,BAMBOO,BAMBOO_SAPLING,CACTUS and all the flowers

```
- BAMBOO,BAMBOO_SAPLING,JUNGLE_LOG,JUNGLE_SAPLING,JUNGLE_LEAVES,OAK_LOG,OAK_SAPLING,OAK_LEAVES,BIRCH_LOG,BIRCH_SAPLING,BIRCH_LEAVES,ACACIA_LOG,ACACIA_SAPLING,ACACIA_LEAVES,DARK_OAK_LOG,DARK_OAK_SAPLING,DARK_OAK_LEAVES,SPRUCE_LOG,SPRUCE_SAPLING,SPRUCE_LEAVES,BEETROOTS,COCOA,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,KELP,SEAGRASS,TALL_SEAGRASS,GRASS,TALL_GRASS,FERN,LARGE_FERN,CARROTS,WHEAT,POTATOES,PUMPKIN,PUMPKIN_STEM,ATTACHED_PUMPKIN_STEM,NETHER_WART,COCOA,VINE,MELON,MELON_STEM,ATTACHED_MELON_STEM,SUGAR_CANE,CACTUS,ALLIUM,AZURE_BLUET,BLUE_ORCHID,CORNFLOWER,DANDELION,LILAC,LILY_OF_THE_VALLEY,ORANGE_TULIP,OXEYE_DAISY,PEONY,PINK_TULIP,POPPY,RED_TULIP,ROSE_BUSH,SUNFLOWER,WHITE_TULIP,WITHER_ROSE,DIRT,GRASS,FARMLAND
```

**Comment by LlmDl** [comment]
Calling this one done, I read through the entire materials page. If I missed one please file a new ticket.
