### ISSUE TITLE
maven repository

### ISSUE THREAD

**Issue by dirtyequi** [TownyAdvanced/Towny#3256]
Hi,

are you interested in having your projects in a real maven repository? We (Cube Nation - a german minecraft server) use "Towny Advanced" as a dependency, and our repository server has difficulties to manage your "php repository" (which by the way is not supported anymore by the maintainer). 

Please tell me your thoughts.

Best

**Comment by LlmDl** [comment]
Not at the moment. You can use this address to get the latest Towny release build http://palmergames.com/file-repo/Towny%20Advanced/Latest/

**Comment by dirtyequi** [comment]
Thanks for your quick reply.
The problem with this URL is that it contains a space, and it is not a true indexed repository, so our repository server (Nexus 3 OSS) cannot resolve dependencies.

**Comment by LlmDl** [comment]
I think we'll eventually move to using maven, Articdive is a fan of it. For the time being, the API changes so little you can probably just host the jar yourself and just replace it once a year.

**Comment by Articdive** [comment]
I have a maven repository that hosts a version of towny Im currently not at
home though so i can give it to you tonight (GMT+1)

**Comment by Articdive** [comment]
this should be a valid repo:
        <repository>
            <id>articdive-repo</id>
            <url>https://nexus.articdive.de/repository/maven-public/</url>
        </repository>
        <dependency>
            <groupId>com.palmergames</groupId>
            <artifactId>Towny</artifactId>
            <version>0.93.0.5</version>
            <scope>provided</scope>
        </dependency>
