### ISSUE TITLE
Found: Towny safemode issue with outlaws

### ISSUE THREAD

**Issue by Kbryst** [TownyAdvanced/Towny#3260]
### What steps will reproduce the problem?
1. A town needs to have an outlaw who's data is too old. (The one I used, their data was 1 month and 2 weeks old, towny data purge is 25 days).

### What is the expected output?
1. Towny boots up into safemode

### What is your Towny version?
Do not say "latest".
0.93.0.0 

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 1.13.2 - super behind on versions - build 561

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

I'm about to board a plane, I don't really have time to pull all of that at this moment, I had to quickly get the server back up before running off. I can provide it once I land if it's needed. 

This is the error. These names were in the outlaw section. I removed 2 of the names and left the 3 names that I knew I had seen within the last few days. The server booted up fine afterward. 

https://pastebin.com/nP17EC85

**Comment by LlmDl** [comment]
Fixed already https://github.com/TownyAdvanced/Towny/blob/master/src/ChangeLog.txt#L3159

You can get this build which contains the fix here https://cdn.discordapp.com/attachments/321710042091094026/580758574393982977/Towny.jar but read the changelog for required changes between your build and 0.93.1.0
