### ISSUE TITLE
Update dependency Essentials to EssentialsX

### ISSUE THREAD

**Issue by Articdive** [TownyAdvanced/Towny#3261]
EssentialsX is the continued version of essentials, it is the currently most distributed continuation of essentials, it's probably worth it making sure we are compatible with that system and not the one from essentials 5 years ago, although I don't expect there to be many changes, maybe some deprecation

**Comment by TheFlagCourier** [comment]
Should we also switch GroupManager to [GroupManager](https://github.com/GroupManager/GroupManager)? It's probably not a big deal if it has proper Vault integration.

**Comment by TheFlagCourier** [comment]
The Maven PR now uses both EssentialsX and GroupManager over the old essentials stuff.
