### ISSUE TITLE
The rank shows up two places!

### ISSUE THREAD

**Issue by BootlegCenny** [TownyAdvanced/Towny#3265]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Have luckPerms
2. Have Towny(ofc)
3. Add a role on LuckPerms
4. Delete all "{permsuffix}" in the ChatConfig.yml file
5. Type and then this happens:
![image](https://user-images.githubusercontent.com/49611200/58379404-204fac80-7fa3-11e9-8582-f21a363fdc29.png)

### What is the expected output?
1. That the second [*] is gone. That's all.

### What is your Towny version?
It is v. 0.93.0.0

### What is your spigot/craftbukkit version?
It is Craftbukkit v. git-Spigot-518206a-a5b9c7bdw
![image](https://user-images.githubusercontent.com/49611200/58379379-c3ec8d00-7fa2-11e9-8850-3060f0c975f3.png)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/gbzTHyDh
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/EZZSUiGP
3. Your townyperms.yml : https://pastebin.com/LSkH8A8X
4. Your log's error : https://pastebin.com/vRmUMStC

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/YHNLRfVg
7. Your channels.yml : https://pastebin.com/hL7LSQuG

**Comment by LlmDl** [comment]
This is your global channel_format:
```
  global: '{permprefix}{townytagoverride}{townycolor}{modplayername}&f:{msgcolour} {msg}'
```
I'm guessing that the [*] is the LP prefix. When you use {modplayername} instead of {playername} you're usually going to get the displayname which is prefix+name+suffix.

Try changing {modplayername} to {playername} and use /townychat reload

**Comment by TheFlagCourier** [comment]
Can confirm, I've seen this behavior before on a server I previously worked on.
