### ISSUE TITLE
Players can steal from various new containers [1.14.1]

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3270]
### What steps will reproduce the problem?
Town claim, let non-town member try to steal from the container.

### What is the expected output?
Players should not be able to take from any containers in towny protected chunks.

### What is your Towny version?
Towny 0.93.1.0

### What is your spigot/craftbukkit version?
Paper-43

### Please use Pastebin.com to link the following files:

Log: https://pastebin.com/raw/htReRCZz
Towny Config: https://pastebin.com/raw/D4dkFUMG

No errors occur.

**Comment by LlmDl** [comment]
you didnt add the new containers to the switch list, like it says to do when you read the changelog which is supposed to be read when using that build
