### ISSUE TITLE
Console Warning 

### ISSUE THREAD

**Issue by yanzilla1** [TownyAdvanced/Towny#3276]
I have a warning in the console that says: [Towny] Error: PlotBlockData:restoreNextBlock() - Material Null, skipping block. what could it be? the console spam this quite a lot.

### What steps will reproduce the problem?
1. Just After Creating a Town with a building inside. 
2. Console Spam [Towny] Error: PlotBlockData:restoreNextBlock() - Material Null, skipping block.

### What is the expected output?
1. Console not spaming [Towny] Error: PlotBlockData:restoreNextBlock() - Material Null, skipping block.

### What is your Towny version?
0.93.1.0 Pre Release 2

### What is your spigot/craftbukkit version?
1.14.2 spigot server

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log: [https://pastebin.com/Qxg7b5HD](url)
2. Your Towny config.yml: [https://pastebin.com/sykWt6VM](url)
3. Your townyperms.yml : [https://pastebin.com/h86xJfSC](url)

**Comment by LlmDl** [comment]
Did the plot get claimed by the town before or after you installed 0.93.1.0 PR 2?

**Comment by yanzilla1** [comment]
after

**Comment by LlmDl** [comment]
pastebin.com the full error, preferably with the parts of the log that precede the error.

**Comment by yanzilla1** [comment]
I Think I figured out... I removed the Towny folder from the plugins folder (Because the Towny folder was created by a previous version of towny) and then I re-launched the server and recreated the town and plots... It seems that this solved the [WARNING] spam in the console.
