### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT

### ISSUE THREAD

**Issue by lKhyst** [TownyAdvanced/Towny#3278]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. I have no idea what to write here but
2. It keeps flooding in the console "Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT"
3.

### What is the expected output?
1. Dont flooding that
2.
3.

### What is your Towny version?
Do not say "latest".
0.93.0.0 

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot-1.8.8-R0.1-SNAPSHOT-latest.jar (I GUESS)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/bg20gpPV
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/PDnnRQsq
3. Your townyperms.yml : https://pastebin.com/QrgWhxui
4. Your log's error : https://pastebin.com/uWALQP2u

(optional) If this is to do with permissions, 
5. Your permissions file : Nope, isnt permission

(optional) If this is to do with chat,
6. Your chatconfig.yml : nope
7. Your channels.yml : nope

**Comment by LlmDl** [comment]
You should be using Towny 0.92.0.0 (For MC 1.8.5) ( http://towny.palmergames.com/?p=1099 )
