### ISSUE TITLE
Towny 0.93.1.0 PreRelease-2 can't read Cyrillic characters

### ISSUE THREAD

**Issue by Der-Rei** [TownyAdvanced/Towny#3279]
### What steps will reproduce the problem?
1. Change regex to work with the symbols of the Russian alphabet:
    name_filter_regex: '[ /]'
    name_check_regex: ^[**а-яА-Я**a-zA-Z0-9._\[\]-]*$
    string_check_regex: ^[**а-яА-Я**a-zA-Z0-9\s._\а-яА-Я[\]-]*$
    name_remove_regex: '[^**а-яА-Я**a-zA-Z0-9._\[\]-]'
2. Create a town on the server with a name containing russian characters, for example Абв
3. And everything seems to be fine, but when you restart the plugin can not read the name of the file in the data
![bandicam 2019-05-31 01-17-54-622](https://user-images.githubusercontent.com/45316376/58810630-fc393e80-8626-11e9-8571-8db7908c326f.png)

### What is the expected output?
1. Reading Russian characters by plugin

### What is your Towny version?
0.93.1.0 PreRelease-2

### What is your spigot/craftbukkit version?
spigot-1.14.2

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/5cUvYzN0:
2. Your Towny config.yml  : https://pastebin.com/gXDEhLpw
3. Your townyperms.yml : default file
4. Your log's error : no console errors

**Comment by LlmDl** [comment]
Assuming you used a version of Towny previous to the Pre Release 2, can you do the following:

- Stop the server.
- Open the config and remove the regex lines.
- Start the server to regenerate the new default regex lines (which were new for the pre-release.)
- Stop the server and add your Cyrillic letters. 
- Test as you were doing already.

It's a long shot but if you used to be able to Cyrillic then the missing regex bits might be the hangup.

**Comment by LlmDl** [comment]
Did it used to work on 0.93.0.0?

**Comment by Articdive** [comment]
I know this is a little out of the blue, but are you still keeping your config in the "UTF-8 Encoding" this is an option up at the top of NotePad++ (which I presuume you use because the photos you sent were coloured)

**Comment by Der-Rei** [comment]
> Did it used to work on 0.93.0.0?

I don't remember exactly if I tried it on this version, but on previous versions also the symbols didn't work for me.




> Also are you sure that Regex supports "А-Я", I would of thought it supports something more like this: "\u0400-\u04FF".

I tried to translate "а-яА-Я" to Jjava entities but it didn't help

![image](https://user-images.githubusercontent.com/45316376/58820499-71af0a00-863b-11e9-8a83-97baf3c21970.png)


![image](https://user-images.githubusercontent.com/45316376/58820426-46c4b600-863b-11e9-85be-39f54824f949.png)

**Comment by Der-Rei** [comment]
I have no idea what to do with this error ¯\_(ツ)_/¯

**Comment by karasikq** [comment]
I have the same error on 0.93.0.0, 0.92.0.0, spigot-1.12.2/craftbukkit-1.12.2.
Regex lines changed, file have UTF-8 Encoding.

**Comment by LlmDl** [comment]
@karasikq So what you changed in the KeyValueFile did not solve the issue?

**Comment by LlmDl** [comment]
Anyone experiencing this issue it would be helpful if you could please test using towny 0.94.0.5 or newer, and with the cyrillic characters in your config regex as described above.

**Comment by LlmDl** [comment]
Ok, got things started on this: https://github.com/TownyAdvanced/Towny/commit/bfa944671b915839dbdea4b92e06e003634d442c

```
1/2 the job towards getting Cyrillic characters to work in town/nation
names. Towns can now be named with Cyrillic characters, they appear
properly in game, save properly BUT do not load correctly after a /ta
reload or a full stop and start.
```

**Comment by Articdive** [comment]
Is this appearing on MySQL or Flatfile? This might be a MySQL issue and  probably not loading those characters correctly

**Comment by LlmDl** [comment]
I'm only testing flatfile @Articdive

**Comment by LlmDl** [comment]
So this is basically done. The only remaining thing is a cosmetic issue where Cyrillic characters in the logs are still shown as ????, which @Articdive says he will fix.

**Comment by LlmDl** [comment]
Closing this, tracking new problems in a new ticket: https://github.com/TownyAdvanced/Towny/issues/3385
