### ISSUE TITLE
Towny and Holographic Display errors

### ISSUE THREAD

**Issue by lilacorn** [TownyAdvanced/Towny#3280]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. download 0.93..0.1 Towny
2. download build #77 HolographicDisplays-2.3.3-SNAPSHOT.jar
3. started server

### What is the expected output?
1. 
2.
3.

### What is your Towny version?
0.93.0.1

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-baafee9-043d31d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
https://pastebin.com/kTSK9nLL

i dont think the holographic display issue is anything to do with the towny config, towny perms n etc so i am going to skip the steps below this point....

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
form skipped, resubmit
