### ISSUE TITLE
Holographic Displays issue

### ISSUE THREAD

**Issue by slvlr** [TownyAdvanced/Towny#3282]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
Server Start

### What is the expected output?
No errors

### What is your Towny version?
0.93.1.0 PreRelaese-2

### What is your spigot/craftbukkit version?
Paper 1.14.2 build 65

https://pastebin.com/bA9tLBGC

**Comment by LlmDl** [comment]
Skipped form, resubmit.
