### ISSUE TITLE
Can't find how to translate this line.

### ISSUE THREAD

**Issue by splops** [TownyAdvanced/Towny#3283]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

**In english.yml, i can not find this particular line to translate to other languages.**
https://i.imgur.com/Z1Ar2yx.png

### What is your Towny version?
0.93.1.0 Pre2

Edit: Sorry, idk how to use url

**Comment by LlmDl** [comment]
That's one that's probably been missed. We'll add it soon.

**Comment by TheFlagCourier** [comment]
@splops You should be able to translate these now on subsequent builds from the master branch.
