### ISSUE TITLE
Cant set Outposts

### ISSUE THREAD

**Issue by rotciv02** [TownyAdvanced/Towny#3285]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. /town set outpost
2.  [Towny] Not Registered
3.

### What is the expected output?
1. /town set outpost
2. Outpost Made
3.

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.93.0.0 [CB/Spigot 1.11-1.13]

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/22fb2m8i
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/8pak265v
3. Your townyperms.yml : https://pastebin.com/BttSJjbZ
4. Your log's error : none ?

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Note:
Is this bug purely because the plugin is for 1.13?

**Comment by TheFlagCourier** [comment]
@rotciv02 The version you are testing against is not meant to be compatible with 1.14. I'm sure that this issue has already been addressed. Please retest with the following 0.93.1.0 PreRelease-2 Build: https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar

Also, please make appropriate changes to your config based on the Change Log: https://raw.githubusercontent.com/LlmDl/Towny/master/src/ChangeLog.txt

If you have discord, you can join the Official Towny Advanced server to gain access to these builds with 1.14 compatibility. Link on the project's readme and on the site.

**Comment by LlmDl** [comment]
/town set outpost is only used to move the spawn point of an already existing outpost. Make outpost by using '/t claim outpost' in the wilderness.
