### ISSUE TITLE
1.14.x : Material and Entity API Updates & Required Changes

### ISSUE THREAD

**Issue by TheFlagCourier** [TownyAdvanced/Towny#3286]
There are a few changes that need to be made to the configuration for 1.14 servers in order to match the new Entities and Materials in the API. Server operators will want to replace / add the appropriate entries where applicable - and we will need to re-work the base configuration to include sane defaults. As the master branch is currently still using 1.13, this is low priority until a dedicated branch for 1.13 is created (besides the less-used '1.13-testing' branch.)

## Materials
- Signs: `WALL_SIGN > [WOOD_TYPE]_WALL_SIGN`
- Signs: `SIGN` > `[WOOD_TYPE]_SIGN`
- Slabs: STONE_SLAB now represents a different block, Old STONE_SLAB is now SMOOTH_STONE_SLAB.
`SMOOTH_STONE_SLAB, CUT_RED_SANDSTONE_SLAB, CUT_SANDSTONE_SLAB, MOSSY_COBBLESTONE_SLAB, SMOOTH_RED_SANDSTONE_SLAB, SMOOTH_SANDSTONE_SLAB, ANDESITE_SLAB, POLISHED_ANDESITE_SLAB, DIORITE_SLAB, POLISHED_DIORITE_SLAB, GRANITE_SLAB, POLISHED_GRANITE_SLAB, MOSSY_STONE_BRICK_SLAB, RED_NETHER_BRICK_SLAB, SMOOTH_QUARTZ_SLAB, ENDSTONE_BRICK_SLAB`
- Stairs: `STONE_STAIRS, ANDESITE_STAIRS, POLISHED_ANDESITE_STAIRS, DIORITE_STAIRS, POLISHED_DIORITE_STAIRS, GRANITE_STAIRS, POLISHED_GRANITE_STAIRS, MOSSY_STONE_BRICK_STAIRS, MOSSY_COBBLESTONE_STAIRS, SMOOTH_SANDSTONE_STAIRS, SMOOTH_RED_SANDSTONE_STAIRS, SMOOTH_QUARTZ_STAIRS, RED_NETHER_BRICK_STAIRS, END_STONE_BRICK_STAIRS`
- Walls: `STONE_WALL, ANDESITE_WALL, DIORITE_WALL, GRANITE_WALL, STONE_BRICK_WALL, MOSSY_STONE_BRICK_WALL, PRISMARINE_WALL, NETHER_BRICK_WALL, RED_NETHER_BRICK_WALL, END_STONE_BRICK_WALL, SANDSTONE_WALL, RED_SANDSTONE_WALL`
- Plants: `CORNFLOWER, LILY_OF_THE_VALLEY, WITHER_ROSE, POTTED_CORNFLOWER, POTTED_LILY_OF_THE_VALLEY, POTTED_WITHER_ROSE, BAMBOO, BAMBOO_SAPLING, POTTED_BAMBOO, SWEET_BERRY_BUSH`
- Generics (Mostly Village): `BELL, BLAST_FURNACE, CAMPFIRE, CARTOGRAPHY_TABLE, COMPOSTER, FLETCHING_TABLE, GRINDSTONE, LANTERN, LECTURN, LOOM, SCAFFOLDING, SMITHING_TABLE, SMOKER, STONECUTTER`
- Storage: `BARREL`
- Special Issue (ie: CommandBlocks): `STRUCTURE`

## Entities
- `Cat` (Extends Animals, Tamable, Sittable)
- `Fox` (Extends Animals, Sittable)
- `Panda` (Extends Animals)
- `Ravager` (Extends Raider)
- `Pillager` (Extends Raider, Illager)
- `TraderLlama` (Extends Llama)
- `WanderingTrader` (Extends AbstractVillager)

**Comment by LlmDl** [comment]
I guess I'll have to finalize things for 1.13 and get a release out for it, then move the master branch onwards.

**Comment by TheFlagCourier** [comment]
Looking over the config nodes, seems like the vast majority of relevant blocks were already added. The only ones that were not seem to be expanding the wooden signs to their various types. Most of the animals are pre-covered, and adding Ravagers / Pillagers to the PROT_MOB_REMOVE_TOWN may be something that we shouldn't default, and let individual servers handle...

**Comment by LlmDl** [comment]
I'm guessing ravagers/pillagers aren't considered Monsters?

Signs aren't usually considered switches, unless you can edit signs after they're placed now?

**Comment by TheFlagCourier** [comment]
Assuming `Signs can now be used while holding a dye to change the text color. `, then sorta'. Plugins like CMI that include a method to change the signs text may also benefit from the change there.
And I seem to have misspoke, as Ravagers do fall under the Monster super-interface. Pillagers as well...

**Comment by LlmDl** [comment]
Yeah we should either do the signs themselves, or maybe just put the dyes into the item_use list, since it probably won't be long before more things can be dyed.

**Comment by TheFlagCourier** [comment]
I'm now wondering if adding the dyes would prevent sheep from being dyed as well...
Went ahead and added the signs under protected switches in the PR's commit chain.

**Comment by LlmDl** [comment]
Adding the signs to the default switch list will probably screw up all kinds of sign shop plugins/command signs plugins. The plot owner would have to give access to all of the plots' chests/switches in order for the other plugins to work. They'll have to be removed from teh switch list and the dyes added to the itemuse list instead.

**Comment by TheFlagCourier** [comment]
Fair point.

**Comment by LlmDl** [comment]
so it looks like just accounting for the illager and ravager are whats still needed for this,

**Comment by LlmDl** [comment]
So the Pillager and Ravager are inherited from Monster, so as far as I can tell there's nothing left to add from the above lists that isn't handled normally.
