### ISSUE TITLE
 error in Towny 1.14.2

### ISSUE THREAD

**Issue by 79372275372** [TownyAdvanced/Towny#3287]
Hello, I use towny on version 1.14.2 and an error occurs with the privatization of territories, the issuance of territories and the privat outpost, it also does not read outposts. Economy changed, did not help.

I downloaded the version of my plugin below.

I need an urgent fix, the players are not thrilled.
[town.zip](https://github.com/TownyAdvanced/Towny/files/3268253/town.zip)

### What steps will reproduce the problem?
1. impossible to sell new chunks /plot claim
2. impossible to buy outpost, ass passes, outpost does not appear /t claim outpost
3. land grab error /t claim

### What is your Towny version?
Do not say "latest". 
[latest.log](https://github.com/TownyAdvanced/Towny/files/3268252/latest.log)

(optional) pastebin: https://pastebin.com/S8suGQHz

**Comment by LlmDl** [comment]
Skipped form (and thought that adding (optional) makes that ok)

Either way, you should be using Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf
