### ISSUE TITLE
Large Ram consumption

### ISSUE THREAD

**Issue by Sykursen** [TownyAdvanced/Towny#3288]
Hello,
I'm the administrator of a small minecraft server with 20 players connected simulatenously every day and I regularly encounter problems on the ram consumption of the towny plugin.

I'use 6681 Megabytes of ram and towny user 4.62 gb just himself.
![image](https://user-images.githubusercontent.com/18405490/59148382-f01ef980-89f7-11e9-9d82-d46e31ace097.png)

I don't know if the plugin is subject to memory leaks, but it's huge as a consumption for just one plugin.

Can you do anything about it?

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
git-Spigot-1a3504a-dfa7583 (1.13.2)

**Comment by LlmDl** [comment]
That isn't Towny's use of the RAM, that is how much RAM your server is using.
