### ISSUE TITLE
Bug: Claims in towns revert, or plot's are set to unowned, after server restart.

### ISSUE THREAD

**Issue by JamesAries** [TownyAdvanced/Towny#3289]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Claim a piece of territory for your town.
2. /plot forsale and have somebody claim it.
3. Restart server after saving.
4. Plot will possibly be unowned.

This occurs to plots which have been claimed or owned for a very long time previously. It happens after every server restart, despite the server saving commonly.

### What is the expected output?
1. The plot will stay owned by the correct person.
2. The claim will remain claimed after the restart.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
1.42.2 R01

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/XsASgGpf
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/4GrUjFmB
3. Your townyperms.yml :
https://pastebin.com/sKwq3JPG
4. Your log's error: NONE PRODUCED

**Comment by LlmDl** [comment]
You should be using Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf
