### ISSUE TITLE
1.14.2 Towny is not saving plot data

### ISSUE THREAD

**Issue by Kbryst** [TownyAdvanced/Towny#3291]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Players will create a town/outpost and then claim plots.
2. At some point (I believe at server restart) all plots are unclaimed. Most towns go back to only owning their homeblock.

### What is the expected output?
1. For their plot data to save.

### What is your Towny version?
0.92.0.14

### What is your spigot/craftbukkit version?
Paper #69 1.14.2, 7 versions behind latest.

Note: I will not give out full info from a production server, but I was able to recreate it on a test server with just limited plugins. The following is from the test server, it looks to be the identical issue. 

1. Your full server startup from the logs\latest.log :
https://pastebin.com/PE4P8gGD

2. Your Towny config.yml (if using MySQL please remove password,) :
*Tested with default yml

3. Your townyperms.yml :
*Tested with default yml

4. Your log's error : 
**Full log is inside the startup log, here's the main part.
https://pastebin.com/VgR2bdF8

**Comment by LukeTheWelder** [comment]
Following, I have the same exact issue.

**Comment by TheFlagCourier** [comment]
That version of Towny does not support 1.14.x.
Please use 0.93.1.0 pre release, available from the Discord (#new-builds) or by building from the master branch.

**Comment by Kbryst** [comment]
Didn't realize there's a discord lol. Took a while to find it, its under "Towny on Discourse". For anyone looking for it.

**Comment by Kbryst** [comment]
found a new issue with this one, will create a new thread to avoid confusion.
