### ISSUE TITLE
1.14.2 ./plot claim - does not work

### ISSUE THREAD

**Issue by Kbryst** [TownyAdvanced/Towny#3292]
### What steps will reproduce the problem?
1. Run command /plot claim

### What is the expected output?
1. User claims plot

### What is your Towny version?
0.93.1.0

### What is your spigot/craftbukkit version?
Paper 1.14.2 #76

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :  https://pastebin.com/w8udAQLw
2. Your Towny config.yml :  Default yml
3. Your townyperms.yml :  Default yml
4. Your log's error :  https://pastebin.com/8K4TbDZ8

**Comment by pheph3** [comment]
i have this exact issue i believe its an API change with vault and or essentials that causes it

**Comment by TheFlagCourier** [comment]
Yes, this is an issue with EssentialsX's 1.14 compat at this time. It is not an issue with Towny. You may have luck using the [EssentialsX-Experimental](https://ci.ender.zone/job/EssentialsX-Experimental/) builds, but our recommendation is to use a economy with full 1.14.2 / Vault 1.7.x compatibility - or [TheNewEconomy](https://github.com/TheNewEconomy/TNE-Bukkit)

**Comment by pheph3** [comment]
okay it what i thought and i do have vault 1.7.2 and get same issue so im going to wait for essentials update it should be coming around soon

**Comment by pheph3** [comment]
according to there discord atleast it roughly 96% done
