### ISSUE TITLE
ERROR Could not pass event PlayerChangePlotEvent to Towny v0.93.0.0

### ISSUE THREAD

**Issue by Klawdek** [TownyAdvanced/Towny#3296]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. It just started happening I have no idea why or what is causing it.
2.
3.

### What is the expected output?
1.  No gient errors in console
2.
3.

### What is your Towny version?
Do not say "latest".
Towny version 0.93.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
[latest.log](https://github.com/TownyAdvanced/Towny/files/3294581/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/5AUvghH9

3. Your townyperms.yml :
https://pastebin.com/V07RS1m8
4. Your log's error : 
https://pastebin.com/bbabSkTJ
(optional) If this is to do with permissions, 
5. Your permissions file :
WHat permissions file???????
(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Klawdek** [comment]
Please do not make the claim that this is a duplicate issue as has been done with every other post about this issue except the one that were dismissed for failing to file form correctly.  I can find no posts that actually give any advice how to fix this.  They all claim it is a duplicate issue and say to see the explanation in another post for which there is either no link,  or the link is to this post https://github.com/TownyAdvanced/Towny/issues/2236 which has nothing to do with this issue.

**Comment by LlmDl** [comment]
Please try out the build for 1.13/1.14:
Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

**Comment by AustinGarrettRichards** [comment]
Still an issue on Towny 0.93.1.0

**Comment by LlmDl** [comment]
Should be fixed in https://github.com/TownyAdvanced/Towny/commit/1f1f1ea882c6b22550bd97ec98b9f4efe762aeda
