### ISSUE TITLE
Exception thread

### ISSUE THREAD

**Issue by Jordan-Mianite** [TownyAdvanced/Towny#3299]
21.06 23:31:19 [Server] WARN Exception in thread "Thread-46" java.lang.IllegalStateException: PlotChangeOwnerEvent may only be triggered synchronously.
21.06 23:31:19 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524)
21.06 23:31:19 [Server] WARN at com.palmergames.bukkit.towny.object.TownBlock.setResident(TownBlock.java:85)
21.06 23:31:19 [Server] WARN at com.palmergames.bukkit.towny.tasks.PlotClaim.residentClaim(PlotClaim.java:194)
21.06 23:31:19 [Server] WARN at com.palmergames.bukkit.towny.tasks.PlotClaim.run(PlotClaim.java:76)

**Comment by LlmDl** [comment]
Form skipped. Resubmit.
