### ISSUE TITLE
Residents (and outsiders/allies) cannot kill mobs in farm plots, not even hostile ones.

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3300]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Set plots to be farm plots
2. Enable mobs in the plots.
3. Have a regular resident (or a non-resident) attempt to kill the mobs.  They won't be able to, not even hostile mobs (hostile mobs were tried with all plot permissions turned on).  This was initially noted for hostile mobs, but later confirmed that residents could also not kill farm animals.

### What is the expected output?
1. Anyone should be able to kill a hostile mob anywhere in town, even on farm plots
2. Residents should be able to kill farm animals on farm plots with friend permissions on. (For some reason farm plots take friend perm settings, not resident ones...probably should be a separate ticket)
3. Even if 1) isn't true, adding hostiles to the config for farm plots should allow them to be killed.

### What is your Towny version?
Do not say "latest".
0.93.1.0, pre-2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 1.13.2, build 632

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/kxYKEa0a

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/skUeREUZ
Please note that the config when I first tried this had the default line for animals that could be killed in a farm plot.  I added the others seen in this file in an attempt to fix this issue.

3. Your townyperms.yml :
https://pastebin.com/12ZCBACp

4. Your log's error : 
No error.

(optional) If this is to do with permissions, 
5. Your permissions file :   Here's the default group:
https://pastebin.com/jf6eD8jC

**Comment by LlmDl** [comment]
Is the plot player-owned for town-owned?

When you do /plot perm what does it say?

**Comment by Momshroom** [comment]
Town owned

**Comment by Momshroom** [comment]
http://prntscr.com/o5e1wj

**Comment by Momshroom** [comment]
On my test server, running 0.93.1.0 (not pre 2) residents CAN kill hostile mobs on farm plots.  On my production server, running pre 2, they cannot.  On neither server can non-residents kill hostile mobs on farm plots.

**Comment by LlmDl** [comment]
We changed the handling of farm animals from just allowing town residents, to using the plot perm's destroy setting. So if a resident/ally/outsider can destroy crops/farm blocks in a farm plot, they can also now kill farm animals. 

If having done /plot set perm outsider on, didnt fix killing of farm animals in the plots then there's a bigger problem here.

If they cannot kill monsters that's probably something we have to look into as well.

**Comment by Momshroom** [comment]
As you can see in the screenshot, destroy is ON for residents in the plot and residents cannot kill farm animals.  They also cannot kill monsters.  Once I promote the user to assistant, they can kill mobs.

**Comment by LlmDl** [comment]
Should be fixed as of https://github.com/TownyAdvanced/Towny/commit/4fe82958138a62077f5ea95bde47efe429d67277
