### ISSUE TITLE
1.14.2: PlayerChangePlotEvent 0.93.1.0 PreRelease-2

### ISSUE THREAD

**Issue by knaxelbaby** [TownyAdvanced/Towny#3301]
### This was solved when updating to the most recent dev of essentialsx  along with towny not saving towns

This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. I claim townblock outside of the homeblock
2.then leave the town
3.entering any townblock will cause the error and not send the message for entering a town

### What is the expected output?
1. The message for entering a town

### What is your Towny version?
Do not say "latest".
**Towny 0.93.1.0 PreRelease-2**

### What is your spigot/craftbukkit version?
Do not say "latest".
CraftBuikkit git-spigot-df0eb25-30a6337 (mC: 1.14.2) Implementing API version 1.14.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/MPFb4FLT
2. Your Towny config.yml (if using MySQL please remove password,) :
default(just generated)
3. Your townyperms.yml :
default(just generated)
4. Your log's error : 
https://pastebin.com/KTXTqGba

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : default english.yml
7. Your channels.yml :

**Comment by knaxelbaby** [comment]
also not saving towns, I have seen the previous posts. But am using the most recent dev

**Comment by LlmDl** [comment]
So updating essentialsX fixed all of the above issues?

**Comment by Focusprw** [comment]
> So updating essentialsX fixed all of the above issues?

I using EssentialsX  2.17.0 (For 1.14), I have bugs same as Knaxelbaby.

**Comment by LlmDl** [comment]
Shouldn't be a Towny issue after the following commit: https://github.com/TownyAdvanced/Towny/commit/1f1f1ea882c6b22550bd97ec98b9f4efe762aeda
