### ISSUE TITLE
Plot Claim Economy Error stack

### ISSUE THREAD

**Issue by jbuddy87** [TownyAdvanced/Towny#3302]
Ive been having issues gettign towny setup for 1.14
im sorry if i dont make this post right.

### What steps will reproduce the problem?
1. Just claiming a plot while having enough funds in the account
2. I tested with craftconomy
3.

### What is the expected output?
1. to give ownership of the plot 
2. (its still takes the players money)
3.

### What is your Towny version?
Towny v0.93.1.0 PreRelease-2

### What is your spigot/craftbukkit version?
spigot 1.14.2-r0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :
https://pastebin.com/DsX9CCet
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/VLz2rF6b
3. Your townyperms.yml :
https://pastebin.com/NhgFyvch
4. Your log's error : 
https://pastebin.com/Sh6g4Sin

im not sure if it has to do wtih permissions or chat : P

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Looks like craftconomy isn't ready for 1.14. Use HellEconomy or TheNewEconomy (the latter is you want a physical economy.)
