### ISSUE TITLE
Daily upkeep not collected

### ISSUE THREAD

**Issue by Freddo3000** [TownyAdvanced/Towny#3303]
### What steps will reproduce the problem?
1. Create a Papermc (# 112) server running Towny, Vault and iConomy 5.8/EssentialsX/Gringotts
2. Launch it and create a town
3. /townyadmin newday
4. Check logs.

### What is the expected output?
Upkeep and taxes should be collected, and broke towns deleted.

### What is your Towny version?
From config.yml: 0.93.1.0 PreRelease-2

### What is your spigot/craftbukkit version?
Papermc # 112

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/fShz7jGt
2. Your Towny config.yml (if using MySQL please remove password,) : [Unmodified](https://pastebin.com/ztXztqZZ)
3. Your townyperms.yml : [Unmodified](https://pastebin.com/sQSetnnV)
4. Your log's error : 
	- [EssentialsX](https://pastebin.com/2R9cdGDC)
	- [Gringotts](https://pastebin.com/7NcEEsbb)
	- [IConomoy 5.8](https://pastebin.com/wekW1Npv)

This issue might be related to #3297

**Comment by JohnS19** [comment]
I think that is an issue with Async, try turning it off and testing it.

**Comment by Freddo3000** [comment]
That appears to be the issue.

**Comment by lukemango** [comment]
https://pastebin.com/fXRqDDcf - error

https://pastebin.com/kQpbRQRp - startup

**Comment by LlmDl** [comment]
Should be fixed as of today's commit: https://github.com/TownyAdvanced/Towny/commit/1f1f1ea882c6b22550bd97ec98b9f4efe762aeda
