### ISSUE TITLE
Claim and tax issues (possible more problems) using Towny in 1.14.3

### ISSUE THREAD

**Issue by Flexxxxx** [TownyAdvanced/Towny#3304]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

**Issue 1:**
### What steps will reproduce the problem?
1. Attempt to claim anything with /t claim outpost, /t claim, /plot claim, etc.
2. Warn will occur in console, after a server restart or a /townyadmin reload the claims vanish. 

### What is the expected output?
1. Run any of the claim commands.
2. Successfully have a new claim/ownership of an area.

**Issue 2:**
### What steps will reproduce the problem?
1. Run /townyadmin newday
2. No taxes are collected. No console errors or warns. Town balances remain unchanged. My test town with a balance of zero did not fall. 

### What is the expected output?
1. New towny day occurs
2. Taxes are collected, towns without necessary finances fall.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
git-paper-115 (MC: 1.14.3)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/7dPBtAYk
2. Your Towny config.yml : https://pastebin.com/UUtUdjY8
3. Your townyperms.yml: https://pastebin.com/EVDwSZcY
4. Your log's error: https://pastebin.com/Z061eb63 (both issues are attached here)

**Comment by LlmDl** [comment]
The first two errors in the link you gave ought to already be fixed with 0.93.1.0 PR 2

Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

The third one is probably not fixed yet but is being tracked in this ticket: https://github.com/TownyAdvanced/Towny/issues/3303
