### ISSUE TITLE
PlotChangeTypeEvent Error, I can't using command /town claim.

### ISSUE THREAD

**Issue by Focusprw** [TownyAdvanced/Towny#3306]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What is your Towny version?
1.13

### What is your spigot/craftbukkit version?
paper 1.14.3 (Build 120 )

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
  - https://pastebin.com/YFHnX6Wd
2. Your Towny config.yml.
 - https://pastebin.com/gn1kv4u5
3. Your townyperms.yml :
 - https://pastebin.com/PHzQLYtV
4. Your log's error : 
- https://pastebin.com/8nhrV1DY
5. Your permissions file :
- Now, I don't use permission plugin.

Question.
Now, Plugin towny can support 1.14 version?
What are your plans for development this plugin?
I like this plugin, I will wait for support 1.14 completely.
Thank you.

**Comment by LlmDl** [comment]
You should be using Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf
