### ISSUE TITLE
1.14.2: Town_prevent_breeding no longer works

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#3307]
Breeding villagers in town claims is no longer able to be toggled. Villager babies spawn within towny claims even when "town_prevent_villager_breeding: 'true'".

Towny 0.93.1.0 Pre release 2
Paper 105

**Comment by LlmDl** [comment]
Looked this up, there's no reason this shouldn't be working still. 

Please supply your config, startup, and whether your world in question has using_towny: true.

**Comment by LlmDl** [comment]
I also need to see your towny\data\worlds\WORLDNAME.txt file for the world in question.

**Comment by LlmDl** [comment]
fixed as of https://github.com/TownyAdvanced/Towny/commit/04ef8c7cb72c7b99934ea98a066a521443f8e083
