### ISSUE TITLE
Towny Commands stop working for players on 1.13+ 

### ISSUE THREAD

**Issue by MamaBeau** [TownyAdvanced/Towny#3308]
### What steps will reproduce the problem?
1. Join my server
2. Play for a while on 1.13+ 
3. It is random when it happens, but it happens a lot.

### What is the expected output?
1. That the commands would work as they should.

### What is your Towny version?
- 0.93.1.0

### What is your spigot/craftbukkit version?
Paper - 1.13.2

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : I literally cannot provide this, my startup log is too long and crashes Pastebin and HasteBin.
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/VYuW4nUa
3. Your townyperms.yml :
https://pastebin.com/HLEa8407
4. Your log's error : No Errors

**Comment by MamaBeau** [comment]
I know you said in previous tickets that you couldn't reproduce this issue. I invite you to my server, where I can ensure you it will happen. The only thing that fixes it, is for the player to relog.

**Comment by LlmDl** [comment]
What does it say in-game when they cannot use a command?

What permission plugin do you use, which version of that plugin is it?

Can you show me a screenshot of the /towny v command's output.

When someone cannot use commands, are other players still able to do so?

Does logging out and logging back in fix it?

**Comment by MamaBeau** [comment]
What does it say in-game when they cannot use a command?
**It doesn't give any information when you cannot use it, it just doesn't register. As far as I understand there are no errors in console when this happens as well.**

What permission plugin do you use, which version of that plugin is it?
**LuckPerms 4.4.1 - Yes I know there is a compatibility issue with this plugin. I'm hoping I can help you fix that by figuring out this issue.**

Can you show me a screenshot of the /towny v command's output.
https://imgur.com/wL7Mz1n

When someone cannot use commands, are other players still able to do so?
**Yes. It seems to be local. It doesn't affect everyone at the same time.**

Does logging out and logging back in fix it?
**Yes, logging out of the server does fix this issue most of the time.**

**Comment by LlmDl** [comment]
That's the luckperms sync thing that's been going on for months/years.

I'm pretty sure LP 4.4.1 had another problem with it relating to Towny as well. You can get Luck's latest build here:  https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/build/libs/LuckPerms-Bukkit-4.4.26.jar

If you're using Towny on 1.13 you should be using Towny 0.93.1.0 PR2 ( https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

**Comment by Momshroom** [comment]
The LP sync issue can also be fixed by de-ranking and re-ranking the glitched player (ie, making them no longer assistant and then assistant again. 

https://github.com/lucko/LuckPerms/issues/1330
