### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3309]
When I download towny 93.0 from the website, does that include the 93.1.0 update(latest) or is it just 93.0? Where do I go to find the latest version?  the 93.0 + versions aren't on the website under dev builds.

**Comment by LlmDl** [comment]
You can get the latest by visiting the IRC and saying !using 1.14, or you can go to the discord and visit the #new_builds channel.

Here's the link to 0.93.1.0 PR 2 https://cdn.discordapp.com/attachments/321710042091094026/583426209988476946/Towny.jar

See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf
