### ISSUE TITLE
Remove cheat_protection feature. It has become more problematic with 1.13.

### ISSUE THREAD

**Issue by northerncarrots** [TownyAdvanced/Towny#3313]
### What steps will reproduce the problem?
1. Host a server on Paper 1.13.2
2. Set `cheat_protection: true`
3. Fall then swim into flowing water
4. Anti-cheat teleports player to bottom of water stream

### What is the expected output?
1. Player swims without being teleported
2. Can be achieved with `cheat_protection: false`

### What is your Towny version?
_0.93.0.0_ and _0.93.1.0 Pre Release 2_

### What is your spigot/craftbukkit version?
Tested with _Paper 1.13.2 Build 626_

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/H1db2GK5
2. Your Towny config.yml (if using MySQL please remove password,) : default
3. Your townyperms.yml : default
4. Your log's error : N/A

(I read [issue 2956](https://github.com/TownyAdvanced/Towny/issues/2956#issuecomment-403304295) and understand this feature is not really kept up to date but I would like to report it anyways)

**Comment by LlmDl** [comment]
Nice, a reminder exactly one year to the day that this feature needs to be removed.

**Comment by LlmDl** [comment]
Done: https://github.com/TownyAdvanced/Towny/commit/26fc32ccc0aa58492156014b9c32e6676656da63
