### ISSUE TITLE
Towny generating issues with Slimefun

### ISSUE THREAD

**Issue by DjagaMC** [TownyAdvanced/Towny#3315]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Get Towny 0.93.0 (or higher/lower) and Slimefun on a 1.14+ server
2. Do /sf guide, nothing shows up on the logs
3. Open the book, a ton of error messages show up
4. Nothing else really happens, but the server has crashed a ton of times using ProtocolLib with this setup so I had to remove it (without Towny it doesnt give any errors)

### What is the expected output?
1. No errors in console
2. No crashing (not 100% sure if it's on Towny's side)

### What is your Towny version?
Do not say "latest".
Used 0.93.0 and 0.93.1.0 pre release 3

### What is your spigot/craftbukkit version?.
Used Paper 1.14.3, Spigot 1.14.3 and CraftBukkit 1.14.3. All give the same issue. (log contains CraftBukkit 1.14.3)

1. Your full server startup from the logs\latest.log :
https://pastebin.com/6NwwKQ6U at 17:04:36 I'm opening the /sf guide book

2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Dk0ViVer

3. Your townyperms.yml :
https://pastebin.com/6cmLrccs

4. Your log's error :
https://pastebin.com/XhfiNW94

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Got a link to the slimefun plugin you're using? Just opening a book doesn't do anything for me.

**Comment by LlmDl** [comment]
Nevermind I grabbed https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/Slimefun4-124.jar and had no issue using /sf guide and then opening the book.

Maybe start removing plugins to find which one is making Towny have those errors. It could probably be Protocolib if it is not the right version for your version of MC/Paper Spigot.

**Comment by DjagaMC** [comment]
I did that already, none of them make it go away. This is very confusing.. I mean as long as it's not a big deal, it's okay

**Comment by LlmDl** [comment]
If you test with just Towny, Slimefun and vault/eco plugins what happens?

**Comment by DjagaMC** [comment]
Uhh I will test this evening

**Comment by LlmDl** [comment]
2 Weeks no feedback, closing ticket for the meantime.
