### ISSUE TITLE
Take the players out of their purchased plots

### ISSUE THREAD

**Issue by andfont** [TownyAdvanced/Towny#3316]
mc spigot version: 1.14.3
towny version: 0.93.1.0
description problem bug:
 for example they buy a plot for 10 of money the next day they lose the plot! and it goes on sale at cost 0, he throws them out of their plot and they have money to pay for the taxa. in summary the next day when I restart the server it takes them out of their plot :(
but it does not happen with all the plots! some do not cast them and we do not know what is happening, with mc 1.13 it did not happen.
Error: 
it does not give any error that we see, just throw most players and we have them angry! Please, is urgent!

**Comment by LlmDl** [comment]
show me your startup log, config, permission file.

**Comment by andfont** [comment]
http://www.mediafire.com/file/8ezsbpz15rnb8iw/Towny.zip/file
I send you all the information but this problem is only happening in 1.14

**Comment by LlmDl** [comment]
You should be using Towny 0.93.1.0 PR4 ( https://cdn.discordapp.com/attachments/321710042091094026/597844593614258177/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

If this does not fix it, please file a new ticket and do not skip the form.

**Comment by andfont** [comment]
Hello, do not close! the incidence please, we are using the:
16:59:59] [Craft Scheduler Thread - 511/INFO]: [MineBackup]  * saving worlds\mundoabf_nether
>version Towny
[17:00:02] [Server thread/INFO]: Towny version 0.93.1.0
[17:00:02] [Server thread/INFO]: Resident-Town-Nation heirarchy combined with a grid based protection system. Including a war event.
We are already using the version you mentioned and it does not work

**Comment by LlmDl** [comment]
You have 0.93.1.0, what I linked is 0.93.1.0 Pre-Release 4. Use the one I linked.

**Comment by andfont** [comment]
They are different? They are different? ok sorry we tried it thank you
