### ISSUE TITLE
Change plot farm "trigger" material

### ISSUE THREAD

**Issue by eUipKh** [TownyAdvanced/Towny#3317]
Hello, it is possible to change this "trigger" ([link](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/utils/CombatUtil.java#L192)) to WHEAT instead of DIRT to let players kill allowed animals in farm plots?

As you mentioned [here](https://github.com/TownyAdvanced/Towny/blob/2361ec7f51b385c215b8d5093a74ca3eda976712/src/com/palmergames/bukkit/config/ConfigNodes.java#L421) not all servers add  this three blocks (GRASS_BLOCK,FARMLAND,DIRT) to their list

**Comment by LlmDl** [comment]
The one you linked is for just normal animal PVP, the test on line 180 is the one for farm plots, which is already set to use wheat.

**Comment by eUipKh** [comment]
The thing is that whitout adding DIRT to the 'farm_plot_allow_blocks' list it does not allow players to kill the animals in the 'farm_animals' list even if they have all the required plot perms to do it

**Comment by LlmDl** [comment]
Which version of Towny are you using?

**Comment by eUipKh** [comment]
Im using Towny v0.93.1.0 Pre Release 4

**Comment by eUipKh** [comment]
Pd: Players can destroy/place crops, logs, flowers, etc on fram plots the only problems is with the mobs

**Comment by LlmDl** [comment]
Can you pastebin.com your config

**Comment by eUipKh** [comment]
config: https://gist.github.com/eUipKh/5e7330b51ce38c113a013f5256ada5ef
screen: https://imgur.com/hGPmvNI
mobs tested: cows and sheeps

**Comment by LlmDl** [comment]
And the testers are residents of that town?

**Comment by eUipKh** [comment]
Yes

**Comment by LlmDl** [comment]
Fixed as of https://github.com/TownyAdvanced/Towny/commit/6d97bf3f0444f35a02f4c58906d3a391391c7c7c

**Comment by eUipKh** [comment]
I haven't had time to test it yet but thank you for the update, I will update this comment once I do.

**Comment by LlmDl** [comment]
Great, I did some testing myself and what was wrong was a pretty simple thing once I spotted it. As far as I can tell other non-farm entities are also still handled properly.

**Comment by eUipKh** [comment]
I just tested it and works perfectly fine! 
Again, thank you for the update and sorry for the late response
