### ISSUE TITLE
1.14 Towny Plot Claim (Ownership) Throws Exception

### ISSUE THREAD

**Issue by StirFryBeans** [TownyAdvanced/Towny#3318]
When performing a /plot claim command, Towny throws an exception related to the threading changes in 1.14. This issue is nearly identical to that experienced in [Issue 3231](https://github.com/TownyAdvanced/Towny/issues/3231) except that it occurs when using the plot ownership functionality versus the town claiming bit.

### What steps will reproduce the problem?
1. Create a town.
2. Claim a plot outside of the homeblock.
3. Put that plot for sale using /plot fs.
4. Claim that plot using /plot claim.
5. Exception is thrown.
6. On a server restart, plot reverts to being for sale.

### What is the expected output?
1. Create a town.
2. Claim a plot outside of the homeblock.
3. Put that plot for sale using /plot fs
4. Claim that plot using /plot claim
5. No exception thrown, command performs successfully. 
6. On a server restart, player retains ownership of plot.

Using Towny version 0.93.1.0

Using Spigot version Spigot-5e4e7f3-5f88938 for 1.14.3. Latest build as of 7/11/2019. 

1. [Latest Log](https://pastebin.com/jtbuYL3c)
2. [Towny Config](https://pastebin.com/mRgYUfMT)
3. [townyperms.yml](https://pastebin.com/bzxf00bb)
4. [Your log's error ](https://pastebin.com/qTqdMfi4)

Assuming this is just because the task is not defined as strictly sync or async.

Thanks for the help!

**Comment by LlmDl** [comment]
You should be using Towny 0.93.1.0 PR4 ( https://cdn.discordapp.com/attachments/321710042091094026/597844593614258177/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf
