### ISSUE TITLE
"Null" When Performing Towny Rank Commands

### ISSUE THREAD

**Issue by StirFryBeans** [TownyAdvanced/Towny#3320]
Receiving a "Null" message in chat when performing any Towny rank add/remove commands. Ranks will initially show correctly when using /town, but will revert all users to default after a server restart. 

There is no console error when performing the commands, or any indication of the error outside of the [Towny] null message.

I have reproduced this using a minimum install of  Spigot-5e4e7f3-5f88938, Vault, EssentialsX 1.7.3, and Towny 0.93.1.0 Pre-Release 4.

### What steps will reproduce the problem?
1. Create a town.
2. Perform a /towny rank add/remove command.
3. "[Towny] null" is received in chat. 
4. Performing /town will show the ranks listed correctly.
5. After a server restart, all ranks will revert to just "Resident".

### What is the expected output?
1. Create a town.
2. Perform a /towny rank add/remove command.
3. Receive confirmation message.
4. Performing /town will show the ranks listed correctly.
5. After a server restart, residents of town will retain their ranks.

Reproduced with Towny 0.93.1.0 Pre Release 4 on Spigot-5e4e7f3-5f88938 for 1.14.3.

Requested Files:
1. [latest.log](https://pastebin.com/vUwwKQXv) (No error is logged in console)
2. [config.yml](https://pastebin.com/9QZ7Hztd)
3. [townyperms.yml](https://pastebin.com/xDwXG0YN)
4. No error is logged in console.

**Comment by JohnS19** [comment]
+1 
Version: Paper 127 (1.14.3)
Same towny version

Ranks get added but the message just displays 'null'.

**Comment by silverwolfg11** [comment]
I had the same issue. Looking through the code, I believe it's a simple fix by returning valid handlerlists in the method getHandlers() in both the TownAddResidentRank and TownRemoveResidentRank events, rather than returning null.

**Comment by LlmDl** [comment]
@silverwolfg11 if you'd like to fix it up and make a pull request it would be very welcome

**Comment by Flexxxxx** [comment]
+1
Version: Paper 131 (1.14.3)
Same towny version

Same problems here, running it through TownyAdmin also returns internal error.
Error: https://pastebin.com/abDjUZCJ

**Comment by LlmDl** [comment]
If someone could test this for me and let me know if it solves the problem:

https://cdn.discordapp.com/attachments/388338495036456960/601066276655464478/Towny.jar

**Comment by Flexxxxx** [comment]
Tested on a dev server and a live 1.14.3 server. Can confirm it works perfectly on both. Thank you!

**Comment by LlmDl** [comment]
Fixed as of https://github.com/TownyAdvanced/Towny/commit/142a774dd892464fc1cf38a118cb4c66bfb6ac00
