### ISSUE TITLE
Plot claim not working

### ISSUE THREAD

**Issue by PhoenixMods** [TownyAdvanced/Towny#3321]
When i try to claim a plot there is for sale, it stops at Processing Plot Claim...
I do not lose money.
And the plot is still up for sale.

### What is your Towny version?
Towny 0.93.1.0 Pre Release 4

### What is your spigot/craftbukkit version?
1.14.2

Log: https://pastebin.com/aNFq41bH
Towny config: https://pastebin.com/FWNXuRR4

**Comment by LlmDl** [comment]
looks like your eco plugin needs a 1.14 update

**Comment by PhoenixMods** [comment]
What Economy does so work, i have tried many of them, but i still get the error.

**Comment by PhoenixMods** [comment]
Got it fixed by putting EssentialsX in and keeping Essentials in server to.
