### ISSUE TITLE
Suggestion: Add Bukkit events for economy actions (deposit/withdraw)

### ISSUE THREAD

**Issue by dextonanderson** [TownyAdvanced/Towny#3322]
It would be great if there was an event which fired whenever a user deposits or withdraws funds from a Town or Nation bank.

Possibly, there could be two Cancellable events for this: `TownEconomyEvent` and `NationEconomyEvent`

The events should have:
- the user who initiated the action
- the amount in question
- the previous balance before the action
- the final balance after the action
- access to the Town/Nation object
- an enum or boolean flag of the transaction type (deposit/withdraw).

**Comment by creatorfromhell** [comment]
To expand on this: I think "an enum or boolean flag of the transaction type (deposit/withdraw)." should be a String type in case plugins that wish to extend Towny's economy function wish to call these events in their towny addon plugin. I.e. maybe a plugin adds stealing capabilities in another plugin, they could call it with the type of "stole".

**Comment by dextonanderson** [comment]
> 
> 
> To expand on this: I think "an enum or boolean flag of the transaction type (deposit/withdraw)." should be a String type in case plugins that wish to extend Towny's economy function wish to call these events in their towny addon plugin. I.e. maybe a plugin adds stealing capabilities in another plugin, they could call it with the type of "stole".

That's a great idea
