### ISSUE TITLE
Suggestion: Add Bukkit event for upkeep timer

### ISSUE THREAD

**Issue by dextonanderson** [TownyAdvanced/Towny#3323]
This may be tricky, but an event fired when the upkeep timer is executed would be great.

The event should contain:

- A collection of fallen Towns/Nations
- The town upkeep amount taken
- The nation upkeep amount taken
- The Unix time of when the timer executed
- maybe more?

**Comment by LlmDl** [comment]
Done as of https://github.com/TownyAdvanced/Towny/commit/0877a1153a4398e1fa5f628b26fb7b0de6ab9032

Will be a part of 0.95.0.1
