### ISSUE TITLE
Plot Names/Notifications Aren't Displayed in Chat

### ISSUE THREAD

**Issue by yifftoast** [TownyAdvanced/Towny#3325]
### What steps will reproduce the problem?
Cannot reproduce the issue. All Towny.jar versions that I have tried do not display plot notifications in chat.

### What is the expected output?
No plot notifications but an awkward notification in the middle of the screen stating either "Wilds" or "Town Name".

### What is your Towny version?
Do not say "latest".
0.93.1.0 Pre Release 4 (For 1.13 & 1.14 Servers)

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.14.3

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/bJLTL9x0
2. Your Towny config.yml : https://pastebin.com/vRB9tiLf
3. Your townyperms.yml : https://pastebin.com/d7Y7GmS8
4. Your log's error : No detectable errors.

(optional) If this is to do with chat,
5. Your chatconfig.yml : https://pastebin.com/4szSWbdQ
6. Your channels.yml : https://pastebin.com/tnfB8PXa

**Comment by eUipKh** [comment]
Change 'using_titles' to false in your config.yml

**Comment by LlmDl** [comment]
That will solve it, but I think the titles feature should be usable _and_ it should also be possible to see plot names.

**Comment by yifftoast** [comment]
Still doesn't work. Changed the specified setting to false and the only difference is that there is no huge message that pops up whenever you walk in or out of town boundaries. 

Sorry for the late response, just got off of work. Is there anything I can upload (screenshots, videos, etc;) to help you guys troubleshoot?

**Comment by eUipKh** [comment]
Oh sorry I thought your only problem was with the titles/subtitles, maybe changing this option 'show_town_notifications' to true could help you

**Comment by LlmDl** [comment]
Nothing yet. I'll try to get this tested out tomorrow.

**Comment by LlmDl** [comment]
What @eUipKh said is the next course of action. I hadn't noticed on the IRC that you had this setting false
```
  # If false it will make it harder for enemies to find the home block during a war
  show_town_notifications: 'false'
```

Please set it to true and let me know what happens.

**Comment by yifftoast** [comment]
It's fixed! I never touched that setting so it must have been someone else with console access. The only problem is that there is a %s next to everything.

**Comment by yifftoast** [comment]
![%s](https://user-images.githubusercontent.com/29941628/61504376-1fd30100-a9a9-11e9-8d62-1d52700b91b3.PNG)

**Comment by LlmDl** [comment]
In your config at line 686:

```
  splitter: '&7 - %s'
```

should be:
```
splitter: '&7 - '
```

**Comment by yifftoast** [comment]
Thanks!
