### ISSUE TITLE
Currently /plot claim is not working

### ISSUE THREAD

**Issue by kazeookami** [TownyAdvanced/Towny#3326]
### What steps will reproduce the problem?
1. Have a town, with several plots.
2. Put up a plot forsale
3. Attempt to claim that plot with /plot claim

### What is the expected output?
1. [Towny]Processing Plot Claim... Message in chat
2. Leave plot, then enter again to find you now own it.

### What is your Towny version?
0.93.1.0 PR5

### What is your spigot/craftbukkit version?
1.14.3

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/xmBZWCqW
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Y8P5K1tT
3. Your townyperms.yml : https://pastebin.com/66Jxjx5H
4. Your log's error : https://pastebin.com/UegxkCa8

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
iConomy 5.05 (Towny Edition) is no longer supported by myself, and it no longer works on 1.14.3 do to it using async improperly. 

You can file a ticket asking @graywolf336 to fix up iConomy, or you can switch over to TheNewEconomy or HellConomy.
