### ISSUE TITLE
Suggestion: Exponential value for towny cost

### ISSUE THREAD

**Issue by monkey8113** [TownyAdvanced/Towny#3328]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

Im suggesting adding exponential cost as an option to the current linear cost towny is using.

![p2m5v7bezrc21](https://user-images.githubusercontent.com/25064806/61597337-da7d3080-ac41-11e9-959c-3a22f753b2e8.jpg)

basically referencing from mcmmo exponential experience value here,
referring to the graph above, The blue line is what towny pricing is now, cost increase with more plot a town have.
Im suggesting exponential cost similar to the green line, the more plot a town have, the cost increase even more. So its friendly to new town and still giving some challenge to big late game player town.

This is taken directly from mcmmo config
`EXPONENTIAL: multiplier * level ^ exponent + base`
with option to modify

Exponential_Values:
  -multiplier: 0.1
  -exponent: 1.92
  -base: 3000

Im suggesting maybe towny can implement is similar to that 
`TOWNY EXPONENTIAL: multiplier * townblock^ exponent + base`
Would be a great way to give extra challenge to late game player with loads of money/control economies yet still friendly for new town which are just starting up.

This is a link to a calculator which can be used to calculate the exponential value whereby X is in this case # of townblock
The value is totally made up
Orange line would be the suggested pricing option 
Green line would be the current linear pricing towny is using
https://www.desmos.com/calculator/a5soublkfo

**Comment by LlmDl** [comment]
Just for notes: 

the /t buy bonus option does have exponential cost increases.

what could be done is adding an exponential cost to the /t claim command.

**Comment by LlmDl** [comment]
This is probably finished but I still need to run some test: https://github.com/TownyAdvanced/Towny/pull/3373/commits/0a07fb380312136b77d4d3e01e18b9c1212be13a

**Comment by LlmDl** [comment]
Done: https://github.com/TownyAdvanced/Towny/commit/d39d26d54c64978c1dbc98cb6159c96f0fc57774
