### ISSUE TITLE
Suggestion: Add missing items to english.yml

### ISSUE THREAD

**Issue by IgnitingIce** [TownyAdvanced/Towny#3334]
I've recently decided to change the style and colors of Towny messages a bit and have come across several things that do not appear to be able to be customized. These include:

- The ".o0o.\_\_\_\_\_\_\_\_.[    ].\_\_\_\_\_\_\_\_.o0o." Header style used for many different things
![Ex 1](https://i.gyazo.com/16564aacb9cb0180537451173007ee13.png)

- The various ranks under /town and /nation (assistant, helper, sheriff)
![Ex 2](https://i.gyazo.com/8284d91cf1dd38ba6c0da377cf202e3a.png)

- The "Friends" line under /resident
![Ex 3](https://i.gyazo.com/c3fdf1ee93805c9caed30da91795c895.png)

- The "Added \<username>" portion of the message given when you /resident friend add \<username>
![Ex 4](https://i.gyazo.com/72023d505172b4c24b154ae7d5bfc024.png)

- The Town and Nation board messages seen upon login
![Ex 5](https://i.gyazo.com/92f6d7432faf48f2adf88ea4346844c7.png)

- The "Build =", "Destroy =", "Switch =", and "Item =" seen after Permissions: and Perm: in /town, /resident, and /plot perm
![Ex 6](https://i.gyazo.com/31b622dee7a6d094d75de45d374eaace.png)

- The error message received when doing various plot commands (/plot perm, /plot evict, /plot clear) when not in a plot: "Not registered."
![Ex 7](https://i.gyazo.com/9a7aaf1e1a2dd9718b83cf007b893d32.png)

**Comment by LlmDl** [comment]
The header style I don't think I'll make customizable, it's too much a part of Towny going back to the first versions, but the rest I can do something about.

**Comment by LlmDl** [comment]
Got this one done yesterday, it'll be part of 0.94.0.4
