### ISSUE TITLE
Issue: Safe mode on launch

### ISSUE THREAD

**Issue by Spzatak** [TownyAdvanced/Towny#3335]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Starting the server
2.
3.

### What is the expected output?
1.Townblock fails to load resulting in safe mode
2.
3.

### What is your Towny version?
Do not say "latest".
0.94.0.3

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.4 build # 147
https://papermc.io/downloads

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/jx23wm8s
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/ye9drpfz
3. Your townyperms.yml :https://pastebin.com/BYFTD6MD
4. Your log's error : https://gyazo.com/3ca78f38d07e88426f5927b92fb13443

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Might be something to do with the new DB so I'm assigning @Articdive so he can take a look.

Can you pastebin.com the townblock's .data file that it's complaining about?

**Comment by Spzatak** [comment]
https://pastebin.com/MKvqAZTV

**Comment by Spzatak** [comment]
<3

**Comment by LlmDl** [comment]
Do you still have a townblocks.txt?

**Comment by Spzatak** [comment]
yes, and this is it's paste
https://pastebin.com/77abncbx

**Comment by LlmDl** [comment]
Of note: that townblock has no town. I believe we used to have some code that ignored and removed townblocks with no town.

**Comment by LlmDl** [comment]
Your other townblocks still have towns right?

**Comment by Spzatak** [comment]
https://gyazo.com/bb3ea89e952f234950657897cff86b09
/plugins/Towny/data
also:
Yee there are alot of townblock with no town it appears

**Comment by Spzatak** [comment]
The server has a single town currently, with around 12 blocks

**Comment by LlmDl** [comment]
What version did the server start on?

**Comment by Spzatak** [comment]
roughly 1.11.x

**Comment by LlmDl** [comment]
Towny version?

**Comment by Spzatak** [comment]
Towny version it started on? I don't believe i have that knowledge anywhere but It was likely the most 
recent release build around december 2016

**Comment by LlmDl** [comment]
If you open a backup from before you updated to the 0.94.0.1 or higher, does your townblocks,txt still include that townblock it's complaining about, and does that townblock have no town?

**Comment by Spzatak** [comment]
Do you recall the release date of 0.94.0.1

**Comment by LlmDl** [comment]
Four days ago we put up 0.94.0.1 on the #new_builds channel of the discord.

It wasn't up for long because it had a flaw.

**Comment by LlmDl** [comment]
I'm mostly wondering if the townblocks that have no town are old ones that were being ignore before but aren't with the new DB. If you went to where they should exist, should there be a town there?

**Comment by Spzatak** [comment]
It appears as though i had previously made a town named surreal to test a few things, and deleted it.
Upon town deletion i have chunk snapshot resetting enabled, so
At one point there was a "town" there, but there no longer is, nor trace of it

**Comment by Spzatak** [comment]
it does include that townblock, and it is still registered to "surreal", however said town was deleted such a long time ago that i do not have it in the deleted town files way back to february 2nd to today before i updated past 0.94.0.1
I also for the record, updated towny today.

**Comment by LlmDl** [comment]
I bet if you tried running 0.94.0.0 using your current data folder, it would load fine?

**Comment by Spzatak** [comment]
HAH! Installing that  provided this:
https://pastebin.com/iZy6vjjr
and then I installed the latest version and it launched with no issue.

a side result:
perhaps the data for removing un-used blocks isnt fully operational in the latest build?

**Comment by Spzatak** [comment]
In other words this is solved but perhaps an issue for you to note has arrived? I am at a loss , 
but im appalled by the support you provide. Over like 2 years 3 years anytime ive had a full blown issue 
youve been prompt to helping <3

**Comment by LlmDl** [comment]
How old of a version were you using before you went past 0.94.0.0?

**Comment by Articdive** [comment]
This should be assigned to @KarlOfDuty it's his automatic code removing townblocks having an issue.

**Comment by KarlOfDuty** [comment]
The code I added does not touch townblocks at all, it only fixes broken nation files and broken town files.

**Comment by LlmDl** [comment]
So as far as I can tell this isn't an issue, it was just from updating from a really old towny that didnt have the nulltownblockremoval code, to one using the new database which doesn't handle null townblocks very well.

**Comment by Spzatak** [comment]
I apologize, I am not sure how old the prior version was. Thank you very much for you help <3
