### ISSUE TITLE
Towny constantly goes into safe mode every day or so

### ISSUE THREAD

**Issue by clogan12** [TownyAdvanced/Towny#3337]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. The server will just crash and go into safe mode every 24 hours or so
2.
3.

### What is the expected output?
1. Towny is stuck in safemode and all the townblocks are messed up
2.
3.

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.94.0.0 

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.13.2
[townyfiles.txt](https://github.com/TownyAdvanced/Towny/files/3438414/townyfiles.txt)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Can you pastebin.com the townblocks.txt file it is complaining about?

Other than that, crashing can be bad. If your server didn't crash it probably wouldn't corrupt.

**Comment by clogan12** [comment]
[GEvw67qP.txt](https://github.com/TownyAdvanced/Towny/files/3438457/GEvw67

**Comment by clogan12** [comment]
> Other than that, crashing can be bad. If your server didn't crash it probably wouldn't corrupt.
The first time it crashed, sometimes it just goes into safe mode and it's very irritating(ie every time I restart the server)

**Comment by LlmDl** [comment]
So what do you have for world names?

**Comment by clogan12** [comment]
@LlmDl a comma and an apostrophe

**Comment by LlmDl** [comment]
You can't have those and use Towny.

**Comment by clogan12** [comment]
@LlmDl what should I do? Just change the name?

**Comment by LlmDl** [comment]
Use world names are names and do not include punctuation.

**Comment by clogan12** [comment]
@LlmDl Can I just change the world names or do I have to change all the towny files?

**Comment by LlmDl** [comment]
Well the towny files wont load as they are, so they have to be changed. The worlds have to all be changed too.

**Comment by clogan12** [comment]
@LlmDl How can I change them(I changed the world name, what should I do for towny files?)

**Comment by LlmDl** [comment]
you're going to have to go through all of the townblocks.txt and then the townblocks\ folder and change them. 

Here's what the townblocks.txt ought to look like: 
```
world,-1690,327
world,-1358,-1360
world,-1690,326
world,-1358,-1361
world,-1690,325
world,-1358,-1362
world,-1690,324
world,2086,-172
world,2086,-173
```

The worlds.txt and towny\data\worlds\WORLDNAME.txt files will also have to be changed.

All of the towny\data\towns\TOWNNAME.txt files will have to have their spawns, homebocks and outpostspawns fixed.

That should be about all teh places that towny records worlds.

**Comment by clogan12** [comment]
@LlmDl is there a fast way to do this?

**Comment by LlmDl** [comment]
There would be if one of the worlds wasn't a comma, there's lots of commas that you wouldn't want to replace in the towny database.

Apostrophes are also a very common thing in our files. 

This is why using those symbols as world names is not a thing you should have done.

**Comment by KarlOfDuty** [comment]
Big oof

**Comment by clogan12** [comment]
@LlmDl I did it, but when I start, all towny claims are wiped

**Comment by LlmDl** [comment]
no it can't have an / in it, use only letters and as far as I know, spaces are not allowed either.

**Comment by clogan12** [comment]
@LlmDl so my world is in a folder, so my worlds are like Earth/A Earth/A_nether. This can't be done?

**Comment by LlmDl** [comment]
I wouldnt do it, but if its not broken maybe it'll work
