### ISSUE TITLE
Towny going in Safe Mode when using MySQL Database

### ISSUE THREAD

**Issue by kekke3r** [TownyAdvanced/Towny#3339]
What steps will reproduce the problem?
1 Starting the server

What is the expected output?
Towny enabled

When i start the server Towny goes in Safe Mode, it only occurs when i'm using mysql as a loading and saving  method for the towny database, if i use flatfile or h2 it works fine. It generates correctly the tabs in the database but suddenly it just says "Failed to Load". I've tried deleting db tags and deleting the entire Towny folder but nothing seems to fix this problem.
P.S. The server is new, so there are no towns, no townblocks, no nations and no players registered. It's a clean installation

Towny Version: 0.94.0.3
Spigot Version: Paper Build #137 for 1.14.4 
MySql database: MariaDB
latest.log : https://pastebin.com/xUjfgA1a
Towny config.yml: https://pastebin.com/RapTuq2H
Console log's error  (debug mode on): https://pastebin.com/eDrHkmhH

Also tried to find a workaround and i got another error:
1 Change the config for load/save to flatfile
2 Start server (no errors)
3 Create a town named "test", deposit some money in the bank, claim few plots
4 Stop Server
5 Change the config for load: flatfile, save:mysql
6 Start Server (no errors)
7 Stop Server
8 Chance the config for load/save to mysql
9 Start Server
Error Log on last step: https://pastebin.com/5PJDNaQc
Hope that could be useful someways

**Comment by LlmDl** [comment]
Ok, I've made up a build for you to test. If it works on a blank server using your instructions at the bottom of your ticket, it'll probably work on a production server.

https://cdn.discordapp.com/attachments/388338495036456960/605399472234692638/Towny.jar


Also please note that the following is also included:
```
0.94.0.4:
    - New Command: /resident friend list
      - Returns a list of your friends.
    - Language files bumped to 0.50.
    - New Config Option: economy.daily_taxes.nation_pertown_upkeep
      - Default: false
      - Uses total number of towns in the nation to determine upkeep instead of nation level (Number of Residents)
      - calculated by (number of towns in nation X price_nation_upkeep).
    - New Config Option: economy.daily_taxes.nation_pertown_upkeep_affected_by_nation_level_modifier
      - Default: false
      - If set to true, the per-town-upkeep system will be modified by the Nation Levels' upkeep modifiers.
    - New Language Strings:
      - The following things can now be translated:
        - The "Added " when you add someone to your friendslist.
        - The "Not Registered" message show when the NotRegisteredException exception is called from failed commands.
      - The getFormattedResidents() format which has 3 colours can now have their colours set.
        - These are commonly seen in the /res screen for the friends list; the townranks in the /town screen; the nationranks in the /nationscreen, and probably other places where to show a list of residents.
        - The first colour is the start of the line, the second colour is the [#] section, the third colour is the list of resident names.
    - Changed Command: /nation list, courtesy of professorg
      - Now available are comparators to choose how to order the list of nations:
      - options are:
        - /n list by name: order alphabetically.
        - /n list by resident: order by nation with the most residents across all towns.
        - /n list by balance: order by nation with the highest nation bank balance.
        - /n list by towns: order by the nation with the most towns.
    - Changed Command: /town list, courtesy of professorg
      - Now available are comparators to choose how to order the list of towns:
      - options are:
        - /t list by name: order alphabetically.
        - /t list by resident: order by town with the most residents.
        - /t list by balance: order by town with the highest town bank balance.
    - New Config Option: economy.new_expand.price_claim_townblock_refund
      - default: 0.0
      - The amount refunded to a town when they unclaim a townblock.
      - Warning: do not set this higher than the cose to claim a townblock.
      - It is advised that you do not set this to the same price as claiming either, otherwise towns will get around using outposts to claim far away.
    - Fix messages showing when unclaiming an area where nothing can be unclaimed. 
    - Change upkeep messages for towns and nations to display fallen towns/nations in a much more condensed way.
    - Change town tax, plot tax, nation tax messages to display in a much more condensed way.
```

**Comment by LlmDl** [comment]
I've had confirmation from someone else taht this build solved it. Please also confirm so that I can close this ticket.

**Comment by kekke3r** [comment]
I can confirm it, towny works perfectly and loads without errors, thanks for the amazing work!
