### ISSUE TITLE
Locked in safe mode - "Error failed to load"

### ISSUE THREAD

**Issue by Artuto** [TownyAdvanced/Towny#3341]
### What steps will reproduce the problem?
1. Start the server

### What is the expected output?
1. Not enter in safemode

### What is your Towny version?
0.94.0.3

### What is your spigot/craftbukkit version?
Paper 1.14.4 build 152

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://gist.github.com/Artuto/ec1fa344890d24ae552ace0aad8cd62f#file-latest-log
2. Your Towny config.yml (if using MySQL please remove password,) : https://gist.github.com/Artuto/ec1fa344890d24ae552ace0aad8cd62f#file-config-yml
3. Your log's error : https://gist.github.com/Artuto/ec1fa344890d24ae552ace0aad8cd62f#file-error-log

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/issues/3339
