### ISSUE TITLE
Exception thread - Town Claims resetting 

### ISSUE THREAD

**Issue by ArathiaMC** [TownyAdvanced/Towny#3342]
Town sizes are resetting to 0 after every server reboot/crash. This happens all the time and for every town on the server. 

1. Create a town and add claims
2. Wait for server reboot/crash
3. Claims reset to 0.

Towny version: 0.93.0.0
Error: https://pastebin.com/SmZNQ7Up
PaerSpigot MC 1.14.4 buld 148

Towny config: https://pastebin.com/DS9695P2
Townyperms config: https://pastebin.com/cvMBUFPy
Error: https://pastebin.com/SmZNQ7Up

**Comment by LlmDl** [comment]
Get Towny 0.94.0.0 http://towny.palmergames.com/release-version-towny-advanced-0-94-0-0-1-13/
