### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by creatorfromhell** [TownyAdvanced/Towny#3343]
Im a simple man. I saw this github from afar, i pondered deep in my thoughts, and i said to myself "Ive got an idea." And with thst thought peocess taking over i sat outside the last street light on the left hand side of a far away town and i just kept thinking about this one idea. This is great i repeated quietly to myself over and over. Then on the 30th day of July in the year of 2019 i said today is the day. And with that i bring you the greatest feature request of them all. This is even better than the study of wumbology. It is: a suggestions channel in the towny discord server. I know this is a lot to take in at first thought, but if you do as i do and follow the worda of the last street light on the left hand side of a far away town, you too can see the great possibilities that this brings to the modern world of technology.

**Comment by dextonanderson** [comment]
Yes

**Comment by creatorfromhell** [comment]
> Yes

Alright you talked me into it. Since this ticket has gotten billions and billions of views, I'll describe the last street light on the left hand side of a far away town. It all starts with the paint colour. We're talking midnight black, it just absorbs all the surrounding colours into it, making everything around it seemingly lifeless. This is further projected by the pinstripe spirals of minion yellow paint running from the bottom to the top. This is done in perfection with the absolute best-in-class 4 inch spacing between each spiral. As you move to the opening there are four crystal clear synthetic glass panels. As you look you notice that the panel in the back has 2 cracks forming an almost spade-like shade in the bottom left hand corner. Meanwhile, you can see the generations of moths that have died trying to harness the power of the 20 watt LED bulb that illuminates the underlying pedestrians as they walk through the streets during the howling hours of the night. This is further made more eery by the distant outline of the burnt out light on the right hand side of town. However, if you look very closely you'll notice one outlying detail that this street light has, which no other one does. That is the engraved outline of the letter "S". What does this "S" stand for you may ask? It stands for Suggestions, as in a suggestions channel in the Towny discord please.

**Comment by Onyxtite** [comment]
I know you mean well, but githubs issue tracker is good enough for this, and to be honest the developer seems to barely have time to update the plugin, if you want a particular feature, i suggest you make an addon or fork with it :/

**Comment by LlmDl** [comment]
I thought @creatorfromhell had the dumbest comment for a bit there but you really turned it around on me
![2rszck](https://user-images.githubusercontent.com/879756/62158726-c1295380-b2d5-11e9-8066-0dd6931a9e57.png)

**Comment by LlmDl** [comment]
This ticket is now for shitposting.
