### ISSUE TITLE
Crossbow damage by fireworks in Towny Claims

### ISSUE THREAD

**Issue by silverwolfg11** [TownyAdvanced/Towny#3346]
Duplicate of closed issue: #3332 
Not fixed.

Towny Version: 0.94.0.5

Replication:
1. Load firework in crossbow
2. Shoot at player within town claim

Throws an NPE in console and the player still takes damage.

I believe the error is caused because townyWorld is null when it's passed through the locationCanExplode method in the TownyEntityListener Class.
Simple fix is to define townyWorld either within the if-statement that checks for a firework or at the base initialization (because all of the initializations of the variable are the same).

**Comment by LlmDl** [comment]
Fill in the form and resubmit.
