### ISSUE TITLE
[Suggestion] Use XYZ coords in "/t" infopane instead of chunk coords.

### ISSUE THREAD

**Issue by johnyuki** [TownyAdvanced/Towny#3347]
You can view a town's info by typing "/t ". One of the bits of information displayed is it's coords. However, it only displays chunk coords, and not it's XYZ coords. This makes looking for locations on dynmap really difficult as you have to manually multiply the chunk coords by 16 to get the XYZ coords.

The infopane should display XYZ coords by default instead of/as well as the chunk coords.

**Comment by LlmDl** [comment]
Those are the Towny coords, which are all used in the /towny map. What can be done is a config option that would let you choose which coords to be shown.

**Comment by LlmDl** [comment]
Closed in the above commit, will be a part of 0.95.0.4 when it is released.
