### ISSUE TITLE
Towny Self Grief

### ISSUE THREAD

**Issue by fennee** [TownyAdvanced/Towny#3349]
Hi there.

So I've got an issue which I've had with every version if Towny I've used that I've been aware of. Whenever somebody deletes their town using /t delete, the towny plugin actually griefs their builds that they've put blood sweat and tears into and CoreProtect can't roll it back. I've had this issue so many times and so many players have complained. I've set the daily upkeep to £0 to prevent towny's from auto deleting, but people still might want to delete their towny and start fresh in order to reset their spawn or some info. But the town still gets griefed by the plugin. I've turned revert_on_unclaim off and the plugin is still doing this.

I'm aware that this might have been a ticket that's been opened quite a few time, since this is quite a serious matter, and I apologies if I haven't spotted it. If you ask me, this setting shouldn't be enabled by default. No plugin should destroy your server by default. Other than that, great plugin. Any help is much appreciated.

Thanks in advance

Towny version:
0.94.0.0

Spigot version 1.14.4

--fennee

**Comment by LlmDl** [comment]
If you're turning the feature off in the config, that area of the config is only for setting default settings for new worlds. You have to use /tw toggle revertunclaim in the worlds you want it off in, if the worlds were around before Towny was installed. This is explained in the install guide, and in the config itself.

**Comment by fennee** [comment]
Excellent thank you. So far this command seems to have done the trick. I've been searching for eveeeer. I'm failing to see where it says in the config or anywhere else online for that matter. But so far, I've tested it by creating some blocks, adding my test towny there and then deleting, and the blocks still remain.

Thanks again.

--fennee
