### ISSUE TITLE
Suggestion: Add support DiscordSRV for Global-Townychat

### ISSUE THREAD

**Issue by Sprungente** [TownyAdvanced/Towny#3350]
### What steps will reproduce the problem?
1. Install DiscordSRV
2. Write in Global 
3.

### What is the expected output?
1. Nothing. Messages from Discord arrive the server but it wont be output in the chat. Without Townychat it works
2. No Messages from the server will output on Discord.
3.

### What is your Towny version?
0.94.0.4 // 0.56 Townychat

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-e5b1b5d-1ec1b05 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/cD4rMaWb
Specially focussing on: 
[02:37:23] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Enabling TownyChat hook
[02:37:23] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No TownyChat channels were automatically hooked. This might cause problems...

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/YV7QNR4s

Fixing support for DiscordSRV. For example for the globalchat.

https://www.spigotmc.org/resources/discordsrv.18494/
https://github.com/DiscordSRV/DiscordSRV

**Comment by LlmDl** [comment]
If it dont work, you should have filled it out as a bug ticket. @KarlOfDuty already said it works.

**Comment by Sprungente** [comment]
Fixed. You never see it

**Comment by LlmDl** [comment]
Show me the channels.yml too, if it requires hooked: true we need to see if you did that.

**Comment by LlmDl** [comment]
@KarlOfDuty can you compare this to what you have working?

**Comment by KarlOfDuty** [comment]
I would need the DiscordSRV configs in order to see if anything is wrong.

**Comment by LlmDl** [comment]
Sounds like he fixed it and I hadn't seen that. Probably just missed the hooked: true added to the channels.yml.

**Comment by Sprungente** [comment]
Hey

I just ignored something in the discordsrv config😆

I‘m sorry for wasting your time




Am 06.08.2019 um 16:09 schrieb LlmDl <notifications@github.com<mailto:notifications@github.com>>:


Sounds like he fixed it and I hadn't seen that. Probably just missed the hooked: true added to the channels.yml.
