### ISSUE TITLE
[Error] Could not pass event EntityExplodeEvent

### ISSUE THREAD

**Issue by xMatula** [TownyAdvanced/Towny#3352]
### What steps will reproduce the problem?
I don't know, probably when a ghast shoot a fireball or others mobs attacking.

### What is the expected output?
Idk

### What is your Towny version?
0.94.0.4

### What is your spigot/craftbukkit version?
1.13.2

### Please use Pastebin.com to link the following files:
1. https://pastebin.com/subTRzS2
2. https://pastebin.com/zKTTBmPP
3. https://pastebin.com/k28KMNA9
4. Same as first.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You should be on 1.14 if you want to use 0.94.0.4. Go back to 0.94.0.0 for now.
