### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to Towny

### ISSUE THREAD

**Issue by Estarqui** [TownyAdvanced/Towny#3355]
### What steps will reproduce the problem?
1. Updated Towny to the latest versión (0.94.0.4)

### What is your Towny version?
0.94.0.4

### What is your spigot/craftbukkit version?
PaperSpigot (MC: 1.14.4) [AE900115]

### Please use Pastebin.com to link the following files:

1. Your log's error :  https://pastebin.com/XgrdnyqX

**Comment by LlmDl** [comment]
Fixed already, part of 0.94.0.5
