### ISSUE TITLE
0.94.0.2+ Issue loading townblocks leads to safemode.

### ISSUE THREAD

**Issue by Lambsy** [TownyAdvanced/Towny#3358]
Loads in safe mode after updating from 0.93.1.0 Pre-Release 5 to 0.94.0.4. When reverting to 0.93.1.0 again, the plugin loads successfully.  

### What steps will reproduce the problem?
1. Stop server.
2. Update Towny from **0.93.1.0 Pre-Release 5** to **0.94.0.4**.
3. Start server.

### What is the expected output?
1. No safe mode

### What is your Towny version?
0.94.0.4

### What is your spigot/craftbukkit version?
Paper 639 (MC: 1.13.2)

### Please use Pastebin.com to link the following files:
1. Towny load log: https://pastebin.com/sNJhHU6A
2. Towny config.yml: https://pastebin.com/d05eeLiZ

Update: The plugin loads successfully with 0.94.0.0. The issue also causes a "too many files" error with plugins trying to load after that causes server to crash.

**Comment by Articdive** [comment]
@KarlOfDuty this one is yours for real though :), at least the outlaw stuff

**Comment by LlmDl** [comment]
@Lambsy pastebin.com this file: plugins/Towny/data/townblocks/world/427_498_16.data 

It is the one that is actually causing the safemode.

**Comment by Lambsy** [comment]
> @Lambsy pastebin.com this file: plugins/Towny/data/townblocks/world/427_498_16.data
> 
> It is the one that is actually causing the safemode.

https://pastebin.com/4rHCTkVn

**Comment by LlmDl** [comment]
Can you pastebin.com your towns.txt now for us please.

**Comment by Lambsy** [comment]
> Can you pastebin.com your towns.txt now for us please.

https://pastebin.com/JhpfZygz

**Comment by LlmDl** [comment]
Is there a towny\data\towns\Skioptis.txt file?

**Comment by Lambsy** [comment]
> Is there a towny\data\towns\Skioptis.txt file?

https://pastebin.com/C0G9PAMH

**Comment by LlmDl** [comment]
Is the townblock file that caused the safe mode in the townblocks.txt?

**Comment by Lambsy** [comment]
> Is the townblock file that caused the safe mode in the townblocks.txt?

Think so. https://pastebin.com/PK4uMPsV

**Comment by KarlOfDuty** [comment]
That moment when @Articdive keeps pinging me for my features working properly.

**Comment by Articdive** [comment]
> That moment when @Articdive keeps pinging me for my features working properly.

Hush I read it in email...

**Comment by LlmDl** [comment]
None of us can spot what is wrong with the townblock file @Lambsy if you can get me a backup .zip of your towny data folder i'd very much appreciate it, so I can use it for testing.

**Comment by LlmDl** [comment]
@Lambsy https://github.com/TownyAdvanced/Towny/releases/tag/0.94.0.5 has a potential fix for this issue. Please let us know if it works.

**Comment by Lambsy** [comment]
> @Lambsy https://github.com/TownyAdvanced/Towny/releases/tag/0.94.0.5 has a potential fix for this issue. Please let us know if it works.

Our server is on 1.13.2. We are unable to update to 1.14.2.

**Comment by LlmDl** [comment]
Thats correct you should probably still be on 0.94.0.0, everything beyond that is meant for 1.14

**Comment by LlmDl** [comment]
Haven't seen any more of this thing. Labeling this a one-off.
