### ISSUE TITLE
Suggestion:add an option to merge towns

### ISSUE THREAD

**Issue by DeadGlamour** [TownyAdvanced/Towny#3361]
In many places, towns will be very friendly and want to merge towns to make it easier for players from each town to work in the other, so I thought merging towns will be a very useful thing to add, the only problem I can see in it is players making new towns to pass the plots limit, this can be overcomed by doing that the merging will cost some % of the merged towns price or make a constant price, depends on the server.

**Comment by LlmDl** [comment]
This idea is already on the tracker in this ticket ( https://github.com/TownyAdvanced/Towny/issues/3193 ) and it is very similar to the nation merging that was just added in 0.94.0.5.

The town merging is much, much more complex that the nation merging however with all the town's townblocks also needing to have their town's changed. Until this ticket ( https://github.com/TownyAdvanced/Towny/issues/3344 ) is closed and we have a more sane way to track townblocks it would be a major burden every time a significantly large town was merged into another. On top of that we have to go through residents who are jailed, outlaw lists and other things. This feature will likely happen some day but there was other things we have to get in order first.
