### ISSUE TITLE
jar file.

### ISSUE THREAD

**Issue by itzfunday** [TownyAdvanced/Towny#3372]
The jar file you currently sent me when i uploaded it and restarted the server I got this issue: 
https://pastebin.com/9fjZwkXa

**Comment by itzfunday** [comment]
I also get this https://pastebin.com/YhVMWGBr

**Comment by LlmDl** [comment]
And this is why you should be filling out the form. You're on which version of MC?

**Comment by itzfunday** [comment]
1.12.2

**Comment by LlmDl** [comment]
Use this: https://cdn.discordapp.com/attachments/388338495036456960/610134935675863040/Towny.jar
