### ISSUE TITLE
TownyUpdater 3.0 fails to load on 0.94.0.5+

### ISSUE THREAD

**Issue by cobrex1** [TownyAdvanced/Towny#3378]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Using paper 167
2. Using towny release 0.94.0.5
3.Using NameUpdater 3.0

### What is the expected output?
1. Server logs show that Nameupdater fails to load and is disabled - see the log report
2. https://pastebin.com/LXNMbyzU
3.

### What is your Towny version?
Do not say "latest". 0.94.0.5

### What is your spigot/craftbukkit version?
Do not say "latest". Paper 167

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/m9i0N1Xk

2. Your Towny config.yml (if using MySQL please remove password,) :
I have reverted to 0.94.04 so config file is not correct version now
3. Your townyperms.yml :
https://pastebin.com/1wFTBNBe
4. Your log's error : 
https://pastebin.com/LXNMbyzU
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
@Articdive can you do the needful please.

**Comment by Articdive** [comment]
Fixed in https://github.com/TownyAdvanced/TownyNameUpdater/pull/2

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/TownyNameUpdater/releases/tag/4.0
