### ISSUE TITLE
Plots resetting to snapshot when unclaimed despite config

### ISSUE THREAD

**Issue by BisGames** [TownyAdvanced/Towny#3382]
### What steps will reproduce the problem?
1.Made a town and money ran out and the plots were unclaimed
2.The plots reverted to the snapshot before being claimed
3.

### What is the expected output?
1.I expected the town to be deleted and the plots unclaimed, but I used the config to make it so the town did not revert back to the snapshot before it was claimed.
2.
3.

### What is your Towny version?
[Towny] Loading Towny v0.94.0.0

### What is your spigot/craftbukkit version?
spigot-1.14.4.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/qgg4rBiG
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/X4h0Xccb
3. Your townyperms.yml :
https://pastebin.com/w0tEG8pz
4. Your log's error : 
N/A

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Config section is called Default New World settings.

Set in worldname.txt or in game using /tw toggle revertunclaim

**Comment by BisGames** [comment]
That will make it so plots dont revert when unclaimed?

**Comment by LlmDl** [comment]
That is why I said to do it, I assumed you wanted them to not revert based on your ticket, and then gave you the advice I had to give.

**Comment by BisGames** [comment]
Sorry oh lord. I was just making sure everything was on the same page.

**Comment by BisGames** [comment]
thanks for the help
