### ISSUE TITLE
Suggestion: Separate Switches and Inventory permissions

### ISSUE THREAD

**Issue by sheepishlyalive** [TownyAdvanced/Towny#3389]
Something I find odd is that you can't allow outsiders to use redstone such as buttons, levers, and pressure plates without also allowing them to access doors, chests, furnaces, dispensers, etc. 
Sometimes I want redstone contraptions to be available to the public. I think it gives opportunities to make things like doorbells, light switches, and one-way doors (putting pressure plates on one side of a door.)
My suggestion would be to split them into "switch" and "inv/inventory."

**Comment by LlmDl** [comment]
This is easy to do, just remove the wooden buttons/wooden pressure plates from the switch ID list in the config. They won't be protected by Towny anymore.

Switch is really 'block/thing I interact with' and item_use is 'item I am trying to use on something'.

Splitting up inventory blocks from the other types of blocks people interact with won't be done.
