### ISSUE TITLE
Towny crashes with cyrillic name of the nation.

### ISSUE THREAD

**Issue by etysoftware** [TownyAdvanced/Towny#3390]
### What steps will reproduce the problem?
1. Create new nation with cyrillic name(example, what I use: привет_сасе1)
2. Try to /stop and start server two or three times

### What is the expected output?
- Towny crashes with no files in data/nations folder
- The player stands still and can not move, Towny commands do not work.
- Console says https://i.imgur.com/WR6UpCb.png

### What is your Towny version?
0.94.0.6

### Spigot version
CraftBukkit version git-Spigot-5e4e7f3-2349feb (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

### Following files:

**Logs**
https://pastebin.com/GEMHS3Qb

**Config.yml**
https://pastebin.com/EnuuuYPB

**townyperms.yml**
https://pastebin.com/M0VzPfCr

- Console says https://i.imgur.com/WR6UpCb.png

### Update
I realized that on my home server (localhost) Cyrillic names are stored normally. For example, the city "махачкала" is called махачкала.txt while on the server the file is called ?????????.txt. Nations too.(but towns works perfectly). Try to delete Towny folder and edit regex: no result.

### Maybe problem in Towny Name Updater
I have error while nation file deleting time 
https://pastebin.com/J5Erqrwz

### I catch the problem
====================      Towny      ========================
[10:59:57] [Server thread/INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[10:59:57] [Server thread/INFO]: [Towny] Deleted 1 old files.
**[10:59:57] [Server thread/INFO]: [Towny] Deleted 1 old files.**
**After that my nation deletes from data/nations**

[10:59:57] [Server thread/INFO]: [Towny] Using: Vault v1.7.2-b107, Essentials Economy via Vault
[10:59:57] [Server thread/INFO]: [Towny] Time until a New Day: 1 hours, 3 seconds

I think problem is towny thinks that cyrillic nation file in data/nation is old and it deletes my file(+ i think i will get a new problem with ??? in cyrillic file name, because name маха = 4 symbols and паха = 4 symbols, but ??? = ???)

**Comment by Articdive** [comment]
The Console is unable to show cyrllic characters, why? Ask Microsoft.

Anyways this should actually only (hopefully) be an issue with you using the wrong version of TownyNameUpdater and Dynmap.

**Comment by Articdive** [comment]
The Console is unable to show cyrillic names. blame Microsoft for that one.

As for TownyNameUpdater please use version 4.0 when you test with development builds you should also use the development builds of the TownyNameUpdater. Dynmap-Towny will have to do their own update for now. Would you be able to give me the plugins/towny/logs/towny.log

**Comment by etysoftware** [comment]
@Articdive my problem is towny crashes, not cyrillic characters in Microsoft console. Towny deletes my cyrillic nation file in data/nations when it start second time After nation created with message about old files. That my problem, not Microsoft console

**Comment by LlmDl** [comment]
I wanted you to give me the exact name of the Nation you're using in your tests.

**Comment by etysoftware** [comment]
I give you it in the post. 

> I wanted you to give me the exact name of the Nation you're using in your tests.

**Comment by LlmDl** [comment]
I see it now, thanks.

**Comment by etysoftware** [comment]
> I see it now, thanks.

Ok. Hope it will work.

**Comment by LlmDl** [comment]
I've started with a fresh copy of Towny, used your config.yml.

Created a town named махачкала which formed a nation named привет_сасе1.

I added money to the town bank in order to make the nation, then I added 100 dollars into the nation bank after it was formed.

I have /stop'd and started the server 5 times now and nothing is corrupting.

As I told you in the IRC, there's no reason that Towny wouldn't like a Cyrillic nation name but be fine with a Cyrillic town name. The nation is being deleted for other reasons, possibly money related?

**Comment by etysoftware** [comment]
> I've started with a fresh copy of Towny, used your config.yml.
> 
> Created a town named махачкала which formed a nation named привет_сасе1.
> 
> I added money to the town bank in order to make the nation, then I added 100 dollars into the nation bank after it was formed.
> 
> I have /stop'd and started the server 5 times now and nothing is corrupting.
> 
> As I told you in the IRC, there's no reason that Towny wouldn't like a Cyrillic nation name but be fine with a Cyrillic town name. The nation is being deleted for other reasons, possibly money related?

No. I think it can be deleted by name ???. On start file delete because it is "old". And here is my problem.

**Comment by LlmDl** [comment]
Old files that are deleted at startup are backup .zip files. It doesn't have anything to do with towns/nations.

The ????'s you see in the console are only there because MS Windows' console doesn't use the right charset to display Cyrillic letters. Towny still knows the name correctly.

**Comment by etysoftware** [comment]
> Old files that are deleted at startup are backup .zip files. It doesn't have anything to do with towns/nations.
> 
> The ????'s you see in the console are only there because MS Windows' console doesn't use the right charset to display Cyrillic letters. Towny still knows the name correctly.

No, I see ??? in filezilla and if i try to download it.

**Comment by LlmDl** [comment]
Does filezilla support UTF-8?

**Comment by etysoftware** [comment]
> Does filezilla support UTF-8?

Idk, but if I create cyrillic file it normally stays there.

**Comment by etysoftware** [comment]
> Does filezilla support UTF-8?

And if i download it i see same result(but ??? replace ____)

**Comment by LlmDl** [comment]
Pastebin.com the full startup from your hosted server that you access via filezilla.

**Comment by etysoftware** [comment]
> Does filezilla support UTF-8?

What? Where startup file can be?

**Comment by LlmDl** [comment]
the latest.log

**Comment by etysoftware** [comment]
I give it in the post

**Comment by LlmDl** [comment]
Im asking to see a new one that is specifically from your hosted server. The one in the  OP could be from your server or local files.

**Comment by etysoftware** [comment]
> Im asking to see a new one that is specifically from your hosted server. The one in the OP could be from your server or local files.

But that log from my hosted server

**Comment by LlmDl** [comment]
Show me a new latest.log or Im locking this,

**Comment by etysoftware** [comment]
https://pastebin.com/M2AU0Ba2

**Comment by LlmDl** [comment]
Nothing looks wrong regarding Towny. When you figure out how to reproduce the problem file a new ticket.
