### ISSUE TITLE
Plot claiming not working.

### ISSUE THREAD

**Issue by MochaGnocca** [TownyAdvanced/Towny#3393]
### What steps will reproduce the problem?
1. Set a plot for sale.
2. Attempt to claim the plot with /plot claim.
3. Walk out of the plot and walk back in.
4. Plot is not claimed and is still for sale.

### What is the expected output?
1. Plot is claimed after using the /plot claim.

### What is your Towny version?
0.94.0.0

### What is your spigot/craftbukkit version?
PaperMC Version 171

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/bwcJiq3A
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/wjHARrDE
3. Your townyperms.yml : https://pastebin.com/wUYcZi4X
4. Your log's error : https://pastebin.com/NVfaKgUB

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your startup is just a bunch of stuff from the middle of a running server with not startup to be found.
Please get a full startup showing all plugins loading. Then test your /plot claim  and if there's an error link a pastebin for it.

**Comment by MochaGnocca** [comment]
I can assure you this is the entirety of the log in my latest.log file. If anything is missing, I’m very sorry about that.

**Comment by MochaGnocca** [comment]
I am currently at work at the moment, as well. Once I get home I will restart the server and perform the bug. That won’t be until sometime after 8 est.

**Comment by MochaGnocca** [comment]
I fixed the log and the specific error in the log.

**Comment by LlmDl** [comment]
Your essentials economy/essentialsX isn't the 1.14 version that has async fixes in it.
