### ISSUE TITLE
Suggestion: Overclaimed Upkeep Penalty

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3394]
An option in the config to set some kind of cost, tax or whatnot for towns that are overclaimed. For example, a town with 50 claimed, but only allowed to claim 20, would have a bonus upkeep cost of x.

**Comment by LlmDl** [comment]
Done as of https://github.com/TownyAdvanced/Towny/commit/9064916e862583103ba5a1edcffe44493acc2449 part of 0.94.0.6
