### ISSUE TITLE
cyrillic doesn't work in latest (0.94.0.5) release

### ISSUE THREAD

**Issue by ntgh-dimako** [TownyAdvanced/Towny#3395]
### What steps will reproduce the problem?
1. install Towny
2. modify regex to add Cyrillic
3. make new town named (for example) Москва
4. restart

### What is the expected output?
1. no crashes or safe mode

### What is your Towny version?
0.94.0.5

### What is your spigot/craftbukkit version?
paper-173 (1.14.4)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/uGSPsLjr
2. Your Towny config.yml  : https://pastebin.com/HG8ZapjV
3. Your townyperms.yml : default
4. Your log's error :  
![image](https://user-images.githubusercontent.com/18640057/63332941-31f5e580-c341-11e9-895d-d8873821c7e9.png)

**Comment by LlmDl** [comment]
It wasn't fixed until .6 which you can have a pre-release copy here:

https://cdn.discordapp.com/attachments/388338495036456960/613343900240707596/Towny-0.94.0.6.jar

Read the changelog for 0.94.0.6
