### ISSUE TITLE
Chunks still resetting after unclaiming

### ISSUE THREAD

**Issue by VyrussGG** [TownyAdvanced/Towny#3400]
So here is the issue: even though in my config it is clearly stated that chunks should NOT revert on unclaim, it is still resetting them.

### What steps will reproduce the problem?
1. Unclaiming plots
2. Deleting your town
3.

### What is the expected output?
1. Chunks should not reset because in the config it is set to 'false'
2.
3.

### What is your Towny version?
0.94.0.0

### What is your spigot/craftbukkit version?
Spigot for 1.14.4

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/5ybHbF8h
2. Your Towny config.yml : https://pastebin.com/3R3LCiZM
3. Your townyperms.yml : https://pastebin.com/hHHAaVVT
4. Your log's error : https://pastebin.com/k2A9MQUJ This is where in the config it is set to not revert, yet in-game chunks are still being reverted.

**Comment by LlmDl** [comment]
The config section you turned it off in is called Default New World Settings. It is only for settings applied to newly made worlds.

The install guide explains you need to turn that feature off in the worlds using /tw toggle revertunclaim.
