### ISSUE TITLE
Firework Crossbow throws EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by northerncarrots** [TownyAdvanced/Towny#3402]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Shoot firework rocket at mobs (using crossbow)
2.
3.

### What is the expected output?
1. No error

### What is your Towny version?
0.94.0.3

### What is your spigot/craftbukkit version?
git-Paper-174 (MC: 1.14.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Unable to retrieve at this time.
2. Your Towny config.yml (if using MySQL please remove password,) : [Config](https://hastebin.com/wopeqarama.coffeescript)
3. Your townyperms.yml : Default
4. Your log's error : [Error](https://hastebin.com/nacijuride.cs)

**Comment by LlmDl** [comment]
Try 0.94.0.5 I am pretty sure this was fixed in that or .6
