### ISSUE TITLE
Nationzones don't read the config settings

### ISSUE THREAD

**Issue by Eryk1983S** [TownyAdvanced/Towny#3403]
Hi again,
in another thread (https://github.com/TownyAdvanced/Towny/issues/3305) I reported the bug with the nationzones and wrote at the end, that everything works fine. However, I made my trials only in the next chunk to the border of a town.

I didn't notice then, that the range of the nationzone isn't that, what is configured.

### What steps will reproduce the problem?
1. Configure the different nationzones for the different nation levels, e.g. in my config (https://pastebin.com/ejaLnzFq)
2. Create a nation on the lowest level. In my example - one town, 6 residents. The range of the nationzone is configured as 1.
3. Use an account of a player, who doesn't belong to the nation and grief next to the town border. You will be able to do that, though it should be forbidden.
4. Then let an another town join your nation, so that it gets the next nation level. In my example: 10 residents, range of NZ: 5.
5. Grief with a foreigner in the neighbour chunks - you can't do that, so it seems to work properly.
6. But grief a little bit further (third chunk from the town border) and you are still able to destroy/build blocks, thought the nationzone should protect 5 chunks.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Spigot 1.12.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:
Towny doesn't report an error, neighter on startup nor during the griefing.
Config.yml - link pasted above
Townyperms.yml - it seems to be irrelevant; if you mean as an expert, I'm wrong, I'll gladly paste it.

**Comment by LlmDl** [comment]
Your version of Towny is old and doesn't have the fix in it that probably makes them work. Turn off nation zones until you can update.

**Comment by Eryk1983S** [comment]
Please, tell me only, if 0.94. will be working with Spigot 1.12.2., if I change the block/item-names in the config, and I won't have any questions to this thread anymore :)

**Comment by LlmDl** [comment]
You might be able to run on 0.94.0.0, make sure you make a backup of things. Lots changed. If that doesn't work just don't enable nation zones.
