### ISSUE TITLE
Generating exception for health not being between 0 and 16

### ISSUE THREAD

**Issue by Stuffing98** [TownyAdvanced/Towny#3404]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. If anyone is inside the spawn zone, which is claimed and worldguarded (We use WorldGuardExtraFlags too, only have a speedbuff at spawn.)
2.
3.

### What is the expected output?
1. No error to be placed into console
2. No drop in server ticks per second. 
3.

### What is your Towny version?
v0.94.0.5

### What is your spigot/craftbukkit version?
spigot-1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/PsFjVcu3 - Full Server Log
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/uPXatben
3. Your townyperms.yml :
https://pastebin.com/szRiHGsu
4. Your log's error : 
[13:16:33] [Server thread/WARN]: [Towny] Task #63 for Towny v0.94.0.5 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 16.0(17.0)
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:107) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at com.palmergames.bukkit.towny.tasks.HealthRegenTimerTask.incHealth(HealthRegenTimerTask.java:69) ~[?:?]
	at com.palmergames.bukkit.towny.tasks.HealthRegenTimerTask.run(HealthRegenTimerTask.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Stuffing98** [comment]
Update: Looks like anywhere that /ta set plot was used is throwing this exception.

**Comment by LlmDl** [comment]
You're setting the plot to a town that already exists right?

Do you have a plugin that alters a player's max health in any way?

**Comment by LlmDl** [comment]
It would be helpful to know if you've been using /ta set plot on wilderness or where a town already existed.

**Comment by Stuffing98** [comment]
> 
> 
> You're setting the plot to a town that already exists right?
> 
> Do you have a plugin that alters a player's max health in any way?

Yeah, all of the land is already claimed and assigned to existing towns. When a player steps into the chunks that are already claimed / assigned it generates this error. It does not appear to do that for plots that were claimed using /town claim. 

In the scenarios where this is occurring it was on Wilderness specifically in the three instances I noticed. (Two being the default 'admin town' for protecting, then a town that was for a player had some manually claimed by an admin and it was doing it there as well.)

The only plugin I am aware of on the server that could modify max health would probably be this one: https://www.spigotmc.org/resources/worldguard-extra-flags.4823/

I'm not 100% confident on that though, I can send you a list of plugins if that'd be helpful too.

**Comment by LlmDl** [comment]
Is that a custom flag you made or something built in? I searched the repo and cannot find any use of the GENERIC_MAX_HEALTH attribute in the source code.

**Comment by Stuffing98** [comment]
> 
> 
> Is that a custom flag you made or something built in? I searched the repo and cannot find any use of the GENERIC_MAX_HEALTH attribute in the source code.

Probably built-in to something on the server. If it's not in the source code of Towny I can try to start up another server for diagnosing.

I tested it on the main server again and immediately after claim it started to generate an error: https://pastebin.com/5iQDWEsP

**Comment by LlmDl** [comment]
Can you give exact steps for reproduction? Something like:

- in the wild/in a town
- use "/ta set plot exacttownname
- stand around/leave the plot/do a jig

**Comment by Stuffing98** [comment]
> 
> 
> Can you give exact steps for reproduction? Something like:
> 
>     * in the wild/in a town
> 
>     * use "/ta set plot exacttownname
> 
>     * stand around/leave the plot/do a jig

1. Step outside existing town, now standing on wilderness plot.
2. Use /ta set plot The_Trade_District
3. Stand still and check console. As soon as 'Plot snapshots completed' error appears to begin generating for however long player is standing in the chunk.

I believe the issue might be with the underlines in the town name. I just tested with a different existing town and it did not generate an error:

1. Step outside existing town, now standing on wilderness plot.
2. Use /ta set plot SpaceForce
3. Stand still and check console. Plot snapshots completed. No error.

**Comment by LlmDl** [comment]
Either town name you're using is already an existing town right?

**Comment by Stuffing98** [comment]
> 
> 
> Either town name you're using is already an existing town right?

Yeah both are existing towns. I just tried with a third existing town that also had an underscore and it did not error so now I'm confused as to what's going on.

**Comment by Stuffing98** [comment]
@LlmDl  

As quickly as this issue came up, it's fixed now it seems.

Another player came to spawn and it didn't error. That made me realize maybe it is something specific to my player. I went outside, got rid of all items and turned on survival mode and went to spawn with him. No error. Started trying to diagnose by turning on god, turning on creative, having all items and error is not coming back yet.

**Comment by LlmDl** [comment]
It's definitely something to do with health. I've given you a test build that has a slight change to what we use for a max health. See if you can make it happen the old way using that build.

**Comment by Stuffing98** [comment]
Reproduce steps:
1. Place 'Golden Energy Sword' - negative 4 max health sword - in hand or in shield slot.
2. Go through portal at spawn to different world (minigames world).
3. Return to spawn using /spawn or step back through portal. 

Will test out this new build asap @LlmDl

**Comment by Stuffing98** [comment]
Looks resolved with version v0.94.0.6, will keep running and see if anything else comes up. 

Thanks for the quick fix!

**Comment by LlmDl** [comment]
Fixed as of 0.94.0.6 and https://github.com/TownyAdvanced/Towny/commit/8a241b0424d723dff4e8714aa432cd481fa422e5
