### ISSUE TITLE
Can't read price_town_overclaimed_upkeep_penalty from config.yml

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3405]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Make a fresh settings folder for towny
2. Do /ta newday
3. Console will tell you:
[02:11:07 INFO]: [Towny] Error could not read economy.daily_taxes.price_town_overclaimed_upkeep_penalty from config.yml
[02:11:07 INFO]: [Towny] Error could not read economy.daily_taxes.price_town_overclaimed_upkeep_penalty from config.yml
[02:11:07 INFO]: [Towny] Error could not read economy.daily_taxes.price_town_overclaimed_upkeep_penalty from config.yml

### What is the expected output?
1. Towny will be able to read the new config options
2.
3.

### What is your Towny version?
Do not say "latest".

0.94.0.6

### What is your spigot/craftbukkit version?
Do not say "latest".

Paper 176 (1.14.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/WySTzHY3

2. Your Towny config.yml (if using MySQL please remove password,) :
Freshly generated default config.yml file.
https://pastebin.com/6Lcv8D8d

3. Your townyperms.yml :
https://pastebin.com/v6HbGKup
Freshly generated towny perms.yml file (I deleted the whole settings folder and let it regenerate)

4. Your log's error : 
[02:11:07 INFO]: [Towny] Error could not read economy.daily_taxes.price_town_overclaimed_upkeep_penalty from config.yml
[02:11:07 INFO]: [Towny] Error could not read economy.daily_taxes.price_town_overclaimed_upkeep_penalty from config.yml
[02:11:07 INFO]: [Towny] Error could not read economy.daily_taxes.price_town_overclaimed_upkeep_penalty from config.yml

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Momshroom** [comment]
I think the issue is that the default config is missing a value for how much the penalty is near here:
    # Uses total number of plots that the town is overclaimed by, to determine the price_town_overclaimed_upkeep_penalty cost.
    # If set to true the penalty is calculated (# of plots overclaimed X price_town_overclaimed_upkeep_penalty).
    price_town_overclaimed_upkeep_penalty: 'true'

in the daily taxes section.

**Comment by LlmDl** [comment]
Just updated this morning's release to include this fix:
https://github.com/TownyAdvanced/Towny/releases/tag/0.94.0.7

We had two config option being set to the same config line.
