### ISSUE TITLE
Log spamming on New Day

### ISSUE THREAD

**Issue by xMatula** [TownyAdvanced/Towny#3407]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. New day taxes
2.
3.

### What is the expected output?
1. No spam
2.
3.

### What is your Towny version?
0.94.0.7

### What is your spigot/craftbukkit version?
Paper version git-Paper-175 (MC: 1.14.4)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : no issues here, look 4.
2. Your Towny config.yml : https://pastebin.com/uEAgBHrR
3. Your townyperms.yml : https://pastebin.com/LLKCFDQu
4. Your log's error : https://pastebin.com/Vq3e9J4U

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/issues/3398#issuecomment-527504175
