### ISSUE TITLE
TownyBans

### ISSUE THREAD

**Issue by ThyV0001** [TownyAdvanced/Towny#3408]
Suggestion:

I suggest the possibility to make towny bans - Accessable by Mayors by default, and a permission node allowing ranks like "Sheriff" get access aswell
/townyban ban {name}
/townyban unban {name} 
/townyban list (list of the towns you're banned from) 
A reason isn't necessary.
Basically it makes it so you can't go in to that town, not by walking or doing /home, /town spawn or even tp to someone inside. It gives you an error "you're not allowed in to this area" kinda like how some world borders work.

**Comment by LlmDl** [comment]
How is this different than the outlaw feature? 

We won't be doing any sort of movement cancelling to keep players from entering a town's borders. Too costly.
