### ISSUE TITLE
Town/Nation Board won't take more than 1 word

### ISSUE THREAD

**Issue by BurntValentine** [TownyAdvanced/Towny#3413]
### What steps will reproduce the problem?
1. Install PaperSpigot 1.13.2 and Towny 0.94.0.0
2. Create a Town and Nation
3. `/t set board Test 1 2 3` and `/n set board Test 1 2 3` do not work, invalid string, however `/t set board Test` works and `/t set board Test_1_2_3` works but the underscores stay in the message
4. Characters also do not work, for example you can't do `/t set board Don't` 

### What is the expected output?
Everything types after board in the `/t set board <message>` and `/n set board <message>` commands should be set as the board message, regardless of spaces or characters

### What is your Towny version?
0.94.0.0

### What is your spigot/craftbukkit version?
This server is running Paper version git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
(Not the latest Paper 1.13.2 as it breaks Shulkers and is unusable currently for my server)

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/0us9Smw0
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Fm4iFnjm
3. Your townyperms.yml : https://pastebin.com/TT9mZ7sb

**Comment by LlmDl** [comment]
Pretty sure we borked the 
```string_check_regex: ^[a-zA-Z0-9\\s._\\[\\]\\#\\?\\!\\@\\$\\%\\^\\&\\*\\-\\,\\*\\(\\)\\{\\}]*$```
a little while back. if you add a space to that line it should be fine after you do /ta reload.

**Comment by BurntValentine** [comment]
Added the space (`string_check_regex: ^[a-zA-Z0-9 \\s._\\[\\]\\#\\?\\!\\@\\$\\%\\^\\&\\*\\-\\,\\*\\(\\)\\{\\}]*$`) and ran `/ta reload` but it still doesn't let me use spaces

**Comment by LlmDl** [comment]
do you get told 'Invalid string, Nation Board not set.' ?

**Comment by BurntValentine** [comment]
That's correct - same for town board, using `/t set board Testing 1 2 3` and `/n set board Testing 1 2 3`

**Comment by BurntValentine** [comment]
Same for `/t set board Can't` and `/n set board Can't` , doesn't allow for the apostrophe

**Comment by LlmDl** [comment]
Want to try using this one?

```^[a-zA-Z0-9\\s._\\[\\]\\#\\?\\!\\@\\$\\%\\^\\&\\*\\-\\,\\*\\(\\)\\{\\}\\']+( [a-zA-Z0-9\\s._\\[\\]\\#\\?\\!\\@\\$\\%\\^\\&\\*\\-\\,\\*\\(\\)\\{\\}\\']+)*$```

**Comment by LlmDl** [comment]
I should note, you probably don't want to allow an apostrophe if you use mysql. Probably a good idea to not allow it anyways because flatfile will probably also fail to load the string.

**Comment by BurntValentine** [comment]
Odd thing to have an issue with - not had any issues with plugins saving and pulling text strings with apostrophes elsewhere that I've noticed (not using SQL)

Same issue using `^[a-zA-Z0-9\\s._\\[\\]\\#\\?\\!\\@\\$\\%\\^\\&\\*\\-\\,\\*\\(\\)\\{\\}\\']+( [a-zA-Z0-9\\s._\\[\\]\\#\\?\\!\\@\\$\\%\\^\\&\\*\\-\\,\\*\\(\\)\\{\\}\\']+)*$`

**Comment by LlmDl** [comment]
I just realized I'd been giving you the string out of the code that makes the config, so you have all sorts of doubled up \\'s.

I just tested this: ```string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$``` and it allowed me to use /t set board a bunch of words

**Comment by BurntValentine** [comment]
`/t set board Testing 1 2 3` still didn't work after setting it to that ^^ and using `/ta reload` - server has a restart in 6 hours though, will give it another look after a full restart

**Comment by BurntValentine** [comment]
Fixed after a restart, had to do a restart for something else so checked sooner xD Thank you!

**Comment by LlmDl** [comment]
Huh, maybe the regex is something we don't handle properly on a /ta reload.
