### ISSUE TITLE
Townynameupdater broken 0.94.0.0

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#3414]
**What steps will reproduce the problem?**
- Change name
- Login
**What is the expected output?**
- Name automatically changes from old name to new name for all aspects of towny.

**What is your Towny version?**
0.94.0.0
TownyNameUpdater v2.5

What is your spigot/craftbukkit version?
paper 186

TownyNameUpdater loads in without any errors.
https://pastebin.com/xjNx9dZi

This seems to be the only error that pops up, it happens when the person with the changed name logs in after the change.
https://pastebin.com/T3WAgFfN

It seems like townynameupdater is changing the name associated to the UUID to the new name, but that does not seem to do anything in-game...

I also cannot use /ta resident rename because apparently none of the names used were 'valid'.

Username: 
FunkyArts -> euthanasia_

**Comment by LlmDl** [comment]
... not a full startup. Why is it like pulling teeth with you.

**Comment by LlmDl** [comment]
Anyways, I've put a fix for this into 0.94.0.10, if you want to update to TNU 4.0 and Towny 0.94.0.10 and test it I'll get you a copy of the new Towny.

**Comment by JohnS19** [comment]
Sure, I'll test it. Is there anything I need to do before upgrading?

**Comment by LlmDl** [comment]
Just read teh changelog carefully so you make any required config changes.

https://git.io/fjbS3

**Comment by JohnS19** [comment]
Actually, on second thought, will there be an update for townynameupdater for 0.94.0.0?

**Comment by LlmDl** [comment]
The bug I fixed isn't in TNU, it was in Towny, so no. You're on 1.14 so you should be on the builds made for 1.14 (0.94.0.2+)
