### ISSUE TITLE
/plot claim not working

### ISSUE THREAD

**Issue by manssimba** [TownyAdvanced/Towny#3415]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. /t claim
2. anyone does /plot claim

### What is the expected output?
1.processing plot claim
2.walk out of plot and then walk in
3. it should be yours

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.94.0.0 

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/rDwhVQUD
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/v1ysFrc2
3. Your townyperms.yml : https://pastebin.com/1VZsVieD
4. Your log's error : https://pastebin.com/cJ792Zdc

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Did the mayor or assistant use /plot forsale {amount} before someone tried to claim it personally with /plot claim?

**Comment by manssimba** [comment]
yes

**Comment by LlmDl** [comment]
Update your essentials/essentials economy to a version made for 1.14

**Comment by manssimba** [comment]
do you support iconomy?

**Comment by LlmDl** [comment]
I'm part of the team that does this one: https://github.com/iconomy5legacy/iConomy/releases
