### ISSUE TITLE
Suggestion: To add `/town balance` command to display the balance of the town the player is in

### ISSUE THREAD

**Issue by axemwa** [TownyAdvanced/Towny#3416]
**### Feature Request/Suggestion: /town balance (+aliases)**

It would be awesome if there was a command specifically for the balance/money of the town the player is in, just like how there's one for the general `/bal` or `/balance` commands/aliases for economy plugins. 

If `/town balance|bal|bank|money` were added it would also make it easier to trigger the command using other plugins that can apply commands to NPCs and armorstands via right-clicking keybinding etc to get easy access to only the balance details, I know it's displayed as part of the `/town` command details but having a command separate for it would also be beneficial in many other ways I think.

If added I think the commands' permission should be `- towny.command.town.balance` and should be added to the **mayor** list in townyperms.yml by default so that only town mayors can check the balance by default, seems to make sense that way I think. Also to have the default message for it to be something like this `msg_town_balance: '&bTown Balance: &a$%s'` in english.yml (and all other language ymls etc)

**Comment by LlmDl** [comment]
I saw why you wanted this originally, which was to use it in holograms. Towny now has it's own placeholders for PAPI, one of which is the %townyadvanced_town_balance% which will show a formatted bank balance.

**Comment by axemwa** [comment]
Oh this is awesome and I see there's also a 1.13.2 release now as well, thanks for the heads up :)

**Comment by ProGamusian** [comment]
> I saw why you wanted this originally, which was to use it in holograms. Towny now has it's own placeholders for PAPI, one of which is the %townyadvanced_town_balance% which will show a formatted bank balance.

can this be added plz?

**Comment by LlmDl** [comment]
@ProGamusian that was already added last year.
