### ISSUE TITLE
{townytagoverride} not working

### ISSUE THREAD

**Issue by PilsetnieksLv** [TownyAdvanced/Towny#3418]
### What steps will reproduce the problem?
1. Using chat by player who has a town and doesn't have a nation.
### What is the expected output?
1. When someone who has a town but doesn't belong to nation use chat, {townytagoverride} appears in front of his nickname.

### What is your Towny version?
Do not say "latest".
0.55 
OR
0.94
Different towny configs say different version

### What is your spigot/craftbukkit version?
1.13.2 Paper

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/CTsn4nxy
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/s3XqNNwd
3. Your townyperms.yml :
https://pastebin.com/favdQJqu
4. Your log's error : 
https://pastebin.com/zrKG25A1
--
6. Your chatconfig.yml :
https://pastebin.com/6jPS1KWm
7. Your channels.yml :
https://pastebin.com/PpBRPCj4

Screenshots with current issue:
https://prnt.sc/pbf8fc

That's how we want to make repair chat (group)(nation)(town)(town prefix)(nickname):
https://prnt.sc/pbf92z

If would be thankful if someone would make a config so chat looks exactly the same as in the screenshot.

**Comment by LlmDl** [comment]
In the chat config you have the modifychat enable: 'false', set it to true and then use /townychat reload or just do it while teh server is stopped.

**Comment by PilsetnieksLv** [comment]
> In the chat config you have the modify chat enable: 'false', set it to true and then use /townychat reload or just do it while the server is stopped.

Hello, just did "true" on modify chat but there was no change after the restart.

**Comment by LlmDl** [comment]
I cant see anything wrong, my guess is you have some other chat plugin interfering. This sort of thing was unreproducable the last time it was filed. They had issues with {townytagoverride} not parsing.

You could go over their startup: https://pastebin.com/NJsz2a60 and see if you use any of the same plugins.

**Comment by PilsetnieksLv** [comment]
I'm curious why does townychat config says version "0.55" even towny version is 0.94.

**Comment by PilsetnieksLv** [comment]
I can send you list with plugins if you can check it.

**Comment by LlmDl** [comment]
Because TownyChat is on version 0.55 and Towny is on 0.94.0.0 (actually 0.94.0.12 if you follow the dev builds.)

I don't need a list, there's one in your server startup. I provided you a list so you can do the figuring out.

**Comment by PilsetnieksLv** [comment]
I checked the list you provided, we don't have any of those chat plugins.

**Comment by LlmDl** [comment]
If you have a test server that you can also make the issue happen on, you can start removing plugins until the issue goes away.

**Comment by PilsetnieksLv** [comment]
Doing it right now, thanks! Will keep you updated.

**Comment by PilsetnieksLv** [comment]
Hi, so we got this issue resolved. I just deleted folder "Settings". It created new settings for towny and now its working.

**Comment by LlmDl** [comment]
Well that is a bit anti-climactic but I'll take it.
