### ISSUE TITLE
Suggestion: Town Toggle for Animal Lure

### ISSUE THREAD

**Issue by madmaz999** [TownyAdvanced/Towny#3419]
**Please explain your feature request to the best of your abilities:**
Hello, I've recently found that animals won't follow players into plots. After asking for help regarding this issue I found that this was due to the players not being able to break dirt. 

The request then, would be if it were possible to add a town toggle, to allow animals to be lured into town.

Thanks regardless, love the plugin!

**Comment by LlmDl** [comment]
Solved this by making the luring requirements less strict, it will be a part of 0.94.0.14:

- Change requirements for luring animals.

    - Old behaviour: Player had to be able to break dirt where the
animal stood. Affected in towns and wilderness.
    - New behaviour: Player has to be able to break dirt where the
animal stands. Affects only personally owned plots.
