### ISSUE TITLE
Issue with worldguard chest-access flag for lecterns

### ISSUE THREAD

**Issue by MidnightSugar** [TownyAdvanced/Towny#3420]
Worldguard 7.0.1 has feature where you set interact to allow and chest-access to deny, and people can look at books in lecterns, but cannot take the books. When towny is installed, and useTowny=false is disabled in the world config, people can take the book regardless of worldguard flag. The worldguard developer said that towny must be uncancelling the event.

**Comment by wizjany** [comment]
ref: https://github.com/TownyAdvanced/Towny/blob/950ea32bfd6a2538186458df7c8df0248f7db73b/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L1086

**Comment by LlmDl** [comment]
wooops. thanks @wizjany and @MidnightSugar for spotting this. Fixed as of https://github.com/TownyAdvanced/Towny/commit/9f3ca69f3994d88d7290193427a5dfbc61a81279

**Comment by LlmDl** [comment]
@wizjany anyone else who has this happen can be  told to use [0.94.0.12 or newer.](https://github.com/TownyAdvanced/Towny/releases/tag/0.94.0.12)

**Comment by wizjany** [comment]
haven't tried it myself but is that fix supposed to print stacktraces all the time, because it looks like it will?

**Comment by LlmDl** [comment]
It should return when the world.isUsingTowny returns false just before that.
