### ISSUE TITLE
Suggestion: Add leaderboard placeholdersapi

### ISSUE THREAD

**Issue by JustintheBox** [TownyAdvanced/Towny#3421]
I would really enjoy placeholders such as %towny_town_top_balance_#% where # you can enter the rank of a town balance. Same with land and residents.

So these placeholders:
%towny_town_top_balance_#%
%towny_town_top_residents_#%
%towny_town_top_land_#%

**Comment by LlmDl** [comment]
I have nothing to do with placeholdersapi, or the existing placeholders that it has for towny.
