### ISSUE TITLE
Suggestion: Lure Activation

### ISSUE THREAD

**Issue by mamilicalmir** [TownyAdvanced/Towny#3422]
**Please explain your feature request to the best of your abilities:**
I have TownyChat, TownyNameUpdate and Towny plugin together with the general plugins like Essentials. I want to suggest to change the lure activation for the animals luring. I already tried setting, towny.wild.destroy.cow or towny.wild.destroy.wheat and it doesn't work. I have 2 worlds, the resources, and the main world. The resources world is where my players gather materials and in main world where they can claim lands but can't edit wilderness.

I tried towny.wild.destroy.dirt and it worked! So, please accept this suggestion thank you.

**Comment by LlmDl** [comment]
Solved this by making the luring requirements less strict, it will be a part of 0.94.0.14:

- Change requirements for luring animals.

    - Old behaviour: Player had to be able to break dirt where the
animal stood. Affected in towns and wilderness.
    - New behaviour: Player has to be able to break dirt where the
animal stands. Affects only personally owned plots.
