### ISSUE TITLE
Blank messages

### ISSUE THREAD

**Issue by Henaminator** [TownyAdvanced/Towny#3424]
Messages are blank after I change the name of:
https://gyazo.com/ee3a750ea9f419e22d5e24d7fbbbdd35
from engish.yml to norwegian.yml

**Comment by LlmDl** [comment]
Did you change it while the server was stopped?

**Comment by Henaminator** [comment]
I have tried both on and off. But I figured it out kinda, I tried copying sections from the norwegian.yml to the english.yml and reloaded, and seem to be working. But when I copy over the whole yml file at once from norwegian to english, it doesn't seem to be working, so there are probably something missing/broke in the norwegian.yml

**Comment by LlmDl** [comment]
Nevermind, at some point the file got it's yaml wrecked.

https://pastebin.com/NnrYGr0x take that and put it into a new file called norwegian.yml in your settings folder.
