### ISSUE TITLE
Suggestion: Protecting Nametagged Mobs

### ISSUE THREAD

**Issue by ElsaTheHobo** [TownyAdvanced/Towny#3431]
Some players, like me, like to keep hostile mobs in their base for fun. Whether it be tiny slimes or endermen stuck in boats, generally players will nametag them to keep them from despawning. However, claiming towny land over them is a risk on servers that allow hostile despawning - you have to set mobs to true for the chunk/town before the game can wipe them out, and this comes with the obvious drawback of allowing hostiles you don't want into the area!

My suggestion: a config option for the mobs setting to **overlook mobs with nametags.**

This way, someone's bank customer husk nicknamed "Karen" won't be vanquished when the area is claimed / mobs are disabled, while still preventing true problems like pillager sneak attacks.

Thanks for considering, the mod is lovely!

**Comment by LlmDl** [comment]
This is a thing as of https://github.com/TownyAdvanced/Towny/commit/b867c0313af08087908701dc67991c2e874c58c4 and will be a part of 0.94.0.16 when it is released.

**Comment by ElsaTheHobo** [comment]
that was fast as shit god damn lmao
