### ISSUE TITLE
Error on world import with Multiverse

### ISSUE THREAD

**Issue by SmallSansSerif** [TownyAdvanced/Towny#3433]
Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Towny version 0.94.0.15
Multiverse-Core version 4.1.1-SNAPSHOT-b777

**Towny fails to add world when importing a world with Multiverse.**

 https://pastebin.com/NKq25vg9

**Comment by SmallSansSerif** [comment]
![2019-10-07_19 08 15](https://user-images.githubusercontent.com/4984139/66356119-e53d8c80-e937-11e9-99b4-f404267908cc.png)

This is what you get in game if you move in that imported world.

**Comment by LlmDl** [comment]
Fixed in 0.94.0.16
