### ISSUE TITLE
Suggestion: Turn towny override into a toggle

### ISSUE THREAD

**Issue by Kbryst** [TownyAdvanced/Towny#3434]
So we have things like /towny spy and /res toggle plotborder.

It would be amazing if we can turn the towny override into a toggle as well. No matter how well I train (and watch) my staff, every now and again they make the same mistake. They think they are raiding a fallen town when really.... they aren't. I've reminded them of /t here a million times over.

Other plugins (like lock plugins) do have their override as toggle command.

**Comment by LlmDl** [comment]
Whats towny override exactly? Their abilities while having a towny.claimed or towny.admin permission nodes?

**Comment by Kbryst** [comment]
I'm talking about the towny.claimed. I've never used the admin nodes (can't think of a reason why I haven't, going to assume I just never noticed them)

**Comment by LlmDl** [comment]
I think what you need is a staff plugin if you have staff that play as normal players some of the time.

https://www.spigotmc.org/resources/staff-the-ultimate-moderation-plugin-1-7-1-14.41500/

This one has the ability to add/remove permission nodes like the towny.claimed.* nodes.
