### ISSUE TITLE
Question: Enable blaze

### ISSUE THREAD

**Issue by PilsetnieksLv** [TownyAdvanced/Towny#3436]
Hello, I want to enable blaze spawning in the towns while the mob spawning flag is enabled. How can I do that? I want to still keep all other hostile mob spawnings disabled. I want that player can make blaze farm from a spawner, currently, I placed a blaze spawner and they aren't spawning.

**Comment by LlmDl** [comment]
You could change the config's `town_mob_removal_entities: Monster,Flying,Slime,Shulker,SkeletonHorse,ZombieHorse` entry.
Remove Monster and add all of the bad mobs in individually, except the blaze. The correct names are on this page https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/LivingEntity.html
