### ISSUE TITLE
Suggestion: Ranks mayors can give to non-town-members.

### ISSUE THREAD

**Issue by DeadGlamour** [TownyAdvanced/Towny#3437]
My idea is this, there will be a new set of ranks, only given to foriegner, perhpas only to other nation memebers or allies, but the idea is this : since town merging has been said to be a complex feature which will take some times, this could be an even better alternative, letting players taking more part in their nation's towns while still keeping the balace of power between the mayors (all retain the same ammount of power, not like the town merging in which 1 loses all power), this could help nations a lot and help friendly towns help each other.

**Comment by LlmDl** [comment]
So you want a rank that can be given to non-town members who are in the same nation? And that rank would give what sort of permission nodes? towny.claimed.townowned.* ?

**Comment by DeadGlamour** [comment]
exactly

**Comment by Prscyse** [comment]
I agree.

**Comment by DeadGlamour** [comment]
Oops silly me didnt see the question, personally I think the ranks should be configed like the rest of the ranks but the default could be a builder for having access to everything which isnt private or trusted which give even in private plots, I hope I understood it right.

**Comment by LlmDl** [comment]
This doesn't completely fill the issue but as of 0.95.0.1 town-owned plots can have Build/Destroy/Switch/ItemUse perms applied to nation-members (separate from Allies.)

I was looking at the code recently regarding applying ranks and there's currently two tests making sure that the player is in the same town. There's probably more tests involved in taking away ranks from players.

**Comment by LlmDl** [comment]
I'm closing this ticket. With the above PR's we don't have to worry about dealing with ranks being held by non-town members.

On top of my previous comment and that town merging is also a thing these days, there's nothing asked for that cannot be done already.
