### ISSUE TITLE
Suggestion: A command to add custom town and nation prefixes and sufixes

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#3440]
A way to customize the prefixes and suffixes of your town and nation.

**Comment by LlmDl** [comment]
This is done by the admin in the town and nation levels, but the town and nation tags can be customized by the mayor/king. 

You're talking about the stuff like 'the land of nationname' right?

**Comment by VreyaViress** [comment]
Yes, so players (mayors or kings) can have the freedom to customize the town's or nation's name to "United States of Akloria (Megalopolis)" without having it predefined by the number of residents and according to the admin's configuration.

If not, at least making it possible to add new hierarchy levels in the config, just like it's possible to add unlimited ranks, and without making them "size" determined, would be awesome. That way players can select from a list of approved prefixes and suffixes from the admin.

**Comment by LlmDl** [comment]
Why doesn't the town just change it's name to United States of Akloria?

**Comment by VreyaViress** [comment]
Because it was shown with underscores for spaces, but I just noticed that was fixed.

Thank you
