### ISSUE TITLE
Custom titles are mashed with player name

### ISSUE THREAD

**Issue by MayorMike** [TownyAdvanced/Towny#3441]
### What steps will reproduce the problem?
1. Change player's title `/n set <player> <title>`
2. Name and title end up mashed together

### What is the expected output?
1. Title and custom titles not being mashed together

### What is your Towny version?
Do not say "latest". 
0.94.0.18

### What is your spigot/craftbukkit version?
Do not say "latest". 
git-Spigot-94af569-d6b3edd (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Server Startup Log: https://pastebin.com/nbyL4wyL
2. Your Towny config.yml: https://pastebin.com/HXHFrtMF
3. Your townyperms.yml : https://pastebin.com/tbLAZvRe
4. Your log's error : No error listed in log

(optional) If this is to do with permissions, 
5. Your permissions file : Not permissions related.

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/qLxAN5VV
7. Your channels.yml : https://pastebin.com/WuKeuBmW

As stated, titles set with `/n set title <player> <title>` get mashed with the player's name. Titles set in the config file are still normal. Screenshot attached shows an example. 
![TownyChat](https://user-images.githubusercontent.com/5709976/66725592-ce43e200-edf0-11e9-98c5-0540452e33c5.png)

**Comment by LlmDl** [comment]
Fixed this in https://github.com/TownyAdvanced/TownyChat/commit/02573e6bde0d59070f6b87b18b12daf3f4de2d22 which will be a part of TC 0.57. I do not know how long this has been a thing or why it popped up just recently if it is not an old issue though.
