### ISSUE TITLE
Fix /ta toggle debug

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#3443]
After the new logger was put in, the debug messages only show if the server was started with debug_mode set to true in the config. The ability to turn it on and off via the '/ta toggle debug' command has been lost.

Steps to reproduce:

- Start server with config's debug_mode: false.
- Use /ta toggle debug.
- Perform any action that should be outputting debug text to the console.
  - Easiest probably being moving to a new plot and breaking something which should display debug text of the cache being rebuilt.

**Comment by Articdive** [comment]
Will do that over the next weekend.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/pull/3452
