### ISSUE TITLE
Suggestion: Make rank names case-insensitive

### ISSUE THREAD

**Issue by AfkF24** [TownyAdvanced/Towny#3445]
**Please explain your feature request to the best of your abilities:**
Basically what the title suggests. When attempting to assign a rank to a player (eg. `/t rank add AfkF24 assistant`) you have to specify it in lower-case which shouldn't really matter that much.

As a side question, does townyperms.yml allow ranks to be capitalized and does that affect how ranks are displayed on `/t <town>` page?

**Comment by LlmDl** [comment]
I am fairly sure I did a ticket a while back that made it so you could do capitalized ranks. People were complaining that Assistants didn't match Mayors/Residents casing on the/town screen.

I'll look into making the command case insensitive.

**Comment by AfkF24** [comment]
Just another quick question. If I change ranks in townyperms.yml to have the first letter capitalized, will it mess up any already granted ranks that players have or does the system not care about case sensitivity?

**Comment by LlmDl** [comment]
i am betting it messes it up real good, but you could test it yourself

**Comment by AfkF24** [comment]
Yeah, changing the capitalization via townyperms.yml just looks at it as a completely new rank, meaning that users lose their ranks. Reverting back to lower-case names works though.

**Comment by LlmDl** [comment]
Done in https://github.com/TownyAdvanced/Towny/commit/462b5bb30847089d195f9264c890c3bcb18e1289 and will be a part of 0.95.0.1
