### ISSUE TITLE
Suggestion: Per-town specific rank permissions

### ISSUE THREAD

**Issue by AfkF24** [TownyAdvanced/Towny#3447]
**Please explain your feature request to the best of your abilities:**
Basically have a command for setting per-town rank permissions, eg. `/t set perm assistant build on` (or similar), etc. Looks easier than it actually is, I know, but really is a game changer.

**Comment by LlmDl** [comment]
You're thinking to apply rank to the plot perm line of all the plots/towns?

**Comment by AfkF24** [comment]
Well pretty much so. I have gone with a workaround where I've created a new rank which has `towny.claimed.owntown.*` permissions to build everywhere regardless of resident b/d/s/i permissions. So in conclusion, not as needed as I initially thought. A simple modification of the townyperms.yml does the trick.

**Comment by LlmDl** [comment]
Yeah, that's not the sort of thing plot perms are going to get. Using new ranks is the way to go.
