### ISSUE TITLE
Question: Chat formatting & sizing

### ISSUE THREAD

**Issue by AfkF24** [TownyAdvanced/Towny#3448]
**Ask your question as best as you are able:**
Don't really know if I should classify this as an issue, but just a quick question regarding chat and why are longer messages being cut into multiple lines?

Eg. I would expect this message to be displayed to its full length (depending on client's chat width setting):
```
[Towny] You have successfully revoked an invite to join your nation.
```
But instead it's being displayed in two lines, almost like there's a per-line character cap for messages the plugin has:
```
[Towny] You have successfully revoked an
invite to join your nation.
```
(It's not this specific message that's doing this only, it's basically any lengthier one.)

**EDIT:** The message shown above is a bad example, as I've noticed that mostly messages containing a variable are doing this. Need to test a bit more to know for sure.

**Comment by LlmDl** [comment]
We dont do this.

**Comment by AfkF24** [comment]
Here's an example where this is happening though:
```
msg_unknown_rank_available_ranks: 'Unknown rank %s. Permissible ranks are %s.'
```
Ingame:
![chatcap](https://user-images.githubusercontent.com/12214250/66967515-766fda00-f081-11e9-992c-bb3d22aa1418.png)
(The chat box clearly has space to fit the message in a single line)

**Comment by LlmDl** [comment]
That one's cutting off because the 2nd line is all one word with no spaces and it wouldn't fit on most screens chat lines. We aren't doing anything other than player.sendMessage() for most things when it gets down to the core of TownyMessanger. I don't know when chat boxes got so wide but mine isn't.

**Comment by AfkF24** [comment]
Running Optifine allows changing the chat width to be >320px.

**Comment by LlmDl** [comment]
Yeah but when we send a message using the bukkit server software to a player, it's probably only working off of a 320px chat box. It cannot tell your chat line is wider.

**Comment by AfkF24** [comment]
Pretty weird to be honest. Towny is only plugin of mine that acts oddly when it comes to this. Even TownyFlight doesn't 'suffer' from this issue, as messages get displayed to the full length of client's chat box
