### ISSUE TITLE
Suggestion: One time warning when town taxes are higher than X amount or percentage

### ISSUE THREAD

**Issue by Prscyse** [TownyAdvanced/Towny#3451]
An option in the config file to enable or disable a warning that works as the town board -but with either a custom format or all in red- that allows players to know whenever the mayor sets the tax amount or percentage higher than a number configured in the config.

The warning could be shown whenever a player receives an invitation to show, as well as when the new tax is set by the mayor, until the next time the player logs in. Like a flag "seen warning" that'll make the warning stop appearing after getting it.

Example:

Warning: This town charges a tax of 75 %.

**Comment by LlmDl** [comment]
This seems like it would be something already handled by the config's section that caps tax percentages:
```
    # maximum tax percentage allowed when taxing by percentages
    max_tax_percent: '25'
```

**Comment by LlmDl** [comment]
Closed for lack of feedback.
