### ISSUE TITLE
Question: Can old ranks player had in their towns be removed somehow?

### ISSUE THREAD

**Issue by AfkF24** [TownyAdvanced/Towny#3455]
**Ask your question as best as you are able:**
I've changed some of names of ranks through townyperms.yml and everything's working just fine except for the part that old ranks players were part of before the change still show up on the /res screen - even though there aren't in use any more. Can this somehow be changed? Thanks!

**Comment by LlmDl** [comment]
Some of those players must still have teh old rank names I'm guessing. Go through the towns residents files in towny\data\residents\name.txt

**Comment by AfkF24** [comment]
Is there a more efficient way of doing this through sql?

**Comment by LlmDl** [comment]
A find and replace?
