### ISSUE TITLE
Suggestion: Config option to hide number of citizens in /t list and show city names in random order

### ISSUE THREAD

**Issue by kekke3r** [TownyAdvanced/Towny#3456]
**Please explain your feature request to the best of your abilities:**
I would like to have a config option to hide number of citizens in /t list and show city names in random order and not sorted by number of citizens.
The majority of new players does /t list and enters the 1° city in the list if it's open, or want to enter in that city even if it's not only because of the number of citizens. This make very difficult for the other cities to gain citizens and claims. I would prefer if players choose the city by visiting them and not only by seeing how many players are in it. I'd like to keep /t list as a command because it's useful for new players to see the name of the cities.

**Comment by LlmDl** [comment]
We recently made it possible to list the towns and nations by a bunch of different rankings. I'm sure a random one would be fairly easy to work in.

**Comment by kekke3r** [comment]
Fantastic! Thanks a lot!

**Comment by LlmDl** [comment]
Done as of the above commit, will be a part of 0.95.0.5
