### ISSUE TITLE
Wither Boss deals 0 damage to animals in the Wilderness

### ISSUE THREAD

**Issue by Blackyvk** [TownyAdvanced/Towny#3459]
### What steps will reproduce the problem?
1. Spawn a wither in wildnerness
2. Let the wither shoot any animal
3. animal is not damaged

### What is the expected output?
1. animal should be damaged in the wildnerness

### What is your Towny version?
0.95.0.1

### What is your spigot/craftbukkit version?
1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/AMffh94t
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/raw/hj4iD2U7
3. Your townyperms.yml :  https://pastebin.com/raw/AK47naVS
4. Your log's error :  no errors

5. worldname.txt: https://pastebin.com/raw/rKYPFyra

**Comment by LlmDl** [comment]
Fixed as of https://github.com/TownyAdvanced/Towny/commit/36fd9d073d880cb9c0b6242ae294f11f292f38a6 and will be a part of 0.95.0.2
