### ISSUE TITLE
Suggestion: Communities inside towns

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#3460]
Small groups inside towns with a custom name, their own channel chat, and collective property -like a town inside a town- but actually, communities. This could be useful for things like schools, hospitals, etc.

**Comment by VreyaViress** [comment]
I create a group inside Colosia's town called Army. Then I invite any resident from the town who wanst to join. Now we have our own Army channel and the leader of the group, if allowed by the mayor, can claim for the group any plot, making that plot and setting its perms.

**Comment by VreyaViress** [comment]
I create a group inside Colosia's town called Regional Hospital. I invite those who want to join. Now we have our own Regional Hospital channel, and the leader of the group can claim plots in the hospital's name.

**Comment by LlmDl** [comment]
What you're describing is more like a town being able to have some of its residents split off from the town, into their own town which exists in a nation with the original town. The new town has the right to the original town's plots.

I like the idea of being able to create a sub-town but there's no simple way to get all the other things you want without it becoming an actual town, separate from the original town.

**Comment by VreyaViress** [comment]
It wouldn't become an actual town because it's perms and property would still be submitted to the mayor or any other configured town.

Making communities a thing would also boost the town ranks usage as, in my experience, not many servers and players do.

Right now, the only way of achieving what I suggested is threating nations as towns and towns as communities. However, it's not the same, as kings don't have permissions over noncapital town's plots.

I do see sub town level additions, and maybe even over levels, as a good useful nonharmful feature. It'll give of creating better-organized metropolises. It'll allow towns to organize armies, and maybe even military units. Some will use the feature to create Ministers or Secretaries, like in a Democracy, while others will use it to create social classes like in a Monarchy. It's a way of adding many possibilities together. Just like the nature of Towny itself, that isn't just a game mode, but actually a tool for players to create anything they like. Make the tool even more useful, please.

**Comment by LlmDl** [comment]
This one is pretty ambitious but I don't think it can be integrated into Towny.
