### ISSUE TITLE
Project: Update Database code

### ISSUE THREAD

**Issue by Articdive** [TownyAdvanced/Towny#3461]
So I'm back for a while again and while I'm at it I might aswell take care of our biggest problem so the plan is this:
- [ ] move all database code to the .database package (it's the new workspace since I'm working on this from scratch)
- [ ] Make TownyDataSource and TownyDatabaseHandler into 1 class TownyDatabase
- [ ] Add Gson/JsonTownyDatabase
- [ ] Make our SQL Databases great by using the normalization methods.
- [ ] Instead of having the loaded users stored in TownyUniverse we store them in the TownyDatabase as a static HashSet, give all stored Objects a unique hashcode(), which will be an integer id that we use in the SQL Database.
- [x] Find a way to make our SQL-database more update-able without too much hassle and specific code (what we have now)
- [ ] Make sure that loading and saving from 1 format works with the other one, this might require saving the object's IDs in flatfile/json.
- [x] Remove the whole load resident names first and then the resident object, this should be finished in 1 entire step from now on we load the Resident object as a whole, meaning their id,name and attributes all at once, and no more loadResidentList() and loadResidents() and loadResident().
- [ ] Use a normalized naming strategy for future objects we require for making War persistant.
- [x] Flip the 1 to n database connections for Resident -- TownBlock, Town -- Nation, Town -- Resident and Town -- TownyWorld. (e.g nation won't save towns=, but town will save nation=), this heavily reduces the complexity of the database, since saving lists is a pest and yeah

**Comment by Articdive** [comment]
Update:
https://i.imgur.com/z063nDK.png

btw that is pretty much copied just different references for towns and nations.

**Comment by suneettipirneni** [comment]
JDBC multithreading
https://docs.oracle.com/cd/A97335_02/apps.102/a83724/tips1.htm

**Comment by suneettipirneni** [comment]
Also async databases are unnecessary (and very hard to implement) we just need the saving calls to be multihreaded so it doesn’t block the main thread for each write to the dB similar to how files are currently saved.

**Comment by LlmDl** [comment]
Much of this will not be implemented in the new UUID based db so I am closing this.
