### ISSUE TITLE
Altering max_claim_radius_value has no effect.

### ISSUE THREAD

**Issue by tmfksoft** [TownyAdvanced/Towny#3462]
### What steps will reproduce the problem?
1. Change `max_claim_radius_value` to any value above the default 4
2. Start server or reload the configuration via `/ta reload`
3. Try and claim a radius higher than 4 and lower than your configured value e.g. `/t claim 5`

### What is the expected output?
1. Being able to claim a radius higher than 4 when configured to do so.
2.
3.

### What is your Towny version?
v0.95.0.0

### What is your spigot/craftbukkit version?
Paper/Spigot 1.14.4-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. latest.log: https://pastebin.com/cn7g7PLy
2. Config: https://pastebin.com/139XfWUn
3. Towny Perms (Default, untouched) https://pastebin.com/qkxC3sVf
4. No errors present in console only in game: https://smallimage.in/168g43l5acxd9p12hp1h3u2zwomrrixj.png

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Does the limit reflect teh config value after you do a stop and start?

**Comment by LlmDl** [comment]
Just tested this and it the config value is read properly after a /ta reload and a full stop and start. Make sure you're saving your config.yml back to your server directory.
