### ISSUE TITLE
Bug with allowed by permission attachment

### ISSUE THREAD

**Issue by Mitsu13Ion** [TownyAdvanced/Towny#3463]
### What steps will reproduce the problem?
1. Use Paper 1.14
2. Ultra Permission and Towny 1.14
3. Look why all people have all perm

### What is the expected output?
1. Player Permission
2. Not a player can use /op
3.

### What is your Towny version?
0.95.0.0

### What is your spigot/craftbukkit version?
#221 Paper

1. Your full server startup from the logs\latest.log : https://pastebin.com/zTwBre21
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/TTEww6QS
3. Your townyperms.yml : https://pastebin.com/H8PGr5QQ
4. Your log's error : nothing 

(optional) If this is to do with permissions, 
5. Your permissions file : is in database

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/RMgCNahX
7. Your channels.yml : https://pastebin.com/3R9Rbd50

**Comment by LlmDl** [comment]
So you'r saying that ultrapermissions is giving everyone access to /op and anything else when you have Towny installed?

**Comment by Mitsu13Ion** [comment]
Yes

**Comment by LlmDl** [comment]
Have your tried one of their slightly older versions that doesn't have the database recode? 

This isn't a Towny issue.
