### ISSUE TITLE
Question: Issue with Depositing

### ISSUE THREAD

**Issue by MarlesTharkley** [TownyAdvanced/Towny#3464]
**Ask your question as best as you are able:**
I went to deposit into my town bank and I wouldn't get anything deposited. I checked the server console and it would say warning file not found and had a minecraft userID that had never played on my server. I thought I had fixed it by copying my playerdata and changing the ID to match, but I had another person on my server have the same issue and it has a different playerdataID. Do I have to manually create each persons bank?

> java.io.FileNotFoundException: ./world/playerdata/32fdfd3c-1cf7-3e01-b5fb-ccc26aa33cc6.dat (No such file or directory)

**Comment by LlmDl** [comment]
Re-file this as a bug report. You need to fill out the form so I will be able to answer you.
