### ISSUE TITLE
Suggestion: Per Town ranks and Cosmetic Ranks

### ISSUE THREAD

**Issue by Sprungente** [TownyAdvanced/Towny#3465]
Part 1: Get the possibility to create ranks without bonus-permissions. A town-rank can be used when min. 1 permission is given. The idea to create rank also without extra permission would be cosmetic and now i come to 

Part 2: A Major should can make the Town more individual. That starts with an own hierarchy. They can rename (if enabled in a config) the name of a rank who was set in townyperms.yml and can create cosmetic-ranks (both are affect their own town)

But first: Is this idea realistic and feasible?

**Comment by LlmDl** [comment]
I believe part 1 is already possible? I don't think the rank has to have any nodes for it to be assignable to a player.

As for part 2, I don't think it would be very feasible to have the ranks be rename-able. We'd have to store all the ranks' names in each town, then filter them all through that ranknamelist in the TownyFormatter/rank lists pages.

**Comment by Sprungente** [comment]
Part 1 isn't possible yet otherwise donator and vip would be available ingame

Part 2: :-(

**Comment by LlmDl** [comment]
Part 1 might be something I can fix. If you're wanting something cosmetic for mayors to be able to use maybe https://github.com/TownyAdvanced/Towny/issues/3439 would work better? Actual titles/surnames in chat would stand out a lot more than a list on the /t screen and the /t ranklist pages.

**Comment by Sprungente** [comment]
that would work better, sounds good :D

**Comment by LlmDl** [comment]
Looks like null ranks won't be coming anytime soon, but mayors can now set titles/surnames.
