### ISSUE TITLE
Issue: Depositing in Town Bank

### ISSUE THREAD

**Issue by MarlesTharkley** [TownyAdvanced/Towny#3467]
### What steps will reproduce the problem?
1./t deposit amount

### What is the expected output?
1. the town to hold the balance and create the account to hold said funding or link it?

### What is your Towny version?
towny 0.95.0.0

### What is your spigot/craftbukkit version?
spigot 1.14.4

### Please use Pastebin.com to link the following files:
(1-4)-v
https://pastebin.com/7CdKtBVP

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
The command is /t deposit {amount}

**Comment by MarlesTharkley** [comment]
I meant to say /t deposit amount I wasn't thinking very well while writing it up

**Comment by LlmDl** [comment]
Your economy plugin probably doesn't support the older vault calls that we use for town and nation banks. You can ask Onenrico to update his plugin or you can switch economy plugins to one that does work.
