### ISSUE TITLE
Suggestion: Add permanent taking of land to Event war.

### ISSUE THREAD

**Issue by pegla2108001** [TownyAdvanced/Towny#3470]
**Please explain your feature request to the best of your abilities:**
Aight, so hear me out.
Regular built-in towny wars, but with conquering.
What kind of conquering? The kind of conquering where one nation can take land from the other, whether it'd be by occupation chunk-per-chunk, occupation on the homeblock or killing the opposing nation's members (toggleable), in a sense that you would still have to declare war independently (so not the entire server is dragged into war, just 2 nations, although you could make this 'expandable' by adding some sort of coalitions of nation and shit like that, so that like 2-3 nations can attack the same one at the same time and be able to reduce the points/capture land), and it would start as the usual flag war, by placing a fence post or wool or whatever. Togglable griefing as well.

**Comment by LlmDl** [comment]
I don't think we're going to go back to the fence/wool thing but the actual taking of land is something I can probably work into Event War. 

The 2 nations thing is also coming along with many more options when the next big war re-write happens.

**Comment by LlmDl** [comment]
This will be a part of 0.95.0.4

**Comment by pegla2108001** [comment]
Could there also be an option if the homeblock is claimed, the town is disbanded, all of its territory goes to the town that conquered it, and the members of the conquered town join the one that conquered it?

**Comment by LlmDl** [comment]
Should be doable, Can you file a new suggestion ticket with those in it?
