### ISSUE TITLE
Suggestion: add new tracking for bstats

### ISSUE THREAD

**Issue by Sprungente** [TownyAdvanced/Towny#3472]
Since i translate a lot in german.yml i'm wondering how many people who are running towny on their server using the german version of the plugin. 
Could you add, that bstats tracks which language is activated? 
I'm curious about the result :D

**Comment by LlmDl** [comment]
Will be a part of 0.95.0.4

**Comment by LlmDl** [comment]
It's also worth mentioning that only about 1/3rd of people using Towny also enable bStats.

Bstats right now shows 114 0.95.0.0 users.
Github download stats show 357 0.95.0.0 downloads.
