### ISSUE TITLE
EconomyChangeEvent WARN

### ISSUE THREAD

**Issue by TheCalypso** [TownyAdvanced/Towny#3475]
### What steps will reproduce the problem?
1./t claim
2. /plot fs 100
3./plot claim (I have 100€)
4.But I don't have plot.

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Do not say "latest".
0.95.0.4 same in 0.94.0.18

### What is your spigot/craftbukkit version?
Do not say "latest".
Use PaperSpigot-223

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/pkRivjx6
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/G2stH344
3. Your townyperms.yml : https://pastebin.com/GgKV7DLC
4. Your log's error : https://pastebin.com/pkRivjx6 (at end)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
That event is a CC3 event, not ours. It would have to be fixed on their end.

**Comment by LlmDl** [comment]
Looks like there's a newer fork of CC3 here: https://github.com/pavog/craftconomy3
