### ISSUE TITLE
Suggestion: Option for Towns to create alliances with other Towns, outside of a nation.

### ISSUE THREAD

**Issue by SkyCodes99** [TownyAdvanced/Towny#3476]
There should be some options in the config to allow towns to ally with each other without the need for a nation. This could also open the door for town vs town wars rather than just nation wars that currently exist.

**Comment by LlmDl** [comment]
With the change to the perm lines in 0.95.0.1 (splitting nation from ally) this could be fairly doable, while still being configurable for the end users.
