### ISSUE TITLE
Suggestion: Weekly Upkeep Option & Set Amounts per level

### ISSUE THREAD

**Issue by SkyCodes99** [TownyAdvanced/Towny#3479]
Here are two features that should be added to the Towny plugin.

1. There should be a section to set weekly upkeep just as there is for daily. Even though it's probably not necessary, there could also be a monthly option as well.

2. There are currently multiplier modifiers for upkeep. There should be an option to set a certain amount for the level rather than change the modifier based on one single number inputted for town and nation each.

**Comment by LlmDl** [comment]
You can change the upkeep timer to be a week.

I dont really understand the second one because you could set the upkeep costs to $1 and use the multiplier to get whatever number you want.

**Comment by SkyCodes99** [comment]
In terms of ease of access and general visibility, there should be an area for daily upkeep and weekly. As for the multiplier modifiers, set amounts as another option to set would help visually and figuring out the exact multiplier for various prices seems like a hassle sometimes.

**Comment by LlmDl** [comment]
I'm still a bit fuzzy on this.

You want there to be two upkeeps on your server, the normal daily one and on the seventh day you want it run twice?

The multiplier thing, if you set your upkeeps to 1 dollar and then set the townLevel's upkeepModifier to 500.0, thats going to charge $500.00 upkeep for the towns in that townLevel.
