### ISSUE TITLE
Suggestion: Player war declaration

### ISSUE THREAD

**Issue by pegla2108001** [TownyAdvanced/Towny#3480]
**Please explain your feature request to the best of your abilities:**
Something like /twar declare <nation name> after that one of the events start depending on the config
(taking land/town swapping nations)
With an option for the cost, command for admins forcing the war, ending the war, setting points for towns (initial formula based on residents and claims), and command for nations peacefully ending the war ./twar end <nation name> 
commands are there just as some sort of guideline 
config for togglable fire/explosions, as well as list of commands forbidden during war.

**Comment by LlmDl** [comment]
This sort of thing will come after the war system is changed to accommodate more than just nation vs nation wars.
