### ISSUE TITLE
Ultra Permissions issue

### ISSUE THREAD

**Issue by PripOO7** [TownyAdvanced/Towny#3481]
### What steps will reproduce the problem?
1. Put Essentials in plugins folder
2. Put Ultra Permissions (https://www.spigotmc.org/resources/ultra-permissions.42678/) in plugins folder. It work well, yet.
3. Then when put this pluguin (At least Towny-0.95.0.3 for 1.14.4)

### What is the expected output?
1. When you put the Towny pluguin all the users have all the permissions, it doesn't happen whit PEX (Permissions X)
2.
3.

### What is your Towny version?
Towny-0.95.0.3 for 1.14.4

### What is your spigot/craftbukkit version?
Spigot 1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This is likely related to the recode that UP did recently and not a Towny issue. Older UPs did not have this issue. Being a premium resource and not open source I can't say what they're doing. Take it to the UP author of whom you are a paying customer.
