### ISSUE TITLE
Suggestion: Allow Buy Bonus max amount to be set in the Town Levels.

### ISSUE THREAD

**Issue by SkyCodes99** [TownyAdvanced/Towny#3483]
This alread exists for nations, but can there also be a feature to set the exact amount of bonus claim chunks per town level as well?

**Comment by LlmDl** [comment]
I don't know if I see the point, the townlevels sets out the number of townblocks they get already. Adding bonus blocks is the exact same thing as that, no? One just has the word 'bonus' in front but they're no different.

**Comment by LlmDl** [comment]
Sky clarified he meant to make the max_purchased_blocks in the config something that can scale based on townlevels rather than being one set maximum.

**Comment by LlmDl** [comment]
Done as of 0.95.1.9.
