### ISSUE TITLE
When using Cyrillic characters in the town name and reloading the plugin, player files are reset

### ISSUE THREAD

**Issue by luckybl0ck** [TownyAdvanced/Towny#3487]
### What steps will reproduce the problem?
1. Join the server
2. Create a town with a Cyrillic name
3. Use /townyadmin reload

### What is the expected output?
1. no error
2. correct reading of cyrillic characters
3. no reset of player files

### What is your Towny version?
Towny version: 0.95.0.4

### What is your spigot/craftbukkit version?
Paper version git-Paper-225 (MC: 1.14.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/agegagukop.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/xalofezufi.coffeescript
3. Your townyperms.yml : https://hastebin.com/utuxasizox.php
4. Your log's error : https://hastebin.com/adivuqagoq.sql

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
From the changelog (where it isn't super helpful)

```
        - name_check_regex: ^[а-яА-Яa-zA-Z0-9._\[\]-]*$
        - string_check_regex: ^[а-яА-Яa-zA-Z0-9\s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
        - name_remove_regex: '[^а-яА-Яa-zA-Z0-9._\[\]-]'
```

you need these settings in your config.yml's regex
