### ISSUE TITLE
/plot set outpost - returns "This area is too close to another town's town block." with no other nearby towns.

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3489]
### What steps will reproduce the problem?
1. Go to a claimed plot in town with no other towns nearby
2. Do /plot set outpost
3. You get this:
https://prnt.sc/psbqo3

### What is the expected output?
1. The plot would get turned into an outpost and you would be charged
2.
3.

### What is your Towny version?
Do not say "latest".

0.95.0.4

### What is your spigot/craftbukkit version?
Do not say "latest".

Paper 209 (1.14.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
 https://pastebin.com/1zkiV0Y4
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/7EJ3DNAh
3. Your townyperms.yml :
https://pastebin.com/0RBbquVW
4. Your log's error : 
No error on log.  Error in chat in the screenshot in the first section.
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Fixed as of the above commit, part of the forthcoming 0.95.0.5
