### ISSUE TITLE
Question: Make deposit all cities at one?

### ISSUE THREAD

**Issue by PripOO7** [TownyAdvanced/Towny#3493]
**Ask your question as best as you are able:**
I think this is a bug. When a do /reload on my server, every city's balance in the bank which has online members  goes to 0. 
I want know if there any cmd to make that deposit all at once

**Comment by LlmDl** [comment]
You should have filed this as a bug report, but you probably use essentials economy, for which this has been an known issue for years. Stop using ess eco if you're going to use /reload.

**Comment by LlmDl** [comment]
There is no command to deposit money to all the banks at once, that would be up to your economy plugin probably.
