### ISSUE TITLE
Strange behavior of /plot fs, /plot nfs, and /plot claim when economy is disabled.

### ISSUE THREAD

**Issue by RalphORama** [TownyAdvanced/Towny#3503]
### What steps will reproduce the problem?

1. Set `economy: false` in settings.yml
2. In a plot that **isn't** for sale, run `/plot claim`
  2a. Get the error `This plot is not for sale. This area has not been claimed.`
3. In a plot claimed by a town, run `/plot fs`
  3a. Receive message `Ralph put the plot (world,-904,-136) up for sale!
  3a. If you run `/plot nfs`, you get the error `This plot is not for sale.`
  3b. If you run `/plot claim`, you will successfully claim the plot.

### What is the expected output?

From step 3b: `/plot nfs` Should say something like "This plot is no longer for sale"

### What is your Towny version?

0.95.1.0

### What is your spigot/craftbukkit version?

Paper version `git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log: https://pastebin.com/HUFVH0CJ
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/2f8FxQPV
3. Your townyperms.yml: https://pastebin.com/6u8ua5vT
4. Your log's error: N/A (See reproduction)

**Comment by LlmDl** [comment]
Nice catch, looks like we were just re-using a language string.
