### ISSUE TITLE
Maven Dependency Issue with NewEconomy

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/Towny#3504]
### What steps will reproduce the problem?
1. Clone the Towny project from github
2. Go to the command line and type "mvn clean package"
3. An error is show, and the following dependencies do not download:
```
        <dependency>
            <groupId>net.tnemc</groupId>
            <artifactId>Reserve</artifactId>
            <version>0.1.3.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.tnemc.tnc</groupId>
            <artifactId>TheNewChat</artifactId>
            <version>1.5.1.0</version>
            <scope>provided</scope>
        </dependency>
```

### What is the expected output?
1. Dependencies should all townload
2. POM file should not show errors

### What is your Towny version?
0.95.1.6

### What is your spigot/craftbukkit version?
1.14.4-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log :  Can't start server. Code not compiling
2. Your Towny config.yml: No changes made to this
3. Your townyperms.yml : No changes made to this 
4. Your log's error : 
Here is the maven failure:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.894 s
[INFO] Finished at: 2019-11-21T12:53:35Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Towny: Could not resolve dependencies for project com.palmergames.bukkit.towny:Towny:jar:0.95.1.6: Failed to collect dependencies at net.tnemc:Reserve:jar:0.1.3.2: Failed to read artifact descriptor for net.tnemc:Reserve:jar:0.1.3.2: Could not transfer artifact net.tnemc:Reserve:pom:0.1.3.2 from/to github (https://maven.pkg.github.com/TheNewEconomy/packages/): Not authorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by LlmDl** [comment]
Not authorized usually means you haven't set up the github token.

**Comment by Goosius1** [comment]
Ok thank you that is probably it!,

I haven't set up that token  yet.

I'll try that

**Comment by Goosius1** [comment]
Got it working using a github token thanks 👍

**Comment by LlmDl** [comment]
It's a pesky system but it's still in beta so hopefully they remove needing a token entirely for people that just need to use the project as a dependency.
