### ISSUE TITLE
Suggestion:  I want to know if these PAPI placeholders can be used in the 1.12.2 version?

### ISSUE THREAD

**Issue by xiaoranjuny** [TownyAdvanced/Towny#3508]
I want to know if these PAPI placeholders can be used in the 1.12.2 version?
Or can I use towny0.95.1.6 on a 1.12.2 server?
More PAPI placeholders:
%townyadvanced_town_residents_amount% - number of residents in a town.
%townyadvanced_town_residents_online% - number of residents in a town that are currently online.
%townyadvanced_town_townblocks_used% - number of townblocks claimed by a resident's town.
%townyadvanced_town_townblocks_bought% - number of townblocks bought by a resident's town.
%townyadvanced_town_townblocks_bonus% - number of bonus blocks given to a resident's town.
%townyadvanced_town_townblocks_maximum% - number of townblocks a town has available to claim.
%townyadvanced_town_townblocks_natural_maximum% - number of townblocks a town has available to claim, not counting bonus/bought townblocks.
%townyadvanced_town_mayor% - a resident's town's mayor's name.
%townyadvanced_nation_king% - a resident's nation's king's name.
%townyadvanced_resident_friends_amount% - number of friends a resident has.
%townyadvanced_nation_residents_amount% - number of residents in a resident's nation.
%townyadvanced_nation_residents_online% - number of residents in a resident's nation that are currently online.
%townyadvanced_nation_capital% - name of a resident's nation's capital.

**Comment by LlmDl** [comment]
Those are not available for 1.12. [0.93.1.0 for 1.12.2](https://www.dropbox.com/s/v2e1uy6wip7rl3u/Towny_Advanced%200.93.1.0%20for%20MC%201.12.2.zip?dl=0) is the newest Towny made for 1.12.2. It does not have built-in PAPI support.

**Comment by xiaoranjuny** [comment]
Can I run Towny-0.95.1.0 for 1.13.2 on spigot1.12.2?
There is no problem with the current test.
Author, do you think this will cause a lot of problems?
If not, I will change to 0.93.10.

**Comment by LlmDl** [comment]
If it works then use it, as far as I remember there are parts which will not work.  Use at your own discretion.
