### ISSUE TITLE
Suggestion: Towny Autobalancing Feature

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3509]
## Motivation ##
While being an admin on my server I've noticed an ongoing issue with towny, players tend to want to join bigger towns rather than smaller ones which creates a huge imbalance in terms of populations. I know that this issue could be rectified by more encompassing server moderation, however its just a lot of work to do so. This is why I think auto balancing should be an _optional_ to Towny.

## Implementation ##

- This feature would be a boolean stored in the config

- When a player joins the town, they would execute something like: `/t autojoin`

For the algorithm I would be using a coin flip for probability. Heres how it works:
- Store all towns in an ordered array sorted by population size (This array would be updated whenever some joins a town) e.g. 0 = not very populated, n = highly populated.
- The goal is to land on heads as many times as possible so for example the probability of landing on heads with one flip is 50%, the probability for two flips is 25%, the probability halves for each successive flip.
- This idea would be attached to how towns joined for example the town with the least population will have a 50% of being joined, the town with second least population will have a 25% chance of being joined and so on.
- By probabilistic nature of the flips, this should balance out towns automatically and naturally.

By having this feature this will take a lot of headache out of admins managing town sizes.

**Comment by LlmDl** [comment]
Similar in thought to this ticket: https://github.com/TownyAdvanced/Towny/issues/2402

**Comment by suneettipirneni** [comment]
Going to use #2402 as the more optimal solution with an implementation of percentages and close this issue.
