### ISSUE TITLE
Nation Leave is not possible using the default townyperms file

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/Towny#3511]
### What steps will reproduce the problem?
1. Log in to your server as a Mayor who is in a nation
2. Type "/n leave"
3. You get an error "You don''t have enough permissions for that command."

-> The underlying cause is that the required permission ("towny.command.nation.leave") is missing from the townyperms.yml file
-> Has this been done on purpose in the default townyperms.yml file?
-> Code-wise, the command works perfectly fine after I add the permission into my local perms file.

NationCommand.java:
```
			} else if (split[0].equalsIgnoreCase("leave")) {

				if (!townyUniverse.getPermissionSource().testPermission(player, PermissionNodes.TOWNY_COMMAND_NATION_LEAVE.getNode()))
					throw new TownyException(TownySettings.getLangString("msg_err_command_disable"));

				nationLeave(player);
```

PermissionNodes.java:
```
TOWNY_COMMAND_NATION_LEAVE("towny.command.nation.leave"),
```

townyperms.yml:  (Pasted directly from github)
```
    .....
    mayor:
        # Mayors get these permissions in addition to the default set.
        - towny.tax_exempt
        - towny.command.towny.top
        - towny.command.town.*
        - towny.command.plot.*
        - towny.claimed.owntown.*
        - towny.command.nation.new
        - towny.outlaw.jailer
        - towny.command.nation.join
        ********* If nation.leave was in the file, I guess it would be somewhere in this section *******
    ranks:
      .......
```

### What is the expected output?
1. I would have thought the town should immediately leave the nation
2. I seemed to be able to do it using the default perms file a few months ago, although perhaps it was always this way and i never noticed. The default of forbidding the leave seemed unexpected to me when it occurred.

### What is your Towny version?
0.95.1.7

### What is your spigot/craftbukkit version?
NA

### Please use Pastebin.com to link the following files:
**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : NA issue seems to be in townyperms file.
2. Your Towny config.yml (if using MySQL please remove password,) : NA issue seems to be in townyperms file
3. Your townyperms.yml : This is the townyperms pasted from master on github:
https://pastebin.com/Ab134uGb
4. Your log's error : NA issue seems to be in townyperms file

**Comment by LlmDl** [comment]
I thought I had fixed this, it's fixed now.
