### ISSUE TITLE
Suggestion: Allow War-Flag to have same option as War-Event:winner_takes_ownership_of_townblocks: 'false'

### ISSUE THREAD

**Issue by DalBrar** [TownyAdvanced/Towny#3514]
**Please explain your feature request to the best of your abilities:**
Our server would like to have more "for-fun" type wars instead of actually losing territory to attacking players so we were thinking it'd be nice if War-Flags also had the same option that the War-Event has, that is **winner_takes_ownership_of_townblocks: 'false'** so that only $$ is gained via winning/defending but properties remain the same.

**Comment by alynchbetbright** [comment]
Hi, although the flag war system itself seems to be unsupported now (as far as I know from reading the comment on the label), 
I am working on a new optional war system 'siege war' which I hope will be able to meet your server requirement. I am planning to send in a PR for this in the next few days. It is designed to allow war-on-demand (like flag war), and has a config which allows a server admin to enable plundering($$) but not invasion.

**Comment by Goosius1** [comment]
Hi, although the flag war system itself seems to be unsupported now (as far as I know from reading the comment on the label), 
I am working on a new optional war system 'siege war' which I hope will be able to meet your server requirement. I am planning to send in a PR for this in the next few days. It is designed to allow war-on-demand (like flag war), and has a config which allows a server admin to enable plundering($$) but not invasion.

**Comment by LlmDl** [comment]
Completed by TheFlagCourier.
