### ISSUE TITLE
Not being able to do /town create (name)

### ISSUE THREAD

**Issue by Alalanderson** [TownyAdvanced/Towny#3518]
### What steps will reproduce the problem?
1. Paper or Spigot installed
2. Plugins: EssentialsX, LuckPermissions, SurvivalPlus, Towny, TownyChat, TownyNameUploader, Vault, World edit
3. do /Town create (Name) 
4. Gives Error Null in Console

### What is the expected output?
1. to create a town
2.
3.

### What is your Towny version?
Do not say "latest".
0.95.10

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml : https://pastebin.com/zVV78W8u
3. Your townyperms.yml :  https://pastebin.com/vugGquc8
4. Your log's error : https://pastebin.com/TVaBmvEt
5. start up log: https://pastebin.com/HkBjnahp

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/CLGueAWV (My Personal rank)

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Alalanderson** [comment]
This might be my start up script https://pastebin.com/iiAxpK45

**Comment by suneettipirneni** [comment]
Something with `TownyLogger.getInstance().logMoneyTransaction(this, amount, null, reason);` just for dev reference.

**Comment by suneettipirneni** [comment]
Hi @Alalanderson, this doesn't seem to be a problem with towny, but instead the file permissions on your server:

> java.io.FileNotFoundException: logs/latest.log (Permission denied)

This is creating the Townylogger to become null and denying you the ability to create a town.

Luckily there's an easy solution to this problem 

To change the perms on the logging folder just execute this in your terminal application:
`sudo chown -R {user} {your_minecraft_folder}`

where {your_minecraft_folder} is the root folder of your minecraft server
and user is the user that runs the server.

Once the server can access the logs it should work, and not break when you try to add a town.

**Comment by ZackRuybal** [comment]
> Hi @Alalanderson, this doesn't seem to be a problem with towny, but instead the file permissions on your server:
> 
> > java.io.FileNotFoundException: logs/latest.log (Permission denied)
> 
> This in return is creating the Townylogger to become null and denying you the ability to create a town, because the server cannot access the log files it needs to edit.
> 
> Luckily there's an easy solution to this problem
> 
> To change the perms on the logging folder just execute this in your terminal application:
> `sudo chown -R {user} {your_minecraft_folder}/logs`
> 
> where {your_minecraft_folder} is the root folder of your minecraft server
> and {user} is the user that runs the server.
> 
> Once the server can access the logs it should work, and not error out when you try to add a town.

Further, the user it should belong to (assuming during setup you told Multicraft to set up a new user per server) should be mc<serverid>. So, for example, a server in the folder server4 would belong to user mc4. If it's in a custom directory and you don't know the id, you can find it within the multicraft panel as well. When you click the server on the server list page, part of the url should look like `view&id=4`. The username number should be mc<numberInURL>.

**Comment by Alalanderson** [comment]
Thank you both so much! did everything you said @suneettipirneni and found the user thanks to @ZackRuybal. And everything works perfect now!
