### ISSUE TITLE
Maven Javadoc executable causes install to fail 

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3519]
After running `mvn install` I now get a new error not present before:
```
MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The javadoc executable '/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/bin/javadoc' doesn't exist or is not a file. Verify the <javadocExecutable/> parameter.
```
I assume it has something to do with the latest java doc merges, in the meantime I have to remove it from the Pom to get the jar to install.

**Comment by LlmDl** [comment]
Have you installed a javadoc tool?

You should be able to mvn build rather than mvn install.

**Comment by suneettipirneni** [comment]
It was weird so javadoc was installed in /usr/bin/ but not in the folder that the plugin was pointing to so I just copied the binary to that folder. Now it works

**Comment by LlmDl** [comment]
I take it back, when I maven install on eclipse I get the error as well. Maybe a custom pom can be used for the actions workflow @TheFlagCourier ?

**Comment by TheFlagCourier** [comment]
Most certainly. The current pom would for sure work with Debian and MacOS, but a duplicate pom with the path to javadocs removed can be used for general devel. I'll post a PR shortly.

**Comment by suneettipirneni** [comment]
I was using macOS and it didn’t work.
