### ISSUE TITLE
Suggestion: Please stop using split as a variable name for storing .split() arrays

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3520]
Split is a super ambiguous name not to mention it conflicts with the method: ```str.split()```. In addition the places it's used its mostly represented as and array argument strings. so let's give the variable a name it deserves.

e.g. use args everywhere
```
String[] args = foo.split(",");
```

**Comment by LlmDl** [comment]
ok

**Comment by suneettipirneni** [comment]
leave it open you coward
