### ISSUE TITLE
Townys balance issues

### ISSUE THREAD

**Issue by Galvabit** [TownyAdvanced/Towny#3524]
We have been having a issue with essentials balance for a while now and switch to TNE but it sucks and so does the dev is there no way of you guys storing towns balances rather than using a external plugin which need to create a npc for is there no way it can just be store in the town data the bank value so instead of checking a offline player constantly it will be able to just go in and check what is in the towns bank 

thanks.

**Comment by LlmDl** [comment]
No we are not going to duplicate what your economy plugin is responsible for. Nice dig on the TNE author who is also part of the TownyAdvanced org though.
