### ISSUE TITLE
Question: Towny API

### ISSUE THREAD

**Issue by 3meraldK** [TownyAdvanced/Towny#3526]
**Ask your question as best as you are able:**
How to detect a player's chat by towny API for example on playerchatevent? I want to detect if player's current channel is nation, or town, or general

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/TownyChat/blob/master/src/com/palmergames/bukkit/TownyChat/events/AsyncChatHookEvent.java

You'd actually be hooking into TownyChat.

**Comment by 3meraldK** [comment]
close it
