### ISSUE TITLE
towny error ， save mode

### ISSUE THREAD

**Issue by xiaoranjuny** [TownyAdvanced/Towny#3527]
**Ask your question as best as you are able:**
For help, I modified the regular expression of the towny plug-in to support Chinese. But the plug-ins all failed after restart. Is there any way to convert flatfile data into mysql data? because mysql supports Chinese, and it still doesn't work when I change all the Chinese town names to English, which seems to need to modify a lot of town data, but it still doesn't work. I feel very uncomfortable now because this is the painstaking work of my players.

**Comment by LlmDl** [comment]
Converting to mysql is explained on the [how towny works](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#using-sql-instead-of-flatfile) wikipage.
