### ISSUE TITLE
According to a mod apparently chests are indistinguishable from buttons.

### ISSUE THREAD

**Issue by Skepoty** [TownyAdvanced/Towny#3530]
So if you are at war with a faction, according to an admin on the server chests are indistinguishable from buttons. So when someone is coming to raid your town, they can just open your metal doors and walk right into your base. Could you separate chests from the switches category so that raiders would have to use TNT to blow through the doors they want to raid? I can try contibuting if it is not too complicated, I have 1 year of dev work experience :P

**Comment by LlmDl** [comment]
Your admin can already make that happen. He just needs to set the switch option for wars to false, and let explosions happen. Explosions will regenerate after a minute.
