### ISSUE TITLE
Not charging for /town spawn

### ISSUE THREAD

**Issue by manuelps** [TownyAdvanced/Towny#3533]
Am I doing something wrong? I can do /town spawn and I don't get charged for it

Config.yml: https://pastebin.com/ipY8e54T
townyperms:  https://pastebin.com/Jd1NdzMa

**Comment by LlmDl** [comment]
are you op, are you mayor, does your town have a spawncost of 0?

**Comment by manuelps** [comment]
I'm not OP, but I am Mayor, I don't think so, I created my town and didn't change anything

**Comment by LlmDl** [comment]
What is your town's spawn cost set to though.

**Comment by manuelps** [comment]
Just checked and it's set to 0... how do I change the default value of this?

**Comment by LlmDl** [comment]
It pulls from the config, but you can set it to any cost up to the config's cost.

**Comment by manuelps** [comment]
Uh, I'm a little bit confused... On my config I have a cosat of 128 right?  So it should default to 128? Or it defaults to 0 with a max of 128?

**Comment by LlmDl** [comment]
It should be defaulting to 128. Did you make your town before you set the config to 128?

**Comment by manuelps** [comment]
just deleted and created a new town and it still defaulted to 0

**Comment by LlmDl** [comment]
File a new ticket, don't skip the form and it'll get looked at.
