### ISSUE TITLE
Confirmations via text Click events

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3534]
Right now a player has to type `accept` or `deny` when most confirmations prompts show. Because we now support spigot we could use the BungeeCord API to easily accomplish handling click events on the text. So players would be able to click accept/deny instead of typing.

This should just require only a little bit of modifications to the already existing confirmation systems.

**Comment by LlmDl** [comment]
The existing system will have to stay in place for those servers not running spigot/paper.

**Comment by suneettipirneni** [comment]
Yes, the current text system would be used for non-spigot servers, while the new click system would come up for spigot servers.
