### ISSUE TITLE
Towny Wilderness protection, how to fix it!

### ISSUE THREAD

**Issue by Jeffrey073** [TownyAdvanced/Towny#3535]
Dear Developer,

I would like to adjust the wilderness so that players cannot demolish / build in the wild, Towny does not respond to it via the config and also does not respond via commands. Hopefully we can solve this as this problem is currently bothering us before opening the server.

Thanks in advance,
Jeffrey

**Comment by LlmDl** [comment]
This should have been a bug report ticket. Pastebin.com your permissions file, your townyperms.yml and your towny\data\worlds\WORLDNAME.txt file.

**Comment by Jeffrey073** [comment]
https://pastebin.com/BaZC7XCQ <-- Townyperms

https://pastebin.com/hhD1NZMh <-- Config

https://pastebin.com/Jwa2GMjK <-- Worlds 

https://pastebin.com/EvxS5876 <-- Permissions

**Comment by LlmDl** [comment]
Wrong worlds file. I want the towny\data\worlds\WORLDNAME.txt

**Comment by LlmDl** [comment]
Remove all of the towny permission nodes from your permission plugin, except towny.admin for your admins

**Comment by Jeffrey073** [comment]
I have only this at the worlds folder, http://prntscr.com/q4s1i5

**Comment by LlmDl** [comment]
yeah choose the one that corresponds to the world you're testing in

**Comment by Jeffrey073** [comment]
https://pastebin.com/8RJSWeQk

**Comment by LlmDl** [comment]
what does towny show when you use /tw

**Comment by Jeffrey073** [comment]
> [00:09:05 INFO]: .oOo._______________.[ /townyworld ]._______________.oOo.
> [00:09:05 INFO]: /townyworld {world} : Current world's status
> [00:09:05 INFO]: /townyworld {world} [world] : Target worlds's status
> [00:09:05 INFO]: /townyworld {world} list : List all worlds
> [00:09:05 INFO]: /townyworld {world} toggle
> [00:09:05 INFO]: Admin: /townyworld {world} set [] .. []
> [00:09:05 INFO]: Admin: /townyworld {world} regen : Regenerate this chunk

**Comment by LlmDl** [comment]
can you show me what it looks like ingame

**Comment by Jeffrey073** [comment]
http://prntscr.com/q4s47e

**Comment by LlmDl** [comment]
No where  have you given the towny.wild.* permission node, and your world has build/destroy/switch/itemuse false.

The issue is that you don't want them build/destroy in the wild or that you do?

**Comment by Jeffrey073** [comment]
I want in the wild that nothing can be demolished or built up that it simply has to be claimed via town claim!

**Comment by LlmDl** [comment]
Then it should already be that way. Is that not the case?

**Comment by Jeffrey073** [comment]
You can just build and demolish in the wilderness and towns now, I don't think that's the intention, because those settings do not change anything in any way.

**Comment by LlmDl** [comment]
Start over with a bug report ticket and don't skip the form this time.
