### ISSUE TITLE
Flagwars don't work

### ISSUE THREAD

**Issue by elwolf6** [TownyAdvanced/Towny#3536]
### What steps will reproduce the problem?
1. Nation A has Nation B as an enemy
2. Both Nation B and Nation A has 1 member on, Nation B member is online and in the town Nation A wants to attack.

### What is the expected output?
1. A resident of Nation A who isn't an opplaces an oak fence at the border of Nation B and nothing happens.

### What is your Towny version?
0.95.1.8

### What is your spigot/craftbukkit version?
Paper 230

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/FeN02PPq
2. https://pastebin.com/tek8QF5b
3. https://pastebin.com/nKV12Wxj
4. no log error

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

@FlagCourier

**Comment by TheFlagCourier** [comment]
Not reproducible on my local machine. Hopping on the server to troubleshoot also came up with no clear solution. Seems to be a broken installation given the other errors experienced on said server.

**Comment by LlmDl** [comment]
Last time this was a thing for him one of the nations was peaceful/neutral. Neither nation file has been produced for the ticket.
