### ISSUE TITLE
Towny Wilderness, how to fix it?

### ISSUE THREAD

**Issue by Jeffrey073** [TownyAdvanced/Towny#3538]
### What steps will reproduce the problem?
1. Towny Wilderness build/break report
2.
3.

### What is the expected output?
1. I want to have wilderness build / demolish the current world config and other configs don't do it.
2.
3.

### What is your Towny version?
0.93.1.0 (for MC 1.8.9)

### What is your spigot/craftbukkit version?
1.8-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Server log: https://pastebin.com/mszLUTDZ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/b77SKGRi
3. Your townyperms.yml : https://pastebin.com/seuryP7c
4. Your log's error : https://pastebin.com/aJtwh2CH or https://pastebin.com/xbSMq793

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/54QkA535

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/VuYPZDJM
7. Your channels.yml : https://pastebin.com/hsEVBqnJ

**Comment by LlmDl** [comment]
In your other ticket it sounded like players could break in the wilderness, but you didn't want them to break in the wilderness.

In this ticket your expected output section says you want to have build/destroy in the wilderness.

Do you want players to use the wilderness?

**Comment by Jeffrey073** [comment]
I just don't want players to be able to demolish or place anything in the wilderness that's all I ask, otherwise it's just a top plugin!

**Comment by LlmDl** [comment]
Is it that they can break anything or only this list of blocks:

SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LOG_2,LEAVES,LEAVES_2,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,ACTIVATOR_RAIL,POWERED_RAIL,DETECTOR_RAIL,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,VINE,NETHER_WARTS,COCOA

**Comment by LlmDl** [comment]
Also: in your pex permission file remove all of the Towny nodes from the Speler group. Townyperms.yml already gives out what players need.

**Comment by Jeffrey073** [comment]
They can break anything in one way or another.

**Comment by Jeffrey073** [comment]
New version (permissions): https://pastebin.com/nQnwnCwF

**Comment by LlmDl** [comment]
Have a test using this copy: https://cdn.discordapp.com/attachments/388338495036456960/651044309323350036/Towny.jar

**Comment by Jeffrey073** [comment]
Yeah, it works! thanks for your help!
