### ISSUE TITLE
Add metadata improvements

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3539]
- Add new interface `Metadatable`
- Add collection container of `CustomDataField` types.

I’m planning on getting these implemented, just leaving this here so I remember.

**Comment by LlmDl** [comment]
This was done yes/no?

**Comment by suneettipirneni** [comment]
No it isn’t also can you unapprove my meta PR I’m doing another refactor.

**Comment by LlmDl** [comment]
For some reason when I made the above comment I'd thought I'd already accepted your PR. Just ask for another review when you've finished your refactor.

**Comment by suneettipirneni** [comment]
> For some reason when I made the above comment I'd thought I'd already accepted your PR. Just ask for another review when you've finished your refactor.

I thought you did? Lol
