### ISSUE TITLE
Towny Member Issue

### ISSUE THREAD

**Issue by itslukemango** [TownyAdvanced/Towny#3544]
Info:
SOME towny members type /t and see they're not in a town, but in /t (their town they were in prior to update) it shows they're in it?

### What steps will reproduce the problem?
1. Use Version 0.95.1.8
2. Have towns in MySQL with members in
3. Update to 0.95.2.0

### What is the expected output?
1. Members stay in their respective town

### What is your Towny version?
Do not say "latest".
Towny-0.95.2.0

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperMC 1.14.4 #233

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : yAGJvCrd
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/9dEcBCqU
3. Your townyperms.yml : https://pastebin.com/55JQsmjr
4. Your log's error : In startup log if there is one

**Comment by LlmDl** [comment]
is there an error shown when the player does /t

**Comment by itslukemango** [comment]
Nope, just says 
"eGirlPro issued server command: /t"

**Comment by LlmDl** [comment]
I can't reproduce this. Could you provide the exact commands the players are using as well as their town files, you can get a flatfile version of your mysql by using /ta mysqldump.

**Comment by itslukemango** [comment]
Sure, can I send you this privately anywhere?

**Comment by LlmDl** [comment]
either on the discord on or irc
