### ISSUE TITLE
Suggestion: Silencable nodes

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3545]
**Please explain your feature request to the best of your abilities:**
When you change channels, there are two different messages. 
[Towny] Modes set: Town
[Towny] [Townychat] You are now talking in Town

I only need one of these messages to show. How do I silence one?

**Comment by LlmDl** [comment]
I still need to know if that advance copy of 0.64 fixed this up.

**Comment by LlmDl** [comment]
Done as of https://github.com/TownyAdvanced/TownyChat/commit/802efbd3a72b8dd56487ae3cb77a83c6183f64bb and 0.64.
