### ISSUE TITLE
Question: I can't seem to find the .jar files

### ISSUE THREAD

**Issue by PackertKZ** [TownyAdvanced/Towny#3546]
If this is a full towny plugin (which I hope) I still can't find the .jar file after trying for awhile. I downloaded all the plugins, did the "Installation guide" and it's missing the .jar file, which the guide says it includes, please help!

**Comment by LlmDl** [comment]
Which version of MC do you use?

**Comment by PackertKZ** [comment]
1.14.*

**Comment by PackertKZ** [comment]
I might be dumb, but the .jar file isn't on the github?

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/releases/tag/0.95.2.0

the releases have files at the bottom of the release, in this case it is a .zip file because it contains the three files you need.
