### ISSUE TITLE
Suggestion: Update pom to spigot 1.15 and create new branch (if needed)

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3556]
Since 1.15 and all of it's API's are out a new 1.15 branch should be created in order to work on future versions of towny. Also since Towny is going to update on a major spigot release, the next major update should be 0.96.0.0, not 0.95.3.0.

**Comment by LlmDl** [comment]
I'll be doing this after a bit of testing. I want to see if a build made using 1.15 will run fine on a 1.14 server. If so we'll support both versions from master until that no longer works.

**Comment by LlmDl** [comment]
Initial tests look good.
