### ISSUE TITLE
Question: "already in channel x"

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3557]
If I'm already in tc for example, and I type tc again, it changes me to general. But in the english.yml, there's a line that says 

tc_you_are_already_in_channel: '[TownyChat] You are already in &f%s'

How do I make it send this message, instead of changing me to general?

**Comment by LlmDl** [comment]
I'll look into this but my guess is that you're basically telling the plugin that you want to leave tc, so it searches out the next global type channel.

The string you're talking about may be used when you are in tc and you use /tc somemessaghere, but I'll have to look into it.

**Comment by BeeRando** [comment]
If possible, this alternative system would be preferable. There are countless times where someone thinks they're changing channels, only to realize they were already in that channel, and now say something that's private in global chat for the entire server to hear. 

Preferred system:
/tc 
"You are already in town chat"
instead of: 
"now speaking in global"

**Comment by LlmDl** [comment]
This is now fixed as of 0.65, you can get an advanced copy here https://cdn.discordapp.com/attachments/388338495036456960/654453088673071115/TownyChat-0.65.jar
