### ISSUE TITLE
1.15 Spigot error "Could not pass event AsyncPlayerChatEvent to TownyChat v0.63"

### ISSUE THREAD

**Issue by elwolf6** [TownyAdvanced/Towny#3558]
### What steps will reproduce the problem?
1. Have server on paper 1.14
2. Switch to spigot 1.15
3. Launch server

### What is the expected output?
1. Towny chat works as normal and no error

### What is your Towny version?
0.95.1.8

### What is your spigot/craftbukkit version?
spigot 1.15

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
https://hastebin.com/odijejawuw.coffeescript
3. Your townyperms.yml :
https://hastebin.com/ukeroqisad.php
4. Your log's error : 
https://hastebin.com/oyawipesif.md
Look at like line 1710
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://hastebin.com/wefobubuqi.shell
7. Your channels.yml :
https://hastebin.com/awakicowiw.bash

**Comment by LlmDl** [comment]
Skipped startup on form

**Comment by LlmDl** [comment]
I see now you included it in the error link, this is cause your dynmap isnt updated for 1.15.
