### ISSUE TITLE
Exception while reading TownBlock file 

### ISSUE THREAD

**Issue by Lambsy** [TownyAdvanced/Towny#3560]
### What steps will reproduce the problem?
1. Start server with data from last run.
2.
3.

### What is the expected output?
1. No go into safe mode.
2.
3.

### What is your Towny version?
Towny version 0.95.1.0 for 1.13.2

### What is your spigot/craftbukkit version?
Paper version git-Paper-652 (MC: 1.13.2)

### Please use Pastebin.com to link the following files:

https://pastebin.com/S5UXyL09

The pastebin has a link two towny data folders, 1 that works (from backup) and 1 that doesn't and pastebin to startup log with error for Towny.

Settings: https://www.dropbox.com/s/623q2ywsfszsd2a/settings.zip?dl=0 (You can view on dropbox).

**Comment by LlmDl** [comment]
Your steps to reproduce do not include which version you used before. The steps you gave given do not work for the vast majority of servers.

**Comment by LlmDl** [comment]
This was caused by the OS' max open files limit.
