### ISSUE TITLE
Error with Updating (to 0.95.2.0)

### ISSUE THREAD

**Issue by scberends** [TownyAdvanced/Towny#3561]
I am trying to upgrade from 0.93.0.0 to 0.95.2.0 on my server. However it will go into safe mode on the 0.95.2.0, regardless of whatever backup I use. I purchased a secondary server to work on the issue. The exact same files that trigger safe mode in our primary server startup fine in our secondary server. The only thing I can think of is that our second server uses a different OS (Ubuntu) while we use CentOS on the primary server.

The safe mode is triggered due to Towny not being able to read the towny chunks. I have removed chunk after chunk based on the startup log for hours and there is no end. All of that is fairly trivial however as the exact same files work fine on a different source.

It should also be noted that before switching we have been dealing with numerous issues relating to issue #3247.

**Thanks for your time, and help is greatly appreciated.**

### What steps will reproduce the problem?
1. Run a server on CentOS using TownyAdvanced build w/ Towny version 0.93.0.0
2. Claim land (Should be stuck in processing as in issue #3247)
3. Update server to TownyAdvanced build w/ Towny version 0.95.2.0

### What is the expected output?
1. Server will trigger safe mode due to Townychunks.

### What is your Towny version?
Running 0.93.0.0, updating to 0.95.2.0

### What is your spigot/craftbukkit version?
Paperspigot; git-Paper-210 (MC: 1.14.4) 

### Please use Pastebin.com to link the following files:

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.
1. Your full server startup from the logs\latest.log: https://pastebin.com/vMp2RNu5
2. Your Towny config.yml: https://pastebin.com/mR6BFTyf
3. Your townyperms.yml: https://pastebin.com/3ZbNk9Ui
4. Your log's error: Triggered safe mode after it could not read Townychunk data.

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
This is probably due to your CentOS having a low max-files-open-setting.

**Comment by LlmDl** [comment]
Yep, you can see the other plugins afterwards throwing too many files open errors. If you google that you can find instructions on how to increase that value.
