### ISSUE TITLE
Some players not removed by towny purge. (also some towns removed only partially)

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3562]
### What steps will reproduce the problem?
1. Have a player over the purge time.
2. Run a purge, either manually or automatically
https://prnt.sc/qaipff -- results of /res on a player who should have been automatically purged, before and after running the manual /ta purge 150

https://prnt.sc/qaiqpg - /seen on that player

EXCEPT... it's not all my players, just some?  Towny did successfully purge quite a few...
3.
NOTE: I've sent mysql dumps of my towny tables to Siris

### What is the expected output?
1. All players over the time limit would be purged.
2.
3.

### What is your Towny version?
Do not say "latest".
0.95.1.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 236 (1.14.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/ZZ5PswNQ
Please ignore the error spam from LeaderHeads.. this is my test server and I was testing things, lol.  
The /ta purge command is run at line 1349 and there's a natural new day right after that.

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/xj326SbE
3. Your townyperms.yml : not relevant, but: https://pastebin.com/vKsKdNz6
4. Your log's error : 
No error for this part of this, though there is an error with the town database issues at the beginning: https://prnt.sc/qaiyu0

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by suneettipirneni** [comment]
I guess the most helpful file would be the resident file for this jake Paul guy

**Comment by LlmDl** [comment]
The /seen command from essentials is not where Towny pulls it's date from. We track last logins when a player logs off, their last-online-date/time is updated in the towny database, which is the only number Towny cares about for purges.

By my calculations the player logging off on August 2, was only gone for 133 days at the time of the ticket.

I'm not sure why Essentials didn't also see them when they logged in on the 2nd of August.

**Comment by Momshroom** [comment]
Thx.  Perhaps CMI was just messing up at the time or they weren’t on long
enough for it to notice them.   I didn’t do the math, just trusted /seen.
Sorry to bother you.

**Comment by LlmDl** [comment]
No worries, thanks for the ticket.
