### ISSUE TITLE
Towny chat overrides chat plugin

### ISSUE THREAD

**Issue by J3fftw1** [TownyAdvanced/Towny#3568]
### What steps will reproduce the problem?
1.install towny + chat +  a other chat plugin in my case essentials
2. set this config option to fasle `modify_chat:`  ` enable: 'false'`
3.restart the server towny still overrides chat plugin

### What is the expected output?
1. to not override
2.be disabled since that config option is to disable that chat format
3.

### What is your Towny version?
Do not say "latest".
Towny-0.95.2.0
TownyChat-0.63

### What is your spigot/craftbukkit version?
Do not say "latest".
v1_14_R1t

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hasteb.in/napejoge.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hasteb.in/amuzukoz.coffeescript
3. Your townyperms.yml : https://hasteb.in/ifatadon.yaml
4. Your log's error :  https://hasteb.in/odajomec.md

(optional) If this is to do with permissions, 
5. Your permissions file :N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://hasteb.in/qitupazi.shell
7. Your channels.yml : https://hasteb.in/behaleko.yaml

**Comment by LlmDl** [comment]
Fixed as of 0.65 https://github.com/TownyAdvanced/TownyChat/releases/tag/0.65
