### ISSUE TITLE
Suggestion: Add configurable list of blocks to ignore handling when ExplosionRegen is enabled

### ISSUE THREAD

**Issue by DalBrar** [TownyAdvanced/Towny#3569]
Currently based on the way the TownyBlockListener.onCreateExplosion() method handles explosions is that it tries to replace a container with air and then restores an empty container upon regen. This is fine and all that it prevents duping however the contents of the container is not dropped and the player loses all it's contents.

An easy fix to this would be to add a configurable list of block materials to ignore in that event and let vanilla explosion behavior take over.

Example (where containers list should be made a configurable list) would still allow server owners to have explosion regen on AND allow for containers to drop their items:
```
@EventHandler(priority=EventPriority.HIGH, ignoreCancelled=true)
public void onCreateExplosion(BlockExplodeEvent event)
{
  List<Material> containers = new ArrayList<Material>();
  containers.add(Material.BARREL);
  containers.add(Material.BLAST_FURNACE);
  containers.add(Material.BREWING_STAND);
  containers.add(Material.CHEST);
  containers.add(Material.DISPENSER);
  containers.add(Material.DROPPER);
  containers.add(Material.FURNACE);
  containers.add(Material.HOPPER);
  containers.add(Material.SHULKER_BOX);
  containers.add(Material.SMOKER);
  containers.add(Material.CHEST_MINECART);
  containers.add(Material.FURNACE_MINECART);
  containers.add(Material.HOPPER_MINECART);

  Material blockType = event.getBlock().getType();
  for (Material container : containers) {
	  if (blockType == container)
		  return;
  }
```

Adding that simple check at the beginning of the method eliminates handling any of the listed containers and prevents duping and etc whilst still regening everything else around.

**Comment by suneettipirneni** [comment]
I'll take this one

**Comment by ElgarL** [comment]
This should not be accepted as a solution. The correct fix is the correctly fill the container in https://github.com/TownyAdvanced/Towny/blob/e9f0cd2ff4a9092d34c442faa2d0e6a33e650375/src/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java#L60

**Comment by DalBrar** [comment]
I agree its not a good solution but I definitely think it'd be a nice feature to add incase someone wants to use it to increase difficulty or things like diamonds not respawning if exploded, etc...

**Comment by suneettipirneni** [comment]
@ElgarL @DalBrar agreed
