### ISSUE TITLE
Contents of containers being lost on explosion with ExplosionRegen enabled

### ISSUE THREAD

**Issue by DalBrar** [TownyAdvanced/Towny#3570]
### What steps will reproduce the problem?
1. Make sure ExplosionRegen is enabled in the config
2. Place a chest down
3. Place a bunch of items inside the chest
4. Stand next to the chest and spawn a creeper
5. When the chest explodes, no contents is dropped. When the chest regens it is empty

### What is the expected output?
5. When the chest explodes, the contents of the chest is dropped on the ground and the chest regens as empty. 

### What is your Towny version?
Towny-0.95.2.1

### What is your spigot/craftbukkit version?
git-Paper-235 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. no errors in log to report.
2. default config with     wild_revert_on_mob_explosion: enabled: 'true'
3. default
4. no errors outputted to console

### Possible solution submitted:
https://github.com/TownyAdvanced/Towny/issues/3569

**Comment by ElgarL** [comment]
What should happen is the chest respawns WITH its contents. I remember it breaking a long time ago and I remember taking a look at it but I guess I never fixed it.
Its been far too many years now for me to remember the code. I hope Llmdl is up to this one ;)

**Comment by ElgarL** [comment]
I've looked a little at this and the bug is in https://github.com/TownyAdvanced/Towny/blob/e9f0cd2ff4a9092d34c442faa2d0e6a33e650375/src/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java#L60
the method is no longer putting the contents back in the container.

**Comment by LlmDl** [comment]
Still have a hang-up on doublechests.

**Comment by ElgarL** [comment]
You will probably have to add each item instead of just setting the contents. Double chests merge when placed and setting will probably wipe out the first half.

**Comment by LlmDl** [comment]
Fixed it with https://github.com/TownyAdvanced/Towny/commit/64147a642898cc38bda142d6a7d8ac462370b67b

**Comment by DalBrar** [comment]
So this problem also exists with Spawners.... if a spawner block gets exploded, it regens as a pig spawner.

**Comment by LlmDl** [comment]
new ticket please @DalBrar
