### ISSUE TITLE
Question: How to export this project

### ISSUE THREAD

**Issue by racer122** [TownyAdvanced/Towny#3579]
Hello, i've a question about how do i need to export this project. Cause i got the whole time invalid plugin.yml.

**Comment by LlmDl** [comment]
what do you mean by export?

**Comment by racer122** [comment]
build an artifact make it into a jar

**Comment by LlmDl** [comment]
you dont need to build it yourself all the versions' jars are linked in the readme: https://github.com/TownyAdvanced/Towny#current-recommended-versions
