### ISSUE TITLE
Pillager can't harm villager

### ISSUE THREAD

**Issue by yumjunstar** [TownyAdvanced/Towny#3580]
### What steps will reproduce the problem?
1. Just install Towny-0.95.2.1.jar , TownyChat-0.63.jar, TownyNameUpdater-4.0.jar and Vault.jar
2. And spawn Pillager with spawnegg and Villager next to it
3. Wait untill pillager attack villager

### What is the expected output?
1. Pillager can't harm villager (reflect arrow) but zombie can attack villager 
???

### What is your Towny version?
0.95.2.1

### What is your spigot/craftbukkit version?
Paper Spigot 1.15.1 paper-26

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/rojasuxuwe.sql
2. Your Towny config.yml (if using MySQL please remove password,) :
Just default I didn't change any setting
3. Your townyperms.yml 
Just default I didn't change any setting
4. Your log's error : 
There is no error
(optional) If this is to do with permissions, 
5. Your permissions file :
there is no permission node

(optional) If this is to do with chat,
6. Your chatconfig.yml :
Just default I didn't change anything
7. Your channels.yml :
Just default I didn't change anything

![2019-12-25_14 02 32](https://user-images.githubusercontent.com/24960675/71440142-9ede1980-273f-11ea-8fa0-2902f1e8ae73.png)

**Comment by LlmDl** [comment]
I am a bit confused about the expected output you describe?

Can you be a bit more thorough in explaining what is happening and what should be happening?

**Comment by yumjunstar** [comment]
> I am a bit confused about the expected output you describe?
> 
> Can you be a bit more thorough in explaining what is happening and what should be happening?

I'm sorry my bad english. english is not my native language.
Pillager can't attack villager with crossbow

**Comment by yumjunstar** [comment]
t

> I am a bit confused about the expected output you describe?
> 
> Can you be a bit more thorough in explaining what is happening and what should be happening?

Even raid mode

**Comment by LlmDl** [comment]
So you think the pillager should be able to hurt the villager just like the villager is already able to be hurt by the zombie?
You want:
```
Zombie hurts villager: yes
Pillager hurts villager: yes
```
but you are seeing :
```
Zombie hurts villager: yes
Pillager hurts villager: no
```

**Comment by LlmDl** [comment]
This will be a part of 0.95.2.5
