### ISSUE TITLE
Question: can someone write me a mini-script

### ISSUE THREAD

**Issue by 3meraldK** [TownyAdvanced/Towny#3581]
**Ask your question as best as you are able:**
can someone write me script

`on chat:`
`....if player's towny channel is general:`
`........send "your current channel is general"`
`....else:`
`........send "your current channel isn't general"`

like this
i am sure skript-mirror is required but please list me jar(plugins) files i need to extract to skript-mirror folder

**Comment by LlmDl** [comment]
Doesn't look like anyone is wanting to do this, sorry.
