### ISSUE TITLE
Daily Upkeep and Taxes Not Collecting

### ISSUE THREAD

**Issue by HuskerFan34** [TownyAdvanced/Towny#3582]
Towny version: 0.95.0.0
Economy plugin: Essentials 2.17.1.11
Vault installed

Towny config: https://pastebin.com/167eHYPM
Towny perms: https://pastebin.com/Wg5LhdKT

Upkeep has not been collecting for over a week by the time I noticed it. /townyadmin newday does not force upkeep/tax collection. All other towny economics are working such as money being subtracted from town banks after claiming new plots or outposts and adding money with /t deposit.

**Comment by LlmDl** [comment]
This isn't a question. Re-file as a bug ticket. Don't skip the form.
