### ISSUE TITLE
Suggestion: Prevent Town Creation via Worldguard Flags

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3584]
**Please explain your feature request to the best of your abilities:**
Many people including myself, use both worldguard and towny on the same server as both have different ways of dealing with protection. Many people have been asking how to protect spawn, and currently the answer to this is to create an npc spawn town. This solution seems a bit clunky, considering that you have to claim the townblocks and create a town just for the purposes of protection. This offers a lower level of precision for selections (chunk by chunk), rather than (point by point).

So to solve this we should integrate into worldguard flags via a soft dependency. This flag will hook into regions and tell whether town creation is allowed or not. If a player tries to create a town in the protected region towny will check if they are in a region and check the if the town creating flag is true if not the town event creation will be cancelled.

**Comment by LlmDl** [comment]
I was thinking of just making a bridge plugin for this, so that Towny doesn't need the dependency in it directly. We've already got an cancellable pre-claim event that is used for this.

**Comment by suneettipirneni** [comment]
Yeah the plugin can register the flag and then listen for the town creation event and then decide to cancel or not

**Comment by bartyrealms** [comment]
This would be very useful. Currently I just deny the '/town claim' command using WorldGuard, but this is not ideal.

**Comment by suneettipirneni** [comment]
Closed, refer to https://github.com/TownyAdvanced/WorldGuard-Towny/releases
