### ISSUE TITLE
Daily Upkeep and Taxes Not Collecting

### ISSUE THREAD

**Issue by HuskerFan34** [TownyAdvanced/Towny#3586]
### What steps will reproduce the problem?
1. New day arrives or executing /townyadmin newday

### What is the expected output?
1. Upkeep is subtracted from town/nation banks
2. Taxes are added to town/nation banks
3.  Towns/Nations with insufficient funds fall
4. Players with insufficient funds in towns with flat tax rates are kicked

### What is your Towny version?
0.95.0.0

### What is your spigot/craftbukkit version?
1.14.4 paper-234

1. Your full server startup from the logs\latest.log : https://pastebin.com/5iepG1JQ
2. Your Towny config.yml : https://pastebin.com/167eHYPM
3. Your townyperms.yml : https://pastebin.com/Wg5LhdKT
4. Your log's error : N/A - Town/Nation banks simply don't change

Economy plugin: Essentials 2.17.1.11
Vault installed

All other towny economics are working such as money being subtracted from town banks after claiming new plots/outposts and adding money with /t deposit.

**Comment by LlmDl** [comment]
In your config you have daily_taxes turned off:
```
  daily_taxes:
   # Enables taxes to be collected daily by town/nation
    # If a town can't pay it's tax then it is kicked from the nation.
    # if a resident can't pay his plot tax he loses his plot.
    # if a resident can't pay his town tax then he is kicked from the town.
    # if a town or nation fails to pay it's upkeep it is deleted.
    enabled: 'false'
```
