### ISSUE TITLE
Suggestion: add negative per-plot-upkeep

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3588]
**Please explain your feature request to the best of your abilities:**

Allow the upkeep for towns in the config to be negative, meaning instead of paying say, $10/chunk the town owns, as its upkeep cost, it can get paid $10/chunk it owns. 

the town with 10 chunks will now get $100/day. 

I suggest this feature because I have the idea to incentivize people to make huge claims on our server via a variety of ways, and nations have huge upkeep cost. So this incentivizes people to constantly spend their money as a way to non-stop grind and invest in the server to claim as much land as possible, and get paid a small amount over time.

**Comment by Goosius1** [comment]
Hi.
A few questions to help this along:

1. Leaving aside incentives for a minute, just to clarify the end goal here - is it that you want towns/nations to own large amounts of unused land?

Or is the goal that you want to offer an additional 'grind' option to players, where if they claim land they get a small bonus?

**Comment by BeeRando** [comment]
q1. Kind of. On my server, i heavily incentivize people owning more land. Owning more land makes people build more. People build temples, spread out towns and cities, etc. Some of it is unused, yes. People may claim land just for the sake of getting more revenue in the long run. But as far as my server goes at least, the more land people have, the more they build. Incentivizing people to spend their money on land increases the grind for money in the first place, which increases the overall grind of the server.

q2. Yes, this also. Some people will claim land just to get a bonus. So it goes both ways. 

Overall though, giving people a reward to claim land would increase the drive to claim land. Some people are rich and don't have a reason to claim land. Sometimes people don't even know why they want money or what they plan to do with it. They just want it. This will encourage people who love to build to claim more land and build more, something they already want to do, and those who want money to play more and invest more time and energy into the server to claim land as it becomes another source of revenue. Overall, I think it just motivates everyone to play more, which is the main goal. Builders are happy, economy people are happy.

**Comment by Goosius1** [comment]
Hi.

Just getting my head around this one🤗🤑🙃

Well, it is very interesting because it fundamentally changes towny land claims, from being a source of cost to a source of profit.

An important thing to work out is ..... what happens to town upkeep?, because upkeep currently works on the basis that claims are a cost.

If upkeep is gone, that might be ok, but just to clarify.....

**Comment by LlmDl** [comment]
This is just an extension of what we already allow for non-plot-based-upkeep.

If you have plot-based-upkeep: false, and use a negative amount for upkeep, towns gain that money.

@BeeRando is just asking for it to work on plot-based-upkeep: true servers.

**Comment by Goosius1** [comment]
Oh good, probably much less to worry about in that case.

**Comment by BeeRando** [comment]
Ya. So basically if the upkeep is based on the amount of chunks a town owns, and each chunk upkeep is negative 10, then that means a town with ten chunks claimed would be given $100 a day, instead of pay $100 a day. If it had 50 chunks claimed, it would make $500 a day, not pay $500 a day. The more land the town claims, the more money it will make over time.

**Comment by Goosius1** [comment]
Ok. Btw does this idea of tie into the town/nation interest rate?

E.g if the town money were to increase by a certain % per day, would this be appealing even by itself because it makes more money?

**Comment by BeeRando** [comment]
This is nothing to do with banks. This is simply making it so if you claim land, you get paid revenue from owning that land.

This is a wholey separate idea. Not promoting nor downplaying the separate bank idea post. This is simply being able to put a - infront of the upkeep cost, so a town gets paid per chunk, instead of spending money per chunk.

This is what it would look like in the existing config.

    # The server's daily charge on each town. If a town fails to pay this upkeep
    # all of it's residents are kicked and the town is removed.
    price_town_upkeep: '0.0'
    # Uses total amount of owned plots to determine upkeep instead of the town level (Number of residents)
    # calculated by (number of claimed plots X price_town_upkeep).
    town_plotbased_upkeep: 'true'
    # If set to true, the plot-based-upkeep system will be modified by the Town Levels' upkeep modifiers.
    town_plotbased_upkeep_affected_by_town_level_modifier: 'false'
    # If set to any amount over zero, if a town's plot-based upkeep totals less than this value, the town will pay the minimum instead.
    town_plotbased_upkeep_minimum_amount: '-10.0' 

At the end, for Town_plotbased_upkeep_minimum_amount: instead of being '10.0', which means every chunk increases the daily upkeep by $10, each chunk owned now gives the town $10. It's just the ability to put "-" infront of the upkeep cost, so a town gets paid money per chunk, instead of spending it.

**Comment by LlmDl** [comment]
Using the town_plotbased_upkeep_minimum_amount would only override the price_town_upkeep if their upkeep did not exceed the min amount. Just like it does for positive amount.

**Comment by BeeRando** [comment]
Oh my bad. Well you still get the idea I'm going for right? The ability to be paid per chunk each new day instead of pay for each chunk.

**Comment by LlmDl** [comment]
As far as I can tell this is actually already a thing. Please test and let us know.

**Comment by BeeRando** [comment]
How exactly do I go about doing that then? Making a town get paid per chunk it owns instead of paying per chunk.

**Comment by LlmDl** [comment]
I think we covered this on the discord and you said that it was indeed working.

**Comment by BeeRando** [comment]
Yup! It works I believe. When doing /t, it shows a negative value for upkeep, which I believe will pay everyone tomorrow.
