### ISSUE TITLE
Suggestion: Add daily interest to town and nation banks.

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3590]
**Please explain your feature request to the best of your abilities:**

Incentivize people to trust and hand over their money to towns/nations. This could greatly increase server politics. 

An option in the config to add a % increase to a town and a nation's bank amount. Disabled by default. For example:

#This is the percentage that the towns bank amount will increase on each new day
"Town bank interest amount: 0.1"
#This is the percentage that the nation's bank amount will increase on each new day.
"Nation bank interest amount: 1.0"

**Extra Advanced Features**
Even further, perhaps there could be a way for a town/nation to upgrade this? I can think of two main ways. 

1) Firstly, is below the upkeep modifiers for each town/nation in the config. So a town with 10 people gets 0.1%, a town with 20 people gets 0.2%, etc. So it'd be configurable based on the size of the town in the config.

2) Secondly, another idea would be that the town/nation pays to upgrade. For example, /t bank upgrade 1, would upgrade the bank's interest by 0.1, doing /t bank upgrade 5, would upgrade the bank's interest by 0.5.

This would operate just like /t buy bonus. It can either be A) a flat configured price, or B) an increasing price. 

Also, a max interest rate for towns/nations could be set. So in the config, the max interest rate for a town can be 0.5, and the max interest rate for a nation can be 1.0

**Comment by Goosius1** [comment]
Hi.

Some thoughts to help this along:

This is very interesting!. This fundamentally changes the towny banking model.

Theres a lot of complexity required by a centralized town bank - E.g is loaning allowed?, how much can be withdrawn per day? what will the rates be for saving and loaning?, can the rates be changed to compete with other banks?, how much is allowed to loaned?, should big savers be given incentives or bonuses?  What will the capital base be? Which players have which roles in the bank?

Given all this, I suspect this design path may inevitably lead to the feature of a  "player managed banking system".

With this feature, not only would a banking town manage saving and loans for their own residents, but successful and skilled banking towns would doubtless be motivated AND requested to manage money for other towns too, and Nations.

So, in terms of implementation, once we switch from trying to automate everything, to facilitating players who wish to operate in a banking role, the implementation becomes a loooot easier.

....e.g rates could be manually adjusted by player bank admins, who also make loan decisions and manually deal with all the other fun bank processes etc.

**Comment by Goosius1** [comment]
A last thought to add to the above:
1. This idea of a 'bank organization' could also work well as a separate organization to towns.
2. This would allow such a system to be popular even in servers without towny.
3. Towny already outsources money management to a certain degree technically.
4. Thus --- is there an argument that this feature would be more effective as an external plugin which could be plugged in to towny servers?

**Comment by BeeRando** [comment]
I think some of your suggestions are really interesting. It could be a separate plugin. I think though that it'd receive the most attention and support, and evolve the most in the long run if it became one of the features of towny its self, rather than having people download an external plugin to use it. It might also be more work as an external plugin, because one of the goals of that is now to work with all other plugins banks, like the various types of factions plugins, kingdoms, etc. Simply being part of towny, and done well, will only give even more reason to download towny, and make it more unique. 

Here's to answer specifically some of your questions with my thoughts. 

1) Loaning: I think loaning shouldn't be plugin based. Being player based is what makes money transactions interesting. There's always a chance someone won't pay you back. Won't pay you back on time, or how much you're owed. That's one of the risks of being a loan shark. The reward of doing it successfully is that you make a lot of money in the end. If it's a guaranteed payback, it just begs the question of why doesn't everyone just give out loans. Also, these risks add to player interactions on the server. It can diversify politics, lead to wars, etc. It also simply means less to code, less to figure out for code (like what if someone gets a loan and never logs back online? Or simply gets loans from everyone and never gets the money to pay back and just stays broke?) and less for the player to learn, not implementing a loan system. Loans will still be done, but by players, at player risk, which is what will lead to skilled bankers. If the entire server can be a banker with 0 risk by simply doing this via a loan command, I feel like that devalues the whole system. I'm also biased though, as I've ran banks on servers and been a loan shark, and competed with other player ran banks, on faction servers. But in summary, don't code a loan system, players who are skilled can do that just fine on their own. Perhaps I need more explanation on how the plugin side of a loan system would work. 

1. Part two. I spent more time thinking about it. Here are my plugin thoughts. Remember, this can simply be done by just letting players take risks in giving out loans. BUT, if loans become a plugin thing, this is how they should be done imo. 

If done via plugin, multiple things are needed
Scenario: 
A) Flat fee-based
 ./t loan BeeRando 500 600
This means I loan beerando 500, to be paid back 600. 
The person needs to accept/deny this loan offer.

B) Percentage based
 .t loan beerando 500 %5
This means I loan BeeRando 500, with a 5% interest.
Every new day, 5% is added onto the $500.
So, today I run /t loan pay Bob 100. This means I pay back bob 100 of my 500 $. A new day hitsd (24h) 5% is added onto the original $500 loan. So now I owe instead of just 400, I owe $425. I pay another 100 today. A new day hits. instead of just owing 325, I now owe 350. And the interest continues to add 5% to the original price each day until the full amount is paid. 

Now, to expand on thsi even further, the full command could be
/t loan beerando 500 5% initial 50

That 50 on the end means that no matter what, the plugin will automatically take 50 from the persons wallet every day. So even if I don't manually type ./t loan pay bob 100, I will still be deducted 50$ from my wallet. 

Full option: /t loan name amount [% or flat number] [Initial or remaining] auto 

Things that would need to be considered/coded, if a loan system was coded. I'll just pretend this is a config, so its easiest.

#Max loan amount. Set to 0 for no max loan
Max_Loan: 0
#Min loan amount. Set to 0 for no min loan.
Min_Loan: 0
#Max loan auto pay per 24h. This will automatically take money from the loaned person's wallet each day to pay back the loan. This amount is set by the player giving out the loan. This is the maximum that auto pay can be set to by the player.
Max_loan_autopay: 50
#This is the maximum percentage amount a player can set when making a loan for someone. 1.0 is 100%, 0.5 is 50%, and 0.05 is 5%. If a loan is set to $1,000, and the loan percentage is at 0.05, then each 24h, the loan will increase by 0.05% off the initial amount. Meaning it will be increased by $50 each 24h that the loan exists.
Max_loan_percentage: 0.05
#Max remaining unpaid loan. This is the maximum amount someone can set for a remaining unpaid loan setting.
Max_Remaining_loan_percentage: 0.05
#Can a player break a loan? This means a player can type /t loan break bob. A player can do this, and break their loan with a player, essentially meaning they refuse to repay the loan. This can be abused and can mean a player can take a loan from someone and instantly break the repayment agreement.
Breaking_loans: True
#enable loan history? This would show the loans someones made, and how long it took them to repay them. It also shows if the person fully paid the loan, or broke it. /t loanhistory name. 
#permission: towny.loan.history (for self), towny.loan.history.other (to view others historys)
Loan_history: True/false
#Failure to pay loan commands. This is a list of commands that would be run if the player is unable to pay back a loan via auto pay
Auto_pay_failure_commands:
 - 
#list of commands to be ran if a player breaks an agreement, refusing to pay back the loan. Requires breaking_loans to be set to true.
Breaking_loans_commands:
 - 
#list of commands to be ran when a player finishes paying out their loan.
Loan_Payment_complete_commands:
 - 

There may be more, but this is what I thought of would be needed while sitting here typing this.

**Comment by Goosius1** [comment]
Hi.
Ok great, I understand your motivations a bit more now.

--- On Loaning ----
* I very much agree with your initial bias for a player based system !
* As for plugin code support for the system, perhaps I was unclear with what I was getting at.
I was suggesting that plugin code should be there only for the purpose of 'supporting' the player based system e.g. information screens to see who has accounts with your bank,  information screens on your current saving/loaning rates, ability to change your basic rate values in-game,  records of transactions etc.
* All the complex operation limits you noted could still be supported with code, but I suggest to support them by allowing the individual banker players to modify any available limits in game, for their own bank only,

--- On Bank Organisation ----
* Regardless of where the plugin code lives, the idea of a 'bank' separate to a town, might be useful.
* This has a few advantages:
1. A bank would have a lot more flexibility with responding to world events.  For example,  if the local town was attacked or became involved in a war, the bank could move to a safer town.  
2. A bank would have a lot more flexibility as to who is running the bank.  Thus you could have residents from different towns and nations.
3. There would be less confusion with the town administration,  who might wish to have a 'town account' as today, but would often be concerned with other things such as building projects, law and order, and warfare. 

--- On Location of Plugin code ---
* I totally understand what you mean about towny assistance and support ! 
* Lets look at what is required in each scenario:
1. Towny native support:
Going with the separate bank organisation idea, this would required a new towny object.  So you would have: Town, Nation, Resident, Bank etc. Then you would need command support "/b <bank command", and other coded rules and processes etc. etc.
2. New standalone plugin:
Going with this idea, you would need to code up support for the Bank organisation, ranks, bank commands, and other support. The basic money handling should be easy enough. Just connect with the "vault" plugin and then you can do thing like: vaultEconomy.depositPlayer(...)
3. Build onto existing economy plugin
Here's something I just thought of!. There are already many economy plugins available (such as "The New Economy/TNE" which is regularly recommended on discord towny support).  A towny server does not actually manage money itself, but rather offloads this responsibility to one of these plugins. If you want to build onto an existing plugin, rather than create one yourself, this could be an option.

**Comment by BeeRando** [comment]
I like these ideas. To start, it depends on how in-depth you want to get with this. Don't forget one of my original ideas was to simply add an interest option in the config for towns/nations. That'd probably be super fast to code and is just two set options in the config. I think that option should be added regardless of any of the rest, due to its simplicity and ease.

For the separate bank idea, I like this. Originally I wanted it to only be run by a town. However it still basically is, just like how a nation still has a capital. For the bank, as you said, it'd be /b new name. So you could do /b new IronBank, for example, like from Game of Thrones. You've now created a bank. You can do /b, or others can do /b ironbank, to view it. on my server, I had this idea of having a physical bank people went to that had admin shops. If someone went through the effort to build a nice big bank on their town, then a staff member would put in the admin signs. I like the idea of promoting people building physical banks. Which would also play in with the capital idea, and perhaps even offer an option to be a different colour on the dynmap, say, purple? With a $ icon. The reason you'd have chunks claimed for a physical bank, is that perhaps you could only do money deposits/withdrawals from the claimed bank chunks, like the existing option within towny for towns/nations. 

Some viewed page info
 - Time made
 - Money
 - Capital
 - Owner
 - Members

Dynmap
 - Purple chunks
 - $ icon, or some kind of bank looking icon

Capital 
 - Claim chunks for a bank
 - Chunks cant be claimed from the wilderness.
 - Chunks can only be purchased from an embassy plot from someone, forcing banks to actually exist within towns
 - Can only deposit/withdraw money from the bank chunks
 - Can /b home, to the banks home

Total commands I can think of
 - /b new name
 - /b view (name)
 - /b invite name
 - /b kick name
 - /b deposit
 - /b withdraw
 - /b claim
 - /b unclaim
 - /b sethome
 - /b home (name)
 - /b toggle public
(and whatever loan commands there are, if added)
 - /b loan(if we're doing


(number prices are just made up and not assumed to reflect each other)
Some config options I can think of

#Can money be withdrawn from anywhere? Set to false, to only allow money actions on land owned by the bank. Recommended false.
Transaction_anywhere: false
#Can the bank claim wilderness land, or only purchase embassy plots? Recommended false.
Wilderness_claim: false
#Is bank home command enabled? This will enable bank members to /b home
Bank_Home: True
#Can anyone teleport to the home of a public bank? With /b home name?
Bank_home_anyone: False
#cost of creating a bank
Bank_creation_cost: 500.00
#Bank rename cost
Bank_rename_cost: 500.00
#allow bank outposts? This will enable disconnected claims in more than one town.
Bank_Outposts: true
#Should the amount of power a bank has to claim land be a set number, or based on member? Options are either set, or player.
Power base: Set
#Amount of power each person adds to a bank
Bank_Player_Power: 1
#Set number of power a bank has
Bank_Set_Amount: 4
#can a bank buy bonus power?
Bank_Bonus_Power: True
#Cost of bonus power
Bank_Bonus_power_Cost: 100.0
#Max bonus power allowed
Max_Bank_Bonus_power: 10
#Maximum amount of members allowed to join a bank
Bank_Member_limit: 5
#Number of outposts allowed
Bank_Outpost_Limit: 3
#Can a bank buy more outposts?
Bank_buy_bonus_outpost: true
#cost of buying additional bonus outposts
Bank_buy_bonus_outpost: 100.00
#bank upkeep cost
Bank_upkeep: 100.00
#bank upkeep outpost modifier. This will increase the upkeep with each outpost owned.
Bank_outpost_upkeep: 100.00
#bank taxes. this is the maximum tax amount a bank can set on its members
Bank_Taxes: 100.00, 
(all the other tax options you guys have)

The bank should only be able to establish more land in other towns by having outposts. This means the bankers can have many tp points, but due to such small limited number of people allowed within a bank, and presumably a high upkeep cost, it shouldnt be too abusable. 

People can only be a member of one bank.

**Comment by LlmDl** [comment]
You can already limit transactions to bank plots fyi. If you have Towny-TNE and use TNE you can also limit transforming bank notes into virtual currency to bank plots.

**Comment by Goosius1** [comment]
Wow this idea is really coming along !!!

It looks like you have a really solid design now for the "full bank organization" idea, and it looks good to me.

So turning my attention now just to the "banking-lite" idea e.g. how can towny banking get up and running with a minimum of code tweaks ?

Well, consider how irl banks work.... their method of making money is *not* via printing a certain amount of extra notes per day (which is comparable to a towny plugin percent setting which increases wealth).

I believe this diagram lays it out:
![bank-income](https://user-images.githubusercontent.com/50219223/71561113-21314b00-2a6a-11ea-949d-bfee78f9e95d.gif)

So....could that work for "towny-banking-lite"?
As in, with no tweaks to code, could a player set up an informal towny bank today, and proceed to operate as a bank in a normal way concerning the fundamentals, by charging interest to loaners, giving interest to savers, and making a profit on the difference ?

**Comment by BeeRando** [comment]
FYI I know nothing about coding btw lmao, so I dont know how easy/difficult any of this is to do, nor can I do any of this myself. I'm only able to come up with ideas and all the options that would probably be needed.

For the banking lite thing, yes, banks make money via interest. I think what you're asking, is it possible for a player to run a bank with out any code changes? If so, yes, I've done that on servers before myself. I usually am very successful on economy servers. I give out someone a loan, and expect them to pay it back with interest. If they don't do this, I go/have people go kill and harass them until they do, or impose other punishments, like get their members to leave their town, get their nation or empire to kick them, get people to not ally them, etc. There are many ways players impose punishments on each other in ways that plugins simply cant. 

All of this is already possible and done by select players on servers. I've done it myself for years on various servers. 

The reason I suggest the increase in wealth is because it's simple and motivates people more to hand over their money to other people, and motivates people who have never been in a banking position to suddenly pursue banking positions. 

I think this answers your question?

**Comment by BeeRando** [comment]
"You can already limit transactions to bank plots fyi. If you have Towny-TNE and use TNE you can also limit transforming bank notes into virtual currency to bank plots."

Ya, thats what I was referencing. For the new bank though, the one created with /b new name, that's what I was talking about, not the default towny banks that towns have. The formal banks that would be created would be limited to doing transactions on their claimed chunks.

**Comment by Goosius1** [comment]
Re the contribution of town wealth generation to banking-lite,

Yes, I get it now thanks!.

I'm a little worried about how the new money would affect the economy. Other than that, no issues.

Just for fun, consider this somwhat evil alternative😈

....instead of leaving the resident money the same while increasing the town money

....how about *decreasing* the resident money while leaving the town money the same.

This would both act as a new type of money sink, easing eco overheating fears,
and I dare say could even more strongly motivate those players to invest in the town😁

**Comment by Goosius1** [comment]
Just to add to that last idea, the coding *could* be simple enough that support could be added for resident/town/nation wealth gain/loss, all in one go, giving max flexibility.

**Comment by BeeRando** [comment]
Ohhhh so each new day, for example, peoples wallets may decrease by like say 1%? This motivates them to put their money in the bank. Its so dirty. I love it 😈

If it can be done all at once though, the option to increase/decrease for resident/town/nation, thatd be amazing.

**Comment by Goosius1** [comment]
Moohooohahahaaaa😈

**Comment by Goosius1** [comment]
@BeeRando Hi, I believe it would be worth splitting this ticket into 2 tickets at this point e.g.

Ticket 1 - Changes to upkeep-by-percentage for resident/town/nation

Ticket 2 - Add bank organisation

**Comment by BeeRando** [comment]
Yes, I'll fully make the two tickets shortly. I'm binging stuff right now with people. 

Should the bank ticket include the loan stuff i layed out earlier, or would a loan system be a third ticket?

**Comment by Goosius1** [comment]
Perhaps specify that inside the bank ticket for now, at least so the end picture of a full banking support system can be viewed all together.
