### ISSUE TITLE
PVP and splash potion

### ISSUE THREAD

**Issue by Mitsu13Ion** [TownyAdvanced/Towny#3592]
### What steps will reproduce the problem?
1. Have Towny
2. splash damage potion on any one in no pvp town
3.

### What is the expected output?
1. potions can be used despite the disabled pvp
2. potions not work if town is no pvp
3.

### What is your Towny version?
0.95.2.2 for 1.14.*/1.15.*

### What is your spigot/craftbukkit version?
Paper 226

2. Your Towny config.yml : https://pastebin.com/3sqtHnZg

**Comment by LlmDl** [comment]
Skipped form. Try again.
