### ISSUE TITLE
PVP and splash potion

### ISSUE THREAD

**Issue by Mitsu13Ion** [TownyAdvanced/Towny#3593]
### What steps will reproduce the problem?
1. use a splash damage potion on any one in no pvp town
2. the player can be kill in no pvp town

### What is the expected output?
1. the potion doesn't do any damage

### What is your Towny version?
0.95.2.2

### What is your spigot/craftbukkit version?
Paper 226

1. Your full server startup from the logs\latest.log : https://pastebin.com/SRsicVtc
2. Your Towny config.yml : https://pastebin.com/3sqtHnZg
3. Your townyperms.yml : https://pastebin.com/6jLnDRcm
4. Your log's error : No error

**Comment by LlmDl** [comment]
I've just tested this and could not reproduce it. If your world is set to have forcepvp true it will override the town's pvp setting. If you don't have PVP forced on in the world then it is likely another plugin interfering.
