### ISSUE TITLE
Flag war bug/question? Unable to place war flags

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3594]
### What steps will reproduce the problem?
I'm unable to place war flags on en enemy nations towns claim. I'm trying to place it on the outer most chunk. The plot is a default regular plot. Both nations are enemies to eachother. I am not opped. I've never used war flags before, this is my first time trying it, so im possibly doing something wrong. 

### What is your Towny version?
Do not say "latest".
0.95.1.8

### What is your spigot/craftbukkit version?
Do not say "latest".
https://imgur.com/a/hu1Zdcr

1. Your full server startup from the logs\latest.log :

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/B9geUYW7
3. Your townyperms.yml :
https://pastebin.com/JEvmiCR5
4. Your log's error : 
none
5. Your permissions file :
https://pastebin.com/8vm0Q6P8

**Comment by TheFlagCourier** [comment]
@BeeRando Try replacing the base block 'fence' with 'oak_fence'. Should solve the problem almost immediately.
