### ISSUE TITLE
Suggestion: Vertically Sectioned Plots

### ISSUE THREAD

**Issue by Cryolophysis** [TownyAdvanced/Towny#3595]
**Please explain your feature request to the best of your abilities:**

So we can customize how wide plots can be with a default of 16, but I didn't see an area in the config to customize how tall a plot can be. I assume it is much easier to just have it fill the world from bottom to top and likely less laggy too, but for high-rise condos and flats this can prove to be rather insecure to individual belongings and spaces.

It would be great, for plot owners, to have the ability to sell off specified vertical sections of their plot. It could be customized by the plot owner for how high the section goes from the block that the owner is standing on. This section could then be sold off to another player almost as if it were a regular plot. The previous owner does not have ownership of the plot after it is sold.

**Comment by LlmDl** [comment]
This has never been added because the way Towny is able to cache player data/permissions per-plot. Sorry, this will probably never be added to Towny,
