### ISSUE TITLE
Keep inventory on death doesnt work

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3596]
Keep xp on death in claimed land works but inv doesnt work. 
Possibly conflicts with combatlogx or CMI?

What is your Towny version?
Do not say "latest".
0.95.1.8

What is your spigot/craftbukkit version?
Do not say "latest".
https://imgur.com/a/hu1Zdcr

Your full server startup from the logs\latest.log :

Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/B9geUYW7

Your townyperms.yml :
https://pastebin.com/JEvmiCR5

Your log's error :
none

Your permissions file :
https://pastebin.com/8vm0Q6P8

**Comment by LlmDl** [comment]
Already fixed as of 0.95.2.1
