### ISSUE TITLE
Console spammed with Error: PlotBlockData:restoreNextBlock()

### ISSUE THREAD

**Issue by Klawdek** [TownyAdvanced/Towny#3599]
### What steps will reproduce the problem?
1. Not sure the error just started happening for no apparent reason.
2. The error seems to happen mostly when towny commands such as list and t spawn townname are used but the seem to happen on their own as well.
3.  This error was reported before back in jun 2019.  It was not properly resolved.  The person who reported it, fixed the problem by deleting the towny folder and then making a new town.  This is not a solution as most towny server admins cannot delete ALL towns and expect everyone to reclaim them.  Despite this not being a proper fix at all, the issue was closed:
https://github.com/TownyAdvanced/Towny/issues/3276

### What is the expected output?
1.  Not to have console spammed with the error
2.
3.

### What is your Towny version?
Do not say "latest".
Towny version 0.94.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Paper-236 (MC: 1.14.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/XX78LUFu

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/e7tXdM9m

3. Your townyperms.yml :

4. Your log's error : 
https://pastebin.com/2GTVb6Th
(optional) If this is to do with permissions, 
5. Your permissions file :
https://pastebin.com/5VkHzbG5
(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This was probably taken care of in a build since 0.94.0.0, if you're on 1.14 you should be using 0.95.2.0 or 0.95.2.3. Your TownyNameUpdater should also be version 4.0.

I'd say at least update then let us know if you still see that happening when plots are reverting to their pre-claimed state.

**Comment by LlmDl** [comment]
No feedback given.
