### ISSUE TITLE
Plot group

### ISSUE THREAD

**Issue by Mitsu13Ion** [TownyAdvanced/Towny#3601]
### What steps will reproduce the problem?
1. /plot new exemple
2. /plot add exemple
3.

### What is the expected output?
1. no error
2.
3.

### What is your Towny version?
0.95.2.3

### What is your spigot/craftbukkit version?
Paper 226

### Please use Pastebin.com to link the following files:

Your full server startup from the logs\latest.log : https://pastebin.com/R3ay8RHB
Your Towny config.yml : https://pastebin.com/3sqtHnZg
Your townyperms.yml : https://pastebin.com/6jLnDRcm
error log : https://pastebin.com/xxeCHPTH

**Comment by LlmDl** [comment]
There's a PR on here that will fix this, just has to be accepted and released.
