### ISSUE TITLE
Bugs with jails

### ISSUE THREAD

**Issue by 3meraldK** [TownyAdvanced/Towny#3602]
I has been sent to jail in some city (i am an outlaw so mayor killed me) and anyway it teleported me to my own city

### What steps will reproduce the problem?
1. become an outlaw in some city
2. become murdered in that city

### What is the expected output?
1. i should be teleported to jail plot

![image](https://user-images.githubusercontent.com/48335651/71624217-b1de6700-2be1-11ea-8ec9-c5d58bc45924.png)

### What is your Towny version?
0.95.1.0

### What is your spigot/craftbukkit version?
git-Paper-236 (MC: 1.14.4) 

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
2. Config.yml
https://pastebin.com/niFEzmLe

3. Your townyperms.yml :
https://pastebin.com/XJfZ5b3X

didn't get errors

**Comment by LlmDl** [comment]
Missing startup, cannot reproduce as is.

**Comment by LlmDl** [comment]
No feedback given.
