### ISSUE TITLE
Suggestion: Towny Banks

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3605]
**Please explain your feature request to the best of your abilities:**
This is a previous ticket that is being split into two sepeprate tickets. The link to the origional ticket is here: https://github.com/TownyAdvanced/Towny/issues/3590

Here is the main post from that other ticket. 

For the separate bank idea, I like this. Originally I wanted it to only be run by a town. However it still basically is, just like how a nation still has a capital. For the bank, as you said, it'd be /b new name. So you could do /b new IronBank, for example, like from Game of Thrones. You've now created a bank. You can do /b, or others can do /b ironbank, to view it. on my server, I had this idea of having a physical bank people went to that had admin shops. If someone went through the effort to build a nice big bank on their town, then a staff member would put in the admin signs. I like the idea of promoting people building physical banks. Which would also play in with the capital idea, and perhaps even offer an option to be a different colour on the dynmap, say, purple? With a $ icon. The reason you'd have chunks claimed for a physical bank, is that perhaps you could only do money deposits/withdrawals from the claimed bank chunks, like the existing option within towny for towns/nations.

Some viewed page info

Time made
Money
Capital
Owner
Members
Dynmap

Purple chunks
$ icon, or some kind of bank looking icon
Capital

Claim chunks for a bank
Chunks cant be claimed from the wilderness.
Chunks can only be purchased from an embassy plot from someone, forcing banks to actually exist within towns
Can only deposit/withdraw money from the bank chunks
Can /b home, to the banks home
Total commands I can think of

/b new name
/b view (name)
/b invite name
/b kick name
/b deposit
/b withdraw
/b claim
/b unclaim
/b sethome
/b home (name)
/b toggle public
(and whatever loan commands there are, if added)
/b loan(if we're doing
(number prices are just made up and not assumed to reflect each other)
Some config options I can think of

#Can money be withdrawn from anywhere? Set to false, to only allow money actions on land owned by the bank. Recommended false.
Transaction_anywhere: false
#Can the bank claim wilderness land, or only purchase embassy plots? Recommended false.
Wilderness_claim: false
#Is bank home command enabled? This will enable bank members to /b home
Bank_Home: True
#Can anyone teleport to the home of a public bank? With /b home name?
Bank_home_anyone: False
#cost of creating a bank
Bank_creation_cost: 500.00
#Bank rename cost
Bank_rename_cost: 500.00
#allow bank outposts? This will enable disconnected claims in more than one town.
Bank_Outposts: true
#Should the amount of power a bank has to claim land be a set number, or based on member? Options are either set, or player.
Power base: Set
#Amount of power each person adds to a bank
Bank_Player_Power: 1
#Set number of power a bank has
Bank_Set_Amount: 4
#can a bank buy bonus power?
Bank_Bonus_Power: True
#Cost of bonus power
Bank_Bonus_power_Cost: 100.0
#Max bonus power allowed
Max_Bank_Bonus_power: 10
#Maximum amount of members allowed to join a bank
Bank_Member_limit: 5
#Number of outposts allowed
Bank_Outpost_Limit: 3
#Can a bank buy more outposts?
Bank_buy_bonus_outpost: true
#cost of buying additional bonus outposts
Bank_buy_bonus_outpost: 100.00
#bank upkeep cost
Bank_upkeep: 100.00
#bank upkeep outpost modifier. This will increase the upkeep with each outpost owned.
Bank_outpost_upkeep: 100.00
#bank taxes. this is the maximum tax amount a bank can set on its members
Bank_Taxes: 100.00,
(all the other tax options you guys have)

The bank should only be able to establish more land in other towns by having outposts. This means the bankers can have many tp points, but due to such small limited number of people allowed within a bank, and presumably a high upkeep cost, it shouldnt be too abusable.

People can only be a member of one bank.

**Comment by LlmDl** [comment]
This is an interesting idea. Part of me wonders if having banks be an object unto itself that can claim land isn't the correct implementation. A lot of what's happening here could potentially be rolled into an expansion of the Towny bank plot type. 

The main reason against having a bank own land in my eyes is that so far no land exists in Towny that doesn't belong to a Town.

I could potentially see this operating through bank plots that are owned personally by a player and maybe also owned by a town.

* This would allow a player to buy a bank plot in a town (or a mayor to make their own bank plot,) to potentially run a command like /bank new {bankname} while standing in their bank plot (or plotgroup of bank plots.) 
* Once created the bank could have the option to deposit/withdraw from a special bank economy account created by Towny (like the town and nation accounts,) via your Economy plugin of choice. 
* Afterwards the money in the bank could potentially work out like real banks.
  * The town can set a tax on bank plots so the mayor gets their cut of things when players run the bank.
  * The players on the server can visit the bank plot and
     * open/close bank accounts,
     * deposit/withdraw money,
     * collect interest from the money in their account.
  * The bank operator can devise loans for purchase.
  * The bank operator can set interest rates.

All of this could be pretty neat but I'd fear it would be fairly abuse-able for both sides.
* Bank operators could empty the entire bank out. (Maybe they can only take out what doesn't belong to players' account at the bank.)
* Bank operators could unclaim the plot. (Maybe we make the plots something that cannot be abandoned.)
* A rich player could try to deposit so much money that the interest would drain the bank's resources. (Maybe interest only pays out when it's possible to pay out.)

**Comment by ponkersboard** [comment]
It says it was completed but it never got implemented did it?
