### ISSUE TITLE
Suggestion: Create system to remind players of available invites.

### ISSUE THREAD

**Issue by jimender2** [TownyAdvanced/Towny#3608]
Issue with accepting nation invites.
 If you are the mayor of a town, and had a nation invite sent to you by a nation, you should be able to accept by using /n join {nation_name} in addition to the /n invite accept {nation_name}
This would be useful when the mayor is offline or when trying to join.

### What is your Towny version?
I dont know,

### What is your spigot/craftbukkit version?
1.14

**Comment by LlmDl** [comment]
As far as I know the nation king can send the invite to the Town whether the mayor is online or not. It will persist until the server is stopped or Towny is reloaded.

The /n join command is only for 'open' nations.

**Comment by jimender2** [comment]
What if the invite makes that nation 'open' to the town.  If that is not a good option, could there be a notification that shows the command to the mayor?  The current invite system is confusing if the mayor is offline when the invite is sent.

**Comment by LlmDl** [comment]
We can probably set up an invite reminder on login for residents and town invites, mayors and nation invites, kings and ally invites.
