### ISSUE TITLE
Towns only partially deleted when fall - errors after next restart

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3610]
### What steps will reproduce the problem?
1. Create a town.
2. Either don't fund it enough or remove money from its town bank.
3. use /ta newday or wait for a new day to occur.
4. restart the server.

After the newday, the town will be gone, /t (fallentown) will tell you it's not a town, etc, BUT, on restart, towny will tell you you the town is missing its home block and if you try /t (fallentown) you'll get a console error and no response in chat.

### What is the expected output?
1. Towns would be fully deleted from the database on falling.
2. Towns would stay deleted across restarts.
3.

### What is your Towny version?
Do not say "latest".
0.95.2.1

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.4 Paper 236

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/0QS9xwQ4
This log is the first restart after the town of Fernweh fell due to lack of funds.. there was no error when it fell and it appeared to have fallen normally until restart.
Here is the newday when it fell, including a /t Fernweh that worked as expected:
https://pastebin.com/PZ52bQxA

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/MUnSNkPk

3. Your townyperms.yml :
https://pastebin.com/afHVuVM5

4. Your log's error : 
On /t (fallentown) after a restart:
https://pastebin.com/s7r68zQe

On restart when towns have fallen and database hasn't been manually cleaned up:
https://pastebin.com/fhxy7LEX

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Should be fixed in 0.94.2.5
