### ISSUE TITLE
Nation zones are smaller around capitals rather than larger

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3611]
### What steps will reproduce the problem?
1. Configure your server to have and use nation zones 
2. Have a nation large enough to have nation zones
3. Give the capitals a bonus plot of nation zone.
4. Capital cities will have one less rather than one more plot of nation zone.

### What is the expected output?
1. On my server the largest nation size should have a nation zone of 3 plots, with an extra around capital cities.  Players from other nations shouldn't be able to mine in that range, but the actual nation zone is much smaller than configured.  A capital city with 68 residents in a nation with 15 towns and 96 residents only has a nation zone of two plots surrounding it (as measured by both action bar notifications and the inability of outsiders to break the ground).
A non capital city with only 2 residents in the same nation has a nation zone of 3 plots.  

The capital of another nation with 22 residents of the town and 44 in the nation (5 towns) has only one nation zone plot surrounding it.  A 12 person town in that same nation has a nation zone two blocks wide

2. I would expect capital cities to get an extra block of nation zone rather than one less.
3.

What is your Towny version?

Do not say "latest".
0.95.2.1

What is your spigot/craftbukkit version?

Do not say "latest".
1.14.4 Paper 236

Please use Pastebin.com to link the following files:

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

Your full server startup from the logs\latest.log :
https://pastebin.com/0QS9xwQ4

Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/MUnSNkPk

Your townyperms.yml :
https://pastebin.com/afHVuVM5

Your log's error :
none (well, only the ones from my other report...)

(optional) If this is to do with permissions,
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Goosius1** [comment]
Hi Momshroom, 
- I fixed this a few weeks back
- It can be expected to be working in 0.95.2.2
- https://github.com/TownyAdvanced/Towny/releases/tag/0.95.2.2

**Comment by LlmDl** [comment]
Yep this one was spotted by Goosius already.
