### ISSUE TITLE
Crash/large lag/error when using towny backup

### ISSUE THREAD

**Issue by PacificMR** [TownyAdvanced/Towny#3621]
### What steps will reproduce the problem?
1. Use /towny backup
2. Big lag and most often a crash. Huge error in console.
3.

### What is your Towny version?
0.95. 2.0

### What is your spigot/craftbukkit version?
Paper 1.15.1 - 33

Error: https://pastebin.com/svshZzTg

**Comment by LlmDl** [comment]
Skipped form. Resubmit.
