### ISSUE TITLE
Question: [API] Trying to detect if a message is sent via town chat

### ISSUE THREAD

**Issue by Aaron2550** [TownyAdvanced/Towny#3625]
**Ask your question as best as you are able:**
I'm sending Chat messages to a discord channel, but when players use town chat their messages still appear in the discord. Is there a way to check if a message was sent via town chat? The [Javadocs](https://townyadvanced.github.io/Towny/) dont really speak to me...

**Comment by silverwolfg11** [comment]
That depends on what Chat plugin you have installed.

If you have the TownyChat plugin installed, then you can depend on TownyChat, listen to the `AsyncChatHookEvent` (make sure you have hooked set to true in your `channels.yml`) and check whether the channel type is town chat.

**Comment by Aaron2550** [comment]
Yeah were using townychat, is there any way to depend on it using maven or do i have to build the jar? im pretty new to this whole business ^^'

**Comment by LlmDl** [comment]
TownyChat isn't on our package manager, you'll have to add it to your maven localrepo manually.
