### ISSUE TITLE
Towny rename problem

### ISSUE THREAD

**Issue by WowwDoge** [TownyAdvanced/Towny#3626]
### What steps will reproduce the problem?
1. create a town use the command "town new blah"
2. change the town name. Use the "town set name blah" command
3. restart the server.

### What is the expected output?
1. https://pastebin.com/ERVYUfck
2. The major error is 
[20:59:26] [Server thread/WARN]: com.palmergames.bukkit.towny.exceptions.NotRegisteredException: The town 'test' is not registered.
3.

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
use the flat file latest.log : https://pastebin.com/2V5Yr8aE
use the mysql latest.log : https://pastebin.com/ERVYUfck

2. Your Towny config.yml (if using MySQL please remove password,) : 
use the flat file config.yml : https://pastebin.com/g3UKyKJF
use the mysql config.yml :https://pastebin.com/7cKr2DSN

3. Your townyperms.yml : https://pastebin.com/vQCm1Yvw

4. Your log's error :
use the flat file logs : https://pastebin.com/2V5Yr8aE
use the mysql logs : https://pastebin.com/ERVYUfck

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Test is old name.
