### ISSUE TITLE
Exploded Spawner returns as Pig Spawner

### ISSUE THREAD

**Issue by DalBrar** [TownyAdvanced/Towny#3627]
### What steps will reproduce the problem?
1. Make sure ExplosionRegen is enabled in the config
2. Stand near a spawner, example Skele Spawner
3. Spawn a creeper to explode it
4. Notice when regened the spawner is now a Pig Spawner

### What is the expected output?
1. When the spawner regens it remain what it initially was

### What is your Towny version?
Towny-0.95.2.2

### What is your spigot/craftbukkit version?
This server is running Paper version git-Paper-34 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. no errors in bootup log
2. default config with ExplosionRegen enabled
3. default townyperms.yml 
4. no errors log

**Comment by suneettipirneni** [comment]
I’ll work on this one.

**Comment by suneettipirneni** [comment]
Should be fixed in #3629
