### ISSUE TITLE
Suggestion: Alternative Towny Upgrade

### ISSUE THREAD

**Issue by Datrixel** [TownyAdvanced/Towny#3633]
I would like to suggest an alternative way to increase the towny plot capacity. I initially enquired via discord as I am a fairly new Towny Admin user so I wasn't sure of its features. I found a server running something similar so I wasn't sure if it was apart of this plugin or they have coded something additional. They rely on custom items as well for apart of their ranks, more can be found with this:

https://pastebin.com/izUfk0GD

I would like to suggest a Towny Upgrade process where the mayor and its residents could deposit 'x' amount of materials for them to increase the plot cap.

For example: 'Town' Level 0 > 'Town' Level 1 would require 64 cobblestone and 64 stone. This small upgrade would allow the town to advance granting them a plot cap of 16.

The next upgrade might be 128 stone & cobble, 64 wheat, and 32 iron ingots, granting the town claim cap up to 32.

**Comment by LlmDl** [comment]
I could see this sort of thing definitely happening via a secondary plugin.

Player uses /townupgrade and an inventory screen opens. The current level info could go up top in the name, it could show the progress of the items needed and the player just drops the items in. When a level is met the plugin adds bonus blocks to the town.

**Comment by Datrixel** [comment]
Awesome, I hope it is not too much of a hassle to implement .

**Comment by Datrixel** [comment]
Has there been any progress with this feature? Really keen on an alternative leveling structure.

**Comment by LlmDl** [comment]
I've gotten a good start on it but there's no real ETA I can give,
