### ISSUE TITLE
[Bug] Issue with short names when removing town invites

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3634]
A Discord user described the issue pretty well here:
![image](https://user-images.githubusercontent.com/18099825/72169622-c683e180-33cf-11ea-81f1-e95ecf561717.png)

I also went in and confirmed that the player's name is actually 99 and it's not just a nickname.

### What is your Towny version?
0.94.0.0

### What is your spigot/craftbukkit version?
Phantom version git-Craftimize-"116739e" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

(It's a paper fork)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : There is no response to the command in the server log so I won't include this here as I don't want to spend half an hour redacting it for no reason.
2. Your Towny config.yml (if using MySQL please remove password): 
[config.txt](https://github.com/TownyAdvanced/Towny/files/4046734/config.txt)

3. Your townyperms.yml: [townyperms.txt](https://github.com/TownyAdvanced/Towny/files/4046735/townyperms.txt)

**Comment by LlmDl** [comment]
Completed as of https://github.com/TownyAdvanced/Towny/commit/b454b07ce5eb295ca68ff68e65546ce61c7f5702
