### ISSUE TITLE
Suggestion: New permission (kick related)

### ISSUE THREAD

**Issue by eUipKh** [TownyAdvanced/Towny#3635]
The creation of this new permission:
- towny.command.town.kick.exempt  (Proposed by Silverwolfg11#4184 / Discord)

To prevent players of being kicked by city staff unless is the mayor of the city the one that execute the command. I think this could be great to create new ranks such as "Co-Mayor" or something else.

Thanks! ;)

**Comment by eUipKh** [comment]
How is my suggestion related to that?

**Comment by LlmDl** [comment]
Woops, wrong ticket.

**Comment by TheFlagCourier** [comment]
Sorry, should have better vetted that cherry-picked commit. It shouldn't close it, as it'll never hit Master, though.

**Comment by LlmDl** [comment]
So I went to do this ticket and found that we actually have a check for this that covers what you need already. The people who cannot be kicked from a town are the mayor and all of the assistants. All you need to do is make sure your co-mayor-ranked players are also given the assistant rank by their mayor.
