### ISSUE TITLE
Dynmap-Towny layer does not work after dynmap reload (1.15.1)

### ISSUE THREAD

**Issue by Caio0202** [TownyAdvanced/Towny#3638]
### Brief explanation

Dynmap-Towny works on server startup, but stops working after reloading Dynmap.
No exceptions are thrown in console when Dynmap-Towny is loading, but it simply doesn't work.

### What steps will reproduce the problem?
1. On server startup, Dynmap-Towny will work normally
2. Then attempt reload of dynmap by /dynmap reload
3. Towns and nations will not show up on dynmap.

### What is the expected output?
1. Towns and nations should show up on the dynmap on reload

### What is your Towny version?
0.95.2.7

### What is your Dynmap-Towny version?
0.74

### What is your Dynmap version?
Dynmap-3.0-beta-9-spigot

### What is your spigot/craftbukkit version?
Paper 35

### Please use Pastebin.com to link the following files:
1. Dynmap-Towny config.yml: https://pastebin.com/0GGwWXCP
2. Dynmap configuration.txt: https://pastebin.com/KBhr8pTZ

**Comment by LlmDl** [comment]
This has been fixed and will be a part of Dynmap 0.75.
