### ISSUE TITLE
TownUnclaimEvent Does Not Trigger On /town unclaim

### ISSUE THREAD

**Issue by jakkuh** [TownyAdvanced/Towny#3643]
### What steps will reproduce the problem?
1. `/town unclaim`
2.
3.

### What is the expected output?
1. `com.palmergames.bukkit.towny.event.TownUnclaimEvent;` would fire
2.
3.

We're trying to implement the removal of LWC Extended locks when a town owner unclaims a plot (with `/town unclaim`), however, it doesn't seem that there is an event to catch for this. The seemingly obvious `TownUnclaimEvent` event is only triggered when a town is deleted by the mayor, or when it falls from lack of funds. 

### What is your Towny version?
0.95.2.0

### What is your spigot/craftbukkit version?
1.15.1 Paper

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/vyuM4gF8
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/mECbs7Ke
3. Your townyperms.yml : https://pastebin.com/NE1Ukxjm
4. Your log's error : n/a

(optional) If this is to do with permissions, 
5. Your permissions file : n/a

(optional) If this is to do with chat,
6. Your chatconfig.yml : n/a
7. Your channels.yml : n/a

**Comment by suneettipirneni** [comment]
@jakkuh thank you for bringing this to our attention we should have a fix relatively soon

**Comment by suneettipirneni** [comment]
@jakkuh I can't reproduce this issue try updating towny to the latest version

**Comment by LlmDl** [comment]
I checked on this and we throw the TownUnclaimEvent when the TownyDatabaseHandler runs the removeTownBlock(TownBlock) method.

**Comment by LlmDl** [comment]
Were you using `/t unclaim` or `/t unclaim all` to test?

**Comment by jakkuh** [comment]
`/t unclaim was used.
