### ISSUE TITLE
Question: are we allowed to fork Towny and modify its code?

### ISSUE THREAD

**Issue by b1sergiu** [TownyAdvanced/Towny#3646]
This license isn't clear to me. If I have a Minecraft server, am I allowed to fork and modify Towny as long as it's closed source, I'm not distributing it and I'm not making any money from it?

**Comment by TheFlagCourier** [comment]
As long as those apply, and attribution is given to upstream, it should be in the clear. (#NotALawyer)

**Comment by LlmDl** [comment]
Yes you can modify towny for your own use, as long as it is not commercial. That being said if you're doing so to add something cool, it would be nice if you'd consider making a PR to get it into the official Towny.

**Comment by b1sergiu** [comment]
Thank you very much. The fork I'm planning to make will be heavily modified so I don't think I'd be able to make a pull request though.
