### ISSUE TITLE
Suggestion: Allow negative amounts to be used in unclaim-refund.

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#3650]
### What steps will reproduce the problem?
1. Set `economy.new_expand.price_claim_townblock_refund` to a negative value
2. Unclaim a plot

### What is the expected output?
1. The printed negative refund should be taken from the town's treasury.

### What is your Towny version?
`0.95.2.10`

### What is your spigot/craftbukkit version?
`git-Paper-238`

### Please link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log:
  To save you some time, I read the whole thing;  nothing interesting is printed.

2. Your Towny config.yml (if using MySQL please remove password,):
  I've set `economy.new_expand.price_claim_townblock_refund` to `-500`.

3. Your townyperms.yml:
  Issue is not permission-related.

4. Your log's error:
  There is no error in the log.

**Comment by MilesBHuff** [comment]
The issue template obfuscates the exact issue somewhat.  Essentially, when you set `economy.new_expand.price_claim_townblock_refund` to a negative value and unclaim a plot, the game says in chat that that value (eg, -$500) has been taken from the treasury;  but when you check the treasury before and after, you find that there has been no change.

**Comment by LlmDl** [comment]
So I looked into this. At first glance of this ticket I thought, 'wow that's fairly evil, and not really what the word refund means,' but I looked into it because we either have to not allow a negative amount at all, or we have to make it work with a negative amount.

Having it cost them money to unclaim would mean that if they cannot pay they cannot complete the unclaim. This is fine for one townblock, or a radius unclaim of a bunch of townblocks, but would we also charge them for every townblock when they try to do ```/t unclaim all```? 

At what point will you end up having towns just deleting themselves because it's cheaper than unclaiming their land, then reclaiming the area (minus what they wanted to unclaim.) Do we then start charging a town that wants to delete itself?

After looking it over I'm inclined to just make it not accept a negative amount, but I'd like your feedback on the above thoughts.

**Comment by MilesBHuff** [comment]
Sure.  Thanks for being willing to get feedback on this;  I appreciate it.  :)

So, on our server ((SettleScape)[https://github.com/SettleScape/server]), we do everything with bonus plots.  So, when you found a new town (which costs $10,000), you get one plot;  everything after that, all bonus plots (at $1000 each).  Players didn't like that that `/t claim` took money out of their town banks without telling them (That's really a separate issue: `/t claim` should tell you how much money you just spent claiming a plot, if nonzero.), but there's also the logic that they've already bought the bonus plot once, and it feels like they're buying it again when using `/t claim`.  However, we still want there to be a net loss of money when frequently claiming and unclaiming plots, in order to prevent people working around the outpost system.  The decision was made to move this to `/t unclaim` instead.  `/t unclaim` shows the amount it cost you to do it, and logically it's like you're paying to reclaim a bonus plot.  So, instead of paying $1000 for a new bonus plot and having to pay more in plot upkeep every day, you can just pay $500 to reclaim an already-used plot.

We don't really use radius claims or unclaims on our server.  It exists, but no-one knows about it, and it's capped to a radius of `1` (9 blocks).  Also, just for context, our plot size is only 8 blocks, not the default 16.

Under our bonus plots only system, in order for it to be cheaper for a town to disband and refound itself rather than just unclaim plots, the town would have to want to unclaim at least 20 plots ($10,000 / $500 = 20), and they would need to have no plots that they don't want to unclaim, since those would accrue an additional $1000 per plot charge after refounding.  If a town of 20 plots decides to completely uproot itself, I don't really see that as much of a problem -- so the hypothetical you give isn't relevant for us.  It might be for another server, but that server just wouldn't use this option, then.

**Comment by LlmDl** [comment]
Sounds reasonable. I'll take a look at getting this implemented after 0.96.0.0 is out. This is more of a suggestion ticket than a bug ticket and we're in bug-fixing mode until 0.96.0.0.

**Comment by MilesBHuff** [comment]
Thanks;  I appreciate it.
There is a bug in there (the fact that negative values say they work, yet they don't), but it's not game-breaking.  It does mean that players will be able to circumvent the outpost system until you get a fix out, though, so I may revert to `/t claim` costing money in the meantime.

**Comment by LlmDl** [comment]
That bug is fixed now as of https://github.com/TownyAdvanced/Towny/commit/e6d28c9f83e3cd344b40791ad5ab5e98fbe63fdb and will be a part of 0.95.2.11 or 0.96.0.0, whichever comes first.

**Comment by MilesBHuff** [comment]
Congratulations on releasing 0.96!  :D

Any plans for this feature as of yet?  :)

Thank you for all you do!

**Comment by LlmDl** [comment]
It's not very high on the priority list. Part of it is every time I see it in the list here my brain just tells me negative refunds are an oxymoron and should probably not be.

**Comment by MilesBHuff** [comment]
That is true, it is oxymoronic.  Maybe rename the variable?  Or have a toggle saying whether it's a refund or a fee?

**Comment by LlmDl** [comment]
Yeah I'm not closing the ticket, so we'll figure something out.

**Comment by MilesBHuff** [comment]
Hey LlmDl!  Long time, no see.  Any plans for this issue lately?

**Comment by LlmDl** [comment]
Not right now. We're getting a few things out of the way to further support 1.16.

I'm working on the run-up to the UUID conversion/removing the residents.txt file from the database and most of the rest of the team are doing things on top of figuring out the new database.

**Comment by MilesBHuff** [comment]
Hey @LlmDl!  Any updates on this one?  :)

**Comment by MilesBHuff** [comment]
Oh!  Awesome!  Thanks, @LlmDl!

**Comment by LlmDl** [comment]
> Oh!  Awesome!  Thanks, @LlmDl!

Thanks for sponsoring me @MilesBHuff !
