### ISSUE TITLE
/t unclaim lag spike (Possible crash)

### ISSUE THREAD

**Issue by jordanwilliams1** [TownyAdvanced/Towny#3652]
1. Make a town and claim plots
2.  do /t unlciam
3. Lag ??

Towny Version: 0.95.2.10 for 1.14.*/1.15.*

Server Version: 
Paper-32 1.15.1

Error during spike: https://pastebin.com/raw/yKes9Sex
Towny Config: https://pastebin.com/raw/kdMaWZXc
Towny perms: https://pastebin.com/raw/pg6bv040

**Comment by LlmDl** [comment]
Your tickets are not welcome until you stop violating the Towny license.

**Comment by jordanwilliams1** [comment]
For anyone who comes across this issue, it was caused by LWC. Just revert back to LWC Extended 2.2.3 on spigot.
