### ISSUE TITLE
Suggestion: Ruined Towns - A second chance for towns that have fallen.

### ISSUE THREAD

**Issue by bartymc** [TownyAdvanced/Towny#3657]
**Ruined Towns** - A second chance for towns that have fallen due to a lack of funds to pay for upkeep. The balanced and "fair" approach.

**Summary:**
- Towns that fall due to not paying upkeep will be put into a "ruined state". From here, they can either recover and become a town again or fall and disappear forever.

**Towns that are in a "ruined state" have the following penalties:**
- No "mayor commands" can be run. This includes inviting players, kicking players, joining/leaving a nation, etc.
- All perms are set to "on" for all groups. This means outsiders can steal from the town.
- The town is still there, so other towns cannot claim over the land of the town.
- A configurable timer begins, where at the end of the configured time, the town will completely fall into ruins, deleted.
- Residents are free to grab their stuff and leave the town considering the mayor is doing a terrible job.
  
**Some "features" that "ruined state" towns will have:**
- On dynmap, add a %flag% that shows is a town is in ruins and also displays X time remaining until town falls completely.
- When entering the ruined state town, it is displayed that the town is in ruins and how long until the town falls
- When using /town [townname], it is displayed that the town is in ruins and how long until the town falls
- When using /town list, on the page that the town appears on, next to the town name, display ruined state and X days remaining.
- When a resident of that town logs in, send them a message that the town is in ruins, how to fix this, how many days are left.
- When a town goes into "ruined state", send a global message similar to how towns currently fall into ruin.
- When a town completely falls, send a similar message globally.

**Possible outcomes for a town that has fallen into a "ruined state":**
- Someone (resident, mayor, nation member) deposits enough money into the town that is equal to or greater than the TOTAL daily upkeep (includes penalties from overclaims). The town is no longer in a ruined state, all of the penalties disappear, and the town may operate again normally. The town is responsible for paying upkeep once again.
- The town does not deposit enough money to cover a day's worth of upkeep. After X amount of time, the town completely falls and is essentially deleted.

**Some terribly edited possible renders of the alerts that a town is ruined:**
![image](https://user-images.githubusercontent.com/42015460/72946071-cf6ba000-3d4b-11ea-8118-c61d9cb60867.png)
![image](https://user-images.githubusercontent.com/42015460/72946081-d85c7180-3d4b-11ea-8614-c7cdf3a43d6f.png)
![image](https://user-images.githubusercontent.com/42015460/72946096-e1e5d980-3d4b-11ea-86d5-94c0ae0b614f.png)
![image](https://user-images.githubusercontent.com/42015460/77120510-6765cd00-6a0f-11ea-9ac4-a4cf33260dc5.png)

This expands on the proposed Siegewar ruined town state system, but is also viable for non-war servers.

**Comment by Goosius1** [comment]
If this ticket was implemented it would likely resolve the following ticket also:
[https://github.com/TownyAdvanced/Towny/issues/3553](url)

**Comment by Goosius1** [comment]
- The foundation for this is progressing well in the siegewar PR branch.
- In the branch, when a town is ruined, the town remains unchanged, except for removed from nation, NPC becomes mayor (to allow the mayor to leave), and a ruins countdown value in the town object is set to >0.
- From this state, it should theoretically be easy for one of the residents to recover to town. Once they do this, just set the resident to mayor, and set the ruins countdown is set to -1 or something (indicating off).
- If the exact monetary debt is to be stored somewhere, one easy way might be....to simply represent it using the normal positive bank account of the new NPC mayor.

**Comment by bartyrealms** [comment]
> * The foundation for this is progressing well in the siegewar PR branch.
> * In the branch, when a town is ruined, the town remains unchanged, except for removed from nation, NPC becomes mayor (to allow the mayor to leave), and a ruins countdown value in the town object is set to >0.
> * From this state, it should theoretically be easy for one of the residents to recover to town. Once they do this, just set the resident to mayor, and set the ruins countdown is set to -1 or something (indicating off).
> * If the exact monetary debt is to be stored somewhere, one easy way might be....to simply represent it using the normal positive bank account of the new NPC mayor.

I like your proposed idea of the NPC mayors. I had not considered what if the town had an inactive mayor when it became ruined. Glad to see this is being worked on because this is something I am looking forward to, will be a huge improvement to my server.

I'm assuming you intend for whoever deposits the money that brings the town balance back to positive will become mayor? This works for me.

**Comment by Haaruun-I** [comment]
Don't know if it's possible to pay NPCs but if it is you the assistant (who did the grief) can just pay the NPC the money they took out to double the cost. I suggest storing it as a negative value in the town bank if it supports that.

Another concern, if the person who paid off the debt is mayor, what happens if multiple people pitched in? Is it the person who paid the most? Most servers have a system in place for inactive mayors anyway, so i think either the former mayor stays mayor, or the server staff can pick.

**Comment by LlmDl** [comment]
Re: storing negative balances, I don't think we can reliably expect any eco plugin to handle negative amounts. We are probably going to have to have a number stored in Towny,  and bypass our use of the TownyEconomyHandler when /t deposit is used on a ruined town. 

When a town goes to Ruin, the mayor should maintain their status. If they are going to use /t leave to abandon their town they will have to /t set mayor a mayor of their choice.

The other scenario is that the mayor is removed via the old-resident delete which choose a successor from the assistants and if none are found the oldest residents.

The other-other scenario is if they are a one-man town and they are deleted via the old-resident delete. Then there would have to be a NPC mayor selected. At that point I think we have to decide if any random can buy the town, since there would be no residents to do it.

**Comment by Haaruun-I** [comment]
If a town goes bankrupt I think the town should be open to "Merge" into another town. The merge might work buy claiming all land in the town as an outpost of the town that merged with it.

Annother option is that nations might have an "Emergency Fund" that can be automatically paid to the town bank. The nation should be able to set a limit on how much the town can use out of it.

Or if its possible to keep track of this stuff. the assistant that caused the town to be bankrupt can be automatically demoted to stop it from happening again but the "Minimum Balance" thing solves this problem too. But I think there should be a default value by the server (or zero if the server didn't set it) and the mayor can change it from there.

**Comment by LlmDl** [comment]
Right now the town-merging is not possible yet. But there is a ticket for it here https://github.com/TownyAdvanced/Towny/issues/3193

**Comment by bartyrealms** [comment]
I do not like the idea of merging towns. 

> The other-other scenario is if they are a one-man town and they are deleted via the old-resident delete. Then there would have to be a NPC mayor selected. At that point I think we have to decide if any random can buy the town, since there would be no residents to do it.

I think it would be fair to just have the town fall completely if only one person were in the town. 

> Another concern, if the person who paid off the debt is mayor, what happens if multiple people pitched in? Is it the person who paid the most? Most servers have a system in place for inactive mayors anyway, so i think either the former mayor stays mayor, or the server staff can pick.

It definitely should just be whoever paid enough to have the town come back. In my opinion it should be handled in the sense that whoever pays the owed amount will be made mayor. This is the most fair and it rewards whoever is the one to rebuild the town. Additionally, it is automated and doesn't require staff intervention (staff intervention would be horrible. I have like 5+ towns fall from not paying upkeep every day).

I believe that the mayor should no longer be mayor, as they are the ones who put the town into ruin. Treat it as the mayor was inept and no longer has his job and whoever saves the town becomes the new mayor.

**Comment by Goosius1** [comment]
- Implemented a working version of this  (It can be improved later on)
- Tested and pushed to siegewar branch (& siegewar 1.13 compatibility branch). It can likely be abstracted out relatively easily later but I just wanted to get a working version out asap.
- This first version is rather simple, and works as follows:
*******************
Step 1. Town is ruined
Step 2. An NPC becomes mayor (like a caretaker)
Step 3. The town reclaim window runs from 24 hours after ruin to 72 hours after ruin (configurable)
Step 4. Any resident can reclaim, using "/t reclaim"
Step 5. The cost is nothing fancy. (No debt tracking etc.). Having already been in ruins for 24 hours, with all perms enabled, a high price has likely already been paid.  Thus the cost is simply the cost of a new town.
Step 6. On reclaim, the reclaiming resident becomes mayor, and the town returns to a normal state, with all previous townblocks still claimed.
*******************

- To use with siegewar:  
1. Deploy siegewar (or sw compatibility) jar  
2. Set config war.siege.switches.enabled to true

- To use without siegewar:  
1. Deploy siegewar (or sw compatibility) jar  
2. Set config war.siege.switches.enabled to true
3. Set config war.siege.switches.attack_enabled to true  (stops attacks)
4. Set config war.siege.switches.nation_leave_disabled to false (stops revolts)

**Comment by bartyrealms** [comment]
Testing your update:

Cannot use '/town reclaim'. Example:
![image](https://user-images.githubusercontent.com/42015460/74984679-4d32d200-5404-11ea-9640-f71319495b2a.png)
![image](https://user-images.githubusercontent.com/42015460/74984812-53c14980-5404-11ea-8556-81fb657a40e1.png)


Config:
https://pastebin.com/8zPFJqTt

**Comment by Goosius1** [comment]
- Hi, looks a little like some lang files need updating
- Check that the required lang file changes are there

**Comment by bartyrealms** [comment]
Testing shows that all systems are working properly on my test server. I have not been able to a full live test of the ruins system.

**Comment by DragonisOmega** [comment]
I love the idea of showing on the dynmap that the town is about to fall.
I would like to see an option of fallen towns get a different colored highlight.
Also when  the town does fall have an option to broadcast cords of the town.

**Comment by Goosius1** [comment]
Hi,
- We got a lot of suggestions building up in this ticket. (some are done, some  are not done, and some may be redundant now)
- Progress on each of these may be hard to track if it is all in one ticket.
- Is it time to split this ticket up into a few smaller tickets ?

**Comment by LlmDl** [comment]
@Goosius1 we want to add this feature first but it doesn't look like it will make it into 0.96.2.0, can you get a pull request ready for 0.96.2.0 or 0.96.3.0?

**Comment by Goosius1** [comment]
Sure thing. I've already started. Should have a PR ready in the next few days.

**Comment by LlmDl** [comment]
So. Bankruptcy is now a thing as of 0.96.2.19. 

#### This is a fair bit different from the above Ruins request but it does fit the following:

  - Negative balances that can be repaid. 
  - The town is still there, so other towns cannot claim over the land of the town.
  - Residents are free to grab their stuff and leave the town considering the mayor is doing a terrible job.
  - When a town goes into "ruined state", send a global message similar to how towns currently fall into ruin.
  - When a town completely falls, send a similar message globally. (This is the normal deletion message.)

#### Stuff that is similar to what was requested but different:

  - No "mayor commands" can be run. This includes inviting players, kicking players, joining/leaving a nation, etc.
    - Mayors cannot toggle open, claim land or add players.
  - All perms are set to "on" for all groups. This means outsiders can steal from the town.
    - All perms are normal except no building is allowed, by anyone given plot perms otherwise.
  - A configurable timer begins, where at the end of the configured time, the town will completely fall into ruins, deleted.
    - Via the debtcap, and the configurable option to delete towns when they hit their debt cap you have a time limit.
    - If your server has a set upkeep (everyone pays the same amount each day) then you can use the debt-cap-override setting to set a fixed debt cap server-wide. In this way you could give a town a week's worth of debt-cap headroom before the upkeep finally breaks the debt cap and the town is deleted.

#### Stuff that bankruptcy doesn't do from the OP:

  - On dynmap, add a %flag% that shows is a town is in ruins and also displays X time remaining until town falls completely.
    - That's up to dynmap-towny to show bankruptcy-status. It is not possible to know how long a town will last.
  - When entering the ruined state town, it is displayed that the town is in ruins and how long until the town falls.
    - We cannot reliably predict how much longer until a town would fall. It could even be configured to not fall.
  - When using /town list, on the page that the town appears on, next to the town name, display ruined state and X days remaining.
    - This is doable, just not done yet.

### With the foundation laid by Bankruptcy, I'm sure some more things from the above will be added. Those things can have their own suggestion tickets where the merits/feasibility can be discussed therein.
