### ISSUE TITLE
Town outposts all of a sudden non-existent and unaccessible.

### ISSUE THREAD

**Issue by keabsmad** [TownyAdvanced/Towny#3662]
### What steps will reproduce the problem?
1. re-setting the world (same world)
2. using /t outpost [#]
3. Says "there are no outpost spawns set for this town"

### What is the expected output?
1. To be able to use outposts again
2. to have a more stable way of accessing outposts
3. use /t outpost 

### What is your Towny version?
0.95.0.0

### What is your spigot/craftbukkit version?
Paperspigot 1.15.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Skipped form. Resubmit and explain what resetting the world is.
