### ISSUE TITLE
Cant change accept command

### ISSUE THREAD

**Issue by Superola86** [TownyAdvanced/Towny#3666]
### What steps will reproduce the problem?
1.    Find accept_command: accept in the config
2.   Change it to something else (i used testaccept)
3. Ingame command /ta reload
3. Resault when typing or clicking the chat after recived an invite is
 "Unknown command. Type "/help" for help."

Same thing when changing the deny command

### What is the expected output?
1.  Acceppting or Denying invitation to town
/ta 

### What is your Towny version?
0.95.2.11/spi

### What is your spigot/craftbukkit version?
Spigot 1.15.1-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/8gwyJ3Qx

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/JDJqL12m

3. Your townyperms.yml :
https://pastebin.com/e6iY6jf7
4. Your log's error :

**Comment by LlmDl** [comment]
Issue happens when changing command in config with restarting server.
