### ISSUE TITLE
Suggestion: Remove "[home]" from town names in Towny-Dynmap

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#3668]
**Please explain your feature request to the best of your abilities:**
Please remove "[home]" from town names. It's unnecessary, and makes it hard to see nearby towns on low zooms.
![image](https://user-images.githubusercontent.com/6566982/73127219-20b5a280-3f8b-11ea-8d4b-563060fb9aeb.png)

**Comment by MilesBHuff** [comment]
Repost of https://github.com/webbukkit/Dynmap-Towny/issues/24.

**Comment by LlmDl** [comment]
Changed as of https://github.com/TownyAdvanced/Dynmap-Towny/commit/253bd126e26fecd5508cc783effcd9991b4b77ed will be a part of .75

**Comment by MilesBHuff** [comment]
Thank you for the insanely fast turnaround!  :)
