### ISSUE TITLE
Town ranks are uncapitalized

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#3669]
### What steps will reproduce the problem?
1. Define a town rank in `townyperms.yml`
2. Assign that rank to someone
3. Run `/t` and read the output.

### What is the expected output?
1. Town ranks should be capitalized just like "Mayor" and "Resident" are.

### What is your Towny version?
`0.95.2.10`

### What is your spigot/craftbukkit version?
`git-Paper-238`

### Please link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log:
  To save you some time, I read the whole thing;  nothing interesting is printed.

2. Your Towny config.yml (if using MySQL please remove password,):
  Issue is not related to `config.yml`.

3. Your townyperms.yml:
![image](https://user-images.githubusercontent.com/6566982/73127321-7179cb00-3f8c-11ea-9c5c-fd92d7ae4229.png)
I would just capitalize the ranks here, but judging by the fact that `mayor` is uncapitalized and the various town ranks are uncapitalized by default, I'm going to go ahead and guess that we're not intended to be capitalizing these, and the fix needs to come from upstream.

4. Your log's error:
  There is no error in the log.

**Comment by LlmDl** [comment]
I'll have to look into this one a bit deeper. I am fairly sure that this was changed to it's current behaviour from when it could not be capitalized. Have you tried making your ranks with a capital letter? If I remember correctly that will make them appear capitalized.

**Comment by MilesBHuff** [comment]
It will, although I'll need to do a database update to prevent breaking existing rank assignments.  Like I said, though, in `townyperms.yml`, it's "`assistant`" (not "`Assistant`") by default, just like it's "`mayor`" and not "`Mayor`".  Since "`mayor`" appears as "Mayor" in-game, it stands to reason that "`assistant`" would show up as "Assistant" in-game.

**Comment by MilesBHuff** [comment]
If you decide that changing the case in `townyperms.yml` is the preferred solution, then the default `townyperms.yml` file should have them capitalized.
The config file would look a bit inconsistent then, though.

**Comment by MilesBHuff** [comment]
A third option -- although this one would be tantamount to a feature request -- is to allow localizing custom ranks.  That would completely separate their IDs in the configs with how they're displayed in-game.
This increases complexity for both you and admins.

**Comment by LlmDl** [comment]
So it will show them capitalized now no matter what your townyperms.yml actually has.

**Comment by MilesBHuff** [comment]
Thanks, LlmDl.  :)
