### ISSUE TITLE
Suggestion: New Rollback System

### ISSUE THREAD

**Issue by creatorfromhell** [TownyAdvanced/Towny#3670]
**Please explain your feature request to the best of your abilities:**
Currently the rollback system is too simplistic. My idea is to create a new database for the rollbacks that saves what player destroyed each block, and/or what entity destroyed each block/item. Then you also log a time for each destroyed block, this allows servers to configure rollback to only based on player and timespan.

**Comment by suneettipirneni** [comment]
Can we use AWS?

**Comment by creatorfromhell** [comment]
> Can we use AWS?

I think we dockerize the backups and important them when we revert. We can create multiple "snapshots."

**Comment by KarlOfDuty** [comment]
Could this be backported to 1.8 as well?

**Comment by gerardvanschip** [comment]
So add CoreProtect functionality to Towny?

**Comment by creatorfromhell** [comment]
> So add CoreProtect functionality to Towny?

More or less, yes. But rather than complete core protect functionality, I would suggest it to be more focused on Towny.
