### ISSUE TITLE
Suggestion: Backport New Features to hMod

### ISSUE THREAD

**Issue by creatorfromhell** [TownyAdvanced/Towny#3671]
**Please explain your feature request to the best of your abilities:**
My hMod Alpha server has the best performance when compared to modern Minecraft. This is why I'm asking for the modern Towny features to be backported to hMod.

**Comment by creatorfromhell** [comment]
@TheFlagCourier could you take this ticket on since you do the backporting?

**Comment by creatorfromhell** [comment]
Here is the jar I need it backported to. http://hey0.net/minecraft/Minecraft_mod%20133.zip

**Comment by creatorfromhell** [comment]
Do you have the link to the jar with this completed?

**Comment by TheFlagCourier** [comment]
#3670 finish that, then we talk.

**Comment by creatorfromhell** [comment]
@TheFlagCourier I was actually hoping @Articdive could include it in his new DB PR

**Comment by TheFlagCourier** [comment]
Yeah, that'd be alright. Have him add the launch codes as well.
