### ISSUE TITLE
some bugs which can climb walls of any height

### ISSUE THREAD

**Issue by 3094300238** [TownyAdvanced/Towny#3674]
this bug i can not replay but my player did.
when destroy blocks under the protection of towny , chances are that you can crash into blocks and then if you hold the Press button you can climb walls
Version:1.12.2 0.95.0

**Comment by TheFlagCourier** [comment]
At this time, TownyAdvanced does not support 1.12.2 servers. The form was also skipped. Given both, this ticket will be closed.

This sounds like either a collision box glitch, or a hacked client was in use, if you can replicate the glitch with a different player, and on a different/updated server, feel free to open a new ticket.

**Comment by LlmDl** [comment]
This would be a client-side thing, there are anti-cheat plugins to detect players' wrong movements.
