### ISSUE TITLE
Suggestion: Exempt specific plots from taxation

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#3675]
**Please explain your feature request to the best of your abilities:**
In my town, we would like to be able to exempt certain plots from taxation.
Specifically, we would also like to allow other towns to have official embassies for free, while still continuing to tax any "embassy" plots owned by players who just want to live in the town without being citizens.

**Comment by LlmDl** [comment]
This is likely going to require that plot-taxes get switched from a town setting, to where the town setting is the default for newly-type-set plots, with the option to set taxation on a per-plot basis. 

Bit of an overhaul but it can be done.

**Comment by MilesBHuff** [comment]
This one had a few upvotes, so there were multiple people wanting it;  is it just too much work to be worth it?

**Comment by LlmDl** [comment]
I can see this being implemented with a per-townblock `taxed` flag that is toggled with `/plot toggle tax`.

**Comment by MilesBHuff** [comment]
Thank you @LlmDl -- you're awesome!
