### ISSUE TITLE
Suggestion: Option to make subzone inside claimed cunck/chunks

### ISSUE THREAD

**Issue by broken1arrow** [TownyAdvanced/Towny#3679]
I know is other plugin some can do it, but overall is towny better plugin far as i see.

So is it something you can add? Is not always you want players have 16*16 and 256 to build on.

I´m has play before on towny server, but gets so awkward to have 16*16 space between plots and road in middle and is players some want use 16*16 not 15*15 so players build in to neighbor´s.  

One large problem is player build down, hard for towny owners to fix the plot agen (reset command not work so good with LWC before at least). So admins have to unlock and remove chest and towny owner have to fix the plot manually.

So some way to limit how big area players can build on (so we not have to use barrier blocks and bedrock).

**Comment by LlmDl** [comment]
Towny cannot do plots at differing sizes. 

It sounds like your mayors need to properly configure their town-owned lands to not allow other players to work on them.

**Comment by broken1arrow** [comment]
Not like subzones? Im not mean the big zones you create (we try different plugin some claim in chunks but not subzones/playerzone can you do in enny size).

In towny you clam hole chunk 16*16 and you need have next player 16 block away if you dont want him destroy the wall/decoration around the plot (is always so players try to us all land they can).

**Comment by LlmDl** [comment]
Yes that is correct. Towny consists of cells on a grid. There is no way to have smaller cells separating other cells. All cells are the same size.

**Comment by broken1arrow** [comment]
Yes but I mean have a layer on top of this (or similar), you can let player build in (and limited height to). 16*16 is big size you need have around every plot.

**Comment by LlmDl** [comment]
We cannot put a layer on top. You need to put your decorations inside of the plots.

**Comment by broken1arrow** [comment]
Yes and player can ofc destroy this :) and is not nice locking have roods some are 16 wide every way.

**Comment by LlmDl** [comment]
When you first set up towny you can set the plot size smaller than 16, then you can combine plots into groups to sell to players if you want (and you're on the latest pre-release.)

**Comment by broken1arrow** [comment]
Hm guess is center on chucks not player? And better if player can change size not on server side.

**Comment by LlmDl** [comment]
As I've explained: Towny's system is a grid of cells which are all the same size squared. By default the size of 16 means that Towny's cells (townblocks/plots,) are all lined up with minecraft's chunks. There's no changing the town_block_size after the server has been started and land has been claimed.

**Comment by broken1arrow** [comment]
So if i change size is center on player not chuck?

**Comment by LlmDl** [comment]
It never centers on the player, it is always a series of squares/cells on a grid.
