### ISSUE TITLE
Suggestion: Allow rare characters in towns' boards.

### ISSUE THREAD

**Issue by Srborjaa** [TownyAdvanced/Towny#3681]
**Please explain your feature request to the best of your abilities:**

Hi, I'm writing this suggestion because whenever I try to write a board that includes rare characters (letters with accents, commas, slashes, double points...) this message appears mostly:

[Towny] Invalid string, town board not set.

And it could be a good idea to allow these characters.

Thanks.

**Comment by LlmDl** [comment]
You need to add these to your config's regex sections. (but not the remove regex)
