### ISSUE TITLE
Suggestion: ''Mine'' Chunk.

### ISSUE THREAD

**Issue by Gazpa47** [TownyAdvanced/Towny#3682]
How about giving mayors the posibility of defining a chunk in their city, by paying a certain amount and a certain tax, to become a ''Mine Chunk''?
It would work generating stone and ores on said chunk, at definable Y levels.

Of course, via config, defining the generation rates of certain ores could be manipulated.
OR even better: Getting the ''wild'' to define ''wild mine chunks'' on the world, and having them set as the only mine chunks. That way people would strive to get specific territories on said areas (I am aware this last thing is much less possible)

**Comment by LlmDl** [comment]
This sort of thing I feel is outside of the realm of Towny, a separate plugin could be made to use the Towny API and achieve this sort of feature though.
