### ISSUE TITLE
Nation Kings have no perms with default townyperms.yml setup.

### ISSUE THREAD

**Issue by Tobberz** [TownyAdvanced/Towny#3683]
### What steps will reproduce the problem?
1. LuckPerms 5.0.48, Towny 0.95.2.13
2. Be the king of a nation.
3. Try to execute any nation command such as /n add or /n set

Example video of error (11s): https://youtu.be/MUw3jtYgW3U

### What is the expected output?
1. Notice informing player that they do not have enough permissions for that command - it doesn't work.
2. FYI: This works on admins with the * perm.

### What is your Towny version?
Towny 0.95.2.13

### What is your spigot/craftbukkit version?
Paper 1.15.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/5xZ2mDgE
3. Your townyperms.yml : https://pastebin.com/FKAsvnpT
4. Your log's error : N/A

**Comment by LlmDl** [comment]
This was caused by removing the Assistant ranks from teh town and nation sections.
