### ISSUE TITLE
Question:is there any version of dynmap-towny that support the dynmap-forge 1.12?

### ISSUE THREAD

**Issue by 3094300238** [TownyAdvanced/Towny#3684]
when i would like to use the dynmap-forge 1.12.2,and put the Dynmap-Towny into the /plugins(Because i am using a catserver core in 1.12.2 which can supports bukkit and forge)
i find that latest dynmapCBBridge works fine
but there is a marker api error which leads to a fatar error of dynmap-towny.
is there any version of dynmap-towny that support dynmap-forge?

I know that i should ask question in Dynmap-towny page,but i am new in Github and i dont know how to report an issue in Dynmap-towny you forked from webbukkit. Apologize!

**Comment by LlmDl** [comment]
You could try an older version: https://github.com/hankjordan/Dynmap-Towny/releases

That one says it's for 1.13 but it might work, if not use 0.70 from this page: https://dev.bukkit.org/projects/dynmap-towny/files/912863
