### ISSUE TITLE
Players not losing money on death to custom monster from 3rd party plugin.

### ISSUE THREAD

**Issue by swaith** [TownyAdvanced/Towny#3686]
### What steps will reproduce the problem?
1. Players have a wallet balance above $0 - configured to drop balance on death. and die to monsters from 3rd party plugin EliteMobs (custom monsters) 
2.  Characters do not drop balance upon death. (Only to custom monsters)

### What is the expected output?
1. Expected to lose balance carried upon dying (as currently with all other death causes I am aware of) 

### What is your Towny version?
Do not say "latest".
Towny v0.95.2.13

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper version git-Paper-87 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/kWUFf9KJ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/491F3KV4
3. Your townyperms.yml : https://pastebin.com/4FrD3p1j
4. Your log's error :  (N/A - no error that I can see)

Link to 3rd party plugin
https://www.spigotmc.org/resources/%E2%9A%94elitemobs%E2%9A%94.40090/
Github: https://github.com/MagmaGuy/EliteMobs

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

![bitmoji](https://render.bitstrips.com/v2/cpanel/33dd5e8f-cc39-4cc1-af24-e49c70b17dc9-a3539d02-5c5d-4a13-bd09-fd23e2618ee3-v1.png?transparent=1&palette=1&width=246)

**Comment by LlmDl** [comment]
In your config on line 979 price_death_type you have '0.1' but it should be 'fixed'

Set that and try again

**Comment by LlmDl** [comment]
This ticket will be closed if there's no response in 12 days.

**Comment by swaith** [comment]
Sorry about that LlmdI - I only just saw the reply email - I have changed it in the config and have set the percentages - I will test it later tonight and let you know what happens.

**Comment by LlmDl** [comment]
Sounds good. Fairly sure it will work better with it set correctly.
