### ISSUE TITLE
Suggestion: Town name chat color depending on town level

### ISSUE THREAD

**Issue by Halfhand1** [TownyAdvanced/Towny#3688]
Add an option which allows the town name color in chat to change depending on the town level. Right now you can only set one color for any town in the config.

For example a settlement would be grey and a metropolis orange.

This would encourage players to build bigger towns and also allows the big tows to set themselves apart from other smaller towns.

**Comment by bartyrealms** [comment]
Couldn't you just use Javascript placeholders to accomplish this?

**Comment by LlmDl** [comment]
This can be done in the town_levels and nation_levels itself, using the prefix/postfixes.
