### ISSUE TITLE
Daily taxes are charged with a random delay

### ISSUE THREAD

**Issue by luckybl0ck** [TownyAdvanced/Towny#3691]
### What steps will reproduce the problem?
1. Wait for a new day (in my case at 8 PM)
2. Taxes are charged with a random delay, from 10 minutes to several hours

### What is the expected output?
1. When a new day starts, taxes are charged immediately

### What is your Towny version?
0.95.2.13

### What is your spigot/craftbukkit version?
Paper version git-Paper-93 (MC: 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/Pn1dviCf
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/rPdh8US2
3. Your townyperms.yml : 
4. Your log's error : there are no error in the console

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

I also noticed that with zero online players, taxes are charged immediately

**Comment by LlmDl** [comment]
Things are fine in your log/config. What sort of TPS do you have when you do have players online?

**Comment by LlmDl** [comment]
If you could, it would be very useful if you were to use /ta toggle debug before the newday code happens. While debug, the dailytimertask actually prints out how long it took to complete. I'd like to see how long it takes.

**Comment by LlmDl** [comment]
It is also worth mentioning that the lower your ticks, the longer it will take for the timer to finish. 

If you ran a solid 15 ticks per second all of the time, the scheduled timer task's delay would only be 75% complete.

**Comment by luckybl0ck** [comment]
Usually the TPS is 17-20. The /ta toggle debug command will log information to a file, right?

**Comment by luckybl0ck** [comment]
Also, the strange thing is that the /towny time command shows that the day starts exactly at the right time, but taxes charges with delay.

**Comment by LlmDl** [comment]
That is because the /towny time command shows the time until the time that it is set to happen in the config.

Using /ta toggle debug will log the information to the normal log as well as teh towny debug log.

I'm making it so that 0.95.2.15 it will print out how long the newday takes every time.
