### ISSUE TITLE
Town Bank Bug

### ISSUE THREAD

**Issue by MrLogano** [TownyAdvanced/Towny#3694]
### What steps will reproduce the problem?
1. Use CMI Economy, using either the Injector, or the recompiled version of Vault.
2. In the default config, change "closed_economy.enabled" to true.
3. Reload the Towny config.
4. Attempt to perform any Towny action that requires money, such as claim townblock.

### What is the expected output?
1. Use Towny as normal, being able perform actions such as claim townblocks.

### What is your Towny version?
0.95.2.14

### What is your spigot/craftbukkit version?
paper-99 (1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
[latest.log](https://pastebin.com/imntXA9u)

2. Your Towny config.yml (if using MySQL please remove password,) :
[config.yml](https://pastebin.com/0Bu1vXgU)

3. Your townyperms.yml :
[townyperms.yml](https://pastebin.com/3UXJFwBu)

4. Your log's error : 
No error is shown in logs, however, you are shown something similar to this in chat.
[screenshot](https://prnt.sc/r0pzvl)

**Comment by LlmDl** [comment]
This one has been narrowed down to CMIEconomy not handling the towny-server account properly.

**Comment by LlmDl** [comment]
Fixed with next CMI Build https://github.com/Zrips/CMI/issues/2787
