### ISSUE TITLE
Suggestion: Rank PAPI Placeholders

### ISSUE THREAD

**Issue by Artuto** [TownyAdvanced/Towny#3695]
Please add Town and Nation rank placeholders, for example:

```
%townyadvanced_town_rank%
%townyadvanced_nation_rank%
```

Then it would return Mayor, Assistant, VIP, Resident, etc.

**Comment by LlmDl** [comment]
The reason why this was never added to TownyChat was because players could have any number of ranks. You could potentially get a placeholder that returns any number of ranks.
