### ISSUE TITLE
Question: Towny Source for MC Version 1.2.5?

### ISSUE THREAD

**Issue by FindZach** [TownyAdvanced/Towny#3696]
Apologies if this isn't the proper place for this inquiry I am a Tekkit Classic player and I would like to customize 1.2.5 (MC Version) of Towny to make a proper Tekkit Classic version of it. The Source would be public; I was wondering if you guys had archives that long ago. I couldn't find it anywhere, I know Palmergames used to handle towny so perhaps you guys have something that far back.

Thanks a lot for reading, if anyone has any advice; responses are appreciated!

- Zach

**Comment by LlmDl** [comment]
That would have been on googlecode probably. I don't know of any way to get it from there.

**Comment by FindZach** [comment]
> That would have been on googlecode probably. I don't know of any way to get it from there.

Thanks I am unfamiliar with google code, I would like to learn though; do you know of any links to help me find it on googlecode?

**Comment by LlmDl** [comment]
It was where we had teh source code prior to using github: https://code.google.com/archive/a/eclipselabs.org/p/towny/source/default/source

I do not know at what stage this was in comparison to 1.2.5 though.
