### ISSUE TITLE
TownyAdvanced not working with my economy plugin

### ISSUE THREAD

**Issue by henrymoonrabbit** [TownyAdvanced/Towny#3698]
Hey, I don't know if anyone actually reads/responds to these but I just started using TownyAdvanced on my server with a basic economy plugin called... Basic Economy (wow!) and the two plugins aren't connecting at all. When my balance is enough to pay for founding a new town, if I type /town create [town name] I get a message saying I have insufficient funds. Does TownyAdvanced have its own built in economy? (I don't think so)
I don't know if I need to do something to get them to sync or just use a more common economy plugin with more support... if anyone could help me out that'd be cool. If I should use a different economy plugin, which one should I use? I'm looking for something basic: pay, bal, etc. preferably with shops (chests with signs or npcs or something?) Thanks for reading all this **!**

**Comment by Momshroom** [comment]
Do you have vault? Is there an error on startup?  Is there an error when you try to make a town? When you type /towny version what is the output?

**Comment by henrymoonrabbit** [comment]
> Do you have vault? Is there an error on startup? Is there an error when you try to make a town? When you type /towny version what is the output?

Wow! Thanks for responding sir I did not think someone would
1. I do have Vault. 
2. Nothing's showing up in the server console, I use mcprohosting to host and the service is called Multicraft. The console is full of 
07.02 03:24:42 [Multicraft] Waiting for log file...
07.02 03:24:22 [Multicraft] Waiting for log file...
07.02 03:24:02 [Multicraft] Waiting for log file...
3. When I try to make a town I am told "[Towny] You can't afford to settle a new town here, which costs 50.0."
4. I'm on Towny version 0.95.2.12.

**Comment by LlmDl** [comment]
People do read these. Please open a [bug report](https://github.com/TownyAdvanced/Towny/issues/new?assignees=&labels=bug&template=bug_report.md&title=) so that we can properly diagnose the issue. Don't skip the form.

**Comment by henrymoonrabbit** [comment]
I noticed this warning in the startup log:
15.02 16:59:36 [Server] Server thread/WARN Error: No compatible Economy plugins found. Install Vault.jar with any of the supported eco systems.
I guess the plugin doesn't work with every economy plugin, I'll just use a supported one. I'm commenting here in case anyone else has the same problem- just look in the console when you start your server and look for red messages
