### ISSUE TITLE
Nation Spawn permissions do not work for people who are not in a nation

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3702]
### What steps will reproduce the problem?
1. Be a nomad (no nation)
2. Try to use nation spawn for a public nation spawn
3. Receive error: "You don't have enough permissions for that command."
4. Player is not teleported

### What is the expected output?
Player is teleported and has permission to do this. The "towny.nation.spawn.public" and "towny.nation.spawn.*" permission nodes are not working for people who are not in a nation. I tested this by adding it to every group in my townyperms.yml file and adding it to the luckperms default group. Luckperms claims that a user inherits these permissions, but are still unable to use /nation spawn othernation.

### What is your Towny version?
0.95.2.15

### What is your spigot/craftbukkit version?
Paper 105 (MC 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/1VJEyzyk
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/H2BtCNYY

(optional) If this is to do with permissions, 
5. Your permissions file :
https://pastebin.com/W3beebi7

**Comment by suneettipirneni** [comment]
I believe I’ve identified the problem I should have a fix tonight.

**Comment by LlmDl** [comment]
This one is fixed as of 0.95.2.16
