### ISSUE TITLE
loss of money from the treasury in cities with the Russian registry

### ISSUE THREAD

**Issue by mnivdick** [TownyAdvanced/Towny#3704]
### What steps will reproduce the problem?
1. It happens all by itself

### What is the expected output?
1. Players in the server could safely store money in the account of their city

### What is your Towny version?
Towny-0.95.2.12

### What is your spigot/craftbukkit version?
Paper 1.15.1

I checked all the log files, nowhere is there anything about transferring and withdrawing money

**Comment by creatorfromhell** [comment]
What economy plugin do you use?

**Comment by mnivdick** [comment]
> What economy plugin do you use?

EssentialsXSpawn-2.17.1.52

**Comment by LlmDl** [comment]
Ess Eco losing town/nation balances is just normal behaviour. The ess team doesn't recommend you use their economy on Towny servers. You skipped the form so this ticket is invalid. Don't refile. Use a different economy plugin.

**Comment by mnivdick** [comment]
> Ess Eco losing town/nation balances is just normal behaviour. The ess team doesn't recommend you use their economy on Towny servers. You skipped the form so this ticket is invalid. Don't refile. Use a different economy plugin.

Can I fix it for my plugin

**Comment by LlmDl** [comment]
I do not understand your question, sorry.

**Comment by mnivdick** [comment]
> I do not understand your question, sorry.

Can you fix Towny for EssentialsX?

**Comment by LlmDl** [comment]
No it is not an issue with Towny. It is an issue on their end, they have a ticket on their tracker for it.

**Comment by LlmDl** [comment]
No it is not an issue with Towny. It is an issue on their end, they have a [ticket](https://github.com/EssentialsX/Essentials/issues/2921) on their tracker for it.
