### ISSUE TITLE
Problem with build, destroy, item_use, and switch permissions

### ISSUE THREAD

**Issue by soloyolorolo** [TownyAdvanced/Towny#3709]
### What steps will reproduce the problem?
1.  Creating a town through /town create town_name
2. Setting permission through /town set perm outsider destroy off
3. outsider still can destroy and place blocks in this chunk, also in town perms by destroy, build, switch, and item_use I'm getting r---, rather than on and off, also it displays that the permissions changed successfully

### What is the expected output?
1. After using /town set perm outsider destroy off that off is displayed next to destroy, and that within that chunk players that are neither allied nor friends cant break blocks within that chunk
2.
3.

### What is your Towny version?
Do not say "latest".
0.95.2.0

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot-1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log : 
[https://pastebin.com/raw/MhwCerQu]

2. Your Towny config.yml (if using MySQL please remove password,) : 
[https://pastebin.com/raw/FiXgumBr]

3. Your townyperms.yml : 
[https://pastebin.com/raw/w4dh3dPv]

4. Your log's error : 
No error message came up in console.

(optional) If this is to do with permissions, 
5. Your permissions file :
Could not upload, opened file in notepad ++ and the file was blank, can create a link to google drive for the file if necessary.

(optional) If this is to do with chat,
6. Your chatconfig.yml : Does not have to with chat
7. Your channels.yml : Does not have to with chat

**Comment by LlmDl** [comment]
I will need to see your permission file.

**Comment by soloyolorolo** [comment]
> I will need to see your permission file.

Ok permissions file is permissions.yml I am assuming, give me a minute and I'll get a link to google drive for it.

**Comment by soloyolorolo** [comment]
https://drive.google.com/file/d/14DwVl5GUsz815cNmNSWF5bK0EoUTsvkH/view?usp=sharing

**Comment by LlmDl** [comment]
Derp, I just realized you don't have any other permission plugin. If the permissions.yml is blank then don't worry about it.

What you can do is use the /ta toggle debug command, then have the outside perform those tests. The log will show what Towny thinks is happening. Please show me what debug messages you get.

**Comment by soloyolorolo** [comment]
10-4 will attempt to now

**Comment by soloyolorolo** [comment]
These looked like the important bits, I can put my entire latest log up if necessary however

[14:32:52] [Server thread/INFO]: [Towny] Debug: TerraMCyoutube (world,-14,17) Cached Status: OUTSIDER
[14:32:52] [Server thread/INFO]: [Towny] Debug: TerraMCyoutube (world,-14,17) Cached Destroy: true
[14:32:52] [Server thread/INFO]: [Towny] Debug: New Cache Created and updated!
[14:32:52] [Server thread/INFO]: [Towny] Debug: New Cache permissions for GRASS_BLOCK:destroy:OUTSIDER = true
[14:33:02] [Server thread/INFO]: [Towny] Debug: Redstone_hands (world,-14,17) Cached Status: TOWN_OWNER
[14:33:02] [Server thread/INFO]: [Towny] Debug: Redstone_hands (world,-14,17) Cached Destroy: true
[14:33:02] [Server thread/INFO]: [Towny] Debug: New Cache Created and updated!
[14:33:02] [Server thread/INFO]: [Towny] Debug: New Cache permissions for GRASS_BLOCK:destroy:TOWN_OWNER = true
[14:33:14] [Server thread/INFO]: TerraMCyoutube issued server command: /town
[14:33:17] [Server thread/INFO]: [Towny] Debug: Cache permissions for destroy : true
[14:33:22] [Server thread/INFO]: Redstone_hands issued server command: /town
[14:33:40] [Server thread/INFO]: Redstone_hands issued server command: /resident toggle map
[14:33:57] [Server thread/INFO]: TerraMCyoutube issued server command: /town
[14:34:14] [Server thread/INFO]: Redstone_hands issued server command: /town set perm ?
[14:34:26] [Server thread/INFO]: Redstone_hands issued server command: /town set perm outsider destroy off
[14:34:35] [Server thread/INFO]: [Towny] Debug: TerraMCyoutube (world,-14,17) Cached Status: OUTSIDER
[14:34:35] [Server thread/INFO]: [Towny] Debug: TerraMCyoutube (world,-14,17) Cached Destroy: true
[14:34:35] [Server thread/INFO]: [Towny] Debug: New Cache Created and updated!
[14:34:35] [Server thread/INFO]: [Towny] Debug: New Cache permissions for DIRT:destroy:OUTSIDER = true
[14:34:37] [Server thread/INFO]: [Towny] Debug: TerraMCyoutube (world,-14,17) Cached Status: OUTSIDER
[14:34:37] [Server thread/INFO]: [Towny] Debug: TerraMCyoutube (world,-14,17) Cached Destroy: true

**Comment by soloyolorolo** [comment]
To be clear TerraMCyoutube is not a resident of the town.
And Redstone_hands is the mayor of the town.

Heres my second test log:

https://pastebin.com/raw/8McXrLgP

This one went from the point I put it in debug mode to the point I disconnected from the server, its a bit neater.

**Comment by LlmDl** [comment]
The plot being tested, what does it read when you use /plot perm

**Comment by soloyolorolo** [comment]
I'll have to retest, but if thats the command I think it is, it read with build destroy item_use and switch, r---, for the other permissions it was normal on and off. I even tested explosions, and explosions did not break blocks in claimed plots. I will retest now

**Comment by soloyolorolo** [comment]
Yes, I was correct. For build, destroy, item_use, and switch it displayed r---

here is the log:
https://pastebin.com/raw/vY16Yzdi

**Comment by soloyolorolo** [comment]
Give me a second and I'll get you a screenshot

**Comment by soloyolorolo** [comment]
![2020-02-20_15 17 38](https://user-images.githubusercontent.com/61290689/74979447-44d29b00-53f4-11ea-8e27-bd0843e62b73.png)

**Comment by LlmDl** [comment]
Certainly doesn't make a lot of sense. If you want to give me the server address I'll pop on and see what I can see.

**Comment by soloyolorolo** [comment]
Sorry. Unfortunately no can do, currently the server is set up as a localhost as I am testing and configuring the server at the moment. I plan on paying for a server in the next few days, I'll try doing making a quick demonstrating the bug as in-depth as possible. If it can not be resolved from there I can try messaging you once the server is up to do further debugging. I appreciate your help none the less.

**Comment by LlmDl** [comment]
No one else is having this issue so it's probably just something mis-configured. Figure out how to port forward and I'll be able to join.

**Comment by soloyolorolo** [comment]
Will do

**Comment by soloyolorolo** [comment]
192.168.49.216 
You should be able to connect to the server using this, be forewarned, my wifi is not the best

**Comment by soloyolorolo** [comment]
My bad on the previous post that was my local IP, that would only work over LAN. Gonna figure out this port forwarding thing

**Comment by soloyolorolo** [comment]
For now I'm going to close this issue, I will come back once the server is up and running to get this debugged. Thank you for your help none-the-less, and this is a pretty incredible plugin, most likely some mistake I made is causing this, given that no one else seems to be running into this problem.

**Comment by soloyolorolo** [comment]
Alrighty got a server up for it, heres the IP: 23.95.9.6:25654

**Comment by soloyolorolo** [comment]
I'll keep the server up and running and check back every half hour or so to see if someone else has joined, I'll check back in 10 min, then 30 min from there.

I'll check back at 7:30PM EST
Then 8:00PM EST

**Comment by LlmDl** [comment]
I won't be able to pop in tonight. Join the discord and @ me so I can contact you tomorrow.

**Comment by soloyolorolo** [comment]
Sounds good man, thank you for your help, and I'll get in contact with you tomorrow.

**Comment by LlmDl** [comment]
Third party plugin was teh culprit here.
