### ISSUE TITLE
Suggestion: Town Merge

### ISSUE THREAD

**Issue by MineHero43** [TownyAdvanced/Towny#3713]
I think it would be pretty neat if there was a way for a town to be able to merge with a neighbouring one without having to disband and let the neighbour over claim it.

Perhaps a /t merge (name of town you’d like to merge with) command could be implemented. All citizens would also be transferred over to the new town.

The idea is pretty basic and would be quite useful imo

**Comment by LlmDl** [comment]
Duplicate https://github.com/TownyAdvanced/Towny/issues/3193
