### ISSUE TITLE
Question: Message unclear

### ISSUE THREAD

**Issue by OskyEdz** [TownyAdvanced/Towny#3716]
Can we change the following message?

msg_unable_ally_offline: "&cUnable to request an alliance because the mayor of the target nation is offline."
to something that make more sense.
It should be "king of the target nation" or "mayor of the target nations capital"

**Comment by LlmDl** [comment]
I've double-checked and that language string is no longer used.

**Comment by OskyEdz** [comment]
Sorry! Should have specified:
msg_unable_ally_offline
Line 212 in english.yml master branch.
https://github.com/TownyAdvanced/Towny/blob/master/resources/english.yml

**Comment by LlmDl** [comment]
It is there, but it is not used any longer.

**Comment by OskyEdz** [comment]
I'm working my way through the file, it is ~1000 lines of messages.
I don't mean to put anyone on the spot here. It would be helpful if the file was sorted. (I gather it's still there due to backwards compact?) 

I guess I could sort it, as it is not really a priority for anything to work exactly...just to help other translators only translate strings used by the plugin.

It may take some time, but would it be okay if did that? Put all of the unused strings below something named "Unused strings - Doesn't need translation"

**Comment by LlmDl** [comment]
The number of unused strings won't amount to very many, which is part of why they aren't removed.

If you sort the strings it won't really matter very much on my end of things, but as I add new strings I will continue to add them in groups ie: # Added in 0.72, as there's not much need to have them sorted once a file has had it's translation completed.

**Comment by OskyEdz** [comment]
That is true and I figured it would not be many. 
I'm sorry for this, I just wanted to speak my mind.
