### ISSUE TITLE
Error on create town

### ISSUE THREAD

**Issue by Curtis73** [TownyAdvanced/Towny#3717]
### What steps will reproduce the problem?
1. Use Gringotts as economy plugin
2. Run /t create
3. Money is not taken, and error is thrown

### What is the expected output?
1. Run /t create
2. Money is taken 
3. Town is created

### What is your Towny version?
0.95.2.18

### What is your spigot/craftbukkit version?
1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/gmsmn8cj
2. Your Towny config.yml : https://pastebin.com/XMFakV51
3. Your townyperms.yml : https://pastebin.com/iPG8b7QZ
4. Your log's error : https://pastebin.com/XtneL8ns

I have also tested this on Towny version 0.95.2.0, creating a town worked fine, but /t deposit returned "not enough money" and didn't function, but no error was thrown.

**Comment by suneettipirneni** [comment]
Gringotts currently does not support the latest versions of towny you need to ask the developer to update it. For now, you'll have to stick with a towny version less than 0.96.2.13.

**Comment by LlmDl** [comment]
This is being tracked here: https://github.com/nikosgram/Gringotts/issues/30
