### ISSUE TITLE
Suggestion: Limit of citizens in a town without a nation

### ISSUE THREAD

**Issue by luckybl0ck** [TownyAdvanced/Towny#3720]
**Please explain your feature request to the best of your abilities:**

The limit of citizens in a town without a nation will be a very useful feature in some cases. This will allow more frequent wars between nations, which will increase activity on the servers.

**Comment by Darutan92** [comment]
I also wanted to say on a similar proposal that it would be great if there was a **separate limit of citizens for the capital of the nation**.

**Comment by LlmDl** [comment]
@Darutan92 That suggestion will need its own ticket.
