### ISSUE TITLE
Town kicked from nation string reusing same town name over and over

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3721]
### What steps will reproduce the problem?
At day change, towns that are getting kicked from their nation for not paying tax appear to repeat the same town name over and over. Potentially charging that town instead of the others.

### What is the expected output?
Towns are properly charged for their nation taxes.

### What is your Towny version?
0.95.2.17

### What is your spigot/craftbukkit version?
Paper-105 MC 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

config.yml: https://hastebin.com/agalovunub.coffeescript

Relevant error/log:

https://hastebin.com/yewogijaco.coffeescript

**Comment by LlmDl** [comment]
fixed as of 0.95.2.19
