### ISSUE TITLE
Could not pass event AsyncChatHookEvent to chat plugin

### ISSUE THREAD

**Issue by MinecraftAdmin** [TownyAdvanced/Towny#3722]
### What steps will reproduce the problem?
1. Updated towny to 0.95.2.19 from 0.95.2.15

### What is the expected output?
1. It should work fine with DeluxeChat 1.15.0

### What is your Towny version?
0.95.2.19

### What is your spigot/craftbukkit version?
1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/Ba9kCcVr
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/raw/fNHLPp4Z
3. Your townyperms.yml : https://pastebin.com/raw/nx7QUgz6
4. Your log's error : https://pastebin.com/raw/Egcq7B6c

**Comment by suneettipirneni** [comment]
@MinecraftAdmin this is caused by an outdated TownyChat download the latest version here: https://github.com/TownyAdvanced/TownyChat/releases

**Comment by LlmDl** [comment]
@suneettipirneni He's using the latest TC 0.66 already.

**Comment by LlmDl** [comment]
This is fixed as of 0.95.2.20, of which here is an advance copy: https://cdn.discordapp.com/attachments/388338495036456960/682923243837063202/Towny-0.95.2.20.jar

Make sure that when 0.95.2.20 is actually released you update again as there will probably be more added.
