### ISSUE TITLE
Exception when player attempted to tab complete

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3723]
### What steps will reproduce the problem?
Running `/ta town Ottomans set mayor GinoDiamond` caused an internal server error and did not tab complete his name. Every letter typed in "GinoDiamond" led to a separate error.

### What is the expected output?
Tabcompletes their name.

### What is your Towny version?
0.95.2.19

### What is your spigot/craftbukkit version?
Paper 105 MC 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/wiqezirovu.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/ihoqoqorur.coffeescript
3. Your townyperms.yml : https://hastebin.com/jezosesuji.php
4. Your log's error : https://hastebin.com/kipazisafo.sql

**Comment by LlmDl** [comment]
Is GinoDiamond part of the Town yet?

**Comment by bartyrealms** [comment]
Yes, they were a resident of the town and I set them as mayor.

**Comment by LlmDl** [comment]
Could not reproduce using /ta town NAME set mayor NAME or with /ta set mayor TOWNNAME MAYORNAME.

**Comment by stzups** [comment]
@bartyrealms 
I found this issue to be reproducible and was able to fix it in [this commit](https://github.com/TownyAdvanced/Towny/commit/e9d57049d6b78787748de9f374b7cbd387e61c83). Thanks for bringing this up, as it turns out certain subcommands similar to the example you gave from /townyadmin did not work at all because of this issue.
