### ISSUE TITLE
`/res jail` doesn't error on invalid subcommands

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#3726]
### What steps will reproduce the problem?
1. `/res jail foo`

### What is the expected output?
1. Some sort of error, as opposed to nothing.

### What is your Towny version?
`0.95.2.20`

### What is your spigot/craftbukkit version?
`git-Paper-243 (MC: 1.14.4)`

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: Nothing interesting.
2. Your Towny config.yml (if using MySQL please remove password,): Not relevant.
3. Your townyperms.yml: Not relevant
4. Your log's error: None.

**Comment by LlmDl** [comment]
You do not say whether the tester should be jailed or not.

**Comment by LlmDl** [comment]
Also the config is relevant, include it. Do not skip the form in the future.

**Comment by stzups** [comment]
This is a common problem on many towny commands when giving improper subcommands - either no error will be given or an irrelevant/unhelpful error will be given.

**Comment by LlmDl** [comment]
Currently if bail isn't enabled you get a message saying bail isn't enabled.

If the player isn't jailed there's no feedback.

If the player is jailed they see the help when given an improper subcommand like foo.

The only time there's no feedback is if the player isn't jailed.

**Comment by MilesBHuff** [comment]
@LlmDl 
The tester is not jailed.
Towny Config: https://github.com/SettleScape/server/blob/master/plugins/Towny/settings/config.yml
Towny Perms: https://github.com/SettleScape/server/blob/master/plugins/Towny/settings/townyperms.yml

**Comment by MilesBHuff** [comment]
The way we encountered this, was a player was trying to jail someone, and was incorrectly using the `/res` command.

**Comment by MilesBHuff** [comment]
Thanks for the quick fix!  Sorry for the lack of info;  will include next time.
