### ISSUE TITLE
Default block_delete config incorrect Bed item ID

### ISSUE THREAD

**Issue by BlatantDecoy** [TownyAdvanced/Towny#3727]
See default config.yml here: https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml

### Issue:
The default config has BED_BLOCK listed under block_delete which causes the block delete task to fail and stop processing any blocks after it.

This can be easily tested by adding BED_BLOCK to mayor_plot_delete and running /plot clear, getting the message "Invalid 'BED_BLOCK' property."

### Solution:
Change the default entry BED_BLOCK in config.yml to `WHITE_BED,ORANGE_BED,MAGENTA_BED,LIGHT_BLUE_BED,YELLOW_BED,LIME_BED,PINK_BED,GRAY_BED,LIGHT_GRAY_BED,CYAN_BED,PURPLE_BED,BLUE_BED,BROWN_BED,GREEN_BED,RED_BED,BLACK_BED`

**Comment by LlmDl** [comment]
Good catch.

**Comment by LlmDl** [comment]
Fixed as of 0.95.2.21
