### ISSUE TITLE
Question: Towny pre-release v0.95.2.20 and release 0.95.2.0 list "null" for any numeric value in /towny prices?

### ISSUE THREAD

**Issue by dielfrag13** [TownyAdvanced/Towny#3729]
Hi Towny devs,

I am running towny out of the box (no config changes) on a locally-hosted Spigot 1.15.2 server, JRE 13, running the Vault API and PhantomEconomy (https://www.spigotmc.org/resources/phantomeconomy-your-hassle-free-economy.75053/) and i'm receiving these price querying command outputs that I know aren't proper. One screenshot is for /towny prices, and the other is just /t. Note that this occurs for both the most recent pre-release (v0.95.2.20) and the most recent official release (0.95.2.0). 

![image](https://user-images.githubusercontent.com/11789604/75631526-ec985780-5bb0-11ea-82e9-13ce02e19b6a.png)

![image](https://user-images.githubusercontent.com/11789604/75631535-ffab2780-5bb0-11ea-9157-b799c3db0eca.png)

Now, I have a buddy who hosts a server on Ramshard. That server is running Java 9. It's having the same null output value problems when ran out of the box. 

I am able to still create new towns and claim plots of land for the prices indicated in the config file (as I discovered by doing some subtraction by checking my account balance before and after creating a new town/claiming a new plot for the test town); it appears that the only issue is that the numeric value is null when using these price querying commands. 

Is this a problem with how the config file is set up out of the box, or is this a bug, or does it perhaps have something to do with my economy plugin? What economy plugin do you recommend we use? I'm happy to switch it up.

I'm also happy to provide other information upon request. 

Thanks for your time! I appreciate all that you do for the Minecraft server community :)

**Comment by LlmDl** [comment]
Re-file as a bug ticket and don't skip the form.
