### ISSUE TITLE
Beta 0.95.2.20 - T Buy Bonus #, no response/reaction.

### ISSUE THREAD

**Issue by LigerXT5** [TownyAdvanced/Towny#3730]
### What steps will reproduce the problem?
1. Run: /t by bonus 1 (or any number)
2. Run /t, check Town Size "[Bought #/150]"

Does respond if you don't have a number, or use something other than a number.
Minor bug: Using "/t buy bonus" results in "Must specify amount. Eg: /town buy bonus # 54" probably shouldn't have a # before 54?

### What is the expected output?
1. Chat response acknowledging the purchase?
2. Town Size Bought field showing an increase before the /
3. If there is an issue, a response in chat?

### What is your Towny version?
Beta 0.95.2.20

### What is your spigot/craftbukkit version?
[12:40:14 INFO]: This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[12:40:14 INFO]: Previous version: git-Paper-118 (MC: 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Startup Log, from last restart: https://pastebin.com/6LXF63nx
2. Towny Config: https://pastebin.com/zgmuxP1R
    I'm aware there has been minor config changes over the time, with the test builds, I've been trying to keep up on them as they come out.
3. townyperms.yml: https://pastebin.com/gEnNd7uX
4. Your log's error : None...

I've checked permissions, and saw no Bonus perm, exception of the TownyAdmin give bonus command. Saw a recent ticket similar to this, #2810 however I have something wrong on my part, which I think I just need a second set of eyes.

**Comment by LlmDl** [comment]
You have using_economy false in your config, so how do you plan to be buying bonus townblocks?

**Comment by LigerXT5** [comment]
That's one I didn't think of checking. Currently the server is small, and didn't have economy set to true, as general money use was still fresh.
Thanks for catching that. I'll give that a test. Thanks!

**Comment by LlmDl** [comment]
Let me know how it goes, I've already just now added a using_economy: true test to the /t buy command, so it will fail earlier on if the economy isn't enabled for Towny.

**Comment by LigerXT5** [comment]
It indeed works. Thank you!
