### ISSUE TITLE
Towny pre-release v0.95.2.20 and release 0.95.2.0 list "null" for any numeric value in /towny prices? 

### ISSUE THREAD

**Issue by dielfrag13** [TownyAdvanced/Towny#3732]
Didn't know if this was actually a bug or my own incompetence at server management but this is a result of a request to refile from https://github.com/TownyAdvanced/Towny/issues/3729. 

### What steps will reproduce the problem?
1. Download Towny (pre-release 0.95.2.20 from Spigot or stable release 0.95.2.0 from the assets section of https://github.com/TownyAdvanced/Towny/releases/tag/0.95.2.0) 
2. place the jar(s) in the plugin folder in the Spigot server files
3. start the server
4. log in; run /towny prices

![image](https://user-images.githubusercontent.com/11789604/75631872-d4760780-5bb3-11ea-9207-9756a11f35bd.png)

or run /t after making a new town: 
![image](https://user-images.githubusercontent.com/11789604/75631526-ec985780-5bb0-11ea-82e9-13ce02e19b6a.png)

### What is the expected output?
1. Numeric values corresponding to the config files should be printing where the 'null' values are currently printing in the output

### What is your Towny version?
0.95.2.0 is what the information in this ticket is related to, but identical results occur when running with 0.95.2.20

### What is your spigot/craftbukkit version?
Spigot 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log : https://pastebin.com/f0mXUy5z
2. Your Towny config.yml: https://pastebin.com/Jh0C4hcm
3. Your townyperms.yml : https://pastebin.com/b38FEK3T
4. Your log's error : no log errors; just unexpected output

(optional) If this is to do with permissions, 
5. Your permissions file : (no permissions plugin included)

(optional) If this is to do with chat,
-- don't think these are the droids we're looking for, but here goes anyway
6. Your chatconfig.yml : https://pastebin.com/ViQJUTub
7. Your channels.yml : https://pastebin.com/W3N9Kkdg

More information can be found in my question ticket https://github.com/TownyAdvanced/Towny/issues/3729 which i created while still thinking this was possibly due to administrative incompetence on my part. 

Thank you for looking into this!

**Comment by LlmDl** [comment]
It appears as though phantomeconomy is stopping Towny from doing things to the economy accounts. From your log: 

```[12:00:07] [Craft Scheduler Thread - 11/ERROR]: [PhantomEconomy] §7Prevented an external plugin from an interaction with the economy!
[12:00:07] [Craft Scheduler Thread - 11/ERROR]: [PhantomEconomy] §7§8 - §7Attempted to removeBalance where amount =< 0.
[12:00:07] [Craft Scheduler Thread - 11/ERROR]: [PhantomEconomy] §7§8 - §7Specified amount: §a0.0§7, Specified UUID: §a4dd034bb-7a51-3853-852b-b3f6c184b76a§7.
[12:00:07] [Craft Scheduler Thread - 11/ERROR]: [PhantomEconomy] §7§8 - §7Please notify the author of such plugin of this as they are using the method incorrectly.
[12:00:07] [Craft Scheduler Thread - 11/INFO]: [Global Message] [test ] couldn't afford to remain a town.```

The null messages could also potentially be a similar issue? I've never seen PhantomEconomy being used before so I don't know if it is incompatible or just mis-configured. You might want to test using a different economy plugin, as your Towny's config looks fine re: costs.

**Comment by dielfrag13** [comment]
I saw that, but that only happens when any plugin attempts to remove a balance of 0 or less. How would that contribute towards every numeric value in `/towny prices` being null? 

I have written my own plugins that check balances just fine using the API, and phantomEconomy doesn't complain.

If there is something i'm missing here and it does have something to do with the removeBalance amount <=0 thing that Phantom was complaining about, i'm happy to try a different economy plugin that you know works with Towny. What would you recommend?

**Comment by LlmDl** [comment]
Common eco plugins include theneweconomy, my fork of iconomy or hyperconomy.

**Comment by LlmDl** [comment]
So I just tested your config and my iconomy and there's no issue.
Then I tested using phantomeconomy and everything returns null as you said it does.

Going to guess that PhantomEconomy is still new enough that it has some kinks to work out.

**Comment by dielfrag13** [comment]
Sounds good. Thank you for looking into this for me! I was just looking through [your repos](https://github.com/LlmDl?tab=repositories) for a fork of iconomy and didn't see anything; any chance I could get you to drop me a link?

Also, does your iconomy plugin implement Vault? I have some other written-in-house plugins of mine that use Vault, so fingers crossed it does 🤞

**Comment by LlmDl** [comment]
Found it:

https://github.com/lokka30/PhantomEconomy/blob/master/src/main/java/io/github/lokka30/phantomeconomy/utils/EconomyImplementer.java#L37

When we ask for the formatted balance (ie, a cost with a dollar symbol or w/e is configured,) PhantomEconomy is returning null.

Here's my ico5 fork: https://github.com/iconomy5legacy/iConomy I cannot guarantee it will receive many updates but it also likely wont need any.

**Comment by dielfrag13** [comment]
Oh wow. I'm quite impressed with how quick you found/noticed that. 

I'm still pretty new to the minecraft plugin dev world; one day I might be at a level where I can find sources of problems that quickly ;) 

Thanks again for looking into this with me! I appreciate it.

**Comment by lokka30** [comment]
Thank you for pointing where I didn't use Vault correctly, simplifies things a bunch!
