### ISSUE TITLE
Missing tab completions

### ISSUE THREAD

**Issue by pvvvo** [TownyAdvanced/Towny#3733]
### What steps will reproduce the problem?
1. /ta town new testnametown pvv(or any name)
2. /ta town toggle w
3. /t m
4. /plot perm h

### What is the expected output?
1. /ta town new testnametown pvvvo
2. /ta town toggle war (instead of withdraw as it shows)
3. /t mayor
4. /plot perm hud

### What is your Towny version?
Preview of .21

### What is your spigot/craftbukkit version?
Paper(243) 1.14.4-R0.1-SNAPSHOT

**Comment by stzups** [comment]
By /ta town toggle war I think you mean /ta toggle war.
