### ISSUE TITLE
Suggestion: Persistent /towny spy

### ISSUE THREAD

**Issue by pvvvo** [TownyAdvanced/Towny#3737]
**Please explain your feature request to the best of your abilities:**
It's so much easier to persiste in `/towny spy` mode, than enable it everytime I re-join on the server or change from channels.

**Comment by LlmDl** [comment]
This is something that can be done already if your permission plugin supports info/option nodes:

https://github.com/TownyAdvanced/Towny/wiki/Towny-Permission-Nodes#infooption-nodes

the towny_default_modes supports the spy mode.
