### ISSUE TITLE
Moving homeblock should have confirmation when it would result in town being too far from their nation.

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/Towny#3740]
(This could also apply to other systems which use town capturing)

### What steps will reproduce the problem?
1. Town-max-distance-from-nation must be configured on the server
2. Get town occupied  (i.e. harass powerful Neighbour until they attack, defeat and capture you)
3. Move town homeblock to be very far from the enemy capital
4. Town (apparently) gets removed from nation

### What is the expected output?
1. Not sure.  Either the homeblock move should be prevented, or the nation kick should be prevented. Either way, the town should not be able to escape in this way.

### What is your Towny version?
siegewar dev/trial version of 1.13.2 compatibility branch

### What is your spigot/craftbukkit version?
This was reported by a player on 1.13/2

**Comment by LlmDl** [comment]
The nation-requires-proximity is a feature that can be turned off. That being said, when the feature is on there should probably be a confirmation the commandsender needs to confirm, which will warn the mayor they will be removed from their nation if they continue.

**Comment by LlmDl** [comment]
Likewise if a capital city is moving their homeblock, the mayor should probably be made aware if any of the nation's towns will be removed from the nation.
