### ISSUE TITLE
Error: TownMobPVM:ItemFrame is not an acceptable living entity.

### ISSUE THREAD

**Issue by Darkweasam** [TownyAdvanced/Towny#3742]
### What steps will reproduce the problem?
No idea

### What is your Towny version?
0.95.2.20

### What is your spigot/craftbukkit version?
paper 152

I get a spam of this:
Startup [18:41:04 WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: TownMobPVM:ItemFrame is not an acceptable living entity.

Default generated folder

**Comment by LlmDl** [comment]
Skipped form. Resubmit.

**Comment by Darkweasam** [comment]
> 
> 
> Skipped form. Resubmit.

Whats the point of linking the default generated folder? smh...

**Comment by LlmDl** [comment]
Because you can't have a default generated folder and get that error. I just tested it on my end now too.

**Comment by Darkweasam** [comment]
Could it be this?

  # Protect living entities within a town's boundaries from being killed by players.
  mob_types: Animals,WaterMob,NPC,Snowman,ArmorStand,Horse,ItemFrame

**Comment by LlmDl** [comment]
Yes it would be exactly that.
