### ISSUE TITLE
Suggestion: Remove 0 plot towns

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3746]
**Please explain your feature request to the best of your abilities:**

Having 0 plot towns doesn't make much sense so I think they should either be deleted when the last plot is unclaimed or the last plot shouldn't be possible to remove.

**Comment by LlmDl** [comment]
This one could be tricky, as /t unclaim all is a command, and as far as I can remember you can /t unclaim your single plot.

The over-all idea behind this is to stop landless towns interfering in nation-conflicts though?

Perhaps a town.isLandless() test could be added to areas of Towny that shouldn't let landless towns take part.

**Comment by LlmDl** [comment]
- New Config Option: plugin.day_timer.delete_0_plot_towns
    - Default: false
    - Whether towns with no claimed townblocks should be deleted when the new day is run.
    - Closes #3746.

/t unclaim all can be blocked by revoking the permission node for the command.

Only other scenario for losing all your land is via war, already confirmed that you cannot unclaim your townblock using /t unclaim.
