### ISSUE TITLE
/plot evict cannot be executed by non-mayors

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3748]
Our chancellor rank is supposed to have access to basically all mayor commands but for some reason cannot use `/plot evict` even though it has `towny.command.plot.*`

https://github.com/EarthMC/Issue-Tracker/issues/962

[townyperms.yml](https://github.com/TownyAdvanced/Towny/files/4302137/townyperms.txt)

**Comment by LlmDl** [comment]
```
				} else if (split[0].equalsIgnoreCase("evict")) {

					if (!townyUniverse.getPermissionSource().testPermission(player, PermissionNodes.TOWNY_COMMAND_PLOT_EVICT.getNode()))
						throw new TownyException(TownySettings.getLangString("msg_err_command_disable"));

					if (TownyAPI.getInstance().isWarTime())
						throw new TownyException(TownySettings.getLangString("msg_war_cannot_do"));
					
					if (!townyUniverse.getPermissionSource().testPermission(player, PermissionNodes.TOWNY_COMMAND_PLOT_ASMAYOR.getNode()))
						throw new TownyException(TownySettings.getLangString("msg_err_command_disable"));
```
My first guess was that the towny.command.plot.asmayor node wasn't being given but it is part of towny.command.plot.*.  The only thing I can see off the hop is you're missing an assistant rank. You're using LuckPerms right?

**Comment by KarlOfDuty** [comment]
Yes, we are using LP. And is the assistant rank required? I thought it was just one of the default custom ranks?

**Comment by LlmDl** [comment]
Assistant is required in order for Towny to choose a sucessor if the mayor is deleted, it could be screwing up other ranks having it missing. 

If the issue is reproduceable 100% of the time on your server I'd say try restoring the assistant ranks, if it is not 100% of the time I'd try /lp sync.

**Comment by KarlOfDuty** [comment]
Ok, will do.
