### ISSUE TITLE
Some formatting that could be fixed in /t/n online

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3754]
The extra square bracket at the end and also the weird extra space in there.

![image](https://user-images.githubusercontent.com/18099825/76168331-2815c180-616f-11ea-8460-c0d08a4c423a.png)

![image](https://user-images.githubusercontent.com/18099825/76168327-1c29ff80-616f-11ea-9b0f-d61c7583ea9a.png)

**Comment by LlmDl** [comment]
The bracket looks like it's the partner of the [Online bracket, but it's lost it's colour.

**Comment by KarlOfDuty** [comment]
Ah true, weird. Couldn't really find where the formatting is done so couldn't check it out myself.

**Comment by LlmDl** [comment]
Should be fixed as of 0.96.0.0 please let us know.

**Comment by LlmDl** [comment]
Reportedly fixed.
