### ISSUE TITLE
Database mess when removed town is recreated- resolved but possibly related to the plot deletion error

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3761]
Note: I've resolved this on my end with database edits, just recording it in case it's related to the plot deletion issues in any way.
### What steps will reproduce the problem?
1. Have a town that's mostly deleted from your db, but still exists without a home block.(They give this error on startup: https://prnt.sc/r64uut ) (They look like this in the db: https://prnt.sc/r65ion ) (These were happening for a while on my server when people ran out of money or were gone to long and towny deleted their towns.  If you went to these "towns" there were no claims at all there, but the mayors still showed as mayors in chat and /res, /t failed when attempted)
2. Have an old resident return and recreate a new town with the same name in the same spot, while the database still partially contains the old one. After he recreates it, it still doesn't have a spawn location in the db.  
3. Stop the server. Delete all other ghost towns from the db so this doesn't happen again. Restart and think towny went into safe mode again(looking over my server logs... I don't think this is what actually happened... I saw the db had no spawn location, saw a bunch of errors in the log with towny cleaning up residents of the other ghost towns I deleted at the same time and assumed safe mode.. but my log shows towny successfully booted) - shut down and delete the 'new' town from the worlds and towns table.  
4. safe mode again because the town is still in the nations table.
5. mayor tries to reclaim town, but can't reclaim the town or any blocks because they are already claimed, but the town doesn't exist.  Delete the claims from the town block table.
This fixes it. On restart, the mayor is auto removed from the resident table and can reclaim his town.
Note: this is recreated from memory and my changelog notes.  I can't promise complete accuracy.

### What is the expected output?
1. Database not retain ghost towns without a spawn location (but I think that was fixed a while back.)
2. Any existing ghost towns get cleaned out of db.
3. 

### What is your Towny version?
At the time of this mess, it was 0.95.2.15

### What is your spigot/craftbukkit version?
Do not say "latest".
At the time of this it was paper 105 (1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log :
I've got about 7 restarts on this one.. which one should I send?
2. Your Towny config.yml (if using MySQL please remove password,) :
I don't think it's relevant, but my config in that time frame was:
https://pastebin.com/5dXs4x5c
3. Your townyperms.yml :
Not relevant here.
4. Your log's error : 
Error when the old resident logs in and tries to do /t at the beginning of this:
https://pastebin.com/d459DYXy
"Error" when towny restarts and cleans up the residents from the ghost towns I deleted in the world table: 
https://pastebin.com/1JChyCxn
Error after deleting the recreated Tobi_Town from the Towns table:
https://pastebin.com/dx6DSEUn
Error after editing the new Tobi_Town out of the worlds table:
https://pastebin.com/H85xEnQy
After editing it out of the nations table:
https://pastebin.com/khm2VV7y
error when mayor tries to reclaim the town I've deleted but not removed from the town blocks table (I think that's the order here):
https://pastebin.com/mZicExr1

**Comment by LlmDl** [comment]
I already have a test branch (which you tested for me,) which does away from the homeblock repairing.  This branch also does away from saving/loading towns in the TownyWorlds, something that will be handled onload and worked upon in memory, allowing for multiple TownyWorlds to have the same Town. This makes sense when you consider that towns can exist in multiple worlds.

Going through the errors:

>Your first one is in the [TownyFormatter](https://github.com/TownyAdvanced/Towny/blob/0.95.2.15/src/com/palmergames/bukkit/towny/TownyFormatter.java#L334) when it is first trying to look up the town's pvp status, but is getting null because the town does not exist.

>Your second error link is the residents who still have records of towns that don't exist anymore.

This is probably something that Towny can handle itself. There's no reason to keep a town in a resident that doesn't exist anymore.

>Your third error is the world loading a town, this will not happen any more when I enable the new world saving/loading of towns.

>Your fourth error is the nation one.

This should probably also be handled automatically, discarding the town from the nation, unless it would be the last town in the nation in which case it should remove the nation via the EmptyNationException catch.

>Your fifth error is again the same as the 2nd, a resident storing a town that doesn't exist.

>Your sixth is interesting.

This is the sort of thing I'm going to test on my end, by creating some ghost townblocks.

**Comment by LlmDl** [comment]
Initial test: Made a 9x9 town, stopped teh server and deleted everything except the 9 files in the towny\data\townblocks\world folder.

Upon starting up again I was able to reclaim the townblocks using the same townname and did not get the PlotChangeEvent errors like you saw in your sixth log: 
```[10:55:11] [Server thread/ERROR]: Could not pass event PlayerChangePlotEvent to Towny v0.95.2.15
java.lang.NullPointerException: null
    at com.palmergames.bukkit.towny.ChunkNotification.getTownPVPNotification(ChunkNotification.java:262) ~[?:?]
    at com.palmergames.bukkit.towny.ChunkNotification.getNotificationContent(ChunkNotification.java:164) ~[?:?]
    at com.palmergames.bukkit.towny.ChunkNotification.getNotificationString(ChunkNotification.java:136) ~[?:?]```

Stopping and starting the server did not present any issue with the townblocks unclaiming.

**Comment by LlmDl** [comment]
Secondary test: Same as before using the emptied database except keeping the existing towny\data\townblocks\world folder, this time using a different name for my town, same result achieved. No errors, no disappearing townblocks.

**Comment by LlmDl** [comment]
Third test:
Start with same 3x3 town. Remove everything from database except for the townblocks.txt and towny\data\townblocks\world\ folder.

Towny started up without issue. Initial tests using /towny map showed no townblocks claimed in the area. I made the town with the same name, and was able to claim two townblocks of nine. Received error messages saying they were either already claimed or not attached to the edge.

I tried surrounding some of the original 3x3 area with new claims to see if any of the previously claimed plots would have issues.

Upon server restart the entire 3x3 town was claimed for my town (because they had the same townname) as well as the 5 new townblocks bordering them.

So while I had some spooky behaviour when Towny loaded up after breaking the database, it fixed itself and there was no loss of townblocks.

I also still did not get any plotchangeevent errors, even though I used the /plot perm hud.

**Comment by LlmDl** [comment]
Fourth test:

Using the same database as before I nuked everything but the townblocks.txt and townblocks folder. This time upon startup and activation of /plot perm hud i did start to get playerchangeplotevent errors like you did. But I am unable to claim any of the plots.

**Comment by Momshroom** [comment]
he wasn't able to claim the plots again, either, until I deleted them from the town blocks table

**Comment by LlmDl** [comment]
Sadly I have to chalk this one up to the database being manipulated/fixed manually, where the townblocks were left. This is not our mysterious vanishing townblocks issue.
