### ISSUE TITLE
Suggestion: TownyWar Module system

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3764]
Something that I've noticed lately is the interest in war systems for Towny, while currently it's entirely possible to make an external plugin to add a war system to Towny, this solution comes with a lot of overhead. Not to mention, the design differences between Towny wars and Towny the plugin itself. We should modularize the towny war system to allow for easier editing of individual war systems, and better support by third party developers.

With these modules would come a handfull of API methods used to facilitate the development of war systems.

Module jars would be placed in /Towny/warModules/

As a result we can further generalize the war commands for example
`/townywar enable <war-type>`

This would take a lot of work out of maintaining war systems as code is encapsulated in it's own jar rather stuck onto the towny codebase.

**Comment by LlmDl** [comment]
There's a fair bit of things in the CombatUtil but certainly there could be more added to it making it easier for war plugin developers.

**Comment by suneettipirneni** [comment]
Well we could just make CombatUtil and others part of the module API

**Comment by LlmDl** [comment]
Yep, give the existing tests better exposure.
