### ISSUE TITLE
Random Town Plot Unclaims

### ISSUE THREAD

**Issue by bsickinger** [TownyAdvanced/Towny#3768]
I'm on 0.95.2.22

I have only noticed it happen to admin towns with an npc set as mayor but its possible other players have had this happen in their towns as well.  A few times its seemed to happen the next day, others I know have happened over extended periods of time. I dont have any errors in console to add to this or anything just wanted to report I'm experiencing that issue on 0.95.2.22

**Comment by TheFlagCourier** [comment]
Do you happen to be using FlatFile or MySQL for data storage, and do you use a war system? If so, which?

**Comment by LlmDl** [comment]
Open a bug report ticket and don't skip the form.
