### ISSUE TITLE
Getting an error in my logs

### ISSUE THREAD

**Issue by Rabidhuman** [TownyAdvanced/Towny#3771]
### What steps will reproduce the problem?
1.Unsure

### What is your Towny version?
 0.95.2.22

### What is your spigot/craftbukkit version?
Paper 1.15.2 build 129

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log  :https://pastebin.com/FXC9Fx2t
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/4YcfAwXx
3. Your townyperms.yml :https://pastebin.com/nxqxNuE0
4. Your log's error : https://pastebin.com/4n97dwfR

**Comment by LlmDl** [comment]
Does this happen all over the place? Or just in an area where there used to be a town?

**Comment by Rabidhuman** [comment]
Unsure. Simply noticed this bug over and over in my logs

**Comment by LlmDl** [comment]
I'm guessing someone either stepped into a ghost townblock that towny thought still contained a town, or they cross over to another world maybe.

**Comment by LlmDl** [comment]
I've since added a bit of a debug message to current builds which will give us more information when this happens again.

**Comment by LlmDl** [comment]
Just to follow up this has been tracked with the new debug code and is being fixed up, with #3911 being the main ticket now.
