### ISSUE TITLE
Untranslatable in current State.

### ISSUE THREAD

**Issue by Effendil** [TownyAdvanced/Towny#3777]
Dont know why i think that but Towny is an Plugin that i many Years old and i cant imaging that nobody give feedback about the weird and complicated languagefiles that made translation unpossible.

Let me explain whats the Problem i found why i wonder that maybe neverever anyone had a problem with that.

If you had Towny in German as example it generates sentences like:

'You kann es sich nicht leisten, hier eine Stadt zu gründen. Die Kosten betragen 250.'

Is there really nobody out there that think that sounds completely weird and unprofessional? And the really sad thing is... you cant build a sentence that ignores the Placeholder... because all Placeholders are simple %s so the first %s in the Sentence the You cant be ignored because if you do so the second %s.. the Money get broken.

Maybe a Translatable Placeholdersystem can fix that or dedicated Placeholders like %target% %money% %nation% and so on are used in the translation.

Excause my really bad english. I hope i have clearly enouth descriped what i mean.

**Comment by OskyEdz** [comment]
I too understand this problem. While translating to Swedish I can most of the times avoid this, but there always be cases where the translation will come short of the meaning or present itself as clumsy.

With named placeholders, it would be easier to translate and take into account that different langues have different ways taking about money, towns and nations. Different nations have different standards.

(@Effendil could you also paste in the original string for your German translation?)
