### ISSUE TITLE
msg_changed_public is not printed properly in Korean.yml

### ISSUE THREAD

**Issue by yumjunstar** [TownyAdvanced/Towny#3779]
### What steps will reproduce the problem?
1. download korean.yml
2. change config english to korean.yml
2. make town
3. /town toggle public

### What is the expected output?
1. [타우니] Format specifier '%s'
2.
3.

### What is your Towny version?
Do not say "latest".
0.95.2.22

### What is your spigot/craftbukkit version?
Do not say "latest".

git-Paper-131

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://paste.gg/p/anonymous/3c3c5c64f3954db59cb4bb4ad09b6be9
3. Your townyperms.yml :
https://paste.gg/p/anonymous/564e3f7e836c4d2c8fc3d3ffa60f399f
4. Your log's error : 
no error
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

I don't know how to contact with translation team so I upload this on issue

**Comment by LlmDl** [comment]
Can you show me a screenshot of what you see?

**Comment by yumjunstar** [comment]
![image](https://user-images.githubusercontent.com/24960675/76720764-0fb23200-6781-11ea-9416-9da250811430.png)

**Comment by yumjunstar** [comment]
![image](https://user-images.githubusercontent.com/24960675/76720849-59028180-6781-11ea-9340-bb6a0f9ed898.png)

![image](https://user-images.githubusercontent.com/24960675/76720878-6e77ab80-6781-11ea-99e2-e86d8921df5f.png)

In korean.yml

**Comment by yumjunstar** [comment]
![image](https://user-images.githubusercontent.com/24960675/76720849-59028180-6781-11ea-9340-bb6a0f9ed898.png)

![image](https://user-images.githubusercontent.com/24960675/76720878-6e77ab80-6781-11ea-99e2-e86d8921df5f.png)

In korean.yml
@LlmDl

**Comment by LlmDl** [comment]
I spotted the issue, the trouble is there are two %s in the string when there should be only one. Can you suggest a translation for it?

The English string is ```The Town's public status is now %s.``` where %s is either enabled/disabled.

**Comment by yumjunstar** [comment]
마을 공개 설정 : %s

마을 = The Town
공개 = public
상태 = status

Thank you for helping me
![image](https://user-images.githubusercontent.com/24960675/76756939-04372900-67ca-11ea-8cd9-1dc83a041240.png)
Finally work

You should change these too
msg_changed_pvp: '&c%s의 PVP 설정 : %s.'
msg_changed_public: '&c%s 공공 설정 : %s.'
msg_changed_expl: '&c%s 폭발 설정 : %s.'
msg_changed_fire: '&c%s 불번짐 설정 : %s.'
msg_changed_mobs: '&c%s 몹스폰 설정 : %s.'

Like these
msg_changed_pvp: '&c마을 PVP 설정: %s.'
msg_changed_public: '&c마을 공개 설정 : %s.'
msg_changed_expl: '&c마을 폭발 설정 : %s.'
msg_changed_fire: '&c마을 불번짐 설정 : %s.'
msg_changed_mobs: '&c마을 몹스폰 설정 : %s.'

**Comment by LlmDl** [comment]
The other strings, beside msg_changed_public do require 2 %s in them because they are made to have 2 variables added. I can change the public message to your suggestion but I cannot change the other language strings.

The change has been made here for new files: https://github.com/TownyAdvanced/Towny/commit/757aee9ce836d31f80ca6540d7123f143f02af1b
