### ISSUE TITLE
TownBlocks being unclaimed randomly.

### ISSUE THREAD

**Issue by slvlr** [TownyAdvanced/Towny#3783]
### What steps will reproduce the problem?
1.Reports are only coming in when players are realizing they are unclaimed. I believe it is happening on Tax collection but I cannot confirm this.

### What is the expected output?
1. Outpost blocks to not be unclaimed if the town has enough balance.

### What is your Towny version?
0.95.2.23 , However I only updated to this version yesterday (I have had reports that this happened again since the update). This issue 100% also happened on the previous build. 

### What is your spigot/craftbukkit version?
Paper 1.15.2 build 137 (Always keep builds up to date) 

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/CtU3fSC7
2. Your Towny config.yml: https://pastebin.com/YZCGDF0K
3. Your townyperms.yml : https://pastebin.com/sXJdi1PG
4. Your log's error : I haven't seen any errors in the logs.

(optional) If this is to do with permissions, 
5. Your permissions file : Not permission related.

(optional) If this is to do with chat,
1. Not chat related.

Other Info:
I have checked all logs for commands of players unclaiming plots. I can confirm that these are not being unclaimed by players but randomly disappearing. 
Image of one of the player reports: 
https://media.discordapp.net/attachments/581163022874050569/689395294210621483/image0.png?width=419&height=907

**Comment by LlmDl** [comment]
Have you got the startup log preceding it becoming unclaimed?
Have you got the log from when the new day happened?

**Comment by slvlr** [comment]
@LlmDl 

This is what was in the logs when taxes were taken this morning:
https://pastebin.com/rrVDzVyS
I am not sure if any outposts were unclaimed in this as none have been reported yet. 

This is what was in the logs when taxes were taken 2 days ago. Outposts were reported to have disbanded then: https://pastebin.com/xYLRTRrm

Is this what you are asking for?
I cannot see any other towny errors/messages.

**Comment by LlmDl** [comment]
Is the startup log in the ticket the one the preceded people losing plots?

**Comment by LlmDl** [comment]
It is unlikely that the taxes are causing it, as they do not delete townblocks, only towns and nations wholesale, which leads to the townblocks being removed en masse (ie, not just an outpost and its surrounding plots, which is what I believe you're saying happened here.)

**Comment by slvlr** [comment]
From what the players are reporting, it is just outposts (and surrounding plots) that are being removed. 
This is the one  https://pastebin.com/xYLRTRrm that happened prior to the plots being deleted yes. However as you said I am not sure if this is what is causing the outposts to be removed as we can only identify them being remove when players log on and report them.

Is there anything else that I could provide to help?

**Comment by LlmDl** [comment]
How often does your server stop and start?

**Comment by slvlr** [comment]
Every day at 10:00AM GMT

Then 0-3 times extra per day if plugins have available updates on spigot.

**Comment by LlmDl** [comment]
Ok, I'm going to need to see all of the latest.log's from the startup that preceded the town claiming the outpost to now. You can share them to me via discord if you want.

It would also be helpful if you could give me the Blackwater.txt from the towny\data\towns\ folder so I can see who's a resident.

**Comment by LlmDl** [comment]
The [pre-release version 0.96.1.1](https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.1) has what I believe to be a solution to the issue of vanishing TownBlocks described in your ticket. I would appreciate it if you would consider updating to 0.96.1.1 and letting me know if you have any more vanishing TownBlocks.

**Comment by LlmDl** [comment]
This is now the main ticket for tracking the disappearing TownBlocks.

There have been no reports of TownBlocks going missing since 0.96.1.1 was released. This ticket will remain open for another 14 days.
