### ISSUE TITLE
MySQL Database issue.

### ISSUE THREAD

**Issue by GenericEntity579** [TownyAdvanced/Towny#3790]
### What steps will reproduce the problem?
1. Player leaves a town and joins a different town.
2. Data does not update that the player is now in a different town.
3. Server restarts and loads database including two towns with same player's name listed causing safemode to occur.

### What is the expected output?
1. Expected to update the playerfile on the MySQL when they join a new Town and to delete old Town data under their name.

### What is your Towny version?
 : 0.95.2.14

### What is your spigot/craftbukkit version?
 : git-Paper-136 (MC: 1.15.2)

1. Server startup : https://pastebin.com/sds9F1ye
2. Towny config.yml : https://pastebin.com/QdyXWihe
3. townyperms.yml : https://pastebin.com/0vC7S3WY
4. Log Error : https://pastebin.com/4NZSjiPD

**Comment by LlmDl** [comment]
This is somewhat common amongst Towny servers using mysql. It is usually not something we can reproduce at will and we chalk it up to poor connection to the mysql database itself. 

Can you say that it is happening every single time someone leaves/joins a town or is it just once in a while?

You should not be using 0.95.2.14, there is a bug with town/nation banks resetting when the town/nation changes its name.

**Comment by GenericEntity579** [comment]
It used to happen rarely maybe once every few days but it appears to be becoming more frequent, almost every other day and twice the past 24 hours. 

Also thanks for the heads up about 0.95.2.14.

**Comment by LlmDl** [comment]
I would suggest just moving back to flatfile, it is all operated in ram anyways so you aren't really gaining any speed. There will eventually be a recode of the entire database.

**Comment by LoXR** [comment]
Whats the command to revert all our data from MySQL to flatfile? Or do we need to export the data off the database to manually add it back to flatfile?

**Comment by LlmDl** [comment]
You can use the /ta mysqldump command or use the instructions on the How Towny Works wikipage.

**Comment by conroy-cheers** [comment]
I've had this occur 3 times over the past week in 0.96.0.0 - have lost a fair bit of player data, including town residents/mayors and outpost spawns. Come to think of it this has all been from the TOWNY_TOWNS table. Will be switching back to flatfile for now.

**Comment by LlmDl** [comment]
Starting in 0.96.1.3 we solved an issue where the save-queues would purge rather than finishing up any slow saving occuring when the server is shut down. While this isn't focused directly towards fixing mysql issues, it will likely solve some of the weirdness.

**Comment by LlmDl** [comment]
This one probably cannot happen any longer, as Residents now store their Town and Towns do not store their residents.
