### ISSUE TITLE
Suggestion: Town upgrade by tiers

### ISSUE THREAD

**Issue by Zeuscp1** [TownyAdvanced/Towny#3795]
I would love to see a mechanic where the town can be upgraded by meeting X requisite.

For example, if you have 3 people in your town and 3 houses it its a village. If  you have 6 people and a bank it is a town. If you have 12 people or more, a bank and a shop it is a city. To upgrade them it would cost money and each rank would grant a benefit. This can be worked and improved upon letting the admins decide and configure the options for this. Since i don't know what can exactly be done about this, i don't know what more to add but to put it into a perspective i would like to have this system in my server and have players build ''bank'' ''stable'' ''shop'' ''tavern'' and other stuff systematically in order to make their town better and upgrade them for money in exchange of new perks, like. Once you have the bank you will be able to collect more taxes or have your money with more security to have less stolen after losing a war or something like this.

**Comment by LlmDl** [comment]
This is outside of the scope of Towny.
