### ISSUE TITLE
Show error log when Player executing /town

### ISSUE THREAD

**Issue by suryomujahid** [TownyAdvanced/Towny#3798]
### What steps will reproduce the problem?
1. After player create new town it show "null" on chat (but the town successfully created without notification they're have been made)
2. When player execute "/town" it didn't appear anything except the log on console

### What is the expected output?
https://pastebin.com/SkghsiMz

### What is your Towny version?
 0.96.0.0

### What is your spigot/craftbukkit version?
Paper-137 (1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/6VEfjrkx
2. Your Towny config.yml (if using MySQL please remove password,) : Default
3. Your townyperms.yml : Default
4. Your log's error : https://pastebin.com/SkghsiMz

(optional) If this is to do with permissions, 
5. Your permissions file :-

(optional) If this is to do with chat,
6. Your chatconfig.yml :-
7. Your channels.yml :-

**Comment by LlmDl** [comment]
Error is on the AConomy side of things. You might have to choose another economy plugin.
