### ISSUE TITLE
/res list returns null in-game, not in console

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3800]
### What steps will reproduce the problem?
Typing /res list in-game results in this:
![image](https://user-images.githubusercontent.com/42015460/77101441-ad119e00-69ed-11ea-8d6b-6732ee6a2265.png)

### What is the expected output?
List of online users. It works in console, but not as a user in-game. Possible permissions issue?
![image](https://user-images.githubusercontent.com/42015460/77101465-b864c980-69ed-11ea-8b20-915f26bfdcb6.png)

### What is your Towny version?
0.95.2.20

### What is your spigot/craftbukkit version?
Tuinity-daa949d (Minecraft 1.15.2)

### Logs & Configs

latest.log:
https://paste.gg/p/anonymous/cd06ee683f524b4b8f1c3f5235c64272
config.yml:

https://paste.gg/p/anonymous/f1e52ed707a941f4ab8ad6c866c0e2fe

townyperms.yml:
https://paste.gg/p/anonymous/14e3babe48664e7fb7eeda2dabb0c4e3

**Comment by LlmDl** [comment]
This would appear to have been fixed by at least 0.95.2.22, please update and re-test.

**Comment by bartyrealms** [comment]
Fixed by updating to 0.96.0.0.
