### ISSUE TITLE
Towny chat not working with Ultimate Chat 

### ISSUE THREAD

**Issue by TKwSni** [TownyAdvanced/Towny#3801]
Is there any posibility to add compatibility with UltimateChat, no matter what I do, I cannot speak on the town chat, ultimatechat seems to be overriding everything

https://github.com/FabioZumbi12/UltimateChat/

### What steps will reproduce the problem?
1. Install https://github.com/FabioZumbi12/UltimateChat/
2. Install Towny Chat
3. /tc or /nc try to chat

### What is your Towny version?
0.96.0.0

### What is your spigot/craftbukkit version?
paper 1.15.2

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :  https://pastebin.com/raw/QEKgmVF6
2. Your Towny config.yml (if using MySQL please remove password,) : default
3. Your townyperms.yml : default
4. Your log's error :  no error

(optional) If this is to do with chat,
6. Your chatconfig.yml : default yml
7. Your channels.yml : default yml

**Comment by LlmDl** [comment]
I don't know if this counts as a TownyChat issue if we're being overridden by another chat plugin.

**Comment by Blackyvk** [comment]
This is the answer from the dev from uchat I found on github 
https://github.com/FabioZumbi12/UltimateChat/issues/188#issuecomment-524880107

**Comment by LlmDl** [comment]
Ok, your ticket doesn't really say what happens that isn't supposed to happen. It just gives instructions on what to do. Can you explain exactly what is happening as clearly as possible?

**Comment by Blackyvk** [comment]
When you type on /tc you should be able to type on towny chat right?

Well after you use /tc and type, you just type in the currently focused channel from  UltimateChat, instead of TC channel.

**Comment by LlmDl** [comment]
So it is not being shown in the UC and TC channels, it is only in the UC channel?

I don't see how us listening after and cancelling the chat events would solve this.

This sounds like UC is acting early on (and potentially cancelling the first chat event and maybe using their own,) and preventing TownyChat from seeing the chat at all.

**Comment by LlmDl** [comment]
A question, if you speak into a channel you're not currently using as your main chat (ie in general and using /tc sometexthere) does it work?

**Comment by Blackyvk** [comment]
no, no matter what channel I am, if I use /tc /nc all messages are being sent to ultimatechat
![2020-03-19_18-28-26](https://user-images.githubusercontent.com/9063912/77120565-87958c00-6a0f-11ea-86d2-00dc55e8368e.gif)

**Comment by LlmDl** [comment]
Yeah this one isn't on us. Make sure he's aware that you're not seeing doubled up chat (ie a townychat town channel and a UC channel.)

**Comment by LlmDl** [comment]
Closing this as it is not something on TownyChat's end.
