### ISSUE TITLE
The name of town are disappear after create town using foreign name(Thai).

### ISSUE THREAD

**Issue by thammachet** [TownyAdvanced/Towny#3803]
### What steps will reproduce the problem?
1. Create town name in thai.
2. /town new Sสวัสดี
3.

### What is the expected output?
1. In the chat it will show town name only 'S'
2. If there are none English in town name it will show ''.
3.

### What is your Towny version?
Towny-0.96.0.0

### What is your spigot/craftbukkit version?
git-spigot-800b93f-8160e29 (1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
- https://pastebin.com/rk4Kt2NN
3. Your townyperms.yml :
- https://pastebin.com/CzjzEnsx
4. Your log's error :  

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/j5Jenbyi
7. Your channels.yml :  https://pastebin.com/AJSsiGqr

**Comment by LlmDl** [comment]
You have skipped the form. The config has important information we need.

**Comment by thammachet** [comment]
> You have skipped the form. The config has important information we need.
Ok I will complete it

**Comment by suneettipirneni** [comment]
Related to #3805

**Comment by thammachet** [comment]
Thank you for fixings.
