### ISSUE TITLE
One person town not properly removed from TOWNY_TOWNS table after mayor removed for time, causing safe mode

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3806]
### What steps will reproduce the problem?
I don't know if this is reproducible, but this is what happened:
1.  Have a one person town where the mayor is removed due to the afk kick.
2. Restart the server. (note that the restart that caused this ALSO updated us to 0.96.0.0)
3. Server goes into safe mode trying to load the town, because it can't find the resident file of the mayor.  The town shows in the db as not having any residents, nor a home block, but still having the deleted resident as mayor. The town is no longer in the nation or world tables, as expected.

Oddly enough, on my test server, which updated to 0.0.96.0 BEFORE the resident was kicked, and then he was kicked in 0.0.96.0 by a /ta newday, the server did not go into safe mode on restart.

### What is the expected output?
1. Town is removed from the TOWNY_TOWNS table when the last resident is removed due to afk kick.
2.
3.

### What is your Towny version?
After the restart that caused the safe mode 0.96.0.0, prior to that (when the resident was kicked) 0.95.2.22

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 1.15.2 #132

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
This is the startup that ended in safe mode:

https://pastebin.com/DBzjWJm7

This is the mayor getting deleted from towny, from the towny log: 

2020-03-17 13:00:03,689 [Thread-789]: [Towny] Deleting resident: Kornmangobbles

That whole day in the towny log:
https://pastebin.com/QC8qLycD
(the town that fell is NOT his town.  His doesn't show falling anywhere in the log. There is no mention of him or his town in the newday AFTER that one.)

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/EnhLfeTJ

3. Your townyperms.yml :
Not relevant.

4. Your log's error : 

The town in the TOWNS table (sorry, it was very late and the server was down... should've recorded this in a better way...)
https://prnt.sc/rjed9u
https://prnt.sc/rjedxa
The rest of the row looked normal to me, but I do have more pictures of some other parts if they're relevant.  

The nation table no longer showed Fautzenville as part of Narnia, and the world table no longer had Fautzenville listed.

I do have a backup of the mysql from right before I fixed this, if it's needed.

The error trying to load and going into safe mode:
https://pastebin.com/Mx6QdFgs

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
So I traced through everything starting from the ResidentPurge task, through to the resident removal and the throwing of the EmptyTownException, the removal of the Town and the actual deletion from the sql database.

If there was an issue in deleting the town from the TOWNY_TOWN tables it should have printed out an error in the log something like ```SQL: Error delete : " + e.getMessage()```

Most of everything in between looked good as well, should have thrown some errors if something was going wrong.

We'll keep this open so I can take another look at it again.

**Comment by LlmDl** [comment]
Sadly was not able to reproduce this after numerous attempts.

**Comment by tribrix** [comment]
It happens with my server, I've just had to delete 2 one man towns from the sql database. I will be back with more details when it occurs again.

**Comment by LlmDl** [comment]
@tribrix I'd love to know how to make it happen at will if you can do that.

**Comment by suneettipirneni** [comment]
@LlmDl imagine asking someone else how to do _your_ job
