### ISSUE TITLE
Suggestion: Disable msg_claim_error when blank

### ISSUE THREAD

**Issue by Cretezy** [TownyAdvanced/Towny#3814]
I created a custom plugin to disable claiming in some areas. When cancelling the event, I sent my own error message.

It would be nice to not send the `msg_claim_error` error if it is blank, allowing me to have a custom message.

My current solution is to set `msg_claim_error` to my error and not send my own message, but this isn't scalable (can only have 1 error message)

**Comment by LlmDl** [comment]
I've made this event have a customizable cancel message, which is more in line with our other cancellable events.
