### ISSUE TITLE
Resident balance not updating after username change with HellConomy

### ISSUE THREAD

**Issue by Lambsy** [TownyAdvanced/Towny#3815]
### What steps will reproduce the problem?
1. Enter server, add money to player with 3rd party economy HellConomy 0.1.5.0.
2. Change username.
3. Enter server again, edit money, see if resident balance (/resident) matches with the balance displayed on the 3rd party economy HellConomy 0.1.5.0 (/money).

### What is the expected output?
1. For the HellConomy balance and resident balance to match after changing username.

### What is your Towny version?
Towny version 0.96.0.0

### What is your spigot/craftbukkit version?
1.15.2

### Please use Pastebin.com to link the following files:
Towny config.yml: https://pastebin.com/yPHpJ0gJ
HellConomy config.yml: https://pastebin.com/W1sg62ex
Screenshot of resident and plugin balance out of sync: https://cdn.discordapp.com/attachments/679080996838047767/691659442378244117/Screenshot_2020-03-23_10.45.11.png

**Comment by LlmDl** [comment]
Should be working in 0.96.0.5, I would appreciate if you could confirm it for me at some point.
