### ISSUE TITLE
this area is too far away from the other towns

### ISSUE THREAD

**Issue by DS9Fireblade** [TownyAdvanced/Towny#3818]
i have a player on my server looking at creating a town but whenever he or myself (owner) try to create his town it comes up with this message that the area is too far away from the other towns, how do i rectify this issue??

![2020-03-24_15 07 49](https://user-images.githubusercontent.com/28073973/77441711-a619cf80-6de1-11ea-992f-9fd0189e9e47.png)

**Comment by LlmDl** [comment]
Your config has a max_distance_between towns option that would need to be raised.

**Comment by DS9Fireblade** [comment]
I have updated the max_distance_between Home blocks to 1,000,000 and i am still getting the same message

**Comment by DS9Fireblade** [comment]
Its ok i have sorted it
