### ISSUE TITLE
Suggestion: Have /t outpost list be clickable

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#3826]
**Please explain your feature request to the best of your abilities:**

It would be a nice feature to have it so when you get the list of outposts in /t outpost list that you could click on one to execute /t outpost (the number of that outpost).

**Comment by Momshroom** [comment]
Also:
Minor fix request: currently /t outpost (plotname) appears to be case sensitive.  ie:  /t outpost gold_farm goes to /t outpost 1, even if /t outpost Gold_Farm goes to /t outpost 2 no matter what /t outpost 1 is named.
https://prnt.sc/rnd2h5
Also, it'd be nice if it accepted spaces for the underscores, but that's just gravy

**Comment by LlmDl** [comment]
Made it case insensitive, also tested and it would appear it already handles spaces. I tested with an outpost name Nether_Outpost, and /t outpost nether outpost is working for me.
