### ISSUE TITLE
Suggestion: Click-To-Spawn for `t list` and `n list`

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#3827]
Often times when on servers and browsing through towns, you see a town name and you'd like to visit it, but towny currently requires you to execute `/t spawn <townname>` What I propose is to make the listing of these towns/nations clickable, where clicking on it in the list will spawn you to the town.

**Comment by TheFlagCourier** [comment]
I think it's a great idea. As long as it respect teleport restrictions and settings.

Perhaps an additional click-event for those with `towny.admin`?
`The %townrank% of %town% is not public, spawn there anyways? [Y]/[N]`

**Comment by suneettipirneni** [comment]
> I think it's a great idea. As long as it respect teleport restrictions and settings.
> 
> Perhaps an additional click-event for those with `towny.admin`?
> `The %townrank% of %town% is not public, spawn there anyways? [Y]/[N]`
> 
> Could even add a confirmation opt-out for admins that get tired of it.

I feel like admins don't necessarily need *confirmations* usually, they have the right to do whatever on the server. However yeah the spawning will respect town perms.

**Comment by TheFlagCourier** [comment]
It's more for those who "accidentally click" while reading from it, but yeah, it's not necesary.

**Comment by Momshroom** [comment]
While not necessary, it would be a nice feature to remind admins who are also players when they are using the admin perm.

**Comment by bartyrealms** [comment]
Perhaps have hover JSON with the cost visible as well.
![image](https://user-images.githubusercontent.com/42015460/77721065-20a04600-6fc0-11ea-8df0-a201a0d8bda6.png)
