### ISSUE TITLE
Suggestion: Add more placeholders for Dynmap-Towny

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3829]
**Please explain your feature request to the best of your abilities:**
![image](https://user-images.githubusercontent.com/42015460/77721542-8d681000-6fc1-11ea-9e62-61749334ed20.png)

Currently the available placeholders for Dynmap-Towny are:
%regionname%, %playerowners%, %playermanagers%, %playermembers%, %nation%, and %flags.

I suggest that some more placeholders be added. Some ideas:

%residentamount%: returns the amount of residents in a town
%founded%: returns the founded date of a town
%board%: returns the town board
%tax%: returns the tax burden of each player (25% or $500)
%bank%: returns the amount of money in the towny bank
%upkeep%: returns the daily amount of upkeep that this town pays
%nationstatus%: returns 'Capital of Nation' or 'Member of 'Nation'

Additionally, add %playermembers_displayname% to show nicknames instead of minecraft names.

**Comment by LlmDl** [comment]
This one is completed as of Dynmap-Towny 0.76
