### ISSUE TITLE
Balance desync after name change

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#3840]
### What steps will reproduce the problem?
1. Change your name 
2. Something unknown occurs? (seems rare)
3. Attempt depositing any money or use /res
4. Confirm the econ plugin works and the balance exists

### What is the expected output?
1. Balance within towny should be the same as the balance of the economy plugin
2. Player should be able to deposit money that they have in their vault hooked econ plugin

### What is your Towny version?
Do not say "latest".
0.95.2.23

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 214 (1.14.4)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/asxxbBZ5
2. Your Towny config.yml  : https://pastebin.com/ydeVKcMg
3. Your townyperms.yml : https://pastebin.com/bcqv0d0t
4. Your log's error : N/A

A user changed his username and now there's no balance listed for him in towny, even though in TNE his balance is still 88k and is visible when doing /balance. When I inspect his balance through /res username, it shows 0.00. He's still apart of his town after changing his name, so townynameupdater worked. All of the other plugins recognize his balance, but towny seems to not recognize the balance.

**Comment by JohnS19** [comment]
https://prnt.sc/roo2ne

The previous usernames correctly have no towny files associated with them anymore.

**Comment by JohnS19** [comment]
Withdrawing $10 from the towny leads to the /res balance gaining $10 but the vault economy plugin does not change. 

It seems like a second economy account was created? Not exactly sure how that's possible or what name it's under...

**Comment by JohnS19** [comment]
Looks like it's depositing and withdrawing to the old username... 

Not sure why that is occurring and whether it's failing from TNE's end or Towny...

**Comment by LlmDl** [comment]
Should be fixed as of 0.96.0.5, if you could confirm it is working when .5 is out that would be great.
