### ISSUE TITLE
Cannot download Towny

### ISSUE THREAD

**Issue by Klawdek** [TownyAdvanced/Towny#3841]
### What steps will reproduce the problem?
1.  Try to download towny
2.  Click on the links that promise the download
3.  It just goes around and you end up on a page with the same links as you started.

### What is the expected output?
1.   A file downloaded
2.
3.

### What is your Towny version?
Do not say "latest". 
I don't have any version until I am able to download.

### What is your spigot/craftbukkit version?
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
From the main github page's readme section:
![capture1](https://user-images.githubusercontent.com/879756/77850444-46804300-7198-11ea-9685-0fd004a4fb3f.PNG)

After choosing the current release version:
![capture2](https://user-images.githubusercontent.com/879756/77850446-48e29d00-7198-11ea-86a2-553030208ca5.PNG)
Scroll all the way to the bottom....
![capture3](https://user-images.githubusercontent.com/879756/77850447-4d0eba80-7198-11ea-8520-400f6b4e017d.PNG)
Downloads are always listed under Assests.


Does this make it clearer?

**Comment by Klawdek** [comment]
It was just a temporary glitch. When I clicked the link it just reloaded the page.  It seems to be working now.  Thank you for the reply.  I should have waited a bit longer before posting it here.
