### ISSUE TITLE
Russian on 0.93.1.0 for 1.12.2

### ISSUE THREAD

**Issue by SiriusWhite74** [TownyAdvanced/Towny#3842]
### What steps will reproduce the problem?
1. Change regex to work with the symbols of the Russian alphabet:
name_filter_regex: '[ /]'
name_check_regex: ^[а-яА-Яa-zA-Z0-9.[]-]*$
string_check_regex: ^[а-яА-Яa-zA-Z0-9\s.\а-яА-Я[]-]*$
name_remove_regex: '[^а-яА-Яa-zA-Z0-9._[]-]'
2. Start the server

### What is the expected output?
1. Working server

### What is your Towny version?
0.93.1.0 for 1.12.2

### What is your spigot/craftbukkit version?
cat server 1.12.2 (based on Spigot)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://ghostbin.co/paste/8od65
2. Your Towny config.yml (if using MySQL please remove password,) : https://ghostbin.co/paste/b22pe
3. Your townyperms.yml : default
4. Your log's error : https://ghostbin.co/paste/a3vfr

In addition, Towny works flawlessly without this.
I've seen threads about this problem, but I haven't found a solution there. Those topics were closed.

**Comment by LlmDl** [comment]
Can you explain the issue. You just say "start the server" without explaining what the problem is at all.

**Comment by SiriusWhite74** [comment]
> Can you explain the issue. You just say "start the server" without explaining what the problem is at all.

When you start the server after editing the configuration, the server crashes. And I can't add Cyrillic to the plugin at all

**Comment by LlmDl** [comment]
Your config's regex does not match what is recommended in the changelog for cyrillic servers:

```
        - name_check_regex: ^[а-яА-Яa-zA-Z0-9._\[\]-]*$
        - string_check_regex: ^[а-яА-Яa-zA-Z0-9\s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
        - name_remove_regex: '[^а-яА-Яa-zA-Z0-9._\[\]-]'
```

**Comment by LlmDl** [comment]
And actually I think Siris was able to add better support by using these: 
```
    - name_check_regex: ^[\P{M}\p{M}*+a-zA-Z0-9._\[\]-]*$
    - name_remove_regex: '[^\P{M}\p{M}*+a-zA-Z0-9\&._\[\]-]'
```

**Comment by SiriusWhite74** [comment]
Thanks! It working!
Closed.

**Comment by SiriusWhite74** [comment]
The server started, but after the creation of the city "Новиград" and restart, the following happened:
- https://ghostbin.co/paste/j454f
Re-open the thread.

```
my regex:
    name_filter_regex: '[ /]'
    name_check_regex: ^[\P{M}\p{M}*+a-zA-Z0-9._\[\]-]*$
    string_check_regex: ^[а-яА-Яa-zA-Z0-9\s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}\p{M}*+a-zA-Z0-9\&._\[\]-]'
```

**Comment by LlmDl** [comment]
It may not be possible to use Cyrillic characters on 0.93.1.0 for 1.12. I do not remember if there was further changes to the code aside from regex changes that enabled people to use Cyrillic characters.

**Comment by SiriusWhite74** [comment]
> It may not be possible to use Cyrillic characters on 0.93.1.0 for 1.12. I do not remember if there was further changes to the code aside from regex changes that enabled people to use Cyrillic characters.

In the server named "Politcubes" (based on towny) on 1.12.2 Cyrillic works fine

**Comment by LlmDl** [comment]
I don't know anything about that, sorry.

**Comment by SiriusWhite74** [comment]
> I don't know anything about that, sorry.

So you don't know how to add Cyrillic to 1.12.2? There are no ways at all?

**Comment by LlmDl** [comment]
Using the updated regex should have solved it, but as I said before there could have been another change to the code at some point since 0.93.1.0 that further allowed cyrillic characters.

The other server, I do not know what version of Towny they use, because as I said I do not know anything about that server.

1.12.2 is very old and we do not actively develop Towny for it.

**Comment by SiriusWhite74** [comment]
Thank you for trying to help
Closed
