### ISSUE TITLE
Suggestion: Add reminder to mayor to deposit money in town bank on creation

### ISSUE THREAD

**Issue by SmallSansSerif** [TownyAdvanced/Towny#3843]
Please add some form of reminder when a user creates a town/nation that would prompt people to remember to deposit money in the town bank to cover upkeep. 

So many people are excited to start a town and simply forget that small detail coming back a day later to find a disbanded town and they are out the creation cost and it becomes a staff issue/ticket.

**Comment by bartyrealms** [comment]
You could include this in the town create message temporarily, but it would make more sense if there was a separate message that was sent to the mayor himself.

**Comment by LlmDl** [comment]
![Capture](https://user-images.githubusercontent.com/879756/79337666-8743c000-7eeb-11ea-8998-45c9171ea687.PNG)
