### ISSUE TITLE
Suggestion: Mob limit per town

### ISSUE THREAD

**Issue by PripOO7** [TownyAdvanced/Towny#3845]
**Please explain your feature request to the best of your abilities:**
Right now I am having a lot of TPS drop because everyone wants to have every possible trade from villagers (1.15.2). My idea is having the possibility  to limit mobs per towns by linking it to a specific town. If someone have villagers not linked inside his town, it will despawn after "X" time. I have a mob limiter, but its imposible to limit everyone.

**Comment by LlmDl** [comment]
Are these typically animal or monster mobs?

**Comment by PripOO7** [comment]
> Are these typically villager, animal or monster mobs? Is it mainly villager?

Now i am having trouble whit Villagers (11% of my ticks) and turtles

**Comment by bartyrealms** [comment]
I am not really a fan of this. It feels out of scope for Towny to deal with this when there are plenty of methods for limiting entities in general.
