### ISSUE TITLE
Suggestion: /t list clickable Pages

### ISSUE THREAD

**Issue by TKwSni** [TownyAdvanced/Towny#3853]
**Please explain your feature request to the best of your abilities:**

I have noticed the new t list clickable feature which is great, and it would be perfect if it had clickable Next and Previous page, and even add a "Click to Join" town if its open.

**Comment by suneettipirneni** [comment]
You read my mind!

**Comment by TKwSni** [comment]
the only issue I saw with this is that if there is a plugin that overrides the /t command, then this wont work, maybe use /town list instead to avoid issues maybe ?

**Comment by LlmDl** [comment]
> the only issue I saw with this is that if there is a plugin that overrides the /t command, then this wont work, maybe use /town list instead to avoid issues maybe ?

Taken care of, thanks for pointing that out.
