### ISSUE TITLE
Bug withdraw money town if town same name

### ISSUE THREAD

**Issue by kenhoang1909** [TownyAdvanced/Towny#3854]
### What steps will reproduce the problem?
1. IF i have town name Long_Town , and another user make new town or change name their town with new name Long.Town
2. At town Long.Town can withdraw money form Long_Town
3.

### What is the expected output?
1. No Error in output
2.
3.

### What is your Towny version?
Do not say "latest".
Towny 1.12.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Skipped form. This is likely an issue with the economy provider plugin.

**Comment by kenhoang1909** [comment]
No this is problem with plugin towny 
Bug when using command /t withdraw money 
IF i have town name Long_Town , and another user make new town or change name their town with new name Long.Town
At town Long.Town can withdraw money form Long_Town

**Comment by LlmDl** [comment]
You skipped the form entirely. Re-file your ticket if you want help.

**Comment by kenhoang1909** [comment]
I had re-file , please check it !

**Comment by LlmDl** [comment]
I did, you skipped the form and I closed that ticket too.

**Comment by kenhoang1909** [comment]
Sorry i don't known that , i think that bug big error with all version you develop ! All member can withdraw money form other towny

**Comment by LlmDl** [comment]
There's a bunch of reasons that could happen, and I can tell you why if you just *fill out the form like you've been asked to do twice*.

**Comment by kenhoang1909** [comment]
Sorry my english is bad , and i don't understand you tell me fill . Please check it ~~

**Comment by LlmDl** [comment]
I did not realize you edited this ticket to fill the form out.

Your issue might reside in the use of Essentials Economy for your economy plugin. 

We don't develop Towny's 1.12.2 branch any longer so I am afraid there isn't much we can do on our end. 1.12.2 is very old.

**Comment by kenhoang1909** [comment]
Ok thank you , i will test lasted version , if have this error bug you can fix it ? . I see this bug form version 1.8.8

**Comment by LlmDl** [comment]
Essentials Economy has been having issues for a long time when it comes to Towny.

**Comment by kenhoang1909** [comment]
Can you suggest me other plugin change Essentials  economy

**Comment by LlmDl** [comment]
I don't have any suggestions for 1.12 servers, sorry.

**Comment by Momshroom** [comment]
In 1.12.2 we used craftconomy3 with no issues.  I don’t know if you can still find it in that version
