### ISSUE TITLE
An Internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by harryhazza3** [TownyAdvanced/Towny#3855]
### What steps will reproduce the problem?
1. /t new Rock
2. /plot claim
3.

### What is the expected output?
1. An Internal error occurred while attempting to perform this command
2. An Internal error occurred while attempting to perform this command
3.

### What is your Towny version?
Towney Advanced.0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/81f4YSZN
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/PkBeAc91
3. Your townyperms.yml :
https://pastebin.com/G3HAZqPM
4. Your log's error : 
Dont know where this is.
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Thank you for the help.

**Comment by harryhazza3** [comment]
It is also worth knowing that i am an operator on the server.

**Comment by LlmDl** [comment]
Your log shows Gringott's erroring at the beginning in your startup. It is also erroring when you create your Town.

You won't be able to /plot claim until you've used the /town claim command.

Make sure that you've updated to the newest Gringott's, he has recently updated his Towny support.

**Comment by harryhazza3** [comment]
Thank you for the reply, i am running the Gringotts-2.11.1-SNAPSHOT which is the latest? when i run the "/town claim circle" command i get "[Towney] Resident doesn't belong to anytown" same as when i do "/town add (name)"

**Comment by LlmDl** [comment]
Judging by your log your Town never gets properly created, because of Gringott's errors.

There are newer versions of Gringott's here: https://github.com/nikosgram/Gringotts/releases

**Comment by harryhazza3** [comment]
ah thank you it works now!

**Comment by abf1223** [comment]
I sort of have the same issue!
