### ISSUE TITLE
Suggestion: Toggle 'Modes set:' on new day

### ISSUE THREAD

**Issue by PeterDorvay** [TownyAdvanced/Towny#3857]
**Please explain your feature request to the best of your abilities:**
Remove 'Modes set:' from triggering on a new day. See photo for reference
![image](https://user-images.githubusercontent.com/21300105/78058037-8c760c00-733c-11ea-84bd-a3eb133110c7.png)

**Comment by LlmDl** [comment]
I've sat down twice looking for what is causing the `Modes set:` to appear and have not had any luck.

I've since tried to replicate it myself and cannot. For this to be solved I think it will have to be re-filed as a bug ticket so we can see your settings.
