### ISSUE TITLE
Bug /t withdraw  if town same name

### ISSUE THREAD

**Issue by kenhoang1909** [TownyAdvanced/Towny#3858]
### What steps will reproduce the problem?
1.Bug when using command /t withdraw money
2.IF i have town name Long_Town , and another user make new town or change name their town with new name Long.Town
3.At town Long.Town can using command /t withdraw money form Long_Town

### What is the expected output?
1.No Error in output
2.
3.

### What is your Towny version?
Do not say "latest".
Towny 1.12.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Skipped the form again, impressive.
