### ISSUE TITLE
Bug in wars when winner_takes_ownership_of_townblocks

### ISSUE THREAD

**Issue by Twistix** [TownyAdvanced/Towny#3862]
### What steps will reproduce the problem?
1. set winner_takes_ownership_of_townblocks to true
2. begin a war
3. win a townplot with a town

### What is the expected output?
1. the townplot when winned is sent to the attacking town
2. but the townplot loss price is removed from the town which win the townplot
For example, Ocreforge is the attacking town and Rieubois the defending. It seems like the good things are done but in bad order : 
![aaaaaaaa](https://user-images.githubusercontent.com/62986675/78117891-8187ae00-7406-11ea-86b5-e85a161ef77b.PNG)
but
![bbbbbbbbbbb](https://user-images.githubusercontent.com/62986675/78117951-93695100-7406-11ea-9cde-19bf085d0685.PNG)

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
spigot 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
https://pastebin.com/n0xWn60b
2. Your Towny config.yml (if using MySQL please remove password,) : 
https://pastebin.com/vY9wJ01N
3. Your townyperms.yml :
https://pastebin.com/df9AgNZL
4. Your log's error : 
none

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This is fixed as of 0.96.1.1

**Comment by Twistix** [comment]
Ok thanks !
