### ISSUE TITLE
World pvp false overrides towns' ability to enable pvp.

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3863]
### What steps will reproduce the problem?
1. Claim land
2. Try to toggle pvp
3. Pvp is not toggled

### What is the expected output?
1. Claim land
2. Try to toggle pvp
3. Pvp is toggled

### What is your Towny version?
Do not say "latest".
0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Tuinity-"68990cb" MC 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :  https://gist.github.com/bartyrealms/de96f94a18114a105c30ee7fa422ea2c
2. Your Towny config.yml (if using MySQL please remove password,) : https://gist.github.com/bartyrealms/5858005fe9df5a99e1c465ab1ca88c74

**Comment by LlmDl** [comment]
This was because the world has the pvp turned off.
