### ISSUE TITLE
Question:  Town Plot Type Question [Economy]

### ISSUE THREAD

**Issue by Darklom** [TownyAdvanced/Towny#3867]
**Ask your question as best as you are able:**
Is anyone else having an issue of setting a plot type with it saying "You can't afford this"

I'm using Gringotts with Vault.

The weird part is that.. everything else in the towny economy works.

[NO ERRORS ON CONSOLE]
1.15.2

**Comment by suneettipirneni** [comment]
Which version of gringotts are you using?

**Comment by Darklom** [comment]
Latest 2.9

**Comment by suneettipirneni** [comment]
https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-rf77e523

2.11.2 is the latest prerelease, and it is also compatible with newer versions of towny.

**Comment by Darklom** [comment]
@suneettipirneni I apologize, I am actually using that one.  2.11.2

**Comment by suneettipirneni** [comment]
can you send your startup log please?

**Comment by Darklom** [comment]
@suneettipirneni https://pastebin.com/fKeFE6zv

**Comment by suneettipirneni** [comment]
are u sure you have the funds in your account?

**Comment by Darklom** [comment]
@suneettipirneni  1000% sure.  I had players test it, with money ON them and in the town vault

**Comment by suneettipirneni** [comment]
ok this sounds like gringotts compatability issue please refer to their github:

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-rf77e523

**Comment by Darklom** [comment]
@suneettipirneni  You think so though?  I'm curious as to why every other economy item works except for that one?  Is there anything different in the script?

**Comment by suneettipirneni** [comment]
There's a ton of reason as to *why* it may not work, too many to list in a comment. Also I can't speak for the code in gringotts.

**Comment by LlmDl** [comment]
This can be re-opened as a bug report rather than a question if it requires more attention.
