### ISSUE TITLE
Cannot afford modifying plot type (Even though funds are available)

### ISSUE THREAD

**Issue by Darklom** [TownyAdvanced/Towny#3870]
### What steps will reproduce the problem?
1. Try to set a plot to inn, prison, or any other similar type
2.
3.

### What is the expected output?
1. Purchase it and change plot type
2.
3.

### What is your Towny version?
0.96.1.1

### What is your spigot/craftbukkit version?
spigot-1.15.2.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://controlc.com/466301f7

2. Your Towny config.yml (if using MySQL please remove password,) :
https://controlc.com/801fc05b

3. Your townyperms.yml :
https://controlc.com/f4fcc451

4. Your log's error : 

NO ERRORS  - It simply says that one cannot afford the item even after having money on them, on vault, and on town vault

The entire economy system works except on this portion

Gringotts & Vault

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Darklom** [comment]
Yes!  It is Gringotts-2.11.2-SNAPSHOT-rbed0924.jar

I also noticed this on /town prices

https://snipboard.io/b3qxiM.jpg

**Comment by Darklom** [comment]
@LlmDl  Updated and same exact issue - https://paste.ofcode.org/tJBbcXKCQfscZmCuARqPuL

I also cross posted to - https://github.com/nikosgram/Gringotts/issues/37

**Comment by LlmDl** [comment]
If there are indeed no errors then this is likely on the Gringotts' side of things. It is odd though.

**Comment by Darklom** [comment]
Got a second person confirming on https://github.com/nikosgram/Gringotts/issues/37

**Comment by LlmDl** [comment]
I have a build I would like you to test for me, are you on the Discord?
