### ISSUE TITLE
Negative upkeep not working as of v96

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3874]
Updating from a .95 version to the latest .96 version ended up making the negative towny upkeep no longer work. Previously, I had it so each chunk gave you 10$/day. So a town's upkeep might say, -730, giving the town 730$/day. Without touching the config, the upkeep for towns now says 0, and the config settings remain the same. 

### What is your Towny version?
Do not say "latest".
0.96.1.0

### What is your spigot/craftbukkit version?
https://imgur.com/a/1FQu2lk

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Can provide shortly, not home. 
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/1i0G4RDJ

**Comment by LlmDl** [comment]
This should be fixed as of 0.96.1.2.
