### ISSUE TITLE
Custom Rank formatting in english.yml

### ISSUE THREAD

**Issue by wbrookey** [TownyAdvanced/Towny#3876]
### What steps will reproduce the problem?
1. Creating a custom rank in townyperms.yml
2. Using custom english.yml formatting
3. Running command: /t

### What is the expected output?
1. 
![image](https://user-images.githubusercontent.com/60930234/78466150-e6bff580-76cb-11ea-8eba-46cea8c4c9db.png)

### What is your Towny version?
Towny version 0.96.1.0

### What is your spigot/craftbukkit version?
Paper-161

No errors
1. Your Towny (english.yml) : https://pastebin.com/SVhCWj6Z
2. Your townyperms.yml : https://pastebin.com/itAcRP5T

**Comment by LlmDl** [comment]
Sorry you haven't really explained what's going on here, can you explain further?

**Comment by wbrookey** [comment]
Absolutely, sorry for not being clear! 

I added a Co-Mayor and a Member rank in townyperms.yml.

In the english.yml there isn't an option to set the formatting for these ranks, so there isn't a way for the 'Co-Mayor:' line to match the 'Mayor' line. It just defaults to the 'standard' formatting.

I realize this might be better suited for a feature request, apologies if I posted in the wrong place!

**Comment by LlmDl** [comment]
Ok, I took a look at this and although it is not super clear there is a spot where you can change the formatting of those rank lines.

```
res_format_list_1: '&2'  #First colour applied to Resident lists, ex: on /res, the friend list's Friends section.
res_format_list_2: '&a'  #Second colour applied to Resident lists, ex: on /res, the friend list's [1] section.
res_format_list_3: '&f'  #Third colour applied to Resident lists, ex: on /res, the friend list's list of friends' names section.
```

**Comment by wbrookey** [comment]
Thanks a lot! This worked. Been lots of trial and error through the english.yml but it's coming out great!
