### ISSUE TITLE
Dynmap-towny 0.76 server lags

### ISSUE THREAD

**Issue by Darutan92** [TownyAdvanced/Towny#3878]
After installing the update dynmap-towny, every 5 minutes my server lags.

```
[ERROR] .... net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84)

[ERROR] .... net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:24)

[ERROR] .... net.minecraft.server.v1_15_R1.WorldNBTStorage.getPlayerData(WorldNBTStorage.java:217)

[ERROR] .... org.bukkit.craftbukkit.v1_15_R1.CraftOfflinePlayer.getData(CraftOfflinePlayer.java:196)

[ERROR] .... org.bukkit.craftbukkit.v1_15_R1.CraftOfflinePlayer.getBukkitData(CraftOfflinePlayer.java:200)

[ERROR] .... org.bukkit.craftbukkit.v1_15_R1.CraftOfflinePlayer.getName(CraftOfflinePlayer.java:58)

[ERROR] .... com.spawnchunk.emeraldbank.util.PlayerUtil.getOfflinePlayer(PlayerUtil.java:16)

[ERROR] .... com.spawnchunk.emeraldbank.modules.VaultConnector.getBalance(VaultConnector.java:126)

[ERROR] .... com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:260)

[ERROR] .... com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingBalance(EconomyAccount.java:174)

[ERROR] .... com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingFormattedBalance(EconomyAccount.java:199)

[ERROR] .... org.dynmap.towny.DynmapTownyPlugin.formatInfoWindow(DynmapTownyPlugin.java:462)

[ERROR] .... org.dynmap.towny.DynmapTownyPlugin.handleTown(DynmapTownyPlugin.java:584)

[ERROR] .... org.dynmap.towny.DynmapTownyPlugin.updateTowns(DynmapTownyPlugin.java:814)

[ERROR] .... org.dynmap.towny.DynmapTownyPlugin.access$000(DynmapTownyPlugin.java:51)

[ERROR] .... org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:299)

[ERROR] .... org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)

[ERROR] .... org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)

[ERROR] .... net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)

[ERROR] .... net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)

[ERROR] .... net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)

[ERROR] .... net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)

[ERROR] .... java.lang.Thread.run(Thread.java:813)

[ERROR] .... ------------------------------

[ERROR] .... --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

[ERROR] .... ------------------------------

[WARNING] .... Can't keep up! Is the server overloaded? Running 15356ms or 307 ticks behind
```

I like the new placeholders, but I don't like the freezes. I am struggling with this by setting the check more than once every 5 minutes, but once an hour. Can add the ability to turn off the check for some placeholders in the config? For example, balance.

1.15.2 PaperSpigot, Towny-0.96.1.1, DynmapTowny 0.76

**Comment by bartyrealms** [comment]
![image](https://user-images.githubusercontent.com/42015460/78504832-69cd6400-773d-11ea-8700-d7543e32c1df.png)

Over the course of 35 minutes, this was ran 7 times, taking an average of 12.83ms per run. This is almost negligible. This should be done asynchronously but it's likely you have worse issues than this causing your server to freeze for so long.

**Comment by LlmDl** [comment]
It'll be largely dependent on the eco plugin, Siris is going to get something together to fix it/cache it.

**Comment by suneettipirneni** [comment]
[Dynmap-Towny-0.76.jar.zip](https://github.com/TownyAdvanced/Towny/files/4439517/Dynmap-Towny-0.76.jar.zip)

@Darutan92 try this jar

**Comment by Darutan92** [comment]
> @Darutan92 try this jar
Thank you, I will unsubscribe in the morning

**Comment by suneettipirneni** [comment]
The issue seems to be remedied, closing.

**Comment by Darutan92** [comment]
I use the material economy (emeralds) and after updating the dynammaptowny to 76, I encountered difficulties that were already written here https://github.com/TownyAdvanced/Towny/issues/3878. New update 77 did not help. I tried all the recommended plugins of the economy and some others. If the economy is material, an error is written to the console and spam of this kind:

https://pastebin.com/J3hz9kg5

If virtual or from TNE and Hell plugins, then it works fine. But in the TNE and Hell-economy plugins I found an error when transferring emeralds from inventory to the town account (/t deposit), which I wrote to the author about. https://www.spigotmc.org/threads/hellconomy.372819/#post-3754763

I would like other plugins to keep up with the new dynmaptowny.

What will reproduce the error?
-Server 1.15.2
-Vault
-Gringotts or EmeraldEconomy https://github.com/nikosgram/Gringotts/releases,  https://www.spigotmc.org/resources/the-emerald-bank.71210/
-Dynmap
-Towny
-DynmapTowny 76, 77
-50+ cities and nations on the map

Yes, if there is only one city, usually a DynmapTowny with most plugins of the real economy doesn’t produce anything, but if there are a lot of them ...
