### ISSUE TITLE
Question: Custom Messages

### ISSUE THREAD

**Issue by CallMeRazer** [TownyAdvanced/Towny#3880]
Hey there,

I am experiencing a little trouble with Towny. Now that I have created a cusom messages.yml file called custom.yml , Towny keeps Spamming my Console with this:

[13:53:35] [Thread-15/INFO]: [Towny] Error could not read default_towny_prefix from custom.yml

I am unsure on how to fix this. My default Prefix looks like this in the custom.yml

default_towny_prefix: '&e&LCrystal&6&lEmpire &8| &7'

I have also tried replacing the ' with " but that also didn't work.
I would be very happy If you could help me with this.

**Comment by LlmDl** [comment]
It was broken yaml found using https://yaml-online-parser.appspot.com
