### ISSUE TITLE
Suggestion: Colour Coding in Titles

### ISSUE THREAD

**Issue by StubbiestPeak75** [TownyAdvanced/Towny#3881]
Ability to color code titles

./n set title (name) (title)
Whereas, &(number) would be recognised as a colour code, instead of a string

Make it so that &6Title, makes the title coloured gold, instead of a &6 being part of the title.

**Comment by Darutan92** [comment]
Probably talking about it.
![image](https://user-images.githubusercontent.com/60871654/78518835-9da69900-77d2-11ea-8e27-6da587452d3e.png)

**Comment by LlmDl** [comment]
This was completed some time ago.
