### ISSUE TITLE
Towny event war bug winner_takes_ownership_of_town

### ISSUE THREAD

**Issue by yumjunstar** [TownyAdvanced/Towny#3882]
### What steps will reproduce the problem?
0. winner_takes_ownership_of_town: 'true'
1. enable war by /townyadmin toggle war
2. occupy a town or nation

### What is the expected output?
1. warning message on console and winner takes ownership of town doesn't take effect
2.
3.

### What is your Towny version?

0.96.1.2

### What is your spigot/craftbukkit version?
paper-158 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://paste.gg/p/anonymous/439c531ad4ee4e4a9f7d1f17a24986f9
2. Your Towny config.yml (if using MySQL please remove password,) :
https://paste.gg/p/anonymous/a0fff2d1235f416495455c91dc45d5e6
3. Your townyperms.yml : https://paste.gg/p/anonymous/c9fb254e6a97423f96c3ad4fc53a8cad
4. Your log's error : https://paste.gg/p/anonymous/0e953b30ce824e52b6ef8fa6ac0586f2

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Should be fixed as well.
