### ISSUE TITLE
Question:outposts will not fully delete

### ISSUE THREAD

**Issue by Caddie08** [TownyAdvanced/Towny#3884]
**Ask your question as best as you are able:**
When a player delete an outpost it keeps the spawn point of the outpost as outpost and won't remove it allowing players to have that outpost available for another place. IS there a way to fix this? So say i have outpost #2 and i no longer want it.. If i unclaim it, and try to use that outpost to be available for another spot elsewhere it won't let me and it keeps the spawn point of that outpost that was deleted, counts against my number of outpost and still shows that the ton owns it. any help would be appreciated

**Comment by LlmDl** [comment]
This isn't a question ticket, file as a bug ticket, include precise steps on how the player managed to do this.
