### ISSUE TITLE
Upgraded from 0.94.0.0 to 0.96.0.0 and now towny does not follow perms set in perms program.

### ISSUE THREAD

**Issue by Klawdek** [TownyAdvanced/Towny#3885]
I just upgraded my server from 1.14.4 to 1.15.2 and towny from 0.94.0.0 to 0.96.0.0 the permissions were set long ago and have worked until now.  Now the perms set in my permission plugin are ignored.  Players can start towns and nations no matter what rank.  When the perms have been set for many versions to allow towns and nations only after getting to certain ranks.
This has been set up the same way since 2017.  We have upgraded a few times along the way and never had this problem before.
### What steps will reproduce the problem?
1.  Uprade from 1.14.4 to 1.15.2 and towny from 0.94.0.0 to 0.96.0.0
2.  Keep the same permissions set in permissions plugin that allow for people to make towns and nations only after getting to a certain rank.
3.

### What is the expected output?
1.  That it would work the same after upgrade as it did before upgrade.  That is playes must be of a certian ranks or higher to create new towns and nations.
2.
3.

### What is your Towny version?
Do not say "latest".
Towny version 0.96.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Paper-146 (MC: 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/6pJRhVdk
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/1yQNHZWw

3. Your townyperms.yml :  https://pastebin.com/uN9viZgD
4. Your log's error :  there is no error players can just start towns no matter what ranks they are

(optional) If this is to do with permissions, 
5. Your permissions file :  https://pastebin.com/AqVhJ6FE

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your king rank should only have towny.command.nation.new, not towny.command.nation.*

Likewise your knight rank should only have towny.command.town.new, not towny.command.town.*

Doing it the way you have done would cause any knight to join another town to have full control over that town.

From the townyperms.yml:

Remove `- towny.command.town.new` from the nomads and `- towny.command.nation.new` from the mayors. This will make it so your permission plugin is relied upon for handing out the above nodes.

Lastly, 0.96.0.0 should not be used, upgrade to 0.96.1.0.

**Comment by Klawdek** [comment]
Thank you very much for answering I will change the perms right away.  I am not sure about changing the townyperms file now that one nation and at least one town have been made by people at lower ranks than what should be able to make towns and nations.  I am afraid they might not be able to access their town.  I am not sure why suddenly it started working like this.  I looked at backups from a couple years ago and was configured the same way.  Either towny changed something or it has been configured wrong all along and nobody ever tried to start a town before obtaining the rank to do so (or maybe somebody did but didn't say anything about it).

Again thank you so much for pointing out the configuration errors and helping to straighten this out.
