### ISSUE TITLE
outposts are not unclaiming completely

### ISSUE THREAD

**Issue by Caddie08** [TownyAdvanced/Towny#3886]
### What steps will reproduce the problem?
1.make outpost
2.unclaim
3.outpost stays just at the spawn point

### What is the expected output?
1.create outpost
2.if you want to delete it, delete the outpost  (using t unclaim)
3.have the outpost completely deleted and that outpost will not count toward town out post amounts

### What is your Towny version?
Do not say "latest".
09600

### What is your spigot/craftbukkit version?
Do not say "latest". paper

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You skipped the form.
