### ISSUE TITLE
Teleport with no funds to a town

### ISSUE THREAD

**Issue by Darklom** [TownyAdvanced/Towny#3887]
### What steps will reproduce the problem?
1. Teleport to a town with no money (in an economy)
2.
3.(IT allows you to teleport to any town without any funds currently)

### What is the expected output?
1. "You do not have enough funds, it cost $XXX to travel to this town"
2.
3.

### What is your Towny version?
Do not say "latest". 

0.96.1.2

### What is your spigot/craftbukkit version?
Do not say "latest".

1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/4uuVcsNL

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/ygyCGu6d

3. Your townyperms.yml :
4. Your log's error : 
No errors

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Can you show us the town's `towny\data\towns\TOWNNAME.txt file` ?

What sort of player is testing this? Are they towny.admin/op?

**Comment by Darklom** [comment]
@LlmDl  I've had various players testing this feature (with no privileges) 

```
This is the portion from the config I'm basing it off from, "spawn_travel:

I have 2 towns, one with a price and one without 

    # Cost to use /town spawn
    price_town_spawn_travel: '40.0'
    # Cost to use '/town spawn [town]' to another town in your nation.
    price_town_nation_spawn_travel: '50.0'
    # Cost to use '/town spawn [town]' to another town in a nation that is allied with your nation.
    price_town_ally_spawn_travel: '50.0'
    # Cost to use /town spawn [town]
    # This is paid to the town you goto.
    price_town_public_spawn_travel: '40.0'
    # When set to true, any cost paid by a player to use any variant of '/town spawn' will be paid to the town bank.
    # When false the amount will be paid to the server account whose name is set in the closed economy setting below..
    town_spawn_cost_paid_to_town: 'true'"
```

Town1
https://paste.ofcode.org/eeU6uq9stxd3PR32w6PEi3

Town2
https://paste.ofcode.org/ZLCuGjrg9TxfUZ6pT6Fdrg

**Comment by LlmDl** [comment]
Darktopia has a spawnCost of 0, while FingerVille has a spawnCost of 30.

Are neither Towns charging players to spawn?

**Comment by Darklom** [comment]
Is the portion of code I showed you the default?  I thought it would be like a fixed price or at least the minimum so people don't abuse the /spawn town 

Otherwise, this is not a bug

**Comment by LlmDl** [comment]
The prices in the config are the default and max amounts set for towns. Mayors can lower the price if they want but not raise it past the config.

**Comment by Darklom** [comment]
@LlmDl  Then it is not an issue but rather a suggestion.  Thank you for the clarification!
