### ISSUE TITLE
Jail positioning

### ISSUE THREAD

**Issue by Darklom** [TownyAdvanced/Towny#3888]
### What steps will reproduce the problem?
1. Setting the coordinates for a jail /town set jail doesn't appear to do anything
2.
3. If you jail a player, it takes them to a random coordinate

### What is the expected output?
1. Take them to designated jail position
2.
3.

### What is your Towny version?
Do not say "latest". 

0.96.1.2

### What is your spigot/craftbukkit version?
Do not say "latest".

1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/4uuVcsNL

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/ygyCGu6d

3. Your townyperms.yml :
4. Your log's error : 
No errors

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You are using /t set jail inside of an already made jail plot yes?

**Comment by Darklom** [comment]
@LlmDl  That is correct

**Comment by LlmDl** [comment]
I tested this and found they were teleported to exactly where I was moving the jail spawn around in the jail plot, using /t set jail.

It could be another plugin conflicting with teleports, maybe looking for safer locations?
