### ISSUE TITLE
Allied Nations cannot travel to Town Spawns

### ISSUE THREAD

**Issue by wbrookey** [TownyAdvanced/Towny#3890]
### What steps will reproduce the problem?
1. Nation1 allies Nation2 (Nation1 contains 'City' and Nation2 contains 'Town')
2. Set /t spawn for 'City' non-public
3. Resident in 'Town' uses /t spawn City
4. Results in message:  'Town spawn travel to towns allied with your nation is forbidden"

### What is the expected output?
1. Based on settings in my config.yml, the towns should be able to travel freely between allied nation's towns

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
Paper build-161

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
2. Your Towny config.yml  : https://pastebin.com/dMC6mLri
3. Your townyperms.yml : https://pastebin.com/550ZaTFi

**Comment by LlmDl** [comment]
Try giving the default rank in the town section the towny.town.spawn.ally node in your townyperms

**Comment by wbrookey** [comment]
Thanks, worked!
