### ISSUE TITLE
Possible incompatibility with PhantomEconomy

### ISSUE THREAD

**Issue by paulhlschr** [TownyAdvanced/Towny#3891]
### What steps will reproduce the problem?
1. Install Towny 0.96.1.2 and Phantomeconomy 1.7 Release
2. Execute `/ta town new [Name] [Mayor]` (in my case: Port_Bulgar and PaulLink)

### What is the expected output?
1. Town gets created and the commands like `/town` work properly without throwing the same error.

### What is your Towny version?
0.96.1.2

### What is your spigot/craftbukkit version?
Paper 1.15.2 #149

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/VSqzJsHP
2. https://pastebin.com/XsLj1TYr
3. https://pastebin.com/MyqE3yAZ
4. https://pastebin.com/Q8mPnvGH

### Additional notes:

As I am not quite sure, which plugin is causing this error specifically, I reported this [issue ](https://github.com/lokka30/PhantomEconomy/issues/25) to the Phantomeconomy developer @lokka30, too.

**Comment by LlmDl** [comment]
That looks to be on the PhantomEconomy end, it is expecting a number only but he is passing more than that.

**Comment by paulhlschr** [comment]
The issue was fixed by PE's developer and towns can be created now. But there is still a problem regarding depositing of money into a town's bank, as although my balance is more than enough to finish the transaction process, Towny just returns, that I don't have enough money.

Sadly there are no error logs, just this chat message. I haven't changed anything to the setup, except updating PE to the fixed version 1.8 RELEASE.

**Comment by LlmDl** [comment]
Try it with TheNewEconomy or HellConomy or HyperConomy or iConomy or if you have to EssentialsEconomy, They all work. You've chosen two plugins that don't support older Vault methods.

**Comment by lokka30** [comment]
Pushed a commit for an upcoming release of PE, new methods are included in the VaultImplementer class now. Would this have fixed the issue?

**Comment by suneettipirneni** [comment]
Can you send a link your PR, if you don’t mind?

**Comment by paulhlschr** [comment]
@suneettipirneni 
> Can you send a link to your PR, if you don’t mind?

Here is the commit for PE, that tried to fix the issue, but it didn't unfortunately: https://github.com/lokka30/PhantomEconomy/commit/7af4fe192a1c59181d8d190e628b4874717c9ee2

**Comment by LlmDl** [comment]
@lokka30 for example:

```
    @Override
    @SuppressWarnings("deprecation")
    public EconomyResponse withdrawPlayer(String name, double amount) {
        return withdrawPlayer(Bukkit.getOfflinePlayer(name), amount);
    }
```
This is still trying to return an offlineplayer which is not how towns and nations exist.

You could use the TownyAPI to specifically ask what the town and nation banks are prefixed by, but by default they are:
```
town-            or       TownySettings.getTownAccountPrefix();
nation-          or       TownySettings.getNationAccountPrefix();
```

You can make it so that if `name` does not begin with either prefix you can use the `return withdrawPlayer(Bukkit.getOfflinePlayer(name), amount);` and if they do begin with either prefix then you can return an account that is directly named `town-Cool_Town`.

If you do want to further hook Towny's API you can directly look up Residents/Towns/Nations EconomyAccount objects and use our internal pay/collect methods.

```
ie:
Town town.getAccount().pay()|.collect()|.payTo()
```

**Comment by lokka30** [comment]
> 
> 
> @lokka30 for example:
> 
> ```
>     @Override
>     @SuppressWarnings("deprecation")
>     public EconomyResponse withdrawPlayer(String name, double amount) {
>         return withdrawPlayer(Bukkit.getOfflinePlayer(name), amount);
>     }
> ```
> 
> This is still trying to return an offlineplayer which is not how towns and nations exist.
> 
> You could use the TownyAPI to specifically ask what the town and nation banks are prefixed by, but by default they are:
> 
> ```
> town-            or       TownySettings.getTownAccountPrefix();
> nation-          or       TownySettings.getNationAccountPrefix();
> ```
> 
> You can make it so that if `name` does not begin with either prefix you can use the `return withdrawPlayer(Bukkit.getOfflinePlayer(name), amount);` and if they do begin with either prefix then you can return an account that is directly named `town-Cool_Town`.
> 
> If you do want to further hook Towny's API you can directly look up Residents/Towns/Nations EconomyAccount objects and use our internal pay/collect methods.
> 
> ```
> ie:
> Town town.getAccount().pay()|.collect()|.payTo()
> ```
I've tried to follow your guide on implementing the Towny API into Maven.
* Put my token with the correct permissions into PhantomEconomy/.m2/settings.xml
* Added the towny repo and the dependency

However, the dependency isn't being found:
```
<dependency>
            <groupId>com.palmergames.bukkit.towny</groupId>
            <artifactId>Towny</artifactId>
            <version>0.95.2.0</version>
            <scope>provided</scope>
        </dependency>
```
[I posted this commit.](https://github.com/lokka30/PhantomEconomy/commit/d75bc250535e118171a62992db764e529bdebf3a)

**Comment by LlmDl** [comment]
Usually your .m2 folder would not be in your project folder, but above it. You should also change the dependency version to 0.96.1.0, I will update the guide.

**Comment by lokka30** [comment]
> 
> 
> Usually your .m2 folder would not be in your project folder, but above it. You should also change the dependency version to 0.96.1.0, I will update the guide.

Cheers, I've moved .m2 to the parent folder of the project and changed the version. Unfortunately it still isn't recognised. 😞

**Comment by LlmDl** [comment]
Are you sure you have your auth token setup in your settings.xml? Does it have package read access?

**Comment by paulhlschr** [comment]
> > 
> 
> > 
> 
> > Usually your .m2 folder would not be in your project folder, but above it. You should also change the dependency version to 0.96.1.0, I will update the guide.
> 
> 
> 
> Cheers, I've moved .m2 to the parent folder of the project and changed the version. Unfortunately it still isn't recognised. 😞 

Create a settings.xml in the .m2/ folder in your user directory (like C:\Users\paulhlschr\.m2) and set the GitHub Package server there, as you could use Packages again in the future. For me it is working fine and I may have already fixed the issue in PE, but in a pretty basic way.

**Comment by lokka30** [comment]
Here are the contents of my settings.xml:
```
<servers>
    <server>
        <id>github-towny</id>
        <username>lokka30</username>
        <password>TOKEN HERE</password>
    </server>
    <server>
        <id>github-tne</id>
        <username>lokka30</username>
        <password>TOKEN HERE</password>
    </server>
</servers>
```
I've moved it into my Users directory, how do I set the GH Package server there?


> For me it is working fine and I may have already fixed the issue in PE, but in a pretty basic way.
Was the fix in the PR you sent?

**Comment by LlmDl** [comment]
Make sure the settings.xml is being put into the .m2 folder that is already existing in your user folder. You can't be using maven and not have an existing .m2 folder.

**Comment by lokka30** [comment]
Paul did an excellent job at guiding me towards getting Maven working. Just working on the depositPlayer method now :)
