### ISSUE TITLE
Lecterns seem to cancel LWC/WorldGuard protection

### ISSUE THREAD

**Issue by pavja2** [TownyAdvanced/Towny#3894]
It appears that recent versions of Towny are causing issues with lectern permissions on my server. Happy to test / provide additional information as needed.

### What steps will reproduce the problem?
1. Create a lectern and place a written book on it.
2. Set the lectern to read-only using /cdisplay for LWC or with worldguard (like [this](https://worldguard.enginehub.org/en/latest/regions/common-scenarios/#how-do-i-allow-players-to-read-lectern-books-but-not-take-them)).
3. Other players can still use the "Take Book" option to remove the book from the lectern if they have build/destroy permissions in the towny plot. This also happens in the wild if all players have build/destroy permissions there.

### What is the expected output?
1. Create a lectern and place a written book on it.
2. Set the lectern to read-only using a protection plugin like LWC or World Guard.
3. Towny does not overrule the more restrictive block protection and players cannot take books.

### What is your Towny version?
95.2.22

### What is your spigot/craftbukkit version?
Paper Spigot Build #133 (Minecraft 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :  https://pastebin.com/wyfnV3rR
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/znJxuiL0
3. Your townyperms.yml : https://pastebin.com/G653ycAp
4. Your log's error :  No errors.

**Comment by LlmDl** [comment]
You need to update to an actual recent version of Towny (0.96.1.0) as soon as possible.

**Comment by LlmDl** [comment]
Towny will decide who can take books from lectern based on who has permission to destroy a lectern in the plot they are located in. What is the perm line of the plot when you do /plot perm on top of the lectern?

**Comment by pavja2** [comment]
> You need to update to an actual recent version of Towny (0.96.1.0) as soon as possible.

Done. Updated Towny to 96.1 and Paper Spigot to #165.

> Towny will decide who can take books from lectern based on who has permission to destroy a lectern in the plot they are located in. What is the perm line of the plot when you do /plot perm on top of the lectern?

That's correct.  So, for example, in the Wild the permissions read as "Wilderness: Build, Destroy, Switch, ItemUse." Players are able to take books off of lecterns in the wild, even if those lecterns are protected with LWC or WorldGuard.

**Comment by LlmDl** [comment]
This is fixed as of 0.96.1.3 which should be out in the next day or two.

If you would like to check out an early release you can get it here: https://cdn.discordapp.com/attachments/669247087329673228/697932964658544750/Towny-0.96.1.3.jar

Keep in mind if you see 0.96.1.3 show up as a pre-release you should redownload it.
