### ISSUE TITLE
Suggestion: Changing Rules for Lecterns

### ISSUE THREAD

**Issue by RealHummus** [TownyAdvanced/Towny#3896]
Instead of taking books from lecterns being under the permission to destroy, it should be under switch  or itemuse.

**Comment by LlmDl** [comment]
The logic behind it is that if someone could destroy the lectern they could take the book.

**Comment by LlmDl** [comment]
Having the lectern in the switch list would also mean players without switch perms could not read books placed on lecterns, so when switch perms are granted it means that players can both read and take the book on the lectern.
