### ISSUE TITLE
Question: How to disable players from creating a town in server spawn? 

### ISSUE THREAD

**Issue by awesomek29** [TownyAdvanced/Towny#3897]
**Ask your question as best as you are able:**
I have an issue, Players are able to create a town in the server spawn. I am using worldguard to spawn protect it. Is there a flag that denies a player when he makes a town?

**Comment by LlmDl** [comment]
Either make an NPC Town there or get worldguard-towny from townyadvanced.github.io

**Comment by awesomek29** [comment]
Thanks
