### ISSUE TITLE
DynmapTowny + item economy = lag

### ISSUE THREAD

**Issue by Darutan92** [TownyAdvanced/Towny#3899]
I use the material economy (emeralds) and after updating the dynmaptowny to 76, I encountered difficulties that were already written here #3878. New update 77 did not help. I tried all the recommended plugins of the economy and some others. If the economy is material, an error is written to the console and spam of this kind:

https://pastebin.com/J3hz9kg5

If virtual or from TNE and Hell plugins, then it works fine. But in the TNE and Hell-economy plugins I found an error when transferring emeralds from inventory to the town account (/t deposit), which I wrote to the author about. https://www.spigotmc.org/threads/hellconomy.372819/#post-3754763

I would like other plugins to keep up with the new dynmaptowny.

What will reproduce the error?
-Server 1.15.2
-Vault
-Gringotts or EmeraldEconomy https://github.com/nikosgram/Gringotts/releases, https://www.spigotmc.org/resources/the-emerald-bank.71210/
-Dynmap
-Towny
-DynmapTowny 76, 77
-50+ cities and nations on the map

Yes, if there is only one city, usually a DynmapTowny with most plugins of the real economy doesn’t produce anything, but if there are a lot of them ...

**Comment by suneettipirneni** [comment]
I reccomend using another item currency plugin besides gringotts for now

**Comment by Darutan92** [comment]
> I reccomend using another item currency plugin besides gringotts for now
Thank you, I’ll check version 78 today, tomorrow I’ll write if it helped, but which plug-in should be used instead of the gringots?)

**Comment by suneettipirneni** [comment]
You can try TNE

**Comment by LlmDl** [comment]
@Darutan92 Let me know if you're able to test a new build for me.
