### ISSUE TITLE
Gringotts disables/breaks some of Towny commands

### ISSUE THREAD

**Issue by FlqmingPig** [TownyAdvanced/Towny#3903]
### What steps will reproduce the problem?
1. Gringotts Plugin installed
2.
3.

### What is the expected output?
1. No town info shows up
2. Generates an exception while executing task 
3. No Nation info shows up

### What is your Towny version?
Do not say "latest".
0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/5a2x3ijd
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/BE5HVizM
3. Your townyperms.yml : https://pastebin.com/23XfF6qM
4. Your log's error : https://pastebin.com/K8fVK7iy

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You skipped teh startup log, but I am guessing you do not have the Gringott's pre-release that fixes their economy.
