### ISSUE TITLE
Question: How to increase town claim limit for all towns in config?

### ISSUE THREAD

**Issue by awesomek29** [TownyAdvanced/Towny#3905]
How would I increase the number of blocks a town can claim? 
A lot of towns on my server get this message "not enough available town blocks"  I would like to make it so they can claim more.

**Comment by LlmDl** [comment]
Covered here: https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#setting-how-many-town-blocks-a-town-receives
