### ISSUE TITLE
Paper: Command Dispatched Async

### ISSUE THREAD

**Issue by Ne0shka** [TownyAdvanced/Towny#3909]
### What steps will reproduce the problem?
1. "Player issued server command: /gch /towny new"

### What is the expected output?
Chat message "[Global] Player: /towny new"

### What is your Towny version?
Towny version: 0.93.1.0 for MC 1.12.2
TownyChat version 0.54

### What is your spigot/craftbukkit version?
Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/FRNH5CLB
2. Your Towny config.yml : https://pastebin.com/nZ5ExLxP
3. Your townyperms.yml : https://pastebin.com/dXniDSZf
4. Your log's error : https://pastebin.com/A2pg4eVm
5. Your chatconfig.yml : https://pastebin.com/hsmVCs5e
6. Your channels.yml : https://pastebin.com/PUwqasez

**Comment by LlmDl** [comment]
Towny doesn't have a '/towny new' command. There is a /town new command.

I don't know why your error shows townychat trying to use /towny as a chat alias, because I do not see that set as an alias in the channels.yml.

**Comment by Ne0shka** [comment]
`Channels:
    general:
        commands: [**gch**]
        type: GLOBAL
        channeltag: '&e[Г]'
        messagecolour: '&f'
        default: true
        permission: 'towny.chat.general'
        craftIRCTag: 'admin'
        range: '-1'`

**Comment by Ne0shka** [comment]
Channels:
    general:
        commands: **[gch]**
        type: GLOBAL
        channeltag: '&e[Г]'
        messagecolour: '&f'
        default: true
        permission: 'towny.chat.general'
        craftIRCTag: 'admin'
        range: '-1'

**Comment by Ne0shka** [comment]
Re-check please

**Comment by LlmDl** [comment]
Re-check what? Your channels.yml does not have a channel using the command /towny.

The command to start a new town is /town new.

If you have a bungee setup you probably have a command /towny, used to join the Towny server but otherwise I can't say why using /towny new would show an error like that.

**Comment by Ne0shka** [comment]
@LlmDl 
I don't have bungee. And I know that the /town new command is used to create a city.
But when you try to send the message "/towny new " to the chat via the command, this error occurs. In this case, an attempt was made to send this message via the /gch (global channel) command.
For some reason, Towny handles 2 slashes. And since the /towny new command does not exist at all, an error occurs.
But this is just my guess, please check whether this problem exists.

**Comment by LlmDl** [comment]
![Capture](https://user-images.githubusercontent.com/879756/79475069-d31a6600-7fcc-11ea-9711-f11560caec85.PNG)

I used /towny new, got the `[Towny] Invalid sub command. ` and had no error message in my log.

**Comment by Ne0shka** [comment]
> send this message via the /gch (global channel) command.
Try send command /tc /towny new, for example. Trouble in 2 slashes.

**Comment by LlmDl** [comment]
I understand now. 

This is something I cannot fix for you because you're on 1.12 and using an old TownyChat. The error is not present in modern versions of TownyChat.
