### ISSUE TITLE
Town Spawns reset on server restart

### ISSUE THREAD

**Issue by DragoNjesterz** [TownyAdvanced/Towny#3910]
### What steps will reproduce the problem?
1. Set a town spawn
2. Restart Server
3. Try to use town spawn and notice it has been removed

### What is the expected output?
1. Town spawn to still be set
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/xL4WET9F
2. Your Towny config.yml (if using MySQL please remove password,) :
 https://pastebin.com/XX61DQc5
3. Your townyperms.yml :
https://pastebin.com/mwWZLG4n
4. Your log's error : 
No error that we can see. Town Spawns just seem to reset upon server restart.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
When you say 'Try to use town spawn and notice it has been removed',
are you saying that when you do /town spawn it tells you that the town spawn has not been set?

Can you show us a towny\data\towns\Townname.txt file that hasn't been reset, and then the same file after the server is restarted, which has had it reset?

If you're talking about players not going to their town spawn when they die, you have town_respawn set to false in your config.

**Comment by DragoNjesterz** [comment]
Yes, when using /town spawn after a server reset. It replies with the message 'town spawn has not been set'

These are the files you request:
Before restart: https://pastebin.com/cfH3UyBi
After restart: https://pastebin.com/62Ebg6pR

Thank you! I created the new town, set the spawn, tested that it worked. Restarted and it no longer worked. In the files above :)

**Comment by LlmDl** [comment]
I cannot tell why but I believe it is because your multiverse is loading after Towny (which shouldn't happen because we have Multiverse-Core as a softdepend in our plugin.yml.

Do you have anything set in multiverse that delays it's startup, or another plugin delaying it?

**Comment by DragoNjesterz** [comment]
Of the plugins currently installed, I have not edited anything to delay it, so I am not sure why it would be delayed. I'm not exactly sure what to do about it or look for, but I will have to look through everything.

**Comment by LlmDl** [comment]
Can you link me to where you got your multiverse jar?

**Comment by LlmDl** [comment]
Nevermind I found it on bukkitdev.

**Comment by LlmDl** [comment]
The world DarkAss, is there anything special about it? It appears that it isn't loaded before Towny loads.

**Comment by DragoNjesterz** [comment]
It was just a new world we created most recently to put towny in.

**Comment by DragoNjesterz** [comment]
Is there anything you would like me to test? I'm not sure why this world would load slower than all the others.

**Comment by LlmDl** [comment]
Can you share your MV config.yml and worlds.yml

**Comment by DragoNjesterz** [comment]
Multi-Verse: https://pastebin.com/6BAKxhsq
Worlds: https://pastebin.com/DGMHPs0J

**Comment by LlmDl** [comment]
DarkAss has hidden: false and autoload: true so again, I am stumped.

You could try removing some plugins, keeping just the minimum for Towny and Multiverse and see if you get the world loading before Towny or you can check with the MV team about why a couple worlds would load later.

**Comment by DragoNjesterz** [comment]
Hmm, alright. I'll post up a question with them and see what I can do on my end to figure out why it's doing that. Would you like me to close this issue?

**Comment by LlmDl** [comment]
Good to know.
