### ISSUE TITLE
TownBlocks with unregistered Towns in them are being loaded instead of deleted automatically.

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3911]
### What steps will reproduce the problem?
1. Town falls due to day change or deletion
2. Server crashes/restarts
3. Some plots may now be marked as part of "some town" instead of being unclaimed.

More info here: https://github.com/EarthMC/Issue-Tracker/issues/1056

Also if someone tries to claim these plots money is taken from them but the plots are not claimed.

![image](https://user-images.githubusercontent.com/18099825/79249267-4ad97b00-7e7d-11ea-81d4-a23ac95b2777.png)

![image](https://user-images.githubusercontent.com/18099825/79249308-5a58c400-7e7d-11ea-86d1-a491a10a51c3.png)

### What is the expected output?
The plots should remain unclaimed or be unclaimed when towny realises they are not part of a town.

### What is your Towny version?
0.96.1.1

### What is your spigot/craftbukkit version?
¯\\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/18099825/79245595-989fb480-7e78-11ea-9333-b9c17f10fdaa.png)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[2020-04-13-4.log.txt](https://github.com/TownyAdvanced/Towny/files/4476561/2020-04-13-4.log.txt)
2. Your Towny config.yml (if using MySQL please remove password,) : [config.yml.txt](https://github.com/TownyAdvanced/Towny/files/4476347/config.yml.txt)
3. Your townyperms.yml : 
[townyperms.yml.txt](https://github.com/TownyAdvanced/Towny/files/4476363/townyperms.yml.txt)

4. Your log's error : 

No errors when someone uses /t claim but this comes up in the console regularly:
![image](https://user-images.githubusercontent.com/18099825/79246672-ca654b00-7e79-11ea-84b2-6b1615589aaf.png)

**Comment by LlmDl** [comment]
0.96.1.3 has debug messaging added so that the NPE you get will show us which townblocks are causing it.

If a townblock has no town entered it should auto-delete itself when towny starts up.

I'd be curious to see what the messed up townblocks' files say in them.

**Comment by KarlOfDuty** [comment]
Fair enough, I will update it when possible.

**Comment by LlmDl** [comment]
It should also not be happening after updating to 0.96.1.1, we did have one server who had some long-gone townblocks come back because the towny\data\townblocks\world\townblockfiles were never actually deleted and got reactivated with the change to townblock loading/saveing.
