### ISSUE TITLE
Players changing their names lose their towny data

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3912]
### What steps will reproduce the problem?
No idea, it would seem like townynameupdater is not active but it is enabled successfully according to the server.

Not sure what I should use to troubleshoot this.

### What is your Towny version?
0.96.1.1, 4.0

### What is your spigot/craftbukkit version?
¯\\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/18099825/79245595-989fb480-7e78-11ea-9333-b9c17f10fdaa.png)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[2020-04-13-4.log.txt](https://github.com/TownyAdvanced/Towny/files/4476561/2020-04-13-4.log.txt)
2. Your Towny config.yml (if using MySQL please remove password,) : [config.yml.txt](https://github.com/TownyAdvanced/Towny/files/4476347/config.yml.txt)
3. Your townyperms.yml : 
[townyperms.yml.txt](https://github.com/TownyAdvanced/Towny/files/4476363/townyperms.yml.txt)

**Comment by LlmDl** [comment]
I've got a proposed version 5.0 that isn't public yet, did you want to test it out?

**Comment by KarlOfDuty** [comment]
I mean maybe? Think it may solve the issues?

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/644202798707114038/703602763925291088/unknown.png

https://cdn.discordapp.com/attachments/644202798707114038/703601188037328896/unknown.png

First bit of head-way.
