### ISSUE TITLE
Towns in one Nation can claim chunks close to each other

### ISSUE THREAD

**Issue by Darutan92** [TownyAdvanced/Towny#3913]
Towns in one Nation can claim chunks close to each other, as well as allied nations, ignoring the "min_plot_distance_from_town_plot". So done at Factions, it is surprising that there is no such division in Towny.
![image](https://user-images.githubusercontent.com/60871654/79294615-a7718000-7ee7-11ea-9d97-b5771e6ce6e0.png)

**Comment by marik354** [comment]
that I think, is already possible
