### ISSUE TITLE
titles set using "/n set title (name) (title)" no longer have space after them

### ISSUE THREAD

**Issue by StubbiestPeak75** [TownyAdvanced/Towny#3915]
These titles were made using /n set title (name) (title)
Titles blend into the name. (Before, they would have space between title and name, see example below)
### What is your Towny version?
 0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Paper-243 (MC: 1.14.4)

1. Your full server startup from the logs\latest.log : https://pastebin.com/eDqXkqh3
2. Your Towny config.yml : https://pastebin.com/JBHRnsFf
3. Your townyperms.yml : https://pastebin.com/uiscC4Kt
4. Your log's error : There is no error in log

If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/xNi0aqTt
7. Your channels.yml : https://pastebin.com/hC0hMVVe

Example: https://imgur.com/a/ZrcNXeW

**Comment by LlmDl** [comment]
So I fixed this a while back and just forgot to release the new version of TownyChat: https://github.com/TownyAdvanced/TownyChat/releases/tag/0.69
