### ISSUE TITLE
Suggestion: Move bucket perms to build/destroy instead of item_use

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3917]
Basically as it places/removes blocks I think it would be more appropriate to have them as part of the build/destroy perms. Our players wish to allow things like boats and minecarts but not block greifing within their claims.

**Comment by LlmDl** [comment]
It is probably a good idea to also consider flint&steel as building a fire block as well if we're making item_use have less of an effect on items that place a block into the world (and not an entity like boats/carts.)

**Comment by k4deng** [comment]
Agreed.

**Comment by LlmDl** [comment]
[x] Decouple buckets from item_use.
[x] Decouple flint_and_steel from item_use.
[ ] Decouple axes and log stripping from item_use.
[ ] Decouple dyes and dying animals/signs from item_use.
