### ISSUE TITLE
Suggestion: Player Created Custom Ranks

### ISSUE THREAD

**Issue by ZenXP815** [TownyAdvanced/Towny#3918]
**Please explain your feature request to the best of your abilities:**
As of right now custom ranks can only be created by admins, I'm suggesting a feature that would allow kings/mayors to create custom ranks, manage these (adding/removing permissions), and appointing members with these ranks. Kings/mayors will also be able to create ranks that gives players permission to create ranks too.

**Comment by LlmDl** [comment]
This sort of thing has been turned down in the past, because we would have to have an entire list of permission nodes that are 'safe' to give out. This would have to be manually managed by the admin anyways.
