### ISSUE TITLE
Allow for servers to opt out of Mayors receiving TOWN_OWNER TownBlockStatus.

### ISSUE THREAD

**Issue by AdrienFd** [TownyAdvanced/Towny#3919]
### What steps will reproduce the problem?
1. JavaJDK 11.0.6 on the server.
2. I have a Bungeecord Network.
3. One of these servers is dedicated to a rp/town style.
4. This server is a spigot server with some plugins : 
- Authme
- EssentialsX
- Multiverse-Core
- ProtocolLib
- SkinsRestorer
- TimeIsMoney
- Towny
- TownyChat
- TownyNameUpdater
- Vault
- WorldEdit
- WorldBorder
5. I tweaked the towny config files to my needs (see the conf linked at the end).
6. Player wasn't OP.

### What is the expected output?
1. Eveything in towny seem to be working great except some mayor/resident permission.
2. I expect these behaviors : 
- Resident CAN build, destroy, switch, use in PLOT THEY OWN [OK]
- Resident CAN switch, use in TOWN OWNED PLOT [OK]
- Resident CAN NOT build, destroy in TOWN OWNED PLOT [OK]
- Friend CAN build, destroy, switch, use in FRIEND OWNED PLOT [NOK]
- Mayor CAN build, destroy, switch, use in TOWN OWNED PLOT [OK]
- Mayor CAN NOT build, destroy, switch, use in RESIDENT OWNED PLOT [NOK]
3. Explanations of NOK
- [Friend] When I created the server I only activate switch and use for friends, that was working and the output of /plot perm in resident plot was : 
_. . . Perm: Build = ---- Destroy = ----
. . . Perm: Switch = f--- Item = f---
. . . PVP: OFF Explosions: OFF Firespread: OFF Mob Spawns: OFF_
Now, I have added build and destroy for friend in the config but it's not taking effect the output of /plot perm is still the same : 
_. . . Perm: Build = ---- Destroy = ----
. . . Perm: Switch = f--- Item = f---
. . . PVP: OFF Explosions: OFF Firespread: OFF Mob Spawns: OFF_
But i expect this one from my settings (BTW this is valid for already existing plot and newly created plot from new town claim) : 
_. . . .Perm: Build = f--- Destroy = f---
. . . Perm: Switch = f--- Item = f---
. . . PVP: OFF Explosions: OFF Firespread: OFF Mob Spawns: OFF_
- [Mayor] I want mayor to have access to town claim and friend plot normaly (destroy, build, use, switch). For the town own claim it's good, but for player owned plot it's not, mayors can destroy, build, use, switch (friend and non friend plot) I don't wan't that, it's the not the way I have made my permissions, in townyperm I switched towny.claimed.owntown.* to towny.claimed.townowned.*
The /plot perm of a town owned claim is this one in case it's needed :
_. . . Perm: Build = ---- Destroy = ----
. . . Perm: Switch = r--- Item = r---
. . . PVP: OFF Explosions: OFF Firespread: OFF Mob Spawns: OFF_
The output seems to be good, at least the 'r' for resident is decent.

### What is your Towny version?
Towny-0.96.1.0
TownyChat-0.68
TownyNameUpdate-4.0

### What is your spigot/craftbukkit version?
Spigot-1.15.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/XL3nx8LP

2. Your Towny config.yml (i use MySQL) : https://pastebin.com/FL1hSXya

3. Your townyperms.yml : https://pastebin.com/sp31kLLV

4. Your log's error : No errors in towny logs file from logs folder.

5. (optional) If this is to do with permissions, 
Your permissions file : No plugin for permission for the moment.

6. (optional) If this is to do with chat,
Your chatconfig.yml : https://pastebin.com/Je9NGPS1

7. (optional) If this is to do with chat,
Your channels.yml : https://pastebin.com/jxeVDnzj

I tried to as clear as possible, thank you !

**Comment by LlmDl** [comment]
Thanks, I'll look into this. Just so you know, previously made plots' perm lines do not change when the config is changed. That part of the config is only for newly claimed plots.

**Comment by AdrienFd** [comment]
Yeah, that was what I supposed, this is the reason why I tried both existing plots and new plots (on wilderness to do /town claim, /plot fs and then use a resident account to /plot claim) 
It's doesn't seem to use the new config at all, but that's not my main concern because from scratch on a test server if the config is done correctly before any town claim is made this work.

**Comment by LlmDl** [comment]
So I've looked into this and it is a different case for Mayors.

When Towny calculates whether a player can do something or not the results are cached so that it as lite-weight as possible.

When we calculate a TownBlock's status mayors are given the TOWN_OWNER status.

When we check a permission we quickly get a number of Statuses out of the way:
```
if (status == TownBlockStatus.OFF_WORLD || status == TownBlockStatus.PLOT_OWNER || status == TownBlockStatus.TOWN_OWNER)
    return true;
```
Doing this right away means Towny doesn't have to run through 340 lines of further tests. The test that the mayor would eventually have (the one for towny.claimed.townowned.*) would mean that every time mayors are doing something in their town they would also have a permission node test.

So the short story is doing what you want is taxing on the server, for what is essentially a mayor having a made-up rule over land in their own town: There isn't anything stopping a mayor from just taking back the plot at any time they want.

**Comment by AdrienFd** [comment]
I kinda get your point of view !

But still, i have a question so I have residents with a rank builder which have the permission towny.claimed.townowned.*, this means they ran through these 340 lines of codes ?

It's a human trust issue that I want to correct with this permission and it's behavior.
It will remove temptation from mayor to look into chest, pick up block they want from resident build until they evict the resident of it's plot.
This is an more an enhacement proposition : To be perfect when mayor evict a resident from a plot the ideal would be an option to /plot clear automatically so nothing is left on the plot, therefore no intentional evict and "grief".

**Comment by LlmDl** [comment]
Those builders are running through some of them yes, not all.

I may end up making a config option that does away with the TOWN_OWNER status which would make the permission nodes work for mayors.
Then you can have it your way and deal with a bit more thinking/lag, while others are unaffected.
