### ISSUE TITLE
Towny mysql issue

### ISSUE THREAD

**Issue by imcsw** [TownyAdvanced/Towny#3921]
### What steps will reproduce the problem?
1. Convert Towny data from flatfile to mySQL.
2. Restart server after the initial startup post conversion.

### What is the expected output?
1. Towny boots into safe mode.
2. Logs state that it could not read a town because a resident's file is missing.
3. After fixing, the same error will appear with a different town and resident.

### What is your Towny version?
Do not say "latest".
Towny 0.96.1.4

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 1.15.2, build 183

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/2LfwkmQh
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/ivkgVXwm
3. Your townyperms.yml : https://pastebin.com/uNNtxneu
4. Your log's error : https://pastebin.com/6L0RbqBa

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Fixed as of 0.96.1.5
