### ISSUE TITLE
Setting switch permission for plots not working for nation members

### ISSUE THREAD

**Issue by CadeKatal** [TownyAdvanced/Towny#3922]
### What steps will reproduce the problem?
1. /plot set perm nation switch on

### What is the expected output?
1. Nation members are able to switch levers and trapdoors

### What is your Towny version?
0.96.0.0, should be the version where plot groups are released.

### What is your spigot/craftbukkit version?
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Skipped form. When you resubmit I need to know if the plot is personally owned or town owned.
