### ISSUE TITLE
Question: How to make some ranks with different amount of claim

### ISSUE THREAD

**Issue by robrunner69** [TownyAdvanced/Towny#3925]
I would like to setup a server with the towny plugin. And I would like to make that when you buy a rank in the shop you have more chunks to claim. I actually did this for the owner:
```
  Owner:
    default: false
    permissions:
    - '*'
    - -vanish.effects.*
    - +vanish.effects.toggle.all
    inheritance:
    - admin
    info:
      prefix: '&4[Owner]&f'
      build: true
      suffix: ''
      towny_maxplots: -1
      towny_extraplots: 264
```
But it doesn't work. So how could I do?

**Comment by LlmDl** [comment]
You are not allowed to sell parts of Towny in ranks. It is against the license.

**Comment by robrunner69** [comment]
I am not selling parts and don't close my subject
the shop I am talking about is in game like the moderator rank

**Comment by LlmDl** [comment]
You can configure how many plots a player can own personally using the maxplots and extraplots meta nodes like you have above.

**Comment by robrunner69** [comment]
yes but it doesn't work

**Comment by robrunner69** [comment]
I am blocked to 8 plots

**Comment by LlmDl** [comment]
If it doesn't work, file a bug report ticket and don't skip the form.
