### ISSUE TITLE
/t set title leads to 70GB logfile - Error: SQL: Data truncation: Incorrect string value

### ISSUE THREAD

**Issue by TKwSni** [TownyAdvanced/Towny#3926]
### What steps will reproduce the problem?
1  /t set title Anthony (笨ｿ笳｡窶ｿ笳｡)

### What is the expected output?
Deny those kind of title in the command maybe?

### What is your Towny version?
Do not say "0.96.1.2".

### What is your spigot/craftbukkit version?
paper "1.15.2".

### Error:

```[19:11:27] [Craft Scheduler Thread - 3463/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: SQL: Data truncation: Incorrect string value: '\xE2\x9C\xBF\xE2\x97\xA1...' for column `dbtowny`.`TOWNY_RESIDENTS`.`title` at row 1 --> com.mysql.jdbc.JDBC42PreparedStatement@3e3fffcc: REPLACE INTO TOWNY_RESIDENTS (`nation-ranks`, `metadata`, `JailDays`, `town`, `town-ranks`, `registered`, `isNPC`, `title`, `friends`, `isJailed`, `JailTown`, `surname`, `name`, `JailSpawn`, `protectionStatus`, `lastOnline`) VALUES ('','','0','Krams','vicemayor','1530407337330','0','(笨ｿ笳｡窶ｿ笳｡)','francis','0','','','Anthony','0','residentBuild#residentDestroy#residentSwitch','1587164415245')```

Later After checking my db, the title was set to "[[[[[]]]]]" _Edit: actually this was the last title he set for himself_

The only relevant settings might be that I use towny in spanish and mysql.

The startup log weights 70gb but thats the only line repeating itself until server crash, well I actually dont know if it crashed or not, I cant see the end of the file.

**Comment by LlmDl** [comment]
I need to see the startup, the config.

**Comment by TKwSni** [comment]
I made a test server with clean install of towny, I only set my databse to mysql, the error is easy to reproduce, no special config or anything.

Here is the log, funny that I copied and pasted the command and changed to an emoji in my local server log.

https://pastebin.com/raw/Bs6HutTn

**Comment by LlmDl** [comment]
I need to see your config for your regex settings.

**Comment by LlmDl** [comment]
So I decided to test this without your config.

I was able to /t set title NAME (笨ｿ笳｡窶ｿ笳｡) without any issue. I was able to reload the database numerous times and after a full stop and start am able to log in and have my title.

Here's a screenshot showing the title in the database:
![Capture](https://user-images.githubusercontent.com/879756/79641295-3a1a5500-815c-11ea-8538-85327b79bddb.PNG)

Could not reproduce, sorry.

**Comment by suneettipirneni** [comment]
@TKwSni it looks like your database isn't using utf-8, you need to change your encoding or update your SQL software as many modern version support utf-8 out of the box.

**Comment by TKwSni** [comment]
> So I decided to test this without your config.
@LlmDl  My config was set to default when I tested it so I believe it wasnt relevant at all

 
> 
> @TKwSni it looks like your database isn't using utf-8, you need to change your encoding or update your SQL software as many modern versions support utf-8 out of the box.

@suneettipirneni Change this probably ? to "utf8_general_ci" ?  these are my towny tables

![imagen](https://user-images.githubusercontent.com/9063912/79669145-7fa04780-8187-11ea-96c7-bc9d0e4c184a.png)


![imagen](https://user-images.githubusercontent.com/9063912/79669055-fdb01e80-8186-11ea-802c-e7eec7473dbd.png)


change to this?

![imagen](https://user-images.githubusercontent.com/9063912/79669158-9777cb80-8187-11ea-9159-c99bba4e2b78.png)

**Comment by suneettipirneni** [comment]
yeah try that

**Comment by TKwSni** [comment]
I tried it, I changed changing every field that was set to latin1 to utf8 and I also changed the database charset and collationto utf8 but I still get the error, what can I do?

**Comment by LlmDl** [comment]
You can try converting to flatfile, then converting back to mysql after you've sorted out the encoding for the entire table.

**Comment by TKwSni** [comment]
Is it possible to get a sql dump of a working db structure?
