### ISSUE TITLE
Question: How to make some ranks with different amount of claim

### ISSUE THREAD

**Issue by robrunner69** [TownyAdvanced/Towny#3927]
I would like that the admin's get more chunk to claim than the other players.
`  Admin:
    default: false
    permissions: []
    inheritance:
    - moderator
    - g:groupmanager_admin
    - g:bukkit_admin
    - g:essentials_admin
    - g:towny_admin
    - g:vanish_admin
    info:
      prefix: '&c[Administrateur]&f'
      build: true
      suffix: ''
      towny_maxplots: -1
      towny_extraplots: 264`
that's what I did and it doesn't work. And I actually don't find the file where we have to change the amount of chunk a member can claim

**Comment by LlmDl** [comment]
File a [Bug Report](https://github.com/TownyAdvanced/Towny/issues/new?assignees=&labels=bug&template=bug_report.md&title=) ticket and don't skip the form.
