### ISSUE TITLE
Unable to set spawncosts

### ISSUE THREAD

**Issue by dorsax** [TownyAdvanced/Towny#3929]
### What steps will reproduce the problem?
1.  `/town set spawncost 10`
2.  Output is `[Towny] Conversion = h, Flags =` where [Towny] is yellow and the rest is red
2.a) no permission issue, I have all permissions granted via permission plugin
2b) not a single user problem on our server -  others have submitted that problem, too

### What is the expected output?
Towny should tell me in my language, that I have successfully changed the spawncosts.

### What is your Towny version?
0.96.1.3

### What is your spigot/craftbukkit version?
Paper version git-Paper-161 implementing Spigot API 1.15.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/XSAtgYEg
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/PUYWWQFT
3. Your townyperms.yml : https://pastebin.com/WZwCkcGD
4. Your log's error : N.A.

**Comment by LlmDl** [comment]
Your log says you're maybe not using the correct command: 
```
[17:11:47] [Server thread/INFO]: Cobert2016 issued server command: /t set stawncost 0
[17:11:57] [Server thread/INFO]: Cobert2016 issued server command: /town set stawncost 0
```

**Comment by dorsax** [comment]
> Your log says you're maybe not using the correct command:
> [17:11:47] [Server thread/INFO]: Cobert2016 issued server command: /t set stawncost 0
> [17:11:57] [Server thread/INFO]: Cobert2016 issued server command: /town set stawncost 0


Others may not use it correct, but I do:

```
[17:07:40] [Server thread/INFO]: dor_sax issued server command: /town set spawncost 10
[17:07:42] [Server thread/INFO]: dor_sax issued server command: /town set spawncost 0
```

**Comment by LlmDl** [comment]
Can you show me a screenshot of what the output is

**Comment by dorsax** [comment]
I didn't know I could that, otherwise I would've pasted it in the initial issue:
![image](https://user-images.githubusercontent.com/56792918/79642500-1ed03980-819e-11ea-93e7-636483b72b12.png)

**Comment by LlmDl** [comment]
Show me your german.yml

**Comment by dorsax** [comment]
Here you go:
https://pastebin.com/MxaP0Q5w
As far as I know we have alway copy&pasted this from the GitHub language files.

**Comment by LlmDl** [comment]
Try setting `msg_spawn_cost_set_to: '&b% hat den Preis für /%s spawn auf %s gesetzt'`
to `msg_spawn_cost_set_to: '&b%s hat den Preis für /%s spawn auf %s gesetzt'`

**Comment by dorsax** [comment]
Thank you, this did the trick!
I also reviewed the original german.yml here: https://github.com/TownyAdvanced/Towny/blob/master/resources/german.yml 
The same problem occurs in line 817. I suggest to change this line to the one suggested by you.

**Comment by LlmDl** [comment]
Yep I was just waiting for confirmation from you that that was the issue.
