### ISSUE TITLE
diamond ore and stuff regenerating

### ISSUE THREAD

**Issue by yimyum** [TownyAdvanced/Towny#3933]
### What steps will reproduce the problem?
1.Place diamond ore
2.Explode with tnt
3.Diamond ore regenerates

### What is the expected output?
1.Place diamond ore
2.Explode with tnt
3.Diamond ore doesn't regenerate

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
PaperMC Build #196

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/wpVLPjgm
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/y5RQLCvZ
(Towny config has regeneration disabled to prevent duping until fixed)
3. Your townyperms.yml :
https://pastebin.com/ShKFQZPX
4. Your log's error : 
None

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
No one's mentioned diamond ore being a problem (except for when they have McMMO's blast mining and /tw toggle revertexpl on,) anyways, I've sorted out duping in 0.96.1.5, so please re-test there. (Assuming this isn't being done with blast mining.)

**Comment by yimyum** [comment]
yes its a blast mining problem thats why i'd rather rare materials dont regenerate

**Comment by LlmDl** [comment]
Either turn off the revert on unclaim (in the world, not the config,) or turn off blast mining.
