### ISSUE TITLE
Suggestion: Nation Add/Remove Ally Events

### ISSUE THREAD

**Issue by jimender2** [TownyAdvanced/Towny#3940]
**Please explain your feature request to the best of your abilities:**
Right now there is only a listener for when allies are invited ally the nation, not when they actually ally the nation. Similar to the NationAddEnemy event listener already built in.

**Comment by jimender2** [comment]
An unally listener would be nice too.

**Comment by LlmDl** [comment]
Should be:
NationAddAllyEvent
NationRemoveAllyEvent
NationAddEnemyEvent
NationRemoveEnemyEvent

**Comment by jimender2** [comment]
I think enemy is already taken care of.
NationAddEnemyEvent
NationRemoveEnemyEvent

**Comment by LlmDl** [comment]
Right you are.

**Comment by LlmDl** [comment]
This one is possible using the existing NationAcceptAllyRequestEvent and the NationRemoveAllyEvent.
