### ISSUE TITLE
Suggestion: Town/Nation government types leading to subsets of Town/Nation ranks

### ISSUE THREAD

**Issue by Issemir** [TownyAdvanced/Towny#3942]
**Please explain your feature request to the best of your abilities:**

Create a configurable list of nation government types which can be chosen with /n set type (A/B/C/D) or some such command. These would then outline different possible town government types for towns within that nation, and nation rank subsets for users within that nation. An example of the types could be Federalism, Autonomy (towns can choose any Town govt type), Authoritarianism, Libertarianism, although this would be left to server admins to configure/flavour

Next, a configurable list of town government types which can be chosen with /t set type (A/B/C/D) or something similar. Each town government type will allow the town to use ranks within a SPECIFIC subset of ranks that could be unique to that government type. Towns which aren't in a nation could be allowed to choose any government type (or none and forced to join a nation for the feature).

The range of town government types could then cater more appropriately for different towns based on their goals and needs. For example, towns which strictly build in plots may want a very different set of permissions (and thus government type) than a town which is free build. A town which is project-based with 80% resource gatherers and 20% builders may want even different ranks and thus a different government type. I feel this suggestion would allow towns to select a subset of ranks which suits them and their requirements without having the confusion of a load of Towny ranks they don't care about. 

You could even go further with the idea and implement different tax features to different town/nation types etc, and making different subsets of configurable plot types available to each government type for a town. If any expansion to this idea is required I'd be happy to do so.

**Comment by LlmDl** [comment]
This would involve a config section in config.yml or townyperms.yml which has various ranks and their customizable permissions structured underneath the various 'government types'.

**Comment by Tauses** [comment]
This sounds really awesome.
