### ISSUE TITLE
townyperms.yml not working.

### ISSUE THREAD

**Issue by smqne** [TownyAdvanced/Towny#3952]
### What steps will reproduce the problem?
Unknown, I installed PaperMC, Towny, and LuckPerms.

### What is the expected output?
For townyperms.yml to work.

### What is your Towny version?
Version: 0.96.1.0 - Mod Disabled

### What is your spigot/craftbukkit version?
Paper version git-Paper-213 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/9SYj8ut8
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/N8mCXKr0 (Its literally the default config)
3. Your townyperms.yml :
https://pastebin.com/D7Ljvveb
4. Your log's error : 
Players do not have permissions, so a "insufficient perms" msg appears.
However, I was able to prompt an error by using "/townyadmin town new a smqne" which is:
https://pastebin.com/JCFQmiqg
(optional) If this is to do with permissions, 
5. Your permissions file :
I am running LuckPerms but I have not added any ranks/perms.

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by v3Monsta** [comment]
Interesting, this is actually something that I noticed as well but figured it was because of something I had misconfigured. I also have LuckPerms installed and nomads were unable to join a town.

**Comment by LlmDl** [comment]
I just tested this:

Using: /ta town new LTOWN Rickard_Stark23
Town was made, no permission error.
Resident is mayor of town. Homeblock is where I was standing on my main account.

I did go and look at where the NPE is and it is failing to get the world you are standing in.
```
TownyWorld world = townyUniverse.getDataSource().getWorld(player.getWorld().getName());
```

Were you standing in a non-Towny world?

**Comment by smqne** [comment]
> I just tested this:
> 
> Using: /ta town new LTOWN Rickard_Stark23
> Town was made, no permission error.
> Resident is mayor of town. Homeblock is where I was standing on my main account.
> 
> I did go and look at where the NPE is and it is failing to get the world you are standing in.
> 
> ```
> TownyWorld world = townyUniverse.getDataSource().getWorld(player.getWorld().getName());
> ```
> 
> Were you standing in a non-Towny world?

This happened it a brand new, practically vanilla test server. Only luckperms and towny installed. As such, only the default world's were generated. I didn't config towny to be on the default world as I assumed it would default to those world's anyways.

**Comment by LlmDl** [comment]
So the world you were standing in has usingTowny=false?

**Comment by smqne** [comment]
I'm away from my computer right now but will check this when I get back. 

However on the main server where I am having this townyperms issue I was sure to make sure I used the command (I think /townyworld enable? Can't remember it off the top of my head but I used whatever the wiki said to) on the world's I wanted to be towny.

Also, towny works as long as I add the permissions associated with the commands to the default rank. However, this isn't a solution as it would let any town member have access to mayor commands and such. The only solution I can come up with is to manually add mayor's/assistants/Kings/etc to their own group.

**Comment by LlmDl** [comment]
This could be just an issue of LP desyncing which is somewhat common. Either /lp sync or have the player relog.

**Comment by smqne** [comment]
> This could be just an issue of LP desyncing which is somewhat common. Either /lp sync or have the player relog.

I tried lp sync when the issue first started to occur because I saw a similar issue where this seemed to solve it. This did not help me. I haven't tried to have the player relog yet

**Comment by LlmDl** [comment]
Well the startup you showed me looked fine enough. I believe your LuckPerms is fairly out of date though. 

My test machine has LP on it as well and I didn't have any issue. 

The actual error you have in your ticket is from doing the command in a world that Towny doesn't recognize as being a Towny world. (usingTowny=false)

**Comment by smqne** [comment]
I'm running luckperms 5.0.72.

If I tried to use the command to toggle unclaim Regen and it didn't work would that mean the world I'm in doesn't support towny? Even though it still regens?

Also, upon further inspection it seems that the issue is towny isn't actually changing the player to the role they should be. Even though doing /t <name> will show a player being the mayor, doing /res <name> shows they aren't even in a town.

**Comment by LlmDl** [comment]
I dunno. You're not really describing things very well. 

Did you do `/tw toggle revertunclaim` or something else? What exactly does it say as a response? Show me a screenshot of what the `/tw` command outputs.

Also, in the OP you're using the command on yourself, is that what you're doing?

**Comment by smqne** [comment]
Yes. And sorry for being vague, I'm working right now and don't have access to my computer so I'm trying to describe everything off of my memory, which is pretty shoddy. I can wait to reply when im back

**Comment by smqne** [comment]
Fixed it. For people with the same issue:

Set include-global-world: to true. Tried to do per world perms and I guess towny doesn't like that.

**Comment by LlmDl** [comment]
That really shouldn't affect towny at all. Odd though.

**Comment by smqne** [comment]
Before I changed that one setting, it didnt work. After I changed it and restarted the server, it worked.
