### ISSUE TITLE
Issue with commands and chat formatting for Nation residents

### ISSUE THREAD

**Issue by awhitekorean** [TownyAdvanced/Towny#3954]
### What steps will reproduce the problem?
1. Being a part of a nation and typing "/town"
2. Being a part of a nation and typing in chat
3.

### What is the expected output?
1.  no information will be displayed (command is executable, but no information displays)
2. Names will appear as "[Town|Nation] [Job] {townyprefix}playername{townypostfix}"
3.

### What is your Towny version?
Do not say "latest".
- 0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
- Spigot 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/eBibb8ub
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/G4CwzSGB
3. Your townyperms.yml :
https://pastebin.com/i1g0wxgq
4. Your log's error : 
n/a
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://pastebin.com/X0ueuKEM
7. Your channels.yml :
https://pastebin.com/PyQRTHT7

**Comment by LlmDl** [comment]
I'm going to need your jobs config(s) in order to debug this.

**Comment by LlmDl** [comment]
Your config's nation_level is missing a level with numResidents: 0

add this:
```
  - kingPostfix: ''
    capitalPostfix: ' (Capital)'
    upkeepModifier: 1.0
    kingPrefix: 'Hokage '
    capitalPrefix: ''
    numResidents: 0
    nationBonusOutpostLimit: 1
    namePostfix: ''
    townBlockLimitBonus: 2
    namePrefix: 'Nation of '
    nationZonesSize: 1
    nationTownUpkeepModifier: 2.0
```
