### ISSUE TITLE
Question: How to give someone from another Town the permission to build?

### ISSUE THREAD

**Issue by dandud100** [TownyAdvanced/Towny#3955]
I set up my own town and nation but I still want to be able to build in another town. Is this possible?

**Comment by suneettipirneni** [comment]
`/res friend add {player}`

**Comment by LlmDl** [comment]
If the town is in your nation they can allow people in the nation to build in areas. Or you can buy an embassy plot in another town.

**Comment by dandud100** [comment]
It is a different nation

**Comment by LlmDl** [comment]
Then it would require the allies flag to work like I said before but that opens it up to a lot more people potentially. The owner of the other nation cannot give you and only you, access to all the plots aside from his own.

**Comment by dandud100** [comment]
Is it possible to add this feature?

**Comment by Momshroom** [comment]
https://prnt.sc/rimx5d

**Comment by LlmDl** [comment]
I don't think we intend on adding names to plots which would whitelist any action, no. Momshroom has a nice guide there.
