### ISSUE TITLE
permissions won't work randomly

### ISSUE THREAD

**Issue by dorsax** [TownyAdvanced/Towny#3956]
### What steps will reproduce the problem?
We had a misconfiguration with the permissions: we gave them additionally through LuckPerms (permission plugin), so everyone had all permissions on nations and towns without knowing it. After we removed them there and moved any changes to the `townyperms.yml`, we now have very odd moments:
1. log in
2. use a command you have permissions in like `/t spawn` -> no permission
3. log out, log in
4. use command like `/t spawn` -> success

Server was rebooted multiple times, LuckPerms database is flawless clean of any towny permission except that `towny.wild.*` is set to false.
I cannot reproduce this on purpose, it is kinda random. Also, it is not affected by the kind of command or the rank, it affects residents and mayors (nations are disabled). Groups like `Admin` with all permissions granted via LuckPerms have no such problems.

### What is the expected output?
No need to relog for the use of those commands.

### What is your Towny version?
0.96.1.3

### What is your spigot/craftbukkit version?
Paper version git-Paper-161 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/1BAcZs3Q
2. Your Towny config.yml: https://pastebin.com/XvBbFEL7
3. Your townyperms.yml : https://pastebin.com/dtyZeGbL
4. Your log's error :  n/a

(optional) If this is to do with permissions, 
5. Your permissions file : Luckperms cannot be pasted, Bukkitperms is empty

**Comment by LlmDl** [comment]
If /t spawn doesn't work you can try using /lp sync, LuckPerms has an issue with desyncing the permissions on the server, sadly affecting townyperms.

**Comment by LlmDl** [comment]
Here is the ticket for it on LuckPerms: https://github.com/lucko/LuckPerms/issues/1330
