### ISSUE TITLE
Checking resident/town/nation info gives no feedback message in console if the name is invalid

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#3957]
Basically using a command such as `t testtesttest` in the console doesn't give any feedback message at all if that town doesn't exist. Same for nations and residents.

As for server info, nothing has changed since the last issue so you can find that info there.

**Comment by suneettipirneni** [comment]
I can't seem to reproduce this, what does `/town testtesttest` say?

**Comment by suneettipirneni** [comment]
Disregard that last comment
