### ISSUE TITLE
Admin withdraw disable

### ISSUE THREAD

**Issue by etysoftware** [TownyAdvanced/Towny#3959]
I making a custom war plugin (with pvp-points to win) and I need setAdminEnabledWithdraw() funciton. I can do it by myself with your sourcecode, but it's gonna be more cooler if you will make it in original TownyAdvanced. If that function already exists, please, give me information about it.

**Comment by LlmDl** [comment]
Could you explain a little bit better what it is you want?

**Comment by etysoftware** [comment]
There is setAdminPvPEnabled() and i want the similar, but with withdraw in town

**Comment by LlmDl** [comment]
So the end goal is to make it so Mayors cannot withdraw?

**Comment by etysoftware** [comment]
yes. All residens can't.

**Comment by etysoftware** [comment]
setAdminEnabledWithdraw(boolean)

**Comment by LlmDl** [comment]
There is a config option for this:

```
    # Set to true to allow withdrawals from town banks
    town_allow_withdrawals: 'true'

    # Set to true to allow withdrawals from nation banks
    nation_allow_withdrawals: 'true'
```
There are also events thrown for Towny town and nation transactions which you can cancel.

**Comment by etysoftware** [comment]
No. I mean toggle this personally for each town. And could be via Towny API

**Comment by LlmDl** [comment]
Right now you can do it per-town using the TownPreTransactionEvent and NationPreTransactionEvent.

Having those events which are cancellable means we don't have to add a per-town and per-nation withdrawal option.

**Comment by etysoftware** [comment]
Thanks a lot!
