### ISSUE TITLE
Dollar signs ($) do not work in {permuserprefix}

### ISSUE THREAD

**Issue by muzak23** [TownyAdvanced/Towny#3960]
### What steps will reproduce the problem?
1. Have a group or user prefix with a $ in it
2. Have your chat use {permuserprefix} (may work with other placeholders I'm not sure)
3. Try to chat, you should see {permuserprefix} where you'd expect your prefix(es) to be
Escaping the $ with `\$` works, but is not a fix as people are 

### What is the expected output?
Dollar signs to be outputted in chat normally, without need for the backslash.

### What is your Towny version?
Towny version: 0.93.1.0 for MC 1.12.2

### What is your spigot/craftbukkit version?
Paper 1.12.2 (build 1618)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log: https://pastebin.com/JEkz3bFD
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/kJxR32vN
3. Your townyperms.yml: https://pastebin.com/B9frutxs
4. Your log's error: No errors.

(optional) If this is to do with permissions, 
5. Your permissions file: Not necessary 

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/w4T25bZA
7. Your channels.yml: https://pastebin.com/ZdyFFfa1

**Comment by LlmDl** [comment]
Here's an advance copy: https://cdn.discordapp.com/attachments/669247087329673228/709032110186561606/TownyChat-0.70.jar
