### ISSUE TITLE
[BUG] TownyAdvanced and ItemsAdder conflict.

### ISSUE THREAD

**Issue by Deathroner** [TownyAdvanced/Towny#3962]
I have a problem using the Towny plugin with ItemsAdder.
When using a vehicle, it happens that the game crashes, you cannot send messages by chat or interact with anyone.
I sent a ticket to the developer of ItemsAdder, and he doesn't understand that he may be failing with his plugin alongside Towny.

> https://github.com/LoneDev6/ItemsAdder/issues/189

I understand that ItemsAdder allows you to get into a vehicle, giving passenger option to an "ArmorStand", I didn't find any settings in Towny, which has to do with blocking the use of an armorstand.

I don't want to change to another plugin, the truth is I have a long list of users with cities, and it really only happens to me with Towny.

With TownyAdvanced: https://www.youtube.com/watch?v=FBkit4ypr1c
Without Towny: https://www.youtube.com/watch?v=RJ6VcHXPBnU

### What is your Towny version?
Version: 0.96.1.0

### What is your spigot/craftbukkit version?
PaperMC 1.15.2 - Build #216

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/BkPp9T56
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/F4dVPdqw
3. Your townyperms.yml : https://pastebin.com/dEMQ7KJM

**Comment by LlmDl** [comment]
I've commented on what IA needs to do on their ticket.
