### ISSUE TITLE
Towny does not protect ic2 blocks

### ISSUE THREAD

**Issue by SiriusWhite74** [TownyAdvanced/Towny#3964]
Why does Towny not prohibit outsiders from opening the inventory of mechanisms from ic2? Towny doesn't have this feature?

**Comment by LlmDl** [comment]
Mods are not always easily supported. You can try the following:

If you hold a clay_brick or brick in your hand and hit the ic2 block to get the block name you can put that block name into the switch_ids list in the config. Mods do not always fire events that Bukkit plugins can use so it could be hit or miss.
