### ISSUE TITLE
Chests don't regenerate properly in wilderness after creeper explosion

### ISSUE THREAD

**Issue by emkirsh** [TownyAdvanced/Towny#3965]
### What steps will reproduce the problem?
1. set `wild_revert_on_mob_explosion` to `true` in the config.
2. place a chest and put stuff in it
3. let it get destroyed by a creeper or any other hazard on the list in config.

### What is the expected output?
1. no items drop from chest
2. blocks regenerate
3. chest regenerates but no items are inside, and they didn't drop after the explosion so they're lost forever.

### What is your Towny version?
0.95.2.0

### What is your spigot/craftbukkit version?
git-Paper-226 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: [latest.log](https://gist.github.com/emkirsh/304ea415574c2141f2940fc89df71ba3)
2. Your Towny config.yml (if using MySQL please remove password,): [config.yml](https://gist.github.com/emkirsh/4b0eed22bbb7f8cdbdda6e16e5c1b413)
3. Your townyperms.yml: [townyperms.yml](https://gist.github.com/emkirsh/dffad282e5fcb39bdd4dd9ba2196805e)
4. Your log's error: _there isn't an error in my log, it's a bug, not a failure._

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
No one should be on 0.95.2.0 any more. Update to 0.96.1.0 or 0.96.1.8 and retest. I just tested on 0.96.1.8 and the chest regenerates with its contents.

**Comment by emkirsh** [comment]
Thanks! Sorry I didn't try that first.
