### ISSUE TITLE
Suggestion: Maximum money in % tax

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3967]
**Please explain your feature request to the best of your abilities:**
We would like there be a way for us (or the town mayor) to set a maximum amount of tax that can be taken per player, even when they are in % tax. Mayors do not like using flat tax because it kicks residents from the town due to having no money, but don't want to be unattractive to rich people who have millions and are unwilling to have even 1% tax.

Something like:
/town set maxtax 500

A config option would work, but players will want to have control over this.

**Comment by suneettipirneni** [comment]
So you’re saying a tax that’s a percentage of the resident’s balance?

**Comment by LlmDl** [comment]
He's saying the existing taxpercent (which is a percentage of the player balance,) but capped at a max amount.
