### ISSUE TITLE
Towny Dynmap "java.lang.NoSuchMethodError" console spam

### ISSUE THREAD

**Issue by WasThisUsernameTaken** [TownyAdvanced/Towny#3968]
### What steps will reproduce the problem?
1. Install Towny(and all plugins in the zip), Dynmap and Towny Dynmap
2. Start server
3. see console spam

### What is the expected output?
1. no console spam

### What is your Towny version?
Towny version: 0.96.1.0
Dynmap-Towny: Dynmap-Towny-0.80
Dynmap version: 3.0-beta-257

### What is your spigot/craftbukkit version?
Paper 227

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/k7k2GCnN
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/raw/wQacPpYu
3. Your townyperms.yml : https://pastebin.com/raw/RBE81mHB
4. Your log's error : https://pastebin.com/raw/wqA4cU19
5. Dynmap Config: https://pastebin.com/raw/A8kvxDu

Maybe related to #3950  but I am running a later version of the Dynmap-Towny plugin.
All plugins were installed on the server at the same time and the error occurred on first launch.

**Comment by LlmDl** [comment]
This should go away once you update to [0.96.1.8](https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.8).
