### ISSUE TITLE
Suggestion: Configurable Dynmap Render Resolution for Towns vs Wild

### ISSUE THREAD

**Issue by DrThicccc** [TownyAdvanced/Towny#3972]
A feature in dynmap-towny so that Towny land claims are rendered at a higher resolution (such as xhi-res 64 ppb) and unclaimed land is rendered at a lower resolution (such as lowres 4 ppb for wild land)? Having high resolution renders for the land people look at most, towns, and low resolution for everything else, the wild, would be a great way to save storage space. I'm not saying to have a resolution beyond what is currently available. It'd have to be Dynmap-towny or an addition to dynmap-towny. The way id imagine it would work is that you set the resolution within dynmap for wild land, which is default. And in Dynmap-Towny you'd have a config to select what resolution to render claimed land. An overlay in a way similar to they way dynmap-towny shows town claims. And if you wanted to, you could make a similar change in Dynmap-worldguard (not you specifically to make the wg change, but the dev for that plugin would do something similar)

**Comment by LlmDl** [comment]
Looks like there is a boost flag we can manipulate, as described here: https://github.com/webbukkit/dynmap/issues/2323#issuecomment-418924802
