### ISSUE TITLE
How can I disable custom colors in surname in title?

### ISSUE THREAD

**Issue by etysoftware** [TownyAdvanced/Towny#3973]
Players can use custom color codes in their town surname and in chat it looks very bad. How can I disable this feauture.

**Comment by silverwolfg11** [comment]
You can prevent the use of color codes in names by removing the '&' in the `regex.string_check_regex` configuration option which if you were initially using the default setting for that and removed the ampersand would look like `string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\*\-\,\*\(\)\{\}]*$`

**Comment by etysoftware** [comment]
it doesn't works

**Comment by LlmDl** [comment]
File a bug ticket if that didn't work.
