### ISSUE TITLE
Question: How to disable color and formatting codes in town names.

### ISSUE THREAD

**Issue by MrNaspo** [TownyAdvanced/Towny#3976]
**Ask your question as best as you are able:**
Hey, I can't find anywhere how to disable color and formatting codes in town names, and anyone help?

**Comment by LlmDl** [comment]
removing `\&` from the name_remove_regex should disallow it.

**Comment by MrNaspo** [comment]
No it still works.

**Comment by MrNaspo** [comment]
I even removed it from string_check_regex and it still works.

**Comment by MrNaspo** [comment]
Actually I think it did work. Thank you!
