### ISSUE TITLE
Suggestion: Prevent capital cities from being taken over in Event War when Town-Ownership transfers are use.

### ISSUE THREAD

**Issue by Louwiiii** [TownyAdvanced/Towny#3977]
A mean for nation not to be disbanded when capitals are conquered, or even to make capital cities not conquerable at all (for example by putting the HP of capital cities home block to a very high value).

**Comment by LlmDl** [comment]
Which war type are you refering to? This is something that Event War already can do.

**Comment by Looowi** [comment]
> Which war type are you refering to? This is something that Event War already can do.

I’m actually talking of event wars. How can you do that, I searched for hours

**Comment by LlmDl** [comment]
Show me your config.yml

**Comment by Looowi** [comment]
https://drive.google.com/open?id=1C3wCj1KGLFoO-Fm0r2YdmtCssbeJQKlk

**Comment by LlmDl** [comment]
You need to turn off `winner_takes_ownership_of_town: 'true'` or there needs to be an added option to prevent capitals from being taken over, and just kicking the nation from the war.

**Comment by Looowi** [comment]
> You need to turn off `winner_takes_ownership_of_town: 'true'` or there needs to be an added option to prevent capitals from being taken over, and just kicking the nation from the war.

Yes thats actually what we need, because we want towns to be taken but not nations or capitals
