### ISSUE TITLE
Spamming console

### ISSUE THREAD

**Issue by Fire177** [TownyAdvanced/Towny#3979]
### What steps will reproduce the problem?
1. A Few seconds after startup
2.
3.

### What is the expected output?
1. Not Spamming
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.1 - 1.12.2

### What is your spigot/craftbukkit version?
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/SwyCJJUa
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/D9f3Y7Lj
3. Your townyperms.yml : https://pastebin.com/kkXvu778
4. Your log's error : https://pastebin.com/iKYNrw9j

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Fire177** [comment]
Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Forgot to add

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/706879558657245265/707243767673127062/Towny-0.96.1.10_-_1.12.2_-_SNAPSHOT_1.jar

Should be fixed with the above jar.
