### ISSUE TITLE
1.15.2 BANK LINKING!! WANT FIX

### ISSUE THREAD

**Issue by etysoftware** [TownyAdvanced/Towny#3980]
### What steps will reproduce the problem?
1. Create a town with name "Малевичград"
2. Create a town with name "Минас Тирит" (/t new Минас Тирит)
3. Use /t deposit
4. Look at banks of both towns, it would be the same

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
spigot 1.15.2 (Java 11)

Towny config.ym: https://pastebin.com/65nRYPn4

**Comment by etysoftware** [comment]
I have deleted Towny folder and restart my local server. And... it's not helps!

**Comment by LlmDl** [comment]
Skipped the form. Invalid Ticket. Resubmit with form filled out.
