### ISSUE TITLE
Suggestion: Add PlotSetForSaleEvent

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#3981]
**Please explain your feature request to the best of your abilities:**

This would be a very useful addition to the API for example a plugin does an action when putting for a plot for sale, then can perform another one after it gets claimed.

**Comment by LlmDl** [comment]
Likewise a not-for-sale event.

**Comment by suneettipirneni** [comment]
> Likewise a not-for-sale event.

We have have that it’s called `PlotClaimEvent`

**Comment by LlmDl** [comment]
The plotclaimevent is not called when someone does /plot nfs though so we should have a notforsaleevent.

**Comment by eUipKh** [comment]
This could be very useful to fix my issue #4022 :(
