### ISSUE TITLE
Bank linking (same banks with different towns)

### ISSUE THREAD

**Issue by etysoftware** [TownyAdvanced/Towny#3982]
### What steps will reproduce the problem?
Create a town with name "Малевичград"
Create a town with name "Минас Тирит" (/t new Минас Тирит)
Use /t deposit
Look at banks of both towns, it would be the same

### What is the expected output?
-. Towns have different banks with different amount of money.

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
spigot 1.15.2 (Java 11)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log: https://pastebin.com/XHK8cY5S
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/w9Py23LQ (default) 
3. Your townyperms.yml : https://pastebin.com/Pc23v0Ds (default)
4. Your log's error (no any errors)
5. Towny log: https://pastebin.com/5UtHRfKi
6. Money csv: https://pastebin.com/s1vybhJq

(optional) If this is to do with permissions, 
5. Your permissions file : no perms

WAIT FOR FIX! It's very important. I tried to to it with clear version of spigot and plugins, but bug exists and it is very bad!

IMAGES:
![image](https://user-images.githubusercontent.com/51130679/81089798-76dc9f00-8f05-11ea-933e-67839622c3ad.png)
![image](https://user-images.githubusercontent.com/51130679/81090014-cde27400-8f05-11ea-9ea6-135ed996099b.png)

If town deletes or creates bank sets to 0.

Works only for that names.

**Comment by LlmDl** [comment]
Test using something other than essentialseconomy. I am fairly sure someone else had this issue and it is a problem with esseco and the cyrillic characters.

**Comment by etysoftware** [comment]
I'm using popular EssentialsX and with another cyrilllic characters it works correctly

**Comment by etysoftware** [comment]
I can't find more usable plugin for economy. Can you give me a link?

**Comment by etysoftware** [comment]
can you make towny compatible with essentialsX?

**Comment by LlmDl** [comment]
Essentials Economy has had major issues with Towny since UUIDs and MC 1.8. Neither the Essentials Team nor the Towny team recommend using their economy with Towny. It is not something I can fix on my end. It is on the EssentialsEconomy side. 

Test with another economy plugin. You said you wanted a quick fix and I bet that is your quick fix.

**Comment by etysoftware** [comment]
but i can't convert essentialsX to TNE, what can i do?

**Comment by LlmDl** [comment]
You can convert esseco to TNE.
