### ISSUE TITLE
Suggestion: Add /towny top balance

### ISSUE THREAD

**Issue by MrNaspo** [TownyAdvanced/Towny#3984]
I feel like this should be a thing, not sure why its not. It would be great if you could make it happen!

**Comment by suneettipirneni** [comment]
Isn’t this the same as an eco plugin giving the top balances?

**Comment by MrNaspo** [comment]
That's for individual users, I'm talking for towns.

**Comment by Darklom** [comment]
I second this, for my leaderboards :D

**Comment by LlmDl** [comment]
Would this be a combination of /town list by balance and /nation list by balance?

**Comment by MrNaspo** [comment]
Yes. But it would be a leaderboard. So far you have **/towny top** for **residents** and **land**. We are just requesting one for **balance** too.

**Comment by LlmDl** [comment]
> Yes. But it would be a leaderboard. So far you have **/towny top** for **residents** and **land**. We are just requesting one for **balance** too.

Yes I was just clarifying what you wanted.

**Comment by ZenXP815** [comment]
This is something I would like, but will towny measure this by the town / nation balance or by the value of blocks, items, etc in town claims?

**Comment by LlmDl** [comment]
We will not be polling every chunk in a town to see how much their blocks/items are worth. It will be bank balances.

**Comment by MrNaspo** [comment]
Yes, it would be by town bank balances.

**Comment by LlmDl** [comment]
For whoever ends up doing this one: this should be a cached thing that last for 5-10 minutes before being updated.
