### ISSUE TITLE
Question: Where can I get TownyFlight and Dynmap-Towny for Towny 0.93.1.0? (1.12.2)

### ISSUE THREAD

**Issue by promlgxd** [TownyAdvanced/Towny#3986]
I think the title says it all.
EDIT - when trying to build it it says 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.dynmap:Dynmap-Towny:jar:0.72
[WARNING] 'dependencies.dependency.systemPath' for org.bukkit:bukkit:jar should not point at files within the project directory, ${project.basedir}/deps/craftbukkit-1.13.2-R0.1-SNAPSHOT.jar will be unresolvable by dependent projects @ line 61, column 17
[WARNING] 'dependencies.dependency.systemPath' for com.palmergames:Towny:jar should not point at files within the project directory, ${project.basedir}/deps/Towny-0.93.0.0.jar will be unresolvable by dependent projects @ line 68, column 17
[WARNING] 'dependencies.dependency.systemPath' for com.palmergames:TownyChat:jar should not point at files within the project directory, ${project.basedir}/deps/TownyChat-0.93.0.0.jar will be unresolvable by dependent projects @ line 75, column 17
[WARNING] 'dependencies.dependency.systemPath' for org.bukkit:bukkit:jar refers to a non-existing file /home/sharkwhiteplayer/Descargas/Dynmap-Towny-0.72/deps/craftbukkit-1.13.2-R0.1-SNAPSHOT.jar @ line 61, column 17
[WARNING] 'dependencies.dependency.systemPath' for com.palmergames:Towny:jar refers to a non-existing file /home/sharkwhiteplayer/Descargas/Dynmap-Towny-0.72/deps/Towny-0.93.0.0.jar @ line 68, column 17
[WARNING] 'dependencies.dependency.systemPath' for com.palmergames:TownyChat:jar refers to a non-existing file /home/sharkwhiteplayer/Descargas/Dynmap-Towny-0.72/deps/TownyChat-0.93.0.0.jar @ line 75, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ----------------------< org.dynmap:Dynmap-Towny >-----------------------
[INFO] Building Dynmap-Towny 0.72
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.426 s
[INFO] Finished at: 2020-05-06T18:53:33+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Dynmap-Towny: Could not resolve dependencies for project org.dynmap:Dynmap-Towny:jar:0.72: The following artifacts could not be resolved: org.bukkit:bukkit:jar:1.13.2-R0.1-SNAPSHOT, com.palmergames:Towny:jar:0.93.0.0, com.palmergames:TownyChat:jar:0.93.0.0: Could not find artifact org.bukkit:bukkit:jar:1.13.2-R0.1-SNAPSHOT at specified path /home/sharkwhiteplayer/Descargas/Dynmap-Towny-0.72/deps/craftbukkit-1.13.2-R0.1-SNAPSHOT.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by LlmDl** [comment]
Towny is on maven but the others are not. You won't find 0.93.0.0 on maven though it is too old. 1.13 servers should use 0.96.1.0 for MC 1.13.2.

**Comment by promlgxd** [comment]
Could I use https://cdn.discordapp.com/attachments/706879558657245265/707324488567750656/Towny-0.96.1.10_-_1.12.2_-_SNAPSHOT_2.jar ?

**Comment by LlmDl** [comment]
That's for 1.12. Use the .jar in this zip https://github.com/TownyAdvanced/Towny/releases/download/0.96.1.0for1.13.2/Towny.Advanced.0.96.1.0.for.1.13.2.zip

**Comment by promlgxd** [comment]
I want to use it for 1.12.2

**Comment by promlgxd** [comment]
It's working so im closing it.
