### ISSUE TITLE
Towny overclaims WorldGuard

### ISSUE THREAD

**Issue by promlgxd** [TownyAdvanced/Towny#3987]
### What steps will reproduce the problem?
1. Create a region with worldguard.
2. A player, inside the region, creates a town.
3. That chunk of the region overrides the region's chunk, although players still can't interact.

### What is the expected output?
1. A player inside the region tries to claim or create a town.
2. A message reporting that there is a region appears.
3. The claim/creation is blocked.

### What is your Towny version?
0.96.1.1.0 - 1.12.2 - SNAPSHOT 2

### What is your spigot/craftbukkit version?
Akarin version git-Akarin-5fe9361 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/VQXHz83T
2. Your towny's config.yml : https://pastebin.com/yukRUeGa
3. Your townyperms.yml : https://pastebin.com/CjmMkYt2
4. Your log's error : No error appears in console at all.

**Comment by LlmDl** [comment]
You can get our plugin https://github.com/TownyAdvanced/WorldGuard-Towny to stop this sort of thing if you're using worldguard in a towny world.
