### ISSUE TITLE
Suggestion: Upkeep based on number of residents

### ISSUE THREAD

**Issue by Looowi** [TownyAdvanced/Towny#3989]
Being able to config that the upkeep is based on the number of residents in the config file.

**Comment by LlmDl** [comment]
The config would be massive if you did this.

**Comment by suneettipirneni** [comment]
I could be a part of the resident file

**Comment by Looowi** [comment]
I’m not sure I was clear. I meant having an option, as the upkeep per number of plots but per resident. This would mean that the upkeep for a town of one person would be of 10 for example, for two it would be of 20 etc. I think it is really important because I’m searching a good mean to prevent fake accounts and inactive players in towns, and having an upkeep based on the resident number would be really helpful I think.

**Comment by LlmDl** [comment]
The town_level already satisfies things which would be per-resident, as the town_level system is based on the numResident line. You would set your upkeep to 10, then set up town_levels and use the upkeep_modifier to multiply the town_upkeep of 10 by the number of residents.
