### ISSUE TITLE
Problem with Towny

### ISSUE THREAD

**Issue by Axuvs** [TownyAdvanced/Towny#3990]
Hello! 
I have a little problem with the Towny plugin. When I try to, for example, expand a city, or change any detail, it says that it basically doesn't exist, as seen on the attached GIF. I don't really know why this happens.
I have the following plugins in my server:
Essentials,
Ultimate Economy,
Vault,
WorldEdit,
and Towny.
I would appreciate any help! :)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/61786885/81357006-9e1ba380-90a0-11ea-925b-30f9bd1a23f3.gif)

**Comment by LlmDl** [comment]
You don't appear to be running my Towny, we dont have addDeputy/moveTownManager/expand commands.

**Comment by Axuvs** [comment]
So then, how can I know what Towny am I running? I installed this version via Minehut.

**Comment by Yldales** [comment]
Hi,

You're using Towny 0.95.2.0. 
[Ultimate Economy](https://dev.bukkit.org/projects/ultimate_economy) override Towny's `/town`. You can use `/towny:t instead`.

**Comment by Axuvs** [comment]
So, I should use /towny:t instead of /town to make any command?

**Comment by LlmDl** [comment]
Yes, you can also set up that alias to be automatic using the server commands.yml file.
