### ISSUE TITLE
Towny Spy?

### ISSUE THREAD

**Issue by Federico2806** [TownyAdvanced/Towny#3991]
Is it normal that when i use /towny spy or /resident toggle spy i dont receive any output in chat and nothing change, so i cant Spy the towny and nation chat?

-Towny version:
0.95.2.23

Paper Version:
Paper(118) 1.15.2-R0.1-SNAPSHOT

**Comment by LlmDl** [comment]
That would not be normal. Update your Towny no one should be on that version.

**Comment by Federico2806** [comment]
Ok thanks, the update fix the problem, but i have a question. Is it possible to change the format of the Spy Chat? The default one is like im in the spied town and its a little confusing. If its possible, how?

**Comment by LlmDl** [comment]
It's not, there is a ticket here: https://github.com/TownyAdvanced/Towny/issues/2665

**Comment by Federico2806** [comment]
It will be a future feature?

**Comment by LlmDl** [comment]
At some point yes. It's not a high priority at the moment.

**Comment by Federico2806** [comment]
Ok perfect, thank you
