### ISSUE TITLE
Suggestion: Add a config to prevent mayors from deleting towns when there are other members in the town.

### ISSUE THREAD

**Issue by Rishabh-Raghunath** [TownyAdvanced/Towny#3992]
A config to prevent mayors from deleting towns when there are other members in the town.
If this option is set to true it should give a message like "You may only transfer the town to another member of the Town" or similar.

**Comment by RishabhRaghunath** [comment]
Do we have any update on this feature? This would be a very useful config for large servers.
Mayors of large towns have the possibility of making players go homeless.

**Comment by LlmDl** [comment]
Technically I believe this can be achieved already. Remove or negate the permission node to delete a town from the mayors in the Townyperms.yml file. 

This will force them to /t set mayor {residentname} and then /t leave.
