### ISSUE TITLE
Question: TownyChat Conflict with NameColours??

### ISSUE THREAD

**Issue by OmegaWeaponDev** [TownyAdvanced/Towny#3994]
**Ask your question as best as you are able:**
I'm the developer of a new NameColours plugin on SpigotMC and for some reason someone has come to be with an issue that I think is more related to TownyChat than my plugin. 

For some reason when someone uses my name colour plugin and they are using TownyChat it comes up with the error: https://hastebin.com/javivawuda.bash 

No other chat plugins seem to have the issue.

**Comment by LlmDl** [comment]
I recall that, I don't think they ever solved it. I'm guessing it is just a configuration issue. Tell them to file a ticket here using this link: https://github.com/TownyAdvanced/Towny/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by OmegaWeaponDev** [comment]
Hmm okay, so you don't think It could be an issue with my plugin then. As i'm only setting the players displayname to apply the name colours.

**Comment by LlmDl** [comment]
You're not in the stack trace at all, so I doubt what you're doing would cause the NPE.

**Comment by OmegaWeaponDev** [comment]
Okay thanks, I've passed the message onto them.
