### ISSUE TITLE
Chat Issue with Name Color Plugin

### ISSUE THREAD

**Issue by RealTitanGod** [TownyAdvanced/Towny#3996]
### What steps will reproduce the problem?
1. Using OmegaNames plugin a player presses Reset
2. They type in chat and its not formatted correctly, error is placed in console.

### What is the expected output?
1. Using OmegaNames plugin a player presses Reset
2. They type in chat and their name color is back to the default.

### What is your Towny version?
0.96.1.5 (TownyChat is 0.69)

### What is your spigot/craftbukkit version?
git-Spigot-e7dc2f5-a8ec1d6 (MC: 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
[latest.log](https://github.com/TownyAdvanced/Towny/files/4605888/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) :
https://hastebin.com/evavemepih.coffeescript

3. Your townyperms.yml : 
https://hastebin.com/haxolileqa.php

4. Your log's error : 
https://hastebin.com/javivawuda.bash

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://hastebin.com/ewexigoxem.shell
7. Your channels.yml : https://hastebin.com/imuhoyezey.bash

**Comment by LlmDl** [comment]
Does putting back the global channelTag in the channels.yml fix it?

**Comment by RealTitanGod** [comment]
No

**Comment by LlmDl** [comment]
https://github.com/OmegaWeaponDev/OmegaNames/pull/2 I've got a potential fix for this on OmegaNames side. Turns out it only errors when players have no colour set yet.

**Comment by LlmDl** [comment]
This is fixed on the OmegaNames side of things. The ticket above has a .zip with the new jar if they don't release it on spigot soon.
