### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by SirAltF4** [TownyAdvanced/Towny#3997]
hiya i was wondering i would like to make it so in the chat each world has a differnt colour eg earth is green, parkour is purple and minigames are gold, how would i do this do i need to rename the worlds so they have the colour code in them or is there a setting in the config im missing 
Thank you Tom

**Comment by LlmDl** [comment]
Sorted you out in the Discord, but for posterity I'll put it here in case someone googles themselves here.

This would be done via a plugin that provides placeholderAPI placeholders and lets you set coloured worldnames.
