### ISSUE TITLE
Towny will not migrate from flatfile to SQL or load SQL database

### ISSUE THREAD

**Issue by spencer-wild** [TownyAdvanced/Towny#3998]
It all started when I followed this: https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#converting-flatfile-to-sql

### What steps will reproduce the problem?
1. In your towny configuration, set the database_load to flatfile, and the database_save to sql
2. Start your server
3. Edit your configuration again to reflect database_load as sql
4. run the command ta reload all

*I have also tried the following without a resolution:
-Creating a new database (towny2)
-Deleting the entire towny folder to see if it was something with the towns I already have 
These didn't change anything, the error is the same. I've included the log from this most recent attempt, as well as the previous one which included the use of actual user data as opposed to having deleted the folder. None of the other plugins (logblock etc) that use mysql have had issues with it so I'm thinking it's either an oversight issue on my side with the configuration of towny or a plugin error.

### What is the expected output?
1. Towny should save the flatfile into the SQL database
2. Towny should load the SQL database

### What is your Towny version?
Do not say "latest".
0.96.1.9

### What is your spigot/craftbukkit version?
Do not say "latest".
[Server thread/INFO]: This server is running Paper version git-Paper-280 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
Log 1 - Clean/Deleted Towny folder, new flatfile, attempted to migrate following instructions on the wiki link
https://pastebin.com/aDiur4VR

Log 2 - Attempted to migrate flatfile to mysql following instructions on wiki link
https://pastebin.com/AwVsmxUp

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/j4nMe094

3. Your townyperms.yml :
https://pastebin.com/CKuBsqkS

4. Your log's error : 
https://pastebin.com/embed_iframe/fqbsUU4H

**Comment by LlmDl** [comment]
The guide says to use mysql, sqlite or h2 in the config, but you've used sql. Can you try using mysql?

**Comment by spencer-wild** [comment]
Oh my god it worked perfectly. Thank you, I feel like a mess after a fair amount of frustration over this. 

All is well, it was my error.
