### ISSUE TITLE
Issues with tree feller on trees at the edge of plots

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#4001]
### What steps will reproduce the problem?
1. Make a farm plot and give residents (or some other group) perms on it.
2. Plant a tree type that grows over the edge near the edge. (tested with giant jungle)
3. Have a member of the perm group attempt to chop tree with treefeller (Mcmmo)
4. Trees that go over the edge will not tree fell properly.   They will sometimes tree fell partially (like 1/4 of a giant jungle tree will go as if it were a tree of it's own).  The resident will be able to break the parts of the tree inside the plot with normal one log at a time tree chopping. When tested with an admin or mayor account, the trees fell properly.  Trees in the middle of the plot or plot group treefell just fine.

### What is the expected output?
1. The tree should disintegrate, or the part inside the plot should, but it doesn't.  The log hit by the player is destroyed and the player is told "Residents aren't allowed to destroy here"

### What is your Towny version?
Do not say "latest".
0.96.1.10

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 273 (Minecraft 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/VuApJfEg
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/s8pPnBWw (darn it, I thought I'd gotten rid of that extra x before version...)
3. Your townyperms.yml :
https://pastebin.com/D3KhEdxA
4. Your log's error : none

**Comment by LlmDl** [comment]
So I've tested this and it is reproduce-able, but it appears that it is on the McMMO side of things.

I've found that the code stopping things is on [this line.](https://github.com/mcMMO-Dev/mcMMO/blob/899a0152badf00869048a3ebd60053ec9f9c2aa6/src/main/java/com/gmail/nossr50/skills/woodcutting/WoodcuttingManager.java#L273) They do actually have a TODO: in there saying it should probably be a continue, which would mean Towny would cancel the block-breaks that the player wouldn't be able to do manually, while letting allowed-breaks to happen. 

It would look strange and be a bit of a pain to clean up manually but it's probably better than the current behaviour.
