### ISSUE TITLE
NullPointerException in latest prerelease

### ISSUE THREAD

**Issue by Binero** [TownyAdvanced/Towny#4002]
[This line](https://github.com/TownyAdvanced/Towny/blob/47e0150bc85c39fe8b2ee09b07dd09e6153aef28/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L256) needs to check whether `block == null` first. Otherwise it can throw (and to my experience will throw) a`NullPointerException`.

https://github.com/TownyAdvanced/Towny/blob/47e0150bc85c39fe8b2ee09b07dd09e6153aef28/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L256

**Comment by LlmDl** [comment]
Looks like the [getClickedBlock() is actually nullable](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerInteractEvent.html) so you would be correct.

**Comment by LlmDl** [comment]
Fixed with https://github.com/TownyAdvanced/Towny/commit/ecc3f2cbe0a8cd580e1f0917588adf40269f93dd
