### ISSUE TITLE
Suggestion: Anti-slimeblock Griefing toggle in towns

### ISSUE THREAD

**Issue by Sickma** [TownyAdvanced/Towny#4004]
**Please explain your feature request to the best of your abilities:**
Due to the change to prevent griefers from using slimeblocks and flying machines from wrecking towns given here: https://github.com/TownyAdvanced/Towny/issues/2417
we can no longer use horizontal flying machines to harvest and make farms with because they can't cross the chunk borders in our town's farm plots. could a permission be added to allow flying machines to cross town borders into wilderness or other town plots with this perm activated?

**Comment by LlmDl** [comment]
I don't quite understand how you would give a flying machine a permission?

**Comment by Sickma** [comment]
not the flying machine so to say, more like a perm that allows a slime block to interact or modify the town chunk, like the PvP, or mob spawning rules do. my farm's current setup is i have the collection and storage set up in a few claimed plots in town but the rest of my farm is outside my towns borders. and what im coming across is i cant get my harvester to cross the chunk border because of the anti-slimeblock-griefing rule. I was wondering if there is a way to have that rule as a toggle for that town plot so i can turn it on or off?

**Comment by LlmDl** [comment]
There's no specific rule regarding slime blocks or slimefun blocks. Towny just doesn't let pistons interact with blocks in chunks that don't share the same owner as the one the piston is in. Piston machines are not entities that can be allowed to do things/are not things we can track to an owner. If we allowed pistons to do actions across plots that don't share an owner, all sorts of piston griefing would occur.

If you want to not have any issues claim the plots you're farming.
