### ISSUE TITLE
Suggestion: Nation Claim

### ISSUE THREAD

**Issue by Kingzzly** [TownyAdvanced/Towny#4005]
I think it would be a cool feature to add /n claim. Meaning that the n spawn is an independent land claim. In the n claimed area, all town members of that nation may build their own shop,farms,buildings etc.

**Comment by suneettipirneni** [comment]
Yeah maybe @LlmDl can implement something like `NationBlock`‘s

**Comment by ZenXP815** [comment]
As an extension to nation blocks can we have nation outposts?

**Comment by Kingzzly** [comment]
Nation ranks could also include helpers/builders etc. so those who have perms can build on the nation land

**Comment by LlmDl** [comment]
It is unlikely that a nation will own land at any point. The capital town of the nation can own land for it.

Nation outposts could potentially become a thing now that /plot set outpost is a thing, there could be a /plot set nationoutpost.

**Comment by Kingzzly** [comment]
How about Nation Warps, after setting up a nation outpost. Just another suggestion

**Comment by ZenArchipelago** [comment]
> It is unlikely that a nation will own land at any point. The capital town of the nation can own land for it.
> 
> Nation outposts could potentially become a thing now that /plot set outpost is a thing, there could be a /plot set nationoutpost.

Does the King of a nation have to be a mayor of the capital or the mayor of any city and set another city as capital?

**Comment by LlmDl** [comment]
The king is the mayor of the capital city @ZenArchipelago
