### ISSUE TITLE
Fireworks protection

### ISSUE THREAD

**Issue by trevor1097** [TownyAdvanced/Towny#4006]
I added `FIREWORK_ROCKET` to the `item_use_ids` and if you click on the ground the "Outsiders aren't allowed to item_use" message. But if i click the firework on the air it still works. I thought it would work the same was as an Ender Pearl but it doesn't.

Using Towny-Seige-96.1.10

**Comment by LlmDl** [comment]
I might be missing something but I cannot get a firework_rocket to launch when I click on the air.

**Comment by trevor1097** [comment]
Okay i have no idea. When i did it yesterday it wasn't blocking them but now it is.
