### ISSUE TITLE
Dynmap-Towny: java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.TownyUniverse.getTownsMap()Ljava/util/Map;

### ISSUE THREAD

**Issue by viveleroi** [TownyAdvanced/Towny#4007]
I couldn't file an issue directly on the dynmap-towny repo so I did here.

### What steps will reproduce the problem?
1. Install towny, dynmap, towny-dynmap
2. Boot server

### What is the expected output?
1. No errors

### What is your Towny version?
Towny-0.96.1.0

### What is your spigot/craftbukkit version?
Paper 1.15.2 b 293

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://hasteb.in/eduluhen.coffeescript
3. Your townyperms.yml : https://hasteb.in/qepuziwe.yaml
4. Your log's error : 
https://hasteb.in/renatexu.md

**Comment by LlmDl** [comment]
![Capture](https://user-images.githubusercontent.com/879756/82155037-bf665780-9837-11ea-99c1-d282e09c412f.PNG)
You don't meet the minimum required Towny version.

**Comment by viveleroi** [comment]
Ok well then fix your README `As of 0.75, Dynmap-Towny has the following minimum requirements: TownyAdvanced 0.95.2.10 or later`

**Comment by suneettipirneni** [comment]
Then why are you surprised it doesn’t work on your version?

**Comment by viveleroi** [comment]
How the fudge is `0.95.2.10` higher than `0.96.1.0`

**Comment by suneettipirneni** [comment]
Oh I thought the 95 was a 96 my bad, we’ll fix that.

**Comment by Redd56** [comment]
still throwing errors in console

**Comment by Redd56** [comment]
also reopen this issue its kidna closed and still happens

**Comment by LlmDl** [comment]
@Redd56 If you still have the issue and it occurs when you use 0.80 and a Towny 0.96.1.2 or newer, show us your startup latest.log file.

**Comment by Redd56** [comment]
k let me make sure everything is updated and upload it

**Comment by Redd56** [comment]
nvm i guess its cause i was using the stable verson of towny from spiggot

**Comment by Rand404** [comment]
I'm having this happen with dynmap 3.1 Beta 2,  dynmap-towny 0.81 and Towny 0.96.2.0

latest.log found here: https://pastebin.com/TBMQZR9A

**Comment by LlmDl** [comment]
@Rand404 Sorry for the late response, I have been on holiday.

You have to use dynmap-towny 0.80 on that version of Towny.
