### ISSUE TITLE
Towny-Dynamp (couldnt post it there)

### ISSUE THREAD

**Issue by jameslinimk** [TownyAdvanced/Towny#4009]
What steps will reproduce the problem?
1. Install Dynmap
2. Install Dynmap-tonwy
3. Error in console

What is the expected output?
1.  For it to work smoothly without errors
2. For it to work on Dynamp
3.

What is your Towny version?
I am on ver 0.80 (lastest)

What is your spigot/craftbukkit version?
Paper 243

Please use Pastebin.com to link the following files:

https://paste.helpch.at/ekiteyoced.bash
DIdnt think the rest were important

**Comment by LlmDl** [comment]
Duplicate: https://github.com/TownyAdvanced/Towny/issues/4007
