### ISSUE TITLE
Suggestion: Contested land

### ISSUE THREAD

**Issue by the4bestgame** [TownyAdvanced/Towny#4011]
I would love to see a feature to the effect of eliminating the first come first serve nature of claiming a fallen town.

As it is when a town falls in towny, whoever can type the command to claim it as an outpost first will instantly claim the chests associated with it Preventing others from participating in your plugin.

Please would you consider adding a wait time to claiming an outpost over land that has previously been claimed, or if two people attempt to claim an outpost at the same time. As it is right now its causing problems

**Comment by LlmDl** [comment]
@Goosius1 has yet to get Fallen Towns into Towny. This ticket can be resubmitted after Towny actually has Fallen Towns.
