### ISSUE TITLE
Suggestion: Outpost Overhaul

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#4013]
Ok let's be honest, Outposts aren't intuitive, every town block is a separate town block and the spawn in each of them is separated. Keep in mind this is all while each of the outpost town blocks is adjacent. 

Let's describe some issues with this setup:
- Way too many spawns to keep track of, and none of the spawns are named, which means they're hard to use in the console. **Edit:** They can be currently named but under this new system a *group* of them would be named rather than a single townblock.
- The question: "How do I unclaim an Outpost?", currently you have to unclaim each townblock individually. 
- Adding onto the third point efficiently managing outposts is nonexistent and there lacks any cohesiveness between adjacent townblocks.

#### How should we approach this issue

I believe our idea of outposts is fundamentally wrong right now we treat singular townblocks as outposts. We should treat outposts as "sub-towns" located off the mainland of a town.

This is extremely similar to the idea of plot groups.

- You can unclaim all with one command
- You can change perms and settings with one command for all outpost townblocks

With Outpost it adds an additional functionality:

- You can have named spawn for outposts, for easier teleports.
- Can be off the mainland

So essentially you can manipulate outposts as if it they were a town which makes managing it much more intuitive.

**Comment by Momshroom** [comment]
This seems like a nice improvement, but:

- it would be nice to be able to move the spawn town block within the outpost group without having to pay for another outpost, the same way you can move the town spawn within the town.
I'm not entirely certain how you would name the command to have it not be confused with the other outpost commands.  Maybe using the name or number of the outpost as below? /plot set outpost TrainingGrounds or /plot set outpost 2?

- You can already name outposts and use the name in a teleport.  Just name the outpost town block and use that name to tp:  /plot set name TrainingGrounds; /t outpost TrainingGrounds.  The name also shows in /t outpost list.

- It would also be lovely if resetting the spawn point of an outpost within it's town block didn't renumber your outposts. (hmm... I probably should've made a ticket for that a long time ago....

Thanks!

**Comment by LlmDl** [comment]
Named spawning is already a thing. Using /plot set name on an outpost townblock will have the outpost take that name, see in /t outpostlist and usable in /t outpost {plotname} to spawn to the location.

**Comment by suneettipirneni** [comment]
> t would be nice to be able to move the spawn town block within the outpost group without having to pay for another outpost, the same way you can move the town spawn within the town.
I'm not entirely certain how you would name the command to have it not be confused with the other outpost commands. Maybe using the name or number of the outpost as below? /plot set outpost TrainingGrounds or /plot set outpost 2?

Yup, this plays into the idea of outposts being subtowns, rather than treated as separate entities. I would plan for each outpost to have a modifiable spawn just like a town.

**Comment by DeadGlamour** [comment]
https://github.com/TownyAdvanced/Towny/issues/3065
I think that while outposts are being redone maybe this should get some notice, since rn if you have a range system to nation invite outposts have to be disabled, which isnt ideal.

**Comment by LlmDl** [comment]
Yeah that one is a fairly simple thing @DeadGlamour .
