### ISSUE TITLE
Dynmap-Towny doesn't update unless you do /dynmap reload

### ISSUE THREAD

**Issue by leogioaiden** [TownyAdvanced/Towny#4014]
### What steps will reproduce the problem?
1. Add a claim to your town
2. Look at map

### What is the expected output?
1. Updates within a reasonable amount of time on the map

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
PaperMC Build #284

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/VBgkQRWA
2. Your Towny config.yml : https://pastebin.com/bssmV5uF
3. Your townyperms.yml : https://pastebin.com/EA2YRg9C
4. Your log's error : https://pastebin.com/wf8jAKcn
5. Dynmap-Towny config (since this is to do with dynmap towny): https://pastebin.com/uXDDTLa4

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You cannot use 0.80 with 0.96.1.0. You need to update your Towny to 0.96.1.10.
