### ISSUE TITLE
Suggestion: Claim land for nations

### ISSUE THREAD

**Issue by leogioaiden** [TownyAdvanced/Towny#4015]
**Please explain your feature request to the best of your abilities:**
Sometimes, we don't want or have to have another town to claim land in your nation. This is also true in real life, where a nation has claimed land that no town has been settled on. This should be true for towny as well. What I'm saying is that we should be able to claim land directly as a nation and then later, when we decide, towns can be able to be created on that land.

**Comment by ZenXP815** [comment]
So basically NationBlocks or Nation Outposts?

Also with these NationBlocks/NationOutposts should have plot perms. And the nation zone should be applicable to them if enabled in the config.

**Comment by leogioaiden** [comment]
Yes, bascially nation blocks. I don't like that I have to have a town in everywhere to recreate a nation in a 1:1000 earth map. I should be able to claim the nation with nationblocks and put a town wherever i want.

**Comment by LlmDl** [comment]
See my comment on another recent ticket: 
https://github.com/TownyAdvanced/Towny/issues/4005#issuecomment-629213085

It is unlikely that any land will be claimable except by a town. With your large earth map you can still claim spaces for your nation by claiming it as the capital, until someone else wants it.
