### ISSUE TITLE
Suggestion: Stricter Settings for Inactive Towns

### ISSUE THREAD

**Issue by Dobbi124** [TownyAdvanced/Towny#4016]
## I suggest that there should be a way to invade towns more easily with the sieging method, for example.

> Town #1: Billy makes his town and makes his own nation.
Town #1: Billy is active for a few days, then leaves the server and doesn't return for two weeks.
Town #1: Before he left, Billy had an upkeep of only $250 and with $10,000 in the bank.
Town #2: James is part of a nation and he finds Town #1 and wants to siege it.
Town #2: James successfully starts a siege on Town #1 and without any resistance for three days, his wins the war.
Town #2: James has stood by the banner of the town before the siege ended and took $50 and after the siege plundered the town of $750.
Town #2: James cannot interact with the town due to permissions set by Billy before he left, and now the only way he can steal his stuff is if he waits until the town falls into ruins.
Town #2: Doing the math, James will have to wait approximately 37 days for it to fall into ruins. If he didn't stand by the banner, it would've taken exactly 37 days. If he didn't stand by the banner or plunder the town, it would've taken 40 days for it to fall into ruins. 

#### I've seen on two very popular servers of this being a problem. In my personal experience, a town not touched in months was raided by my nation and they crammed all of their stuff into one chunk and having a high amount in the bank. Doing the math, we would've had to wait almost 55 days, almost two months for it to fall into ruins!

I have a few suggestions for fixing this, 

#### 2. Even though this might sound crazy, a possible second siege by the nation currently occupying the town (after the immunity timer expires for another siege), but this siege is not really a siege of the town, but I like to call it a Power Siege, a siege for power to control the town. The leader of the nation will have permission along with the previous mayor to change anything he wants about the town (besides kicking out members or deleting the town). If the town defends that even once, the defenders win, but if not, the power belongs to the invader.

Using method two, the wait time for towns with more money in the bank would be calculated as for example...
>> Initial Town Siege Time: 3 days
Siege Immunity: 8 Days
Power Siege Time: 3 Days

Giving us a total of 14 days, exactly two weeks in this instance.
If no one in your town has shown signs of resistance for two weeks, then its safe to say they left.

#### **NOTE:** A power siege cannot happen if the town being invaded shows any sign of resistance, including standing near the banner for any duration of time, or killing attacking members. Any signs of resistance coming from the defenders should not allow a Power Siege to take place.

The following things could cancel out a power siege.

- If the capital of the nation is being attacked
- If there are no members of the town left (only NPCs are left)
- If the town attempts to rebel against its occupier
- If the town is deleted by the original mayor

I love the plugin and I hope these ideas can be used or edited so that the experience becomes more fun and less dull for all servers, or if all else, another solution is thought of to prevent towns from being raided for long lengths of time. I'm also willing to take suggestions for fixing this up to work better with the plugin, thank you! 😄

**Comment by LlmDl** [comment]
Siege war is not a part of Towny yet. We are waiting on @Goosius1 to get it into place in stages.

**Comment by Goosius1** [comment]
Hi.

- Pillage and plunder are designed only to be 'Annoyances' which play a part in war and 
   negotiations, and steal a maximum of about 15-30% of the town bank.
- It sounds like the problem you are describing is that of inactive players.
- I suggest this be dealt with directly by using the existing feature of deleting inactive residents.
  (after 10,20,30,40 days, whichever is preferred)
- If there is going to be a 'power siege' feature, it won't be before official Towny release, 
   as I am focusing on preparing the code for that now (and fixing critical issues etc.)

**Comment by Dobbi124** [comment]
Alright, I’m glad to hear that you’re still working on it. I hope everyone goes well and if you need me to clarify anything here in the future, I’d be more than willing to help, thank you and good luck!

**Comment by LlmDl** [comment]
This issue is going to be closed for now. As goosius has said above, Towny already deals with players who are inactive for too long.
