### ISSUE TITLE
Suggestion: Finding forsale plots in all towns.

### ISSUE THREAD

**Issue by mzyax** [TownyAdvanced/Towny#4020]
**Please explain your feature request to the best of your abilities:**

I have a suggestion for `/town plots {town}`

`/t plots` should list forsale plots in all towns. This eases the process for a new player finding a plot, specially when mayors aren't on.

**Comment by suneettipirneni** [comment]
How should they be listed so it’s easy to find, we can list coordinates but that’s not really inherently clear

**Comment by mhiaxo** [comment]
> 
> 
> How should they be listed so it’s easy to find, we can list coordinates but that’s not really inherently clear

hmm true! list coords maybe with the ability to click to teleport like /t list?

**Comment by suneettipirneni** [comment]
That could work

**Comment by LlmDl** [comment]
players can also use /towny map big and see all the for sale plots visually.

**Comment by suneettipirneni** [comment]
> players can also use /towny map big and see all the for sale plots visually.

That map is the opposite of intuitive

**Comment by LlmDl** [comment]
A list of coordinates is not helpful like a visual map of your surroundings, which includes the direction you're facing.

**Comment by suneettipirneni** [comment]
> A list of coordinates is not helpful like a visual map of your surroundings, which includes the direction you're facing.

That’s why we want to make them clickable aka the previous comments.

**Comment by LlmDl** [comment]
Making the /towny map townblocks clickable is an interesting idea, however it would probably have to have limits placed on it when war or pvp is active.

**Comment by mhiaxo** [comment]
I tried to use the map. It's confusing. I can't "rely" on this for a new player (who's going to be quite young, probably) to use this. Maybe if the for sales $ was clickable and all I have to say is "Hey, do /towny map and click on the +" but in the current state, it's just not helpful at all.
