### ISSUE TITLE
Suggestion: Permission node to act asmayor in Town owned plots only (not player-owned.)

### ISSUE THREAD

**Issue by eUipKh** [TownyAdvanced/Towny#4022]
**Please explain your feature request to the best of your abilities:**

Allow ranks with the permission `towny.claimed.townowned.*` to change **town owned** plots perms and put them for sale / not for sale.

I may be wrong but Currently the only two ways to do that is with the permission `towny.command.plot.asmayor` or creating a rank called "assistant" but this would give the rank the permission to modify **player owned** plots.

Thanks.

**Comment by LlmDl** [comment]
towny.claimed.townowned.* should not be allowing players to put plots up for sale/not for sale.

the towny.command.plot.asmayor is the node which:
 - allows setting plots up for sale,
 - allows players to re-claim plots from residents for sale, 
 - allows players to set plots to other plot types when they don't own the plot personally,
 - when combined with the /plot evict node, they are allowed to evict players.
 - it is also used to determine whether /plot set perm and /plot toggle can be used, on plots they don't personally own.

What you want is for a node that would allow only the /plot fs and /plot nfs commands to be used?

**Comment by eUipKh** [comment]
What we want is to have this permissions to work only with town owned plots and not with player owned plots:
* allows setting plots up for sale/not for sale
* command /plot set perm

**Comment by eUipKh** [comment]
Hello, is there any updates related to this?

**Comment by LlmDl** [comment]
No update on this one yet.

**Comment by LlmDl** [comment]
This is now a thing as of 0.98.1.5.
