### ISSUE TITLE
Townblocks.txt Deleting all data

### ISSUE THREAD

**Issue by AlteriaMC** [TownyAdvanced/Towny#4023]
### What steps will reproduce the problem?
1. Restart backup of Data folder via old backup
2. Update to 0.96.1.0 from 0.94.0.0 and delete config.yml to be updated by new Towny jar
3. Receive "(Towns) homeBlock tried to load invalid TownBlock." message.

### What is the expected output?
1. Start up server and maintian any towns' claimed blocks

### What is your Towny version?
Do not say "latest".
0.94.0.0 and after upgrade to 0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.4-R0.1-SNAPSHOT Spigot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/gGCs75mZ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/hJkmURY5
3. Your townyperms.yml :https://pastebin.com/7EaDfFgC
4. Your log's error : [WARNING] [Towny] Error: [Warning] Miaria homeBlock tried to load invalid TownBlock.

[WARNING] [Towny] Error: [Warning] Alteria homeBlock tried to load invalid TownBlock.

[WARNING] [Towny] Error: [Warning] Venatora homeBlock tried to load invalid TownBlock.

Townblocks.txt is 497mb from backup, is reduced to 0 upon startup of either version of Towny

**Comment by LlmDl** [comment]
From the looks of it, your Gringott's is too new for your version of Towny. 

They made some changes for us to reflect changes we made with town and nation bank accounts sometime after 0.96.1.0.

If you update your Towny to 0.96.1.10 you will find that Towny no longer uses the townblocks.txt file, instead loading all townblocks in the towny\data\townblocks\ folder. You will want to start with a backup first, from before you had this trouble.

**Comment by AlteriaMC** [comment]
I've done a complete wipe/reset of the main server and restored from the backup server (where everything works and displays correctly). Upon loading into the server, all town blocks are still unclaimed (towny 0.94.0.0 still at this point), but now claiming plots works again for the town's. So far, just re-claiming the previous plots has worked, but this is a pain due to 2 NPC mayor towns for the server. I'll continue like this then upgrade to 0.96.1.0 after all plots are reclaimed. Thanks for noticing the problem with gringotts!

**Comment by LlmDl** [comment]
Did you use a different name for your world, which has now changed to another name?

**Comment by LlmDl** [comment]
Need some feedback on this, or the ticket will be closed.

**Comment by AlteriaMC** [comment]
Sorry just saw the email notification for this. The world did not change.
Town blocks were nonexistent for both my server and personal town (only two
at the time) and I was able to claim the original chucks back and "rebuild"
the town.

**Comment by LlmDl** [comment]
Odd, but alright.
