### ISSUE TITLE
EmojiChat breaks with a "hooked: true" TownyChat channel

### ISSUE THREAD

**Issue by VoxPopuliZombiemold** [TownyAdvanced/Towny#4024]
### What steps will reproduce the problem?
1. Download this extremely minimal test server with pre-setup configs: https://www.dropbox.com/s/nck4zlr65wdqmsw/1.15_Test_Server_%28DeluxeChat%2CTownyChat%2CEmojiChat%29.zip?dl=0
2. Run it, Op yourself
3. Try to use an emoji code :+1:

### What is the expected output?
1. The :+1: code should be replaced with a thumbs-up emoji, or a foreign character without the emojichat resource pack

### What is your Towny version?
0.96.1.10

### What is your spigot/craftbukkit version?
Paper-304 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[latest.zip](https://github.com/TownyAdvanced/Towny/files/4672515/latest.zip)

2. Your Towny config.yml (if using MySQL please remove password,) : 
[config.zip](https://github.com/TownyAdvanced/Towny/files/4672519/config.zip)

3. Your townyperms.yml : 
[townyperms.zip](https://github.com/TownyAdvanced/Towny/files/4672520/townyperms.zip)

4. Your log's error :  None

(optional) If this is to do with permissions, 
5. Your permissions file : Not related

No Errors, TownyChat just strips the special characters out of chat:

https://images2.imgbox.com/91/d7/XWWyXiMC_o.png

(optional) If this is to do with permissions, 
5. Your permissions file: Not related
(optional) If this is to do with chat,
6. Your chatconfig.yml: [ChatConfig.zip](https://github.com/TownyAdvanced/Towny/files/4672523/ChatConfig.zip)
7. Your channels.yml : [Channels.zip](https://github.com/TownyAdvanced/Towny/files/4672522/Channels.zip)

**Comment by VoxPopuliZombiemold** [comment]
I have taken this issue to the DeluxeChat and EmojiChat developers to root out the issue, and the consensus is that the issue likely lies with TownyChat.

**Comment by LlmDl** [comment]
You skipped the form. Please fill it out in full.

**Comment by VoxPopuliZombiemold** [comment]
I included all the requested files, please review. It's worth noting that, aside from the hooked chat setting, this bug is replicable with stock configs.

**Comment by LlmDl** [comment]
This may be related to something I was already planning on looking into. TownyChat does placeholders fine, but when used in conjunction with deluxechat, it stops. Your image shows the same behaviour.

**Comment by LlmDl** [comment]
I've tried to reach out to @extendedclip about this, as I believe it is on the DC end. So far no response.
