### ISSUE TITLE
Dynmap-Towny Continuous exception in console

### ISSUE THREAD

**Issue by darkcloud784** [TownyAdvanced/Towny#4025]
### What steps will reproduce the problem?
1. Install Towny Advanced, Dynmap, and Dynmap-Towny
2. Configure all of the above
3. Start the server

### What is the expected output?
1. Server starting
2. Load plugins
3. See Towny info on Dynmap

### What is your Towny version?
Dynmap-Towny - 0.80 for Towny 0.96.1.2+
Towny - 0.96.1.10 for 1.14.*/1.15.*
Dynmap - Version 3.0-RC2-318 is enabled - core version 3.0-RC2-318

### What is your spigot/craftbukkit version?
I'm using Papermc Paper-307 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
https://pastebin.com/fx2u4SJb

## Note ##

I am putting this bug report here because there is no issue tracker enabled on the dynmap-towny github, as you can see by going to https://github.com/TownyAdvanced/Dynmap-Towny/issues and it redirecting to only pull requests.

**Comment by LlmDl** [comment]
Skipped the form. Resubmit.
