### ISSUE TITLE
Leads do not seem to be protected by towny

### ISSUE THREAD

**Issue by CottonBawl** [TownyAdvanced/Towny#4028]
### What steps will reproduce the problem?
1. Any outsider will be able to steal animals by breaking leads off of fence posts
2.
3.

### What is the expected output?
1. Leads should be protected from outsiders
2.
3.

### What is your Towny version?
Towny-0.96.1.10

### What is your spigot/craftbukkit version?
1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 
NO LOG ERROR

(optional) If this is to do with permissions, 
5. Your permissions file :
NOT A PERMISSION ERROR

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Add ,LEAD to your protection.switch_ids list in the config.
