### ISSUE TITLE
Towny locks itself into Safe Mode for unknown reasons

### ISSUE THREAD

**Issue by qualityrice** [TownyAdvanced/Towny#4030]
### What steps will reproduce the problem?
Completely unknown. A server was opened to ~10 beta testers and after ~10 towns were created and after a random server restart, Towny put itself into safe mode. No Towny configs were modified prior to the restart, the problem seemed to arise out of thin air. The problem is not limited to a certain host/OS since it also occurs on local servers.

A possible cause for the error is that there seems to be 2 threads attempting to write to a file.

### What is the expected output?
N/A. No output is expected.

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-226 (MC:1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/Nq43SVsd
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/fxXWZHYU
3. Your townyperms.yml : https://pastebin.com/Cp6LUkNu
4. Your log's error : https://pastebin.com/ELd13bJq

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Can you show me what is in the Stj?rna_?ngar.txt file?

**Comment by qualityrice** [comment]
> 
> 
> Can you show me what is in the Stj?rna_?ngar.txt file?

Here is the Stj_rna__ngar.txt: https://pastebin.com/TZEdz0RE
Please note that this is not the only problematic town, deleting this town does not resolve the issue, however, deleting all data does.

**Comment by LlmDl** [comment]
What if you run the server locally, with only Towny/Vault/Your economy plugin? Safe mode still?

**Comment by qualityrice** [comment]
> 
> 
> What if you run the server locally, with only Towny/Vault/Your economy plugin? Safe mode still?

Yeah, still safe mode and same error.

**Comment by LlmDl** [comment]
Can you get me your backup from your towny\backup\ folder?

**Comment by qualityrice** [comment]
> 
> 
> Can you get me your backup from your towny\backup\ folder?

Here is a backup from right before the problem started: https://send.firefox.com/download/11b2efbe5877df7d/#2OuHUvVGtH0JEIgFen6Atw

However, restoring the old backup doesn't even resolve the issue even though it used to work fine. It's really strange.

**Comment by suneettipirneni** [comment]
@qualityrice you mentioned that there’s two threads writing to a file, what makes you’d suspect that?

**Comment by LlmDl** [comment]
@suneettipirneni this is what his host told him

@qualityrice I was able to fix the data and get it to load by replacing the ? with the actual characters for the townnames seen in the towns.txt file.

Maybe your host is using an encoding on the OS-level that prevents you from saving files with unicode characters.

**Comment by qualityrice** [comment]
> 
> 
> 
> Maybe your host is using an encoding on the OS-level that prevents you from saving files with unicode characters.

Could be. I'll write to my host and ask them to fix this if they can. If not, I'll simply make a plugin that prevents the use of special characters in Towny. Thank you for your help.

**Comment by LlmDl** [comment]
You can also just modify the regex settings in the config to not allow those characters.

**Comment by LlmDl** [comment]
This was determined to be caused by the Host limiting the characters which could be used at the OS level.
