### ISSUE TITLE
Leads and Sweet Berries not protected properly by Towny

### ISSUE THREAD

**Issue by CottonBawl** [TownyAdvanced/Towny#4032]
### What steps will reproduce the problem?
1. Berries can’t be broken (which is fine) however they can be right-clicked and harvested
2. Leads can be broken off of fence posts. 
3.

### What is the expected output?
1. Berries should not be harvestable
2. Leads should not be breakable in a town claim
3.

### What is your Towny version?
Do not say "latest".
0.96.1.10

### What is your spigot/craftbukkit version?
Do not say "latest".
1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
The leads part I've already fixed.

**Comment by CottonBawl** [comment]
Hmph. I was able to replicate it but I will double check myself

**Comment by LlmDl** [comment]
It probably will require 0.96.1.11 for the leads to work, alongside adding lead to the switch_ids.

To protect the berries just add SWEET_BERRY_BUSH to the switch_ids.

**Comment by CottonBawl** [comment]
Thank you
