### ISSUE TITLE
[Suggestion] Towny shematics & NPC´s

### ISSUE THREAD

**Issue by TheRobLP** [TownyAdvanced/Towny#4035]
Basically, I had the idea that there could be schematics that can be purchased with Gold & ressources, for example a "Farm" schematic. After building this schematic it cannot be destroyed by breaking, only by interacting with a special terminal that is inside of the building. This terminal also has a bunch of other features. For example you can hire a farmer in a farm building, who automatically plants and harvests crops. There would be a vast variety of buildings, which can also be upgraded with ressources & money. For example Barracks, where you can train guards to defend your land against monsters, or a Mining facility, where you get Miners to mine ores. But the heart of it all will be the town hall, which becomes bigger and bigger, as you upgrade it. It will also be required to upgrade it for town upgrades (for example expand town size). While there will be schematics for the buildings, players can optionally choose to build their own buildings and convert them into Towny buildings by selecting a radius (ressource and money cost still apply and it has to have a certain amount of blocks). I know this is a big one, but I hope that it gets put into consideration. Thank you so much in advance, for reading.

**Comment by LlmDl** [comment]
Sounds like the mod Minecolonies.

**Comment by LlmDl** [comment]
We won't be re-inventing the MineColonies and Structurize mods inside of Towny. They already have a very active dev team doing far more for their type of mod than the Towny team could ever try to recreate.
