### ISSUE TITLE
Question: Towny Switch Perm (Probably User Error)

### ISSUE THREAD

**Issue by Nibrock** [TownyAdvanced/Towny#4037]
Trying to set up a single town server, in which players can purchase plots and build on them without being able to build or destroy on public property. I have some test plots set out getting familiar with the plugin, and everything works perfectly except for the switch permission from what I can tell. Players cannot break or build in public areas, or areas they don't own, but they can in plots they have purchased. They can't open doors or use chests in the plot that they own though. Tried setting the perms for the specific plot to on for just the switch perm, no luck, and then all perms, also no luck. I'm definitely not super familiar with Towny but after scouring the towny commands and github links I have yet to find a solution. Any help is greatly appreciated.

**Comment by LlmDl** [comment]
Towny will not block anything from a plot owner, so you likely have another plugin interfering.

**Comment by Nibrock** [comment]
Plugins (24): Admin-GUI, ChatFeelings, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, GSit, GUIShop, Holograms, HologramsPlaceholders*, LuckPerms, PlaceholderAPI, ProtocolLib, SignShop, SignShopGuardian, SkinsRestorer, TheNewEconomy, TimeIsMoney*, Towny, TownyChat, TownyNameUpdater, Vault, WorldEdit, WorldGuard

The only ones I can think of that would interfere are LuckPerms, Essentials, or WorldGuard. Didn't use worldguard or essentials to claim land or do anything inside the designated town area. LuckPerms may be the issue, as I didn't add any special permission nodes into any group.

**Comment by LlmDl** [comment]
It could be a world-guard global region.

**Comment by Nibrock** [comment]
It sure was, must've switched them on accident. Thanks man. Sorry for the trouble.
