### ISSUE TITLE
Any town member may list plots for sale

### ISSUE THREAD

**Issue by AlphaDelta23** [TownyAdvanced/Towny#4041]
### What steps will reproduce the problem?
1. Belong to a town and not be town staff
2. Go in to a town plot
3. use /plot fs

### What is the expected output?
1. Denial
2.
3.

### What is your Towny version?
0.96.1.11

### What is your spigot/craftbukkit version?
MC 1.15.2
PaperMC 327

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/pyNNkMjM
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/sEPTcU5u
3. Your townyperms.yml : https://pastebin.com/g6pk7HNN
4. Your log's error : N/A

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
More than likely, you have given towny permission nodes in your permission plugin. What Towny nodes did you give players in your luckperms ?

**Comment by AlphaDelta23** [comment]
towny.command.nation.*
towny.command.plot.*
towny.command.resident.*
towny.command.town.*
towny.nation.spawn.*
towny.town.*
towny.wild.*
towny.chat.general
towny.chat.local
towny.chat.town
towny.chat.nation

**Comment by Momshroom** [comment]
That would be why.  If you give your players those towny perms in your permissions plugin, they’ll be able to do things in other people’s towns.   Use townyperms.yml for those and remove them from your perms plugin. Only the towny.wilds.* and the chat perms make sense there.
