### ISSUE TITLE
Cant use command /town 

### ISSUE THREAD

**Issue by PieNguyenn** [TownyAdvanced/Towny#4043]
I cant use /town command, but i can use towny:town command
Spigot 1.14.4
Towny version is Towny-0.96.1.11
1. My log: https://pastebin.com/naQZPRbh
2. Towny configuration: https://pastebin.com/d349VXcb

**Comment by PieNguyenn** [comment]
When i put sunlight in, the plugin isnt work at all

**Comment by LlmDl** [comment]
Remove sunlight then. It probably has a conflicting command.
