### ISSUE TITLE
Question: How to disable color and formatting codes in town names?

### ISSUE THREAD

**Issue by MrNaspo** [TownyAdvanced/Towny#4044]
**Ask your question as best as you are able:**

Hey, I made an issue about this previously, but it didn't end up fixing it. How can I diable color and formatting codes in town names?

**Comment by Blandix** [comment]
I have the exactly same question, it's awful because in /t list you see for example "&a&lTown_Name

**Comment by MrNaspo** [comment]
Yeah, its even worse when people use &k.

**Comment by LlmDl** [comment]
Show me your config's regex section.

**Comment by MrNaspo** [comment]
https://ibb.co/X5HHDzy

Picture^

**Comment by MrNaspo** [comment]
And yes I've tried removing \& from string_check_regex

**Comment by MrNaspo** [comment]
I removed the backslash too, not sure why it didn't appear in the previous comment.

**Comment by LlmDl** [comment]
if you set the name_remove_regex to `[^\P{M}\p{M}*+a-zA-Z0-9._\[\]-]` I think that will work?

**Comment by Blandix** [comment]
> if you set the name_remove_regex to `[^\P{M}\p{M}*+a-zA-Z0-9._\[\]-]` I think that will work?
> edit: I see that that is what you're using. This will not change already named towns, but should prevent towns from using & in their names in the future.

One user tried it, and it' doesnt work for me :c

![image](https://user-images.githubusercontent.com/43183267/83361393-fe7bc900-a35e-11ea-9cca-93f56dc8768e.png)

**Comment by Blandix** [comment]
I'll try restarting the server, just in case that the reload isn't enough

**Comment by docwhomc** [comment]
> if you set the name_remove_regex to `[^\P{M}\p{M}*+a-zA-Z0-9._\[\]-]` I think that will work?

I don't think that regex matches anything... the `^` after the opening bracket negates the matching, `\p{M}` matches all mark characters, and `\P{M}` matches all non-mark characters.  So `[\P{M}\p{m}]` matches any character and `[^\P{M}\p{m}]` matches nothing (note that the `*+a-zA-Z0-9._\[\]-` is redundant).
A very conservative option would be to use `[^A-Za-z0-9_]`, which would match any character that isn't a letter (A through Z, without accents, in upper or lower case), a decimal digit, or an underscore.

**Comment by MrNaspo** [comment]
Why is this becoming so complicated? Why isn't there a solid answer for this? @LlmDl can you make an update for the plugin, that fixes this issue with a simple true or false in the config?

**Comment by docwhomc** [comment]
I'm guessing that `\P{M}\p{m}*` was meant to allow graphemes consisting of a non-mark followed by any number of mark characters.  However, a bracket matches a character.  Inside brackets, the meaning of `*` is changed from 0 or more instances of whatever proceeded it to a literal `*` character.
Also, `.` matches every character except `\n` (newline), which probably isn't what you intended.  Assuming you meant to allow a literal period in a town name, you'd want to use `\.` in the regex instead of `.`.

**Comment by LlmDl** [comment]
> > if you set the name_remove_regex to `[^\P{M}\p{M}*+a-zA-Z0-9._\[\]-]` I think that will work?
> 
> I don't think that regex matches anything... the `^` after the opening bracket negates the matching, `\p{M}` matches all mark characters, and `\P{M}` matches all non-mark characters.  So `[\P{M}\p{m}]` matches any character and `[^\P{M}\p{m}]` matches nothing (note that the `*+a-zA-Z0-9._\[\]-` is redundant).
> A very conservative option would be to use `[^A-Za-z0-9_]`, which would match any character that isn't a letter (A through Z, without accents, in upper or lower case), a decimal digit, or an underscore.

This is probably why it isn't doing its job.

@MrNaspo another config option shouldn't be necessary because that regex is supposed to be doing the job. You keep filing question tickets instead of bug reports.

**Comment by MrNaspo** [comment]
Oh okay, well I didn’t know this was a bug. I just thought there would be a way to. Can you move this thread to a bug report or something?

**Comment by Blandix** [comment]
> > if you set the name_remove_regex to `[^\P{M}\p{M}*+a-zA-Z0-9._\[\]-]` I think that will work?
> 
> I don't think that regex matches anything... the `^` after the opening bracket negates the matching, `\p{M}` matches all mark characters, and `\P{M}` matches all non-mark characters. So `[\P{M}\p{m}]` matches any character and `[^\P{M}\p{m}]` matches nothing (note that the `*+a-zA-Z0-9._\[\]-` is redundant).
> A very conservative option would be to use `[^A-Za-z0-9_]`, which would match any character that isn't a letter (A through Z, without accents, in upper or lower case), a decimal digit, or an underscore.

I've tried this and i almost broke mi sv.

Im a bit stupid, and i'm not a native english speaker, so it's harder to me to understand the technical terms in another language, so, what happens? Is there any temporary solution? Or we need to wait for it?

Thanks

**Comment by docwhomc** [comment]
Sorry, you're saying that `[^A-Za-z0-9_]` didn't work either?  If so, there could also be an issue in the underlying code.

**Comment by LlmDl** [comment]
Someone could file a new bug report and not skip out on the form.
