### ISSUE TITLE
Towny Top Land Error

### ISSUE THREAD

**Issue by Tolmikarc** [TownyAdvanced/Towny#4045]
### What steps will reproduce the problem?
1. Type /towny top land (all/resident/town)

### What is the expected output?
1. A list of the top land owners for towns and residents will appear in chat.

### What is your Towny version?
0.96.1.10

### What is your spigot/craftbukkit version?
Paper version git-Paper-143 MC: 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/iTM85ygy and https://pastebin.com/Wttk5Yqx (its a long log)
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/nzusfdTB
3. Your townyperms.yml : https://pastebin.com/ywJZKnuQ
4. Your log's error : https://pastebin.com/h015dKX4

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
What appears instead?

**Comment by Tolmikarc** [comment]
When players type the command it says an internal error has occurred.
