### ISSUE TITLE
Question: How to rename Wilderness?

### ISSUE THREAD

**Issue by ZakFrosty** [TownyAdvanced/Towny#4046]
I'm having problems changing the **Wilderness** (When you get out of a town, into the wilderness) notification to my language, I've been trying with my _config.yml_, the default _english.yml_ and a custom _language.yml_ but I can't seem to rename the Wilderness designation. **Is there a way to do this?**

**Comment by LlmDl** [comment]
Towny\data\worlds\worldname.txt files contain the individual worlds' wilderness names.
