### ISSUE TITLE
Question:towny issues

### ISSUE THREAD

**Issue by matthewblack044** [TownyAdvanced/Towny#4047]
I'm having issues with a few problems with towny.
-the host I use marks Version: 0.95.2.22 as the latest version, should I use this instead of the actual latest version im using (0.96.1.0)
-changing the costs of towns, claiming and nations in the config does nothing in the game, it keeps using default prices 
-most config changes don't seem to work, however all the other config files but the main one seem to work. (chatconfig, channelconfig, townypermissions all work, however config.yml doesn't)
-can't create a nation, after using /n create it says create is not a command.
-i'm trying to create a comayor and coking rank, similar to mayor and king since assistant doesnt have all permissions, however creating these (almost copies of the king and mayor rank) seems to mess up the files.

If anyone could help me with these issues I'd be eternally grateful!

**Comment by LlmDl** [comment]
These are probably all issues with your host, and your host's config file editing GUI (assuming you're not using an FTP client to actually download/upload your config files.)

**Comment by matthewblack044** [comment]
Hey, thanks for the response,

I am using filezilla to upload it to the server, do I not have to install towny on the host and the ftp client, or can I just install it in the ftp client alone and not touch the host plugin?

**Comment by LlmDl** [comment]
If the host's interface is not working well, I suggest uploading via FTP for any config change/jar update.

**Comment by matthewblack044** [comment]
I uploaded it on both the ftp and the host interface, is that a problem? Should I ignore the host interface and do everything via ftp? Sorry for the questions, fairly new at this.

**Comment by LlmDl** [comment]
I'd say use FTP  all the time.

**Comment by matthewblack044** [comment]
Alright, I'll go and leave the host interface alone then and see if that fixes it, thanks a lot for the help and the swift replies!
