### ISSUE TITLE
make a fill command 

### ISSUE THREAD

**Issue by alsilisk** [TownyAdvanced/Towny#4051]
allow you to fill large areas with townblocks not using the circle or rectangle feature but a worldedit pos1 and pos2 style 

thanks again

alsilisk

**Comment by suneettipirneni** [comment]
There are a couple of issues with this:
1) Most servers usually don't allow regular players to have worldedit perms.
2) Towny defines townblocks based on chunks, which means that a worldedit selection likely won't align with townblocks.

**Comment by LlmDl** [comment]
We don't use a wand. The best I can offer you is if you make a donut of claims you can get the centre filled in. Not a high priority atm also.
