### ISSUE TITLE
Some reason my commands wont work

### ISSUE THREAD

**Issue by kittielovemaster** [TownyAdvanced/Towny#4054]
### What is your spigot/craftbukkit version? Magma 1.12.2

02.06 18:32:34 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:423) [CraftEventFactory.class:3d116a0]
02.06 18:32:34 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:416) [CraftEventFactory.class:3d116a0]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1343) [vp.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.monster.EntityCreeper.func_70645_a(EntityCreeper.java:208) [acs.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1153) [vp.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) [ade.class:?]
02.06 18:32:34 [Server] INFO at noppes.npcs.entity.EntityNPCInterface.func_70652_k(EntityNPCInterface.java:334) [EntityNPCInterface.class:?]
02.06 18:32:34 [Server] INFO at noppes.npcs.ai.EntityAIAttackTarget.func_75246_d(EntityAIAttackTarget.java:114) [EntityAIAttackTarget.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:810) [vq.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2697) [vp.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:612) [vq.class:?]
02.06 18:32:34 [Server] INFO at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:425) [EntityNPCInterface.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2515) [vp.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:321) [vq.class:?]
02.06 18:32:34 [Server] INFO at noppes.npcs.entity.EntityNPCInterface.func_70071_h_(EntityNPCInterface.java:297) [EntityNPCInterface.class:?]
02.06 18:32:34 [Server] INFO at noppes.npcs.entity.EntityCustomNpc.func_70071_h_(EntityCustomNpc.java:50) [EntityCustomNpc.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:2337) [amu.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2291) [amu.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.world.World.func_72939_s(World.java:2075) [amu.class:?]
02.06 18:32:34 [Server] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:845) [oo.class:?]
02.06 18:32:54 [Multicraft] Skipped 10 lines due to rate limit (30/s)
02.06 18:32:54 [Server] ERROR Could not pass event EntityDeathEvent to MoneyFromMobs v1.3
02.06 18:32:54 [Server] INFO org.bukkit.event.EventException: null
02.06 18:32:54 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:3d116a0]
02.06 18:32:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:3d116a0]
02.06 18:32:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:3d116a0]
02.06 18:32:54 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:423) [CraftEventFactory.class:3d116a0]
02.06 18:32:54 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:416) [CraftEventFactory.class:3d116a0]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1343) [vp.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.monster.EntityZombie.func_70645_a(EntityZombie.java:581) [adt.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1153) [vp.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) [ade.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:245) [adt.class:?]
02.06 18:32:54 [Server] INFO at noppes.npcs.entity.EntityNPCInterface.func_70652_k(EntityNPCInterface.java:334) [EntityNPCInterface.class:?]
02.06 18:32:54 [Server] INFO at noppes.npcs.ai.EntityAIAttackTarget.func_75246_d(EntityAIAttackTarget.java:114) [EntityAIAttackTarget.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:810) [vq.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2697) [vp.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:612) [vq.class:?]
02.06 18:32:54 [Server] INFO at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:425) [EntityNPCInterface.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2515) [vp.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:321) [vq.class:?]
02.06 18:32:54 [Server] INFO at noppes.npcs.entity.EntityNPCInterface.func_70071_h_(EntityNPCInterface.java:297) [EntityNPCInterface.class:?]
02.06 18:32:54 [Server] INFO at noppes.npcs.entity.EntityCustomNpc.func_70071_h_(EntityCustomNpc.java:50) [EntityCustomNpc.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:2337) [amu.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2291) [amu.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.world.World.func_72939_s(World.java:2075) [amu.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:845) [oo.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:985) [MinecraftServer.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
02.06 18:32:54 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) [MinecraftServer.class:?]
02.06 18:33:06 [Multicraft] Skipped 7 lines due to rate limit (30/s)
02.06 18:33:06 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:33:06 [Server] INFO CONSOLE issued server command: /list
02.06 18:33:06 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:33:06 [Server] INFO default: kittielove
02.06 18:33:39 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:33:39 [Server] INFO CONSOLE issued server command: /list
02.06 18:33:39 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:33:39 [Server] INFO default: kittielove
02.06 18:34:12 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:34:12 [Server] INFO CONSOLE issued server command: /list
02.06 18:34:12 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:34:12 [Server] INFO default: kittielove
02.06 18:34:46 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:34:46 [Server] INFO CONSOLE issued server command: /list
02.06 18:34:46 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:34:46 [Server] INFO default: kittielove
02.06 18:35:19 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:35:19 [Server] INFO CONSOLE issued server command: /list
02.06 18:35:19 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:35:19 [Server] INFO default: kittielove
02.06 18:35:52 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:35:52 [Server] INFO CONSOLE issued server command: /list
02.06 18:35:52 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:35:52 [Server] INFO default: kittielove
02.06 18:35:53 [Multicraft] Auto-saving world...
02.06 18:35:53 [Server] INFO Saving is already turned on
02.06 18:35:53 [Server] INFO Saving...
02.06 18:35:53 [Server] INFO [Server] World saved.
02.06 18:35:56 [Server] INFO kittielove issued server command: /help
02.06 18:35:56 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:36:07 [Server] INFO kittielove issued server command: /help townychat
02.06 18:36:07 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:36:11 [Server] INFO kittielove issued server command: /help 2
02.06 18:36:11 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:36:24 [Server] ERROR Could not pass event EntityDeathEvent to MoneyFromMobs v1.3
02.06 18:36:24 [Server] INFO org.bukkit.event.EventException: null
02.06 18:36:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:3d116a0]
02.06 18:36:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:3d116a0]
02.06 18:36:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:3d116a0]
02.06 18:36:24 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:423) [CraftEventFactory.class:3d116a0]
02.06 18:36:24 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1339) [vp.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1153) [vp.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:394) [aeh.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:287) [aeh.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(EntityTippedArrow.java:107) [afa.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:2337) [amu.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2291) [amu.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.world.World.func_72939_s(World.java:2075) [amu.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:845) [oo.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:985) [MinecraftServer.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) [MinecraftServer.class:?]
02.06 18:36:24 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
02.06 18:36:24 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
02.06 18:36:24 [Server] INFO Caused by: java.lang.NullPointerException
02.06 18:36:24 [Server] INFO at me.Chocolf.MoneyFromMobs.MainListener.onDeath(MainListener.java:83) ~[?:?]
02.06 18:36:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor6.execute(Unknown Source) ~[?:?]
02.06 18:36:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:3d116a0]
02.06 18:36:24 [Server] INFO ... 17 more
02.06 18:36:25 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:36:25 [Server] INFO CONSOLE issued server command: /list
02.06 18:36:25 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:36:25 [Server] INFO default: kittielove
02.06 18:36:27 [Server] INFO kittielove issued server command: /town Hyrule
02.06 18:36:27 [Server] INFO exec:com.palmergames.bukkit.towny.Towny#Towny v0.96.1.0
02.06 18:36:31 [Server] INFO kittielove issued server command: /help 3
02.06 18:36:31 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:36:58 [Server] INFO exec:com.earth2me.essentials.Essentials#Essentials v2.17.2.0
02.06 18:36:58 [Server] INFO CONSOLE issued server command: /list
02.06 18:36:58 [Server] INFO There are 1 out of maximum 72 players online.
02.06 18:36:58 [Server] INFO default: kittielove

02/06/2020 (18:31)

Client
some reason the towny commands are not working.

**Comment by LlmDl** [comment]
I'd like you to refile this ticket using the form. Please link to your files on pastebin.com. What you've shown here isn't anything helpful.
