### ISSUE TITLE
[Towny] Not allowed to XXXX in the wild.

### ISSUE THREAD

**Issue by stianna** [TownyAdvanced/Towny#4056]
### What steps will reproduce the problem?
1.Breaking blocks
2.Placing blocks
3.Opening chests

### What is the expected output?
1.Breaking the block
2.Placing the block
3.Opening the chest

### What is your Towny version?
Towny-0.96.1.0

### What is your spigot/craftbukkit version?
spigotmc-1.15.2-70fb0

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/9fDEgcTs
2. https://pastebin.com/wsjAJea8
3. https://pastebin.com/pm2RraF1
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file : This is empty

I ran through some previous issue tickets, and forums with the issue and tried the things they give, so my configs and perm configs might be a mess, but it's been like this since the server was created. It seems to be anyone without OP can't build, or destroy in the wild.

**Comment by LlmDl** [comment]
Instead of giving them towny.wild, give them towny.wild.*
