### ISSUE TITLE
Double Chat in game - TownyChat 0.71

### ISSUE THREAD

**Issue by cobrex1** [TownyAdvanced/Towny#4057]
### What steps will reproduce the problem?
1. Install TownyChat 0.71
2. I also have DeluxeChat 1.15.0 installed

When chatting in-game the chat appears in a double line - repated.
https://gyazo.com/a5f04dc12ebd53a4314a8b5407f73830

### What is the expected output?
1. Single line of chat when talking in-game
2.
3.

### What is your Towny
0.96.1.12

### What is your spigot/craftbukkit version?
SpigotPaper #334

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://pastebin.com/C5n3YFVg
7. Your channels.yml :
https://pastebin.com/VfknWXms

**Comment by LlmDl** [comment]
This is fixed on an as-yet-unreleased version of DeluxeChat.
