### ISSUE TITLE
Way to merge towns

### ISSUE THREAD

**Issue by karlovm** [TownyAdvanced/Towny#4060]
Is there a simple way to merge towns to one via Towny?

I need it for my wars plugin,

**Comment by ZenArchipelago** [comment]
Do you mean like annex a town, because in that case there is a plug-in known as War For Towny on spigot which can do that.

**Comment by suneettipirneni** [comment]
If you’re talking about merging two towns into one expect that very soon.

**Comment by LlmDl** [comment]
Duplicate of https://github.com/TownyAdvanced/Towny/issues/3193
