### ISSUE TITLE
How to add one townblock to another town?

### ISSUE THREAD

**Issue by karlovm** [TownyAdvanced/Towny#4061]
![image](https://user-images.githubusercontent.com/51130679/84001606-a8ff7780-a96f-11ea-893f-25ac57082cb5.png)
I tried to use this. But idk how to do it right. Hope you can help me

**Comment by LlmDl** [comment]
After the `tb.setTown(win);` add a `TownyUniverse.getInstance().getDataSource().saveTownBlock(tb);`

**Comment by karlovm** [comment]
why I can't destory in the merged townblock?
Townchunks is 2 (my town now is owner of that townblock), but i can't destroy|place etc. in it.

**Comment by LlmDl** [comment]
Your playercache might be operating on the previous cached results for breaking. Leave the plot and hit something, then return and try again. If it allows it, then it is just the cache.
