### ISSUE TITLE
Towny Economy Issue

### ISSUE THREAD

**Issue by TheWackersKian** [TownyAdvanced/Towny#4062]
### What steps will reproduce the problem?
1. Attempt to claim a plot in towny.
2. Tax will not be withdrawed from your account, leading in your plot becoming unclaimed.

### What is the expected output?
1. Successfully claiming a plot
2. Tax being withdrawed correctly and keeping the plot.

### What is your Towny version?
Do not say "latest". 0.96.1.0

### What is your spigot/craftbukkit version?
Do not say "latest". 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/nkzvsANh
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/2hNtxW40
3. Your townyperms.yml : https://pastebin.com/mu3Ydcm0
4. Your log's error : N/A

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A 
7. Your channels.yml : N/A

I have no clue why this is problem is occuring.

**Comment by LlmDl** [comment]
Gringott's recently made an update in their snapshots to support the Towny pre-releases. You should probably make sure you're on the newest Gringott's snapshot and then also make sure you've updated to Towny 0.96.1.11. Then re-test this.

**Comment by TheWackersKian** [comment]
Hi there I have now retried with this with the latest version of both and still no luck unfortunately.

**Comment by LlmDl** [comment]
You may want to open a ticket with Gringotts in this case. Towny is just listening to the Vault response.
