### ISSUE TITLE
Softer town deletion

### ISSUE THREAD

**Issue by Looowi** [TownyAdvanced/Towny#4063]
Town deletion when the town doesn’t have enough money to pay the upkeep is too quick, moreover when creating a town is very expensive. There would be several solutions to make it a little better :
- A message to inform people that they need to deposit money in te bank when they create their town (people often think that having money on them is enough)
- Taking the money directly from mayor when there is not enough money in the town’s bank
- An option in the config to make the town lose a certain number of claims per day until it has no claim

**Comment by suneettipirneni** [comment]
A solution to this problem is en-route:
https://github.com/TownyAdvanced/Towny/pull/4031

**Comment by LlmDl** [comment]
> * A message to inform people that they need to deposit money in te bank when they create their town (people often think that having money on them is enough)
This is already in the pre-releases.
> * Taking the money directly from mayor when there is not enough money in the town’s bank
This is not planned.
> * An option in the config to make the town lose a certain number of claims per day until it has no claim
The town bankruptcy linked above will make towns able to be bought-back, after they have been bankrupted.
