### ISSUE TITLE
Town chest protections can be bypassed with an un-researched slimefun item

### ISSUE THREAD

**Issue by ItsSynchro** [TownyAdvanced/Towny#4065]
### What steps will reproduce the problem?
1. Get a slimefun item that you havent researched
2. right click a chest in a town
3.

### What is the expected output?
1. Deny ability to bypass chest protection

### What is your Towny version?
0.96.1.10

### What is your spigot/craftbukkit version?
git-Paper-341

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hasteb.in/ubarasiz.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hasteb.in/axozalar.coffeescript
3. Your townyperms.yml : https://hasteb.in/qivipafa.yaml
4. Your log's error : none

**Comment by LlmDl** [comment]
I would appreciate instructions that include how to get said items, I have never used slimefun.

**Comment by ItsSynchro** [comment]
> I would appreciate instructions that include how to get said items, I have never used slimefun.

Type "/sf cheat" and select any item. You have to ensure that you're not opped and able to bypass the chest protections though.

**Comment by LlmDl** [comment]
Link to slime fun?

**Comment by ItsSynchro** [comment]
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/ , you'll also need their dependency "CS-CoreLib" https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/

**Comment by ItsSynchro** [comment]
I was told to link you to here by BusyBuscuit (the lead developer of Slimefun). https://github.com/TheBusyBiscuit/Slimefun4/wiki/protection-plugins
