### ISSUE TITLE
Nation Spawn toggles not respected

### ISSUE THREAD

**Issue by jimender2** [TownyAdvanced/Towny#4066]
### What steps will reproduce the problem?
1. Changed the n spawn permissions in the config to be false for all but the nation spawn (so ally and neutral nation spawns turned off).
2. Restarted / started the server
3. Can still tp to other nation spawns (even deopped and in new towns / nations)

### What is the expected output?
1.  Players should not be able to tp to the ally and neutral nation spawns.

### What is your Towny version?
Do not say "latest".
0.96.1.11 (was also noticed back in 0.96.1.0 and before)

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Paper-309 (was noticed on previous versions too)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

[config-1-.txt](https://github.com/TownyAdvanced/Towny/files/4749657/config-1-.txt)
[townyperms-3.txt](https://github.com/TownyAdvanced/Towny/files/4749658/townyperms-3.txt)

**Comment by LlmDl** [comment]
If you'd like to confirm this is fixed please test this pre-release of 0.96.2.2 https://cdn.discordapp.com/attachments/581163022874050569/727293278692573234/Towny-0.96.2.2.jar
