### ISSUE TITLE
/plot toggle mobs will not work If town mobs are toggled on

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#4067]
I’m not sure if this is a bug or intended behavior so I’m not sure if this is a bug report or a feature suggestion.  It’s been this way as long as I can remember.  

### What steps will reproduce the problem?
1. Toggle mobs on in town with /t toggle mobs. 
2. Toggle mobs in a specific plot with /plot toggle mobs 
3.No matter what you do with the plot, mobs stay off on the plot. 

### What is the expected output?
1. Toggling mobs off in the plot would override the town setting even when they’re on in the town. 
2.
3.

### What is your Towny version?
Do not say "latest".

0.96.1.11 , but I remember this behavior from at least 7 years ago. 

### What is your spigot/craftbukkit version?
Do not say "latest".

Paper #341, Minecraft 1.15.2, but, as above, I remember this for years.  

### Please use Pastebin.com to link the following files:

I’ll grab the files momentarily and add them to the ticket. I’m on my phone atm, but they won’t have changed significantly since my last report.  

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :

https://pastebin.com/zf42bLX0

2. Your Towny config.yml (if using MySQL please remove password,) :

https://pastebin.com/jutxqL3T

3. Your townyperms.yml :

https://pastebin.com/Kw3Shpps

4. Your log's error :  No error. 

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Momshroom** [comment]
Files now added in.  Sorry for the delay

**Comment by dorsax** [comment]
This bug does also apply to the newly added plot groups, they cannot be toggled either. The success message shows, but the info does not and it doesn't work either.

Running on Version 0.96.1.3

**Comment by LlmDl** [comment]
This is likely the same thing we found with PVP being overridden by the Town.
