### ISSUE TITLE
Dynmap towny

### ISSUE THREAD

**Issue by alex17lol** [TownyAdvanced/Towny#4070]
When I restart the server I get an error in console

And dynmap towny is not working properly because of it and I already know the cause the cause is a custom economy plugin my dev is making for me but I dont know why the error is happening and thats my question why this happens and how to fix it

?
The dynmap towny should work properly and not give me any errors

goosius1's siegewar(had no idea where to put it on his github):
Dynmap-Towny-0.80
Towny-0.96.1.11

I use tunity 1.15.2 (Tunity is a fork of paper)

1. Your full server startup from the logs\latest.log : https://pastebin.com/PKvUsPN7

**Comment by Goosius1** [comment]
I had an idea on this. Investigating something now....

**Comment by Goosius1** [comment]
* This issue appears to have been solved by the custom eco plugin developer. 
* I got confirmation from a server admin that an updated eco jar was made which resolves this issue (I don't have further details or the jar)
* Thus I believe this ticket can be closed, as work does not seems to be needed Towny-side.
