### ISSUE TITLE
Question: I want know this bug

### ISSUE THREAD

**Issue by 20181241** [TownyAdvanced/Towny#4072]
**Ask your question as best as you are able:**
Towny verstion is 0.96.1.10 
I'm one of the users who enjoys Towny. one day on, the land becomes unclaim when someone does not unclaim. There is also an error that only certain commands, such as t kick, leave, cannot be used.
I am sorry to provide you with detailed information and would like to get some help accordingly.

**Comment by LlmDl** [comment]
Without your server admin filing a bug report I'm afraid there is not enough information to solve the issues you're experiencing. They are welcome to file that ticket though.

**Comment by 20181241** [comment]
Due to the error that leads to 'msg_bankrupt', it seems that the land is being sold out because the money or maintenance costs of the village safe are not recognized.

**Comment by LlmDl** [comment]
Again, without a bug report filed, I cannot really tell what is going on.

**Comment by 20181241** [comment]
I'm sorry. I'll check more and come back if it doesn't work out.
