### ISSUE TITLE
Death but money wasn't lost

### ISSUE THREAD

**Issue by NightPrimez** [TownyAdvanced/Towny#4075]
### What steps will reproduce the problem?
1. install CMI, Vault 1.7.3
2. enable CMI Economy like this https://i.imgur.com/AbgGLGZ.png
3. set percentage to make money drop (im setting 0.1)
4. suicide

### What is the expected output?
1. money should drop from my balance

### What is your Towny version?
0.96.1.0 (0.96.1.11 not working too.)

### What is your spigot/craftbukkit version?
1.15.2-SSSpigot (paper fork)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/m2d7wVpJ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Pf8bgdxD
3. Your townyperms.yml : https://pastebin.com/dA6dvGf2
4. Your log's error : **None**

(optional) If this is to do with permissions, 
5. Your permissions file : **None**

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/9dsiDnRQ
7. Your channels.yml : https://pastebin.com/wknYmUJC

**Comment by LlmDl** [comment]
Does this only happen when you suicide using /kill ?
