### ISSUE TITLE
Listing towns or nations do not work in console

### ISSUE THREAD

**Issue by richiedevs** [TownyAdvanced/Towny#4076]
### What steps will reproduce the problem?
By using console and writing `/t list` or `/n list`

### What is the expected output?
What you expect: for it to list the towns/nations

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
spigot-1.14.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/gua8W18G
2. Your Towny config.yml: https://pastebin.com/f2zDNC0L
3. Your townyperms.yml: https://pastebin.com/i4z28h1A
4. Your log's error: No error, just: [Towny] Only 0 pages available

**Comment by LlmDl** [comment]
I tested this on both 0.96.1.12 and 0.96.1.0 and had no issue using either /t list or /n list in the console.

What does /towny universe show?

**Comment by richiedevs** [comment]
it shows
```xml

-###---###-
#####-#####   [Towny 0.96.1.0]
###########   By: Chris H (Shade)/ElgarL/LlmDl
-#########-
--#######--   Residents: 9 | Towns: 0 | Nations: 0
----###----   Worlds: 6 | TownBlocks: 0
-----#----- 
-----------   [TownyChat 0.68]
```

**Comment by LlmDl** [comment]
You have no Towns or Nations to list then. That's why it shows you having 0 towns/0 nations.
