### ISSUE TITLE
Occassional NullPointerException when players change plots

### ISSUE THREAD

**Issue by ComradeVist** [TownyAdvanced/Towny#4078]
### **What steps will reproduce the problem?**
1. Play Towny normally and walk through lots of plots
2. Watch for actionbar plot messages to begin to duplicate and spam for plots you've walked in recently

(I don't have a lot of information about it. I noticed it June 2nd, a few days after a few major updates to plugins, like PlotSquared v5 and EssentialsX. Usually happens once or twice a day. Here's a video of it as well https://imgur.com/a/nxD11mg)

### **What is the expected output?**
No null pointers should occur. Actionbar messages should not repeat plots a player is not in.

### **What is your Towny version?**
0.96.1.11

### **What is your spigot/craftbukkit version?**
Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### **Please link the following files:**

1. Your full server startup from the logs\latest.log:
https://pastebin.com/mMthe7jT

2. Your Towny config.yml (if using MySQL please remove password): 
https://pastebin.com/pkHxG825

3. Your townyperms.yml: 
https://pastebin.com/GqA04rdx

4. Your log's error: 
`[17:21:25] [Server thread/WARN]: [Towny] Task #-2140197916 for Towny v0.96.1.11 generated an exception
java.lang.NullPointerException: null
	at com.palmergames.bukkit.towny.listeners.TownyCustomListener.lambda$onPlayerChangePlotEvent$0(TownyCustomListener.java:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by suneettipirneni** [comment]
@ComradeVist can u try this jar and see if the issue is resolved?
**[Towny-0.96.1.12.jar.zip](https://github.com/TownyAdvanced/Towny/files/4777279/Towny-0.96.1.12.jar.zip)**

**Comment by suneettipirneni** [comment]
@ComradeVist sorry that last one was the wrong jar, here's the correct one:
[Towny-0.96.1.12.jar 2.zip](https://github.com/TownyAdvanced/Towny/files/4777282/Towny-0.96.1.12.jar.2.zip)

**Comment by ComradeVist** [comment]
I'll give it a try, thank you. I'll write if I experience this issue again following :)

**Comment by suneettipirneni** [comment]
Has the issue cropped up again?

**Comment by ComradeVist** [comment]
The issue still occurs with the build you sent me, unfortunately. I'm trying to check my logs to see if it's the same stack trace, but a bug with FAWE resulted in a very, *very* large log...

**Comment by ComradeVist** [comment]
The new error basically looks like this:
```
[com.palmergames.bukkit.towny.Towny] [Towny] Error: Map doesn't contain key: CraftPlayer{name=<username>}
{}
```
Here's a snippet of the log when it started occurring. Let me know if there's any other information I should provide.
https://pastebin.com/ceYrTVQ5

**Comment by LlmDl** [comment]
> The new error basically looks like this:
> `[com.palmergames.bukkit.towny.Towny] [Towny] Error: Map doesn't contain key: CraftPlayer{name=<username>} {}`
> Here's a snippet of the log when it started occurring. Let me know if there's any other information I should provide.
> https://pastebin.com/ceYrTVQ5

Sorry for the late reply, by any chance are these <usernames> also Citizens NPCs?

**Comment by ComradeVist** [comment]
Definitely not. All of the usernames that were in Towny messages were online players, and I know for sure there aren't any npcs with a few of those names, if not all of them.

**Comment by LlmDl** [comment]
Ok, so I'm settling down to take another look at this one and I see in your config you have the action bar messages turned off. 

Is this still a present issue on your server and/or do you have the actionbar messages enabled now?

**Comment by ComradeVist** [comment]
Hi, I've fallen a bit behind on Towny updates. I'll make sure to catch up ASAP and monitor for this bug. It's very occasional but I usually end up hearing about it quickly :)

**Comment by ComradeVist** [comment]
Hello. I've come to report that it still happens. No errors in my log. It was relatively frequent while on 1.14, but when I updated to 1.15 it became very infrequent. In fact, this is the first it's happened in weeks. I was on the same Towny version before upgrading. I'm not entirely sure this is Towny's fault.

**Comment by LlmDl** [comment]
Can you show me some of the recent errors and give me your current towny version?

**Comment by ComradeVist** [comment]
Currently 0.96.2.20. probably should be on latest release, mb. There were no errors at all around the time it started.

**Comment by LlmDl** [comment]
Update to 0.96.3.0 asap.

**Comment by ComradeVist** [comment]
The issue was caused by a bug in BentoBox that was fixed this month. Thank you for all your time, effort, and patience into what ultimately was a wild goose chase.
