### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by tomgabe22** [TownyAdvanced/Towny#4080]
Hello! I’ll preface this by saying I have no idea about how Java Servers work, plugins or coding or any of those things. I just want to start a Towny Roleplay Economy Server with a friend and this Plugin looks Absolutely AMAZING! I was wondering if this plugin comes with an Economy Beforehand? Or would I need to download a separate economy plugin?

**Comment by LlmDl** [comment]
You need an economy plugin and the plugin called Vault to bridge between Towny and the economy plugin.

**Comment by LlmDl** [comment]
Read the install guide: https://github.com/TownyAdvanced/Towny/wiki/Installation
