### ISSUE TITLE
Non-sanitized data using MySQL

### ISSUE THREAD

**Issue by Saghetti0** [TownyAdvanced/Towny#4081]
### What steps will reproduce the problem?
1. Create a town with a quotation mark in it
2. Reload towny
3. Watch as it crashes and burns (Towny fails to load data and goes into safe mode)

### What is the expected output?
1. It should properly load data.

### What is your Towny version?
Do not say "latest".
0.93.1.0 for 1.12.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paperspigot 1.12.2 build 1618

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/mAP1tFMV
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/0jr39waH
3. Your townyperms.yml : https://pastebin.com/prCnVdDP
4. Your log's error : https://pastebin.com/d7S2LWFz

Note: This happened to me on a server with over 20 people online at the same time. I reloaded Towny just so I could apply some settings, but then it decided to just self destruct. I'm baffled that the Towny devs don't know how to sanitize their data.

**Comment by Saghetti0** [comment]
This is a really urgent bug that should be fixed ASAP. For now, I'm just going to edit my MySQL database directly so that I don't experience this crash anymore. Does this happen on a data store such as H2 or SQLite?

**Comment by Saghetti0** [comment]
![image](https://user-images.githubusercontent.com/60995055/84585375-170acb00-adc4-11ea-94e3-661b81886fa4.png)
How did this get added to the project?

**Comment by silverwolfg11** [comment]
> I'm baffled that the Towny devs don't know how to sanitize their data.
We do know how to sanitize data.
However, initially when the DB was designed the regex enforced town names to follow alphabetical characters preventing any SQL injection anyway. This will be fixed soon.

**Comment by Saghetti0** [comment]
Maybe use PreparedStatements? Also, this bug could be used to literally wipe entire databases of Towny servers. This should be fixed ASAP

**Comment by suneettipirneni** [comment]
This is a 1.12 towny issue which only affects < 5% of all towny users. Most people already have the patched version but we can back port the fixes to 1.12.

**Comment by LlmDl** [comment]
This got done a while ago and the ticket got missed for an update.
