### ISSUE TITLE
Pistons placed on the edge of town claims never unextend

### ISSUE THREAD

**Issue by ComradeVist** [TownyAdvanced/Towny#4084]
### What steps will reproduce the problem?
1. Create a fresh server
2. Create a town
3. Place a piston on the border of the town's wild/town border and power it
4. Unpower the piston and notice it does not unextend
https://i.imgur.com/JcVfiuY.png

### What is the expected output?
1. The piston should unextend as it is not powered and entirely within a town claim
2. Pistons should not get stuck powered

### What is your Towny version?
0.96.1.11

### What is your spigot/craftbukkit version?
Paper 1.15.2 350

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :
https://pastebin.com/wHbAJURE
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/nMTcBDbj
3. Your townyperms.yml :
https://pastebin.com/2GHGmZZF
4. Your log's error : 
No error

This was an issue in the past. It only affects pistons placed on the border of a town and wild

**Comment by LlmDl** [comment]
This happens every 2-3 years, something changes and this happens. Thanks for the ticket.

**Comment by ComradeVist** [comment]
I think I was the last one who reported it too! It always breaks one of my old farms :)
