### ISSUE TITLE
Suggestion: Add separate town spawn/nation spawn warmup bypass permission node

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#4090]
**Please explain your feature request to the best of your abilities:**
Currently the permission to bypass town spawn/nation spawn warmup times also gives you immunity to cooldowns and spawn costs. I think that this permission should be split into the separate permissions for each function, for better customization.

**Comment by LlmDl** [comment]
Looked through the code and the old node `towny.command.townyadmin.town.spawn.freecharge` still exists, allowing free spawns. It is a child node of towny.admin.spawn, which is the one that bypasses warmups/cooldowns.

If you give `towny.command.townyadmin.town.spawn.freecharge` they will not pay and still be charged.
