### ISSUE TITLE
Boats break item frames

### ISSUE THREAD

**Issue by remcodd2** [TownyAdvanced/Towny#4093]
### What steps will reproduce the problem?
If u bump into an item frame with a boat, even in a protected plot, it still breaks

### What is the expected output?
They shouldnt break

### What is your Towny version?
I am not sure bc im on Earthmc and not a developer

### What is your spigot/craftbukkit version?
1.15

So the issue is that flyhackers about this glitch by flying into an area with a boat, that they were able to place outside the town borders. This means that everything within an item frame can be stolen, even though theft shouldnt be possible in a towny plot

**Comment by docwhomc** [comment]
If I understand correctly, it could be fixed by having `HangingBreakByEntityEvent` check if the `getRemover()` method returns a `Vehicle` instance.  If it does, check if the `Vehicle`'s `getPassenger()` method returns a player with the permissions necessary to break the item frame.  If not, cancel the event.

**Comment by LlmDl** [comment]
I have a ticket on [the Spigot JIRA tracking this](https://hub.spigotmc.org/jira/browse/SPIGOT-3999?filter=-2) and as far as I understand it, there is no protection for this because the API does not fire the correct events. I thought there was a ticket for this on here already but I cannot find one open or closed. If you can find a solution @docwhomc it would be greatly appreciated.

**Comment by LlmDl** [comment]
@docwhomc did do a bit of researching into this and found that it is still a missing part of the bukkit/craftbukkit API, as described in the ticket I linked above. We'd love to fix this but we cannot, due to the missing/broken event for boats breaking item frames.

**Comment by docwhomc** [comment]
We may have a fix... docwhomc/Towny@a3cb64a18c0f2a7856aeb42dc64ec28a9e0f5be6

**Comment by remcodd2** [comment]
Is there any update to this regarding the possible fix doc suggested. In the server i play on, i've just been robbed stuff from item frames for the **second** time, even though it was completely sealed off. This means that as long item frames are glitched and can be broken, people will glitch and hack their way in with a boat.

Currently nothing can be displayed in an item frame that has value, because it can and will get stolen

**Comment by docwhomc** [comment]
I'm working on it, but the Bukkit API doesn't handle the collision of boats with item frames properly.  I'm still trying to find the event it does trigger.
I'd suggest only displaying copies for the time being.

**Comment by bluestonecarrot** [comment]
I saw this issue on the EMC tracker and I actually have a fix. If u check my repos I made a plugin that works around the incorrect events being fired.

**Comment by remcodd2** [comment]
I got an update from the EMC github, perhaps this will help @docwhomc 

https://github.com/EarthMC/Issue-Tracker/issues/1162#issuecomment-650903800

**Comment by remcodd2** [comment]
@docwhomc any update to this? i got robbed again

**Comment by remcodd2** [comment]
has it been fixed? havent had any response

**Comment by LlmDl** [comment]
Ya it's been fixed, part of the above commit.

**Comment by remcodd2** [comment]
To be sure, would it affect any current hanging itemframes at the moment? Like will they drop and have to be replaced for example?

**Comment by bluestonecarrot** [comment]
The current item frames should not be vulnerable if my plug-in is installed. However, it *might* not work for 1.16 as I haven't tested it there.

**Comment by LlmDl** [comment]
@bluestonecarrot with your plugin you'll probably want to account for the cave_air and bubble_column materials. Towny opted to just do isLiquid and isEmpty tests for the same result.

@remcodd2 once the update is made all the item_frames will be protected from boats.
