### ISSUE TITLE
Mod machine can be opened when a chunk is protected by towny

### ISSUE THREAD

**Issue by 3094300238** [TownyAdvanced/Towny#4094]
### What steps will reproduce the problem?
1.when you setup a immersive engineering mod in server ,you will notice there're some machine which has its unique gui.
2.when you enter a chunk protected by towny
3.right click the machine and you can open gui to steal anything.

### What is the expected output?
1.player without permission can steal something.

### What is your Towny version?
Do not say "latest".
0.93.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12.2

**Comment by LlmDl** [comment]
You can attempt to solve this by right clicking on the machine while holding a clay brick. It will tell you the block name of the machine. This block name is then added to the Towny config.yml's switch_id list.
