### ISSUE TITLE
Purchasable town claims

### ISSUE THREAD

**Issue by Teamustu** [TownyAdvanced/Towny#4095]
I was wondering if there was a way to add extra claim chunks to a specific town, so that I could allow players to purchase extra town claims with points or currency. I have seen this done on other servers, but I can’t seem to find a support thread that talks about it. Thank you in advanced

**Comment by LlmDl** [comment]
There are instructions on [this page](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#buying-townblocks) for configuring purchaseable TownBlocks.
