### ISSUE TITLE
/towny top land doesn't work

### ISSUE THREAD

**Issue by 3meraldK** [TownyAdvanced/Towny#4099]
### What steps will reproduce the problem?
1. type /towny top land

### What is the expected output?
1. expected output would be top land list

### What is your Towny version?
0.96.1.11

### What is your spigot/craftbukkit version?
git-Paper-353

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/CxE661bv
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/CZpnS2Nm
3. Your townyperms.yml : https://pastebin.com/TnVSC1sa
4. Your log's error : https://pastebin.com/3P8aQRBh

**Comment by LlmDl** [comment]
This was fixed in 0.96.1.12. Update and if it doesn't work I'll reopen this ticket.
