### ISSUE TITLE
Dragon breath not considered harmful.

### ISSUE THREAD

**Issue by Zacky26** [TownyAdvanced/Towny#4100]
### What steps will reproduce the problem?
1. Install SlimeFun Hotbar Pets or spawn a dragon at your town (NOT RECOMMENDED).
2. Use the dragon pet to spawn a dragon breath or use the command /fireentity dragon.
3. Players take damage (THE ISSUE)

### What is the expected output?
1. Players should be immune.

### What is your Towny version?
Towny Advanced 0.96.1.12

### What is your spigot/craftbukkit version?
Paper 3.5.3

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Not necessary.
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/erijusasor.coffeescript
3. Your townyperms.yml :https://hastebin.com/vufiniyiyi.php
4. Your log's error : No errors

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Zacky26** [comment]
BTW, I believe this is an issue with the lingering potion.

**Comment by LlmDl** [comment]
If it's the entity DragonFireball you could probably just add DRAGON_FIREBALL to the town_mob_removal_entities list in the config.yml. Did you want to test that?

**Comment by Zacky26** [comment]
Adding that doesn't work apparently. The Dragon_Fireball still works.

**Comment by LlmDl** [comment]
If this is still a thing could you please use /ta toggle debug and then do some of this dragon fireball damage for me, then show me the log of it?
