### ISSUE TITLE
Homeblock Exception

### ISSUE THREAD

**Issue by PreciseOXT** [TownyAdvanced/Towny#4104]
Hi,

Can someone please tell me how fix the 'gethomeblock exception'?

This occasionally occurs when a new town is created and no homeblock is created.
'/town set homeblock' 
gives the error message, 
'Town has not set a homeblock, use /town set homeblock.'

![unknown](https://user-images.githubusercontent.com/66925101/85234182-ba607d80-b45f-11ea-883c-3bb2491f91ae.png)

Is this what I need and how do I add it?
https://github.com/TownyAdvanced/Towny/blob/ba700bffef82ffd7d82999d2d13e2727f0472c2e/src/com/palmergames/bukkit/towny/object/Town.java

Thanks in advance.

**Comment by LlmDl** [comment]
You're likely getting that getHomeBlock exception message from dynmap-towny. If you update to Towny 0.96.1.13 which I just uploaded the message will now tell you which town has no homeblock.

**Comment by PreciseOXT** [comment]
Awesome, thanks for the response!
