### ISSUE TITLE
Question:Disable chat formatting by players

### ISSUE THREAD

**Issue by ArmeniumYT** [TownyAdvanced/Towny#4105]
Hey there,
I'm having an issue where people are using color codes (&1, &2, etc) to change the color of their town, nation, and even messages as appears with TownyChat. Is there a way to prevent this? I'm absolutely sure there is some simple fix for this but I can't seem to find it.
I've tried manipulating the regexes and setting `townychat.chat.color` and `towny.chat.color` to false with LuckPerms but none of that seems to work.

**Comment by docwhomc** [comment]
What did you change the regexes to?

**Comment by LlmDl** [comment]
This should be a bug report.
