### ISSUE TITLE
Able to teleport while moving/taking damage

### ISSUE THREAD

**Issue by Warriorrrr** [TownyAdvanced/Towny#4109]
### What steps will reproduce the problem?
1. Do /t spawn, /n spawn or /res spawn twice (No cooldown time)
2. Move
3. The second teleport will cancel, but the first one will still teleport you

![image](https://user-images.githubusercontent.com/50800980/85413907-b752b380-b56b-11ea-91fa-d4aab67c7060.png)
After this I still teleported to my t spawn.

### What is the expected output?
You won't teleport

### What is your Towny version?
0.96.1.13

https://github.com/EarthMC/Issue-Tracker/issues/1170 is why I made this issue, it also has a video displaying the bug further

**Comment by LlmDl** [comment]
Skipped form.
