### ISSUE TITLE
Question: Will the Towny data reset after changing the IGN?

### ISSUE THREAD

**Issue by glitchism** [TownyAdvanced/Towny#4110]
**Ask your question as best as you are able:**
Hey there! I'm a guy playing a Towny server, now I need to change my IGN for some reason, but I have some rumors that the Towny data will be reset after changing the IGN. I didn't change it yet, but let's see if I can change. Sorry if my English is not good, English isn't my first language.
Here's some of the rumors: 
https://github.com/EarthMC/Issue-Tracker/issues/1140
https://github.com/EarthMC/Issue-Tracker/issues/1024
https://github.com/EarthMC/Issue-Tracker/issues/1015

**Comment by JaVolimKatarinu** [comment]
This issue has been patched and you can change your IGN on EMC. Your data wont be deleted.

**Comment by glitchism** [comment]
Ok, i'll close this
