### ISSUE TITLE
Friend system is bugged

### ISSUE THREAD

**Issue by filipohano** [TownyAdvanced/Towny#4112]
The friend system doesn't work with claiming. A player adds another player as friend, set the town permissions to friend build on and friend destroy on, and it doesn't work. What can cause this?

**Comment by LlmDl** [comment]
Towns do not have a friends list. Friends lists only apply to resident-owned plots, not Town-owned plots.


See this video: https://www.youtube.com/watch?v=wvshFTv3l6A&list=PLvzvmyk0uI0WsLf4iyJZRhD_T2e-ANCmE&index=2
