### ISSUE TITLE
Regeneration of the world

### ISSUE THREAD

**Issue by MrKamikazee** [TownyAdvanced/Towny#4116]
### What steps will reproduce the problem?
1. i don't know, when i put false in the config, nothing happens

### What is the expected output?
1. that the regeneration of the world is deactivated when a town falls or when a zone is declaimed

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
paper spigot 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/VCB2PNSs
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/aQnkxYwn
3. Your townyperms.yml :https://pastebin.com/2cJ1cRuD
4. Your log's error :

**Comment by LlmDl** [comment]
The New World Settings section of the config is only default settings for new worlds, it's explained in the config section comments, the install guide and the how towny works page. You need to be using the /tw toggle commands or manually setting the worldname.txt file.
