### ISSUE TITLE
Suggestion: Town friendlist for plot permissions.

### ISSUE THREAD

**Issue by Qorrin** [TownyAdvanced/Towny#4117]
**The Issue:** 

In the current build of Towny, it is impossible to grant build perms to an individual player who is not in your town.  On many towny servers, players like helping other towns in their nation with build projects.  

The only method of allowing players to turn on build perms for all members of the nation, or to claim it yourself and add all the builders as friends.  The first option is dangerous as you may not trust everyone in the nation to build in your town.  The second option is tedious as you have to constantly put up for sale and claim plots, and can often run into limits on how many plots you can claim.  You can also give certain players embassy plots but again this might not cover the whole build and is even more tedious. 

**Recommended Solution:** 

As for my suggestion, I believe it would be very helpful and convenient to add Foreign ranks for towns.  You could grant these to anyone who is not in your town, and would have similar roles to existing ranks.  For example, the Foreign Builder rank would allow you to have Builders who are simply not in your town.  Or, if adding such ranks is inconvenient, simply allow mayors to grant the Builder rank to people who are not in their town.  

I think this would encourage more cooperation within a nation and allow for larger build projects that don't have to fit perfectly within chunk borders.

**Comment by LlmDl** [comment]
At the moment town ranks cannot be given to non-town members. What could work better is a town friendslist. This would treat townfriends the same as town residents when the TownBlockStatus is checked for a player in their playercache.

**Comment by ZenArchipelago** [comment]
Would someone on the town friends list be able to work with non embassy plots? @LlmDl

**Comment by LlmDl** [comment]
Yes, the idea is they would be able to work as if they were a resident on any town-owned plot.

Eventually a townblock could also have the same thing done to it.
