### ISSUE TITLE
towny null on online-mode=false

### ISSUE THREAD

**Issue by kiozix** [TownyAdvanced/Towny#4120]
### What steps will reproduce the problem?
1./t new town
2.
3.

### What is the expected output?
1. town created
2.
3.

### What is your Towny version?
Do not say "latest". 0.93.1.0 for MC 1.12.2

### What is your spigot/craftbukkit version?
Do not say "latest". im using catserver 20.06.23
https://github.com/Luohuayu/CatServer/releases/tag/20.06.23

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : No error found for this issue https://pastebin.com/H7YGB9ZB
2. Your Towny config.yml (if using MySQL please remove password,) : default configuration with mysql password and info removed https://pastebin.com/cN9DnMeT
3. Your townyperms.yml : default https://pastebin.com/YjPcDeg0
4. Your log's error :  no error logs found

hello when i switch the server to online-mode false towny doesn't work anymore and goes out null when i do / t new town when i switch online-mode to true the plugins work niquel which solution to fix the bug?

**Comment by kiozix** [comment]
Towny version updated from empty  to 0.93.1.0 for MC 1.12.2

**Comment by LlmDl** [comment]
This is likely due to your economy provider not returning the player's balance. You should update your Towny to [0.96.2.0 for 1.12.2](https://github.com/TownyAdvanced/Towny/releases/tag/0.96.2.0for1.12.2) and then update your TNE to latest.
