### ISSUE TITLE
some wall shouldn't exist .. I am on 1.16, just updated, idk what is going on

### ISSUE THREAD

**Issue by itsMystikk** [TownyAdvanced/Towny#4121]
### What is your Towny version?
Do not say "latest".
0.96.2.0

### What is your spigot/craftbukkit version?
Do not say "latest".
paper 1.16 build 8

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/gVePq40W
3. Your townyperms.yml :
https://pastebin.com/u5ueQwip
4. Your log's error :  https://pastebin.com/egJTXGL4

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
It would appear that ```com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:stone_brick_wall does not accept 'false' for east property at position 32: ...wall[east=<--[HERE]``` false is not longer accepted for walls, they are now low none or tall according to teh wiki: https://minecraft.gamepedia.com/Wall#Block_states
