### ISSUE TITLE
carpenters blocks

### ISSUE THREAD

**Issue by GoogeTan** [TownyAdvanced/Towny#4124]
### What steps will reproduce the problem?
1. Use thermos 1.7.10
2. Install carpenters blocks
3. Create private
4. Place door in it
5. Use hammer + shift on it

### What is the expected output?
1. door open

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
Where i can see it?

https://pastebin.com/5FbPij8k
https://pastebin.com/SGkALx9h
https://pastebin.com/8MqzHMqG

**Comment by LlmDl** [comment]
While holding a clay brick in your hand, hit the door, Towny should tell you what the block is named, then you put it into the switch_ids list. If this does not work then the mod does not support the Bukkit API Towny uses.
