### ISSUE TITLE
/plot group set [type] shows many confirmations.

### ISSUE THREAD

**Issue by trevor1097** [TownyAdvanced/Towny#4127]
So when playing with plot groups you have to change the group perm with /plot group set perm for the whole group and not the individual plots.

![group perms](https://user-images.githubusercontent.com/7597614/86193499-0b383c00-bb1a-11ea-93ba-8830989ad67b.png)

When you try to can either the settings (pvp, mobs) or the type (farm, shop) the confirmation is bugged in that it doesn't group like it should. If you try to accept it will once change one of the plots at random.

![plot group](https://user-images.githubusercontent.com/7597614/86193159-40905a00-bb19-11ea-95e9-a99a350ae7f0.png)

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
git-Paper-27 (MC: 1.16.1)

**Comment by suneettipirneni** [comment]
The first issue mentioned about perms is intentional. If you want perms on an individual plot, stand in the plot and do `/plot set perm ...`, I'll look into fixing the other issues brought up.

**Comment by suneettipirneni** [comment]
I'm not able to reproduce the issues you described perhaps you can give specific steps on what causes it?

**Comment by LlmDl** [comment]
I've gotten it as far as [/plot toggle no longer be allowed to be used in PlotGroups.](https://github.com/TownyAdvanced/Towny/commit/213604fe985f79b374d35189de563860f0f2a0aa) The message now says to use /plot group toggle, which from looking at the code should work fine. 

The getting-it-to-only-confirm-once for /plot group set TYPE will be a bit more work as some code has to be moved.

**Comment by trevor1097** [comment]
So for now i will just set the type for the plots and them group them. I have also noticed with changing the plot type on a regular plot it sends the "plot type set to farm" before you confirm the plot type switch.
![plot type confirm](https://user-images.githubusercontent.com/7597614/86521074-032e1400-be1a-11ea-986a-f02033c34472.png)

**Comment by LlmDl** [comment]
@trevor1097 in the above screenshot you changed a regular plot to a farm, right?

**Comment by trevor1097** [comment]
Correct
