### ISSUE TITLE
Can't create a town

### ISSUE THREAD

**Issue by Truongvv10** [TownyAdvanced/Towny#4131]
### What steps will reproduce the problem?
1. Trying to create a town using: /t new TestTown
    Can't do any '/confirm' or '/cancel'

### What is the expected output?
1. When trying to do '/confirm' to confirm that you want to create a town, it sais; 'You have nothing to confirm!'

### What is your Towny version?
Towny-0.96.2.0

### What is your spigot/craftbukkit version?
paper version get-paperr-375 (MC: 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/hXgAPT7C
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/suvhGiyS
3. Your townyperms.yml :
https://pastebin.com/m5bUiR4H
4. Your log's error : 
Doesn't say the error, just in chat saying; 'You have nothing to confirm!'

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your startup says your Towny is in safe mode. You have a bunch of plugins. It is possible one of them has taken control of the /confirm option.

Your startup log says you have Towny 0.96.2.0 but your config you show says you're on 0.95.2.0.

**Comment by Truongvv10** [comment]
> Your startup log says you have Towny 0.96.2.0 but your config you show says you're on 0.95.2.0.

Ah yes I see, during transfer I copied the old files and updated the jar, this made it fix it thank you.
