### ISSUE TITLE
Suggestion: Add proper integration with respawn anchors

### ISSUE THREAD

**Issue by suneettipirneni** [TownyAdvanced/Towny#4132]
**Please explain your feature request to the best of your abilities:**

Currently, when someone dies in towny they respawn back to their town, 1.16 introduced the respawn anchor block which allows players to set a respawn point in the nether. Towny should give higher precedence to the respawn anchor, as it is purposely chosen and intended by the player.

**Comment by LlmDl** [comment]
This should come with a config option to have town_respawn override respawn anchors, so servers can maintain old behaviour.
