### ISSUE TITLE
Question: Teleport to home town only?

### ISSUE THREAD

**Issue by HightechCaveman** [TownyAdvanced/Towny#4133]
In my server, most players don't want any form of tp except for teleporting to your home town. That means no /warp, no /spawn, no /t spawn (other town). Is there any way to have it where you can't teleport to other towns besides your own?

**Comment by LlmDl** [comment]
Towny cannot do anything about other plugins doing /warp and /spawn (you can disable those in that plugin,) you can stop /t spawn other towns by disabling it in the config at `allow_town_spawn_travel: 'false'`
