### ISSUE TITLE
Not able to pick up blocks

### ISSUE THREAD

**Issue by NYBluff** [TownyAdvanced/Towny#4135]
my players who created a town and have started mining have been getting the issue of not being able to pick up blocks they mined, in the wild and in their town plot. 
 down below is the txt file that is causing the issue according to my developer.
From what I saw, players couldn't pick up dirt, logs, flowers and etc. 

pvp=true
forcepvp=false
# Can players found towns and claim plots in this world?
claimable=true
worldmobs=true
forcetownmobs=false
firespread=true
forcefirespread=false
explosions=true
forceexplosions=false
endermanprotect=true
disableplayertrample=true
disablecreaturetrample=true

# Unclaimed Zone settings.
unclaimedZoneBuild=true
unclaimedZoneDestroy=true
unclaimedZoneSwitch=true
unclaimedZoneItemUse=true
unclaimedZoneName=Wilderness

# The following settings are only used if you are not using any permissions provider plugin
unclaimedZoneIgnoreIds=GOLD_ORE,IRON_ORE,COAL_ORE,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,DIAMOND_ORE,REDSTONE_ORE,GLOWING_REDSTONE_ORE,SUGAR_CANE_BLOCK,NETHER_WARTS

# The following settings control what blocks are deleted upon a townblock being unclaimed
usingPlotManagementDelete=true
plotManagementDeleteIds=WHITE_BED,ORANGE_BED,MAGENTA_BED,LIGHT_BLUE_BED,YELLOW_BED,LIME_BED,PINK_BED,GRAY_BED,LIGHT_GRAY_BED,CYAN_BED,PURPLE_BED,BLUE_BED,BROWN_BED,GREEN_BED,RED_BED,BLACK_BED,TORCH,REDSTONE_WIRE,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN,WOODEN_DOOR,ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,STONE_PLATE,IRON_DOOR_BLOCK,WOOD_PLATE,REDSTONE_TORCH_OFF,REDSTONE_TORCH_ON,DIODE_BLOCK_OFF,DIODE_BLOCK_ON

# The following settings control what blocks are deleted upon a mayor issuing a '/plot clear' command
usingPlotManagementMayorDelete=true
plotManagementMayorDelete=ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN

# If enabled when a town claims a townblock a snapshot will be taken at the time it is claimed.
# When the townblock is unclaimded its blocks will begin to revert to the original snapshot.
usingPlotManagementRevert=true
# Any block Id's listed here will not be respawned. Instead it will revert to air.
plotManagementIgnoreIds=GOLD_ORE,LAPIS_ORE,LAPIS_BLOCK,GOLD_BLOCK,IRON_ORE,IRON_BLOCK,MOSSY_COBBLESTONE,TORCH,SPAWNER,DIAMOND_ORE,DIAMOND_BLOCK,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN,ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,GLOWSTONE,EMERALD_ORE,EMERALD_BLOCK,WITHER_SKELETON_SKULL,WITHER_SKELETON_WALL_SKULL,SHULKER_BOX,WHITE_SHULKER_BOX,ORANGE_SHULKER_BOX,MAGENTA_SHULKER_BOX,LIGHT_BLUE_SHULKER_BOX,LIGHT_GRAY_SHULKER_BOX,YELLOW_SHULKER_BOX,LIME_SHULKER_BOX,PINK_SHULKER_BOX,GRAY_SHULKER_BOX,CYAN_SHULKER_BOX,PURPLE_SHULKER_BOX,BLUE_SHULKER_BOX,BROWN_SHULKER_BOX,GREEN_SHULKER_BOX,RED_SHULKER_BOX,BLACK_SHULKER_BOX,BEACON

# If enabled any damage caused by explosions will repair itself.
usingPlotManagementWildRegen=true
PlotManagementWildRegenEntities=creeper,endercrystal,enderdragon,fireball,smallfireball,largefireball,tntprimed,explosiveminecart
usingPlotManagementWildRegenDelay=20

# This setting is used to enable or disable Towny in this world.
usingTowny=true

# This setting is used to enable or disable Event war in this world.
warAllowed=true
metadata=

**Comment by LlmDl** [comment]
Towny has no effect one who can pick up what blocks. This will be another plugin doing this.

**Comment by NYBluff** [comment]
I still believe its a towny issue because towny admins are able to pick up blocks without any issue, maybe there is a towny permission missing, can you direct me to what permission it is if there is one missing? Wheather claimed or not the blocks aren't allowed to be picked up.

**unclaimedZoneIgnoreIds**=BONE_MEAL,FLINT_AND_STEEL,BUCKET,WATER_BUCKET,LAVA_BUCKET,MINECART,STORAGE_MINECART,INK_SACK,SHEARS,ENDER_PEARL,GLASS_BOTTLE,FIREBALL,ARMOR_STAND,SKULL_ITEM,BIRCH_BOAT,ACACIA_BOAT,DARK_OAK_BOAT,JUNGLE_BOAT,OAK_BOAT,SPRUCE_BOAT,END_CRYSTAL,POWERED_MINECART,COMMAND_MINECART,EXPLOSIVE_MINECART,HOPPER_MINECART,CHORUS_FRUIT,BLACK_DYE,BLUE_DYE,BROWN_DYE,CYAN_DYE,GRAY_DYE,GREEN_DYE,LIGHT_BLUE_DYE,LIGHT_GRAY_DYE,LIME_DYE,MAGENTA_DYE,ORANGE_DYE,PINK_DYE,PURPLE_DYE,RED_DYE,WHITE_DYE,YELLOW_DYE,DIAMOND_AXE,GOLDEN_AXE,IRON_AXE,WOODEN_AXE,STONE_AXE

**Comment by LlmDl** [comment]
You're talking about picking up block entities from the ground and not breaking blocks right?

**Comment by NYBluff** [comment]
> You're talking about picking up block entities from the ground and not breaking blocks right?

Yes, as soon as the player breaks the block. They are not able to pick up the entity.  I threw blocks like logs, iron ore, dirt to a player. They couldn't pick up the entity.

**Comment by LlmDl** [comment]
Towny doesn't do anything to stop people picking up blocks. You can probably start removing plugins to figure out what is causing it.

**Comment by NYBluff** [comment]
> Towny doesn't do anything to stop people picking up blocks. You can probably start removing plugins to figure out what is causing it.

I'll try that out. And get back to you. 
I still find it strange that players with the TownyAdmin perms have no issue with this.

Regular players with basic perms have this issue ever so often for about 5 to 20 minutes. Somehow it resolves itself which makes no sense.
