### ISSUE TITLE
Suggestion: Toggle death item drop for arena chunks

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#4137]
Very simple idea. I'd love to be able to toggle the dropping of items on death in arena chunks in the config. This would let server admins create warp arenas, and even players, create pvp arenas that are just for fun where people can pvp as much as they want and not worry about losing their items on death. 

#drop items on death in arena chunks?
Arenadeathdrop: true

Additionally, perhaps another option could be added at the same time, for a town wide toggle, that would be admin permission by default.

/ta town name toggle itemdrop
/t toggle itemdrop

**Comment by suneettipirneni** [comment]
I've created an update to support arena exclusive keep-inventory on arena plots. As for your other request towny already has a town-wide keep-inventory option called `global_town_settings.keep_inventory_on_death_in_arena` in the config.

**Comment by BeeRando** [comment]
True that other option exists, but thats not exactly what people think it is.
A) It doesn't let you keep inventory in just your town/nation claim, it lets you keep it EVERYONES claim, which caught me off guard at first. 
B) It doesn't let you do it for a specific town. My suggestion was making one town, like a spawn town, or an event town, be keep inventory on death, not the entire server keep inventory on death.

**Comment by LlmDl** [comment]
Since the PR does complete this ticket's title can you file a new one for a Town setting for keepinventory @BeeRando ?
