### ISSUE TITLE
SQL Operation lags server?

### ISSUE THREAD

**Issue by lucasboss45** [TownyAdvanced/Towny#4141]
### What steps will reproduce the problem?
1. Wait for new day code to execute or just use /ta newday

### What is the expected output?
1. No errors

### What is your Towny version?
Towny 0.96.2.0

### What is your spigot/craftbukkit version?
PaperMC-375 (MC 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://ghostbin.co/paste/c385m (It's too big for Pastebin apparently)
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/TyE94Yhz
3. Your townyperms.yml : https://pastebin.com/A1v5BA6W
4. Your log's error : https://pastebin.com/1L2quV20

~~(optional) If this is to do with permissions, 
5. Your permissions file :~~

~~(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :~~

**Comment by LlmDl** [comment]
Looks as though your server was just lagging:

- The TPS was poor enough that it took an extra ~70 minutes for the new day to happen.
- You're doing a worldborder fill while doing other server operations.
- Some of those operations are doing radius claims (/t claim 53, /t claim 5) which may or may not be also making plot snapshots if you have the revert on unclaim active in the world.

It was not Towny that decided to make a thread dump, it is your paper. It is a good idea to let worldborder do its fill operation before doing anything else on the server.
