### ISSUE TITLE
Question: Towny terrain snapshots taking 20GB??

### ISSUE THREAD

**Issue by lucasboss45** [TownyAdvanced/Towny#4142]
**Ask your question as best as you are able:**
Is it normal that towny uses 20GB for it's plot snapshots? The world file is only about 2GB in size with about 30 towns with each about 200 townblocks at least.

**Comment by LlmDl** [comment]
We're storing blockdata and not using minecraft's chunk system (plots don't have to be chunk sized,) so the compression is not there.

**Comment by lucasboss45** [comment]
Is there any chance this could be improved in the future?

**Comment by LlmDl** [comment]
Potentially yes but it is not a high priority.

**Comment by MFredMx** [comment]
What the hell do you mean with not a high priority? It is really bad SE practice to store data like this. You literally stored every block literally. What you should have done at least is to store the blocks as bytes and create a mapping table for the blocks. But the way it’s implemented at the moment it is for the garbage can.

**Comment by LlmDl** [comment]
You can just turn the feature off if you want. If you want to submit a PR to do what you're talking about you are very welcome.

**Comment by LlmDl** [comment]
This will be taken care of eventually. My initial tests showed that zipping them up shrank the size considerably. Also discovered that using the spigot chunk snapshot system essentially created the same (large) size of file, so moving the feature over to using that (and limiting the feature to servers using the 16x16 plot size) is untenable. This will be tracked via a new ticket: https://github.com/TownyAdvanced/Towny/issues/4327
