### ISSUE TITLE
TownyChat is bugged, chat format sometimes stop working 

### ISSUE THREAD

**Issue by Xiri99** [TownyAdvanced/Towny#4143]
### What steps will reproduce the problem?
1. Joining the server
2. Talking in townychat

### What is the expected output?
1. Console error: https://pastebin.com/WyQeEPJB
In-game: https://gyazo.com/085251af696a4758febfa8768e9c646d

Sometimes just switches over after it's been working for them for some time, not only if you join the server, isn't bugged for everyone and just comes out of nothing and sometimes goes away if you rejoin a few times

### What is your Towny version?
Do not say "latest".
Towny: 0.96.2.0
TownyChat: 0.72

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperSpigot-375 (1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/mhmQtnH5
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/3n1a9ngk
3. Your townyperms.yml : https://pastebin.com/xzgby0pG
4. Your log's error : https://pastebin.com/WyQeEPJB

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/QxxYCLL6
7. Your channels.yml : https://pastebin.com/BZeXeeBA

**Comment by LlmDl** [comment]
I am willing to bet the marriagemaster placeholder  %marriagemaster_Status_Heart% is sometimes returning null maybe?

**Comment by LlmDl** [comment]
In your screenshot is it only xxflamedudexx who is not appearing correctly or am I missing something else?

**Comment by Xiri99** [comment]
Just got someone else, have multiple people that have this issue

https://pastebin.com/MzZ24K9b
![afbeelding](https://user-images.githubusercontent.com/64747336/86642472-36b89c00-bfdc-11ea-99e2-8a5df83e49c4.png)

**Comment by Xiri99** [comment]
Never saw the marriagestatus returning null so far, I'll try to remove it from the chat format to see if that fixes the issue

**Comment by Xiri99** [comment]
Works so far, I'll let you know whether it comes back or not, please leave this open for about 24 hours

**Comment by LlmDl** [comment]
Sounds good.
