### ISSUE TITLE
Placeholder request

### ISSUE THREAD

**Issue by LordLeo122** [TownyAdvanced/Towny#4145]
something like %townyadvanced_daily_town_tax% and %townyadvanced_daily_nation_tax% which would return the value of tax within the town or nation.

**Comment by LlmDl** [comment]
To clarify: Is this for the tax towns/nations charge players or for the upkeep that towns/nations pay the server to continue to exist?

**Comment by LordLeo122** [comment]
Charge players, upkeep is already a placeholder.
