### ISSUE TITLE
Suggestion: FlagWar: Failed Attack Cooldown (And Attacker Ratios)

### ISSUE THREAD

**Issue by TheNylox** [TownyAdvanced/Towny#4148]
Hello , i was thinking about a  feature for warflags :

In my server i made a rule that a city can flagwar the same city only 1 time every 2 day (to prevent massive attacks) . Actually i need to check every attack . What about adding a cooldown that manage this ? I mean Nation A got 3 city and want to attack City B . Those 3 city can do only 1 attack (per city) to che enemy City B . Sorry for my bad english i dont know if i explained right .

Another feature can be instead of turn pvp on only in the flagged plot it turn pvp on on the attached plot like a 3x3 chunk

**Comment by TheNylox** [comment]
Oh i miss a thing for the cooldown of warflag . If you win the attack you can attack again . the cooldown start only if you lose

**Comment by Darutan92** [comment]
Nice addition. There are two nations with the same number of citizen, but one consists of several cities, and the other from one city, why the one in which there are several cities can attack several chunks at once (according to the number of cities included in it)? This introduces an imbalance. Players on my server use this and I had to limit it by writing in the rules. I would like it to be implemented mechanically.

The offer for the PVP zone in 3x3 is also good.

**Comment by TheFlagCourier** [comment]
This issue has been moved to the above linked ticket.
