### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by YuseiEleven** [TownyAdvanced/Towny#4149]
**Ask your question as best as you are able:**
Hello, is towny language file, when i change the prefix, nothing change, even after a reload of the language file, even after a restart. I still have the [Towny] tag and the [TownyChat] tag, im using the last version in 1.16.1. Is it a bug? 
Here is the line in the language file (default_towny_prefix: '&6[Ville]'), everything else is by default for the plugin.

**Comment by LlmDl** [comment]
Make sure you're renaming your language file to something new and setting that name in the towny config.yml. Otherwise Towny will overwrite your changes.
