### ISSUE TITLE
Question: Localchat format + Wars settings?

### ISSUE THREAD

**Issue by SiphMC** [TownyAdvanced/Towny#4150]
Hello, I actually got 3 questions about your plugin.

**first one:** 
I can't find out where do I change the local chat format? In my ChatConfig.yml I can see: global, town,nation, alliance and default, but there is missing LocalChat, I tried to add it but it didn't work. Do I need to use another plugin just for it? If yes, do you have any suggestion?

**second one:**
I would like to add immunity to towns, I saw it in a towny server. I didn't see anything in your config files about it. Am I just blind? If nope, can I know what plugin should I use to complete the plugin feature?

**third one:**
I would like to put colored banner as a item to start a siege, I saw a oak_fence, how can I add every colored banner as a siege item?

Thanks for your time and for this plugin! :)

**Comment by LlmDl** [comment]
1: local is of GLOBAL type, as seen in the channels.yml

2: what do you mean by immunity

3: Seige war is not part of Towny (yet).

**Comment by SiphMC** [comment]
@LlmDl 
1: OMG I didn't think about it, thank you so much, I'll change it later!

2: by immunity I mean: Make your town immune to any siege

3: Do you know what plugin I should use to make it enable? I have been playing on a lot of server and they all had a siege plugin 0.0

**Comment by LlmDl** [comment]
There is a siege war pull request here but it hasn't been merged yet. The test jar is linked in the Pull Request.

**Comment by SiphMC** [comment]
Perfect I'll test your chat config and try it.

I just tried and it did fail, but I guess I'll review it in a few hours!

**Comment by SiphMC** [comment]
Alright, everything is working! I'll close that ticket! :)

Thanks for your time!
