### ISSUE TITLE
/town commands not working

### ISSUE THREAD

**Issue by MinervaMinecraft** [TownyAdvanced/Towny#4155]
### What steps will reproduce the problem?
1. Execute /town --> no result, error in 
2. Execute /town claim --> "null" msg
3. Execute /town here, within the owned town borders --> "null" msg

NB: "/town deposit" does work, so it does not affect every "/town" command 

### What is the expected output?
1.  info about the town
2. claiming a plot
3.  display info on the town

### What is your Towny version?
Do not say "latest".
0.96.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper: 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/tNrJYnZR

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/kjnSQPNJ

3. Your townyperms.yml :
https://pastebin.com/4X3ZkQ6E

4. Your log's error : 
- for /town command: see 1
- for /town claim & /town here command: just a "null" msg from towny in the game

(optional) If this is to do with permissions, 
5. Your permissions file 
I'm using Luckperms, I have added only towny.admin.* for my admin groups and towny.wild.* enabled

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This is happening because you are missing a couple Nation_levels.

You need one at numResidents: 0 and another at numResidents: 1.
