### ISSUE TITLE
User not receiving invite/not in a town

### ISSUE THREAD

**Issue by austin652** [TownyAdvanced/Towny#4157]
### What steps will reproduce the problem?
1. /towny invite user (in this case "stry")
2. /ta town name add user
3. /res user ("stry")
4. /ta delete user

### What is the expected output?
1. user is sent an invite to in chat to accept or decline
2. user is added to the defined town
3. towny profile displayed with time stamps
4. the user is deleted (if offline or online it says "user is Online or is an NPC.")

### What is your Towny version?
Do not say "latest".
96.2.3

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperSpigot 1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/qm2j2VJM
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/xfF0HmLg
3. Your townyperms.yml :
https://pastebin.com/CC3ui7s2
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

This is probably a very specific issue but after several user reconnects, restarts, manual mySQL resident deletes I can't find a solution to this problem myself and wonder if it might have something to do with their ign being only 4 characters.

![2020-07-12_12 37 13](https://user-images.githubusercontent.com/19559876/87252690-1c9b1580-c443-11ea-8759-22fb232b580d.png)
![2020-07-12_12 39 54](https://user-images.githubusercontent.com/19559876/87252691-1d33ac00-c443-11ea-850a-bbcbeaabe20d.png)
![2020-07-12_13 18 02](https://user-images.githubusercontent.com/19559876/87252692-1d33ac00-c443-11ea-8856-bd0ee3c2c3b5.png)
![2020-07-12_13 18 04](https://user-images.githubusercontent.com/19559876/87252693-1dcc4280-c443-11ea-82b3-a601bd81d964.png)

**Comment by LlmDl** [comment]
So a mayor is not able to /t invite stry?
But you can use the /ta town NAME add stry.

Can you show me the mysql entry for stry?

**Comment by austin652** [comment]
The mayor can invite stry, however stry doesn't receive the invite and towny lists stry as not in a town, to be more clear the town lists stry as in the town but the player is not considered in the town. the sql shows them in a town but in-game /res NAME defines them as not in a town
![mysql](https://user-images.githubusercontent.com/19559876/87253077-4144bc80-c446-11ea-967f-c55f1cf3da88.png)

**Comment by LlmDl** [comment]
they're marked as being an NPC, which is why they cannot be /ta deleted, probably also why they aren't getting an invite.

**Comment by austin652** [comment]
so if i switch that from 1 to 0 that should possibly fix it?

**Comment by LlmDl** [comment]
I would imagine yes.

**Comment by austin652** [comment]
I changed isNPC from 1 to 0 and restarted, but it changed back to 1

**Comment by LlmDl** [comment]
That is very strange.

**Comment by austin652** [comment]
Sorry for the super late response. Just tried to change isNPC from 1 to 0 while the server was offline and when I turned the server on it was marked with 1 again. My server is running Towny 0.96.2.9 on PaperSpigot 1.16.1 #128

**Comment by LlmDl** [comment]
That doesn't really make sense. Do you have a plugin that would be doing this?

**Comment by austin652** [comment]
Citizens maybe?

**Comment by LlmDl** [comment]
Doubtful. Stop the server and disable everything except vault, your economy plugin and Towny. Make the database change and then start the server. See if it goes back to 1.

**Comment by austin652** [comment]
Disabled everything except vault, my economy plugin and Towny and made the change while it was off and it went back to 1 still

**Comment by LlmDl** [comment]
Sounds like w/e you're doing to edit your database is not editing the database.

**Comment by austin652** [comment]
I was using MySql workbench to edit it before and after doing it directly from phpMyAdmin i'm still getting the same result

**Comment by LlmDl** [comment]
I'd say convert to flatfile using the instructions on the How Towny Works wikipage, flatfile is more reliable in general. I have never heard of anyone with this issue using either mysql or flatfile, but I believe it will stop if you're using files (unless something else is interfering.)

**Comment by austin652** [comment]
Converted to flatfile using the methods that were on the wiki, then turned off the server like before, went into the user file changed NPC:True to false and turned the server on it changed back to true

**Comment by LlmDl** [comment]
The only way Towny does that is if someone is using the /ta toggle npc {resident} command on them.

**Comment by austin652** [comment]
I'm the only one on after these restarts and I don't do the command and the user doesn't have access to it

**Comment by LlmDl** [comment]
OK, still incredibly strange. Probably not Towny causing it, since it will only set the NPC value on load of the database, or when that command is run.

**Comment by austin652** [comment]
Would it have to do with Essentials? because that's my economy plugin, I had Essentials,EssentialsChat,EssentialsSpawn,Vault and Towny running that time you said economy, vault and towny

**Comment by LlmDl** [comment]
Unlikely.

**Comment by austin652** [comment]
On a fresh server with only towny default config, essentials default config and vault the problem still exists, the person is marked as an npc right away when their profile is created for the first time

**Comment by LlmDl** [comment]
Sorry for the late response, I have been on holiday.

If you want to try having them join a test server of mine, we can test it on my end.

**Comment by austin652** [comment]
No problem. We can try that

**Comment by austin652** [comment]
Sorry if it's posted somewhere obvious but I can't find anything about a test server.

**Comment by LlmDl** [comment]
Hit me up on the discord and I can give you teh address.
