### ISSUE TITLE
TownyChat not using RGB colors from perms plugin

### ISSUE THREAD

**Issue by winnipeg21** [TownyAdvanced/Towny#4159]
### What steps will reproduce the problem?
1. Use any of these variables for chat formatting

- {permuserprefix}
- {permgroupprefix}
- {permprefix}
- or any vault prefixes

2. Latest Towny and Towny Chat builds
(what I get https://s.pingu.ga/OxHpt)

### What is the expected output?
1. To have `Town Tag - Prefix - Surname - Username : Message`

### What is your Towny version?
Do not say "latest".
Towny - 0.96.2.3
TownyChat - .73

### What is your spigot/craftbukkit version?
Do not say "latest".

Paper - #89

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/YkquGLj7
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/NzC7KmqV (towny)
3. Your townyperms.yml : https://pastebin.com/8cEuVJDy
4. Your log's error : No error really?

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/hwCBSuMC

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/r5hUeRYc
7. Your channels.yml : Default

**Comment by suneettipirneni** [comment]
Whats the format of the rgb color in your perm plugin

**Comment by winnipeg21** [comment]
`&#ff0000 ` that kind of format

**Comment by suneettipirneni** [comment]
[TownyChat-0.73.jar.zip](https://github.com/TownyAdvanced/Towny/files/4909268/TownyChat-0.73.jar.zip)
Can you try this jar and see if it fixes it?

**Comment by winnipeg21** [comment]
Still the same issue with the text not being colored. 

https://s.pingu.ga/EjEtV

**Comment by suneettipirneni** [comment]
Sorry that was the wrong one, try this one:
[TownyChat-0.73.jar.zip](https://github.com/TownyAdvanced/Towny/files/4909269/TownyChat-0.73.jar.zip)

**Comment by winnipeg21** [comment]
lmao will try

**Comment by winnipeg21** [comment]
Same issue sadly

**Comment by suneettipirneni** [comment]
Are the messages themselves working with hex colors?

**Comment by winnipeg21** [comment]
With that last jar you gave me? No

**Comment by suneettipirneni** [comment]
[TownyChat-0.73.jar.zip](https://github.com/TownyAdvanced/Towny/files/4909498/TownyChat-0.73.jar.zip)
try this one

**Comment by winnipeg21** [comment]
So the prefix formatting is working.. But when you add `&#ff0000` or any hex code, that hex doesn't work

**Comment by suneettipirneni** [comment]
Like it doesn't show in the message field?

**Comment by winnipeg21** [comment]
So if I do something like:
`{nationtagoverride}{towntagoverride}{permgroupprefix}{surname}{playername}&8: &#ff0000 {msg}`
I get:
https://s.pingu.ga/kik8G

**Comment by suneettipirneni** [comment]
Alright now try this:
[TownyChat-0.73.jar.zip](https://github.com/TownyAdvanced/Towny/files/4909977/TownyChat-0.73.jar.zip)

**Comment by winnipeg21** [comment]
Eh GG it works perfectly. Thanks a lot man!

**Comment by suneettipirneni** [comment]
Ok nice, you can keep using that jar we'll probably have a formal update tommorow.

**Comment by winnipeg21** [comment]
Ight you're the goat man!

**Comment by winnipeg21** [comment]
Another thing to add.. Hex color doesn't want to work in the language file and the language file isn't updating the help commands messages when you do `/townyadmin reload all` or `/townyadmin reload lang`

**Comment by suneettipirneni** [comment]
What do you mean by help commands, and are you saying it's not paring the hex from the Lang file when you add it in?

**Comment by LlmDl** [comment]
Anything about the language files should be tracked in a separate ticket with clear instructions for what should be fixed. This ticket has already got a PR that will close it @winnipeg21.

**Comment by winnipeg21** [comment]
> What do you mean by help commands, and are you saying it's not paring the hex from the Lang file when you add it in?

Ya the language file isn't parsing the hex

**Comment by winnipeg21** [comment]
> Anything about the language files should be tracked in a separate ticket with clear instructions for what should be fixed. This ticket has already got a PR that will close it @winnipeg21.

Y'all I'll do a little more testing and might make a ticket. Thanks for the heads up on that!

**Comment by winnipeg21** [comment]
Not to be rude, but be nice to get this issue back to light. Suneettipirneni fixed it but it seems the pr was closed.

**Comment by Momshroom** [comment]
If you mean this PR: https://github.com/TownyAdvanced/Towny/pull/4177
It says it was merged.

**Comment by winnipeg21** [comment]
That's not the one linked to this issue I believe. The one linked says it's been closed.
