### ISSUE TITLE
Question: How to put town prefix before a name

### ISSUE THREAD

**Issue by SiphMC** [TownyAdvanced/Towny#4162]
**Ask your question as best as you are able:**
Hello, how can I put the names of town and nation as a prefix before the name of a guy?
Is it TownyNameUpdater?

Here a screenshot
![PREFIX](https://user-images.githubusercontent.com/67846476/87267340-6876aa80-c495-11ea-9361-c4e05cc105c1.png)

If not, can you tell me how could I reach wht I need?

Thanks again mates! :)

**Comment by LlmDl** [comment]
TownyChat does that.
