### ISSUE TITLE
Question: Show the name of town in the nation/town on a player

### ISSUE THREAD

**Issue by SiphMC** [TownyAdvanced/Towny#4163]
**Ask your question as best as you are able:**

Hello, I had opened a question here, but it was closed... (#4162). I need to know how to show the name of a town and nation before the name of a player.

**I'm not talking about chat and tablist, I'm talking about in game, when you see a player. I would like that just by looking at him, you can see his town and nation.**

If towny can't do this, what plugins should I use?

![PREFIX](https://user-images.githubusercontent.com/67846476/87351650-bcca6a80-c527-11ea-83d3-35f0085bed62.png)

Sorry for reposting... 

Please don't close it, I'll close it by myself when I'll have considered it!

**Comment by LlmDl** [comment]
You mean hovering above the player? There's a plugin that does that using placeholders, which you can input Towny's placeholders as found on the wiki.

**Comment by SiphMC** [comment]
Alright thanks, closing the ticket! :)
