### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by TheGoodMan2006** [TownyAdvanced/Towny#4164]
**Ask your question as best as you are able:**
"Towny is preventing you from logging in using this account name"
How can this be disabled?
5 minutes later all was right

**Comment by LlmDl** [comment]
Accounts that match the names of the  towny war-spoils/towny closed-economy account/NPC accounts are not able to log in.

**Comment by TheGoodMan2006** [comment]
Thank you. My nick was NPC01)
