### ISSUE TITLE
Towny doesn't allow payments of 0 to proceed

### ISSUE THREAD

**Issue by klugemonkey** [TownyAdvanced/Towny#4165]
Towny doesn't allow payments of 0 to proceed, so can not sell a plot for free.

master: 7f8a18c 
com.palmergames.bukkit.towny.object.EconomyAccount:65

```
	boolean _pay(double amount) throws EconomyException {
		if (canPayFromHoldings(amount)) {
			if (TownyEconomyHandler.isActive())
				if (amount > 0) {      // <-- HERE
					return TownyEconomyHandler.subtract(getName(), amount, getBukkitWorld());
				} else {
					return TownyEconomyHandler.add(getName(), Math.abs(amount), getBukkitWorld());
				}
		}
		return false;
	}
```

**Comment by LlmDl** [comment]
I've never had an issue using /plot fs 0, then /plot claim but I cannot say I've tested that very recently. You've tested this in game using one of the payments?

**Comment by LlmDl** [comment]
I will need a response within 6 days or this will be closed.
