### ISSUE TITLE
Shulkerboxes not being returned to player inventory when player attempts to place them in an area where they don't have permission to build

### ISSUE THREAD

**Issue by Inceris** [TownyAdvanced/Towny#4166]
Shulkerboxes not being returned to player inventory when player attempts to place them in an area where they don't have permission to build. This issue is intermittent. It occurred a few times and then once more after the player rebooted their client, and then stopped.

### What steps will reproduce the problem?
A player attempts to place a shulkerbox in an area that they haven't been granted permission to place blocks by the town owner.

### What is the expected output?
The shulkerbox returns to the player's inventory as normal.

### What is your Towny version?
0.96.2.2

### What is your spigot/craftbukkit version?
Paperspigot 1.16.1 build #91

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/cXbLxy7N
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/S4EaicEf
3. Your townyperms.yml : https://pastebin.com/HngybSCp
4. Your log's error : Not Applicable - No log output at the time of the error

**Comment by LlmDl** [comment]
Them losing any block from lack of permissions would be a client-side visual glitch that would fix itself by relogging. Towny isn't putting the shulker box anywhere because it technically never leaves their inventory. I'm not sure what else to tell you.

**Comment by Inceris** [comment]
It's certainly not a visual glitch. That much I can confirm. As I said, this player had restarted their client entirely and was still missing their shulkerboxes, and using invsee, I watched them disappear

**Comment by LlmDl** [comment]
Just tested it out, it acts exactly as I said. You may have another plugin interfering.
