### ISSUE TITLE
Suggestion: WorldSetting for disabling mobs in wild, while allowing towns to turn them on.

### ISSUE THREAD

**Issue by jackstrosahl** [TownyAdvanced/Towny#4169]
Basically, the same as the toggle for plots or towns not having monster spawns, but in wild.  It would be a config option that by default allows the spawns.  I think separately there could be a config option for disabling passive spawns.

**Comment by LlmDl** [comment]
In this concept, would you still want there to be mobs spawnable in towns?

**Comment by jackstrosahl** [comment]
Yes, these config options would only disable monster spawns or passive mob spawns in wild.
