### ISSUE TITLE
Question: How to unlock a plot?

### ISSUE THREAD

**Issue by FruityShoemaker** [TownyAdvanced/Towny#4172]
I try to break a block in a plot that isn't the original town block but is still claimed, it doesn't let me break the block and says this plot is locked, how do I fix this?

**Comment by LlmDl** [comment]
The plot is making a snapshot used in the revert-on-unclaim feature. It will unlock when that is finished. If it does not you can delete the snapshot_queue.txt file and /ta reload db.
