### ISSUE TITLE
Certain switch perms should probably actually be destroy perms

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#4176]
**Background:**

We are using Towny to replace chest-locking plugins.  The way we're doing this, is we're adding chests, barrels, etc to the `switch_ids` field in `Towny/settings/config.yml`, and defaulting resident-owned plots to allowing friends to switch.  We also default towns to allowing switching for residents and nation members.

This works well, since players can choose whom to allow access to their chests by whom they add to their friendslist;  and storage on town-owned plots is always community storage.  Far simpler and easier than LWC or Lockette;  and it even "unlocks" the chests and doors of towns that cease to exist.

Additionally, trapped chests can always be opened by anyone;  and pressure-plates/buttons/levers can always be toggled by anyone.  The latter allows the creation of effectively public doorways.

**Issues:**

However, `switch_ids` doesn't just contain chests and doors:  it also contains things like redstone repeaters, comparators, etc.  This means that anyone on your friends list can *also* switch those things, in addition to chests and doors.  This isn't ideal, to say the least;  both because it violates the principle of least privilege, and because friends are able to tinker with redstone contraptions they should not have access to.  

This isn't a *huge* deal for residential plots, since you probably trust the people you've added as "friends" to not do that.  But in town-owned plots, things are a little different.  Town owners really don't want random townies to be able to switch their redstone contraptions.

One way around this is to protect such devices with iron doors, and only add a lever or button to open the door when the door is in use.  This would allow access only to the builder, so long as Chorus Fruits remain blocked in `item_use_ids`;  but it's not ideal.

**Request:**

If Towny had some way to separate some switches from others, then none of this would be an issue.  Access to chests and doors could be granted without also granting access to other switches.

1. One way to do this is by implementing two `switch_ids` fields in `Towny/settings/config.yml`;  but this would require modifying the GUI, and divides the same behaviour into two artificial categories.

2. Another option is to add a field called "`force_disable_switch_ids`".  Anything added to this field would never be enabled, even when permission is given to switch.  However, this would prevent some redstone collaboration.

3. A third option, and the one I currently like best, is to add a field called "`build_switch_ids`".  Any switchable blocks added to this field would only be switchable if you have *build* permissions for the plot in-question.  This seems to resolve the issue without causing others;  but it may be trickier to code.  Logically, switching redstone repeaters should always have come with build permissions, and not the same permissions you give your friends to open chests.

You may have better ideas for a solution, though.  Thanks for taking the time to read this all the way through.  Thoughts?

**Comment by KarlOfDuty** [comment]
I think seperating switches from containers would be something many players would appreciate. The ability for others to use redstone but not open chests is something our newer players ask about regularly.

**Comment by MilesBHuff** [comment]
@KarlOfDuty

I think what you may want is to make buttons/levers/pressureplates public by removing them from `switch_ids` in `Towny/settings/config.yml`.

This ticket is more-specifically about the other kinds of switching, like switching repeaters, comparators, etc, which you typically do not want to allow even when you allow, eg, levers.

**Comment by KarlOfDuty** [comment]
Ah I guess we are talking about different issues then. I kinda feel like what you are suggesting is the more complicated way of doing things though.

**Comment by LlmDl** [comment]
This sort of ties into a request Karl made, where some of our item_use options including buckets, should more like be considered build tests. (Placing a water bucket should be a build water test, not a item_use bucket test.) I could see editing redstone repeaters/comparators becoming destroy tests, rather than switch tests.

Keeping things as simple as possible, I think the separation of switches and containers would be one solution.

As for the OPs requests. 
1) I'm not exactly clear on what you mean here. You don't describe either category and there's no GUI in Towny.
2) This is overly complicated I think.
3) This one makes a bit more sense but still complicates things for the end users. I believe making things like editing redstone machines into destroy tests would satisfy the third request, no?

**Comment by MilesBHuff** [comment]
> This sort of ties into a request Karl made, where some of our item_use options including buckets, should more like be considered build tests. (Placing a water bucket should be a build water test, not a item_use bucket test.) I could see editing redstone repeaters/comparators becoming destroy tests, rather than switch tests.

This is exactly option 3, without the ability to configure.  I would be quite happy with this.

1. By "GUI", I'm referring to the various HUDs the mod provides, specifically `/plot perm hud`.  "GUI" isn't the most-accurate term, I suppose, since they're text-based interfaces.

2. Yeah, I'm not a fan of it either.

3. Yes, integrating redstone apparatuses such as repeaters and comparators into build/destroy test would be perfect.  Hopefully things like levers, buttons, and pressure plates could be left-out, though.

**Comment by MilesBHuff** [comment]
Here are the blocks that should probably be under build/destroy permissions, rather than switch permissions:
```NOTE_BLOCK,BEACON,COMPARATOR,REPEATER,COMMAND_BLOCK_MINECART,TNT_MINECART,DAYLIGHT_DETECTOR,DRAGON_EGG,ITEM_FRAME,POTTED_ACACIA_SAPLING,POTTED_ALLIUM,POTTED_AZURE_BLUET,POTTED_BAMBOO,POTTED_BIRCH_SAPLING,POTTED_BLUE_ORCHID,POTTED_BROWN_MUSHROOM,POTTED_CACTUS,POTTED_CORNFLOWER,POTTED_DANDELION,POTTED_DARK_OAK_SAPLING,POTTED_DEAD_BUSH,POTTED_FERN,POTTED_JUNGLE_SAPLING,POTTED_LILY_OF_THE_VALLEY,POTTED_OAK_SAPLING,POTTED_ORANGE_TULIP,POTTED_OXEYE_DAISY,POTTED_PINK_TULIP,POTTED_POPPY,POTTED_RED_MUSHROOM,POTTED_RED_TULIP,POTTED_SPRUCE_SAPLING,POTTED_WHITE_TULIP,POTTED_WITHER_ROSE```

**Comment by KarlOfDuty** [comment]
How can interacting with a note block be a destructive action?

**Comment by Momshroom** [comment]
It changes the sound.   Now imagine your town spawn plays a song when you land on it...

**Comment by KarlOfDuty** [comment]
That's not destructive? It just switches the settings, it doesn't destroy anything like using a bucket on water/lava does.

**Comment by Momshroom** [comment]
I’ve had players invest huge amounts of time programming long songs into noteblock chains.   Changing that to play a different song (or random notes) definitely would seem destructive to me.   That said, I’ve not had a player do that who wasn’t smart enough to not have the noteBlocks in a plot that had switch off. I was just answering how it could be destructive.   If we’re counting changing repeater speeds as destructive, this seems it would count as well.  If not, just build most of your redstone on plots that have switch turned off

**Comment by KarlOfDuty** [comment]
Well I wouldn't call any of those destructive as no blocks or items are destroyed.

**Comment by MilesBHuff** [comment]
The blocks may not be destroyed, but the song is.  Players can grief the song, ruining hours of work in an instant.  That is by definition destructive.

**Comment by LlmDl** [comment]
- [x] Potted Plants
- [x] Redstone Interactables ("COMPARATOR","REPEATER","DAYLIGHT_DETECTOR")
- [ ] Noteblocks
- [ ] Beacon
- [ ] ItemFrame
- [ ] Command Minecart, Command Block
- [ ] TNT Minecart
- [ ] Dragon Egg
