### ISSUE TITLE
Suggestion: New taxes config values

### ISSUE THREAD

**Issue by 3meraldK** [TownyAdvanced/Towny#4178]
**Please explain your feature request to the best of your abilities:**
I don't want citizens and cities being kicked from city/nation because they cannot afford taxes. I don't want to decompile Towny and delete resident / city removing part and compiling it again either, it would take long of time. So I propose to add those new config values in taxes section called:

- kick_resident_cannot_afford_tax: boolean #When set to true and resident cannot afford town taxes then is being kicked from his town.
- kick_city_cannot_afford_tax: boolean #When set to true and city cannot afford nation taxes then is being kicked from its nation.

It'd be really helpful guys, I appreciate that!

**Comment by LlmDl** [comment]
Why would anyone pay tax again if this was used? Just turn off taxation entirely...

**Comment by 3meraldK** [comment]
> Why would anyone pay tax again if this was used? Just turn off taxation entirely...

Nah, example
> player M sets taxes
> player R stopped paying them
> player M uses custom punishments etc.

The same with city
and my server community proposed it also to do that
