### ISSUE TITLE
When I do /t spawn (anytown) or /t spawn nothing happens. Nothing shows up in my console it's as if I never did any command.

### ISSUE THREAD

**Issue by HyenaGodKing** [TownyAdvanced/Towny#4184]
### What steps will reproduce the problem?
1.
2.
3.

### What is the expected output?
1. When I do /t spawn I want to teleport to my town
2. When I do /t spawn (town) I want to teleport to a specific town.

### What is your Towny version?
Towny-0.96.1.9

### What is your spigot/craftbukkit version?
paper-375.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/wn79MW3i
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/mpKmtZYA
3. Your townyperms.yml : https://pastebin.com/JCUNNFJg
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You should update your Towny to at least 0.96.2.0 and retest. If that fails, try using something other than tuinity.

**Comment by HyenaGodKing** [comment]
> You should update your Towny to at least 0.96.2.0 and retest. If that fails, try using something other than tuinity.

I did both and still doesn't work for me.

**Comment by LlmDl** [comment]
Can you show me your new startup using 0.96.2.0?

**Comment by HyenaGodKing** [comment]
https://pastebin.com/EFNtT7Zt Here. It's still not working

**Comment by LlmDl** [comment]
In your other ticket I pointed out that you did not give the right node for /town spawn.
