### ISSUE TITLE
Question: Player price_death doesn't work?

### ISSUE THREAD

**Issue by SiphMC** [TownyAdvanced/Towny#4185]
Hello, when someone die on my server, he doesn't lose 20% of his cash, he loses 0,20$, Do you know what I did wrong in this config?

`  death:
    # Either fixed or percentage.
    # For percentage 1.0 would be 100%. 0.01 would be 1%.
    price_death_type: percentage
    # A maximum amount paid out by a resident from their personal holdings for percentage deaths.
    # Set to 0 to have no cap.
    percentage_cap: '0.20'
    # If True, only charge death prices for pvp kills. Not monsters/environmental deaths.
    price_death_pvp_only: 'true'
 
    price_death: '1.0'
 
    price_death_town: '0.0'
 
    price_death_nation: '0.0'
`

**Comment by LlmDl** [comment]
Putting the price_death to 1.0 and setting the type to percentage should cost 100% of their balance. The percentage_cap would then make it only 20% of their holdings.

**Comment by SiphMC** [comment]
So if I want them to lose 20% of their money, what will I have to do? 0.0

**Comment by LlmDl** [comment]
set the percentage_cap to 0 and the price_death to 0.2
