### ISSUE TITLE
TownyChat Broke at the Latest Towny Build

### ISSUE THREAD

**Issue by Zacky26** [TownyAdvanced/Towny#4187]
### What steps will reproduce the problem?
1. Just use the new towny release.
2. Try /tc or any other channel
3. The chat format doesn't work. Additionally, everyone can see their messages. 

### What is the expected output?
1. For it to work properly, obviously, not the broken one XD

### What is your Towny version?
0.96.2.5

### What is your spigot/craftbukkit version?
Paper-99

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/zLeUimAH
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/fzt4N6c5
3. Your townyperms.yml : Not applicable
4. Your log's error : https://pastebin.com/hWEndSYA

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/s8X051dq
7. Your channels.yml : https://pastebin.com/8YciXvjk

**Comment by LlmDl** [comment]
This is fixed as of TownyChat 0.74
