### ISSUE TITLE
How do I give a group access to /t spawn (town name) within the nation

### ISSUE THREAD

**Issue by HyenaGodKing** [TownyAdvanced/Towny#4190]
### What steps will reproduce the problem?
1. When a player in the group "Soldier" does /t spawn (town b) even through their apart of town a it says they dont have access to that command.
2. I set it in the config to disable town travel in your nation or outside your nation I'm just wondering if there is a permission node to allow them to travel despite whats disabled in the config.
### What is the expected output?
1. I want any group I assign to be able to travel to any town within their nation meanwhile every other group by default can't

### What is your Towny version?
Towny-0.96.1.9

### What is your spigot/craftbukkit version?
paper-375.jar

Please use Pastebin.com to link the following files:
Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

Your full server startup from the logs\latest.log : https://pastebin.com/EFNtT7Zt
Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/mpKmtZYA
Your townyperms.yml : https://pastebin.com/JCUNNFJg
Your log's error :

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/Py3PwaW6

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by HyenaGodKing** [comment]
When I give the people the townyadmin perms it still doesn't work so thats why I think it's bugged.

**Comment by LlmDl** [comment]
So going over your townyperms.yml you give teh default town members towny.town.spawn which isn't a node at all. They need `- towny.town.spawn.town` to be able to use their own town's spawn.

You did not include your permission plugin's file so I do now know what you've done to the Soldier group.

**Comment by LlmDl** [comment]
Furthermore: 

```
  # Allow regular residents to use /town spawn [town] to other towns in your nation.
  # Valid values are: true, false, war, peace
  # When war or peace is set, it is only possible to teleport to the town,
  # when there is a war or peace.
  allow_town_spawn_travel_nation: 'false'
```
because this is false no one is allowed to travel to other towns in their nation.

**Comment by HyenaGodKing** [comment]
But I don't want anyone in the default group  having access to teleporting to other towns spawn. I just want to make it so that I can set certain groups to be able to do /t spawn to other towns within their nation

**Comment by LlmDl** [comment]
Yes, you need to enable the spawning type in the config, but only give the group you want the permission node for spawning to their nation's towns.
