### ISSUE TITLE
Dynmap-Towny v0.81 - No towny ifo appears on the Dynamp

### ISSUE THREAD

**Issue by cobrex1** [TownyAdvanced/Towny#4191]
### What steps will reproduce the problem?
1. Have Towny 0.96.2.5 installed
2. Have Dynmap v3.0 snapshot installed (dev called it this as it was a quick fix)
3. Have Dynmap-Towny v0.81 installed

### What is the expected output?
1. Dynmap render with towns and nations. However, the map is just blank of towns, town icons, town shading, nations and nation shading. All gone.

### What is your Towny version?
as above, 0.96.2.5, towny-dynmap 0.81 and dynmap v3.0 snapshop

### What is your spigot/craftbukkit version?
Paper 1.15.1 #379

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log :
https://hastebin.com/ayonuyegol.md

2. Your Towny config.yml (if using MySQL please remove password,) :
https://hastebin.com/ajacuceyay.coffeescript

3. Your townyperms.yml :

4. Your log's error : 
Above

**Comment by suneettipirneni** [comment]
Can you try this jar and see if it works?
[Dynmap-Towny-0.81.jar.zip](https://github.com/TownyAdvanced/Towny/files/4944420/Dynmap-Towny-0.81.jar.zip)

**Comment by cobrex1** [comment]
Yup, happy to give that a go

**Comment by cobrex1** [comment]
no change - 
https://hastebin.com/pidaleneqi.md

**Comment by suneettipirneni** [comment]
I'm 99% this should work.
[Dynmap-Towny-0.81.jar.zip](https://github.com/TownyAdvanced/Towny/files/4944503/Dynmap-Towny-0.81.jar.zip)

**Comment by cobrex1** [comment]
Perfect, thank you - that fixed it - tomorrow I will update to the 1.16 compatible version and make sure it works with that too.

Thank you Siris :)

**Comment by LlmDl** [comment]
Download link has been fixed on the dynmap-towny release page.
