### ISSUE TITLE
Nether Portals Dont Work inside Towns

### ISSUE THREAD

**Issue by Drainer2002** [TownyAdvanced/Towny#4197]
What steps will reproduce the problem?
The fire bypass wasn't working for nether portals.
I have to do /plot toggle fire   so that I can open up a Nether Portal on a plot

What is the expected output?
Nether Portals can be opened using a flint without toggle the perms for fire 

What is your Towny version?
Towny Version 0.96.2.5 for MC 1.14./1.15./1.16.*

What is your spigot/craftbukkit version?
paper 1.16.1

Please use Pastebin.com
config.townyperms.zip

to link the following files:

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

Your full server startup from the logs\latest.log :
Your Towny config.yml (if using MySQL please remove password,) :
Your townyperms.yml :
Your log's error :
(optional) If this is to do with permissions,
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by suneettipirneni** [comment]
You literally skipped the entire form.
