### ISSUE TITLE
Towny Chat isnt like Normal. It is Fully White

### ISSUE THREAD

**Issue by Drainer2002** [TownyAdvanced/Towny#4198]
### What steps will reproduce the problem?
1. Towny Chat is not like normal.
2.  It is Fully White when you approach to a town

### What is the expected output?
1. Like the Towny Chat will be gold
2. red for pvp

### What is your Towny version?
Towny Version 0.96.2.5 for MC 1.14.*/1.15.*/1.16.*

### What is your spigot/craftbukkit version?
paper 1.16.1

### Please use Pastebin.com
![2020-07-20_20 26 41](https://user-images.githubusercontent.com/67148013/87972114-0c340c00-cacf-11ea-9990-f15d2cf502b4.png)

 to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/14AmW4zL
2. Your Towny config.yml (if using MySQL please remove password,) :   https://pastebin.com/GxMuHZhs
3. Your townyperms.yml : https://pastebin.com/hccgYxzT
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Skipped the form again...

**Comment by Drainer2002** [comment]
How ?

**Comment by LlmDl** [comment]
We spoke about the outcome of this on the discord, I was not able to reproduce and said it was likely another plugin interfering.
