### ISSUE TITLE
Question: Why player can't do /ac?

### ISSUE THREAD

**Issue by SiphMC** [TownyAdvanced/Towny#4200]
**Ask your question as best as you are able:**
Hello, it seems like I can't do /ac on my server. I tries to go in /admin.

I use the version 0.96.2.0.

**Chatconfig:**
https://pastebin.com/iYwf1W9s

**Townyperms:**
https://pastebin.com/x7ifh3KX

**Channels:**
https://pastebin.com/CVysF70v

**Problem screenshot:**
https://gyazo.com/9972bca0d274cc94e8126f4ea2cf680a

**Comment by LlmDl** [comment]
I dunno, maybe some other plugin overrides it? I know your screenshot shows no auto complete, what happens when they do /ac and press enter?

**Comment by SiphMC** [comment]
For a player, it's the screenshot that I sent you, but when I do it on my OP account, it opens the admin chat?

**Comment by LlmDl** [comment]
Sounds like you have another plugin adding an admin chat (towny's is either /a or /admin,) and it has determined your players aren't allowed to use it.

**Comment by SiphMC** [comment]
You are right, but they're major plugin. Can I change the command through the config to like /alc? Or do I need to rewrite that part of code in the source?

**Comment by LlmDl** [comment]
You can set the command to w/e you want in the channels.yml

**Comment by SiphMC** [comment]
Or is there any way I can override the other plugin with /ac?

**Comment by SiphMC** [comment]
it works, thanks!
