### ISSUE TITLE
Town chat channels showing in dynmap

### ISSUE THREAD

**Issue by Jimeneznet** [TownyAdvanced/Towny#4201]
### What steps will reproduce the problem?
1. Use dynmap
2. Join a town channel
3. Speak

### What is the expected output?
1. Nothing. Town channels should not show up in dynmap.

### What is your Towny version?
latest.
jk 0.96.2

### What is your spigot/craftbukkit version?
git-Spigot-00287a20-7560f5f
API version 1.16.1-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
https://pastebin.com/7cLsyRPj
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/4RbXmNUR
3. Your townyperms.yml :
https://pastebin.com/ZSt3Yspd
4. Your log's error : 
- None - See above
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://pastebin.com/qpvbA63m
7. Your channels.yml :
https://pastebin.com/FmzAmApV

**Comment by LlmDl** [comment]
Please supply your dynmap-towny config also.

**Comment by LlmDl** [comment]
I see you do not have dynmap-towny.jar. [Getting it](https://github.com/TownyAdvanced/Dynmap-Towny/releases/tag/0.80) will allow you to stop chat from appearing on the webpage.

**Comment by Jimeneznet** [comment]
I will try. And edit once done.

**Comment by Samkist** [comment]
I have both of these jars and I still have this issue?

**Comment by LlmDl** [comment]
@Samkist file a new ticket, don't skip the form.
