### ISSUE TITLE
Suggestion: Allow lighting soul sand on fire when lighters/fire-spread is disabled

### ISSUE THREAD

**Issue by viveleroi** [TownyAdvanced/Towny#4204]
**Please explain your feature request to the best of your abilities:**

You can't light soul sand on fire when lighter use/fire-spread is disabled. A lot of people use soul fire for decoration.

**Comment by LlmDl** [comment]
This is a new 1.16 thing right? Soul Sand has the blue fire?

**Comment by Momshroom** [comment]
Yes, but it’s soul soil that lights, not soul sand.

**Comment by viveleroi** [comment]
It's both, "Fire ignited on soul sand or soul soil becomes soul fire"

https://minecraft.gamepedia.com/Fire

**Comment by LlmDl** [comment]
So it's soul sand and soul soil then?

**Comment by Momshroom** [comment]
Yes.  Sorry.  Both. Oddly enough the wiki says soul sand isn’t flammable at
the top of the page, then says you can light soul fire on it at the
bottom...

**Comment by LlmDl** [comment]
```
  - New Config Option: protection.fire_spread_bypass_materials
    - Default: NETHERRACK,SOUL_SAND,SOUL_SOIL
    - Materials which can be lit on fire even when firespread is disabled.
    - Still requires the use of the flint and steel.
```
