### ISSUE TITLE
Users with towny rank can't build even with permissions

### ISSUE THREAD

**Issue by Soujiro17** [TownyAdvanced/Towny#4208]
### What steps will reproduce the problem?

When a player with a towny rank tries to build/destroy/switch in the town where he is, he can't.

### What is the expected output?

That he can build

### What is your Towny version?
0.96.2.0 for 1.12.2

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/5frzL2XJ
2. Your Towny config.yml : https://pastebin.com/ZkCf0BVV
3. Your townyperms.yml : https://pastebin.com/GCcp3gqp

**Comment by LlmDl** [comment]
The spacing on your townyperms.yml file looks wrecked.

Which towny rank are you testing with?

**Comment by Soujiro17** [comment]
I'm trying with "test" and "assistant"

**Comment by Soujiro17** [comment]
Someone with rank "test" is supposed to have the same permissions as a mayor. However, it cannot break blocks when the / t set perm is activated

**Comment by LlmDl** [comment]
What message does that rank receive when attempting to break things? 

If you're uploading the townyperms.yml file with no indentation to your server, it will likely not read properly. The pastebin links of all your files have lost their spacing. What does the townyperms.yml file on your server look like?

**Comment by Soujiro17** [comment]
The identation is right, when i copied and pasted it messed up. The message is "You can't interact with {block}"

**Comment by LlmDl** [comment]
That's not a Towny message. Maybe EssProtect or EssAntiBuild.

**Comment by Soujiro17** [comment]
Fixed. Thanks you.
