### ISSUE TITLE
Replacing the deprecated methods

### ISSUE THREAD

**Issue by karlovm** [TownyAdvanced/Towny#4211]
I use several methods that I would like to replace with better ones.

1. Town.getHoldingBalance()
2. Town.pay(double)
3. TownyMessaging.sendTownMessage(Town, Message)

 Thanks for the answer!

**Comment by karlovm** [comment]
help

**Comment by LlmDl** [comment]
Unsure of what you're asking for here. Can you give some examples.

**Comment by karlovm** [comment]
1. How to get town's bank balance
2. Withdraw from town's bank
3. Send message to town

I write plugin and all of that methods are deprecated.

**Comment by karlovm** [comment]
![image](https://user-images.githubusercontent.com/51130679/88457277-c63fc500-ce8d-11ea-9f78-30dfb5a3acfd.png)

**Comment by LlmDl** [comment]
You should read the javadocs:
https://townyadvanced.github.io/javadocs/towny/0.96.0.0/com/palmergames/bukkit/towny/object/Town.html#pay-double-java.lang.String-

https://townyadvanced.github.io/javadocs/towny/0.96.0.0/com/palmergames/bukkit/towny/object/Town.html#getHoldingBalance--

https://townyadvanced.github.io/javadocs/towny/0.96.0.0/com/palmergames/bukkit/towny/TownyMessaging.html#sendPrefixedTownMessage-com.palmergames.bukkit.towny.object.Town-java.lang.String-

**Comment by karlovm** [comment]
Ok. I use town.collect(double) instead town.pay(double, string), town.getAccount().getHoldingBalance() instead town.getHoldingBalance() and town.sendPrefixedMessage(stirng) instead town.sendMessage(stirng)

**Comment by karlovm** [comment]
thanks

**Comment by LlmDl** [comment]
use town.getAccount().pay() instead of town.pay()

**Comment by karlovm** [comment]
but pay is deprecated

**Comment by karlovm** [comment]
![image](https://user-images.githubusercontent.com/51130679/88457768-dc4f8480-ce91-11ea-958b-11915a4f93c2.png)

**Comment by LlmDl** [comment]
Ah, use town.withdrawFromBank() if you're on the latest versions of Towny.

**Comment by karlovm** [comment]
withdrawFromBank() needs resident

**Comment by LlmDl** [comment]
town.getAccount().withdraw(amount, null) 

or null can be a string with the reason you're taking money out.

**Comment by karlovm** [comment]
thanks
