### ISSUE TITLE
Syncloads on Towny

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#4212]
### What steps will reproduce the problem?
1. Actually unsure but syncloads
2.
3.

### What is the expected output?
1. Not dumping/Syncloading
2.
3.

### What is your Towny version?
0.96.2.2

### What is your spigot/craftbukkit version?
Tuinity-699f5f2 pretty close to the latest commit on paper

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : N/A
3. Your townyperms.yml : N/A
4. Your log's error : https://ghostbin.co/paste/mc5ew

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Skipped the form. Resubmit.
