### ISSUE TITLE
Syncloads on Towny v2

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#4213]
### What steps will reproduce the problem?
1. Not entirely sure
2.
3.

### What is the expected output?
1. Not being killed by watchdog
2.
3.

### What is your Towny version?
0.96.2.2

### What is your spigot/craftbukkit version?
Tuinity-699f5f2  

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://ghostbin.co/paste/ynenh - total log is far too big, I can provide on DM
2. Your Towny config.yml (if using MySQL please remove password,) : https://ghostbin.co/paste/dakct
3. Your townyperms.yml : https://ghostbin.co/paste/h497u
4. Your log's error : https://ghostbin.co/paste/ynenh

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Extra Note: Just updated to latest Towny version from releases after the conversion of data.

**Comment by suneettipirneni** [comment]
The UUID Authenticator seems to be triggering the watchdog, are you sure this is a towny issue? @0liverGMC

**Comment by 0liverGMC** [comment]
Not entirely sure, reported to Tuinity as well to see what comes back from them - seems this is a common issue plaguing lots of servers. Both of my servers have similar issues w these syncloads just killing the server with watchdog. When I get an answer from Tuinity I'll update here as well.

**Comment by suneettipirneni** [comment]
This may be a related issue on their issue tracker: https://github.com/Spottedleaf/Tuinity/issues/143
