### ISSUE TITLE
Question: The server dies after the command / t unclaim all. And one more small question

### ISSUE THREAD

**Issue by khmelev77** [TownyAdvanced/Towny#4214]
**Ask your question as best as you are able:**

Hello!
I am having problems using the / t unclaim all command. After entering it, my server dies. (Killed). The size of the city is about 8x8. I have a small server and only my friends and I play. The server (at startup) has 2 gigabytes of RAM and 4 processor cores. 3.2GHz.

Is there anything I can do to prevent this command from killing my server? 
Can I disable this command somehow? And leave only /t uncliam? I would be glad to see an example of how to do this.
 
I am using spigot 1.16.1 and bPermission, vault and economy plugin.

And one more question:
I have already seen a solution to this problem somewhere, maybe you can give me a link. I need to protect the main spawn of the players on the server, I want to do it using Towny. I need that the main spawn of the players cannot be captured and that there is no mayor.

Really looking forward to the answer! Thank. Sorry for my bad english.

**Comment by LlmDl** [comment]
Your server likely is not beefy enough to handle the revert on unclaim feature towny uses to roll back unclaimed land to its wilderness state.

Use `/tw toggle revertunclaim` on all your worlds to disable the feature. 

You can claim an NPC town on your spawn using the instructions in the [Mayor section of the How Towny Works page.](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#mayors)
