### ISSUE TITLE
Towny Spy not "spying"

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#4221]
### What steps will reproduce the problem?
1. Use TownyChat 0-74, Towny 0.96.2.7
2. use /towny spy
3.

### What is the expected output?
1. Spy of all town,local, nation, and alliance chat
2.
3.

### What is your Towny version?
Towny 0.96.2.7

### What is your spigot/craftbukkit version?
Tuinity-d3dc35c

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/pofosehedi.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/umubuvajab.coffeescript
3. Your townyperms.yml : https://hastebin.com/ovecibuzid.php
4. Your log's error :  N/A

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://hastebin.com/axaburipig.shell
7. Your channels.yml : https://hastebin.com/gizociwuqi.bash

**Comment by LlmDl** [comment]
I do not see a startup log, just a log with random stuff in it. Please attach full startup sequence.

**Comment by 0liverGMC** [comment]
https://hastebin.com/humizapomo.md

**Comment by LlmDl** [comment]
I am not able to reproduce this. Does Towny tell you that you have the spy mode set when doing `/towny spy` ?

**Comment by 0liverGMC** [comment]
https://i.mineadia.com/7SBMcpQN8Y.png Even after setting it off and on still nothing.

**Comment by LlmDl** [comment]
I am guessing there is another plugin interfering.

**Comment by LlmDl** [comment]
I should also mention, if you can see the channel naturally you wont see the [SPY] {message}, you just see the normal channel.

**Comment by 0liverGMC** [comment]
I should've mentioned this before but it may be because of the deluxechat version that I am using now - it is a dev build they supplied through discord to fix the the duplicate chat.

**Comment by 0liverGMC** [comment]
https://i.mineadia.com/KO02aV0PlW.png

**Comment by LlmDl** [comment]
OK, so this is related to the DeluxeChat dev builds handling TownyChat by cancelling our chat messages rather than editing the format/message/recipients. Clip is going to look into what is possible. It may end up that he removes the message's recipients so TownyChat doesn't fire anything, except for the spying hopefully.

**Comment by LlmDl** [comment]
This one got fixed up on DeluxeChat's end, and I will have TownyChat 0.75 out to fix up some double-chat-on-spying soon.
