### ISSUE TITLE
Towny causing people to glitch out.

### ISSUE THREAD

**Issue by HyenaGodKing** [TownyAdvanced/Towny#4224]
### What steps will reproduce the problem?
This happened to two players so far, one doesn't know exactly how it happened and the other said "There was a tunnel and I ran into it. The ceiling was too low, and I started taking suffocation damage. I pressed shift to dismount, but a plugin (Towny perhaps) showed an error message that read "Don't disembark here! " 
This is an example of what they see it causes a lot more problem after that. Apparently their falling forever. https://cdn.discordapp.com/attachments/737544631004168232/737544778505257051/unknown.png

### What is the expected output?
I expect it to not reproduce that bug.

### What is your Towny version?
Towny-0.96.2.0.jar

### What is your spigot/craftbukkit version?
paper-375.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/6Pe793rH
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/0kpbXz3v
3. Your townyperms.yml : https://pastebin.com/CcjhX9qG
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
The message, nor the placing players in the blocks and not killing them, is Towny.
