### ISSUE TITLE
Dynmap won't show Towny layers

### ISSUE THREAD

**Issue by matthewblack04** [TownyAdvanced/Towny#4226]
### What steps will reproduce the problem?
1.as i'm unsure what causes the problem, I'm not entirely sure however
2. use any dynmap towny version and any towny and any dynmap version
3. check the map to see no towns

### What is the expected output?
1.I'm unsure what is meant with the expected output, I can clarify it in a comment if it's important
2.
3.

### What is your Towny version?
Do not say "latest". -Towny 0.96.2.0
-Townychat 0.72
-Townynameupdater 5.0

### What is your spigot/craftbukkit version?
Do not say "latest". paperspigot 1.15.2 (371)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/TwmJ7qvM
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/6Dg2N8mJ
3. Your townyperms.yml :https://pastebin.com/yK9DmYrf
4. Your log's error : https://pastebin.com/BrWipssr

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by matthewblack04** [comment]
important to note: it doesn't matter what version of towny,dynmap or dynmap towny I use, I will always have the same problem.
-it also tells me it can't display by nation and display by towns if I have protected-player-info on false in the dynmap config, while I want this on true to see players moving, however in the bug above its turned to true to show the bug exists even with that off.

**Comment by LlmDl** [comment]
Try using a modern version of [dynmap-towny.](https://github.com/TownyAdvanced/Dynmap-Towny/releases/tag/0.80)

**Comment by matthewblack04** [comment]
I've tried every version from 0.70 to 0.81 and got the same problem with all of them

**Comment by LlmDl** [comment]
Can you show me the startup when you use 0.80.

**Comment by matthewblack04** [comment]
https://pastebin.com/JruTe3a8 this is the log when using 0.80 it seems to get rid of the error message, however towny layers are still not visible

**Comment by matthewblack04** [comment]
taking some more time looking into it I feel it might be a dynmap problem rather than a dynmap-towny problem as it doesnt show any layers whatsoever (heads usually do show up but not now since I have protect-player-visibility on false for dynmap towny) however, im also very unsure whats causing this

**Comment by LlmDl** [comment]
Your towny and dynmap-towny versions are correct now. You could be right about it being on dynmap's side of things.
