### ISSUE TITLE
Suggestion: Add plots grid option to dynmap.

### ISSUE THREAD

**Issue by DeadGlamour** [TownyAdvanced/Towny#4227]
**Please explain your feature request to the best of your abilities:**
This isn't really anything major but I thought I'd mention it either way, so currently it's rather hard to count chunks in a specfic area in the dynmap, whether its for claiming or whatever reason I sometimes find the use of finding how many chunks there are and their borders.

**Comment by LlmDl** [comment]
This is likely unrealistic. Rendering every townblock individually would bog down the website.

**Comment by winnipeg21** [comment]
F3 + H shows chunk boarders in-game. Chat will say if you are in wild or a town or a plot. Not hard

**Comment by DeadGlamour** [comment]
What about adding this grid only on a certain level like another lair of the picture, so only once you zoom in enough it will show the grid.

**Comment by DeadGlamour** [comment]
> F3 + H shows chunk boarders in-game. Chat will say if you are in wild or a town or a plot. Not hard

I know, but it'd be so much better if there was a grid option, esspecially for larger areas.

**Comment by winnipeg21** [comment]
> > F3 + H shows chunk boarders in-game. Chat will say if you are in wild or a town or a plot. Not hard
> 
> I know, but it'd be so much better if there was a grid option, esspecially for larger areas.

As LlmDl said, it would slow down the webserver largely.. I've been using towny for many years now, F3 + H is the best option.

**Comment by LlmDl** [comment]
I've always been a fan of /res toggle map, /towny map big and /res toggle constantplotborder myself.

**Comment by winnipeg21** [comment]
Ah yes, I thought the command was always /t toggle map now res for the longest time
