### ISSUE TITLE
Towny causing issues with mods that interact with different dimensions

### ISSUE THREAD

**Issue by Reliphyte** [TownyAdvanced/Towny#4229]
### What steps will reproduce the problem?
1. Build WarpDrive Spaceship
2. Try to launch
3. Get error message about protect area
(Disabling towny in the world fixes it, but I want towny in the world)

### What is the expected output?
1. Build WarpDrive Spaceship
2. Try to launch
3. Get launched into space

### What is your Towny version?
Do not say "latest".
0.96.2.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12.2, not sure of the exact versions

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Attatched
[latest.log](https://github.com/TownyAdvanced/Towny/files/5008467/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) : https://hasteb.in/etepolot.coffeescript
3. Your townyperms.yml : https://hasteb.in/osamacol.yaml
4. Your log's error : N/A

**Comment by LlmDl** [comment]
Sorry for the late response, I have been on holiday.

The warpdrive is a block you hit? or an item you use? I would like to see the exact message you get.
