### ISSUE TITLE
How do I make a certain group able to do /t spawn to towns within their nation?

### ISSUE THREAD

**Issue by HyenaGodKing** [TownyAdvanced/Towny#4230]
How do I give a specific group the permissions to do /t spawn to any town in their nation
I don't want everyone able to do /t spawn to any town in their nation
I just want a specific group to do that
How can this be done?

I tried giving the group the perm towny.town.spawn.nation https://github.com/TownyAdvanced/Towny/wiki/Towny-Permission-Nodes#town-nodes

This is my townyperms: https://pastebin.com/ZKepGnz7
This is my towny config: https://pastebin.com/Cx15iiPu
Pastebin

I set allow_town_spawn_travel_nation: 'false' to true in my config but it just made everyone able to travel to towns within nation.

How do I make it so that only a particular group is able to do /t spawn to towns within their nation meanwhile other players in other groups can't?

**Comment by LlmDl** [comment]
```
  # Allow regular residents to use /town spawn [town] to other towns in your nation.
  # Valid values are: true, false, war, peace
  # When war or peace is set, it is only possible to teleport to the town,
  # when there is a war or peace.
  allow_town_spawn_travel_nation: 'false'
```
Has to be set to true, because the config overrides all permission nodes.

Then you have to remove towny.town.spawn.nation from the default nation group in the townyperms.yml, and give it to the rank in your permission plugin.
