### ISSUE TITLE
New day crashing

### ISSUE THREAD

**Issue by LoXR** [TownyAdvanced/Towny#4232]
### What steps will reproduce the problem?
1. Players doesnt have enough money to upkeep
2. New Day begins and their Town is disbanded
3. Server will crash

### What is the expected output?
1. Smooth database transition
2. Read resident files properly and not crash the server if a player had changed town during the new day
3.

### What is your Towny version?
Do not say "latest".
Towny version: 0.96.2.9

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Paper-382 (MC: 1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://mcpaste.io/ea1bacef9fae1fee
2. Your Towny config.yml (if using MySQL please remove password,) : https://mcpaste.io/2258cab5900deb8b
3. Your townyperms.yml : https://mcpaste.io/ca0280e3cb63e40a
4. Your log's error : https://mcpaste.io/09a0ce1c1f7e26b8

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by silverwolfg11** [comment]
This is caused by an outdated version of TownyFlight. Should be resolved once you update TownyFlight to the latest version.
