### ISSUE TITLE
Dynmap-Towny constant generating and not working right?

### ISSUE THREAD

**Issue by xXsoarusXx** [TownyAdvanced/Towny#4233]
I am trying to run Dynmap-Towny on my server and I got to where I'm constantly getting this trend of messages feeding through my console screen: 

03.08 13:03:44 [Server] Craft Scheduler Thread - 1/WARN [Dynmap-Towny] Plugin Dynmap-Towny v0.81 generated an exception while executing task 51
03.08 13:03:44 [Server] INFO java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.object.Town.getTownBlocks()Ljava/util/Collection;
03.08 13:03:44 [Server] INFO at org.dynmap.towny.DynmapTownyPlugin.handleTown(DynmapTownyPlugin.java:632) ~[?:?]
03.08 13:03:44 [Server] INFO at org.dynmap.towny.DynmapTownyPlugin.updateTowns(DynmapTownyPlugin.java:858) ~[?:?]
03.08 13:03:44 [Server] INFO at org.dynmap.towny.DynmapTownyPlugin.access$000(DynmapTownyPlugin.java:55) ~[?:?]
03.08 13:03:44 [Server] INFO at org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:307) ~[?:?]
03.08 13:03:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-0509002-6b95d59]
03.08 13:03:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.1.jar:git-Spigot-0509002-6b95d59]
03.08 13:03:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
03.08 13:03:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
03.08 13:03:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

I also already have a town created as well, but I'm not able to see it on my Dynmap at all. If anyone is able to let me know if there is something I didn't do or if I did something wrong, please let me know as I was unable to find anything on YouTube or even on the web that accurately helps my issue at hand.

**Comment by LlmDl** [comment]
Sorry for the late response, I have been on holiday.

You have not paid attention to teh required Towny version for that version of dynmap-towny. Update towny or downgrade your dynmap-towny.

**Comment by xXsoarusXx** [comment]
I have tried multiple versions but still not able to get it to work

**Comment by LlmDl** [comment]
If you had tried to use Towny 0.96.2.0 and Dynmap-Towny 0.80 you would see they work.
