### ISSUE TITLE
Question: Is there a way to allow the bypass of Mythic Mobs spawning in towns?

### ISSUE THREAD

**Issue by binhxlore** [TownyAdvanced/Towny#4234]
I am currently running both Towny and Mythic Mob on my server.  When a town is protected from hostile mob spawning, this also protects the town from the Mythic Mob random spawns.  I have these world bosses that spawn in the world and I would like them to be able to spawn even in protected town areas, but still allow these towns to be protected from vanilla mobs.  Is there any way to do this?  I was able to set the despawning of named entities to false and this allows the boss to walk into the protected land, but it does not allow it to actually spawn.

**Comment by Momshroom** [comment]
Towny removes mobs by their base type.  We dealt with this with mythic mobs by making mythic in types we did not want in towns to always have a hostile base type mob and vice versa.   A hook would be lovely, but this did solve the problem for us. (In our case, we wanted our mythics NOT to spawn in towns, but some had non-hostile base mobs and so we had to switch that out, but you could do it the other way.)

**Comment by LlmDl** [comment]
Sorry for the late response, I have been on holiday.

This would require one of two things:

MythicMobs listens to see if their spawning fires a MobRemovalEvent and cancels it or,
Towny checks to see if the mob is a MythicMobs using their API every time any mob is spawned.

It would be much more efficient if MythicMobs did the checking.
