### ISSUE TITLE
An Internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by abf1223** [TownyAdvanced/Towny#4237]
### What steps will reproduce the problem?
1./t new Test
2.
3.

### What is the expected output?
1.An Internal error occurred while attempting to perform this command
2.
3.

### What is your Towny version?
Do not say "latest".Towny-0.96.2.9

### What is your spigot/craftbukkit version?
Do not say "latest".1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/dP86aUWV
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/tZUFwARF
3. Your townyperms.yml : https://pastebin.com/2FNJEB2h
4. Your log's error : I can't find this.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by silverwolfg11** [comment]
This issue is due to md_5 changing up some bungeecord stuff recently, so some versions of bungeecord that support 1.16 do not have some API. 

This issue can be resolved by updating your bungeecord to the latest version. Or you could just use the compiled jar on the linked pull request.
