### ISSUE TITLE
Suggestion: Permission node to remove TP delay

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#4239]
**Please explain your feature request to the best of your abilities:**

There seems to be a permission node for most things on Towny but I noticed that there was no node for bypassing the teleport delay. It'd be helpful to have for teleportation portals and for moderators.

**Comment by LlmDl** [comment]
Sorry for the late response, I have been on holiday.

towny.admin.spawn was missing from the wiki and does what you want.
