### ISSUE TITLE
placeholder compatibility

### ISSUE THREAD

**Issue by AdolfoD43** [TownyAdvanced/Towny#4244]
sorry i am currently using featherboard and title advanced to do custom welcome msg and scoreboards but for some reason the towny placeholders i used before don't work for me in these plugins these are the placeholders:

{towny_currenttown_residents}

{towny_currenttown_name}

**Comment by JohnS19** [comment]
I believe the current placeholders are here: https://github.com/TownyAdvanced/Towny/wiki/Placeholders

The ones you might be looking for are: 
{townyadvanced_town_residents_amount}
{townyadvanced_town}

**Comment by AdolfoD43** [comment]
no, I am aware of those placeholders, but they only work as position markers for your city (if you belong to one), the variant that existed before (current) served for cities which were not part of it, so if you entered the territory of another town Of which you were not part, it appeared in the scoreboards, on the other hand I am not looking for placeholders to use in the same plugins, I need placeholders that are from towny, and are recognized by the following plugins: featherboard and titleadvanced.

**Comment by LlmDl** [comment]
You were using the towny placeholder expansion that was not developed by us. It should still work if you have the old ecloud download file still.
