### ISSUE TITLE
There is a problem related to /t set title for example: /t set title nameofplayer &4   when I use a colorcodes the whole resident list gets colored

### ISSUE THREAD

**Issue by Drainer2002** [TownyAdvanced/Towny#4250]
### What steps will reproduce the problem?
1. type /t set title playername &4test
2. that's for an example
3. the whole resident list gets colored with red (as I am using &4)

### What is the expected output?
1. to only color the player's name where the command was executed on

### What is your Towny version?
Towny Version 0.96.2.9

### What is your spigot/craftbukkit version?
paper 1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/tPkPG0aa
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/HhuFndSL
3. Your townyperms.yml : https://pastebin.com/CPVJsXAQ
4. Your log's error : no any log errors

(optional) If this is to do with permissions, 
5. Your permissions file :  It is luckperms so there is no perms files (it is in the form of .db)(I access it through web)

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/mZGUfPPp
7. Your channels.yml : https://pastebin.com/z1tggxhF

**Comment by LlmDl** [comment]
You're seeing this in the `/town` status' screen's resident list? Or in `/res list`? Or where?

**Comment by Drainer2002** [comment]
in /town
