### ISSUE TITLE
Bug with permissions

### ISSUE THREAD

**Issue by gabenitez0** [TownyAdvanced/Towny#4251]
### What steps will reproduce the problem?
I don't know, on the discord channel they only told me to update luckperms, but I already have it updated. These are the plugins I have installed:
Plugins (41): AdvancedAFKPlugin*, AuctionHouse, AuthMe, BuycraftX, Citizens, ClearLag, DiscordSRV, EntityTrackerFixer, Essentials, EssentialsMysqlStorage, EssentialsSpawn, HolographicDisplays, LeaderHeadsRevamped, LimitPillagers, LitePlaytimeRewards, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, NametagEdit*, PlaceholderAPI, ProtocolLib, PvPManager, RandomTeleport, ReferralSystem, SkinsRestorer, SpecializedCrates, StackMob, SuperCredits, SuperLobby, TheNewEconomy, Towny, TownyChat, TownyFlight, TownyNameUpdater, Vault, VillagerOptimiser, WitherAC, WorldBorder, WorldEdit, WorldGuard

### What is the expected output?
That users can always use towny commands as if they have permissions (which they already have)

### What is your Towny version?
Towny version: 0.96.2.0

### What is your spigot/craftbukkit version?
PaperSpigot #133 (1.16.1)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/cCUefgbm
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/QCzkk9i9
3. Your townyperms.yml : https://pastebin.com/H8mtgYZn
4. Your log's error : haven't error

(optional) If this is to do with permissions, 
5. Your permissions file : nothing in luckperms

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/A85NMjSS
7. Your channels.yml : https://pastebin.com/EYYAenDa

**Comment by LlmDl** [comment]
You haven't said what they issue is, only that you expect players to be able to do things they have permission for. Update your LP to v5.1.72 or newer and most interference from LP should stop, assuming you're finding player have a permission node in townyperms and they still cannot do the command.

**Comment by gabenitez0** [comment]
> No ha dicho cuál es su problema, solo que espera que los jugadores puedan hacer cosas para las que tienen permiso. Actualice su LP a v5.1.72 o más reciente y la mayoría de las interferencias de LP deberían detenerse, asumiendo que encuentra que el jugador tiene un nodo de permiso en townyperms y aún no puede ejecutar el comando.

Hi, where do i find that version of luckperms?
I have this: https://www.spigotmc.org/resources/luckperms.28140/updates

**Comment by LlmDl** [comment]
https://ci.lucko.me/job/LuckPerms/1145/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.1.86.jar from https://luckperms.net/download
