### ISSUE TITLE
`/t deposit` fails, and deletes money

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#4253]
Using `/t deposit` gives me a message saying `[Towny] You don't have that much.`, even when I *do* have that much.  It removes the money from my wallet anyway, but does not add it to the town.  As such, no-one is currently able to deposit money into their towns.

### What steps will reproduce the problem?
1. `/t deposit 1`

### What is the current output?
1. `[Towny] You don't have that much.`

### What is the expected output?
1. `[Towny] PLAYER deposited 1 to the Town bank.`

### What is your Towny version?
`0.96.2.9`

### What is your spigot/craftbukkit version?
`git-Paper-385 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

### Please link to the following files:
1. Your full server startup from `logs\latest.log`: https://gist.github.com/MilesBHuff/c0b8f89c16073b17084e4532eb608c7d
2. Your Towny `config.yml` (if using MySQL please remove password): https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/config.yml
3. Your `townyperms.yml`: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/townyperms.yml
4. Your log's error: (no error)
5. Your permissions file: https://github.com/SettleScape/server/tree/master/minecraft/plugins/LuckPerms/yaml-storage/groups
6. Your `ChatConfig.yml`: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/ChatConfig.yml
7. Your `Channels.yml`: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/Channels.yml

**Comment by LlmDl** [comment]
I'm not able to reproduce this using the same essentials, vault and towny versions. Anything you can think of? That message should only be seen if the player doesn't have enough money.

**Comment by MilesBHuff** [comment]
Not a clue.  I tried it again today, and am having the same issue -- "You don't have that much", alongside a deletion of the amount I tried to deposit.

**Comment by MilesBHuff** [comment]
Issue persists in `0.96.2.9`.

**Comment by LlmDl** [comment]
I was testing using 0.96.2.9. What's your town's name?

**Comment by MilesBHuff** [comment]
"Delta."

**Comment by LlmDl** [comment]
Using your config I have the issue. I have not figured out which setting your config uses that is interfering yet.

**Comment by MilesBHuff** [comment]
Okay!  Well at least it's reproducible.  Any ideas?  I can test on my local to help speed things up, if you want.

**Comment by suneettipirneni** [comment]
@MilesBHuff I think I've identified the issue, try this jar out:

[Towny-0.96.2.11.jar.zip](https://github.com/TownyAdvanced/Towny/files/5060479/Towny-0.96.2.11.jar.zip)

**Comment by MilesBHuff** [comment]
@suneettipirneni Confirmed fixed -- thank you!!  :D

**Comment by suneettipirneni** [comment]
> @suneettipirneni Confirmed fixed -- thank you!! :D
> Out of curiosity, what was the issue?

It was an incorrect condition for checking the bank cap:
<img width="529" alt="Screen Shot 2020-08-12 at 9 29 46 AM" src="https://user-images.githubusercontent.com/11075493/90020905-7e3ae380-dc7e-11ea-9b78-49aa2c290fcf.png">

**Comment by SomeCatIDK** [comment]
Having this same exact issue in both `0.96.5.0` and `0.96.5.7` in 1.16.4. 

Using default config with `Liteconomy` as the economy plugin.

**Comment by LlmDl** [comment]
@SomeCatIDK Liteconomy may not have support for the vault methods Towny uses. Talk to the liteconomy author, they would know better.

**Comment by SomeCatIDK** [comment]
> @SomeCatIDK Liteconomy may not have support for the vault methods Towny uses. Talk to the liteconomy author, they would know better.

This fixed it. For some reason, it was able to take money to create a town but not to deposit into one.
