### ISSUE TITLE
Towny Chat Channels throwing AsyncPlayerChatEvent Error

### ISSUE THREAD

**Issue by Zakkary19** [TownyAdvanced/Towny#4255]
### What steps will reproduce the problem?
1.go into /tc
2.type something into chat
3.throws error into console and shows chat message to everyone but in gray text with no prefix

### What is the expected output?
1.go into /tc
2.type something into chat
3.send a private message that people outside of the town cant see with the [TC] before the message

### What is your Towny version?
Do not say "latest".
Towny version 0.96.2.9
TownyChat version 0.72

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper version git-Paper-130 (MC: 1.16.1)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/RqTD5fF0
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/99EigJjZ
3. Your townyperms.yml : https://pastebin.com/CEN44WUc
4. Your log's error : https://pastebin.com/B48m4aQc

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/CdQqbiQ8
7. Your channels.yml : https://pastebin.com/9UiQv8US

**Comment by LlmDl** [comment]
Update TC to the latest 0.75.
