### ISSUE TITLE
Suggestion: Make staff tax exemption optional

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#4258]
**Please explain your feature request to the best of your abilities:**

All of our current players depend on taxes to automatically keep their town banks sufficient to pay plot upkeep;  but each of our towns has at most a couple members, and they would like to pay tax even if they're staff.

Can there be a setting to disable staff tax exemption?

**Comment by LlmDl** [comment]
The only reason they're exempt from paying tax is that they have the towny.tax_exempt permission node. This could be removed from the ranks who want to still pay taxes to the town. A new rank called taxfree could be made and the towny.tax_exempt node can be given there, and that rank can be given to staff who do not want to pay tax.
