### ISSUE TITLE
Suggestion: Fishing rods and PvP improvements

### ISSUE THREAD

**Issue by 3meraldK** [TownyAdvanced/Towny#4263]
1. Keep AFK players only being not pulled by others via fishing rod in non-PvP areas.
2. Add a new config value if Non-AFK players can be pulled out or not in non-PvP areas.

I hope it will be approved. Thanks for your attention.

**Comment by LlmDl** [comment]
Sounds like a duplicate of this: https://github.com/TownyAdvanced/Towny/issues/4180 ?

**Comment by 3meraldK** [comment]
> Sounds like a duplicate of this: #4180 ?

It didn't say about new config values or something

**Comment by LlmDl** [comment]
It would be a config option. 

As far as I remember, Towny does not track whether a player is AFK or not, so I don't know if that will be something we would consider in the logic for the feature.
