### ISSUE TITLE
Players not able to use Town command until relog

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#4264]
### What steps will reproduce the problem?
1. Join a town 
2. Try and towny specific command
3. Unable to use towny commands until a relog 

### What is the expected output?
1. A player to be able to use all towny commands instead of relogging after joining a town
2.
3.

### What is your Towny version?
0.96.2.9

### What is your spigot/craftbukkit version?
Tuinity CI build 141 - pretty much latest paper upstreamed

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/winalinevo.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/tomokeyoza.coffeescript
3. Your townyperms.yml : https://hastebin.com/idisopecib.php
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file : Can give a luck perms editor on request

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by TheCrunchy** [comment]
This is a bug with luckperms

**Comment by suneettipirneni** [comment]
> This is a bug with luckperms

The bug causing this was fixed in a recent version of luck perms

**Comment by TheCrunchy** [comment]
Wasnt fixed, https://github.com/lucko/LuckPerms/issues/1330

**Comment by Momshroom** [comment]
I can confirm that this has popped back up for me a few times recently after updating to the most recent towny pre-releases.  I was to say .10 is when it started again.  I updated paper at the same time, but did not change lp versions.  It’s been rare, though.

**Comment by 0liverGMC** [comment]
Yea even after updating Towny and LuckPerms seems I'm out of luck.

**Comment by LlmDl** [comment]
@0liverGMC is this the same server that had the residents removed from all of the towns?

**Comment by 0liverGMC** [comment]
Yea, think that is the whole cause going to import the database to mysql and see if it solves our problems.

**Comment by MinecraftAdmin** [comment]
Can confirm I am getting this issue on Towny 0.96.2.9 and Luckperms 5.1.93

**Comment by LlmDl** [comment]
@MinecraftAdmin no one should be using 0.96.2.9 any more. Update to 0.96.2.11 at least.

**Comment by Kbryst** [comment]
I'm on 0.96.2.15 and Luck Perms 5.1.93
Paper spigot 1.16.2

I am having this issue.

**Comment by LlmDl** [comment]
This is the LP issue acting up again. 5.1.72 had the issue fixed but it has returned.
