### ISSUE TITLE
Wither does not damage animals if townyworld explosions are toggled off

### ISSUE THREAD

**Issue by sh1mrr4** [TownyAdvanced/Towny#4266]
### What steps will reproduce the problem?
1. Toggle explosions off in the world you are in
2. Spawn the Wither
3. Watch how it attacks, but fails to kill animals (e.g. sheep, rabbit...)

### What is the expected output?
1. The Wither should be able to kill all mobs (including animals)

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
paper 1.15.2-378

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/yxMKv1VS
2. Your Towny config.yml : https://pastebin.com/TFZSWWzv (should be the default config)
3. Your townyperms.yml : https://pastebin.com/4AJe4fjq (should be the default permissions)
4. Your log's error : No errors.

**Comment by LlmDl** [comment]
In this scenario (explosions off in the world) does the Wither still hurt players with the same explosions?

**Comment by sh1mrr4** [comment]
Yes, I just tested it again and players do take damage from those projectiles thrown by the wither. 
On a side note: I removed Animals from the list of entities, that are protected in a town, and this seems to enable the wither to damage them again (even if there was no town anywhere nearby).

**Comment by LlmDl** [comment]
Yeah I'll have to handle animals in the towns vs animals in the wild separately probably.

I feel that in towns animals should probably be protected, or maybe always be protected if they're on a farm plot. In the wild it should behave according to the explosions setting probably. Explosion reverting for withers added recently so it will be ok to have the wilderness explosion on.

**Comment by LlmDl** [comment]
In the new explosions protection branch this has been sorted out:

- explosion setting will determine if the entities are damaged.
- wilderness explosion on will cause the animal to be damaged if they are in the wild.
