### ISSUE TITLE
Towny doesn't update resident names on account name change

### ISSUE THREAD

**Issue by lucasboss45** [TownyAdvanced/Towny#4268]
### What steps will reproduce the problem?
Change your account name

### What is the expected output?
N/A

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
PaperMC (git-Paper-385) 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/HMxUn1U0
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/V8sKFunY
3. Your townyperms.yml : https://pastebin.com/mGHi7YrK
4. Your log's error : N/A

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

![image](https://user-images.githubusercontent.com/29255472/90334897-19122580-dfd1-11ea-8adb-a20997701818.png)

**Comment by LlmDl** [comment]
You're missing TownyNameUpdater which serves this purpose (until we have things moved over to UUIDs.)

**Comment by lucasboss45** [comment]
That's a thing? Well, I'll go add that right away.
Just to make sure, it's this right? 
https://github.com/LlmDl/TownyNameUpdater/blob/master/TownyNameUpdater.jar

**Comment by LlmDl** [comment]
I think that should be the same as this: https://github.com/TownyAdvanced/TownyNameUpdater/releases/download/5.0/TownyNameUpdater-5.0.jar
