### ISSUE TITLE
Prevent use of &e in titles and surnames.

### ISSUE THREAD

**Issue by SiphMC** [TownyAdvanced/Towny#4270]
**Ask your question as best as you are able:**

Is there a way to disable the uses of chat format in title?

Players can use chat format:
https://gyazo.com/738941da2d472789bc39b9d1883a6614

**Comment by SiphMC** [comment]
Up?

**Comment by LlmDl** [comment]
For those wondering: `name_remove_regex: '[^\P{M}a-zA-Z0-9\._\[\]-]'` will stop all & from being used in the titles. I think I'll probably end up making it so that &e cannot be used except for admins.

**Comment by TheEndless7** [comment]
After stopping the server, doing what you recommended and starting the issue remains. Here's what my config looks like.

`   # Regex fields used in validating inputs.
  regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\._\[\]-]'`

**Comment by LlmDl** [comment]
Does `name_remove_regex: '[^a-zA-Z0-9\._\[\]-]'` work?

**Comment by TheEndless7** [comment]
It works, thanks a lot for the help.
