### ISSUE TITLE
Towny sends incorrect message in claim process

### ISSUE THREAD

**Issue by hydridity** [TownyAdvanced/Towny#4272]
### What steps will reproduce the problem?
1. Have town with reached town size (for example town size with 8/8 without any bonuses)
2. Trying to claim more using rect or circle (/t claim rect 4)

### What is the expected output?
1. Towny to notify with message: Not enough available town blocks to claim this selection.
Instead it sends incorrect message: This area has already been claimed.
It even says that "area has already been claimed" if the specified area is not attached to town edge and there are no claimed areas around
Trying to claim only one town block with /t claim, sends correct message with not enough town blocks or area not being attached to town edge

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
 git-Spigot-9639cf7-8fb6585 (MC: 1.16.1)

**Comment by LlmDl** [comment]
You skipped the form. Please include it.

**Comment by LlmDl** [comment]
Thanks. I know where the issue is I just have to clear it up.
