### ISSUE TITLE
/t and some related commands not working

### ISSUE THREAD

**Issue by Blueme00** [TownyAdvanced/Towny#4275]
### What steps will reproduce the problem?
1. Using /t or /town

### What is the expected output?
1. The player's town information should be displayed in chat.

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/70wEZhAs
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/fxUwgja5
3. Your townyperms.yml : https://pastebin.com/rfM5eu3f
4. Your log's error : https://pastebin.com/5C5pTMys

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/FmMicqWj
7. Your channels.yml : https://pastebin.com/gHtDW4Dh

**Comment by Blueme00** [comment]
If needed, I'm on the discord server @MrShelbyBlue#0641

**Comment by LlmDl** [comment]
How many residents are in the town and is teh town a capital city of a nation.

**Comment by Blueme00** [comment]
I can't even check the number of residents.  I would guess between 5 and 10.  There are no nations currently.

**Comment by LlmDl** [comment]
Can you show me the towny\data\residents\MAYORNAME.txt file please.

**Comment by Blueme00** [comment]
I would love to! Just a few moments please.

**Comment by Blueme00** [comment]
https://pastebin.com/06jjHy7b

**Comment by LlmDl** [comment]
And the town Crossefa has the mayor listed as teh mayor in the towny\data\towns\Crossefa.txt ?

**Comment by Blueme00** [comment]
Oh that's bizarre, let me send you what I have.  I don't believe so, but I've never really explored these files before.

**Comment by Blueme00** [comment]
https://pastebin.com/VsucHPNi

**Comment by LlmDl** [comment]
So that town has no mayor set, which shouldn't happen. You can add yourself manually or try using the `/ta set mayor crossefa mrshelbyblue`

The reason it has failed thus far is the town has no mayor.

**Comment by Blueme00** [comment]
Ok that makes a lot of sense for sure!

**Comment by Blueme00** [comment]
Ok that seemed to do it.  Does this mean that no residents are able to use the /t command then?

**Comment by Blueme00** [comment]
Also, if a town mayor leaves the town, Towny will automatically set the new mayor correct?  What happens if a current mayor is completely removed from towny?

**Comment by LlmDl** [comment]
None of them were able to use the /t command because the town could not resolve a mayor (which should never happen.)

When a mayor uses /t leave they have to either /t set mayor {residentname} or use /t delete. If towny removes the mayor for inactivity, towny will choose from the assistant rank or, failing that, any other resident.

**Comment by Blueme00** [comment]
Ok, I think I might have a fix to prevent this in the future for my server.  Is there a way to force towny to delete a user?  And if so, does the user automatically get created again if they're in the server or would they have to relog into the server again?

**Comment by LlmDl** [comment]
I actually have a database PR in the works that will stop this from happening in the future. It is very rare to begin with.

**Comment by LlmDl** [comment]
If you want to force delete a user you can do /ta delete NAME, and they will get a new resident file created when they log in next.

**Comment by Blueme00** [comment]
ok that sounds excellent!  I think I can work with that!  Thanks for the help!
