### ISSUE TITLE
Towns seem to be corrupted without a crash or log

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#4276]
### What steps will reproduce the problem?
1. Restart server
2. Check a random town 
3. /t (name)

### What is the expected output?
1. A status page of the town
2. Town players to claim etc
3.

### What is your Towny version?
0.96.2.9

### What is your spigot/craftbukkit version?
Tuinity CI build 145 - pretty much latest paper upstreamed

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/ucawafufub.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/winalinevo.md
3. Your townyperms.yml : https://hastebin.com/tomokeyoza.coffeescript
4. Your log's error : https://hastebin.com/muvoyamiqo.php (Only error, no error on startup either)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
There's a 99% chance the town you're looking up has no mayor. You can manually set it back and the /t screen should work. 

There's an update in the works which will make this not happen to towns when they load, it's fairly rare and i've only seen it happen to a handful of mysql server setups.

**Comment by 0liverGMC** [comment]
This has happened to a bunch of towns, although I am 100% certain they did have a mayor - also it's like these towns cease to exist all the players can't do anything, is that the same reason for the no mayor thing?

**Comment by 0liverGMC** [comment]
https://hastebin.com/ojefevulap.sql - here's a new log from when I tried using towny admin to set a mayor.

**Comment by LlmDl** [comment]
In that example was Shables already a member of Seafloore?

**Comment by LlmDl** [comment]
I should also mention you should update to 0.96.2.11 or 0.96.2.12 (if it is out by the time you see this.) 
0.96.2.9 had some economy refactor bugs still in it, which could potentially be the source of your issue.

Also, using /ta set mayor TOWN PLAYER is probably better than using the /ta town TOWN set mayor PLAYER command.

**Comment by 0liverGMC** [comment]
Yea both commands don't work, so yea looks like I'll update it - and yes Shables was the mayor of it.

**Comment by 0liverGMC** [comment]
Yea, same issue with latest https://hastebin.com/opumajokiq.bash - guess I'll just do it all manually just slightly annoying a restart can just fuck it up.

**Comment by LlmDl** [comment]
open the towny\data\towns\seafloore.txt and add a mayor=Shables line to it if it is missing.

**Comment by 0liverGMC** [comment]
Added in the line, seems the spawn point was deleted as well as seen in this ss https://i.mineadia.com/eAU2LN1kq3.png

**Comment by LlmDl** [comment]
That town is also missing teh residents=NAMES line. You're not using my experimental towns-dont-save-residents branch are you?

**Comment by 0liverGMC** [comment]
Not that I know of, using all the pre-releases usually from the main towny page - also seems that all my towns are missing that residents= line.

**Comment by LlmDl** [comment]
Something went very wrong for you somewhere.

**Comment by 0liverGMC** [comment]
Yea but all towns still have their residents? I'm going to migrate to mysql and see what happens lmao.

**Comment by 0liverGMC** [comment]
So I have also boiled it down to the data conversion that took place in 0.96.2.4, checking my towny backup from when it did that conversion shows the residents= line and all towns being in tact.

**Comment by LlmDl** [comment]
That's around when the eco refactor was put in place. You must have upgraded before one of the subsequent fixes was made.

**Comment by 0liverGMC** [comment]
So, my plan is to manually go in and make sure each town is all set, then convert to MySQL to see if that can help both the issues with the perms and fix this from not happening.

**Comment by LlmDl** [comment]
This should not happen any longer in the pre-releases that have my new town/nation saving/loading code.
