### ISSUE TITLE
Towns going corrupt, making server start in safe mode until I manually delete them from towns.txt

### ISSUE THREAD

**Issue by Rabidhuman** [TownyAdvanced/Towny#4277]
### What steps will reproduce the problem?
1. on server start

### What is the expected output?
1. not safe mode

### What is your Towny version?
Do not say "latest".
Towny v0.96.2.11

### What is your spigot/craftbukkit version?
Do not say "latest".
paper 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/YKnfj8LU

2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/R8H7Y0NJ
3. Your townyperms.yml :https://pastebin.com/YB2jAEPX
4. Your log's error : Towns are going corrupt, here is a second occurence from a seperate log that is similar to the one above https://pastebin.com/pm2c3qbn

**Comment by LlmDl** [comment]
Can you show me your towny\data\towns\plug.txt file?

**Comment by LlmDl** [comment]
This cannot happen any longer with the pre-releases.
