### ISSUE TITLE
OnPlayerLogin Lag Spikes

### ISSUE THREAD

**Issue by Cdotsharpy** [TownyAdvanced/Towny#4286]
### What steps will reproduce the problem?
1. Setup a server with flatfile databased Towny 0.96.2.13 and needed addons (Economy plugin TownyChat, TownyNameUpdater).
2. Create a town with a account.
3. Try logging in and out again and again with that account and watchout the lag spikes from another user inside.

### What is the expected output?
1. Each login will cause huge lag spikes for couple seconds.
2. TPS will drop to 11 while it was constant 20 without any login event.
3. This will cause server crash if there is like 10 players joining in together.
(Normal constant 20 TPS than login causes huge lag spike)
![resim](https://user-images.githubusercontent.com/70144803/91044758-78e67d00-e61e-11ea-9f48-2c220c2e9908.png)

(Each spike shows a login from latest.log)
![resim](https://user-images.githubusercontent.com/70144803/91044650-4c326580-e61e-11ea-9e78-9e44357d8334.png)

### What is your Towny version?
Issue still happening on 0.96.2.13

### What is your spigot/craftbukkit version?
PaperSpigot 1.16.1 Build 138

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.ubuntu.com/p/xN8987Yt6K/
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.ubuntu.com/p/4s9FV9hQJk/
3. Your townyperms.yml : https://pastebin.ubuntu.com/p/BbbcMKyGN4/
4. Your log's error : Timings sent on discord for privacy.
![resim](https://user-images.githubusercontent.com/70144803/91044927-bd721880-e61e-11ea-8581-40a120c8fea9.png)

**Comment by BlondeCow** [comment]
I'm having the same problem, needs to be solved urgently.

**Comment by Caleston** [comment]
Same issue here too, using flatfile database. Our server crashes with even 2 new players joining, previously joined players seem to load though.

**Comment by LlmDl** [comment]
@Cdotsharpy @BlondeCow @Caleston does it go away if you have `flatfile_backup_type: none` set in the config?

**Comment by Caleston** [comment]
> @Cdotsharpy @BlondeCow @Caleston does it go away if you have `flatfile_backup_type: none` set in the config?

No, we disabled daily backups and set the backup type to none. Same error occurred.

**Comment by Cdotsharpy** [comment]
> 
> 
> @Cdotsharpy @BlondeCow @Caleston does it go away if you have `flatfile_backup_type: none` set in the config?

Just tested, nope its still happening after setting "flatfile_backup_type: none"
![resim](https://user-images.githubusercontent.com/70144803/91050670-a8e64e00-e627-11ea-93f0-8dd08347c2f0.png)

**Comment by LlmDl** [comment]
Return your backup setting to what you had previously and please test this: https://cdn.discordapp.com/attachments/669247087329673228/747449820704407623/Towny-0.96.2.14.jar

**Comment by Cdotsharpy** [comment]
> 
> 
> Return your backup setting to what you had previously and please test this: https://cdn.discordapp.com/attachments/669247087329673228/747449820704407623/Towny-0.96.2.14.jar

Tested no tps drops so far
![resim](https://user-images.githubusercontent.com/70144803/91051463-d54e9a00-e628-11ea-9b6a-5f95f61575bc.png)

**Comment by Cdotsharpy** [comment]
But this version has something about economy broken as it seems, when i delete my town and create new one its not taking money from my balance and posting this error in console https://pastebin.ubuntu.com/p/92vr2Yb4cJ/

**Comment by Cdotsharpy** [comment]
Identified problem its related my aconomy plugin, its fixed when economy plugin changed to ico5 thanks for support
