### ISSUE TITLE
Question:Issuing additional chunks not from the Treasury

### ISSUE THREAD

**Issue by 1Vesemir1** [TownyAdvanced/Towny#4287]
Is there a parameter in config that allows you to Issue additional chunks not from the city Treasury but so that additional chunks are issued with the addition of people to the city?
------------
Please forgive me if you could not understand the above sentence.(this is a Google translation)

**Comment by LlmDl** [comment]
Perhaps you need to use the /t buy bonus command and purchase more townblocks?
