### ISSUE TITLE
Town claims restrictions

### ISSUE THREAD

**Issue by imbsqt** [TownyAdvanced/Towny#4289]
Hi,

Im looking to configure towny for my land claiming system, i want to have it so that when a player reaches a certain rank they gain 1 town claim, then potentially when they reach another rank later on they get another claim etc.

can this be done?

thanks

**Comment by LlmDl** [comment]
Towny typically gives out more claims based on how many players are in the town.

It would be possible to make the max-residents-per-town setting to 1, making it so players never get more than the config's town_block_ratio amount. You could then give bonus claims later on to the one-person towns.
