### ISSUE TITLE
Question: Town Colors

### ISSUE THREAD

**Issue by SundraLOL** [TownyAdvanced/Towny#4290]
Whats the command for changing town colors and nation colors because red on the dynmap is kinda wack

**Comment by LlmDl** [comment]
Nations can use /n set mapcolor. There is no command for towns.

**Comment by SundraLOL** [comment]
Will you add a command for changing town colors?

**Comment by LlmDl** [comment]
It's not a planned feature, no.

**Comment by Menestt22** [comment]
yep I've already done it.
