### ISSUE TITLE
Overclaim penalty not working

### ISSUE THREAD

**Issue by cisc0disc0** [TownyAdvanced/Towny#4294]
### What steps will reproduce the problem?
1. Attempting to claim while townblock limit is hit in your town
2.
3.

### What is the expected output?
1. Claim is expected to go through, and charge an overclaim penalty
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.2.0 for 1.13.2

### What is your spigot/craftbukkit version?
Do not say "latest".
paperclip-655

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/raw/UCvE8PCi
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/3DR3JpQF
3. Your townyperms.yml :
https://pastebin.com/CXpX6Drh
4. Your log's error : 
https://i.imgur.com/Ufvf9SF.png

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Thank you.

**Comment by LlmDl** [comment]
Its actually only possible to get the overclaim if you had claimed land and then lose residents. Or add a nation to get the nationclaimsbonus and then leave the nation after claiming all of it.
