### ISSUE TITLE
world.txt being ignored?

### ISSUE THREAD

**Issue by Tstorm89** [TownyAdvanced/Towny#4295]
I'll try to keep this simple, but I could use a little help with an issue relating to data in the world.txt file.

What I want towny to do is...
1) allow certain blocks to be placed in the wild
2) remove certain blocks when a plot or entire town is unclaimed.

The default settings should cover these needs just fine, (e.g. planting saplings in the wild is a-ok and it appears as a default setting. Likewise, when towns fall into ruin I want torches and beds to break, and this appears as a default setting as well). HOWEVER, neither of these features seems to work and I cannot figure out why that may be. 

Any help is much appreciated!

**Comment by LlmDl** [comment]
Show me your towny\data\worlds\worldname.txt file in which you have been editing.

**Comment by Tstorm89** [comment]
pvp=true
forcepvp=false
# Can players found towns and claim plots in this world?
claimable=true
worldmobs=true
forcetownmobs=false
firespread=false
forcefirespread=false
explosions=true
forceexplosions=false
endermanprotect=true
disableplayertrample=false
disablecreaturetrample=false


# Unclaimed Zone settings.
unclaimedZoneBuild=false
unclaimedZoneDestroy=true
unclaimedZoneSwitch=true
unclaimedZoneItemUse=true
unclaimedZoneName=Wilderness

# The following settings are only used if you are not using any permissions provider plugin
unclaimedZoneIgnoreIds=SAPLING,LEAVES,LEAVES2,LOG,LOG2,DIAMOND_ORE,LAPIS_ORE,REDSTONE_ORE,GLOWING_REDSTONE_ORE,GOLD_ORE,IRON_ORE,COAL_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,CRAFTING_TABLE,TORCH,LADDER,RAILS,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,VINE,NETHER_WARTS,COCOA


# The following settings control what blocks are deleted upon a townblock being unclaimed
usingPlotManagementDelete=true
plotManagementDeleteIds=WHITE_BED,ORANGE_BED,MAGENTA_BED,LIGHT_BLUE_BED,YELLOW_BED,LIME_BED,PINK_BED,GRAY_BED,LIGHT_GRAY_BED,CYAN_BED,PURPLE_BED,BLUE_BED,BROWN_BED,GREEN_BED,RED_BED,BLACK_BED,TORCH,REDSTONE_WIRE,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN,WOODEN_DOOR,ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,STONE_PLATE,IRON_DOOR_BLOCK,WOOD_PLATE,REDSTONE_TORCH_OFF,REDSTONE_TORCH_ON,DIODE_BLOCK_OFF,DIODE_BLOCK_ON


# The following settings control what blocks are deleted upon a mayor issuing a '/plot clear' command
usingPlotManagementMayorDelete=true
plotManagementMayorDelete=ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN

# If enabled when a town claims a townblock a snapshot will be taken at the time it is claimed.
# When the townblock is unclaimded its blocks will begin to revert to the original snapshot.
usingPlotManagementRevert=false
# Any block Id's listed here will not be respawned. Instead it will revert to air.
plotManagementIgnoreIds=GOLD_ORE,LAPIS_ORE,LAPIS_BLOCK,GOLD_BLOCK,IRON_ORE,IRON_BLOCK,MOSSY_COBBLESTONE,TORCH,SPAWNER,DIAMOND_ORE,DIAMOND_BLOCK,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN,ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,GLOWSTONE,EMERALD_ORE,EMERALD_BLOCK,WITHER_SKELETON_SKULL,WITHER_SKELETON_WALL_SKULL,SHULKER_BOX,WHITE_SHULKER_BOX,ORANGE_SHULKER_BOX,MAGENTA_SHULKER_BOX,LIGHT_BLUE_SHULKER_BOX,LIGHT_GRAY_SHULKER_BOX,YELLOW_SHULKER_BOX,LIME_SHULKER_BOX,PINK_SHULKER_BOX,GRAY_SHULKER_BOX,CYAN_SHULKER_BOX,PURPLE_SHULKER_BOX,BLUE_SHULKER_BOX,BROWN_SHULKER_BOX,GREEN_SHULKER_BOX,RED_SHULKER_BOX,BLACK_SHULKER_BOX,BEACON

# If enabled any damage caused by explosions will repair itself.
usingPlotManagementWildRegen=true
PlotManagementWildRegenEntities=Creeper,EnderCrystal,EnderDragon,Fireball,SmallFireball,LargeFireball,WitherSkull
usingPlotManagementWildRegenDelay=15

# This setting is used to enable or disable Towny in this world.
usingTowny=true

# This setting is used to enable or disable Event war in this world.
warAllowed=true
metadata=

**Comment by LlmDl** [comment]
Having:
```
unclaimedZoneBuild=false
unclaimedZoneDestroy=true
unclaimedZoneSwitch=true
unclaimedZoneItemUse=true
```
means that anyone can destroy/switch/itemuse anything in the wild, only building is being restricted to the list here:
```unclaimedZoneIgnoreIds=SAPLING,LEAVES,LEAVES2,LOG,LOG2,DIAMOND_ORE,LAPIS_ORE,REDSTONE_ORE,GLOWING_REDSTONE_ORE,GOLD_ORE,IRON_ORE,COAL_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,CRAFTING_TABLE,TORCH,LADDER,RAILS,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,VINE,NETHER_WARTS,COCOA
```

You've also got `usingPlotManagementDelete=true` which should make the list below delete on a townblock being unclaimed. Which blocks are you using to test exactly?

**Comment by Tstorm89** [comment]
Yes, the first part works fine - building is all I want to restrict in the wild. This is with the exception of blocks on that list of course. I have tested torches, saplings, and crafting tables in the wild, though despite being on the list, I still get 'not allowed to build in the wild.'

I did some more testing on the usingPlotManagementDelete and have found that it actually does work in most cases. I had only been testing torches, and for some reason, torches are not deleted despite being listed. I tried again with a bed and signs, and those were successfully deleted.

**Comment by LlmDl** [comment]
might be the difference between torch and wall_torch?

**Comment by Tstorm89** [comment]
Nailed it! I didn't know there was a difference - wall_torch took care of it.

Now I just need help figuring out why blocks listed under 'unclaimedZoneIgnoreIds' are still not allowed to be built in the wild.

**Comment by LlmDl** [comment]
if you need to get the correct names, hold a clay brick in your hand and hit the block, it will tell you what name Towny needs to have for it to be a proper Material.

**Comment by Tstorm89** [comment]
That's good to know. Much appreciated!

Any ideas what I may be doing wrong on this last issue? Item IDs should be correct.

**Comment by LlmDl** [comment]
What is your Towny version number?

**Comment by Tstorm89** [comment]
0.96.2.0

**Comment by LlmDl** [comment]
I've narrowed it down and figured out why it doesn't work. When Towny still had a using_permission: true/false in the config we would use that list when permissions was set to false. (This is a setting that dated back to before Bukkit had built-in permissions, so not every server had them.)

When I finally got rid of the using_permissions option I neglected to retain that worldsetting list, as it was only used when using_permissions was set to false (and the comments in the file still reflect that.)

For the short term you can give players the towny.wild.build.MATERIALNAME permission nodes. I will be making a change that re-activates that list however, this would require you to update onto the towny pre-releases (this change would be part of 0.96.2.17.)

**Comment by Tstorm89** [comment]
Ahhh interesting. I assumed it was related to the comment in there. I took note of it, but didn't completely comprehend it.

Sounds good though! I will do that for the time being. Using item IDs into the worldname.txt keeps things far more simple and organized in my opinion, and I am very happy to hear you will be reactivating this list feature! I will keep an eye out for the 0.96.2.17 release!

Your support has been wonderful, thank you very much for your time!
