### ISSUE TITLE
Towny not working after doing some simple translation...

### ISSUE THREAD

**Issue by KozzaX** [TownyAdvanced/Towny#4297]
### What steps will reproduce the problem?
1.I modified 2 simple letter in a french word in the french.yml

### What is the expected output?
1.To modify the following english sentence : You can't destroy in wilderness so it can be understandable in French

### What is your Towny version?
v0.96.1.9

### What is your spigot/craftbukkit version?
1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/iwNR1hHL
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/dkCakUeg
3. Your townyperms.yml : https://pastebin.com/v1KqR0gM
4. Your log's error : https://pastebin.com/YGSnvtZk
5. The french.yml file : https://pastebin.com/6Zqw9uiB

Thanks in advance for your help !

**Comment by LlmDl** [comment]
In your config's town_level you have 
```
  - numResidents: 24
    namePostfix: ' (Grande Citadelle)'
    mayorPrefix: 'Duc '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 384
    upkeepModifier: 15
    townOutpostLimit: 0
  - numResidents: 28
    namePostfix: ' (Métropole)'
    mayorPrefix: 'Lord '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 448
    upkeepModifier: 20
    townOutpostLimit: 0
```
both upkeepmodifier lines need to be doubles (ie 15.0 and 20.0) and not integers.

**Comment by KozzaX** [comment]
That's perfect ! Thank you for the help ! :D
