### ISSUE TITLE
Question: Fire blocking revert feature

### ISSUE THREAD

**Issue by AZFire1** [TownyAdvanced/Towny#4298]
**Ask your question as best as you are able:**
Is fire supposed to block the regeneration or (reverting) of mob damage in the wild or towns un-building?

**Comment by LlmDl** [comment]
I couldn't say, you're saying that when the regen goes to replace a fire block it doesn't, and then skips onto the next block?

**Comment by AZFire1** [comment]
Yeah, which ends up making the terrain kinda messy.

**Comment by LlmDl** [comment]
Probably you should file a bug report, and include the towny\data\worlds\WORLDNAME.txt file of the world you're doing your testing in.
