### ISSUE TITLE
Towns that have fallen into ruin aren't removed from /t list or the database but cause NPE's

### ISSUE THREAD

**Issue by MKieburtz** [TownyAdvanced/Towny#4299]
### What steps will reproduce the problem?
1. Let a town fall into ruin (maybe restart the server)
2. /t list will show the town still existing. /t townname will throw an NPE 

### What is the expected output?
1. The town should be removed from /t list
2. The result of /t townname should be 'townname is not registered'

### What is your Towny version?
0.96.2.16

### What is your spigot/craftbukkit version?
Tuinity (paper fork) #148

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/smYRZpLU
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/2wxu8wsw
3. Your townyperms.yml : https://pastebin.com/DiQhVyCz
4. Your log's error : After doing /t townname (that fell into ruin) https://pastebin.com/9CAxdAcn

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by suneettipirneni** [comment]
Did you restart the server a bit after the town fell?

**Comment by MKieburtz** [comment]
Yes I believe that restarting the server fixed it in this case. This is still a problem though because residents of the fallen town can't remake their town until the server restarts.

**Comment by suneettipirneni** [comment]
I was asking because restarting could’ve caused the issue in the first place.

**Comment by MKieburtz** [comment]
The server restarts periodically, every 12hrs to be precise.

**Comment by suneettipirneni** [comment]
So I’m guessing what happened is the server restart coincided with the daily towny timer.

**Comment by MKieburtz** [comment]
It's off by an hour, so I don't think this is the issue.

**Comment by LlmDl** [comment]
I've not had the chance to try and reproduce this but looking over the code it appears the same code is run whether the town is deleted by a player or by the daily upkeep. Can you confirm that it still shows up in your /t list when you're manually deleting a test town?

**Comment by MKieburtz** [comment]
I can't reproduce it by creating a town then deleting it.

**Comment by LlmDl** [comment]
Ok I'll test it out and get some debug code and see which step it's happening on.

**Comment by LlmDl** [comment]
So in beginning to test this, using 0.96.2.17 on flatfile I could not reproduce the issue. You're using 0.96.2.16 (which shouldn't make a difference,) and mysql (which also shouldn't make a difference because the TownsMap that Towny uses to list the towns already has the town removed from it before it goes to any mysql/flatfile specific code.)

How many times did this happen?

**Comment by MKieburtz** [comment]
Only saw it happen once, sorry for late reply, didn't haven any internet for a few days

**Comment by LlmDl** [comment]
Hmmm, next time the upkeep ruins a town check and see if it's caused any issues. Also make sure you've updated to 0.96.2.17 (or newer if you see something newer,) as 0.96.2.16 has a permission bug.

If you have a second instance of the bug feel free to reopen the ticket.
