### ISSUE TITLE
Suggestion: Make BlockExplodeEvents revert based on a configurable list.

### ISSUE THREAD

**Issue by emkirsh** [TownyAdvanced/Towny#4300]
**Please explain your feature request to the best of your abilities:**
Currently for `PlotManagementWildRegenEntities` you can only use entities. Any explosion that is NOT from an entity will be regenerated automatically. This is very frustrating for players trying to bed blast for ancient debris in the nether. So, currently the only way to prevent bed blasts from being reverted is disabling reversion for the entire world, which now means that Ghast fireballs will *not* revert. Please add beds as a config option so we no longer must choose between ghasts and bed blasts! Thanks!

**Comment by LlmDl** [comment]
Ok, so after looking into this and coding a whole system to handle BlockExplodeEvents caused by beds which do not return a bedblock as the exploding block, I have found that we cannot cancel a BlockExplodeEvent when it is caused by a bed. 

The best I can do is make it not revert the blocks, but since this is meant to stop people mining using bed explosions I don't think this will be a solution.

Question: How is it that players are surviving the bed explosions on your server?

**Comment by LlmDl** [comment]
I've gotten things working re: cancelling a bed explosion now. Must have just been really tired the other day.

I've been trying to decide whether this ends up being a "dont revert the bed explosions (and other defined blocks as well)" feature or if it will be a feature solely handling bed explosions in the nether.

If bed explosions don't revert, you end up with giant holes all over the nether. Does using the bed for mining rely on the ancient debris blocks being found while they revert back into existence?

**Comment by emkirsh** [comment]
Hi! Sorry for the delayed response. We are surviving by being smart. Right-clicking the beds from an angle with a block directly between us and the bed.

**Comment by emkirsh** [comment]
> Does using the bed for mining rely on the ancient debris blocks being found while they revert back into existence?

Ancient debris doesn't explode. It's like Obsidian.

**Comment by LlmDl** [comment]
So the request you're making is to have it so that the bed explosions do not regenerate at all and there's permanent giant holes?

**Comment by emkirsh** [comment]
yes.

**Comment by emkirsh** [comment]
but as a configurable option.
