### ISSUE TITLE
Suggestion: Teleport Outlaws to their towny spawn when they enter the Town.

### ISSUE THREAD

**Issue by SuperMayhemMan** [TownyAdvanced/Towny#4301]
There's a feature that allows you to outlaw a person from your town, but apart from being warned about it and sent to the town's jail on death (assuming they have one) they can still roam freely around the town for the most part. 

It would be nice to have the option for there to be a command to send outlaws to spawn or their own town, if they step on to the claimed area of the town they're outlawed in, so basically a blacklist command. For server owners that wouldn't want players to have this power, it could be a permission or enabled / disabled in config, whatever works better.

The main reason why I'm suggesting this is because the command would provide more security for your town, or if you just didn't want a specific person to be near your town for malicious reasons.

**Comment by LlmDl** [comment]
I can see this happening, and it doesn't run into the issue of people just repeatedly bumping into a town's border. 

This would default to off, and potentially it could use a warmup to give players a chance to turn back around within 5 seconds or so.
