### ISSUE TITLE
Suggestion: Add further customization for town withdrawal. 

### ISSUE THREAD

**Issue by MrNaspo** [TownyAdvanced/Towny#4302]
Right now, we can only allow withdrawal from town banks for all residents, no matter their rank in the town, or disable withdrawal completely without even the owner being able to withdraw. This poses some pretty obvious issues. So maybe in the config you can add the ability to allow only certain ranks in a town to be able to withdraw? That would be great and I believe it's much needed!

**Comment by LlmDl** [comment]
The townyperms.yml can have any town rank given the permission node to withdraw. This is something you can add yourself.

**Comment by MrNaspo** [comment]
Oh okay, my bad sorry! But I can't see any withdraw permission. How can I remove the ability to withdraw from default town members?

**Comment by TheMasteredTeddy** [comment]
The permission is a child node of towny.command.town.

         towny.command.town.withdraw

**Comment by MrNaspo** [comment]
Okay, so to deny that would I put like a minus in front of it or something? Like

>  -towny.command.town.withdraw

 ?

**Comment by TheMasteredTeddy** [comment]
I believe you'd be setting it to false

      towny.command.town.withdraw: false

**Comment by MrNaspo** [comment]
Ah okay. Thank you very much!

**Comment by MrNaspo** [comment]
@LlmDl just to make sure, does that seem right to you? the ": false". Because I've never seen something like that, I thought it would be a "-" so - -towny.etc. Nothing against Teddy, but I just want to make sure.

**Comment by LlmDl** [comment]
The negated node works. Townyperms doesn't take : false as an option.

**Comment by MrNaspo** [comment]
Okay. So it would be 
- -towny.command.town.withdraw 
In the configuration then right?

**Comment by MrNaspo** [comment]
The dash then minus... github formatted it weird

**Comment by LlmDl** [comment]
if you have a rank 
```
    - towny.command.town.*
    - -towny.command.town.withdraw
```
in the townyperms.yml they will receive all of the commands under /town except the negated permission node for the withdraw command.
