### ISSUE TITLE
Suggestion: Honorary/Temporary Members 

### ISSUE THREAD

**Issue by Haaruun-I** [TownyAdvanced/Towny#4303]
The suggestion is to have some way to grant permissions to people outside of a town, for example, grant architect rank to someone so they can do a paid build or maybe even assistant so they can help expand the town and claim new chunks.

The honorary membership is an alternative, like dual citizenship they can join the town and then be granted the perms that way.

A real-life example of why this would be useful :
I was hired to build a potion brewery under a shop plot, but it was claimed by the owner. I had to leave my current town, join that town, be given architect, then leave and rejoin and wait for a town assistant to come on and resell my plots to me.

**Comment by LlmDl** [comment]
In the above example, a personally-owned shop plot, the plot owner could add you as a friend and turn on friend build/destroy in the plot.

At the moment, storing town ranks can only be applied to town members.
