### ISSUE TITLE
Dynmap Towny not working

### ISSUE THREAD

**Issue by Slayerpax** [TownyAdvanced/Towny#4304]
### What steps will reproduce the problem?
1. Install the latest version of towny/dynmap/dynmap-towny
2. start server
3. type /dynmap reload 

### What is the expected output?
1. https://pastebin.com/tM2GzLsw
2. https://pastebin.com/ne1zPggK
3.

### What is your Towny version?
Do not say "latest".
Towny-0.96.2.0.jar
Dynmap-Towny-0.82.jar

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.2 Paperspigot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://controlc.com/1687e2be 
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Jx75u4Ck
3. Your townyperms.yml : https://pastebin.com/rQb46qe7
4. Your log's error : https://pastebin.com/tM2GzLsw,https://pastebin.com/ne1zPggK

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Use dynmap-towny 0.80 if you still use Towny 0.96.2.0
