### ISSUE TITLE
Wither explosions not being treated as explosions & not reverting blocks

### ISSUE THREAD

**Issue by AZFire1** [TownyAdvanced/Towny#4307]
### What steps will reproduce the problem?
1. Spawn a wither.
2. Have it do some damage to the world.
3. Notice it doesn't revert wither damage.

### What is the expected output?
1. For it to revert wither damage explosions as well.

### What is your Towny version?
0.96.2.17

### What is your spigot/craftbukkit version?
I use Purpur, https://mcpaste.io/cb793f8b1d9b8a5f

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) https://paste.helpch.at/uhoyacewiy.coffeescript:
3. Your townyperms.yml : https://paste.helpch.at/yajagefamu.php
4. Your log's error : No error.

(optional) If this is to do with permissions, 
5. Your permissions file : This does not do with permissions

(optional) If this is to do with chat,
6. Your chatconfig.yml : This does not do with chat.
7. Your channels.yml : This does not do with chat.

**Comment by LlmDl** [comment]
May be related to https://github.com/TownyAdvanced/Towny/issues/4300
