### ISSUE TITLE
Towny town rename causes town to be deleted and can not be read

### ISSUE THREAD

**Issue by ThorinEk** [TownyAdvanced/Towny#4309]
### What steps will reproduce the problem?
1. Update Towny from 0.95.2.1 to 0.96.2.3
2. Update regex pattern according to release notes
3. Rename Town "Jonkoping" to "Jönköping".
4. In the `towny/data/towns folder`, "Jonkoping.txt" was moved to `towny/data/towns/deleted`. I have put the file back and also tried renaming the file to "Jönköping.txt" but with no success. I am guessing the file needs to rename itself to "Jönköping.txt" automatically?
### What is the expected output?
1. Unicode symbols working correctly and ability to rename towns without issues.

### What is your Towny version?
0.96.2.3

### What is your spigot/craftbukkit version?
git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

1. Your full server startup from the logs\latest.log : https://pastebin.com/1qYyasdk
2. Your Towny config.yml : https://pastebin.com/wS1yUMQz
3. Your townyperms.yml : https://pastebin.com/G7b3wZ0X
4. Your log's error : https://pastebin.com/2hBzU9AD

**Comment by LlmDl** [comment]
The error in the startup is when your server tries to find the town 'Jönköping' which it is probably getting from in the towny\data\towns.txt. Can you confirm the town is renamed in the towns.txt?

Can you also confirm there is not a towny\data\towns\J_nk_ping.txt ?

**Comment by ThorinEk** [comment]
- The town was renamed correctly to "Jönköping" in towns.txt. 
- There is no such file as: towny\data\towns\J_nk_ping.txt

I tried to rename the town to Jonkoping again everywhere and that solved the problem with Safe Mode. However, since the townblocks had been updated to Jönköping, the entire town got deleted. I have solved the problem by removing the spawn/admin-town Jönköping and protecting it with a WorldGuard region instead. 

I could create a new "Jönköping" which worked fine but my economy plugin did not seem to handle it and threw this error on /t claim: https://paste.ubuntu.com/p/VKdrzJMPHs/

I have also reverted back to the old regex format in the config to automatically remove unicode characters from town names so the problem does not happpen again.
Since these issues yesterday, I have updated Towny to the latest version 0.96.2.17.

**Comment by LlmDl** [comment]
I'm guessing what happens is you rename the town, the economy account attempts to be changed to the new name which your eco plugin doesn't support, which results in the rename failing mid-way and the town gets deleted because it never gets to the point that the new town is saved.

**Comment by ThorinEk** [comment]
I see, atleast the economy plugin saved the correct name in the MySQL-database: "town-Jönköping". But I suppose other parts of the plugin is not compatible with unicode characters. Thanks for your assistance. I really appreciate Towny and the excellent release notes which allows updating from really old versions thanks to the good instructions.
