### ISSUE TITLE
Doesn't put money in the bank of the town

### ISSUE THREAD

**Issue by AleksandrMine** [TownyAdvanced/Towny#4313]
### What steps will reproduce the problem?
1. I enter the command / t deposit 1000

### What is the expected output?
1. Writes the following to the console 
2. Instead of the money being transferred to the bank of the town, it is transferred to the bank of the resident
3. Writes the following to the console - https://gist.github.com/AleksandrMine/875dd6c923eee653b58ea9a5459f2d2d#file-warn-L4

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
paper spigot 1.16.2

**Comment by LlmDl** [comment]
Skipped the form. Resubmit.
