### ISSUE TITLE
Doesn't put money in the bank of the town (By form)

### ISSUE THREAD

**Issue by AleksandrMine** [TownyAdvanced/Towny#4314]
### What steps will reproduce the problem?
1. I enter the command / t deposit 1000

### What is the expected output?
1. Instead of the money being transferred to the bank of the town, it is transferred to the bank of the resident
2. Writes the following to the console - https://gist.github.com/AleksandrMine/875dd6c923eee653b58ea9a5459f2d2d#file-warn-L4

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
paper spigot 1.16.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : help.zip
2. Your Towny config.yml (if using MySQL please remove password,) : dont use
3. Your townyperms.yml : help.zip
4. Your log's error :  help.zip

(optional) If this is to do with permissions, 
5. Your permissions file : standart
[help.zip](https://github.com/TownyAdvanced/Towny/files/5219623/help.zip)

(optional) If this is to do with chat,
6. Your chatconfig.yml : help.zip
7. Your channels.yml : help.zip

**Comment by LlmDl** [comment]
Looks like the economy plugin doesn't support the older vault methods to handle fake player accounts. Can you link me the source code of the economy plugin you're using?

**Comment by LlmDl** [comment]
Or your economy plugin doesn't handle unicode characters like you have in your town name.

**Comment by AleksandrMine** [comment]
my economy plugin https://www.spigotmc.org/resources/expconomy-1-8-8-1-14-4-buy-things-with-exp.71824/

**Comment by LlmDl** [comment]
Does it work when you use a plain english name for your town?

**Comment by AleksandrMine** [comment]
no

**Comment by LlmDl** [comment]
The plugin likely doesn't work with the deprecated vault methods towny uses then (I couldn't find the source code.) You could ask the plugin author to add Towny support. If they want they can join the discord for any help they need.

**Comment by AleksandrMine** [comment]
That is, if I use another economic plugin, everything will work?

**Comment by LlmDl** [comment]
Yes.

**Comment by AleksandrMine** [comment]
Yes, everything worked, it's a pity of course that exp doesn't work :(

**Comment by LlmDl** [comment]
TheNewEconomy might do exp economy, I don't know for sure.
