### ISSUE TITLE
Cannot create a town

### ISSUE THREAD

**Issue by nuvx** [TownyAdvanced/Towny#4325]
### What steps will reproduce the problem?
1. trying to create a town using /town new nuvx
2. cannot use /confirm or /cancel

### What is the expected output?
1. While OPed when trying to do '/confirm' to confirm that you want to create a town, it says; 'You have nothing to confirm!'
2. If not OPed it says You do not have permission to use that command for /confirm and /cancel

### What is your Towny version?
Towny-0.96.2.0

### What is your spigot/craftbukkit version?
Paper 1.16.3 1.16.3 #191

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/2ZHa2SvQ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/kYJixkMj
3. Your townyperms.yml : https://pastebin.com/AsivVYWv
4. Your log's error : no error

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Which Towny nodes have you given/taken away in your luckperms?

**Comment by nuvx** [comment]
The only two nodes I have added are towny.claimed.* and towny.command.townyadmin.* to some staff ranks. Other than those two I haven't added or taken away any towny nodes to any ranks (groups) or users in luckperms.

**Comment by LlmDl** [comment]
When you get prompted to use /confirm, what happens when you use /towny:confirm

**Comment by nuvx** [comment]
That worked, I tried it while OPed and while not Oped, worked both times.

**Comment by LlmDl** [comment]
Something has overridden it. If you update to the pre-releases we've already made the clickable messages force using /towny:confirm.

**Comment by nuvx** [comment]
Thank you
