### ISSUE TITLE
Messages gets duplicated on both general and local chat. Using DeluxeChat

### ISSUE THREAD

**Issue by Skiper132** [TownyAdvanced/Towny#4329]
### What steps will reproduce the problem?
1. Typing a message on the general channel

### What is the expected output?
1. When a message is sent, it should only show on the selected channel.

### What is your Towny version?
Towny-0.96.2.17
TownyChat-0.79
DeluxeChat 1.16.1-dev (recommended by the developer)

### What is your spigot/craftbukkit version?
paper-254

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/gv68SY3X
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Pfqx4pXF
3. Your townyperms.yml : https://pastebin.com/TbinsJTg
4. Your log's error : No errors on log

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/xTGcqam2
7. Your channels.yml : https://pastebin.com/BQXd0sc2

**Comment by LlmDl** [comment]
This was solved according to you on teh discord, closing the ticket.
