### ISSUE TITLE
Question: Order of taxes

### ISSUE THREAD

**Issue by aco4** [TownyAdvanced/Towny#4330]
**Ask your question as best as you are able:**
I want my residents to be taxed with a 1% tax plus a $15 plot tax. My question is, which tax will be calculated first? Depending on which one is taxed first, the tax rate varies greatly.

In fact, if the plot tax is taken first, then the balance of my residents will approach $0 but never reach it (mathematically).

**Comment by LlmDl** [comment]
Residents pay the town tax first, then the plot taxes second.
