### ISSUE TITLE
Question: Regeneration on claims

### ISSUE THREAD

**Issue by SundraLOL** [TownyAdvanced/Towny#4331]
**Ask your question as best as you are able:**
Hello, I disabled regeneration within towny's config but its still reverting the claims to how it was before building or destruction. How do I fix this?

**Comment by AZFire1** [comment]
Would you be able to send config?
Maybe you accidentally clicked the wrong button while uploading the file through your FTP client (I've accidentally done that before)
Also, did you restart after uploading the file, or at least reload the file with /ta reload config (I recommend restarting for bigger features such as this for basically any plugin)

**Comment by LlmDl** [comment]
Use '/tw toggle revertunclaim' to turn the feature off.
To stop already progressing regenerations stop the server delete the towny\data\regen.txt file.

The New World Settings section of the [config](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) is only default settings for new worlds, it's explained in the config section comments, the [install guide](https://github.com/TownyAdvanced/Towny/wiki/Installation#configuring-existing-worlds) and the [how towny works](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#reverting-unclaimed-townblocks-to-their-original-state-on-unclaim) page. You need to be using the /tw toggle commands or manually setting the worldname.txt file.

**Comment by SundraLOL** [comment]
Also how do I disable claiming in the nether
