### ISSUE TITLE
Townblock database problem

### ISSUE THREAD

**Issue by ZFreddyy** [TownyAdvanced/Towny#4334]
### What steps will reproduce the problem?
1. Any reload of the server
2. Any restart of the server
3. Any toggling off and on of the server

### What is the expected output?
1. Town claimblocks should be in data and be available as claimed before the reload
2. Homeblocks and spawn should still be available
3.

### What is your Towny version?
Do not say "latest". 

I have tried 0.96.2.0 & 0.96.1.1. Problems remains on both versions.

### What is your spigot/craftbukkit version?
Do not say "latest".

Paper 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/hmSyNUmB
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/WdwvVc13
3. Your townyperms.yml : (note i use LuckPerms) https://pastebin.com/r4PqZhyh
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

I know previous ticket were created with this same subject and would be fixed in 0.96.2.0, but I am still having this problem both with that version and 0.96.1.1. Also not, if it is of any importance, we are using a Earth map which was upload to our server.pro database. 

Thanks

**Comment by LlmDl** [comment]
0.96.1.1 introduced the new TownBlock savign/loading code. It is a very early pre-release and should not be used any more. 0.96.2.0 should be used (unless you want to use the latest pre-release 0.96.2.18.)

Your instructions for reproducing are very unclear. 

I understand on every stop/restart of the server you're having something happen. 

You're saying you have no claimblocks in data and all townblocks are unclaimed?
You're saying homeblocks are not saved at all and are unclaimed?
You're saying spawn points are not saved at all but the townblocks are still claimed?

**Comment by ZFreddyy** [comment]
Thank you for the quick reply. Here is an example. 

**Before /reload:**
[New Cairo (Settlement)]
Town Size: 2/8 [Home: 113, -117]
Spawn is set and I can do /t spawn

**After /reload:**
[New Cairo (Settlement)]
Town Size: 0/8 [Home: none]
Spawn unavailable (homeblock doesn't exist)

Town balance is ok though, economy is fine. 

One thing curious is when looking at this page: https://github.com/TownyAdvanced/Towny/releases/tag/0.96.2.0 you guys mention that the directory for townblocks data should be: towny\data\townsblocks\WORLDNAME\deleted\TOWNNAME\ folder

Mine looks more like this: Root > plugins > Towny\data\townblocks**\earth\earth\**deleted
Notice the double worldname... possible issue with directory? If so how to fix?

**Comment by LlmDl** [comment]
whats your root folder looks like. Are your worlds all stored inside of a earth folder in the root folder?

**Comment by ZFreddyy** [comment]
Is this the information you are looking for?

![image](https://user-images.githubusercontent.com/71838133/94171336-24256480-fe5f-11ea-8c77-dac25a1f876c.png)

![image](https://user-images.githubusercontent.com/71838133/94171362-2edff980-fe5f-11ea-88d9-b9d116f97341.png)

![image](https://user-images.githubusercontent.com/71838133/94171401-37d0cb00-fe5f-11ea-8958-0d694c28727c.png)

**Comment by LlmDl** [comment]
From your startup: `-------- World Settings For [earth/earth] --------`

You should probably have put your 3 world folders directly in the root folder, not in a 'earth' subfolder. The world names are all being passed through with the two folders. This will confuse Towny, probably anything else that saves based on world.

**Comment by ZFreddyy** [comment]
It does seem like this has fixed the issue. Will run some more tests with other players and will come back and let everyone know that the issue is indeed resolved. 

Thank you for your help!

**Comment by ZFreddyy** [comment]
Everything has been running smoothly since moving the world folders to the root directory. 

Thank you again.

**Comment by LlmDl** [comment]
Cheers, have fun.
