### ISSUE TITLE
Towny alliance messages are broken

### ISSUE THREAD

**Issue by generalunderscore** [TownyAdvanced/Towny#4335]
### What steps will reproduce the problem?
1. Assume I am the leader of the nation of Brazil, and the nation of Chile sends me an ally request.
2. However, in my chat, I get the message "The nation of Brazil has requested an alliance with you".
3. I can still do /n ally accept chile and I will ally with the correct nation, its just that you dont know what nation sent you the ally request.
4. Doing /n ally received will list the correct nation name. Additionally, all other messages (i.e. "You are now allied with this nation" or "The request for an alliance has been sent to this nation") work well and display the correct nation.

![image](https://user-images.githubusercontent.com/71852766/94204747-210f9000-fec2-11ea-8706-3e4065a5cc07.png)
[I am the leader of Brazil]

### What is the expected output?
1. If I get an ally request from Chile it should say "You have been requested to ally Chile".

### What is your Towny version?
0.96.2.17

### What is your spigot/craftbukkit version?
We use TUnity: TUinity version git-Tuinity-"f663f6e" (MC: 1.16.2) (API version 1.16.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/g6s6WjDc
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/5EG1AvzX
3. Your townyperms.yml : https://pastebin.com/C07We1Km
4. Your log's error : No error appears in the console. This is what happens when I send and accept the request with debug mode on: https://pastebin.com/CxcwM7xx

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/Ci14A6Rp
7. Your channels.yml : https://pastebin.com/9Jyi8UmX

**Comment by LlmDl** [comment]
This was all fixed in 0.96.2.18. Please re-test using that version.

**Comment by generalunderscore** [comment]
It works, thanks.
