### ISSUE TITLE
Does UltimateEconomy work alongside TownyAdvanced?

### ISSUE THREAD

**Issue by cjnelson00** [TownyAdvanced/Towny#4337]
Although I do not have the Ultimate Economy Townworld set to my world, I am having troubles with TownyAdvanced in my world. When I go to type in /t add (town name) and press enter, nothing happens and nothing appears in the chat. (I have followed the other steps for setup for TownyAdvanced and it appears to be working minus this particular problem).

This may be a problem with TownyAdvanced and Ultimate Economy having very similar commands for town creation, but I am not sure.

### What steps will reproduce the problem?
1. Entering the command /t new (town name)
2. Entering the command /town new (town name)      [this command gives a separate response in game chat related to UltimateEconomy's town system]

### What is the expected output?
1. A town to be created
2. (or at least an error message to appear in game chat)

### What is your Towny version?
Do not say "latest".

Towny 0.96.2.0

### What is your spigot/craftbukkit version?
Do not say "latest".

Spigot 1.16.3

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/ve7MF7Ss
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/yzJHWue8
3. Your townyperms.yml : https://pastebin.com/h0Qb6KJT
4. Your log's error : https://pastebin.com/cp1vvB8J

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Add vault and retest:
```
24.09 18:53:34 [Server] Server thread/WARN Error: No compatible Economy plugins found. Install Vault.jar with any of the supported eco systems.
24.09 18:53:34 [Server] Server thread/WARN Error: If you do not want an economy to be used, set using_economy: false in your Towny config.yml.
```

Knowing now that ultimate_economy is the one with the townsystem built into it: I wouldn't be surprised if you run into other issues. Get vault and see if Towny will connect to ultimate_economy, show me the new log if your commands do not work.

**Comment by cjnelson00** [comment]
It works, thank you for the help!

(Quick question though- now that i have claimed my first few spaces in the game, and realized that 16 by 16 isnt a whole lot, if i change the config settings will it be problematic without first deleting my town and then reclaiming land? I am the only town on the server as of right now)

**Comment by LlmDl** [comment]
No you can change that anytime (`town_block_ratio`), it will affect existing towns but if it goes to a higher number no existing towns will find themselves over-claimed.

**Comment by cjnelson00** [comment]
So if i want the plot size (town_block_size) to be 32x32, i should change that while also making the town_block_ratio 16? I am a little confused about town_block_ratio

**Comment by cjnelson00** [comment]
Im seeing now that ratio is just related to plots for town residents, so should i delete my town and then restart with the new settings, then claim?

**Comment by LlmDl** [comment]
Sorry I misread you. You want to set the town_block_size only one time. It will affect existing claims, 32x32 would move your claims over.
