### ISSUE TITLE
Server crashes when deleting a city with large territories!

### ISSUE THREAD

**Issue by FelsonMW** [TownyAdvanced/Towny#4338]
### What steps will reproduce the problem?
1. For example: a player privatizes many territories.
2. Plays with friends, everything is fine
3. I decided to delete the city, delete it and the server crashes. As we understood, this is due to the fact that the player conquered a lot of territories, however, as I was told, this problem was fixed on a similar server.
4. After a reboot, the city is not always deleted (a few chunks are deleted)

### What is the expected output?
1. I want the server not to crash. When a player delete a city with large territories.

### What is your Towny version?
0.96.2.15 (we think about switching to 0.96.2.18, but it makes no sense, this problem cannot be solved)

### What is your spigot/craftbukkit version?
Paper1.16.1 and Paper1.15.2 (Both there and there, the same mistake).

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/qWVB7KgH
3. Your townyperms.yml : https://pastebin.com/D1MdpLky
4. Your log's error : 

[config.zip](https://github.com/TownyAdvanced/Towny/files/5283149/config.zip)
[townyperms.zip](https://github.com/TownyAdvanced/Towny/files/5283152/townyperms.zip)
![dasdasdй](https://user-images.githubusercontent.com/71789017/94275382-91182780-ff4f-11ea-9c29-13695f971dca.png) (Screenshot when deleting a city (crash))

**Comment by LlmDl** [comment]
Show me the towny\data\worlds\WORLDNAME.txt file please.

**Comment by FelsonMW** [comment]
https://pastebin.com/rHEVUQjs

**Comment by LlmDl** [comment]
You have `usingPlotManagementRevert=true` which means that when a large town is deleted, those townblocks are all reverted to their pre-claimed status and appearance. Your server may not be able to handle it all at once. 

What did you do to delete the town?

**Comment by FelsonMW** [comment]
That's it, I don't need anything else from you. Thank you so much for those. support! I got it!
