### ISSUE TITLE
Towns cannot claim the last townblock

### ISSUE THREAD

**Issue by generalunderscore** [TownyAdvanced/Towny#4342]
### What steps will reproduce the problem?
1. Towns that are 1 claim away from the limit (ex. towns that have claimed 25/26 chunks) cannot claim the last chunk.
2. Doing so results in the message "Not enough available town blocks to claim this selection" appearing.
3. 

### What is the expected output?
1. The last townblock should be claimed.
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.2.18

### What is your spigot/craftbukkit version?
Do not say "latest".
We use TUnity: TUinity version git-Tuinity-"f663f6e" (MC: 1.16.2) (API version 1.16.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
Your full server startup from the logs\latest.log : https://pastebin.com/g6s6WjDc
Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/5EG1AvzX
Your townyperms.yml : https://pastebin.com/C07We1Km
Your log's error : No error appears in the console, even with debug mode on. It just says that the command "/t claim" was run, that's it.

(optional) If this is to do with permissions, 
Your permissions file :

(optional) If this is to do with chat,
Your chatconfig.yml :
Your channels.yml :

**Comment by LlmDl** [comment]
I just tested making a town from scratch, made a nation and did `/t claim auto` this claimed 17/18 townblocks (instead of all 18,) but I was still able to manually claim the last townblock. So there's probably something going on.
