### ISSUE TITLE
Permission towny.wild

### ISSUE THREAD

**Issue by AndreyADeveloper** [TownyAdvanced/Towny#4343]
After installing Towny on my Minehut server, my users continue getting an issue with breaking blocks in the wild. They get the error "Not allowed to Destroy in the wild" and "Not allowed to Switch in the wild." Even after adding it into Permissions.yml, they still get the error.

**Comment by AndreyADeveloper** [comment]
![image](https://user-images.githubusercontent.com/71163171/94378096-995d9780-00f4-11eb-96c1-6c2eb1ab954e.png)

**Comment by LlmDl** [comment]
put towny.wild.* in the nomad group in the townyperms.yml

**Comment by AndreyADeveloper** [comment]
Hi there,

I've attempted that, however, it still did not work.

**Comment by LlmDl** [comment]
File a bug report.
