### ISSUE TITLE
Minehut towny.wild permission not working

### ISSUE THREAD

**Issue by AndreyADeveloper** [TownyAdvanced/Towny#4344]
### What steps will reproduce the problem?
1. Installing the Towny Plugin on Minehut and attempting to enable towny.wild

### What is the expected output?
1. Users unable to break/use blocks in wild

### What is your Towny version?
0.95.2.0

### What is your spigot/craftbukkit version?
![image](https://user-images.githubusercontent.com/71163171/94456095-6c0afb00-0181-11eb-8879-97177e8e9dc9.png)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/JzfeQJwa
2. https://pastebin.com/VXZMTFKR
3. https://pastebin.com/eTij9p37
4. Your log's error : There is no log error as I am knowing of

(optional) If this is to do with permissions, 
5. Your permissions file : My permissions file is empty.

**Comment by LlmDl** [comment]
you did not add ` - towny.wild.*` to the townyperms.yml like is explained on the Permission Nodes wikipage.

**Comment by AndreyADeveloper** [comment]
Thank you, it all works now! For some reason, when I did that the first time, it had not worked. Thank you again!
