### ISSUE TITLE
Towny unclaim rollback works but not on every block?

### ISSUE THREAD

**Issue by EasyMcCheesyMC** [TownyAdvanced/Towny#4346]
On my server i have denied Towny unclaim rollback, but it still rollbacks signs and redstone?

After i denied Towny unclaim rollback, signs and redstone was still rollbacked, nothing else. 
Is this a bug or something i can fix by commands/config ?? 

Please help!

- Adrian H.

**Comment by LlmDl** [comment]
Signs and redstone fall under the PlotManagementDelete feature, which is enabled in the world files at `usingPlotManagementDelete`

**Comment by EasyMcCheesyMC** [comment]
oh, it works! Thank you for the help!
