### ISSUE TITLE
Error: An Internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by Mikie3** [TownyAdvanced/Towny#4347]
### What steps will reproduce the problem?
1. command: /town new tes
2. command: /confirm
3.

### What is the expected output?
1. An Internal error occurred while attempting to perform this command
2.
3.

### What is your Towny version?
Towny-0.96.2.0-for-1.12.2.jar

### What is your spigot/craftbukkit version?
Spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/YyK6prQs
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/RHkHzybx
3. Your townyperms.yml :
https://pastebin.com/E9iyG86d
4. Your log's error : 
https://pastebin.com/sxFc4mUk

(optional) If this is to do with permissions, 
5. Your permissions file : 
No. I use LuckPerms.

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I have not seen anyone using CraftConomy3 in years. The error is on the CC3 side of things. If that plugin is under active development again, show the plugin author your error. Otherwise, choose a different eco plugin.

**Comment by Mikie3** [comment]
> I have not seen anyone using CraftConomy3 in years. The error is on the CC3 side of things. If that plugin is under active development again, show the plugin author your error. Otherwise, choose a different eco plugin.

which eco plugin can you recommend?

**Comment by LlmDl** [comment]
TheNewEconomy, HellConomy, HyperConomy, iConomy5 TownyEdition, really anything that isn't essentials economy or aconomy.

**Comment by Mikie3** [comment]
Thank you
