### ISSUE TITLE
Towny locked in Safe Mode every day

### ISSUE THREAD

**Issue by Krakenazo** [TownyAdvanced/Towny#4352]
### What steps will reproduce the problem?
1. New day in Towny
2. Deletes Town or resident.
3. Towny locked in safe Mode.

### What is the expected output?
1. New in day in Towny.
2. Delete Town or resident.
3. Database synchronizes. 

### What is your Towny version?
Do not say "latest". 0.96.2.11

### What is your spigot/craftbukkit version?
Do not say "latest". PaperSpigot 1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/zAhBTm6L
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/ciLyC9TK
3. Your townyperms.yml : https://pastebin.com/tqhzsnjv
4. Your log's error : https://pastebin.com/eqTSfJm1

**Comment by LlmDl** [comment]
You should not still be on 0.96.2.11. Update to 0.96.2.19 and this should not happen any longer.

**Comment by Krakenazo** [comment]
Okay, I'll try.

**Comment by Krakenazo** [comment]
Now this happens:

[Towny]: Loading Error: Could not properly read nation data.

**Comment by LlmDl** [comment]
Can you get me the full startup with debug_mode set to true in the config?
