### ISSUE TITLE
how do I give myself (as an admin) money to start a town/nation?

### ISSUE THREAD

**Issue by SatanSoul38** [TownyAdvanced/Towny#4355]
I have started with zero bal, and I can't figure out how to give myself (or just generally earn) any money. I would really like to know how to give money, and how (if possible) to set it so that a player gets a set amount of money when they join.

**Comment by LlmDl** [comment]
That would be up to your economy plugin. They will usually have admin commands to grant money to any player you want. 

Economy plugins usually also have default starting balances.

Other plugins like a jobs plugin would allow your players to earn money.

**Comment by SatanSoul38** [comment]
ah, I see. thanks. any recommendations for a jobs plugin?

**Comment by LlmDl** [comment]
I don't have any experience with them but I hear that Jobs Reborn is popular.
