### ISSUE TITLE
Question: how to know item use ids in a mod

### ISSUE THREAD

**Issue by 3094300238** [TownyAdvanced/Towny#4359]
**Ask your question as best as you are able:**
I noticed that someone can place liquid using a bucket, and the liquid is added by a mod.
so how can i know its item_use_ids?

**Comment by LlmDl** [comment]
You can add the item to the itemuse_ids in the config.

**Comment by 3094300238** [comment]
but the question is, how can i know the item_use_ids of an item?

**Comment by LlmDl** [comment]
You might get the name of the item if you hover over it after turning on advanced tooltips using F3+h. Otherwise maybe talk to the mod author about what they named their item.
