### ISSUE TITLE
Server permission help

### ISSUE THREAD

**Issue by Woofer21** [TownyAdvanced/Towny#4361]
so i have towny on a server have the line 
 unclaimed:
  unclaimed_zone_build: 'false'
  unclaimed_zone_destroy: 'false'
  unclaimed_zone_item_use: 'false'
  unclaimed_zone_ignore: SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LEAVES,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,LOG_2,VINE,NETHER_WARTS,COCOA
  unclaimed_zone_switch: 'false'

changed to 
unclaimed:
  unclaimed_zone_build: 'true'
  unclaimed_zone_destroy: 'true'
  unclaimed_zone_item_use: 'true'
  unclaimed_zone_ignore: SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LEAVES,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,LOG_2,VINE,NETHER_WARTS,COCOA
  unclaimed_zone_switch: 'true'

member still cant break blocks outside of a town/nation what am i doing wrong
cus clearly im doing something wrong

**Comment by LlmDl** [comment]
Helped you on the discord.
