### ISSUE TITLE
Towny Chat Not Enabled

### ISSUE THREAD

**Issue by JediM4ster** [TownyAdvanced/Towny#4362]
### What steps will reproduce the problem?
1. Loading the server

### What is the expected output?
1. Towny Chat enabled again

### What is your Towny version?
Towny 0.96.2.0 and towny chat version 0.79.

### What is your spigot/craftbukkit version?
1.16.3 (paper)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/RNHhdgMi
2. Your Towny config.yml (if using MySQL please remove password,) : Could not paste
3. Your townyperms.yml : https://pastebin.com/G86E0SaK
4. Your log's error : https://pastebin.com/UqwSFKvB

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/nyT6fPcw
7. Your channels.yml : https://pastebin.com/HFVfkwUx

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/TownyChat/releases/tag/0.79 says it's for 0.96.2.17 and newer. Use TownyChat 0.72.
