### ISSUE TITLE
Players unable to pay taxes were kicked even if them got enough money

### ISSUE THREAD

**Issue by emanondev** [TownyAdvanced/Towny#4364]
Nearly 100 player got kicked from their town after updating from 96.2.0 to latest when tax were collected for the first time, they all got enough money to pay taxes, it happened only on some towns.

I have an hypothesis, on my config towns have 200k bank limit, those town where players were kicked had already reached bank limit, and only players who were not extempt from taxes were kicked on console it says they were not able to pay for taxes

actually if a town has reached bank limit it's not possible to deposit anymore money, is it possible that the plugin was unable to put collected money by residents on the town because the limit was reached and counted failed transactions as players were unable to pay?

server is 1.15.2 latest towny version was used

**Comment by LlmDl** [comment]
How did it go with testing that jar I gave you @emanondev ?
