### ISSUE TITLE
TownyChat throws errors and posts strange message to chat when a user with an invalid username (such as a user from GeyserMC/Floodgate with a symbol prefix) tries to send a message

### ISSUE THREAD

**Issue by Technophilus** [TownyAdvanced/Towny#4369]
### What steps will reproduce the problem?
1. Create a PaperSpigot server, install Towny and TownyChat. Set up behind Velocity proxy.
2. Install Geyser and Floodgate on Velocity 1.1.0+ proxy. Set up the proxy according to the guide with BungeeGuard.
3. Set the Floodgate user prefix to '+'.
4. Join with a Bedrock user.
5. Try to chat. You will get a console error and a strange message instead of the chat message:
`{worldname}{townytagoverride}{townycolor}{permprefix}{group} {townyprefix}{modplayername}{townypostfix}{permsuffix}&f: {msg}`

### What is the expected output?
1. `[g] [world] default +Technophilus: <Message Here>`

### What is your Towny version?
Towny 0.96.2.0
TownyChat 0.72
TownyNameUpdater 5.0

### What is your spigot/craftbukkit version?
Paper 1.16.3 (Build 228)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/8Xji7nQr
**This is a clean, new server. These files are just the defaults.**
2. Your Towny config.yml (if using MySQL please remove password): https://gist.github.com/Technophilus/4dd704dd37181a3cf996d3f41789e19d (pastebin wouldn't let me upload it)
3. Your townyperms.yml: https://pastebin.com/84P42c3f
4. Your log's error: https://pastebin.com/cBV89KiW (this happens even if the user is manually registered)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/0urRAGfY
7. Your channels.yml: https://pastebin.com/ZudeHYum

**Comment by LlmDl** [comment]
If you are going to put non-vanilla characters into Minecraft names you need to allow players who join to have those name in the Towny database, by allowing them in the regex in the Towny config.

**Comment by Technophilus** [comment]
Thank you. I added some symbols to the regexes and it works now. For anyone who has this same issue, change the regex here to add your symbols:
```
regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\+\$\*\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\+\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```
