### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to TownyChat0.72

### ISSUE THREAD

**Issue by ZFreddyy** [TownyAdvanced/Towny#4371]
### What steps will reproduce the problem?
1. Multiple messages will create that error message in the console
2.
3.

### What is the expected output?
1. I would expect TownyChat not to create multiple error messages
2.
3.

### What is your Towny version?
TownyChat 0.72

### What is your spigot/craftbukkit version?
Paper 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/bk8mjEtt
3. Your townyperms.yml : https://pastebin.com/TcHTbqpx
4. Your log's error : https://pastebin.com/y4RyZm28

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/jxQrbtUF
7. Your channels.yml : https://pastebin.com/5Q3UG796

This has only started since we move the server from one host to another. Maybe some settings have been reset in the process but I can't put my finger on it. Thank you!

**Comment by LlmDl** [comment]
Add your startup if you want help on this.

**Comment by ZFreddyy** [comment]
Full server startup: https://pastebin.com/CmeTGBJm

Sorry forgot about that one.

**Comment by LlmDl** [comment]
That was not the full server startup.
