### ISSUE TITLE
java.lang.NullPointerException when trying to create a new town or nation 

### ISSUE THREAD

**Issue by octillery143** [TownyAdvanced/Towny#4372]
### What steps will reproduce the problem?
1.type in commands /town new [name] or /nation new [name]
2.
3.

### What is the expected output?
1.to create a nation or a town 
2.
3.

### What is your Towny version?
Do not say "latest".
towny 0.96.2.19

### What is your spigot/craftbukkit version?
Do not say "latest".
papermc build 168 

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/rVJMvLgq
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/9jcHiRLd
3. Your townyperms.yml : https://pastebin.com/vSd3PiCy
4. Your log's error : https://pastebin.com/kvz8WQAu

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
In your log:
```
[15:38:30] [Server thread/INFO]: [Towny] Warning: No compatible Economy plugins found. Install
[15:38:30] [Server thread/INFO]:         Vault.jar or Reserve.jar with any of the supported eco
[15:38:30] [Server thread/INFO]:         systems. If you do not want an economy to be used, set
[15:38:30] [Server thread/INFO]:         using_economy: false in your Towny config.yml.
```
