### ISSUE TITLE
Citizen incompability print stack trace on console

### ISSUE THREAD

**Issue by emanondev** [TownyAdvanced/Towny#4375]
### What steps will reproduce the problem?
1. get Citizen
2. put an npc inside a town
3. restart the server ( / let the npc walk inside/outside the town?) 

### What is the expected output?
1. towny should check if target entity is a player but has no resident object / plugin should check if player is an npc

### Versions?
Citizen version 2.0.27-SNAPSHOT (build 2133)
Towny version  0.96.2.20
Server version Paper version git-Paper-229 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
https://pastebin.com/9cbtwj0z

**Comment by LlmDl** [comment]
We already have a test to make sure the player is a resident, are some of these NPCs using the same name as actual players with resident data?

**Comment by emanondev** [comment]
Yes
