### ISSUE TITLE
Hello! I have the same balance of cities in one nation

### ISSUE THREAD

**Issue by KevstaRU** [TownyAdvanced/Towny#4379]
Good time of day
I have a problem, my friends tell me that this is a bug

In General, in towny, two cities in the same nation are located, but their city balance is the same...
![towny1](https://user-images.githubusercontent.com/73141732/96514709-b1948280-126c-11eb-93c5-a6ee7f892981.jpg)

for verification, I will put 1 coin in the balance of one:
![towny2](https://user-images.githubusercontent.com/73141732/96514719-b48f7300-126c-11eb-90be-40ab540d1aaa.jpg)

help please

**Comment by LlmDl** [comment]
This happens when your economy plugin cannot read the unicode characters in your Town name. This means all of the seven-letter towns using cyrillic end up sharing the same account because the economy plugin cannot tell the difference.
