### ISSUE TITLE
Suggestion: KeepInventory during War.

### ISSUE THREAD

**Issue by Drainer2002** [TownyAdvanced/Towny#4380]
I suggest having a **keep inventory** during wars  there will be 2 types

like if it is a **flagWar**:
**keep inventory only to the towns which are involved in the war**
there should be options like these below for example **keep_inventory_on_death_in_town_during_flag_war** same for eventwar

   If People should keep their inventories on death in a town.
   Is not guaranteed to work with other keep inventory plugins!
  **keep_inventory_on_death_in_town: 'false'**
 
   If People should keep their inventories on death in their own town.
   Is not guaranteed to work with other keep inventory plugins!
  **keep_inventory_on_death_in_own_town: 'false'**
 
  If People should keep their inventories on death in an allied town.
  Is not guaranteed to work with other keep inventory plugins!
  **keep_inventory_on_death_in_allied_town: 'false'**

while for **event war**:
**keep inventory for all towns except the ones who are in neutral.**

I don't think **keep_exp** is a good idea to add.

**Comment by LlmDl** [comment]
I can see this becoming one of the common-war-settings that would be applicable to any of the various war types.

**Comment by LlmDl** [comment]
EventWar now has a setting that overrides Towny's keeping-inventory option.
