### ISSUE TITLE
New Day results in catastrophic money loss for towns 

### ISSUE THREAD

**Issue by JustAMatt** [TownyAdvanced/Towny#4387]
### What steps will reproduce the problem?
1.Use Towny 0.96.2.22
2.Let a new day happen
3.Rip?

### What is the expected output?
Some towns that previously had 120k to 420k went down to bankruptcy within a day. The only connection I could find between towns that went under and those that didn't was if they had a tax percent or not.

### What is your Towny version?
Towny 0.96.2.22

### What is your spigot/craftbukkit version?
Purpur 802 (1.16.3)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://paste.gg/p/anonymous/8cb5dd538d474777aa578f43f9630561
2. Your Towny config.yml (if using MySQL please remove password,) : https://paste.gg/p/anonymous/e074ab816e5f41b7bbeee467b652cd0b
3. Your townyperms.yml : https://paste.gg/p/anonymous/5084a9e7e3524373856ff6b219f00a3f
4. Your log's error : https://cdn.discordapp.com/attachments/737088038622199809/769660938684071957/unknown.png

(optional) If this is to do with permissions, 
5. Your permissions file : no

(optional) If this is to do with chat,
6. Your chatconfig.yml : no
7. Your channels.yml : no

**Comment by LlmDl** [comment]
Fairly sure this is fixed in 0.96.2.23, if anyone on 0.96.2.22 sees this make sure you update.

**Comment by LlmDl** [comment]
This was confirmed to be from the bug introduced in .22 that was already fixedin .23.
