### ISSUE TITLE
Named Mobs Despawning

### ISSUE THREAD

**Issue by BetaBurnt** [TownyAdvanced/Towny#4389]
### What steps will reproduce the problem?
1. Enable "mob_removal_skips_named_mobs:" in the config.yml
2. Claim a town, toggle mob spawning on (town or plot), spawn a mob and name it
3. Disable mob spawning again, the mob despawns after a short while.

If it's a mob-specific issue it was a named Piglin.

### What is the expected output?
Named mobs, of any type, not being removed on town land whether mobs are disabled or not.

### What is your Towny version?
0.96.3.0

### What is your spigot/craftbukkit version?
This server is running Paper version git-Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/HucfuFv5
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/gmeN0HvT
3. Your townyperms.yml : https://pastebin.com/t6TrAhae
4. Your log's error : N/A

**Comment by LlmDl** [comment]
You're disabling the mob spawning using a /plot or /t or /tw command ? What are the exact instructions please.

**Comment by BetaBurnt** [comment]
/t or /plot - it makes no difference. If you enable mobs via `/t toggle mobs` and place the named mob in the claimed area and then disable mobs again with `/t toggle mobs` the named mob despawns after a short while rather than be ignored.

Same for enabling just on a specific plot with `/plot toggle mobs`, place the named mob and then disable mobs in that plot again - despawns rather than be ignored.

**Comment by LlmDl** [comment]
Ok, I just wanted to be sure. The `mob_removal_skips_named_mobs` option in the config was only ever made to work using the MobRemovalTimerTask I think. I'll see if it's possible to make it work on the other part.

**Comment by LlmDl** [comment]
Ok, I took a look and there is only the MobRemovalTimerTask doing any removing, and it is definitely not removing named mobs. What name is the piglin being given? What is giving the piglin a name?

**Comment by BetaBurnt** [comment]
And now I can't get it to happen... Even though I've changed nothing at all on the server and previously got it to happen consistently every time I tried it...

Previously:
Tried with naming it with a nametag (not done via a plugin or anything, basic MC nametag) and naming the spawn egg itself so it spawns with a name - both times just named "&6STAY ALIVE"

Just:
No different... figured I'd test with different name types and mob types to see if anything was different.

Tested with a named zombie and creeper - placed all 6 (1 of each via nametag, 1 of each via spawn egg rename) in the same plot while mob spawning was enabled via `/plot toggle mobs` and then toggled it back off and.... they're now fine?

I have no idea what's going on now :L

**Comment by BetaBurnt** [comment]
Yeah it's behaving now... All I've done is a server restart since I was able to regularly replicate it -.-

I'll close this for now - asked the players who reported it to let me know if it starts happening again, but for now I can't get it to do it :L
