### ISSUE TITLE
SlimeFun Conflict with Wither-Proof Blocks

### ISSUE THREAD

**Issue by AlphaDelta23** [TownyAdvanced/Towny#4390]
### What steps will reproduce the problem?
MC 1.16.3
Paper 246
SlimeFun4 vRC 16
Towny v0.96.3.0

When using SlimeFun's "Wither-Proof" blocks (obsidian and glass) in a Towny world with revert entity explosion enabled, the blocks do not function as intended and are destroyable by Wither attacks.

When revert entity explosion is disabled the blocks function as intended.

### What is your Towny version?
Towny v0.96.3.0

### What is your spigot/craftbukkit version?
PaperMC 246

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/TJSZm0hp
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/MVysZUSJ
3. Your townyperms.yml : https://pastebin.com/RDqK2TtA
4. Your log's error : N/A

**Comment by LlmDl** [comment]
Can you explain what the wither-proof block feature is in more detail?

**Comment by LlmDl** [comment]
From the looks of it here https://github.com/Slimefun/Slimefun4/blob/87d319cd02334e5c923fcc7b282c127ba991bcbc/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java the listener they use is on Highest priority, so we cannot know they will be cancelling the explosion unless we operated on Monitor priority. We use High priority. This is not something we can fix.

**Comment by AlphaDelta23** [comment]
Understood and thank you for taking the time evaluating the possibility. Will have to work around the issue.

**Comment by LlmDl** [comment]
Have you tried putting glass and obsidian in the ignore list? The only side effect I can think of off the top of my head is that the revert-on-unclaim feature would ignore them.

**Comment by AlphaDelta23** [comment]
Haven't tried that, but will do and report back once I am able to test it.
