### ISSUE TITLE
Suggestion: Load chunks async when checking cool downs

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#4391]
**Please explain your feature request to the best of your abilities:**
https://prnt.sc/v7eagp
This code, as far a I can tell, does a synchronous load (in line 51) of the chunks a player is going to tp to before then using paper's async methods (in line 57) to teleport them.  Would it speed things up to make both async?  And would the paper async method load the chunk properly anyway?

**Comment by LlmDl** [comment]
It looks like you're right, the teleportAsync will do the async chunk load or at worst load it sync (on spigot) https://github.com/PaperMC/PaperLib#teleportasync
