### ISSUE TITLE
Block Glitch Bug

### ISSUE THREAD

**Issue by EchoRapidz** [TownyAdvanced/Towny#4393]
Some players discovered an issue that allows players to essentially spider/fly up buildings.

It only works in claimed areas where they have no permission and a video of it can be found here uploaded by the player who encountered it

- > https://www.youtube.com/watch?v=GOk02QvIwHM

It occurs on my 1.15.2 Tuinity Towny server that runs Towny version 0.96.2.17
And occurs on my newer towny server that runs Tuinity 1.16.3 and runs Towny version 0.96.2.0

**Comment by LlmDl** [comment]
This sort of thing, I feel, is more in the realm of an anti-glitch/anti-cheat plugin.

**Comment by 0xBit-MC** [comment]
> 
> 
> This sort of thing, I feel, is more in the realm of an anti-glitch/anti-cheat plugin.

@EchoRapidz, you should look into anti-cheat plugins that manage "Phase" or "FastPlace" checks, I don't have this issue on my server because of my anti-cheat.
