### ISSUE TITLE
Plot not working

### ISSUE THREAD

**Issue by Nze25** [TownyAdvanced/Towny#4397]
### What steps will reproduce the problem?
1. User without any op permission 
2. /plot fs or other plot commands

### What is the expected output?
1. No respond from Towny

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
paper-135

config.yml: https://pastebin.com/ivuA9hWe
townyperms.yml: https://pastebin.com/kkEpCpnY

**Comment by LlmDl** [comment]
> [9:31 PM] Nze_: wait, its working with ./towny:plot

No startup so I can't comment on which plugin is conflicting here.
