### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by FireDragon5** [TownyAdvanced/Towny#4398]
Hi. Is it possible to remove the /g chat that players can talk in or the /t , /n ones?
FireDragon5Today at 8:03 AM
How to remove this https://prnt.sc/v957ah ?

**Comment by LlmDl** [comment]
Towny handles chat channel like so:

If you have the permission node for the channel and you have not actively left it in your login session, you will see all the channels.

**Comment by FireDragon5** [comment]
Thx you
