### ISSUE TITLE
Add GUI for the FarmPlot List

### ISSUE THREAD

**Issue by Drainer2002** [TownyAdvanced/Towny#4403]
Add a GUI to the farm list, like what to be planted (all are customized using GUI) as same as ItemUse and Switch GUI which was added in Towny Version 0.96.3.1.

**Comment by LlmDl** [comment]
Completed already: https://github.com/TownyAdvanced/Towny/commit/b09e50d3ef801018b569bc5204fc28b3b7f93b19
