### ISSUE TITLE
Question: Is there a way to stop lavacast griefing into claimed chunks?

### ISSUE THREAD

**Issue by aco4** [TownyAdvanced/Towny#4407]
**Ask your question as best as you are able:**
Is there a way to prevent lavacast griefing? For example, is there a way to prevent lava/water flowing into other plots, similar to how a piston cannot push into a different plot?

Recently a player was able to create a lavacast that started in the wilderness and spilled into claimed territory. This could be prevented if the lava/water used to create the lavacast was not able to flow into the claimed chunks.

**Comment by LlmDl** [comment]
This sort of thing isn't stopped because it is laggy and because it is minecraft and anyone can make a wall even one block tall to stop it. You can also ban players that do this sort of thing (after you make it a bannable rule.)

**Comment by aco4** [comment]
Actually, you would need a wall up to build limit. The player can continue to add layers, making the lavacast grow in size. But thanks for answering my question.

**Comment by LlmDl** [comment]
You can also just not let them use lava buckets in teh wild. Or allow it and ban griefers.
