### ISSUE TITLE
Fix more protections in updated entity listener.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#4409]
- [x] Minecarts:
  - will not break to wither black skull, wither blue skull, firework, end crystal
  - [x] Fixed creeper, charged creeper, respawn anchor, tnt minecarts. wither summon
  - [x] Fixed tnt, fireballs, (This is tricky to test because they return the player who fires the fireball or lights the TNT, so you cannot be testing this on land you control.)
- [x] ArmorStands blowing up to Respawn Anchors and (maybe beds)

- [x] ItemFrames:

    - Breaks to fireballs, wither blue skull, wither black skull.

- [x] LeashHitch:

    - Breaks to fireballs.

- [x] Boats:

    - Breaks to tnt, tnt minecart, fireball, creeper, charged creeper, wither summon, wither black skull, wither blue skull, end crystal, respawn anchor, bed (nether).

- [x] Paintings:

    - Breaks to fireballs.

**Comment by sirsalad** [comment]
- [ ] ItemFrames:

    - Breaks to fireballs, wither blue skull, wither black skull.

- [ ] LeashHitch:

    - Breaks to fireballs.

- [ ] Boats:

    - Breaks to tnt, tnt minecart, fireball, creeper, charged creeper, wither summon, wither black skull, wither blue skull, end crystal, respawn anchor, bed (nether).

- [ ] Paintings:

    - Breaks to fireballs.

**Comment by sirsalad** [comment]
Players without the required permission can ignite tnt in claims with a flame bow. Below, it is noted if that has an effect.

Fireballs were used by:
> I got around this by summoning a pile of fireballs with one account and using a 2nd account without destroy perms to hit them into minecarts/boats.

- [ ] ItemFrame:

    - Breaks to tnt if player igniting has destroy permissions. 

- [ ] ArmorStand:
    
    - Breaks to end crystals, respawn anchor, bed (nether)

- [ ] LeashHitch:

    - Breaks to tnt if player igniting has destroy permissions.
  
- [ ] PassiveAnimals:
    - Will take damage to bed explosion (nether).

- [ ] Boats:
    
    - Breaks to tnt, tnt lit by redstone, tnt minecart, fireball, creeper, charged creeper, wither spawning, wither black skull, wither blue skull, end crystal, respawn anchor, bed (nether).

- [ ] Minecarts:

    - Breaks to tnt if player igniting has destroy permissions, tnt lit by redstone, tnt minecart, creeper, charged creeper, wither spawning, wither blue skull, wither black skull, end crystal, respawn anchor, bed (nether). Fireballs don't destroy the minecarts, but the explosion will push the minecart.

- [ ] Paintings:

    - Breaks to tnt if player igniting has destroy permissions.

**Comment by LlmDl** [comment]
For itemframes, paintings and leashhitches (all hanging entities,) those are purposeful/part of the revamp. 

Lots of what were items are not because we're testing if the user has destroy perms.

**Comment by sirsalad** [comment]
Also found that in both claims and wilderness, I cannot damage passive mobs, armor stands, and item frames with items in them with projectiles.
When I try to, the console returns `[INFO]: nonplayerdamage`

**Comment by LlmDl** [comment]
Re: 
- ArmorStands: I could not make them blow up in a claimed plot with explosions turned off using respawnanchors (which are the same explosion type as beds in the nether) or end crystals.
- Boats: blew up when manually lighting tnt (how it works because of how Bukkit makes the lighter of the tnt the attacker) but not when redstone was used (because I dont register as the attacker.)
  - end crystal, respawn anchor/bed, creeprs were also not blowing them up.

I think you may have been testing with a prior version. The new code for explosion damage will handle basically every entity type (except vehicles and hanging entities (paintings,itemframes,hitches) in one simple check, whether it is the wilderness or in a town.
