### ISSUE TITLE
Some redstone blocks do not respect plot permissions when hit by Arrows.

### ISSUE THREAD

**Issue by sirsalad** [TownyAdvanced/Towny#4413]
Blocks include: Target, Wooden Buttons, Wooden Pressure Plates.

### What steps will reproduce the problem?
1. Create a town.
2. Claim a plot in that town.
3. Ensure Switch permission is off and `TARGET` is in `switch_ids:`.
4. Use a player without Switch permission to shoot the target block.
*The arrow firing seems to be canceled if the player is within reach of the target block

### What is the expected output?
1. The arrow gets canceled, target block does not output redstone signal, and `msg_cache_block_error_plot:` message in chat.

### What is your Towny version?
Do not say "latest".
Towny-0.96.3.2

### What is your spigot/craftbukkit version?
Do not say "latest".
paper-251 (1.16.3)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : none
2. Your Towny config.yml (if using MySQL please remove password,) : none
3. Your townyperms.yml : none
4. Your log's error :  none

(optional) If this is to do with permissions, 
5. Your permissions file : none

(optional) If this is to do with chat,
6. Your chatconfig.yml : none
7. Your channels.yml : none

**Comment by LlmDl** [comment]
I'm not entirely sure if the Bukkit api supports this sort of behaviour yet. The ProjectileHitEvent is not cancellable, so we may not be able to cancel the resulting hit.

**Comment by TheFlagCourier** [comment]
> I'm not entirely sure if the Bukkit api supports this sort of behaviour yet. The ProjectileHitEvent is not cancellable, so we may not be able to cancel the resulting hit.

What about overriding the power output, ie modify it's BlockData with [AnaloguePowerable](https://papermc.io/javadocs/paper/1.16/org/bukkit/block/data/AnaloguePowerable.html)? Could be possible with `setPower(0)`?

**Comment by LlmDl** [comment]
So far I have not found an event that gets thrown when the arrow hits the block. I somewhat expected it to fall into the catch-all EntityChangeBlockEvent, but not even the BlockRedstoneEvent is thrown.

**Comment by LlmDl** [comment]
The same goes for things like wooden buttons and pressure plates.
