### ISSUE TITLE
Explosion Issues

### ISSUE THREAD

**Issue by Drainer2002** [TownyAdvanced/Towny#4414]
### What steps will reproduce the problem?
1. Place  TNT in a claimed explosion plot beside a claimed non-explosion plot border 
2. where both plots are claimed (one is explosion enabled and the other is disabled)
3. And fire the TNT using the flint it will not explode any block in (enabled explosion) plot
4. it is just as if it is canceled cause being very near to a non-explosion plot
5. In the picture below is a demonstration where the orange concrete side is the non-explosion plot
6. while the TNT side is the explosion plot and there is a border shown in between them using F3 + G 

### What is the expected output?
1. TNT should explode the blocks in (enabled explosion) plot
2. without affected non-explosion plot
3. after firing it using the flint

### What is your Towny version?
Towny 0.96.3.2

### What is your spigot/craftbukkit version?
Paper-138 (Version 1.16.1)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : **Skipped**
2. Your Towny config.yml (if using MySQL please remove password,) : **Skipped**
3. Your townyperms.yml : **Skipped**
4. Your log's error :  **Skipped**

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :
![2020-11-03_19 45 31](https://user-images.githubusercontent.com/67148013/98072577-663ac080-1e77-11eb-9d72-70280b6ef1cc.png)

**Comment by LlmDl** [comment]
I think you may have been running the wrong version. At some point I gave sirsalad and you the wrong jar. Here's what I get on the explosion branch:

![2020-11-05_06 18 39](https://user-images.githubusercontent.com/879756/98240378-ee2fd180-1f2e-11eb-9a7e-14782dee6740.png)
![2020-11-05_06 18 47](https://user-images.githubusercontent.com/879756/98240391-f1c35880-1f2e-11eb-876c-ef4083bd3f9a.png)
