### ISSUE TITLE
Toggle Wilderness (build/destroy/access/use)

### ISSUE THREAD

**Issue by data-dataninja** [TownyAdvanced/Towny#4416]
**Ask your question as best as you are able:**
Let me first say: THIS IS AN AWESOME PLUGIN!

Not sure if this has been asked, I like to turn off wilderness  build/destroy so players dont mess up the landscape of wilderness.

THANKS

**Comment by LlmDl** [comment]
Just dont give any of the towny.wild.* nodes (which are not given by default.)
