### ISSUE TITLE
/t claim results in Server Thread Dump

### ISSUE THREAD

**Issue by ThorinEk** [TownyAdvanced/Towny#4418]
### What steps will reproduce the problem?
1. It seems that everytime someone types **/t claim**, multiple Server Thread Dumps are spammed in the console. This seems to result in heavy lag and connection issues.
2.
3.

### What is the expected output?
1. No server thread dump and no lag because of /t claim
2.
3.

### What is your Towny version?
0.96.3.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-257 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

1. Your full server startup from the logs\latest.log :
https://paste.ubuntu.com/p/jp3fsdgxfM/
2. Your Towny config.yml (if using MySQL please remove password,) :
https://paste.ubuntu.com/p/GkwCP7n3cn/
3. Your townyperms.yml :
https://paste.ubuntu.com/p/qcYx2mJ4Hw/
4. Your log's error : 
https://paste.ubuntu.com/p/GnhpNF4kPw/

**Comment by LlmDl** [comment]
Try out this preview copy of TNE which is meant to fix a bug like what you're describing: https://cdn.discordapp.com/attachments/267902896970924036/772478178135638036/TNE-0.1.1.12.jar

**Comment by ThorinEk** [comment]
Thanks a lot! That seems to have solved the issue. Sometimes it is hard to know which plugin is causing the error. So big thanks for your help even though it wasn't primarily about your plugin :)
