### ISSUE TITLE
./t unclaim rect (number) not working

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#4427]
### What steps will reproduce the problem?
1. stand in a claimed area. (or claim it, in this case I did /t claim rect 3, it said it claimed, but also tried it in an outpost of an established town)
2. do /t unclaim rect (number) (I tried 3 and 4)
3. Towny says "[Towny] Selected Area contains no valid plots" and the land is not unclaimed.

### What is the expected output?
1.  Towny should unclaim the land.
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.3.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 249 (1.16.3)

### Please use Pastebin.com to link the following files:
Llmdl said it was okay to skip the form.
He also said to reference his notes:

@Momshroom can you ticket that one, I think it might be related to https://github.com/TownyAdvanced/Towny/issues/4395
Don't worry about hte full form, just the version numbers

fwiw, /t claim rect DID work, but I was standing in the town at the time.
unclaim didn't

LlmDlToday at 3:46 PM
if you look at line 3493 of the TownCommand
which is 2 lines before the message you describe gets printed out.
it looks like we're filtering out all of the owned townblocks even though it's an unclaim
I dunno why we're filtering out owned townblocks though smh

LlmDlToday at 3:48 PM
no, I don't have the time atm to close it

but you can cite my notes

fixing this is probably going to need some testing
it's probably supposed to be filtering something but not owned blocks
probably so you cannot unclaim someone else's land

**Comment by LlmDl** [comment]
This test was added in https://github.com/TownyAdvanced/Towny/commit/ac7d9678791c04236e9c5e6dda6ef996efd3b45b

As of this moment I haven't figured out why it was put in there. The filteringOwnedTownBlocks stuff looks to be completely normal/fine. For some reason the amount returned by the AreaSelectionUtil has returned an empty selection.
