### ISSUE TITLE
Suggestion:  Add a /town plotgroup list page with groups, prices.

### ISSUE THREAD

**Issue by data-dataninja** [TownyAdvanced/Towny#4431]
**Please explain your feature request to the best of your abilities:**
We are using Towny for more like a MMORPG + build style experience:

1. Server Managed Towns (Town districts / town npcs/quests)
2. Player buy land from server (availble. Wtihbuilding, without, size sm-1plot , md-4 plot, lg-9plots)  
3. MMORPG style wilderness
4. Resource worlds (player go gather resource etc,  no townyrules periodic/reset )

This is how we want to go about it:
1 Whole map claim as a town
2 Town is public no fee/tax
3 Town perm is off for all
4 Server admins are mayors (maintain build/destroy townplots; maintain npc shops/quests)
5 Town plot group to indicate districts (ArtDistrict, TradesDistrict, TownCenter etc)
6 Town plot group for landsell to players (smhouse-023, lgland-128 etc.)

So currently the group feature is very confusing, 
Theres no 
1 list of groups in the town, 
2 check groups list prices 
3 intuitive  add/remove plot to group 
4. intuitive naming plot group name aginst plot name

Please let me know  what's the best way to go about  impleting the 6 points above, & if I should raise this as an issue or a bug.
THANKS

**Comment by LlmDl** [comment]
Re 3. intuitive add/remove plot to group
> This is done using `/plot group add {groupname}` and `/plot group remove` while standing in the plot, is it not?

Re 4. intuitive naming plot group name aginst plot name
> I don't quite understand you. `/plot group rename {name}` is the command to rename a plot group.

**Comment by LlmDl** [comment]
re: 1 Whole map claim as a town
> It is probably unrealistic to claim the entire map. your database will be huge.
re: 2 Town is public no fee/tax
> Make the towns open to join and with no tax.
re: 3 Town perm is off for all
> Don't turn on resident build/destroy in town-owned plots/cover teh towns in WG regions if you want them to not build on personally owned land.
re: 4 Server admins are mayors (maintain build/destroy townplots; maintain npc shops/quests)
> Ok
re: 5 Town plot group to indicate districts (ArtDistrict, TradesDistrict, TownCenter etc)
> make them into plot groups.
re: 6 Town plot group for landsell to players (smhouse-023, lgland-128 etc.)
> sell the plot groups to people.

**Comment by data-dataninja** [comment]
> Re 3. intuitive add/remove plot to group
> 
> > This is done using `/plot group add {groupname}` and `/plot group remove` while standing in the plot, is it not?
> 

is there a way to do 'town group list' list group name/id/prices?



> Re 4. intuitive naming plot group name aginst plot name
> 
> > I don't quite understand you. `/plot group rename {name}` is the command to rename a plot group.

plot group {id} rename {newname}  while not standing in the town?

**Comment by data-dataninja** [comment]
> re: 1 Whole map claim as a town
> 
> > It is probably unrealistic to claim the entire map. your database will be huge.
> 
its fine I have mv, so town world (town+wildness) & none towny(resource) world 



THANKS SO MUCH for your prompt help.

our server is dgworlds.apexmc.co   still beta ( 2 worlds at the moment :  MiddleEarthmap+magic;  Realearthmap) they all running towny feel free to check them out. MiddleEarthmap is being developed more

**Comment by LlmDl** [comment]
> > Re 3. intuitive add/remove plot to group
> > 
> > > This is done using `/plot group add {groupname}` and `/plot group remove` while standing in the plot, is it not?
> >
> > is there a way to do 'town group list' list group name/id/prices?

I don't recall if we have a list command, I thought we did.

> > Re 4. intuitive naming plot group name aginst plot name
> > > I don't quite understand you. `/plot group rename {name}` is the command to rename a plot group.
> 
> plot group {id} rename {newname} while not standing in the town?

I don't really see the benefit of having a rename command that doesn't require the player to be presently standing in the plotgroup itself. Since the name is made upon creation of the plotgroup I don't think very many people will be setting a different name that often.

> also when player move to a plot, the plotname shows different parts quite confusing to me ~ unowned towncenter - town - [home] etc is there a way just show certain part?

The various parts of what is shown is configured in the config.yml's notifications section. Only parts which differ from the previous townblock are shown, ie: when you move from a pvp plot to non-pvp, you see the No PVP in the notification.

**Comment by data-dataninja** [comment]
Yes please do :

Group lists:  /town group list  (shows group name, prices)
Group enhancements: (a /perm hud shows group, b /towny map shows group, etc)


Also a question, as I plan to run "Server-Managed-Towns" (ie open, free, build/destroy perm for buildteam only),
how do I create multiple towns (London & New York; Shire & Mordor etc) ? 
or please implement a "Server-Managed-Towns" type ?

THANKS

**Comment by LlmDl** [comment]
Use /ta set mayor TOWNNAME npc, then your mayor is an NPC that doesn't pay upkeep. You can leave to start other towns.

**Comment by data-dataninja** [comment]
Thanks. How about the build perm for my server managed towns? 
ie how to set perm for my staff (build team, admin)? 

Resident only access perm
Build team can build/destroy (town specific)
Admin (can more like a mayor) group plots/ sell plots (set up npcs etc)


How to achieve the above 3 different perms for my server managed town? or should I request a feature of server managed town type ?

THANKS

**Comment by LlmDl** [comment]
There's no per-town build/destroy override permission node. Staff can be given towny.claimed.alltown.* and build/destroy in any town.

A london mayor can give the builder rank (one you make in the townyperms.yml's town section, which has towny.claimed.townowned.*) to their residents, creating a london build team, which can build anywhere in non-resident plots in london.

**Comment by data-dataninja** [comment]
cool. 
so I was wondering i can use world guard with towny on this?
ie 
- A "servertown" Region of each Server Managed Towns
- Town build/destroy perm on for town residents 
- Build team as build flag on ther servertown regions 
- Build team must be the resident for town ?

also questions. whats build vs destroy perm?  build only builds destroy only destroys or build can destroy own builds, destroy can destroy everything?

THANKS

**Comment by LlmDl** [comment]
Towny towns cannot be configured with WG regions. Plot perms are explained on the wiki's How Towny Works page.
