### ISSUE TITLE
Bug When Referring a Command in TownyChat

### ISSUE THREAD

**Issue by xT3Kx** [TownyAdvanced/Towny#4435]
### What steps will reproduce the problem?
1. Using a channel alias like "/g" or "/tc" then following it up with a command For example someone asks what the command to check their perks and someone types "/g /perks" it will run the command "/perks" instead of output into general chat.

### What is the expected output?
1. For the command to post to chat instead of run.

### What is your Towny version?
Towny-0.96.3.0, TownyChat-0.82

### What is your spigot/craftbukkit version?
Paper 1.16.4 (#4756)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/QQ70fd9r
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/rZSRVStD
3. Your townyperms.yml : https://pastebin.com/54FxCWyQ
4. Your log's error : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/p3cNVU77
7. Your channels.yml : https://pastebin.com/GCPZvdZf

**Comment by LlmDl** [comment]
This is like any other time you want to say a command in chat with nothing else in front of it. You're going to have to put something like a . in front of the / (ex: `/g ./perks`)

**Comment by xT3Kx** [comment]
That's a little inconvenient. It doesn't seem happen with other chat plugins.

**Comment by LlmDl** [comment]
Do you have examples of other plugins that treat it that way?

When TownyChat sees someone using a /g or /tc command we just peel off the first command to get the channel they want to speak in, put them into that directedChat, then have them send their chat into that channel.

**Comment by xT3Kx** [comment]
Every command I send through /g will. The reason I use it this way is by default your chat would go to local to limit overall server spam. So using /g enters a global chat. I had a player accidentally leave the nation they owned by telling someone how to /n leave.

**Comment by LlmDl** [comment]
Yeah, but I asked for examples of chat plugins that different from what Townychat does. 

I'll be adding confirmations to /n leave and /t leave soon.
