### ISSUE TITLE
Is it possible to get rid of the feature that breaks builds when a town runs out of money and gets disbanded?

### ISSUE THREAD

**Issue by timothykra** [TownyAdvanced/Towny#4439]
On my Towny server, people come and go so when they stop playing, the town upkeep cost takes money out of the bank until the town is disbanded. When this happens, blocks start disappearing randomly and almost any build that was in the town gets destroyed. I have tried to do /co rollback with CoreProtect but it doesn't work on these builds. I really hate that feature since it breaks almost any chance of those players coming back. Is there a way to turn it off?

**Comment by LlmDl** [comment]
Use `/tw toggle revertunclaim` in each world you want it turned off in.

The New World Settings section of the [config](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) is only default settings for new worlds, it's explained in the config section comments, the [install guide](https://github.com/TownyAdvanced/Towny/wiki/Installation#configuring-existing-worlds) and the [how towny works](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#reverting-unclaimed-townblocks-to-their-original-state-on-unclaim) page. You need to be using the /tw toggle commands or manually setting the worldname.txt file.

**Comment by timothykra** [comment]
Thank you
