### ISSUE TITLE
Issue: Error Executing Task

### ISSUE THREAD

**Issue by ArmonicPvP** [TownyAdvanced/Towny#4440]
### What steps will reproduce the problem?
1. I don't know

### What is the expected output?
1. Nothing in the console

### What is your Towny version?
Do not say "latest".
0.96.3.4

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/QuHgpr69
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/1ruRchxX
3. Your townyperms.yml :  https://pastebin.com/RWyD675e
4. Your log's error : https://pastebin.com/sugffzf9

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/HHCr8YPG
7. Your channels.yml : https://pastebin.com/LQ9Nw6DC

**Comment by TheFlagCourier** [comment]
Sorry for the spam there, thought it was a Dynmap issue with all the NullPointers being thrown... 

But nope! Just a misconfigured configuration. See line 34 of your config.
```yaml
levels:
  # default Town levels.
  town_level:
  - numResidents: d
```

@ArmonicPvP `numResidents` needs to be an integer, not a character.
