### ISSUE TITLE
Suggestion: Consider adding support for Bluemap (Like Dynmap)

### ISSUE THREAD

**Issue by AZFire1** [TownyAdvanced/Towny#4443]
**Please explain your feature request to the best of your abilities:**
Could you consider adding support for Bluemap? It's like Dynmap. Check it out https://bluecolored.de/bluemap
Here's the plugin page https://www.spigotmc.org/resources/bluemap.83557/

**Comment by TheFlagCourier** [comment]
An addon with BlueMap support is in development from a third-party developer. Currently, it looks like it needs to be locally built, and may or may not be ready for public consumption. https://github.com/Jena-bot/TownyBlue

**Comment by LlmDl** [comment]
Yep this one is already being taken care of by the community.
