### ISSUE TITLE
Suggestion:  Add Lead to default config generation for item use

### ISSUE THREAD

**Issue by slvlr** [TownyAdvanced/Towny#4445]
**Please explain your feature request to the best of your abilities:**
Add Lead to default config generation for item use.

I have added it myself so no issue for me. But I think most people wouldn't like people being able to use leads on other peoples pets within towns.

**Comment by LlmDl** [comment]
It should not needed as of 0.96.3.2 or so, lead use should automatically be throwing a test. I don't know which version you're on.

**Comment by slvlr** [comment]
I am on 0.96.3.5 People could lead animals until I added it into item use list.

**Comment by LlmDl** [comment]
Ok I'll have to double check that then.

**Comment by LlmDl** [comment]
I've put it back into the config, I think this is one of the items that people will likely want to be able to remove from item_use if they want.
