### ISSUE TITLE
Suggestion: Customized SQL flags.

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/Towny#4446]
**Please explain your feature request to the best of your abilities:**

Under the config.yml, there should be an option to added customized flags for MySQL users, such as those provided by Dynmap and other plugins that connect with SQL.

An addition could be added to the config.yml as simple as this, `flags: "?allowReconnect=true&useSSL=false"` with adjustments to https://github.com/TownyAdvanced/Towny/blob/ecd31de0bb2f12bbb9be648ffcb7bb21649ac5cb/src/com/palmergames/bukkit/towny/db/TownySQLSource.java#L101 

I've been having to compile my own .jar with changes to the above mentioned TownySQLSource on Line 101 to add custom flags.

**Comment by 0xBit-MC** [comment]
Not sure if this is righttttttttttt, but here you go. You would start by removing the need for `TownySettings.getSQLUsingSSL()` and start with the stuff at the bottom?

TownySettings.java
```
public static String getSQLFlags) {
		return getString(ConfigNodes.PLUGIN_DATABASE_FLAGS);
	}
```

TownySQLSource.java L:78
```
String hostname = TownySettings.getSQLHostName();
String port = TownySettings.getSQLPort();
String flags = TownySettings.getSQLFlags();
db_name = TownySettings.getSQLDBName();
tb_prefix = TownySettings.getSQLTablePrefix().toUpperCase();
```
TownySQLSource.java L:93
```
else if (this.type.equals("mysql")) {
 driver1 = "com.mysql.jdbc.Driver";
 this.dsn = ("jdbc:mysql://" + hostname + ":" + port + "/" + db_name + flags);
 username = TownySettings.getSQLUsername();
 password = TownySettings.getSQLPassword();
```

**Comment by LlmDl** [comment]
Did you want to submit a Pull Request so you can get the credit? Your snippets looks like they're on track.
