### ISSUE TITLE
Cant Heal in the Wild

### ISSUE THREAD

**Issue by PorkChip01** [TownyAdvanced/Towny#4449]
So I recently downloaded the plugin to play with my girlfriend and after fixing some things to make it suitable for us, I noticed I couldn't heal in the wilderness. Only way to heal is by being in our town and was wondering if there was a certain piece of code to change so I can heal in the wild? Could this perhaps be a bug?

Any advice is helpful, have a good day!

**Comment by LlmDl** [comment]
The hunger/healing task only heals players in their town, not the wilderness.

**Comment by PorkChip01** [comment]
Is there a way I could edit the code somehow? I've tried looking in the towny settings, to no avail.

**Comment by LlmDl** [comment]
You'd need to delete lines 40 + 41 of the com.palmergames.bukkit.towny.tasks.HealthRegenTimerTask

**Comment by PorkChip01** [comment]
Perfect, thanks man. Take your time

**Comment by PorkChip01** [comment]
Hey, I can't seem to find com.palmergames.bukkit.towny.tasks.HealthRegenTimerTask anywhere, I'm pretty new to this. Could you point me in the direction to it? Thank you.

**Comment by PorkChip01** [comment]
Hi, LlmDI! I've been trying to edit this code but I keep getting an error after trying to have maven compile the jar. After deleting the code, I've gotten an exception is never thrown in body of corresponding try statement. 
The exception is:
"exception com.palmergames.bukkit.towny.exceptions.TownyException is never thrown in body of corresponding try statement" 
Do you have any suggestions to fixing this compile error?

**Comment by LlmDl** [comment]
Can you show me your code? Is it on github?

**Comment by PorkChip01** [comment]
It is, I forked it for my own. https://github.com/PorkChip01/Towny

Everything should be in the same place as it is

**Comment by LlmDl** [comment]
Looks like you can just remove the try-catch surrounding incHealth(player)

**Comment by PorkChip01** [comment]
I'll try that and let you know how it goes. Cheers!
