### ISSUE TITLE
my config gets reverted and i don't know why

### ISSUE THREAD

**Issue by sexibatka** [TownyAdvanced/Towny#4458]
everytime when i remove primed tnt and tnt minecart from the wilderness explosion revert it just resets the entire config

**Comment by LlmDl** [comment]
You're probably breaking the YAML formatting by messing with the spacing or using tabs, or your editor itself is doing the same thing.

**Comment by sexibatka** [comment]
this is how that part of the config looks like hwere is the problem?
 # This section is applied to new worlds as default settings when new worlds are detected.
    wild_revert_on_mob_explosion:
      # Enabling this will slowly regenerate holes created in the
      # wilderness by monsters exploding.
      enabled: 'true'
      # The list of entities whose explosions should be reverted.
      entities: Creeper,EnderCrystal,EnderDragon,Fireball,SmallFireball,LargeFireball,Wither,WitherSkull
      delay: 20s

**Comment by LlmDl** [comment]
you need to be setting that list in the towny\data\worlds\WORLDNAME.txt file. The config is only defaults for new worlds.

**Comment by sexibatka** [comment]
thank you so much i had 10 people waiting on me to fix it much love and also nice plugin
