### ISSUE TITLE
Explosions are no longer damaging players/mobs when they probably still should be.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#4464]
Started mid-0.96.3.7 or somewhere in the pre-releases when I re-did the explosion listeners.

**Comment by Momshroom** [comment]
The issue was in my sort-of .5 build from when making my PR, if that helps.   I had updated my fork to the upstream before starting.

**Comment by LlmDl** [comment]
This one is fixed by https://github.com/TownyAdvanced/Towny/commit/d5c1a1920c1cd1bc36e1552842390404dbb74f17 in a half-assed way, but it will be redone when the [PVP](https://github.com/TownyAdvanced/Towny/commit/d5c1a1920c1cd1bc36e1552842390404dbb74f17) events get put in / war gets stripped out of the TownyEntityListener.
