### ISSUE TITLE
Question: A town that had letters "ü" and "ß" in the name broke my towny

### ISSUE THREAD

**Issue by Darkweasam** [TownyAdvanced/Towny#4466]
**Ask your question as best as you are able:**
I had a town with this weird name (no idea how they been able to name a town like that) so after I uploaded from 93.3 to 93.8 the server didnt boot up due to this (So I couldnt do /townyadmin to delete town)

My solution was that, I renamed the Town in the data/towns and data/townblocks to be able to start up, however whenever I do /townyadmin town <uglyname> i get "An internal error occoured" so I cannot delete the town using their ugly and the renamed name either.

I probably missed some files where I should change the town name too, any ideas?

**Comment by LlmDl** [comment]
The town name will be listed in the residentname.txt files, the nationname.txt file, the townblocks files.

**Comment by Darkweasam** [comment]
Thats kind of extremely hard to dig through that many files

**Comment by LlmDl** [comment]
Might be nice if you filed a bug report rather than a question, which includes the startup log with the errors you mentioned.

**Comment by Darkweasam** [comment]
There was only an error in startup which said "inappropiate letters in town name" which i fixed using the method I started my question with. There are no errors since then, but when I want to "inspect" the town ingame, I get the classic "An internal error occoured" mc error line

**Comment by LlmDl** [comment]
Yes, but I'm curious as to which letters in the Town name weren't allowed? If you use the default regex in Towny's config, unicode characters are allowed.

**Comment by Darkweasam** [comment]
https://pastebin.com/3vWLcTTi

It doesnt show, I believe both the above mentioned letter triggered it

**Comment by LlmDl** [comment]
This is a situation where your operating system doesn't support saving files with unicode characters.

**Comment by Darkweasam** [comment]
I can write and use these letters as fine everywhere else. Its not my system but a dedicated hosting service. This town's name wasnt an issue for so long(1+ month) until I updated from 93.3 to 93.8

**Comment by LlmDl** [comment]
File a bug report. I need to see the files requested in a bug report.
