### ISSUE TITLE
Suggestion: Time Penalty for leaving town/nation?

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#4476]
Essentially this feature will be a few configuration options which manage the ability to apply a time penalty for residents that leave towns. This will trigger a town leave event which could check for `Enforce_Town_Leave_Penalty` and if it is true, it can check `enforce_penalty_on_first_leave`. If `enforce_penalty_on_first_leave` is false, it will allow a resident to join and leave a town once within the `penalty_time`, preventing players from joining and leaving more then two towns in a given `penalty_time`. This will not deny the resident from leaving the second town, as it will only reset the timer and not check for `enforce_penalty_on_first_leave`

This idea could be extended to towns that join/leave nations using the same concept above.

Config options/section:
1. enforce_town_leave_penalty = true/false
2. enforce_nation leave_penalty = true/false
3. enforce_penalty_on_first_leave = true/false
4. penalty_time = (time options)

**Comment by LlmDl** [comment]
This ticket reminds me a bit about https://github.com/TownyAdvanced/Towny/issues/2949

The both of them require some new Timer stuff I do plan on adding.

**Comment by fabmm** [comment]
Great Idea! I was thinking the same!!
