### ISSUE TITLE
"Null" error while creating outpost

### ISSUE THREAD

**Issue by treeDerevo** [TownyAdvanced/Towny#4480]
### What steps will reproduce the problem?
1. /t set outpost
2. [Towny] null

### What is the expected output?
1. Creating an outpost

### What is your Towny version?
0.96.3.0

### What is your spigot/craftbukkit version?
Paper 1.15.2

No errors in the console, no logs are displayed. Previously, everything worked with this config. Normal server startup and nothing like that.

**Comment by LlmDl** [comment]
You should update your Towny and if you have trouble, file a ticket without skipping the form.
