### ISSUE TITLE
[Bug] Nation Toggle Peaceful 

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/Towny#4502]
Previously tracked on #4467
 
**What steps will reproduce the problem?**
    Create a nation
    Toggle Nation Neutrality
    Nation becomes peaceful without paying a dime.

**What is the expected output?**
    Nations pay the price for neutrality.

**What is your Towny version?**
Towny 0.96.4.0, TownyChat 0.83, TheNewVersion 0.1.1.12

**What is your spigot/craftbukkit version?**
Purpur version 841, implements Paper-Spigot 1.16.4-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:
**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/hJk0pqpj
2. Your Towny config.yml: https://pastebin.com/bTFp5qWe
3. Your townyperms.yml : https://pastebin.com/xUSQwm7H
 Note on TownyPerms, unlike the previous bug report on the same issue, the permission to toggle neutrality works fine.
4. Your log's error : No error log or issues in console, only photos
Photo 1 - https://i.imgur.com/yZvK0Jv.png

**Comment by 0xBit-MC** [comment]
At the time, I have completely removed the permission `- towny.command.nation.toggle.neutral` from the King Rank in townyperms.yml, which it now operates properly. Unlike the previous bug report.

**Comment by LlmDl** [comment]
I thought this was fixed. No one should be using 0.96.4.0 due to a bug that has been fixed. Update to 0.96.5.0 or 0.96.5.1 and see if this was properly fixed.

**Comment by 0xBit-MC** [comment]
> 
> 
> I thought this was fixed. No one should be using 0.96.4.0 due to a bug that has been fixed. Update to 0.96.5.0 or 0.96.5.1 and see if this was properly fixed.

We are currently moving to new hardware, with this we are going to 0.96.5.1 and I'll let you know how it goes.

**Comment by 0xBit-MC** [comment]
Tested 0.96.5.2 and it works fine. Thank you for handling this!
