### ISSUE TITLE
Suggestion: Colour the channel name in the switching message to the channels' message colour.

### ISSUE THREAD

**Issue by ratedslice69** [TownyAdvanced/Towny#4503]
![A8354763-69F7-4F33-AD79-D201F138BC17](https://user-images.githubusercontent.com/72847516/100630896-597b8200-32e8-11eb-8c64-2106ae84ea39.jpeg)
**Please explain your feature request to the best of your abilities:** 
When switching modes the channels stay yellow ba reading the information from the channels.yml

**Comment by LlmDl** [comment]
This will be part of TownyChat 0.97.
