### ISSUE TITLE
Question:what do I do if it says that the player is not registered

### ISSUE THREAD

**Issue by Artmancall** [TownyAdvanced/Towny#4504]
I'm super new to this and server hosting, what do I do if it says that the player is not registered when I do
/ta town new (name) (playername)
Ex:
/ta town new OGrate "*cheeseballs768"

does it have something to do with "online"/knowing if its a Java account 

I have 2 plug-ins (Geyser, and Floodgate) installed for Bedrock players to join with out a Java account, plus they could link their Java account with there bedrock account if they have one. (When a bedrock player joins the server, it automatically puts a "*" in front of their gamertag untill they decide to link their Java account, it will change their gamertag to whatever the Java gamertag is)

I have a friend that has a Java account (and joined in with Java edition) and it worked fine with them, is there some kind of list I can manually put them in?

**Comment by LlmDl** [comment]
Geyser can be used without Floodgate, at which point you will not have players with a * in their name.

**Comment by MWHunter** [comment]
See https://github.com/TownyAdvanced/Towny/issues/4369#issuecomment-707903386 on how to allow non-vanilla characters into people's names, which *, a non-vanilla character, is put as a prefix before bedrock player's names.  Seems to work with light testing, but I wouldn't be surprised if more issues result from floodgate.

**Comment by squeaky2137** [comment]
Sorry to chat here but if you change the prefix in floodgate to _ it works this also helps with other plugins that don’t allow *

**Comment by MWHunter** [comment]
Java edition allows _ in the name so it would fix the other plugins, but you could run into the issue where a Java and Bedrock player share a username, which some plugins can’t handle.

**Comment by LlmDl** [comment]
I am not paid enough to deal with floodgate servers. Don't use floodgate if you're using geyser.
