### ISSUE TITLE
Suggestion: Add a town toggle for elytra fly and enderpeal teleport as well as chorus fruit teleport

### ISSUE THREAD

**Issue by JustJP2K** [TownyAdvanced/Towny#4506]
**Please explain your feature request to the best of your abilities:**
It would be really cool to see a toggle for turning off elytra flying in your town as well as ender pearl teleport and chorus fruit teleport. That way if a war should start in your town you can defend your town walls without enemiess intruding.

**Comment by LlmDl** [comment]
Ender pearls and chorus fruit are already handled as item_use. No checks for elytras but couldn't the defenders have their own elytras?
