### ISSUE TITLE
Residents unable to kills animals on farm plots

### ISSUE THREAD

**Issue by GizaRoho** [TownyAdvanced/Towny#4507]
### What steps will reproduce the problem?
1. Set town plot to FARM
2. Set perm to resident ON (for all perms)
3. Resident tried to kill animals, were unable to kill. They were able to kill when plot was reset and they were given DESTROY perms on plot. 

### What is the expected output?
1. Residents should be able to kill animals when given perms on a Farm plot, they cannot.
2.
3.

### What is your Towny version?
Towny 0.96.4.0 

### What is your spigot/craftbukkit version?
PaperMC-1.16.4 - compatible with spigot plugins.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/8UTGzPpL
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/HmFLUJXM
3. Your townyperms.yml :  https://pastebin.com/GNDzpiBj
4. Your log's error :  Cannot see an error

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Killing animals requires the players to be able to destroy Wheat inside the farm plot. You have wheat in the farm_plot_block list in the config. I'm wondering if the plot did not have the destroy option enabled for residents if it was a town-owned plot, or the destroy option enabled for town if it was a resident-owned plot.

**Comment by GizaRoho** [comment]
I made sure the residents had the destroy permission also, I gave the residents full permission on the plot. It was not a resident owned plot, it belonged to the townSent from my Galaxy
-------- Original message --------From: LlmDl <notifications@github.com> Date: 03/12/2020  00:21  (GMT+00:00) To: TownyAdvanced/Towny <Towny@noreply.github.com> Cc: GizaRoho <tiffanyjclarke97@gmail.com>, Author <author@noreply.github.com> Subject: Re: [TownyAdvanced/Towny] Residents unable to kills animals on farm plots (#4507) 
Killing animals requires the players to be able to destroy Wheat inside the farm plot. You have wheat in the farm_plot_block list in the config. I'm wondering if the plot did not have the destroy option enabled for residents if it was a town-owned plot, or the destroy option enabled for town if it was a resident-owned plot.

**Comment by LlmDl** [comment]
OK, I'll do some testing myself.

**Comment by LlmDl** [comment]
Works like it should with cows, in a town-owned farm plot, with resident destroy on.

What animal are you testing? Can you give me any other things to take into account during the test?

**Comment by GizaRoho** [comment]
It was cows we were using, perhaps i should try updating. We also had sheep and pigsSent from my Galaxy
-------- Original message --------From: LlmDl <notifications@github.com> Date: 03/12/2020  12:28  (GMT+00:00) To: TownyAdvanced/Towny <Towny@noreply.github.com> Cc: GizaRoho <tiffanyjclarke97@gmail.com>, Author <author@noreply.github.com> Subject: Re: [TownyAdvanced/Towny] Residents unable to kills animals on farm plots (#4507) 
Works like it should with cows, in a town-owned farm plot, with resident destroy on.
What animal are you testing? Can you give me any other things to take into account during the test?

**Comment by LlmDl** [comment]
Good point, no one should be using 0.96.4.0 any longer.
