### ISSUE TITLE
Towns all go to -1 balance after a day

### ISSUE THREAD

**Issue by ArmonicPvP** [TownyAdvanced/Towny#4508]
### What steps will reproduce the problem?
1. Wait 1 day
2.
3.

### What is the expected output?
1. Town balances do not go to -1
2.
3.

### What is your Towny version?
Do not say "latest". 0.96.5.0

### What is your spigot/craftbukkit version?
Do not say "latest". 1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/UDfYj0QB
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/3SzPbfFU
3. Your townyperms.yml : https://pastebin.com/uUFU5wkX
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Startup log wasn't given.

**Comment by ArmonicPvP** [comment]
https://drive.google.com/file/d/1hYV1iUka6N6C5n43CVBwvN6UYQd5ndgm/view?usp=drivesdk

Startup log is too big to upload to pastebin

**Comment by LlmDl** [comment]
Unfortunately essentials eco is known to reset, this is why Towny warns you about this in the startup.
