### ISSUE TITLE
Suggestion: Ride Horses/Other Ridable Entity Perm

### ISSUE THREAD

**Issue by GuildM** [TownyAdvanced/Towny#4509]
**Please explain your feature request to the best of your abilities:**
Well I wanna know first if there is a settings to disable riding horses from the plots that you don't own, because people can steal someone's horses and also its horse armor even tho it wasn't their plot or belong into that town. So if there is no settings for that, maybe having a ride perm will be a good feature.

**Comment by LlmDl** [comment]
You can add saddle with teh switch_ids in the config, but it has the added effect where if you dismount in land you don't own you lose your horse.

It is better to get a dedicated horse plugin which will protect horses based on who owns the horse.
