### ISSUE TITLE
Suggestion: Resident based upkeep

### ISSUE THREAD

**Issue by elwolf6** [TownyAdvanced/Towny#4516]
**Please explain your feature request to the best of your abilities:**

Resident based upkeep. Currently there's `nation_pertown_upkeep` for nations and `town_plotbased_upkeep` for towns but there should be something like `nation_perresident_upkeep` and `town_perresident_upkeep` that makes the upkeep the value of `nation_perresident_upkeep` or `town_perresident_upkeep` X `price_nation_upkeep` or `price_town_upkeep`

Currently it's possible to do by making a lot of town / nation levels but being completely honest I am too lazy to do that and I am not creative enough to think of 100+ name suffixes and mayor/king prefixes.

**Comment by LlmDl** [comment]
You are right, this is already covered by the town and nation levels' upkeepModifiers.

**Comment by elwolf6** [comment]
please llama have mercy 😭

**Comment by LlmDl** [comment]
I'll look into how this would affect the existing code, it might be too difficult to make sense with the rest of it.
