### ISSUE TITLE
Question about Dynmap-Towny

### ISSUE THREAD

**Issue by stijnjw** [TownyAdvanced/Towny#4522]
I keep getting [this](https://prnt.sc/vvy9wq) error, and I don't understand why. 
I am also getting [these](https://prnt.sc/vvyavu) errors ingame, the first one being when making a town (it still creates the town), and the second one is when claiming, and it also seems to work. 
Also, when I run /towny prices, it returns [this garbage](https://prnt.sc/vvyc9i).
I've tried doing multiple things, I just can't figure it out. Please help.
Also, if possible, I would like all the prices to be 0, because this is a private server with a few of my friends =)
Thanks

**Comment by LlmDl** [comment]
Sounds like you just need to set using_economy: false and remove any costs/prices stuff from the dynmap-towny configuration.

**Comment by stijnjw** [comment]
Yeah I didnt know you needed vault, I realised that quickly after making this post, that's also why I closed it =)
