### ISSUE TITLE
Error of permission

### ISSUE THREAD

**Issue by AlfreDGR** [TownyAdvanced/Towny#4527]
### What steps will reproduce the problem?
When you put a tnt or something in the enemy town appear this error
1.https://media.discordapp.net/attachments/581163022874050569/784758885474369546/unknown.png?width=1182&height=665
2.
3.

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
Do not say "latest".

MY CONFIG OF WAR

event:
 
    warning_delay: '300'
 
    #If false all towns not in nations can be attacked during a war event.
    towns_are_neutral: 'true'
 
    enemy:
 
      # If true, enemy's can only attack the edge plots of a town in war.
      only_attack_borders: 'true'
 
    plots:
 
      # If true, nation members and allies can regen health on plots during war.
      healable: 'true'
 
      # If true, fireworks will be launched at plots being attacked or healed in war every war tick.
      firework_on_attacked: 'true'
 
    # If true and the monarch/king dies the nation is removed from the war.
    # Also removes a town from the war event when the mayor dies.
    remove_on_monarch_death: 'false'
 
    # If enabled players will be able to break/place any blocks in enemy plots during a war.
    # This setting SHOULD NOT BE USED unless you want the most chaotic war possible.
    # The editable_materials list in the Warzone Block Permission section should be used instead.
    allow_block_griefing: 'false'
 
    # A townblock takes damage every 5 seconds that an enemy is stood in it.
    block_hp:
      town_block_hp: '60'
      home_block_hp: '120'
 
    eco:
      # This amount is new money injected into the economy with a war event.
      base_spoils: '100000.0'
 
      # This amount is taken from the losing town for each plot lost.
      wartime_town_block_loss_price: '2500.0'
 
      # This amount is taken from the player if they die during the event
      price_death_wartime: '250.0'
 
    # If set to true when a town drops an enemy townblock's HP to 0, the attacking town gains a bonus townblock,
    # and the losing town gains a negative (-1) bonus townblock.
    costs_townblocks: 'false'
 
    # If set to true when a town drops an enemy townblock's HP to 0, the attacking town takes full control of the townblock.
    # One available (bonus) claim is given to the victorious town, one available (bonus) claim is removed from the losing town.
    # Will not have any effect if war.event.winner_takes_ownership_of_town is set to true.
    winner_takes_ownership_of_townblocks: 'false'
 
    # If set to true when a town knocks another town out of the war, the losing town will join the winning town's nation.
    # The losing town will enter a conquered state and be unable to leave the nation until the conquered time has passed.
    winner_takes_ownership_of_town: 'false'
 
    # Number of Towny new days until a conquered town loses its conquered status.
    conquer_time: '3'
 
    points:
      points_townblock: '10'
      points_town: '50'
      points_nation: '150'
      points_kill: '2'
 
    # The minimum height at which a player must stand to count as an attacker.
    min_height: '60'
 
 
  ############################################################
  # +------------------------------------------------------+ #
  # |                   Flag War Settings                  | #
  # |                                                      | #
  # |               [Separate from Event War]              | #
  # |           --------------------------------           | #
  # |        DEPRECATED: Minimally Supported Through       | #
  # |             3rd Party Contributions Only             | #
  # +------------------------------------------------------+ #
  ############################################################
 
  enemy:
 
    # If false, players won't be able to place war flags, effectively disabling warzones.
    allow_attacks: 'false'
 
    # If true, enemy's can only attack the edge plots of a town with war flags.
    only_attack_borders: 'true'
 
    # This many people must be online in target town in order to place a war flag in their domain.
    min_players_online_in_town: '2'
 
    # This many people must be online in target nation in order to place a war flag in their domain.
    min_players_online_in_nation: '3'
 
    max_active_flags_per_player: '1'
 
    flag:
 
      # This setting modifies the time between a war flag's Material shift. Accepts `s`(seconds) and `m`(minutes).
      # Currently, you would multiply this times 10 to get the total time a flag should be in play.
      # (It can also be set to `h` and `d` - but ain't nobody got time fo' that.)
      waiting_time: 1m
 
      # This is the block a player must place to trigger the attack event.
      base_block: fence
 
      # This is the block a player must place to trigger the attack event.
      light_block: torch
 
    beacon:
 
      # Must be smaller than half the size of town_block_size.
      radius: '3'
      # The range the beacon will be drawn in. It's flexibility is in case the flag is close to the height limit.
      # If a flag is too close to the height limit (lower than the minimum), it will not be drawn.
      height_above_flag:
        min: '3'
        max: '64'
      draw: 'true'
      wireframe_block: glowstone
 
    # While true, prevent players from performing certain actions while their town
    # has an active enemy war flag placed.
    prevent_interaction_while_flagged: 'true'
 
    # While true, prevent players from performing certain actions while a town in their nation
    # has an active enemy war flag placed.
    prevent_nation_interaction_while_flagged: 'true'
 
    # This is how much time that must pass after a town in a nation has been flagged
    # before certain actions can be performed, measured in milliseconds.
    time_to_wait_after_flagged: '600000'
 
    # If set to true, when a war flag finishes it's countdown successfully, the attacking town takes full control of the townblock.
    # Setting this to 'False' will result only in monetary exchanges.
    flag_takes_ownership_of_townblocks: 'true'
 
 
  ############################################################
  # +------------------------------------------------------+ #
  # |              Warzone Block Permissions               | #
  # |                                                      | #
  # |              Used in Flag & Event Wars               | #
  # +------------------------------------------------------+ #
  ############################################################
 
  warzone:
 
    # List of materials that can be modified in a warzone.
    # '*' = Allow all materials.
    # Prepend a '-' in front of a material to remove it. Used in conjunction with when you use '*'.
    # Eg: '*,-chest,-furnace'
    editable_materials: tnt,fence,ladder,fire,scaffolding,oak_fence,birch_fence,spruce_fence,jungle_fence,dark_oak_fence,acacia_fence
    item_use: 'true'
    switch: 'false'
 
    # Add '-fire' to editable materials for complete protection when setting is false. This prevents fire to be created and spread.
    fire: 'false'
    explosions: 'true'
    explosions_break_blocks: 'true'
 
    # Only under affect when explosions_break_blocks is true.
    explosions_regen_blocks: 'true'
 
    # A list of blocks that will not be exploded, mostly because they won't regenerate properly.
    # These blocks will also protect the block below them, so that blocks like doors do not dupe themselves.
    # Only under affect when explosions_break_blocks is true.
    explosions_ignore_list: CHEST,TRAPPED_CHEST,FURNACE,BURNING_FURNACE,DROPPER,DISPENSER,HOPPER,ENDER_CHEST,WHITE_SHULKER_BOX,ORANGE_SHULKER_BOX,MAGENTA_SHULKER_BOX,LIGHT_BLUE_SHULKER_BOX,YELLOW_SHULKER_BOX,LIME_SHULKER_BOX,PINK_SHULKER_BOX,GRAY_SHULKER_BOX,SILVER_SHULKER_BOX,CYAN_SHULKER_BOX,PURPLE_SHULKER_BOX,BLUE_SHULKER_BOX,BROWN_SHULKER_BOX,GREEN_SHULKER_BOX,RED_SHULKER_BOX,BLACK_SHULKER_BOX,LIGHT_GRAY_SHULKER_BOX,SHULKER_BOX,NOTE_BLOCK,LEVER,STONE_PLATE,IRON_DOOR_BLOCK,WOOD_PLATE,DIODE_BLOCK_OFF,DIODE_BLOCK_ON,FENCE_GATE,GOLD_PLATE,IRON_PLATE,REDSTONE_COMPARATOR_OFF,REDSTONE_COMPARATOR_ON,WHITE_BANNER,ORANGE_BANNER,MAGENTA_BANNER,LIGHT_BLUE_BANNER,YELLOW_BANNER,LIME_BANNER,PINK_BANNER,GRAY_BANNER,LIGHT_GRAY_BANNER,CYAN_BANNER,PURPLE_BANNER,BLUE_BANNER,BROWN_BANNER,GREEN_BANNER,RED_BANNER,BLACK_BANNER,PAINTING,BARREL,OAK_SIGN,SPRUCE_SIGN,BIRCH_SIGN,JUNGLE_SIGN,ACACIA_SIGN,DARK_OAK_SIGN,ITEM_FRAME,BLAST_FURNACE,RAIL,SMOKER,DETECTOR_RAIL,ACTIVATOR_RAIL,POWERED_RAIL
 

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I'll reopen this when the form is filled out.
