### ISSUE TITLE
Outlaw doesn't get teleported to jail when killed

### ISSUE THREAD

**Issue by stijnjw** [TownyAdvanced/Towny#4529]
### What steps will reproduce the problem?
1. /t outlaw add [name] a person
2. Kill them in your land
3. They spawn at the world spawn

### What is the expected output?
They get teleported to jail

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
git-Spigot-a19903d-5b74714 (MC: 1.16.4), which is 'the latest version'

**Comment by LlmDl** [comment]
I'll reopen this when you fill out the form.

**Comment by stijnjw** [comment]
Oh sorry, I've edited the message

**Comment by LlmDl** [comment]
You need to set `town_respawn: 'false'` to true.
