### ISSUE TITLE
Suggestion: Allow outlaws to get killed in a pvp off plot/town

### ISSUE THREAD

**Issue by JustJP2K** [TownyAdvanced/Towny#4532]
That way if you dont want players to imprison outlaws, (can be abused) but still want players to be at an advantage in their own town against outlaws without outlaws harassing residents

**Comment by LlmDl** [comment]
So the town would be able to hurt the outlaw but the outlaw couldn't hurt the Town?

**Comment by JustJP2K** [comment]
yep! would love to see that get implemented. would help stop the mayhem that is spreading on my server :P

**Comment by LlmDl** [comment]
Not very fair. I don't think this would be added.

**Comment by JustJP2K** [comment]
well hes an outlaw after all. so he shouldnt enter the city. and if he does its at his own risk in my opinion. basically the same thing with jail.

**Comment by JustJP2K** [comment]
the problem im having is that players jail other players in their town after killing him and he/her cannot get out of jail since they dont have any money or friends to bail them out. so they are basically stuck there forever. It would seem better to just give them a disadvantage in a town instead of jailing him/her. if they really wanted to then go and kill and loot they could start a war perhaps.

**Comment by TheFlagCourier** [comment]
> other players in their town after killing him and he/her cannot get out of jail since they dont have any money or friends to bail them out. so they are basically stuck there forever. 

Sounds like a case for a `maximum_jail_sentence` timer setting, rather than making the player a punching bag.

**Comment by JustJP2K** [comment]
sure. that works as well

**Comment by JustJP2K** [comment]
would be very cool to see it in a future update :3

**Comment by JustJP2K** [comment]
btw, if new things get added to the config. would it mean i have to delete the old config, let it regenerate and edit it again?

**Comment by LlmDl** [comment]
New options are added with their default setting.

I do plan on rewriting jails and at that point all jailed players will have a hours-amount they are jailed for.

**Comment by LlmDl** [comment]
Also you can make use of the outlaw teleport feature recently added, setting it to instantly teleport them when they enter a town they should not be in. Meaning they wont be able to be sent to jail. Alternatively you can turn off the entire jailing-outlaw feature.
