### ISSUE TITLE
Question: Major can't do nothing in his own town

### ISSUE THREAD

**Issue by Gallons291** [TownyAdvanced/Towny#4535]
Hi, im setting up a towny server but when my friend buy a town he can't build, destroy and do nothing in the town. I tried to add -towny.claimed.owntown.* ; -towny.claimed.townowned.build.* ;  -towny.command.plot.* in the major permission in townyperms.yml 
but he's steel unabled to do nothing in its own town. How can I fix? Thank you :)

**Comment by LlmDl** [comment]
That won't be Towny stopping them.
