### ISSUE TITLE
Self kick

### ISSUE THREAD

**Issue by emanondev** [TownyAdvanced/Towny#4536]
### What steps will reproduce the problem?
join a town, get a rank to kick players, try to kick yourself you will get msg_you_cannot_kick_yourself message but you'll be kicked (Mayor rank has not been tested)

### What is the expected output?
You should not be kicked

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
Not important, 1.16.4

**Comment by LlmDl** [comment]
I fixed this earlier for a somewhat unrelated ticket.
