### ISSUE TITLE
Residents may see other towns townchat

### ISSUE THREAD

**Issue by emanondev** [TownyAdvanced/Towny#4546]
### What steps will reproduce the problem?
1. Unknow

Some players reported of being able to see other player chatting in town chat while stayng in other towns,
This bug happens only sometime and only to some players

They also provided some screenshots and logs, of 3 reports 2 cases were confirmed

### What is the expected output?
1. Players should see only their own town chat

### What is your Towny version?
Version: 0.96.5.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-296 (MC: 1.16.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/ntQk90QG -i pasted only towny related logs-
2. Your Towny config.yml (if using MySQL please remove password,) : -not relevant, not for public-
3. Your townyperms.yml : https://pastebin.com/qZ3ry8hq
4. Your log's error : -none-

If this is to do with permissions, 
5. Your permissions file : 

If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/0KUgS6FH
7. Your channels.yml : https://pastebin.com/qk885vfC

Note: i can share full logs and configs but i wouldn't like them to be free access for anyone my discord id is Emanon#7414

**Comment by LlmDl** [comment]
Skipped the form.

**Comment by Drc-DEV** [comment]
Can confirm this happening

**Comment by LlmDl** [comment]
> Can confirm this happening

The code basically makes this impossible so if you have anything to contribute as to how it is done, I'd love to hear it.
