### ISSUE TITLE
Suggestion: Add New Github Discussions To Towny Repo

### ISSUE THREAD

**Issue by TheBeeCollector** [TownyAdvanced/Towny#4548]
**Please explain your feature request to the best of your abilities:**

Github just announced a new feature on public repos that allow people to engage in threaded discussions. And I think it would be a great resource for the towny repo.

You can view the demo here: https://github.com/githubevents/universe2020/discussions

> Discussions live in your project repository, so they’re accessible where your community is already working together. Their threaded format makes it easy to start, respond to, and organize unstructured conversations. Questions can be marked as answered, so over time a community’s knowledge base grows naturally. And because discussions aren’t closed the way issues are, they can easily serve as a place for maintaining FAQs and other collaborative documentation. We recognize that community discussion is as much a part of development as coding, so discussion contributions appear in users’ contribution graphs.

This prevents people from creating an issue ticket for questions on using towny and allows developers and Minecraft admins to keep track and discuss the progress of certain developments without having to dig into a ticket or worse, a PR that's flooded with commits. 

This is shouldn't be a replacement for discord by any means, as discord is good at fast Q/A, but it's not that great for keeping track of longer-term thoughts/questions/ideas. I think this is something towny should look into as it could improve communication a lot.

**Comment by LlmDl** [comment]
I'm not exactly looking forward to another thing to monitor, and without proper monitoring people can end up with the wrong information being given as an answer, but I think we could try it out.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/discussions/4550
