### ISSUE TITLE
Suggestion: Ability to see plot claim date and time

### ISSUE THREAD

**Issue by itslukemango** [TownyAdvanced/Towny#4556]
I'd like to see a feature where admins (probably using /ta) can see when a plot was claimed (probably /ta checkplot as an example).
This is useful for us as most Towny servers use a method of seeing who placed what blocks, edited what and when, and some players attempt to "frame" other players by claiming land that was destroyed before claiming. This would then be classed as griefing to an unknowingly staff member. The ability to see when plots were claimed would resolve this immediately. This has been requested by several of our staff and players.

**Comment by LlmDl** [comment]
This could be fairly easily add to the normal townblock status output (/plot perm) screen, as a registered date. Any townblocks with a registered of 0 would not show anything but anything newer would be able to have a date/time shown (like residents/towns.)
