### ISSUE TITLE
NewNationEvent trouble

### ISSUE THREAD

**Issue by XuPuPG** [TownyAdvanced/Towny#4557]
When 'n new' the nation arg in event always null
https://github.com/TownyAdvanced/Towny/blob/d9ede6d122ca170f65122c77fce19fd7bfaccb24/src/com/palmergames/bukkit/towny/object/Town.java#L220

**Comment by XuPuPG** [comment]
NationCommand#newNation , first setUUID and capital and then fire town,setNation

**Comment by LlmDl** [comment]
That event is when a town joins a nation. You want the NewNationEvent.

**Comment by XuPuPG** [comment]
no, when a town creates a nation, the event of adding it to a nation is first called, and then a nation is created.

**Comment by XuPuPG** [comment]
when new nation
1) https://github.com/TownyAdvanced/Towny/blob/a3f090c52f1579a17099a0359980af29eacde184/src/com/palmergames/bukkit/towny/command/NationCommand.java#L1078
2) https://github.com/TownyAdvanced/Towny/blob/a3f090c52f1579a17099a0359980af29eacde184/src/com/palmergames/bukkit/towny/command/NationCommand.java#L1141
3)
https://github.com/TownyAdvanced/Towny/blob/a3f090c52f1579a17099a0359980af29eacde184/src/com/palmergames/bukkit/towny/command/NationCommand.java#L1146
4)
https://github.com/TownyAdvanced/Towny/blob/dcfd9339d5e343aee3a52d0e09a98e57d42b15af/src/com/palmergames/bukkit/towny/object/Town.java#L198
**NationAddTownEvent fired**
5)
https://github.com/TownyAdvanced/Towny/blob/a3f090c52f1579a17099a0359980af29eacde184/src/com/palmergames/bukkit/towny/command/NationCommand.java#L1160
**NewNationEvent fired**

**Comment by XuPuPG** [comment]
and if wondering, if a king in a nation removes a town, then the nation is removed first, then the towns are removed, and then the king's town is removed.

**Comment by XuPuPG** [comment]
and when the database is restarted /ta database reload, the towns are first added to the nation, which is also null. How can I handle these cases if I also need to reload data in my plugin?

**Comment by LlmDl** [comment]
I think I'm understanding you now.

**Comment by silverwolfg11** [comment]
> and when the database is restarted /ta database reload, the towns are first added to the nation, which is also null. How can I handle these cases if I also need to reload data in my plugin?
Unfortunately there is really no way to get around the null UUID on database reload since the db stubs all the townyobjects by name first, and then loads each type of townyobject in a sequential order.
You could just alternatively skip your plugin logic if the nation UUID is null.
