### ISSUE TITLE
Suggestion: Config option to prevent towns and nations sharing one name.

### ISSUE THREAD

**Issue by XuPuPG** [TownyAdvanced/Towny#4558]
I propose to prohibit the same names for cities and nations, as is done for cities
example:
Town: abc
Nation: abc  <-- illegal case on create or rename
what to do for servers that are updated?
```java
public void solveCollision() {
        for (Map.Entry<String, Town> stringTownEntry : TownyUniverse.getInstance().getTownsMap().entrySet()) {
            String name = stringTownEntry.getValue().getName();
            while (TownyUniverse.getInstance().getDataSource().hasNation(name))
                name = name.concat("_");
            try {
                TownyUniverse.getInstance().getDataSource().renameTown(stringTownEntry.getValue(), name);
            } catch (AlreadyRegisteredException | NotRegisteredException ignore) {
            }
        }
    }
```

**Comment by illumeleet** [comment]
this should be added as a config value

**Comment by PolitcubesScripts** [comment]
++++

**Comment by TheFlagCourier** [comment]
Good proposition, but I'm going to agree with illumeleet on this one.

Some nations can benefit from sharing a name of their towns:
  - Rome, Rome (/ The [Holy] Roman Empire)
  - New York (City), New York 
  - Guatemala (City), Guatemala
  - Mexico (City), Mexico
  - Oklahoma (City), Oklahoma
  - Panama (City), Panama
  - Vatican City {City-State}

**Comment by LlmDl** [comment]
This would have to be a setting which defaulted to off, because there are lots of servers with towns and nations that share a name.
