### ISSUE TITLE
Outpost not working (null)

### ISSUE THREAD

**Issue by nuvx** [TownyAdvanced/Towny#4565]
### What steps will reproduce the problem?
1. Created a town
2. Moved away well away from the town and homeblock
3. Used /town claim outpost
4. Towny gives Null in chat and no outpost is created.
5. On the town screen it shows 0 of 1 outpost before and after the attempt.

### What is the expected output?
1. Claim an outpost

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
1.16.4 #261
Also using Luck Perms: 5.2.35 which is the latest version (updated 4 days ago)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/SEkmfbAB
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/kYJixkMj
3. Your townyperms.yml :  https://pastebin.com/AsivVYWv
4. Your log's error : No console error

(optional) If this is to do with permissions, 
Don't believe so, tried it with and without OP

**Comment by LlmDl** [comment]
I am not able to reproduce this. Usually receiving [Towny] Null means your economy plugin could not be reached/the money could not be paid. 

Did you pay $12500 for the outpost?

**Comment by nuvx** [comment]
Yes, I tried it with a 0 town bank balance, but I had the money, then again after I deposited 20k in the town bank. Same result, just says null in chat.

**Comment by LlmDl** [comment]
Usually receiving null means your economy plugin is not work/cannot be reached.

**Comment by nuvx** [comment]
Thats weird because all other features involving economy and towns work

**Comment by LlmDl** [comment]
Indeed, can you think of anything else?

**Comment by nuvx** [comment]
I tried it after resetting the cost of outpost to 0 and it still didn't work. Would it still be an economy issue if the cost of the outpost is 0 and it still says null?

**Comment by LlmDl** [comment]
Probably not.

**Comment by LlmDl** [comment]
I've just tested this a second time, this time using your config. I am able to claim an outpost fine. 

This means there's probably something special about your town or the world you're trying to put your outpost in.
