### ISSUE TITLE
Unsaved Towny Data (1.16.3)

### ISSUE THREAD

**Issue by EnderGamingFilms** [TownyAdvanced/Towny#4569]
### What steps will reproduce the problem?
using towny with SQL database
restart server

### What is the expected output?
Save town data

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
paper 1.16.3-253

### Links
1. Your full server startup from the logs\latest.log : https://paste.helpch.at/jacixavule.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://paste.helpch.at/mikecotiqe.coffeescript
3. Your townyperms.yml : https://paste.helpch.at/imukuxufem.php

**Comment by LlmDl** [comment]
your config:
```
    database_load: flatfile
    database_save: mysql
```
You can't leave those on different settings after you've converted. See the How Towny Works wikipage for conversion instructions.
