### ISSUE TITLE
Suggestion: PlayerJoinChatChannelEvent

### ISSUE THREAD

**Issue by MrMaurice211** [TownyAdvanced/Towny#4575]
**Please explain your feature request to the best of your abilities:**
Add an event which is fired everytime a player changes or joins a Chat Channel on TownyChat

**Comment by LlmDl** [comment]
So this is nearly complete but it ends up firing in a couple places.

- It fires when a player does is in townchat and then does /g
- It also fires when a player has done /channel leave general and then uses /channel join general.

Do those two satisfy the request?

**Comment by LlmDl** [comment]
This will potentially be closed by https://github.com/TownyAdvanced/TownyChat/pull/32

**Comment by MrMaurice211** [comment]
> So this is nearly complete but it ends up firing in a couple places.
> 
> * It fires when a player does is in townchat and then does /g
> * It also fires when a player has done /channel leave general and then uses /channel join general.
> 
> Do those two satisfy the request?

Yes! Thank you a lot!
