### ISSUE TITLE
Outside Contributions Currently infringe on Towny License

### ISSUE THREAD

**Issue by TheBeeCollector** [TownyAdvanced/Towny#4576]
So earlier today I was getting ready to create a branch on my local towny repo to start working towards ticket #3036. As I read the contributing.md document the licensing caught my eye. I had never seen software use a CC BY-NC-ND license. So I decided to look into what is enforced. However, in my research, it seemed I found that license isn't compatible with the "fork and pull-request" model that towny uses. I truly believe that this was an honest licensing mistake, and I'll explain why below:

Before I begin this, the goal of this ticket is ***not*** to:
- Be accusatory
- Blame others
- Or threaten anyone in any way

**I don't blame anyone for anything stated below**

But to instead address an issue about towny's licensing model, that could negatively impact contributors. And to maintain a non-toxic dialogue with the towny community and maintainers.

### The issue:

**The full issue thread about this is located here: [Mathworks Licensing Issue
](https://github.com/numworks/epsilon/issues/38)**

In my research, I was able to find a repo that originally had the same licensing model as towny: CC-BY-ND-NC. Many parts of this Github public repo mirrored what towny is currently doing such as allowing pull requests. 

The OP sums up the infringements in this case pretty well:

> The license you chose, however, is not merely non-free (in the sense of freedom), but not open source. CC-BY-NC-ND forbids anyone from making modifications to your source code -- even though you state in your project's README that you welcome contributions and that pull requests are accepted.

Reading further on through the thread, it's apparent that **any pull requests are using derivative work.**

Why?

A pull request must be:
- public (which means anyone on GitHub can download the code)
- a modification of the source

This means any contributor submitting a pull request is breaking the no-derivs rule by creating a publicly modified version of towny, which the original license strictly forbids. And again **just stating that "you allow GitHub contributions or forks" doesn't change the terms of the license.**

### The outcome:

Epsilon by numworks ended up changing their license from **CC-BY-NC-ND** to **CC-BY-NC-SA**. This was chosen for many reasons, the main ones being:

- Contributors could contribute the repo without infringement on the owner license.
- Repo was now officially open source (yay)

Others included:
- Retains the fact that the code cannot be used for commercial gain from CC-BY-NC-ND
- Retains the enforcement of attribution from CC-BY-NC-ND
- Enforces that any other distributions of the code must use the same license.

___

### What happens if the license is infringed on?

The biggest being that your license cannot be enforced:

> This License and the rights granted hereunder will terminate automatically upon any breach by You of the terms of this License.

-- **Source:** Creative Commons CC-BY-NC-ND license; Termination; section a

This is not a great outcome considering your code is basically not protected by any licensing at this point. Other than that, life goes on as usual.

### Can you have an *"open source"* repo that doesn't allow derivatives?

- No, that breaks one of the tenets of open source:
	- > The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software. 

    -- **Source**: The open-source initiative: https://opensource.org/osd

This makes ethical sense, non-open-source repo's shouldn't be able to benefit from the open-source community.
___
However, the biggest issue doesn't necessarily affect the copyright holder but instead the contributors:

According to the license, anyone who is currently hosting a GitHub repo with modified towny code is infringing on the license. This means that the owner of towny *could technically* come after you, however, I doubt anyone from Towny would because they're nice people. But regardless this leaves many of the contributors in legal limbo, because in order to contribute they must infringe on the towny license. 

I think towny should fix these infringement issues by using a license that allows contributions.

As this license affects every outside contributor to Towny, I think this ticket thread should be an open dialogue to remedying the issues stated above. This doesn't just affect future contributors like me, but also any other contributors to the towny source.

I want to thank the towny team and contributors for the work that they do, and I hope we can resolve this issue soon just as numworks did with their community.

**Comment by LlmDl** [comment]
The reason for no-derivatives is that we don't want to have what happened to factions happen to towny, a schism that splits apart the core towny experience into something that will vary greatly based on which version of towny a server opted to use, leaving the player-base in the dark as to what they're getting into. If there are improvements to the core plugin made, all servers benefit.

As the license holder, I am allowed to say "you can fork this and make pull requests back to the project" and "you can have your fork on github as long as you're not putting any .jars available for download."

>**Can I waive license terms or conditions?**
>Yes. You may always choose to waive some license terms or conditions. Material licensed under a CC license but with additional permissions granted or conditions waived may be compatibly licensed with other material under the same license. Our CC+ protocol provides a mechanism for facilitating that grant or waiver.


As to this:
> This License and the rights granted hereunder will terminate automatically upon any breach by You of the terms of this License.
* "You" would be referring to yourself and not me.

As to meeting someone else's standard of "open source", I feel that Towny does qualify as being open source. 

No offense taken obviously, if you do not want to pass on the copyright of your code by making a pull request you are not required to contribute.

There is already [a ticket](https://github.com/TownyAdvanced/Towny/issues/3255) about changing the license but so far I've not seen another license that restricts commercial use and distribution of modified towny, which are my main concerns.

**Comment by TheBeeCollector** [comment]
Just some more quick questions then,

If you're waiving the non-derivative part of the non-derivative license, then what's the point of the non-derivative license? 

Also, how can you allow modified source code to be public but not allow modified jars? Is there a difference in usage?
 If you have the source code, you have everything you need to compile the modified jar, they go hand in hand. Also from a legal standpoint how do you prove that having the source code isn't the same as having a modified jar. The only difference is one is compiled and the other one isn't, but can be. Many people already have the tools on their computer to compile the source code into a jar. By having a public Github repo with the source code any person with a computer can obtain a modified jar. That's like saying guns aren't allowed but the full step-by-step instructions and materials to build the guns are? See what I'm getting at? That's a bit of a contradiction.

**Comment by LlmDl** [comment]
I really don't feel up to this discussion via an issue ticket. Drop on in to the discord if you really want to make a stink about it.

I am not waiving the non-derivative part of the license.
