### ISSUE TITLE
I cant create a town

### ISSUE THREAD

**Issue by MatrimAldous** [TownyAdvanced/Towny#4577]
### What steps will reproduce the problem?
1. I write /town new testt 
2. Nothing happened and no error message too.

### What is the expected output?
1. Create a town

### What is your Towny version?
Do not say "latest".
Towny-0.96.5.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Bukkit 1.16.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/uT2g7BmX
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/WELqJziV (When i paste this pastebin 
warned against offensive content)
3. Your townyperms.yml : https://pastebin.com/c859RLJp
4. Your log's error : https://pastebin.com/ei9tXKCE

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
From the log:
```
20:14:54] [Server thread/INFO]: [Towny] Warning: No compatible Economy plugins found. Install
        Vault.jar or Reserve.jar with any of the supported eco
        systems. If you do not want an economy to be used, set
        using_economy: false in your Towny config.yml.
```
