### ISSUE TITLE
20 MySQL connections instead of 10

### ISSUE THREAD

**Issue by Tsumitsuki** [TownyAdvanced/Towny#4587]
LlmDl wants a ticket for this so here it is^^

simply discovered that there are 20 connections from towny to my bd instead of the 10 set in the settings (and mentioned by LlmDl).
not a big deal for me but since it should only be 10 it's still a bug^^

### What is your Towny version?
0.96.5.6

### What is your spigot/craftbukkit version?
paper: 324 - 1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/80JYqXsm
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/RvtTv6tu
3. Your townyperms.yml : -
4. Your log's error : -

**Comment by LlmDl** [comment]
I was hoping you'd also share the evidence of there being 20 connections as well though...

**Comment by LlmDl** [comment]
Ok, I've had it clarified to me that the connection pooling setting max is actually used for loading and saving, so 10 + 10 = 20. I think we'll be lowering that down because we don't really need 10 for loading (which we rarely do.)

**Comment by Tsumitsuki** [comment]
sry i'm not at home and the bd can't be accessed from outside. but the ftp works so i could get the files on the go. 

buf case closed i guess if it's 10 up and 10 down.

**Comment by darbyjack** [comment]
Hi there, thanks for letting me know about this. I've just implemented a PR that will half the current default to account for the loading and saving.
