### ISSUE TITLE
Question: Error with Dynmap-Towny task 78

### ISSUE THREAD

**Issue by tesdai** [TownyAdvanced/Towny#4596]
Recieving an error, have been for a couple days, happens every few seconds. Just updated to Towny 0.96.5.0 to try and fix with no luck. Was running 0.96.3.0. Using Dynmap-Towny-0.82 the entire time.
I have using_economy: 'false' if it matters any.

[WARNING] .... [Dynmap-Towny] Plugin Dynmap-Towny v0.82 generated an exception while executing task 78
java.lang.NullPointerException: null
at com.palmergames.bukkit.towny.TownyEconomyHandler.getFormattedBalance(TownyEconomyHandler.java:290) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin.formatInfoWindow(DynmapTownyPlugin.java:489) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin.handleTown(DynmapTownyPlugin.java:637) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin.updateTowns(DynmapTownyPlugin.java:859) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin.access$0(DynmapTownyPlugin.java:852) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:307) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-253]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-253]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[INFO] .... [Dynmap-Towny] error adding area marker The_New_Joe_Republic__0
[INFO] .... [Dynmap-Towny] error adding area marker Wasteland__0
[INFO] .... [Dynmap-Towny] error adding area marker Moscow__0
[INFO] .... [Dynmap-Towny] error adding area marker Istanbro__0
[INFO] .... [Dynmap-Towny] error adding area marker Wateredge_Trading_Company__0
[INFO] .... [Dynmap-Towny] error adding area marker Merilia__0
[INFO] .... [Dynmap-Towny] error adding area marker Lux__0
[INFO] .... [Dynmap-Towny] error adding area marker Epsilon__0
[INFO] .... [Dynmap-Towny] error adding area marker Isle_Island__0
[INFO] .... [Dynmap-Towny] error adding area marker wss__0
[INFO] .... [Dynmap-Towny] error adding area marker Johaldi__0
[INFO] .... [Dynmap-Towny] error adding area marker Alster__0
[INFO] .... [Dynmap-Towny] error adding area marker Farmstæt__0
[INFO] .... [Dynmap-Towny] error adding area marker Empire__0
[INFO] .... [Dynmap-Towny] error adding area marker Nuggets_Farm__0
[INFO] .... [Dynmap-Towny] error adding area marker Dust_Walkers__0
[INFO] .... [Dynmap-Towny] error adding area marker idkmanijustwantahome__0
[INFO] .... [Dynmap-Towny] error adding area marker Mootans_Clan__0
[INFO] .... [Dynmap-Towny] error adding area marker Kinabalu__0
[INFO] .... [Dynmap-Towny] error adding area marker Toastland__0
[INFO] .... [Dynmap-Towny] error adding area marker AdminVille__0
[INFO] .... [Dynmap-Towny] error adding area marker Ranger_Citadel__0
[INFO] .... [Dynmap-Towny] error adding area marker Mitonial_Union__0
[INFO] .... [Dynmap-Towny] error adding area marker Utopia__0
[INFO] .... [Dynmap-Towny] error adding area marker Anarcho-Penguinism__0
[INFO] .... [Dynmap-Towny] error adding area marker ChadNautica__0
[INFO] .... [Dynmap-Towny] error adding area marker Phos__0
[INFO] .... [Dynmap-Towny] error adding area marker Brome__0
[INFO] .... [Dynmap-Towny] error adding area marker BoredIsland__0
[INFO] .... [Dynmap-Towny] error adding area marker Yoru_Crime_Syndicate__0
[INFO] .... [Dynmap-Towny] error adding area marker Sparta__0
[INFO] .... [Dynmap-Towny] error adding area marker Funky_Island__0
[INFO] .... [Dynmap-Towny] error adding area marker Himinio__0
[INFO] .... [Dynmap-Towny] error adding area marker NDF__0
[INFO] .... [Dynmap-Towny] error adding area marker Sand_Runners__0
[INFO] .... [Dynmap-Towny] error adding area marker Spectrum__0
[INFO] .... [Dynmap-Towny] error adding area marker The_skärgård__0
[INFO] .... [Dynmap-Towny] error adding area marker Plateau_of_Gold__0

Minecraft Version: Paper 1.16.3
Towny Version: Towny 0.96.3.0 and 0.96.4.5
Dynmap-Towny Version: 0.82

**Comment by LlmDl** [comment]
show me your dynmap-towny config.

**Comment by tesdai** [comment]
https://pastebin.com/xwTUJBT7

Is pastebin ok?

**Comment by LlmDl** [comment]
can you give this a test for me: https://cdn.discordapp.com/attachments/669247087329673228/788879945106849822/Dynmap-Towny-0.83.jar

**Comment by tesdai** [comment]
Thank you. It seems to not be throwing errors anymore. Have had it running for about 4 hours now without issue.

**Comment by LlmDl** [comment]
Anyone having this error just needs to update: https://github.com/TownyAdvanced/Dynmap-Towny/releases/tag/0.83
