### ISSUE TITLE
Using world alias in chat - Not world name

### ISSUE THREAD

**Issue by JoshJamesLS** [TownyAdvanced/Towny#4606]
Hello! I'm jsut wondering if there is a way to use the world alias instead of the world name when cofiguring the chat format. I have a nether world named "Spawn_nether" with its alias set to "Nether", and I want the chat to show Nether. not Spawn_nether. Thanks in advance

**Comment by LlmDl** [comment]
What are you using to set the alias?

**Comment by JoshJamesLS** [comment]
I'm using the multiverse plugin

**Comment by LlmDl** [comment]
Does multiverse have a placeholder you can use?

**Comment by JoshJamesLS** [comment]
I don't believe so but I might be wrong

**Comment by LlmDl** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#multiverse-core

**Comment by JoshJamesLS** [comment]
Worked perfectly, thanks a lot
