### ISSUE TITLE
Usage of Towny Chat and DiscordSRV Plugin

### ISSUE THREAD

**Issue by JoshJamesLS** [TownyAdvanced/Towny#4615]
Hello! I have had an issue with permissions between the two plugins. DiscordSRV allows players to send messages in game via discord and vice versa. I have towny chats that require specific permissions in game - these are working, only the correct roles can see the correct chats. However, when sending a message into the admin chat (for example) all roles in game can see this. 

I have been in touch with DiscordSRV developers assuming it was an issue with their plugin, however they have tested everything and can't find anything.

I was told to pass this message on to Towny devs: (hopefully it helps to understand the issue)

> DiscordSRV is using Towny's channel.isPresent(playername) method (returns if a player is "present" in a chat or not) to determine if chat should be send to a player or not. This seems to return true for each player in your case.

### What steps will reproduce the problem?
1. Sending a message in discord to a chat that requires specific permission to view

### What is the expected output?
1. Only players with the corresponding role in game should be able to read it

### What is your Towny version?
Towny - 0.96.5.0
TownyChat - 0.84
TownyNameUpdater - 5.0

### What is your spigot/craftbukkit version?
Paper Spigot - 1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log : https://pastebin.com/RkQSNQXP
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/teDBSDsH
3. Your townyperms.yml : https://pastebin.com/YSFWeu6M
4. Your log's error : No specific error

(optional) If this is to do with permissions, 
5. Your permissions file : Group Manager
   - Global Groups : https://pastebin.com/pRh3KvG8
   - Groups : https://pastebin.com/z36wJVuS

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/1kVbmy5U
7. Your channels.yml : https://pastebin.com/trgg6zvh

**Comment by LlmDl** [comment]
I thought I might have fixed this already but it was testing the player's permission node before they were being assigned their permissions (too early on the player join event.)

I have a fix for this but the min. required Towny version has already been bumped to 0.96.5.5. If you want to update to 0.96.5.6 I can give you the townychat to test it with discordsrv.

**Comment by JoshJamesLS** [comment]
I'll happily update to 0.96.5.6. And yes, please if you could. Thanks

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/790670353315659816/TownyChat-0.85.jar

**Comment by JoshJamesLS** [comment]
After testing it thoroughly with several differnet ranks adn scenarios it seems to be working except for the need to restart the server before any of the cahnges can be made.

In one scenario the testing player started off as the lowest rank (noo additioonal chat permissions) - which worked perfectly.
Then, I gave the player a higher rank (for example, admin) and the player could see the newly added chats from discord - with new permissions. After the server had restarted then the player was able to access the correct chats etc. So, after

**Comment by LlmDl** [comment]
Yeah they will have to relog to be marked present. I might be able to work that out.

**Comment by JoshJamesLS** [comment]
Just tried that - yes, a relog does fix this. But if there is no need for a relog then even better I guess! SO, overall it seems to be working.

**Comment by LlmDl** [comment]
They should also get access once they actually join the channel using /join {channelname}, /ch join {channel} or /ac (the shortcut command). I'm not sure I want to re-evaluate the players channels when their permissions change.

**Comment by JoshJamesLS** [comment]
They can join with those commands, yes. But they will still be able to see chats from "no longer permitted" chats until they relog

**Comment by LlmDl** [comment]
Hmmm, well that is a bit of a bother isn't it.

**Comment by LlmDl** [comment]
One thing that discordsrv could do to make this a ton easier is to use the player.hasPermission(channel.getPermission()), if their API can work with that.

**Comment by JoshJamesLS** [comment]
I've passed the message on, see what the dev says
