### ISSUE TITLE
label-siegewar Question: Disabling Towny Border Protection in Siege War

### ISSUE THREAD

**Issue by greenalex27** [TownyAdvanced/Towny#4618]
Having a problem here. I want to enable placing chests on the border of town claims however I am new to setting up towny and can't find a way to enable it in the config. 

When it happens I am getting this message in console: 
[Towny] Error could not read msg_err_siege_war_too_many_town_blocks_nearby from english.yml

**Comment by LlmDl** [comment]
The siegewar discord's install guide says you need to delete your english.yml and let the new one get made by the siegewar towny jar. Make sure you're using teh links here: https://github.com/TownyAdvanced/Towny/projects/10

**Comment by greenalex27** [comment]
> The siegewar discord's install guide says you need to delete your english.yml and let the new one get made by the siegewar towny jar. Make sure you're using teh links here: https://github.com/TownyAdvanced/Towny/projects/10

Would that fix the issue with not being able to place chests on the borders of towns?

**Comment by LlmDl** [comment]
I don't know anything about that issue. Does it only affect teh end of sieges or is it stopping placement of any chest at any time?

**Comment by greenalex27** [comment]
> I don't know anything about that issue. Does it only affect teh end of sieges or is it stopping placement of any chest at any time?

Only the placing of chests at any time it seems.

**Comment by LlmDl** [comment]
You should file a new bug report ticket and not skip the form.

**Comment by greenalex27** [comment]
> You should file a new bug report ticket and not skip the form.

Will do. Didn't realize it was a bug.
