### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by Leftic10** [TownyAdvanced/Towny#4621]
Hi, i've been trying to fix so that people can build/break/use/switch in the wilderness, but after looking for hours I still haven't found a fix. Could you please help me?

""
this was the question i gave for where i got send to a FAQ page. This page did not help actually and i have already tried for what was in that. So i still cannot break/mine/use/switch anything.
Please help.

Thank you

**Comment by LlmDl** [comment]
Explain what you tried already.

Show me what the players get as a message when they are testing.

**Comment by Leftic10** [comment]
Players get you are in the wilderness! and then wont let them do anything.
I've tried putting towny.wild.* and towny.admin.* in the config  under nodes and also tried doing it manually with towny.wild.build but nothing of that seems to work

**Comment by LlmDl** [comment]
` you are in the wilderness!` is not a towny message. File a bug report if you cannot figure out which plugin is overriding it.

**Comment by TheFlagCourier** [comment]
A quick Google brings this up: https://www.reddit.com/r/admincraft/comments/bjk2jh/wilderness_not_letting_players_build

I'm the post, it turns out to be their economy plugin.

**Comment by TheFlagCourier** [comment]
And #4623 confirms my suspicions.

**Comment by Leftic10** [comment]
thank you so much. You just saved me a lot of headache
