### ISSUE TITLE
Wilderness

### ISSUE THREAD

**Issue by Leftic10** [TownyAdvanced/Towny#4623]
### What steps will reproduce the problem?
1. I try to mine/build/use anything in the wilderness
2. it says you are in the wilderness!
3. and then im stuck

### What is the expected output?
1. That i can mine/build etc. in the wilderness

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.96. 5.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot minecraft 1.16. 4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/8EQhnT18
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cVYHgeYf
3. Your townyperms.yml : https://pastebin.com/NkN2h1cH

(optional) If this is to do with permissions, 
5. Your permissions file : is empty

(optional) If this is to do with chat,
6. Your chatconfig.yml : never changed
7. Your channels.yml : never changed

**Comment by TheFlagCourier** [comment]
As stated in #4621, this is not an issue with Towny.
And it's more likely an issue related to your economy plugin.

**Comment by LlmDl** [comment]
Yep good old Ultimate Economy.
