### ISSUE TITLE
Teleportation Canceled on Damage is overriden if issued more than once.

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/Towny#4624]
### What steps will reproduce the problem?
1. Type `/t spawn` more than once while in combat or moving.
2. You will be teleported back to your town spawn, regardless of "canceled by damage" or "canceled by movement" because one of the teleportation events becomes unchangeable. 

### What is the expected output?
1. If you get damaged, or move. You cancel your `/t spawn` teleportation.

### What is your Towny version?
0.96.5.7

### What is your spigot/craftbukkit version?
git-Purpur-905 (1.1.6.4-R0.1-Snapshot Paper Stream)

### Please use Pastebin.com to link the following files:
config.yml: https://pastebin.com/SpKDjKrn
IMG: https://i.imgur.com/4FXkNuh.png

No logs, errors or debugging pointed directly to an issue; It appears this maybe just a logic thing.

**Comment by LlmDl** [comment]
I'll test this out but this sounds awfully close to one of the bugs related Tuinity servers had that couldn't be reproduced.
