### ISSUE TITLE
[Siege War] Strange behaviour with town peacefulness

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#4627]
### What steps will reproduce the problem?
1. Enable `peaceful_towns` under "Common War settings".
2. Set `new_town_peacefulness_enabled` to `false`.
3. Create a town. 
4. Create a nation with the new town as its capital. 
5. Execute `/ta newday`.
6. [The town will become "Peaceful", and the nation will be deleted.](https://gyazo.com/fe51a612015a15bc537a69a97603c83b) (note: there is no nation upkeep - see the config below). 

### What is the expected output?
1. The town should not change peacefulness state unless `/t toggle peaceful` is executed _and_ the time set in `new_town_confirmation_requirement_days` (or `confirmation_requirement_days` for non-new towns) has elapsed.                                 
2. The nation should not be deleted.

### What is your Towny version?
The siegewar/master branch at the [latest commit](https://github.com/TownyAdvanced/Towny/commit/81ae23a2c49b00f10c5d1b0d0bdde1113b1a7a22).

### What is your spigot/craftbukkit version?
Purpur version git-Purpur-924 (MC: 1.16.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : [Link](https://pastebin.com/ygi3TM9f)
2. Your Towny config.yml (if using MySQL please remove password,) : [Link](https://pastebin.com/ZQdXJFui)
3. Your log's error : N/A. There is no error. 

### Speculation

In the `SiegeWarListener` class, the `TownPeacefulnessUtil` method `updateTownPeacefulnessCounters` is triggered upon a `PreNewDayEvent`. This executes a [different](https://github.com/TownyAdvanced/Towny/blob/siegewar/master/src/com/palmergames/bukkit/towny/war/siegewar/utils/TownPeacefulnessUtil.java#L53) `updateTownPeacefulnessCounters` for every non-ruined town. 

I suspect the issue lies within it. If a town does not have the IntegerDataField `peacefulnessChangeConfirmationCounterDays` (such as new towns), `getPeacefulnessChangeConfirmationCounterDays` [always returns 0](https://github.com/TownyAdvanced/Towny/blob/siegewar/master/src/com/palmergames/bukkit/towny/war/siegewar/metadata/TownMetaDataController.java#L29). This causes the town peacefulness to switch even if there is no pending peacefulness state change. Why exactly the nation is also deleted eludes me.

**Comment by LlmDl** [comment]
I'll take a look at this after christmas, good find.

**Comment by LlmDl** [comment]
Ok I'm fairly sure I've fixed the first part (new towns acting like they aren't already set on their desired peaceful setting.)

I'm reading over the next part (losing the nation.)

From what I can see, any peaceful town has to have a Guardian Town with a nation near to it.

If it does not have a guardian town, then it is kicked from its nation (leading to an empty nation in your scenario, which causes the nation to be deleted.)

What I'm trying to figure out is if this was ever supposed to affect a town that has its own nation? Are towns with nations not supposed to be able to be peaceful?

**Comment by LlmDl** [comment]
Ok, so when a peaceful town goes to make a nation, they are shown a message that this is a bad idea.

The bug you found meant that towns which were not peaceful (and were not shown the warning message on nation-creation,) were having their peaceful status set to on, then immediately having their nation deleted because they were peaceful.

**Comment by LlmDl** [comment]
BTW: thanks for being brave and trying out the siegewar/master branch. I'm still not getting very much feedback on the dev builds I've been giving out, so the little things that have gotten reconnected wrong are potentially still out there.
