### ISSUE TITLE
Suggestion: Add "/town list public [Integer]"

### ISSUE THREAD

**Issue by GrandMelo** [TownyAdvanced/Towny#4628]
**Please explain your feature request to the best of your abilities:**

On the server I am playing, there is an economy which works by visiting the public towns and buy and their shop. Since town list only shows 10 towns each page included not public ones, it is bad for newer unknown shops to rise, so that "/town list public" would be an equivalent to a "shop list". It also would show towns, mayors want visitors to know nonetheless if there is a shop.

I thought it would be a nice addition to the project. With Integer I mean, which page number should be shown. I think that part is already included in the command "/town list".

**Comment by LlmDl** [comment]
This is a good idea. I'll see about adding it after Christmas.
