### ISSUE TITLE
Suggestion: Per player's plot ban system

### ISSUE THREAD

**Issue by TKwSni** [TownyAdvanced/Towny#4632]
**Please explain your feature request to the best of your abilities:**

Basically, an "outlaw" system but per plot...  if a player adds someone to their "enemy list" even if they are in the same town, teleport the player out of the plot, nobody wants unwanted players in their properties, I think many players would like this.

This list unlinke the "friend list" should be only visible for the player and maybe admins.

**Comment by GNosii** [comment]
essentially plot outlaws
