### ISSUE TITLE
Chest Issue

### ISSUE THREAD

**Issue by Tauses** [TownyAdvanced/Towny#4636]
### What steps will reproduce the problem?
1. Deop yourself 
2. Place chest outside of a claim
3. 

### What is the expected output?
1. You get a message saying you dont have permission to place down a chest
2.
3.

### What is your Towny version?
Do not say "latest".
Towny-SeigeWar-0.96.5.8-Snapshop2631c80

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.4 Paper

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[latest.log](https://github.com/TownyAdvanced/Towny/files/5748775/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) : 
[config.txt](https://github.com/TownyAdvanced/Towny/files/5748780/config.txt)

3. Your townyperms.yml: 
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/5748781/townyperms.txt)

4. Your log's error : There is none.

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
So what does it actually say when you cannot place the chest?

**Comment by Tauses** [comment]
[Towny] You dont have enough permissions for that command.
