### ISSUE TITLE
Dynmap-Towny is not showing

### ISSUE THREAD

**Issue by Krissdrzp** [TownyAdvanced/Towny#4637]
Hello.

I cant seem to get Towny-Dynmap working on my server. 
I've talked to LlmDI at discord, but we could not solve it right away. Is there anything here we could go deeper into?

Kindly regards,
Programmet
Discord: Programmet#8569
[2020-12-28-2.log](https://github.com/TownyAdvanced/Towny/files/5749162/2020-12-28-2.log)

**Comment by Krissdrzp** [comment]
Webmap: http://spill.eikamc.no/

**Comment by 0xBit-MC** [comment]
Misconfigured Dynmap/configuration.txt appears to be the issue. Solution was having them simply remove the configuration and go through it one by one. 

Also had them try EP-Dynmap-Towny for 1.16.4 and Towny 0.96.5.0+

Image of working map: https://i.imgur.com/UupnbVB.png
