### ISSUE TITLE
Plot name not switching when moving from a for sale plot to an unowned plot

### ISSUE THREAD

**Issue by Managering** [TownyAdvanced/Towny#4638]
### What steps will reproduce the problem?
1. have a town
2. set a plot for sale
3. set a plot as unowned
4. walk from plot for sale to unowned

### What is the expected output?
1. the plot name should update to reflect "Unowned"
2. Just like walking from a owned plot, to an unowned plot

### What is your Towny version?
Towny-0.96.5.7.jar, was also in the 0.96.5.0 release

### What is your spigot/craftbukkit version?
1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
99% sure these files wouldn't be required. I'll resubmit if required.

forgot to add screenshot:
https://imgur.com/a/KaouFOj

**Comment by LlmDl** [comment]
The plot which has been set for sale, was it personally owned by your resident or town-owned?

**Comment by Managering** [comment]
It is a town owned plot which has been set for sale.

**Comment by LlmDl** [comment]
It is unowned then, the not-for-sale plot is also unowned, so when you pass between them, the Unowned has not changed and will not be shown.

**Comment by Managering** [comment]
Wouldn't it make more sense to show the difference in being for sale and just being an unowned plot?

Right now if you go from a plot for sale to an unowned plot, it seems like the unowned plot is for sale as well, as it doesn't update.

**Comment by LlmDl** [comment]
It should show a not-for-sale, as that is what is actually changing.
