### ISSUE TITLE
Sheep cannot be sheared in towns

### ISSUE THREAD

**Issue by Managering** [TownyAdvanced/Towny#4641]
### What steps will reproduce the problem?
1. have a town
2. have a farm plot with sheep
3. try to let someone shear the sheep with item_use perms on

### What is the expected output?
1. it's expected that item_use enables shearing
2. It does not
3. Even with destroy on it's not possible to sheer. After turning kill on, sheeps were killable, but not shearable.

What is your Towny version?
Towny-0.96.5.7.jar

What is your spigot/craftbukkit version?
1.16.4

pic: https://imgur.com/a/wGHjnHu

(Cow milking does work, tested that after)

**Comment by LlmDl** [comment]
Turn on destroy. Shearing is not an itemuse test any more.

**Comment by Managering** [comment]
Even with destroy it does not allow sheeting.

Plus shouldn't sheeting be an item use thing?

**Comment by LlmDl** [comment]
It used to be, but a number of things that were switch/itemuse have become destroy tests, because that is more accurate to what is being done. I'll need you to refile this without skipping the form. Call the ticket: "Shearing sheep in farm plot doesn't respect destroy  permission."
