### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by ArkQuark** [TownyAdvanced/Towny#4642]
### What steps will reproduce the problem?
1. Install plugin in magma server
2. Install mods in server
3. Made a town

### What is the expected output?
1. [WARN] [com.palmergames.bukkit.towny.Towny] [Towny] Task #35 for Towny v0.96.2.0-for-1.12.2 generated an exception
java.lang.NullPointerException: null

### What is your Towny version?
Do not say "latest".
Towny 0.96.2.0-for-1.12.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Magma on Bukkit 1.12.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://log.mtxserv.com/tELfvU0
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/mpU2WvEy
3. Your townyperms.yml : https://pastebin.com/ZrxEXVtg
4. Your log's error :  

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/QYrEiMsB

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Show me the spam

**Comment by ArkQuark** [comment]
https://pastebin.com/XzYBA9TX

**Comment by LlmDl** [comment]
Looks like you shouldn't be using the revert-on-unclaim feature with your mods. Bukkit doesn't know what the blocks are.

Turn it off using `/tw toggle revertunclaim` in each world and delete the `towny\data\plot-block-data\` folder.

**Comment by ArkQuark** [comment]
Thanks
