### ISSUE TITLE
[Siege War] Explosions do not damage blocks

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#4645]
### What steps will reproduce the problem?
1. Enable siege war (`enabled: 'true'`).
2. Enable forced explosions (`/tw toggle forceexplosion`). 
3. Ignite a TNT block. It does not matter whether it is placed in Wilderness or a town. There will be no block damage. 
4. Disable siege war and reload the config (`/ta reload config`).
5. Ignite a TNT block. The surrounding terrain will now be damaged. 

### What is the expected output?
Explosions should damage the blocks, given that `forceexplosion` is set to true in the world. Note that the issue will occur regardless of whether this is toggled - it is enabled for the sake of illustration. 

### What is your Towny version?
Siege war at the [latest](https://github.com/TownyAdvanced/Towny/commit/c540ca9e68a5876aeed0f4d01f6f55c89e4247d9) commit. 

### What is your spigot/craftbukkit version?
git-Purpur-933 (MC 1.16.4)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : [Link](https://pastebin.com/F9wsy1nC).
2. Your Towny config.yml (if using MySQL please remove password,) : [Link](https://pastebin.com/fyYuYj6H).
4. Your log's error : N/A. There is no error.

**Comment by LlmDl** [comment]
Siege war has it's own setting: 
```
      # If true, then town explosions are always set to on during sieges.
      # The town explosions flag returns to its previous value when the siege ends.
      # The setting is false by default, because SiegeWar is designed to be minimally-destructive.
      # The setting is only recommended for use in combination with a block regeneration feature.
      explosions_always_on_in_besieged_towns: 'false'
```

Try setting that to true and check what happens please.

**Comment by LlmDl** [comment]
You are correct in that the force explosion setting should still work, I'd just like to know how it works with the SiegeWar config set properly as well.

**Comment by galacticwarrior9** [comment]
I can confirm the issue still occurs with `explosions_always_on_in_besieged_towns` set to true.

**Comment by LlmDl** [comment]
After looking at the code, it should only be stopping block explosions which are going to affect a siege banner. But you're saying it is affecting explosions across the entire world?

**Comment by LlmDl** [comment]
In testing I could not get explosions to not blow up. Are you sure that it is Towny stopping the explosions?
