### ISSUE TITLE
Shearing sheep in farm plot doesn't respect destroy permission.

### ISSUE THREAD

**Issue by Managering** [TownyAdvanced/Towny#4652]
What steps will reproduce the problem?
have a town
have a farm plot with sheep
try to let someone shear the sheep with item_use perms on
What is the expected output?
it's expected that item_use enables shearing
It does not
Even with destroy on it's not possible to sheer. After turning kill on, sheeps were killable, but not shearable.
What is your Towny version?
Towny-0.96.5.7.jar

What is your spigot/craftbukkit version?
1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : There is no start up error. It's a townyperms thing so if you don't mind I am leaving this one out.
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/oxujeqiked.coffeescript
3. Your townyperms.yml : https://hastebin.com/ufelokigay.yaml
4. Your log's error : no log error.

**Comment by LlmDl** [comment]
Can you try adding SHEARS to the `farm_plot_allow_blocks` list in the config and seeing if it allows it them, please?

**Comment by Managering** [comment]
As long as it is a farm plot with resident destroy on, sheeps can now be sheared. Blocks that are not specified in the config are not destroy-able. 

Solved. Thank you.

For privacy things I am removing the hastbins in the ticket :)
