### ISSUE TITLE
Placeholder not updating.

### ISSUE THREAD

**Issue by AAigars** [TownyAdvanced/Towny#4653]
### What steps will reproduce the problem?
1. Check the value of %townyadvanced_town_balance% and then deposit/withdraw and then recheck the value and it will stay the same. I'm using iConomy not sure if it is related to that.

### What is the expected output?
1. For the value to update once you deposit/withdraw.

### What is your Towny version?
`Towny-SeigeWar-0.96.5.9-SNAPSHOT+c0d7e5a`

### What is your spigot/craftbukkit version?
`git-Tuinity-"610b3aa" (MC: 1.16.4)`

### Please use Pastebin.com to link the following files:
**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : `Nothing really in latest.log, didn't want to expose the ips of my players. If you need it dm me on discord Luaa#0381.`
2. Your Towny config.yml (if using MySQL please remove password,) : `https://pastebin.com/raw/VTT6yD0z`
3. Your townyperms.yml : `https://pastebin.com/raw/x55Pyydk`

**Comment by LlmDl** [comment]
The placeholder uses a cache so we aren't hitting the economy plugin all the time:
`bank_account_cache_timeout: 600s` 

Are you certain the bank value doesn't change after 600 seconds?

**Comment by AAigars** [comment]
> The placeholder uses a cache so we aren't hitting the economy plugin all the time:
> `bank_account_cache_timeout: 600s`
> 
> Are you certain the bank value doesn't change after 600 seconds?

I feel so stupid, lmao. That is probably why yes. Let me take a look.

**Comment by AAigars** [comment]
Yep, that was the problem. Any major problems with lowering the cache timeout to like 120 seconds?

**Comment by LlmDl** [comment]
Not really, depends on how your eco handles it.

**Comment by AAigars** [comment]
Alright, thank you :)
