### ISSUE TITLE
Error with command /t new or /town new

### ISSUE THREAD

**Issue by PVC69** [TownyAdvanced/Towny#4656]
### What steps will reproduce the problem?
1. command: /t new
2.
3.

### What is the expected output?
1.Error
![Screenshot_15](https://user-images.githubusercontent.com/76838201/103437860-db830180-4c2c-11eb-8980-0fe9f99d4bd1.jpg)
![Screenshot_16](https://user-images.githubusercontent.com/76838201/103437953-c78bcf80-4c2d-11eb-8f9e-53b0c93e3081.jpg)

2.
3.

### What is your Towny version?
Do not say "latest".
v0.96.5.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.1 Paper

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[latest (2).log](https://github.com/TownyAdvanced/Towny/files/5758858/latest.2.log)

2. Your Towny config.yml (if using MySQL please remove password,) : 
[config_and_townyperms.zip](https://github.com/TownyAdvanced/Towny/files/5758862/config_and_townyperms.zip)

3. Your townyperms.yml :
4. Your log's error : 
![Screenshot_15](https://user-images.githubusercontent.com/76838201/103437944-99a68b00-4c2d-11eb-88dd-55c5536d7516.jpg)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Update your spigot/paper and try again.

**Comment by PVC69** [comment]
Updating my spigot/paper will result in 10 other plugins not working

**Comment by LlmDl** [comment]
I guess you're in a pickle then. Update it to the last-possible version of 1.16.1.

**Comment by PVC69** [comment]
Why would it be a problem with paper, if it worked for entire month completly fine?

**Comment by LlmDl** [comment]
There were some early-ish versions of 1.16.1 that didn't handle hover text the way it is handled now.

**Comment by PVC69** [comment]
i tried a newer 1.16.1 and same error

**Comment by LlmDl** [comment]
How about you show me the full version number of that 1.16.1 version.

**Comment by PVC69** [comment]
well i dont have it anymore i updated to 1.16.4 and now im debugging 2 other plugins to work so server is fixed...
Got any idea about this?
![Screenshot_19](https://user-images.githubusercontent.com/76838201/103438753-c01cf400-4c36-11eb-8074-112480f5f0b7.jpg)

**Comment by LlmDl** [comment]
I'd try redownloading anything that gives you a "Invalid plugin.yml" message and if that fails, talk to the plugin author.

**Comment by PVC69** [comment]
ok, i redownloaded but same problem, i contacted the plugin author
