### ISSUE TITLE
Crossbow firework damage in claims

### ISSUE THREAD

**Issue by DasCodes** [TownyAdvanced/Towny#4657]
### What steps will reproduce the problem?
1. Shoot with a loaded firework crossbow in claims while pvp is off.
Edit 2. You're able to damage players. (Going to check if it applies to mobs as well)

### What is the expected output?
Edit 1. No damage.

### What is your Towny version?
0.96.5.10

### What is your spigot/craftbukkit version?
Custom fork of paper 1.15.2.

**Comment by LlmDl** [comment]
You want players to receive damage when PVP is off?

**Comment by DasCodes** [comment]
No, players receive damage even when the pvp is off in claims.

**Comment by LlmDl** [comment]
Ok, your explanation of how to make it happen and what you want to happen is a bit off up there.

**Comment by DasCodes** [comment]
Oh right my bad, sorry. So the expected output should be "No damage to players".
