### ISSUE TITLE
Suggestion: Town ranks in chat

### ISSUE THREAD

**Issue by Scones91** [TownyAdvanced/Towny#4658]
**Please explain your feature request to the best of your abilities:**
As I've seen in other issues and was told in discord this is not currently feasible due to the ability of having more ranks. I suggest that this is added with a posibility of adding a weighting/priority of the ranks so the highest one is the one shown.

(Feeling like this short explanation covers it ;))

**Comment by HotProtato** [comment]
Adding on to this, it'd be great if the rank ladder was added and optional. If the ladder is disabled, only use the groups currently used, otherwise, use the highest group on the ladder the player has.
