### ISSUE TITLE
Towny uses lowest priority & value node instead of highest value/highest priority node

### ISSUE THREAD

**Issue by Aiden-WTF** [TownyAdvanced/Towny#4660]
### What steps will reproduce the problem?
1. Make two ranks with the same node (ex. outposts) yet different values
2. Test which takes priority, seems to always be lowest priority node/value or the one added first (ex. default group's node)

### What is the expected output?
1. Towny uses the highest priority in LP or highest value node.

### What is your Towny version?
0.96.5.6

### What is your spigot/craftbukkit version?
1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : 
3. Your townyperms.yml : https://pastebin.com/52mR3MMd

(optional) If this is to do with permissions, 
5. Your permissions file :

**Comment by LlmDl** [comment]
Skipped form, I need to see the LP editor.

**Comment by Aiden-WTF** [comment]
What exactly do I give you for you to see the LP editor/where do I find this? Thanks.

**Comment by LlmDl** [comment]
I believe the command is /lp editor

**Comment by Aiden-WTF** [comment]
https://luckperms.net/editor/bJhm1sFo75

**Comment by LlmDl** [comment]
Ok, I've taken a look and before I start testing things I'd like you to try a couple things;

1. There's a bunch of the wrong nodes in your LP. Ranks like Zues, Hades, Aries, Poseidon, Helios have `meta.towny_outposts.12` which is not the correct node (meta.towny_maxoutposts.12 would be correct.) Please remove these.
2. Like-wise `meta.towny_maxoutposts:.12` is not a node either, adding the : to the meta node is not needed. (Other permission plugins use meta/info/option nodes very differently than LP.
3. Instead of using the meta nodes you should consider using the standard permission node: instead of `meta.towny_maxoutposts.#` give `towny_maxoutposts.#`.

**Comment by Aiden-WTF** [comment]
The wrong nodes are not the ones being tested, therefore it isn't really too much of a concern to update them until I find a solution. The : to nodes was just a pre-caution as I didn't know how it worked exactly. Also, I tried to use regular permissions right now but it still doesn't seem to work.

**Comment by LlmDl** [comment]
So this morning I tested this out with some added debug code in Towny.

First I made a track with the default group and two more, each one got a higher number of max_outposts than the previous group in the track. 
After being set using the '/lp group plustwo meta set towny_maxoutposts 6' command this is how it appears: 
![Capture](https://user-images.githubusercontent.com/879756/103536633-81ff1a80-4e58-11eb-9610-7047b6b599bb.PNG)

I had no issue with the either of the previous groups in the track overriding the correct amount I was supposed to have.

Second, I deleted the track and used the parent groups like you have on your server, making the groups inherit each other.

I had no issue again, I received the correct number response from LP via Vault for my primary group's towny_maxoutposts meta value.

Not sure what to tell you if you want to try out my copy with the debug code I'd share it with you.

**Comment by Aiden-WTF** [comment]
I guess? I'm not sure why this is happening to me exactly. If you want, you can join the server I'll give you perms for more outposts and you can see? But, weird.

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/795731412379631676/Towny-0.96.5.13.jar

You'll see debug messaging in the console/logs.

**Comment by Aiden-WTF** [comment]
I've had time to expirement here. So, it seems the issue is that the players experiencing issues have a primary group which inherits permissions from the default group (max 3 outpost group) and that is their primary. However, their non-primary group has a higher amount of allowed outposts. I think that Towny should automatically use the higher amount of outposts (or allow an option to do that) as sometimes the primary group isn't the one that has the correct amount of outposts.

I have screenshots of my experiment here, both people showing the issues with the same recreation.

**Player 1:**

Console Log:
https/i.aiden.wtf/chrome_pDB9KmvQ4M.png

Permissions:
https/i.aiden.wtf/chrome_AUvRSiWA88.png

**Player 2:**

Console Log:
https://i.aiden.wtf/chrome_0clAVIc8SI.png

Permissions:
https://i.aiden.wtf/chrome_BeP0xSxf8q.png

**Comment by LlmDl** [comment]
So you're basically showing me that the primary group's maxoutposts is being returned properly, you're just not treating their primary group as the primary group. You have to solve for your weighting.
