### ISSUE TITLE
Editing the ChatConfig.yml doesn't do anything

### ISSUE THREAD

**Issue by stijnjw** [TownyAdvanced/Towny#4673]
### What steps will reproduce the problem?
1. Edit the "both" string in tag_formats in ChatConfig.yml
2. /ta reload all
3. It doesn't do anything

After changing it and reloading: https://prnt.sc/whqxn0 (default)
(I'm trying to remove the nation part because it's too long)

### What is the expected output?
The prefix changes to what you make it to

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
I'm not sure where do find this, but I don't think it matters.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/EmYVS3E5
2. Your Towny config.yml (if using MySQL please remove password): https://pastebin.com/DskTFtci
3. Your townyperms.yml: https://pastebin.com/mEVqPAhx
4. Your log's error: none

(optional) If this is to do with permissions, 
5. Your permissions file: /

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/Ec9RHvjx
7. Your channels.yml: https://pastebin.com/qfr2GCBk

**Comment by LlmDl** [comment]
Does it work if you use `/townychat reload`?

**Comment by stijnjw** [comment]
Oh, I didnt know that was a thing. I'll try it tomorrow, thank you for the help :)
