### ISSUE TITLE
Suggestion: Autofill names for town/nation invites

### ISSUE THREAD

**Issue by bartymc** [TownyAdvanced/Towny#4674]
**Please explain your feature request to the best of your abilities:**
Autofill the names of players and towns when using the town and nation invite commands.

**Comment by LlmDl** [comment]
Can you tell me which commands are being used exactly?

**Comment by LlmDl** [comment]
So I found that `/t add` was not made to tab-complete and have made it work, but looking at `/n add` it is set to tab complete.

**Comment by bartymc** [comment]
I believe I was mistakenly trying to use /n invite instead of /n add, I can confirm that /n add tab completes.
