### ISSUE TITLE
Towns without a nation cannot be attacked

### ISSUE THREAD

**Issue by OLdGoogol** [TownyAdvanced/Towny#4677]
### What steps will reproduce the problem?
1.set the towns_are_neutral to false
2.use /Ta toggle War to start a war
3.when the War is active, a nation member cannot reduce a non-nation town's HP. However, the town's residents lose their permission to build or switch as well, with a message:'destroying xxblock is not allowed in the warzone. 
It is obvious that the town is deemed as in a warzone, but not attackable.

### What is the expected output?
1.A town without a nation can be attacked
2.When outsiders stand on its blocks, they can see the change of the townblocks' HP
3.Otherwise, all towns will quit their nations for avoiding the danger of involvement in a War.

### What is your Towny version?
Do not say "latest".
0.96.5.13

### What is your spigot/craftbukkit version?
Do not say "latest".
paper-211

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This is something that won't be an issue when the event war revamp happens his year.

For now: EW was never supposed to have nation-less towns play much of a role. The town_are_neutral setting was mainly to allow nation-less towns the ability to pvp in the war, but they still would not be able to attack townblocks' HP or have their townblocks HP attacked.

The nation-less towns not being able to destroy or switch does sound like a bug which I will look at.
