### ISSUE TITLE
Suggestion: Allow plot evict to have admin support

### ISSUE THREAD

**Issue by RSNFreud** [TownyAdvanced/Towny#4678]
**Please explain your feature request to the best of your abilities:**

Allow admins to use /townyadmin plot evict to evict a member from a town they are not a part of

**Comment by LlmDl** [comment]
Did you want them evicted from the town they belong to or evicted from a plot the player owns personally?

**Comment by glassesUSA** [comment]
Plot

**Comment by RSNFreud** [comment]
Evicted from the plot the player owns
