### ISSUE TITLE
Suggestion: Flaggs for Villager Trading

### ISSUE THREAD

**Issue by AlmightyAnubis** [TownyAdvanced/Towny#4681]
Currently trading with villagers is a problem in our town. We have an market place and villager trading wasn't protected in earlier versions of towny so everyone could trade with them. With the update, only the Plot- and the Townowner can trade with villagers, wich makes our market place quit useless. Is it possible, to add some kind off flags for villager trading, so you can toggle who can trade with the villagers.

My other suggestion would be, to allow trading on Shop plots, but this would be the worse solution.

**Comment by LlmDl** [comment]
I haven't done anything to make Towny affect who can trade with villagers, so I don't know what your having happen. What message is shown when they try to trade with a villager?

**Comment by AlmightyAnubis** [comment]
The villager GUI just doesn't open, there is no more message. I am not the server admin, but the admin told me, I should ask here and he doesn't affect this

**Comment by LlmDl** [comment]
Yeah it's not Towny causing the issue, sorry.
