### ISSUE TITLE
Dynmap Shows Local Chat

### ISSUE THREAD

**Issue by nikupatel** [TownyAdvanced/Towny#4684]
### What steps will reproduce the problem?
1. Install Towny
2. Install Towny-Dynmap
3. Localchat should be set as GLOBAL with a range

### What is the expected output?
1. Localchat shows up on the dynmap just like generalchat

### What is your Towny version?
0.96.5.14
### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 400
(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://pastebin.com/epDL3Hxa
7. Your channels.yml :
https://pastebin.com/qHMdp4uY

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/800718795286904832/TownyChat-0.87.jar

Can you test this out for me?
