### ISSUE TITLE
When I change Friendly-Fire settings, they don't change ingame

### ISSUE THREAD

**Issue by lucakaleron** [TownyAdvanced/Towny#4685]
### What steps will reproduce the problem?
1. Changing friendly-fire from false to true in the config and world file after already playing on that world
2.
3.

### What is the expected output?
1. Friendly-Fire now allowed
2.
3.

### What is your Towny version?
Do not say "latest".
- 0.96.5.7

### What is your spigot/craftbukkit version?
Do not say "latest". 
- Spigot 12

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/XTqeCvYM
3. Your townyperms.yml : https://pastebin.com/Q6qmhvQa
4. Your log's error : 
5. World File: https://pastebin.com/vhTkXFN8

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by lucakaleron** [comment]
I'm aware that the friendly-fire settings in the config only affect newly created worlds and not already existing ones, that's why I also changed it in the world.txt file

**Comment by LlmDl** [comment]
using `/tw toggle friendlyfire on` will work. There was a visual bug in the feedback of the command in earlier builds. No one should be using 0.96.5.7 any more.
