### ISSUE TITLE
Suggestion: Easier Jail info

### ISSUE THREAD

**Issue by Zenomac** [TownyAdvanced/Towny#4686]
I've been doing a bit of configuration with towny and towny wars... I'm wondering if you (towny devs) can add a description when jailed on how to become un-jailed. It took me a while to figure it out personally and ended up having to google it. Having new people especially new people to Minecraft would make it difficult to explain to everyone every time someone asks. 

**Change the jail message to something that describes how to bail yourself out**

I'm sure it's not a super difficult enhancement to add but it's just a QOL change :)

**Comment by LlmDl** [comment]
That's a good idea, will be part of the Jail revamp for sure. I'm thinking a book gui showing the possible ways to become unjailed specific to the server, written via the config settings.
