### ISSUE TITLE
Suggestion: Request terminology change - from town "Conquered" to town "Occupied"

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/Towny#4688]
h3. DESCRIPTION
- There is a flag in the Town object, DB, and Town screen, to indicate if a town is occupied or not
- Currently the flag has the name "Conquered"
- However this terminology is wrong. 
- For example, Paris during WW2 was known as "Occupied Paris", not "Conquered Paris"
- In general, "conquering" is the act of invasion, but once the invasion is complete, a territory is given the status of "Occupied".

h3. EXPECTED
- I don't mind about the backend variable names, but if possible, please change the tag which displays at the top of an occupied town screen from "Conquered" to "Occupied".

**Comment by LlmDl** [comment]
This is a configurable bit in the language file, but I'm happy to change it.
