### ISSUE TITLE
TownySwitchEvent is not thrown for outsider trying to sit in minecart

### ISSUE THREAD

**Issue by Abwasserrohr** [TownyAdvanced/Towny#4690]
### What steps will reproduce the problem?
1. Catch the TownySwitchEvent event.
2. Try to sit in a minecart that is within a town (player is a outsider)

### What is the expected output?
1. The TownySwitchEvent event should be thrown even if the player (outsider) is sitting in the minecart to modify the outcome.

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
git-Paper-401

### Files

I append additional files if required.

**Comment by LlmDl** [comment]
Skipped form.
