### ISSUE TITLE
Colored Town Names

### ISSUE THREAD

**Issue by Kovalski4** [TownyAdvanced/Towny#4692]
### What steps will reproduce the problem?
1. Create town or rename exist town with started '&' character.
2. Town name appears like colored

### What is the expected output?
1. & char isn't allowed or town name not colorfull

### What is your Towny version?
0.95.5.13

### What is your spigot/craftbukkit version?
Custom

My players don't hate this. They are loved! Colored town names look like more characteristic. But towns named started with '&' looks like ugly. It can be added as a new feature. Custom town colors!

**Comment by LlmDl** [comment]
You can prevent the use of & by modifying the regex. If this ticket is about some parts of the Towny message outputs not parsing out the & then we would need to see which areas they are not being parsed out.
