### ISSUE TITLE
Towny Chat issue with newest release

### ISSUE THREAD

**Issue by JustJP2K** [TownyAdvanced/Towny#4694]
5.01 15:30:25 [Server] ERROR Could not pass event AsyncPlayerChatEvent to TownyChat v0.85
15.01 15:30:25 [Server] INFO java.util.UnknownFormatConversionException: Conversion = 'r'
15.01 15:30:25 [Server] INFO at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:101) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:186) ~[?:?]
15.01 15:30:25 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1132.execute(Unknown Source) ~[?:?]
15.01 15:30:25 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1934) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1849) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1787) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.4.jar:git-Paper-414]
15.01 15:30:25 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
15.01 15:30:25 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
15.01 15:30:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
15.01 15:30:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
15.01 15:30:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

**Comment by LlmDl** [comment]
Skipped the form.
