### ISSUE TITLE
Throwing Enderpearl inside owned region results in console-error

### ISSUE THREAD

**Issue by TamrielNetwork** [TownyAdvanced/Towny#4695]
### What steps will reproduce the problem?
1. Use latest paper - 416
2. Use TownyAdvanced 0.96.6.0
3. Throw Enderpearl inside town you own (maybe even if youre only allowed to itemuse) (or only if you got * perm/op/owner rank)

### What is the expected output?
1. Get teleported -> you do but it gives you errors
2. Don't get console error

### What is your Towny version?
Do not say "latest".
0.96.6.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper-416

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/Vtpaqwaw
2. Your Towny config.yml (if using MySQL please remove password,) : Can't paste because of pastebins smartfilter... Shouldnt be the issue anyways tho
3. Your townyperms.yml : https://pastebin.com/SX8frAqB
4. Your log's error : https://pastebin.com/Qr7kuMUt

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by TamrielNetwork** [comment]
Its not only when throwing pearls. https://pastebin.com/8yqYgV8m
Seems like most permissions result in this error.
It may be because Im owner and got the * permission node. But I dont really think that thats intended.

**Comment by LlmDl** [comment]
Whats your exact mc account name?

**Comment by TamrielNetwork** [comment]
leop2

**Comment by LlmDl** [comment]
Ok, so the error is taking place in the PlayerCache where it's trying to use your UUID to get a Resident object from the database, it is failing to get the Resident (which should never happen.)

I will need you to show me your towny\data\residents\leop2.txt file.

**Comment by TamrielNetwork** [comment]
okay. I removed the townynameupdater jar (which was stated that it isnt needed anymore) maybe thats why?
I use mysql but this is the data-file
https://pastebin.com/2hGitC39

**Comment by LlmDl** [comment]
Your resident file has somehow gotten the wrong UUID stored at some point:

83fa10aa-2019-401b-8ae2-72f7789b0f4c put that in it's place or delete the line and let towny re-add the correct line.

**Comment by TamrielNetwork** [comment]
Okay sure thanks a lot! Then it had to do with me removing the nameupdater probably. I had it installed until 0.95.0.0 and removed it today. Ill try it and close it if its fixed! Thanks a lot!!

**Comment by TamrielNetwork** [comment]
And have I got to change it inside the mysql db too? I dont want to mess this up. I noticed it also changed the uuid of leop4 (one of my alts that joined after the update). So I dont really wanna clear out all uuids if it affected not only players that joined after the update

**Comment by TamrielNetwork** [comment]
Okay after deleting the UUIDS of leop2 and leop4 in the mysql-database they changed to the right ones. Thanks a lot for the help! Hope  it didnt affect other players.

**Comment by LlmDl** [comment]
I had not noticed you were using MySQL, the MySQL DB will have to have its UUID altered to your actual UUID.
