### ISSUE TITLE
Suggestion: Permission-based Daily Upkeep Discounts

### ISSUE THREAD

**Issue by GeneralSarcasam** [TownyAdvanced/Towny#4696]
**Please explain your feature request to the best of your abilities:**

Giving a town's mayor or nation's king a permission (such as towny.nation.discount or towny.town.discount) would reduce the town's or nation's daily upkeep by a percentage specified in the config file.

**Comment by LlmDl** [comment]
Very similar to #2613. Runs into the same trouble of having to do permission lookups on players during the daily timer task though.

**Comment by SuperEms** [comment]
I think this would be a great and useful feature as well. I'd really like to see it added.
