### ISSUE TITLE
Database error lags out the server

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#4699]
This problem lags the server a lot at random momments, the connection to the database works fine until this happens, and it fixes itselft after 15-30 seconds. The guys of the hosting i use say its a problem of the plugin (HumbleServers) or its configuration. It cant be wrong credentials bc it connects and saves/loads data from the database, it just ends the connection at some point for no reason and then resumes. The problem is that when that happens it lags the server and kicks people out.

### What steps will reproduce the problem?
1. start the server using mysql storage
2. wait for some minutes/hours until it randomly happens

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
git-Paper-416 (MC: 1.16.4)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :
[latest.log](https://github.com/TownyAdvanced/Towny/files/5826789/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) :
[config.txt](https://github.com/TownyAdvanced/Towny/files/5826794/config.txt)

3. Your townyperms.yml :
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/5826793/townyperms.txt)

4. Your log's error : 
![image](https://user-images.githubusercontent.com/25410859/104855074-57e23980-58e9-11eb-8fbe-3eaaab9a51d2.png)

**Comment by LlmDl** [comment]
Is the mysql hosted on the same machine as the towny server?

**Comment by ElMoha943** [comment]
In other one

**Comment by LlmDl** [comment]
That's why it cannot stay connected. Don't use a non-localhost mysql db. Use towny in flatfile and update your server to 0.96.6.0.

**Comment by ElMoha943** [comment]
@LlmDl is there a way to export the mysql data to a flatfile?

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#converting-sql-to-flatfile
