### ISSUE TITLE
Error in /t deposit from version 0.96.5.4

### ISSUE THREAD

**Issue by Espantonius** [TownyAdvanced/Towny#4707]
### What steps will reproduce the problem?
1. Place version 0.96.5.4 or higher
2. Create a city and place the command / t deposit

### What is the expected output?
You would have to deposit the money but an error message appears. "Withdrawing from this bank is disabled"

### What is your Towny version?
I have tried all of version 0.96.5.X

### What is your spigot / craftbukkit version?
I've tried with two: Paper (MC: 1.16.4) and Tuinity (MC: 1.16.4)

I have also tried all four economy plugin recommendations and have the same bug.
It seems that since the change "Rework town and nation withdraw / deposit to reduce redundancies." in version 0.96.5.4 and later it has stopped working.
![Screenshot_1](https://user-images.githubusercontent.com/14083246/105199333-f5827680-5b3e-11eb-9f7b-b2d17b7f3da4.png)

**Comment by LlmDl** [comment]
This is likely something with your config, which you did not supply. I have been testing deposit/withdrawing all over the place during teh 0.96.5.* development, without issue. Share your config.

**Comment by Espantonius** [comment]
This is my config: https://gist.github.com/Espantonius/80600c63ba1d73236045d5f3ea44254f

**Comment by Espantonius** [comment]
Apparently it is for this option:
     # Set to true to allow withdrawals from town banks
     town_allow_withdrawals: 'false'
     # Set to true to allow withdrawals from nation banks
     nation_allow_withdrawals: 'false'

If i activate this they will be able to withdraw money. What do i have to deny permissions so that the command does not use it?

**Comment by LlmDl** [comment]
Fixed it: https://cdn.discordapp.com/attachments/669247087329673228/801491007664422912/Towny-0.96.6.1.jar

Make sure you re-download the 0.96.6.1 when its out for real.
