### ISSUE TITLE
In the latest release withers can damage town claims even with mobs and explosions off in towns

### ISSUE THREAD

**Issue by MoistPencil** [TownyAdvanced/Towny#4708]
### What steps will reproduce the problem?
1. Disable Mobs in a town
2. Summon a Wither and stand in the town claims
3. Watch as the Wither destroys everything within the town (lol)

### What is the expected output?
1. ~~Wither will bypass mob greifing; off~~
2. Wither will not destroy blocks within the town
3. Wither will not kill mobs within the town.

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.96.6.0

### What is your spigot/craftbukkit version?
Do not say "latest".
I use puprpur #959 which is a fork of Paper Spigot and Tunity. This incorporates Spigot version 1.16.5.
(purpur is not a hard performance improvement and just allows for more in-depth configuration options so this should cause no issues)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/raw/q58is6tK
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.pl/view/2f294e71
3. Your townyperms.yml :
https://pastebin.pl/view/dc2e5c34
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Players did not know what they were talking about on this one.
