### ISSUE TITLE
Towny v0.96.7.0 NullPointerException

### ISSUE THREAD

**Issue by Wolf2323** [TownyAdvanced/Towny#4710]
### Problem
Since a update yesterday to the new Towny version the linked exception is spammed in the log.

### What is your Towny version?
Do not say "v0.96.7.0".

### What is your spigot/craftbukkit version?
Do not say "git-Tuinity-"1d169e7" (MC: 1.16.5)".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : Patebins SMART filter prevented me from uploading -> https://paste.ubuntu.com/p/YP5Hq3jFpb/
3. Your townyperms.yml : https://paste.ubuntu.com/p/pqZrJxG8QV/
4. Your log's error : https://pastebin.com/rtgneVjQ

**Comment by LlmDl** [comment]
So it looks like an NPC is killing a player? Try this out: https://cdn.discordapp.com/attachments/669247087329673228/801799710863392789/Towny-0.96.7.1.jar

**Comment by Wolf2323** [comment]
This has fixed it ;)
