### ISSUE TITLE
Local Chat Broken

### ISSUE THREAD

**Issue by JustJP2K** [TownyAdvanced/Towny#4711]
### What steps will reproduce the problem?
Use townychats local chat and try to talk to others

### What is the expected output?
Says no one is in range or you are alone in this channel

### What is your Towny version?
0.96.6.0
Towny Chat
0.86

### What is your spigot/craftbukkit version?
1.16.5

1. Your full server startup from the logs\latest.log : https://paste.helpch.at/ubebejozig.md
2. Your Towny config.yml: https://paste.helpch.at/hunidagiso.coffeescript
3. Your townyperms.yml : https://paste.helpch.at/xubituduma.php
4. Your log's error : 
No error

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://paste.helpch.at/hozezoqofu.shell
7. Your channels.yml : https://paste.helpch.at/huveraxiro.bash

**Comment by LlmDl** [comment]
Works fine for me once I took the placeholders out of the chatconfig's global channel_format.

**Comment by JustJP2K** [comment]
which placeholders? the essential nickname ones? or all of them.
Does that mean you cant use placeholders to format chat?

**Comment by LlmDl** [comment]
%rep_colour% and %essentials_nickname%

**Comment by JustJP2K** [comment]
Any way for it to support placeholders? Would be awesome

**Comment by LlmDl** [comment]
It supports placeholders just fine. It's probably because you're using floodgate, which I am not paid anywhere near enough to support.

**Comment by JustJP2K** [comment]
I'll double check and see if the problem persists without floodgate

**Comment by JustJP2K** [comment]
yeah floodgate was the issue. damn. so no support planned for floodgate at all?

**Comment by LlmDl** [comment]
If you can get all the people who wont buy a java account to start sponsoring me it might happen. I've already wasted a ton of time into people having geyser issues.

I'm considering making Towny shut itself down until the admin switches a config option acknowledging they will not receive support, but I know a no one will bother to read that either.
