### ISSUE TITLE
"[Towny] zip file closed"

### ISSUE THREAD

**Issue by darjeeliing** [TownyAdvanced/Towny#4712]
### What steps will reproduce the problem?
I'm not entirely sure as I don't know what caused it in the first place. However, the steps I took which seemed to cause it were the following:
1. Transferred my data from flatfile to mysql
2. Realized some chunks which were originally claimed no longer were after the transfer
3. Tried to claim those chunks and got a response in chat which simply said "[Towny] zip file closed"
4. Switched back to flatfile, which caused the missing chunks to be claimed once again
5. Realized the same issue was still happening, where it's impossible to claim chunks
6. Tried other towny commands and realized other commands give the same output (full list of broken commands: [https://pastebin.com/JfGd7S5a](https://pastebin.com/JfGd7S5a) )

### What is the expected output?
I'm not sure how to describe this in steps, but the commands are supposed to give their desired output (for example, claiming a chunk/townblock or depositing money in the town bank) rather than just saying "zip file closed"

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-443 (MC:1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : [latest.log](https://pastebin.com/WVWFwTYV)
2. Your Towny config.yml (if using MySQL please remove password,) : [config.yml](https://0bin.net/paste/GwGCpCXN#4rBdROouATmjlTzlKOJ7jAvtKNLJHgWNI6qI-cYyH/+) (I couldn't use pastebin because it kept telling me I had to make it private due to "potentially offensive or questionable content")
3. Your townyperms.yml : [townyperms.yml](https://pastebin.com/mKRHPZhx)
4. Your log's error : There were multiple errors in the log but I don't know which one is relevant, here are all warns and errors related to towny: [https://pastebin.com/5gxcnU7M](https://pastebin.com/5gxcnU7M)

(optional) If this is to do with permissions, 
I don't think this has anything to do with permissions but I'd be glad to provide my permissions file if asked

(optional) If this is to do with chat,
I don't think this has anything to do with chat but I'd be glad to provide these files if asked

**Comment by LlmDl** [comment]
the error says your towny\data\worlds\delete\ folder has a file called osfor?? in it which cannot be read properly. delete it manually and see if that fixes it.

**Comment by darjeeliing** [comment]
I've just tried deleting it and the issue is still present, here's my new latest server log: [latest log](https://pastebin.com/2JkU6bmh)

**Comment by darjeeliing** [comment]
I deleted the file in question and the issue is still present. Here is my latest server log: [latest log](https://pastebin.com/MpHU3dL5). This time, however, I found an error specifically within towny which is in this pastebin: [towny error](https://pastebin.com/T0XFgbv7)

**Comment by LlmDl** [comment]
That one looks to be on TNE's end of things. You should not be using 0.96.5.0 any more, update to 0.96.7.0.

**Comment by darjeeliing** [comment]
Updating towny and TNE seems to have fixed the issue, thanks.
