### ISSUE TITLE
World keeps generating things from previous world

### ISSUE THREAD

**Issue by stijnjw** [TownyAdvanced/Towny#4713]
### What steps will reproduce the problem?
1. create a town on a world
2. generate new world
3. delete town

### What is the expected output?
it does not generate a town in a sea

### What is your Towny version?
0.96.6.0

### What is your spigot/craftbukkit version?
1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/35Xbb1M4
2. Your Towny config.yml (if using MySQL please remove password,) :https://prnt.sc/xk6gd5
3. Your townyperms.yml :https://pastebin.com/D8DNXUER
4. Your log's error : /

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
The New World Settings section of the [config](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) is only default settings for new worlds, it's explained in the config section comments, the [install guide](https://github.com/TownyAdvanced/Towny/wiki/Installation#configuring-existing-worlds) and the [how towny works](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#reverting-unclaimed-townblocks-to-their-original-state-on-unclaim) page. You need to be using the /tw toggle commands or manually setting the worldname.txt file.
