### ISSUE TITLE
Error with database connect.

### ISSUE THREAD

**Issue by alex110220021** [TownyAdvanced/Towny#4714]
Error from the logs: 
https://pastebin.com/HMev4iP5

My Config: 
  database:
    database_load: mysql
    database_save: mysql
    gather_resident_uuids: 'true'
    sql:
      hostname: '127.0.0.1'
      port: '3606'
      dbname: aimatt
      table_prefix: towny_
      username: aimatt
      password: *************
      flags: ?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf-8
    pooling:
        max_pool_size: '5'
        max_lifetime: '180000'
        connection_timeout: '5000'

PaperSpigot 1.16.4

**Comment by LlmDl** [comment]
Connection was refused, not a Towny issue. Form skipped. Talk to your host.
