### ISSUE TITLE
Suggestion: [Event War] Disable invisible players from healing/attacking claim blocks during war.

### ISSUE THREAD

**Issue by GoldenEdit** [TownyAdvanced/Towny#4715]
A config value eg.

`war.event.invisible_players_attack_defend: true/false`

should be added, this will enable server admins to prevent invisible players from abusing their invisibility to essentially hide inside plots to heal them/damage them.

**Comment by EchoRapidz** [comment]
+1

**Comment by LlmDl** [comment]
This will be part of EventWar 0.0.9.
