### ISSUE TITLE
Suggestion: Combine plots and sell together

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#472]
Originally reported on Google Code with ID 436

```
Our users often build in multiple plots and then sell the property, which makes it so
that others have to buy it in chunks. It would be very useful to have the ability to
sell them all as one plot.
```

Reported by `botsko` on 2011-11-05 16:54:34

**Comment by suneettipirneni** [comment]
> /plot group new - (automatically sets id)
/plot group add (id) - adds current plot you're standing in to group with id
/plot group remove (id) - removes current plot you're standing in from group with id
/plot group name (id) (newname) - sets a name for display, wont be unique
/plot group setcost (cost) - sets cost for stood in group

> if you were to set a resident mode, store the current groupid the resident is working on, you dont need to have any id supplied in the commands
they make a new group, get the groupid assigned automatically, then get a resident mode set on them. they can walk around and do /plot group add, /plot group name {name}, /plot group setcost {cost}, /plot group forsale {cost} and towny can pull all of it from the resident mode
/plot group manage {id} could set the resident mode
/plot group info {id} could display a status screen for teh group

from discord

**Comment by suneettipirneni** [comment]
@LlmDl where are the resident modes defined, I found the interface but I can't seem to find the file where all the default modes are listed.

**Comment by LlmDl** [comment]
Modes aren't set to a specific list, they can be any one word. It's possible to toggle on modes that do nothing at all.

**Comment by suneettipirneni** [comment]
So I just call Resident.setModes(new String[] {"group"}); If I want to set the grouping mode?

**Comment by LlmDl** [comment]
You probably want to do Resident.getModes() first, if there is already a groupingmode you would remove it, then replace it with Resident.setModes(The rest of the String[] you got from .getModes()).

**Comment by suneettipirneni** [comment]
How should I store the groupid in the mode?

**Comment by LlmDl** [comment]
I'd say something like "group"+id# so the mode isn't just an id number which would probably confuse some people.

**Comment by suneettipirneni** [comment]
Sounds like a plan
