### ISSUE TITLE
Issue of using townychat in usingtowny off world

### ISSUE THREAD

**Issue by HalcyonAzure** [TownyAdvanced/Towny#4724]
### What steps will reproduce the problem?
1.Switch usingtown off in a world
2.A player who doesn't have the management permission of town but has the permission of nomad enters the server in that world
3.Chat system does not work properly, players can not be switched to the default chat channel, but players with administrator permissions can use townychat to switch chat channel to chat normally.

### What is the expected output?
1.In a world where usingworld is closed, players cannot use commands about town as it should. But players can still use townychat to chat in local, global or other ways.

### What is your Towny version?
Towny: 0.96.7.0
TownyChat: 0.86

### What is your spigot/craftbukkit version?
Paperspigot 1.16.5#439

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :https://pastebin.ubuntu.com/p/yQgjK4R2Kb/
   (Pastebin failed to paste, so I used Ubuntu Pastebin instead)
2. Your Towny config.yml  :https://pastebin.ubuntu.com/p/4kcJngTP2n/
3. Your townyperms.yml :https://pastebin.ubuntu.com/p/RfXxmp52gp/
4. Your log's error : https://pastebin.ubuntu.com/p/MMzxBrqGRh/

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :https://pastebin.ubuntu.com/p/k6Y46Jtdtk/
7. Your channels.yml :https://pastebin.ubuntu.com/p/Yvgnq69gwS/

**Comment by LlmDl** [comment]
TownyChat doesn't operate on non-towny worlds. Consider making the world usingTowny but not claimable.

**Comment by HalcyonAzure** [comment]
Now I set not claimable and the problem has been solved! Thank you very much. When I saw the error, I thought it was caused by an runtime error of the plug-in.
