### ISSUE TITLE
Towny replaces `[` on messages when it shouldn't

### ISSUE THREAD

**Issue by diogotcorreia** [TownyAdvanced/Towny#4725]
### What steps will reproduce the problem?
1. Set the `msg_confirmation_spigot_click_cancel` message to `[lang]towny.msg_confirmation_spigot_click_cancel[args][arg]%s[/arg][arg]%s[/arg][/args][/lang]`.
2. Trigger that message using in-game commands.
3. See that the output does not look like what was on the file.

![image](https://user-images.githubusercontent.com/7467891/106027709-127cf380-60c3-11eb-93c2-89a45e4466a1.png)

This is a big deal since [Triton](https://www.spigotmc.org/resources/triton-translate-your-server.30331/) (my plugin) needs to recognize that placeholder in order to correctly translate the message.

### What is the expected output?
1. It should output the message correctly, so Triton can detect it
The correct message should be `[lang]towny.msg_confirmation_spigot_click_cancel[args][arg]cancel[/arg][arg]/cancel[/arg][/args][/lang]`

### What is your Towny version?
0.96.7.0

### What is your spigot/craftbukkit version?
1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : not related
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/EFYsDcQi
3. Your townyperms.yml : not related
4. Your log's error : not related
5. Language file: https://pastebin.com/vSHNZE03

### Additional Information

Upon inspecting the source code, it seems to be related to lines 114 and 115 of TownySpigotMessaging.java.

https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/TownySpigotMessaging.java#L114-L115

**Comment by LlmDl** [comment]
Skipped the form, I need to see your config to see what you put for the confirm/cancel commands.

**Comment by diogotcorreia** [comment]
@LlmDl updated the post, the config is the default tho

**Comment by LlmDl** [comment]
Does this work: https://cdn.discordapp.com/attachments/669247087329673228/804075689681879040/Towny-0.96.7.1.jar ?

**Comment by LlmDl** [comment]
I ended up going back through this because when you look at what it's doing it doesn't make much sense. 

This was added via a PR: https://github.com/TownyAdvanced/Towny/pull/3631/commits and in [this particular commit](https://github.com/TownyAdvanced/Towny/pull/3631/commits/ef313ebad9a60593f6e35b4e810d483e6b699a77) it got changed to replacing the / with [ and then [ with "", which is a bit pointless (but probably got overlooked.)

**Comment by diogotcorreia** [comment]
@LlmDl Thank you, I've tested it and it works perfectly! :)
