### ISSUE TITLE
/t buy bonus [n] when the town is out of money (Not bankrupt yet) shows absolutely no response in chat or console

### ISSUE THREAD

**Issue by alkalinekats** [TownyAdvanced/Towny#4728]
### What steps will reproduce the problem?
1. Be on an account within the town that can purchase bonus claim blocks for the town you are in
2. a. Have the amount that the bonus claim blocks cost more that there is available in the bank or
2. b. Withdrawal money from the town bank so it is lower than the purchasing cost of a bonus claim block
3. Run /t buy bonus 1
4. See no response in chat

### What is the expected output?
1. Possibly a message that says that the town does not have enough money to purchase a claim block with how much more they would need
2. An error that explains what happened even if a message like above cannot be shown

### What is your Towny version?
Do not say "latest".
0.96.2.0

### What is your spigot/craftbukkit version?
Do not say "latest".
We do not run on a spigot or craftbukkit server, we run a paper server
CMI: 8.7.8.0 BungeeCord  MySQL -> 8.8.0.8
Paper(138) 1.16.1-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : I do not have pro for pastebin and it is 609kb I do have a custom domain and you can download it here http://alka.is-a-k.at/latestlog.zip
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/w41xJp7z
3. Your townyperms.yml : https://pastebin.com/83egq5Q9
4. Your log's error : There is no console error that shows up

(optional) If this is to do with permissions, 
5. Your permissions file : (I am trying my hardest to provide all the info but since I'm not too experienced, I do not know what file this is referencing)

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/vAgAGwLb
7. Your channels.yml : https://pastebin.com/5reB1bDJ

Please tell me to screw off if this is a feature request and not a bug, I'm still learning the system

**Comment by LlmDl** [comment]
No one should be using 0.96.2.0 unless they are on MC 1.12.

Updating to 0.96.7.0 is a drag-and-drop update. 

```java
		double cost = town.getBonusBlockCostN(n);
		// Test if the town can pay and throw economy exception if not.
		if (!town.getAccount().canPayFromHoldings(cost))
			throw new EconomyException(Translation.of("msg_no_funds_to_buy", n, Translation.of("bonus_townblocks"), TownyEconomyHandler.getFormattedBalance(cost)));
```

This is likely not an issue any longer based on the above.
