### ISSUE TITLE
Suggestion: For chats that have a given range (aka local chats) have a message to let players know when no one is within the specified range

### ISSUE THREAD

**Issue by JustAMatt** [TownyAdvanced/Towny#4733]
**Please explain your feature request to the best of your abilities:**

Lets say I have a chat that only works within 300 blocks. Player A and B are 250 blocks apart. Player B slowly walks away while keeping a conversation, Without realizing he is now 301 blocks away and his messages will not reach player A.

This suggestion would let players know when they have gone outsides of the specified range. Example "There is no close enough to hear you!"

Same thing could be added for Nation or Town chats when no one is online except for the sender.

**Comment by LlmDl** [comment]
There is an alone message already.
