### ISSUE TITLE
Suggestion: A command to restore all individual Plot perms to the general perms of the Town

### ISSUE THREAD

**Issue by JustAMatt** [TownyAdvanced/Towny#4734]
**Please explain your feature request to the best of your abilities:**

A command such as "/t perm reset" which when used will revert all plots that have different configurations to those shown in /t to be in line with /t.

Useful for towns that wish to make large modifications town-wide and have a fragmented plot perm system. Especially useful since Plot perms override Town perms.

**Comment by LlmDl** [comment]
That is what /t set perm reset, /res set perm reset does.
