### ISSUE TITLE
Suggestion: Pay Debt With Items

### ISSUE THREAD

**Issue by Kovalskki** [TownyAdvanced/Towny#4735]
Players can pay their debts with items. SiegeWar debts are really challenging. It would be much better if there was an option to pay debt with items.

Debt item values can be configure in config.yml

**Comment by Goosius1** [comment]
FYI Assuming this ticket is referring to plunder costs, SiegeWar has some options to reduce this without having to create or deploy an items-to-cash feature.
- Option 1. Reduce the plunder cost in the config
- Option 2. Enable the "extra_money_percentage_per_town_level" config. This will ensure smaller towns pay proportionally less plunder than larger towns.

**Comment by Kovalskki** [comment]
This ticket primarily assuming nation taxes. Conquered towns pay nation taxes and this amount can be paid with items.

**Comment by Kovalskki** [comment]
This is Historically accurate idea. I think, Towny is can be better with this idea. Plunder can be plunder items with this idea!

**Comment by Goosius1** [comment]
- Ah I see.
- Have you considered reducing further the server-configured maximum nation tax ?
- Also have you investigated yet to see if any economy plugins allow multiple items to be converted to cash ?
- But generally, even if the above two things workarounds fix the problem, I do like the idea. The described mechanism could also be used in voluntary arrangements of regular 'Tributes' of items, even from one nation to another.

**Comment by Kovalskki** [comment]
I am aware that I can lower the costs, but I do not want to do that. It doesn't give the real feeling of war.

**Comment by LlmDl** [comment]
This is something which can easily be done using any shop plugin. Just make shops for your players to sell their valuable items at, then they can deposit the money in their town banks to pay the nation's tax.

**Comment by Kovalskki** [comment]
My suggestion has nothing to do with paying money. It's about paying debts with items. Please reevaluate, this is a necessary thing.

**Comment by LlmDl** [comment]
> This ticket primarily assuming nation taxes. Conquered towns pay nation taxes and this amount can be paid with items.

Tax paid to the nation is money in the town bank transferred to the nation bank. This is paying money. That money can be gotten by selling items to a shop.

To change the tax system over to handle items and money, when there are already many shop plugins which will turn items into money, would be a waste of time and make the configuration of the tax system even more complex.

**Comment by Kovalskki** [comment]
You don't need to change the tax system for what I'm talking about, it's an extra feature. It's about pay our debt from by giving items. For example, we are plunder a certain amount of gold from the conquered town. If conquered town cant pay and bankrcupty system enabled town is in debt. My suggestion is an option about pay debt with items. Conquered town can pay their debt with own items. It is so realistic right?

**Comment by LlmDl** [comment]
Yes and if you want to do that right now all you need is a shop plugin which will give the player money for those items.

**Comment by Kovalskki** [comment]
No, I definitely don't want it done right away.  I want this to be part of towny.

**Comment by Goosius1** [comment]
- Generally speaking, I like the idea of a "Tribute" feature for regular transfer of items, but I concur something like this should be done with different plugin (not Towny).
- What you might need is two "linked" chests..........these chests could be linked by some sort of in-game "treaty" between two players.
- After this the tribute payer must put certain specific items into the chest, and when the tribute time arrives, the items get transferred if they are sufficient, but if not, a global alert goes out to say that the treaty is broken.
- I suggest to suggest this to the devs of an existing economy-type plugin or build a new plugin for it.

**Comment by Kovalskki** [comment]
My suggestion is about debt. Not like items based tax. It is working like "foreclosure". Can be give to foreclosure values to items with using config.yml and this items can using to pay debt.
