### ISSUE TITLE
Suggestion: Create town/nation's warp

### ISSUE THREAD

**Issue by TheophaneGorge** [TownyAdvanced/Towny#4737]
Possibility to the mayor to create town/nation's warps. Warp is like "home" for the town/nation.

**Comment by LlmDl** [comment]
How is this not already covered with the town and nation spawns?

**Comment by TheophaneGorge** [comment]
No because the town/nation warp is an other place where the mayor set a town warp (/t set warp <Name of the warp>) in the outpost by exemple where the citizen can teleport using /t warps <Name of the warp>

**Comment by LlmDl** [comment]
Then can you tell me why a mayor wouldn't just use outposts for this?

**Comment by TheophaneGorge** [comment]
Because the citizen can tp to this outpost using /t warp <Name> and actually it's impossible to teleport to an outpost

**Comment by LlmDl** [comment]
It is very possible to teleport to an outpost, using /t outpost {name or number}
