### ISSUE TITLE
Townblocks can't be taken down when players from multiple towns attacks

### ISSUE THREAD

**Issue by ipozow** [TownyAdvanced/Towny#4740]
### What steps will reproduce the problem?
1. Start a war with /ta toggle war, with at least 2 nations with enemies
2. With a group of ally players from the same nation but different towns, (ex: 2 from BillyBobTown and 1 from other town, but the same nation) go to an enemy town block that can be attacked. 
3. Wait until the town block has 2 HP. If the 3 players are there, it will be not taken down. 
The town block will take damage from multiple players, but only until the HP number is bigger than the player amount (only if the player amount is composed of players from different towns, although I am not 100% sure of that. Maybe it affects also with players of the same town)

I think that this bug was introduced when there was a feature added where instead of one town randomly taking all the points when conquering a town block, should distribute the points between the players that conquered it. 

### What is the expected output?
1. The town block should be able to being taken down from the 2 HP if there are 3 players or more. 

The thing is that if the townblock has 1 HP and there are 2 or more people of different towns, it will be not taken down either. 

### What is your Towny version?
Do not say "latest".
0.96.7.0

### What is your spigot/craftbukkit version?
Do not say "latest".
paper 436

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/hu3UawrJ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/66XULRpS
3. Your townyperms.yml: https://pastebin.com/NFcgQGxx
4. Your log's error : https://pastebin.com/ep1QXuxx

**Comment by LlmDl** [comment]
Try this out for me: https://cdn.discordapp.com/attachments/669247087329673228/807994455528833034/Towny-0.96.7.0.jar

**Comment by ipozow** [comment]
seems like it's working now

**Comment by FizzleTits** [comment]
also having difficulty with war... seems that players are in plots deemed "Attackable: True" on /towny war hud
but they are not able to attack the plot

**Comment by ipozow** [comment]
Yesterday we had a war and the problem reappeared. When I tested this we tried with 3 players, but in the real war there were like 15 players in a chunk, and some townblock were taken down correctly where some others weren't possible to take down even with 1 player (the townblock had 1 HP)
I will try to test this in the future but I will need some time for that
