### ISSUE TITLE
NPE: Could not pass event PlayerChangePlotEvent to Towny v0.96.7.0 when /plot perm hud is on (maybe issue with featherboard too?)

### ISSUE THREAD

**Issue by TamrielNetwork** [TownyAdvanced/Towny#4754]
### What steps will reproduce the problem?
1. use featherboard (maybe toggle on/off)
2. use /plot perm hud
3. move around?

### What is the expected output?
1. a scoreboard showing the perms
2. no errors

### What is your Towny version?
Do not say "latest".
0.96.7.0

### What is your spigot/craftbukkit version?
Do not say "latest".
paper-467 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/TuBqN4Fh
2. Your Towny config.yml (gist because pastebin blocks it) : https://gist.github.com/TamrielNetwork/a16f73ee534e7fd252799c33daf71d75
3. Your townyperms.yml : https://gist.github.com/TamrielNetwork/4ce9bb2902a6005a5406360671e19a80
4. Your log's error : https://pastebin.com/hcbS3jR3

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I have never seen it fail to get a plots' firespread status before. Very odd.

You link to the startup doesn't have the startup. Might be useful.

**Comment by TamrielNetwork** [comment]
Well it was my full latest.logs. I can also share the startup but really dont want to share my whole pluginlist tbh. At least not public. My serverstartup is normal, only with some legacy warnings but no errors or any failed connections to mysql from towny.

**Comment by TamrielNetwork** [comment]
Also when I asked the guy to do /fp toggle and /plot perm hud again all errors stopped. So it for sure has to do with the permchecks and Im pretty sure also with featherboard since the command he did before the errors was /fb toggle

**Comment by LlmDl** [comment]
Ah, so it'll be a case of the permhud being replaced mid-update and not finding the correct teams any longer.

**Comment by TamrielNetwork** [comment]
okay. I disabled /plot perm hud for now. Is there any way you can fix that tho?

**Comment by LlmDl** [comment]
yeah its just a matter of making sure the player we're updating actually has the plot perm hud still in view.

**Comment by LlmDl** [comment]
Would be useful if i had a copy of fb to test with,

**Comment by TamrielNetwork** [comment]
I could give you one somehow probably. Lmk if you want me to do that because it's technically not allowed. I'll find a way tho xD

**Comment by LlmDl** [comment]
@LlmDl  on the discord.

**Comment by LlmDl** [comment]
Actually I don't think it will be necessary. Still message me on the discord so I can give you a test build to try out.
