### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by k4deng** [TownyAdvanced/Towny#4756]
**Please explain your feature request to the best of your abilities:**

I use a dynmap called Bluemap and I would like support for towny claims on it. I asked on how this could be achieved and this was an answer.

--"Blue provides an api and then devs of the mods that want support in blue map create a compat plugin to add in support iirc"

Not many people use Bluemap but I do and would love towny support!

**Comment by LlmDl** [comment]
Someone did this already though: https://github.com/TownyAdvanced/Towny/wiki/Plugins-using-the-Towny-API
