### ISSUE TITLE
Region regeneration blockdata bug

### ISSUE THREAD

**Issue by FrankHeijden** [TownyAdvanced/Towny#4771]
### What steps will reproduce the problem?
1. Place two beds next to each other in the nether
2. Right click one bed such that it explodes

#### Before Explosion
![PreExplode](https://user-images.githubusercontent.com/22407829/108563131-4681b800-7301-11eb-8023-1a3b70a4c24b.png)

#### After Region Restoration
![PostRestore](https://user-images.githubusercontent.com/22407829/108563190-58fbf180-7301-11eb-9402-01e690053a36.png)

### What is your Towny version?
v0.96.7.0

### What is your spigot/craftbukkit version?
git-Paper-"732b2f6b5"

**Comment by LlmDl** [comment]
I do see this, looks like 1/2 the bed manages to blow up and drop as a bed-drop.

**Comment by LlmDl** [comment]
Two bugs one stone. Thanks.

**Comment by FrankHeijden** [comment]
Amazing! Thanks ^^
