### ISSUE TITLE
Suggestion: Create camp mechanic as temporary protection for new players or players without a town.

### ISSUE THREAD

**Issue by SmallSansSerif** [TownyAdvanced/Towny#4773]
Towny Camps

SUMMARY:

The learning curve for Towny land claim is high for a new player so trying to explain through chat, wikis or tutorials all before they bail is often a challenge. A simple starting out mechanic would help bridge the gap while they get to know the server and commands maybe.

Create a temporary day, time-limited 1-chunk camp protection that's town/nation aware so users could have a temporary base while mobile and asking for a town to join or before they start a new town.

Using a command or ideally placing a camp fire and it claims the chunk. It could have the default town flags, or predefined flags from config like no pvp, mobs, etc. via config. Doesn't really need in-game controls for this simple claim.

BASICS:

Create a sub-town level camp claim mechanic. 

You can't make camps if you own a town. They are pre-town temp claims.

Players could use a command or ideally place an item such as a camp fire to create a simple 1 chunk claim that abides by the nation and town boundries and borders.

Use auto unclaim time-based mechanic via config so that it would be temporary and not have to be cleaned up by admins or detract from players moving into towns.

**Comment by LlmDl** [comment]
This has been done, as a separate plugin TownyCamps, which is available to my Sponsors in the discord.
