### ISSUE TITLE
Towny's protection doesnt protect certain blocks

### ISSUE THREAD

**Issue by TamrielNetwork** [TownyAdvanced/Towny#4774]
It seems that the block listener priorities are set to HIGH instead of something like LOW, which can cause issues for some plugins that listen on HIGH that expect claims plugin events to have already run by then. Usually plugin listeners that protect blocks are set to LOW to make sure they get run and, if needed, canceled before the majority of other plugins run. This has caused an issue with a plugin called [RoseStacker](https://www.spigotmc.org/resources/rosestacker.82729/) and its custom spawner handling which listens on HIGH. The reason for RoseStacker not listening on HIGHEST is to allow other plugins to run after itself.

### Possible Solution
Setting the block listeners in [TownyBlockListener.java](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java) to a lower priority such as LOW will fix this issue. This is remarkably similar to #3329 which was implemented last year. 

### What steps will reproduce the problem?
1. Install a plugin that manages claimed blocks that does not have a direct hook to check towny claims. In my case [RoseStacker](https://www.spigotmc.org/resources/rosestacker.82729/).
2. Have one player create a claim and place a stacked spawner within that claim
3. Have a second player attempt to break that stacked spawner, which results in the spawner breaking instead of being protected due to the event priority conflict

### What is the expected output?
1. The spawner is protected while inside the claim

### What is your Towny version?
0.96.7.0

### What is your spigot/craftbukkit version?
paper-470 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/vXwruFJs
2. Your Towny config.yml (if using MySQL please remove password,) : https://gist.github.com/TamrielNetwork/a16f73ee534e7fd252799c33daf71d75
3. Your townyperms.yml : https://gist.github.com/TamrielNetwork/4ce9bb2902a6005a5406360671e19a80

**Comment by TamrielNetwork** [comment]
The developer is @Esophose

**Comment by LlmDl** [comment]
This runs into the same issue, we have to set ourselves on high because of other plugins such as WorldGuard.

**Comment by LlmDl** [comment]
The RoseStacker plugin can just listen to the event on Monitor to find out if something has changed the outcome of the break in between the High and Monitor priorities.

**Comment by Esophose** [comment]
I didn't realize that WorldGuard was listening on NORMAL which just seems a bit ridiculous, sounds reasonable to me that you're listening on HIGH then. I'll just change my priorities for my block events to HIGHEST because that seems to work as a good enough fix. Thanks for responding so quickly~

**Comment by LlmDl** [comment]
No worries. Good luck with RoseStacker.
