### ISSUE TITLE
Suggestion: Make Town and Nation bank transaction history persist through restarts

### ISSUE THREAD

**Issue by wm-b** [TownyAdvanced/Towny#4775]
Currently, whenever a server restarts town and nation bank transaction history is cleared. Since I restart my server automatically every day, this information doesn't stick around for very long. It would be helpful to have an option to make this data be stored for longer so that mayors and kings have access to see if a player might be stealing from the nation/town.

**Comment by LlmDl** [comment]
At the moment this information is stored in memory as the transactions occur. Everything is also stored in the money.csv in the towny\logs\ folder.
