### ISSUE TITLE
"Anti-pvp trident lightningstrike cancel" implemented wrongly

### ISSUE THREAD

**Issue by kilian544** [TownyAdvanced/Towny#4778]
### What steps will reproduce the problem?
Throw a trident with channeling at some mob, or any entity for that matter, in a plot, or if applicable to wilderness, where pvp is disabled.

### What is the expected output?
When thrown at a player lightning/damage is canceled, when thrown at a mob it is not.

### Current output.
When the trident is thrown at any entity the lightning gets canceled.

### What is your Towny version?
0.96.7.1

### What is your spigot/craftbukkit version?
git-Paper-465 (MC: 1.16.5) (Implenting API version 1.16.5-R0.1-SNAPSHOT)

### Extra info.
The current implementation impose limitations that disallow a sane and safe solution for the problem at hand. Though I think it takes away a core vanilla feature which we should strive not to change.

If my assumptions are right we are trying to prevent players taking damage through nefarious use of a trident with the channeling enchantment. We could check if the entity hit by the trident is a player, but this solution will fail if the trident is thrown at an entity close to the player and the player getting hit by the explosion.

The other solution would be to disable EntityDamageEvent.DamageCause.LIGHTNING to the player in any pvp-disabled location. One drawback here is that also "natural" impacts of lightning to the player are disabled.*

*One possible workaround would be keeping track of lightningstrikes and compare any damage to the player to one of such strikes. Though I am hesistant to advise implementation of such system...

If you wish I could share with you code on the second solution!

Source of current implementation: 
#4648 
#4647 
#4631

**Comment by kilian544** [comment]
@LlmDl Just wondering, any feedback/opinion on this?

**Comment by LlmDl** [comment]
Right, I read this when you posted it but not in detail.

The reason mobs are hurt by the trident is that mobs don't fall under PVP rules. Mobs are always damageable in Town land despite what the plot's PVP setting is. I don't see why the lightning damage should be cancelled on the monster just because PVP is disabled there.

**Comment by kilian544** [comment]
The problem is exactly that, lightning is, flat out, disabled when pvp is disabled. Exactly what I was thinking, "why should the lightning (damage) be canceled for them." For players I get it, there is no good way to prevent the explosion damage from the lightning impact.

I think you might have misread what I meant, if you need any further clarification please don't hesitate to tell me!

**Comment by LlmDl** [comment]
Yeah try and lay it out as clearly as you can. We block the damage when its a player being hit because it is PVP damage at that point.

**Comment by kilian544** [comment]
https://github.com/TownyAdvanced/Towny/blob/ac2b8ee4308ba5b3f0a7f0d48c02fda8d67a49a7/src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java#L96-L115

You don't, you block the **[LightningStrikeEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/weather/LightningStrikeEvent.html)** when it is caused by a Trident. This event is triggered regardless of the EntityType. So, when a trident spawns lightning in a chunk, or anywhere towny has, disabled pvp. It simply gets canceled.

**Comment by LlmDl** [comment]
Thanks for spotting this.
