### ISSUE TITLE
Free Claiming

### ISSUE THREAD

**Issue by ColoTramites** [TownyAdvanced/Towny#4781]
### What steps will reproduce the problem?
1. /t new test
2. /t claim

### What is the expected output?
It should take away 5,000 from the town bank, and if the money is in the bank, it is taken, but if there is no money, people can claim a plot for free.

### What is your Towny version?
0.96.5.0

### What is your spigot/craftbukkit version?
Paper 1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/1WJYtxX2
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/U5CWRt1D
3. Your townyperms.yml : https://pastebin.com/W58XiX8F
4. Your log's error : I get no error in the logs

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Issue resolved by updating Towny to 0.96.7.0 (probably coincidence.)
