### ISSUE TITLE
Magma Foundation perms problem

### ISSUE THREAD

**Issue by HonzaVinCZ** [TownyAdvanced/Towny#4788]
Hello, I'm running Towny on my Magma server and it works all well except one thing. I noticed some problems with permissions. I got permission towny.wild.* set but after I created a town, claimed some town chunks, set two of them for sale and claimed them for myself, other residents are always allowed to destroy/switch and everything on my plot. Even after trying set perm off for each /town, /plot and /resident, nothing changed and residents can destroy, switch and everything. Only group that can't destroy/switch and all in my town is nomad. 
Towny was added after some time to my world, it's not there from world creation. 

I checked all docs, forums and everything but without any luck to figure out my problem.

### What is your Towny version?
Towny-0.96.2.0-for-1.12.2.jar

### What is your spigot/craftbukkit version?
Magma Dev HEAD-1bc8635

### Please use Pastebin.com to link the following files:
**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log :
[latest.log](https://github.com/TownyAdvanced/Towny/files/6078381/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/xVBDhRcX

3. Your townyperms.yml :
https://pastebin.com/xUhL9pai

**Comment by LlmDl** [comment]
Did you put any towny nodes in your permission plugin?

**Comment by HonzaVinCZ** [comment]
I'm so sorry, I'm just silly I didn't try that earlier. The problem was that my mate had OP I didn't know about and she didn't know that too lol. I checked OPs list and there it was. Sorry for your wasted time. After deop-ing my mate everything works fine as it is supposed to.
