### ISSUE TITLE
Can No Longer Teleport to Outposts By Name

### ISSUE THREAD

**Issue by HuskerFan34** [TownyAdvanced/Towny#4789]
### What steps will reproduce the problem?
1. Name an outpost plot
2. Try to teleport to the outpost plot using /t outpost (plot name)
3. Get teleported to town outpost 1 instead (plot name not recognized so towny thinks you're just running /t outpost)

### What is the expected output?
1. Get teleported to the outpost with the plot name you specified
2.
3.

### What is your Towny version?
0.96.7.0

### What is your spigot/craftbukkit version?
paper-1.16.4-416

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/eLXbCLmt
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/VpJxTpMy
3. Your townyperms.yml : https://pastebin.com/QwtPnDRZ

Please correct me if I'm wrong, but in the past I seem to recall being able to name an outpost plot, then teleporting to that outpost using /t outpost (plot name). Now it seems the only way to teleport to an outpost is by using its outpost number. Below you can see I have named my third outpost plot "EndPortal". However, when I run the command "/t outpost EndPortal" I just get teleported to outpost 1. I have to do /t outpost 3 to teleport to the end portal outpost.
![image](https://user-images.githubusercontent.com/59267792/109881565-207fe000-7c3e-11eb-8457-407cfc993376.png)

If a town has a bunch of outposts, it's convenient to be able to use outpost names instead of having to remember what number each outpost is. Thanks!

**Comment by LlmDl** [comment]
Does clicking on the outpost in the outpostlist work?

**Comment by HuskerFan34** [comment]
Yes, clicking on the outposts in /t outpost list teleports you to the correct outpost.

**Comment by LlmDl** [comment]
Just tested this and using /t outpost NAME worked fine on two outposts. Got anything else you think might be breaking it for you?

**Comment by HuskerFan34** [comment]
I can't think of anything else that might be interfering. The way to name outposts is by using /plot set name on the outpost plot, correct? 
![image](https://user-images.githubusercontent.com/59267792/109913404-86d32580-7c73-11eb-8bd1-be9d7dea4a7e.png)

I do this on the outpost plot yet /t outpost EndPortal doesn't teleport me to the correct outpost. If I'm alone in having this issue then it may just have something to do with my plugin setup. If you feel free to close the thread bc it's specific to me

**Comment by LlmDl** [comment]
You are correct about naming plots.

Does `/towny:town outpost EndPortal` work?

**Comment by HuskerFan34** [comment]
Using /towny:town yields the same results. No matter what named outpost I try to teleport to, I'm teleported to outpost #1.

![image](https://user-images.githubusercontent.com/59267792/110228905-897b8800-7eca-11eb-9d66-d5b38e2191c6.png)

**Comment by LlmDl** [comment]
Do other towns on the same server have the issue?
