### ISSUE TITLE
Friendly Fire Won't Enable

### ISSUE THREAD

**Issue by Vulpine24** [TownyAdvanced/Towny#4790]
Even with Friendly Fire enabled (I use the in game command to toggle it) players in the same town cannot pvp against each other if they choose to. There's no error messages in the log, and I've tried disabling it as well. Nothing has worked so far, any ideas on what could be causing this bug?

**Comment by LlmDl** [comment]
Is pvp on in the plot they're fighting over?

**Comment by Vulpine24** [comment]
yes, we actually figured out the issue but just in case anyone else runs into this, I figured I'd mention that it had something to do with Towny being hooked into DeluxeCombat. We added Towny to the ignore list for the DeluxeCombat hooks and the friendly fire function returned to normal.

**Comment by LlmDl** [comment]
Interesting.
