### ISSUE TITLE
Entities unable to be placed in explosions_ignore_list.

### ISSUE THREAD

**Issue by MdoubleM** [TownyAdvanced/Towny#4791]
Towny version: 0.96.7.4
Server Paper: 520 version 1.16.5

Hi, I have some errors during a Towny war.
~1. It doesn't toggle PvP on in the citys automatically.~
2. This items: item_frames, paintings and armor_stands are added to the explosions_ignore_list and when there is an explosion it breaks the blocks where they are on and then they break. But it doesn't happen for example with repeaters, comparators, minecarts, banners, rails.

latest.log: https://pastebin.com/SdVwgDUB
townyperms.yml: https://pastebin.com/d64TxV5Z
config.yml: https://pastebin.com/Yifj5tMP
explosions_ignore_list: https://pastebin.com/aap7xEmw

**Comment by LlmDl** [comment]
Are the cities part of a nation? Is the nation in the war?

There may not be much I can do about hanging entities and armourstands having their base blocks exploded.

**Comment by MdoubleM** [comment]
Yes, the cities are part of a nation and that nation was in the war.

Sorry but I don't understand that last part. Repeaters and comparators, for example, they normally break if you break the block below them, but if I add this items to the explosions_ignore_list, the block below them doesn't break with an explosion so they can't be broken. Why can't this be done with item_frames, paintings and armor_stands?

**Comment by LlmDl** [comment]
Those three are entities and not blocks. I might be able to solve for that. The PVP thing I probably need actual instructions to reproduce it.

**Comment by MdoubleM** [comment]
Okay, so I need to show you something for the PvP thing or I just wait?

**Comment by LlmDl** [comment]
I want to see the exact steps I should follow in order to make a town not have PVP on when it is in play during a war.

**Comment by MdoubleM** [comment]
I'll wait then

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/c086d768ef13f008000b4691512f422c5c3fe6dc fixed the pvp not being turned on in warzones.
