### ISSUE TITLE
Suggestion: coup d'etat feature for towns and nations.

### ISSUE THREAD

**Issue by MistyMountainMC** [TownyAdvanced/Towny#4797]
**Please explain your feature request to the best of your abilities:**
Add a “/t coup” or “/n coup” so if over a majority of  residents or towns are unhappy with the current mayor/king and he/she is unwilling to give up the position either a resident of a mayor can type “/t coup” or “/n coup” and it will send out a sort of vote/poll to everyone in the town/nation and if you say yes to a coup you could say who you want to be the new mayor/king or the most senior resident/assistant could automatically take the job, it could be a feature of seigewar that some servers only activate after a week or so or just normal towny I suggest normal towny

**Comment by LlmDl** [comment]
I am unlikely to add this, a mayor and a king are the people who paid for and manage the town/nation and having a mechanic that allows players to take it away from them is not really fair at all.

Something like this could be made as an add-on plugin.

**Comment by DevonDucks** [comment]
> I am unlikely to add this, a mayor and a king are the people who paid for and manage the town/nation and having a mechanic that allows players to take it away from them is not really fair at all.
> 
> Something like this could be made as an add-on plugin.

Ok thank you btw it’s a amazing plugin!

**Comment by LlmDl** [comment]
This is something that can be done via EventWar's Riot and CivilWar wartypes.
