### ISSUE TITLE
Hi there.

### ISSUE THREAD

**Issue by Misquoth** [TownyAdvanced/Towny#4801]
Hi there. 

I'm trying to be able to have a Lectern with a book that can't be removed.

However, even if I open all perms for outsiders, no one can even read the book. 

using luckperms and world guard, but have not configured any area with worldguard.

How can I debug / troubleshoot to figure out why other players cannot even read the book?

I have not added them to the switch list.

I had another post, however I could not comment on it.

If this is a bug I would like to report it. Please let me know what info is necessary.

_Originally posted by @Misquoth in https://github.com/TownyAdvanced/Towny/discussions/4800_

**Comment by LlmDl** [comment]
We have a bug report template: https://github.com/TownyAdvanced/Towny/issues/new?assignees=&labels=bug&template=bug_report.md&title=
