### ISSUE TITLE
Problems with permissions regarding lectern

### ISSUE THREAD

**Issue by Misquoth** [TownyAdvanced/Towny#4803]
### What steps will reproduce the problem?
1. Me as OP, placing book on lectern in town, perms open, no one else can read book
2. Other players non-OP can place book/lectern and be read by others
3.

### What is the expected output?
1. Place book, on lectern so others can read. Goal is to be able to read but not take, but right now just looking to get reading working.
2.
3.

### What is your Towny version?
0.96.7.0

### What is your spigot/craftbukkit version?
PaperMC : This server is running Paper version git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/XBCN4gq9
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/TmAwpPg8
3. Your townyperms.yml : https://pastebin.com/PFNYYK3N
4. Your log's error : No errors

(optional) If this is to do with permissions, 
5. Your permissions file :

**Comment by LlmDl** [comment]
Does it say anything when they try to open the book?

**Comment by Misquoth** [comment]
No, there is no message.

**Comment by LlmDl** [comment]
It's probably not Towny then. You don't have Lecterns in the Switch list so Towny wouldn't stop them from reading the book.

**Comment by Misquoth** [comment]
I've done some more testing. This seems to work at all other parts of my town and outposts. The only difference is that this is near the world spawn. I'm not using worldguard or anything else that I think would interfere with this. What would you suggest to troubleshoot this futher?

**Comment by LlmDl** [comment]
Maybe the default vanilla spawn radius?

**Comment by Misquoth** [comment]
That was it. I didn't know about the built in spawn radius protection.

All set.

Thanks.
