### ISSUE TITLE
Suggestion: Add a town staff permission and allow the use of friend for town permissions

### ISSUE THREAD

**Issue by not-senate** [TownyAdvanced/Towny#4805]
In order to customize permissions allow town leaders to set perms for staff and friends in the town. This would help for area like a town square where you want your town staff to be able to build and use things but you don't want just anyone in your town to be able to break things.

**Comment by LlmDl** [comment]
To accomplish this you can make a builder rank in the town section of the townyperms.yml and give them `towny.claimed.townowned.*`.

Only personally-owned plots have a friends category.
