### ISSUE TITLE
Regeneration in wilderness dupes blocks

### ISSUE THREAD

**Issue by icemails** [TownyAdvanced/Towny#4812]
### What steps will reproduce the problem?
1. go in wilderness
2. place tnt near shulkerbox and/or beacons
3. fire the tnt
4. the explosion drops the shulkerbox/beacons and finally regenerate them too

### What is the expected output?
1.that items which where droped not regenerate or that no items drops after an explosion

### What is your Towny version?
0.96.7.5

### What is your spigot/craftbukkit version?
1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/7NebvKHN
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/W26FV33j
3. Your townyperms.yml : https://pastebin.com/egb2Y6Jb
4. Your log's error :  https://pastebin.com/gsTsxXxv

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I need to see your towny\data\worlds\WORLDNAME.txt

**Comment by icemails** [comment]
Here is the pastebin of it:

https://pastebin.com/ukxwqugR

**Comment by LlmDl** [comment]
Your plotManagementIgnoreIds=GOLD_ORE,LAPIS_ORE,LAPIS_BLOCK,GOLD_BLOCK,IRON_BLOCK,MOSSY_COBBLESTONE,TORCH,MOB_SPAWNER,DIAMOND_ORE,DIAMOND_BLOCK,SIGN_POST,WALL_SIGN,GLOWSTONE is missing a ton of blocks. You should replace it with this list:
`GOLD_ORE,LAPIS_ORE,LAPIS_BLOCK,GOLD_BLOCK,IRON_ORE,IRON_BLOCK,MOSSY_COBBLESTONE,TORCH,SPAWNER,DIAMOND_ORE,DIAMOND_BLOCK,ACACIA_SIGN,BIRCH_SIGN,DARK_OAK_SIGN,JUNGLE_SIGN,OAK_SIGN,SPRUCE_SIGN,ACACIA_WALL_SIGN,BIRCH_WALL_SIGN,DARK_OAK_WALL_SIGN,JUNGLE_WALL_SIGN,OAK_WALL_SIGN,SPRUCE_WALL_SIGN,GLOWSTONE,EMERALD_ORE,EMERALD_BLOCK,NETHER_GOLD_ORE,ANCIENT_DEBRIS,SOUL_TORCH,SOUL_WALL_TORCH,CRIMSON_SIGN,CRIMSON_WALL_SIGN,WARPED_SIGN,WARPED_WALL_SIGN,LODESTONE,RESPAWN_ANCHOR,NETHER_PORTALFURNACE,BLAST_FURNACE,SMOKER,BREWING_STAND,TNT,AIR,FIRE,NETHER_QUARTZ_ORE,SHULKER_BOX,WHITE_SHULKER_BOX,ORANGE_SHULKER_BOX,MAGENTA_SHULKER_BOX,LIGHT_BLUE_SHULKER_BOX,YELLOW_SHULKER_BOX,LIME_SHULKER_BOX,PINK_SHULKER_BOX,GRAY_SHULKER_BOX,LIGHT_GRAY_SHULKER_BOX,CYAN_SHULKER_BOX,PURPLE_SHULKER_BOX,BLUE_SHULKER_BOX,BROWN_SHULKER_BOX,GREEN_SHULKER_BOX,RED_SHULKER_BOX,BLACK_SHULKER_BOX`

**Comment by icemails** [comment]
Thanks, but will that also work with blocks which are affected by explosions?

I can test it toworrow and will add Beacons and other Blocks to it too.

**Comment by LlmDl** [comment]
That list is also used to prevent certain blocks from exploding and causing a regeneration.

**Comment by icemails** [comment]
With the part of the config from you and added BEACON to it it still drops the Beacon.

https://prnt.sc/10v5vh0

So any Plugin which can interact with towny to do this?

**Comment by LlmDl** [comment]
I'm not sure I understand you, you want beacon blocks to be dupable?

**Comment by icemails** [comment]
No, they drop and regenerate so from 1 beacon you get 1 dropped and 1 regenerated.

**Comment by LlmDl** [comment]
Show me your towny\data\worlds\WORLDNAME.txt file.

**Comment by icemails** [comment]
Here it is:

https://pastebin.com/vjgrb3bt

**Comment by LlmDl** [comment]
Well you're set up properly I couldn't say why it isn't using that list. Have you done a full stop and start since changing the world file?

**Comment by icemails** [comment]
Yeah, the server restarts every night.

https://prnt.sc/10x70t5

That are the plugins we have installed.
Eventually you sea something which is not good with interacting with towny?

**Comment by LlmDl** [comment]
Nothing sticks out to me, try it on a test server with just the minimum needed for Towny. Then add plugins back until it breaks.
