### ISSUE TITLE
Nether Portals crash the server 

### ISSUE THREAD

**Issue by GeneralDarian** [TownyAdvanced/Towny#4813]
I think this is a bug relating to towny preventing nether portals from being made in claimed towns.

### What steps will reproduce the problem?
1. As a default player, make a nether portal that will lead to a town that isn't yours.
2. Enter it.
3. The server crashes.
4. Entering the portal as an administrator will create the portal in the town. 

### What is the expected output?
1. Well, I'm not sure what the expected output should be. Should the portal refuse to light or spawn nearby instead?

### What is your Towny version?
Do not say "latest".
0.96.7.4

### What is your spigot/craftbukkit version?
Do not say "latest".
We use Paper (1.16.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/R50LE54A
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/qcrsKEBS
3. Your townyperms.yml : https://pastebin.com/3PxXjdYd
4. Your log's error : https://pastebin.com/ZVNsXk8Z

**Comment by LlmDl** [comment]
I do not get a crash on my test server what I see is: 
![2021-03-18_08 36 58](https://user-images.githubusercontent.com/879756/111635113-2b517d80-87c5-11eb-95e1-6496af20b584.png)


Your crash report doesn't specify anything Towny related in it. There might be a plugin that isn't expecting the portal creation to be cancelled?
