### ISSUE TITLE
Town Names Not Changing but wiping Town Banks.

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/Towny#4818]
### What steps will reproduce the problem?
1. Create a new town and deposit money into the bank.
2. Take note of balance in bank, and change the towns name
3. Receive a chat error, "Not Registered" and no money in the towny bank.

### What is the expected output?
1. The name of the town changes and the bank stays intact.

### What is your Towny version?
Towny 0.96.7.8

### What is your spigot/craftbukkit version?
git-Purpur-1001 (1.16.5)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : No error persistent in logs
2. Your Towny config.yml: https://pastebin.com/0u1arkmk
3. Your townyperms.yml: https://pastebin.com/ZqH85cfV
4. Your log's error: No error persistent in logs

### Additional Information: 
Currently using TheNewEconomy (TNE) versus 0.1.1.12

**Comment by 0xBit-MC** [comment]
Image 1: https://i.imgur.com/BLcupff.png
   Issuing command `/t` to take note of Bank account.
   
Image 2: https://i.imgur.com/wRixGRz.png
   Issuing command `/t set name Testing` to change the name of the town.
   
Image 3: https://i.imgur.com/smhxFzH.png
   Error occurs, `[Towny]: Not registered` after executing the previous command.
   
Image 4: https://i.imgur.com/IH35Osx.png
   Issuing command `/t` to notice the bank account empty

**Comment by LlmDl** [comment]
This Not registered thing is something I've got a fix for in 0.96.7.9, I think the money not being transferred over is just a side effect of the renaming not finishing.

**Comment by LlmDl** [comment]
Please give https://github.com/TownyAdvanced/Towny/releases/tag/0.96.7.9 a shot and let me know if its fixed.

**Comment by 0xBit-MC** [comment]
Issue was resolved with 0.96.7.9, sorry for the late reply.
