### ISSUE TITLE
Suggestion: Change plot border to be a worldborder particle

### ISSUE THREAD

**Issue by RSNFreud** [TownyAdvanced/Towny#4820]
**Please explain your feature request to the best of your abilities:**
Using  https://github.com/yannicklamprecht/WorldBorderAPI can you change the border to be more of a worldborder type particle and stretch it up further to make it easier to see through walls?

**Comment by LlmDl** [comment]
That uses packets as far as I remember, so probably no.

**Comment by LlmDl** [comment]
Yes that uses packets, which Towny doesn't use.
