### ISSUE TITLE
TownyChat not working with DiscordSRV

### ISSUE THREAD

**Issue by SpiderBlitz** [TownyAdvanced/Towny#4822]
### What steps will reproduce the problem?
1. Install the latest versions of Towny, Towny Chat and DiscordSRV on Paper
2. Send a message

### What is the expected output?
1. Output in Discord through DiscordSRV
2. No Console Error

### What is your Towny version?
Towny - 0.96.7.9
Towny Chat - 0.87

### What is your spigot/craftbukkit version?
Paper 562 (MC: 1.16.5)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/HnqTiwqU
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/FDEhZSuK
3. Your townyperms.yml :
https://pastebin.com/642BdZDF
4. Your log's error : 
https://pastebin.com/y06f2JPq

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://pastebin.com/0nWnK9Sk
7. Your channels.yml :
https://pastebin.com/TUuEyaiu

**Comment by LlmDl** [comment]
Did you do what DiscordSRV says to do in their config when you're using DiscordSRV and TC together?

**Comment by mtmtyu** [comment]
I'm also in the same situation.
