### ISSUE TITLE
Suggestion: block regen to not affect blocks placed after explosion

### ISSUE THREAD

**Issue by emkirsh** [TownyAdvanced/Towny#4825]
**Please explain your feature request to the best of your abilities:**
Some of my players are complaining that they "accidentally" placed a iron block in the creeper hole and it got overwritten by a dirt block with regen. I said that it was their fault for testing the regen with a valuable block and they should have known better, but it would be a cool feature (if not too hard to implement) to skip filling in blocks that have been placed since the explosion.

**Comment by LlmDl** [comment]
Doing this would just open up the opposite problem: someone would place a dirt block where a valuable was about to regenerate.

**Comment by emkirsh** [comment]
Ohhhhhh. That's true

--Eli Kirshenbaum

________________________________

**Comment by emkirsh** [comment]
Better to not open a path to griefing than accommodate bad decision making

--Eli Kirshenbaum

________________________________
