### ISSUE TITLE
Towny Wilderness Permissions Issue

### ISSUE THREAD

**Issue by TGTGamer** [TownyAdvanced/Towny#4844]
https://clips.twitch.tv/SweetHumbleRhinocerosMau5-sp8O9vvIpKWxYRTO

### What steps will reproduce the problem?
Unknown. Still investigating. We set the following settings
```
# Unclaimed Zone settings.
unclaimedZoneBuild=false
unclaimedZoneDestroy=false
unclaimedZoneSwitch=false
unclaimedZoneItemUse=false
unclaimedZoneName=Wilderness
```

![image](https://user-images.githubusercontent.com/11413796/113300450-d568f380-92f5-11eb-8fc4-33f959efb5b6.png)

### What is the expected output?
Allowed to place wilderness blocks.

### What is your Towny version?
0.96.7.10

### What is your spigot/craftbukkit version?
Paper(553) 1.16.5-RO.1-Snapshot

### Files:
https://gist.github.com/TGTGamer/c350d331c17a380200f13386f9c9a1fb
[townyDebug.json.gz](https://github.com/TownyAdvanced/Towny/files/6243826/townyDebug.json.gz)
[world.txt](https://github.com/TownyAdvanced/Towny/files/6243806/world.txt)
[world_nether.txt](https://github.com/TownyAdvanced/Towny/files/6243807/world_nether.txt)
[world_the_end.txt](https://github.com/TownyAdvanced/Towny/files/6243808/world_the_end.txt)

**Comment by LlmDl** [comment]
The video shows the player trying to place torches in the Nation Zone surrounding the town. I have double checked that nationzones also abide by the wilderness ignore mat lists, so I can only assume the player involved is not part of the nation who owns that town.

I'll need much clearer and precise instructions to reproduce this.
