### ISSUE TITLE
Redstone disappears when revert on unclaim is Disabled

### ISSUE THREAD

**Issue by Luberr-Dhruv** [TownyAdvanced/Towny#4845]
### What steps will reproduce the problem?
1. change `revert_on_unclaim` to `false` in the config.yml file
2. run `/tw toggle revertunclaim` to Disabled
3. claim a plot
4. place some redstone dust, hoppers, redstone blocks, repeaters, etc..
5. unclaim plot
6.  Redstone dust disappears

### What is the expected output?
1. Redstone dust should not disappear
2.
3.

### What is your Towny version?
Do not say "latest". towny-0.96.7.0

### What is your spigot/craftbukkit version?
Do not say "latest". paper build #575

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : [latest.log](https://pastebin.com/fN9s1f2W)
2. Your Towny config.yml (if using MySQL please remove password,) : [config.yml](https://pastebin.com/jDmdD3UX)
3. Your townyperms.yml : [townyperms.yml[(https://pastebin.com/3t0Ea8SE)
4. Your log's error : <I dont understand this>

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
There is a list of blocks which are cleared from plots which are unclaimed, these are in the towny\data\worlds\worldname files.
