### ISSUE TITLE
Prefix being set to lowercase in TownyChat

### ISSUE THREAD

**Issue by 1CAMOU** [TownyAdvanced/Towny#4847]
### What steps will reproduce the problem?
1. Set luckperms prefix for rank
2. Type in chat

### What is the expected output?
1. An uppercased prefix

### What is your Towny version?
TownyChat-0.87
Towny-0.96.7.11

### What is your spigot/craftbukkit version?
Airplane 3ed988 1.16.5

**Comment by LlmDl** [comment]
Going to need an `/lp editor` link for your LP setup, it doesn't look like we're purposefully setting it to lower-case and that it is just what Vault is giving us to use.

**Comment by 1CAMOU** [comment]
https://luckperms.net/editor/wJ6W6D3l5o

**Comment by LlmDl** [comment]
Which rank did you test this with?

**Comment by 1CAMOU** [comment]
its happening with all ranks

**Comment by LlmDl** [comment]
I'll need your chatconfig.

**Comment by 1CAMOU** [comment]
[ChatConfig.txt](https://github.com/TownyAdvanced/Towny/files/6258670/ChatConfig.txt)

**Comment by LlmDl** [comment]
Do you get anything different when you use {permgroupprefix} instead of {permprefix} ?

**Comment by 1CAMOU** [comment]
i get no prefix then

**Comment by LlmDl** [comment]
Strange stuff, I'm going to make a guess that there's some disconnect between what you have configured in LP and what Vault reads from LP and sends to us to use.

**Comment by 1CAMOU** [comment]
Nvm, would be a nice idea to have Vault installed *facepalm*

**Comment by LlmDl** [comment]
are you a wizard?
