### ISSUE TITLE
Problem with "Economy" plug-in *Please read if this was not the right place to post this*

### ISSUE THREAD

**Issue by MrTrowsel** [TownyAdvanced/Towny#4851]
### What steps will reproduce the problem?
1. Create Town
2. use /t
3.

### What is the expected output?
1. Nothing in-game
2. A warning in the console log
3.

### What is your Towny version?
Version 0.96.7.0

### What is your spigot/craftbukkit version?
Spigot 1.16.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/gX55fNE6
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/gX55fNE6
3. Your townyperms.yml : https://pastebin.com/6ZhMhLCP
4. Your log's error : https://pastebin.com/u9T26ci9 (on sthe creation of a town) and https://pastebin.com/m8wYcvNn (when using /t)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
That economy plugin probably doesn't implement Vault's deprecated but useful methods.

**Comment by MrTrowsel** [comment]
any other plugins you would recommend?

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/wiki/Frequently-Asked-Questions 

You have many options and only a few that you should not use.
