### ISSUE TITLE
HUD not updated when leaving plot group

### ISSUE THREAD

**Issue by Misquoth** [TownyAdvanced/Towny#4856]
### What steps will reproduce the problem?
1. create a plot group and set price
2. Leave plot
3. On screen display of plot info does not update when leaving plot

### What is the expected output?
In testing it seems like the behavior is to update the HUD plot info when the plot entered differs from the plot left.
This seems to work for all cases I've tested except when leaving a group plot. It works on the town border for the group, not town plots.

### What is your Towny version?
v0.96.7.0

### What is your spigot/craftbukkit version?
Paper : Paper-576

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/KzwGRcwJ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/dewZ1FPp
3. Your townyperms.yml : https://pastebin.com/LEmWUi5k
4. Your log's error : no error

**Comment by LlmDl** [comment]
When you say HUD are you talking about what shows up in the chat/action bar or what you see in the scoreboard when you have `/plot perm hud` active?

**Comment by LlmDl** [comment]
Spotted it in testing. Will be fixed as of 0.96.7.12.
