### ISSUE TITLE
/t new (townname) gives error

### ISSUE THREAD

**Issue by Centralgz** [TownyAdvanced/Towny#4858]
### What steps will reproduce the problem?
1./t new (town-name)
2.
3.

### What is the expected output?
1. an internal error occured while attempting to perform this command
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.7.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Bungeecord server-----Spigot 1.16.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/NZ5m3cqj

2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/ymJGxtz9

3. Your townyperms.yml :# This file contains custom permission sets which will be assigned to your players https://pastebin.com/NUWQBkb8

4. Your log's error : https://pastebin.com/hqxyi2uE

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Update your spigot to a newer version of 1.16.1 or any newer version of 1.16.*.

**Comment by Centralgz** [comment]
> Update your spigot to a newer version of 1.16.1 or any newer version of 1.16.*.

Thank you very much! This worked, I switched to 1.16.4, I was trying to fix this for too long.
