### ISSUE TITLE
Suggestion: Ability to trust someone in town or plot

### ISSUE THREAD

**Issue by Bibithom** [TownyAdvanced/Towny#4860]
**Please explain your feature request to the best of your abilities:**
Hello,
Towny is a wonderful plugin for managing town's permissions at different scales.
But, it's not so easy to give to a particular player a particular permission.
For example, a mayor need to claim a plot, add another player as friend, this other player need to add mayor as friend, to allowed him to build inside a plot.
It's ok for many situations but it comes with some troubles, all mayor/resident plot are shared, this process is not so intuitive for players nor mayors.

Is it possible to ad a simple command like /town trust <player> and /plot trust <player> to allow him to build, use switch, destroy and use items inside this entire town/this plot ? With obviously, /plot untrust <player> /town untrust <player> and maybe /plot trusted and /town trusted (which give a list of trusted players).

It may be difficult to add that kind of mechanics.

Thank you for reading, have a nice day !

**Comment by LlmDl** [comment]
The friendslist isn't quite how you describe, it doesn't need to be mutual. Only the plot owner needs to have the player in their friendlist, and the plots still require the friend group to have Build/Destroy/Switch/Itemuse activated in the plot itself.

I don't know what you mean by "all mayor/resident plot are shared" I don't think this accurately describes how plot perms work.

**Comment by Bibithom** [comment]
Ok, my bad for friends and plots perm, i haven't seen that.
Is there a way for a mayor to allow someone to build in his town without the necessity to add the builder to the town ?

**Comment by LlmDl** [comment]
The plot can be sold to them as an embassy plot. If/when this ticket is filled it would be possible.

**Comment by Bibithom** [comment]
Ok thank you have a nice day

**Comment by LlmDl** [comment]
Closing in favour of #4117
