### ISSUE TITLE
Townyperms.yml don't add user to luckperms group

### ISSUE THREAD

**Issue by Soncomander** [TownyAdvanced/Towny#4861]
### What steps will reproduce the problem?
1. On Luckperms create group `nomad` and `resident`
2. On Townyperms.yml add `group.nomad` on nomad permissions and `group.resident` on towns.default permissions
3. Run `/lp user <USER> parent info`, only default group is active
4. Join/rejoin a town, no parent `resident` detected
5. Leave town, no parent `nomad` detected
6. Run `/lp user <USER> permission check group.resident` or `/lp user <USER> permission check group.nomad` and will return true respecting the rule from Townyperms.yml
7. Repeat step 4 and 5, node is added but not affecting luckperms

### What is the expected output?
1. Townyperms.yml add group node
2. Towny add user to group
3. Luckperms detect group

### What is your Towny version?
0.96.7.10

### What is your spigot/craftbukkit version?
1.16.5-R0.1-SNAPSHOT

### Links
Townyperms.yml: https://pastebin.com/SvXdpXEU
Luckperms Editor: https://luckperms.net/editor/x0ao2QcKww

## Comments
Using luckperms command to add has permission this same nodes it will work and detect has a new group, maybe `group.` need a different parse

**Comment by LlmDl** [comment]
That's not how it works. I'm guessing the group node isn't parsed outside of LP's own  files. I don't believe this would be an error on Towny's side of things, especially if LP see's the player as having the node itself.

**Comment by LlmDl** [comment]
And also if you want to add more nodes to the nomad/resident groups in Townyperms.yml, just add them into the townyperms.yml file.

**Comment by Soncomander** [comment]
I was trying to centering all my perms in one place after I had a similar problem like #4847 but on Tablist with Vault and LP has a whole, prefix not respecting CamelCase and going lowercase. (See the linked Townyperms)

Do you think is worth a new issue or I can post on #4847?

**Comment by LlmDl** [comment]
No need to post in a ticket that ended up being caused by not installing Vault.

You do not need to be trying to put all your permissions in one place. Towny has its own built-in permissions system in townyperms. If you think LP doesn't respect CamelCase then file a ticket with Luck.
