### ISSUE TITLE
Suggestion: Add ResidentPreJailEvent

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#4862]
**Please explain your feature request to the best of your abilities:**

Some servers may require finer control to limit the circumstances under which residents can be jailed. The existing ResidentJailEvent is not cancellable and is called *after* imprisonment has taken place.

**Example use case, from my server:**

Teleportation on my server is severely limited. The only forms of teleportation are (1) range-limited TPA requests and (2) respawns at town homeblocks after dying. With the jail mechanic enabled, ranked residents can imprison other residents on the other side of the map to quickly summon them to the town. A ResidentPreJailEvent would allow us to check how far the detainee is from their town and deny the request if appropriate.

**Comment by LlmDl** [comment]
The event isn't great but it will do what you want. With the coming jail overhaul it'll end up being a lot nicer.
