### ISSUE TITLE
Suggestion: Automatically set town and nation tag on town and nation creation

### ISSUE THREAD

**Issue by johnyuki** [TownyAdvanced/Towny#4869]
**Please explain your feature request to the best of your abilities:**

With Townychat, {townytagoverride} display the town/nation tag if it's present. If it isn't present then it shows the town/nation name as a whole. Making it display the town and nation name as a whole is kind of annoying as it takes up a lot of space on the chat line. By making the plugin automatically set the town and nation tags to the first 4 letters of the town and nation names, it bypasses this issue. 

Additionally, when using {towntag} without a tag set, it is just blank and doesn't appear at all, and having the towny plugin automatically set tags would fix this issue too.

**Comment by LlmDl** [comment]
{towntagoverride} does the tag if is present or otherwise shows the whole town name.

**Comment by johnyuki** [comment]
> 
> 
> {towntagoverride} does the tag if it is present or otherwise shows the whole town name.

Yes but the issue then is that for longer town names it makes the chat look like this: 
https://i.imgur.com/b7fZRiR.png

With longer town + nation names it takes up a lot of space in the chat by default, which is why it would be nice to have a config option for it to automatically set a tag by using the first letters of the town/nation name.
