### ISSUE TITLE
Towny doesn't register bedrock players (UUID?)

### ISSUE THREAD

**Issue by xxxcrow** [TownyAdvanced/Towny#4873]
### What steps will reproduce the problem?
1. Install towny
2. Install geyser
3. Any action with towny as a bedrock player

### What is the expected output?
1. Confirmation dialogue?

### Towny version
1. Towny-0.96.7.12

### Paper version:
1. Yatopia 1.16.5-77

Clean install, no errors or any info about the problem in the server logs and console
Even no error when a player joins or tries to claim a town/join/break

**Comment by LlmDl** [comment]
If you're using floodgate and geyser, floodgate is not supported.

**Comment by xxxcrow** [comment]
Solved by changing floodgate prefix from "*" to "."
(I tried some other prefixes before, but they didn't work)
