### ISSUE TITLE
Brand new players cannot see town, nation or ally chat until relogging or talking in them.

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#4874]
### What steps will reproduce the problem?
1. Have a brand new (not in the towny db at all) player join the server. (I replicated this by dropping the resident from the towny residents table while the server was off).
2. Invite the new player to the town and have them accept.
3. Talk in town, nation, or admin chat - the player cannot hear you.
4. If the player relogs it fixes it for all chats.  If they talk in one of the chats, it fixes it for that chat, but not the others.
5. Before relogging or speaking in the chats, /channel list shows the player out of all the non-general chats.

### What is the expected output?
1. New players joining towns before relogging for the first time should be able to hear town/nation/ally chats without having to reload or speak in them.
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.7.11

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 546 (1.16.5) 

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://paste.gg/p/Momshroom/fa5baca35ccf43c0b3bc612594fdca4a
2. Your Towny config.yml (if using MySQL please remove password,) :
https://paste.gg/p/Momshroom/3625ac679a69482cbd75c08f164874ac
3. Your townyperms.yml :
https://paste.gg/p/Momshroom/7b222379d85646edba755bf4feea8b26
4. Your log's error : 
no error
(optional) If this is to do with permissions, 
5. Your permissions file :
issue occurs even without a permissions plugin loaded

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://paste.gg/p/Momshroom/a778118b6b994ccd9f4b5dba0cebb203
7. Your channels.yml :
https://paste.gg/p/Momshroom/82bfb098f6de4880bd076672b7996c8b

**Comment by LlmDl** [comment]
Closed by https://github.com/TownyAdvanced/TownyChat/commit/047b14f6ac39c33414f15521ad85467c166352d2
