### ISSUE TITLE
[API][EVENTS]Exception while creating a town.

### ISSUE THREAD

**Issue by Clercq** [TownyAdvanced/Towny#4876]
### What steps will reproduce the problem?
1. /t new name
2. Just go to any another chunk within some seconds
3. /confirm
4. Your town will be created but the homeblock is not. It causes an exception, and no info will be moved to the database. Yeah, it will be fixed after any action with the town(e.g. create a homeblock), however, you will not receive the NewTownEvent. Actually, it happens because you've set <<towny home>> without homeblock.

### What is the expected output?
1. Get the same coordinates for homeblock
2. Getting the NewTownEvent

### What is your Towny version?
Do not say "latest".
0.96.5.6

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.5, I guess it's 1.16.5-R0.1-SNAPSHOT
https://github.com/pl3xgaming/Purpur

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your log's error :  https://pastebin.com/ew6jjmQi

**Comment by LlmDl** [comment]
retest using 0.96.7.0

**Comment by LlmDl** [comment]
was fixed in https://github.com/TownyAdvanced/Towny/commit/61e4ee63e6453ee83b6bfdd31833cb994cdb17aa

**Comment by Clercq** [comment]
Got it thanks
