### ISSUE TITLE
Suggestion: Biome based claim prices

### ISSUE THREAD

**Issue by jravuwannab** [TownyAdvanced/Towny#4879]
Configurable claim prices based off of biomes would be a nice feature to see. I think some pretty cool stuff could be done on earth servers with it.

**Comment by drewdorris** [comment]
Seconded. I want to discourage players from claiming in the ocean and other biomes, but not completely prevent it.

Additional daily upkeep based on biome per claim, i.e. an additional biome tax per claim, would also be a great feature
