### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by Dudunkin** [TownyAdvanced/Towny#4884]
**Please explain your feature request to the best of your abilities:**

Suggestion: Add a setting to confing that allows players to use the bed everywhere, and revel in it, and use it without saying that this bed is occupied.
Setting like bed_usage_everywhere

(Sorry for my english)

**Comment by LlmDl** [comment]
There's nothing stopping players from using any bed if deny_bed_use is set to false.

Towny is not the sort of plugin to bypass the "bed is occupied" message.
