### ISSUE TITLE
[1.16.5-0.96.7.13] java.lang.StackOverflowError: null after /town confirm.

### ISSUE THREAD

**Issue by Yldales** [TownyAdvanced/Towny#4890]
Hi,

### What steps will reproduce the problem?
1. Set up a server using [Paper 626](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/626/downloads/paper-1.16.5-626.jar).
2. Install [Vault 1.7.3](https://media.forgecdn.net/files/3007/470/Vault.jar).
3. Install Towny [0.96.7.13](https://github.com/TownyAdvanced/Towny/releases/download/0.96.7.13/Towny-0.96.7.13.jar).
4. Install Gringotts (MinecraftWars/Gringotts) (Compiled from MinecraftWars/Gringotts@278de97df9f40c6d64e3a66ee35205a38923e7fa)
5. Use `/town create Whatever`, then `/town confirm`.
6. The _java.lang.StackOverflowError: null_ error should occur, freezing Towny, and spamming the logs with the same error.

### What is your Towny version?
Towny version 0.96.7.13

### What is your spigot/craftbukkit version?
Paper version git-Paper-626 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : -
2. Your Towny config.yml (if using MySQL please remove password,) : Default file.
3. Your townyperms.yml : Default file.
4. Your log's error : https://pastebin.com/raw/WaEvLCvr

**Comment by LlmDl** [comment]
This would appear to be a bug on Gringott's end of things. I'll take a look at it when I have the time.

**Comment by Yldales** [comment]
Thanks 🙂 . Should I open an issue on the MinecraftWars/Gringotts's issue tracker ?

**Comment by LlmDl** [comment]
Yeah this is a ticket for them.
