### ISSUE TITLE
Towny Death Event Broken with Citizens/Sentinel plugin

### ISSUE THREAD

**Issue by TheLastBlockbender** [TownyAdvanced/Towny#4895]
### What steps will reproduce the problem?
1. Get killed by a sentinel npc from the citizens/sentinel plugins
2. console gets an error:

### What is the expected output?
1. Get killed by an npc without getting console errors
2.
3.

### What is your Towny version?
Do not say "latest".
96.7.14

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/kcWEn9RP
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/WEKjxXZV
3. Your townyperms.yml : https://pastebin.com/JeTiUAKb
4. Your log's error : https://pastebin.com/smqnUTWL

**Comment by LlmDl** [comment]
Wanna test this out: https://cdn.discordapp.com/attachments/669247087329673228/837358164159889490/Towny-0.96.7.15.jar

**Comment by TheLastBlockbender** [comment]
Ok that works. Thank you so much!
