### ISSUE TITLE
Hex color codes are not being parsed in TownyChat spy messages

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#4896]
### What steps will reproduce the problem?
1. In `channels.yml`, put a hex color code in the `channeltag` for any channel. For example: `channeltag: '&8[&#14a6e0TC&8]'`
2. Type `/townychat reload`
3. Type `/towny spy`
4. Ask someone to speak in the channel, and the spy message will appear like so: 

![screenshot](https://i.gyazo.com/6a09fbe2e3c0cd397ee085444f8664e9.png)

### What is the expected output?
The hex color code should be parsed or not shown 

### What is your Towny version?

* Towny 0.96.7.14
* TownyChat 0.87

### What is your spigot/craftbukkit version?
Purpur 1.16.5, Build 1065.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your Towny config.yml (if using MySQL please remove password,) : [Link](https://pastebin.com/4pbp9rNU)
2. Your chatconfig.yml : [Link](https://pastebin.com/GP6i7yHC)
3. Your channels.yml : [Link](https://pastebin.com/TMzeRTHG)
4. [Startup log](https://pastebin.com/ZXTZKmSQ)

**Comment by LlmDl** [comment]
Please test that this fixes it: https://cdn.discordapp.com/attachments/669247087329673228/837804624219865179/TownyChat-0.88.jar

**Comment by galacticwarrior9** [comment]
> 
> 
> Please test that this fixes it: https://cdn.discordapp.com/attachments/669247087329673228/837804624219865179/TownyChat-0.88.jar

This works, thank you
