### ISSUE TITLE
Plot permissions aren't working, I need help.

### ISSUE THREAD

**Issue by WOLFRAGE99** [TownyAdvanced/Towny#4897]
Any player can edit any plot, Even plot roles have been set for the plot and aren't functioning properly.
(Breaking, Placing, Switchuse, Item use) in any town.

 What is the expected output?
1.Players cannot edit any town plots they haven't joined or don't have permission to.

Towny version
0.96.7.0

spigot version?
spigot.16.5
(Not sure how to find the actual spigot version)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/r9cHNL8m
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/kWLMEMuA
3. Your townyperms.yml : https://pastebin.com/EsdU1Y7k
4. Your log's error : Not exactly sure, Sorry I'm new.

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/SNW9vvpy

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Warriorrrr** [comment]
From the looks of your permissions pastebin, it looks like you gave players the `towny.*` node, which gives them access to everything. If removing it doesn't work, send a link to your luckperms editor and I'll take a look.

**Comment by WOLFRAGE99** [comment]
Aye thanks for the help! I'll do that soon and send feedback if it works.

**Comment by Warriorrrr** [comment]
I'll assume this has been resolved, if it hasn't, comment here or join the Discord for more support.
