### ISSUE TITLE
Cant add permission to residents or else

### ISSUE THREAD

**Issue by BerkayAksoylu** [TownyAdvanced/Towny#4900]
### What steps will reproduce the problem?
1. ./t set perm resident build on (anything includes "i"
2.
3.

### What is the expected output?
1. adding perm successfully
2.
3.

### What is your Towny version?
0.96.7.0

### What is your spigot/craftbukkit version?
paper 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://paste.wumpus.cc/uwehomepub.yaml
2. Your Towny config.yml (if using MySQL please remove password,) : https://paste.wumpus.cc/jewibezole.coffeescript
3. Your townyperms.yml : https://paste.wumpus.cc/kehehuqugo.properties
4. Your log's error : https://prnt.sc/12ek3a2  /  https://paste.wumpus.cc/damuyagaje.css /  (there is no error in console but this is one of the errors about towny)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :https://paste.wumpus.cc/lobelerehi.coffeescript
7. Your channels.yml : https://paste.wumpus.cc/bajuhudobu.yaml

**Comment by Warriorrrr** [comment]
Was fixed by the user changing their OS language.
