### ISSUE TITLE
Suggestion: Add translation lines

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#4908]
Instead of having the following three translation lines:

```
msg_cache_block_error_town_resident: '&cResidents aren''t allowed to %s here.'
msg_cache_block_error_town_allies: '&cAllies aren''t allowed to %s.'
msg_cache_block_error_town_outsider: '&cOutsiders aren''t allowed to %s.'
```

Please expand them to 12 of them:

```
msg_cache_block_error_town_resident_build: '&cResidents aren''t allowed to build.'
msg_cache_block_error_town_resident_destroy:
msg_cache_block_error_town_resident_swtich:
msg_cache_block_error_town_resident_item:
msg_cache_block_error_town_allies_build: '&cAllies aren''t allowed to build.'
msg_cache_block_error_town_allies_destroy:
msg_cache_block_error_town_allies_swtich:
msg_cache_block_error_town_allies_item:
msg_cache_block_error_town_outsider_build: '&cOutsiders aren''t allowed to build.'
msg_cache_block_error_town_outsider_destroy:
msg_cache_block_error_town_outsider_swtich:
msg_cache_block_error_town_outsider_item:
```

Otherwise, when trying to translate this, and even if the line `destroy: 'Destroy'
` has been translated, the lines will state something like: **Los extranjeros no tienen permitido _BUILD_.**

This is because, as I was told, these words are somehow hard-coded, so they can't be translated everywhere.

**Comment by LlmDl** [comment]
I took a look at the code and the action words aren't hard-coded:
```
build: 'Build'
destroy: 'Destroy'
switch: 'Switch'
item_use: 'Item_Use'
```
These are the words used in the above msg_cache_block_error... strings you pointed out above.

I don't believe there's any missing translations here.

**Comment by VreyaViress** [comment]
Thank you for answering. I was able to confirm that the translation is working in the "msg_cache_block_error_town" lines, which is grat, as can be seen in the following image:
https://i.imgur.com/TO6IGHy.png

However, they don't seem to be working in the "/town" screen, as can be seen here:
https://i.imgur.com/b4122x5.png

This is how the lines look in my translation file:
https://i.imgur.com/YJHfzOn.png
