### ISSUE TITLE
Suggestion: Add a command to set a custom town / nation prefix and suffix.

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#4914]
The town and nation's prefixes and suffixes are currently determined according to the "levels:" section in config.yml.

Please add a command such as `/town set prefix 'Land of '`.

This will be very useful when using the placeholders `%townyadvanced_player_location_town_prefix%` and `%townyadvanced_player_location_town_postfix%`.

**Comment by LlmDl** [comment]
This would require us to store a prefix and postfix on all of the towns and probably the nations as well, that would be there to override the config.
