### ISSUE TITLE
Suggestion: Add a plot owner name placeholder

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#4916]
Currently, there is the placeholder `%townyadvanced_player_plot_owner%`, which displays either true or false if you own the plot you're standing on or not.

Please add a placeholder such as `%townyadvanced_player_plot_owner_name%` to display the blank or the name of the owner of the plot you're standing on.

I also noticed the recently added placeholder `{townyadvanced_player_location_plot_name}` hasn't been added to the placeholder list in the wiki https://github.com/TownyAdvanced/Towny/wiki/Placeholders.

**Comment by LlmDl** [comment]
The wiki is only updated when a release build is made, which is why you don't see it on the wiki yet.
