### ISSUE TITLE
Suggestion: Add a formatted town and nation name placeholders

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#4918]
I got the placeholder `{towny_town_nameformatted}` from Mvdw, which gives me the name of a Town without the brackets []. This is useful when using Conditionperms as I'm adding players to teams to only show tag names to those of your town. If works great.

However, I actually want to do this with the people of your own nation.

However, there is not a `{towny_nation_nameformatted}` Mvdw placeholder.

Is there an internal or PAPI placeholder to show the nation's name without the brackets []?

All these PAPI placeholders return names inside brackets: 
```
%townyadvanced_town%
%townyadvanced_town_formatted%
%townyadvanced_nation%
%townyadvanced_nation_formatted%
```

**Comment by LlmDl** [comment]
Use the placeholder formatting section of the Towny config.yml to remove the brackets.
