### ISSUE TITLE
Suggestion: Add option to disable msg_new_day

### ISSUE THREAD

**Issue by VreyaViress** [TownyAdvanced/Towny#4919]
Please add an option to disable the msg_new_day message.

**Comment by LlmDl** [comment]
Can you expand on why you wouldn't want people to know about the new day occurring?

**Comment by VreyaViress** [comment]
As I don't have an economic system, and therefore, don't use taxes, and as time is different for each of my worlds, being slower during the day in some of them, I find the message confusing. 

However, you might very well set this to low priority, as I now know there are many plugins that can be used to disable messages, such as Triton, which worked just fine to remove this one.

Thank you for your attention.
