### ISSUE TITLE
trouble with towny 0.96.7.0

### ISSUE THREAD

**Issue by enloken** [TownyAdvanced/Towny#4923]
### What steps will reproduce the problem?
1. tried it a few times
2. tried find a solution in internet, but i dont founded it

### What is the output?
1.nothing
2.nothing
3.nothing

### What is your Towny version?
Towny-0.96.7.0.jar

### What is your spigot/craftbukkit version?
paper-1.16.5-651.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
https://pastebin.com/uHYV0YFi latest.log
2. https://drive.google.com/file/d/1x86mM4lbrprvS6szFihS0EiUk4d4kkFd/view?usp=sharing
3. https://drive.google.com/file/d/15NM8v5PNdSeHpT9eWa_GYAsNCUu2aY64/view?usp=sharing

When I create a city using English characters and restart the server, everything works fine and towny allows me to continue working, but as soon as the Cyrillic alphabet is used in the name of the nation/city, towny switches to safe mode. Also, the cities in the data folder are there with a strange name, instead of the name they have???????. txt, and when I download them, they become just __________.txt. I hope you can help me.
[________.txt](https://github.com/TownyAdvanced/Towny/files/6453285/________.txt)

**Comment by LlmDl** [comment]
Your server Operating System is not set up to allow towny to save unicode characters. This might be your doing or your Host's doing. Read this: https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#towny-regex-settings in order to configure Towny to not allow those characters to be used in your file system.

**Comment by enloken** [comment]
regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[a-zA-Z0-9._\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^a-zA-Z0-9\&._\[\]-]'
    this dont solve the problem, i will test with another ways to solve it

**Comment by LlmDl** [comment]
It wont fix any existing files but it will prevent new towns being name that way.
