### ISSUE TITLE
Not Registered Expection Performance Issue

### ISSUE THREAD

**Issue by Kovalski4** [TownyAdvanced/Towny#4929]
### What steps will reproduce the problem?
1. idk

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
Tuinity

### Please use Pastebin.com to link the following files:

[log.txt](https://github.com/TownyAdvanced/Towny/files/6481247/log.txt)

**Comment by LlmDl** [comment]
Looks like you have a resident that doesn't exist.
