### ISSUE TITLE
Suggestion: Jail Break

### ISSUE THREAD

**Issue by Kovalski4** [TownyAdvanced/Towny#4931]
**Please explain your feature request to the best of your abilities:**
Option to make jails more aggressive. 
In the current system, the only way to get out of prison is to pay money. That's boring and overpowered. If the prisoner doesn't have money, jailed for a lifetime. My idea is explosions should not be turned off once the towns have prisoners.

This idea also supports my idea of the prisoner transfer system. Towns can transfer prisoners to prison town and turn off their explosions. #4930

**Comment by LlmDl** [comment]
EventWar already jail breaks, not sure if we'll do it in non-war time. I thought more servers would let them use enderpearls/chorus fruit, as players who reach the wilderness will be unjailed. They can also get out of jail by leaving the town. There are more ways than just paying bail.

**Comment by Kovalski4** [comment]
Only siegewar allowed in my server and I think more server like this because eventwar is too old. We need more "war" reasons and jail break with explosions is a good point.

**Comment by LlmDl** [comment]
Event War is getting a big overhaul after I finish the Jail overhaul.
