### ISSUE TITLE
[Some?] Database Migrations Failing to run [0.96.1.0 -> 0.97.0.0]

### ISSUE THREAD

**Issue by Parsonswy** [TownyAdvanced/Towny#4935]
### What steps will reproduce the problem?
1. Create a fresh install of Towny 0.96.1.0 with mysql datastorage.
2. Stop server and replace with 0.97.0.0.
3. Start server.
4. I am noticing specifically an issue with the the `_NATIONS` table. It still has the `towns` column and the `assistants` column. I've not done a full comparison of the schema so there may be other tables that are out of date as well.
5. Attempting to create a new nation results in a log file full of
   ```
   [01:32:55] [Craft Scheduler Thread - 1054/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: SQL: Field 'towns' doesn't have a default value --> HikariProxyPreparedStatement@1267287812 wrapping com.griefcraft.shaded.mysql.jdbc.ServerPreparedStatement[786195] - REPLACE INTO TOWNY_NATIONS (`capital`, `metadata`, `taxes`, `neutral`, `registered`, `nationBoard`, `enemies`, `uuid`, `nationSpawn`, `mapColorHexCode`, `isOpen`, `spawnCost`, `name`, `isPublic`, `tag`, `allies`) VALUES ('TLET','','0.0','0','1621041249973','/nation set board [msg]','','***','','556b2f','0','0.0','***','0','','')
   ```
   because of the depreciated column. In our case our log file grew until we hit our disk allocation for the server and it was killed.

### What is the expected output?
1. The `towns` column in `_NATIONS` appears to have been dropped sometime between versions 96.1 and 97.0. I would assume it should be automatically removed.

### What is your Towny version?
`0.97.0.0`

### What is your spigot/craftbukkit version?
```
This server is running Paper version git-Paper-655 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/J1NBxpP3
2. Your Towny config.yml (if using MySQL please remove password): https://pastebin.com/8yCKKE7T
3. Your townyperms.yml: https://pastebin.com/YwWAhcyv
4. Your log's error : 
   ```
   [01:32:55] [Craft Scheduler Thread - 1054/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: SQL: Field 'towns' doesn't have a default value --> HikariProxyPreparedStatement@1267287812 wrapping com.griefcraft.shaded.mysql.jdbc.ServerPreparedStatement[786195] - REPLACE INTO TOWNY_NATIONS (`capital`, `metadata`, `taxes`, `neutral`, `registered`, `nationBoard`, `enemies`, `uuid`, `nationSpawn`, `mapColorHexCode`, `isOpen`, `spawnCost`, `name`, `isPublic`, `tag`, `allies`) VALUES ('TLET','','0.0','0','1621041249973','/nation set board [msg]','','***','','556b2f','0','0.0','***','0','','')
   ```

**Comment by LlmDl** [comment]
Towny is supposed to automatically drop those columns but on some Mysql servers they do not. I have recently put together a build that would be a bit more aggressive in trying to drop the columns. If you're using a test server I will give you the build to try out. I cannot get the columns to not automatically drop on my test server.

**Comment by Parsonswy** [comment]
Thank you for the prompt response.

Yes, I do have a server I can test on. We use Mariadb and I've seen this happen on versions `10.4.18/Ubuntu 18.04` and `10.3.25/Ubuntu 20.04`.

**Comment by LlmDl** [comment]
Try it out using this: https://cdn.discordapp.com/attachments/669247087329673228/843136534235447296/Towny-0.97.0.1.jar

Let me know if it drops the tables properly.

**Comment by Parsonswy** [comment]
Unfortunately that did not drop the tables.
```
plugman info Towny
[15:05:24 INFO]: [PlugMan] Plugin Information: Towny
[15:05:24 INFO]: - Version: 0.97.0.1
[15:05:24 INFO]: - Author(s): Shade, Modified by FuzzeWuzze. Forked by ElgarL. Forked by LlmDl.
[15:05:24 INFO]: - Status: Enabled
```
```
  | 1 | varchar(32) | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 2 | mediumtext | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 3 | mediumtext | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 4 | mediumtext | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 5 | mediumtext | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 6 | mediumtext | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 7 | mediumtext | latin1_swedish_ci |   | No | None |   |   | Change | Drop | More
  | 8 | float |   |   | No | None |   |   | Change | Drop | More
  | 9 | float |   |   | No | None |   |   | Change | Drop | More
  | 10 | tinyint(1) |   |   | No | 0 |   |   | Change | Drop | More
  | 11 | varchar(36) | latin1_swedish_ci |   | Yes | NULL |   |   | Change | Drop | More
  | 12 | bigint(20) |   |   | Yes | NULL |   |   | Change | Drop | More
  | 13 | mediumtext | latin1_swedish_ci |   | Yes | NULL |   |   | Change | Drop | More
  | 14 | mediumtext | latin1_swedish_ci |   | Yes | NULL |   |   | Change | Drop | More
  | 15 | tinyint(1) |   |   | No | 1 |   |   | Change | Drop | More
  | 16 | tinyint(1) |   |   | No | 1 |   |   | Change | Drop | More
  | 17 | text | latin1_swedish_ci |   | Yes | NULL |   |   | Change | Drop | More
  | 18 | mediumtext | latin1_swedish_ci |   | Yes | NULL
```

**Comment by LlmDl** [comment]
Did the startup log make any mention of `Error updating table `? If so please show this.

**Comment by Parsonswy** [comment]
I don't see one. Full startup log is https://pastebin.com/Vw2901hq.

**Comment by LlmDl** [comment]
ok give this one a shot please: https://cdn.discordapp.com/attachments/669247087329673228/843163770049134632/Towny-0.97.0.1.jar

**Comment by Parsonswy** [comment]
No change. [Startup log](https://pastebin.com/ANcGp9eZ).

**Comment by LlmDl** [comment]
OK this one has a bunch of debug messages: https://cdn.discordapp.com/attachments/669247087329673228/843183152293609472/Towny-0.97.0.1.jar

**Comment by Parsonswy** [comment]
[Output](https://pastebin.com/LjsYZHQM).

**Comment by LlmDl** [comment]
And yet your DB has those columns in those tables still?

**Comment by Parsonswy** [comment]
Yes. I included the SQL errors from running the `/nation new` command which
fail because the column is still there.

**Comment by LlmDl** [comment]
Yes, this is essentially the behaviour I've encounted: for an unknown reason some mysql servers are reporting they do not having the columns present, so Towny doesn't try to remove them. The code we use to check if the columns are present:
```java
    		DatabaseMetaData md = cntx.getMetaData();
        	ResultSet rs = md.getColumns(null, null, table, column);
        	if (!rs.next()) {
        		System.out.println("Not found: " +column+ " in " + table + " table.");
        		return;
        	}
```
is standard and should work on all mysql/mariadb servers.

The servers who have this issue are a small percentage.

**Comment by Parsonswy** [comment]
Some debug stuff below.... In the meantime, can I just drop the `towns` and `assistants` columns to get the plugin working, or do I need to move/confirm that the data has been moved somewhere else?

---

I threw together a plugin with
```java
HikariDataSource ds = new HikariDataSource(hc);
Connection c = ds.getConnection();
DatabaseMetaData md = c.getMetaData();
ResultSet rs = md.getColumns(null, null, "TOWNY_NATIONS", "%");

while(rs.next()) {
	System.out.println(rs.getString(4));
}
```

and got

```
[04:56:29 INFO]: name
[04:56:29 INFO]: towns
[04:56:29 INFO]: capital
[04:56:29 INFO]: assistants
[04:56:29 INFO]: tag
[04:56:29 INFO]: allies
[04:56:29 INFO]: enemies
[04:56:29 INFO]: taxes
[04:56:29 INFO]: spawnCost
[04:56:29 INFO]: neutral
[04:56:29 INFO]: uuid
[04:56:29 INFO]: registered
[04:56:29 INFO]: nationBoard
[04:56:29 INFO]: nationSpawn
[04:56:29 INFO]: isPublic
[04:56:29 INFO]: isOpen
[04:56:29 INFO]: metadata
[04:56:29 INFO]: mapColorHexCode
```

Changing `getColumns()` to
```java
ResultSet rs = md.getColumns(null, null, "TOWNY_NATIONS", "towns");
```
I do indeed get
```
[05:00:59 INFO]: towns
```

I will clone this repo and see if I can figure out why this test code runs differently than Towny as it doesn't seem to be a bug or misconfiguration with our MariaDB server.

**Comment by LlmDl** [comment]
If you're going to test that out note that the cleanup() code is only run if the version number is newer that the last_run_number in the config. In the builds I made for you I was forcing it to run everytime.

**Comment by Parsonswy** [comment]
In the meantime, can I just drop the towns and assistants columns to get the plugin working, or do I need to move/confirm that the data has been moved somewhere else?

**Comment by LlmDl** [comment]
No those things in teh cleanUp() method just need to be dropped. They're columns we won't ever use again.

**Comment by Parsonswy** [comment]
It doesn't look like the table prefix is being added to the table name in the [`md.getColumns()`](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/db/SQL_Schema.java#L478) call during the migration?

I added the prefix and the migration worked. Might this actually be the fix? I don't understand how this would not have shown up in previous testing or been more widespread as the MySQL default config prefixes the table names. I've opened and tagged a PR with the change if it is actually what is necessary.

**Comment by LlmDl** [comment]
Really quite strange that this is what fixes it. All the PR does is move it from one spot to the other.

**Comment by Parsonswy** [comment]
The part that fixed it was that it was not being prefixed on [this](https://github.com/TownyAdvanced/Towny/pull/4952/files#diff-e9d852b6839786176d6a9f7b1aed49c60c5e23545b84ddd5f5696e59bb210529R478) line for the `md.getColumns()` call. I just moved the concatenation so it only needed doing once and was consistent in the debug messaging.

**Comment by LlmDl** [comment]
Yeah, thanks for figuring this out. I'll probably test it on my end where it was never broken to make sure it still works for non-failing servers.
