### ISSUE TITLE
Joining nation chat doesn't give an error when not in a nation, just stops displaying entered texts.

### ISSUE THREAD

**Issue by Litning11** [TownyAdvanced/Towny#4936]
### What steps will reproduce the problem?
1.  Join /nc without being in a nation
2. Speak in chat
3.

### What is the expected output?
1. An error saying you're not in a nation and therefore can't speak in that channel
2.
3.

### What is your Towny version?
Do not say "latest".
0.97.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
"This server is running Purpur version git-Purpur-1082 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 29 version(s) behind
Previous version: git-Purpur-1061 (MC: 1.16.5)"

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/028rMNzA
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/7X3rWCUr
3. Your townyperms.yml : https://pastebin.com/V8S3jq9v
4. Your log's error : See latest.log

(optional) If this is to do with permissions, 
5. Your permissions file : https://luckperms.net/editor/9fCpjhx1cD

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/PM8vNZBN
7. Your channels.yml : https://pastebin.com/pwN8JmnN

**Comment by Maroon28** [comment]
Hey! Have you tried de-opping yourself if you were opped? If you have all permissions, it would let you in the channel regardless of if you're in a nation or not.

**Comment by Litning11** [comment]
> Hey! Have you tried de-opping yourself if you were opped? If you have all permissions, it would let you in the channel regardless of if you're in a nation or not.

No.
