### ISSUE TITLE
Suggestion: Nation-controlled per-town NationTax Exemption

### ISSUE THREAD

**Issue by SeanSean98** [TownyAdvanced/Towny#4937]
Towny for PVE servers are based on economy and community building.

I suggest adding a tax exemption for towns within a nation.
You can compare it to the **town_tax_exemption permission** but for towns in nations.
Essentially nation staff will be able to grant specific towns the ability to avoid tax within the nation.

This would add another layer to the management and influence of a nation.
It could be easily displayed in the **/nation** tab to make it visible to others.

**VIP Towns:** London(Hamlet), Paris(City), Brussels(Metropolis)
or
**Tax Exempted:** London(Hamlet), Paris(City), Brussels(Metropolis)

**Comment by LlmDl** [comment]
Are you talking about the tax a town pays to the nation or the upkeep a town pays to the server?

**Comment by SeanSean98** [comment]
The tax a town pays to the Nation.
Meaning once a tax is set, all towns must pay up.
To get more flexibility for "newer towns" it would be easier to tax exempt those towns from paying the tax.
Which would instead would be covered by the nation bank.

**Comment by LlmDl** [comment]
For the time being the nation can just pay the tax money back into the Town bank using the existing command.

**Comment by SeanSean98** [comment]
Meaning a Nation King has to   **/nation deposit town amount**   for an x amount of towns.
Kinda the reason why a nation tax exemption for towns would work as a solution.
But thanks for reading and replying to the suggestion :) appreciated
