### ISSUE TITLE
adventure-api error spam in console

### ISSUE THREAD

**Issue by TheElitePanda** [TownyAdvanced/Towny#4938]
### What steps will reproduce the problem?
1. the error appears to be whenever I am within a town region
2. when not in a towny region or world, it does not appear

### What is the expected output?
(I don't know what you mean by expected output but I will assume it's what happening right now)

1. https://pastebin.com/k5icc4SY
2. server console is complaining about adventure-api
3.

### What is your Towny version?
Do not say "latest". 

0.96.7.14

### What is your spigot/craftbukkit version?
Do not say "latest".

using git-Paper-683 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/PqSRayyL
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/aBiTQUBG
3. Your townyperms.yml : https://pastebin.com/1vi2U61B
4. Your log's error : (I don't understand this question but I assume it's the error that I have found via console. https://pastebin.com/k5icc4SY (please let me know if I need to redo this step)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by GNosii** [comment]
Seems like this is caused by these lines on [TownyCustomListener#onPlayerChangePlotEvent](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java)
```java
msg = Colors.translateColorCodes(msg);
/**/
final String message = msg;
/* Inside task: */
playerAudience.sendActionBar(Component.text(message));```
