### ISSUE TITLE
Suggestion: Allow mayors to set their own bail amounts.

### ISSUE THREAD

**Issue by aco4** [TownyAdvanced/Towny#4940]
**Please explain your feature request to the best of your abilities:**
a command like `/t set bail mayor 69420`
It would also be even cooler to have a percent bail: `/t toggle bail percentage`
It could be used like this: `/t set bail mayor 50` (50%)

This might need some config options to limit crazy town mayors:
`max_bail_mayor`
`max_bail_mayor_percent`
... etc.

So bail cannot be higher than $10,000 or higher than 50% of the jailed player's balance.

**Comment by Semisol** [comment]
Small thing: There should be a cap on % bail, like with `taxpercentcap`.

**Comment by LlmDl** [comment]
This will be implemented but not using any percentages.
