### ISSUE TITLE
Town name too long

### ISSUE THREAD

**Issue by JustinDevB** [TownyAdvanced/Towny#4942]
### What steps will reproduce the problem?
1. Name a town too long
2. Interact with the town via command in anyway
I am unable to interact with the town with /ta town (as seen in the error log) to attempt to rename the town.

### What is the expected output?
1. Town to work properly

### What is your Towny version?
Do not say "latest".
0.97.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
This server is running Purpur version git-Purpur-1078 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 40 version(s) behind
Previous version: git-Purpur-1060 (MC: 1.16.5)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Not relevant, and too big to be pasted
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/ihmqbx8K
3. Your townyperms.yml : https://pastebin.com/18aFPRPT
4. Your log's error : https://pastebin.com/MkGcMhHk

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
So you've enabled long town names, but the code Towny uses to display the title bars of the status screens doesn't handle names that long.

**Comment by JustinDevB** [comment]
So what can I do? The town is unable to deposit money in their bank because of this error.

https://pastebin.com/QvVb1Kzd

and I am unable to rename the town because any command I do throws an error.

**Comment by LlmDl** [comment]
You'll likely have to rename the town in the database/resident files, until something can be done about the header.

**Comment by LlmDl** [comment]
Yeah now that I think about it you have to edit the townblocks it owns as well. Might want to find a mass-text editor to do the find & replace.

**Comment by JustinDevB** [comment]
Is there an possible way I can just delete the town through commands? It would avoid me causing a safe mode and I can just give the town the money to reclaim

**Comment by LlmDl** [comment]
You might be able to /ta town NAME delete
