### ISSUE TITLE
Suggestion: Teleport outlaws away (when it is set in the config) right after getting outlawed

### ISSUE THREAD

**Issue by TamrielNetwork** [TownyAdvanced/Towny#4944]
**Please explain your feature request to the best of your abilities:**
Its more of a nice to have, but atm people that get outlawed can still stay in the town (even if teleporting away is enabled in the config). Would be nice if they would get tpd right after getting outlawed :smiley:

**Comment by SmallSansSerif** [comment]
I've had players want this too as someone has a troll player in their area and they won't leave.
