### ISSUE TITLE
Town deposited money change automatically

### ISSUE THREAD

**Issue by LunarECL** [TownyAdvanced/Towny#4945]
### What steps will reproduce the problem?
1. deposite money
2. wait a day or few hours
3. automatically decrease or increase by the town
(even look up bankhistory, it is same)

### What is the expected output?
1. same money
2.
3.

### What is your Towny version?
Do not say "latest".
0.97.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :

[https://docs.google.com/document/d/10EVsCudbUsrMQkATELp1BZYQcqZiRdJCpfxGntE-7ng/edit?usp=sharing](url)
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LunarECL** [comment]
startup log 
https://docs.google.com/document/d/1r14umyDCGl7aGKnqztV8Cx38PTuZ1-kn_kx--uK_ndI/edit?usp=sharing

**Comment by LlmDl** [comment]
How certain are you that the changing balance isn't just the Town collecting taxes or paying upkeep? the /t bankhistory command doesn't persist through restarts.

If you want to, you can look in your towny\backups\ files to see the older money.csv logs of all the money transactions.

**Comment by LunarECL** [comment]
![image](https://user-images.githubusercontent.com/38317983/119503125-96ab6300-bda5-11eb-9b59-793cc41ffe8c.png)
![image](https://user-images.githubusercontent.com/38317983/119503167-a1fe8e80-bda5-11eb-936a-e57a889833ca.png)
certainly disappear... I already checked the transactions and there was no withdraw

**Comment by LlmDl** [comment]
This is probably something you want to explain to the EssentialsXEconomy developers. If there's no record of it changing in either the bankhistory book or in the money.csv files, then Towny probably isn't the one losing the money.
