### ISSUE TITLE
NullPointerException: null at com.palmergames.bukkit.towny.TownyUniverse.<init>

### ISSUE THREAD

**Issue by viveleroi** [TownyAdvanced/Towny#4947]
https://paste.gg/p/anonymous/a0eb0a632ade46ff9ae8f0d4c35757ad

### What steps will reproduce the problem?
1. Use api methods like `TownyAPI.getInstance().getResident(player.getName())`
2. Error

### What is the expected output?
1. No error

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
Paper build 714. Paper build 674 worked, so something between those broke. 

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://paste.gg/p/anonymous/7d1c4ba2336444e0b705bd2f4e492b01
2. Your Towny config.yml (if using MySQL please remove password,) : https://paste.gg/p/anonymous/6479e368989344db842a091df24ba18e
3. Your townyperms.yml : https://paste.gg/p/anonymous/8c6599614c734b2c9743a3e73074b506
4. Your log's error :  https://paste.gg/p/anonymous/a0eb0a632ade46ff9ae8f0d4c35757ad

**Comment by LlmDl** [comment]
It would be nice to see more of your source code. That method can return null but the error you're showing is because your TownyAPI instance is null.

**Comment by viveleroi** [comment]
I'm not sure that I'm responsible, this worked fine on paper 674.

```
Resident resident = TownyAPI.getInstance().getResident(player.getName());
        if (resident != null) {
            return resident.hasTown() && super.allowsPlayer(player);
        }
```

**Comment by LlmDl** [comment]
Ah, I bet related to this:
```
[10:25 AM] viveleroi: some devs in the paper channel said "spigot made changes to how the classloaders work"
[10:25 AM] viveleroi: so it may be due to spigot changes
```

That is fairly strange.

**Comment by viveleroi** [comment]
I figured I'd ask them if they knew what recent change might cause it, that was their reply. I can't say how accurate it is but clearly something in recent paper (or spigot) causes it.

**Comment by LlmDl** [comment]
Well if they've done something that breaks that API call there's probably going to be a fairly large number of people coming to us about it.

**Comment by viveleroi** [comment]
Just in case this helps, I had originally had the following (likely related) error but you mentioned I was using a deprecated API: https://paste.gg/p/anonymous/6149719d05c3403f95f95ad20f08f84a

My original code used `TownyAPI.getInstance().getDataSource().getResident(player.getName())`

**Comment by viveleroi** [comment]
Just in case it's missed, here's my source file: https://paste.gg/p/anonymous/fe97b5f922f9414382b99170fad7cfb0

I don't meant to double up messages here and discord, will try to avoid that.

**Comment by viveleroi** [comment]
A recent spigot change revealed a flaw in how I had included towny in my build.gradle file, I had used `implementation 'com.github.TownyAdvanced:Towny:0.97.0.0'` when I should have used `compileOnly`
