### ISSUE TITLE
Updated towny not loading + econ issue previous build

### ISSUE THREAD

**Issue by morlanius** [TownyAdvanced/Towny#4950]
### What steps will reproduce the problem?
1. install version  Towny-0.97.0.0
2. use sql
3.
 Towny-0.97.0.0.jar doesn't load (see pastebin)

Towny-0.96.7.0.jar appears to work normally but now refuses to hook the economy, no error messages in console
just insufficient funds message. Other plugins are accessing the econ fine.
Vault installed.

### What is the expected output?
1. normal use
2.
3.

### What is your Towny version?
Do not say "latest".
Towny-0.97.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot-1-16-5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml https://pastebin.com/0EUuCuLj
3. Your townyperms.yml : https://pastebin.com/84iskDpF
4. Your log's error : https://pastebin.com/UHgjUnjB

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by morlanius** [comment]
restoring version  to Towny-0.96.7.0 without changing any configs stops the error and everything seems normal except its not hooking vault. The version Towny-0.97.0.0 gives the errors detailed above.

The old version worked once and then gives not enough money message when player has plenty. other plugins are using it just fine and can buy/sell without issues. the econ is Economy from Spigot repo and is also using SQL with a different user and a different database on the same server,

**Comment by LlmDl** [comment]
Seeing your full server startup could be helpful.

**Comment by morlanius** [comment]
Here is a log from startup to shutdown showing loading up current version, talking in local to test then shutting down again.
After debugging this for a while I found that a quicker way to see if its loaded Towny or not. Also, the issue with the previous version I mentioned seems to be down to the economy plugin and unrelated. But the current version wont load at all.

As the plugin isn't hooking the database it seems that an exception is thrown every dis/connection which makes sense if its unable to access the datasource. Reerted to 0.96.7.0 for the time being.

Please excuse that I haven't edited out all the world loading (have many worlds).

https://pastebin.com/vqEm5ft9

**Comment by LlmDl** [comment]
Looks like we've updated the HikariCP version since 0.96.7.0 and your server doesn't already have the logger class we use. Shouldn't be too difficult to shade it in.

**Comment by morlanius** [comment]
Towny-0.96.7.0 also isn't hooking the econ and we have vault and Reserve.
When trying to deposit it responds "null" as well as /t spawn says "null"
Nothing in console log when doing this.

**Comment by morlanius** [comment]
I just tried as OP and it says "The server economy plugin Economy via Vault could not return the Town account"
And yeah, I'm looking to update once 0.97+ is updated that it will load. All the other plugins we use are working fine though and I think they are using vault, but they also don't create accounts so I suspect its around that.

**Comment by morlanius** [comment]
Which build would you recommend while I wait for HikariCP to be factored in to a new build?

**Comment by LlmDl** [comment]
Can you give this a test and let me know if I properly shaded in teh logger: https://cdn.discordapp.com/attachments/669247087329673228/848220708776443974/Towny-0.97.0.1.jar

**Comment by morlanius** [comment]
Loaded just fine.
Thank you.
