### ISSUE TITLE
upgrade to 0.97 causes sql errors

### ISSUE THREAD

**Issue by hmmcrunchy** [TownyAdvanced/Towny#4958]
### What steps will reproduce the problem?
1.upgrade from 0.96.7.0 to 0.97.0.0
2. start server
3. also no occurs when reverting to 0.96.7.0 

### What is the expected output?
1. towny to start
2. server to start
3.

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
spigot-1.16.5-R0.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :  https://pastebin.com/yeF3bCv8    - endless logs from towny
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/ByJLwtee
3. Your townyperms.yml : https://pastebin.com/e87ufNQC
4. Your log's error : https://pastebin.com/jtT1rmLP  - logs up 70GB log files of this 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Hey, so this is one of those mysql things I could never reproduce and affects a small percentage of people. Thankfully it's also something that got fixed in the 0.97.0.1 by someone who also had their mysql server ignore our requests to drop the old columns. Try update to 0.97.0.1 and let me know how it works.

**Comment by hmmcrunchy** [comment]
Hey there, ha ha im always the few xD 

ive loaded the new one and that seems to have cracked it - all loaded, no errors. 

thanks very much indeed

**Comment by LlmDl** [comment]
Thanks for confirming that it works on your end.
