### ISSUE TITLE
Message after running added subcommand

### ISSUE THREAD

**Issue by MetalWarLord** [TownyAdvanced/Towny#4971]
### What steps will reproduce the problem?
1. Create a new subcommand using the TownyCommandAddonAPI
2. Run the command in game

### What is the expected output?
1. Not showing this message
![image](https://user-images.githubusercontent.com/85002487/120136973-9fe86580-c1d3-11eb-8f85-5bea7fd86faf.png)

### What is your Towny version?
0.97.0.1

### What is your spigot/craftbukkit version?
Paper 1.16.5

Nothing was changed in the original config and no error message was sent.

**Comment by LlmDl** [comment]
You got some code to show us?

**Comment by MetalWarLord** [comment]
I've got this in the main class of my plugin:
`AddonCommand relCommand = new AddonCommand(CommandType.TOWN, "rel", new Command());`
`TownyCommandAddonAPI.addSubCommand(relCommand);`

And the `Command()` class is a `CommandExecutor` class with an empty `onCommand()` method. 
If I write something in the `onCommand()`, it runs perfectly, but I still get that message.

**Comment by LlmDl** [comment]
Something along the way would appear to be throwing a TownyException.

**Comment by Warriorrrr** [comment]
A TownyException is thrown if a CommandException occurs, I can't reproduce the error with an onCommand method that instantly returns true.

**Comment by MetalWarLord** [comment]
Oh... Sorry! For some unknown reason I've written `return false;` at the end of onCommand...
