### ISSUE TITLE
Suggestion: Allow Individual plot perms and ability to view who has perms to a plot

### ISSUE THREAD

**Issue by gabeeebaby** [TownyAdvanced/Towny#4975]
**Please explain your feature request to the best of your abilities:**
Allow individual players to get permissions to a plot through /plot set perm IGN build on. It would allow people to share a plot with some one else without having to mess with their friend perms or let all of their friends have access to a specific plot.

Viewing who has perms to a plot would allow easy identification of who can access it and would go well with the above feature but also on its own. It could be at the bottom of /plot perm. It could list who has perms sort of like how a resident list for a town is, and doing /plot perm IGN would show what specific perms that player has.

**Comment by LlmDl** [comment]
This one ties into this ticket https://github.com/TownyAdvanced/Towny/issues/4117 which is asking for the ability to add a player to a town which would then get treated as a resident.

**Comment by LlmDl** [comment]
I think I would be inclined to add the ability to make a player have equal rights to the plot, in the same way that the plot owner isn't checked for individual Build/Destroy/Switch/Itemuse perm types.

**Comment by gabeeebaby** [comment]
Adding equal rights would definitely be useful, but I was talking more about allowing individuals to have access to certain or all perms of a plot without being the owner. For example, if you want only a certain player to have access to a plot that stores your valuables and they aren’t in the same town, the only option is friending, but then all you friends have access to your plot. Giving just that player perms to switch, build, etc without being the owner/co owner of that plot.

**Comment by LlmDl** [comment]
Yeah but from a code stand point what you're asking for is a big change in how data is stored/processed. 

What I'm talking about would essentially give the marked player the PLOT_OWNER TownBlockStatus and not require any changes to how plot permissions are saved.
