### ISSUE TITLE
/sethome and /home commands are blacklisted, even for residents of the town, despite setting otherwise

### ISSUE THREAD

**Issue by savourybun** [TownyAdvanced/Towny#4978]
### What steps will reproduce the problem?
1. Enable town_command_blacklisting in config.yml
2. Add sethome and home to town_blacklisted_commands
3. Add sethome and home to player_owned_plot_limited_commands
4. Restart or reload Towny

### What is the expected output?
1. /sethome and home to not work for players who are not residents of the town they are standing in
2. /sethome and home to work for players who are residents of the town they are standing in

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
git-Paper-740 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/KRvKKab1
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/iScFvfsU
3. Your townyperms.yml : https://pastebin.com/WSzF8Mrh
4. Your log's error : NA

**Comment by StubbiestPeak75** [comment]
I believe you haven't added a towny.claimed.townowned.* node for your residents

**Comment by LlmDl** [comment]
> I believe you haven't added a towny.claimed.townowned.* node for your residents

This doesn't have anything to do with the above issue.

**Comment by StubbiestPeak75** [comment]
While my solution didn't indeed fix the problem, i have found that this behaviour is fixed in 0.97.0.2
