### ISSUE TITLE
Suggestion: givebonus outpost

### ISSUE THREAD

**Issue by benevolent2012** [TownyAdvanced/Towny#4979]
**Please explain your feature request to the best of your abilities:**
Could a command be added similar to `/ta givebonus {town} {#}` except that it would give outposts instead of town blocks?
In essence, it would be increasing the max outposts as nation bonuses do.

**Comment by LlmDl** [comment]
I'm already not a big fan of the givebonus command (because it is frequently used to sell townblocks on server shops.) This would be subject to the same abuse of the license.
