### ISSUE TITLE
Players get kicked into another channel type on town deletion.

### ISSUE THREAD

**Issue by StubbiestPeak75** [TownyAdvanced/Towny#4984]
### What steps will reproduce the problem?
1. Create a new town
2. Join general channel (in my case its called /a, /all, /g, /gc, /global)
3. use /t delete
4. You will get a messsage saying [Towny] Modes set:
5. You will be placed in HELP chat instead, another global channel type.

### What is the expected output?
1. Player remains in the same global channel they have been in when town was deleted.

### What is your Towny version?
Towny: 0.97.0.2
TownyChat: 0.88

### What is your spigot/craftbukkit version?
Paper version git-Paper-572 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/4fae0aMD
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/j4sVBiVU
3. Your townyperms.yml :  https://pastebin.com/23pkJhgj
4. Your log's error : I am not getting an error.

(optional) If this is to do with permissions, 
5. Your permissions file : -

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/rr0DThjr
7. Your channels.yml : https://pastebin.com/3Fy37HfR

**Comment by StubbiestPeak75** [comment]
I have tested this on players leaving town regularly, but this happens only when town gets deleted.

**Comment by LlmDl** [comment]
So the instructions in the original post are incorrect? `3. leave town` should be `3. use /t delete` ?

**Comment by StubbiestPeak75** [comment]
Yes, I’m sorry for the mistake.

Step number 3 should be “use /t delete”.
