### ISSUE TITLE
Suggestion: Election system

### ISSUE THREAD

**Issue by GroleDev** [TownyAdvanced/Towny#4988]
Integrate an election/referendum (or basically vote) system to Towny.

1 - Allow king/mayor to set up recurrent elections,for exemple "/n set election 3" will set up an election every three months.

2 - All mayor can run for national election with "/n run" and all resident of a town can run for municipal election with "/t run"

3 - Admin Configuration for automatically launching elections when the king/mayor is absent for a few weeks.

4 - Allow king/mayor and co-king/co-mayor to set up referendums for example "/n referendum Is it a cool idea ?" set up a vote that lasts X day(s) (based on the admin config) where residents of the nation/town can do "/n vote yes\no”', the day before vote's end, residents can consult the result with "/n referendum result".

I hope you like my idea, thanks for reading it !

**Comment by SeanSean98** [comment]
I think this is a great idea, however this feels like it's an entire plugin by itself.
The core of the mayorship/kingship is to own the town/nation you've paid for.

However this concept of an election based leadership could incentivize an entire new category of servers.
I for one would love to see some sort of election based towny plugin!

**Comment by MilesBHuff** [comment]
Please use approval voting, or at least make it an option -- first-past-the-post voting is really terrible!

**Comment by ElMoha943** [comment]
theres a plugin that does something similar: https://www.spigotmc.org/resources/towny-elections-enjoy-democracy-supports-1-16.67400/

**Comment by Darutan92** [comment]
> Есть плагин, который делает нечто подобное: https://www.spigotmc.org/resources/towny-elections-enjoy-democracy-supports-1-16.67400/
It only partially implements this.

**Comment by Darutan92** [comment]
> theres a plugin that does something similar: https://www.spigotmc.org/resources/towny-elections-enjoy-democracy-supports-1-16.67400/
It only partially implements this.
