### ISSUE TITLE
NPE on startup com.palmergames.bukkit.towny.object.Resident.setJailCell(Resident.java:131)

### ISSUE THREAD

**Issue by viveleroi** [TownyAdvanced/Towny#4990]
### What steps will reproduce the problem?
1. Install Towny 0.97.0.2
2. Boot server

### What is the expected output?
1. No errors

### What is your Towny version?
0.97.0.2

### What is your spigot/craftbukkit version?
Purpur 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
4. Your log's error : https://paste.gg/p/anonymous/2b8cb7bef49c48e287a66bfbab2ce260

**Comment by LlmDl** [comment]
@viveleroi can you test this out for me please https://cdn.discordapp.com/attachments/669247087329673228/851074817025114123/Towny-0.97.0.3.jar
