### ISSUE TITLE
towny.admin.outlaw.teleport_bypass  not bypass /t spawn

### ISSUE THREAD

**Issue by slvlr** [TownyAdvanced/Towny#4994]
### What steps will reproduce the problem?
1.I added towny.admin.outlaw.teleport_bypass node to staff. This has allowed them to enter towns that they are outlawed to, but /t spawn <name> does not work and it still gives them the error message saying that they are outlawed. Is this a separate node?

### What is the expected output?
1. User with towny.admin.outlaw.teleport_bypass to be able to use /t spawn <name>

### What is your Towny version?
0.97.0.2

### What is your spigot/craftbukkit version?
Paper 1.16.5 build 770

**Comment by LlmDl** [comment]
Different nodes:

- towny.admin.spawn: User is able to bypass the costs, warmups and cooldowns for spawning.
  - towny.admin.spawn.nocharge: User will not be charged to spawn to towns.
  - towny.admin.spawn.nocooldown: User will not have to wait to use the spawn commands after spawning.
  - towny.admin.spawn.nowarmup: User will not have to wait to spawn after using the spawn commands.
