### ISSUE TITLE
Town staff are exempt from taxes. even when exempt permission is removed.

### ISSUE THREAD

**Issue by DaniGTA** [TownyAdvanced/Towny#4995]
### What steps will reproduce the problem?
1. remove tax_exempt permission in townyperm file
2. see taxes

### What is the expected output?
1. That Town Staff paying taxes

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
PAPER 1.16.5 #775

Townyperms.yml in a txt format to upload to github
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/6619337/townyperms.txt)

Log:
[Resident Msg] PLAYER: Town staff are exempt from taxes.

**Comment by LlmDl** [comment]
What do you mean exactly when you say "see taxes"

**Comment by DaniGTA** [comment]
See the log it says that the Town staff are exempt from taxes.

**Comment by LlmDl** [comment]
Did you do /ta reload all or /ta reload perms after making the edits to the townyperms.yml?

**Comment by DaniGTA** [comment]
i restartet the server

**Comment by LlmDl** [comment]
Ok, looking at teh source code: mayors are always exempt, assistants who no longer have the exempt node will still end up paying.

**Comment by DaniGTA** [comment]
so there is right now no way to remove mayors tax exempt right ?

**Comment by LlmDl** [comment]
Not at the moment.
