### ISSUE TITLE
Suggestion: Add option that allows different distance pricing for /t spawn or /n spawns.

### ISSUE THREAD

**Issue by LeftTheNegotiator** [TownyAdvanced/Towny#5005]
My suggestion is to add an option that will charge for a /t spawn of another town, however it would cost the amoung of blocks away it is, for example by default, 100 blocks = 1g. 

This could also work with /n spawn as well, calculating the distance to the spawnpoint blockwise. It seems like a unique way of inflation control.

**Comment by LlmDl** [comment]
Duplicate of #3144.
