### ISSUE TITLE
Suggestion: Placeholders for town and plot perm line.

### ISSUE THREAD

**Issue by Darkweasam** [TownyAdvanced/Towny#5006]
**Please explain your feature request to the best of your abilities:**
Hello,

I would like to have several more placeholders, as I am trying to make my own GUI for Towny because it is very hard to many players that are first seeing the multiplayer world of Minecraft.

I would like to have the following placeholders:
- [x] Plot owner's name (the one that you stand on currently) - if it has one
- [ ] Plot's toggleable options (mobs, pvp, fire, etc) displaying true/false depending if they are enabled in the given town
- [ ] Town's toggleable options (mobs, pvp, fire, public, etc) displaying true/false depending if they are enabled in the given town

Many thanks

*LlmDl Edit*: (From a sponsor on the Discord.)
- [x] Plot's Town's resident count.
- [x] Plot's Town's mayor's name.
- [x] Plot's Town's nation name.
- [x] PVP placeholder that shows (No PVP) instead of blank.

**Comment by LlmDl** [comment]
If you're making a GUI you'd be better off making something that accesses the API so you can get anything you'd need.

**Comment by Darkweasam** [comment]
> 
> 
> If you're making a GUI you'd be better off making something that accesses the API so you can get anything you'd need.

Well I am not a java developer and has no knowledge of such, I am making the GUI with the help of a plugin
