### ISSUE TITLE
Could not pass event TownySwitchEvent to Towny v0.97.0.0

### ISSUE THREAD

**Issue by ItsSynchro** [TownyAdvanced/Towny#5007]
### What steps will reproduce the problem?
1. Uncertain as the error was randomly thrown without any pretext

### What is the expected output?
1. 

### What is your Towny version?
Stable Release 0.97.0.0

### What is your spigot/craftbukkit version?
Paper 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml : https://pastebin.com/GtYCzGcZ
3. Your townyperms.yml : https://pastebin.com/rrwJHLF0
4. Your log's error : https://pastebin.com/h9UF1MKR

**Comment by LlmDl** [comment]
Can you test this out for me: https://cdn.discordapp.com/attachments/669247087329673228/854109137117380638/Towny-0.97.0.6.jar
