### ISSUE TITLE
Can't create new town with mohist server

### ISSUE THREAD

**Issue by Naini0712** [TownyAdvanced/Towny#5011]
Hello.
When I create new town, Towny issued the error "An internal error occourred while attempting to perform this command."
Only I paid creating cost, new town wasn't created.
This is mohist(Bukkit + Spigot + Forge) server, problem may be complicated.

I sync Enderpay's money and Essential's money(Vault) with GrandEconomy(Mod) and Grand-Economy-Vault-Integration(Plugin).
I think that is cause.

If it isn't Towny's bug, please show me the reasons and details. Because I'll contact other plugin/mod author.

### What steps will reproduce the problem?
1. /town new {townname}
2. /confirm

### What is the expected output?
1. Creating new town and pay costs.

### What is your Towny version?
0.96.2.0-for-1.12.2

### What is your spigot/craftbukkit version?
mohist-1.12.2-209(I'm sorry I can't find spigot/craftbukkit from mohist version.)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :  I couldn't paste all of logs because lastest.log has 14.92MB and more than 100k lines. 
plugin list: https://pastebin.com/JhmMPLTX 
mod list: https://pastebin.com/cNeAU73P
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/0XZZuTbw
3. Your townyperms.yml : https://pastebin.com/pyNb3uv3
4. Your log's error : https://pastebin.com/Md6gcsMd

(optional) If this is to do with permissions, 
5. Your permissions file : I have op permission.

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Looks like enderpay doesn't have support for the Vault methods we use. You will have to choose a different economy plugin.

Also you should be using 0.97.0.0 for 1.12.2.
