### ISSUE TITLE
During and after a war event wilderness regeneration is not working

### ISSUE THREAD

**Issue by MetalWarLord** [TownyAdvanced/Towny#5014]
### What steps will reproduce the problem?
1. Create 2 nations!
2. Start a war event!
3. Use a TNT near the town border!

### What is the expected output?
1. Regeneration of the wilderness

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
Paper 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. config.yml: https://pastebin.com/C3Ba7LUv

**Comment by LlmDl** [comment]
would be nice if you also included your towny\data\worlds\WORLDNAME.txt so I can see your settings.

**Comment by MetalWarLord** [comment]
Oh... Of course.
Here it is: https://pastebin.com/kUZX0ZQZ

**Comment by LlmDl** [comment]
Can you give this a shot: https://cdn.discordapp.com/attachments/669247087329673228/856258446584315914/Towny-0.97.0.7.jar

**Comment by MetalWarLord** [comment]
I've tested it. It still doesn't work.

**Comment by MetalWarLord** [comment]
I took some screenshots...
The yellow carpet indicates the town border.

Before explosion:
![before](https://user-images.githubusercontent.com/85002487/122689172-071c9700-d221-11eb-8792-954de094435d.png)
After explosion:
![after_explosion](https://user-images.githubusercontent.com/85002487/122689174-08e65a80-d221-11eb-98bc-e2ef96c65641.png)
During regeneration:
![during_regen](https://user-images.githubusercontent.com/85002487/122689177-0ab01e00-d221-11eb-8fa9-893ad1b12910.png)
After regeneration and the end of the war:
![after](https://user-images.githubusercontent.com/85002487/122689169-04ba3d00-d221-11eb-96e9-331801fc82c1.png)

**Comment by LlmDl** [comment]
The side that didn't regen is in the wilderness?

**Comment by MetalWarLord** [comment]
Yes, it is.
