### ISSUE TITLE
Suggestion: Make /t bankhistory and /n bankhistory a little more permanent 

### ISSUE THREAD

**Issue by goldengate03** [TownyAdvanced/Towny#5018]
**Please explain your feature request to the best of your abilities:**
 It resets too often and when I need to verify a deposit. I can't. So I would like this to be more permanent. Let's say 25 pages (because plot tax is it's own page) of Town/Nation Bank history. This would make it a more useful command.

**Comment by LlmDl** [comment]
It currently resets on each startup/reload. You can get historical transaction data from the towny\backup\ .tar files' logs folders' money.csv files.

**Comment by LlmDl** [comment]
Duplicate of #4775

**Comment by goldengate03** [comment]
This isn't a duplicate

**Comment by goldengate03** [comment]
What I am saying is that it doesn't log everything and the plugin devs should make it log more items...

**Comment by LlmDl** [comment]
What is it not logging?

**Comment by goldengate03** [comment]
It’s not logging every single time money is drawn out, it randomly resets.
If I misunderstood the said duplicate suggestion, I have another suggestion
but I will make another thread for that. I am not a Server owner, just a
mere player on a Server where the upper staff told me to suggest it here

**Comment by LlmDl** [comment]
It resets every time the server is stopped or reloaded. I don't think there's any transaction happening via towny command which isn't being logged.
