### ISSUE TITLE
Suggestion: Tax revenue

### ISSUE THREAD

**Issue by SeanSean98** [TownyAdvanced/Towny#5020]
As a mayor it is hard to figure out how much money your town will collect from taxes.
A command would be useful to help the mayor understand how much money would be collected from their members.
This would include 3 separate lines:

- Revenue from members tax ($)
- Revenue from members plottax ($)
- Revenue from members total ($)

Basically this will give the Mayor and Town Staff an estimate of the revenue they can expect.

**Comment by LlmDl** [comment]
Some of this is already available via `/town plots`, I don't remember at the moment if there's a way to see what is coming in from residents' taxes.

**Comment by dragontekgaming** [comment]
Would it be possible to have a transaction log similar to `/t bankhistory` and/or `/n bankhistory`?

**Comment by LlmDl** [comment]
@dragontekgaming
The tax revenue is already recorded as transactions in the bank history books.

Towny stores all transactions in the towny\logs\money.csv, with previous days' logs in your towny\backups\ files.

There's already a ticket to make Towny able to go back farther using only the books but it isn't a high priority.
