### ISSUE TITLE
You are not a mayor or assistant.

### ISSUE THREAD

**Issue by tskopen** [TownyAdvanced/Towny#5028]
### What steps will reproduce the problem?
1./plot forsale

### What is the expected output?
1. you are not a mayor or assistant (even though I am)

### What is your Towny version?
0.97.0.6

### What is your spigot/craftbukkit version?
i use paper and its 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://mcpaste.io/0df4650c102489f7
2. https://mcpaste.io/5079842b48168c59
3. https://mcpaste.io/83a78280818c5d51
4. Your log's error : no clue where this is or how to get it

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your townyperms.yml's mayor has `towny.command.plot.*` which is giving `towny.command.plot.asmayor` to all mayors. This is the permission node being tested for that results in the not-mayor-or-assistant message, if they don't have the node.

You can try using `/ta checkperm tskopen towny.command.plot.asmayor` to see whether Towny thinks you have the node.

Anyways, if I boot up my test server and just use `/plot forsale` I'm fairly confident it will work fine. This is more than likely due to your permission setup. Make sure you have no Towny nodes in your LuckPerms.

**Comment by tskopen** [comment]
why dont i want towny perms in luckperms?

**Comment by LlmDl** [comment]
Because they're already given out properly in the townyperms.yml. Advanced permission setups can require LP to have Towny nodes in them, but most of the time it's unneeded and just results in scenarios like yours, where something isn't being allowed.

**Comment by LlmDl** [comment]
Do `/lp editor` and give me your link.

**Comment by tskopen** [comment]
I don't want you to have access to my editor unless ik why I'm amusing I just do the command /lp group default permissions clear towny

**Comment by LlmDl** [comment]
Anyways, giving someone the /lp editor link doesn't let them edit your permissions. Its the simplest way for you to show me what you did in your LP re: Towny nodes.

**Comment by tskopen** [comment]
ok
here https://luckperms.net/editor/z2HRgKsXoo

**Comment by LlmDl** [comment]
You should remove all of those, a number of them are probably causing your issue. If players cannot build/destroy in the wild use `/ta toggle wildernessuse`.

**Comment by tskopen** [comment]
ok can i keep /lp group default permissions set towny.command.town.new  false world for people cant create a town In spawn?

**Comment by LlmDl** [comment]
If you have a spawn world you don't want people to claim in, just use `/tw toggle claimable`.

**Comment by tskopen** [comment]
ok cool it works now Thanks Mate :D
