### ISSUE TITLE
Plot claim doesn't work

### ISSUE THREAD

**Issue by BigTallahasee** [TownyAdvanced/Towny#5034]
### What steps will reproduce the problem?
1.Just putting up a plot forsale
2.Then trying to plot claim
3.

### What is the expected output?
1.To be able to purchase plots that are forsale
2.
3.

### What is your Towny version?
Do not say "latest".
0.97.0.8

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.17

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : N/A
2. Your Towny config.yml (if using MySQL please remove password,) : Using H2
3. Your townyperms.yml : Haven't done anything with the towny plugin. I downloaded it threw it in the server and started it up thats all!
4. Your log's error : No errors are showing up

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Warriorrrr** [comment]
Skipped the form, please include useful info such as server logs, your config and/or command output

**Comment by BigTallahasee** [comment]
XD I have no clue on how to do any of that so i guess goodluck with it.
