### ISSUE TITLE
Suggestion: Dynmap icon for ruined towns

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5035]
**Please explain your feature request to the best of your abilities:**

It would be nice to have a Dynmap icon for ruined towns.  This would help players to identify them on the map, and either reclaim them or loot them.

**Comment by LlmDl** [comment]
This was added semi-recently, not yet released. Duplicate of https://github.com/TownyAdvanced/Towny/issues/5026

**Comment by MilesBHuff** [comment]
Oh awesome!  And sorry;  I must have forgotten to remove the open-only filter when I searched to make sure I wasn't making a duplicate.
