### ISSUE TITLE
Suggestion: (simple) abandoned towns

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5041]
As an alternative to the suggestions in #4970, #5031, and #5036, which turned out to be technically complex;  I would like to propose a much simpler way to meet the requirements of the suggesters:

- There would be a boolean in the config which enables "abandoned" towns.  If enabled, the following would occur:
  - Towns which have hit their debt ceiling (or which have 0 in the bank, if bankruptcy isn't enabled) are considered "abandoned"
  - Such "abandoned" towns function the same as bankrupt towns, but with the following additional caveats:
    - Protections are disabled
    - Anyone can reclaim them
    - They use the ruins map icon
    - When you enter them, they say "Abandoned" instead of "Town", "Hamlet", etc.
    - They use the `town_ruining.town_ruins.ruins_become_public` setting, but this setting doesn't actually change any town settings -- it just overrides them while the town is abandoned.
  - Other than the above caveats, they remain as normal towns, with their original mayors and residents.
    - "Reclaiming" an abandoned town makes the reclaimer the mayor, and makes the old mayor a normal resident.

**Comment by LlmDl** [comment]
This functionality is served by TownyHistories.
