### ISSUE TITLE
Suggestion: plot merge (buy multiple plots at once)

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5044]
**Please explain your feature request to the best of your abilities:**
I would like the ability to merge different plots and put them forsale togheter so when someone does `/plot claim` they claim all the plots at the same time, instead of having to do it for each one. This also helps if i want to have bigger plots than the block size, if they are all individual claims someone could claim part of a big plot.

This could work like `/plot merge` and it would merge the plot you currently are on and the one in the direction your looking at (like plotsquared).

**Comment by LlmDl** [comment]
We already have this: `/plot group` is the base command.

**Comment by ElMoha943** [comment]
> We already have this: `/plot group` is the base command.

omg how i never saw this, thanx you very much
