### ISSUE TITLE
Beds and signs break after unclaiming town blocks

### ISSUE THREAD

**Issue by Element-Development** [TownyAdvanced/Towny#5048]
### What steps will reproduce the problem?
1. Claim a chunk using /t claim
2. Place down a bed and/or a sign
3. Unclaim the chunk using /t unclaim

### What is the expected output?
1. The beds and signs shouldn't break, because we set usingPlotManagementDelete=false and removed all block IDs that would be reset after unclaiming.
2.
3.

### What is your Towny version?
version: 0.97.0.9

### What is your spigot/craftbukkit version?
Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/wHwgw7QV
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/xmTdwSTB
3. Your townyperms.yml : https://pastebin.com/LJyFVbvR
4. Your log's error : None. There is no error in the console.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Other: The world.txt file
https://pastebin.com/t1rGbJBB

**Comment by LlmDl** [comment]
You use mysql, you will have to deactivate the feature in your mysql.
