### ISSUE TITLE
Suggestion: Make a PlotGroup's plot easier to move to a different PlotGroup.

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5050]
**Please explain your feature request to the best of your abilities:**
Hello i would like to be able to override a plot group with other. Right now you have to do `/plot group remove` before you can asign a new one, it would be faster if you could just override it. Its a small silly improvement.

**Comment by LlmDl** [comment]
The idea that the single plot would move from one plot group to the other? Not the whole plotgroup being added to the new plotgroup?

**Comment by ElMoha943** [comment]
> The idea that the single plot would move from one plot group to the other? Not the whole plotgroup being added to the new plotgroup?

exactly i think it would save a lot of time, for my case of use at least.

**Comment by gabeeebaby** [comment]
Adding /plot group delete could also be useful to just completely remove a plot group. Right now each plot has to be individually removed.

**Comment by ElMoha943** [comment]
Hello @LlmDl sorry for bumping and old issue, but would it be possible to remove the confirmation when using `/plot group add` in another group? The whole point of this suggestion was to make it easier to transfer a large amount of plots from a group to another. If its not possible, maybe a config option to turn it of or a `-f` parameter in the command or something to ignore the confirmation. Thanx in advance.

**Comment by LlmDl** [comment]
I figured if it was being moved to another group, the mayor would want to know that it's happening, it could probably be enhanced with an -ignorewarn like /t spawn.

**Comment by ElMoha943** [comment]
Yes that would be really useful for my case of use.
