### ISSUE TITLE
Suggestion: /t warp (multiple spawns)

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5056]
**Please explain your feature request to the best of your abilities:**
Could be a `/t warp` command, mayors would be able to set multiple warps with `/t warp set {name}`, and remove them with `/t warp delete`, players can teleport to those warps with `/t warp {name}`. 

In adition, it would be great for mayors to set perms on who can use each warp (residents/allies/enemies or even town ranks like assistant/chief)

**Comment by LlmDl** [comment]
This sort of a thing is already accomplished using `/plot set outpost` and I have not yet seen enough of a justification to essentially duplicate what is already there.

**Comment by ElMoha943** [comment]
Plot warps would be better, you could set more than 1 per townblock, add a custom name to it and as said aboce, customize teleport perms for each individual warp.

**Comment by ElMoha943** [comment]
Also: if you add this feature you should remvoe /plot set outpost. From my point of view outpost should be intended for plots outside the main town. Take it as a overhoul of the current system

**Comment by LlmDl** [comment]
Unlikely I will remove /plot set outpost when the permission node can be removed from teh townyperms.yml.
