### ISSUE TITLE
Towns revert on unclaim despite revert_on_unclaim being false / disabled

### ISSUE THREAD

**Issue by trwnh** [TownyAdvanced/Towny#5057]
### What steps will reproduce the problem?
1. Set `revert_on_unclaim.enabled` to `'false'`
1. Claim a town block or create a new town
1. Break some blocks
1. Unclaim the block or delete your town

### What is the expected output?
1. Chunks do not regenerate or revert.

### What is your Towny version?
Tested with 0.97.0.6 and 0.97.0.10

### What is your spigot/craftbukkit version?
```
This server is running Paper version git-Paper-90 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bb44da8)
You are 1 version(s) behind
Previous version: git-Paper-53 (MC: 1.17)
```

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://gist.github.com/trwnh/c76224095800a8aa631a7eba16544800
2. Your Towny config.yml (if using MySQL please remove password,) : https://gist.github.com/trwnh/8a3f6b06649b3ba72af02c85913b755e
3. Your townyperms.yml : [still the default] https://gist.github.com/trwnh/84c73f26c43ec33220bb7461be6dbe32
4. Your log's error : No error

**Comment by LlmDl** [comment]
The New World Settings section of the config is only default settings for new worlds, it's explained in the config section comments, the install guide and the how towny works page. You need to be using the `/tw toggle revertunclaim` or manually setting the worldname.txt file.
