### ISSUE TITLE
Axolotls / Wolves cannot damage fish or enemies at all when Towny is present on 1.17 server

### ISSUE THREAD

**Issue by SnareChops** [TownyAdvanced/Towny#5059]
### What steps will reproduce the problem?
1. Create a spigot or paper 1.17 or 1.17.1 server
2. Install Towny and Towny Chat (no other plugins)
3. Spawn a squid (in or out of a town)
4. Spawn an axolotl (in or out of a town)
5. Observe that the axolotl does attack, but that the squid does not receive any damage
6. Also observe that tamed wolves will attack enemies, but do not do any damage
7. Also observe no error messages in console
8. Issue is **not** present when Towny is removed from the server (axolotls / wolves can kill mobs again)

### What is the expected output?
1. Wolves should be able to damage enemies or other mobs
2. Axolotls should be able to damage fish and squid

### What is your Towny version?
Confirmed issue exists on:
- 0.97.0.6
- 0.97.0.10

### What is your spigot/craftbukkit version?
Confirmed issue exists on:
- Spigot 1.17 build: 3186
- Paper 1.17 build: 78
- Paper 1.17.1 build: 90
- Paper 1.17.1 build: 96

### Potentially Relevant Configuration Files
[latest.log](https://pastebin.com/Mg1M5UmT)
[config.yml](https://pastebin.com/hgUjxwqt)
[townyperms.yml](https://pastebin.com/Ri8KQXKA)

**Comment by LlmDl** [comment]
I'll need to know how that test build worked for you, so I can either fix it or merge the branch referenced above.

**Comment by SnareChops** [comment]
Confirmed Axolotls can damage other mobs outside of towns
