### ISSUE TITLE
Suggestion: Optional Nation Ally Cap.

### ISSUE THREAD

**Issue by twerk4kanye** [TownyAdvanced/Towny#5064]
**Please explain your feature request to the best of your abilities:**
I was wondering if you'd ever consider the idea of adding a cap to the amount of allies a nation would have in towny, it would give nations more of a reason to be strategic with their allies and to prevent servers from going stagnant and having nations be allied with everyone on the map, it would also encourage more geopol as everyone would have to think more about which allies would benefit them the most.

**Comment by LlmDl** [comment]
I would consider that @twerk4kanye, very cool.
