### ISSUE TITLE
Suggestion: Ability to automatically set 'Ruined' towns to 'private'

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5066]
**Please explain your feature request to the best of your abilities:**
I'd like to see a config option for ruined towns to automatically enable the 'private' setting so players have to work harder to raid them.
(Inverse of issue #4959)

**Comment by Warriorrrr** [comment]
The ruined town's open setting is set to the value of the ruins become public setting, if the ruins become public setting is false (default) ruins will be private.

**Comment by MilesBHuff** [comment]
Oh!  Awesome.  Interesting, okay.
I assumed `false` meant that ruins would use whatever their setting was when they were alive.
Well, cool.  Thanks!
