### ISSUE TITLE
Suggestion: new TownyPermission: Mob-Farming

### ISSUE THREAD

**Issue by lukemango** [TownyAdvanced/Towny#5067]
**Please explain your feature request to the best of your abilities:**
We have a farm option, but our players are asking for a mob-farm option to allow outsiders aswell to kill passive mobs aswell. Players can currently kill hostile mobs in other peoples towns regardless, and understandably not passive mobs, we're asking for a setting on a plot basis, something like **/plot set perm outsider mobfarm on** - allowing them to kill any regardless.

**Comment by LlmDl** [comment]
The way the farm plot is supposed to work, is that players who can destroy in the farm plot, can kill the config's farm_animals in the plot. Try using `/plot set perm outsider destroy on`.

**Comment by itslukemango** [comment]
As much as that might resolve some issues, design of the area then becomes limited as a lot of blocks for decoration (leaves, bee hives) are breakable
