### ISSUE TITLE
Suggestion: Color codes in town/nation tag

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5068]
**Please explain your feature request to the best of your abilities:**
Ability to set custom colors to the town/nation tag (per town*). Maybe it could also be permission based.

**Comment by LlmDl** [comment]
Just a heads up: while this sounds simple its a bit of a nightmare, ie: we have to start formatting this in many places and plugins that use the tags (like TownyChat and other Chat/PAPI plugins,) also have to start formatting it as well.

**Comment by ElMoha943** [comment]
> Just a heads up: while this sounds simple its a bit of a nightmare, ie: we have to start formatting this in many places and plugins that use the tags (like TownyChat and other Chat/PAPI plugins,) also have to start formatting it as well.

what about a command that just adds the color code behind the tag in the variable where its saved? im just guessing tho, i didnt have time to look at the code of how its done. But take your time!

**Comment by ElMoha943** [comment]
As an adition to this i would like a %towny_town_tag_color% if possible 😄

**Comment by dandyjay** [comment]
bump, this would be huge for nation customization and identification
