### ISSUE TITLE
Plot group action bar not showing correctly

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5069]
### What steps will reproduce the problem?
1. create a plot group
2. put it for sale
3. make a player claim it
4. walk in the plots of the group (as in the video below, sorry for it being so quick, github only let me put videos <10mb)

https://user-images.githubusercontent.com/25410859/125381018-94a75e80-e369-11eb-839d-6853bd8d56a1.mp4

### What is the expected output?
It should always show %player_name% - pvp - [group] instead of changing to [not for sale]

### What is your Towny version?
0.97.0.10

### What is your spigot/craftbukkit version?
Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/vu4SfJi4
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/yGKQ1stD
3. Your townyperms.yml : https://pastebin.com/1gFzqDXw
4. Your log's error : N/A

**Comment by LlmDl** [comment]
In the above video is the plot group only the one plot? The plot which is for sale is not part of the plot group?

**Comment by LlmDl** [comment]
I am not able to reproduce this exactly. 

So far I have come the closest by doing the following:

/plot fs 10
/plot group add NAME
/plot claim

But I still always see the [group] when I should.

**Comment by LlmDl** [comment]
Nevermind, I believe I've sorted it out.
