### ISSUE TITLE
Suggestion: Top placeholders

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5073]
**I would like some new placeholders to display the top residents, townblocks and bank money of towns/nations.**

I know there are placeholders for individual values like` %townyadvanced_town_balance%` for money, but i would like something like `%townyadvanced_top_town_balance_{n}%` where {n} would be number in top (1 being the best one).

I struggled a lot with tons of 3rd party plugins to try making this but i just cant, because most plugins are designed for per player values and not whole townys.

EDIT: like the `/t list by` command but in a placeholder format to use in holographic displays, chat messages, etc.

**Comment by Tylwen** [comment]
It would take a % townyadvanced_town_balance_unformated% placeholder where there is no $, just the pure value

**Comment by Romvnly-Gaming** [comment]
Sorry to be that guy that revives dead issues, but I think this needs to be done. It's a good use.


Just a suggestion though, I want to just bring attention to this issue.

**Comment by PuppyNomNom** [comment]
I would also love to see this. <3
