### ISSUE TITLE
Bone Meal Not Working Totally

### ISSUE THREAD

**Issue by LordyZa** [TownyAdvanced/Towny#5086]
### What steps will reproduce the problem?
1.  Use
2. Bone
3. Meal

### What is the expected output?
1. That bone meal works, basically grow crops, grass, moss, etcetera.

### What is your Towny version?
Towny 0.97.0.4

### What is your spigot/craftbukkit version?
git-Purpur-1265 (No spigot version showing with /version sadly)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/ChxEGfpM
2. https://pastebin.com/hTgD0DFB
3. https://pastebin.com/NB80PYua
4. No error apparently showing in console apparetly

Also, I leave a screenshot here
![2021-07-17_22 11 46](https://user-images.githubusercontent.com/81047976/126055297-649e1be9-24ab-41ef-9cb8-468718332013.png)

**Comment by Warriorrrr** [comment]
This has already been fixed, use pre-release 0.97.0.5 or above.
