### ISSUE TITLE
Error When User use the /t list or /t new & loading Error 'channel.yml'

### ISSUE THREAD

**Issue by DMgroupX** [TownyAdvanced/Towny#5087]
### What steps will reproduce the problem?
1. first, when user use the ./t list than server doesn't work. (It just shows form, and the town's name and population do not come out)
2. second, when user use /t new , than server doesn't work. 
3. third, Towny chat form do not appear, only nicknames appear.

### What is the expected output?
1. user can use the command
2. user can make the town
3. 

### What is your Towny version?
Do not say "latest".

0.97.0

### What is your spigot/craftbukkit version?
Do not say "latest".

git-Paper-466 (MC : 1.16.5)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/hfbxURCe
3. Your townyperms.yml : https://pastebin.com/wScQ7cfd
4. Your log's error : https://pastebin.com/d0FKME71

(optional) If this is to do with permissions, 
5. Your permissions file : none

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/Bc8FEmer
7. Your channels.yml : https://pastebin.com/TgziFfNm

**Comment by LlmDl** [comment]
Skipped the startup, skipped the config. Include these files to have the ticket re-opened.

**Comment by DMgroupX** [comment]
add new file.
thank you for notice

**Comment by LlmDl** [comment]
You're out of date: https://github.com/TownyAdvanced/Towny/releases/tag/0.97.0.0

Update and retest.

**Comment by DMgroupX** [comment]
we're using 0.97.0.0 now
Is it old one?

**Comment by LlmDl** [comment]
The startup says you're using 0.96.7.0 https://pastebin.com/uPppw4wq

**Comment by DMgroupX** [comment]
when we use 0.96.7.0, we have the problem.
so we update the towny but the same problem appear again.

**Comment by LlmDl** [comment]
I would like to see the up to date startup log.

**Comment by LlmDl** [comment]
I still also have not seen your config, your link in the ticket goes to a copy of your channels.yml.

**Comment by DMgroupX** [comment]
this is start log for 0.97.0.0 : https://pastebin.com/uDzhG4Bs
and this is config.yml (sorry for that) : https://pastebin.com/NhNrwrxW

**Comment by LlmDl** [comment]
The startup and config both show you're still using Towny 0.96.7.0.
