### ISSUE TITLE
Suggestion:  /t rtp - random teleport to open plots. 

### ISSUE THREAD

**Issue by mzyax** [TownyAdvanced/Towny#5090]
Thank you so much for adding my suggestion #4019. I'm sure this will help towny servers retain new players. 

My new suggestion is something I made a private custom plugin for, but I would much prefer for if it was part of Towny and/or a sponsored plugin so other server owners can use it as well.

- `/t rtp` would teleport a player to a random plot, preferably one that they can afford, in an open town. 
- `/t rtp <player>` would let someone with permission, for example, a mod or admin teleport a specific player to a random towny plot. 
- The `rtp` event  for plugin dev stuff. 

Thank you!

**Comment by 0xBit-MC** [comment]
So if I am getting this right, you want the ability to teleport a player to a random public/open town plot that is for-sale/claimable?

**Comment by LlmDl** [comment]
That is what they're after yes. @mzyax has made a few small plugins to add conveniences to new players on the server. This is the last one that hasn't been added into Towny.

**Comment by LlmDl** [comment]
Things needed to be done to fit into towny:
- needs to use our teleport warmup/cooldown system
- needs to not send a player to a town they're enemied/outlawed in
- needs to follow the TownySettings.getDisallowedTownSpawnZones() config setting 
- probably also needs to charge the player to spawn to the town, if the town has a spawn price

**Comment by LlmDl** [comment]
This has been fulfilled! Details: https://github.com/TownyAdvanced/Towny/wiki/Sponsor-Perks#townyrtp
