### ISSUE TITLE
Suggestion: individual town colors in dynmap

### ISSUE THREAD

**Issue by catsaretheend** [TownyAdvanced/Towny#5093]
**Please explain your feature request to the best of your abilities:**
being able to individually color towns in dynmap.

if in a nation towns could be different shades of a same color?

**Comment by Goosius1** [comment]
- Could you add a mocked up towny-dynmap pls to give an idea of what that the (_towns in a nation with different shades_) version of this might look like?
- If there are  visual issues with that, how about this for an alternative for nations ?
  - Colour the BORDER of the town with the selected nation colour
  - Colour the FILL of the town with the selected town colour
- A second mock-up would also be helpful to see that alternative, because although it might sound good on paper, it would disrupt the existing pattern of strong-border-plus-weak-fill, which might or might not look dodgay.

**Comment by Goosius1** [comment]
FYI if no feasible way is found to combine nation & town colours, here is another option:

Servers must choose between:
- A. Nation colours (as per the feature which exists today), OR
- B. Town colours only (with the border & fill like how the current feature works)

**Comment by LlmDl** [comment]
I like this one:

> - If there are visual issues with that, how about this for an alternative for nations ?
>    - Colour the BORDER of the town with the selected nation colour
>    - Colour the FILL of the town with the selected town colour

**Comment by catsaretheend** [comment]
That is an excellent idea.

to 22. heinäk. 2021 klo 16.47 LlmDl ***@***.***> kirjoitti:

**Comment by catsaretheend** [comment]
That would also work

to 22. heinäk. 2021 klo 16.35 Goosius1 ***@***.***> kirjoitti:

**Comment by Goosius1** [comment]
- We need to figure out which option looks good and suits you Cats
- When you get time, can you do up some mock-ups please, of the two visual options which you like e.g.
  - nation towns different shades of a same color
  - border for nation, fill for town
- When we can visually see these options in a mockup, you can then see if either of them works visually for you.

**Comment by catsaretheend** [comment]
Sure, will do that.

su 25. heinäk. 2021 klo 11.46 Goosius1 ***@***.***> kirjoitti:

**Comment by Caleston** [comment]
This would be a good feature. I've always wondered why nations have /n set mapcolor, but towns didnt have /t set mapcolor, even though the dynmap-Towny config definitely had options to edit town colors as well. +1

**Comment by LlmDl** [comment]
This one is basically done but wont function until Dynmap-Towny 0.87 is released, which will probably happen the same day 0.97.1.0 is released.

**Comment by LlmDl** [comment]
![Capture](https://user-images.githubusercontent.com/879756/127415165-2257606f-e03b-486f-8fb2-4bdc8fd7f1bf.PNG)
blue nation with red, yellow and gold towns

silver nation with darkmagenta, and two other colours I forgot the names of

**Comment by Goosius1** [comment]
That looks good to me.
