### ISSUE TITLE
Deprecated event causing notable performance issue

### ISSUE THREAD

**Issue by morlanius** [TownyAdvanced/Towny#5097]
### What steps will reproduce the problem?
1. Boot server
2. have towny-0.97.0.1.jar installed
3.

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Do not say "latest".
0.97.0.1

### What is your spigot/craftbukkit version?
Do not say "latest".
1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 
Items 1-3 are unnecessary as it is a depreciated method causing performance issues, mainly when making SQL operations.
https://pastebin.com/KnTemW31

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Can you show timings that this is doing anything to your performance? 

Those are just spigot messages telling we are using the methods we deprecated. Update to 0.97.0.14 which has had the FlagWar entirely removed.

**Comment by morlanius** [comment]
Not really, I don't currently have benchmarking tools installed on the remote server, the lag spike is randomly between 1-2 seconds when interacting with the econ. it "feels" like there's a sleep() statement in there somewhere (I'm not saying there is).
I will update now and get let you know.

So no more war?

**Comment by LlmDl** [comment]
If its always before something with your economy, your economy is taking time to respond.

FlagWar is available as a standalone jar now: https://github.com/TownyAdvanced/FlagWar/releases/tag/0.3.0

**Comment by morlanius** [comment]
I see whats happening now, thanks for the info.
