### ISSUE TITLE
Suggestion: Nation outpost /n outpost

### ISSUE THREAD

**Issue by JustAMatt** [TownyAdvanced/Towny#5098]
Allowing nations to create /n outposts similar to town outposts that can be accessed by all nation members.

The number of outposts each nation gets should be configurable under the basic towny settings.

It'd be a great addition to the nation system in towny, and considering most of the backbone is already there it shouldn't be too difficult.

**Comment by LlmDl** [comment]
This might end up being something a town sets on a plot for price. 

Nations don't own land so the outpost would have to go with the town which set it. 

It could also be argued it should be something by the king, otherwise one town could use up the nation's outpost limit.

If it was limited to the king it should be decided whether they lose the outpost if the town leaves the nation.

Alternatively it could be something that can only be set in the capital, but then we have to figure things out when a nation changes its capital.

Definitely a few things to figure out.

**Comment by JustAMatt** [comment]
I think that the best way to go about it is to have the king or co-kings set it on a plot owned by the capital city.

**Comment by 0xBit-MC** [comment]
I think an alternative to this could be allowing towns in a nation to have access to their capital's outposts. Perhaps a configuration item for the user to `/n set outposts public` or `/n set outpost private` to allow toggling for capital privacy and etc.

**Comment by LlmDl** [comment]
One way this could be tackled, and also complete this https://github.com/TownyAdvanced/Towny/issues/4562 ticket, would be to give outposts a system that could open up outposts to various groups, resident, town, nation, ally, outsider.

Then a mayor could choose to open outposts to their nation members or their residents.

**Comment by JustAMatt** [comment]
> One way this could be tackled, and also complete this #4562 ticket, would be to give outposts a system that could open up outposts to various groups, resident, town, nation, ally, outsider.
> 
> Then a mayor could choose to open outposts to their nation members or their residents.

I do like this idea, however, the command to be used by nontown residents would be rather weird wouldn't it? /n outpost would be pretty ideal since it's just /t outpost but with an "n"

**Comment by LlmDl** [comment]
It would end up being the town's outpost in the long run, similar to how public towns allows players to /t spawn [someothertown]. 

/t outpostlist could show if the player has permission to spawn to the town's outpost, and the user would just click from the list.

**Comment by JustAMatt** [comment]
So for example /t Imperial_Town_Generic 5 for someone that wants to visit outpost number 5 from town Imperial_Town_Generic ?

**Comment by LlmDl** [comment]
I believe the command that actually runs when a normal player uses it is /t outpost [number|name]. It would probably be changed to accept /t outpost [number|name] {optionaltownname}.

It would have to be able to take a town argument in there, so it knows which town to use, which is something that can be automated when they use the /t outpostlist command and click the desired outpost.

**Comment by JustAMatt** [comment]
I would honestly like the format mentioned above so it's consistent with the already existing /t spawn. 

Autocomplete for optional town name and a msg similar to "This outpost does not exist for this town, were you trying to use another town's outpost?" would make it pretty simple to work out for new players too.
