### ISSUE TITLE
Jail Database Error

### ISSUE THREAD

**Issue by Firav** [TownyAdvanced/Towny#5115]
### What steps will reproduce the problem?
1. Create a town.
2. Establish a jail plot.
3. Set a jail position.

Error occurs upon `/plot set jail`

### What is the expected output?
1. For a jail to be created within the database.

### What is your Towny version?
0.97.0.9

### What is your spigot/craftbukkit version?
Spigot 3096-Spigot-9fb885e-296df56 1.16.5-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Unable
2. Your Towny config.yml (if using MySQL please remove password,) : [townyconfig.txt](https://github.com/TownyAdvanced/Towny/files/6875173/townyconfig.txt)
3. Your townyperms.yml : [townyperms.txt](https://github.com/TownyAdvanced/Towny/files/6875174/townyperms.txt)
4. Your log's error : https://pastebin.com/pb3eQrfs

**Comment by Warriorrrr** [comment]
Use 0.97.0.10 or above, this was fixed in that version.
