### ISSUE TITLE
Nation issues after #5114

### ISSUE THREAD

**Issue by illumeleet** [TownyAdvanced/Towny#5117]
### What steps will reproduce the problem?
1. Use the /n spawn command
2. or create nation
3. or almost any nation command

Also, nation deletion doesn't work.

![image](https://user-images.githubusercontent.com/51333325/126968805-0991b254-4e3f-446b-a09f-f44e36a1faa8.png)

### What is the expected output?
1. getSpawn works fine
2. nation gets deleted
3. Nation set commands doesn't throw an error

### What is your Towny version?
0.97.0.17

### What is your spigot/craftbukkit version?
1.16.5 git-Purpur-1171

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : generated by towny
3. Your townyperms.yml : generated by towny
4. Your log's error : https://pastebin.com/g9HEA78S

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Can you give it a shot after building off of https://github.com/TownyAdvanced/Towny/commit/32ca74733e835f01c0cae4418874c49fc5da077c ?

**Comment by illumeleet** [comment]
Fixed
