### ISSUE TITLE
Not changing flag in /town here (visual)

### ISSUE THREAD

**Issue by horny-infinity** [TownyAdvanced/Towny#5122]
### What steps will reproduce the problem?
1. using russian language in english.yml
2. turn off any flag for example exlosion
3.

### What is the expected output?
1.for example explosion will be off (ВЫКЛ) in /town here, but they a on(ВКЛ)  
2.
3.

### What is your Towny version?
Towny version: 0.97.0.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-574 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
https://pastebin.com/hpP2sXz8 - english.yml (i think its fine)
https://pastebin.com/zb5dqeSK - config.yml (idk fine too)

**Comment by TheFlagCourier** [comment]
Neither paste is sufficient, as viewing them is restricted.
![image](https://user-images.githubusercontent.com/2712890/127179972-0b695fca-7525-4b02-b21c-4a92934708e2.png)

Just to be on the safe side, confirm that your translation is [YAML compliant](http://www.yamllint.com/).

Also of note: You should _not_ be modifying the english.yml, but making a copy of it to modify instead.

```yaml
# From the file itself...
description: >
    Language file for all game messages.  Do not alter this file.
    If you wish to change any of the entries, make a copy named something else.
    Alternate language files can be enabled by altering the
    [language] entry in config.yml
```

**Comment by LlmDl** [comment]
I need to see the server startup log, the towny config, as is requested.

**Comment by horny-infinity** [comment]
![image](https://user-images.githubusercontent.com/42267170/127327709-c735a63e-25c7-4109-9155-f5afe15d3a30.png)
russian language)))) idk what to do

**Comment by LlmDl** [comment]
https://gist.github.com

**Comment by LlmDl** [comment]
So `/town here` just shows what you would see if you used `/town townname`. It does not show the plot's permissions which are seen using `/plot info`.

**Comment by horny-infinity** [comment]
![image](https://user-images.githubusercontent.com/42267170/127382492-713c8126-47c1-49be-8b79-178c051cf7f7.png)
its says explosions on but they off, its just always on

**Comment by horny-infinity** [comment]
https://gist.github.com/horny-infinity/68844e531f2641b7c1fa7ac07775f4d0 english.yml
https://gist.github.com/horny-infinity/3dd2663a176840a5af2c436976d33217 config.yml

**Comment by LlmDl** [comment]
What does `/tw` show?
