### ISSUE TITLE
/towny top issue

### ISSUE THREAD

**Issue by Garrett119** [TownyAdvanced/Towny#5124]
### What steps will reproduce the problem?
1. Running /towny top <any parameter> (without parameters it properly responds with the usage for the command, but with any of the three parameters - i.e. residents, land, or balance; it throws a "internal error occurred while attempting to perform this command")

### What is the expected output?
1. A List of the top towns per attribute

### What is your Towny version?
0.97.0.16

### What is your spigot/craftbukkit version?
git-Purpur-1265

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[2021-07-28-3.log.gz](https://github.com/TownyAdvanced/Towny/files/6898183/2021-07-28-3.log.gz)
[2021-07-28-2.log.gz](https://github.com/TownyAdvanced/Towny/files/6898184/2021-07-28-2.log.gz)
[latest.log](https://github.com/TownyAdvanced/Towny/files/6898178/latest.log)
2. Your Towny config.yml : https://pastebin.com/WB7eCBSZ
3. Your townyperms.yml : https://pastebin.com/pZ96HArg
4. Your log's error : https://pastebin.com/GR9GDsmE

**Comment by LlmDl** [comment]
Is there any more to the error you linked?

**Comment by LlmDl** [comment]
Just tested and all three subcommands work like they should. Your latest.log doesn't include the startup but it does show me you have errors happening all over the place. Cannons is not happy.

**Comment by Garrett119** [comment]
Yeah cannons is always throwing errors, that’s a whole other problem but it hasn’t crushed server performance and it’s still working so I haven’t done anything about it. I don’t believe cannons has anything to do with the /towny top error. I’ll get you another log when the server restarts on schedule tonight/tomorrow morning to fit the startup and error in one log. There was no more to the error unless it took a solid few minutes to throw

**Comment by Warriorrrr** [comment]
Having the full error caused by using the /towny top command would be useful, linked error log file has the caused by section cut off.
