### ISSUE TITLE
Suggestion: /ta purge with specific town

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5125]
**Please explain your feature request to the best of your abilities:**
I would like the ability to purge only members of an specific town or with/out town.

**Comment by LlmDl** [comment]
You can already purge townless players using `/ta purge [days] townless` to purge townless players who haven't logged in in the given days.

Mayors can use `/t purge [days]` to purge members of their own town.

So the only thing that isn't available is a `/ta purge [days] [town]` command.

**Comment by ElMoha943** [comment]
> You can already purge townless players using `/ta purge [days] townless` to purge townless players who haven't logged in in the given days.
> 
> Mayors can use `/t purge [days]` to purge members of their own town.
> 
> So the only thing that isn't available is a `/ta purge [days] [town]` command.

oh sorry didnt know that, thanx!

**Comment by ElMoha943** [comment]
It would be nice a tab complete for townless bc its missing, also for town names with the new feature.

**Comment by LlmDl** [comment]
> It would be nice a tab complete for townless bc its missing, also for town names with the new feature.

https://github.com/TownyAdvanced/Towny/commit/abed93d48b965c3b255d76b99769c3682dc5ffc3 takes care of the missing townless tabcomplete.
