### ISSUE TITLE
Relational placeholders is bugged

### ISSUE THREAD

**Issue by GreenArrowlol** [TownyAdvanced/Towny#5134]
### What steps will reproduce the problem?
N/A (I don't know dude)

### What is the expected output?
1. Shouldn't give a error for the tab plugin as it isn't tab's fault (I've checked all its config and stuff)
2. Here's the error, [](https://pastebin.com/h8saDcvB) I had the error pop up everytime right after I started using relational placeholders.
2. Fix the issue where it shows the whole %towny advanced town% %towny advanced nation% playername issue (it shows the placeholders used on first join. I've even noticed that it isn't an issue only at my server as a server I know uses relational placeholders and all their reset everyones tabs and tags had the placeholders shown.

### What is your Towny version?
Towny version: 0.97.0.18
The issue occurs in every towny version

### What is your spigot/craftbukkit version?
1.16.5.
Probably gives the same errors at lower versions

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/cA1gFAFu
3. Your townyperms.yml : has nothing to do with perms
4. Your log's error : 
5. Placeholder error: https://pastebin.com/h8saDcvB
(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You're saying that when someone logs in or when the server has just started up the placeholder shows instead of the words/colours that are supposed to be put in place of the placeholder?

ie: You see %townyadvanced_town% instead of "townname".

**Comment by GreenArrowlol** [comment]
Yes, it shows the placeholder on first join, it only starts working when
- a player respawns
- a player rejoins

**Comment by LlmDl** [comment]
Its probably a case of them looking up the placeholder before we've logged the player in.

**Comment by GreenArrowlol** [comment]
Okay
