### ISSUE TITLE
Suggestion: Option to keep basic resident data forever

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#5135]
We delete inactive towns and resident files after a certain amount of weeks in order to free up land. Many players eventually return so it would be nice if basic resident data would be kept forever such as join dates.

**Comment by LlmDl** [comment]
Until the time that we start saving all of their objects as a UUID, it might make sense that deleted residents end up creating a new file: a hibernated resident file keyed to the player UUID with registered date saved. On join we can check if there is a hibernated resident file for the UUID and pull their true join date from that file.
