### ISSUE TITLE
`/t plotgrouplist` pager doesn't work

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5139]
The functionality added in #4431 does not actually seem to work when the town has several pages of plotgroups. 
![image](https://user-images.githubusercontent.com/6566982/127757411-d45d11dc-b3cc-43d0-bdd2-229c6626da91.png)

### What steps will reproduce the problem?
Method one:  `/town plotgrouplist 2`
Method two:  `/town plotgrouplist`, and click on the ">>>" button in chat.

### What is the expected output?
1. See the next page of output.

### What is your Towny version?
0.97.0.19

### What is your spigot/craftbukkit version?
git-Paper-783 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/bPvjYed5
2. Your Towny config.yml (if using MySQL please remove password,) : https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/config.yml
3. Your townyperms.yml  :https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/townyperms.yml
4. Your log's error : (no error)

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/ChatConfig.yml
7. Your channels.yml : https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/Channels.yml

**Comment by LlmDl** [comment]
Ought to be fixed with https://github.com/TownyAdvanced/Towny/commit/9c815925123c6c0b3982e51802f3cadb8c939cd0

**Comment by MilesBHuff** [comment]
Sweet -- thanks!
