### ISSUE TITLE
Blocks not in `switch_ids` still count as switching

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5140]
Outsiders are unable to switch blocks that have been explicitly removed from the `switch_ids` list.  In previous versions (like 0.96.X), these blocks worked.  Now (0.97.0.8 through 0.97.0.19, and possibly earlier) pressure plates, although excluded from `switch_ids`, are still counted as switching.  This is preventing players from accessing areas they used to be able to access.

### What steps will reproduce the problem?
1. Remove pressure plates from `switch_ids`
2. Have an outsider walk onto a pressure plate

### What is the expected output?
1. The pressure plate should actuate

### What is your Towny version?
0.97.0.19

### What is your spigot/craftbukkit version?
git-Paper-783 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/bPvjYed5
2. Your Towny config.yml (if using MySQL please remove password,) : https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/config.yml
3. Your townyperms.yml  :https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/townyperms.yml
4. Your log's error : (no error)

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/ChatConfig.yml
7. Your channels.yml : https://github.com/SettleScape/server/blob/16038dbd0341515b411a62e708b3c59d7884b31e/minecraft/plugins/Towny/settings/Channels.yml

**Comment by LlmDl** [comment]
At a glance I think its that we're checking any physical action (which I think pressure plates count as,) for switching perms:

https://github.com/TownyAdvanced/Towny/blob/9c815925123c6c0b3982e51802f3cadb8c939cd0/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L337

I'll have to test this out and see what strange things happen if this is limited to only switch blocks.
