### ISSUE TITLE
`allowed_map_colors` is not honored

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5143]
`config.yml`:
> `  allowed_map_colors: dark_red:AA0000, red:FF5555, gold:FFAA00, yellow:FFFF55, dark_green:00AA00, green:55FF55, aqua:55FFFF, dark_aqua:00AAAA, dark_blue:0000AA, blue:5555FF, light_purple:FF55FF, dark_purple:AA00AA, white:FFFFFF, gray:AAAAAA, dark_gray:555555, black:000000`

Game:
> ![image](https://user-images.githubusercontent.com/6566982/127759037-49d75301-b30d-4b4b-aeb7-48ba8d39b536.png)

### What steps will reproduce the problem?
1. Configure `allowed_map_colors` to something other than the default
2. Try to use one of your newly-defined map colors

### What is the expected output?
1. `allowed_map_colors` should be honored.

### What is your Towny version?
0.97.0.19

### What is your spigot/craftbukkit version?
git-Paper-783 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/yq4pByT4
2. Your Towny config.yml (if using MySQL please remove password,) : https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/config.yml#L736
3. Your townyperms.yml  :https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/townyperms.yml
4. Your log's error : (no error)

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/ChatConfig.yml
7. Your channels.yml : https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/Channels.yml

**Comment by LlmDl** [comment]
Did you try a full stop and start or just /ta reload config?

**Comment by Warriorrrr** [comment]
There are 2 allowed_map_colors settings, in your config.yml you edited the one for towns instead of the one for nations.

**Comment by MilesBHuff** [comment]
@LlmDl 
> Did you try a full stop and start or just /ta reload config?

Full stop;  I never do `/ta reload config`.

@Warriorrrr 
> There are 2 allowed_map_colors settings, in your config.yml you edited the one for towns instead of the one for nations.

Lol.  Wooww.  Thanks!
