### ISSUE TITLE
Nation fill color set arbitrarily

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5145]
### On my local, Delta seems to have the correct fill:
![image](https://user-images.githubusercontent.com/6566982/127759290-1b934a78-bb13-42c1-8409-f36ceb6e59b4.png)
### However, Ugab has a blue fill now;  it used to have red:
![image](https://user-images.githubusercontent.com/6566982/127759324-5ffc6ac6-5e5f-4ebb-92aa-3f334ef88dd9.png)
### On the server, it's worse.  Here's Delta:
![image](https://user-images.githubusercontent.com/6566982/127759334-9cbf1f1c-4bf5-410b-9b5d-9941218515d3.png)
### And Ugab:
![image](https://user-images.githubusercontent.com/6566982/127759335-c760ecd6-70fc-4d0a-8251-79b5227e27ff.png)
### There doesn't seem to be any way to configure the fill.  In the past, it matched the border set by `/n set mapcolor`.

<hr>

### What is your Towny version?
0.97.0.19

### What is your spigot/craftbukkit version?
git-Paper-783 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/yq4pByT4
2. Your Towny config.yml (if using MySQL please remove password,) : https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/config.yml
3. Your townyperms.yml  :https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/townyperms.yml
4. Your log's error : (no error)

(optional) If this is to do with permissions, 
5. Your permissions file : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/ChatConfig.yml
7. Your channels.yml : https://github.com/SettleScape/server/blob/67e5f0f7fe1863cfb368fcda896347e8937830ce/minecraft/plugins/Towny/settings/Channels.yml

**Comment by LlmDl** [comment]
The town should set /t set mapcolor.
