### ISSUE TITLE
Notifcations not appearing in Action Bar after an update

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#5148]
### What steps will reproduce the problem?
1. Update to 1.17.1 
2.
3.

### What is the expected output?
1. Notifications of plots, wilderness, etc showing up in action bar
2.
3.

### What is your Towny version?
0.97.0.0

### What is your spigot/craftbukkit version?
This server is running Airplane version git-Airplane-61 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 11f0c70 on HEAD)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://bytebin.lucko.me/IV9I2w9Bvy
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Warriorrrr** [comment]
Update to the latest pre-release.
