### ISSUE TITLE
Suggestion: `/ta town NAME claim`

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5149]
It would be nice if admins could `/t claim` as another town.

**Comment by Warriorrrr** [comment]
You can already use /ta set plot townname.

**Comment by MilesBHuff** [comment]
@Warriorrrr Oh!  Cool.  Is there also one for unclaiming?  I can't find one.

**Comment by MilesBHuff** [comment]
@Warriorrrr Is there also one for unclaiming?  I can't find one.
