### ISSUE TITLE
Suggestion: Stable Plots

### ISSUE THREAD

**Issue by roracle** [TownyAdvanced/Towny#5161]
Ability to allow a plot to destroy release a lead from where it's posted. 

The exception of this otherwise "destroy" action is allowing player towns to let visitors ("outsiders") stable a horse. The reason removing a lead shouldn't be considered a destroy action is because the destroy permission suggests those with the perm can destroy anything, lead aside.

The intended method of play is interrupted by this plugin to begin with, but the absolute control from the developer's end allows for fine tuning these things, and this happens to be one of those things.

This could, perhaps, be accomplished using a new plot type called "stable".  Now I'm not knowledgeable at all on how you guys do things, but if it happens that a plot type would help (the aforementioned "stable" plot) will allow for that exception to be done. Perhaps even an option to charge for stabling an animal there.

I hope this helps explain my request. Thank you!

**Comment by LlmDl** [comment]
This is doable with the config's custom townblock type section and putting the `LEAD` in the allowedblocks for the stable plot.
