### ISSUE TITLE
Suggestion: /t set board support of "/" character.

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5166]
i need to put the discord link in one of the towns boards, it wont let me use the "/" character. It should support every character "\ ` ~ | °" etc.

**Comment by LlmDl** [comment]
This is one you can enable yourself, but make sure you test that things are saved correctly before putting it on your live server.

The Config's `string_check_regex` regex is what will determine is allowed in the boards. 

Setting it to 
```
string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}\/]*$
```
should enable you to use `/`, but like I said before: it could potentially make issues saving and loading the boards.

**Comment by ElMoha943** [comment]
I just tested it and it *SEEMS* to work, thanx you!
