### ISSUE TITLE
Plugin Incompatability: ChatSentinel

### ISSUE THREAD

**Issue by Firav** [TownyAdvanced/Towny#5171]
The plugin [ChatSentinel](https://github.com/2lstudios-mc/ChatSentinel) blocks all chat commands from TownyChat. There are no errors or logs that I can trace other than the feedback message from the said plugin. I've [opened a report with the author of said plugin](https://github.com/2lstudios-mc/ChatSentinel/issues/11), and has since[ pushed me to y'all to report the incompatibility](https://github.com/2lstudios-mc/ChatSentinel/issues/11#issuecomment-893162856).

**Comment by LlmDl** [comment]
I'm not entirely sure what they're talking about. 

If I had to guess they're not entirely happy with how TownyChat is able to allow people to speak into channels they're not currently focused on. (ie: you're in general chat but use `/tc somewords` to talk into the town chat for a moment, while not leaving the general channel as your default speaking channel.)

**Comment by LlmDl** [comment]
Having thought this over more: I'm not entirely sure we'd be able to not send chat messages as chat messages, as this would mean any of the plugins that hook into TownyChat's AsyncChatHookEvent wouldn't be able to act on the directedchat messages, and any other chat modifying plugin would also not be able to act on them either. 

If it counts for anything, I don't believe we're running commands twice, the command is being run once then the chat message is being run one.

**Comment by linsaftw** [comment]
When this issue happens it's because a Bukkit command is run with the player as executor inside another command. This is a common issue and has been already reported by many plugins and fixed by their respective developers.

**Comment by LlmDl** [comment]
We're making the player say something from within a command, not run a command. Is this not kosher?

**Comment by linsaftw** [comment]
> We're making the player say something from within a command, not run a command. Is this not kosher?

That will obviously toggle ChatSentinel too.

**Comment by LlmDl** [comment]
If the thing which is triggering the issue here is a person speaking into a directed chat channel they will be using something like `/g some words` which will then make townychat make the player say `some words`. I don't see how this is triggering ChatSentinel.

**Comment by linsaftw** [comment]
> If the thing which is triggering the issue here is a person speaking into a directed chat channel they will be using something like `/g some words` which will then make townychat make the player say `some words`. I don't see how this is triggering ChatSentinel.

Because ChatSentinel listens to both commands and chat for cooldown. The solution would be to instead make channels "persistent" instead of having to specify on each message to speak on global.

**Comment by LlmDl** [comment]
Or maybe ChatSentinel could tell the difference between a command and a chat.

**Comment by linsaftw** [comment]
> Or maybe ChatSentinel could tell the difference between a command and a chat.
> 
> Edit: also, we're not checking on each message if they're speaking in general. The user is likely using the `/g somewords' command in order to speak into a channel which they're not focused on.

Okay i wil see if i can implement this feature in the future.
