### ISSUE TITLE
Towny Duplication 

### ISSUE THREAD

**Issue by CodexApple** [TownyAdvanced/Towny#5173]
### What steps will reproduce the problem?
1. Create a new town within the overworld.
2. Enable Towny World Regenerations
3. Place a chest at the willderness
4. Claim that chest
6. Unclaim the plot
7. Then for some reason regenerations remembers the item placed.

### What is the expected output?
1. Should not be duplicated in any way.
2. Placed items in the wilderness by players should return as air.
3. Overall cancels the event.

### What is your Towny version?
Do not say "latest".
Towny-0.97.0.17

### What is your spigot/craftbukkit version?
Do not say "latest".
1.17.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/C7tHfbvB
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/X3ygJPKS
3. Your townyperms.yml : https://pastebin.com/9W8YArju
4. Your log's error : <No Error>

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Warriorrrr** [comment]
If you don't want blocks to regenerate after being unclaimed, you can add blocks to the block_ignore section of the config, or disable the feature entirely using /tw toggle revertunclaim.
