### ISSUE TITLE
Towns getting randomly deleted (upkeep is all at 0)

### ISSUE THREAD

**Issue by 777Ricky** [TownyAdvanced/Towny#5177]
### What steps will reproduce the problem?
1. Not entirely sure I believe it is happening at reboot as I get reports of it nearly every morning when I wake up
2.
3.

### What is the expected output?
1. Towns get deleted
2.
3.

### What is your Towny version?
Do not say "latest".
Towny-0.97.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot 1.16.5

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://paste.md-5.net/uvukayafah.coffeescript
3. Your townyperms.yml : https://paste.md-5.net/inawoxufin.php
4. Your log's error : https://paste.md-5.net/nusodabode.sql

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by 0xBit-MC** [comment]
I am reading over your error log and I am not seeing any deletion events that seem to be caused my the plugin. Your config file looks correct. Could you reference where you are seeing towns get deleted by the plugin?

In the future, you should take the time to remove your player's IP Addresses from the startup log. I'd be pretty upset if my IP was leaked to the internet by the server I played on.
