### ISSUE TITLE
Suggestion: Option for storing bank money through towny

### ISSUE THREAD

**Issue by xSehrMotiviert** [TownyAdvanced/Towny#5183]
Hi,

I like (and a couple others I know) the idea of having an option in towny, where you can select, if the town/nation economy is stored through the economy plugin or directly in the towny flatfile/mysql database.

It would make things so much easier for me at the moment.

I hope, that this may one day will be a new feature 😄

**Comment by LlmDl** [comment]
Towny will never have the capabilities of an economy plugin, and probably shouldn't as it is outside of the scope of the plugin. While I appreciate your request I have already been roped into maintaining one economy plugin already, I do not wish to be responsible for another.
