### ISSUE TITLE
Suggestion: One-Day-Bankruptcy Grace Period before Ruin Status.

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#5193]
**Please explain your feature request to the best of your abilities:**
This suggestion is to bring some more compatibility to SiegeWar and controlling the meta of the game-play involved with the add-on. This could also be taken as a SiegeWar suggestion depending on how the solution folds out. (So lets tag @Goosius1)

Essentially this feature is a request to enable a "grace period" where a town is registered as reaching its bankruptcy cap (on my server it is -256G), but not being immediately deleted on the first day upkeep comes around but instead being deleted the next day upkeep comes around. Essentially going through upkeep twice instead of once. 

The reason for this is because of the meta of the current game-play style on SiegeWar servers is waiting until the very last possible minute to plunder a town, causing the town to immediately fall into bankruptcy and be thrown into ruin. This becomes incredibly difficult to balance because players are either asleep or unable to gain access at upkeep time. For example, our upkeep time is around 4am PST. 

In my opinion, the immediately dissolution of towns immediately because of a timed plunder isn't fair. Giving the town at least some time to put forward towards their losses is fair. 

I'm not sure how Goosius see's this feature, but at the very least, it would be interesting to have some sort of way to prevent plunder a few hours before upkeep.

**Comment by LlmDl** [comment]
Just playing devil's advocate here, but is there a reason your bankruptcy cap can be reached by plundering so often?
