### ISSUE TITLE
Suggestion: Safe spawns to protect people using public spawns which could be considered traps.

### ISSUE THREAD

**Issue by DiamantesIces** [TownyAdvanced/Towny#5198]
**Please explain your feature request to the best of your abilities:**
This is to prevent spawn-trapping (Eg: make town spawn at Y256 but dig to bedrock so that players who spawn there fall to their death. If we add this feature Instead of spawning at Y256, players will spawn at Y1)

Just a suggestion to make the game more enjoyable! Thanks for your time and thanks if you're adding it!

**Comment by LlmDl** [comment]
This would make every existing install which has any towns with roofs over their spawns, cause the players to begin spawning on their roof.

We might check if there's anything below the spawn point, or you could just put a rule on your server that would disallow this practice.
