### ISSUE TITLE
Suggestion: More Placeholders

### ISSUE THREAD

**Issue by roracle** [TownyAdvanced/Towny#5204]
I'm designing a GUI for Towny in Command Panels, and would like to get placeholders for town and plot toggles and permissions, including residents, town information such as bank balance, etc.

Basically, everything that has a string or integer value. Just to have them available. I'm just getting started on this panel, but with all the Placeholders I would be able to finish this next week at the earliest.

If there are other ways of extracting the data I need, please let me know.

Thank you!

**Comment by LlmDl** [comment]
Making placeholders for everything our API allows for is a bit silly.
