### ISSUE TITLE
Suggestion: add line in lang "en-US.yml"

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5217]
**Please explain your feature request to the best of your abilities:**
Add the ability to customize these lines when entering the command /t [town_name]:
![image](https://user-images.githubusercontent.com/73141732/130385751-1c6b12d1-a019-43ee-a636-8acee600703b.png)

**Comment by LlmDl** [comment]
res_format_list_1
res_format_list_2
res_format_list_3

Are the three translation lines that are used to format those ranks.

**Comment by 1Pootis1** [comment]
> res_format_list_1
> res_format_list_2
> res_format_list_3
> 
> Are the three translation lines that are used to format those ranks.

So it only changes the color, and not the word itself, for example, "Assistant"
![image](https://user-images.githubusercontent.com/73141732/130466246-6eb248fa-d823-42b7-b8d0-5c766ac390dc.png)

**Comment by LlmDl** [comment]
It uses the names of your townyperms.yml's ranks...

**Comment by 1Pootis1** [comment]
aa...
can you make their names in other languages, for example, in Russian?

**Comment by LlmDl** [comment]
I would expect you can use russian characters.

Note that you cannot change: nomad, default, mayor, king.
