### ISSUE TITLE
Bug report towny. 

### ISSUE THREAD

**Issue by Kiogra** [TownyAdvanced/Towny#5219]
### What steps will reproduce the problem?
1. I create a city
2. I invite a person
3. An error arrives which says that the guest is not allowed to enter the city

### What is the expected output?
1. I create a city
2. I invite a person
3. The person enters and helps in the city

### What is your Towny version?
Do not say "latest". Towny-0.97.0.0

### What is your spigot/craftbukkit version?
Do not say "latest". Papermc#209

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/J5FdWaqw
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/XgSFRB8N
3. Your townyperms.yml : https://pastebin.com/TBxbxdPc
4. Your log's error : https://pastebin.com/vMT25E15

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Looks like all you have to do is remove the plugin WorldChat.
