### ISSUE TITLE
Players can lure animals/mobs in other plots

### ISSUE THREAD

**Issue by aco4** [TownyAdvanced/Towny#5222]
### What steps will reproduce the problem?
1. Spawn an cow/axolotl in your town
2. Have an outsider try to lure it with wheat/a tropical fish in a bucket, respectively
3. It will follow the outsider

### What is the expected output?
1. The animal/mob will not follow the outsider

### What is your Towny version?
0.97.1.3

### What is your spigot/craftbukkit version?
1.17

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/ZVtGFzGF
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/38puBe5W
3. Your townyperms.yml : https://pastebin.com/sgQUMuZT
4. Your log's error : no error

**Comment by LlmDl** [comment]
Ok, so I've gone over the code and figured out how it's being handled currently.

Tempting animals is only stopped when:

- the animal is not in the wilderness.
- the animal is in a personally-owned plot in a town (owned by a resident personally, not just owned by a town.)
- the tempter is able to break dirt where the animal is.

The reason for the 2nd point is that if town-owned plots were restricted, no resident would be able to lure an animal through the town to their personally-owned plot, to be stored/bred.

A solution to your issue would be to store those animals in personally-owned plots in your town.

**Comment by aco4** [comment]
> the tempter is able to break dirt where the animal is.

You mean "the tempter is _not_ able to break dirt where the animal is"?

**Comment by LlmDl** [comment]
Correct, that was a typo.
