### ISSUE TITLE
Suggestion: Ability to see "Glow" effect on town members

### ISSUE THREAD

**Issue by Martajnez** [TownyAdvanced/Towny#5241]
Allowing players to toggle visibility of Glow effect on players from the same town to improve team coordination.

e.g
![image](https://user-images.githubusercontent.com/64419373/131229389-7a7e5e27-a109-4827-bafd-6ff8efc27756.png)

**Comment by GNosii** [comment]
This can be done using the TownyAPI, but I don't see an good reasoning as to why it should be implemented into Towny directly.

**Comment by LlmDl** [comment]
I recently looked into doing special glowing stuff for SiegeWar and I am not a big fan. 

It requires using more libraries which are version dependent to Minecraft's version. 

A server that wants to have glowing can probably find a plugin that will adopt Towny support like @GNosii said. If any plugin author wants help adding Towny support to their glow plugin I'm more than happy to help them use the Towny API on our Discord.
