### ISSUE TITLE
[Towny]: Driver error: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver

### ISSUE THREAD

**Issue by Aritex1** [TownyAdvanced/Towny#5245]
Towny startup log: https://pastebin.com/A6riLzxc
Version: 0.97.1.4
First started after updating to 0.97.1.3 and persists to 0.97.1.4
This does not affect usage as Towny is still logging to MySQL.

**Comment by LlmDl** [comment]
What details can you provide about your mysql server?

**Comment by Aritex1** [comment]
Let me know if theres any exact info you need,

Using HeidiSQL v11.3.0.6295 libmysql.dll library
Hosted on same machine the MC server runs on
