### ISSUE TITLE
Unable to deposit money in the bank

### ISSUE THREAD

**Issue by ChiyodaXiaoYi** [TownyAdvanced/Towny#5250]
### What steps will reproduce the problem?
1. Use the command /towny:t deposit 100
2. The bank balance is still 0

### What is the expected output?
Increase in the balance of the town

### What is your Towny version?
0.97.1.4
(0.97.1.0 also has this bug)

### What is your spigot/craftbukkit version?
Spigot 1.17.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/0NMXg8QG
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/DhqCVC5B
3. Your townyperms.yml : https://pastebin.com/xG6fTjAB
4. Your log's error : no error

**Comment by LlmDl** [comment]
```
[10:42:18] [Server thread/INFO]: [Towny] Plugins found: 
[10:42:18] [Server thread/INFO]: [Towny]   Permissions: TownyPerms, LuckPerms 5.3.47 via Vault
[10:42:18] [Server thread/INFO]: [Towny]   Economy: SunLight-Economy via Vault
[10:42:18] [Server thread/INFO]: [Towny]   Add-ons: TownyChat v0.89, LuckPerms v5.3.47
```

It is either because Sunlight doesn't support the older Vault methods, or because your Sunlight is erroring during your startup.
