### ISSUE TITLE
You can break some protected blocks in wilderness

### ISSUE THREAD

**Issue by MykeUhu** [TownyAdvanced/Towny#5251]
Problem:
It looks like you can destroy or place some of the new designed blocks in wilderness. 
Place torches on fence, destroy torches on fence, you can use your tools to get ore´s
look like minecraft has renamed or redesigned some block, blockID´s

Sorry for bad englisch. (i try my best, but prefer german)
you can call me @discord MykeUhu#7419

### What steps will reproduce the problem?
1. use minecraft 1.17.1
2. go to a block and try to destroy or place it
3.

### What is the expected output?
1. nothing, you can just do it
2.
3.

### What is your Towny version?
Do not say "latest".
0.97.1.4

### What is your spigot/craftbukkit version?
This server is running Paper version git-Paper-84 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5059ada)
You are 147 version(s) behind.
(nitrado, the newest you can install )

try to update:
This server is running Paper version git-Paper-231 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f99119e)
You are running the latest version
Previous version: git-Paper-84 (MC: 1.17.1)
nothing changes

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/UsYmpLCv^

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/MH76JHcf

3. Your townyperms.yml :
https://pastebin.com/8FDsCcnT

4. Your log's error : 
there is no error

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your towny\data\worlds\WORLDNAME.txt files each have a list of blocks in it which are ignored/allowed to be used in the wilderness protections.

The config defaults to 
```
unclaimed_zone_ignore: SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LEAVES,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,LOG_2,VINE,NETHER_WARTS,COCOA
``` which is used to populate your world files when you install towny.
