### ISSUE TITLE
Suggestion: New placeholders

### ISSUE THREAD

**Issue by JonatanLaMerce** [TownyAdvanced/Towny#5255]
Hi all, is there any way or placeholder to count the players that are inside a nation or city, without the need for the player to be inside the nation or city?

it would be helpful for server administrators to be able to show the number of residents in each nation or city without the need for the player to be inside the nation/city.

Something similar to %townyadvanced_town_residents_amount% and %townyadvanced_nation_residents_amount% but without the need for the player to be inside the nation or city.

thanks!

**Comment by LlmDl** [comment]
`%townyadvanced_nation_residents_amount%`
`%townyadvanced_town_residents_amount%`
Already exist.
