### ISSUE TITLE
Players are able to make town adjacent to each other even if I set the min distance to 5 (chunks)

### ISSUE THREAD

**Issue by DiamantesIces** [TownyAdvanced/Towny#5260]
### What steps will reproduce the problem?
1. Player A creates town A (no nation)
2. Player B creates new town B (no nation) in the chunk adjacent to towny A's homeblock

### What is the expected output?
1. Player B cannot create a new town less than 5 chunks from town A's claim

### What is your Towny version?
0.97.1.4

### What is your spigot/craftbukkit version?
Paper 1.16.5

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/ixzp1N6N
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/qUQXz15F
3. Your townyperms.yml : https://pastebin.com/zrzdC8CE
4. Your log's error : https://pastebin.com/tGAVLtrD
5. Image: https://pasteboard.co/KiGid2a.png

**Comment by LlmDl** [comment]
I am unable to reproduce this, even when using your config. Any guesses?

**Comment by DiamantesIces** [comment]
I deleted all plugins (jar and directories, including Towny 0.97.1.4), installed 0.97.1.5 and found these through testing :

1) When `min_distances_ignored_for_towns_in_same_nation: 'false'`
+ If town A is made, town B can be made adjacent to A, regardless if A is in a nation or not
+ Both towns can claim close to each other, regardless if none, one or both of them is in a nation

2) When `min_distances_ignored_for_towns_in_same_nation: 'true'`
+ Towns cannot be made adjacent, or claim close to each other, even if they're in the same nation (Which is just what I want, but I don't know if this is intended)

But when I set to `'false'` again, this time it works like 2) which is really weird
If the problem maybe the fact that the mayors are all NPCs, I can try to get a friend to test with me on the server

**Comment by LlmDl** [comment]
Odd, I think I tested that, as it was the only thing different from my config and yours. I will test again.

**Comment by LlmDl** [comment]
So I had a browse through the code to see where this could be happening.

I found that upon town creation, the min_distance_ignored_for_town_in_same_nation is completely ignored (because the town doesn't exist yet, and it also could not possibly have a nation yet either.)

It does test distances between the rest of the towns and their townblocks, on town creation.
