### ISSUE TITLE
Suggestion: New options in the configuration

### ISSUE THREAD

**Issue by JonatanLaMerce** [TownyAdvanced/Towny#5274]
Good morning, would it be possible an option in the configuration to deactivate the confirmation messages, the messages of city creation or any other message? 

i attach a messages examples. 
![2021-09-10 16_56_01-Minecraft 1 16 5 - Multijugador (servidor de terceros)](https://user-images.githubusercontent.com/16003674/132874002-eed7e910-3abe-4704-b81d-d6f86909452e.png)

Thank you very much!

**Comment by LlmDl** [comment]
We added that message because many Towns were not paying attention to their bank and were deleted on the next new day. 

Is there an argument as to why you would not want your mayors to be warned about this once?

**Comment by JonatanLaMerce** [comment]
Hello and thank you for replying,
A good reason to implement the option to be able to decide which messages are shown to the player, would be to improve the user experience by creating automatic servers.

In my case, we are developing a server in which the creation of cities is automatic, and the player can choose what kind of city and what size he wants, and visually, for the player experience would be not to fill the screen with messages. I don't know if I'm the only one but at the level of server creators it would be a very good implementation to automate the cities.

Thank you very much!

**Comment by LlmDl** [comment]
And you're doing this by making the player run a command instead of using the API to make them a town?

**Comment by JonatanLaMerce** [comment]
Thats because i don't have a lot of experience programming,  and i'm making It with denizen
