### ISSUE TITLE
The Create mod "Deployer" can't build within Towny protected area

### ISSUE THREAD

**Issue by Abwasserrohr** [TownyAdvanced/Towny#5288]
Hello there,

I'm opening this issue for remotehorst23. I wrote on the Discord about the issue and LlmDl found the reason that probably results in this issue. I write more details about it below.

### What steps will reproduce the problem?
1. Install [Create mod](https://www.curseforge.com/minecraft/mc-mods/create), [Mohist](https://mohistmc.com/) and Towny.
2. Try to let a "Deployer" build a block.

### What is the expected output?
1. The "Deployer" should be able to build a block if it is in the `fake_residents` list.
I [contacted you guys on Discord](https://discord.com/channels/321452088519426058/581163022874050569/888118516870438953), LlmDl wrote that it's probably because the fake residents list is only checked on `getResident(String)`, but not on `getResident(UUID)`. I can't really reference where the problem is, I only found is that it is probably here where the error output happens: https://github.com/TownyAdvanced/Towny/blob/cde220207e6f95fd675b73c9d03786de68b4c468/src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java#L292

### What is your Towny version?
v0.97.1.0

### What is your spigot/craftbukkit version?
Mohist version 1.16.5-775 (MC: 1.16.5), Forge version 36.2.4
Mohist is used to get the Create mod running with Towny.

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log: https://pastebin.com/raw/G1ADECUP (We tried some fast debugging using Skript and skript-mirror to see if we could get it fixed without setting up a new plugin)
2. Your Towny config.yml: https://pastebin.com/raw/WShvhzSS
3. Your townyperms.yml: https://pastebin.com/raw/pdBwqJ3F
4. Your log's error: `[Towny] Failed to fetch resident: Deployer`

**Comment by LlmDl** [comment]
I made something for you to test: https://cdn.discordapp.com/attachments/581163022874050569/888138153586729010/Towny-0.97.1.10.jar

Even with it getting teh resident in the playercacheutil, it is unlikely that Deployer will be able to do anything, unless it was made to return a TownBlockStatus.ADMIN, which would then mean anyone could grief with the deployer.

**Comment by Abwasserrohr** [comment]
Thank you for the test version.

The error `[Towny] Failed to fetch resident: Deployer` is now no longer happening.
I see the problem that anyone could grief with the deployer and I don't really think Towny needs to have compatibility with all the mods. We tried to use `com.palmergames.bukkit.towny.event.actions.TownyBuildEvent` again with the new version, but it is sadly still not triggered for the fake player, there are no errors in the log.

**Comment by LlmDl** [comment]
Checking things over, it should still fire an event, I would like to see your listener.

**Comment by Abwasserrohr** [comment]
I changed up my listener and waiting for remotehorst23 to respond with the results, if the `TownyBuildEvent` is still not fired, I will send everything I have.

**Comment by Abwasserrohr** [comment]
Sorry for not responding, have not heard back from remotehorst23.😅
