### ISSUE TITLE
Suggestion: Enhancements to Town Ruining

### ISSUE THREAD

**Issue by BlueFyreMatt** [TownyAdvanced/Towny#5305]
I have a variety of features I'd love to be added to Townys ruining system, some may be duplicates of feature requests that already exist so I apologise if thats the case, but let me know and I'll edit them out of the request!

Customizable permissions when towns get ruined - Currently towny enables all permissions so players are free to do anything, preferably this would be customizable at the same level that you can customise current town permissions (Such as enabling/disabling use, place, destroy, interact for residents, nations, allies etc)

Ability to enable/disable explosions in ruined towns

Ability to whitelist or blacklist specific items from being used, placed or destroyed within ruined towns (For example letting people mine ore blocks, but still protecting the structures within the ruins)

Ability for separate reclaim times for the mayors, assistants and residents, with whoever issuing the reclaim command becoming the town mayor and the former mayor becoming a town assistant

Ability for reclaim times to be disabled entirely, allowing a town to be reclaimed as soon as it falls

A grace period where if you reclaim a town within x amount of time, you get a discounted reclaim price

A towns reclaim price is adjustable depending on the predicted value of the town (Plots owned, residents etc) and a toggleable multiplier for each additional day the town has been ruined

**Comment by LlmDl** [comment]
This is a good pile of work.

**Comment by LlmDl** [comment]
A lot of what you want is just a town without (slightly less protections.)

The idea behind ruining a town (and having a min. reclaim time) is that it prevents someone deleting their town (to get out of a war,) and then reclaiming their town right away. This is why it requires some time to pass before it can be reclaimed. This is why things can be destroyed. Mayors are not supposed to want their towns to go into ruin.

**Comment by BlueFyreMatt** [comment]
Understood, however I run a server with both Siegewars and a Casual towny, the casual server has war disabled and has 9k residents, 353 towns and 47 nations, and I'm currently having an issue with players on our casual server blowing up ruined towns because TNT gets enabled and there's no system in place to disable block damage in a ruined town, as it enables everything, and it also doesn't regenerate the land, so a player who goes on holiday for say, 3 weeks, is at risk of coming back to a town thats been blown up and looted in its entirety. 

Is there any way you could at least add a config option to enable the block regeneration from entity explosions in ruined towns? It'd save myself and my mods a lot of time having to enforce it as a rule and it means ruined towns would actually look more ruined rather than them looking like craters across the world. I'd appreciate anything you can do!

**Comment by LlmDl** [comment]
Does your casual server have bankruptcy disabled? Why is a town dying in just 3 weeks?

**Comment by BlueFyreMatt** [comment]
Where it states "Ruins can optionally be preserved from build/destroy actions.", how customisable is this? As in, can I configure it to protect the ruins from build/destroy but still allow item-use and container access? And prevent block damage through explosions etc?
