### ISSUE TITLE
Suggestion: Permission-based invite restrictions

### ISSUE THREAD

**Issue by BunkerSlav** [TownyAdvanced/Towny#5306]
I'd like to be able to restrict people from joining towns who have mayors in different permission groups.

Let's say for example I have a permission called "race.human" and a permission called "race.orc". 
I would like to prevent "race.orc" players from joining towns that have a mayor who has the "race.human" permission and vice versa. 

If it could also perform a simple check to kick them when using any towny command if their permission has changed, that would be great too.

I imagine it simply as a list in the config. 

"GroupRestrictionPermissions:
-race.human
-race.ork
-race.elf"

And then whatever permission you add to the group will exclude players who have these permissions from joining towns of players with different permissions also on the list.
All other permissions will be ignored and if there is no permission on the list it is disabled.

As for when a player has no permissions on the list, I would either like it to force them to get a permission from that list to join any town.

**Comment by LlmDl** [comment]
This is something that should be a separate plugin from Towny, using the events Towny throws for joining towns.

If/when a player changed their race it would kick the player.

**Comment by BunkerSlav** [comment]
Hmm... To be fair, in retrospect I should've suggested it on the Towny Cultures repo as it might fit with the whole cultures theme of that one. But point taken, I'll make my own.

**Comment by LlmDl** [comment]
Have you got a race plugin you already use?

**Comment by BunkerSlav** [comment]
Nope, using Skript as we discussed in your Discord. Gonna close this issue now, then. Thanks anyways.
