### ISSUE TITLE
Suggestion: Add sync between servers

### ISSUE THREAD

**Issue by zReport02** [TownyAdvanced/Towny#5333]
**Please explain your feature request to the best of your abilities:**
Hi, it would be very nice if it were possible to **synchronize data between multiple servers**!
Maybe through redis or similar!

**Comment by LlmDl** [comment]
Hi, this is something I plan on doing when I have enough sponsors that I can dedicate the time it takes to transform Towny into something that can operate over multiple servers. Thanks for requesting it.
