### ISSUE TITLE
Locale don't exist defaut settings PAPI

### ISSUE THREAD

**Issue by almazoff-paste** [TownyAdvanced/Towny#5370]
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java

Please add this strings to locale-config, this is necessary to set default text if town or nation or other is empty!!!
![изображение](https://user-images.githubusercontent.com/88402370/137520152-840aca72-7a27-4915-9657-2d72327dd2fe.png)

**Comment by GNosii** [comment]
This is already part of the codebase. 
https://github.com/TownyAdvanced/Towny/blob/ea246c8e6f899ab303cdfce8a5c3c25540746365/src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java#L153-L162
Pretty sure this issue can be closed.

**Comment by Warriorrrr** [comment]
I think the thing they're asking is to make the default values configurable in the language files, instead of just empty strings.
