### ISSUE TITLE
Potential Edge-Case with JSON.Simple, potentially affecting `MojangAPI`, `BukkitTools`, and `GatherResidentUUIDTask`

### ISSUE THREAD

**Issue by TheFlagCourier** [TownyAdvanced/Towny#5375]
> Traditional bug report form skipped due to: a) I am not entirely sure how to reliably test this specific issue due to potential interference with the player cache; b) The issue was discovered while tweaking the pom file; c) It's way too early in the morning (4am 💀)

### Summary
I may have found a previously undocumented edge-case issue with the `GatherResidentUUIDTask`. Debated on if I should have added this wall of text to <https://github.com/TownyAdvanced/Towny/issues/4611>, or made a new issue...

The only things keeping the whole chain working seem to be the VaultAPI dependency, since it directly bundles a copy of Bukkit 1.13.1 which in turn provides the needed dependency, and the Player Cache. 

### Replicating Issue

The issue is noticeable during the build process. By adding the following to the pom.xml, in the VaultAPI dependency declaration, and attempting a clean compile - the build will error-out due to missing the dependency.

```xml
<exclusions>
  <exclusion>
    <groupId>org.bukkit</groupId>
    <artifactId>bukkit</artifactId>
  </exclusion>
</exclusions>
```

I have not been able to test in-game yet (see disclaimer 'C' above). Theoretically though, if someone *doesn't* have Vault (eg. Reserve users) or something else providing JSON.Simple, and the UUID isn't already stored in the player cache, a failure should occur. At runtime, I suspect that this may be causing a `MojangException` to be thrown, which may have helped mask the issue as an "HTTP 204 error" or passed it as `null` which would have resulted in an infinitely reattempted task chain.

### Methods Under Effect

- `BukkitTools#getUUIDFromResident(Resident)`
- `MojangAPI#send(String)`

### Possible Solutions

- Shade in a copy of JSON.Simple
  - Use the [original version](https://github.com/fangyidong/json-simple) (_mostly died out circa 2012_):
  ```xml
  <dependency>
    <groupId>com.googlecode.json-simple</groupId>
    <artifactId>json-simple</artifactId>
    <version>1.1.1</version>
    <scope>compile</scope>
  </dependency>
  ```
  - or, the [cliftonlabs fork](https://github.com/cliftonlabs/json-simple) (Not compatible, partial re-write required!)

- Switch to [GSON](https://github.com/google/gson) (Provided by Bukkit; in "[Maintenance Mode](https://github.com/google/gson/issues/1821)")

- Use an entirely different JSON serializer, like [Jackson](https://github.com/FasterXML/jackson) or [Moshi](https://github.com/square/moshi)

**Comment by Warriorrrr** [comment]
Made a commit that potentially fixes this (3b9652661d36244c3edd532a43256314242728a8) by switching it to gson, haven't tested it on a server yet.
