### ISSUE TITLE
Discord hook Event error

### ISSUE THREAD

**Issue by NeotenySS** [TownyAdvanced/Towny#5413]
### What steps will reproduce the problem?
1. Install DiscordSRV and use alerts.yml
2. write to alerts.yml trigger about AcceptAlly
3. Nation1 send ally to Nation2 and this accept ally

### What is the expected output?
1. Fix issue with NationAcceptAllyRequestEvent.java
Example:
NationDenyAllyRequestEvent.java works without error when a nation deny to ally another nation

### What is your Towny version?
0.97.2.0.

### What is your spigot/craftbukkit version?
spigot 1.16.5.

### Please use Pastebin.com to link the following files:
https://pastebin.com/hPJtMRBb

(optional) If this is to do with permissions, 
5. Your permissions file : doesn't have (only townyperms)

(optional) If this is to do with chat,
6. Your chatconfig.yml : default
7. Your channels.yml : default

Towny, TownyChat, SiegeWar default options and other plugins doesn't install because um use server for testing.

P.S.: I think that the problem is not related to DiscordSRV, as it perfectly captures the rest of the events in the plugin, however, I found the problem in this event, and strangely enough, the code is open, although the plugin swears that it may be closed.

**Comment by Warriorrrr** [comment]
The NationRequestAllyNationEvent class does not have a senderNation field, you will need to get the sender from the invite field and then cast it to a nation.

**Comment by NeotenySS** [comment]
"does not have a senderNation field"

Look: NationRequestAllyNationEvent

line 16	public NationAcceptAllyRequestEvent(Nation senderNation, Nation receiverNation) {
line 17		this.senderNation = senderNation;
line 18		this.receiverNation = receiverNation;

Have sender, how i can fix it, if trigger can hook 1 event, plugin can't hook both event simultaneously

**Comment by Warriorrrr** [comment]
Yes, the NationAcceptAllyRequestEvent does have that field, but NationRequestAllyNationEvent (the one in the error message) doesn't.

**Comment by NeotenySS** [comment]
Oh, yeah. I mixed up the events when I wrote, but the link with the error is correct, the event is written there NationAcceptAllyRequestEvent

**Comment by Warriorrrr** [comment]
senderNation is a private field, you need to use the getSenderNation() method.

**Comment by NeotenySS** [comment]
Problem solved, thanks for your help!
We solved this issue very quickly!
But I'm shocked, I also use the NationDenyAllyRequestEvent event and specify the "senderNation" values ​​there too (it's private), but it works: D
I do not know exactly what it may be connected with, there is too much code to study from you)
