### ISSUE TITLE
Spam to console

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5427]
### What steps will reproduce the problem?
1. enable the language in the game settings for "pre-reform-Russian"
2 .observe spam in the console <<[Towny] Could not convert 'rpr' into a locale, falling back to en_US.>>

### What is your Towny version?
Towny 0.97.2.0

### What is your spigot/craftbukkit version?
paper-1.17.1-359

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[latest.log](https://github.com/TownyAdvanced/Towny/files/7492634/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/2wSVHJL4
3. Your townyperms.yml : https://pastebin.com/Lye72hKv
4. Your log's error :  [Towny] Could not convert 'rpr' into a locale, falling back to en_US.
![image](https://user-images.githubusercontent.com/73141732/140652989-970a5154-98b0-43fa-ada8-16c4120085c0.png)

I added the rpr.yml file to the languages folder, but it didn't solve my problem

![image](https://user-images.githubusercontent.com/73141732/140653164-35aa9753-d98b-491c-b536-fddd4a8d65eb.png)

**Comment by LlmDl** [comment]
This was fixed in the pre-releases. It is due to Mojang having a couple of "made up" locales. Putting a rpr.yml into your reference folder doesn't do anything, it would have to go into the override folder (which might still not work.

**Comment by 1Pootis1** [comment]
Thank you, we are expecting a new full-fledged release, otherwise it's scary to put pre-releases :)

**Comment by LlmDl** [comment]
I expect things too.
