### ISSUE TITLE
Suggestion: Restore blocks of wilderness

### ISSUE THREAD

**Issue by w15736776759** [TownyAdvanced/Towny#5443]
**Please explain your feature request to the best of your abilities:**
I believe this will contribute to the beauty of the world's terrain and the inexhaustible resources

**Comment by LlmDl** [comment]
Towny can already keep your world beautiful by keeping players from harvesting in the wilderness, and by reverting unclaimed land back to their pre-claimed state. You should consider a resource world for players to gather resources from.

Re-populating a world with resources is outside of the scope of Towny.
