### ISSUE TITLE
Terrain noting regenerating with Revert on Block Explosion

### ISSUE THREAD

**Issue by BakProject** [TownyAdvanced/Towny#5445]
### What steps will reproduce the problem?
1.  wild_revert_on_mob/block_explosion under the 'entities' adding RespawnAnchor, RESPAWN_ANCHOR, or Respawn_Anchor

### What is the expected output?
1. The terrain will regenerate just as TNTPrimed

### What is your Towny version?
version: 0.96.7.0
Do not say "latest".

### What is your spigot/craftbukkit version?
Paper Version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/t9mBjzTZ
3. Your townyperms.yml : https://pastebin.com/kwX5YmUD
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
RESPAWN_ANCHORS and BEDS are considered block explosions and not entity explosions. Use `/tw toggle revertblockexpl` to toggle their regeneration.

**Comment by BakProject** [comment]
I have run this command and the terrain is still not regenerating back. I have made sure this command is ENABLED.

**Comment by LlmDl** [comment]
Show me a screenshot of `/tw` and include your towny\data\worlds\WORLDNAME.txt file.

**Comment by BakProject** [comment]
![2021-11-14_19 41 24](https://user-images.githubusercontent.com/34917462/141709427-c8429a12-9f12-4599-b8dc-8beb43ebdbed.png)


towny\data\worlds\WORLDNAME.txt file : https://pastebin.com/Q4VDHZ7X

**Comment by LlmDl** [comment]
your world's PlotManagementWildRegenBlocks is missing the respawn_anchor.

**Comment by BakProject** [comment]
I would change this in the actual file correct? If so thank you for re-visiting this for me.

**Comment by LlmDl** [comment]
You must add it in each world you want to have it regenerate. Respawn Anchors only blow up in the nether as far as I understand.

**Comment by BakProject** [comment]
It has been fixed. Thank you again for re-visiting this issue for me.
