### ISSUE TITLE
Not working with WorldEdit / FAWE and WorldGuard

### ISSUE THREAD

**Issue by ConaII** [TownyAdvanced/Towny#5449]
### Server Implementation

Purpur (git-Purpur-1171)

### Server Version

1.16.5 (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Describe the bug

Using FAWE or WorldEdit, WorldGuard and Towny breaks protection.
I have not tested WorldGuard 1.17
I have tested:
 - Towny-0.97.2.0 (Latest release)
 - towny-0.97.2.17 (Pre-release)
 - towny-0.97.2.18 (Latest pre-release)

### To Reproduce

1. Install FAWE or WorldEdit, any version.
2. Install WorldGuard
3. Install Towny (Towny-worldguard does not fix this, any version)
4. Join the server, create a region and protect it, put some props like ITEM_FRAMES, PAINTING, ARMOR_STAND, and I don't know more.
5. Do /rg bypass and try breaking them, it will break even it says that you can't.
(PD: You need to bypass towny wild protection too, for example giving permission towny.*)

### Expected behaviour

well, not breaking things that it shouldn't

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
  - I found nothing in the logs.
  - https://pastebin.com/4haUiUQD
2. Your Towny config.yml (if using MySQL please remove password,) :
  - Default one and customized do the same.
  - https://pastebin.com/A3MZP6Ce

3. Your townyperms.yml :
  - Again, I tested the default config and the customized config, they don't cause this.
  - https://pastebin.com/pjZdH72Z
4. Your log's error : 
  - no errors.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by ConaII** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1414

**Comment by LlmDl** [comment]
>  it will break even it says that you can't.

Can you show a screenshot of this?

**Comment by ConaII** [comment]
Fine, i will try to record it

**Comment by LlmDl** [comment]
[Image shown in discord](https://cdn.discordapp.com/attachments/581163022874050569/909627934686449724/unknown.png) shows this is not a Towny denial message. Towny is allowing this to happen as you say you give Towny wilderness-use in your test. Another plugin is likely trying to cancel the action but not succeeding, but still shows its message.
