### ISSUE TITLE
TownyChat not putting players in the right channel on request

### ISSUE THREAD

**Issue by skw359** [TownyAdvanced/Towny#5451]
### What steps will reproduce the problem?
1. Go into a channel (/lc, /g)
2. You will stay into the previous channel before you typed in the requested channel. This happens randomly, so I am unsure what exactly will trigger this problem, but I know it's also player-specific
For example, if I were in general chat (/g) and switched to local (/lc), my chat will still send in general unless I request /lc again or chat in the local command `/lc hello this is a test!`
It can be seen here: 
![image](https://user-images.githubusercontent.com/75508453/141890381-eaac37d8-7774-4623-9d14-293efec92616.png)
Console: https://pastebin.com/BMSx4ZxD

### What is the expected output?
To put the player into the right chat upon request

### What is your Towny version?
Towny Version: 0.97.2.18

### What is your spigot/craftbukkit version?
This server is running Purpur version git-Purpur-1427 (MC: 1.17.1)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/p6McFd2a
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/yuaBLH34
3. Your townyperms.yml : https://pastebin.com/s2m2x2DC
4. Your log's error : None

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/8XBnRzC6
7. Your channels.yml : https://pastebin.com/wKuL0eWs

**Comment by LlmDl** [comment]
From the discord:
```
@Wizz I'm lookin at your townychat ticket and I cannot reproduce it myself. I tested using your channels.yml, and immediately got an error when speaking into the general channel, because you have a blank/empty channeltag.

it did not affect the ability to have your bug happen though

If you could get someone who this happens to, to do the following:
1. use /tc (and have them receive teh "you are now talking in townchat" message)
2. use /res toggle bop and get a screenshot of what towny outputs. (It should be something like [Towny] modes set: town,bop)

I suspect that the mode is being added, but when they talk next they have either lost the mode, or they cannot use that channel, and townychat is putting them into a global type channel.
```

**Comment by skw359** [comment]
It just happened to me - 
![image](https://user-images.githubusercontent.com/75508453/142561161-5e0166e7-2dad-4748-95f9-aa04e63ff5a4.png)
My messages were being sent in general chat, however, and I toggled on/off but it did not make a difference where my messages were being sent 

For reference, on a normal test server, `/res toggle bop` allows for /tc and normal usage of chats upon request

**Comment by skw359** [comment]
Here's when it affected the player: 
![image](https://user-images.githubusercontent.com/75508453/142705959-791d3fd7-e896-4a8d-9b8d-dd8ba79013d4.png)
