### ISSUE TITLE
Suggestion: [TownyHistories] Page List Numbers

### ISSUE THREAD

**Issue by Litning11** [TownyAdvanced/Towny#5467]
Similar to `/t list` , `/ruin list` should show the amount of pages at the bottom.

![image](https://user-images.githubusercontent.com/82062096/143248719-b26438ea-47d3-4532-aea4-75dda26b0aa7.png)

![image](https://user-images.githubusercontent.com/82062096/143248873-6e71334d-b5ac-4a35-b46d-76e6dc880fed.png)

Like in the first screenshot you can see "<<< Page x of X >>>", add that to the bottom of the second screenshot.

**Comment by LlmDl** [comment]
Closed in TownyHistories 0.0.14.
