### ISSUE TITLE
Towny causing 100% RAM usage

### ISSUE THREAD

**Issue by ThorinEk** [TownyAdvanced/Towny#5473]
Hello!

I have identified Towny to be the cause of 100% RAM usage on my server through disabling every plugin. The server works and players can join without Towny, but with Towny, it crashes on startup and closes down again. The problem occurred with Towny 0.97.2.0 and I have since updated to 0.97.3.0 but with no success. I am using TheNewEconomy and have not made any changes to the server or any plugins the weeks prior to the first occurrence of the issue. As seen in in logs error below, an exception in Towny happens for task 9.

Thanks in advance for any assistance.

### What steps will reproduce the problem?
1. Start the server
2.
3.

### What is the expected output?
1. Not full 100% RAM usage
2.
3.

### What is your Towny version?
0.97.3.0

### What is your spigot/craftbukkit version?
git-Paper-388

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/bnhrMJXw

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/EYe3eaCA

3. Your townyperms.yml :
https://pastebin.com/PQVhWx2P

4. Your log's error : 
https://pastebin.com/ThN18gnz

**Comment by LlmDl** [comment]
I only see Fe in your startup, not TheNewEconomy. Does it work without an economy plugin installed?

**Comment by ThorinEk** [comment]
My apologies, I have been changing plugins back and fourth trying to find a solution and chose the wrong startup log.
I have now tried running the server with Towny and no economy plugin, the problem still exists. I believe that I have now managed to get a more useful error message which shows an error with Towny Chat.
Here is the new startup log: 
https://pastebin.com/eGaeVXsa

**Comment by Warriorrrr** [comment]
What are your startup flags? If your xms and xmx flags are set to the same value then it's expected your server will use all of that all the time.

**Comment by LlmDl** [comment]
> 

TownyChat is only throwing an error because Towny is disabled.

**Comment by ThorinEk** [comment]
My hosting company support resolved the issue and gave me the following quote: 

> I checked the server out while it was running and on the current world it would timeout within about 2 minutes, I changed the world temporarily to see if this still occurred.

When changing the world I noticed that Towny reported that the world could not be found to regenerate chunks to their previous state.

I've disabled towny's chunk regen, changed to the original world, and restarted the server.

The thread death and errors no longer occur, however if Towny does encounter a lot of towns/chunks to regen it will cause issues again.
> 

Perhaps this is possible to fix so that Towny does not cause 100% RAM usage and crashes when trying to regenerate chunks, cheers!

**Comment by LlmDl** [comment]
Can you maybe explain more about the "Towny reported that the world could not be found" and "changed to the original world" means here?

**Comment by ThorinEk** [comment]
I have requested an elaboration of those quotes from the one who wrote them. I will get back to you if I get any response.

**Comment by ThorinEk** [comment]
Hello, here comes an explanation which I have received:

> You had set Towny to regen chunks based on if the town disbanded or not, during this time a lot of chunks had been scheduled to regenerate. There is a "regen.txt" file in the towny data folder that handles all these chunks, there wasn't an error per se with Towny on this so much as there was a large accumulation of chunks that were trying to regen all at once from what I understood. When switching the world, as you don't have multiverse-core or another plugin to load multiple at once, it couldn't find the world "world" (as it was not loaded) which showed all the chunks that needed to be regenerated and lead me to that conclusion. Deleting the contents of regen.txt fixed the previous issue, contacting the towny author you may want to double check with them if they run the regen.txt list one by one, all at once, or if you can change how it operates.

Hopefully this brings some clarity to the issue. Maybe it is possible to opitimize so that a large amount of chunks scheduled for regeneration does not crash the server?

**Comment by LlmDl** [comment]
I'll look into this. I'm not sure about their comment about the worlds not being loaded all the time, that might be true.

I did notice you have your revert_on_unclaim speed set to 4s instead of 1s. This means that your plots are taking 4x as long as they would normally to complete their revert. This could also be why you have so many incomplete regenerations.

**Comment by ThorinEk** [comment]
Very nice to see you have made a patch for this! The reason I set revert_on_unclaim speed to 4s was that I thought slower reverting could maybe cause less lag, but I will try to change it back to 1s then.
Thanks!
