### ISSUE TITLE
Suggestion: Complex/Json for TownyChat

### ISSUE THREAD

**Issue by winnipeg21** [TownyAdvanced/Towny#5479]
### **Please explain your feature request to the best of your abilities:**

Imagine townychat with complex formatting like kingdoms. That way we can have hover and click actions per text/placeholder. Make things more modern as the kids say

**Comment by LlmDl** [comment]
This is difficult to accomplish and still use Bukkit's native chat events (which makes us compatible with many other chat plugins. Something like this would probably end up being a completely new plugin which would not be as compatible with other chat plugins.

**Comment by Warriorrrr** [comment]
Can start being implemented once #5672 is merged, we'll have to split TownyChat up into a legacy bukkit side and a modern paper side, or just make it paper only.

**Comment by LlmDl** [comment]
Alternatively https://github.com/LaBoulangerie/TownyChatRemake is probably able to do most of what you'd like.

**Comment by winnipeg21** [comment]
It lacks a few features but nonetheless still useful. I do agree with Wariorrrr there about having two seperate townychats (if need be). Sorry for the late response just got the notification lmao
