### ISSUE TITLE
Plot names are not parsing the colors or format

### ISSUE THREAD

**Issue by ehetteNandaYo** [TownyAdvanced/Towny#5481]
### What steps will reproduce the problem?

Sometime in the past /plot set name &aColor would color the plot name or take the format
now it doesnt for some reason, but it works if the player title prefix has colors it works but only if there is no plot name set.

![image](https://user-images.githubusercontent.com/62739770/143998476-dca36d55-cc2a-4710-90cb-28644f008d4f.png)

### What is the expected output?

Format the text

### Towny version

0.97.3.2

### Server version

1.17.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: Not needed
2. Your Towny config.yml: default
3. Your townyperms.yml: default
4. Your log's error: no error

**Comment by LlmDl** [comment]
How's 0.97.3.2 working for you otherwise? It's not been released yet.

**Comment by LlmDl** [comment]
Closed by https://github.com/TownyAdvanced/Towny/commit/16fafb0b0d12dcb809d8de425505359b18d72cbf

**Comment by ehetteNandaYo** [comment]
> How's 0.97.3.2 working for you otherwise? It's not been released yet.

The only thing I have noticed is that /nation nameofnation doesnt work

**Comment by LlmDl** [comment]
thats been fixed in a coming PR
