### ISSUE TITLE
towny wont create a town or deposit 

### ISSUE THREAD

**Issue by Chucky891** [TownyAdvanced/Towny#5499]
### What steps will reproduce the problem?

1. wont let new people who join the server  create a town 
2.  wont let you deposit money to towny bank 
3.  

### What is the expected output?

normal you can use either /t new and /t create to make a town 
narmally you can /t deposit  1000 aand lets u add money 

### Towny version

[12:09:20 INFO]: [Towny] Towny Version: 0.97.5.0
[12:09:20 INFO]: [Towny] You are up to date.

### Server version

.[12:08:46 INFO]: This server is running Paper version git-Paper-32 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 77ff1f3)
You are running the latest version
Previous version: git-Paper-25 (MC: 1.18)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:     https://pastebin.com/R9K63UCG
2. Your Towny config.yml:  https://pastebin.com/9ymU5yLm
3. Your townyperms.yml:  https://pastebin.com/9CdxeZwn
4. Your log's error: not sure where to get this sorry completely new message me on  disocrd BarbieKiller#7883 

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
EconomyPlus has an incomplete Vault implementation:

https://github.com/ItsWagPvP/EconomyPlus/blob/ac08a9245feefb2e6384b9a710c77481c8ccec1a/src/main/java/me/itswagpvp/economyplus/vault/VEconomy.java#L305-L308

This returns false every time Towny tries to make a town or nation account.
