### ISSUE TITLE
Common treasury for cities

### ISSUE THREAD

**Issue by StonFlip** [TownyAdvanced/Towny#5501]
### What steps will reproduce the problem?

I don't know, the problem always appears on its own and at different times.

### What is the expected output?

Cities have a general balance and can spend it.  Sorry for the typos, I use google translate and it can make mistakes.

### Towny version

Towny-0.97.5.0

### Server version

1.16.5 Paper

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/CWSsMZc8
2. Your Towny config.yml: https://pastebin.com/dKq1fvHK
3. Your townyperms.yml: https://pastebin.com/gWfxA86z
4. Your log's error:  No error, please see screenshot: https://imgur.com/a/ASMECvV

(optional) If this is to do with permissions,
5. Your permissions file: 

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
I think you are describing towns sharing a bank account. 

I have seen this happen when towns are named with Unicode characters, that your economy plugin cannot interpret, so all four-character long towns share the same account, all 5 character long towns share an account. 

This is not an issue in Towny. You can prevent Towny allowing unicode characters in town and nation names by following the Regex instructions on the How Towny Works wikipage.
