### ISSUE TITLE
[TownyHistories] Suggestion: decay after set period

### ISSUE THREAD

**Issue by BirbEXE** [TownyAdvanced/Towny#5510]
### **Please explain your feature request to the best of your abilities:**

Hey, 
I wanted to suggest that you could set towns to decay after a certain amount of time,
so that it leaves the town for a set period, maybe a week or two, before it'll turn off build blocking
and slowly start to decay.

also, it'd be nice if there was a config option where certain groups of people could
access build perms for the town after it was disabled, like old town members, allies, or nation members

thanks!
~ birb.

**Comment by LlmDl** [comment]
This is sort of how the Towny ruining feature works. 

1. Town is "deleted" for non-payment of upkeep or `/t delete` and becomes a ruin for a period of time.
2. Town ruining period passes and the town is actually deleted.
3. If your revert-on-unclaim setting is true, then it starts to revert.

**Comment by BirbEXE** [comment]
> This is sort of how the Towny ruining feature works. 
> 
> 1. Town is "deleted" for non-payment of upkeep or `/t delete` and becomes a ruin for a period of time.
> 2. Town ruining period passes and the town is actually deleted.
> 3. If your revert-on-unclaim setting is true, then it starts to revert.

Ah, thanks for the clarification.
I need to look into ruin settings more
