### ISSUE TITLE
Suggestion: Wilderness Decay

### ISSUE THREAD

**Issue by BirbEXE** [TownyAdvanced/Towny#5511]
### **Please explain your feature request to the best of your abilities:**

heya, this suggestion is a little far-fetched due to resource limitations, but a feature that could decay builds in the wilderness
would be nice.
I want players to be able to build and break in the wilderness, but I don't want the terrain to be destroyed.
I do understand that it might be hard to implement, and you'd have to add a config option for a block to replace mined ores

this feature also might cause some performance issues, so if it gets added, it should be
disabled by default.

thanks for reading my waffle, and thanks for your time!
~ birb.

**Comment by LlmDl** [comment]
This is actually already doable via https://www.spigotmc.org/resources/problockregen-regen-blocks-plants-and-crops.101632/
