### ISSUE TITLE
Suggestion: TownyAdmin Rename does not cost.

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/Towny#5513]
### **Please explain your feature request to the best of your abilities:**

Greetings,

This suggestion is to prevent economic costs for TownyAdmin commands such as but not limited to:
```
- /townyadmin town <town> set name <new-name>
- /townyadmin nation <nation> set name <new-nation>
```

Currently as of 0.97.3.0, running these commands require an admin to join the town, deposit gold into the bank to change names. This can become quiet difficult given the amount of times the task has to be repeated for each town that is getting their named changed.

Thanks,
0xBit

**Comment by LlmDl** [comment]
There already exists /ta town NAME rename NEWNAME and /ta nation NAME rename NEWNAME commands which aren't charged for.
