### ISSUE TITLE
Suggestion: Option to show what nation you're entering when you enter a town

### ISSUE THREAD

**Issue by WafflesAreBetterMinecraft** [TownyAdvanced/Towny#5524]
### **Please explain your feature request to the best of your abilities:**

My server uses the nations part of the plugin more than the towns, because there are only a few governments on the server and each of them can have as many towns as they want under one main ruler. 

I'd like there to be an option to show which nation you're entering and not just the town, in case players don't know what nation the town they're entering is a part of. This is important because different countries on the server have different laws, so depending on where you are, there's different rules you have to follow.

This would make the plugin more customizable and more informative, so I hope it's added! The plugin has been really helpful so far.

**Comment by noisereactz1** [comment]
goooood idea.

**Comment by AlessioGr** [comment]
Added it with https://github.com/TownyAdvanced/Towny/pull/5530 😄

**Comment by LlmDl** [comment]
I believe they are requesting the option for the using_titles section of the config to accept a {nationname} placeholder like it does with {townname}, it does not have anything to do with the invites, although that is also nice looking.

**Comment by AlessioGr** [comment]
> I believe they are requesting the option for the using_titles section of the config to accept a {nationname} placeholder like it does with {townname}, it does not have anything to do with the invites, although that is also nice looking.

Ohhh I see, I thought with "entering a town" they meant entering via an invite - oops! Lemme try to add that to my PR as well

**Comment by AlessioGr** [comment]
https://github.com/TownyAdvanced/Towny/pull/5534
Now that should do it:
![image](https://user-images.githubusercontent.com/70709113/146109659-f25598d1-38df-4ca7-96d4-5cdf31765427.png)
Shows in the title via the `{nationname}` placeholder.

**Comment by LlmDl** [comment]
I did make this possible in 0.98.4.0.
