### ISSUE TITLE
Villager deletion issue when converting into a zombie villager

### ISSUE THREAD

**Issue by nurdism** [TownyAdvanced/Towny#5541]
### What steps will reproduce the problem?

1. Create a town
2. Turn mob spawning in the town OFF
3. Spawn a villager
4. Nametag the villager
5. Bring a nametagged zombie/husk into the town to zombify the villager (Use Hard difficulty for 100% zombification chance)
6. See the zombie villager disappear

This is the same issue #5226

### What is the expected output?

Since the villager was nametagged, the zombie villager retains that nametag and therefore should not despawn.

### Towny version

0.97.5.0

### Server version

paper-1.18.1-79

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml: https://pastebin.com/1sYTYHM0
3. Your townyperms.yml: https://pastebin.com/8BF30tQK
4. Your log's error: n/a (no errors)

**Comment by LlmDl** [comment]
When the zombievillager is spawned it likely has no name tag on it. I'll investigate.

**Comment by LlmDl** [comment]
I am unable to reproduce this. The zombie villager spawns with the nametag and does not disappear.

**Comment by nurdism** [comment]
After some debugging, it seems another plugin is causing the nametag to not carry when the villager converts.
