### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to TownyChat v0.9

### ISSUE THREAD

**Issue by Guildedcraft** [TownyAdvanced/Towny#5551]
### What steps will reproduce the problem?

1. Start server
2. Speak in chat
3. View server console

### What is the expected output?

Expected output is no error after a player chats in game.

### Towny version

Towny 0.97.2.0, TownyChat 0.90

### Server version

papermc 1.17.1 b295

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/DX1UYWfk
2. Your Towny config.yml: https://pastebin.com/Z9q6cVCi
3. Your townyperms.yml: https://pastebin.com/cw8TS38B
4. Your log's error: https://pastebin.com/6am3gL5b

(optional) If this is to do with permissions,
5. Your permissions file: N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/DPjRdtGM
7. Your channels.yml: https://pastebin.com/nAGU8pN5

I know there are many plugins that are out of date or not current versions but this error has been plaguing us since 1.15, and occurs even when _all_ plugins are up to date. I'm basically at a loss trying to fix it.

**Comment by LlmDl** [comment]
It could be helpful to see more of what preceded the error in your log. 

Your Towny is out of date. You should update to 0.97.5.0 and retest.

**Comment by Guildedcraft** [comment]
Updated to most recent (0.97.5.0 and 0.91) of both towny and townychat, error persists. Nothing follows the error, it can happen as soon as startup as long as someone chats in global chat. This doesn't seem happen in any other chat channel. 
Pastebin of full server log after updating with the error at the bottom: https://pastebin.com/6HyFEJpw

**Comment by LlmDl** [comment]
If I had to guess, some other plugin is making the message null. Your new long still doesn't show what message was sent.

**Comment by Guildedcraft** [comment]
Yes it does. the message always comes through _after_ the error itself. In this case, the message that was sent is at the very bottom of the log.
`[20:07:50] [Async Chat Thread - #0/INFO]: [Staff World][Admin] ~Nate: error test`

**Comment by LlmDl** [comment]
Your channels.yml, you removed the global channeltag.

**Comment by LlmDl** [comment]
Closed by https://github.com/TownyAdvanced/TownyChat/commit/27f46966a60c0be4b90d763267c9d98ac7465a5e
