### ISSUE TITLE
HikariCP has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by GNosii** [TownyAdvanced/Towny#5555]
### What steps will reproduce the problem?

1. Follow the steps from [Converting flatfile to SQL](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#converting-flatfile-to-sql).
2. Restart your server
3. You will be met with this error.

### What is the expected output?

Towny starts.

### Towny version

Originally found in 0.97.5.1 
Reproduced in 0.97.5.3 (latest prerelease)

### Server version

Airplane git-Airplane-12 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://gist.github.com/GNosii/db4bee750ac4a52416483e0c05f558cf#file-latest-log
2. Your Towny config.yml: https://gist.github.com/GNosii/db4bee750ac4a52416483e0c05f558cf#file-config-yml
3. Your townyperms.yml: https://gist.github.com/GNosii/db4bee750ac4a52416483e0c05f558cf#file-townyperms-yml
4. Your log's error: https://gist.github.com/GNosii/db4bee750ac4a52416483e0c05f558cf#file-error-log
5. database.yml (localhost): https://gist.github.com/GNosii/db4bee750ac4a52416483e0c05f558cf#file-database-yml

**Comment by LlmDl** [comment]
This might be a good reason to include hikari via the plugin.yml.

**Comment by GNosii** [comment]
Seems like this doesn’t happen anymore.
