### ISSUE TITLE
Config values converted to `!!org.bukkit.configuration.MemorySection`

### ISSUE THREAD

**Issue by benlmyers** [TownyAdvanced/Towny#5559]
### What steps will reproduce the problem?

1. Delete Towny directory, Towny-x.x.x.x.jar, TownyChat-x.x.x.x.jar from Plugins folder
2. Add Towny-0.97.5.0.jar and TownyChat-0.97.5.0.jar to Plugins folder
3. Run server.
4. The default config files generated have `!!org.bukkit.configuration.MemorySection {}` for most properties. This applies to all the `.yml` files inside the settings directory, except for `channels.yml`.

### What is the expected output?

I am expecting to see the normal default configuration files, as detailed in [the wiki](https://github.com/TownyAdvanced/Towny/wiki/Config-Files).

I have tried using both the release and pre-release versions of Towny; deleting the Towny folder inside Plugins; copying/pasting the contents of the default config files from the wiki to their respective files on the server; using Towny.jar without TownyChat.jar.

### Towny version

0.97.5.0 (latest release)
Also tested on 0.97.5.3 (latest pre-release) with the same results.

### Server version

CraftBukkit version 3372-Spigot-8965a50-c59b0ca (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/rxj7b8LU
2. Your Towny config.yml: https://pastebin.com/SxFSBpEQ
3. Your townyperms.yml: https://pastebin.com/4520xHUW
4. Your log's error: https://pastebin.com/qJSvUqcE

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/qgVfZuWF
7. Your channels.yml: https://pastebin.com/VjJnkW2x

I appreciate your work!

**Comment by LlmDl** [comment]
You need to change out your craftbukkit jar for a spigot or papermc jar: https://papermc.io/downloads

Thanks for sponsoring me this morning, I really appreciate it. If you hop into the Discord I can give you the sponsor role.

**Comment by LlmDl** [comment]
Apparently something is not working with Spigot jars, paper jars are not having this issue.

**Comment by LlmDl** [comment]
There has been a ticket filed with Spigot: https://hub.spigotmc.org/jira/browse/SPIGOT-6865
