### ISSUE TITLE
Your townyperms.yml's towns section is missing the default group. Maybe you renamed it?

### ISSUE THREAD

**Issue by SwedishTurtles** [TownyAdvanced/Towny#5561]
### What steps will reproduce the problem?

1. The server that is experiencing the problem restarted
2. The server turned back on normally
3. Towny was locked into safe mode due to the error.

### What is the expected output?

A normal startup

### Towny version

0.97.5.3

### Server version

Spigot 1.18.1

### Please use Pastebin.com to link the following files

https://pastebin.com/CQuARxHL

**Comment by LlmDl** [comment]
Attach your townyperms.yml

**Comment by SwedishTurtles** [comment]
https://www.mediafire.com/file/1a1mnofarfp6jb0/townyperms.yml/file

**Comment by LlmDl** [comment]
Your townyperms.yml doesn't look it is made with Towny 0.97.5.3. File a new ticket and don't skip the form.
