### ISSUE TITLE
Your townyperms.yml's towns section is missing the default group. Maybe you renamed it?

### ISSUE THREAD

**Issue by SwedishTurtles** [TownyAdvanced/Towny#5562]
### What steps will reproduce the problem?

The server that is experiencing the problem restarted
The server turned back on normally
Towny was locked into safe mode due to the error.

### What is the expected output?

A normal startup

### Towny version

0.97.5.3

### Server version

Spigot 1.18.1

### Please use Pastebin.com to link the following files

https://pastebin.com/CQuARxHL
(I already submitted an issue but didn't add a link to townyperms.yml, this one does have it.)

**Comment by LlmDl** [comment]
Skipped the form again.
