### ISSUE TITLE
Default group in Townyperms.yml is missing

### ISSUE THREAD

**Issue by SwedishTurtles** [TownyAdvanced/Towny#5563]
### What steps will reproduce the problem?

The server that is experiencing the problem restarted
The server turned back on normally
Towny was locked into safe mode due to the error.

### What is the expected output?

Towny to work correctly

### Towny version

0.97.5.3

### Server version

Spigot 1.18.1

### Please use Pastebin.com to link the following files

This is the third issue I have submitted and on the last one, you said I skipped the form for a second time. As far as I know, I didn't skip anything and I have no clue what you are talking about. Here is the pastebin link:
https://pastebin.com/CQuARxHL

**Comment by LlmDl** [comment]
You skipped it again. I want to see your server startup, config, townyperms.yml. I won't lock this one if you can supply the files the form asks for.

**Comment by SwedishTurtles** [comment]
Somehow the issue fixed itself, server is back to normal.

**Comment by gerardvanschip** [comment]
Im having the exact same issue both with 0.97.5.3 and 0.97.5.5
I can fix it by removing the Townyperms.yml file, then start the server again which creates a new version of the file, when I restart again I need to remove the file again. Basically I need to remove the file between each restart.

**Comment by LlmDl** [comment]
Cutting edge spigot builds are mucking things up, @gerardvanschip switch to paper or hang tight for 0.97.5.6 out later today.

**Comment by gerardvanschip** [comment]
Thought something like that, no worries. Super pleased that Towny so far is running smoothly as butter.
