### ISSUE TITLE
Suggestion: Denylist or permission that prevents invites & outlaw.

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#5568]
### **Please explain your feature request to the best of your abilities:**

This suggestion is simply to create a feature that can be granted to a staff rank that prevents that user from receiving town invites or being added to outlaws, friends and etc. It will simply just prevent the event from happening saying "You can't (invite, outlaw or friend) that user."

**Comment by LlmDl** [comment]
I think the way I'll go about handling this is to make a permission node under towny.admin, like towny.admin.staffmode.

A staff member who has that permission node will be able to use /res toggle staff, which end enabled will suppress various ,messages. It could also be used for solving https://github.com/TownyAdvanced/Towny/issues/3939, making admin overrides of protections require the staff mode, if we can get that working alongside the caching.
