### ISSUE TITLE
Nation vs Nation

### ISSUE THREAD

**Issue by AllieDragon** [TownyAdvanced/Towny#5571]
### What steps will reproduce the problem?

1. Started a nation vs nation war through admin commands
2. It said that the war could not be started, this may be helpful: 
3. Failed to get the correct number of teams for war to happen!
4. This happened even though I had two separate nations both online with the correct amount of people for my config trying to go to war with one another.

### What is the expected output?

I expected for the nations to be able to go to war with one another

### Towny version

Towny - 0.97.5.4
EventWar - 0.0.15

### Server version

1.18.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/FLEwCHEn
2. Your Towny config.yml: https://pastebin.com/pepq7V8V
3. Your townyperms.yml: https://pastebin.com/kCVpZuWX
4. Your log's error:  https://pastebin.com/jvYwn595
5. My eventwar config https://pastebin.com/iV1r9th9

**Comment by LlmDl** [comment]
Do both nations consider each other enemies?

**Comment by AllieDragon** [comment]
Yea that was the issue
