### ISSUE TITLE
Nation vs Nation war not ending

### ISSUE THREAD

**Issue by AllieDragon** [TownyAdvanced/Towny#5576]
### What steps will reproduce the problem?

1. Started nation vs nation war
2. Killed the leader four times to take over nation
3. Enemy nation was destroyed and remaining town went into my nation
4. The war didn't end however.

### What is the expected output?

The expected output was for the war to end

### Towny version

Towny - 0.97.5.6
EventWar - 0.0.16

### Server version

1.18.1

### Please use Pastebin.com to link the following files

[latest.log](https://github.com/TownyAdvanced/Towny/files/7783335/latest.log)
If you look towards the end you can see the error in the console after the last kill.

**Comment by LlmDl** [comment]
This is fixed in 0.0.16, but I feel that the nation vs nation war end book isn't able to report the correct information when a nation has been conquered and removed. When you see a nation vs nation war end, please get a copy of one of the war end books and if it isn't quite right, let me know.
