### ISSUE TITLE
Citizens NPC problem or CrazyEnchantment or Towny? I don't know.

### ISSUE THREAD

**Issue by svdermant** [TownyAdvanced/Towny#5577]
### What steps will reproduce the problem?

Hello Guys nice to meet you. I have an issue with the latest dev build of CrazyEnchantments from Jenkins also here: https://jenkins.badbones69.com/job/Crazy-Enchantments/lastBuild/ - I just don't know if it's a CrazyEnchantments problem or a Citizens, Sentinel or Towny problem. I don't get smart from the error message. The following problem: I created an NPC using /npc name --trait sentinel He is also set as follows so that he attacks monsters within a radius of 30 blocks. This NPC has equipment that is Enchanted. Well, if I accidentally hit this one, the following message - Now I don't know how to fix this or who to contact is this Now a Citizens Problem or Towny or Sentinel or CrazyEnchantment? How can I fix this?. Greets from Germany.

To Solve this i must downgrade to the Towny Version 0.96.2.0

I have already notified the developer of CrazyEnchantments but have not received a response to it to date. Maybe you can do something there.

I have already asked about this in a German forum and I was told I could also ask the towny developers.

### What is the expected output?

I see this Message When i hit the NPC with Enchanted Armor or so.
 Here: https://pastebin.com/By1Wg2mw

### Towny version

The descripted Error occurs when i using this Version of Towny https://github.com/TownyAdvanced/Towny/releases/tag/0.97.5.6

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-792 (MC: 1.16.5)

### Please use Pastebin.com to link the following files

I have only the latest Server log from the start which the error occurs so send it here
https://pastebin.com/sEpHwDxg

No TownyConfigs was edited by me

**Comment by LlmDl** [comment]
CrazyEnchantments needs to update their Towny support.

**Comment by svdermant** [comment]
Thank you i report this to the dev on his Discord server
