### ISSUE TITLE
Database issues upon town rename

### ISSUE THREAD

**Issue by Firav** [TownyAdvanced/Towny#5600]
### What steps will reproduce the problem?

1. Rename town multiple times
2. Restart server
3. Bork town

### What is the expected output?

All townblocks to be updated correctly in database.

### Towny version

0.97.2.10

### Server version

git-Paper-792 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files

No applicable errors pertaining to this issue.

**Comment by LlmDl** [comment]
The solution applied is a bit of a bandaid, but the switch over to using town UUIDs throughout most of the database is coming in the 0.98.*.* series, so this wont be an issue for very long.
