### ISSUE TITLE
TownyHistories dynmap comment says "Camps" instead of "ruins"

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5609]
### What steps will reproduce the problem?

```
    # When set to true, and dynmap is found on the server, Camps will appear on the dynmap.
    enable_dynmap_support: 'true'
```

### What is the expected output?

```
    # When set to true, and dynmap is found on the server, ruins will appear on the dynmap.
    enable_dynmap_support: 'true'
```

### Towny version

Unrelated to Towny.

### Server version

Unrelated to server.

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: Does not require starting server.
2. Your Towny config.yml: Not related to this file.
3. Your townyperms.yml: Not related to this file.
4. Your log's error: Does not require starting server.

(optional) If this is to do with permissions,
5. Your permissions file: Not related to this file.

(optional) If this is to do with chat,
6. Your chatconfig.yml: Not related to this file.
7. Your channels.yml: Not related to this file.

**Comment by LlmDl** [comment]
already fixed
