### ISSUE TITLE
Suggestion: trust list of towns for admins  /t trust list 

### ISSUE THREAD

**Issue by Chucky891** [TownyAdvanced/Towny#5615]
### **Please explain your feature request to the best of your abilities:**

a place to see who trust who in towns in case anything happens and admin and just in general as well as players to check in which towns they were trusted and if some griefs the town they trust in the admin can untrust them if the owner of the town not there to prevent bans or kicks maybe ?

**Comment by Chucky891** [comment]
perfect thank you

**Comment by LlmDl** [comment]
The `/t ranklist {townname}` can show an admin who is trusted in that Town.

For plot trusting it will likely require a new system storing plot's trust lists in memory.
