### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by Olzie-12** [TownyAdvanced/Towny#5630]
### **Please explain your feature request to the best of your abilities:**

You've added the `TownPreAddResidentEvent` and this fires before the actual event happens, is it possible we can get the pre version of when you remove the resident as well?

**Comment by Olzie-12** [comment]
In the docs, it says after. But in the code its firing before. So a bit confused

**Comment by LlmDl** [comment]
> In the docs, it says after. But in the code its firing before. So a bit confused

Not sure what you mean here.

**Comment by LlmDl** [comment]
Are you looking to be able to cancel a resident leaving a town?
