### ISSUE TITLE
QualityArmory. Weapons do not damage players. 

### ISSUE THREAD

**Issue by Felson999** [TownyAdvanced/Towny#5635]
### What steps will reproduce the problem?

We use the plugin QualityArmory (latest version). Weapons from this plugin do not damage players. Previously, everything worked on older versions of towny, everything stopped working from version 0.97.2.13 and higher. Firearm damage do not work anywhere in the world.

### What is the expected output?

Find out what you have added to this version, that weapon damage has stopped damaging players and how to fix it for us to make it work.

### Towny version

The bug starts appearing with version 0.97.2.13 and higher (Everything works on version 0.97.2.12, 2.11, 2.10..... (We checked))

### Server version

Purpur 1.16.5

### Please use Pastebin.com to link the following files

default configs

**Comment by LlmDl** [comment]
I am fairly certain that QualityArmory needs to adapt to an API change we made. Tell them to update their Towny support.
