### ISSUE TITLE
TownyCamps Localization 

### ISSUE THREAD

**Issue by FARF12** [TownyAdvanced/Towny#5649]
### What steps will reproduce the problem?

Hello LlmDl.I ran into a problem in the localization of camps.Despite the fact that the English version of localization is indicated in the config, he still tries to turn to the Russian one.I created a Russian localization but it ignored it

### What is the expected output?

localization -.-

### Towny version

97.5.12

### Server version

1.16.5

![Screenshot_426](https://user-images.githubusercontent.com/88440932/150154620-e8bfc90b-2932-486d-af7a-5b133acd29bb.png)
![Screenshot_427](https://user-images.githubusercontent.com/88440932/150154633-5411de24-b3e1-412e-8210-cc21c3305f65.png)
![Screenshot_428](https://user-images.githubusercontent.com/88440932/150154637-4778b350-0d84-45b1-9fa6-0521901afc4f.png)

**Comment by LlmDl** [comment]
you need to put your ru-RU.yml into the override folder.

**Comment by FARF12** [comment]
> you need to put your ru-RU.yml into the override folder.

it works
