### ISSUE TITLE
Towny x Crazy Enchantments Flood

### ISSUE THREAD

**Issue by MarkE-Official** [TownyAdvanced/Towny#5654]
### What steps will reproduce the problem?

![consoleflood](https://user-images.githubusercontent.com/93688829/150303361-2a8f9821-febb-4d85-8c5a-935b275f1f5c.PNG)

I'm having this flood saying these on my console, it is somehow intertwined with towny config. How can I resolve this? Send Help.

### What is the expected output?

On how can I resolve this on my end.

### Towny version

Towny-0.97.5.0

### Server version

1.17.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: 
2. Your Towny config.yml: https://pastebin.com/gzmdT7i6
3. Your townyperms.yml: https://pastebin.com/UBystebY
4. Your log's error: On the Picture Provided.

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/zYXeyDTa
7. Your channels.yml:

**Comment by LlmDl** [comment]
CrazyEnchantments is using part of the CombatUtil which had the method change. They should update their Towny support.
