### ISSUE TITLE
/t deposit

### ISSUE THREAD

**Issue by TaskTUA0921** [TownyAdvanced/Towny#5655]
### What steps will reproduce the problem?

https://github.com/TownyAdvanced/Towny/issues/4253
You're having this problem again.

### What is the expected output?

https://github.com/TownyAdvanced/Towny/issues/4253

### Towny version

97.5.12

### Server version

Spigot1.18.1

### Please use Pastebin.com to link the following files

https://github.com/TownyAdvanced/Towny/issues/4253

**Comment by LlmDl** [comment]
Skipped the form.
