### ISSUE TITLE
NPC's attacking other NPC's throws spammy error

### ISSUE THREAD

**Issue by LegitStraightUp** [TownyAdvanced/Towny#5656]
### What steps will reproduce the problem?

when NPC's are attacking mobs or other NPC's it spams a "TownyPlayerDamagePlayerEvent"
Removing the NPC removes the error, but they are for quests etc

### What is the expected output?

no errors? I guess....

### Towny version

0.97.5.0

### Server version

purpur-1.18.1-1513.jar

### Please use Pastebin.com to link the following files

[1. Your full server startup from the logs\latest.log:](https://paste.denizenscript.com/View/92457)
2. Your Towny config.yml:https://paste.denizenscript.com/View/92459
3. Your townyperms.yml:https://paste.denizenscript.com/View/92460
4. Your log's error:https://paste.denizenscript.com/View/92461

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Fix is part of 0.97.5.14.
