### ISSUE TITLE
Suggestion: Make TownyMessaging's methods support Adventure's Components

### ISSUE THREAD

**Issue by PainOchoco** [TownyAdvanced/Towny#5670]
### **Please explain your feature request to the best of your abilities:**

Some of TownyMessaging methods do not support Adventure's Component.
It would be cool if they did, here is a list of methods that only support strings and could support components:

TownyMessaging#
- `sendDebugMsg`
- `sendDevMsg`
- `sendErrorMsg`
- `sendGlobalMessage`
- `sendInvitationMessage`
- `sendMessage`
- `sendMsg`
- `sendNationMessagePrefixed`
- `sendPrefixedNationMessage`
- `sendPrefixedTownMessage`
- `sendTownMessagePrefixed`

And finally these one could support [Adventure's Title](https://docs.adventure.kyori.net/title):
- `sendTitleMessageToNation`
- `sendTitleMessageToResident`
- `sendTitleMessageToTown`

Thanks and keep up the good work!

**Comment by LlmDl** [comment]
All messaging should be routed through the a path that handles MM as of a while ago.
