### ISSUE TITLE
Error in /p info

### ISSUE THREAD

**Issue by TheSirCororo** [TownyAdvanced/Towny#5677]
### What steps will reproduce the problem?

1. Execute command /p info (it not works at all chunks, only a few, don't know why
2. See exception in console and don't see correct output

### What is the expected output?

Normal working of command /p info

### Towny version

0.97.5.0

### Server version

Paper 1.17.1-404 (latest)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/nbRQtLcN
2. Your Towny config.yml: https://pastebin.com/CD32spTY
3. Your townyperms.yml: https://pastebin.com/NXdxj0JN
4. Your log's error: https://pastebin.com/WGKbKQxE

**Comment by LlmDl** [comment]
if you're able to find a townblock with this problem, please go to it, use `/towny map` and make note of the world and x and z coordinates at the top of the command output.

Using the world, x and z, please find the townblock file in the `towny\data\townblocks\WORLD\x and z` and upload it to pastebin.com and supply the link. 

I would also like to see a screenshot of what `/towny map` shows at the location.

**Comment by TheSirCororo** [comment]
Strange, the error didn't reoccur.

**Comment by LlmDl** [comment]
Let me know if it comes back, with the asked for information.
