### ISSUE TITLE
Exception - Text contains unterminated color string

### ISSUE THREAD

**Issue by skw359** [TownyAdvanced/Towny#5680]
### What steps will reproduce the problem?

This problem might be specific to _something_, but I'm not entirely sure what - using `/t boardwalk` outputs the problem though:

1. Use `/t boardwalk`
2. Done, free stacktrace in console! https://www.toptal.com/developers/hastebin/elonefagaf.properties

### What is the expected output?

Information about the town in chat

### Towny version

Towny v0.97.5.15

### Server version

Paper version git-Paper-175 (MC: 1.18.1)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://www.toptal.com/developers/hastebin/cowesifobi.yaml
2. Your Towny config.yml: https://www.toptal.com/developers/hastebin/ozakefutoj.yaml
3. Your townyperms.yml: https://www.toptal.com/developers/hastebin/ihoxazonut.properties
4. Your log's error: https://www.toptal.com/developers/hastebin/elonefagaf.properties

(optional) If this is to do with permissions,
5. Your permissions file: 

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://www.toptal.com/developers/hastebin/nicivudeho.coffeescript
7. Your channels.yml: https://www.toptal.com/developers/hastebin/igopuyeqiv.yaml

**Comment by LlmDl** [comment]
If this is still an issue with Boardwalk i'd like to see their towny\data\towns\boardwalk.txt, the issue is when towny is trying to format their town status screen's subtitle line.

**Comment by skw359** [comment]
[boardwalk.txt](https://github.com/TownyAdvanced/Towny/files/7966505/boardwalk.txt)
Sure, here ya go

**Comment by skw359** [comment]
I'm using `status_title_pvp: '&#ADF3FD(PVP)'` which might be causing the error

**Comment by skw359** [comment]
Oh I discovered another one: `help_0: '&#ADF3FD&lGeneral Towny Help'` (using that will get an internal error with this stacktrace: https://www.toptal.com/developers/hastebin/ilicerumal.properties

**Comment by LlmDl** [comment]
Yep, I'm working on it.

**Comment by LlmDl** [comment]
So it works fine now, but for some reason the blue you chose (which colours fine everywhere else,) ends up showing the PVP in purple. I have run out of time to diagnose that one so far.
