### ISSUE TITLE
territory protection bug

### ISSUE THREAD

**Issue by PawsTenebria** [TownyAdvanced/Towny#5685]
### What steps will reproduce the problem?

1. moss_carpet big_dipleaf azalea flowering_azalea sea_pickle ametyst crystal dropped after the explosion and then restored
2. The following items can be stolen from flowerpots: azalea flowering_azalea

### What is the expected output?

blocks will be protected by the city

### Towny version

towny-0.97.5.15

### Server version

1.18.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Since the potted plants part has been fixed, I am going to track the other issue in a separate ticket: https://github.com/TownyAdvanced/Towny/issues/5689
