### ISSUE TITLE
Suggestion: Towny EventWar Minimum Number of Players Conditions

### ISSUE THREAD

**Issue by Anth64** [TownyAdvanced/Towny#5696]
### **Please explain your feature request to the best of your abilities:**

If the town does not have the minimum number of players, (as in a total for the town) 
ex.
```
Town A has 3 residents but the minimum is 4, however all of town A's residents are online.
Town A should be able to go to war since their whole town is online, despite being below the minimum.
```
This would be a good option so that people cannot split into smaller towns to avoid war completely if they are not neutral.

**Comment by LlmDl** [comment]
Part of 0.0.28
