### ISSUE TITLE
Hex colour support broken on systems using Adventure

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#5698]
### What steps will reproduce the problem?

1. Use hex codes in the status screens.
2. Incorrect colour appears.

### What is the expected output?

Adventure.text is unable to read the legacy hex codes that ChatColor.of(hexcode) generates when we use StringMgmt's translateHexColors.

### Towny version

Any version post-status-screen overhaul.

### Server version

n/a

### Please use Pastebin.com to link the following files

.

**Comment by Warriorrrr** [comment]
Possibly something that might be fixed once I put some more work into the minimessage pr, haven't touched the TownyFormatter yet there.

**Comment by LlmDl** [comment]
Yeah I'm going to redo the status screen parts which aren't making components directly anyhow though.
