### ISSUE TITLE
Cannot set enabled all perms for all players in town

### ISSUE THREAD

**Issue by TheSirCororo** [TownyAdvanced/Towny#5701]
### What steps will reproduce the problem?

1. Enter `/ta town TOWNNAME set perm build on` or `/ta town TOWNNAME set perm on`
2. See that perm in town plots didn't change

### What is the expected output?

Change perms in all town plots

### Towny version

0.97.5.0

### Server version

Paper 1.17.1-404

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: no errors
2. Your Towny config.yml: https://pastebin.com/3p9x7jm6
3. Your townyperms.yml: https://pastebin.com/m9ARnBZc
4. Your log's error: no errors

### Additional info:
This problem started from this discussion https://github.com/TownyAdvanced/Towny/discussions/5682

**Comment by LlmDl** [comment]
I have not been able to reproduce this bug. It has either been fixed since your ticket was made or there was something else being done incorrectly.
