### ISSUE TITLE
Towny not working when I restart my server

### ISSUE THREAD

**Issue by OpTempo121** [TownyAdvanced/Towny#5709]
### What steps will reproduce the problem?

1. I install towny it works perfectly fine
2. I stop my server and boot it up again and boom it no longer works. 
3. The plugin is still being recognized by my server but when I type in a towny command literally nothing happens, the command doesn't get red either.
4. Not sure how to fix this but here's a list of my plugins
- CMILib 1.1.1.1.0
- EssentialsX 2.19.2
- Jobs 5.0.1.2
- multiworld
- Vault
- Worldedit-bukkit 7.2.9

### What is the expected output?

I expected it to work when I restart my server

### Towny version

0.97.5.0

### Server version

1.18.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
Skipped the form.

**Comment by LlmDl** [comment]
If you're using 1.18.1 you need to use Towny 0.97.5.15 or newer.
