### ISSUE TITLE
Suggestion: MongoDB database

### ISSUE THREAD

**Issue by zekepari** [TownyAdvanced/Towny#5710]
### MongoDB support as a database

Towny currently allows for 2 methods of storing data. Flatfile, and MySQL.
It would be great if another commonly used database such as MongoDB was added as well.
I know many developers typically like to use one database host for all data relating to one project. This would make data organisation so much more easier for developers intending to use Towny.

**Comment by TheSirCororo** [comment]
And what about PostgreSQL?
