### ISSUE TITLE
There is no centering [DynmapTowny]

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5711]
### What steps will reproduce the problem?

1. Go to dynmap site (dynmap version Dynmap-3.3.1-spigot)
2. Click on town
3. there are no lines and centering (see the screenshot below)
![image](https://user-images.githubusercontent.com/73141732/152602195-6912ab65-f9fd-4642-a154-921f93e138a0.png)

this problem appeared only on the new version of dynmap, on version Dynmap-3.3-beta-3 it worked, but not on versions higher

### What is the expected output?

![image](https://user-images.githubusercontent.com/73141732/152602780-5bf41d97-0440-4d00-bdf2-72b80b06d287.png)

### Towny version

0.97.5.0

### Server version

Paper 1.17.1-404

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: no errors
2. Your Towny config.yml: https://pastebin.com/3p9x7jm6
3. Your townyperms.yml: https://pastebin.com/m9ARnBZc
4. Your log's error: no errors

**Comment by LlmDl** [comment]
Show your dynmap-towny config, did you put in CSS to center thins in the info window?

**Comment by 1Pootis1** [comment]
```
infowindow: <div class="infowindow"><center><span style="font-size:150%;">Город »
  %regionname% </span> <br /> <span style="font-weight:bold;">%board%</span> <hr style="border-width:3px;border-color:grey;">
  <span style="color:#CD853F">Основан</span> » <span style="font-weight:bold;">%founded%</span>
  <br /> <span style="color:#CD853F">Нация</span> » <span style="font-weight:bold;">%nation%</span><br/>
  <span style="color:#CD853F">Культура</span> » <span style="font-weight:bold;">%culture%</span>
  <hr style="border-width:3px;border-color:grey;"> <span style="color:#CD853F">Лорд</span>
  » <span style="font-weight:bold;">%playerowners%</span><br /> <span style="color:#CD853F">Жители
  </span> » <span style="font-weight:bold;">%playermanagers%</span></center></div>
```

**Comment by LlmDl** [comment]
I'm not really a CSS wiz, I cannot say why it doesn't work for you there.

**Comment by 1Pootis1** [comment]
But it worked on the old versions, two versions ago 🧐

**Comment by LlmDl** [comment]
I haven't changed anything, maybe it's a change in dynmap?

**Comment by 1Pootis1** [comment]
Maybe what should I do in this case?

**Comment by LlmDl** [comment]
I don't know, are you able to use your current dynmap and see if its still broken on the dynmap-towny from 2 versions ago?

**Comment by 1Pootis1** [comment]
I checked, rolled back the versions and there was no such error, and as soon as I install the latest version of dynmap, it appears

**Comment by LlmDl** [comment]
So maybe you can try asking the dynmap author if they've done something that affects centering.

**Comment by 1Pootis1** [comment]
Well, I will ask and I will write to you about the results, maybe I'm not the only one who has a similar problem.

**Comment by 1Pootis1** [comment]
Fixed in the new version of dynmap
https://github.com/webbukkit/dynmap/issues/3651
