### ISSUE TITLE
when doing /t or /t set name there is a large lag spike

### ISSUE THREAD

**Issue by CuboidCat** [TownyAdvanced/Towny#5720]
### What steps will reproduce the problem?

I am not sure how to exactly reproduce the issue. I recently changed the regex in the config to   
regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
in order to allow color codes to be used in town names.

### What is the expected output?

There will be a lag spike and this error in the console
[message.txt](https://github.com/TownyAdvanced/Towny/files/8012143/message.txt)

### Towny version

Towny-0.97.5.0

### Server version

Paper 1.17.1

### Please use Pastebin.com to link the following files

1. Logs: https://pastebin.com/nDjnf9Sr
2. config: https://pastebin.com/xiJtGJ6c
3. perms: https://pastebin.com/1ApW9FBG
4. error: https://pastebin.com/CssmRUtM
6. chatconfig.yml: https://pastebin.com/urHTS8cr
7. channels.yml: https://pastebin.com/kfLyw7Un

**Comment by LlmDl** [comment]
The lag is from BetterEconomy.

**Comment by CuboidCat** [comment]
removing BetterEconomy did not fix the issue. I am now just using the default essentials economy and it is not fixed.
https://pastebin.com/nF5fQfRz

**Comment by LlmDl** [comment]
Maybe essentials doesn't like it either, EssentialsEconomyX isn't recommended.

**Comment by CuboidCat** [comment]
Which economy plugin would you recommend?

**Comment by CuboidCat** [comment]
I just tried this plugin and the same issue is happening
https://www.spigotmc.org/resources/the-new-economy.7805/
so idk

**Comment by LlmDl** [comment]
It's not an issue for other servers. Maybe its got to do with the & in your town name but I'd doubt it.

**Comment by CuboidCat** [comment]
That's so strange. It lags when I do /t aswell idk what it is

**Comment by LlmDl** [comment]
Its the economy plugin responding slow to the bank account balance query.
