### ISSUE TITLE
Error command /player

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5721]
### What steps will reproduce the problem?

1. write /player <nickname> (the error does not occur with all nicknames!)
2. look at the console

### What is the expected output?

normal behavior of the /player command

### Towny version

0.97.5.0

### Server version

Paper 1.17.1-404

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: no errors
2. Your Towny config.yml: https://pastebin.com/3p9x7jm6
3. Your townyperms.yml:  https://pastebin.com/m9ARnBZc
4. Your log's error: https://pastebin.com/qGJpnP4r

![image](https://user-images.githubusercontent.com/73141732/152879823-ac283ccc-9d1d-4e69-8a04-173da10d45c9.png)

**Comment by LlmDl** [comment]
Show me your full startup.

**Comment by LlmDl** [comment]
Also tell me if you're using a resource pack or a different font.

**Comment by 1Pootis1** [comment]
Here is the startup log: https://pastebin.com/QyNuzTXA
I don't use any fonts or resource packs, the screenshot shows the Windows Terminal application

**Comment by 1Pootis1** [comment]
![image](https://user-images.githubusercontent.com/73141732/153003497-84f25e7b-f6a3-4ea8-85bc-23437cfa3267.png)
he is not the mayor of the city, but only a citizen, and when entering a command on behalf of a player, he simply does not write anything, an error in the console, the same as I threw above

**Comment by LlmDl** [comment]
I meant what you see when they use `/town townname` where `townname` is their town's name.

**Comment by 1Pootis1** [comment]
![image](https://user-images.githubusercontent.com/73141732/153030063-95a6405f-0793-4980-ad6b-9dde46f63ff5.png)

**Comment by 1Pootis1** [comment]
https://pastebin.com/7RYJxE7z

**Comment by LlmDl** [comment]
The issue is either the player's formatted name (title, name and surname) are too long or the hex colour codes in the surname and title.

**Comment by 1Pootis1** [comment]
And how to solve this problem? It's not just this player, is there still, maybe there is a way out of this situation?

**Comment by LlmDl** [comment]
Tell me if this fixes it: https://cdn.discordapp.com/attachments/669247087329673228/940732230664351764/towny-0.97.5.0.jar

**Comment by 1Pootis1** [comment]
After 2.5 hours, a planned reboot of the servers, as soon as it passes, I will immediately report the result

**Comment by 1Pootis1** [comment]
It works! Thank you very much :)
