### ISSUE TITLE
Suggestion: Towny Event War - Add a Conquered State to Towns After a Nation War is Over

### ISSUE THREAD

**Issue by Anth64** [TownyAdvanced/Towny#5726]
### **Please explain your feature request to the best of your abilities:**

In event war there is already a setting that allows a town to have conquered status.

It is called `conquer_time`

I believe that perhaps conquer time can be reworked to instead of temporarily adding it to the conquering nation during the war it works something similar to this.

- War starts, towns and residents get locked into their nations/towns.
- Town falls during war, conquer state applies.
- Town cannot leave nation, resident cannot leave town and are removed from the war.
- War finishes.
- Conquer time applies after war finishes.

This would encourage more player interaction as conquered towns should be considered lootable by the conquering town/nation.

Perhaps a way to install new government (i.e. a mayor/king) after a town/nation is conquered would be a neat idea as it would encourage riots/civil war to happen more often.

**Comment by LlmDl** [comment]
There is now an option in 0.0.32 which prevents residents leaving their town while their town is conquered

**Comment by LlmDl** [comment]
Let me know if this ticket is complete now.
