### ISSUE TITLE
French translatations don't work well

### ISSUE THREAD

**Issue by ThomasLETELLIER** [TownyAdvanced/Towny#5731]
### What steps will reproduce the problem?

1- Edit the line "language: en-US.yml" to "language: fr-FR.yml".
2- Perform on the server /ta reload lang
3- Try the command "/town" should display French content
However, when creating a city with "/town create 
![Towny_FRENG_](https://user-images.githubusercontent.com/56863923/153703563-414fc45a-2894-46b0-ad82-d7780c5fc5fe.png)
example", the texts will be in English (like many others)

### What is the expected output?

All commands should display the text in French

### Towny version

0.97.5.0

### Server version

Pufferfish 1.18.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/mcQzc1LB
2. Your Towny config.yml: https://pastebin.com/6Bjaq2pC
3. Your townyperms.yml: https://pastebin.com/bNeZqnrj
4. Your log's error: There's no log's errors

**Comment by ThomasLETELLIER** [comment]
Adding my fr-FR.yml lang file : https://pastebin.com/eSimCyGa

**Comment by gaffy00** [comment]
What language do you have your Minecraft client set to? Towny's multi-language support sends messages to clients based on their locale. You can read more here: [https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#multi-language](url).

**Comment by ThomasLETELLIER** [comment]
Ohhh, I feel a little silly but indeed, my game is in English..
But indeed, I copied the translation in global.yml and the translation is effective.

Thank you very much for this clarification, you can close this ticket !
