### ISSUE TITLE
Suggestion: Treasury Integration

### ISSUE THREAD

**Issue by lokka30** [TownyAdvanced/Towny#5752]
### **Please explain your feature request to the best of your abilities:**

Treasury is now ready for Towny to integrate into it :smile:

The Economy API seems to be finished (at least at this stage). We also plan on adding a Region (land protection) API in the future which Towny could also utilize.

Let me know if you need a hand with anything. This can also be PR'd.

**Comment by LlmDl** [comment]
@lokka30 have you put up a Wiki or got any example documenations that can be used to make a TreasuryAdapter in Towny?

**Comment by lokka30** [comment]
> @lokka30 have you put up a Wiki or got any example documenations that can be used to make a TreasuryAdapter in Towny?

Not yet, though we should wait for https://github.com/lokka30/Treasury/pull/180 to be merged before we start. 😃

**Comment by LlmDl** [comment]
Please let me know when you're wanting to begin a PR to put Treasury as a supported economy type.
