### ISSUE TITLE
Suggestion: Option to disable town board message on join

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/Towny#5756]
### **Please explain your feature request to the best of your abilities:**

As the title says :3 The reason for this is I would like to see a clean and unified motd (created by Essentials) when the player joins. There are many plugins in my server and some of them send their messages on join which cannot be disabled.

**Comment by Warriorrrr** [comment]
The town and nation boards on login can be disabled by setting `display_board_onlogin` to false in the global town and global nation settings.
