### ISSUE TITLE
Suggestion: townybuild

### ISSUE THREAD

**Issue by eZstahq** [TownyAdvanced/Towny#5763]
### **Please explain your feature request to the best of your abilities:**

I want there to be a command /t builds  and there it was possible to buy buildings for any resource and coins at the same time. this will improve the development in cities, and cities will become more beautiful. there you will be able to write off your buildings, items and the amount of currency needed for purchase. it will also be possible to add harraketristics of buildings, and your buffs to the city

**Comment by LlmDl** [comment]
That sounds like a lot of work for the developer. I'm not really interested in doing that.

**Comment by eZstahq** [comment]
hi @LlmDl its not a lot off work, becouse all shop can doing in deluxemenu., but link this menu to towny and all, there is such a system on politmine
