### ISSUE TITLE
Suggestion: Add "custom explosions" to the regeneration of wilds

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/Towny#5773]
### **Please explain your feature request to the best of your abilities:**

Damage from explosions like  "cannons plugin" does not regenerate. Can you add a way to regenerate it?
![imagen](https://user-images.githubusercontent.com/91406867/155754699-f22b8d22-16af-4e6e-a025-95b3af481410.png)

**Comment by LlmDl** [comment]
It uses world.createExplosion() so we should regenerate it already. What is the entity that represents the cannonball?

**Comment by Peskdt** [comment]
It uses 2 projectiles. Like a snowball (doesn't regenerate) and a TNT (the first explosion doesn't regenerate, but the following does)

**Comment by LlmDl** [comment]
Put the snowball into the regenerate-able entities list.

**Comment by Peskdt** [comment]
Didn't work

![imagen](https://user-images.githubusercontent.com/91406867/155758024-0ce7e240-4c13-42bb-91e6-b9fed9e0f340.png)

**Comment by LlmDl** [comment]
Did you add it to the world or the config?

**Comment by Peskdt** [comment]
The world's data

**Comment by LlmDl** [comment]
Show me your world file. Make sure you're doing a stop and start after editing.

**Comment by Peskdt** [comment]
![imagen](https://user-images.githubusercontent.com/91406867/155761930-7eb0e811-9a0d-48a3-b155-41abb9799e41.png)

**Comment by Peskdt** [comment]
Oh, it's working, but the delayed explosions of tnt doesn't regenerate. Ty
