### ISSUE TITLE
Suggestion: Add a command for seeing who's trusted in a town.

### ISSUE THREAD

**Issue by Seagoddess** [TownyAdvanced/Towny#5788]
### **Please explain your feature request to the best of your abilities:**

/t trust add [player] lets a player see allow those who are not a part of a town to build, edit, etc. To my knowledge there is no command to see who and who is not trusted without adding them to the gui on /plot perm add which on a large server would take forever. For those unaware of they even should do /plot perm add there should be a command that just flat out lists who has any perms in the ENTIRE town not just a single plot.

**Comment by LlmDl** [comment]
Already exists in `/town trust list`.
