### ISSUE TITLE
Suggestion: Use TA to claim a plot for a town

### ISSUE THREAD

**Issue by BlueFyreMatt** [TownyAdvanced/Towny#5790]
### **Please explain your feature request to the best of your abilities:**

Currently there's no command that allows a person to forceclaim a chunk for a town. Instead, you have to add yourself to the town, claim the chunk and remove yourself from the town again.

I'd explain it more but the feature is very self explanatory...

**Comment by LlmDl** [comment]
`/ta set plot {townname}` Does this already.
