### ISSUE TITLE
Suggestion: EventWar alternate ending: Peace Agreement.

### ISSUE THREAD

**Issue by Oleksiy13321** [TownyAdvanced/Towny#5794]
### **Please explain your feature request to the best of your abilities:**

it would be a good idea to make it possible to sign a peace agreement

**Comment by Oleksiy13321** [comment]
war can be stopped by command like: /declare whitePeace and you and the other country receives a message where it can press / confirm or / cancel or you can surrender by /declare surrender and your country or city will become part of the enemy city

**Comment by LlmDl** [comment]
Ideally we will support 3 methods of player-initiated "peaceful" endings.

- [ ] Peace for Money (one side offering an amount of money for peace.)
- [ ] Peace for Surrender (which could result in merging into the other victorious party.)
- [ ] Peace for Nothing (an amenable ending to the war.)

**Comment by LlmDl** [comment]
Part of 0.0.41
