### ISSUE TITLE
Error to /ta unclaim

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5798]
### What steps will reproduce the problem?

1. enter /ta unclaim in empty chunk
2. see console 
![image](https://user-images.githubusercontent.com/73141732/157564691-7ceb8aa5-669a-4925-a139-e1e8fa4f3ef8.png)

### What is the expected output?

нормальная рабочая команда unclaim

### Towny version

Towny-0.98.0.0

### Server version

paper 1.17.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: not necessary
2. Your Towny config.yml: not necessary
3. Your townyperms.yml: not necessary
4. Your log's error: not necessary

(optional) If this is to do with permissions,
5. Your permissions file: not necessary

(optional) If this is to do with chat,
6. Your chatconfig.yml: not necessary
7. Your channels.yml: not necessary

**Comment by LlmDl** [comment]
Turns out the form was necessary.
