### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by caarson** [TownyAdvanced/Towny#5801]
### What steps will reproduce the problem?

clicking the discord link

### What is the expected output?

to join discord

### Towny version

N/A

### Server version

N/A

### Please use Pastebin.com to link the following files

N/A

**Comment by LlmDl** [comment]
Which link? The discord is linked in many places.

**Comment by caarson** [comment]
> Which link? The discord is linked in many places.

https://github.com/TownyAdvanced/Towny

Under “Contact / Support”

**Comment by LlmDl** [comment]
It's working fine for me.

**Comment by caarson** [comment]
> It's working fine for me.

Yes! This appears to be an issue with my account... for some reason, I am banned?
If you could unban me (caarson#0001) that would be great, sorry for the false alarm.
