### ISSUE TITLE
Suggestion: Option to either Annex or Topple 

### ISSUE THREAD

**Issue by ItsJuls** [TownyAdvanced/Towny#5804]
### **Please explain your feature request to the best of your abilities:**

What i mean is that when you win in a town vs town war or even a nation vs nation war in EventWar, there should be an option or command to either Annex them(Take of all of their land) or Topple their Government(Aka Puppet them) and change the mayor of that town or nation. It would be a good feature for people to war to topple bad towns

**Comment by j0g32** [comment]
That could also be achieved by using/funding a civil war or riots in the event war?

**Comment by LlmDl** [comment]
This is probably going to come to pass in #6465, as the decision to annex/topple shouldn't be required to happen right away.

A king who has conquered a town might want to see if they will fall into line before deposing them with a puppet.

Making it something that isn't an immediate decision is also easier to code in regards to having to handle possible outcomes right after a war ends.
