### ISSUE TITLE
endless dupe and problems with interaction in the regions

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5805]
### What steps will reproduce the problem?

1. put roots in private
2. DO NOT HAVE ACCESS TO THE CITY (REGION)
3. hoe PKM on the roots
4. they will fall endlessly

https://user-images.githubusercontent.com/73141732/158267665-a680d7b9-113c-46f9-9eb1-c78b1f438d2c.mp4

## perhaps such a bug exists for other similar blocks, a pumpkin or the like.

And yet, players not added to private can put food in fires, see the screenshot below
![image](https://user-images.githubusercontent.com/73141732/158268397-0646d718-48f9-4b08-a6f6-d70b02831b6d.png)

### What is the expected output?

Do not fall, a special message is written

### Towny version

Towny-0.98.0.0

### Server version

paper 1.17.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: no errors
2. Your Towny config.yml:  https://pastebin.com/9sp980gG
3. Your townyperms.yml: https://pastebin.com/MKCwrG1S
4. Your log's error: no errors

**Comment by 1Pootis1** [comment]
There, with fires, I sent a screenshot of the same trouble

**Comment by LlmDl** [comment]
File a ticket with instructions on repeating it please.
