### ISSUE TITLE
EventWar blocking Towny plot perms

### ISSUE THREAD

**Issue by Verbannt** [TownyAdvanced/Towny#5811]
### What steps will reproduce the problem?

1. Have switch_use, item_use, build_and_destroy_editable_materials set to "false" in config
2. Begin a war
3. Try to open a chest/door, use an item, place/break a block and find that you are unable to even in your own town

If the above fields are set to "true" then you have those permission globally, even in enemy towns.
Only tested with World War, not other war types.

### What is the expected output?

I'm not certain how these permission are intended to work, but when **switch_use**, **item_use**, and **build_and_destroy_editable_materials** are set to "true," the perms behave as I would expect. Which is to be enabled globally in all towns.

However, when the fields are set to "false," then players lose the affected plot perms even inside their own towns. I would expect that a setting of "false" allowed Towny to keep it's non-war plot perm settings, while "true" would override non-war settings and allow enemies access that they wouldn't otherwise have.

If I'm misunderstanding the permissions, please correct me, thank you!

### Towny version

Towny version: 0.98.1.0
EventWar version: 0.0.36

### Server version

1.16.5

### Please use Pastebin.com to link the following files

Eventwar - warconfig.yml
https://pastebin.com/vnDGR3bS

**Comment by LlmDl** [comment]
So I was looking this over and players should only be getting assigned the WARZONE TownBlockStatus when they're not residents of the Town they are trying to break in.

You have `warzone_affects_residents: 'false'` which should mean that they don't have their TownBlockStatus made into WARZONE. Are you testing with a resident of the Town or with someone who is an Ally via a Nation or Nation Alliance?

**Comment by Verbannt** [comment]
Okay, I think that's my issue.
I was testing more last night and noticed that it was working for some players (actual residents of the town), but I didn't actually realize the players having trouble were only allies until you pointed this out.

It seems that proper residents do have permissions in their own towns. Apparently the town owner has been giving members of his nation perms with /t trust add <name> and it's these players that lose permission once war starts.

So it seem everything's working as intended, and I just didn't understand the situation well enough. 
But, is it possible for allies to retain their permission in allied towns during war?

**Comment by LlmDl** [comment]
I can probably get allies and trusted players to also get the correct behaviour. Trusted *might* lead to issues since the mayor could technically trust an enemy, but I don't see anyone doing that.

**Comment by Verbannt** [comment]
Yeah, if it would be possible to get ally perms, that would be brilliant. I was thinking trusted might be a little difficult for the same reason you mentioned, so if you're not able to set that one up don't worry too much. I can just tell people to toggle ally perms in the town for war, so long as that one is working.
Thank you for such a quick reply!

**Comment by LlmDl** [comment]
This should be fixed up in the upcoming 0.0.37.
