### ISSUE TITLE
Towny Chat Issue

### ISSUE THREAD

**Issue by dragontekgaming** [TownyAdvanced/Towny#5818]
### What steps will reproduce the problem?

1. added a channel [Trade]
2. edited channel tags, channel color
3. reloaded townychat

### What is the expected output?

I expected to see the channel I created with the correct tag and color. Tag was correct, channel color was not.
Then all other channels started acting up.
when in general without changing channels, there is no tag (perfect, this is what I want)
No channels show the &8[ I set.
After switching channels,and going back to general, I suddenly get the [g] tag in general.

### Towny version

Towny version: 0.98.1.0
TownyChat version: 0.96

### Server version

Paper 1.18.2 build 244

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/pr4ZLzcu
2. Your Towny config.yml: https://pastebin.com/MALkd4Qw
3. Your townyperms.yml: https://pastebin.com/11Yau3J2
4. Your log's error: No log errors

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/hiZydapz
7. Your channels.yml: https://pastebin.com/eaZvW6CB

**Comment by LlmDl** [comment]
Your global channel_format should not include the {channelTag}. You should make your trade channel a DEFAULT type.

Having an empty channelTag in the channels.yml in the global section might be screwing things up.

Screenshots of what your chat look like are also very helpful.

**Comment by dragontekgaming** [comment]
https://imgur.com/a/lY8xgKp

After updating the removal of {channelTag} from global channel format, changing trade channel to DEFAULT type, and fix the empty channelTag in channels.yml. Then did a `/townychat reload`

**Comment by dragontekgaming** [comment]
Also having an issue where people are being put now into trade chat by default.

**Comment by LlmDl** [comment]
You have the trade channel set to default: true.

>After updating the removal of {channelTag} from global channel format, changing trade channel to DEFAULT type, and fix the empty channelTag in channels.yml. Then did a /townychat reload

Looks like the channelTag isn't shown in general any longer. Is your trade channel looking better?

**Comment by dragontekgaming** [comment]
channelTag isn't showing in general, and trade channel looks good. However formatting of all other channel tags and chat colors has not taken.
Fixed trade default: true.

**Comment by LlmDl** [comment]
Show me your current chatconfig and channels files.

**Comment by dragontekgaming** [comment]
channels.yml: https://pastebin.com/Jj61Ea9N 
ChatConfig.yml: https://pastebin.com/LmeNqxj3

I skipped the top of chat config to save scroll time.

**Comment by LlmDl** [comment]
So the only discrepancy I can spot from the screenshot to your current channels.yml is your town channeltag has white []'s instead of gray []'s. What am I missing?

**Comment by dragontekgaming** [comment]
I also changed town tag color to dark green and town chat color to light green.
Nation is gold tag, yellow chat, 
Alliance is cyan tag, teal chat

**Comment by LlmDl** [comment]
I'm betting just stopping and starting the server, after confirming that your channels.yml on the server is correct will solve this. There's no reason some channels would load their settings and others wouldn't.

**Comment by dragontekgaming** [comment]
I'll restart in a minute and let you know. Colors reverted back from the image to defaults on town, nation, and alliance.

**Comment by dragontekgaming** [comment]
Restarting seems to have fixed the issue!

Thank you for your time!
