### ISSUE TITLE
Towny lang file inculudes a minecraft server advertisment

### ISSUE THREAD

**Issue by Coder-TheSid** [TownyAdvanced/Towny#5822]
### What steps will reproduce the problem?

The traslate files include a server advertisment.
In Towny folder goto "plugins/Towny/settings/lang/reference/tr-TR.yml" at tr-TR.yml 518,523,524,525,528,528,531,533 and 534  inculudes "&e&lAVENOR &8&l》" which is a Turkish Towny server's name please remove that advertisments

### What is the expected output?

![image](https://user-images.githubusercontent.com/74655120/159154279-5d9e6f8a-f00b-4ff9-80a0-6466585e21a4.png)

### Towny version

0.98.1.2

### Server version

Purpur 1.17.1

### Please use Pastebin.com to link the following files

no

**Comment by Warriorrrr** [comment]
Looks like whoever translated that got a bit confused, I've removed the translations with the server name on crowdin and approved the new translations someone else suggested right after. For now you can manually override the strings using the lang override system while waiting for the next pre-release.
