### ISSUE TITLE
Suggestion: EventWar should rollback the towns after the war should be finished

### ISSUE THREAD

**Issue by ItsJuls** [TownyAdvanced/Towny#5825]
### **Please explain your feature request to the best of your abilities:**

would be more decisive in attacks and easier for the staff to deal with towns

**Comment by LlmDl** [comment]
Not sure I understand whats being rolled back here? Please explain in detail what you want.

**Comment by ItsJuls** [comment]
The griefing of Towns if that happens/Explosions are forced on so people won't be angry at their town being permanently destroyed after the War
