### ISSUE TITLE
Suggestion: Make '/townyadmin reset' require confirmation

### ISSUE THREAD

**Issue by BeepSterr** [TownyAdvanced/Towny#5829]
### **Please explain your feature request to the best of your abilities:**

Accidentally ran `/townyadmin reset` thinking it would reset all residents/towns/nations but instead... it wiped all config files I /just/ finished setting up.
Would be nice if there was some sort of warning of what the command did before it actually executes...

**Comment by LlmDl** [comment]
This can definitely be set up in the next pre-release. Thanks for Sponsoring also. I'm on a bit of a getaway this weekend but I'm dropping into the Discord every now and then, hopefully I'll catch you on there.
