### ISSUE TITLE
Suggestion: Outpost dynmap markers

### ISSUE THREAD

**Issue by Vanstredam** [TownyAdvanced/Towny#5831]
### **Please explain your feature request to the best of your abilities:**

So for this suggestion, I would like to suggest markers in Dynmap-towny for outposts as people tend to make external areas for settlements in their own towns (often to increase chunks).

It's more of a quality of life suggestion, and how it would work is that it would display the marker as a tower icon (this can be configured) with the name **{town} ({Outpost plot})** [ex: Edinburgh (Fort Albany)]. The name in the parenthesis will be dependent on the outpost plot's name.

**Comment by LlmDl** [comment]
This will likely be part of the MapTowny support instead of Dynmap-Towny.

**Comment by MilesBHuff** [comment]
Huh.  This has been something I've been hoping for for years.  Sad to see it closed.

**Comment by LlmDl** [comment]
Re-opening because of interest by a sponsor.

**Comment by MilesBHuff** [comment]
Thank you @LlmDl!

**Comment by MilesBHuff** [comment]
Thank you!  :D
