### ISSUE TITLE
Suggestion: Auto-expiring invities

### ISSUE THREAD

**Issue by Moldytzu** [TownyAdvanced/Towny#5845]
### **Please explain your feature request to the best of your abilities:**

I hate when I'm trying to recruit and I can't because I've sent too many invites 1 week ago. I have to spam /t invite -<name> which is a very tedious procedure. Make invites expire after 1 hour or after a longer time.

**Comment by gaffy00** [comment]
This exists already. Set `invite_system.expirationtime` in your config.
