### ISSUE TITLE
Everyone can build on player plots

### ISSUE THREAD

**Issue by Thaotter** [TownyAdvanced/Towny#5848]
### What steps will reproduce the problem?

I don´t now what I have done wrong but everyone can build on my plot. And I have done /t set perm off, and /t set perm reset

Don´t know why you closed my report before this one because it isn´t solved

### What is the expected output?

So that the owner of the plot is the only one who can build/destroy on it by default. But that individual players can change it for themselves if they want anything different.

### Towny version

Towny Advanced 0.98.1.0

### Server version

Spigot 1.17

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/xd798Jhq
2. Your Towny config.yml: https://pastebin.com/xxJxDBYN
4. Your townyperms.yml: https://pastebin.com/T8TGdBTK
5. Your log's error: 

(optional) If this is to do with permissions,
6. Your permissions file: https://pastebin.com/Y1e0XQrF

(optional) If this is to do with chat,
7. Your chatconfig.yml:
8. Your channels.yml:

**Comment by LlmDl** [comment]
Are there any Towny nodes in your luckperms? Your permissions file link does not work.

**Comment by Thaotter** [comment]
Didn´t seem to work on pastebin but heres another one i tried
https://controlc.com/ab797075

**Comment by LlmDl** [comment]
You've put a bunch of Towny nodes in your Luck Perms. Remove them all. Towny's permissions are pre-configured in your townyperms.yml file.

**Comment by Thaotter** [comment]
It worked! Thank you!
