### ISSUE TITLE
Outposts not being fully unclaimed

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#5851]
### What steps will reproduce the problem?

1. Claim outpost
2. Unclaim outpost (potentially after restart)
3. Chunk is cleared of claims, but outpost remains and shows in /town and /t outpost teleports to it, even if now wilderness.

### What is the expected output?

Outpost should be removed from the town and be set back to zero outposts.

### Towny version

Towny 0.98.1.0

### Server version

Paper version git-Paper-408 (MC: 1.17.1)

### Please use Pastebin.com to link the following files

- No related errors found in logs

**Comment by LlmDl** [comment]
This is fixed as of 0.98.1.6
