### ISSUE TITLE
Suggestion: Add chat command for admins to toggle the info tool

### ISSUE THREAD

**Issue by gingerchew** [TownyAdvanced/Towny#5875]
### **Please explain your feature request to the best of your abilities:**

I recently needed to put a brick in an item frame. I had to look through all of the mods that are installed on the server to see which one had a *"wand"* item that could be doing it.

I finally found that it was Towny, but the only fix is to change the item. I found the place to change it in the config. It would be nice to have a command to toggle the tool being active. `/towny info toggle` or something similar would solve this. 

This opens up the possibility of other commands: `/towny info` to give an *"info tool"*, then `/towny info toggle|on|off` can turn it on and off.

**Comment by LlmDl** [comment]
It's also possible to deop yourself and put in the item.
