### ISSUE TITLE
Set nodes to false in Townyperms.yml

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/Towny#5879]
### What steps will reproduce the problem?

1. Trying to negate nodes on townyperms.yml
2. 
nomad:
![imagen](https://user-images.githubusercontent.com/91406867/165207949-ac0bcc3b-1091-4ccb-b49f-0747cf89b8ae.png)

town:
 default.
![imagen](https://user-images.githubusercontent.com/91406867/165208059-59de1823-e751-43ce-b242-6368377ea64a.png)

nopassport:
![imagen](https://user-images.githubusercontent.com/91406867/165208093-b6315663-40c1-4a67-9111-833610644d13.png)

3. Citizens with the rank "nopassport" still can using /n spawn on allies and public nations.

### What is the expected output?

Citizens with that rank will not be able to use "/n spawn" on allies and public nations.

### Towny version

0.98.1.7

### Server version

Purpur 1.17.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: Nothing on console
2. Your Towny config.yml: why
3. Your townyperms.yml: I sent important screenshots
4. Your log's error: No errors

(optional) If this is to do with permissions,
5. Your permissions file: ok there u go
[townyperms.zip](https://github.com/TownyAdvanced/Towny/files/8559304/townyperms.zip)

**Comment by Peskdt** [comment]
It works on public nations, but not with allies, I'll still trying. Thanks

**Comment by LlmDl** [comment]
So you've put your nopassport as a town rank, which is assigned before players' nation nodes/nation ranks are given.

This means they're given the false ally/public nodes. Later they are given the default nation nodes which include `  - towny.nation.spawn.ally` and that might be why you're seeing them still able to use ally spawns.

Making the nopassport rank into a nation rank might solve you issue.

**Comment by Peskdt** [comment]
Omg, thanks for the clarification. O thought that last time. I'll check and try later
