### ISSUE TITLE
Alliances of Nations

### ISSUE THREAD

**Issue by Oleksiy13321** [TownyAdvanced/Towny#5881]
### **Please explain your feature request to the best of your abilities:**

Hi, I think it would be a great idea to add military alliances so that you can do something like NATO or other military alliances. you can make a name for them, send invitations to different nations and most importantly fight together through the EventWar plugin

there can also be commands such as 
/alliance create [name] or /a create, 
/a add [nation]
/a kick [nation]
/a joinwar [war] 
/ac[alliance chat]

**Comment by LlmDl** [comment]
The alliance war type is now available as of 0.0.55.
