### ISSUE TITLE
Changing the mayor of a town with /ta set mayor disables upkeep

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#5882]
### What steps will reproduce the problem?

1. Create a town.
2. Set someone else as the mayor of the town with `/ta set mayor`.
3. The town will no longer pay upkeep. The `hasUpkeep` flag is set to false.

![screenshot](https://i.gyazo.com/3ee6ffa62668c5a6b7ec1952fca7ac74.png)

### What is the expected output?

The town should still pay upkeep. 

If that is intended behaviour, however, then it would be useful to have a `/ta` command that toggles upkeep for a town, e.g. `/ta town <town name> toggle upkeep`. We often have to install new mayors for towns on our server, and manually changing the `hasUpkeep` flag for these in the database becomes a hassle.

### Towny version

0.98.1.10

### Server version

Purpur 1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [Link](https://pastebin.com/jRg3pW3L)
2. Your Towny config.yml: [Link](https://pastebin.com/DspHkVvW)
3. Your log's error: No error.

**Comment by LlmDl** [comment]
Can you supply the resident file from towny\data\resident\RESIDENTNAME.txt of the player who was made mayor using the /ta set mayor command?

**Comment by galacticwarrior9** [comment]
[Link](https://pastebin.com/K9pgWQe4)
