### ISSUE TITLE
Towny Town upkeep still at $10

### ISSUE THREAD

**Issue by KjayCopper** [TownyAdvanced/Towny#5884]
### What steps will reproduce the problem?

owning a town and buying more than one plot

### What is the expected output?

per plot add $10 to upkeep

### Towny version

1.98.1.10

### Server version

Paper 312 - MC 1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/kCKBp22M
2. Your Towny config.yml: https://pastebin.com/k1j0SnCX
3. Your townyperms.yml: https://pastebin.com/E3HyBpC1
4. Your log's error: No reported error

**Comment by LlmDl** [comment]
From your config:
```
    # Uses total amount of owned plots to determine upkeep instead of the town level (Number of residents)
    # calculated by (number of claimed plots X price_town_upkeep).
    town_plotbased_upkeep: 'false'
```

You probably want that to be true.
