### ISSUE TITLE
Towny upkeep not being taken from some towns

### ISSUE THREAD

**Issue by BlueFyreMatt** [TownyAdvanced/Towny#5886]
### What steps will reproduce the problem?

Not much is known about the problem at this time. I can see from running Towny in debug that its stating that money was taken from the town bank, however by manually checking the town bank before and after New Day, the amount remained the same. I'm currently unable to identify anything amongst the affected towns that are similar in any way that could be a cause, and with such a large amount of towns its extremely difficult to identify which towns are being taxed and which aren't.

### What is the expected output?

The towns should have paid taxes

### Towny version

Currently running 0.98.1.6, will update to latest and re-check tomorrow.

### Server version

Purpur-1599 (1.18.2)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/MmKGKcuP - I've shown the Towny specific information, I'll happily share more privately but not in a public Github issue.
2. Your Towny config.yml: https://pastebin.com/tsHPrVZu 
3. Your townyperms.yml: https://pastebin.com/phA3jNm0
4. Your log's error: N/A

**Comment by LlmDl** [comment]
pleaes share your towny\logs\money.csv, you may have to get it from your latest towny\backups\*backupfile*

**Comment by BlueFyreMatt** [comment]
[money.csv](https://github.com/TownyAdvanced/Towny/files/8594959/money.csv)

There's the file you requested, I'll also include the backup file below to ensure you have what you need:

[money.csv](https://github.com/TownyAdvanced/Towny/files/8594980/money.csv)

I was also running the debugger at the same time, let me know if you'd like that log. From briefly looking at the money.csv files its showing the money being taken (Take for example Harkendale or Fruitopia City) but for whatever reason its not actually taking it. If you'd like to see for yourself then let me know, I'd happily give read access.

**Comment by LlmDl** [comment]
So the daily taxes will call this:
```java
	public boolean withdraw(double amount, String reason) {
		if (subtractMoney(amount)) {
			notifyObserversWithdraw(this, amount, reason);
			if (TownySettings.getBoolean(ConfigNodes.ECO_CLOSED_ECONOMY_ENABLED))
				return payToServer(amount, reason);

			return true;
		}
		
		return false;
	}
```
It is the `notifyObserversWithdraw(this, amount, reason);` that is logging to the money.csv.

The only way that runs is if `if (subtractMoney(amount))` which is ultimately decided by what Vault tells us your economy plugin via this `TownyEconomyHandler.subtract(getName(), amount, world);` which is only run after we've checked that the account can pay. So in your case we know that Vault told us the withdrawal was successful otherwise we would not be logging it, and the town would be going bankrupt or deleted.

I am sorry to say, this is likely on the economy plugin's side of things. You are using EssEco which is not recommended anyways.

**Comment by BlueFyreMatt** [comment]
Unfortunate but I knew there would be a slim chance thats the case. I don't suppose there's any open source alternatives you recommend using with towny instead of Essentials? I say open source so we can make some modifications to import all the EssEco data.

TownyAdvanced/TownyEco when?;)

**Comment by LlmDl** [comment]
I am already underpaid enough that actively developing an economy plugin is basically out of the question.

I do maintain iconomy5, I recommend using TheNewEconomy. It can convert from Esseco apparently.
