### ISSUE TITLE
EventWar homeblock switching towns bug

### ISSUE THREAD

**Issue by darthpeti** [TownyAdvanced/Towny#5895]
### What steps will reproduce the problem?

1. declare a nation war on a nation
2. conquer townblocks until you reach the homeblock
3. successfully "conquer" the homeblock

### What is the expected output?

The homeblock is not supposed to be conquered and the town should just get kicked out of the war i think?

### Towny version

0.98.1.10 and eventwar 0.0.44

### Server version

purpur 1609 1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml: https://bin.bloom.host/atedugireh (eventwar config) 
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Closing, as the homeblock is meant to switch sides too.
