### ISSUE TITLE
Tamed Wolves Not Being Hittable During PVP

### ISSUE THREAD

**Issue by imbennji** [TownyAdvanced/Towny#5896]
### What steps will reproduce the problem?

1. be in a town claimed area
2. have a player apart of that town tame a wolf
3. have someone separate from that town try and hit the tamed wolf
4. have someone separate from that town try and hit the owner than the tamed wolf
5. No wolves take damage, even when aggro

### What is the expected output?

I want the tamed wolves to be hittable during pvp or in general. like how you can set certain mobs or animals to be protected by towny in the config, but I want to be able to set tamed wolves to be either protected or not in my case not protected.

### Towny version

Towny-0.97.0.0 for 1.12.2.jar

### Server version

1.12.2 spigot (with viaversion)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/sRWAAmcP
2. Your Towny config.yml: https://pastebin.com/duUddd7G
3. Your townyperms.yml: https://pastebin.com/RyP5AHJn
4. Your log's error: No Log Error

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
Is this reproducible on the latest release/pre-release?
