### ISSUE TITLE
Suggestion: Spawn point ring drawing is very unoptimized

### ISSUE THREAD

**Issue by Heliosares** [TownyAdvanced/Towny#5899]
### **Please explain your feature request to the best of your abilities:**

It looks like SpawnPoint#drawParticle() is called for every single spawn point in memory, regardless of whether or not it's loaded. This is resulting in about 10k synchronous tasks being scheduled on my server. Seems inefficient. I've disabled the spawn point ring because of it, but given it's something enabled by default it might be worth optimizing.

**Comment by LlmDl** [comment]
Have you got any timings showing the 10k tasks?
