### ISSUE TITLE
Error when player has no city in TAB

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#5911]
### What steps will reproduce the problem?

Set the placeholder %townyadvanced_town% in the tab above the player, through the TAB plugin, in this case, after the player enters now, there will be an error, the screenshot of which is shown below

### What is the expected output?

No error

### Towny version

Towny-0.98.1.0

### Server version

paper 1.17.1 build 409

### Please use Pastebin.com to link the following files

(https://pastebin.com/prWPRDYn)

**Comment by LlmDl** [comment]
Missing the config and startup and all the other things a bug ticket asks for.

**Comment by 1Pootis1** [comment]
1. Your full server startup from the logs\latest.log: https://pastebin.com/syS8KnnV
2. Your Towny config.yml: https://pastebin.com/argBczeA
3. Your townyperms.yml: https://pastebin.com/GY70hhTX
4. Your log's error: https://pastebin.com/prWPRDYn

(optional) If this is to do with permissions,
5. Your permissions file: -

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/ibSZRQc3
7. Your channels.yml: https://pastebin.com/8q4KjbF9

**Comment by LlmDl** [comment]
It is failing to load a translation used in the placeholder, and you're only allowing ru-RU in your languages so you're probably using an incomplete ru-RU.yml in your towny\settings\lang\override\ folder. Please supply your ru-RU.yml.
