### ISSUE TITLE
Suggestion: Towny advertisement to Discord GUI Feature 

### ISSUE THREAD

**Issue by celticpixie14** [TownyAdvanced/Towny#5916]
### **Please explain your feature request to the best of your abilities:**

I may explain this badly so apologies in advance. I recently had a player suggest the idea of being able to advertise towns via discord. I thought this was a good idea but would be even better if it were implemented in game via the plugin itself. Would it make sense to add some kind of GUI option to advertise a town and it's features/ideas in order to attract new players towards specific towns?

**Comment by LlmDl** [comment]
Might be something to put into another plugin. Not super interested in it myself.
