### ISSUE TITLE
Suggestion: Add following strings to translation file

### ISSUE THREAD

**Issue by martin-desktops** [TownyAdvanced/Towny#5920]
### **Please explain your feature request to the best of your abilities:**

Hello, I convert Towny to Polish and I wish the following strings were translatable, so that language consistency would be better.

1. Word "Wilderness" in placeholders
2. [Towny] Usage [command]
3. [Towny] Eg: [command] [syntax]

**Comment by LlmDl** [comment]
The wilderness name is set in the world. It is not translatable.

The other thing is probably something I could search around and find. Any list of where the Usage/Eg's are being used?

**Comment by martin-desktops** [comment]
You can get these return messages by respectively executing following commands:

 [Towny] Usage [command]: 	`/t join`
[Towny] Eg: [command] [invalid syntax]: 	`/t outlaw InvalidSyntax`

Besides that, there is also a message for `"/t bankhistory"` - "No pages to display!", which is also untranslatable.
