### ISSUE TITLE
Towny not working after the server restarted

### ISSUE THREAD

**Issue by MattGold-5829** [TownyAdvanced/Towny#5932]
### What steps will reproduce the problem?

I don't know of any steps to reproduce, Towny randomly stopped working after a server restart.

### What is the expected output?

For the Plugin to work, it throws internal errors when any Towny command is ran.

### Towny version

0.98.2.0

### Server version

Paper 1.18.2, Build 350

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/acqygApU
2. Your Towny config.yml: https://pastebin.com/7Q72gcpX
3. Your townyperms.yml: https://pastebin.com/hBKQSf2b
4. Your log's error: https://pastebin.com/f3AzvE2x

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
The portion of your startup log that would have been useful is missing.

**Comment by MattGold-5829** [comment]
It's been fixed, something was wrong with config
