### ISSUE TITLE
Suggestion: Add an option to disable or enable fire spread in wilderness.

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#5951]
### **Please explain your feature request to the best of your abilities:**

As the title says, I would suggest adding a config option to disable or enable fire spread in wilderness. The reason for this is that as it is right now, at least from what I've found, you can either choose to have fire spread enabled in wilderness and toggleable in towns, or have fire spread disabled everywhere. There is currently no way to have fire spread disabled in wilderness but toggleable in towns.

**Comment by LlmDl** [comment]
Pretty sure that the town-land is independent of the wilderness already:
```java
	/**
	 * Towny's primary internal test to determine if something can burn
	 * at the given location, based on Towny's plot permissions.
	 * 
	 * @param block - Block being tested.
	 * @return true if the burn is allowed.
	 */
	private static boolean isAllowedBurn(Block block) {
		TownyWorld townyWorld = TownyAPI.getInstance().getTownyWorld(block.getWorld().getName());
			
		/*
		 *  Something being ignited in the wilderness.
		 */
		if (TownyAPI.getInstance().isWilderness(block)) {
			if (isNotPortal(block) && isNotCandle(block) && isNotCampfire(block) && (!townyWorld.isForceFire() && !townyWorld.isFire()))
				// Disallow because it is not above obsidian and neither Fire option is true.
				return false;

		/*
		 *  Something being ignited in a town.
		 */
		} else {
			if ((isNotPortal(block) && isNotCandle(block) && isNotCampfire(block) && isNotFireSpreadBypassMat(block))          // Allows for NetherPortal/Netherrack/Soul_Sand/Soul_Soil ignition.
			&& (!townyWorld.isForceFire() && !TownyAPI.getInstance().getTownBlock(block.getLocation()).getPermissions().fire)) // Normal fire rules. 
				// Disallow because it is not above obsidian or on a FireSpreadBypassMat, and neither Fire option is true.
				return false;
		}

		// Fire is allowed here.
		return true;
	}
```

In town it only checks to see if the world is forcing file on at the location.

**Comment by Wextra** [comment]
Well from when I tested with having fire spread disabled on the server/through worldguard, it would also not work inside of towns even if toggled enabled. If I instead had it enabled on the server, towns could indeed toggle, but fire spread would then also be permanently enabled in the wilderness, allowing for players to excessively grief.

**Comment by LlmDl** [comment]
Don't use WG to disable fire. Towny doesn't override WG anywhere.

**Comment by LlmDl** [comment]
Use the /tw toggle fire option to disable fire in the wild.

**Comment by Wextra** [comment]
Alright, thank you for the swift answers. I will try it out and see what happens. Fire spread should be allowed in WG then as well I suppose?

**Comment by Wextra** [comment]
Yup, that solved it. Thank you!

**Comment by LlmDl** [comment]
Yes, you don't really want WG global regions in your Towny world doing things that Towny is already doing.
