### ISSUE TITLE
Suggestion: Entity removal upon town unclaim/deletion

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#5953]
### **Please explain your feature request to the best of your abilities:**

Currently the delete upon unclaim and regeneration for towns seem to only support blocks, but this leaves things likes armor stands, end crystals, animals and unremoved mobs out of the removals.

It leaves nasty looking floating armor stands, end crystals and mass animal farms behind even after the town is deleted and regenerated back to wild.
 
However, entities that are underground seem to still get replaced by the regeneration system when it restores the mined blocks and animals may suffocate too, which is good in this regard.

I think if possible, it would be great if Towny would support removal of such entities as well.

**Comment by LlmDl** [comment]
Have you tried putting them in to the world's plotManagementDeleteIds?

**Comment by LlmDl** [comment]
END_CRYSTAL and ARMOR_STAND would be the materials to try.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/6a27132128d4fbc1fedd7f7416318d5a2a03152f is going to be used for this
