### ISSUE TITLE
Suggestion: Option for disabling numbers in town and nation names.

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#5954]
### **Please explain your feature request to the best of your abilities:**

As mentioned in the title, I would suggest adding an option for disabling numbers in town and nation names. The only way to do it right now is to remove numbers from the regex, which does however instead result in different parts of towny not working.

**Comment by GNosii** [comment]
What do you mean by "different parts of Towny not working"? You shouldn't really have any issues with that, it would be nice if you could elaborate on it, that way we can also help you with your suggestion
