### ISSUE TITLE
Issue with "own_town_and_wilderness_limited_commands"

### ISSUE THREAD

**Issue by sh1mrr4** [TownyAdvanced/Towny#5958]
### What steps will reproduce the problem?

1. Set up a server with with towny (default config)
2. Remove sethome,home from "player_owned_plot_limited_commands", but leave it for "own_town_and_wilderness_limited_commands"
3. Create a new town with one player account.
4. Enter that town with a separate account and try to run one of the blocked commands.
5. The commands should work inside the town (e.g. /sethome).

### What is the expected output?

If I understood that setting correctly, players should be able to run those blocked commands in the wilderness and their own towns, but not other towns. However, in this case "own_town_and_wilderness_limited_commands" doesn't seem to have any effect.

### Towny version

0.98.2.0

### Server version

Paper 1.18 - 379

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/aFgfUBek
2. Your Towny config.yml: https://pastebin.com/FCkK1ZD5
3. Your townyperms.yml: https://pastebin.com/vzhZhB3B

**Comment by LlmDl** [comment]
As per the comments:
```
    # This allows the usage of blacklisted commands only in the player's town 
    # and the wilderness (essentially blocking commands from being ran by tourists/visitors)
    # Players with the towny.globally_welcome permission node are not going to be limited by this list.
    # Commands have to be on town_command_blacklisting.town_blacklisted_commands, else this is not going to be checked.
    own_town_and_wilderness_limited_commands: sethome,home,bal
```
You have to also include any of these commands in the town_blacklisted_commands section, which you have left at default.

**Comment by sh1mrr4** [comment]
Oh damn, for some reason I wasn't really able to grasp the concept of removing access to a command in all towns and then reenabling it in the one you belong to... ^^

Sorry for the hassle and thanks a lot for your help :)

**Comment by LlmDl** [comment]
No worries.
