### ISSUE TITLE
Suggestion: /t list by upkeep

### ISSUE THREAD

**Issue by SideLo98** [TownyAdvanced/Towny#5964]
### **Please explain your feature request to the best of your abilities:**

an upkeep sorting option while using /town list by upkeep similar to other sorting options like /t list ruined, bankrupt etc. As some towns in my server doesn't have upkeep probably coz they got reclaimed after being ruined and now they don't pay upkeep anymore even after being reclaimed. So it will help a lot.

**Comment by LlmDl** [comment]
The bug with reclaiming and NPC mayors not setting the correct upkeep value was solved a while ago, so that's nice.
