### ISSUE TITLE
Cannot invoke "java.util.UUID.equals(Object)" because the return value of "com.palmergames.bukkit.towny.object.Town.getUUID()" is null

### ISSUE THREAD

**Issue by AToska21** [TownyAdvanced/Towny#5980]
### What steps will reproduce the problem?

1. Try to set homeblock/claim land
2. Get the error

### What is the expected output?

Homeblock being set correctly

### Towny version

0.98.2.4

### Server version

1.19 Paper (build #8)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/sc8Tf8mr
2. Your Towny config.yml: https://pastebin.com/axNez66J
3. Your townyperms.yml: https://pastebin.com/SsKHuk43
4. Your log's error: https://pastebin.com/JaHLJ6nP

**Comment by LlmDl** [comment]
You're only seeing this when you use /ta town NAME set homeblock?

**Comment by AToska21** [comment]
> You're only seeing this when you use /ta town NAME set homeblock?

No, I see it on anything that requires mayor permissions. I did try messing with the files in data folder to switch mayorship of a town with my friend (he became mayor of mine and I became mayor of his)

**Comment by LlmDl** [comment]
It appears to fail because one of your towns on your server has no UUID, which should not be possible.

How many files are in your towny\data\towns\ folder?

**Comment by AToska21** [comment]
3

**Comment by AToska21** [comment]
the towns have a UUID
`uuid=e9f3f9b7-db32-4d50-a7bd-ee95a2e2233c`

**Comment by AToska21** [comment]
maybe `nationZoneEnabled=true` is a problem, as the town has no nation???

**Comment by LlmDl** [comment]
No, its failing during a search through your server towns to see if your homeblock would be too close to another town's homeblock, and one of those towns has no UUID.

How many towns are seen in `/t list`

**Comment by AToska21** [comment]
> No, its failing during a search through your server towns to see if your homeblock would be too close to another town's homeblock, and one of those towns has no UUID.
> 
> How many towns are seen in `/t list`

There are 3 towns. The town I'm trying to claim territory in is in Europe. (earth map) All the other towns are located in North America.

**Comment by LlmDl** [comment]
Are you absolutely certain all three towns' files have a UUID set?

**Comment by AToska21** [comment]
> Are you absolutely certain all three towns' files have a UUID set?

Yes, I just checked the files.

**Comment by LlmDl** [comment]
using /ta reload db should reload things and hopefully actually set the UUID for the town in question

**Comment by AToska21** [comment]
Oops, found the issue. Setting a town's board from a config does not go well.

**Comment by LlmDl** [comment]
Interesting. Glad its sorted out.

**Comment by AToska21** [comment]
> Interesting. Glad its sorted out.

Whenever you set a town's board the the TXT file, it errors out. You might want to add a warning saying like "don't edit this file you might break stuff."
