### ISSUE TITLE
Merging Towns: Incorrect Math

### ISSUE THREAD

**Issue by lukemango** [TownyAdvanced/Towny#5984]
### What steps will reproduce the problem?

Skip requested by LlmDl

### What is the expected output?

Skip requested by LlmDl

### Towny version

0.98.2.5

### Server version

Paper 1.18.2 - #386

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: Skip requested by LlmDl
2. Your Towny config.yml: https://pastebin.com/y4LNnLvv
3. Your townyperms.yml: Skip requested by LlmDl
4. Your log's error: Skip requested by LlmDl

Attached are the two towns in question.
[Broglandia.txt](https://github.com/TownyAdvanced/Towny/files/8943532/Broglandia.txt)
[ObsidianOrder.txt](https://github.com/TownyAdvanced/Towny/files/8943533/ObsidianOrder.txt)

**Comment by LlmDl** [comment]
False alarm on this one.
