### ISSUE TITLE
Can't teleport to the outpost using the command "/t outpost"

### ISSUE THREAD

**Issue by ClayCoffee** [TownyAdvanced/Towny#5997]
### What steps will reproduce the problem?

1. Claim a outpost
2. /t outpost
3. Index -1 out of bounds for length 0

### What is the expected output?

Teleport to my first outpost

### Towny version

0.98.3.0

### Server version

 This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
This one was spotted by a sponsor on the discord already, its been fixed here: https://cdn.discordapp.com/attachments/581163022874050569/993137759797645512/towny-0.98.3.1.jar
