### ISSUE TITLE
Suggestion: Kills count as within town inside of a radius from a town border.

### ISSUE THREAD

**Issue by Zumodenaranja** [TownyAdvanced/Towny#6003]
### **Please explain your feature request to the best of your abilities:**

Be able to specify a radius from the town borders where if you get killed in the radius it would still count as if you died on the town. This would mean if you have set outlaws to get jailed on death, they would get jailed as well if they died close to your town.

**Comment by MilesBHuff** [comment]
This could be added as a part of the existing nationZones.

**Comment by LlmDl** [comment]
Might be possible, NationZones only exist in the playercache, but the math might be able to be reused.

**Comment by MilesBHuff** [comment]
Was this found to be not possible?

**Comment by LlmDl** [comment]
This one is fairly tricky as we do fire an event for when a player kills a player, and that event is used in other towny plugins. 

The event's location is what is what is used by those plugins, and if its wilderness then that plugin isn't going to account for a nearby town.

It's better if each plugin that has a reason to act upon a nearby death figures out the situation for themselves.
