### ISSUE TITLE
Suggestion: Special permissions for peaceful towns/nations

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#6015]
### **Please explain your feature request to the best of your abilities:**

Currently the only negative side to being peaceful seems to be an extra cost, but I think it could be great if that could be expanded upon more by adding special permissions for towns or nations that are peaceful. 

Such as: negative permission so that peaceful nations cant set an /n enemy or /n ally, or non-peaceful towns not being able to use /t outlaw system, etc. It would be very customizable if we could set any sort of permission to be negative if that town/nation has peaceful status.

If that is something that is possible to do, I think it would help server owners define the line between peaceful and not peaceful better. Even a simple method of achieving this could be an automatic extra peaceful 'rank' for all those in a peaceful town/nation, which could then negate many permissions for players in that town. 

Also another thing I'd like to suggest shortly along with this: certain automatic map color or shade for peaceful towns/nations, which would definitely help it be more obvious to see who is peaceful and who is not.

**Comment by LlmDl** [comment]
I'll have to see about the best way to go about this one, but I think a rank in the townyperms.yml might be the best route and easier on servers than requiring an LP context.
