### ISSUE TITLE
Chat color not formatting correctly

### ISSUE THREAD

**Issue by MorgenFreemen** [TownyAdvanced/Towny#6021]
### What steps will reproduce the problem?

1. Add ChatInjector
2. Add the PAPI placeholder for town names and tags
3. Showing color codes in chat, not coloring

### What is the expected output?

I'm expecting to see colored names of towns and nations

### Towny version

0.98.3.1

### Server version

1.19 paper #61

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/US1VzXvD
2. Your Towny config.yml: https://pastebin.com/3q67niSq
3. Your townyperms.yml: https://pastebin.com/wkSEP6Jh
4. Your log's error: https://imgur.com/a/9gI125M

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/NKZbEqLe
7. Your channels.yml: None?

**Comment by LlmDl** [comment]
This is caused by PAPI no longer formatting colours, it has already been fixed in the upcoming 0.98.3.2.
