### ISSUE TITLE
Not work /t spawn

### ISSUE THREAD

**Issue by StonFlip** [TownyAdvanced/Towny#6023]
### What steps will reproduce the problem?

idk

### What is the expected output?

The /t spawn command does not work on the server. After entering the command, there is no error, just nothing happens. At the same time, if you write /T SPAWN or /towny:town spawn it will work

### Towny version

Towny-0.98.3.0

### Server version

1.16.5

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/k9XidHaC
2. Your Towny config.yml:  https://pastebin.com/1z3iePFa
3. Your townyperms.yml: https://pastebin.com/xPA5KnjU
4. Your log's error: none

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by StonFlip** [comment]
video: https://imgur.com/a/c5YB9zD

**Comment by LlmDl** [comment]
You probably have a plugin stealing the /t command. you can force it to Towny using your server commands.yml.

**Comment by LlmDl** [comment]
It's probably Chatty.
