### ISSUE TITLE
Notifcations not working

### ISSUE THREAD

**Issue by SirKillian** [TownyAdvanced/Towny#6026]
### What steps will reproduce the problem?

When crossing a chunk border, chat, actionbar and/or bossbar notifications don't show.

### What is the expected output?

Notifications to show up.

### Towny version

0.98.3.0

### Server version

Paper 1.19 git-paper-"cd215af" - (build 61)

### Please use Pastebin.com to link the following files

config.yml https://paste.helpch.at/aribacisin.yml
townyperms.yml: https://paste.helpch.at/afifitoned.yml
log's error: no errors show up

**Comment by LlmDl** [comment]
Skipped form. I cannot comment with no information presented.

**Comment by SirKillian** [comment]
> Skipped form. I cannot comment with no information presented.

Updated issue with full configs.

**Comment by LlmDl** [comment]
You need this true:
```
  # Enables the [~Home] message.
  # If false it will make it harder for enemies to find the home block during a war
  show_town_notifications: 'false'
  ```
