### ISSUE TITLE
Problems with GemsEconomy (maybe easy to fix this time)

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/Towny#6030]
### What steps will reproduce the problem?

If I'm not wrong, this issue is similar to #6010 .

This time I was trying to create a nation, then a similar NPE was thrown.
While the NPE was thrown, the nation was created successfully in the meantime but there is no notification or broadcast in the chat saying my nation was created.

### What is the expected output?

There should be no NPE

### Towny version

0.98.3.2

### Server version

Purpur 1.19

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastes.dev/IWjmuZrJR3
2. Your Towny config.yml: https://pastebin.com/ZUuQ6ZT8
3. Your townyperms.yml: https://pastebin.com/PZNkktxx
4. Your log's error: https://pastes.dev/K0kNvHO3MB

(optional) If this is to do with permissions,
6. Your permissions file:

(optional) If this is to do with chat,
7. Your chatconfig.yml:
8. Your channels.yml:

**Comment by LlmDl** [comment]
This is really an issue on GemsEconomy's end, they undid the pull request I put in to their repo.

I made a comment here: https://github.com/Ghost-chu/GemsEconomy/commit/93f7d1f8cebcf962e5d734131a5b907c8539ac18#r77919974

**Comment by Akiranya** [comment]
Thanks for the quick reply! If you remember, I restored the PR you made and I'm using the own-made GemsEconomy last time the remaing bug was fixed. Do you have any idea how this NPE happened this time?

**Comment by LlmDl** [comment]
Got a link to your source?

**Comment by LlmDl** [comment]
Looks fine to me at a glance, it is creating the new Account async, maybe Towny is asking for the balance before GE was done making the account?

**Comment by Akiranya** [comment]
I thought of that too! but I think it's not easy for Towny to pass a callback to the async method of GemsEconomy (as it would make the Vault hook of Towny so boilerplate) I'll try to make it sync and see if it works. I'll let you know when it's done. Thanks for your time.

**Comment by Akiranya** [comment]
I fixed this bug on GemsEco's side. The way that towny gets an economy account by NAME (including non-player name, eg. towns, nations) assumes that the eco plugin will always return a valid account even if the account does not exist in the eco plugin database. However, asking for an account by name (i.e. using getAccount method of GemsEco) doesn't make GemsEco automatically create the account if not existing.

Now the GemsEco will create an account if the requested account name does not exist. This fixed this issue.

**Comment by LlmDl** [comment]
Good to hear, hopefully the GE author will accept a pull request fixing this.
