### ISSUE TITLE
Conversion = 'to'

### ISSUE THREAD

**Issue by dandyjay** [TownyAdvanced/Towny#6036]
### What steps will reproduce the problem?

1. type one of many commands (/t deposit, /t set taxes, among others)
2. command functions properly, but in chat this message is returned: 
![image](https://user-images.githubusercontent.com/62490812/179675468-8f00cb3a-6b10-4e8e-b424-4e9d4125f7c9.png)

### What is the expected output?

proper command response

### Towny version

0.98.3.2

### Server version

paper 1.18.2 build number 380

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/1363JaWL
2. Your Towny config.yml: https://pastebin.com/RHE6zRyy
3. Your townyperms.yml: https://pastebin.com/87PnR0Sp
4. Your log's error: N/A no error thrown in console

(optional) If this is to do with permissions,
5. Your permissions file: N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml: not using towny chat
7. Your channels.yml: not using towny chat

**Comment by dandyjay** [comment]
there's also a strange lack of messages for certain commands, i.e. in console:
19.07 21:09:27 [Server] INFO KA1ZEN_ issued server command: /towny:t invite accept DANDYCORP
19.07 21:09:27 [Server] INFO [Nation Msg] DANDYCORP: The town of Porkalorpolis joined the nation!
but in game:
![image](https://user-images.githubusercontent.com/62490812/179849236-02154675-9d7c-41f5-a73f-f02ceccfd173.png)
nothing

**Comment by dandyjay** [comment]
> Show me your language file you changed.

my language files are default except for the global override in which i have
```

# Global language file override file.
# Here you can add your own messages, and they will be applied to each language.
# To add messages for specific languages, copy the file from the reference folder to this one, and alter the messages.

# Messages can be added like so: (hint: remove the # to uncomment it)
default_towny_prefix: '&8&l[&#8200ff&lBITREALM&8&l] &b'
default_town_prefix: '&8&l[%townyadvanced_town_map_color_hex%%s&8&l] &b'
default_nation_prefix: '&8&l[%townyadvanced_town_map_color_hex%%s&8&l] &b'
msg_err_friendly_fire_disable: ''
```

**Comment by LlmDl** [comment]
Remove the %townyadvanced_town_map_color_hex% from your default_town_prefix and default_nation_prefix. We don't parse placeholders there and that is what is causing your issue. Probably the same thing in your SiegeWar ticket.

**Comment by dandyjay** [comment]
wow, sure enough. cheers.
is there any way to achieve what i'm trying to do with the colored town prefixes based on their dynmap color? i like the ability for players to customize their stuff.

**Comment by LlmDl** [comment]
I don't believe so.
