### ISSUE TITLE
Jail Plot particle still remains despite resetting the plot and unclaiming the land

### ISSUE THREAD

**Issue by HikayatAyat** [TownyAdvanced/Towny#6040]
### What steps will reproduce the problem?

1. Create jail plot with **/plot set jail**

2. Attempt to delete the jail plot with **/plot set reset** 

3. Failed to remove jail particle spawn. Proceeded to use **/t unclaim**

4. Jail plot particle still remains
![2022-07-20_12 33 06](https://user-images.githubusercontent.com/109643174/179897596-c226ea0b-9b11-423d-925c-c190754d418e.png)

5. Move jail plot to different chunk. Successful in changing plot as new particle appears in new chunk.
![2022-07-20_11 56 58](https://user-images.githubusercontent.com/109643174/179897640-3d63ed04-0913-4f1a-b866-7503599166b1.png)

6. Test by jailing player with **/t jail**

7. Command failed to transport jailed player to new jail plot.  Jailed player is transported to the old jail plot.

### What is the expected output?

1. Old jail plot should be deleted/cleared with /plot set reset or /t unclaim. Jail particle should also be removed upon clearing/resetting the plot.

2. Jailed players should be transported to new jail chunk instead of the old chunk.

### Towny version

0.98.3.0

### Server version

1.19

### Please use Pastebin.com to link the following files

Hi it's my first time reporting a bug in this forum, so I hope the documents are all in order. May I request the following files be kept secret? Please dispose/delete them after the issue is resolved. Have uploaded the requested files according to the supported documents GitHub requested below. Hope this helps.

1. Your full server startup from the logs\latest.log:
https://pastebin.com/bM5p55vh

2. Your Towny config.yml:
https://pastebin.com/YTABTcMU

4. Your townyperms.yml:
https://pastebin.com/dbgZitqi

5. Your log's error:
https://pastebin.com/QmGhL1Ds

**Comment by HikayatAyat** [comment]
Hi thanks for the reply. I asked a player to recreate but the issue still persist. Looking at the logs, no error has popped out. 

I have magnified to the following lines where they did /plot set reset. 
https://pastebin.com/wCtyjCwb

**Comment by HikayatAyat** [comment]
Found it. These are the only lines in the folder given. Hope it helps.
https://pastebin.com/2m4NWpss

**Comment by LlmDl** [comment]
Good stuff, I could not find anything that would interrupt the deleting of the jail.
