### ISSUE TITLE
Suggestion: Make Plot Taxes a source of revenue for players rather than revenue for the town bank.

### ISSUE THREAD

**Issue by Duergur** [TownyAdvanced/Towny#6047]
### **Please explain your feature request to the best of your abilities:**

I want to create a source of revenue for players based on building things like farms and inns and setting them as towny plots. 
Rather than the towny plot tax being paid by the owner of the plot to the town bank, I want the town bank (server bank if possible) to pay the towny plot tax out to the plot owner. 

So like setting negative upkeep for a town pays out to town members, a negative tax per special plot would pay out to the player rather than take money from the player.

**Comment by MilesBHuff** [comment]
This would have to only be allowed when there is a negative plot upkeep.  Otherwise, players would be taxed by themselves.
