### ISSUE TITLE
Outposts in another world.

### ISSUE THREAD

**Issue by incristi1** [TownyAdvanced/Towny#6057]
### What steps will reproduce the problem?

Don't know the problem to reproduce this.
"you can only outposts in your homeblocks world"

### What is the expected output?

Outposts should be claimable in another world.

### Towny version

0.98.2.0

### Server version

1.18.2

### Please use Pastebin.com to link the following files

https://pastebin.com/CZZHyVSW - config
https://pastebin.com/NfcdqLQq - perms

**Comment by LlmDl** [comment]
```
  # Set to 0 to disable. When above 0 an outpost may only be claimed within the given number of townblocks from a townblock owned by the town.
  # Setting this to any value above 0 will stop outposts being made off-world from the town's homeworld.
  # Do not set lower than min_distance_for_outpost_from_plot above.
  max_distance_for_outpost_from_town_plot: '30'
  ```
