### ISSUE TITLE
Suggestion: Allow /plot set name to be used while plot is in a plot group

### ISSUE THREAD

**Issue by Warriorrrr** [TownyAdvanced/Towny#6059]
### **Please explain your feature request to the best of your abilities:**

Plot name is a seperate thing from plot group name, but can't be changed if a plot is in a group due to all /plot set subcommands being blocked. This also affects any api-registered set/toggle subcommands.

**Comment by MilesBHuff** [comment]
There's a workaround for this:  remove the plot from the group, set a name, then re-add.  But this is of course not ideal.
I have been desiring this feature now for quite some time.
