### ISSUE TITLE
Suggestion: Add option to allow public town spawns only for people who have visited that town

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#6063]
### **Please explain your feature request to the best of your abilities:**

A problem I've been noticing on servers is that people tend to play the game as lazily as possible, often constantly just relying on public _/t spawns_ or _/tpa_ commands. I'm not really a fan of making it so you have to travel everywhere with no means of fast travel, but I thought of this cool idea that could probably work well in the plugin.

I've been playing a lot of Elden Ring recently and I thought of a cool idea that could be added to Towny itself similar to how Graces work in the game: **An option that logs people who have visited a town**, that way you would actually have to travel to a town in order to gain _/t spawn_ access to it.

It would help reduce the amount of town camping toxic PvPers do where they find a random public town and harass the owners of it.

Bonus: Maybe also add it to people who run _/t join_ or _/t invite accept_, that way people actually have to visit the town in order to join it, which helps prevent a lot of town hopping.

**Comment by LlmDl** [comment]
I like it.

**Comment by ARR4NN** [comment]
This could be an addon. I might take a look later.

**Comment by o7-hmoe** [comment]
I like this idea, I just see lots of potential issues with other teleporting plugins, such as essentials /home and /tpa

**Comment by ItsJuls** [comment]
I could try this

**Comment by MilesBHuff** [comment]
This would be a great replacement for SettleScape's current solution, which was to restrict Wanderers from teleporting to towns at all.

**Comment by LlmDl** [comment]
This is now a thing: TownyWayPointTravel is a plugin available to my sponsors!
