### ISSUE TITLE
Option to prevent people from claiming in a straight line

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#6080]
### **Please explain your feature request to the best of your abilities:**

One major problem I’ve noticed on many servers is the fact that some people make long snake like claims that look ugly on Dynmaps.

I thought a good idea to mitigate this is to maybe make it so after claiming about two chunks in one direction, you have to claim in other adjacent chunks as to fill in your claims in order to make them more circular/square.

**Comment by JKJameson** [comment]
This would also prevent people from claiming large perimeters to auto-fill for free.

example...
![image](https://user-images.githubusercontent.com/275770/217844664-9caa71e3-06cf-4457-8fa7-eab7aaa73212.png)

![image](https://user-images.githubusercontent.com/275770/217844831-d60983b1-aa3e-4801-9c23-911892066cec.png)

**Comment by LlmDl** [comment]
Those perimeters don't actually auto-fill for free. That's just a limitation of how dynmap-towny renders donuts.
