### ISSUE TITLE
Suggestion: Make /town list better

### ISSUE THREAD

**Issue by th3lucas** [TownyAdvanced/Towny#6085]
### **Please explain your feature request to the best of your abilities:**

I want the /town list command to be more usefull. I have a few ideas for that:

- [ ] Toggle if towns with debt should be displays in "/town list" (fight inactive towns without deleting them)
- [x] Make a "/town list inactive/debt" for all towns with debt

- [ ] Display more information in /town list (all settings should be toggle in config)
Example:
TOWN NAME - Town Level - Mayor - Citizens: 69 -  Tax: 5% - open/closed
If these are too much information you could display them in a hover menu
open closed status could be displayd with a colored town name for example

**Comment by LlmDl** [comment]
The second is already available via /t list by bankrupt.
