### ISSUE TITLE
Suggestion: Toggle tax percentage for nations as well as towns

### ISSUE THREAD

**Issue by Xyoron** [TownyAdvanced/Towny#6106]
### **Please explain your feature request to the best of your abilities:**

You can enable percentage based taxes for towns doing /t toggle taxpercent but /n toggle nationtaxpercent isn't a thing for some reason.

**Comment by Caleston** [comment]
This could be good in preventing towns from constantly being kicked from nations as well, as percentage tax won't kick but still lets towns contribute something.

**Comment by PainOchoco** [comment]
Please assign me to this issue I can work on that
