### ISSUE TITLE
Suggestion: Monospaced ASCII map

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#6114]
### **Please explain your feature request to the best of your abilities:**

It would be awesome if the ASCII map were monospaced.  However, I'm not sure Minecraft has a monospaced font option.  So, as an alternative, you could change the existing symbology to use [fullwidth letters](https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)#Block), which would have the effect of making the map monospaced, without requiring a special monospaced font.

I would do this in my own config, but not all the symbols in the ASCII map are customizable; see #6113.

**Comment by LlmDl** [comment]
![2022-08-15_14 19 35](https://user-images.githubusercontent.com/879756/184702381-c562b6d7-13b9-43f2-b7d3-fd142c5c3081.png)
 Seems to be some-what possible.

**Comment by MilesBHuff** [comment]
Currently it's possible to "monospace" (use fullwidth characters for) all of the configurable symbols.  But not all of the symbols are configurable (see #6113).

**Comment by LlmDl** [comment]
![2022-08-15_14 28 49](https://user-images.githubusercontent.com/879756/184703808-2bbdca84-bb9d-4b84-b9c2-b94f5624887f.png)
I've made it so that it can read in unicode characters. It can get pretty messy depending on what you use.

**Comment by MilesBHuff** [comment]
Yeah, it going partial fullwidth and proportional is not going to look good.  It really has to be all one or the other.

**Comment by LlmDl** [comment]
I am making it possible to use unicode. I don't have the time to go hunting down all the symbols. If you manage to find a character set that doesn't make it look terrible and go over the allowable linewidths, let me know.

**Comment by MilesBHuff** [comment]
@LlmDl See below:

**Proportional:**
> \---------------------------
> \----------CHJ+-------------
> \---------++A+J+------------
> \---+H+-----++I+------------
> \---+++------+++------------
> \---+++-----++++------------
> \---------------------------

**True monospace:**
```
---------------------------
----------CHJ+-------------
---------++A+J+------------
---+H+-----++I+------------
---+++------+++------------
---+++-----++++------------
---------------------------
```

**Fullwidth:**
> －－－－－－－－－－－－－－－－－－－－－－－－－－－
> －－－－－－－－－－ＣＨＪ＋－－－－－－－－－－－－－
> －－－－－－－－－＋＋Ａ＋Ｊ＋－－－－－－－－－－－－
> －－－＋Ｈ＋－－－－－＋＋Ｉ＋－－－－－－－－－－－－
> －－－＋＋＋－－－－－－＋＋＋－－－－－－－－－－－－
> －－－＋＋＋－－－－－＋＋＋＋－－－－－－－－－－－－
> －－－－－－－－－－－－－－－－－－－－－－－－－－－

**Comment by LlmDl** [comment]
I understand it fully, I just don't have the time to get that done today. Monospace would be best, probably not cause linebreak issues.

**Comment by MilesBHuff** [comment]
Ah, got it -- thanks for the clarification.
What can I do to help you?

**Comment by LlmDl** [comment]
Ideally if you can find a monospaced character set: I would take your characters and probably make it the towny default. The only one that really sets things askew is the Inn plot I, which isn't as wide as other chars. 

You can try it out here:
https://cdn.discordapp.com/attachments/669247087329673228/1008824955565252618/towny-0.98.3.6.jar

use \uFF02 to drop in unicode characters if you'd like

**Comment by MilesBHuff** [comment]
Ah, if it's just the characters you need, I gave an example of them (with the Ｉ) in the fullwidth example above:
－－－－－－－－－－－－－－－－－－－－－－－－－－－
－－－－－－－－－－ＣＨＪ＋－－－－－－－－－－－－－
－－－－－－－－－＋＋Ａ＋Ｊ＋－－－－－－－－－－－－
－－－＋Ｈ＋－－－－－＋＋Ｉ＋－－－－－－－－－－－－
－－－＋＋＋－－－－－－＋＋＋－－－－－－－－－－－－
－－－＋＋＋－－－－－＋＋＋＋－－－－－－－－－－－－
－－－－－－－－－－－－－－－－－－－－－－－－－－－
The above is not in a code block at all -- it is just a collection of Unicode symbols, and every one of them has the same width.

**A list of all fullwidth symbols needed to complete the ASCII map:**
- Home:  `Ｈ` (\uFF28)
- For Sale:  `＄` (\uFF04)
- Wilderness:  `－` (\uFF0D)
- Default:  `＋` (\uFF0B)
- Shop:  `Ｃ` (\uFF23)
- Arena:  `Ａ` (\uFF21)
- Embassy:  `Ｅ` (\uFF25)
- Wilds:  `Ｗ` (\uFF37)
- Inn:  `Ｉ` (\uFF29)
- Jail:  `Ｊ` (\uFF2A)
- Farm:  `Ｆ` (\uFF26)
- Bank:  `Ｂ` (\uFF22)

**Comment by LlmDl** [comment]
I did use that in testing, if you try it out you'll find the full width makes the lines too wide to fit in the chat box. I also did not have any luck with \uFF0B for default plots for some reason.

**Comment by MilesBHuff** [comment]
@LlmDl Ahh, I see now -- thanks for the clarification.

I guess one option would be to reduce the width of the map by one or two symbols.  While it would mean a reduced FoV, it would also mean a squarer map and better performance -- so this reduction can be a good thing or a bad thing, depending on point of view.

And huh.  Maybe a different symbol for default plots would work?  `＝` and `＃` seem like a potentially viable options;  alternatively, we could do `＂` for default and `＇` for wilderness.  I wonder why `＋` wouldn't work, though; that's odd.  Minecraft is pretty inconsistent with its unicode support -- I wish it had emojis, because then we could make the textual map quite pretty.

**Comment by LlmDl** [comment]
At this point, the code supports anything unicode so you can play around with it. Note that the home, forsale and wilderness symbols are only loaded at startup/server reload. So do that on a test server.

**Comment by MilesBHuff** [comment]
Got it -- thanks, @LlmDl.  I'll play around with it some, and report back with some screenshots.

**Comment by MilesBHuff** [comment]
@LlmDl 
> The only one that really sets things askew is the Inn plot I, which isn't as wide as other chars.

Side-note:  a really easy fix for that, is just to have Inns be "N" by default, which should be about the same width as the hyphens.
