### ISSUE TITLE
Suggestion: Allow customizing colors of the ASCII map

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#6115]
### **Please explain your feature request to the best of your abilities:**

Several of the current color choices in the ASCII map are not particularly accessible;  and even if they were, it would still be nice to configure them, as I'm sure each server owner will have their own ideas about the ideal colors for the symbols on the map.

I'd therefore like to suggest that all the symbols' colors are made configurable.

Can be done at the same time as #6113.

**Comment by MilesBHuff** [comment]
Does the closing of this issue imply that #6113 will also be closed?

**Comment by LlmDl** [comment]
#6113 was already closed by other PRs, I am re-opening this ticket.

**Comment by MilesBHuff** [comment]
Thank you!
