### ISSUE TITLE
Suggestion: Allow configuring the dimensions of the ASCII map

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#6117]
### **Please explain your feature request to the best of your abilities:**

The ability to configure the width and height of the ASCII map is something I can see use cases for, and not just for my server.

Specifically relating to mine, though:
- I'd like to limit the ASCII map to the server's render distance, just for consistency.  A benefit of this, is that players would know that, if a plot shows in the ASCII map, it's loaded on the server.
- I'd also like to reduce the width from the default so that fullwidth characters will fit (see #6114), thus allowing us to have a monospaced map.

This is not an attempt to change the default width;  just an attempt to get a configurable width/height.
Regarding the default height, though:  It is currently one line less than the full chat height, and should be increased by 1.

**Comment by MilesBHuff** [comment]
Ah, unfortunate;  this would have been a nice feature to have.  Oh well.  Thanks for considering it, at least.

**Comment by LlmDl** [comment]
Ticket being reopened, I'm not sure how quickly I'll get to it as it might be easy/might tricky to implement.

**Comment by MilesBHuff** [comment]
Oh wow!  That was fast!  Thank you!
