### ISSUE TITLE
Internal error on /ta town <town> outpost

### ISSUE THREAD

**Issue by LukeTHadley** [TownyAdvanced/Towny#6120]
### What steps will reproduce the problem?

1. Have a town on a server with an outpost
2. Be OP/have townyadmin level permisions
3. Attempt the command `/ta town <name_of_town> outpost` (with no index given after `outpost`)

### What is the expected output?

A message saying something like `You must enter the index number of the outpost you wish to visit, possible outposts are 1-X...`...

What actually happens is, on a mc client, the full red `An internal error occurred while attempting to perform this command`, console errors with a `ArrayIndexOutOfBoundsException`.

### Towny version

Towny Version: 0.98.3.0

### Server version

Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e294802)

### Please use Pastebin.com to link the following files

Log File: https://pastebin.com/VkzPmBQT

Its just an index out of range error on the arguments list; and unfortunatly I am not willing to give you my full server logs.

**Comment by LukeTHadley** [comment]
> Can you show me the towny\data\towns\townname.txt file of the town you're testing with?

Unfortunatly not no, im guessing because im using a mySQL database. Any ingame command I can do to do a dump of the information i need to a file for you?
In the `towny\data\` direcotry I only have `plot-block-data` folder & `regen.txt`, `snapshot_queue.txt`, `worlds.txt`.

Can also confirm that I was doing other testing of other commands directly after `/ta town <townname>` and a few others are causing internal errors; all `ArrayIndexOutOfBoundsException`'s.

So far:

- `/ta town <TOWN> add`
- `/ta town <TOWN> forcemerge`
- `/ta town <TOWN> rename`
- `/ta town <TOWN> outpost`
All cause the same null/ArrayIndexOutOfRangeExceptions.

`/ta town IOW invite` doesn't error but also doesn't say anything when you don't give a player name, unlike `/ta town IOW kick` which gives me a message `None of thoes names were valid`.

**Comment by LlmDl** [comment]
I'll need to see the town from your mysql db then, namely the outposts column.

**Comment by LukeTHadley** [comment]
Here is a dump of all columns in `TOWNY_TOWNS` (only the town i was testing with)
https://pastebin.com/W0iEZSPT

Also to confirm it isn't just this one individual town, i have tried a splattering of others on my server and they all cause the same errors.

**Comment by LukeTHadley** [comment]
When running `/ta town <TOWN> outpost` on a town that does not have any outposts, it does give a resonse to me
![Screenshot 2022-08-16 at 19 44 42](https://user-images.githubusercontent.com/47950318/184955330-a31ae9c3-a87f-4d15-b52b-c7da6a866e5b.png)

It just seems to be on towns that do have outposts.

My towny config - sorry for not posting it earlier I thought the error would be replicatable <https://pastebin.com/m0zuCaFt>

**Comment by LlmDl** [comment]
Just realized this is already fixed in the pre-releases.

**Comment by LukeTHadley** [comment]
Cool! Thanks for the quick response also. Appreciate it! Have a good day.
