### ISSUE TITLE
Suggestion: (EventWar) More API Features

### ISSUE THREAD

**Issue by JustinDevB** [TownyAdvanced/Towny#6123]
### **Please explain your feature request to the best of your abilities:**

Ability to find out what nation/town started a war through the API Events. Currently the EventWarStartEvent only returns a list of Nations and Towns involved.

Would be nice to have:

Town getWarringTown()
Town getWarredTown()
Nation getWarringNation()
Nation getWarredNation()

Method names can be changed, just a rough idea of what they could look like.

**Comment by LlmDl** [comment]
The War start and end events now include the getDeclarationOfWar from the war, which can be used to figure out who started things.
