### ISSUE TITLE
Using a title prefix as % breaks town chat and leaks TC to general chat in earthPol

### ISSUE THREAD

**Issue by keijodputt** [TownyAdvanced/Towny#6125]
### What steps will reproduce the problem?

1. As a Mayor or role with Mayor perms, do `/t set title (user) %` 
2. Make the user talk in Town Chat

This is leaked to General Chat:
![image](https://user-images.githubusercontent.com/9009579/185766700-97c27ef0-e0a5-437e-a353-d4c830bae501.png)

### What is the expected output?

I expect to see nothing.

### Towny version

0.98.3.5 (up to date at the moment of writing)

### Server version

Purpur 1.18.2: git-Purpur-1632

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/2eu8aVcZ 
2. Your Towny config.yml: https://pastebin.com/txQMYAwN
3. Your townyperms.yml: https://pastebin.com/sSku5yaA
4. Your log's error: There is no error that I could catch.

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/z3KuvKjD
7. Your channels.yml: https://pastebin.com/m2SHc6Mx

**Comment by LlmDl** [comment]
This will be part of TownyChat 0.97.
