### ISSUE TITLE
Gringotts and Towny compatability issues?

### ISSUE THREAD

**Issue by Darklom** [TownyAdvanced/Towny#6148]
**### What steps will reproduce the problem?**

If you either die or try to start a new town an error will be produced.

**### What is the expected output?**

No errors and the ability to create a town.

**### Towny version**

Towny v0.98.3.6

**### Server version**

Paper version git-Paper-135 (MC: 1.19.2)

-----

**1. Your full server startup from the logs\latest.log:**

[Startup](https://controlc.com/2176cead) - Couldn't be pastebin as it said some content was offensive lol.

**3. Your Towny config.yml:**

[Config](https://pastebin.com/vLSWTSdc)

**4. Your townyperms.yml:**

[Townyperms](https://pastebin.com/6QgBwntd)

**6. Your log's error:**

Error 1 - [[05:27:44 ERROR]: Could not pass event PlayerDeathEvent to Towny v0.98.3.6
(optional) If this is to do with permissions,](https://pastebin.com/siWEMERw)

Error 2 - [On /town create test123](https://pastebin.com/QK85HJLc)

**Comment by LlmDl** [comment]
First: thanks for sponsoring today, make sure you mention me in the discord so you can get your Sponsor rank and access to the sponsor plugins.

The error on town creation appears to be on Gringott's end of things. They're trying to get a town that hasn't been created yet or something.

The error on death shows that Towny couldn't associate an EconomyAccount with an Account in Gringotts, which also happen on town creation.

I notice your Gringotts version is 2.12.3 which appears to be unreleased. Gringotts has gone from working, to not working, to working again over the years. You might want to try their released 2.12.2 and see if you fare better. @nikosgram may know if something has changed recently as well.

**Comment by nikosgram** [comment]
Hello 😄 

Indeed, I found some time to work on some issues with gringotts. I'm planning for a stable release within the next weeks. 

Some of the fixed issues are relevant to Towny implementation of gringotts

They are some performance issues that gringotts currently face cause of some legacy sql implementation that is incredibly hard to fix and keep backward compatibility with older versions of gringotts and as you can understand, this is my current priority for the stable release.

So sorry for the inconvenience that this issue caused. I'll try my best to publish a stable release as soon as a solution to the stability issues has been addressed. 

😄

**Comment by LlmDl** [comment]
Thanks @nikosgram, if you haven't seen it already I have been working on a Vault PR which might make all of our lives easier: https://github.com/MilkBowl/VaultAPI/pull/138

**Comment by LlmDl** [comment]
Closing this as Gringotts-Towny is apparently working again.
