### ISSUE TITLE
Suggestion: [EventWar] EventWarDeclareEvent and Cancellable events

### ISSUE THREAD

**Issue by Maroon28** [TownyAdvanced/Towny#6149]
### **Please explain your feature request to the best of your abilities:**

This is just a small suggestion for a minor API tweak for the EventWar API, but it would be nice to make all events cancellable by default so that other plugins could implement checks or other behavior before a war starts. And if possible, a war declaration event since that seems to be the only thing missing from the suite!

**Comment by LlmDl** [comment]
I don't think it would be wise to make all of the events cancellable, things like the war ending and starting should occur.

The new EventWarDeclarationEvent is cancellable however and it will let you prevent wars from starting.
