### ISSUE TITLE
Suggestion: Add more title/subtitle placeholders for the using_titles option

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#6159]
### **Please explain your feature request to the best of your abilities:**

Due to the limitations of the using_titles option in config, I thought it would be neat to suggest a few placeholders to add to the title/subtitle option that could make it cooler.

- {nationname} - Name of the town.
- {nationcapitalname} - Name of the nation, with the "Capital of " prefix (configurable in lang)
- {nation_motd} - Shows the nationboard message.
- {nation_residents} - Shows the number of residents in the nation.
- {nation_residents_online} - Shows the number of nation residents online currently.

**Comment by Jqnnies** [comment]
Also a quick addon to that, allow placeholder names in the titles as well so I can use WorldGuard region names.

**Comment by LlmDl** [comment]
If you can make a new ticket for the placeholder thing, that will take a bit more thought and I cannot complete it right now.
