### ISSUE TITLE
Suggestion: Towny menu customizability

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#6168]
### **Please explain your feature request to the best of your abilities:**

Since the current resident/town/nation menus are hard coded into Towny, I thought it could add to the customizability if you could freely change the aesthetic of the menus without having to fork the plugin to do it yourself.

It could also help with implementing servers with custom calendars or ones that use Minecraft days for the date of a town instead of real life time.

**Comment by LlmDl** [comment]
Are you speaking about the status screens? What menu are you talking about?

**Comment by Jqnnies** [comment]
> Are you speaking about the status screens? What menu are you talking about?

Yeah those, the ones you do when running /res or /t

**Comment by LlmDl** [comment]
Those are already fully customizable, the status screen events allow you to add/remove/modify the Components that make up the status screens.

**Comment by Jqnnies** [comment]
> Those are already fully customizable, the status screen events allow you to add/remove/modify the Components that make up the status screens.

Wait they are? Last time I asked a dev about it they said it was hard coded into Towny.

**Comment by LlmDl** [comment]
Its been customizable for months if not a year now.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commits/master/src/com/palmergames/bukkit/towny/event/statusscreen 

Jan 1 2021

**Comment by Jqnnies** [comment]
How exactly do I change the layout of it though?

**Comment by LlmDl** [comment]
event.getStatusScreen() will get you the StatusScreen object that you can manipulate.
