### ISSUE TITLE
NoSuchFieldError for HONEYCOMB on 1.14.4

### ISSUE THREAD

**Issue by coopyo** [TownyAdvanced/Towny#6170]
### What steps will reproduce the problem?

create new craftbukkit/spigot server 1.14.4
place any item in your hand
to cause exception: punch a block, interact with a block, or destroy a block
view console for error

**Note: I removed all other plugins from my server(dynmap and anti-creeper), excluding townyChat, and the error was still present**

### What is the expected output?

no exceptions for HONEYCOMB blocks, which should not be referenced in this version of MC

### Towny version

error consistently replicated in following versions: 
v.0.98.0
v0.97.5
v.0.98.1

### Server version

craftbukkit version git-bukkit-3405493
consistently replicated error using  git-Spigot-cbd1a1b-3405493

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
[config.txt](https://github.com/TownyAdvanced/Towny/files/9584717/config.txt)

3. Your townyperms.yml:
4. Your log's error:
[serverLog.txt](https://github.com/TownyAdvanced/Towny/files/9584593/serverLog.txt)

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
You should be using version 0.98.1.0 and you will have to modify the TownyPlayerListener's onPlayerInteract method to look like the following on line 336:

```java
				if (item.name() == "HONEYCOMB" && ItemLists.WEATHERABLE_BLOCKS.contains(clickedMat))
					event.setCancelled(!TownyActionEventExecutor.canBuild(player, loc, item));`
```

This will replace the call for Material.HONEYCOMB.

I am no longer supporting 1.14 versions. You should consider using a modern version of MC, there are other bugs left behind in older Towny versions.

**Comment by coopyo** [comment]
@LlmDl Thanks. I would have just fixed it myself, but I saw the other similar bug thread on 1.15, and thought you would have the fix lined up easily.
I will continue using 1.14- Its a world with very few people on a sentimental save for version 1.14, so It will work for us. This just spammed the console and I didnt want to see it anymore. If anything else comes up on this version, Ill fix it myself. Thanks for your help. I do appreciate it... Towny since 2012!

Nick
