### ISSUE TITLE
Suggestion: Change the "king" command fill to "leader"

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#6174]
### **Please explain your feature request to the best of your abilities:**

Not really a big gripe, but I kinda don't like that the leader name in commands is "king" and should be more neutral with something like "leader" instead. This is generally for the servers that have multiple ideologies as king is something more reserved for a monarchy other than a democracy.

**Comment by LlmDl** [comment]
Can you tell me where the king tab completion exists and leader is not an option?

**Comment by Jqnnies** [comment]
> Can you tell me where the king tab completion exists and leader is not an option?

When doing commands that correlate to a nation leader, such as _/n set king_.

**Comment by LlmDl** [comment]
Anywhere that king is offered as a tab complete, Towny also offers leader. This was a change made in 0.98.2.0: https://github.com/TownyAdvanced/Towny/pull/5865

**Comment by Jqnnies** [comment]
> Anywhere that king is offered as a tab complete, Towny also offers leader. This was a change made in 0.98.2.0: #5865

Thank you! I've been looking for this for so long!
