### ISSUE TITLE
If i try to make new town, console says "An internal error occurred while attempting to perfom this command"

### ISSUE THREAD

**Issue by 9wh** [TownyAdvanced/Towny#6175]
### What steps will reproduce the problem?

exclute /town new [randomname]

### What is the expected output?

A new town was made

### Towny version

0.93.3.8

### Server version

paper bukkit 1.19.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:https://pastebin.com/JvUmAq7s
2. Your Towny config.yml:https://pastebin.com/LXnCXPP8
3. Your townyperms.yml:https://pastebin.com/52pJtfNQ
4. Your log's error:https://pastebin.com/WcgswG6G

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
LiteEco is known to not work with Towny. Their Vault implementation is probably incomplete. 

Choose another economy plugin.
