### ISSUE TITLE
TownPreUnclaimEvent cancellation message is not sent, user is not informed of failure  

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#6178]
### What steps will reproduce the problem?

1. Write a listener for TownPreUnclaimEvent that cancels the event and sets a cancellation message.
2. Join a town, go to a claimed townblock and type `/t unclaim`.

You will see the following message, which misleads the player into thinking the townblock was successfully unclaimed:

![image](https://i.gyazo.com/8a08bcda0089ec6aa156ab207d564352.png)

The user is not sent the cancellation message. It is actually sent to the console:

![image](https://i.gyazo.com/e1f266ca2b2e979ea6bb4c89ae71e8c0.png)

### What is the expected output?

The user is not told that the townblock was successfully unclaimed. Instead, the cancellation message is sent to them.

### Towny version

0.98.3.5

### Server version

Paper 1.19.2

**Comment by LlmDl** [comment]
I took a look into this and the event you're listening to is called from the DatabaseHandler, and is called under many scenarios that don't involve a player.

You probably want to use the TownPreUnclaimCmdEvent which is able to send a cancellation message to the unclaiming player.

**Comment by galacticwarrior9** [comment]
You're right, thank you
