### ISSUE TITLE
User not registered magma server

### ISSUE THREAD

**Issue by Mick162534** [TownyAdvanced/Towny#6184]
### What steps will reproduce the problem?

Im running a server on magma1.12.2 with ftb modpack revelation 3.6
I have only towny installed(or with essentials and vault)
When I try /t new arandomtownname 
I get returned with (user is not registered)

### What is the expected output?

A town to be created

### Towny version

0.97.0.0

### Server version

Magma And mc 1.12.2

### Please use Pastebin.com to link the following files

[towny.log](https://github.com/TownyAdvanced/Towny/files/9621555/towny.log)
[latest.log](https://github.com/TownyAdvanced/Towny/files/9621556/latest.log)

**Comment by LlmDl** [comment]
Towny will attempt to register players when they log in. There is an error in your startup from TownyChat when your player joins.

My guess is the same sort of thing has prevented you from being registered.

**Comment by Mick162534** [comment]
Thanks alot for checking up So a workaround would be turning towny chat off and using another chat plugin maybe  ?
