### ISSUE TITLE
Suggestion: Fallen town chunks begin to decay

### ISSUE THREAD

**Issue by Vanstredam** [TownyAdvanced/Towny#6192]
### **Please explain your feature request to the best of your abilities:**

I've been tampering a bit with the town revert system, and I've not been getting a lot of satisfactory results with it.

So I wonder if it's possible for a decay event to occur after a town falls rather than the reverting, whereas when a town is unclaimed, blocks and the architecture around it begin to fall into ruin, rolling back some terrain and even ores but having the structures stay relatively intact, but the twist being that some cobblestone becomes mossy cobblestone, stone bricks becoming mossy stone bricks, vines and trees growing on builds and other naturalistic events occurring.

It would be really unique because it helps preserve a world's resources and aesthetic without things becoming too mined out, especially when using maps such as the Earth or a pregenerated world.

**Comment by LlmDl** [comment]
I might make this into something that goes into TownyHistories, since that plugin expects the revert-on-unclaim to not be active.
