### ISSUE TITLE
Bankruptcy Bug

### ISSUE THREAD

**Issue by advex0123** [TownyAdvanced/Towny#6200]
### What steps will reproduce the problem?

1. Use the same config and feature
2. Make town and let it go into the maximum debt 

### What is the expected output?

Town will not be delted

### Towny version

0.98.3.6

### Server version

1.18.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/y26jNzEc
2. Your Towny config.yml: https://pastebin.com/BWyD4pnK
3. Your townyperms.yml: https://pastebin.com/cHPTJc7i
4. Your log's error: N/A

(optional) If this is to do with permissions,
5. Your permissions file: 

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
![2022-10-04_15 18 25](https://user-images.githubusercontent.com/879756/193918355-3d5d5069-8e5e-4efd-84e1-38af84c8e4c6.png)
```
3:18 PM]LlmDl: I have my upkeep costing $4 a day
[3:18 PM]LlmDl: I started at 0
[3:18 PM]LlmDl: went into bankruptcy at -4
[3:19 PM]LlmDl: newday'd again, dropped to -8
[3:19 PM]LlmDl: newday'd again, would have dropped below the -10 cap and got deleted
```

I will probably need more clear steps to reproduce this. 

Using the debtcap.override I was able to limit my debtcap to 10, which did result in the town being deleted when it tried to put me to -12.
