### ISSUE TITLE
Suggestion: Per town townyperms.yml

### ISSUE THREAD

**Issue by manul694** [TownyAdvanced/Towny#6213]
### **Please explain your feature request to the best of your abilities:**

By default town uses townyperms.yml, but to change file of Towny permissions user can use API method Town.setTownyPermsFile(String). It's very useful for creating own addons.

**Comment by Warriorrrr** [comment]
Couldn't you just add your own permission as a child to the towny.town.townname node?

**Comment by LlmDl** [comment]
This is true ^

**Comment by Warriorrrr** [comment]
Closing this since the thing I mentioned should indeed work, if it doesn't, feel free to let us know.
