### ISSUE TITLE
Suggestion: Permission-based Daily Upkeep Discounts

### ISSUE THREAD

**Issue by Luciusred** [TownyAdvanced/Towny#6220]
### **Please explain your feature request to the best of your abilities:**

Giving a town's mayor or nation's king a permission (such as towny.nation.discount or towny.town.discount) would reduce the town's or nation's daily upkeep by a percentage.
Example: 
towny.nation.discount.70 - 70% discount 
towny.town.discount.50 - 50% discount

**Comment by Caleston** [comment]
This just feels like something some servers would give out to donators

**Comment by Luciusred** [comment]
> This just feels like something some servers would give out to donators

hmm but i want create bulding (which buy for res) with discount... not for donation
