### ISSUE TITLE
Exploded blocks still regenerate

### ISSUE THREAD

**Issue by ZBLL-CUBER** [TownyAdvanced/Towny#6233]
### What steps will reproduce the problem?

1. I exploded a creeper and then disabled Towny with Plugman, and all the exploded blocks instantly got regenerated. While reloading the plugin is not advised, it made me sure that the reason why the blocks regenerate is Towny - it probably rushed to end all its tasks.

### What is the expected output?

I expected the blocks to NOT get regenerated.

### Towny version

[16:25:38 INFO]: Towny version 0.98.3.0
[16:25:38 INFO]: Resident-Town-Nation heirarchy combined with a grid based protection system. Including a war event.

[16:25:38 INFO]: Website: http://townyadvanced.github.io/
[16:25:38 INFO]: Author: Shade, Modified by FuzzeWuzze. Forked by ElgarL. Forked by LlmDl.

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/0t8Qpx0A
2. Your Towny config.yml: https://pastebin.com/YiHYVyMU
3. Your townyperms.yml: https://pastebin.com/9ryuw7A7
4. Your log's error: ?

**Comment by ZBLL-CUBER** [comment]
I expect the blocks to not regenerate because I configured them to not be regenerating. Maybe I missed something in the configuration and it's still enabled?
The reason I mentioned disabling it is because I was trying to figure out which plugin was causing it. I would explode a creeper and disable a potential plugin - if the hole would be recovered or left untouched, the plugin is the cause; if the hole would continue regenerataing, the plugin has nothing to do with it.

**Comment by Warriorrrr** [comment]
You need to use /tw toggle revertblockexpl or revertentityexpl if you want to disable explosion reverting, the new world settings section of the config is only applied to new worlds.
