### ISSUE TITLE
Swedish Characters in Town Name Causing Safe Mode

### ISSUE THREAD

**Issue by ThorinEk** [TownyAdvanced/Towny#6257]
### What steps will reproduce the problem?

1. Create towns with names that include the Swedish characters å,ä,ö.
2. Restart the server

### What is the expected output?

Towny should enter Safe Mode because it is not able to load the name of the towns with special characters in their name. 

Towns with these names have existed on the server for many months now. Without any recent changes to any configuration the name of these towns can no longer be loaded.

### Towny version

0.98.3.0

### Server version

git-Paper-125 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3f0415b)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/wE5Ta2tD
2. Your Towny config.yml: https://pastebin.com/Ef5RKHKc
3. Your townyperms.yml: https://pastebin.com/GvVBg1L6
4. Your log's error: https://pastebin.com/G3KzLw5r

**Comment by PainOchoco** [comment]
Cannot reproduce on my side, Towny load the town flawlessly after a restart.
![image](https://user-images.githubusercontent.com/47084457/197338940-5c4c7740-9e5f-4b18-b904-5c7bd2481ee6.png)
You may have another problem.

**Comment by ThorinEk** [comment]
Okay, thanks for giving it a try. I am thinking of attempting to remove the files for the towns with the special characters. Do you think that is a good idea? The towns effected are small and almost no active player is using them.

**Comment by PainOchoco** [comment]
You can try to copy the files elsewhere and removes them from the Towny folder and then restart the server. Let us know if the problem is still there.

**Comment by LlmDl** [comment]
This is likely something to do with your host not allowing files to be saved with those characters. This will not be a problem after the UUID based DB is adopted.
