### ISSUE TITLE
Need to make Iris load before Towny to prevent some problems

### ISSUE THREAD

**Issue by ColdTearsYY** [TownyAdvanced/Towny#6258]
### What steps will reproduce the problem?

Iris wiki: https://volmitsoftware.gitbook.io/iris/

1.set an outpost or set your homeblock in a world created with Iris. You are expected to teleport to it using commands.
2.restart the server
3.You can't teleport to them.It says that There are no outpost spawns set for this town.

And many other similar missing problems occured after a restart.

I guess it has something to do with the loading sequence but not sure...

ps.Worlds created with Iris is loaded in bukkit.yml.

### What is the expected output?

Teleport as expected.

### Towny version

0.98.3.0

### Server version

purpur 1.19.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:https://paste.ubuntu.com/p/t8bgDtXkYB/
2. Your Towny config.yml:https://paste.ubuntu.com/p/MZKSVhbbwx/
3. Your townyperms.yml:https://paste.ubuntu.com/p/hcS3YCBNTH/
4. Your log's error: none

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
I tried adding Iris to the softdepend in the plugin.yml in this jar: https://cdn.discordapp.com/attachments/669247087329673228/1033745702087565383/Towny-0.98.3.0.jar

Give it a test for me.

**Comment by ItsJuls** [comment]
i thought it meant Iris the fabric mod lol.

**Comment by ColdTearsYY** [comment]
I tried adding soft depend before opening this issue. I tried the version you posted and didn't fix.

**Comment by LlmDl** [comment]
I tried looking through the Iris source code to see if they throw a WorldInitEvent but couldn't find anything.

If they were throwing that bukkit event then Towny would see the world being loaded.

I'm not entirely certain this is about loading worlds though. If the world wasn't loaded/found to be a towny world you wouldn't be able to make a town or claim any land, but you're saying that only the spawn points aren't being saved.

This leads me to believe Towny is loading your data, including the spawns, which don't have a matching world (cause iris is loading it later,) and Towny removes the spawn.

Use a world-loader like Multiverse or make Iris load your non-loaded World earlier.

**Comment by ColdTearsYY** [comment]
I did have a world-loader plugin called PhantomWorlds on server already...

I knew this problem has something to do with the loading squence because **the same problem occured on another plugin**, and the author fixed it with adding a eventlistener to listen the worlds each time to see if this world is in the plugin's enable-world whitelist. I didn't know if this method would work since I am noob at programming...

I will also send an issue to Iris to see how to load their worlds earlier.

Many thanks! Appreciate to your works!

**Comment by jman13378** [comment]
use depend: pluginname
