### ISSUE TITLE
Suggestion [EventWars]: Force PvP on people that are part of a war in wilderness

### ISSUE THREAD

**Issue by Folas1337** [TownyAdvanced/Towny#6277]
### **Please explain your feature request to the best of your abilities:**

I'd love to see a feature where people who are part of a war would have their pvp force turned on in the wilderness, otherwise they could just stay in the wilderness and chicken out of the fight or border hop as soon as they're about to die.

This would only happen as long as the war is taking part of course and only affect members of the town/nation that's at war.

It should also be a config option for each war type in my opinion.

**Comment by Folas1337** [comment]
Oh yeah this is regarding EventWars. Just now noticed this is the Towny repository and there is none for EventWars.

**Comment by LlmDl** [comment]
Part of 0.0.53.
