### ISSUE TITLE
safe mode

### ISSUE THREAD

**Issue by jman13378** [TownyAdvanced/Towny#6278]
### What steps will reproduce the problem?

install jar and run the server

### What is the expected output?

no safe mode

### Towny version

0.98.3.18

### Server version

Current: git-Purpur-1794 (MC: 1.19.2)*
Previous: git-Purpur-1605 (MC: 1.18.2)

You are 41 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:[latest (2).log](https://github.com/TownyAdvanced/Towny/files/9914422/latest.2.log)
2. Your Towny config.yml: [config.txt](https://github.com/TownyAdvanced/Towny/files/9906233/config.txt)
3. Your townyperms.yml: [townyperms.txt](https://github.com/TownyAdvanced/Towny/files/9906234/townyperms.txt)
4. Your log's error: 
```
[22:35:39] [Server thread/ERROR]: [Towny] Loading Error: Could not read town data 'Town1'.
[22:35:39] [Server thread/ERROR]: [Towny] Database: Failed to load database.
com.palmergames.bukkit.towny.exceptions.initialization.TownyInitException: Database: Failed to load database.
	at com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:145) ~[tny.jar:?]
	at com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:266) ~[tny.jar:?]
	at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:159) ~[tny.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:35:39] [Server thread/INFO]: =============================================================
[22:35:39] [Server thread/WARN]: [Towny] [WARNING] - ***** SAFE MODE ***** 0.98.3.18
[22:35:39] [Server thread/INFO]: =============================================================
```
Towny jar is tny.jar

**Comment by LlmDl** [comment]
Show me your towny\data\townys\town1.txt file

**Comment by jman13378** [comment]
thats the thing there isnt 1 and if i add 1 it will just throw town2 then town3

**Comment by LlmDl** [comment]
Towny wont try to load a town that isn't there. You have a town1.txt file, you can probably just delete it. It was a town that had a name which could not be read from the database, so Towny renamed it.

**Comment by jman13378** [comment]
so Ötüken

**Comment by LlmDl** [comment]
Your host probably doesn't let you save files with special characters in them. Not sure why your file browser doesn't see it as town1.txt, cause that's what Towny renamed it. Make sure you've refreshed your browser/app.

**Comment by jman13378** [comment]
well that did it but that never happened before and the town has existed for awile now

**Comment by jman13378** [comment]
```
01.11 23:08:41 [Server] INFO Jonathan_Nathan issued server command: /ta town Otuken
01.11 23:08:41 [Server] WARN [Towny] Plugin Towny v0.98.3.18 generated an exception while executing task 8128
01.11 23:08:41 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.palmergames.bukkit.towny.object.Resident.getFormattedName()" because the return value of "com.palmergames.bukkit.towny.object.Town.getMayor()" is null
01.11 23:08:41 [Server] INFO at com.palmergames.bukkit.towny.TownyFormatter.getStatus(TownyFormatter.java:343) ~[tny.jar:?]
01.11 23:08:41 [Server] INFO at com.palmergames.bukkit.towny.command.TownyAdminCommand.lambda$parseAdminTownCommand$5(TownyAdminCommand.java:1285) ~[tny.jar:?]
01.11 23:08:41 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1794]
01.11 23:08:41 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1794]
01.11 23:08:41 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
01.11 23:08:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
01.11 23:08:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
01.11 23:08:41 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LlmDl** [comment]
I suspected in the last ticket that you changed hosts recently. Your Otuken.txt is missing a mayor. This shouldn't happen.

**Comment by jman13378** [comment]
i renamed the town file and renamed the town and it just removed the entire file

**Comment by jman13378** [comment]
> I suspected in the last ticket that you changed hosts recently. Your Otuken.txt is missing a mayor. This shouldn't happen.

we haven't we have been with apex for awhile now

**Comment by jman13378** [comment]
all spawns were cleared

**Comment by LlmDl** [comment]
If your world changed name it will do that. In the other ticket I saw evidence your world had changed name.

**Comment by jman13378** [comment]
wait thats why its townyworld now?

**Comment by LlmDl** [comment]
I honestly don't know what you've done at this point. You did something though.

**Comment by jman13378** [comment]
homeBlock=townyworld,-641,609
![image](https://user-images.githubusercontent.com/101841938/199362287-c7459beb-8c9a-4516-bcba-81d077c2fc79.png)

**Comment by jman13378** [comment]
> I honestly don't know what you've done at this point. You did something though.

I just restored a data backup with all of the files you told me to delete

**Comment by jman13378** [comment]
this is the data/townblocks/townyworld/cyprus.data
name=
price=-1.0
town=cyprus
type=Default
outpost=false
changed=false
locked=false
claimedAt=1651279107046
metadata=
groupID=
trustedResidents=
customPermissionData={}

**Comment by LlmDl** [comment]
I don't understand the context of any of this. What town is in the screenshot? You cut off the name.

Why are you showing me townblock data for a townblock somehow called cyprus.data ?

**Comment by jman13378** [comment]
cyprus is the town

**Comment by LlmDl** [comment]
If you change a world name, or if your world isn't loading before towny loads, then your spawn points aren't able to load proper locations because Bukkit doesn't know about that world.

**Comment by jman13378** [comment]
i fixxed the loading problem

**Comment by jman13378** [comment]
and we havent changed the world name

**Comment by LlmDl** [comment]
Then it was cause the world loaded after towny.

**Comment by LlmDl** [comment]
You should probably just replace your whole towny\data\ folder with a data folder from a good backup from towny\backups\.

I'm afraid that's all the help I can afford to give you.

**Comment by jman13378** [comment]
> You should probably just replace your whole towny\data\ folder with a data folder from a good backup from towny\backups.
> 
> I'm afraid that's all the help I can afford to give you.

there is no good folder
