### ISSUE TITLE
Suggestion: [TownyCamps] Allow to use /res spawn to teleport back to camps

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/Towny#6284]
### **Please explain your feature request to the best of your abilities:**

Currently there seems no way to teleport to campfire (although player can `/sethome`, my server does not have such feature for maximum immersion). 

I was wondering if you could provide an config option, if enabled, the player can type command `/res spawn` to teleport back to their campfire, and this teleportation feature shares the cooldown & delay of `/town spawn`. Why `/res spawn`? because it is basically the same as `/town spawn` or `/spawn` and is kinda duplicate. It would be nice if campfire can serve as a temporary spawn point of the player just like towns. So before the player finds a town, they temporarily have a campfire where they can go back to as they wish

**Comment by LlmDl** [comment]
As far as I can see, if deny_bed_use is true in the towny config, towny will already let camp owners use the bed to set their /res spawn.

`/res spawn` always takes the resident to their bed spawn, or if they do not have one, the town spawn.

**Comment by Akiranya** [comment]
Thanks for the quick reply! Right now I don't think this new feature is needed anymore... Taking the existing advantage of `/res spawn` seems better to make a new feature.

**Comment by LlmDl** [comment]
yep, just make sure that deny_bed_use is true so that Towny limits bed use to personally-owned plots and Inn plots, and so that TownyCamps can allow camp-owners to use their beds in their camps.
