### ISSUE TITLE
Suggestion [EventWar]: Add permission node for "/ta war <warType>"

### ISSUE THREAD

**Issue by Folas1337** [TownyAdvanced/Towny#6286]
### **Please explain your feature request to the best of your abilities:**

I don't want to exactly give moderators the "towny.admin" permission node but it's currently required to use "/ta war <warType>".

I would instead like to have more granular control over it by having a permission node that grants only the command I mentioned.

**Comment by LlmDl** [comment]
Part of 0.0.54
