### ISSUE TITLE
Minimessage gradient format is not working

### ISSUE THREAD

**Issue by ArtifactyNight** [TownyAdvanced/Towny#6291]
### What steps will reproduce the problem?

add gradient format to `global.yml`
```yml
default_towny_prefix: '<gradient:#AA076B:#61045F>(Towny)</gradient> &b'
```

![image](https://user-images.githubusercontent.com/53427253/200637410-5cfa0032-679b-4e5c-ba98-aaedeff66577.png)

### What is the expected output?

Gradient format should work fine.

### Towny version

`0.98.4.0`

### Server version

Purpur 1.19.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/qceTxUHL
2. Your Towny config.yml: https://pastebin.com/W1JN0aCU
3. Your townyperms.yml: https://pastebin.com/pKsLPfFY
4. Your log's error: -

**Comment by nilanjanH** [comment]
@Warriorrrr - Am new to OSS; would like to work on this issue. Thanks.
