### ISSUE TITLE
Suggestion: Transferable Claims

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#6295]
### **Please explain your feature request to the best of your abilities:**

Add an option/command to transfer chunks directly to another town, without unclaiming the chunk.

Currently towns are struggling to move claims between themselves and always require an Admin to do it for them.
Would be good if towns would be able to do this on their own, as the ability to transfer seems to exist at least.

A command similar to /ta set plot X, but usable by towns, perhaps with some sort of a confirmation by the other town.
Could be good if the chunk could be set on sale, similarly to plot sales, but actually transferring the chunk to another town.

Unclaiming + Reclaiming is problematic due to the regeneration system and entity & plot deletions kicking in and removing things.
Embassy plots are not a good alternative either, because it does not actually transfer the chunk and will not show up on map nor free up claims for the town.

**Comment by LlmDl** [comment]
Is this still an issue for you now that the entity & block deletions are queued?

**Comment by Caleston** [comment]
> 

Not an issue performance wise, but players would still very much like this feature so that they can sell/transfer their claims back and forth. 
Entity & block deletions get performed even if the plot gets claimed again quick, so it doesn't really prevent their valuables/containers/entities from going poof, hence it would be better to just transfer the claim without the whole unclaiming process.
