### ISSUE TITLE
Enters safe mode after editing enable_economy

### ISSUE THREAD

**Issue by T0wns** [TownyAdvanced/Towny#6302]
### What steps will reproduce the problem?

I performed a clean install of Towny, and when I edit the file and change enable_economy to false, it enters Safe Mode and stops working. I've done this twice now, each with a new install. I've had to unload the plugin entirely for the time being. I really need help!

### What is the expected output?

...not this. It should have just disabled the cost of towns and nations.

### Towny version

v0.98.4.0

### Server version

Paper version git-Paper-81 (MC: 1.19)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/9weexgMQ
2. Your Towny config.yml: https://pastebin.com/WLRuqbb9
3. Your townyperms.yml: https://pastebin.com/VTn1GrcS
4. Your log's error: https://pastebin.com/vqUV54Yj

**Comment by LlmDl** [comment]
As I've explained in the discord, and as it says in your error: you've broken the yaml formatting of your config.
