### ISSUE TITLE
Suggestion: add multipaper support

### ISSUE THREAD

**Issue by Alienn-Know** [TownyAdvanced/Towny#6305]
### **Please explain your feature request to the best of your abilities:**

can you add multi power support? I want to use it on my server, but a lot of towny does not work correctly, for example, inviting a player to a city, a nation, messages about private/private territories, synchronization of a city/national chat, and much more

**Comment by LlmDl** [comment]
This is not a priority. My time on Towny is limited and since I'm not seeing much in the way of sponsorships I don't see myself taking this on.
