### ISSUE TITLE
Falling Blocks bypass Build perms

### ISSUE THREAD

**Issue by sudura** [TownyAdvanced/Towny#6312]
### What steps will reproduce the problem?

1. Build a kick-ass sand shooter outside someone's town
2. Fire the kick-ass sand shooter into their town
3. Sand lands in the town as a block

### What is the expected output?

I guess that the sand breaks on landing like when it lands on slabs?

### Towny version

Reproduced on multiple servers; but on my own: Towny-0.98.4.0

### Server version

1.19.2 PaperMC

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: Unable to post due to "potentially offensive" - should not matter
2. Your Towny config.yml: https://pastebin.com/mVfm8izJ
3. Your townyperms.yml: https://pastebin.com/X8iVDc16
4. Your log's error: No error

(optional) If this is to do with permissions,
5. Your permissions file: No perms used besides TownyPerms

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by sudura** [comment]
I should add this isn't really an issue; I was working on patching for my own use but I didn't find any mention of it so I thought it was worth noting in-case it's not intended

**Comment by LlmDl** [comment]
Is there even an event for when sand goes airborn?

**Comment by sudura** [comment]
Not that I can find - my way of patching was (in my mind so maybe doesn't work out this way) to try and block it when the sand block is created; if the origin was a falling block

In saying that; it would break falling sand from people who do have perms so it's 50/50 

I can't find anything on Spigot for becoming a falling block however

**Comment by sudura** [comment]
Apparently EntityChangeBlockEvent can record both it changing into & from a falling block

In theory then the location can be checked on both?

**Comment by LlmDl** [comment]
If that's teh case then something can be done.
