### ISSUE TITLE
/t set board doesn't show cyrillic letters

### ISSUE THREAD

**Issue by Tenkotataii** [TownyAdvanced/Towny#6317]
### What steps will reproduce the problem?

1. Use Towny
2. Create a town
3. Try using /t set board with Cyrillic letters
4. Get an error which means board message can't be put

### What is the expected output?

To see the message we wrote after writing the command

### Towny version

0.98.4.0

### Server version

Pufferfish 1.18.2 latest build

### Please use Pastebin.com to link the following files

![2022-11-17_23 55 40](https://user-images.githubusercontent.com/100620548/202558340-455b1432-947c-4a57-a1d2-b33f6d3f1e8b.png)
![2022-11-17_23 55 46](https://user-images.githubusercontent.com/100620548/202558361-e26840d7-3d96-4400-b6ac-331703badead.png)

**Comment by Warriorrrr** [comment]
Skipped the form, please link the required files & preferably a translation of the error message.

**Comment by Tenkotataii** [comment]
One more question: in which section should I put pictures? I put them in "pastebin" section because I don't know how to link them.

**Comment by LlmDl** [comment]
that's fine

**Comment by Tenkotataii** [comment]
do i need to link more info about it in a new issue ticket?

**Comment by LlmDl** [comment]
new ticket: don't skip the form that explains what files and logs we want to see, if you post a screenshot set your MC Client to English so that we can read the error message (I don't read Cyrillic.)

**Comment by Tenkotataii** [comment]
okay, thanks for help
