### ISSUE TITLE
Suggestion: Levels of relations between nations

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#6325]
### **Please explain your feature request to the best of your abilities:**

Towny currently has only 2 types of relations with nations, which are Enemies or Allies. This system could be expanded to include more levels than just black/white, such as:

Unfriendly = Bad relations = Teleports blocked

Friendly = Good relations = No perks
Trade = Trade relations established = Teleportation benefits (lower cost, cooldown, etc)

Allies* = Military Alliance = Current Ally perks + if a nation adds an enemy, it also adds the allies of that enemy as enemies automatically, could help spice things up.
Enemy* = War = Teleports blocked, battles possible

These could all use the same kind of system as Ally/Enemy, adding much more flavor to nation relations and hopefully spicing up geopolitics.
Currently many nations are forming alliances as just trade alliances for ally perks, which confuses geopolitics since you don't really know who is militarily allied. It would be beneficial to separate relation types a bit more, so that nations dont have to be all or nothing to each other.

**Comment by thatguycy** [comment]
User requested for this issue to be added to WDE. Available in pre-release for v0.2.0.
