### ISSUE TITLE
Why are cities starting to connect with each other?

### ISSUE THREAD

**Issue by Suwero** [TownyAdvanced/Towny#6338]
### What steps will reproduce the problem?

1. One player creates a city in Russian. Let's say he created Moscow
2. The second player also creates his own city in Russian. And he created Ufa
3. After a while, these cities are connected and their balance becomes common. I don't know why this is happening.. The player who created Moscow can withdraw money from his city and money is also withdrawn from Ufa.

### What is the expected output?

Before that, everything was just perfect) I really like the plugin, but the fact that cities have started to connect with each other is bad

### Towny version

0.98.4.0

### Server version

1.17.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://logs.hosting-minecraft.pro/muzesavine
2. Your Towny config.yml: [config.log](https://github.com/TownyAdvanced/Towny/files/10097682/config.log)
3. Your townyperms.yml: [townyperms.log](https://github.com/TownyAdvanced/Towny/files/10097683/townyperms.log)
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
I have seen this happen: EssentialsXEconomy cannot do Cyrillic characters for the economy accounts, so your accounts which have the same name-character-length will all share the same economy account.

Change economy plugins.
