### ISSUE TITLE
/plot clear and /t delete doesn't work

### ISSUE THREAD

**Issue by Reeferx7** [TownyAdvanced/Towny#6364]
### What steps will reproduce the problem?

/plot clear doesn't remove the signs from plot

https://streamable.com/php9e6

Also, /t delete / unclaim doesn't revert the area to snapshot

Both enable on config.

### What is the expected output?

-

### Towny version

Towny Version: 0.98.4.6

### Server version

1.19.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml: https://pastebin.com/ezzYcHJe
3. Your townyperms.yml: https://pastebin.com/DsXmjMeA
4. Your log's error: -

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Reeferx7** [comment]
Startup log: https://pastebin.com/6caA84zT

WORLDNAME.txt : https://pastebin.com/aSshneJb

**Comment by LlmDl** [comment]
You might want to try it on paper instead of pufferfish. You're configured correctly and no one else has this issue.

**Comment by Reeferx7** [comment]
Thanks for your help, i find the reason of the problem i change the level-type=minecraft\:flat to level-type=minecraft\:normal and all work fine with purpur too, very strange bug.

**Comment by LlmDl** [comment]
I don't really see how the level-type factors into it, might be a height thing.
