### ISSUE TITLE
Suggestion: TownyChat permission granularity

### ISSUE THREAD

**Issue by sudura** [TownyAdvanced/Towny#6381]
### **Please explain your feature request to the best of your abilities:**

As well as towny.chat.xyzchannel

Could we get towny.chat.xyzchannel.listen
And towny.chat.xyzchannel.send

I want some people to listen; but not be able to send to a channel.

**Comment by sudura** [comment]
Can be done right now with /chmute but this makes syncing and doing it while they're offline impossible

**Comment by LlmDl** [comment]
This is a duplicate of https://github.com/TownyAdvanced/Towny/issues/1020
