### ISSUE TITLE
Could not pass event WrappedPlayerInteractEvent to Nova v0.12.11

### ISSUE THREAD

**Issue by ErythroCraft** [TownyAdvanced/Towny#6400]
### What steps will reproduce the problem?

1. Installing newest version of Towny on my spigot server 1.19.3_R1
2. Starting server with updated plugins inklusive Nova plugin
3. starting server [no bug]

4. using items with mouse click event.
5. Asking ByteZ [owner of Nova plugin]
6. ByteZ saide "Looks more like a Towny issue to me"

Please watch out the latest log file I uploaded.
More infos I can not post, because on 1.19 until 1.19.2 the server was working correctly.

Thanks for your work.

### What is the expected output?

Could not pass event WrappedPlayerInteractEvent to Nova v0.12.11

### Towny version

v0.98.4.16

### Server version

ev-Spigot-d90018e-ae8f5fc (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files

[latest.log](https://github.com/TownyAdvanced/Towny/files/10314723/latest.log)

**Comment by LlmDl** [comment]
Having a null TownyUniverse usually happens when someone has improperly added Towny to their plugin pom.xml file, and has included Towny in their own plugin which results in an un-initialized TownyUniverse.

This is not a Towny issue, but you will want to figure out which plugin has been improperly pom'd and compiled.

**Comment by LlmDl** [comment]
Actually I take that back, your Towny startup does appear to be interrupted.

Turn on your towny config's debug_mode and show me the new Towny startup.

**Comment by ErythroCraft** [comment]
Here are the file 

1. [debug.log](https://github.com/TownyAdvanced/Towny/files/10314897/debug.log)

2. [towny.log](https://github.com/TownyAdvanced/Towny/files/10314901/towny.log)
 
3. [latest.log](https://github.com/TownyAdvanced/Towny/files/10314899/latest.log)

Hope it can help

**Comment by ErythroCraft** [comment]
Thanks for the infos. I posted your answer to https://discord.com/channels/859080327096172544/1057649922394038322

**Comment by LlmDl** [comment]
Your latest.log doesn't have the debug messaging in it, and your debug.log looks like it hasn't faulted anywhere. Can you show me the latest.log that was made after you turned on debug_mode in the config.yml to true?

**Comment by LlmDl** [comment]
Another ticket was filed with a similar issue. They had three towns with no mayors. The error you received should no longer occur on 0.98.4.18 and newer.
