### ISSUE TITLE
/tc <message> fails with stack trace

### ISSUE THREAD

**Issue by DeltaOrion** [TownyAdvanced/Towny#6402]
### What steps will reproduce the problem?

1. create new paper server (git paper 1.19.3 build 362)
2. Install Towny and TownyChat with the following config https://github.com/DeltaOrion/Gladia2.0/tree/master/plugins/Towny/settings
3. Join a town (the bug works whether the town is in a nation or is independent) 
4. Type /tc <message> and an internal error occurs

Note.
Typing in /tc first, then typing in the message after works fine. 

### What is the expected output?

Actual Output: A stack trace (an internal error occurred when you run this command)
Expected Output: A message parameter should be sent to the town chat

### Towny version

Towny: v 0.98.4.17
Towny Chat: v 0.99

### Server version

(git paper 1.19.3 build 362)

### Please use Pastebin.com to link the following files

All Config Files
https://github.com/DeltaOrion/Gladia2.0/tree/master/plugins/Towny/settings

Latest Log
https://pastebin.com/vcqxiHKi

**Comment by LlmDl** [comment]
Latest.log / stack trace errors aren't available anymore.

**Comment by DeltaOrion** [comment]
https://pastebin.com/xCVesb1z

**Comment by LlmDl** [comment]
That link is also now no longer available.

**Comment by DeltaOrion** [comment]
clearly pastebin sucks so i'll upload to discord
https://cdn.discordapp.com/attachments/720246865702158416/1058930977772159097/2022-12-29-12.log

**Comment by LlmDl** [comment]
Got it happening on my end as well, it appears to be something with the new chat signing.

**Comment by LlmDl** [comment]
Actually I think this was sorted out by Paper. I updated to latest as of this moment 367 and the issue vanished.

Their changelog does show a number of commits related to player.chat() and ChatProcessor.
