### ISSUE TITLE
[NullPointerException] Towny disables while enabling

### ISSUE THREAD

**Issue by LcyDev** [TownyAdvanced/Towny#6403]
### What steps will reproduce the problem?

Not applicable

### What is the expected output?

1. This error shouldn't be produced.
2. Towny and expansions remain enabled.

### Towny version

0.98.4.17

### Server version

Current: git-Purpur-1858 (MC: 1.19.2)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/vRDicKDR
2. Your Towny config.yml: https://pastebin.com/TDNifa1Y
3. Your townyperms.yml: https://pastebin.com/uCr7NNc8
4. Your log's error: https://pastebin.com/Kkuiavhx

**Comment by LlmDl** [comment]
By any chance do you have teh towny\data\towns\townname.txt that doesn't have a mayor? You can figure out which town it fails on by setting debug_mode to true in the config.

**Comment by LcyDev** [comment]
Forgot to say, i fixed it, there was 3 towns without mayor, ty!

**Comment by LlmDl** [comment]
We will be accounting for this in 0.98.4.18 and onwards.
