### ISSUE TITLE
Typing "/stop" does not shut down the server due to Towny.

### ISSUE THREAD

**Issue by madebygood** [TownyAdvanced/Towny#6411]
### What steps will reproduce the problem?

1. Type /stop

2. The server is shutting down.

3. However, after the towny mysql shutdown message appears, bukkit stops working.
Server won't turn off even after waiting for over an hour.

### What is the expected output?

Graceful shutdown of the server.

### Towny version

[0.98.4.19]

### Server version

1.19.2
purpur-1858 build bukkit

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [https://pastebin.com/e1pT9Fen](https://pastebin.com/e1pT9Fen)
2. Your Towny config.yml: [https://pastebin.com/ZXbzEEvr](https://pastebin.com/ZXbzEEvr)
3. Your townyperms.yml: [https://pastebin.com/SV3ScuDf](https://pastebin.com/SV3ScuDf)

Note :
1) This doesn't happen every time. From experience, there is a 50% chance that the server will not turn off.

2) Running mysql and towny database.yml as default causes problems. And, even if I do tuning with my knowledge, problems arise.

3) "[com.palmergames.hikaricp.HikariDataSource] Towny MySQL - Shutdown completed."

After is output, a message that towny plugin has been successfully terminated should appear.

but,
That message is not printed. So I'm pretty sure this is towny's problem.

![image](https://user-images.githubusercontent.com/43653581/210447715-db178b56-69c7-4e27-b101-d6ab7c6e65c1.png)

![image](https://user-images.githubusercontent.com/43653581/210448727-708a95d8-7276-48c7-bd7f-1f67616b8933.png)

**Comment by LlmDl** [comment]
When it fails do you see this line
```
Shutdown initiated...
```
and not:
```
Shutdown completed
```
?

**Comment by LlmDl** [comment]
If that is the case your server is holding on the hikari data pool closing. 

From the looks of it there should be some information logged by hikari if you can find where it logs to:
```java
   public synchronized void shutdown() throws InterruptedException
   {
      try {
         poolState = POOL_SHUTDOWN;

         if (addConnectionExecutor == null) { // pool never started
            return;
         }

         logPoolState("Before shutdown ");

         if (houseKeeperTask != null) {
            houseKeeperTask.cancel(false);
            houseKeeperTask = null;
         }

         softEvictConnections();

         addConnectionExecutor.shutdown();
         if (!addConnectionExecutor.awaitTermination(getLoginTimeout(), SECONDS)) {
            logger.warn("Timed-out waiting for add connection executor to shutdown");
         }

         destroyHouseKeepingExecutorService();

         connectionBag.close();

         final var assassinExecutor = createThreadPoolExecutor(config.getMaximumPoolSize(), poolName + " connection assassinator",
                                                                           config.getThreadFactory(), new ThreadPoolExecutor.CallerRunsPolicy());
         try {
            final var start = currentTime();
            do {
               abortActiveConnections(assassinExecutor);
               softEvictConnections();
            } while (getTotalConnections() > 0 && elapsedMillis(start) < SECONDS.toMillis(10));
         }
         finally {
            assassinExecutor.shutdown();
            if (!assassinExecutor.awaitTermination(10L, SECONDS)) {
               logger.warn("Timed-out waiting for connection assassin to shutdown");
            }
         }

         shutdownNetworkTimeoutExecutor();
         closeConnectionExecutor.shutdown();
         if (!closeConnectionExecutor.awaitTermination(10L, SECONDS)) {
            logger.warn("Timed-out waiting for close connection executor to shutdown");
         }
      }
      finally {
         logPoolState("After shutdown ");
         handleMBeans(this, false);
         metricsTracker.close();
      }
   }
   ```

**Comment by madebygood** [comment]
![image](https://user-images.githubusercontent.com/43653581/210455160-d03a2495-1c21-42eb-9728-10f14c8a7f98.png)

Under normal circumstances, the output should look like this picture.

Can I find hikari's log and attach it here?

**Comment by LlmDl** [comment]
When it freezes does it show the `Shutdown completed.` line?

**Comment by madebygood** [comment]
> When it freezes does it show the `Shutdown completed.` line?

Yes, that's right. 'Shuldown completed.' After the message is printed, the bucket is frozen.
how can i solve it?

my.ini, towny database.yml
Setting it to the default value or tuning the value as recommended by an expert will also result in an error.

**Comment by LlmDl** [comment]
If you see that message then your hikari has closed and Towny is finishing up its backup/cleanup tasks. Have you got any files in your plot-block-data folder?

**Comment by madebygood** [comment]
![image](https://user-images.githubusercontent.com/43653581/210457012-684f33da-53e2-40e0-80bc-497915baa294.png)
I have that files.

Backup cleanup can take more than an hour?

**Comment by LlmDl** [comment]
None of those files are the outdated .data files, so they won't be causing any issue.

The only other remaining part could be Towny finishing its own backup. Does your server have any backups in the towny\backups\ folder?

**Comment by madebygood** [comment]
![image](https://user-images.githubusercontent.com/43653581/210457746-d5b7e3b0-de28-4651-b0bf-bc06bc7fd0a2.png)

yes there is.

Can I turn off towny backup?

Will that solve the problem?

**Comment by LlmDl** [comment]
Your server is in mysql, so it doesn't save anything except your config, langfiles, and teh plot-block-data.

You do have a fair number of them. You must be stopping and starting the server often. You can disable the automatic backups in the config, or you can disable the automatic cleanup of backups by setting the old-backups time to 0.

**Comment by madebygood** [comment]
![image](https://user-images.githubusercontent.com/43653581/210461620-d9972962-0995-4130-876b-b5842669599c.png)

Disabled automatic backup.

The server is being cycled on and off once per day.

Is there anything else I can do to resolve the issue?

**Comment by LlmDl** [comment]
Probably nothing else on your end of things. Might be worthwhile talking to your host if it persists. 

No one else is having issues with it hanging on shut down, might be hardware/server related.

**Comment by Warriorrrr** [comment]
Can you run jstack \<pid> with the server's pid while it's halted and send the ouput here?
