### ISSUE TITLE
Cannot convert to MySQL

### ISSUE THREAD

**Issue by LcyDev** [TownyAdvanced/Towny#6420]
### What steps will reproduce the problem?

1. Have towny data
2. Try to convert it to mysql following:

https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#converting-flatfile-to-sql
 

### What is the expected output?

This server is running Purpur version git-Purpur-1858 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 482a83f on HEAD)

### Towny version

0.98.4.17

### Server version

This server is running Purpur version git-Purpur-1858 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 482a83f on HEAD)

### Please use Pastebin.com to link the following files

1. Your Towny config.yml: https://paste.gg/p/anonymous/123fc193e65c42a49e8c9abc13d1ab6b
2. Your log's error: https://paste.gg/p/ConaII_/87c779605668485c8be032d0fdd82b80

**Comment by Warriorrrr** [comment]
You need to fix your database's character set & collation, it seems to be using latin1_swedish instead of utf8mb4.

**Comment by LcyDev** [comment]
Ok, it seems that's true, what should it be set to?

 utf8mb4_swedish
 utf8mb4_general_ci
 utf8mb4_unicode_ci

**Comment by LlmDl** [comment]
If you want to support many characters going for the unicode one is a good move.
