### ISSUE TITLE
Protected string always overrides

### ISSUE THREAD

**Issue by LcyDev** [TownyAdvanced/Towny#6421]
### What steps will reproduce the problem?

I did not change neither jar or lang files
But it's still logging this

### What is the expected output?

not this

### Towny version

0.98.5.0

### Server version

git-Purpur-1858 (MC: 1.19.2)*

### Please use Pastebin.com to link the following files

```
[Towny] Attempted to override an protected string. Skipped msg_ptw_warning_1
[07:12:41] [Server thread/WARN]: [Towny] Attempted to override an protected string. Skipped msg_ptw_warning_1
[07:12:41] [Server thread/WARN]: [Towny] Attempted to override an protected string. Skipped msg_ptw_warning_2
[07:12:41] [Server thread/WARN]: [Towny] Attempted to override an protected string. Skipped msg_ptw_warning_2
[07:12:41] [Server thread/WARN]: [Towny] Attempted to override an protected string. Skipped msg_ptw_warning_3
[07:12:41] [Server thread/WARN]: [Towny] Attempted to override an protected string. Skipped msg_ptw_warning_3
```

**Comment by LlmDl** [comment]
Supply your towny\settings\lang\global.yml file.

**Comment by LcyDev** [comment]
Yeah, it was the override file

**Comment by LcyDev** [comment]
But now i have another problem, the plugin won't translate to the specified language

**Comment by LlmDl** [comment]
Don't try to override teh ptw message strings.

**Comment by LcyDev** [comment]
>   # If you want to override any of the files above with your own translations you must:
>   # - Copy the file from the towny\settings\lang\reference\ folder 
>   #   into the lang\override\ folder and do your edits to that file.

I tried this, copying `es-MX.yml` to `override` folder and it's still english
```yml
  language: es-MX.yml
  enabled_languages: es-MX.yml
```

**Comment by LlmDl** [comment]
Towny has a es-MX.yml file already. Why are you putting one into teh override folder? If you have to, you don't need to include the PTW message lines.

**Comment by LcyDev** [comment]
Because it won't traslate, only if i copy the contents of es-MX.yml into global.yml towny translates properly.

**Comment by LlmDl** [comment]
Did you set your MC client to use Mexican Spanish?

**Comment by LcyDev** [comment]
Ooooh what?? No i didn't
Towny has that feature?

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#multi-language
