### ISSUE TITLE
TownyChat Error to console

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#6426]
### What steps will reproduce the problem?

1. send message to chat
2. see console
![image](https://user-images.githubusercontent.com/73141732/211939193-84157cbd-5d7f-4ee7-9004-f050a3a88f92.png)

### What is the expected output?

no errors

### Towny version

Towny-0.98.5.0
TownyChat-0.100

### Server version

paper-1.19.3-359

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/4MqVV9PM
2. Your Towny config.yml: https://pastebin.com/tqyENTap
3. Your townyperms.yml: https://pastebin.com/u4GTPd4H
4. Your log's error:  https://pastebin.com/d3YyrVw3

(optional) If this is to do with permissions,
5. Your permissions file: luckperms-h2-v2.mv.db

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/uVKEHtxr
7. Your channels.yml: https://pastebin.com/89GcfVwa

**Comment by LlmDl** [comment]
Your server is failing on this line:

https://github.com/TownyAdvanced/TownyChat/blob/master/src/com/palmergames/bukkit/TownyChat/channels/StandardChannel.java#L94

I have to assume some other plugin is making the chat event's getRecipients null some how.

Have you tried removing plugins related to chat and re-adding them one-by-one.

I am not able to reproduce this error.

**Comment by LlmDl** [comment]
https://github.com/KaspianDev/AntiPopup/blob/master/src/main/java/com/github/kaspiandev/antipopup/listeners/ChatListener.java#L29

![image](https://user-images.githubusercontent.com/879756/212140644-ebd4d615-311d-4bbf-9a0b-f50bb61447dd.png)
