### ISSUE TITLE
TownyChat broken

### ISSUE THREAD

**Issue by LcyDev** [TownyAdvanced/Towny#6429]
### What steps will reproduce the problem?

Install TownyChat-0.101 on 1.19.3

### What is the expected output?

Chat formatting doesn't work, strange error when players chat:
 `java.util.UnknownFormatConversionException: Conversion = 'to'`

### Towny version

Towny v0.98.6.0

### Server version

Current: git-Purpur-1892 (MC: 1.19.3)*

### Please use Pastebin.com to link the following files

https://paste.gg/p/ConaII_/ce8354f0db384aecab25301dfea1c8a8

**Comment by LlmDl** [comment]
I don't know what you mean by Chat doesn't work, or have enough information to go off of. You skipped the form.

**Comment by LcyDev** [comment]
Hey, please check the link it's all there

**Comment by LcyDev** [comment]
Let me know if you need anythic else @LlmDl

**Comment by LlmDl** [comment]
Townyperms.yml
Full startup log

**Comment by LcyDev** [comment]
https://paste.gg/p/ConaII_/e7f2551e493841bcb2597a5016d6e43b

**Comment by LlmDl** [comment]
The issue is caused by your players somehow not being able to speak into any of the channels.

Your townyperms.yml has some of the chat nodes which shouldn't have prevented them joining the general channel.

Because it cannot find a channel, and because you have modify_chat enabled, it is falling into some code which most people won't have, and it is failing because you have a PAPI placeholder in your GLOBAL channel_format: %townychat_townytag%. 

I would start by replacing that with {channelTag} if that's what that placeholder is trying to do. 

Then I would figure out why your players cannot use any TownyChat channels.

**Comment by LcyDev** [comment]
ChannelTag doesn't give me the especified tag on Channels.yml
It will just give me 
![image](https://user-images.githubusercontent.com/72966048/212211947-40bc0140-727f-4bb2-ae54-923d191f1337.png)

**Comment by LcyDev** [comment]
Wait, this is false, apparently doing `/townychat reload` won't update the channelTags and thats why it wasn't working as i wanted

**Comment by LcyDev** [comment]
It appears townychat doesn't register `towny.chat.join` and `towny.chat.leave` permissions that's why i missed them with luckperms

**Comment by LlmDl** [comment]
Those are normally needed, the join node is only tested if a player has actually left a channel and wants to rejoin it. V0.101 fixed a very old bug with that permission node

I'm not sure what you've done in your LP, Townyperms.yml already has teh nodes required.

I would also like to ask where you got your eventwar.jar you are not a sponsor.

**Comment by LcyDev** [comment]
![image](https://user-images.githubusercontent.com/72966048/212213498-1cdfa233-e45d-451a-b532-4e635919297b.png)

**Comment by LcyDev** [comment]
![image](https://user-images.githubusercontent.com/72966048/212213764-2efe9337-f5e8-4f8c-85a8-fd2f78850346.png)

> I would also like to ask where you got your eventwar.jar you are not a sponsor.

It's not my server, i'm the manager, @Denum1986 the owner is a sponsor.

**Comment by LcyDev** [comment]
Well it seems it wasn't working properly because i also had to add `towny.chat.general` to the default group before

**Comment by LlmDl** [comment]
If you'd like to share your /lp editor link I will take a look at it.

**Comment by LcyDev** [comment]
This is fixed now.

Still, /townychat reload won't update channel tags

**Comment by LlmDl** [comment]
![Untitled](https://user-images.githubusercontent.com/879756/212323353-80d74ded-9147-4b9c-9728-27d566efdc93.png)
I am not having any issue with {channelTag} not reloading when I run `/townychat reload`.
