### ISSUE TITLE
Suggestion: Expansion to Alliances.

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#6432]
### **Please explain your feature request to the best of your abilities:**

Currently, there are Towns, Nations. Nations can create alliances by befriending one nation at a time and vice-versa with enemies. 

My proposed expansion to Alliances would create a third layer that sits on top of Nations. This layer would mirror the way Towns work in Nations, but instead of "Towns," it would be Nations. This would allow a nation to join multiple Alliance coalitions. It would have to be considered that nations can not start individual small alliances like the current system allows using `/n ally add` but instead would probably need to do `/alliance new <alliance name>` and add `/alliance invite <nation>.` 

This system already sort of exists in geopolitical servers but only as a fantasy that works in theory, but it is often difficult to track, etc. I feel that this third layer expanding of Alliance would benefit players who want to expand on the relationships groups of nations can create. 

By creating a separate alliance system, players would have more options for forming alliances, and alliances could be formed between nations, creating more opportunities for diplomacy and cooperation in the game. Additionally, it would allow for more complex geopolitical relationships to develop, making the game more interesting and engaging for players.

**Comment by LlmDl** [comment]
I had started on a previous incarnation of Alliances ([seen here](https://github.com/TownyAdvanced/Towny/compare/master...feature/Alliance)) that I ultimately dropped working on, as it got a fair bit complicated as to which layer (nation, alliance) would take precedence when determining how Enemies are calculated.

I don't recall if it supported letting a nation join multiple alliances though.

While non-alliance'd nations exist it gets tricky deciding where Enemies get pull from though.

**Comment by 0xBitMC** [comment]
I brought the issue of enemies to the discord and came up with a few ideas to solve this.

You could weigh the size of the alliance, the biggest being the one to take the cake to the enemy declaration. Another solution is to allow the nation to set a Primary alliance, which can be switched once daily. Another person also proposed weighing your enemies in size. 

If I was to give my opinion, primarily setting an alliance and being able to change it one in a given time frame seems like a cool idea. You're still a part of other alliances and treaties, etc.

**Comment by LlmDl** [comment]
The last commit I had made it looks like I changed Alliance's enemy lists to just be a collection of Nations instead of other Alliances.
