### ISSUE TITLE
Suggestion: Skript support

### ISSUE THREAD

**Issue by TheWeirdCoder** [TownyAdvanced/Towny#6443]
### **Please explain your feature request to the best of your abilities:**

I think you should add support for skript! If your a skripter like me it could be helpful by being able to make custom events happenn :) There is skript-towny but is quite outdated

**Comment by LlmDl** [comment]
I'm not terribly interested in adding support for skript. If you enjoy Towny you should consider becoming a sponsor. If I get enough sponsors maybe I will worry about updating skript-towny.
