### ISSUE TITLE
Suggestion: New {playerdiplomacycolor} format for TownyChat

### ISSUE THREAD

**Issue by MattWillen** [TownyAdvanced/Towny#6446]
### **Please explain your feature request to the best of your abilities:**

It would be a nice addition to have
`# {playerdiplomacycolor} - Change the playername color based on the relationship with another player's town.`
added to the format list.

The code line is pretty self explanatory, I think it could be a fine addition that really doesn't add anything special, but adds another option of configuring chat that many could like.

As for the colors based on the player relationship with another player:
- Enemy: red (&c)
- Ally: green (&a)
- Neutral: default color specified in the channel_format like in the example below

> `{modplayername} &2≫&7{msgcolour} {msg}`   <--- &7 is added at the beginning of the "chat" to make it colored

**Comment by LlmDl** [comment]
As I'd explained on the discord, I don't believe this is possible with TownyChat, but I'll look into it.

**Comment by LlmDl** [comment]
This one is not possible because TownyChat (and bukkit's Chat api that TownyChat uses) does not send messages to individuals, we only send a single message to all recipients. This might be something that could be done in TownyChatRemake, which does not have the same limitation to the bukkit api.
