### ISSUE TITLE
TownyChat problem

### ISSUE THREAD

**Issue by haroldrc** [TownyAdvanced/Towny#6452]
### What steps will reproduce the problem?

1. install item adder
2. use lpc 
3. modify_chat: enable: 'false'
  
  emojis are made with item adder (: joy :), emojis work in private chat but not in public chat (after upgrading to 1.19.3 they don't work anymore)

### What is the expected output?

indexed emojis

### Towny version

0.98.6.1

### Server version

This server is running Pufferfish version git-Pufferfish-55 (MC: 1.19.3)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: 
2. Your Towny config.yml: 
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
You skipped the form.
