### ISSUE TITLE
TownyChat problem

### ISSUE THREAD

**Issue by haroldrc** [TownyAdvanced/Towny#6454]
### What steps will reproduce the problem?

  install item adder
  use lpc
modify_chat: enable: 'false'
emojis are made with item adder (: joy :), emojis work in private chat but not in public chat (after upgrading to 1.19.3 they don't work anymore)

### What is the expected output?

indexed emojis

### Towny version

0.98.6.1

### Server version

This server is running Pufferfish version git-Pufferfish-55 (MC: 1.19.3)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/8DbVJB6X
2. Your Towny config.yml: https://pastebin.com/F45rdRqB
3. Your townyperms.yml: https://pastebin.com/Lnj79ViJ
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/XnwhXmMJ
7. Your channels.yml: https://pastebin.com/msGSfu4c

**Comment by LlmDl** [comment]
Does it still happen when TownyChat is not installed?

I don't have items adder to test. I would not suspect TownyChat has anything to do with this. LPC usually overrides TownyChat entirely for global chatting (and maybe even town/nation channels.)

**Comment by haroldrc** [comment]
with version 1.19.2 everything works correctly, after updating towny and towny chat it doesn't work anymore

**Comment by LlmDl** [comment]
Does it still not work when TownyChat is not installed?
