### ISSUE TITLE
Suggestion: All towns in the same nation have the same color (overriding individual town mapcolor) 

### ISSUE THREAD

**Issue by 128912891289** [TownyAdvanced/Towny#6455]
### **Please explain your feature request to the best of your abilities:**

For Dynmap-Towny, it would be cool if there was a way to make it so that nation color could override the color set by towns in that nation. It seems to be that even running `/ta nation <nation> set mapcolor <color>`, the color still remains what is chosen by the individual towns. I think it would be great if all the towns in the same nation could have the same color. I don't imagine that this would be very difficult to add and would be very great. 
If this is already actually a thing and I'm just doing something wrong, I can send more info.

**Comment by LlmDl** [comment]
In your dynmap-towny config:
```
visibility-by-town: false
visibility-by-nation: true
```

**Comment by 128912891289** [comment]
I made the changes, but it still seems to not be working. Here is my config file: https://pastebin.com/KH157JR2

**Comment by LlmDl** [comment]
Are you setting the colour using 
```
  NationOfBlue:
    strokeColor: '#0000FF'
    fillColor: '#0000FF'
    ```
Maybe try removing the nationstyle if you're seeing everything use that colour.

or using the ingame colour command?

**Comment by 128912891289** [comment]
I was using the ingame color command. I also tried removing the nationstyle and it still didn't seem to work. The problem seems to be that its using the town mapcolor instead of the nation mapcolor for all of the towns.

**Comment by LlmDl** [comment]
File a new bug report ticket and don't skip any of the form, and include your dynmap-towny config.
