### ISSUE TITLE
/t deposit get money but dont transfer to bank

### ISSUE THREAD

**Issue by pouyarisk** [TownyAdvanced/Towny#6458]
### What steps will reproduce the problem?

1. use player point with vault hook on highest priority
2. make town
3. do /t deposit x
4. respond: you dont have enough money
5. gets money
6. your town bank still empty

### What is the expected output?

money goes to bank

### Towny version

0.98.6.2

### Server version

1.19.3 paper 383

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: too big for pastebin uploaded manually
2. Your Towny config.yml: https://pastebin.com/qcbJY6Pp
3. Your townyperms.yml: https://pastebin.com/ejywvVeY
4. Your log's error: no error

[latest.log](https://github.com/TownyAdvanced/Towny/files/10519746/latest.log)

**Comment by LlmDl** [comment]
Your economy plugin of choice [does not support Vault in a way that can do fake player accounts](https://github.com/Rosewood-Development/PlayerPoints/blob/master/src/main/java/org/black_ixx/playerpoints/PlayerPointsVaultLayer.java) choose another economy plugin.
