### ISSUE TITLE
Towny-Dynmap: All towns in the same nation have the same color (overriding individual town mapcolor) 

### ISSUE THREAD

**Issue by 128912891289** [TownyAdvanced/Towny#6460]
### What steps will reproduce the problem?

1. In config:  
`visibility-by-town: false
visibility-by-nation: true` 
2. Turn on server. 
3. Open dynmap website. 

### What is the expected output?

All the towns in the same nation could have the same color. 
(follow up to #6455 )

### Towny version

0.97.2.0

### Server version

Paper version git-Paper-"fa1a7c180" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/JJVqQwnV
2. Your Towny config.yml: https://pastebin.com/3vn6a6tK 
3. Your townyperms.yml: https://pastebin.com/Z7k0nVdx 
4. Your log's error: https://pastebin.com/ZimtqEQU 
5. Towny-Dynmap config.yml: https://pastebin.com/KH157JR2

**Comment by LlmDl** [comment]
Your towny is out of date, your dynmap-towny is out of date.

You're using 1.16.5 and there's no reason to not be using the most up-to-date Towny/Dynmap-Towny.

Update and retest.

**Comment by 128912891289** [comment]
I updated Towny and Dynmap-Towny, but now it seems that around each town there is a outline of the nation's color, but the fill color is still the town's color.

**Comment by LlmDl** [comment]
OK, can I see your new startup log and your current dynmap-towny config

**Comment by 128912891289** [comment]
Here is the startup log: https://pastebin.com/XgnRNvS3 and here is the Dynmap-Towny config: https://pastebin.com/vMhLzvjn

**Comment by LlmDl** [comment]
Code looks like to me:

```java
                //CALCULATE FILL COLOUR
                if (dynamicTownColorsEnabled) {
                    //Here we know the server is using town colors. This takes top priority for fill
                    colorHexCode = town.getMapColorHexCode();              
                    if(!colorHexCode.isEmpty()) {
                        //If town has a color, use it
                        townFillColorInteger = Integer.parseInt(colorHexCode, 16);
                        townBorderColorInteger = townFillColorInteger;
                    }                
                } else {
                    //Here we know the server is using nation colors
                    colorHexCode = town.getNationMapColorHexCode();              
                    if(colorHexCode != null && !colorHexCode.isEmpty()) {
                        //If nation has a color, use it
                        townFillColorInteger = Integer.parseInt(colorHexCode, 16);     <---- Fill being set with nation's colour.
                    }                            
                }

                //CALCULATE BORDER COLOR
                if (dynamicNationColorsEnabled) {
                    //Here we know the server is using nation colors. This takes top priority for border
                    colorHexCode = town.getNationMapColorHexCode();              
                    if(colorHexCode != null && !colorHexCode.isEmpty()) {
                        //If nation has a color, use it
                        townBorderColorInteger = Integer.parseInt(colorHexCode, 16);     <---- Border being set with nation's colour.
                    }                                
                } else {
                    //Here we know the server is using town colors
                    colorHexCode = town.getMapColorHexCode();              
                    if(!colorHexCode.isEmpty()) {
                        //If town has a color, use it
                        townBorderColorInteger = Integer.parseInt(colorHexCode, 16);                
                    }                
                }
```

Note that both use `town.getNationMapColorHexCode();` to get the colour used, so if your border colour is working it ought to be also getting the same colour for the fill.

**Comment by LlmDl** [comment]
Actually nevermind, you have `dynamic-town-colors: true`, make it false.

**Comment by 128912891289** [comment]
It seems to have worked! Thank you! But, it also seemed to make all towns not in a nation are the same color, is there a way to change this (like have it randomized like before)? If not, that's okay, thank you!!

**Comment by LlmDl** [comment]
It is not coded that way, when you dont use the town colouring to fill it will end up probably using the config's `  fillColor: '#FF0000'` option.

**Comment by 128912891289** [comment]
Okay, thanks!
