### ISSUE TITLE
Suggestion: Dynmap-Towny reload command

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#6463]
### **Please explain your feature request to the best of your abilities:**

Add a reboot command, otherwise when you change the values ​​in the configuration, you need to restart the server every time, and this is inconvenient

**Comment by LlmDl** [comment]
Dynmap-Towny reloads itself if Dynmap is reloaded.

**Comment by 1Pootis1** [comment]
> Dynmap-Towny reloads itself if Dynmap is reloaded.

Okay, just the reboot command was removed from dynmap, it's not very convenient

**Comment by LlmDl** [comment]
OK, I don't put a high priority on Dynmap-Towny as its another plugin which I did not start, got stuck maintaining and the code is a mess. I put a higher priority on tickets filed by sponsors, and I currently have a bunch of other tickets from sponsors.

A work around is using a plugin manager to disable/enable dynmap. If you enjoy my plugins consider becoming a sponsor.

**Comment by 1Pootis1** [comment]
ok, thx
