### ISSUE TITLE
[EventWar] Suggestion: Configurable option to allow Nations the ability to change their conquered Towns' mayors.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#6465]
### **Please explain your feature request to the best of your abilities:**

Maybe have it work for a limited time only after conquering is achieved.

@Peskdt

**Comment by Peskdt** [comment]
Could you add an option to change the operation of the Town vs Town event (which currently merges the losing towith to the winning town)?

The new option is that at the moment of winning the battle, the winning town can choose a player (from their town) to be a mayor in the losing town.

It would be nice if the election command had a node that can be distributed in the townyperms.yml permissions.

**Comment by LlmDl** [comment]
That would be interesting. I don't know what election command you're talking about though.

**Comment by Peskdt** [comment]
Oh, It can also work to set the soldier with the highest score as the mayor. Better than creating a command to set it

**Comment by LlmDl** [comment]
Oh I was confused, there could be a prompt to decide who to set.

**Comment by Peskdt** [comment]
Is it possible to make that?

**Comment by LlmDl** [comment]
Could be a thing yeah, have to work it out though, the player selected to be mayor might not want it either.

**Comment by Peskdt** [comment]
Yeah, it should be an invitation from someone with that permission. and the receiver can choose to be or not be the mayor.
