### ISSUE TITLE
Suggestion: Ignore min_distance_claim for neutrals/enemies

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/Towny#6466]
### **Please explain your feature request to the best of your abilities:**

Make an option to ignore the min distance for claim any chunk for neutral towns and enemies towns

Like this option:
![imagen](https://user-images.githubusercontent.com/91406867/216160819-f5226ad4-8dfc-486c-aec7-48453f3d6f6b.png)

**Comment by LlmDl** [comment]
Is the idea to have one setting for neutral towns and another setting for enemy towns?

If it were the case of one setting why wouldn't you just have the min_distance settings turned down to 0?

**Comment by LlmDl** [comment]
@Peskdt I am still confused by this setting. Can you clarify what you want here and why setting the entire min_distance to 0 isn't working?

**Comment by LlmDl** [comment]
@Peskdt If you can tell me what this ticket is requesting I will reopen it.
