### ISSUE TITLE
Suggestion: /t discord

### ISSUE THREAD

**Issue by GreenArrowlol** [TownyAdvanced/Towny#6474]
### **Please explain your feature request to the best of your abilities:**

Basically, it would let people with a permission node( for example "towny.discord.set") set their "Town" Discord's invite.
So whoever has the above permission can do
/t discordset discord.gg/invitecode
and if any resident does /t discord then they will be sent a message of the discord.

THIS IS COMPLETELY DIFFERENT FROM SERVER'S /DISCORD.

THIS SUGGESTION IS FOR a special /discord command for each towns.

Also can be added for Nations.

Even tho you might think this is not needed I'm pretty sure its a good enough idea.

**Comment by LlmDl** [comment]
I don't believe this is within the scope of Towny. It could be made into a separate plugin. I would not make that plugin for free though.

**Comment by GreenArrowlol** [comment]
> 

I guess a paid addon then?
