### ISSUE TITLE
When I Entered The Game I Looked My Town Balance

### ISSUE THREAD

**Issue by MysticPasha** [TownyAdvanced/Towny#6477]
### What steps will reproduce the problem?

1. First Thing I Was playing Normally, I only looked my Town Balance 
2. After That I  saw The Town Has Got 5506133 Golds
3. I wasn't active at that hour
![image](https://user-images.githubusercontent.com/124742728/217388471-b1c1ee10-8bcd-49b2-bbd7-b31b25380bf2.png)

### What is the expected output?

My 12 gold at The Town Balance

### Towny version

0.98.6.5

### Server version

It was 1.19.3

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Talk to your server admin about this. This is not something I can help you with.

**Comment by MysticPasha** [comment]
> Talk to your server admin about this. This is not something I can help you with.

He try to help me but he doesn't know why.

**Comment by LlmDl** [comment]
I am afraid this is above my paygrade.
