### ISSUE TITLE
A bug where the claim world automatically becomes false when the server is reloaded.

### ISSUE THREAD

**Issue by madebygood** [TownyAdvanced/Towny#6481]
### What steps will reproduce the problem?

1. type "/townyworld toggle claimable" on world named "TEST"
2. when server restart, TEST world's toggle claimable will be false.
3. this is bug 

### What is the expected output?

when restart, claimable have to not reset

### Towny version

0.98.6.4

### Server version

1.19.2 purpur

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
You skipped the form. Try again later.
