### ISSUE TITLE
Towns Cant join nations it says the town doesn't have enough players even though required_number_residents_join_nation is set to 0

### ISSUE THREAD

**Issue by FrenchAtlas** [TownyAdvanced/Towny#6493]
### What steps will reproduce the problem?

![image](https://user-images.githubusercontent.com/125897937/220196808-ff09c188-7645-464f-b3fb-96675c8045b3.png)

### What is the expected output?

towns able to join nations

### Towny version

0.98.3.16

### Server version

1.19.2

### Please use Pastebin.com to link the following files

https://paste.ee/p/k5Go4

**Comment by LlmDl** [comment]
So version 0.98.3.17's changelog is:

  - Make sure all TownyWorld settings are being reset to the config's settings when /tw set usedefault is run, add confirmation.
  - New Command: /ta town TOWNNAME toggle forcedisablepvp
    - Changes a town's forcedisabledpvp setting, which can make a town have PVP off while the world is forcepvp=true.
    - Good for admin/server towns.
  - **Fix nations unable to add towns.**
  - Async the EntityDelete calls in TownyRegenAPI.
  - Fix outlaws being killed not getting sent to jail correctly.

You're out of date. Updating is easy.
