### ISSUE TITLE
Suggestion: Option to Make Chunks Always Claimable During Event Wars

### ISSUE THREAD

**Issue by goflishMC** [TownyAdvanced/Towny#6525]
### **Please explain your feature request to the best of your abilities:**

With the war event when 1 town captures a chunk from another town, I'd like that chunk to still be able to be contested and taken back from the town that took it during the same war. 

A bonus would be to add an optional cooldown before that chunk could be taken by another town after it was just taken.

**Comment by LlmDl** [comment]
Part of 0.0.63.

**Comment by goflishMC** [comment]
thanks for getting this in!
