### ISSUE TITLE
Pressure Plates do not respect SWITCH settings in builds beyond 0.98.6.6

### ISSUE THREAD

**Issue by PirateSoftware** [TownyAdvanced/Towny#6530]
### What steps will reproduce the problem?

1. Enable all perms on a plot except for switch permission
2. Place any pressure plate within that plot.
3. Have an outsider step on the pressure plate.
4. The plate still activates despite PRESSURE_PLATES being in the "switch_ids:" section of "protection:" in the config.
This appears to have been caused by a SWITCH change in 0.98.6.7

### What is the expected output?

Pressure plates should be respected by switch settings just like levers, doors, and other switches.
Adding LEVER to this list works just fine while PRESSURE_PLATES does not and STONE_PRESSURE_PLATE etc does not either.

### Towny version

This does not happen in 0.98.6.6 but does in 0.98.6.9

### Server version

1.18.2 Paper

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

**Comment by LlmDl** [comment]
@devPesto probably broke this with #6495

**Comment by devPesto** [comment]
I'll take a look. Sorry about that.
