### ISSUE TITLE
TNT causing regeneration in wild and nether even when toggled off. 

### ISSUE THREAD

**Issue by AncientSM** [TownyAdvanced/Towny#6531]
### What steps will reproduce the problem?

/tw toggle revertentityexpl
got chat verification it was disabled 
blew up tnt
landscape regenrated after 20 seconds

Tried setting time until regeneration to 0 this still didnt stop it from regenerating. 

### What is the expected output?

the hole to remain in the ground without filing itself in (stg im not trying to be a smart ass)

### Towny version

0.98.6.11

### Server version

spiggot 1.19.3

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:https://pastebin.com/2MSYZmFz
3. Your townyperms.yml:https://pastebin.com/snP2zedd
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:https://pastebin.com/9XkMarLW
7. Your channels.yml:

**Comment by LlmDl** [comment]
Sorted out on discord.
