### ISSUE TITLE
Suggestion: /n outlaw

### ISSUE THREAD

**Issue by Fruitloopins** [TownyAdvanced/Towny#6544]
### **Please explain your feature request to the best of your abilities:**

You can /t outlaw and prevent people joining your town but something like /n outlaw would be good to prevent towns from joining your nation because as far as I know the only way to prevent people from joining is to completely toggle open on your nation

**Comment by LlmDl** [comment]
This is a good idea, but I think I'll use a name different to "outlaw", as that comes along with a fair number of expected features: jailing, teleporting, etc.

**Comment by CorruptedGreed** [comment]
Maybe `/n restrict` could work as a name

**Comment by Dres12345** [comment]
Good suggestion, the nation Patagonia has had issues with towns joining just for the claim bonus, then leaving to join their original nation after they’ve finished claiming.
