### ISSUE TITLE
Suggestion: Make TownyCaptureSites with Random Item show it is 1 random item, not all

### ISSUE THREAD

**Issue by ArmonicPvP** [TownyAdvanced/Towny#6556]
### **Please explain your feature request to the best of your abilities:**

Rather than sites with 1 random item showing EVERY SINGLE ITEM as being an hourly reward (players think you get all the items), show maybe the item they will get that hour, OR show somewhere where it says Reward: 1 random item or something like that

https://i.imgur.com/QOotZ1p.png

**Comment by LlmDl** [comment]
yeah that's probably a good idea
