### ISSUE TITLE
Typing /plot fs returns internal error

### ISSUE THREAD

**Issue by ArmonicPvP** [TownyAdvanced/Towny#6557]
### What steps will reproduce the problem?

1. /plot fs 0
2. Have alt do /plot claim
3. Type /plot fs on that plot
4. Get internal error

### What is the expected output?

Expected output is for it to put plot up for sale or tell you there is no value

### Towny version

latest

jk 0.98.6.15

### Server version

1.19.3 paper 439

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error: https://pastebin.com/H8AF9fey

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by ArmonicPvP** [comment]
better error with the command typed beforehand: https://pastebin.com/bD9STAez

**Comment by Warriorrrr** [comment]
This is already fixed by 0.98.6.17, you should update
