### ISSUE TITLE
Suggestion: Add way to configure reclaim message when you don't have enough money

### ISSUE THREAD

**Issue by vyvin** [TownyAdvanced/Towny#6560]
### **Please explain your feature request to the best of your abilities:**

I'd like to request a way to either statically or through a placeholder, edit the message that comes up when trying to reclaim a town in ruins when you don't have enough money.

Right now all it says is, "You don't have enough money for that."
Which isn't very helpful if players forget about the /towny prices command or don't have access to use that.

I'd like to be able to do, "You need %reclaim_cost% in order to reclaim the town." or "You need $50,000 to reclaim the town." when a player doesn't have enough.

**Comment by LlmDl** [comment]
This has been taken care of by adding a new feedback message to denied confirmations, as well as by removing an unneeded 'can they pay' test in the TownRuinUtil.
