### ISSUE TITLE
Suggestion: Improve revert on unclaim snapshot taking

### ISSUE THREAD

**Issue by Warriorrrr** [TownyAdvanced/Towny#6561]
### **Please explain your feature request to the best of your abilities:**

Currently when a plot is claimed and the revert on unclaim feature is enabled, it will lock the plot in order to take a snapshot and unlock it once it's done. I think this could probably be improved by taking a ChunkSnapshot of the claimed plot then processing that into a PlotBlockData off main.

This would remove the need to lock the chunk and the regen api's world coord queue.

**Comment by LlmDl** [comment]
as long as it accounts for the plots which are bigger than a chunk yes
