### ISSUE TITLE
Embassy plots are still owned by deleted residents

### ISSUE THREAD

**Issue by lexiccn** [TownyAdvanced/Towny#6562]
### What steps will reproduce the problem?

1. Resident claims an embassy plot
2. Resident is deleted, for example by inactivity
3. Resident stops owning most plots (they go for sale)
4. Embassy plots they owned do not go for sale and still have their name.

### What is the expected output?

They are evicted from the embassy plots too.

When they rejoin as a resident despite "owning" these plots in my experience they usually do not, it's owned by a phantom resident - They still have to evict and reclaim.

### Towny version

0.98.6.0 - I did have a read through pre-releases.

### Server version

Paper 1.19.3, slightly out of date but I've reproduced this consistently elsewhere

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: N/A
2. Your Towny config.yml: https://pastebin.com/qdLsRjgr
3. Your townyperms.yml: https://pastebin.com/TTcL0urC
4. Your log's error: N/A

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by sudura** [comment]
As a sidenote despite this being a bug it's used intentionally in a lot of servers that may be worth consideration; setting plots to embassy to prevent them going for sale and being griefed by anyone who can claim them in the town.
