### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by FARF12** [TownyAdvanced/Towny#6576]
### **Please explain your feature request to the best of your abilities:**

I encountered the problem that the %townyadvanced_townblock_claim_price% placeholder only shows the base price of the chunk.
It would be nice if you added a new placeholder which shows the final price, not just the base price

**Comment by LlmDl** [comment]
Will be a part of 0.98.6.21.
  - New PAPI Placeholder: %townyadvanced_townblock_next_claim_price%
    - Displays the cost of the player's town's next claim, taking into account any townblock price increase rules.
