### ISSUE TITLE
Suggestion: Resident plot type

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#6577]
### **Please explain your feature request to the best of your abilities:**

The issue:
The way to properly on-board a resident is:
1. Invite them
2. Ask them to t spawn to town
3. show them a plot where they can build
4. Teach them to claim a plot

This is process takes a bit of time and doesn't scale well with a lot of residents. Most mayors invite residents and don't properly invite them. New players that are invited don't know what to do and don't know about /t spawn.

Suggested solution:
Ability to set plot type "resident". After player accepts town invite, they are automatically teleported to the resident plot and given full plot permissions. They also get messages in chat or a book introducing them to the town and plot. All steps above are automated. The player is introduced to the town and towny itself without much effort for the mayor. Mayor still has incentive to create resident plot types since they want residents to stay in town for as long as possible.

**Comment by LlmDl** [comment]
This is actually already mostly done with the plugin [TownyRTP](https://github.com/LlmDl/SponsorPlugins/blob/main/TownyRTP.md) aside from your suggestion that it be a process that handles residents that are already town members. I will probably add it to that. Not sure about the plot type thing. It seems to just replace a normal plot that is put for sale.

**Comment by FixTheAdmin** [comment]
`This is actually already mostly done with the plugin [TownyRTP](https://github.com/LlmDl/SponsorPlugins/blob/main/TownyRTP.md)`

Players are still being invited to towns regardless of TownyRTP. I think we should optimize that experience so residents can start play as soon as possible. 

You bring up a good point though about the plot type being too similar to normal plots. Adding another one can be confusing. The proposed feature above could work with plots for sale that are free instead of adding a separate plot type.

**Comment by LlmDl** [comment]
Yeah that's what TownyRTP does, it finds a town to put the player in, with a plot forsale, they can use /plot claim on it to join the open town and then own the plot as well.

All that needs to be added is the ability for a town member to find a plot in their own town, when they join the town. This can be done easily when they join the town with a confirmation asking if they'd like to be moved to a plot they can buy.

**Comment by LlmDl** [comment]
Now a feature in TownyRTP 0.0.5 +
