### ISSUE TITLE
Can use leads in other players town claims

### ISSUE THREAD

**Issue by EcoSMP** [TownyAdvanced/Towny#6580]
### What steps will reproduce the problem?

![image](https://user-images.githubusercontent.com/97478346/226476643-349ff6ca-0098-412b-87a7-dfcc13de496b.png)

### What is the expected output?

Leads should not be able to be used unless permission has been granted.

### Towny version

0.98.6.20

### Server version

1.19.2 PurPur

### Please use Pastebin.com to link the following files

config.yml: https://pastebin.com/UdXEc44W
townyperms.yml: https://pastebin.com/yjZXngtm

**Comment by LlmDl** [comment]
I am unable to reproduce this, I do receive the "Not allowed to item_use" message which is what is expected.
