### ISSUE TITLE
[EventWar] Create option to allow for surrendering during the warmup periods.

### ISSUE THREAD

**Issue by Theeno74** [TownyAdvanced/Towny#6593]
### **Please explain your feature request to the best of your abilities:**

There could be a setting where an alotted preparation time set by the admin (s,m,h,d) must pass before any war or conflict begins (Could be activated and deactivated for each type of conflict?). Within this time any side of the confllict can send a /surrender or /whitepeace offer to the other side, so any side can back down from the conflict. Protections set by the admin for towns will still be active until the timer to war runs out, once that happens, regular EventWar wars happen. For reference, Victoria 3's diplomatic incidents are a good comparison.

**Comment by LlmDl** [comment]
Will be a part of 0.0.96
