### ISSUE TITLE
Suggestion: /ts private

### ISSUE THREAD

**Issue by CorruptVD** [TownyAdvanced/Towny#6598]
### **Please explain your feature request to the best of your abilities:**

Make it so towns can make it so only trusted/allied nations can use their /town spawn

**Comment by LlmDl** [comment]
So I was right, this is already a thing (partially)

For trusted residents:

"global_town_settings.do_trusted_residents_count_as_residents",
"# When set to true, a player that is trusted by a town is allowed to spawn to the town as if they were a resident.",
"# Allows allows the residents of entire an town when that town is trusted by the town."),

The above config setting has to be true.

For allied players there are a couple settings:
"global_town_settings.is_nation_ally_spawning_requiring_public_status",
"# When set to true both nation and ally spawn travel will also require the target town to have their status set to public."),

"global_town_settings.allow_town_spawn_travel_ally",
"# Allow regular residents to use /town spawn [town] to other towns in a nation allied with your nation.",
"# Valid values are: true, false, war, peace",
"# When war or peace is set, it is only possible to teleport to the town,",
"# when there is a war or peace.")
