### ISSUE TITLE
BUG: [Towny] Finishing File IO Tasks...

### ISSUE THREAD

**Issue by Truongvv10** [TownyAdvanced/Towny#6604]
### What steps will reproduce the problem?

1. Get the newest build 0.99.0.0
2. Use database sql
3. stop the server

### What is the expected output?

[Towny] Finishing File IO Tasks...

Server doesn't want to shut down properly

### Towny version

0.99.0.0

### Server version

1.19.4 purpur

### Please use Pastebin.com to link the following files

[latest.log](https://github.com/TownyAdvanced/Towny/files/11178907/latest.log)

**Comment by LlmDl** [comment]
Your WORLDS table likely has old worlds in it that did are not able to get a UUID recorded. 

Remove those worlds from your DB.
