### ISSUE TITLE
Nothing is returned when invited to a nation

### ISSUE THREAD

**Issue by Lemar98** [TownyAdvanced/Towny#6614]
### What steps will reproduce the problem?

If a nation sends an invitation to a town to join a nation, but the town already belongs to some other nation, then the player who sent the invitation will not receive any message about this.

1. Just send nation invite for town which already in other nation
2. See nothing in chat

### What is the expected output?

Nothing.

### Towny version

0.99.0.2

### Server version

1.16.5

### Please use Pastebin.com to link the following files

I think none of the things listed here apply to the problem. If it's not, let me know!
-------------------------------------------------------------------------------------------------------------
1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml: 
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Lemar98** [comment]
Now in version 0.99.0.3 a message by the key "msg_err_already_in_town" is displayed from the message configuration but a message by the key "msg_err_already_nation" should be displayed

**Comment by LlmDl** [comment]
msg_err_already_in_town: '&c%s is already a part of %s.'

The actual language string has no mention of a town.
