### ISSUE TITLE
Double Space

### ISSUE THREAD

**Issue by EpicSpeed** [TownyAdvanced/Towny#6620]
### What steps will reproduce the problem?

%townyadvanced_resident_primary_rank% has a space in beginner of the output which creates double space in the chat. It should be removed because in towny chat config we can not remove it ourselfs and it conflicts with {townytagoverride} placeholder or {channelTag} who also has space at the end

e.g TownName(space_of_TownName)(space_of_the_placeholder)Here_comes_placeholder or ChannelTag(Space_of_ChannelTag)(Space_of_the_placeholder)Here_comes_placeholder

My setup:

    town:
        commands: [tcc]
        type: TOWN
        channeltag: '&f{&3ГЧ&f}'
        messagecolour: '&b'
        permission: 'towny.chat.town'
        range: '-1'
        spam_time: '0.5'

    local:
        commands: [l,lc]
        type: GLOBAL
        channeltag: '&e&l{Л}&l'
        messagecolour: '&e'
        default: true
        permission: 'towny.chat.local'
        range: '50'
        
 town: '{channelTag} {townycolor}%townyadvanced_resident_primary_rank%{townyprefix}{permgroupprefix}{modplayername}{townypostfix}{permsuffix}&f:{msgcolour}

  global: '{channelTag} {townytagoverride}%townyadvanced_resident_primary_rank% {townyprefix}{permgroupprefix}{modplayername}{townypostfix}{permsuffix}&f:{msgcolour}
  
  
In townychat (between towny members i mean) its work okay BECAUSE there are no {townytagoverride}. We can fix it by removing {townytagoverride} in config, BUT I want to see to that towns players belong to in global chat. So in order to fix it, we need to remove beginning space of the %townyadvanced_resident_primary_rank% placeholder

### What is the expected output?

Output: https://i.imgur.com/7U23wsK.png

### Towny version

From version where were added new placeholder to towny ranks.

### Server version

1.19.4 or my 1.12.2 custom (both have same problem)

**Comment by LlmDl** [comment]
Please attach your actual chatconfig.yml and channels.yml, as well as your townyperms.yml. I do not have what I need to close this ticket.

**Comment by EpicSpeed** [comment]
Channels: https://pastebin.com/KRfZefuG
Chatconfig: https://pastebin.com/Fva7HqE3
Townyperms: https://pastebin.com/fN7d77uH

**Comment by EpicSpeed** [comment]
I fixed it, but:

tag_formats:
  world: '&f[&f%s&f]'
  town: '&f[&3%s&f]'
  nation: '&f[&e%s&f]'
  # First %s is the nation tag, second is the town tag.
  # You may also use %t for the town tag and %n for the nation tag!
  both: '&f[&6%s&f > &3%s&f]'
  
  still after  /townychat reload
  
https://i.imgur.com/OH8XUgV.jpg

**Comment by LlmDl** [comment]
Show me your chatconfig.yml now.

**Comment by EpicSpeed** [comment]
https://pastebin.com/2nf0HQnY

**Comment by EpicSpeed** [comment]
that fix just removed space between Town and Ranks https://i.imgur.com/BE35RbU.jpg, but the double space is still "alive"

**Comment by LlmDl** [comment]
Is the staff tag your resident rank prefix or a permission rank that is supplied by {modplayername}, if it is the latter, then the 2nd space is from the space after the primary rank placeholder `%townyadvanced_resident_primary_rank% {townyprefix}{permgroupprefix}`

**Comment by EpicSpeed** [comment]
STAFF is a permission for LP

**Comment by EpicSpeed** [comment]
prefix.13.&f(&9&lSTAFF&f)&9

**Comment by LlmDl** [comment]
remove the space after %townyadvanced_resident_primary_rank% in the global channel_format.

**Comment by EpicSpeed** [comment]
It fixed the problem, but then another arises. Now I dont have space between towny rank and permission from LP https://i.imgur.com/jtwdjSk.jpg

**Comment by LlmDl** [comment]
Some will want the space and some will not, if it were going in a scoreboard or hologram they would not want the space.
