### ISSUE TITLE
TownyChat suddenly stopped working

### ISSUE THREAD

**Issue by Iced-Coded** [TownyAdvanced/Towny#6625]
### What steps will reproduce the problem?

I really don't know.

### What is the expected output?

I expect to see town, nation + privilege prefixes, but there are no prefixes and just nicknames.

### Towny version

Towny: 0.99.0.0
TownyChat: 0.103

### Server version

1.19.3

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/bNAs8w0a
2. Your Towny config.yml: https://pastebin.com/7k6FvjpB
3. Your townyperms.yml: https://pastebin.com/zAMfaVka
4. Your log's error: https://pastebin.com/yusbf6ni

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/TWNtrKZ1
7. Your channels.yml: https://pastebin.com/kzwX2zP3

**Comment by LlmDl** [comment]
Paper's plugin loading strategy is getting in the way. You need to turn it off using their startup argument, I'm sorry I don't know what the argument is but the paper team can probably tell you.
