### ISSUE TITLE
Small isue

### ISSUE THREAD

**Issue by EpicSpeed** [TownyAdvanced/Towny#6626]
### What steps will reproduce the problem?

Image to an issues: https://i.imgur.com/NwGff0Q.jpg and https://i.imgur.com/PQLVBaZ.jpg

### What is the expected output?

underline thing appears in /t and plot name. In chat it looks good. 

### Towny version

version: towny-0.99.0.1.jar

### Server version

1.12 and 1.19

### Please use Pastebin.com to link the following files

Config: https://pastebin.com/tFjgtYQ0
Townyperms: https://pastebin.com/fN7d77uH

**Comment by LlmDl** [comment]
I cannot tell what you've adding <underline> to.

**Comment by EpicSpeed** [comment]
@LlmDl is it okay what i have <underline>MayorPlaceholder thing?

**Comment by LlmDl** [comment]
I only see the ✍ emoji, I'm still not sure what you're wanting/doing.

**Comment by EpicSpeed** [comment]
I want to see in /t mayor prefix like this: https://i.imgur.com/TGOn19I.jpg but it shows like this: https://i.imgur.com/NwGff0Q.jpg

**Comment by EpicSpeed** [comment]
I marked it with red

**Comment by Warriorrrr** [comment]
MiniMessage does not have an \<underline> tag, use \<u> or \<underlined> instead. [Webui link](https://webui.advntr.dev/?mode=chat_closed&input=%3Cunderline%3Edoesn't%20exist%0A%3Cu%3Eworks%20as%20expected%3C%2Fu%3E&bg=grass)
