### ISSUE TITLE
Suggestion: required_defenders_online bypass if town has below set amount of players

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6628]
### **Please explain your feature request to the best of your abilities:**

Right now, EventWar strictly follows required_defenders_online even if a town has less than the set amount of players. So if the set amount is 3 and a town only has one resident, that town is essentially unattackable. To solve this, I suggest adding a config option similar to min_online_ignores_low_pop but for required_defenders_online, that basically means that if a town has less than the amount of players set in required_defenders_online, it instead checks if all players in that town is online, and if they are, makes the town attackable.

**Comment by LlmDl** [comment]
Each war type has a `min_online_ignores_low_pop` setting in the config, which does what you're requesting.

If the nation/town population is below the required number online, it checks if the town/nations entire population is online.
