### ISSUE TITLE
Suggestion: Add /t bantown

### ISSUE THREAD

**Issue by davidcanas** [TownyAdvanced/Towny#6638]
### **Please explain your feature request to the best of your abilities:**

/t bantown would ban all members belonging to a specific city

example:
/t bantown Florida

all florida members would be banned from the city

**Comment by davidcanas** [comment]
add all the city members to the outlaw list

**Comment by davidcanas** [comment]
like /t trustcity

**Comment by LlmDl** [comment]
Duplicate of #6544
