### ISSUE TITLE
Suggestion: Command blocking function for sub-commands with a main command

### ISSUE THREAD

**Issue by Lemar98** [TownyAdvanced/Towny#6642]
### **Please explain your feature request to the best of your abilities:**

I am having an issue with the Towny plugin's command blocking feature. Specifically, when I attempt to block the command '/cmi sethome', it is not being blocked by the plugin. After reviewing the Towny code, I have identified the problem: the plugin listens for the PlayerCommandPreprocessEvent, splits the command into an array by spaces, and checks only the first argument for a match with blocked commands. This approach does not work for plugins that have a main command before the sub-command. Therefore, I believe that the plugin should check all arguments of the command for a match with blocked commands to ensure proper blocking of sub-commands with main commands.

**Comment by Lemar98** [comment]
> https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

Friend, I'd love to donate, but I can't make it through github. I wrote to you about it on Discord.
Provide me with any other payment methods (like paypal or cryptocurrency) and I will support you today

**Comment by Lemar98** [comment]
When I try block a cmi sethome command it's doesn't blocked for me
I was tried:
sethome
cmi sethome
cmi:sethome
/cmi sethome
/cmi:sethome
/sethome

but all of things is not blocked
maybe the problem in cmi plugin ?

**Comment by Warriorrrr** [comment]
The pull request is not merged yet.

**Comment by Lemar98** [comment]
> The pull request is not merged yet.

Oh, sry, I'm blindness ;)
