### ISSUE TITLE
Error: 'You cannot own more then 0 outposts'

### ISSUE THREAD

**Issue by Atmois** [TownyAdvanced/Towny#6646]
### What steps will reproduce the problem?

Using /town claim outpost with the config results in 'You cannot own more then 0 outposts' being outputted (Non OPs Only). 

![image](https://user-images.githubusercontent.com/130537361/235546523-3b954a16-6ac4-4523-95b7-0e7195908858.png)

### What is the expected output?

A Outpost being claimed

### Towny version

0.99.0.0

### Server version

Paper 1.19.4

### Please use Pastebin.com to link the following files

Latest Log: https://pastebin.com/9NiC5Ra4
config.yml: https://pastebin.com/iymEbjLq
townyperms.yml: https://pastebin.com/9RNEwqdR

**Comment by LlmDl** [comment]
Your town_level section is missing a numResidents: 0 level, that might be causing an issue. You should try adding  a town level with numResidents: 0.

**Comment by LlmDl** [comment]
Nevermind, uninstall PowerRanks. It is breaking the permission nodes Towny uses.

**Comment by LlmDl** [comment]
```
[23:05:55] [Server thread/WARN]: [Towny]   Warning: PowerRanks is incompatible with Towny.
                           PowerRanks will override Towny's ability to give
                           permissions via the townyperms.yml file. You can expect
                           issues with Towny permissions (and other permission
                           providers,) while PowerRanks is installed.
```

**Comment by Atmois** [comment]
Ah alright, thanks will do.
