### ISSUE TITLE
Money duplication with /t withdraw command

### ISSUE THREAD

**Issue by Alexis-Elaxis** [TownyAdvanced/Towny#6666]
### What steps will reproduce the problem?

1. Make /t withdraw 5000
2. The money isn't removed from town bank
3. You can duplicate money

### What is the expected output?

![image](https://github.com/TownyAdvanced/Towny/assets/52383750/9720f5f1-8f8d-4071-894b-03b1f987d017)

### Towny version

![image](https://github.com/TownyAdvanced/Towny/assets/52383750/d04bc197-e821-4226-9948-ef770bb5d228)

### Server version

![image](https://github.com/TownyAdvanced/Towny/assets/52383750/7eb8c4f8-4a39-471a-86c8-fb4d5d1da538)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://hastebin.com/share/iquyeqolex.makefile
2. Your Towny config.yml: https://pastebin.com/Z6aqkSrE
3. Your townyperms.yml: https://pastebin.com/YxYkjRqH
4. Your log's error: None

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
We already know that two plugins named "Economy" do not work with Towny: https://github.com/TownyAdvanced/Towny/wiki/Frequently-Asked-Questions
