### ISSUE TITLE
Suggestion: Configurable Dynmap Info Tab For Capture Sites

### ISSUE THREAD

**Issue by WyattPereira** [TownyAdvanced/Towny#6709]
### **Please explain your feature request to the best of your abilities:**

Would be great to have a fully configurable dynmap info menu for towny capture sites, similar to that already present in the dynmap-towny plugin.

**Comment by LlmDl** [comment]
At the moment the captures sites infowindow is just the same thing as what TCS changes the /town statusscreen to.

Could you give an example of what you'd want it to be able to look like?

**Comment by WyattPereira** [comment]
Possibly something like:

{CaptureSite Name}
------------------
Controller: {Town or Nation Controller}
Controlled for: {Time since last takeover}
Reward: {Reward}

At the moment it looks like this:

Town2 @ (Europe,142, -442)
-------------------------
Currently under the control of Town1, who have held control for 1.9 days. Hourly reward: $0. TownyCaptureSites and Towny cannot find a usable Economy plugin! This CaptureSite can be attacked using '/t capture'. The HP stat can only be attacked/healed from within the home block.


I think having the ability to format the menu would be a great addition.
