### ISSUE TITLE
Vault is not an economy plugin.

### ISSUE THREAD

**Issue by LoliColleen** [TownyAdvanced/Towny#6714]
### What steps will reproduce the problem?

1. Install Folia
2. Add Vault and Towny to plugins
3. Start the server
Towny will warn:
[Towny]   Warning: No compatible Economy plugins found. Install
                           Vault.jar or Reserve.jar with any of the supported eco
                           systems. If you do not want an economy to be used, set
                           using_economy: false in your Towny config.yml.

### What is the expected output?

Vault should be detected.
Here is a Folia-supported Vault:
https://github.com/Geolykt/Vault/tree/v1.7.3-folia

### Towny version

0.99.1.0

### Server version

Folia version git-Folia-"ca3b7ad" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: ca3b7ad)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
[latest.log](https://github.com/TownyAdvanced/Towny/files/11635736/latest.log)

2. Your Towny config.yml:
[config.txt](https://github.com/TownyAdvanced/Towny/files/11635748/config.txt)

3. Your townyperms.yml:
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/11635750/townyperms.txt)

4. Your log's error:
[Towny]   Warning: No compatible Economy plugins found. Install
                           Vault.jar or Reserve.jar with any of the supported eco
                           systems. If you do not want an economy to be used, set
                           using_economy: false in your Towny config.yml.

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
[ChatConfig.txt](https://github.com/TownyAdvanced/Towny/files/11635769/ChatConfig.txt)

7. Your channels.yml:
[Channels.txt](https://github.com/TownyAdvanced/Towny/files/11635774/Channels.txt)

**Comment by LlmDl** [comment]
```
[21:27:53] [Server thread/WARN]: [Towny]   Warning: No compatible Economy plugins found. Install
                           Vault.jar or Reserve.jar with any of the supported eco
                           systems. If you do not want an economy to be used, set
                           using_economy: false in your Towny config.yml.
                           ```
                           
Besides Vault (which is only a bridge) what eco plugin are you using?
