### ISSUE TITLE
Suggestion: TownBlockClaimCostCalculationEvent Get Player claiming

### ISSUE THREAD

**Issue by JustinDevB** [TownyAdvanced/Towny#6728]
### **Please explain your feature request to the best of your abilities:**

Allow access through the event to the player that is attempting to claim the chunks.

TownBlockClaimCostCalculationEvent#getPlayer() does not exist. There is no way to access the player firing the event.

**Comment by LlmDl** [comment]
The event is not always thrown from claiming, it also is thrown when /towny prices is used and probably other places.

**Comment by LlmDl** [comment]
It is pulled for
- claiming with /t claim
- the /towny prices command
- the papi placeholder
- the town merge command
