### ISSUE TITLE
Suggestion: Add a max_overclaim_limit and min_town_overclaim_age config for overclaim

### ISSUE THREAD

**Issue by CorruptedGreed** [TownyAdvanced/Towny#6734]
### **Please explain your feature request to the best of your abilities:**

Add a way to configure the following:
1. how many blocks can be overclaimed by a town every towny day
2. how old a town needs to be to able to overclaim blocks from other towns

`max_overclaim_limit` - the max amount of blocks that can be overclaimed from a town by another town every towny day. This should prevent towns from mass recruiting and instantly overclaiming their neighbors, making it much more gradual process. Ex: being set to 8 would mean a town can only overclaim 8 blocks from another town each towny day.

`min_town_overclaim_age` - the minimum age (in days) a town must exist for before being able to overclaim blocks from other towns. Ex: being set to 7 would mean a town can only overclaim 7 days after its been founded.

(Take the makeshift names with a grain of salt)
![image](https://github.com/TownyAdvanced/Towny/assets/47507792/b9404dad-cb61-49af-8163-babfc2916f11)

**Comment by LlmDl** [comment]
max_overclaim_limit - could be done using cooldown on the command, requiring them to wait X minutes/seconds between commands does put a hard cap on how many they can do per day. I know its not exactly a x-per-day but at the same time we don't have to track how many they did and when they did them.

min_town_overclaim_age - this is easy to do, just check that the town is old enough when using the command.

**Comment by CorruptedGreed** [comment]
> max_overclaim_limit - could be done using cooldown on the command, requiring them to wait X minutes/seconds between commands does put a hard cap on how many they can do per day. I know its not exactly a x-per-day but at the same time we don't have to track how many they did and when they did them.

This seems fair, but what if the town has multiple players who can claim? (I.E councillors/co-mayors) Wouldn't they be able to bypass this limit if it's a command cooldown, or is it possible to attribute a cooldown to the town and not the player running the command?

**Comment by LlmDl** [comment]
Cooldowns can be put onto single players or affect entire towns/nations.

**Comment by CorruptedGreed** [comment]
That sounds good then, it addresses making things more gradual (along with min_town_overclaim_age)
