### ISSUE TITLE
taxes are not collected

### ISSUE THREAD

**Issue by FARF12** [TownyAdvanced/Towny#6768]
### What steps will reproduce the problem?

I using TNE as economy and towny Towny v0.99.0.0 
When I write /ta nevdaa, the plugin writes that taxes have been collected, but the treasury of the cities remains the same. After a couple of minutes, such an error appears.
![Screenshot_1566](https://github.com/TownyAdvanced/Towny/assets/88440932/b596764e-2f57-4667-8c05-fee5a914f79c)

### What is the expected output?

Fine working taxes 

### Towny version

Towny v0.99.0.0 

### Server version

1.16.5 paper fork

### Please use Pastebin.com to link the following files

https://pastebin.com/7Y4iFxE6

**Comment by Warriorrrr** [comment]
This seems more like an issue with TNE since it's doing profile lookups for town accounts.
