### ISSUE TITLE
Error occurred while enabling Towny v0.99.2.0 

### ISSUE THREAD

**Issue by robtbs** [TownyAdvanced/Towny#6778]
### What steps will reproduce the problem?

this error happens when the server is starting

### What is the expected output?

https://paste.gg/p/anonymous/a60f161438644e54abc410402c7f79ac

### Towny version

Towny version 0.99.2.0

### Server version

Paper version git-Paper-49 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e8bec64)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://paste.gg/p/anonymous/a82cc9eb09e54ff0b2cc9849e6270f21
2. Your Towny config.yml: https://paste.gg/p/anonymous/aef245f2cb6e472abd95e6b2eca3d680
3. Your townyperms.yml: https://paste.gg/p/anonymous/ed4bac8e7a4042f897687a1d986db6bb
4. Your log's error: https://paste.gg/p/anonymous/a60f161438644e54abc410402c7f79ac

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Did you modify your towny jar in any way? It cannot find any language files, which should be impossible if you use the jar we offer.

**Comment by robtbs** [comment]
no, i got the jar from https://www.spigotmc.org/resources/towny-advanced.72694/

i just upload it asis

**Comment by Warriorrrr** [comment]
Unable to reproduce this using the jar from the last release and build 49 of paper, what version of java are you using?
