### ISSUE TITLE
New 1.20 feature let's anyone edit any sign when you don't have build access

### ISSUE THREAD

**Issue by Vaspei** [TownyAdvanced/Towny#6780]
### What steps will reproduce the problem?

with new 1.20, you can edit signs, and players are able to edit signs in towns they aren't apart of

### What is the expected output?

Should deny users with no access to a town from being able to edit signs and hanging signs

### Towny version

99.2.2

### Server version

1.20

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
this only affects hanging signs since I can't reproduce this with regular signs
