### ISSUE TITLE
Suggestion: 2 new placeholders

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#6788]
### **Please explain your feature request to the best of your abilities:**

1) %townyadvanced_player_location_is_outpost% - returns True or False based on whether the townblock in the player's location is outpost

1) %townyadvanced_player_location_plot_price% - returns the price of plot the player standing in

**Comment by Warriorrrr** [comment]
I don't like the idea of adding placeholders for the purposes of scripting when we already have a pretty good API
