### ISSUE TITLE
Suggestion: International Chat

### ISSUE THREAD

**Issue by MrBendy453** [TownyAdvanced/Towny#6790]
### **Please explain your feature request to the best of your abilities:**

Add a new chat feature that allows higher ranked members of nations to make chats that can be seen and used by members of each nation. For example: a chat could be made between the USA and Canada; it could function like any other nation or town chat. This could be useful between allied nations that operate as a singular state.

**Comment by LlmDl** [comment]
`/ac` already exists but isn't as fine-tuned as this suggestion.

**Comment by MrBendy453** [comment]
> `/ac` already exists but isn't as fine-tuned as this suggestion.

The idea is that you can single out specific nations.

**Comment by LlmDl** [comment]
Yes I undestood that.
