### ISSUE TITLE
Suggestion: Towny CaptureSites per site monetary rewards.

### ISSUE THREAD

**Issue by Dynamite99** [TownyAdvanced/Towny#6791]
### **Please explain your feature request to the best of your abilities:**

Pretty simple, but instead of a global config setting for money reward, you can choose to adjust the money for each of the capture sites.

Setting the monetary reward for each site can be done in the GUI

The setting in the config can be switched to something like this instead:

capturesites:
  
  capture_site_hp: '50'
  
  defender_spawn_cooldown: '60'
  
  **DEFAULT**_money_reward: '250.00'

**Comment by LlmDl** [comment]
I did already make this a thing: 

https://github.com/TownyAdvanced/Towny/issues/6546 

```
0.13.0:
  - Make config buildable/destroyable lists able to support wildcard *, adding this will mean that anything can be build/destroyed in CaptureSites.
  - Make money-rewards configurable per-site.
    - Sites will default to the config value.
    - Closes https://github.com/TownyAdvanced/Towny/issues/6546
  - New Command: /ta capturesite rewardmoney {amount}
    - Used to set how much money a capturesite awards per-hour.
```
