### ISSUE TITLE
Bug: City is deleted moments after putting the same name as the name of another city, only without graphic accentuation. 

### ISSUE THREAD

**Issue by davidcanas** [TownyAdvanced/Towny#6793]
### What steps will reproduce the problem?

Create 2 cities 
One with the name for example "Russia" and another with the name "Rússia"
A few minutes/hours later, one of the cities will disappear from the registers, and all the chunks will be unclaimed (no rollback) 
And it also does not warn anything in the chat, the city just disappears out of nowhere. 

### What is the expected output?

Create two cities with different name with a different graphic accent of difference, and run fine, the cities do not get deleted. 

### Towny version

0.99.2.5

### Server version

1.19.2

### Please use Pastebin.com to link the following files

It's not a problem with the server, it's a general problem that occurs with everyone.

**Comment by LlmDl** [comment]
You skipped the form.
