### ISSUE TITLE
Suggestion: /t ban <player>

### ISSUE THREAD

**Issue by AJlovesgaming19** [TownyAdvanced/Towny#6795]
### **Please explain your feature request to the best of your abilities:**

Be able to outright ban people from your town instead of outlawing. On larger servers, it doesn't help when players (especially hackers) can easily tp to your town when you don't want them to, and you don't want to set your town to private just because of one player. Outlawing can still exist, but banning gives extra security to people.

**Comment by Warriorrrr** [comment]
What would banning do exactly? there's already the option to prevent outlaws from entering your town

**Comment by AJlovesgaming19** [comment]
Ive just had issues where outlaws are entering my town and I cant kill them because they are too overpowered. These people often break other server rules or are just general un-"gamesman"-like. Outlawing can be used between private server players where there is high trust not to break rules, and can be used in roleplay. Banning can be used in public servers and whilst /t ban is a command, it outlaws people, not ban people.
