### ISSUE TITLE
After sleeping on a bed in a town everything from inventory disappears.

### ISSUE THREAD

**Issue by Iced-Coded** [TownyAdvanced/Towny#6816]
### What steps will reproduce the problem?

1. Place a bed
2. wait for night
3. Sleep.
4. Profit

### What is the expected output?

Not to lose everything from the inventory.

### Towny version

0.99.2.0

### Server version

1.19.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://mclo.gs/VbxvUdd
2. Your Towny config.yml: https://mclo.gs/EtwcRSm
3. Your townyperms.yml: https://mclo.gs/vZRruHF
4. Your log's error: N/A

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
I can almost certainly tell you that this isn't towny.

**Comment by Iced-Coded** [comment]
Okay, thanks.
