### ISSUE TITLE
Towny Update 99.3.0 > 99.3.1/99.4.0/99.5.0 Disables Plugin

### ISSUE THREAD

**Issue by KowalskiXCIX** [TownyAdvanced/Towny#6823]
### What steps will reproduce the problem?

Whilst running Towny version 99.3.0, I attempted to update to 99.3.1, which broke during startup and disabled the plugin, I waited and version 99.4.0 came up, I tried updating again, it broke the same way, I tried version 99.5.0, still broke again
I tried multiple paper MC versions, and they all break, I am stuck on version 99.3.0 and can't update anymore

(for clarification, by break I mean the plugin disabling in the startup process of Paper MC)

### What is the expected output?

Plug is supposed to load during startup, but refuses to

### Towny version

99.3.1, 99.4.0, 99.5.0

### Server version

1.20.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/pFrU8tyJ
2. Your Towny config.yml: https://pastebin.com/rLUxJSCS
3. Your townyperms.yml: https://pastebin.com/mvS5j8G4
4. Your log's error: https://pastebin.com/s0vSNXc4

**Comment by KowalskiXCIX** [comment]
I have Towny Menus installed v: 0.0.6 as well, but this error occurs before menus gets a chance to load

**Comment by LlmDl** [comment]
Can I see your towny\data\worlds\worldname.txt file?

**Comment by KowalskiXCIX** [comment]
Yes, https://pastebin.com/TfET2iVi
This is for the main "world"

**Comment by KowalskiXCIX** [comment]
Okay, I appreciate it!

**Comment by Warriorrrr** [comment]
created a pr that fixes the exception when a key is given an empty input string, I'd still like to investigate whether the list of entities being empty is due to us
