### ISSUE TITLE
Sniffer being despawned as if a monster when mob spawn flag is off in a town.

### ISSUE THREAD

**Issue by RealFinePoint** [TownyAdvanced/Towny#6824]
### What steps will reproduce the problem?

1. Hatch a sniffer in a town with mob spawn off.
2. It vanishes.

### What is the expected output?

The sniffer hatches without vanishing, since it's a passive mob.

### Towny version

0.99.5.0

### Server version

paper-1.20.1-68

### Please use Pastebin.com to link the following files

Log: https://mcpaste.io/9a1d7163b8d09eee
Config: https://pastebin.com/KQSqUdeP
Perms: https://pastebin.com/EGGAmp0Z

**Comment by Cocolennon** [comment]
Perhaps check your config?

**Comment by LlmDl** [comment]
Towny has only been configured to remove `Monster,Flying,Slime,Shulker` and Sniffers are not monsters or flying. It is unlikely that Towny is the thing removing your sniffers.

**Comment by RealFinePoint** [comment]
> Towny has only been configured to remove `Monster,Flying,Slime,Shulker` and Sniffers are not monsters or flying. It is unlikely that Towny is the thing removing your sniffers.

I thought so too, but turning on mob spawns through Towny immediately fixed the issue.

**Comment by LlmDl** [comment]
Could not reproduce. As said, this isn't a Towny issue.

**Comment by RealFinePoint** [comment]
It was fixed with one of the recent Towny updates which did include multiple changes related to spawning.
