### ISSUE TITLE
Suggestion: Allow option for Nation levels to use town count

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#6831]
### **Please explain your feature request to the best of your abilities:**

Currently Nations progress levels using "numResidents".

It would be nice to have an option to change this path to be via total towns in nation. I have my nation levels set up to give benefits for being in a nation, such as reduced town upkeep.

I'd like to have the nations progress through the levels by having more towns in that nation rather than the total amount of residents, as this will cause nation leaders to try and keep towns, just like mayors have incentive to keep residents. 

What would be good is have these 2 options inside the nation level configs:
useTownCount: true/false (bool)
numTowns: 3 (int)

It will also be nice to have a resident per town requirement for joining a nation, this could work by either having it in the config for each nation level, or an command the nation leader can run to set their own personal requirement.

**Comment by LlmDl** [comment]
> It will also be nice to have a resident per town requirement for joining a nation, this could work by either having it in the config for each nation level, or an command the nation leader can run to set their own personal requirement.

This is already an option in the config.

As for the nation_level based on town-count, I dont think this is an option but I can look into how easy it is to implement. It may be trivial or it may end up being quite difficult.

**Comment by tomhmagic** [comment]
ah thank you, I was just thinking of it being a bool option to switch from using resident count to town count, then either having a new option to put it in the nation levels or just used numResidents as the number of towns
