### ISSUE TITLE
Suggestion: /ta command to view war score and war hud for different wars (wars you are not part of)

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6833]
### **Please explain your feature request to the best of your abilities:**

Currently the only war to see war score and towny war hud is to be an active part of the war. I would like for there to be a townyadmin command (and possibly even a /towny war command) to view war score and war hud for wars you are not part of. A similar command for war stats would probably also be good.

**Comment by LlmDl** [comment]
I have made it possible to have towny war stats, scores, participants all accept a war name.

The hud is trickier to do right away because of the way huds are updated, we get a war off of the player whose scoreboard we're touching.

**Comment by LlmDl** [comment]
Hud option will be part of 0.0.91
