### ISSUE TITLE
Eventwar editable_materials can not be edited

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6836]
### What steps will reproduce the problem?

1. Try to edit (place/break) blocks listed in editable_materials in a warzone
2. Can't do it

### What is the expected output?

The expected output is for players to be able to edit these materials in a warzone.

build_and_destroy_editable_materials: 'true'
editable_materials: tnt,ladder,obsidian,shulker_box,end_crystal,cobweb

### Towny version

Towny 0.99.5.0, Eventwar 0.0.89

### Server version

1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/3d0rGe3e
2. Your Towny config.yml: https://pastebin.com/2yC7aBsQ
3. Your townyperms.yml: https://pastebin.com/FBAMahyC
4. Your log's error:

**Comment by LlmDl** [comment]
Can I see your warconfig.yml?

**Comment by LlmDl** [comment]
I could not reproduce this one, I'll leave this ticket open while you re-test things.
