### ISSUE TITLE
Suggestion: Event war newday tokens

### ISSUE THREAD

**Issue by tskopen** [TownyAdvanced/Towny#6839]
### **Please explain your feature request to the best of your abilities:**

Make the number of tokens you get per day changeable.
Why?
For admins can have rage weeks where towns get a ton of tokens to gear up for war. Or to change how fast you can start wars without editing each war config and messing up the balance between town vc nation wars.

**Comment by LlmDl** [comment]
Part of 0.0.91

**Comment by tskopen** [comment]
LimDI Top G if your not a sponsor thats just sad.
