### ISSUE TITLE
disable_creature_pressureplate_stone in config.yml didn't work ( in fact it always keeps true)

### ISSUE THREAD

**Issue by ColdTearsYY** [TownyAdvanced/Towny#6843]
### What steps will reproduce the problem?

1.install towny.
2.take stone plate for example. Link a redstone lamp with the stone plate. Use spawn eggs to spawn a cow on it.
3.the stone plate doesn't work and the redstone isn't lit up.

### What is the expected output?

cows can activate redstone lamp when standing on a stone plate.

### Towny version

towny 0.99.5.0
(also 0.99.2.0)

### Server version

purpur-1.20.1-2006

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://mclo.gs/q7txaxf
2. Your Towny config.yml: https://mclo.gs/hxRmy3z
3. Your townyperms.yml: https://mclo.gs/PK1cXAY
4. Your log's error: not found

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
In your switch_ids in the config.yml you have NON_WOODEN_PRESSURE_PLATES, the cow is being blocked from using the plate because of this. Use a wooden pressure plate.

**Comment by ColdTearsYY** [comment]
Thanks a lot and it works.
