### ISSUE TITLE
Private dont work.

### ISSUE THREAD

**Issue by Karma678** [TownyAdvanced/Towny#6846]
### What steps will reproduce the problem?

1. Players just can break any town.

### What is the expected output?

Expected result: The protection of towns from raiders will work.

### Towny version

0.99.0.0

### Server version

1.19.3

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/LZrSpAsR
3. Your Towny config.yml: https://pastebin.com/Epx9p7zZ
4. Your townyperms.yml: https://pastebin.com/dNDZrbuY
5. Your log's error: https://pastebin.com/jhpAtBCv

(optional) If this is to do with permissions,
6. Your permissions file:

(optional) If this is to do with chat,
7. Your chatconfig.yml: https://pastebin.com/kCfBRJYc
8. Your channels.yml: https://pastebin.com/SpK88zB0

**Comment by Karma678** [comment]
sorry i will delete

**Comment by Warriorrrr** [comment]
This is not a bug, somewhere in your permissions plugin/townyperms you're giving players permission to break stuff in towns, generally just look at /lp verbose and /lp user name checkperm to see the cause.

**Comment by Karma678** [comment]
What is permisson?
