### ISSUE TITLE
Claim filling.

### ISSUE THREAD

**Issue by Vodq** [TownyAdvanced/Towny#6855]
# Claimfill

basically, /towny claim fill, that fills your claim after you make borders instead of having to claim everything inside

**Comment by Warriorrrr** [comment]
Duplicate of #6624, this isn't a very high priority for us since /res toggle townclaim exists.

**Comment by Vodq** [comment]
shouldn't it be useful since most people want to claim big pieces of land, even the lands plugin has this.
