### ISSUE TITLE
Embassy plot permissions being reset upon Towny database reload

### ISSUE THREAD

**Issue by gorbyhail** [TownyAdvanced/Towny#6856]
### What steps will reproduce the problem?

In one specific town (the oldest) on the server, owned embassy plot permissions seem to be sticking to allow everyone to switch and itemuse. When using "/plot perm reset" on an affected plot, the permissions do correctly set to whatever the owner has as default permissions for their owned plots, usually friends only for build/destroy/itemuse/switch.

However, when using "/ta reload all" or restarting the server, the owned embassy plots all go back to allowing anyone to switch/itemuse on them. Any manually set plot permissions are also overridden.

### What is the expected output?

I expect the owned embassy plot permissions in this specific town not to reset every time the Towny database is reloaded.

### Towny version

0.99.5.0

### Server version

Paper 1.20.1 Build 68

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [https://pastebin.com/qNuiEvHw](url)
2. Your Towny config.yml: [https://pastebin.com/tGpyVUSx](url)
3. Your townyperms.yml: [https://pastebin.com/SvB0HXLD](url)
4. Your log's error: Cannot find any log errors related to Towny unfortunately

**Comment by gorbyhail** [comment]
Small update to this, it's resetting the owned embassy plot permissions to the default town-owned plot permissions. I don't think this is expected behaviour as it makes no sense that the plot owners permissions would be overridden like this?

**Comment by LlmDl** [comment]
I've taken a look at this and I'm wondering at which point the resident sets the permissions to the embassy plot?

Plots don't automatically take a resident's permission line when they're purchased.
