### ISSUE TITLE
wild_revert_on_mob_explosion not working

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6857]
### What steps will reproduce the problem?

1. Blow up an entity listed in 'entities:' (in my example TNT) in the wilderness
2. Wait for it to revert.
3. Doesn't revert.

### What is the expected output?

For the entity block damage to be reverted after a set amount of time (in my case 180 seconds).

### Towny version

Towny 0.99.5.0.

### Server version

1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/itEb3zM1
2. Your Towny config.yml: https://pastebin.com/ahdxRB9j
3. Your townyperms.yml: https://pastebin.com/gg60BDfP
4. Your log's error: -

**Comment by LlmDl** [comment]
I need to see your towny\data\worlds\WORLDNAME.txt file, where worldname is the world you're testing in. I also need to know what mob is exploding exactly.

**Comment by LlmDl** [comment]
The 0.99.3.0-0.99.5.0 releases had some issues pertaining to that list of entities being wiped out. This probably explains why the list was empty or missing TNT for you.

The naming is very wonky, yes, that has always been the case but it is documented in the HowTownyWorks wiki page. Some day maybe we'll end up renaming a lot of those settings/the code that backs them.
