### ISSUE TITLE
TownyChat commands not working and minimessage not parsing

### ISSUE THREAD

**Issue by o7-hmoe** [TownyAdvanced/Towny#6867]
### What steps will reproduce the problem?

ISSUE 1: colors not parsing in /channel
1. install townyChat 0.107 and Towny 0.99.5.0
2. execute /channel
3. notice that the colour codes are displayed as <aqua> instead of the colour.

ISSUE 2: colors not appearing in {msgcolour}
1. install townyChat 0.107 and Towny 0.99.5.0
2. Open Channels.yml and change the messagecolour of town chat to be &e
3. Open ChatConfig.yml and change channel_format for town entry to be: '{channelTag} {towntag}{townyprefix}{modplayername} : {msgcolour}{msg}'
4. restart server or try using /townychat reload, if it works
5. notice that the {msgcolour} which should be applying yellow, does not apply yellow to the chat message

### What is the expected output?

Output listed above in each issue

### Towny version

Towny 0.99.5.0
TownyChat 0.107

### Server version

Paper version git-Paper-72 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a3c760e)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/E2Ba8Rhf
2. Your Towny config.yml: https://pastebin.com/mAEbF9RB
3. Your townyperms.yml: https://pastebin.com/vb0mLcZ1
4. Your log's error: none

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/1wF35Zmh
7. Your channels.yml: https://pastebin.com/kv48sGyA

**Comment by o7-hmoe** [comment]
removed issue of `/townychat reload` not working, it works as intended

**Comment by LlmDl** [comment]
The channels.yml link has expired.

**Comment by LlmDl** [comment]
I also wonder if MessageFilter, ChatControl might be to blame.

Because we were able to see <aqua> get parsed we know that the channels' msgcolour isn't null, when a msgcolour is null we just replace {msgcolour} with "". That leads me to believe that the colour code was added, but was being removed.

Does either of the above plugins require a permission node to colour player chat text?

**Comment by o7-hmoe** [comment]
I'll test it on a local test server running just towny and townychat and
see what happens.

Not sure about permission nodes but I was typing in chat as an operator so
I shouldnt need any permissions. I think this might be an issue on my end.

**Comment by LlmDl** [comment]
I've got a PR for fixing the helpmenus that's already been merged, the code for message colouring looks good though.

**Comment by LlmDl** [comment]
![Capture](https://github.com/TownyAdvanced/Towny/assets/879756/39de0c51-4d45-4a71-acfc-53bf32fdae5a)
Just switched the town chat from default to &4 and successfully got it to work.
