### ISSUE TITLE
Suggestion: Remove exclaves if outposts are disabled

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6872]
### **Please explain your feature request to the best of your abilities:**

Right now, players can claim a line of chunks and then unclaim chunks in the middle to get what looks like an outpost but doesn't function like one. I would however like for there to at least be an option to not allow such exclaves if outposts are disabled.

Here's an example:
https://cdn.discordapp.com/attachments/697448134594265169/1131571600752394250/image.png

**Comment by LlmDl** [comment]
This is already available if you use the min_adjacent_townblocks feature.
