### ISSUE TITLE
Money is lost in a closed economy

### ISSUE THREAD

**Issue by Mihanoks** [TownyAdvanced/Towny#6874]
### What steps will reproduce the problem?

1. Rename the town.
2. View the change in the balance of the accounts of the town and the server.

### What is the expected output?

The server account balance should not change.

### Towny version

Towny 0.99.5.0

### Server version

Purpur-1985 (MC: 1.19.4)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/aHn1cn3i
2. Your Towny config.yml: https://pastebin.com/HULPMK04
3. Your townyperms.yml: https://pastebin.com/7hc32nEY
4. Your log's error: https://pastebin.com/E77LHfvZ

**Comment by LlmDl** [comment]
Why are you saying that the server account balance should not change, in the `What is the expected output?` section?

Setting the name will use .withdraw() which does pay to the server if the closed economy is enabled.

```java
/**
* Attempts to withdraw money from the account, 
* and notifies account observers of any changes.
*
* @param amount The amount to withdraw.
* @param reason The reason for subtracting.
* @return boolean indicating success.
*/
public synchronized boolean withdraw(double amount, String reason) {
if (subtractMoney(amount)) {
	notifyObserversWithdraw(this, amount, reason);
	if (TownySettings.getBoolean(ConfigNodes.ECO_CLOSED_ECONOMY_ENABLED))
		return payToServer(amount, reason);

	return true;
}

return false;
}
```

**Comment by LlmDl** [comment]
It's also worth noting that XConomy by YiC200333 is already known to not support Vault fully and won't work for Towny servers.

**Comment by LlmDl** [comment]
No, if the cost is free we don't cause any payment or any effect on your server account:

```java
		double renameCost = TownySettings.getTownRenameCost();
		if (TownyEconomyHandler.isActive() && renameCost > 0 && !town.getAccount().withdraw(renameCost, String.format("Town renamed to: %s", newName))) {
			TownyMessaging.sendErrorMsg(sender, Translatable.of("msg_err_no_money", TownyEconomyHandler.getFormattedBalance(renameCost)));
			return;
		}
```

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/1131608698771492985/towny-0.99.5.4.jar

Please re-test using this jar

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/1131611942172242071/towny-0.99.5.4.jar

Should fix it.
