### ISSUE TITLE
Suggestion: command "/townyadmin mute <chatchannel>"

### ISSUE THREAD

**Issue by IIIzP0III** [TownyAdvanced/Towny#6876]
### **Please explain your feature request to the best of your abilities:**

requesting a command

       /townyadmin mute <chatchannel> for townychat

I was looking for a feature to mute/disable the global chat channel to force players to use proximity/local channels -

I searched and came across the same request in a forum where it was never seen from 2020 -

Original request of MrNuck in 2020:
"
>     I'm currently using DeluxeChat and TownyChat to handle chat on my server.
>     DeluxeChat manages formats and TownyChat manages channels.
>
>     My players can move between chats easily, but I want to know if there's a way to silence only the global chat so players can
>     only be reached through proximity chat and direct messages. /ignoreall can't to this since it will mute all channels, and I want
>     players be able to talk in local chat while ignoring the global chat.
>
"
  - Discussion in '[Spigot Plugin Help](https://www.spigotmc.org/forums/spigot-plugin-help.42/)' started by [MrNuck]

**Comment by LlmDl** [comment]
You could just remove the general channel from teh channels.yml or not give players the permission node for that channel
