### ISSUE TITLE
I don't know the error

### ISSUE THREAD

**Issue by yuankun1** [TownyAdvanced/Towny#6879]
### What steps will reproduce the problem?

I don't know

### What is the expected output?

I don't know

### Towny version

[T][城镇]towny-0.99.5.4

### Server version

1.16.5 catserver

### Please use Pastebin.com to link the following files

1. (https://paste.ubuntu.com/p/74PJ7n5qJd/)

**Comment by LlmDl** [comment]
You have a plugin that is setting an Entity to Unknown type, 
` com.github.mechalopa.hmag.entity.AbstractFlyingMonsterEntity.func_70071_h_`

It's probably this.

**Comment by yuankun1** [comment]
> You have a plugin that is setting an Entity to Unknown type, ` com.github.mechalopa.hmag.entity.AbstractFlyingMonsterEntity.func_70071_h_`
> 
> It's probably this.

This creature is a physical creature in mods

**Comment by LlmDl** [comment]
Ok, that mod author has not set a key to their EntityType.

**Comment by yuankun1** [comment]
> Ok, that mod author has not set a key to their EntityType.

Does this plugin fix it?
Or find the author of the mod to fix it.

**Comment by LlmDl** [comment]
I'm not particularly interested in fixing a bug created by a mod author.

https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-
