### ISSUE TITLE
permission prefix gets uncapitalized for no reason

### ISSUE THREAD

**Issue by muffinicent** [TownyAdvanced/Towny#6880]
### What steps will reproduce the problem?

have luckperms and towny
create a role on luckperms with the prefix [Moderator]
when talked in chat it turns into [moderator]

### What is the expected output?

i would've expected it to stay as [Moderator]

### Towny version

0.99.5

### Server version

1.20.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

[every file that's asked for.zip](https://github.com/TownyAdvanced/Towny/files/12140296/every.file.that.s.asked.for.zip)

**Comment by LlmDl** [comment]
Can you please put the files on a paste service so I don't need to unzip something.

**Comment by muffinicent** [comment]
alright i will do that in the morning

**Comment by muffinicent** [comment]
well it just fixed itself so
