### ISSUE TITLE
Placeholder API returns incorrect

### ISSUE THREAD

**Issue by Ferrlix** [TownyAdvanced/Towny#6897]
### What steps will reproduce the problem?

1. Use chat plugin (sunlight in this case)
2. use the %townychat_channeltag% placeholder in said plugin config
3. the placeholder returns with the %townychat_townytag%, identically

### What is the expected output?

in general, for example, it should return the channel tag; [G]
returns townytag instead, the combination of the town and nation tags

### Towny version

0.99.5.0
townychat 0.108

### Server version

1.20.1
git-paper-"a40e48f"

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: (https://pastebin.com/kbUVFxPE)
2. Your Towny config.yml: https://pastebin.com/pfD9JMhU
3. Your townyperms.yml: https://pastebin.com/8BT5h1jQ
4. Your log's error: no error

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/PtxMP9ny
7. Your channels.yml: https://pastebin.com/nzsg1ZmE

**Comment by Ferrlix** [comment]
doing '/papi parse me %townychat_channeltag%' returns this, my townytag (server town)
![image](https://github.com/TownyAdvanced/Towny/assets/126913961/66d41738-0499-4e78-85df-64583d6f9258)

**Comment by LlmDl** [comment]
I have never been responsible for the townychat placeholder expansion.
