### ISSUE TITLE
[Eventwar] /warp can still be executed even though it's blacklisted

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6898]
### What steps will reproduce the problem?

1. Include warp in the blacklisted_commands
2. Execute /warp during war
3. Can still do it

### What is the expected output?

To not be able to execute /warp during war.

### Towny version

Towny 0.99.5.0
Eventwar 0.0.91

### Server version

1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/U3sRTen3
2. Your Towny config.yml: https://pastebin.com/CVJz5V54
3. Your townyperms.yml: https://pastebin.com/BCYLyAMk
4. Your log's error: -
5. Your warconfig.yml: https://pastebin.com/11nDxteu

**Comment by LlmDl** [comment]
Looks like you've only blacklisted it in the jail-blacklist and not the war one:
```
  # Commands that cannot be run by players who have an active war.
  war_blacklisted_commands: somecommandhere,othercommandhere
```
