### ISSUE TITLE
Suggestion: [Eventwar] War is over book instant surrender compatibility

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6899]
### **Please explain your feature request to the best of your abilities:**

Right now, if a war ends with surrender (and I assume that it also requires no side to have scored), the war is over book says that the war ended in a stalemate. I was therefore advised to make a suggestion about making it so it would in this case say that a side has won with the losing side surrendering. I assume this might also be the case if one side has a higher score than the other side but still surrenders.

**Comment by LlmDl** [comment]
Will be a part of 0.0.96
