### ISSUE TITLE
Suggestion: Update EULA spam to reflect August 2nd, 2023 EULA changes

### ISSUE THREAD

**Issue by natereprogle** [TownyAdvanced/Towny#6900]
### **Please explain your feature request to the best of your abilities:**

[Mojang published](https://www.minecraft.net/en-us/article/minecraft-eula-and-commercial-usage-guidelines-updates) a new [Minecraft Usage Guidelines](https://www.minecraft.net/en-us/usage-guidelines) yesterday (August 2nd, 2023), which specify how server owners can charge for their servers.

Of this, the following language was added:

> You may make money by charging for access to your server by:
>
>* Asking for donations, so long as you don’t offer the donor something that only they can use. However, you may offer all players server wide rewards if donation goals are met.
> * Selling entitlements that affect gameplay provided they don’t ruin other players’ experience or give a competitive advantage in the game

Currently, if the console runs the `/ta givebonus`, the player or town members are spammed with a message that states that the server (incorrectly) breaks Minecraft EULA. Now, [I](https://github.com/TownyAdvanced/Towny/issues/3038) [am](https://github.com/TownyAdvanced/Towny/issues/2740) [well](https://github.com/TownyAdvanced/Towny/issues/2480) [aware](https://github.com/TownyAdvanced/Towny/issues/2479) of the Towny teams' comments regarding this, but with the updates to the Minecraft Usage Guidelines, these no longer apply. Plus, [it's excruciatingly clear that the player base does not want this](https://github.com/TownyAdvanced/Towny/issues?q=is%3Aissue+is%3Aclosed+EULA), and I bet you most of the time, this message doesn't even apply. It's damaging to a server's player base when plugins, without permission, tell players that a server is breaking the literal law, and that they should "consider player on a Towny server that respects the wishes of the Towny team". On my server, specifically, I'm just trying to give out extra blocks to players that vote. It's free and has never been against EULA, even before yesterday's updates. But, now knowing this message exists, I can't do that without risking my players leaving or submitting Tickets asking why we're breaking the law.

As long as a server allows regular players to use Towny unobstructed, giving bonus blocks then classifies as an "entitlement", wherein players are "entitled" to _extra_ bonus blocks. Extra blocks do not give any competitive advantage, nor do they ruin others' experience. Now, "competitive advantage" is pretty vague, and in the end this would all depend on the server's Towny config settings, but as long as a server owner is following the EULA, this shouldn't matter. 

The fact that this message is spammed whenever console runs a command, _regardless_ of the context (Say, it's an admin literally just running the command, or it's from a voting plugin such as Voting Plugin, or a player purchased it from an in-game store with in-game money, etc.) is kind of ridiculous.

I highly suggest that the Towny team reconsider this message, and at least add the ability to disable it, since purchasing bonus blocks is no (for the most part) longer against EULA.

**Comment by LlmDl** [comment]
I don't agree with you:

- Allowing players to get townblocks does give them a competitive advantage, they can claim more land without needing to gather players into their town.
- Towny's license does not allow for commercial usage, ie: selling the townblocks for money, so the Mojang EULA change is a moot point anyways.
- No message is displayed when the console runs `/ta givebonus TOWNNAME amount`.

I've been involved with Towny for 11 years and 99% of Towny servers are not sponsoring. Don't forget how crappy it feels finding out someone that needs my support is also selling Townblocks in their shop and making bank.
