### ISSUE TITLE
Suggestion: Convert outposts to towns

### ISSUE THREAD

**Issue by AToska21** [TownyAdvanced/Towny#6902]
### **Please explain your feature request to the best of your abilities:**

Hello, I am currently using the Towny server on my server and we have encountered a problem. Some of my members claim land on outposts so they can give to their friends to "colonise", but the friends want to make separate towns without reclaiming everything. Is there a feature where outposts can be converted to towns?

**Comment by LlmDl** [comment]
No that is not a feature.
