### ISSUE TITLE
Suggestion: Permission node for town enter/exit notifications

### ISSUE THREAD

**Issue by invpt** [TownyAdvanced/Towny#6907]
### **Please explain your feature request to the best of your abilities:**

Currently, it seems that notifications for entering/exiting towns can only be enabled/disabled globally. For my use case, it would be nice if there was a permission node, e.g., `towny.notify`, that was required for players to be given notifications.

My use case: I want to move my server's spawn area around the Towny world to showcase different towns, but while players are in the spawn, I don't want them to be notified about towns. If there was a permission node for notifications, I could set players to gamemode=adventure while they are in spawn and then use the LuckPerms context `gamemode=survival` to only give the `towny.notify` permission to players who are outside of spawn.

**Comment by LlmDl** [comment]
I am not currently taking suggestions https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-
