### ISSUE TITLE
New Bukkit Error

### ISSUE THREAD

**Issue by madebygood** [TownyAdvanced/Towny#6916]
### What steps will reproduce the problem?

I don't know when or how it happens.

However, after updating to the latest version, various errors are being displayed on bukkit.

### What is the expected output?

![image](https://github.com/TownyAdvanced/Towny/assets/43653581/beebce8a-c580-4f8e-a345-162eb9138163)

![image](https://github.com/TownyAdvanced/Towny/assets/43653581/4f277d13-0ec6-4801-a9e6-484aa70f6175)

### Towny version

0.99.5.9

### Server version

1.19.2 PurPur

### Please use Pastebin.com to link the following files

.

**Comment by Warriorrrr** [comment]
Update to 0.99.5.10, it's fixed in there.
