### ISSUE TITLE
Bug: Leaderboard placeholder always returns 1st place

### ISSUE THREAD

**Issue by Xayanix** [TownyAdvanced/Towny#6924]
### What steps will reproduce the problem?

Use %townyadvanced_top_town_land_n% placeholder.

### What is the expected output?

Obvious

### Towny version

0.99.2.0

### Server version

1.20.1

### Please use Pastebin.com to link the following files

![image](https://github.com/TownyAdvanced/Towny/assets/12672902/4dd78692-2f68-4e47-babd-2a908b5367e2)
![image](https://github.com/TownyAdvanced/Towny/assets/12672902/d2acbc8f-0808-46ad-a2fd-ee1a116d2404)
![image](https://github.com/TownyAdvanced/Towny/assets/12672902/e2b4fb3f-b2ca-45e1-929e-9ee6ad522fff)

etc

**Comment by LlmDl** [comment]
Out of date Towny.
