### ISSUE TITLE
Issue Protecting Modded Inventories with switch_IDs

### ISSUE THREAD

**Issue by Chickandduck** [TownyAdvanced/Towny#6926]
### What steps will reproduce the problem?

1. Using clay brick on the modded inventory to recieve block ID (Block being Ironchests mods chest)
2. <img width="620" alt="image" src="https://github.com/TownyAdvanced/Towny/assets/66577738/769a706e-90e8-4698-b724-1080a6ae9132">
3. Using said ID in the config.yml file in the Protection categorie in the switch_id subcategorie  (ID being Ironchests:iron_chest)
4. Saving the File to apply changes
5. Rebooting the Server to ensure changes are applied.
6. Creating a town
7. Placing Modded inventory block in the Town claim
8. Set NPC as Town Mayor
9. Leave the town
10. Remove Operator priveleges from user
11. go to a new plot and hit anything to reset your Towny cache. Then return to the original plot and try to open the chest.

12. Attempt to Right Click Modded Inventory Block. 

### What is the expected output?

Chat message to user: "Outsiders are not permitted to switch"
Modded Inventory block access denied to user with modded inventory within a town claim while not being a resident of said Town.
<img width="1454" alt="image" src="https://github.com/TownyAdvanced/Towny/assets/66577738/7a5da65d-fce5-4f94-90fd-415b60d629b4">

### Towny version

Towny version: towny-0.99.5.11

### Server version

Arclight Server version: arclight-forge-1.16.5-1.0.24

Minecraft version: 1.16.5

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://gist.github.com/Chickandduck/c1f9eb21e7fdaa79201fb3bae89484b5 (Pastebin had a 512 kb limit sorry!)
2. Your Towny config.yml: https://pastebin.com/8VLiJBS4
3. Your townyperms.yml: https://pastebin.com/fCbKysBW
4. Your log's error: Non applicable

**Comment by LlmDl** [comment]
Could you add one more step, after step 9, go to a new plot and hit anything to reset your Towny cache. Then return to the original plot and try to open the chest.

**Comment by Chickandduck** [comment]
> Could you add one more step, after step 9, go to a new plot and hit anything to reset your Towny cache. Then return to the original plot and try to open the chest.

Done and Info tool screen shot also

**Comment by LlmDl** [comment]
From the chat in Discord it appears that arclight is not throwing any event at all when a modded chest is opened when using the version supplied above.
