### ISSUE TITLE
SQL Error Unknown column 'uuid'

### ISSUE THREAD

**Issue by danyl756** [TownyAdvanced/Towny#6936]
### What steps will reproduce the problem?

During tax collection server tps drops to 0 due to sql error
I don't understand how to solve this, please help me

### What is the expected output?

Error-free tax collection

### Towny version

0.99.5.8

### Server version

1.16.5 purpur

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/c3hX48Kr
2. Your Towny config.yml: https://pastebin.com/VwN7Uqgq
3. Your townyperms.yml: https://pastebin.com/hHm8H0Y9
4. Your log's error: https://pastebin.com/yp06F85Q

**Comment by LlmDl** [comment]
What does your Hibernated Residents table look like?

**Comment by danyl756** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/55052043/fc69eadb-0201-4d0b-8e80-46ee3b94afbe)
![image](https://github.com/TownyAdvanced/Towny/assets/55052043/5673c07a-32f6-4ec2-8469-5cbf72a7bc59)
The table is empty

**Comment by LlmDl** [comment]
What version/type of mysql are you using exactly?

**Comment by LlmDl** [comment]
Check if this fixes it: https://cdn.discordapp.com/attachments/669247087329673228/1143006925265567765/towny-0.99.5.13.jar

**Comment by danyl756** [comment]
> What version/type of mysql are you using exactly?

10.7.4-MariaDB

**Comment by danyl756** [comment]
> Check if this fixes it: https://cdn.discordapp.com/attachments/669247087329673228/1143006925265567765/towny-0.99.5.13.jar

It didn't help

**Comment by LlmDl** [comment]
You may have to rename your name column to uuid, or drop the HIBERNATED_RESIDENTS table and let Towny re-make it with that new jar.

**Comment by danyl756** [comment]
It worked! Looks like the problem was in column 'name' which is now 'uuid'
Thank you very much for your help!
