### ISSUE TITLE
Breeding doesnt work in town claimed land

### ISSUE THREAD

**Issue by TheCrunchy** [TownyAdvanced/Towny#6942]
### What steps will reproduce the problem?

1. Create a new town, wait a min for towny to have processed the land
2. Spawn 2 cows
3. Breed those cows
4. XP is dropped but the baby doesnt spawn

### What is the expected output?

A baby should spawn

### Towny version

0.99.5.0.

### Server version

Paper 126 

### Please use Pastebin.com to link the following files

Config
https://pastebin.com/5TjA0tn0

Townyperms
https://pastebin.com/qAJxaNX8

No errors in logs 
[latest (9).log](https://github.com/TownyAdvanced/Towny/files/12410979/latest.9.log)

**Comment by LlmDl** [comment]
Towny doesn't do anything to stop breeding animals. Something else is causing this for you.

**Comment by TheCrunchy** [comment]
I doubt that is true when breeding works fine in the wilderness?

**Comment by LlmDl** [comment]
I expect its only a coincidence, or you have a plugin that uses the TownyAPI which is at fault.
