### ISSUE TITLE
"Wolf" type no longer a protected entity 

### ISSUE THREAD

**Issue by James-P-Bennett** [TownyAdvanced/Towny#6957]
### What steps will reproduce the problem?

1. Edit the settings/config.yml file.
`# Protect living entities within a town's boundaries from being killed by players or mobs.
  mob_types: Animals,WaterMob,NPC,Snowman,ArmorStand,Villager,Hanging,Wolf,Cat,Horse,Parrot,AbstractHorse,Axolotl,Camel,Cat,ChestedHorse,Chicken,Cow,Donkey,Fox,Frog,Goat,Hoglin,Horse,Llama,Mule,MushroomCow,Ocelot,Panda,Parrot,Pig,Rabbit,Sheep,SkeletonHorse,Steerable,Strider,Tameable,TraderLlama,Turtle,ZombieHorse`
 
2. Reload the configuration / server

3. Have a player not part of a town attack any tamed or untamed wolf type within the town's borders, they are still able to deal damage and kill the entities.

### What is the expected output?

No damage dealt with the lang message output "Outsiders are not allowed to destroy"

### Towny version

<summary>I'm gonna say it. Watch me say it. latest. There. I said it. Now what are you going to do about it?</summary>

**Towny Version: 0.99.5.0**

### Server version

Current: git-Purpur-2025 (MC: 1.20.1)*
Previous: git-Purpur-2019 (MC: 1.20.1)
* 25 version(s) behind

### Please use Pastebin.com to link the following files

1. **For security reasons I am not going to provide that.**
2. [Towny config.yml](https://pastebin.com/ACCzM2ZV)
3. [townyperms.yml](https://pastebin.com/naG8TtqA)
4. **There is no error output when searching error or warn keywords in server output @ TownyAdvanced**

**Comment by LlmDl** [comment]
I think we determined that this was because of the PVP setting, no?

**Comment by James-P-Bennett** [comment]
It was a PVP setting. The world's wilderness had pvp enabled but towns did not. And for those also encountering the issue that might stumble on this issue, I'll explain a bit.
When PVP is active, wolves can still pose a threat in claimed areas because they may become hostile towards players and attack them while remaining invulnerable. To mitigate this issue, the plugin developers likely made it to where they can be attacked by anyone within town claims no matter the town's pvp or protection status.

I'd like to change this into a feature request where in areas such as peaceful towns where PVP is not active, I propose that tamed wolves lacking aggression towards the attacking player, should remain invulnerable to harm and stay passive within the peaceful town limits.

**Comment by James-P-Bennett** [comment]
https://github.com/TownyAdvanced/Towny/issues/6983
