### ISSUE TITLE
Suggestion: Block change config for Camps

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#6961]
### **Please explain your feature request to the best of your abilities:**

If possible, it would be great if we could change the material for the block required to make a camp. If it could also support custom model data, that would be amazing. I know campfires are the obvious choice, but with custom model data, I'd love to make a custom tent block which would awesome. 

Something like this in the config, where custom model data is optional if supplied

Material: PAPER
CustomModelData: 10441

**Comment by LlmDl** [comment]
Currently we're using the Campfire's lit/unlit status to also show the camp's protection. I'm not sure I want to give that up.

**Comment by tomhmagic** [comment]
Oh no worries, I'll close this one. Was on the fly idea.
