### ISSUE TITLE
Plot Group Forsale causes error when no Economy-Plugin is installed

### ISSUE THREAD

**Issue by JaHollTV** [TownyAdvanced/Towny#6969]
### What steps will reproduce the problem?

1. Have a plot group
2. Have no Economy Plugin
3. Set the plot goup forsale with price of 0

### What is the expected output?

With no economy-plugin there should be always an overwrite for the price to 0 and if the price is 0 there should be no Error.

What woul realy help is an PlotGroupSetForSaleEvent, like the PlotSetForSaleEvent.
Then Servers with a custom minecraft independent economy can then send custom messages / handle custom economy.

### Towny version

0.99.5.0

### Server version

Paper 1.20.1

### Please use Pastebin.com to link the following files

Errorlog of    /plot group fs 0        https://pastebin.com/1Grn3yeu

**Comment by xCraimax** [comment]
Would be cool if this would get fixed.
