### ISSUE TITLE
Error when the attackers disconnect from the server (TownyCaptureSite)

### ISSUE THREAD

**Issue by levraimarius** [TownyAdvanced/Towny#6974]
### What steps will reproduce the problem?

1. The attackers start a battle
2. Defenders are connected
3. Attackers disconnect
4. An error message appears several times in the console
5. At the end of the battle the defenders lost the fortress

### What is the expected output?

Leave the fortress to the defenders

### Towny version

Towny v0.99.5.17
TownyCaptureSite v0.21.0

### Server version

Minecraft Paper 1.20.1

### Please use Pastebin.com to link the following files

https://pastebin.com/NRJpHdiG

**Comment by LlmDl** [comment]
I've taken a look at this and there shouldn't be a way to get this error easily. Can I see your TownyCaptureSites config?

**Comment by LlmDl** [comment]
It would also be helpful to see the leading up to this error as it is likely due to rebalancing the HP.

**Comment by levraimarius** [comment]
Yes of course : 

`  
version:
  # This is the current version.  Please do not edit.
  version: 0.21.0
  
  
capturesites:
  
  # How much HP does the CaptureSite homeblock have?
  capture_site_hp: '100'
  
  # How many seconds does a defender have to wait after they can use /t defender again.
  defender_spawn_cooldown: '360'
  
  # How much money is given to the town which controls a CaptureSite each hour, by default.
  # This is only given if the site is set to Money rewards.
  # Sites can be configured to give different amounts using /ta capturesite rewardmoney {amount}.
  money_reward: '100.00'
  
  # How much time passes in between rewards being given out to the town which has captured sites.
  # When set to 1 hour this will use Towny's NewHourEvent.
  # When set to any other time, the rewards will be paid out after the given amount of time has passed, after the server starts.
  # ie: If you set to 30m, 30 minutes after the server starts the towns will be rewarded, and again every 30 minutes.
  # This setting requires a full stop and start of your server to take effect.
  rewards_timer: 2h
  
  # How long does a CaptureBattle last if the attackers have not won?
  battle_duration: 20m
  
  # When set to true, a town in the same nation cannot take over a capturesite from a nation-member-town.
  prevent_same_nation_attacking: 'false'
  
  
  balancing:
  
    # When enabled, CaptureSite HP will be adjusted based on who is online at the start of a capture battle.
    enabled: 'true'
  
    # When enabled, CaptureSite HP are re-balanced when players log in or out during battles they are a part of.
    rebalancing_enabled: 'true'
  
  # How long after a battle has ended until another CaptureBattle can start?
  cooldown_after_battle: 1h
  
  # A per-town cooldown, affecting how often a town can use '/t capture' to iniate a battle.
  town_capture_command_cooldown: 1h
  
  # The colour used for the CaptureSite when it is displayed on a mapper like Dynmap-Towny.
  # If the capturesite is controlled by a town, the border-colour will use the town's map colour.
  town_map_colour_hex_code: ff0000
  
  # When either hitting or being hit, will non-involved players be teleported away to their town spawns, if they are in a CaptureSite with an active Battle?
  are_non_involved_players_teleported_away_when_they_are_in_combat: 'true'
  
  
  protections:
  
    # When true, defenders will always be able to use switches in the CaptureSites, allowing them more freedom of movement through doors.
    defender_switch_use: 'true'
  
    # A list of materials which will be allowed to be placed in Capture Sites.
    # Use names from this list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    # Ex: buildable_blocks_whitelist: TNT,LADDER
    # To allow everything use buildable_blocks_whitelist: *
    buildable_blocks_whitelist: '*'
  
    # A list of materials which will be allowed to be broken in Capture Sites.
    # Use names from this list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    # Ex: destroyable_blocks_whitelist: TNT,LADDER
    # To allow everything use destroyable_blocks_whitelist: *
    destroyable_blocks_whitelist: '*'
  
  # An optional override for your Dynmap infowindows. Leave this setting blank to have TownyCaptureSites construct the Dynmap infowindow using the town's status screen.
  # Placeholders you can use in this message:
  # - {controller} - Shows who currently has the site captured.
  # - {timesincelastcapture} - Shows how long it has been since someone captured the site.
  # - {reward} - Shows the reward for holding the capture site.
  # - {newline} - To create a new line.
  # You're also able to use CSS/HTML.
  dynmap_text_override: Forteresse contrôlée par {controller} {newline}depuis {timesincelastcapture}
capturessites:
  
  # When set to true, players that want to participate in attacking a CaptureSite's HP will also require the permission node 'townycapturesites.allowed_to_battle'.
  # If you have the balancing feature enabled it will also be affected, counting only those players which have the permission node.
  require_battle_permission_node: 'false'
  
  # When set above zero, this will limit how many CaptureSites a single town can control at one time.
  max_sites_per_town: '-1'
  
  # When set to true, towns which become conquered lose their CaptureSites.
  conquered_towns_lose_sites: 'true'
  
  
discord_embeds:
  
  # Set to true in order to send embeds to your Discord.
  enabled: 'true'
  
  # Supply your valid discord webhook url here.
  webhook_url: https://discord.com/api/webhooks/1146944967206506536/qnWsSTsyFZcj22StMBpjbty7K2EhePZt_xrZsPWSe59g5thVdLD6iyMQO-hP_vKkzzzy
  
  # The colour of the embed when a battle begins.
  attack_colour: c38414
  
  # The colour of the embed when a battle is won by an attacker.
  attack_won_colour: c02525
  
  # The colour of the embed when a battle is won by a defender.
  attack_defended_colour: 4ac932
  
  # The colour of the embed when a capture site is taken over with no battle (no defender controlled it.)
  no_contest_win_colour: 2698bd
`

**Comment by LlmDl** [comment]
And can you get me a slice of the log from the server logs folder that precedes the error?

**Comment by levraimarius** [comment]
https://paste.denizenscript.com/View/114876#9700

**Comment by LlmDl** [comment]
I have given Aznaar a copy that will stop it spamming/replace that spam with a helpful message in case it should happen again.
