### ISSUE TITLE
Suggestion: Eventwar Adding conquer and dynmap options

### ISSUE THREAD

**Issue by incristi2** [TownyAdvanced/Towny#6977]
### **Please explain your feature request to the best of your abilities:**

 When the defenders' home-block is knocked down, the choice to give money or to give their territory without /surrender can be over, because not everyone wants to lose their buildings.

And when a plot is captured, make another color or change ownership to the attacker, but only at the time of war, without right of grief.
It could help players to know which town-blocks were occupied in the case of a very large country.

Dynmap hide should be disabled in the war area.

**Comment by LlmDl** [comment]
As I understand it you want a few things:

1. When the homeblock has its HP dropped to 0, which will remove a town from the war, you want the losing town to pay money like they have run the /surrender command?

2. You want the townblocks-switch-towns feature but without griefing?

3. You want players to not be able to hide on dynmap.


----

3 will be done easily.

2 Is done by not using the townblocks-switch-towns feature. When a townblock loses its HP and the townblocks-switch-towns feature is disabled the townblocks stop being fought over. The town that drops the HP to 0 will get points for their work. No one will be able to grief the townblock. Players can see a townblock's HP and its attackable status using `/towny war hud`.

1 I'm not clear about what you want yet.
