### ISSUE TITLE
Suggestion: Add permission bypass for delete_old_residents

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#6978]
### **Please explain your feature request to the best of your abilities:**

Are you able to add a permission note for delete_old_residents checks. I'd like to be able to add some people to this so they won't get deleted.

**Comment by LlmDl** [comment]
This is already available and done using the Resident#isNPC() test. You can make a player into an NPC using `/ta toggle npc NAME`. We do it this way so we're not running permission tests on potentially offline players which will slow the purge task down.
