### ISSUE TITLE
Suggestion: Add lists or array to Towny MetaData

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#6979]
### **Please explain your feature request to the best of your abilities:**

If possible can you add support for lists or arrays for meta data?

**Comment by LlmDl** [comment]
I mentioned this on the Discord but I would like clarification here.

What sort of Lists are you wanting? Only Primitives, or are you hoping for things like Lists of Towns/Players?

**Comment by tomhmagic** [comment]
sorry been away. Yea I was mainly thinking primitive. So we could register the meta data just like the other types (number, bool, string) but have it be an array.
