### ISSUE TITLE
Suggestion: Protect parrots from being fed cookies in claims

### ISSUE THREAD

**Issue by Fruitloopins** [TownyAdvanced/Towny#6981]
### **Please explain your feature request to the best of your abilities:**

Currently if a player without permissions in a town feeds a cookie to a parrot it will take damage right up until it's about to die, this will cause it to teleport to the owner if they are online.

I think if possible there should be a check for if the user has destroy perms in the plot or something like that.

**Comment by LlmDl** [comment]
What the heck is minecraft doing with parrots and cookies these days...

**Comment by Fruitloopins** [comment]
I checked the wiki and it was apparently added shortly after they were added to the game because of this Reddit post https://www.reddit.com/r/Minecraft/comments/6b0fkh/dear_mojang_please_remove_feeding_chocolate_to/
