### ISSUE TITLE
Suggestion: Set wolf hostility state when entering peaceful town borders

### ISSUE THREAD

**Issue by James-P-Bennett** [TownyAdvanced/Towny#6983]
### **Please explain your feature request to the best of your abilities:**

Currently, When world PVP is active and a town has their PVP as false, wolves can still pose a threat in claimed areas because they may become hostile towards players for their actions outside of the town limits and attack them while remaining invulnerable. To mitigate this issue, the plugin developers likely made it to where they can be attacked by anyone within town claims no matter the town's pvp or protection status or the wolves hostility attribute when the world pvp is true. This has resulted in some grief situations where players will come through and kill everyone's wolves despite being non-hostile within towny claims.

In areas like peaceful towns, where PVP combat is not enabled, I suggest implementing a system where tamed wolves, which do not have any aggression towards players should remain completely immune to any harm. This immunity would extend specifically within the boundaries of the tranquil town environment. Essentially, this feature would ensure that tamed wolves residing in peaceful towns always maintain a passive and non-hostile stance towards players, guaranteeing their safety regardless of any PVP actions initiated by other players within or outside the town's limits. This enhancement not only adds a layer of anti-grief for players who have tamed wolves as companions but also gives the outsiders more protection.

**Comment by LlmDl** [comment]
I'm going through this and debugging things. I cannot get the wolves in a pvp-off plot to attack me from a pvp-on wilderness. Do you know of any tricks to get the wolf to aggro?

**Comment by James-P-Bennett** [comment]
For some reason this has turned out to be incredibly confusing and hard for me to explain so bear with me lol.

After testing it myself with world PVP enabled and a town's PVP disabled, wolves will now only attack/be attacked and deal damage in the wilderness but will still continue to try and attack players within a peaceful town's borders. So turns out I was sort of wrong about what I was saying before. 

I should instead update the feature request to change the state of wolves to no longer be hostile towards players when stepping into a peaceful town's border.

**Comment by LlmDl** [comment]
Alright, I am checking it out and when I agro a wolf in pvp-enabled wilderness, and then run into a pvp-disabled town, the wolf follows me and their damage is stopped.

Weirdly though, even though we're setting their target as null and their angry as false, they continue to try to attack me.

It is because the target is not properly being removed/their anger is not being stopped, that the player can then hurt them (because at that point Towny can tell the player is being targeted by an angry wolf.)

I will see about fixing the wolf's target-removal/de-agro.

**Comment by James-P-Bennett** [comment]
> Alright, I am checking it out and when I agro a wolf in pvp-enabled wilderness, and then run into a pvp-disabled town, the wolf follows me and their damage is stopped.
> 
> Weirdly though, even though we're setting their target as null and their angry as false, they continue to try to attack me.
> 
> It is because the target is not properly being removed/their anger is not being stopped, that the player can then hurt them (because at that point Towny can tell the player is being targeted by an angry wolf.)
> 
> I will see about fixing the wolf's target-removal/de-agro.

Right, seems like you beat me to the punch, I just uploaded a YouTube clip regarding that
https://www.youtube.com/watch?v=IyXpydShJ7c

**Comment by LlmDl** [comment]
Just to make an update:

I have managed to start preventing hurting tamed wolves from a pvp-disabled town, when the wolf is outside in the pvp-enabled wilds. 

I have found an issue in craftbukkit/spigot regarding wolves/some other mobs, where taking away their target can cause them to re-target the mob they last targeted. This means they target the player in a loop and is not super great.

**Comment by LlmDl** [comment]
I have managed to stop players in non-pvp areas being able to hurt wolves in pvp-areas, but the bug within spigot that causes the wolves to re-target is something I cannot solve for at the moment.
