### ISSUE TITLE
Suggestion: Config option to toggle outsider container access for ruins

### ISSUE THREAD

**Issue by Sk8nkill** [TownyAdvanced/Towny#6989]
### **Please explain your feature request to the best of your abilities:**

Config option to toggle outsider container access for ruins with TownyHistories.

**Comment by LlmDl** [comment]
At the moment it looks like TownyHistories is only protecting against build and destroy actions. Did you want the ability to disallow switch use? Or are you looking to have containers not protected from looting?

**Comment by Sk8nkill** [comment]
Yes, I was looking to disallow switch use within a ruin
