### ISSUE TITLE
Suggestion: Event fired when determining town, nation and resident prefixes 

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#6995]
### **Please explain your feature request to the best of your abilities:**

Useful if you want these to be dynamic, e.g. determined by the TownyCultures culture of a town, or the most popular culture of a nation, etc.

**Comment by LlmDl** [comment]
Town, Nation and Resident prefixes are all completely separate and determined differently.

Maybe its better to just make a Placeholder with what you actually want, ie: A TownyCulture PAPIPlaceholder?

**Comment by galacticwarrior9** [comment]
I apologise, I meant to type "events fired", not "event fired".

What I had in mind was replacing the prefix shown in /t and /n (for example), which a PAPI placeholder cannot do.

**Comment by LlmDl** [comment]
Ah. That is doable.
