### ISSUE TITLE
Suggestion: Command to remove town from top lists

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#6996]
### **Please explain your feature request to the best of your abilities:**

Are you able to create a /ta command to remove a town from one or all of the top list?

The command could look like: /ta town [townName] set list [land/balance/residents] [true/false]

I have a few NPC towns, especially for capturesites that have a lot of town blocks, and would like to remove them from the lists. Mainly as I use the placeholders to have a hologram top 5 display.

**Comment by LlmDl** [comment]
It would be easier to have them hidden across all of land/balance/residents lists and not have it individual, would that be acceptable?

**Comment by tomhmagic** [comment]
Oh yes, that would be fine. I would be hiding them from all anyway
