### ISSUE TITLE
Suggestion: Add a /plot set outpost spawn command to move outpost spawn points.

### ISSUE THREAD

**Issue by Tuaniwan** [TownyAdvanced/Towny#6998]
### **Please explain your feature request to the best of your abilities:**

For the command that lets you change the spawn location of an outpost plot/chunk:

`/plot set outpost spawn`

all params auto complete except for "spawn", not sure if there are other options other than "spawn" adding this would make it much more intuitive for players/admins, I have been around towny for many many years and I always thought that the only way to change an outpost's spawn point was to do `/plot set outpost`, which charges the town for the price of an entirely new outpost.

It could also be added to the wiki if it is not already.

**Comment by LlmDl** [comment]
So the commands are a bit outdated, and I might change things but currently this is how they work:

`/t claim outpost` claims a new plot and makes it an outpost.
`/plot set outpost` makes an already claimed plot into an outpost, it is a fairly recently-added command.
`/t set outpost` sets the spawnpoint of an already existing outpost. This aligns with `/t set spawn` and has been around a lot longer than `/plot set outpost`.
