### ISSUE TITLE
command return online players nicknames

### ISSUE THREAD

**Issue by Lemar98s** [TownyAdvanced/Towny#7003]
### **Please explain your feature request to the best of your abilities:**

On this screenshot I typed /t add f and get player names which is currently online.
![image](https://github.com/TownyAdvanced/Towny/assets/132149336/d8dc58ef-835a-48ee-9126-00e07d653437)
Offline players which have a f letter in nickname and are residents doesn't displays.

On my server there is no way to get the names of players who are online and in vanish, but typing such a command by an ordinary player can declassify the online status of players in vanish.
![image](https://github.com/TownyAdvanced/Towny/assets/132149336/5fd08133-d5f1-43f9-8512-0bb1a11980f8)

**Comment by LlmDl** [comment]
OK, so I've looked at the code and we're currently only offering online players, but we're filtering that list to hide players that the command-user cannot see (due to vanishing.)
```java
case "add":
	if (args.length == 2)
		return getVisibleResidentsForPlayerWithoutTownsStartingWith(args[1], sender);
	break;
```

So I'm guessing your only seeing players which aren't vanished?

**Comment by Lemar98s** [comment]
No, this command also outputs the players who are in vanish.

**Comment by LlmDl** [comment]
What system are you using to vanish players?

**Comment by Lemar98s** [comment]
PremiumVanish

**Comment by LlmDl** [comment]
If it this: https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/ please ask the author what they are using to hide players. We are using the normal Player#canSee() method to determine if player X can see player Y.

**Comment by Lemar98s** [comment]
I apologize for the delay in responding. I found some settings in the plugin configuration that we use and attach a link to them. Maybe it will be useful in solving the problem.

https://pastebin.com/kd12bKTj

**Comment by LlmDl** [comment]
Unfortunately that doesn't tell me if the plugin is actually using Bukkit's vanishing code.

**Comment by LeonMangler** [comment]
PremiumVanish does always use Spigot's standard Player#hidePlayer mechanism in recent Minecraft versions (1.19.3+) with an up-to-date ProtocolLib, so I see no problem with using Player#canSee on up-to-date servers. For supporting older servers, I suggest using the vanish metadata API, which requires no additional dependencies and also supports other popular vanish plugins like VanishNoPacket and SuperVanish (Details in PremiumVanish resource description).

**Comment by LlmDl** [comment]
What versions are you using for MC and ProtocolLib @Lemar98s ?

**Comment by yngdrms** [comment]
1.16.5
![image](https://github.com/TownyAdvanced/Towny/assets/79171955/061dccf1-8c25-4322-b155-48e7d625442e)
