### ISSUE TITLE
Nation claims (suggestion)

### ISSUE THREAD

**Issue by callmeaxo** [TownyAdvanced/Towny#7009]
### **Please explain your feature request to the best of your abilities:**

please make this an actual thing I was brainstorming things then  I thought why don't we claim chunks for nations so when a town come to that area they immediately join the nation so it save a lot of time 

and its optional so can you do it?

also make more sense bc towns don't claim chunks to make a country

**Comment by LlmDl** [comment]
The amount of coding required to make this happen makes this something I will probably not take on. I have plenty of things suggested by sponsors that will come first.

**Comment by callmeaxo** [comment]
but its a nice suggestion right?

**Comment by LlmDl** [comment]
It's a lot of work and I don't believe it would be a good fit.
