### ISSUE TITLE
Suggestion: New Placeholders 

### ISSUE THREAD

**Issue by AntiHrist-Miko** [TownyAdvanced/Towny#7033]
### **Please explain your feature request to the best of your abilities:**

Я предлагаю внести в плагин пару заполнителей, такие как: (пример)
%townyadvanced_town_{name}% 
%townyadvanced_nation_{name}% 
Которые будут выводить название определенного города. Так же и с: 
%townyadvanced_town_{name}_residents_amount% 
%townyadvanced_town_{name}_residents_amount% 
И всеми другими переменными, которые существуют. Можно хотя бы основными - название города, население, мэр города. 

Также, хочу чтобы разработчик ввёл в плагин boolean placeholders, Включено ли PVP и т.п. из списка (toggle). Потому что на данный момент, невозможно воссоздать TownyMenu с помощью Deluxemenus или попросту вывести информацию игроку о его городе...

**Comment by LlmDl** [comment]
This wont happen, the API is available for this sort of work.
