### ISSUE TITLE
Suggestion: Convert data from Residence

### ISSUE THREAD

**Issue by daniel-skopek** [TownyAdvanced/Towny#7041]
### **Please explain your feature request to the best of your abilities:**

It would be great if data could be converted from the Residence plugin (https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-20.11480/) to Towny.

**Comment by LlmDl** [comment]
As I understand, Residence is a cuboid protection plugin and there would be quite a bit of work involved in making cuboids into Towny's cells-on-a-grid system, with the ability to make things work 1:1 nearly impossible.
