### ISSUE TITLE
The players endlessly and just so writes off money from the city, HELP!

### ISSUE THREAD

**Issue by YgSnoMan** [TownyAdvanced/Towny#7047]
### What steps will reproduce the problem?

I can't know what led to this, but I tried both to completely cut off taxes, and to include them and limit them, I have a limit of 100,000, but people don't even have millions written off on payday

### What is the expected output?

I want a fixed amount to be debited from cities on payday (with us it is 18:00)

### Towny version

towny-0.99.6.2

the error was noticed much earlier

### Server version

1.19.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: java -Xms128M -Xmx$((16384-512))M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
https://drive.google.com/file/d/1VRAP03uYwNGKgI7SUaXBXQY8I4USqVXh/view?usp=sharing
2. Your Towny config.yml: https://drive.google.com/file/d/1Rveqw5njOSOs00veK1VKt5LT48dc_y3H/view?usp=sharing
3. Your townyperms.yml: https://drive.google.com/file/d/1Rveqw5njOSOs00veK1VKt5LT48dc_y3H/view?usp=sharing
4. Your log's error: -

**Comment by LlmDl** [comment]
Please use a pastebin service for the requested files, and re-explain what is happening, your translation is not clear.

**Comment by YgSnoMan** [comment]
The players' funds are simply debited from the city, the money from the city's bank is debited for nothing!!! there is no word about this in /t bankhistory, I tried both to completely remove taxes and to include them, the money is still written off

**Comment by YgSnoMan** [comment]
tax per day is set at 100,000, millions are debited from the city bank and not even during the new day "new_day_time"

**Comment by YgSnoMan** [comment]
the tax per day is set at 100,000, millions are debited from the city bank and not even during the onset of a new day "new_day_time", but in principle throughout the day with an unknown frequency

**Comment by LlmDl** [comment]
I want to see your startup and your config, on something like pastebin.com, not your googledrive

**Comment by YgSnoMan** [comment]
https://pastebin.com/pwjSsVQx

**Comment by YgSnoMan** [comment]
https://pastebin.com/N6CRgB0U

**Comment by LlmDl** [comment]
Your config:

```
  daily_taxes:
  
    # Enables taxes to be collected daily by town/nation
    # If a town can't pay it's tax then it is kicked from the nation.
    # if a resident can't pay his plot tax he loses his plot.
    # if a resident can't pay his town tax then he is kicked from the town.
    # if a town or nation fails to pay it's upkeep it is deleted.
    enabled: 'false'
```

You have configured it not to charge taxes and upkeep.

I still have not seen your latest.log's startup.

**Comment by YgSnoMan** [comment]
yes, I have now turned off the tax write-off so that the cities that still have money written off are not deleted

**Comment by LlmDl** [comment]
Show me your startup

**Comment by YgSnoMan** [comment]
https://pastebin.com/N6CRgB0U

**Comment by YgSnoMan** [comment]
perhaps there are problems with the translation to "startup" here it is

**Comment by LlmDl** [comment]
I want to see the latest.log startup, showing me your plugins enabling. I don't need to see your java arguments.

**Comment by YgSnoMan** [comment]
https://drive.google.com/file/d/1VRAP03uYwNGKgI7SUaXBXQY8I4USqVXh/view

**Comment by YgSnoMan** [comment]
it weighs over 50 mb I can't send it by text

**Comment by LlmDl** [comment]
I don't wand the google drive link it doesn't work for me.

**Comment by YgSnoMan** [comment]
which cloud can I use to send you this file?

**Comment by LlmDl** [comment]
```
[18:06:49] [Server thread/INFO]: [Towny]   Warning: EssentialsX Economy has been known to reset
                           town and nation bank accounts on rare occasions.
```

EssentialsXEconomy is known for resetting bank accounts. It cannot read Cyrillic characters either so towns will share an account.

Stop using EssentialsXEconomy.
