### ISSUE TITLE
Suggestion:Eventwar - make defeating bank plots give money

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7050]
### **Please explain your feature request to the best of your abilities:**

make defeating bank plots give a config amount of money (amount or percent) when using townblock hp

For wars that have multiple occupants (riots/alliance/world) have the amount split between all occupants, or even have it in each war type config where bank plot rewards can be customised.

**Comment by LlmDl** [comment]
Does this server use bank plots, forcing players to deposit and withdraw inside of them?

It would have to make it so that towns cannot unset bank plots when a war is on.

**Comment by tomhmagic** [comment]
yes we do, however having spawn also be a plot seems to make it a little useless. Would be nice if once a bank plot is made, you can no longer use the home plot. I can make another request if needed

**Comment by LlmDl** [comment]
Yeah something should be done in Towny itself to make bank plots a bit more involved.

**Comment by LlmDl** [comment]
I'm ready to do this one but I have a bit of an issue where the money is split amongst numerous groups on the attacker's side.

Currently when a townblock is brought to 0 hp there is only the one Town which brought it to 0hp. In the case where there are multiple towns attacking one plot, the town with the most attackers there will end up being chosen as the "one Town".

How important is it to split the money up beyond the chosen attacking Town which is already getting credit for removing the townblock from the war?

**Comment by tomhmagic** [comment]
I don't think it's that important, whatever you think is better and feasible.
