### ISSUE TITLE
in ja_JP, color syntax is translated

### ISSUE THREAD

**Issue by graycat27** [TownyAdvanced/Towny#7062]
> I will edit the incorrect colour tags, they have since been hidden because they should not have been translatable.  
_Originally posted by @LlmDl in https://github.com/TownyAdvanced/Towny/issues/7061#issuecomment-1787973084_

**Comment by graycat27** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/64903817/a854a847-53e5-4493-8e17-58a878afde40)

**Comment by LlmDl** [comment]
Already fixed on crowdin.
