### ISSUE TITLE
Doesn't save town plots on restart.

### ISSUE THREAD

**Issue by ZincHere** [TownyAdvanced/Towny#7065]
### What steps will reproduce the problem?

1. Adding town plots to your town. (this also includes existing ones)
2. Restart the server
3. Get the error 'Towny: This town does not have a spawn location.' and all town plots are switched to wilderness.

### What is the expected output?

I expected to see all of the town plots and plot types saved.

### Towny version

![image](https://github.com/TownyAdvanced/Towny/assets/141356354/0f837059-7107-47a8-848d-698e282dcf16)

### Server version

![image](https://github.com/TownyAdvanced/Towny/assets/141356354/6966a831-623a-444b-83c3-530f0b08bc6e)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/5ghjBhEB (btw anything that looks like weird characters is just the ChatColor plugin)
2. Your Towny config.yml: https://pastebin.com/Kkv0qY0G
3. Your townyperms.yml: https://pastebin.com/6FBmk5fM
4. Your log's error: "[13:06:24] [Craft Scheduler Thread - 8/WARN]: [Towny] Your towny\data\townblocks\ folder contains a folder named 'world' which doesn't appear to exist on your Bukkit server!
[13:06:24] [Craft Scheduler Thread - 8/WARN]: [Towny] Towny will load the townblocks regardless, but if this world no longer exists please delete the folder."

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by ZincHere** [comment]
Btw, this is my world name:
![image](https://github.com/TownyAdvanced/Towny/assets/141356354/fc654642-f082-4d66-a300-778bab9c828a)

If I try to rename it, it completely restarts a new seed! How do I fix that?

**Comment by LlmDl** [comment]
As I said on teh discord:

Move your three world folders from inside the world folder, into the server root folder.

Change your server.properties to use the new un-nested world names.
