### ISSUE TITLE
Suggestion: /townyworld toggle usebeds

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7076]
### **Please explain your feature request to the best of your abilities:**

/townyworld toggle usebeds

if having deny_bed_use to true, this makes it so you have to own the plot to use a bed or an inn plot.  But if you have other worlds where you don't want town creation but you want to allow sleep, they cannot.

**Comment by LlmDl** [comment]
I went to see what it would take to make this per-world today and found that this is already possible via permissions,

In any world you want players to use bed and set their spawn you just need to give players this node `towny.bypass_bed_restriction` in your permission plugin's per-world settings.
