### ISSUE TITLE
errors after restart

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#7078]
### What steps will reproduce the problem?

1. Write the command /towny reload db/all
2. see console

My coder made a structure plugin for towny, and it partially breaks when rebooting and there are errors in the console, please look

### What is the expected output?

no errors and the plugin works

### Towny version

Версия Towny: 0.100.0.0

### Server version

paper 1.18.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/614BzRZq
2. Your Towny config.yml: https://pastebin.com/B7QxAqYj
3. Your townyperms.yml: https://pastebin.com/azVGBGW7
4. Your log's error: https://pastebin.com/614BzRZq

**Comment by LlmDl** [comment]
Looks like your coder broke it, have them fix it.

**Comment by TheSirCororo** [comment]
> Looks like your coder broke it, have them fix it.

No. After my experiments I found out that Towny recreated `Town` object after plugin reloading and `equals` with `hashCode` method had broken and my HashMap had broken. I think you should override `equals` and `hashCode` method in `Town` object to prevent this.
