### ISSUE TITLE
Tnt damage reverting even though I have it disabled in the config

### ISSUE THREAD

**Issue by AdaptableRuben** [TownyAdvanced/Towny#7079]
### What steps will reproduce the problem?

1. Download the config of towny
2. Install it on any server
3. Start the server and blow up a tnt to reproduce it

### What is the expected output?

No damage from the tnt should be reverted according to what the config has ben set too

### Towny version

0.100.0.0

### Server version

Paper 1.20.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
https://pastebin.com/Sm5mkye8 player ips has been removed from the logs file

2. Your Towny config.yml:
https://pastebin.com/VX1GA0k6

3. Your townyperms.yml:
https://pastebin.com/ntR2faei

4. Your log's error:
No error log seems to appear in console

I dont know exactly if its a bug altrough from looking the config file it looks like some logic error in the code since there is no error appearing in console, I tried many fixes like messing around with the config by changing values and having installed the latest version to see if its fixed and after testing found this issue was still persistent so I dediced to report it since its quite strange.

Video showing the issue: https://www.youtube.com/watch?v=XxDzgp_f6Jw&ab_channel=AdaptableRubenGaming

**Comment by Warriorrrr** [comment]
This option is in the new world settings section of the config, as the name states these are only applied to new worlds. Use the /tw command to toggle it instead.

**Comment by AdaptableRuben** [comment]
Managed to fix it so thank you, I sometimes get confused when theres a ton of stuff in a plugin
