### ISSUE TITLE
Tab completion not working properly

### ISSUE THREAD

**Issue by Spruce-Studios** [TownyAdvanced/Towny#7080]
### **Please explain your feature request to the best of your abilities:**

Hello! The command /t shows correctly in the tab-completion menu. However, players who don't have access to things like /t claim and /t buytown can still see them in the tab completion menu!

This is the #1 reason players are leaving my server. They get overwhelmed by all the options, even though they're disabled and ones I don't want them to use.

Is there any way to hide these arguments from the menu? Please help!

**Comment by LlmDl** [comment]
Tab completion code runs on every character they type, if you want your server also doing permission tests with every letter they type, then your suggestion would be acceptable. The code is the way it is, assuming that most servers don't want permission tests happening that frequently.

**Comment by Spruce-Studios** [comment]
> Tab completion code runs on every character they type, if you want your server also doing permission tests with every letter they type, then your suggestion would be acceptable. The code is the way it is, assuming that most servers don't want permission tests happening that frequently.

Would it be added as an option in config then? Something like tab-complete-all: true
Defaulted to true, and when false it would run permission checks with each character

**Comment by LlmDl** [comment]
I'm currently accepting feature requests from people who are sponsors. Less than 1% of servers are sponsoring.
