### ISSUE TITLE
> Looks like your coder broke it, have them fix it.

### ISSUE THREAD

**Issue by 1Pootis1** [TownyAdvanced/Towny#7083]
> Looks like your coder broke it, have them fix it.

No. After my experiments I found out that Towny recreated `Town` object after plugin reloading and `equals` with `hashCode` methods had broken and my HashMap had broken. I think you should override `equals` and `hashCode` method in `Town` object to prevent this.

_Originally posted by @TheSirCororo in https://github.com/TownyAdvanced/Towny/issues/7078#issuecomment-1807187231_

**Comment by LlmDl** [comment]
There's already a PR for what they're asking. You should consider sponsoring.
