### ISSUE TITLE
Capturesite minimum hieght not saving

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7088]
### What steps will reproduce the problem?

Start battle
Health will not go down
run /ta capturesite setminheight NUMBER
Health will start to go down

### What is the expected output?

Min height to save and HP to go down

### Towny version

towny-0.100.0.3
TownyCaptureSites-0.22.0

### Server version

1.20.2

### Please use Pastebin.com to link the following files

Capturesite Config - https://pastebin.com/sXhYkhq3

No errors in logs

**Comment by tomhmagic** [comment]
returned

**Comment by LlmDl** [comment]
![868qzs](https://github.com/TownyAdvanced/Towny/assets/879756/7d526765-af0e-47f8-bf5a-6d1d992cdcd0)
