### ISSUE TITLE
Add the Towny-Block-Glitching fix from TownyCombat into Towny

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#7095]
### **Please explain your feature request to the best of your abilities:**

It has been a problem in Towny for years, which apparently has a fix but for some reason is gated behind the TownyCombat plugin.
Why cant this be an option in Towny itself? It feels a bit unfair as this block glitch is like an actual glitch.

![image](https://github.com/TownyAdvanced/Towny/assets/1515422/8716c7c8-65f6-4c7d-83ee-dcd4bbd03c53)

**Comment by LlmDl** [comment]
I have always thought this was something reserved to an anti-cheat plugin.

**Comment by Caleston** [comment]
> I have always thought this was something reserved to an anti-cheat plugin.

Which anti-cheat plugin is recommended by Towny for fixing the Towny block glitch?
