### ISSUE TITLE
DiscordSRV broke on 0.100.0.6

### ISSUE THREAD

**Issue by cobrex1** [TownyAdvanced/Towny#7106]
### What steps will reproduce the problem?

When I updated to 0.100.0.6 server -> discord chat stopped working. This is also the case for 0.7.
I reverted to 0.5 and server -> discord chat still not working but was working before updating to 0.6
Discord -> server works fine on all the versions tested from 0.5 to 0.7
Disabling towny totally and server -> discord works fine again.

### What is the expected output?

When chatting in global channels, expect to see chat in discord minecraft-chat channel. 

### Towny version

0.100.0..6 & 0.7

### Server version

Paper 1.20.2 release 298 and 307

### Please use Pastebin.com to link the following files

There are no errors on start-up. TownyChat is not installed as I use venturechat

**Comment by LlmDl** [comment]
I don't think Towny can stop DiscordSRV doing its job. The update to 0.100.0.6 and it not working was probably just coincidence.

Does the startup show discordsrv loading?

**Comment by LlmDl** [comment]
it was discovered it was not being caused by towny
