### ISSUE TITLE
Suggestion: Ability to toggle off "Friendly Fire"

### ISSUE THREAD

**Issue by Veyronity** [TownyAdvanced/Towny#7115]
### **Please explain your feature request to the best of your abilities:**

Friendly Fire is where you can /plot toggle pvp on or /t toggle pvp on on someone when it's a resident, but not outsiders.
While there may be good reasoning behind it, I've personally seen nothing but harm from it.
So to make both sides happy, just make it togglable.
Something like /t toggle friendlyfire on/off will work
Thank you.

**Comment by LlmDl** [comment]
Friendlyfire is toggle-able per world with /tw toggle friendlyfire. Likewise, if friends want to fight they can do so in Arena plots (set with /plot set arena.)

I am currently taking suggestions from sponsors only. Only 1% of servers are sponsoring the time I put into Towny and that is not enough.
