### ISSUE TITLE
Nation/Town Disbanning

### ISSUE THREAD

**Issue by LittleDuck363** [TownyAdvanced/Towny#7132]
### What steps will reproduce the problem?

1. Create a town and nation.
2. Add members to the said nation and town.
3. Have one of those members leave the town.
4. The town or nation will randomly disban or the town will leave the nation, even if the town is the capital of the nation.

### What is the expected output?

The member to leave the nation/town without either disbanning or not having the town leaving the nation even if it's the capital.

### Towny version

0.100.0.11

### Server version

1.20.2 build #318

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/EvfwX1kg
2. Your Towny config.yml: https://pastebin.com/8H2wWNi2
3. Your townyperms.yml: https://pastebin.com/A59JgfUX
4. Your log's error: No error occurs, it just happens.

**Comment by LlmDl** [comment]
Your startup was not included, just some random logs. I've sent you a jar to test out on Discord.

**Comment by Warriorrrr** [comment]
Did the jar end up being tested?

**Comment by LittleDuck363** [comment]
Yes, it still kicks the capital town from the nation whenever someone leave the town.Sent from my iPhoneOn Dec 27, 2023, at 12:04 PM, Warrior ***@***.***> wrote:﻿
Did the jar end up being tested?

**Comment by LittleDuck363** [comment]
Also, when another town leaves a nation it kicks the capital from the nation too.Sent from my iPhoneOn Dec 27, 2023, at 12:04 PM, Warrior ***@***.***> wrote:﻿
Did the jar end up being tested?

**Comment by LlmDl** [comment]
Can you show me your logs @LittleDuck363 of this occurring with the jar I gave you?

**Comment by LittleDuck363** [comment]
Paper 1.20.2 Server Log [#nwHGxKP]mclo.gsSent from my iPhoneOn Dec 27, 2023, at 1:24 PM, LlmDl ***@***.***> wrote:﻿
Can you show me your logs @LittleDuck363 of this occurring with the jar I gave you?

**Comment by Warriorrrr** [comment]
Where in the log did the issue occur?

**Comment by LlmDl** [comment]
I am not seeing a log...

**Comment by LlmDl** [comment]
Thank you for getting the log clickable Warrior, @LittleDuck363 I don't see any occurrence of a leave command being used in the log. Can you please attach a log showing someone using /n leave and then the resulting disbanding.
