### ISSUE TITLE
Suggestion: Is there a way to delete the wild chunky ， regen chunky？

### ISSUE THREAD

**Issue by xiaoluofa** [TownyAdvanced/Towny#7135]
### **Please explain your feature request to the best of your abilities:**

Is there a way to delete the wild chunky ， regen chunky？
Regenerate field materials and treasure chest
Reduce storage

**Comment by LlmDl** [comment]
I am unlikely to add this as a feature. A plugin that already regenerates the world can use our API to not regenerate areas that have towns.
