### ISSUE TITLE
Suggestion: Config option to prevent claiming water chunks

### ISSUE THREAD

**Issue by HerbertsStudios** [TownyAdvanced/Towny#7136]
### **Please explain your feature request to the best of your abilities:**

Please add an ability to prevent claiming water chunks, what i mean is if the entirety of the surface is water like an ocean chunk then it wont be allowed to be claimed

I have this issue where people keep claiming chunks of water near towns that have a large coast line so they can just tp to it and prevent having to actually go to the town

**Comment by LlmDl** [comment]
This is a feature in TownyProvinces already. but that plugin has a _lot_ more going on that just blocking water claiming. I might look into what it would take to make this a standalone plugin/feature after Christmas.

**Comment by HerbertsStudios** [comment]
Alright thank you, it would be cool if it was a base feature as many users do not use towny provinces. Happy holidays!

**Comment by LlmDl** [comment]
Yeah TownyProvinces is something you have to implement from teh start or not at all.

Of note:
This will have to be based off of the chunk's biome. Using just surface water will result in players just building some dirt on the water to bypass the plugin. I will likely do some sort of threshold of ocean-variety biome: if its greater than 50% ocean you cannot claim it.

**Comment by HerbertsStudios** [comment]
Sounds good, could the threshold be a configurable percentage?

**Comment by LlmDl** [comment]
Yep
