### ISSUE TITLE
Suggestion: Please make min_plot_distance_from_town_plot for NPC Town

### ISSUE THREAD

**Issue by Yeon228** [TownyAdvanced/Towny#7147]
### **Please explain your feature request to the best of your abilities:**

Can yon add min_plot_distance_from_npc_town_plot just for NPC town?
In this time npc town and normal town share this value so I have many inconvenience to make NPC [town]([url](url))

**Comment by LlmDl** [comment]
`/ta town new [townname]` no longer uses proximity rules.
