### ISSUE TITLE
Town Names not displaying in Action Bar when entering/leaving

### ISSUE THREAD

**Issue by xenxero1** [TownyAdvanced/Towny#7148]
### What steps will reproduce the problem?

1. Create a town (or have players do so).
2. Enter or leave the border
3. Inspect Action bar

### What is the expected output?

Expected to see the town name upon entering it's borders.

### Towny version

0.100.0.0

### Server version

1.20.4 Paper

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
https://pastebin.com/PmD5EUH5

2. Your Towny config.yml:
https://pastebin.com/7fW64sap

3. Your townyperms.yml:
https://pastebin.com/iwYaSsXT

4. Your log's error:
N/A -- No error generated.

**Comment by xenxero1** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/14264597/a66c54ed-e3c4-4670-84e2-0552f2975df7)
Other plugins installed that could cause a conflict. I've confirmed that the Jobs plugin still makes use of the action bar to display money and XP gains, whereas Towny is not functioning as expected.

**Comment by Warriorrrr** [comment]
Update towny
