### ISSUE TITLE
Suggestion: Ceding/giving chunks 

### ISSUE THREAD

**Issue by HerbertsStudios** [TownyAdvanced/Towny#7149]
### **Please explain your feature request to the best of your abilities:**

right now theres no real good way to give chunks to other towns, maybe add a new perm node town.cede where you can do /plot cede town_name and it is given to the town

**Comment by LlmDl** [comment]
This gets a bit hairy in that there's all sorts of rules about distances between towns. 

Before I add this I would want to have the code consolidated to something so there's no duplication of tests so things can stay consistent going forward.

FWIW admins can flip plots for towns using `/ta set plot [townname]` for players that want to do this now.

**Comment by Warriorrrr** [comment]
What's wrong with unclaiming and having the other town re-claim?

**Comment by LlmDl** [comment]
I've had other people want to have something immediately flip plots in the past, where the server uses the revert on unclaim or plot-clearing features and unclaiming results in blocks being displaced.

https://github.com/TownyAdvanced/Towny/pull/7151 is my first step towards making things a bit more uniform as for whether a plot should be allowed to flip to a different town.

**Comment by LlmDl** [comment]
You don't have to contribute suggestions any longer.

**Comment by Caleston** [comment]
> You don't have to contribute suggestions any longer.

Oh? Sorry I didn't know that. You implemented my suggestion last week so had no idea there was an issue with me.
I just thought your earlier description sounded a lot like my then-sponsor suggestion https://github.com/TownyAdvanced/Towny/issues/6295
