### ISSUE TITLE
Not work /t deposit

### ISSUE THREAD

**Issue by jabaGR** [TownyAdvanced/Towny#7156]
The money is withdrawn, and the message "You dont have that much" is displayed
Use CoinEngine

**Comment by LlmDl** [comment]
CoinEngine does not implement Vault properly: https://github.com/nulli0n/CoinsEngine-spigot/blob/5f59acb78b491d7cf9f65def5503b4965ee5477b/src/main/java/su/nightexpress/coinsengine/currency/impl/CurrencyEconomy.java#L56

This is not an issue with Towny.
