### ISSUE TITLE
Plot Names/Notifications Aren't Displayed in Chat

### ISSUE THREAD

**Issue by cwilde98** [TownyAdvanced/Towny#7157]
### What steps will reproduce the problem?

My towny server has an issue where the plot/town/wilderness notifications do not show in chat.
Much like the same as this issue:
https://github.com/TownyAdvanced/Towny/issues/3325
Yes, I have disabled titles.
Yes, I have enabled notifications.

### What is the expected output?

I want the town name/plot notifications to show in chat when entering a town so you know where you are like it should by default.

### Towny version

Towny Version: 0.100.0.0

### Server version

1.20.4

### Please use Pastebin.com to link the following files

1. [Your full server startup from the logs\latest.log:](https://pastebin.com/udSwnW3i)
2. [Your Towny config.yml:](https://pastebin.com/w9gLNcJC)
3. [Your townyperms.yml:](https://pastebin.com/2imLs4zu)

**Comment by LlmDl** [comment]
For 1.20.4 support update Towny to the latest pre-release version.
