### ISSUE TITLE
Suggestion: Prevent Home Block bank transactions if bank plot avaliable (with is_banking_limited_to_bank_plots true)

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7162]
### **Please explain your feature request to the best of your abilities:**

When using is_banking_limited_to_bank_plots it would be nice to then block residents from interacting with the town bank from the home block as well if a bank plot is supplied

mentioned in comments of https://github.com/TownyAdvanced/Towny/issues/7050
thought it best be its own request

**Comment by LlmDl** [comment]
So if they have a bank plot, they cannot use their homeblock any longer?

**Comment by tomhmagic** [comment]
yes only if they have set is_banking_limited_to_bank_plots to true.
