### ISSUE TITLE
Suggestion: Add ability for /ta town new NAME to bypass proximity claiming rules.

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7163]
### **Please explain your feature request to the best of your abilities:**

Add a force argument when using /ta set plot (town) to override proximity rules

could be a --force at the end of all the separate types of /ta set plot

**Comment by LlmDl** [comment]
The way this command currently works, is that if there is a town at the location, the townblock flips over to the specified town.

If there is no Town present you can use the normal /ta set plot townname rect 4 area claiming which will only select other plots with no town present. 

The proximity rules are not applied to either of these.

**Comment by tomhmagic** [comment]
oh I may have miss remembered the command I ran, I was making some admin made towns for different things and couldn't create a town near another. Does /ta town new use proximity rules?

**Comment by LlmDl** [comment]
`/ta town new NAME` does go through the normal proximity tests. I'm doing to consolidation/refactoring on claiming rules code and when I'm done that it should be pretty easy to get things override-able for admins making new towns.

**Comment by LlmDl** [comment]
This one was a simple add to the PR already started.

**Comment by LlmDl** [comment]
Turns out what I thought was only in the PR was in fact already merged previously, so it has gone in early.
