### ISSUE TITLE
Suggestion: Add a way for towns to make plots either only for new residents or not

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7164]
### **Please explain your feature request to the best of your abilities:**

Add an argument to the /plot toggle command for Mayors to set plots to be only for new residents (owns 0 plots) or only for current residents (1+ plots)

Command could be something like
/plot toggle claim all/new/old

/plot toggle claim all - default when setting up plots, allows all residents to /plot claim
/plot toggle claim new - only residents with 0 plots can /plot claim
/plot toggle claim old - only residents with 1+ plots can claim

This allows Mayors to create dedicated plots for new residents, especially for an open town, maybe at a cheaper price but preventing older residents to claim them all. 

Vice versa for the only old residents, allows Mayors to decide where they want old residents to claim, maybe at a higher cost.

**Comment by Warriorrrr** [comment]
Why would this be needed?

**Comment by tomhmagic** [comment]
> Why would this be needed?

It creates a way for Mayors to designate plots to either just new joining members, or current members.

New member's plots can be cheaper without old residents taking them and mayors can be assured that if they set up an area for new joins, that it will actually be there for when new players join

> I will be adding this at some point, I just haven't decided how to go about setting who is new to town, ie a mayor or admin decision.

Would it be easier just to block anyone who has 1+ plots for a new plot, and vice versa for an old plot, blocking anyone with 0 plots?

**Comment by LlmDl** [comment]
> Would it be easier just to block anyone who has 1+ plots for a new plot, and vice versa for an old plot, blocking anyone with 0 plots?

Yeah that works fine up until someone wants them to have 2+ plots.

**Comment by tomhmagic** [comment]
I'm not sure I understand. The newby plots would only be for new joining members, so someone with 0 plots. Or are you trying to make it more dynamic where the mayor can choose the minimum needed for that plot?

**Comment by LlmDl** [comment]
I'm just future-proofing the idea because once you add something, someone will come along wanting the same thing, just a tiny bit different.

What I'll likely end up doing it making up something the mayors can set into the plots themselves, which will restrict /plot claim to people with a joined-town date of X days ago or less.

There's already a max-plots system for residents/resident ranks that can limit how many plots a resident can own based on their permissions (ie: their town ranks.)
