### ISSUE TITLE
Suggestion: Towny Capture Sites Attack Time/Spawn Points

### ISSUE THREAD

**Issue by TylorTurner** [TownyAdvanced/Towny#7168]
### **Please explain your feature request to the best of your abilities:**

We have peak hours for players, It would be nice to have a time set when players can attack the captures site. Additionally kicking out owner ship of all the sites when the timer is up.

The spawn points can be an issue to with the capture point, spawn points being in the same chunk it can cause unfair fights

**Comment by LlmDl** [comment]
I am prioritizing tickets made by sponsors these days. If you would like to renew your sponsorship I would re-prioritize this ticket.
