### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by Ricola4325** [TownyAdvanced/Towny#7169]
### **Please explain your feature request to the best of your abilities:**

I dont know if its a feature that we already have, but I couldn't find any config for it.

I want to know if it would be possible to set a config for overriding explosions protection for Towny claims within a siegezone area. Also if there could be a linked config for this to allow block regeneration after a battle session. Thanks!

**Comment by LlmDl** [comment]
SiegeWar doesn't have any explosions/block regenerations added to it at the moment.

**Comment by Peskdt** [comment]
That would be cool for cannons integration or simply prisions breaking for prisioner release mechanics
