### ISSUE TITLE
Suggestion: discord webhook integration

### ISSUE THREAD

**Issue by HerbertsStudios** [TownyAdvanced/Towny#7185]
### **Please explain your feature request to the best of your abilities:**

Could towny have some sort of built in webhook integration? like in the console you put in your webhook url and have a file like lang called messages where you can edit what messages go and what commands fire message events

**Comment by LlmDl** [comment]
This is something which was covered already in the TownyTweaks plugin: https://www.spigotmc.org/resources/townytweaks.106463/

**Comment by HerbertsStudios** [comment]
Oh my bad

**Comment by LlmDl** [comment]
No worries
