### ISSUE TITLE
[Bug] Towny making problems on our server when nation is used, returning either "Null", "Internal Error" or nothing at all

### ISSUE THREAD

**Issue by ACH1980** [TownyAdvanced/Towny#7190]
### What steps will reproduce the problem?

Not sure if it's able to being reproduced, but here is what I've done:
1.: Create a Town
2.: Create a Nation with the Town from step 1 as capital
3.: 
a) Execute `/t`, `/t [name]`, `/town`, `/town [name]`, `/n`, `/n [name]`, `/nation` or `nation [name]` and get not response
b) Execute `/towny prices` and get an Internal Error back
c) Execute `/t here`, `/town here` and get `Null` back

### What is the expected output?

a) The towns or nations status (depending on whether the town or the nation command are being used)
b) getting an overview over townies prices.
c) getting a list of towns/nations (depending on which command was used)

### Towny version

v0.93.0.0

### Server version

1.12.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: 
[startup.txt](https://github.com/TownyAdvanced/Towny/files/13924392/startup.txt)

2. Your Towny config.yml: 
3. Your townyperms.yml:
4. Your log's error:
a) 
[message2.txt](https://github.com/TownyAdvanced/Towny/files/13924424/message2.txt)
b) 
[message1.txt](https://github.com/TownyAdvanced/Towny/files/13924441/message1.txt)
c) 
[message.txt](https://github.com/TownyAdvanced/Towny/files/13924511/message.txt)

Please note: We are a quite big network with quite a bunch (28 to be exact) of modpacks each being played by a good amount of players, so changing the network is not an option. Therefore if we gonna change to a newer towny versions it has to support all our server versions.

**Comment by LlmDl** [comment]
You're incredibly out of date, even for 1.12.2. Update to this: https://github.com/TownyAdvanced/Towny/releases/tag/0.97.0.0for1.12.2

If you still have issues re-submit a ticket where you haven't skipped parts of the form, the parts you skipped would have been useful.

**Comment by ACH1980** [comment]
Yeah the problem is, that 1.12.2 is not our oldest version. Our oldest modpacks are still 1.5.2. Also our Owner didn't wanted to give me the configs he said I should try it without them, because he didn't think it's relevant for the issue. I told him that even if it's not  relevant to the issue itself that info would be needed to be able to reproduce it, but he didn't wanted to provide that info anyway. So atm I'm not able to provide those files :(
