### ISSUE TITLE
Suggestion: Add revertblockexpl and revertentityexpl for Towns

### ISSUE THREAD

**Issue by Ricola4325** [TownyAdvanced/Towny#7192]
### **Please explain your feature request to the best of your abilities:**

Right now we have nodes for:
- towny.command.townyworld.toggle.revertentityexpl
- towny.command.townyworld.toggle.revertblockexpl

These apply only for Wilderness, it would be excelent if it can be added also for Towns as this can work excelent with SiegeWar to toggle force explosions with regen.

**Comment by LlmDl** [comment]
I am hesitant to do any reverting in towns when explosion reverting is not a perfect system. If explosions are rolled back imperfectly you cannot consider Towny a true protection plugin any longer.

I am currently primarily considering suggestions from sponsors.
