### ISSUE TITLE
[CaptureSites] Make it possible to stop the using_titles messages when entering a capture site.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#7210]
### **Please explain your feature request to the best of your abilities:**

Or make them describe entering a CaptureSite.

**Comment by mcmixlandnet** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/106306516/2e1e3d54-0053-4e95-ba9b-20688270debb)

Information about CapturSites is displayed as a city in the scoroboard and on the screen.
