### ISSUE TITLE
Towny Using Colours in Titles

### ISSUE THREAD

**Issue by cwilde98** [TownyAdvanced/Towny#7215]
### What steps will reproduce the problem?

Set your permissions so that you are not able to use essentials/townychat colours in chat.
Do /t set title [name] &aTest
The colours work and players are able to create custom coloured prefixes when I do not want them to

### What is the expected output?

A permission to use colours in titles (then I can make it so only kings can add colours etc)

### Towny version

0.100.1.0

### Server version

1.20.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Skipped the form, otherwise I'd probably be able to answer you.

**Comment by LlmDl** [comment]
Actually, this was already documented: https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#towny-titles-and-surnames
