### ISSUE TITLE
Suggestion: Add title and surname colours to a permission

### ISSUE THREAD

**Issue by cwilde98** [TownyAdvanced/Towny#7217]
### **Please explain your feature request to the best of your abilities:**

Instead of title or surname colours being either ON or OFF via the regex, have it as a permission. I will give you an example scenario: Kings can set peoples titles and surnames with colours, mayors can not.
This just adds a tiny bit of flexibility. Thank you.

**Comment by LlmDl** [comment]
I am currently prioritizing suggestions from sponsors, as they are supporting development and keep me busy.

**Comment by LlmDl** [comment]
I have an ongoing pull request to change how NameValidation is handled and I might be able to work this in.
