### ISSUE TITLE
Suggestion: Bankhistory to book & quill?

### ISSUE THREAD

**Issue by byggmesterPRO** [TownyAdvanced/Towny#7234]
### **Please explain your feature request to the best of your abilities:**

I would just wish there was a `/t bankhistory write` command. Since there is no way I know of to save the bankhistory your town makes I would love for there to be a command like `/t bankhistory write` where you could hold a book & quill and it would write down the history into it and signs it to prevent editing.
That would be baseline, if you would like to make it more fancy where it potentially charges the town a certain amount of money for a signed book of the bankhistory and it will be placed in the owners inventory or potentially a town chest.

Thank you, I would only like the `/t bankhistory write`.

**Comment by LlmDl** [comment]
I am currently taking suggestions from sponsors only. Only 1% of servers are sponsoring the time I put into Towny and that is not enough.
