### ISSUE TITLE
{channelTag} does not show up in chat

### ISSUE THREAD

**Issue by sleezydread** [TownyAdvanced/Towny#7239]
### What steps will reproduce the problem?

1. uploading `TownyChat-0.112.jar` and `Towny-0.100.1.0.jar` to my server's plugins folder
2. launching server as an op
3. writing a message in chat

### What is the expected output?

I expect to see the {channelTag} before {worldname} after I send a message in chat 
![javaw_TLqmrPvbzj](https://github.com/TownyAdvanced/Towny/assets/119277477/bf113878-973c-4b0a-aa44-31e8f4ebc25e)

### Towny version

Towny 0.110.1.0

### Server version

v1_20_R2 - 1.20.2 - paper  git-Paper-318 (MC: 1.20.2)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/VB2y4HkM
2. Your Towny config.yml: https://pastebin.com/UZsdeyDy
3. Your townyperms.yml: https://pastebin.com/hax60ucj
4. Your log's error: N/A

(optional) If this is to do with permissions,
5. Your permissions file: N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/C3p8uwhi
7. Your channels.yml: https://pastebin.com/gWZ3r7tf

**Comment by w1th0utme** [comment]
I am using towny version 0.100.1.11 and townychat version 0.113 and the problem still persists

**Comment by LlmDl** [comment]
0.114 fixes it
