### ISSUE TITLE
[EventWar] Suggestion: Add AngelChest support to prevent graves for warring players that die in warzones.

### ISSUE THREAD

**Issue by DarioMavilia** [TownyAdvanced/Towny#7243]
### **Please explain your feature request to the best of your abilities:**

Hook into the AngelChest API so that the plugin follows keep inventory (or lack of) functions set by the war config.

Link to the API: https://github.com/JEFF-Media-GbR/AngelChestAPI

When `disable_keep_inventory` is set to true: Inventories are dropped during war like normal, but players not dying in a war will spawn a grave using Angel Chests. 

Similar behaviour for `drop_inventory_of_3rd_party_actors`.

**Comment by LlmDl** [comment]
https://github.com/JEFF-Media-GbR/AngelChestAPIExample/blob/master/src/main/java/de/jeff_media/AngelChestAPIExample/ExampleListener.java
