### ISSUE TITLE
Suggestion: TownyFlight Temp Flight

### ISSUE THREAD

**Issue by tomhmagic** [TownyAdvanced/Towny#7252]
### **Please explain your feature request to the best of your abilities:**

Add a temp fly part of towny flight to give people temporary perms to fly, then the flight gets cancelled after the timer.

something like /tfly temp [resident] [time]

time takes seconds unless m/h/d is supplied

for example

/tfly temp tomhmagic 100 = 100 seconds
/tfly temp tomhmagic 1h = 1 hour

if you are also able to do placeholders for the amount of fly time left would be awesome, either that a /ta command to check a user has the permissions to fly as I we use CMI temp fly at the moment, and I use these placeholders to create a staff check command to make sure someone can fly and isn't hacking

%townyflight_player_temp% – Left temp fly amount in seconds
%townyflight_player_temp_formatted% – Formatted temp fly amount

**Comment by LlmDl** [comment]
From people who've spoken about this sort of thing in the past, I've gathered that time is usually only counted against the player while they are actually in the air flying. This is desirable, right?

**Comment by tomhmagic** [comment]
Either way works for me, I don't mind. It would be nice so if people have to run off to capturesites then they don't waste their temp fly time.
