### ISSUE TITLE
Towny regenerating old chunk where once stood a claim before world reset

### ISSUE THREAD

**Issue by Wayturns** [TownyAdvanced/Towny#7258]
### What steps will reproduce the problem?

I don't even know...

### What is the expected output?

For those chunks to stay the way they are

### Towny version

0.100.1.13

### Server version

1.20.4 Purpur

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://mclo.gs/Fj7pXq7
2. Your Towny config.yml: https://mclo.gs/SyrGbD2
3. Your townyperms.yml:  https://mclo.gs/6i5l0aH
4. Your log's error: No error
I just have the video idk how else to explain I also typed in the chat so keep an eye out for the chat
The video: https://youtu.be/IvD7VszHGJY

**Comment by Wayturns** [comment]
video will finish uploading in roughly 1h so u can see for ur self

**Comment by LlmDl** [comment]
If you reset a world you should not keep the towny\data\plot-block-data\ folder for that world or this will happen.
