### ISSUE TITLE
Suggestion: Add a way for a resident to see all the towns they're outlawed in

### ISSUE THREAD

**Issue by CorruptedGreed** [TownyAdvanced/Towny#7278]
### **Please explain your feature request to the best of your abilities:**

It would work similar to `/res plotlist`, using a command like `/res outlawlist`

outlawlist
{#} - Shows a player a list of towns they're outlawed in, with an optional page number.
[name] {#} - Shows a list of towns outlawed for the given player name, with an optional page number.

**Comment by Fruitloopins** [comment]
i can try this

**Comment by LlmDl** [comment]
If you don't manage to finish it @Fruitloopins I'll get to this one in the near-ish future.
