### ISSUE TITLE
Console spammed with erros

### ISSUE THREAD

**Issue by UckzDev** [TownyAdvanced/Towny#7284]
### What steps will reproduce the problem?

1. Just running the server.

### What is the expected output?

No spam of errors in console

### Towny version

v0.100.1.16

### Server version

1.20.4 Paper

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
https://pastebin.com/7j7BSewh
2. Your Towny config.yml:
https://pastebin.com/3DDLw2gL
3. Your townyperms.yml:
https://pastebin.com/sHVuDa0u
4. Your log's error:
Lots of errors, the two descriptions:
1. https://pastebin.com/Rkmi6gQw
2. https://pastebin.com/LyZ9En2b
(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
Your server somehow has a townblock that does not have an associated town which usually indicates some broken state
