### ISSUE TITLE
`/t deposit` and `/n create` fail, remove money

### ISSUE THREAD

**Issue by OyenDeveloper** [TownyAdvanced/Towny#7293]
### What steps will reproduce the problem?

1. when using /t deposit I get a failure message, but my money disappears and the town bank does not increase.
2. When I use /n create I can't create a nation with the error message "you don't have enough money to create a nation". and it doesn't take any money.

### What is the expected output?

1. `[Towny] PLAYER deposited 1 to the Town bank.`
2. `[Towny] PLAYER create nation called ....`

### Towny version

0.100.1.0

### Server version

git-Purpur-1990 (MC: 1.20)*

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/z0N5UT1s
2. Your Towny config.yml: https://pastebin.com/dsb664J2
3. Your townyperms.yml: https://pastebin.com/em4BRyQz
4. Your log's error: (no error)

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
Your economy plugin, coinengine, is already listed as known to not work with towny in our [faq](https://github.com/TownyAdvanced/Towny/wiki/Frequently-Asked-Questions).

**Comment by OyenDeveloper** [comment]
I found a great solution. I deactivated coins engine as the main economy, and replaced it with vault.
