### ISSUE TITLE
[Tower of Babel] Suggestion: Additional way of gaining fluency, other than speaking.

### ISSUE THREAD

**Issue by dawwggS** [TownyAdvanced/Towny#7294]
### **Please explain your feature request to the best of your abilities:**

Currently, the only way of gaining fluency in a language is by speaking it and waiting on the random chance of gaining a small point towards fluency.
I was thinking of maybe gaining fluency from being in the proximity of someone speaking the language.

**Comment by LlmDl** [comment]
Proximity to someone speaking could be a neat idea...
