### ISSUE TITLE
Suggestion: Add the ability for towns to toggle whether plots go up for sale on resident leave/purge

### ISSUE THREAD

**Issue by CorruptedGreed** [TownyAdvanced/Towny#7295]
### **Please explain your feature request to the best of your abilities:**

Add a command (such as `/t toggle plotresale`) for towns to determine whether plots put themselves back for sale upon a resident leaving/purging. 

Currently towns circumvent unwanted purchases of plots put back for sale by setting high plotprice (i.e `/t set plotprice 10000`). Having the ability to toggle plotresale would just result in plots being reclaimed by the town and nfs.

**Comment by LlmDl** [comment]
I do like the idea of making this a thing for mayors to decide but I thought I'd also make sure you're aware of a global setting that does this already:

```
"town.default_taxes.does_non-payment_place_plot_for_sale",
"false",
"",
"# Does a player's plot get put up for sale if they are unable to pay the plot tax?",
"# When false the plot becomes town land and must be set up for-sale by town mayor or staff."),
```

**Comment by CorruptedGreed** [comment]
Would enabling this work with taxes disabled, and does it only apply to plots put up for sale after failing to pay plot tax (or general removal)?

**Comment by LlmDl** [comment]
Yeah this setting is only used when plots are lost due to non-payment of taxes. I wasn't thinking about when players leave/are purged.
