### ISSUE TITLE
Suggestion: Y Level Option For T/N Spawn & Outposts

### ISSUE THREAD

**Issue by TylorTurner** [TownyAdvanced/Towny#7306]
### **Please explain your feature request to the best of your abilities:**

Players can dig to bedrock and set a spawn point for Towny and "Teleport" underground and hide. I think adding a Y level requirement just like event war would remove this issue entirely.

**Comment by LlmDl** [comment]
Closed by the creation of a new plugin: https://github.com/LlmDl/TownySpawnPointLimits9000
