### ISSUE TITLE
[EventWar] Suggestion: Make it possible to translate some phrases

### ISSUE THREAD

**Issue by NeotenySS** [TownyAdvanced/Towny#7326]
### **Please explain your feature request to the best of your abilities:**

Please make it possible to translate phrases (In the guide book they are not translatable, and in general their translation would be useful not only within the guide book):
- [x] 1) Riot
- [x] 2) Town vs Town war
- [x] 3) National Civil War
- [x] 4) Wars of Independence
- [x] 5) Nation vs Nation War
- [x] 6) Alliance vs Alliance war
- [x] 7) World War
- [x] 8) Riot DoW Cost:
- [x] 9) Town vs Town DoW Cost
- [x] 10) Civil War DoW Cost
- [x] 11) Independence War DoW Cost
- [x] 12) Nation vs Nation DoW Cost
- [x] 13) Alliance vs Alliance DoW Cost
- [x] 14) World War DoW Cost

Thank you for your hard work and good support for everyday people and sponsors alike!

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/bfcc1569-21b9-44fc-b8ca-139aebf19529)

These messages appear when the player declares a world war, but there is only one nation in the world, in response he receives a message that cannot be translated

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/3a5fb355-4afd-4e58-9f0d-647bdf123522)

Another message that appeared additionally when the new 2 nations were just created and a world war was declared

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/c13a56eb-e24b-4276-85cb-aada65b2ecb6)

Please also add translation of the output message when using webhook in discord.

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/4c00c832-ba46-4fd0-8ca7-93fadf2a2ef5)
 In Discord webhook message can't translated too

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/f3830f68-8e38-4f7e-9e5b-866033b32a54)

That too in chat if no have town and other captured

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/c777fff5-6b80-4060-a863-7157e44ed5a6)
When war is declared, the inscription is not translatable in the book (used the World War method)

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/74258c2d-16f9-44d8-a49c-4e82a00a8d74)
The titles of books that are given to the player when he acquires them for tokens or receives them because of the beginning/end of wars are also untranslatable

**Comment by NeotenySS** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/11386982/19e2e617-30be-45bf-b0a4-aa7b590f0706)
Discord webhook can't translated

**Comment by NeotenySS** [comment]
I think most of the text through discord webhook is untranslatable.
If needed, I can find free time to test sending notifications to each type of war in the webhook.

Is it possible to make the text that is sent to discord exclude color characters, such as for example: &r, &a, &e, and etc.

**Comment by LlmDl** [comment]
- [ ] The reasons wars fail to begin because town/nation cannot war.
- [ ] Discord Webhook strings.
- [ ] Discord Webhook countdown.
- [ ] War Declared, continues, ends titles in war start, continue, end books, 
- [ ] War start, continue, ends Book titles
- [ ] Discord Message colour stripping.
