### ISSUE TITLE
Suggestion: Town Bank Splits/goes to Nation

### ISSUE THREAD

**Issue by TheGamerBeeC** [TownyAdvanced/Towny#7331]
### **Please explain your feature request to the best of your abilities:**

If a town falls, its bank assets could either go to the nation bank or be divided among online players. It would be unfortunate to lose everything, so redistributing them seems more beneficial.

**Comment by LlmDl** [comment]
I am currently taking suggestions from sponsors only. Only 1% of servers are sponsoring the time I put into Towny and that is not enough.
