### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by HealthyPepper55** [TownyAdvanced/Towny#7342]
### **Please explain your feature request to the best of your abilities:**

**I would like to see the create mod deployer supported.** 
Currently it only responds to the establishment sound and observers. If you can't, I'd be happy to answer that it's not possible. Please wait for the response. (I am Japanese and I am using translation, so I know there are some things that are not right, but please respond.)

**Comment by LlmDl** [comment]
I do not understand your suggestion. Sorry.

I am currently taking on suggestions from Sponsors only.

**Comment by Warriorrrr** [comment]
I assume they're talking about https://create.fandom.com/wiki/Deployer, which is not possible (or at least something we'd put a lot of effort for) to support
