### ISSUE TITLE
Towny Privates do not work

### ISSUE THREAD

**Issue by Rockntt** [TownyAdvanced/Towny#7343]
### What steps will reproduce the problem?

Reinstall towny

### What is the expected output?

Expected players to do not have access to other towns, but they can open chests and break in towns.

### Towny version

0.100.2.0, but the same issue follows me on 0.97.0.3

### Server version

1.16.5

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/2aF6FXy9
2. Your Towny config.yml: https://pastebin.com/EJT6X0L8
3. Your townyperms.yml: https://pastebin.com/zuna4pwG
4. Your log's error: no error logging

**Comment by LlmDl** [comment]
This is usually caused by Towny nodes put into a permission plugin. Did you put towny nodes into your permission plugin?

**Comment by Rockntt** [comment]
Yes, I did

**Comment by LlmDl** [comment]
I'd start by removing those. Adding anything like `towny.*` and `towny.claimed.*` has likely caused your issue.

**Comment by Rockntt** [comment]
Did so and the problem didnt go away
