### ISSUE TITLE
Towny reload error

### ISSUE THREAD

**Issue by Rockntt** [TownyAdvanced/Towny#7344]
### What steps will reproduce the problem?

Have only following plugins enabled:
Citizens, PlugManX, ProtocolLib, Towny

### What is the expected output?

expect to have towny reloaded

### Towny version

0.97.0.3

### Server version

Purpur 1.16.5

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/V1rdMpxX
2. Your Towny config.yml: Default
3. Your townyperms.yml: Default
4. Your log's error: https://pastebin.com/wge9euUc

**Comment by LlmDl** [comment]
There's no reason for a server to use 0.97.0.3 when I just released 0.100.2.0 which supports 1.16.5.
