### ISSUE TITLE
ZombieVillager and Villager

### ISSUE THREAD

**Issue by moda84** [TownyAdvanced/Towny#7355]
### What steps will reproduce the problem?

1. Remove "Monsters" from "town_mob_removal_entities", "wilderness_mob_removal_entities" and "world_mob_removal_entities"
2. Replace "town_mob_removal_entities", "wilderness_mob_removal_entities" and "world_mob_removal_entities" to Blaze,CaveSpider,Creeper,Drowned,ElderGuardian,Enderman,Endermite,Evoker,Giant,Guardian,Husk,Illusioner,Piglin,PiglinBrute,Pillager,Ravager,Silverfish,Skeleton,Spider,Stray,Vex,Vindicator,Warden,Witch,Wither,WitherSkeleton,Zoglin,Flying,Slime,Shulker,SkeletonHorse,ZombieHorse
3. If use Zombie in "town_mob_removal_entities", "wilderness_mob_removal_entities" and "world_mob_removal_entities" spawn disable and from ZombieVillager

(IDK why but, if use "zombie" ZOMBIEvillager not spawn too) :c
Please help. How allow only zombievillager go to town plots (not for all monsters)?

### What is the expected output?

ZombieVillager remove after time

### Towny version

Towny: 0.100.2.0

### Server version

git-Pufferfish-46 (MC: 1.20.4)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
https://pastebin.com/hAmdNdFE
4. Your townyperms.yml:
5. Your log's error:

(optional) If this is to do with permissions,
6. Your permissions file:

(optional) If this is to do with chat,
7. Your chatconfig.yml:
8. Your channels.yml:

**Comment by LlmDl** [comment]
In bukkit ZombieVillager extends Zombie, and so a ZombieVillager is also a Zombie.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/ZombieVillager.html

Not much to do about that.
