### ISSUE TITLE
ALLIAS /town NOT work

### ISSUE THREAD

**Issue by moda84** [TownyAdvanced/Towny#7358]
### What steps will reproduce the problem?

1. Open chat
2. Try use /town set spawncost 0
3. "Unknown command. Type "/help" for help."
4. If use /t set spawncost 0
5. Cost set to 0 for spawn

### What is the expected output?

In Towny0.100.1.20 "/town" work, in 0.100.2.1 is not working

### Towny version

0.100.2.1

### Server version

git-Pufferfish-46 (MC: 1.20.4)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
https://pastebin.com/hAmdNdFE
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
![image](https://github.com/TownyAdvanced/Towny/assets/50800980/6c6c5dd6-b144-407e-90d9-785697c221a2)

Unable to reproduce, you also skipped the part of the form that asks for your latest.log. Likely another plugin is interfering.
