### ISSUE TITLE
ALLIAS /town NOT work from PLAYERsender

### ISSUE THREAD

**Issue by moda84** [TownyAdvanced/Towny#7359]
### What steps will reproduce the problem?

1. Open chat
2. Try write /town set spawncost 0
3. "Unknown command. Type /help for help"
4. Try write /t set spawncost 0
5. Cost set to 0

### What is the expected output?

/town work in console, but not work if player use it.

### Towny version

0.100.2.1

### Server version

git-Pufferfish-46 (MC: 1.20.4)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/gEGUWs8g
2. Your Towny config.yml: https://pastebin.com/hAmdNdFE
3. Your townyperms.yml: https://pastebin.com/CYa1LfZw
4. Your log's error: https://imgur.com/a/ovgz3SN

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
does `/towny:town set spawncost 10` work?

**Comment by moda84** [comment]
No

https://imgur.com/a/WKxxeDR

**Comment by moda84** [comment]
Plugin list:
https://imgur.com/a/IJbiGxk

**Comment by LlmDl** [comment]
Have you got a plugin that has a /tell command, or a plugin that blocks commands or plugin lists?

**Comment by moda84** [comment]
Yes (about /t**ELL**)
Yes, but /tOWN not works after update Towny

**Comment by LlmDl** [comment]
It is very unlikely that Towny is the cause of the issue.

**Comment by moda84** [comment]
Thx for help.
CoffeeProtect by default block command what start with "to".
I remove it and all working.
Sorry for waste time.
