### ISSUE TITLE
cliams are rest upon server resart

### ISSUE THREAD

**Issue by Greenguy196** [TownyAdvanced/Towny#7416]
### What steps will reproduce the problem?

restarting server 

### What is the expected output?

after reart claims would saver and not have to be reclaimed 

### Towny version

0.100.2.0 - 0.100.2.8

### Server version

1.20.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: (https://pastebin.com/Y9YA6Xbu)
2. Your Towny config.yml: https://pastebin.com/KjXrRMvn
3. Your townyperms.yml: https://pastebin.com/dQnVLiKM
4. Your log's error:

**Comment by LlmDl** [comment]
This was sorted on the discord, don't use slashes in your world names.
