### ISSUE TITLE
Merged balances

### ISSUE THREAD

**Issue by Imcoocked** [TownyAdvanced/Towny#7433]
### What steps will reproduce the problem?

1. Countries should be created in approximately the same period of time 
2. The balance of countries has been combined, now when the leader of one country withdraws money from his country, money is also withdrawn from another country that was created in the same period of time.

### What is the expected output?

Countries Must Have Their Personal Balances

### Towny version

0.100.2.0

### Server version

PAPER 1.20.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [link](https://pastebin.com/vUpjx3VM)
2. Your Towny config.yml: [link](https://pastebin.com/yMXGyXBX)
3. Your townyperms.yml: [link](https://pastebin.com/B6veQESM)
4. Your log's error: **This is not shown in the logs.**

Might help:
Vault 1.7.3
EssentialsX 2.21.0 config: [link](https://pastebin.com/Ap34XE4G)

**There are no other economic plugins installed on the server that could cause the error.**

Many countries have been created on the server, of which eight countries have 3 merged balances. When replenishing the balance, it also grows in the related country, but not immediately, you need to wait a little. I tried to replenish the balance of the countries myself, to distance their balances from each other as much as possible, but it did not help. 
![image](https://github.com/TownyAdvanced/Towny/assets/47953758/70e95808-5418-46c9-9520-eeeda60a0ae9)

**Comment by Warriorrrr** [comment]
Known issue, essentialsx economy is currently incompatible with town/nation names containing non alphabetic characters due to the way our economy calls are done. Will be fixed by #7425.

**Comment by Imcoocked** [comment]
> Known issue, essentialsx economy is currently incompatible with town/nation names containing non alphabetic characters due to the way our economy calls are done. Will be fixed by #7425.

I am very grateful for the quick reply, in which case I will wait for the plugin update. Is there any way to fix this for a while? By the time a new version of the plugin is released, for example, install another plugin for the economy?

**Comment by LlmDl** [comment]
Don't use EssentialsXEconomy, this is one of a few issues present in it.

**Comment by Imcoocked** [comment]
Well. Thank you all very much! In this case, I will change the economy plugin and wait for the towny update.
