### ISSUE TITLE
TOwny can outsiderr attack the towny and break

### ISSUE THREAD

**Issue by cinarz82222** [TownyAdvanced/Towny#7448]
### What steps will reproduce the problem?

my friend outside they can be breka blocks adn build switch

### What is the expected output?

its nto probblem

### Towny version

 towny-0.100.2.9.jar

### Server version

1.19.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:https://mclo.gs/Xhja5cz
3. Your townyperms.yml:https://mclo.gs/4Ngf8a7
4. Your log's error: 
its the essehntials[:https://mclo.gs/4Ngf8a7](https://mclo.gs/IK3T4IU)

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by cinarz82222** [comment]
help me

**Comment by LlmDl** [comment]
Did you put any towny permission nodes in your permission plugin (like LuckPerms)?

3 hours ago I was asleep, have patience.

**Comment by cinarz82222** [comment]
yes
 deafult

**Comment by cinarz82222** [comment]
I put in the pemr in default

**Comment by cinarz82222** [comment]
how can ı cehck?

**Comment by LlmDl** [comment]
Pray tell, which permission nodes did you put in your LP default group?

**Comment by cinarz82222** [comment]
wait sır ı cehck the luckperms

**Comment by cinarz82222** [comment]
towny.wild*
towny*

**Comment by cinarz82222** [comment]
I use luckperms and this
![Uploading Ekran görüntüsü 2024-06-05 160659.png…]()

**Comment by cinarz82222** [comment]
![Ekran görüntüsü 2024-06-05 160755](https://github.com/TownyAdvanced/Towny/assets/96992799/1dacd11f-370b-4a02-b930-b8b014ea608a)
![Ekran görüntüsü 2024-06-05 160813](https://github.com/TownyAdvanced/Towny/assets/96992799/c82213cf-2cbe-432d-8222-486a00436563)

**Comment by cinarz82222** [comment]
![Ekran görüntüsü 2024-06-05 160915](https://github.com/TownyAdvanced/Towny/assets/96992799/cd099b1c-2f98-485a-baab-b670a8dafc41)
 thi a seevr console
