### ISSUE TITLE
Suggestion: Set outpost names

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#7450]
### **Please explain your feature request to the best of your abilities:**

Outposts, in Dynmap, currently all display as "Town_Outpost_X".  This is pretty unsightly (if only because of the underscores).  Most outposts on my server have names that people have referred-to them as for years;  it would be nice to be able to use these names on the map.  When no name is set, *then* it should fall back to either "Town Outpost X" (without the underscores) or no text at all, as per admin preference.

(I don't want the cheap solution of treating the outpost's homeblock's name as the outpost's name, since that often is not 1:1 with the outpost's name.  Example:  Nelta's homeblock is "Anchor", and Omega Station's homeblock is "Omega East".  Even in towns this is not the case:  Delta's homeblock is "Capitol".)

These outpost names should also be displayed in `/town outpost list`.  (An aside, but I've always been kinda slightly bothered by the fact that there was no way to name the outposts in this list;  it'll be nice to finally be able to do that.)

![image](https://github.com/TownyAdvanced/Towny/assets/6566982/ee99b613-78bc-4ee6-a987-2cda4dad6e97)
![image](https://github.com/TownyAdvanced/Towny/assets/6566982/99f66380-9861-4a7f-83dc-e85132dc5676)
![image](https://github.com/TownyAdvanced/Towny/assets/6566982/4fad8cda-6e4d-4202-bb09-1d188f658a63)
![image](https://github.com/TownyAdvanced/Towny/assets/6566982/0ebf6c3a-073d-4a97-b4c6-f7a62435f636)

**Comment by LlmDl** [comment]
I'm a bit confused, you're asking dynmap-towny to use a name for the outposts, but you also want outposts to have a 2nd name that isn't the existing plot/outpost name?

**Comment by MilesBHuff** [comment]
There was a discussion in Discord about this;  I figured I'd put the gist of that here, so that onlookers have more context:

It turns out that the issue is one of using outposts as miniature towns, which is different from how outposts were originally envisioned.  The best solution is probably making most of the outposts on SettleScape into full towns;  but given the fact that this is not actually fully possible in Towny (only workaroundable with active, ongoing admin intervention with NPC mayors and trusted lists), cosmetic outpost names (separate from their homeblock names) will be added to better-support using outposts as mini towns until such a time as exists a proper ability for players to make/join multiple towns simultaneously.  This will be toggleable in configs.  The name displayed for outposts on the map and in lists will be, in order of preference:  the cosmetic name (if set), the homeblock plot name (if set), or some fallback ("Outpost").

**Comment by LlmDl** [comment]
Closed in lieu of https://github.com/TownyAdvanced/Towny/issues/7479

**Comment by MilesBHuff** [comment]
There was a discussion in Discord about this; I figured I'd put the gist of that here, so that onlookers have more context:

I suggested maybe just using the plot group name instead of the plot name if the outpost plot is in a plot group.  This would be a lot simpler, requiring the addition of a single helper function like this:
```
public static String getOutpostName(TownBlock townBlock) {
    return townBlock.group.getName() || townBlock.getName() || localize("DEFAULT_OUTPOST_NAME");
}
```It would then be used in 4 places.  No database work would be needed.

LlmDl wasn't a fan of the idea, though, in his view, an outpost is *just* a plot of type outpost, and nothing else.  He proposed instead perhaps adding nameable districts, which would finally make direct use of what had, until then, been an abstraction added many years ago by another contributor:  `ObjectGroup`.  `PlotGroup` inherits it, but all this time it hasn't been used directly.  These Districts would be relatively featureless groups of plots that can have a name set on them... and that's it (at least for now).
He's not sure how they will appear on the map.

(Please correct me if I got anything wrong!)

For the time-being, it seems that my feature request is denied, and outposts will remain addressed solely by their plot names.  :(  Maybe in the future I'll make a PR that adds an equivalent to the above pseudocode, but with the group names optional per a config boolean defaulting to `false`.

This Districts idea *is* neat.  I can definitely think of many places where I'll make use of it in my own town, and I'm sure other players will find good ways to use it, too.

**Comment by MilesBHuff** [comment]
@LlmDl The removal of underscores from outpost names seems to have not yet been added to the mainline -- they reappeared after I updated to 0.100.3.1 from the patch you Discorded me.

**Comment by MilesBHuff** [comment]
Upon further thought, using plot groups or Districts to name outposts might be a bit of a non-starter because both are capable of containing more than one Outpost plot, which would result in duplicate Outpost names on the map.  To be fair, this can also happen if two separate outposts are given the same plot name;  so maybe it's not a hard-block to doing something like the pseudocode I posted earlier.

Regardless, it'd probably still be nice to have a wrapper to provide a fallback display value for outposts without names -- this would then mean that the fallback display logic in Dynmap-Towny could be removed in favor of this shared helper method, ensuring consistent display values and making the code more-modular.
