### ISSUE TITLE
Towny fails to update to version `0.100.2.0` or higher.

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#7452]
### Describe the problem

Towny fails to load with versions at or above `0.100.2.0`.  I have not tested versions between `0.100.1.0` and `0.100.2.0`; the issue may begin in them.

**Tested:**

- `0.99.5.12` to `0.100.2.13` (failed)
- `0.99.5.12` to `0.100.2.0` (failed)
- `0.99.5.12` to `0.100.1.0` (succeeded)
- `0.100.1.0` to `0.100.2.0` (failed)

It's possible that this is due to SettleScape being on an older version of Minecraft (`1.17.1`), or perhaps due to this latest version of Towny requiring a version of some third-party plugin that I cannot update due to a lack of `1.17.1` support.  But to be honest, at this point I have no idea why this is failing.  If I had the time right now, I'd test down the `0.100.1.X` betas to see if I could find the exact point-release where the issue first arose;  but it's already way past my bedtime as-is and I need to drive to another state for a conference today.  Maybe you'll know what the issue is just by looking at the logs?

### What steps will reproduce the problem?

1. ????
2. Update https://github.com/SettleScape/server to `0.100.2.0` or higher.

### What is the expected output?

It should "just work".

### Towny version

`0.100.2.0`

### Java version

Oracle JVM `17.0.11`

### Server version

Paper version `git-Paper-411` (MC: `1.17.1`) (Implementing API version `1.17.1-R0.1-SNAPSHOT`) (Git: `6625db3` on `ver/1.17.1`)

### Please use Pastebin.com to link the following files
0. Your server plugins: https://github.com/SettleScape/server/blob/master/notes/plugins.rst
1. Your full server startup from the logs\latest.log: https://gist.github.com/MilesBHuff/df285fd790894f5a4f1f4df942ae5f1c#file-latest-log
2. Your Towny config.yml: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/config.yml
3. Your townyperms.yml: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/townyperms.yml
4. Your log's error: https://gist.github.com/MilesBHuff/df285fd790894f5a4f1f4df942ae5f1c#file-errors-md
7. Your permissions file: https://github.com/SettleScape/server/tree/master/minecraft/plugins/LuckPerms/yaml-storage/groups
8. Your chatconfig.yml: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/ChatConfig.yml
9. Your channels.yml: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/Channels.yml

**Comment by Warriorrrr** [comment]
This error was previously reported in #7399 and fixed in #7403 last month, do you have a log with the error happening on the latest pre-release?

**Comment by MilesBHuff** [comment]
> do you have a log with the error happening on the latest pre-release?

Yes actually.  But I'm away from my computer at present, and am going to be at Southeast Linuxfest all weekend.  I'll try to get it to you when I can.

**Comment by MilesBHuff** [comment]
@Warriorrrr https://gist.github.com/MilesBHuff/1c86f099a70065cc56952a561d35a688

**Comment by MilesBHuff** [comment]
Thanks guys!  I just tried `0.100.3.0`, and it worked just fine.
