### ISSUE TITLE
Suggestion: avoid suffocation at homeblocks

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#7463]
### **Please explain your feature request to the best of your abilities:**

At present, if a homeblock is set and then covered deeply underground, when players `/t spawn` there (I assume also `/t outpost`.), they suffocate with no way to escape.  This can be abused by players.

Proposed solution:  If the spawn location is buried in non-breatheable blocks, spawn at the closest Y-level at that X/Z coordinate with two breatheable blocks (or the world height, if no double breathables are found).

Seemingly good but actually fraught solution:  Preventing players from placing things in the two voxels above the homeblock spawn surface.  The problem with this solution, is that it prevents putting buttons and pressure plates and such.  I know pressure plates can be used for evil;  but in my own town, the pressure plate on the spawn surface actually plays the town anthem for spawner-inners.  So, imho preventing the placement of carpet and redstone and whatever at the homeblock would be throwing out the baby with the bathwater.  (This is also why I specified "breathable" blocks instead of just "air" blocks above.)

**Comment by LlmDl** [comment]
I'd have to see if the location can be altered when we teleport using PaperLib. This one should be a rule in your server that is heavily punished.

**Comment by MilesBHuff** [comment]
> This one should be a rule in your server that is heavily punished.

I definitely agree there, and it will be so.
