### ISSUE TITLE
Restarted during World War

### ISSUE THREAD

**Issue by TylorTurner** [TownyAdvanced/Towny#7471]
### What steps will reproduce the problem?

I simply restarted my server and backed it up and my server was dead from the World War.

### What is the expected output?

To continue on as normal

### Towny version

100.2.13 - Towny
0.0.126 - Event War

### Server version

1.20.4 purpur

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml: https://mclo.gs/MzaTK0T
3. Your war config: https://mclo.gs/zWY0vZE
4. Your log's error: https://mclo.gs/TsNbKUr

**Comment by LlmDl** [comment]
Never seen it do that before.

**Comment by LlmDl** [comment]
I am 99% sure this got fixed.
