### ISSUE TITLE
World War Conquered Towns Not Transfering

### ISSUE THREAD

**Issue by TylorTurner** [TownyAdvanced/Towny#7472]
### What steps will reproduce the problem?

We were working on this a bit but it still seems to be an issue. Unsure if it is my fault. 

3 total nations are fighting
A, B, and C.

A Takes B (Conquered)
C Takes A
B Gets left behind and takes A's Nation.
B should have been conquered to C and only one nation is left in the world war.

### What is the expected output?

Nation B should have been captured but was left behind un captured. They took their capturing nations, nation.

### Towny version

towny-0.100.2.13
EventWar-0.0.126

### Server version

1.20.4 PurPur

### Please use Pastebin.com to link the following files

1. Your Towny config.yml: https://mclo.gs/cGazudI
2. Your eventwar: https://mclo.gs/iY4ma5j

**Comment by LlmDl** [comment]
Did you use the version I gave you before your sponsorship was cancelled?

**Comment by TylorTurner** [comment]
If it was the latest event War in discord event war section yes.

**Comment by LlmDl** [comment]
No I sent you a jar to test, which you said you would try out, not something which was released proper.
