### ISSUE TITLE
LoadedMetadataEvent does not fire off on Folia

### ISSUE THREAD

**Issue by CorruptedGreed** [TownyAdvanced/Towny#7473]
### What steps will reproduce the problem?

1. Launch a Folia server jar with a plugin listening for LoadedMetadataEvent
```
public class LoadedMetaDataListener implements Listener {
    @EventHandler
    public void onMetaLoaded(LoadedMetadataEvent event) {
        System.out.println("LoadedMetadataEvent event happened");
    }
}
```
2. The event does not happen
![image](https://github.com/TownyAdvanced/Towny/assets/47507792/d4d30af4-dda9-4432-978f-a2a95a149b0f)

### What is the expected output?

"LoadedMetadataEvent event happened" printed in console

For Paper:
![image](https://github.com/TownyAdvanced/Towny/assets/47507792/3fbb6092-c1c2-476b-96b9-b3d6499e1489)

### Towny version

Towny 0.100.3.0

### Server version

1.20.4 Folia

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/8uPpGuSm
2. Your Towny config.yml: https://pastebin.com/Uzuk0rL8
3. Your townyperms.yml: https://pastebin.com/pbZJuSut

**Comment by Warriorrrr** [comment]
This bug was fixed in the affected plugin by registering the deserializer in onLoad instead of onEnable, since the event currently does not fire if no metadata was loaded - #7531 addresses that
