### ISSUE TITLE
Suggestion: Create new District TownyObject.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#7479]
- Extends our ObjectGroup, like a PlotGroup.
- Similar command structure to PlotGroup, but with limited fields: `UUID uuid`, `String name`, `Set<TownBlock> townblocks`
- Similar database to PlotGroup.

- Allows a mayor/assistant to create a grouping of plots into what is named a District.
  - Districts have a name, and a Set of TownBlocks.
  - These District names will appear in Chunk Notifications, on the Dynmap.

- Unlike PlotGroups, the townblocks within a District are allowed to have their individual plot permissions, owners and plot names.

The end goal is to make a blob of land which can be given a distinct name, without requiring the use of restrictive PlotGroups.

This could be used to name a blob of land surrounding an Outpost townblock, and so this concept will supercede the [Suggestion: Set outpost names](https://github.com/TownyAdvanced/Towny/issues/7450) ticket.

**Comment by LlmDl** [comment]
These districts should probably try to reuse the adjacent claims code we have, so they are forced into being contiguous land masses.

**Comment by MilesBHuff** [comment]
This Districts idea *is* neat.  I can definitely think of many places where I'll make use of it in my own town, and I'm sure other players will find good ways to use it, too.  Thanks!

Regarding displaying them on the map:  I'm not sure how or if they should show there.  Maybe solely in the popup?  Maybe there should be a separate ticket to control the Dynmap aspects, to allow this feature to go through faster, without being held-back.

**Comment by LlmDl** [comment]
Nothing will happen on the mapping side until I get around to making Dynmap-Towny aware of Districts.

**Comment by MilesBHuff** [comment]
You rock, Llmdl!
