### ISSUE TITLE
Cauldron permissions

### ISSUE THREAD

**Issue by LavaLooter** [TownyAdvanced/Towny#7485]
### What steps will reproduce the problem?

Probably this is more a suggestion, but for my POV this must be fixed.
Try getting lava from a cauldron inside a quarter (type commons) so where you only got switch and itemuse permissions.
From my understanding that should definitely be possible.
Right now I need to give players permissions to break the cauldren. Only then it works. Please fix that.
(building a public lab in my town where each town member should be able to get lava from the cauldrons.

### What is the expected output?

lava from cauldron works without break-permission

### Towny version

I would love to tell you a version but im only a player on ccnet mc-server. Admins said I should tell my problem here.
I think they use "latest"....

### Server version

like 1.20.6 (im using that version when joining)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
This is not the Quarters bug tracker.
