### ISSUE TITLE
Towny commands aren't working

### ISSUE THREAD

**Issue by Feelyx0** [TownyAdvanced/Towny#7490]
### What steps will reproduce the problem?

I installed towny to my server but /t /town and /towny commands aren't working. 

### What is the expected output?

Towny commands to work (/t /town /towny)

### Towny version

Towny 0.100.3.0
TownyChat v0.115

### Server version

1.16.5 Spigot

### Please use Pastebin.com to link the following files

1. latest.log : https://pastebin.com/Dj9rFsSJ
2. Towny config.yml: https://pastebin.com/V40YQL3W
3. Your townyperms.yml: https://pastebin.com/Ye6jWRX8
4. Your log's error: https://pastebin.com/k1sPQeCE

(optional) If this is to do with permissions,
5. Your permissions file: Nothing in permissions file. I've deleted and reinstalled luckperms few times while trying to fix towny commands. Can it make this file empty ?

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://pastebin.com/LCrTPjkb
7. Your channels.yml: https://pastebin.com/utUKmzsD

**Comment by Feelyx0** [comment]
There is no info after i use /towny command. /t and /town just dont work ı guess, they show up as blue not red but after i write /t or /town my username comes up. /t was the same as /t for tell from essentials but i both disabled the command from essentials config and then deleted essentials from server completely to try if either of them fixes the problem. Neither of them fixed it.

**Comment by LlmDl** [comment]
It looks like your version of 1.16.5 is out of date compared to the last version of paper/spigot made for 1.16.5, I have dropped support for 1.16.5 as of the pre-releases of Towny. On Towny's next release we will no longer support any version older than 1.19. I would recommend updating your 1.16.5 paper/spigot/whatever you use. Then I could consider not using 1.16.5 at all. It's old.

**Comment by Feelyx0** [comment]
Oh ok then. Thanks for the help
