### ISSUE TITLE
Baltop issue

### ISSUE THREAD

**Issue by Imcoocked** [TownyAdvanced/Towny#7496]
### What steps will reproduce the problem?

1. Download Vault, UltraEconomy and Towny
2. Create a baltop hologram based on the UltraEconomy placeholders

### What is the expected output?

Only real players must be shown, not towns or nations

### Towny version

**0.100.2.0**

### Server version

**1.20.1 Paper**

### Please use Pastebin.com to link the following files

No console issues were present

Behaviour in the game:
![image](https://github.com/TownyAdvanced/Towny/assets/47953758/387d55a2-05d0-492d-8094-2131da51c515)

**Comment by LlmDl** [comment]
That's something the economy plugin would decide to show or not.
