### ISSUE TITLE
chat issue

### ISSUE THREAD

**Issue by Yurielvillanueva** [TownyAdvanced/Towny#7500]
### What steps will reproduce the problem?

![image](https://github.com/TownyAdvanced/Towny/assets/107783416/6a06d888-d96c-4a6a-896c-ca912c1ec603)

### What is the expected output?

i didn't see any errors,  

### Towny version

Towny Version: 0.100.2.0

### Server version

https://pastebin.com/ZUfSvEgp

### Please use Pastebin.com to link the following files

https://pastebin.com/ZUfSvEgp

**Comment by Warriorrrr** [comment]
Please elaborate on what your issue is? When you went to the discord I already replied to your message with instructions for how to change the message format in townychat, and you skipped the part of the issue form that asks for your townychat files

**Comment by Warriorrrr** [comment]
Closing due to lack of response, please use our discord for support requests
