### ISSUE TITLE
Suggestion: Prefixing the tags with the map color of the town & nation

### ISSUE THREAD

**Issue by murk223** [TownyAdvanced/Towny#7502]
### **Please explain your feature request to the best of your abilities:**

Add a new feature that changes the town/nation's tag color in chat depending on its unique map color.

**Comment by LlmDl** [comment]
Are you using the tag in a papi placeholder, or are you using them in townychat?

**Comment by LlmDl** [comment]
Still hoping for clarification on this @murk223
