### ISSUE TITLE
World Corruption

### ISSUE THREAD

**Issue by M0chaCat** [TownyAdvanced/Towny#7510]
### What steps will reproduce the problem?

Load Towny
Find a corrupted column of blocks, usually in lines or clusters

### What is the expected output?

not having world corruption

### Towny version

0.115

### Server version

Purpur 1.20.6

### Please use Pastebin.com to link the following files

Most signs, and some Torches will be deleted and the server will have holes from bedrock start forming in lines 1x1 to 1x5. And  if you fill them in they will (after a moment, or server reboot) either go back to being holes and sometimes expanding, or having new holes next to them
Not sure what caused this issue but it only started after installing towny, and stops when disabling it. 

1. Your full server startup from the logs\latest.log: https://pastebin.com/i9WiinXj
2. Your Towny config.yml: https://pastebin.com/9D9tDsNz
3. Your townyperms.yml: https://pastebin.com/8e9VsiCH
4. Your log's error: Wasnt any errors

**Comment by LlmDl** [comment]
There was a few older towny versions, which were only released as pre-releases, which did not make good snapshots. The snapshots are used in the revert on unclaim feature.

Snapshots made using 0.100.3.0 or 0.100.2.0 should not have this issue.

Were you using a pre-release in the past, which could be responsible for bad snapshots being taken?

**Comment by MeowArcane** [comment]
ive only used that version of towny, for maybe a day or so iirc

**Comment by LlmDl** [comment]
I just claimed some land, with the revert on unclaim feature turned on, then unclaimed it and I am not having any corruption.

Please provide clearer steps to reproduce your issue.

**Comment by MeowArcane** [comment]
the corruption has happend to claimed and never claimed land, and land thats never been modified

**Comment by LlmDl** [comment]
Towny doesn't revert land which is claimed, your corruption is probably not related to Towny. Do you have a screenshot of it?

**Comment by MeowArcane** [comment]
![CleanShot 2024-07-15 at 11 45 50@2x](https://github.com/user-attachments/assets/7e80125f-8e78-487c-bce6-624aa27079c4)
when removing townys .jar(s) it stops making more corrupted columns

**Comment by LlmDl** [comment]
I would stop your server, then delete the plot-block-data folder in the towny\data\ folder.

You have bad snapshots.
