### ISSUE TITLE
Suggestion: Translatable Titles

### ISSUE THREAD

**Issue by darksaid98** [TownyAdvanced/Towny#7512]
### **Please explain your feature request to the best of your abilities:**

I know the issue name may be a bit ambiguous so here it goes. This has less to do with "translations" and more so with the customizability of the plugin (*as far as looks go*).

**Problem:**
These lines are hardcoded limiting the customizeability of certain parts of the plugin.

Lines:
- https://github.com/TownyAdvanced/Towny/blob/0f06d68c81bbc60308b8754cec5d7f215168dce6/Towny/src/main/java/com/palmergames/bukkit/util/ChatTools.java#L21-L31
- https://github.com/TownyAdvanced/Towny/blob/0f06d68c81bbc60308b8754cec5d7f215168dce6/Towny/src/main/java/com/palmergames/bukkit/util/ChatTools.java#L72-L87

There is quite a bit more in the ChatTools file than the above :(

Perhaps I want my town info page title to be something like: `<dark_gray><strikethrough>   <reset> Town <dark_gray><strikethrough>   <reset>`, rather than the towny default of `.oOo.____`.

**Request:**

- Unhardcode the entire title/subtitle and expose either through translations or config.
- It'd be nice to completely be able to disable the padding on both title and subtitle.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

99/100 servers are not sponsoring right now so I'm not taking on suggestions. If you'd like to code this and make a PR you're welcome to do that.
