### ISSUE TITLE
"[Towny] An exception occurred while loading district list java.sql.SQLSyntaxErrorException: Unknown column 'uuid' in 'field list'..."

### ISSUE THREAD

**Issue by leothawne** [TownyAdvanced/Towny#7523]
### What steps will reproduce the problem?

1. Download Towny-0.100.3.9.jar
2. Replace Towny-0.100.3.3.jar with Towny-0.100.3.9.jar
3. Run the server

### What is the expected output?

I expected to see Towny successfully working as usual

### Towny version

0.100.3.9

### Server version

Purpur 1.20.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/B4VmXaQ4
2. Your Towny config.yml: https://pastebin.com/E48wszDG
3. Your townyperms.yml: https://pastebin.com/NndrHJhy
4. Your log's error: 
![image](https://github.com/user-attachments/assets/c0f695db-86f9-4abe-801c-42d4da4d4a61)

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
There was an issue with Districts if you used SQL and 0.100.3.6. The problem was resolved in 0.100.3.7 but if your server used 0.100.3.6 you would have to drop the TOWNY_DISTRICTS table from your DB.

Are you certain you never used 0.100.3.6?

**Comment by leothawne** [comment]
I did try to update to Towny 0.100.3.3 but not 0.100.3.6.
I dropped the TOWNY_DISTRICTS table and I'll try to update to 0.100.3.9 now

**Comment by leothawne** [comment]
Problem solved! Thank you!
