### ISSUE TITLE
Suggestion: Overclaim upkeep if over outpost limit

### ISSUE THREAD

**Issue by Angsiyan** [TownyAdvanced/Towny#7526]
### **Please explain your feature request to the best of your abilities:**

If a town has 1/0 outposts then they have to pay overclaim or extra upkeep for each outpost over limit. 
They only lose teleporting if above limit now and its not much of a penalty.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

99/100 servers are not sponsoring right now so I'm not taking on suggestions. If you'd like to code this and make a PR you're welcome to do that.
