### ISSUE TITLE
Suggestion: Invulnerability in towny

### ISSUE THREAD

**Issue by unnamed199cz** [TownyAdvanced/Towny#7543]
### **Please explain your feature request to the best of your abilities:**

People are always abusing claimed chunks to kill people, by setting globally that people in towny are "invulnerable", its best option how to cut off chunk abusing, and about people going into chunks, many pvp plugins have option to kick someone out of safezone

**Comment by LlmDl** [comment]
I am currently only taking suggestions from sponsors, thank you.

**Comment by unnamed199cz** [comment]
Thats sad, but thanks for quick response
