### ISSUE TITLE
Suggestion: NPC Have full Access To Switching

### ISSUE THREAD

**Issue by TylorTurner** [TownyAdvanced/Towny#7550]
### **Please explain your feature request to the best of your abilities:**

Can you add an option to disable switching from NPC's. Currently In my server players can use NPC's to break in to other Towns.

**Comment by LlmDl** [comment]
I have been looking into this and it looks like we already block NPCs.

NPCs should be receiving a NOT_REGISTERED townblockstatus which will always return a false permission when we test them if they can build/destroy/switch.

What plugin is supplying your NPCs? 

Please test that you see debug messages thrown for them when you have used `/ta toggle debug`, then have them use a switch.

I would like to see those debug messages.

**Comment by TylorTurner** [comment]
> I have been looking into this and it looks like we already block NPCs.
> 
> NPCs should be receiving a NOT_REGISTERED townblockstatus which will always return a false permission when we test them if they can build/destroy/switch.
> 
> What plugin is supplying your NPCs?
> 
> Please test that you see debug messages thrown for them when you have used `/ta toggle debug`, then have them use a switch.
> 
> I would like to see those debug messages.

I already found a solution with the dev of the plugin. So all is good on my side. Do you want me to follow your instructions still?

**Comment by LlmDl** [comment]
Are they still able to use switches?

**Comment by TylorTurner** [comment]
> Are they still able to use switches?

No he fixed it for my specific use case.

**Comment by LlmDl** [comment]
OK, there must have been something overriding Towny in this instance because I don't think Citizens NPCs have been allowed to switch.
