### ISSUE TITLE
Outlaw does not teleport players away on add

### ISSUE THREAD

**Issue by Waspyethan** [TownyAdvanced/Towny#7552]
### What steps will reproduce the problem?

  # If set to true, when a player is made into an outlaw using /t outlaw add NAME, and that new
  # outlaw is within the town's borders, the new outlaw will be teleported away using the outlaw_teleport_warmup.
  outlaw_teleport_away_on_becoming_outlawed: 'true'
  
  it is set like this on the config but players inside a town are not being teleported away. They will be teleported if they enter a new chunk or leave and try to re-enter.

### What is the expected output?

that upon adding to t outlaw a player is teleported away

### Towny version

Towny-0.100.3.0.jar

### Server version

1.20.4

### Please use Pastebin.com to link the following files

https://pastebin.com/9r2Xb0ku

**Comment by Warriorrrr** [comment]
From the 0.100.3.1 changelog:
> Fix new outlaws not being teleported out of the town they were outlawed in.

Update to the latest pre-release to fix your issue.
