### ISSUE TITLE
Suggestion: Add the "Province" System

### ISSUE THREAD

**Issue by Tiger1228cym** [TownyAdvanced/Towny#7560]
### **Please explain your feature request to the best of your abilities:**

Hello! Due to some special requirements and considerations that are in line with reality, I suggest adding a "province" system in the plugin, which is equivalent to a sub country. Cities no longer directly join the country, but directly join provinces. The governor can rule the cities within the province with instructions.

(The above is machine translation)

**Comment by LlmDl** [comment]
I am no longer taking suggestions from people who are not sponsoring, sorry.

You can read about this decision on the project readme if you are interested.

Further, adding provinces would likely add up to a massive amount of work.

Consider using TownyProvinces.
