### ISSUE TITLE
Suggestion: Dynmap placeholder

### ISSUE THREAD

**Issue by Khavyx** [TownyAdvanced/Towny#7561]
### **Please explain your feature request to the best of your abilities:**

A placeholder that allows you to know from the dynmap if a nation is conquered, if it is the capital, or city of a nation

**Comment by LlmDl** [comment]
You can already use `%nationstatus%` which will output:
"Capital of NATIONNAME" if it is a capital of a nation, and "Member of NATIONNAME" if it is not the capital.
