### ISSUE TITLE
When I unclaim a town, the lava in that town cannot flow

### ISSUE THREAD

**Issue by ZherKing** [TownyAdvanced/Towny#7573]
### What steps will reproduce the problem?

1.create a town
2.unclaim the town just created
3.put the lava

### What is the expected output?

the lava is flowing

### Towny version

0.100.3.0

### Server version

Paper 1.21-106

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:https://pastebin.com/Kp1ydw22
3. Your townyperms.yml:https://pastebin.com/TFw02fmN
4. Your log's error:none

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
![2024-08-26_08 52 39](https://github.com/user-attachments/assets/0987a6ff-85af-43e5-b79f-de891cfa551a)
![2024-08-26_08 52 41](https://github.com/user-attachments/assets/695f886f-fdf4-4ad4-b33b-c5a15ea249e4)
![2024-08-26_08 52 42](https://github.com/user-attachments/assets/bbb28772-d112-4fb1-ba42-f1d689107d92)


This is not something I can reproduce, and it doesn't make a lot of sense. Towny only prevents flow into Towns that still exist/places that are claimed:
![2024-08-26_08 54 16](https://github.com/user-attachments/assets/7b6568a0-89f9-428b-9e97-5481ac58a1b7)
