### ISSUE TITLE
Adding color to plot groups in towny doesnt work

### ISSUE THREAD

**Issue by Shanedagoat12** [TownyAdvanced/Towny#7577]
### What steps will reproduce the problem?

First find a plot and turn it into a plot group with /plot group add
Then try to add color by doing, for example what i did, /plot group add &4&lArmory (Supposed to make the word armory bold and red)
![Screenshot 2024-08-27 170108](https://github.com/user-attachments/assets/9cfe307e-c12f-4e65-871b-e7f2bb448985)

### What is the expected output?

I expected the word Armory to be bold and red, instead its white.
![Screenshot 2024-08-27 170407](https://github.com/user-attachments/assets/0b4ea6fc-1aa4-4871-b966-7f58d20a047a)

### Towny version

0.100.3

### Server version

1.20.1

### Please use Pastebin.com to link the following files

1. Idk how to find this
2. Idk how to find this, im not the owner of the server.
3. Mayor and Nation leader
4. dont have an error

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
The owner of the server has to allow the & symbol via a edit to the Towny regex.
