### ISSUE TITLE
Towns with 2 residents are considered the wrong town level and have an issue with bonus claim blocks

### ISSUE THREAD

**Issue by orangeowie4** [TownyAdvanced/Towny#7582]
### What steps will reproduce the problem?

1. Have a town level for towns with 1 resident and one with 3 resident
2. Create a town
3. Invite someone so it has 2 residents
4. It's listed as the next town (for us it's Hamlet), when it's not at 3 residents yet. It also can't buy the 10,000 bonus claim blocks that the 1 resident tier has as a limit.

### What is the expected output?

I expected the town to have the correct tier and be able to claim. This issue is fixed when it goes to 3 residents, re-appears when it goes back to 2, and does not happen in between the 3 resident and 5 resident levels at 4 residents.

### Towny version

0.100.3.12

### Server version

1.21.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/BYvTEDyS
2. Your Towny config.yml: https://pastebin.com/J1nGueme
3. Your townyperms.yml: https://pastebin.com/h3R56kRU
4. Your log's error: No error

**Comment by LlmDl** [comment]
I cannot reproduce this. If you've edited your config to change the numResidents: 2 town-level to numResidents: 3, maybe try stopping and starting the server.
