### ISSUE TITLE
Plot group doesn't delete from SQL DB correctly.

### ISSUE THREAD

**Issue by Alienn-Know** [TownyAdvanced/Towny#7592]
### What steps will reproduce the problem?

![image](https://github.com/user-attachments/assets/2b00ad4c-ba68-425d-8e2e-d7cd5ce16c49)
![image](https://github.com/user-attachments/assets/a444dba2-054e-46ac-8229-a785fb654a3c)
`/stop` - server
start -> server
then
![image](https://github.com/user-attachments/assets/2b00ad4c-ba68-425d-8e2e-d7cd5ce16c49)
and catch unhandeled error

probably because when delete a group it is not deleted from the database, then when start the server and initialize the plugin, incorrect objects of the `PlotGroup` class are created

### What is the expected output?

probably this chunk go to group `1`

### Towny version

![image](https://github.com/user-attachments/assets/079e344c-1412-47c6-8385-c6cad4bcd875)
without any plugin modifications

### Server version

![image](https://github.com/user-attachments/assets/ed1e2569-3613-4ae2-ac8b-e24ad0aed0ce)
without any core modifications

### Please use Pastebin.com to link the following files

maybe it won't be needed here

![image](https://github.com/user-attachments/assets/73718537-0bfc-488c-960f-c71ef85fd6f8)
![image](https://github.com/user-attachments/assets/057ee8ec-0a8c-406e-a456-222c83ac06db)
![image](https://github.com/user-attachments/assets/4dfc1b5f-c3a1-4901-9409-839f1a98d4c3)

then if you try to `/plot group add 1` on another free territory (without a group or group), the same error occurs

`added`
I understood that when trying to add a new group that did not exist yet, this error occurs, when trying to add an existing group everything happens normally
`added`
I deleted all group in db and the error disappeared, and doesn't appear again

**Comment by LlmDl** [comment]
You did not include your startup log and so I don't know what database type you use

**Comment by Alienn-Know** [comment]
[2024-09-12-5.log](https://github.com/user-attachments/files/16993392/2024-09-12-5.log)

**Comment by LlmDl** [comment]
Can you test if this is still an issue while using this jar:

https://cdn.discordapp.com/attachments/690693742067449941/1284886176343392357/towny-0.100.4.2.jar?ex=66ed8900&is=66ec3780&hm=967e9b61a084c4b2bb81eba95bc1b70d02aaa678e27b29b63f245c7c903cbf60&

**Comment by Alienn-Know** [comment]
> Can you test if this is still an issue while using this jar:
> 
> https://cdn.discordapp.com/attachments/690693742067449941/1284886176343392357/towny-0.100.4.2.jar?ex=66ed8900&is=66ec3780&hm=967e9b61a084c4b2bb81eba95bc1b70d02aaa678e27b29b63f245c7c903cbf60&

thanks, now there are no errors, but there is still a problem with the database, old records that remain unrelated are not deleted
![image](https://github.com/user-attachments/assets/6896a12b-1f8c-4837-89f1-561192faed2f)

**Comment by Alienn-Know** [comment]
![image](https://github.com/user-attachments/assets/14136db4-42ab-4bed-99e0-7e2b0952b94a)
![image](https://github.com/user-attachments/assets/8c7b74a0-4f8b-4fa4-a2b5-684552ce8375)

**Comment by Alienn-Know** [comment]
> Can you test if this is still an issue while using this jar:
> 
> https://cdn.discordapp.com/attachments/690693742067449941/1284886176343392357/towny-0.100.4.2.jar?ex=66ed8900&is=66ec3780&hm=967e9b61a084c4b2bb81eba95bc1b70d02aaa678e27b29b63f245c7c903cbf60&

thanks, everything works fine
