### ISSUE TITLE
Suggestion: No default tax for nations?

### ISSUE THREAD

**Issue by Angsiyan** [TownyAdvanced/Towny#7612]
### **Please explain your feature request to the best of your abilities:**

**Please add a section for default nation taxes, just like how towns do.** 
So many new nations fall on first new day, it is a constant issue. 

This would be a good QoL improvement and save players from frustration when they dont know the difference between town and nation bank. 
Alternatively make creating a nation put a part of the cost to the nation bank, ensuring that they will last even a while.

**Comment by Warriorrrr** [comment]
The new nation defaults section has a default taxes section just like the new town section does, there is already no nation tax by default.
