### ISSUE TITLE
The plugin deletes entire chunks, block by block

### ISSUE THREAD

**Issue by AnnieReuvers** [TownyAdvanced/Towny#7614]
### What steps will reproduce the problem?

Literally just adding the plugin to my server creates this glitch (videos attached)

https://github.com/user-attachments/assets/8eb21a08-dce3-49ba-ae0d-2b17b85e2e02
https://github.com/user-attachments/assets/b912a439-3efe-457b-9290-6767caa6fa98

### What is the expected output?

All blocks are removed, except for bedrock and gravel (because gravel falls). Console gives no messages regarding this

### Towny version

Initially on towny-0.100.1.14, but updating to towny-0.100.4.0 still gives me this issue

### Server version

Paper 1.20.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
[2024-09-26-9.log.gz](https://github.com/user-attachments/files/17154480/2024-09-26-9.log.gz)

2. Your Towny config.yml:
[config (1).yml.txt](https://github.com/user-attachments/files/17154507/config.1.yml.txt)

3. Your townyperms.yml:
[townyperms.yml.txt](https://github.com/user-attachments/files/17154513/townyperms.yml.txt)

4. Your log's error: ---

**Comment by LlmDl** [comment]
There was a short number of pre-releases which made corrupted snapshots.
This could have included 0.100.1.14. Upgrading Towny to the latest
prerelease will not fix these snapshots and they should be removed from the
plot-block-data folder located in the towny\data\ folder.

**Comment by LlmDl** [comment]
I checked and the issue began in 0.100.1.16 and was fixed in 0.100.1.21. Snapshots made in .16->.20 are corrupted.

**Comment by LlmDl** [comment]
I have also just tried to re-create this ticket. I started a server using 0.100.4.3, MC 1.21.1, claimed some land, unclaimed the land after a minute. No block corruption occurred.

If you have the time to diagnose this further or get it to a point that is re-creatable you're welcome to create a ticket or submit a PR for this issue which is apparently not occurring on all installations.
