### ISSUE TITLE
Suggestion: Allows Beds Priority Vs Town Spawn during respawn process.

### ISSUE THREAD

**Issue by TylorTurner** [TownyAdvanced/Towny#7616]
### **Please explain your feature request to the best of your abilities:**

Please allow players that sleep in a bed to prioritize their T spawn. Currently beds are useless when allowing Towny to control the spawn system.

**Comment by LlmDl** [comment]
Towny uses /res spawn to send players to their bed spawn (when they have a bed spawn, otherwise that send them to their /t spawn.)

Is that what you're looking for?

**Comment by TylorTurner** [comment]
I would like for a players bed to be prioritized on death, currently they
are forced to T Spawn.
