### ISSUE TITLE
Suggestion: Custom status for town

### ISSUE THREAD

**Issue by moda84** [TownyAdvanced/Towny#7628]
### **Please explain your feature request to the best of your abilities:**

Hi!
Please add the ability to set custom statuses for cities to the API.
![изображение](https://github.com/user-attachments/assets/3b2186a8-d4df-465f-a216-9ffd4322577f)

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

99/100 servers are not sponsoring right now so I'm not taking on suggestions. If you'd like to code this and make a PR you're welcome to do that.
