### ISSUE TITLE
Wilderness translate

### ISSUE THREAD

**Issue by Alienn-Know** [TownyAdvanced/Towny#7631]
### What steps will reproduce the problem?

when I leave the town, does not translate the value of `Wilderness` from translation files, always uses ` ~ Wilderness`

### What is the expected output?

translated ` ~ Wilderness` -> ` ~ Дикие земли`

### Towny version

0.100.4.3

### Server version

1.20.6

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by Warriorrrr** [comment]
Use the command /tw set wildname
