### ISSUE TITLE
towny-server message bug

### ISSUE THREAD

**Issue by Alienn-Know** [TownyAdvanced/Towny#7634]
### What steps will reproduce the problem?

when the closed_economy option is active in config, when trying to withdraw/deposit, from a city/nation I always get the error `withdraw -> msg_err_no_money`, `deposit -> msg_insuf_funds`, although the money is actually withdrawn/deposited

### What is the expected output?

do not receive error messages

### Towny version

0.100.4.5

### Server version

1.20.6

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Skipped the form. Please re-submit.
