### ISSUE TITLE
/t spawn doesnt throw error but i cant tp to my town spawn

### ISSUE THREAD

**Issue by voidpuls** [TownyAdvanced/Towny#7650]
### What steps will reproduce the problem?

unsure 

### What is the expected output?

i expect to tp but dont

### Towny version

latest

### Server version

1.20.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml:
3. Your townyperms.yml:
4. Your log's error:

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

https://pastebin.com/xMCrnR4n
https://pastebin.com/tAJFux81

https://pastebin.com/50J514SZ

**Comment by LlmDl** [comment]
Does `/towny:town spawn` work?

Is there any error in the log when you run either command?

**Comment by voidpuls** [comment]
no errors and neither work

**Comment by LlmDl** [comment]
It works fine for me, you likely have a plugin doing something. Remove plugins until it works.

**Comment by voidpuls** [comment]
ill test it on the updated server as we are rebuilding it anyways
