### ISSUE TITLE
Suggestion: Blacklist of blocks for wilderness

### ISSUE THREAD

**Issue by Mapter228** [TownyAdvanced/Towny#7667]
### **Please explain your feature request to the best of your abilities:**

How about adding the ability to forbid building/using only specific blocks in the wilderness? I know that right now there is an option to allow only specific blocks, but I would prefer the opposite, a blacklist of blocks instead of a whitelist.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

99/100 servers are not sponsoring right now so I'm not taking on suggestions. If you'd like to code this and make a PR you're welcome to do that.
