### ISSUE TITLE
Dynamic nation range issue

### ISSUE THREAD

**Issue by MrToirol** [TownyAdvanced/Towny#7668]
### What steps will reproduce the problem?

*(This issue is only relevant if the `GNATION_SETTINGS_NATION_PROXIMITY_TO_OTHER_NATION_TOWNS` config node is set.)*

1. Using the dynamic nation range, create two towns outside of the "capital range".
2. Delete the chain of towns linking them to the "capital range". (i.e. the towns that allowed them to join in the first place by expanding the nation range)
3. These towns will never get kicked from the nation, even during newdays.
 
Looking at the code, it appears that:
The [ProximityUtil.closeEnoughToOtherNationTowns](https://github.com/TownyAdvanced/Towny/blob/7fbd0d8e8672fb9c971c74a6e4420f32dd2d3341/Towny/src/main/java/com/palmergames/bukkit/towny/utils/ProximityUtil.java#L318-L334) method only requires 1 town (which we'll name "B") in the nation to be close enough to town "A". Therefore, even if town B itself is out of range, neither will be kicked, because they will satisfy each other's requirements.
This means that a nation can have 2+ towns completely detached from its "core" nation range and they will not be kicked.

### What is the expected output?

- The towns get kicked on newday.
- No other town can join the nation using towns A and B's dynamic range (not *that* important as it would get kicked next newday anyway).

### Towny version

0.100.4.2

### Server version

1.20.4

### Please use Pastebin.com to link the following files

I cannot access those files as I am just a player, however there is no error or permission issue as it appears to be an issue in the code itself.

I can however provide the following config values:
GNATION_SETTINGS_NATION_PROXIMITY_TO_OTHER_NATION_TOWNS = 1000
GNATION_SETTINGS_NATION_PROXIMITY_TO_CAPITAL = 3500
GNATION_SETTINGS_NATION_PROXIMITY_TO_CAPITAL_CAP = 0

**Comment by LlmDl** [comment]
I have looked over the code and I'm not sure about your theory about B and A towns not being close enough to each other.

I'll probably get around to testing this with some smaller numbers though.

**Comment by LlmDl** [comment]
I will probably have to add something into the order the towns are searched in, going from closest to farthest. The new code works fine as when its not checking far towns first I guess.

**Comment by LlmDl** [comment]
I believe this sorts it out: https://github.com/TownyAdvanced/Towny/actions/runs/11801038567/artifacts/2177235259 if you wouldn't mind testing it on your end. It is working properly on mine.

**Comment by LlmDl** [comment]
If you like my work I'd urge you to become a sponsor, and you're welcome.
