### ISSUE TITLE
Issue related to VaultUnlocked

### ISSUE THREAD

**Issue by Houdeeny** [TownyAdvanced/Towny#7675]
### What steps will reproduce the problem?

The Towny commands work fine when using the original Vault plugin, but not when using VaultUnlocked.

1. Start a fresh server with Towny, VaultUnlocked, and EssentialsX installed.
2. Try starting a new town with `/town new <Town Name>`, or viewing an existing town's status with `/town <Town Name>`.
3. Error shows up both in chat, and in console.

### What is the expected output?

Expected output is just the commands working as intended, like being able to create a town, or having the town's status show up in chat.

### Towny version

0.100.4.13

### Server version

Current Purpur Version: 1.21.3-2336-34c18f0 (MC: 1.21.3)*
* You are running the latest version

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/xLhxmbYP
2. Your Towny config.yml: https://pastebin.com/ZH4SgesH
3. Your townyperms.yml: https://pastebin.com/vkKfYMrh
4. Your log's error: https://pastebin.com/jDvfXxUb

**Comment by LlmDl** [comment]
```
[14:34:33] [Server thread/INFO]: [Towny]   Economy: 
[14:34:33] [Server thread/INFO]: [Towny]   Warning: No compatible Economy plugins found. Install
                           Vault.jar or Reserve.jar with any of the supported eco
                           systems. If you do not want an economy to be used, set
                           using_economy: false in your Towny config.yml.
```

As far as I know Essentials has not added VaultUnlocked support.

Use iConomyUnlocked or TheNewEconomy, or another plugin that supports VaultUnlocked.
