### ISSUE TITLE
Suggestion: Publish main jar file in stable release (outside of the zip file)

### ISSUE THREAD

**Issue by HydrolienF** [TownyAdvanced/Towny#7686]
### **Please explain your feature request to the best of your abilities:**

I'm using `xyz.jpenilla.run-paper` to do test from a Gradle project & towny as a dependency. cf https://github.com/HydrolienF/FlagsH/blob/4.3.1/build.gradle.kts#L60
It work well with snapshot release as the release contains the jar file.
It doesn't work with main release because the jar file is incide a zip.

Is it possible to get the jar file outside of a zip file so that I can use it with run-paper?
I can send a pull request for the workflow if you agree.

**Comment by LlmDl** [comment]
I am currently only taking suggestions from sponsors, thank you.
