### ISSUE TITLE
TownyServerAccount.ACCOUNT" is null while checking for TownyUUID

### ISSUE THREAD

**Issue by lightPlugins** [TownyAdvanced/Towny#7706]
### What steps will reproduce the problem?

After setting up my fresh Economy Plugin and configuring Towny, I encountered the following error when running the command /town create TestTown.

This is the code where I get a null return:
```java
public UUID getTownyObjectUUID(String account) {
    return TownyEconomyHandler.getTownyObjectUUID(account);
}
```
Info: The Towny server account does not exist in my database after startup. This method is used to create the town account:
```java
public boolean isTownyUUID(UUID uuid) {
    // Towny's economy server account.
    if (uuid.equals(UUID.fromString("a73f39b0-1b7c-4930-b4a3-ce101812d926"))) {
        return true;
    }

    if (TownyUniverse.getInstance().hasTown(uuid)) {
        return true;
    }

    return TownyUniverse.getInstance().hasNation(uuid);
}
```

Here is my [VaultImplementer](https://github.com/lightPlugins/lightCoins/blob/master/src/main/java/io/lightstudios/coins/impl/vault/VaultImplementer.java) used in my economy plugin

### What is the expected output?

creating a town successfully

### Towny version

pre-Alpha **[0.101.0.3 for MC 1.19.* & 1.20.* & 1.21.*](https://github.com/TownyAdvanced/Towny/releases/tag/0.101.0.3)**

### Server version

 This server is running Paper version 1.21.4-15-master@bb76819 (2024-12-15T09:48:21Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files

1. Your full server startup + error from the logs\latest.log: https://mclo.gs/edSlMVJ
2. Your Towny config.yml: complete defaults
3. Your townyperms.yml: complete defaults

**Comment by LlmDl** [comment]
I would like to see your towny config please

**Comment by lightPlugins** [comment]
solved by using the "modern" UUID system provided by Towny itself
